### ISSUE TITLE
Correct MIME type and file extension for attached report file in emails

### ISSUE THREAD

**Issue by thomaszbz** [fail2ban/fail2ban#1003]
fail2ban is sometimes sending its report as a file attachment via email.

However, using mail clients such as Thunderbird on Gnu/Linux, the user is forced to store the file to disk an cannot open it directly.

The reason for that is a wrong MIME type:

    Subject: [Fail2Ban] somejail: banned XXX.XXX.XXX.XXX
    User-Agent: Heirloom mailx 12.5 6/20/10
    MIME-Version: 1.0
    Content-Type: application/octet-stream
    Content-Transfer-Encoding: quoted-printable

The reason for the wrong MIME type is either, that it's not explicitly set, or that the mail program cannot determine it because it has no file extension. In Thunderbird, there is no file name visible at all (user has to click on white space), and when opening, he or she is offered the server's name for the file name.

So I would suggest to give the file a name and the extension ".txt". Plus, the content type should be changed to "text/plain" (if not set automatically via server-side mail programm via file extension).

I'm using fail2ban 0.8.6 on up-to-date debian 7. I know this version is rather old. If the issue is already fixed in newer versions, then I would still appreciate a backport to the debian 7 packages.

**Comment by sebres** [comment]
How fail2ban sends emails is configured - it is full configurable as an action in /etc/fail2ban/action.d/*mail*.conf
Which one you use is configured in your `jail.conf` / `jail.local`.

For example <a href="https://github.com/fail2ban/fail2ban/blob/master/config/action.d/sendmail-whois.conf">/etc/fail2ban/action.d/sendmail-whois.conf</a> is configured.
This uses a sendmail (and sendmail default mime-type).

So if you will change it just add content-type in `actionban` before mail body...
previously:
```
...
From: <sendername> <<sender>>
To: <dest>\n
Hi,\n
The IP <ip> has just been banned by Fail2Ban after
...
```
hereafter:
```
...
MIME-Version: 1.0
Content-Type: text/plain;
From: <sendername> <<sender>>
To: <dest>\n
Hi,\n
The IP <ip> has just been banned by Fail2Ban after
...
```

If you really need an extention you can try something like header `Content-Disposition`.

**Comment by thomaszbz** [comment]
I see. I found out that the magic happens in heirloom mailx then:
http://stackoverflow.com/questions/10343106/linux-mail-file-log-has-content-type-application-octet-stream-a-noname-attac

I guess heirloom mailx is creating a binary attachment whenever characters can't be displayed. Until now, that happens just sometimes. And the reason for that seems to be the wois output. I found a swedish string in the whois output (which comes from such a binary attachment):

    Landåvägen

When I store the binary file to disk, then I get a

    file attachment.txt 
    attachment.txt: ISO-8859 text

which means the original output seems to be in ISO-8859 character set (heirloom mailx should not touch the character set, as it hopefully would pass through binary input).

So, to track it down: Possibly, I need UTF-8 in the whois output.

**Comment by sebres** [comment]
Just try to sendmail to you self (and if success add to you action/conf) a content-type with **charset=utf-8**, something like this:
```
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
```

**Comment by thomaszbz** [comment]
I already tracked it down to whois output itself:

    whois XXX.XXX.XXX.XXX > x
    file x
    x: ISO-8859 text

My debian has just UTF8-locales installed (via dpkg-reconfigure locales). I'm wondering why there is ISO-8859 output coming from whois. I don't like that at all.

I was already sending me some test mails with the original command which is used by fail2ban. And it's the whois characterset and heirloom mailx which causes the trouble

Just setting charset=utf-8 for non-utf-8 content seems not to be the best option. I'm still wondering why these crazy local character sets are used in 2015... especially in the most international tool called whois...

**Comment by sebres** [comment]
Strange, my whois returns `ASCII text` (is also a subset of UTF-8), check your LANG environment variable, should be something like :
```
echo $LANG
en_US.UTF-8
```
But in practice, some whois servers might use some other character set as ASCII.
> Just setting charset=utf-8 for non-utf-8 content seems not to be the best option

Well, not the best, but normally all modern mail clients by detecting of wrong single-byte character will either correct wrap it to utf-8 (using default single-byte encoding or auto-recognition) or wrap it to something like `?`.

**Comment by thomaszbz** [comment]
yes, it's

    echo $LANG
    en_US.UTF-8

on my system as well. I also tested on a ubuntu system with and get ISO-8859 from whois again.

**Comment by thomaszbz** [comment]
My file mail-whois-lines.local now contains

    actionban = printf %%b "Hi,\n
            The IP <ip> has just been banned by Fail2Ban after
            <failures> attempts against <name>.\n\n
            Here are more information about <ip>:\n
            `whois <ip>| { c=$(cat) ; cs=$(echo -ne "$c" | file -b --mime-encoding -) ; echo -ne "$c" | iconv -f $cs -t UTF-8//TRANSLIT - ; }`\n\n
            Lines containing IP:<ip> in <logpath>\n
            `grep '\<<ip>\>' <logpath>`\n\n
            Regards,\n
            Fail2Ban"|mail -s "[Fail2Ban] <name>: banned <ip>" <dest>

and it's working with several test cases. For these test cases I got correct character set in mails and there is no attachment any more.

**Comment by thomaszbz** [comment]
My solution could be applicable for other users as well. Especially when there is crappy output from WHOIS as the RFC 3912 states. Would you like to apply it to the standard configuration of fail2ban? What do you think?

**Comment by sebres** [comment]
Thanks for you contribution...

> Would you like to apply it to the standard configuration of fail2ban?

In any case, would be nice have it configurable (because for example `iconv` may be not exist, option not supported etc.)

so I think, it could be something like:
**in common include or in config defaults:**
```
whois_def = whois <ip> || echo missing whois program
whois_iconv = whois <ip> | { c=$(cat) ; cs=$(echo -ne "$c" | file -b --mime-encoding -) ; echo -ne "$c" | iconv -f $cs -t UTF-8//TRANSLIT - ; } || %(whois_def)s

whois = %(whois_iconv)s
```
**in \*mail\*.conf:**
```
actionban = ....
Here are more information about <ip>:\n
`%(whois)s`\n\n
Lines containing IP:<ip> in <logpath>\n
...
```

**Comment by thomaszbz** [comment]
Is there a cleaner way to pipe variable content to a program (I mean cleaner than using echo -ne $var). Best would be binary-safe.

What do you think about *detecting* existence of iconv and file commands?

How about passing well-defined UTF-8 to sendmail?

**Comment by sebres** [comment]
> Is there a cleaner way to pipe variable content to a program (I mean cleaner than using echo -ne $var)? 

`%(param)s` - is a standard substituation for in fail2ban config, will be evaluated (substituated) during loading of config once at start of f2b (not by executing of action).
`<ip>` - are another runtime f2b-variables, will be substituted by (before) executing of action.
If you mean shell variables, it can be used only inside one run (inside call of action). Don't know about `export var` but imho it's not safe enough.

> what do you think about detecting existence of iconv and file commands?

Too complex, make it simpe configurable.
But following expression ` || echo missing whois program` at end of action will say you "anithing is wrong in config".
> How about passing well-defined UTF-8 to sendmail?

It's imho default, but if we set header `content-type` (as described above) it will force to use UTF-8.

**Comment by thomaszbz** [comment]
ok, I'll let it run now a few days and then I should see if any problems occur. There's a bunch of "volonteers" willing to provide some test cases over the time, so I don't have to write them by myself ;)

**Comment by thomaszbz** [comment]
There's PR #1006 for this issue. However, it seems not to pass the CI tests.

User needs to activate the new behaviour so the commit should not change behaviour at all.  What's wrong?

**Comment by thomaszbz** [comment]
CI tests go green now.

**Comment by thomaszbz** [comment]
There's a nice way to avoid the echo's using bash and the <<< operator:

    whois ... | { WHOIS_OUTPUT=$(cat) ; cs=$(file -b --mime-encoding - <<< "$WHOIS_OUTPUT") ; iconv -f $cs -t UTF-8//TRANSLIT - <<< "$WHOIS_OUTPUT$"; }

However, this might not be POSIX compliant and also does not work when applied to my standard debian wheezy installation using the fail2ban config files. I would like to have some similar syntax which is POSIX compliant. Using dash, I get a

    /bin/dash: 2: Syntax error: redirection unexpected

for that.

I did some more investigation on the echo / echo -ne issue and found out that using echo is not a nice solution in terms of POSIX compatibility.

References: http://www.etalabs.net/sh_tricks.html

**Comment by thomaszbz** [comment]
now using printf which is the standard way how fail2ban is doing things. Should also be POSIX compliant that way.

**Comment by yarikoptic** [comment]
why don't you create a proper  pull request for the changes you are proposing?

**Comment by sebres** [comment]
@yarikoptic #1006 ?

**Comment by thomaszbz** [comment]
@yarikoptic You still need feedback?
