### ISSUE TITLE
Rules in firewallcmd-* filters don't survive firewalld reload/restart

### ISSUE THREAD

**Issue by mrc0mmand** [fail2ban/fail2ban#1005]
Rules for firewalld don't have `--permanent` option, so they won't survive firewalld reload (eg. via `--reload`) or restart (which happens after updates). This is really annoying, because, for example, in case of firewallcmd-ipset filter firewalld reload/restart (eg. after system update) deletes all references to ipset sets, but fail2ban will silently continue adding new banned IPs to them, even if it has no effect.

I came up with possible solution (at least for firewallcmd-ipset filter) which is to modify `firewallcmd-ipset.conf` Definition section from
```
[Definition]
actionstart = ipset create fail2ban-<name> hash:ip timeout <bantime>
              firewall-cmd --direct --add-rule ipv4 filter <chain> 0 -p <protocol> -m multiport --dports <port> -m set --match-set fail2ban-<name> src -j <blocktype>

actionstop = firewall-cmd --direct --remove-rule ipv4 filter <chain> 0 -p <protocol> -m multiport --dports <port> -m set --match-set fail2ban-<name> src -j <blocktype>
             ipset flush fail2ban-<name>
             ipset destroy fail2ban-<name>
```
to
```
[Definition]
actionstart = ipset create fail2ban-<name> hash:ip timeout <bantime>
              firewall-cmd --direct --add-rule ipv4 filter <chain> 0 -p <protocol> -m multiport --dports <port> -m set --match-set fail2ban-<name> src -j <blocktype>
              firewall-cmd --permanent  --direct --add-rule ipv4 filter <chain> 0 -p <protocol> -m multiport --dports <port> -m set --match-set fail2ban-<name> src -j <blocktype>

actionstop = firewall-cmd --direct --remove-rule ipv4 filter <chain> 0 -p <protocol> -m multiport --dports <port> -m set --match-set fail2ban-<name> src -j <blocktype>
             firewall-cmd --permanent --direct --remove-rule ipv4 filter <chain> 0 -p <protocol> -m multiport -dports <port> -m set --match-set fail2ban-<name> src -j <blocktype>
             ipset flush fail2ban-<name>
             ipset destroy fail2ban-<name>
```
where the second firewall-cmd call with the `--permanent` option will ensure that the rules persist through restarts/reloads. (The first call without `--permanent` has immediate effect, the second one works only after reload/restart).

Another possible solution would be to use only calls with `--permanent` and after fail2ban start/stop just use `firewall-cmd --reload` to load/unload all added rules.

I hope someone will come up with better solutions.

**Comment by Namsep** [comment]
It's also missing IPv6 support, though it will be a discussion what for prefix to ban by default. I would opt to block /56 ranges. Many providers distribute /56.

**Comment by mikecentola** [comment]
Good call on this. I've added it to mine as well.

**Comment by elyscape** [comment]
> I hope someone will come up with better solutions.

This is actually the recommended solution. From [the `firewall-cmd` man pages](http://linuxmanpages.net/manpages/fedora21/man1/firewall-cmd.1.html):

> If you want to make a change in runtime and permanent configuration, use the same call with and without the **--permanent** option.
