### ISSUE TITLE
How to handle courier "535 Authentication rejected"

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#1012]
*Authentication rejected* means the reqested type of login is **not advertised**, not listed in `ESMTPAUTH="PLAIN LOGIN"`.
Is it a reason for getting into the official fail2ban courier authentication filter?

**Comment by leeclemens** [comment]
A quick search doesn't show "Authentication rejected".

Are you referring to the line "535 Authentication failed" (last updated by yourself) in commit 
https://github.com/fail2ban/fail2ban/commit/d757ef584f7928086f439da5653031019eeb4110 ?

**Comment by szepeviktor** [comment]
Here it is: https://github.com/svarshavchik/courier/blob/ceb4d4231dc6ae3545802af3bd18c7cd1d30ce10/courier/courier/module.esmtp/courieresmtpd.c#L1313

**Comment by buanzo** [comment]
The error message Viktor refers too appears under very special
circumstances, normally associated with attack tools and with clients
during configuration testing, hence the confusion with 535 Authentication
failed.

**Comment by szepeviktor** [comment]
I take it as trying an auth. method that it not advertised.
Would you merge a PR?

**Comment by leeclemens** [comment]
Closing due to lack of response, feel free to submit a PR with your proposed changes and new log lines to match (and ChangeLog)...please reference DEVELOP.

**Comment by szepeviktor** [comment]
These are very rare. So I keep it in my `courier-smtp.local`. The followings are for Googlers.

```
^%(__prefix_line)serror,relay=<HOST>,msg="535 Authentication rejected",cmd: AUTH( \S+)?$
^%(__prefix_line)serror,relay=<HOST>,msg="502 ESMTP command error",cmd: (HOST: \S+|GET \S+ \S+|\.)$
^%(__prefix_line)serror,relay=<HOST>,msg="writev: Broken pipe",cmd: HOST: \S+$
```
The first one is the one mentioned above. The second one is HTTP (in fact garbage) on SMTP. It sounds strange but they are in my logs.
The last one is also HTTP, I think the connection breaks this time.
