### ISSUE TITLE
fail2ban 0.9.1 install on OSX Mavericks problems

### ISSUE THREAD

**Issue by brunobhr** [fail2ban/fail2ban#1017]
Hello,
I'm having a hard time getting Fail2ban to work on a OSX Mavericks 10.9.5 Client version.
I'm trying to install version 0.9.1
I followed this tutorial:
https://forgetcomputers.zendesk.com/hc/en-us/articles/201010250-Setting-up-Fail2ban-on-Mac-OS-X-10-7-
and tried also this altenative:
http://thefragens.com/2010/11/fail2ban-and-os-x-server-part-deux/

When I use the jail.local from thefragens.com with Packet Filter (pf), I got ERROR messages,
and when I use the regular 0.9.1, login attempts to sshd are not logged by fail2ban.log
but are logged by system.log

Any help would be greatly appreciated,
Bruno

**Comment by sebres** [comment]
> I got ERROR messages

That is very informative. Please provide little bit more an information: at least the errors you mean (excerpt from fail2ban.log file, console output by start (errors in output of `fail2ban-client start`), etc).

**Comment by brunobhr** [comment]
sebres,
Thank you for your respond.
Sorry for not being informative enough.
I'd like to run 0.9.1 as provided here.
I have this is jail.local:
[ssh-pf]

enabled = true
filter  = sshd
action  = pf
logpath = /var/log/system.log

When I do : sudo fail2ban-client start
I have:
2015-04-07 21:41:19,023 fail2ban.server         [98761]: INFO    Starting Fail2ban v0.9.1
2015-04-07 21:41:19,023 fail2ban.server         [98761]: INFO    Starting in daemon mode

And /var/log/fail2ban.log says:
2015-04-07 21:32:16,236 fail2ban.server         [98657]: INFO    Changed logging target to /var/log/fail2ban.log for Fail2ban v0.9.1
2015-04-07 21:32:16,239 fail2ban.database       [98657]: INFO    Connected to fail2ban persistent database '/var/lib/fail2ban/fail2ban.sqlite3'
2015-04-07 21:32:16,250 fail2ban.database       [98657]: WARNING New database created. Version '2'

When I try to ssh from another box, I get this output from /var/log/system.log:
07/04/15 21:41:50,648 sshd[98770]: error: PAM: unknown user for illegal user test from aputxxxxx.x.x.xxxxxxoo.fr via 192.168.1.14
07/04/15 21:41:50,659 sshd: unknown [pam][98774]: in od_record_create(): failed: 13
07/04/15 21:41:50,659 sshd: unknown [pam][98774]: in od_record_create_cstring(): failed: 13
07/04/15 21:41:51,830 sshd: unknown [pam][98774]: in od_record_create(): failed: 13
07/04/15 21:41:51,830 sshd: unknown [pam][98774]: in od_record_create_cstring(): failed: 13
07/04/15 21:41:51,830 sshd: unknown [pam][98774]: in pam_sm_authenticate(): OpenDirectory - Unable to get user record.

But then, fail2ban doesn't log any of my attempts, or does anything..

Thank you very mush for your help,
Bruno

**Comment by sebres** [comment]
Hm, strange... No more entries in /var/log/fail2ban.log? I see no ERROR messages, about which you spoke...

Normally default configured a maxretry = 3 and findtime is 10 minutes, so an IP should make 3 failures within 10 minutes to have ban for IP. But I think, f2b should at least log a failure found... 

Where is your `jail.local`? It should reside in the same directory as `jail.conf` (usually `/etc/fail2ban/`).

Can you dump the configuration with `fail2ban-client -d` and post it here. And also the output of `fail2ban-client status`.
Can you stop f2b and then start it with `fail2ban-client -v -v start` and post the output here...

**Comment by brunobhr** [comment]
sebres,
Thank you for taking the time.

ERROR messages appear when I try a different jail.conf,
that is supposed to be already configured for OSX.
I found this @ http://thefragens.com/2010/11/fail2ban-and-os-x-server-part-deux/
But it seemed to be a dead end, so I stopped trying this.

I'm now only trying to run the regular 0.9.1 packages I found on GitHub.

No, no more entries in /var/lof/fail2ban.log

I haven't change the standard settings:

# "bantime" is the number of seconds that a host is banned.
bantime  = 600

# A host is banned if it has generated "maxretry" during the last "findtime"
# seconds.
findtime  = 600

# "maxretry" is the number of failures before a host get banned.
maxretry = 3


Both jail.local and jail.conf reside in /etc/fail2ban


Here are the dumps you requested:
Tue Apr 07: 23:19:25 /usr/local/bin:sudo fail2ban-client -d
['set', 'logtarget', '/var/log/fail2ban.log']
['set', 'loglevel', 'INFO']
['set', 'dbpurgeage', 86400]
['set', 'dbfile', '/var/lib/fail2ban/fail2ban.sqlite3']

Tue Apr 07: 23:19:15 /usr/local/bin:sudo fail2ban-client status
Status
|- Number of jail:	0
`- Jail list:	

Tue Apr 07: 23:21:25 /usr/local/bin:sudo fail2ban-client -v -v start
INFO   Loading configs for fail2ban under /etc/fail2ban 
DEBUG  Reading configs for fail2ban under /etc/fail2ban 
DEBUG  Reading config files: /etc/fail2ban/fail2ban.conf
INFO     Loading files: ['/etc/fail2ban/fail2ban.conf']
INFO     Loading files: ['/etc/fail2ban/fail2ban.conf']
INFO   Using socket file /var/run/fail2ban/fail2ban.sock
INFO   Loading configs for jail under /etc/fail2ban 
DEBUG  Reading configs for jail under /etc/fail2ban 
DEBUG  Reading config files: /etc/fail2ban/jail.conf, /etc/fail2ban/jail.local
INFO     Loading files: ['/etc/fail2ban/jail.conf']
INFO     Loading files: ['/etc/fail2ban/jail.local']
INFO     Loading files: ['/etc/fail2ban/jail.conf', '/etc/fail2ban/jail.local']
INFO   [#         ] Waiting on the server...DEBUG  Starting '/usr/local/bin/fail2ban-server' with args ['fail2ban-server', '-s', '/var/run/fail2ban/fail2ban.sock', '-p', '/var/run/fail2ban/fail2ban.pid', '-b']
2015-04-07 23:21:29,824 fail2ban.server         [1738]: INFO    Starting Fail2ban v0.9.1
2015-04-07 23:21:29,824 fail2ban.server         [1738]: INFO    Starting in daemon mode
DEBUG  OK : 'pong'

DEBUG  OK : '/var/log/fail2ban.log'
DEBUG  OK : 'INFO'
DEBUG  OK : None
DEBUG  OK : '/var/lib/fail2ban/fail2ban.sqlite3'

Thanks again for your help.
Bruno

**Comment by sebres** [comment]
It says: you have **no jails** configured! So anything is wrong with jail.conf-jail.local. But very strange - without any error...
Are jail.conf and fail2ban.conf a stock versions (or customized from you)? What was configured in fail2ban.local?
As which user fail2ban runs? Has rights to read `/etc/fail2ban/...`? Has full rights for `/var/run/fail2ban/` and `/var/lib/fail2ban/`?
Which python version (output of `python --version`)? Should be at least 2.6.

Can you try the latest master from github and it conf's (I hope it returns more debug info by `... -v -v start`)?

**Comment by brunobhr** [comment]
sebres,
I made a few changes to jail.local / jail.conf:

# Fail2Ban jail specifications file
#
# Comments: use '#' for comment lines and ';' (following a space) for inline comments
#
# Changes:  in most of the cases you should not modify this
#           file, but provide customizations in jail.local file, e.g.:
#
# [DEFAULT]
# bantime = 3600
#
# [ssh-iptables]
# enabled = true
#

# The DEFAULT allows a global definition of the options. They can be overridden
# in each jail afterwards.

[DEFAULT]

# "ignoreip" can be an IP address, a CIDR mask or a DNS host. Fail2ban will not
# ban a host which matches an address in this list. Several addresses can be
# defined using space separator.
ignoreip = 127.0.0.1/8

# "bantime" is the number of seconds that a host is banned.
bantime  = 600

# A host is banned if it has generated "maxretry" during the last "findtime"
# seconds.
findtime  = 600

# "maxretry" is the number of failures before a host get banned.
maxretry = 3

# "backend" specifies the backend used to get files modification.
# Available options are "pyinotify", "gamin", "polling" and "auto".
# This option can be overridden in each jail as well.
#
# pyinotify: requires pyinotify (a file alteration monitor) to be installed.
#              If pyinotify is not installed, Fail2ban will use auto.
# gamin:     requires Gamin (a file alteration monitor) to be installed.
#              If Gamin is not installed, Fail2ban will use auto.
# polling:   uses a polling algorithm which does not require external libraries.
# auto:      will try to use the following backends, in order:
#              pyinotify, gamin, polling.
backend = auto

# "usedns" specifies if jails should trust hostnames in logs,
#   warn when DNS lookups are performed, or ignore all hostnames in logs
#
# yes:   if a hostname is encountered, a DNS lookup will be performed.
# warn:  if a hostname is encountered, a DNS lookup will be performed,
#        but it will be logged as a warning.
# no:    if a hostname is encountered, will not be used for banning,
#        but it will be logged as info.
usedns = warn


# This jail corresponds to the standard configuration in Fail2ban 0.6.
# The mail-whois action send a notification e-mail with a whois request
# in the body.

[ssh-iptables]

enabled  = false
filter   = sshd
action   = iptables[name=SSH, port=ssh, protocol=tcp]
           sendmail-whois[name=SSH, dest=you@example.com, sender=fail2ban@example.com]
logpath  = /var/log/sshd.log
maxretry = 5

[proftpd-iptables]

enabled  = false
filter   = proftpd
action   = iptables[name=ProFTPD, port=ftp, protocol=tcp]
           sendmail-whois[name=ProFTPD, dest=you@example.com]
logpath  = /var/log/proftpd/proftpd.log
maxretry = 6

# This jail forces the backend to "polling".

[sasl-iptables]

enabled  = false
filter   = sasl
backend  = polling
action   = iptables[name=sasl, port=smtp, protocol=tcp]
           sendmail-whois[name=sasl, dest=you@example.com]
logpath  = /var/log/mail.log

# ASSP SMTP Proxy Jail
[assp]
enabled  = false
filter   = assp
action = iptables-multiport[name=assp,port="25,465,587"]
logpath  = /root/path/to/assp/logs/maillog.txt

# Here we use TCP-Wrappers instead of Netfilter/Iptables. "ignoreregex" is
# used to avoid banning the user "myuser".

[ssh-tcpwrapper]

enabled     = false
filter      = sshd
action      = hostsdeny
              sendmail-whois[name=SSH, dest=you@example.com]
ignoreregex = for myuser from
logpath     = /var/log/sshd.log

# Here we use blackhole routes for not requiring any additional kernel support
# to store large volumes of banned IPs

[ssh-route]

enabled = false
filter = sshd
action = route
logpath = /var/log/sshd.log
maxretry = 5

# Here we use a combination of Netfilter/Iptables and IPsets
# for storing large volumes of banned IPs
#
# IPset comes in two versions. See ipset -V for which one to use
# requires the ipset package and kernel support.
[ssh-iptables-ipset4]

enabled  = false
filter   = sshd
action   = iptables-ipset-proto4[name=SSH, port=ssh, protocol=tcp]
logpath  = /var/log/sshd.log
maxretry = 5

[ssh-iptables-ipset6]
enabled  = false
filter   = sshd
action   = iptables-ipset-proto6[name=SSH, port=ssh, protocol=tcp, bantime=600]
logpath  = /var/log/sshd.log
maxretry = 5

# bsd-ipfw is ipfw used by BSD. It uses ipfw tables.
# table number must be unique.
# 
# This will create a deny rule for that table ONLY if a rule 
# for the table doesn't ready exist.
#
[ssh-bsd-ipfw]
enabled  = false
filter   = sshd
action   = bsd-ipfw[port=ssh,table=1]
logpath  = /var/log/auth.log
maxretry = 5

# This jail demonstrates the use of wildcards in "logpath".
# Moreover, it is possible to give other files on a new line.

[apache-tcpwrapper]

enabled  = false
filter	 = apache-auth
action   = hostsdeny
logpath  = /var/log/apache*/*error.log
           /home/www/myhomepage/error.log
maxretry = 6

# The hosts.deny path can be defined with the "file" argument if it is
# not in /etc.

[postfix-tcpwrapper]

enabled  = false
filter   = postfix
action   = hostsdeny[file=/not/a/standard/path/hosts.deny]
           sendmail[name=Postfix, dest=you@example.com]
logpath  = /var/log/postfix.log
bantime  = 300

# Do not ban anybody. Just report information about the remote host.
# A notification is sent at most every 600 seconds (bantime).

[vsftpd-notification]

enabled  = false
filter   = vsftpd
action   = sendmail-whois[name=VSFTPD, dest=you@example.com]
logpath  = /var/log/vsftpd.log
maxretry = 5
bantime  = 1800

# Same as above but with banning the IP address.

[vsftpd-iptables]

enabled  = false
filter   = vsftpd
action   = iptables[name=VSFTPD, port=ftp, protocol=tcp]
           sendmail-whois[name=VSFTPD, dest=you@example.com]
logpath  = /var/log/vsftpd.log
maxretry = 5
bantime  = 1800

# Ban hosts which agent identifies spammer robots crawling the web
# for email addresses. The mail outputs are buffered.

[apache-badbots]

enabled  = false
filter   = apache-badbots
action   = iptables-multiport[name=BadBots, port="http,https"]
           sendmail-buffered[name=BadBots, lines=5, dest=you@example.com]
logpath  = /var/www/*/logs/access_log
bantime  = 172800
maxretry = 1

# Use shorewall instead of iptables.

[apache-shorewall]

enabled  = false
filter   = apache-noscript
action   = shorewall
           sendmail[name=Postfix, dest=you@example.com]
logpath  = /var/log/apache2/error_log

# Monitor roundcube server

[roundcube-iptables]

enabled  = false
filter   = roundcube-auth
action   = iptables[name=RoundCube, port="http,https"]
logpath  = /var/log/roundcube/userlogins


# Monitor SOGo groupware server

[sogo-iptables]

enabled  = false
filter   = sogo-auth
# without proxy this would be:
# port    = 20000
action   = iptables[name=SOGo, port="http,https"]
logpath  = /var/log/sogo/sogo.log

# Ban attackers that try to use PHP's URL-fopen() functionality
# through GET/POST variables. - Experimental, with more than a year
# of usage in production environments.

[php-url-fopen]

enabled = false
action  = iptables[name=php-url-open, port="http,https"]
filter  = php-url-fopen
logpath = /var/www/*/logs/access_log
maxretry = 1

# A simple PHP-fastcgi jail which works with lighttpd.
# If you run a lighttpd server, then you probably will
# find these kinds of messages in your error_log:
# ALERT – tried to register forbidden variable ‘GLOBALS’
# through GET variables (attacker '1.2.3.4', file '/var/www/default/htdocs/index.php')
# This jail would block the IP 1.2.3.4.

[lighttpd-fastcgi]

enabled = false
filter  = lighttpd-fastcgi
action  = iptables[name=lighttpd-fastcgi, port="http,https"]
# adapt the following two items as needed
logpath = /var/log/lighttpd/error.log
maxretry = 2

# Same as above for mod_auth
# It catches wrong authentications

[lighttpd-auth]

enabled = false
filter  = lighttpd-auth
action  = iptables[name=lighttpd-auth, port="http,https"]
# adapt the following two items as needed
logpath = /var/log/lighttpd/error.log
maxretry = 2

# This jail uses ipfw, the standard firewall on FreeBSD. The "ignoreip"
# option is overridden in this jail. Moreover, the action "mail-whois" defines
# the variable "name" which contains a comma using "". The characters '' are
# valid too.

# [ssh-pf]

# enabled	= true
# filter	= sshd
# action	= pf
# logpath	= /var/log/system.log


# These jails block attacks against named (bind9). By default, logging is off
# with bind9 installation. You will need something like this:
#
# logging {
#     channel security_file {
#         file "/var/log/named/security.log" versions 3 size 30m;
#         severity dynamic;
#         print-time yes;
#     };
#     category security {
#         security_file;
#     };
# };
#
# in your named.conf to provide proper logging.
# This jail blocks UDP traffic for DNS requests.

# !!! WARNING !!!
#   Since UDP is connection-less protocol, spoofing of IP and imitation
#   of illegal actions is way too simple.  Thus enabling of this filter
#   might provide an easy way for implementing a DoS against a chosen
#   victim. See
#    http://nion.modprobe.de/blog/archives/690-fail2ban-+-dns-fail.html
#   Please DO NOT USE this jail unless you know what you are doing.
#
# [named-refused-udp]
#
# enabled  = false
# filter   = named-refused
# action   = iptables-multiport[name=Named, port="domain,953", protocol=udp]
#            sendmail-whois[name=Named, dest=you@example.com]
# logpath  = /var/log/named/security.log
# ignoreip = 168.192.0.1

# This jail blocks TCP traffic for DNS requests.

[named-refused-tcp]

enabled  = false
filter   = named-refused
action   = iptables-multiport[name=Named, port="domain,953", protocol=tcp]
           sendmail-whois[name=Named, dest=you@example.com]
logpath  = /var/log/named/security.log
ignoreip = 168.192.0.1

# Multiple jails, 1 per protocol, are necessary ATM:
# see https://github.com/fail2ban/fail2ban/issues/37
[asterisk-tcp]

enabled  = false
filter   = asterisk
action   = iptables-multiport[name=asterisk-tcp, port="5060,5061", protocol=tcp]
           sendmail-whois[name=Asterisk, dest=you@example.com, sender=fail2ban@example.com]
logpath  = /var/log/asterisk/messages
maxretry = 10

[asterisk-udp]

enabled  = false
filter	 = asterisk
action   = iptables-multiport[name=asterisk-udp, port="5060,5061", protocol=udp]
           sendmail-whois[name=Asterisk, dest=you@example.com, sender=fail2ban@example.com]
logpath  = /var/log/asterisk/messages
maxretry = 10

# To log wrong MySQL access attempts add to /etc/my.cnf:
# log-error=/var/log/mysqld.log
# log-warning = 2
[mysqld-iptables]

enabled  = false
filter   = mysqld-auth
action   = iptables[name=mysql, port=3306, protocol=tcp]
           sendmail-whois[name=MySQL, dest=root, sender=fail2ban@example.com]
logpath  = /var/log/mysqld.log
maxretry = 5


# Jail for more extended banning of persistent abusers
# !!! WARNING !!!
#   Make sure that your loglevel specified in fail2ban.conf/.local
#   is not at DEBUG level -- which might then cause fail2ban to fall into
#   an infinite loop constantly feeding itself with non-informative lines
[recidive]

enabled  = false
filter   = recidive
logpath  = /var/log/fail2ban.log
action   = iptables-allports[name=recidive]
           sendmail-whois-lines[name=recidive, logpath=/var/log/fail2ban.log]
bantime  = 604800  ; 1 week
findtime = 86400   ; 1 day
maxretry = 5

# PF is a BSD based firewall
[ssh-pf]

enabled = true
filter = sshd
action = pf
logpath  = /var/log/sshd.log
maxretry=5

Now when I run fail2ban as root I have:
Wed Apr 08: 16:07:16 /etc/fail2ban/filter.d:sudo fail2ban-client start
Password:
ERROR  No file(s) found for glob /var/log/sshd.log
ERROR  Failed during configuration: Have not found any log file for ssh-pf jail

This is the regular 0.9.1 install, just with the [ssh-pf] modified as:
[ssh-pf]

enabled = true
filter = sshd
action = pf
logpath = /var/log/system.log


Any ideas maybe?
Thanks again very much for your help,
Bruno

**Comment by sebres** [comment]
very strange is before changing `logpath = /var/log/sshd.log` you had still an error within jailreader (client) for jail `ssh-pf`. But after changing I see not where the client sends it to server.
Even dumping of configuration `sudo fail2ban-client -d` does not output this or any jail at all. It should be something like this:
```
['set', 'logtarget', '/var/log/fail2ban.log']
['set', 'loglevel', 'INFO']
['set', 'dbpurgeage', 86400]
['set', 'dbfile', '/var/run/fail2ban.sqlite3']
...
['add', 'ssh-pf', '...']
['set', 'ssh-pf', 'addlogpath', './tests/files/testcase01.log', 'head']
['set', 'ssh-pf', 'addlogpath', './tests/files/testcase02.log', 'head']
['set', 'ssh-pf', 'maxretry', 5]
['set', 'ssh-pf', 'addignoreip', '127.0.0.1/8']
['set', 'ssh-pf', 'logencoding', 'auto']
['set', 'ssh-pf', 'bantime', 600]
['set', 'ssh-pf', 'ignorecommand', '']
['set', 'ssh-pf', 'findtime', 600]
['set', 'ssh-pf', 'addfailregex', '...']
['set', 'ssh-pf', 'addaction', '...']
...
['start', 'ssh-pf']
```
I'm with my latin at end :)
Please send me packed your whole configuration `/etc/fail2ban`.

**Comment by leeclemens** [comment]
Closing as many months have gone by without further info, and may be better suited for the mailing list anyway. More recent "Issue" indicates the "no jails configured" situation has been overcome.
