### ISSUE TITLE
Fail2ban do not detect changes in log file in NFS directory?

### ISSUE THREAD

**Issue by simpleuser99** [fail2ban/fail2ban#1019]
Hello everybody!
I mounted NFS directory by my server. I installed fail2ban by my server and i switch logtarget on nfs.
But fail2ban do not work. If i use fail2ban-regex /path/to/nfs/logfile /etc/fail2ban/filter.d/myfilter i have a true resault. Why fail2ban do not detect changes in log file in NFS directory?

**Comment by yarikoptic** [comment]
On Wed, 08 Apr 2015, simpleuser99 wrote:

>    Hello everybody!
>    I mounted NFS directory by my server. I installed fail2ban by my server
>    and i switch logtarget on nfs.
>    But fail2ban do not work. If i use fail2ban-regex /path/to/nfs/logfile
>    /etc/fail2ban/filter.d/myfilter i have a true resault. Why fail2ban do not
>    detect changes in log file in NFS directory?

http://www.fail2ban.org/wiki/index.php/HOWTO_Seek_Help

could be that inotify is not effective, or smth else -- we would need more information

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by simpleuser99** [comment]
Sorry for the little infornation.
Additional information:
Fail2Ban v0.8.14
CentOS release 6.6 (Final)# fail2ban filter configuration for nginx
I install fail2ban through a yum from epel

my custom filter:
[Definition]
failregex = limiting requests.*client: <HOST>
ignoreregex =

also i add to end of jail.conf my new jail:
[nginx-limit-req]

enabled = true
filter = nginx-limit-req
action  = iptables-multiport[name=nginx-limit-req,port="80,443"]
logpath = /path/to/nfs/mylogfile
maxretry = 3

Other settings for fail2ban are default.

My file2ban log (log level 4) https://drive.google.com/open?id=0BzKa_21K6cbTWVpDcF9BS3VDVDQ&authuser=0

Also i mount nfs with readonly option.

I try to use inotifywait -rm /path/to/nfs/ and i has not received result. inotifywait do not detect nfs log modifying.

**Comment by yarikoptic** [comment]
On Wed, 08 Apr 2015, simpleuser99 wrote:

>    I try to use inotifywait -rm /path/to/nfs/ and i has not received result.
>    inotifywait do not detect nfs log modifying.

interesting...
just try with backend = polling within section [DEFAULT] in jail.local overriding settings of
jail.conf

**Comment by simpleuser99** [comment]
Great! It is work!
Thank you for help me with my trouble.

**Comment by yarikoptic** [comment]
with  that I  will close it since I don't think there is any thing we could do really
