### ISSUE TITLE
Log-file is not parsed upon startup

### ISSUE THREAD

**Issue by weberhofer** [fail2ban/fail2ban#1020]
I'm using fail2ban 0.8.14 on Linux and I'm trying to block some spammers permanently via fail2ban. Therefore I have created a simple filter very similar to the one described at https://gist.github.com/sergejmueller/8171854. My 'log'-file has this format:

[2015-04-15:12:00:00] 192.168.0.1 # SOME NOTES

The problem I'm having is that upon start-up the entries are not processed - this is exactly the same problem that some users on the above mentioned reference are referring to.

I have recognized, that as soon as I add a single line to the 'log'-file (repeating the last one I have in the file) makes fail2ban processing all the lines and banning the previous entries, too.

Any ideas?

**Comment by leeclemens** [comment]
That log line doesn't look like the ones in the gist (they have IP first, then date). What if you run fail2ban-regex against the log file, does it match? Keep in mind the findtime factors in (fail2ban will ignore log lines that are too old).

**Comment by weberhofer** [comment]
I have other rules than in gist. Checking the regex says:

Failregex: 11 total
|-  #) [# of hits] regular expression
|   1) [11] ^[^ ]* <HOST> .*
|      192.168.0.1  Wed Apr 15 13:00:00 2015
...
Lines: 11 lines, 0 ignored, 11 matched, 0 missed

Therefore I think there must something else be wrong, like the people commenting the gist example says.

**Comment by leeclemens** [comment]
Can you provide your configuration (since it is apparently not the same as the gist you reference)? Log files during startup? fail2ban-client status for the jail?

**Comment by sebres** [comment]
Dump your configuration with `fail2ban-client -d` and check:
- jail presents (and enabled);
- jail uses your filter resp. regex;
- `addlogpath` for log that jail observes is expected log file;
- IP not in `addignoreip`;
- to be banned, each IP should make `maxretry` failures (attempts) during of `findtime`;
- an action was specified for the jail;

**Comment by weberhofer** [comment]
I have retried with version 0.9.2 and still have the same behaviour; I'm now using the same sources as described in https://gist.github.com/sergejmueller/8171854 , except that I have adapted the jail to work with 0.9.2 (see https://gist.github.com/sergejmueller/8171854#comment-1461279).
Still nothing gets banned until I open vi and write the same file. This makes fail2ban to parse all the lines and to do ban the IP-addresses.

**Comment by sebres** [comment]
I think, I understand your problem. The last log-file position will be saved into sqlite db, so long check sum of first line not modified, f2b will not read again already "processed" lines. 

In your case, you should change a first line of your "log-file", before start f2b, to process all "failures" again. I want check this as FR-option to jail-related disable this behavior.

But now, better would be to make a simple persistent jail, observes empty log, and add to this jail your IP via `fail2ban-client set <JAIL> banip <IP>`. All this IPs should be restored after restart if bantime was not yet reached (or persistent).

But I believe I have fixed a little bug (inside #716) as regards to restart / restoring banned IPs (I will look at my source code, to verify that).

**Comment by sebres** [comment]
So except a problem with already "treated" rows, indeed exists another one: by restart during "restoring" already banned IPs, f2b checks it bantime and will ban only up to this ban-end-time. (But if I interpret the source code correctly, this logic is also a little bit broken). Additionally, If it will read all entries from your "persistent" "log-file", it will say "already banned" for all IPs, already restored from DB. It will not prolong its bantime at all, because this logic not available in master branch (it was first implemented in #716). 

I want see what we can do in your case.

**Comment by weberhofer** [comment]
Thank you for deeply analyzing the problem; the problem seem to be very specific for this special case; so maybe this static banning could be implemented in another way. In the jail.conf there is the setting "ignoreip". A setting like "banip" could be implemented to statically ban ip addresses (or networks). The special jail to ban ip-addresses would then be irrelevant.

**Comment by sebres** [comment]
The setting like "banip" seems to be on the one hand to uncomfortable, on the another it can be realized directly in firewall (iptables, etc.) with the same effort (so the question would be then - why over fail2ban).

**Comment by weberhofer** [comment]
You're right, changing the configs is not fail2ban's concept to ban addresses and a bit uncomfortable.
