### ISSUE TITLE
How to match an IP not a HOST?

### ISSUE THREAD

**Issue by pmalek** [fail2ban/fail2ban#1021]
I would like to filter out this type of ssh break in attempts:

```
Mar 13 16:32:37 ubuntu sshd[29811]: reverse mapping checking getaddrinfo for 226.xxx.xxx.61
226.xxx.xxx.61.djdj.xxx.zj.dynamic.XXX.com.cn [61.xxx.xxx.226] failed - POSSIBLE BREAK-IN ATTEMPT!
```

I know I can try to match it with the following line in 

```
^%(__prefix_line)sreverse mapping checking getaddrinfo for <HOST> \[.*?\] failed - POSSIBLE BREAK-IN ATTEMPT.\s*$
```

```
^%(__prefix_line)sreverse mapping checking getaddrinfo for <.*?> \[<HOST>\] failed - POSSIBLE BREAK-IN ATTEMPT.\s*$
```

but how I explicitly filter it out by IP of this client trying to connect?

**Comment by leeclemens** [comment]
"<HOST>" is replaced in the regex to match an IP (or hostname iirc). All tags with <> get replaced, so I think "<.*?>" may be giving you problems.

Side note: This message isn't necessarily a failed login attempt, so you'll probably be better off just using the sshd filter.
