### ISSUE TITLE
Ignoreregex hit but host still going to ban

### ISSUE THREAD

**Issue by GlebTyazhyolov** [fail2ban/fail2ban#1023]
Hello,

The fail2ban version is 0.9.1

I try to configure exclusions for exim maillog filter. I added ignoreregex lines to EXIM.LOCAL filter and tested it with fail2ban-regex. It hits successfully on all lines that contains excluded host. But ignored host still going to ban. Of cource i restarted fail2ban after config change.

Below in more details on example of forward2o.mail.yandex.net host that i used in my debug attempts.

The JAIL.LOCAL part of config relates to EXIM:
[exim]
enabled = true
filter = exim
action = bsd-ipfw[table=10,port=25]
port   = smtp
logpath = /var/log/exim/mainlog
#1h
bantime = 3600
#30m
findtime = 1800

Filters in EXIM.LOCAL defined as
failregex = ^%(pid)s %(host_info)sF=(<>|[^@]+@\S+) rejected RCPT [^@]+@\S+: (User unknown)\s*$

Ignoreregex = outbound-mail\.sendgrid\.net
                \.yandex\.net
                (and so, and so)

Did test it with fail2ban-regex on filtered by hostname part of exim maillog that contains records like
2015-04-16 08:51:35 [20062] H=forward2o.mail.yandex.net [37.140.190.31]:43684 I=[10.50.1.110]:25 F=<kera82@yandex.ru> rejected RCPT <dcnsxci@mvk.ru>: User unknown

 fail2ban-regex ~/test-yandex.log /usr/local/etc/fail2ban/filter.d/exim.local /usr/local/etc/fail2ban/filter.d/exim.local

Results
=======

Failregex: 0 total

Ignoreregex: 231 total
|-  #) [# of hits] regular expression
|   8) [231] .yandex.net
`-

But host forward2o.mail.yandex.net still banned:

2015-04-16 09:49:37,946 fail2ban.actions        [31386]: NOTICE  [exim] Ban 37.140.190.31
 
# ipfw table 10 list | awk -F"/" '{print $1}' | xargs -L 1 host
<...>
31.190.140.37.in-addr.arpa domain name pointer forward2o.mail.yandex.net.
<...>

Just in case to make sure that banned IP always appears in log with it's "ignoreregexed" hostname:
cat /var/log/exim/mainlog | grep 37.140.190.31 | grep -v "yandex.net" > ~/test-yandex2.log
fail2ban-regex ~/test-yandex2.log /usr/local/etc/fail2ban/filter.d/exim.local /usr/local/etc/fail2ban/filter.d/exim.local
Running tests
=============

Use   failregex file : /usr/local/etc/fail2ban/filter.d/exim.local
Use ignoreregex file : /usr/local/etc/fail2ban/filter.d/exim.local
Use         log file : /root/test-yandex2.log
Use         encoding : US-ASCII

Results
=======

Failregex: 0 total

Ignoreregex: 0 total

I would be gratefull for any ideas.

**Comment by leeclemens** [comment]
Please use the mailing list for general help, see http://www.fail2ban.org/wiki/index.php/HOWTO_Seek_Help for more info.

Also, a config setting of "(and so, and so)" isn't useful for other people to read and subsequently help you.
