### ISSUE TITLE
http request not accepted by the apache after installation of fan2ban

### ISSUE THREAD

**Issue by infoebt** [fail2ban/fail2ban#1025]
I was able to install fan2ban successfully and have it run as a service.   After I restart my server (ec2),  my apache server, which started up successfully, cannot see any incoming http request  (access_log, error_log). 

1) I redo the setup three times (from an image without fan2ban) the same setup and my apache server stop receiving http request right after the "successfully" restart of the server instance.  
2) On the client browser, it show "cannot connect to server".
3) i don't see any ban on the iptables
4) my current setup include apache 2.4, centos7.0
5) My current setup is behind cloudflare with a cloudflare module installed so that the original ip can be reflected in the access log.  
6) no errors in the fail2ban logs.

I have done extensive search on this case but couldn't find anything similar on the web.  Would appreciate if someone can shed some lights on this.

**Comment by justabaka** [comment]
Sounds like a network/cloudflare module configuration issue, fail2ban does not block anything by default. Try disabling the cloudflare module and accessing the server directly. If it works, proceed with the module configuration.

Also check if your ec2 instance has a persistent IP address set up.
