### ISSUE TITLE
banaction = route gives action start and stop errors. 

### ISSUE THREAD

**Issue by utags** [fail2ban/fail2ban#1026]
When I added "banaction = route" to the "jail.local" it gives following errors. But if I use "banaction = iptables-multiport" there's no such a issue. So should I modify my route.conf file in order to fix this issue? I use default route.conf file which can find in here. https://github.com/fail2ban/fail2ban/blob/master/config/action.d/route.conf.

WARNING 'actionstart' not defined in 'Definition'. Using default one: ''
WARNING 'actionstop' not defined in 'Definition'. Using default one: ''
WARNING 'actioncheck' not defined in 'Definition'. Using default one: ''
WARNING 'actionstart' not defined in 'Definition'. Using default one: ''
WARNING 'actionstop' not defined in 'Definition'. Using default one: ''
WARNING 'actioncheck' not defined in 'Definition'. Using default one: ''
WARNING 'actionstart' not defined in 'Definition'. Using default one: ''
WARNING 'actionstop' not defined in 'Definition'. Using default one: ''
WARNING 'actioncheck' not defined in 'Definition'. Using default one: ''
WARNING 'actioncheck' not defined in 'Definition'. Using default one: ''
WARNING 'actioncheck' not defined in 'Definition'. Using default one: ''
WARNING 'actionstart' not defined in 'Definition'. Using default one: ''
WARNING 'actionstop' not defined in 'Definition'. Using default one: ''
WARNING 'actioncheck' not defined in 'Definition'. Using default one: ''
WARNING 'actionstart' not defined in 'Definition'. Using default one: ''
WARNING 'actionstop' not defined in 'Definition'. Using default one: ''
WARNING 'actioncheck' not defined in 'Definition'. Using default one: ''
WARNING 'actionstart' not defined in 'Definition'. Using default one: ''
WARNING 'actionstop' not defined in 'Definition'. Using default one: ''
WARNING 'actioncheck' not defined in 'Definition'. Using default one: ''
WARNING 'actionstart' not defined in 'Definition'. Using default one: ''
WARNING 'actionstop' not defined in 'Definition'. Using default one: ''
WARNING 'actioncheck' not defined in 'Definition'. Using default one: ''
WARNING 'ignoreregex' not defined in 'Definition'. Using default one: ''
WARNING 'actionstart' not defined in 'Definition'. Using default one: ''
WARNING 'actionstop' not defined in 'Definition'. Using default one: ''
WARNING 'actioncheck' not defined in 'Definition'. Using default one: ''
WARNING 'actionstart' not defined in 'Definition'. Using default one: ''
WARNING 'actionstop' not defined in 'Definition'. Using default one: ''
WARNING 'actioncheck' not defined in 'Definition'. Using default one: ''
WARNING 'actionstart' not defined in 'Definition'. Using default one: ''
WARNING 'actionstop' not defined in 'Definition'. Using default one: ''
WARNING 'actioncheck' not defined in 'Definition'. Using default one: ''
WARNING 'actionstart' not defined in 'Definition'. Using default one: ''
WARNING 'actionstop' not defined in 'Definition'. Using default one: ''
WARNING 'actioncheck' not defined in 'Definition'. Using default one: ''
WARNING 'actionstart' not defined in 'Definition'. Using default one: ''
WARNING 'actionstop' not defined in 'Definition'. Using default one: ''
WARNING 'actioncheck' not defined in 'Definition'. Using default one: ''
WARNING 'actionstart' not defined in 'Definition'. Using default one: ''
WARNING 'actionstop' not defined in 'Definition'. Using default one: ''
WARNING 'actioncheck' not defined in 'Definition'. Using default one: ''
WARNING 'actionstart' not defined in 'Definition'. Using default one: ''
WARNING 'actionstop' not defined in 'Definition'. Using default one: ''
WARNING 'actioncheck' not defined in 'Definition'. Using default one: ''
WARNING 'actionstart' not defined in 'Definition'. Using default one: ''
WARNING 'actionstop' not defined in 'Definition'. Using default one: ''
WARNING 'actioncheck' not defined in 'Definition'. Using default one: ''

**Comment by mrc0mmand** [comment]
These are not errors, just warnings - you can safely ignore them. Action `route` defines only actions 'actionban' and 'actionunban'. Other actions are unnecessary, so route.conf doesn't define them. In this case, fail2ban will generate empty actions for the missing ones, which is followed by warnings you mentioned.

**Comment by sebres** [comment]
@mrc0mmand agree, but I think it would be better to set all three to empty in `route.conf`, to prevent this warning.

**Comment by mrc0mmand** [comment]
@sebres good point, that would be wise.

**Comment by agentmoller001** [comment]
This can be fixed easily by adding ...

actioncheck =
actionstart =
actionstop =

... to the route.conf under [Definition].

nano /etc/fail2ban/action.d/route.conf

    # Fail2Ban configuration file
    #
    # Author: Michael Gebetsroither
    #
    # This is for blocking whole hosts through blackhole routes.
    #
    # PRO:
    #   - Works on all kernel versions and as no compatibility problems (back to debian lenny and WAY further).
    #   - It's FAST for very large numbers of blocked ips.
    #   - It's FAST because it Blocks traffic before it enters common iptables chains used for filtering.
    #   - It's per host, ideal as action against ssh password bruteforcing to block further attack attempts.
    #   - No additional software required beside iproute/iproute2
    #
    # CON:
    #   - Blocking is per IP and NOT per service, but ideal as action against ssh password bruteforcing hosts

    [Definition]
    actionban   = ip route add <blocktype> <ip>
    actionunban = ip route del <blocktype> <ip>
    actioncheck =
    actionstart =
    actionstop =

    [Init]

    # Option:  blocktype
    # Note:    Type can be blackhole, unreachable and prohibit. Unreachable and prohibit correspond to the ICMP reject messages.
    # Values:  STRING
    blocktype = unreachable
