### ISSUE TITLE
dovecot filter not ban hacker attemps

### ISSUE THREAD

**Issue by dzint** [fail2ban/fail2ban#1028]
Fail2ban v0.9.1.dev

this is my log /var/log/mail.log

> Apr 22 13:22:17 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<dmartinez>, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=<Jp8wX04UKgAly9Xo>

i use dovecot.conf filter but not work, not ban :(

Debian Wheezy

**Comment by mrc0mmand** [comment]
Problem here is in missing '<>' in 'user' field. According to one of dovecot's fail regexes, if field 'user' is defined, it must contain at least '<>' characters:

`
^%(__prefix_line)s(pop3|imap)-login: (Info: )?(Aborted login|Disconnected)(: Inactivity)? \(((auth failed, \d+ attempts)( in \d+ secs)?|tried to use (disabled|disallowed) \S+ auth)\):( user=<\S*>,)?( method=\S+,)? rip=<HOST>(, lip=(\d{1,3}\.){3}\d{1,3})?(, TLS( handshaking(: SSL_accept\(\) failed: error:[\dA-F]+:SSL routines:[TLS\d]+_GET_CLIENT_HELLO:unknown protocol)?)?(: Disconnected)?)?(, session=<\S+>)?\s*$
`

The part I mentioned above is `( user=<\S*>,)?`

If you'd like to fix it, you can change `( user=<\S*>,)?` part to something like `( user=(<\S*>)?,)?`

**Comment by dzint** [comment]
thank you for answer @mrc0mmand i proced to this changement 

> [INCLUDES]

before = common.conf

[Definition]

_daemon = (auth|dovecot(-auth)?|auth-worker)

failregex = ^%(__prefix_line)s(%(__pam_auth)s(\(dovecot:auth\))?:)?\s+authentication failure; logname=\S* uid=\S* euid=\S* tty=dovecot ruser=\S* rhost=<HOST>(\s+user=\S*)?\s*$
            ^%(__prefix_line)s(pop3|imap)-login: (Info: )?(Aborted login|Disconnected)(: Inactivity)? \(((auth failed, \d+ attempts)( in \d+ secs)?|tried to use (disabled|disallowed) \S+ auth)\):( user=(<\S*>)?,)?( method=\S+,)? rip=<HOST>(, lip=(\d{1,3}\.){3}\d{1,3})?(, TLS( handshaking(: SSL_accept\(\) failed: error:[\dA-F]+:SSL routines:[TLS\d]+_GET_CLIENT_HELLO:unknown protocol)?)?(: Disconnected)?)?(, session=<\S+>)?\s*$
            ^%(__prefix_line)s(Info|dovecot: auth\(default\)|auth-worker\(\d+\)): pam\(\S+,<HOST>\): pam_authenticate\(\) failed: (User not known to the underlying authentication module: \d+ Time\(s\)|Authentication failure \(password mismatch\?\))\s*$
            ^%(__prefix_line)sauth-worker\(\d+\): pam\(\S+,<HOST>\): unknown user\s*$

ignoreregex =

[Init]

journalmatch = _SYSTEMD_UNIT=dovecot.service

but does not BAN ip :(

**Comment by mrc0mmand** [comment]
Sorry for the confusion - I absolutely forgot about the 'session' field, which acts (almost) the same as the 'user' field (if it's defined, it has to contain at least '<>' and some text between these brackets).

So the correct full regex should be:

`
 ^%(__prefix_line)s(pop3|imap)-login: (Info: )?(Aborted login|Disconnected)(: Inactivity)? \(((auth failed, \d+ attempts)( in \d+ secs)?|tried to use (disabled|disallowed) \S+ auth)\):( user=(<\S*>)?,)?( method=\S+,)? rip=<HOST>(, lip=(\d{1,3}\.){3}\d{1,3})?(, TLS( handshaking(: SSL_accept\(\) failed: error:[\dA-F]+:SSL routines:[TLS\d]+_GET_CLIENT_HELLO:unknown protocol)?)?(: Disconnected)?)?(, session=(<\S+>)?)?\s*$
`

Changes I made:
* Replaced `( user=<\S*>,)?` with `( user=(<\S*>)?,)?`
* Replaced `(, session=<\S+>)?` with `(, session=(<\S+>)?)?`

**Comment by leeclemens** [comment]
@dzint what version of dovecot are you using?

**Comment by dzint** [comment]
@leeclemens 
> dovecot --version : 2.1.7

@mrc0mmand thank you for your answer :) but i test it and not work again. :(

**Comment by mrc0mmand** [comment]
@dzint That's weird, I tested the config file you provided and it works:

```
# fail2ban-client --version
Fail2Ban v0.9.1.dev
# wget -O /etc/fail2ban/filter.d/dovecot.conf https://raw.githubusercontent.com/dzint/fail2ban_/master/dovecot.conf
# sed -i '1d' /etc/fail2ban/filter.d/dovecot.conf
# echo "Apr 22 13:22:17 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=" > faillog
# fail2ban-regex --print-all-matched faillog /etc/fail2ban/filter.d/dovecot.conf

Running tests
=============

Use   failregex filter file : dovecot, basedir: /etc/fail2ban
Use         log file : faillog
Use         encoding : UTF-8


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   2) [1] ^\s*(<[^.]+\.[^.]+>)?\s*(?:\S+ )?(?:kernel: \[ *\d+\.\d+\] )?(?:@vserver_\S+ )?(?:(?:\[\d+\])?:\s+[\[\(]?(auth|dovecot(-auth)?|auth-worker)(?:\(\S+\))?[\]\)]?:?|[\[\(]?(auth|dovecot(-auth)?|auth-worker)(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)?\s(?:\[ID \d+ \S+\])?\s*(pop3|imap)-login: (Info: )?(Aborted login|Disconnected)(: Inactivity)? \(((auth failed, \d+ attempts)( in \d+ secs)?|tried to use (disabled|disallowed) \S+ auth)\):( user=(<\S*>)?,)?( method=\S+,)? rip=<HOST>(, lip=(\d{1,3}\.){3}\d{1,3})?(, TLS( handshaking(: SSL_accept\(\) failed: error:[\dA-F]+:SSL routines:[TLS\d]+_GET_CLIENT_HELLO:unknown protocol)?)?(: Disconnected)?)?(, session=(<\S+>)?)?\s*$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed [processed in 0.00 sec]
|- Matched line(s):
|  Apr 22 13:22:17 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=
`-
```

Could you provide more log lines for further testing?

**Comment by dzint** [comment]
> Apr 22 12:20:30 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<admin>, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=<eGg3gk0UWgAly9Zo>
> Apr 22 12:20:34 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<root>, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=<3JZzgk0USwAly9Zo>
> Apr 22 12:20:35 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<user>, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=<ozGDgk0UjwAly9Zo>
> Apr 22 12:20:38 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<test>, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=<ZHmzgk0U4wAly9Zo>
> Apr 22 12:20:38 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<webmaster>, method=PLAIN, rip=37.203.214.104,lip=81.164.24.87, session=<rQu4gk0UBQAly9Zo>
> Apr 22 12:20:40 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<admin>, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=<Q9HTgk0UuwAly9Zo>
> Apr 22 12:20:42 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<web>, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=<t6b1gk0UggAly9Zo>
> Apr 22 12:20:44 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<root>, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=<g/IPg00UXwAly9Zo>
> Apr 22 12:20:45 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<user>, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=<1QYgg00UpgAly9Zo>
> Apr 22 12:20:45 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<www>, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=<bdwhg00UrwAly9Zo>
> Apr 22 12:20:48 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<test>, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=<cV5Pg00UZAAly9Zo>
> Apr 22 12:20:48 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<webmaster>, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=<0SxUg00UdgAly9Zo>
> Apr 22 12:20:50 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<admin>, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=<r+dvg00U0QAly9Zo>
> Apr 22 12:20:52 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<web>, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=<4NSRg00UWAAly9Zo>
> Apr 22 12:20:54 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<root>, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=<TSisg00UpQAly9Zo>
> Apr 23 09:34:43 mail dovecot: pop3-login: Aborted login (no auth attempts in 3 secs): user=<>, rip=71.6.167.142, lip=81.164.24.87, TLS, session=<wZY0UF8UTABHBqeO>
> Apr 23 02:00:22 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 6 secs): user=<test>, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=<3ZLz9lgU2ACwPYrL>
> Apr 23 02:00:25 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 6 secs): user=<test>, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=<ewAp91gUZgCwPYrL>
> Apr 23 02:00:33 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 10 secs): user=<test>, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=<VfNa91gU6QCwPYrL>
> Apr 23 02:00:36 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 10 secs): user=<test>, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=<E/uK91gUugCwPYrL>
> Apr 23 02:00:39 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 10 secs): user=<test>, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=<mya891gUWQCwPYrL>
> Apr 23 02:00:49 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<test>, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=<FdLs91gU7QCwPYrL>
> Apr 23 02:00:52 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<test>, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=<EcIc+FgUFgCwPYrL>
> Apr 23 02:00:56 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<test>, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=<ozNO+FgUHACwPYrL>
> Apr 23 02:00:59 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<test>, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=<+kZ++FgU4wCwPYrL>
> Apr 23 02:01:02 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<test>, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=<+v+v+FgUpwCwPYrL>
> Apr 23 02:01:05 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<test>, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=<5Gzg+FgUYgCwPYrL>
> Apr 23 02:01:06 mail dovecot: pop3-login: Disconnected (no auth attempts in 53 secs): user=<>, rip=176.61.138.203, lip=81.164.24.87, session=<zdTt+VgUmgCwPYrL>
> Apr 23 02:01:08 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<test>, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=<dDwR+VgU3ACwPYrL>
> Apr 23 02:01:12 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<test>, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=<Th1J+VgUYgCwPYrL>
> Apr 23 02:01:15 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<test>, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=<OG19+VgUywCwPYrL>
> Apr 23 02:01:20 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=<test>, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=<xhu++VgUcACwPYrL>

**Comment by mrc0mmand** [comment]
@dzint Ok, I've added one last edit and now it matches everything it should (from log you provided):

`
 ^%(__prefix_line)s(pop3|imap)-login: (Info: )?(Aborted login|Disconnected)(: Inactivity)? \(((auth failed, \d+ attempts)( in \d+ secs)?|tried to use (disabled|disallowed) \S+ auth)\):( user=(<\S*>)?,)?( method=\S+,)? rip=<HOST>(, ?lip=(\d{1,3}\.){3}\d{1,3})?(, TLS( handshaking(: SSL_accept\(\) failed: error:[\dA-F]+:SSL routines:[TLS\d]+_GET_CLIENT_HELLO:unknown protocol)?)?(: Disconnected)?)?(, session=(<\S+>)?)?\s*$
`

```
# fail2ban-regex --print-all-matched faillog2 /etc/fail2ban/filter.d/dovecot.conf

Running tests
=============

Use   failregex filter file : dovecot, basedir: /etc/fail2ban
Use         log file : faillog2
Use         encoding : UTF-8


Results
=======

Failregex: 30 total
|-  #) [# of hits] regular expression
|   2) [30] ^\s*(<[^.]+\.[^.]+>)?\s*(?:\S+ )?(?:kernel: \[ *\d+\.\d+\] )?(?:@vserver_\S+ )?(?:(?:\[\d+\])?:\s+[\[\(]?(auth|dovecot(-auth)?|auth-worker)(?:\(\S+\))?[\]\)]?:?|[\[\(]?(auth|dovecot(-auth)?|auth-worker)(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)?\s(?:\[ID \d+ \S+\])?\s*(pop3|imap)-login: (Info: )?(Aborted login|Disconnected)(: Inactivity)? \(((auth failed, \d+ attempts)( in \d+ secs)?|tried to use (disabled|disallowed) \S+ auth)\):( user=(<\S*>)?,)?( method=\S+,)? rip=<HOST>(, ?lip=(\d{1,3}\.){3}\d{1,3})?(, TLS( handshaking(: SSL_accept\(\) failed: error:[\dA-F]+:SSL routines:[TLS\d]+_GET_CLIENT_HELLO:unknown protocol)?)?(: Disconnected)?)?(, session=(<\S+>)?)?\s*$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [32] (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
`-

Lines: 32 lines, 0 ignored, 30 matched, 2 missed [processed in 0.01 sec]
|- Matched line(s):
|  Apr 22 12:20:30 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=
|  Apr 22 12:20:34 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=<3JZzgk0USwAly9Zo>
|  Apr 22 12:20:35 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=
|  Apr 22 12:20:38 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=
|  Apr 22 12:20:38 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=37.203.214.104,lip=81.164.24.87, session=
|  Apr 22 12:20:40 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=
|  Apr 22 12:20:42 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=
|  Apr 22 12:20:44 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=
|  Apr 22 12:20:45 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=<1QYgg00UpgAly9Zo>
|  Apr 22 12:20:45 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=
|  Apr 22 12:20:48 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=
|  Apr 22 12:20:48 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=<0SxUg00UdgAly9Zo>
|  Apr 22 12:20:50 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=
|  Apr 22 12:20:52 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=<4NSRg00UWAAly9Zo>
|  Apr 22 12:20:54 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=37.203.214.104, lip=81.164.24.87, session=
|  Apr 23 02:00:22 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 6 secs): user=, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=<3ZLz9lgU2ACwPYrL>
|  Apr 23 02:00:25 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 6 secs): user=, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=
|  Apr 23 02:00:33 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 10 secs): user=, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=
|  Apr 23 02:00:36 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 10 secs): user=, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=
|  Apr 23 02:00:39 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 10 secs): user=, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=
|  Apr 23 02:00:49 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=
|  Apr 23 02:00:52 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=
|  Apr 23 02:00:56 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=
|  Apr 23 02:00:59 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=<+kZ++FgU4wCwPYrL>
|  Apr 23 02:01:02 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=<+v+v+FgUpwCwPYrL>
|  Apr 23 02:01:05 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=<5Gzg+FgUYgCwPYrL>
|  Apr 23 02:01:08 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=
|  Apr 23 02:01:12 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=
|  Apr 23 02:01:15 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=
|  Apr 23 02:01:20 mail dovecot: pop3-login: Aborted login (auth failed, 1 attempts in 17 secs): user=, method=PLAIN, rip=176.61.138.203, lip=81.164.24.87, session=
`-
|- Missed line(s):
|  Apr 23 09:34:43 mail dovecot: pop3-login: Aborted login (no auth attempts in 3 secs): user=<>, rip=71.6.167.142, lip=81.164.24.87, TLS, session=
|  Apr 23 02:01:06 mail dovecot: pop3-login: Disconnected (no auth attempts in 53 secs): user=<>, rip=176.61.138.203, lip=81.164.24.87, session=
`-
```

Those two missed lines are not something which should be banned for (the second one is legitimate message when client disconnects before sending any auth info to server and the first one says 'no auth attempts').
Also bear in mind that these regexes don't have to match every line from your logs, only the offending ones.

**Comment by dzint** [comment]
i have test your new regexes :) but not work 

see the my jail.conf : 
>[dovecot]
>enabled = true
>filter  = dovecot
>action  = iptables-allports[name=dovecot]
>logpath = /var/log/mail.log
>maxretry = 5

**Comment by mrc0mmand** [comment]
Could you check fail2ban log for any error/suspicious messages?

**Comment by dzint** [comment]
>root@mail:~# fail2ban-client stop
>Shutdown successful
>root@mail:~# fail2ban-client start && tail -f /var/log/fail2ban.log
>2015-04-23 21:55:23,770 fail2ban.server         [28110]: INFO    Starting Fail2ban v0.9.1.dev
>2015-04-23 21:55:23,770 fail2ban.server         [28110]: INFO    Starting in daemon mode
>2015-04-23 21:55:24,576 fail2ban.actions        [28112]: INFO    Set banTime = 360000
>2015-04-23 21:55:24,618 fail2ban.server         [28112]: INFO    Jail dovecot is not a JournalFilter instance
>2015-04-23 21:55:24,639 fail2ban.jail           [28112]: INFO    Jail 'ssh' started
>2015-04-23 21:55:24,664 fail2ban.jail           [28112]: INFO    Jail 'pure-ftpd' started
>2015-04-23 21:55:24,702 fail2ban.jail           [28112]: INFO    Jail 'postfix' started
>2015-04-23 21:55:24,750 fail2ban.jail           [28112]: INFO    Jail 'couriersmtp' started
>2015-04-23 21:55:24,763 fail2ban.actions        [28112]: NOTICE  [ssh] Ban 222.187.223.214
>2015-04-23 21:55:24,802 fail2ban.jail           [28112]: INFO    Jail 'courierauth' started
>2015-04-23 21:55:24,903 fail2ban.jail           [28112]: INFO    Jail 'sasl' started
>2015-04-23 21:55:25,034 fail2ban.jail           [28112]: INFO    Jail 'dovecot' started
>2015-04-23 21:55:25,531 fail2ban.actions        [28112]: NOTICE  [ssh] Ban 62.149.237.11
>2015-04-23 21:55:25,686 fail2ban.actions        [28112]: NOTICE  [sasl] Ban 197.211.24.53

**Comment by mrc0mmand** [comment]
When you (try to) trigger dovecot jail, are there any errors/etc.?

**Comment by dzint** [comment]
no error @mrc0mmand :(
do you want desable all other jail and let only dovecot ?

**Comment by mrc0mmand** [comment]
You may want to enable debug logging (change `loglevel` to `DEBUG` in `fail2ban.conf` and monitor fail2ban's behavior while triggering dovecot's jail.

**Comment by leonklingele** [comment]
Similar problem here. Using latest `dovecot.conf` from master.

```
$ grep "auth failed" /var/log/mail.log

Apr 30 22:04:57 sky dovecot: imap-login: Aborted login (auth failed, 1 attempts in 2 secs): user=<email@example.com>, method=PLAIN, rip=111.111.111.111, lip=222.222.222.222, TLS, ..
Apr 30 22:05:03 sky dovecot: imap-login: Disconnected (auth failed, 1 attempts in 6 secs): user=<email@example.com>, method=PLAIN, rip=111.111.111.111, lip=222.222.222.222, TLS: Disconnected, ..
Apr 30 22:05:13 sky dovecot: imap-login: Aborted login (auth failed, 1 attempts in 6 secs): user=<email@example.com>, method=PLAIN, rip=111.111.111.111, lip=222.222.222.222, TLS, ..
Apr 30 22:05:15 sky dovecot: imap-login: Aborted login (auth failed, 1 attempts in 2 secs): user=<email@example.com>, method=PLAIN, rip=111.111.111.111, lip=222.222.222.222, TLS, ..
Apr 30 22:05:17 sky dovecot: imap-login: Aborted login (auth failed, 1 attempts in 2 secs): user=<email@example.com>, method=PLAIN, rip=111.111.111.111, lip=222.222.222.222, TLS, ..
Apr 30 22:05:22 sky dovecot: imap-login: Aborted login (auth failed, 1 attempts in 2 secs): user=<email@example.com>, method=PLAIN, rip=111.111.111.111, lip=222.222.222.222, TLS, ..
Apr 30 22:05:26 sky dovecot: imap-login: Aborted login (auth failed, 1 attempts in 2 secs): user=<email@example.com>, method=PLAIN, rip=111.111.111.111, lip=222.222.222.222, TLS, ..
```

```
$ fail2ban-regex /var/log/mail.log /etc/fail2ban/filter.d/dovecot.conf 

Running tests
=============

Use   failregex file : /etc/fail2ban/filter.d/dovecot.conf
Use         log file : /var/log/mail.info



Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [55198] MONTH Day Hour:Minute:Second
`-

Lines: 55198 lines, 0 ignored, 0 matched, 55198 missed
Missed line(s): too many to print.  Use --print-all-missed to print all 55198 lines
```

```
$ fail2ban-client --version
Fail2Ban v0.8.13
```

```
$ dovecot --version
2.2.13
```

**Comment by sebres** [comment]
@leonklingele 
What in your log excerpt is hidden under `..` is very important, because matching regular expression for this lines parses it **to end of line**.
So to test it, we need 2-3 lines completely...
If you don't want, you can change the 2nd line in `failregex` to something like (+ original in current master):
```
^%(__prefix_line)s(pop3|imap)-login: (Info: )?(Aborted login|Disconnected)(: Inactivity)? \(((auth failed, \d+ attempts)( in \d+ secs)?|tried to use (disabled|disallowed) \S+ auth)\):( user=<\S*>,)?( method=\S+,)? rip=<HOST>(, lip=(\d{1,3}\.){3}\d{1,3})?(, TLS )?
^%(__prefix_line)s(pop3|imap)-login: (Info: )?(Aborted login|Disconnected)(: Inactivity)? \(((auth failed, \d+ attempts)( in \d+ secs)?|tried to use (disabled|disallowed) \S+ auth)\):( user=<\S*>,)?( method=\S+,)? rip=<HOST>(, lip=(\d{1,3}\.){3}\d{1,3})?(, TLS( handshaking(: SSL_accept\(\) failed: error:[\dA-F]+:SSL routines:[TLS\d]+_GET_CLIENT_HELLO:unknown protocol)?)?(: Disconnected)?)?(, session=<\S+>)?\s*$
```

**Comment by leonklingele** [comment]
It turned out that I was not using the default `login_log_format_elements` in dovecot's `conf.d/10-logging.conf`.
This is the log format I'm using:
`login_log_format_elements = "user=<%u> method=%m rip=%r lip=%l mpid=%e %c %k"`

Sorry for the trouble.

**Comment by sebres** [comment]
> It turned out that I was not using the default

For a custom dovecot logging, you should certainly use a custom `failregex` in fail2ban.

**Comment by christhomas** [comment]
Can I ask what the point of matching user, session etc is? because after you've got the "auth failed" and then the subsequent <HOST> extraction, what use is the rest of the regex? 

I'm just wondering what you're matching the rest of the string for when you should have already successfully matched and the rest is not useful information, as far as I can see.

**Comment by sebres** [comment]
> Can I ask what the point of matching user, session etc is?

The question is rather why dovecot developers placed the IP information after some foreign input (like a username) in the log message. 
So in order to obtain an IP address (from `rip=...`) you should pass some data which is not necessarily guaranteed to be a "safe" input.

Thus the answer is:
- if you have a foreign input in-between **you must** parse the string anchored from both sides (even to avoid possible injection on this foreign input).
- additionally in 0.10 capturing of a user-name (using tags `<F-USER>`) could help to recognize an intruder with valid legitimate account trying to brute force another accounts (see https://github.com/fail2ban/fail2ban/issues/1263#issuecomment-262258507 for possible scenario).
  Since #2014 fail2ban can recognize behavior like this.

**Comment by christhomas** [comment]
oh thats a good point, so you're thinking injection attacks into that field could mean it breaks matching?

**Comment by sebres** [comment]
Either that or at least it opens a vector to organize flooding/ddos (this way one can slowing down the filter in one session and do brute attack in another), or even injection to ban legitimate IPs not belonging the intruder (ban list as well as firewall's rules growing, etc).
Just see this as the matter of responsibility.

Anyway if you want additionally specify your own regex, you can simply do it in your derivative config (jail.local or filter.d/dovecot.local) using:
```ini
failregex = %(known/failregex)s
            ^your own left anchored RE to catch <ADDR> ...
```
Or even overwrite if it is needed.
And if something gets wrong, then you'll be responsible for "disaster" ;)
