### ISSUE TITLE
Correct way to remove fail2ban, installed using the setup.py

### ISSUE THREAD

**Issue by boolean-is-null** [fail2ban/fail2ban#1031]
I havent found any guide how to (nor a setup.py option) remove fail2ban when installed with the setup.py

How do I correctly remove fail2ban from my system?

**Comment by leeclemens** [comment]
It largely depends how you installed it. If by package (deb,rpm), you should be able to uninstall it the same way. Otherwise you'll need to delete the files created by setup.py's installation.

**Comment by boolean-is-null** [comment]
as stated above I installed as described on the github site..

tar xvfj fail2ban-0.9.1.tar.bz2
cd fail2ban-0.9.1
python setup.py install

To be honest, I have no idea which files were created, except the config files and the executables..

**Comment by leeclemens** [comment]
The setup.py installation prints the files it creates, iirc. This isn't really an "issue' with fail2ban, so I'm going to mark it closed.
