### ISSUE TITLE
was about to release but new test breakages while building Debian packages

### ISSUE THREAD

**Issue by yarikoptic** [fail2ban/fail2ban#1034]
just whining out loud since may be someone would listen and help out (I am a bit burnt out for today already and will be busy in upcoming days).  Here are the 2 failing tests while building for up-to-date Debian sid (as root in a build env):

1. I hate unicode problems:
```
======================================================================
FAIL: testAddBanInvalidEncoded (fail2ban.tests.databasetestcase.DatabaseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/buildd/fail2ban-0.9.2/.pybuild/pythonX.Y_3.4/build/fail2ban/tests/databasetestcase.py", line 200, in testAddBanInvalidEncoded
    or readtickets[0] == tickets[0]
AssertionError: False is not true
 
```
`2`. probably smth trivial
```
======================================================================
FAIL: testSyslogSocketNOK (fail2ban.tests.servertestcase.TransmitterLogging)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/buildd/fail2ban-0.9.2/.pybuild/pythonX.Y_3.4/build/fail2ban/tests/servertestcase.py", line 805, in testSyslogSocketNOK
    }[platform.system() in ('Linux',)]
  File "/tmp/buildd/fail2ban-0.9.2/.pybuild/pythonX.Y_3.4/build/fail2ban/tests/servertestcase.py", line 88, in setGetTest
    self.assertEqual(v(self.transm.proceed(setCmd)), v((outCode, outValue)))
AssertionError: Tuples differ: (1, Exception('Failed to change log target',)) != (0, 'SYSLOG')

First differing element 0:
1
0

- (1, Exception('Failed to change log target',))
+ (0, 'SYSLOG')
```

up-to-date (with some not pushed changes to master) debian branch is available from my clone http://github.com/yarikoptic/fail2ban

**Comment by sebres** [comment]
Hmm, strange.
I have no errors in current master by `testAddBanInvalidEncoded` with python 3.4.
```
/usr/bin/python3 | (3, 4, '3.4.0 (default, Apr 11 2014, 13:05:11) \n[GCC 4.8.2]')
Fail2ban 0.9.1.dev test suite. Python 3.4.0 (default, Apr 11 2014, 13:05:11) [GCC 4.8.2]. Please wait...
..............
----------------------------------------------------------------------
Ran 14 tests in 7.637s
OK
ready.
```

**Comment by yarikoptic** [comment]
Me neither if I run locally. Bit it fails when I build in minimal build environment (cowbuilder), as root

**Comment by sebres** [comment]
would be nice to know what exactly not equal in compared tickets (line 200)...
Can you add logging of both tickets and heavydebug it?

**Comment by yarikoptic** [comment]
On Mon, 27 Apr 2015, Serg G. Brester wrote:

>    would be nice to know what exactly not equal in compared tickets (line
>    200)...
>    Can you add logging of both tickets and heavydebug it?
(Pdb) print(readtickets[0])
FailTicket: ip=127.0.0.1 time=0 #attempts=0 matches=['user "?????"', 'user "????????"']
(Pdb) print(FailTicket("127.0.0.1", 0, [invstr, 'user "\xc3\xa4\xc3\xb6\xc3\xbc\xc3\x9f"']))
*** UnicodeEncodeError: 'ascii' codec can't encode characters in position 132-138: ordinal not in range(128)
(Pdb) print(tickets[0])
*** UnicodeEncodeError: 'ascii' codec can't encode characters in position 60-64: ordinal not in range(128)


now that it is morning...  on my laptop

*(Pdb) print(readtickets[0])
FailTicket: ip=127.0.0.1 time=0 #attempts=0 matches=['user "Ñâåòà"', 'user "Ã¤Ã¶Ã¼Ã\x9f"']
(Pdb) print(FailTicket("127.0.0.1", 0, [invstr, 'user "\xc3\xa4\xc3\xb6\xc3\xbc\xc3\x9f"']))
FailTicket: ip=127.0.0.1 time=0 #attempts=0 matches=[b'user "\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd"', 'user "Ã¤Ã¶Ã¼Ã\x9f"']
(Pdb) print(tickets[0])
FailTicket: ip=127.0.0.1 time=0 #attempts=0 matches=['user "Ñâåòà"', 'user "Ã¤Ã¶Ã¼Ã\x9f"']


but I have locale throughout en_US.UTF-8 when in that env C but changing LC_ALL
or LC_LANG quickly didn't help

**Comment by sebres** [comment]
Hmm, have you tried log instead of print? I don't know what for encoding for stdout used inside of build env...
Imho in addition, allready `readtickets[0]` doesn't look good...
```
FailTicket: ip=127.0.0.1 time=0 #attempts=0 matches=['user "?????"', 'user "????????"']
```
So I think, anything is wrong in your build environment...

**Comment by yarikoptic** [comment]
On Mon, 27 Apr 2015, Serg G. Brester wrote:

>    Hmm, have you tried log instead of print? I don't know what for encoding
>    for stdout used inside of build env...
>    Imho in addition, allready readtickets[0] doesn't look good...

>  FailTicket: ip=127.0.0.1 time=0 #attempts=0 matches=['user "?????"', 'user "????????"']

>    So I think, anything is wrong in your build environment...
that is the point to figure out "what" and I don't think it is "Wrong"
-- it is just different from what test expects

**Comment by sebres** [comment]
Yep, but so different, that testing of invalid encoded chars is not possible. 
So you can either "repair" that, "what" is "wrong" or bypass this test case (that is only for checking an invalid encoded chars in matches json).
It's not so easy to build inv-encoded test case works for both 2.x and 3.x.
First try to execute following lines and post the output here:
```
>>> import sys; sys.getdefaultencoding()
'utf-8'
>>> 'user "\xc3\xa4\xc3\xb6\xc3\xbc\xc3\x9f"'
'user "Ã¤Ã¶Ã¼Ã\x9f"'
>>> 'user "\xc3\xa4\xc3\xb6\xc3\xbc\xc3\x9f"'.encode('utf-8', 'replace')
b'user "\xc3\x83\xc2\xa4\xc3\x83\xc2\xb6\xc3\x83\xc2\xbc\xc3\x83\xc2\x9f"'
>>> b'user "\xc3\x83\xc2\xa4\xc3\x83\xc2\xb6\xc3\x83\xc2\xbc\xc3\x83\xc2\x9f"'.decode('utf-8')
'user "Ã¤Ã¶Ã¼Ã\x9f"'
```

**Comment by yarikoptic** [comment]
ok -- resolved issues... for utf, just had to set locale to present C.UTF-8.  The other one had to deal with absent /var/log -- no /var/log, then no setting to SYSLOG -- adjusted the test(s)
now building debian packages, if everything looks ok -- 0.9.2 will come tomorrow morning. cheers!
