### ISSUE TITLE
Ubuntu 15.04 install issue

### ISSUE THREAD

**Issue by riegaz** [fail2ban/fail2ban#1036]
I tried to install fail2ban on the latest released ubuntu version. After doing a fresh install, it gives me errors when it tries to start the service.

Could anyone reproduce this?

**Comment by yarikoptic** [comment]
let me read your mind and guess that it is complaining that python3-systemd  is not installed ( one way it another).  anyways,  it is a problem to be fixed by ubuntu maintainers ( so file/ research within  launched)...  or wait until I will upload fixed Debian package and it gets sucked into ubuntu
