### ISSUE TITLE
Fail2Ban crashed after load ~400 logfile...

### ISSUE THREAD

**Issue by joinfok** [fail2ban/fail2ban#1043]
Hi!

I set up  F2B 0.8.07 to centos 5.1 latest (Yes, this very old... :) )

Work this fine before adding many virtualhost.

I set Up one jail and add a ~350 virtualhost access.log file. 
Start F2B and load, work successfull. ---- and detect logrotate, reloading logfiles and crashed!

If set up 2 jail (user n*all virtualhost logs), crashed in loading, F2B dead.

F2B run as root, ulimit is unlimited, /etc/security/limits.conf  set fail2ban soft 10 000, cat /proc/limits/...fail2ban maf_open_file is 1024...

I use default gamin, gamin is set to limits max_open_file 1024.

Pleas help me solving this.

In log no information, F2B not push message to logfile awaiting load jailed logfiles.

**Comment by leeclemens** [comment]
Using the pyinotify backed may help you with that many logs. I don't recall what version it was added (should be in a comment in jail.conf).

**Comment by joinfok** [comment]
U upgrade F2B 8.14 latest stable from EPEL
Install depedencies:
I use python 2.4 and pythin-inotify-0.1.0-1.2.el5.rfx86_64
gamin-0.1.7
gamin-python-0.1.7

The problem is stable, if try load all logfile, F2Bcrashed.

I use limitted load (virtualhosts/[a-d]*/access.log) logfiles, working good.

I don' understand this: (should be in a comment in jail.conf).
Pleas write more!

**Comment by sebres** [comment]
<blockquote>python 2.4</blockquote>
Hmm... Imho, it is at least 2 versions out of date (I think even 2.6 was stopped for developing - regards further development of modules it is true also).

<blockquote>I don' understand this: (should be in a comment in jail.conf).</blockquote>
```
backend = pyinotify
```

**Comment by joinfok** [comment]
Many problemmm :XD...
I try backend to pyinotify - not load backend pyinotify module.... 

I check this: Package python-inotify-0.1.0-1.2.el5.rf.x86_64 already installed and latest version
I try import manual in python shell, import succes... in fail2ban can't importing this....

I try backend=polling, all logfile loading successfull!

What is a differetn a Gamin,Polling,PyInotify mode? Idealisch vs Stable vs Performance... etc?

**Comment by sebres** [comment]
<blockquote>what is a different...</blockquote>
I your case (crash / exception) it is a stability (only polling is python pure - also with core python backend only). Both another are backend modules with extern libs (so theoretical bugs are possibe in python bin implementation, as well as in lib self). As already said - your version is simple too old.

About performance: gamin resp. pyinotify should have better performance and shorter reaction time as polling.

**Comment by leeclemens** [comment]
@joinfok you're using an operating system that stopped being fully supported in Q1 2014 - the latest release for which is 5.11 - 10 versions later than your 5.1 :)

iirc, python26 is available from epel for centos5 and I know pyinotify is available.

**Comment by leeclemens** [comment]
I'm going to close this for reasons already mentioned (lots of unsupported versions of things). If you are still having issues, please reopen.
