### ISSUE TITLE
MWL not sending logs with email notifications

### ISSUE THREAD

**Issue by jbaxley** [fail2ban/fail2ban#1044]
The action, while banning the IP and sending an email notification, isn't sending any logs associated with the banned IP.  

Centos 7

**Comment by justabaka** [comment]
It may be a configuration issue. Are there any error messages?

**Comment by jbaxley** [comment]
Nope, no error messages.

-Jeb

**Comment by superian** [comment]
I am seeing this (Debian Jessie, Fail2Ban v0.8.13) on some jails, but not others.

Sample SSH email:

> Hi,
>
> The IP 184.173.26.138 has just been banned by Fail2Ban after
> 3 attempts against ssh.
>
> Here is more information about 184.173.26.138:
> (info about it deleted)
>
>
> Lines containing IP:184.173.26.138 in /var/log/auth.log
> Nov  5 08:21:38 example sshd[20158]: Failed password for invalid user ubnt from 184.173.26.138 port 51131 ssh2
> Nov  5 08:21:38 example sshd[20158]: error: Received disconnect from 184.173.26.138: 3: com.jcraft.jsch.JSchException: Auth fail [preauth]
>
>
> Regards,
> Fail2Ban

Sample Apache jail email:

> Hi,
> 
> The IP 193.201.227.112 has just been banned by Fail2Ban after
> 5 attempts against apache-xmlrpc.
> 
> 
> Here is more information about 193.201.227.112:
>
> (info about it deleted)
>
>
> Lines containing IP:193.201.227.112 in /home/*/logs/*access.log
>
>
>
> Regards,
>
> Fail2Ban

From jail.local:

> action    = %(action_mwl)s
>
> # JAILS
>
> [ssh]
>
> enabled   = true
> maxretry  = 3
>
> (..)
>
> [apache-xmlrpc]
>
> enabled  = true
> port     = http,https
> action   = %(action_mwl)s
> filter   = apache-xmlrpc
> logpath  = /home/*/logs/*access.log
> maxretry = 5

Here are the lines it's not showing:

> # grep 193.201.227.112 /home/username/logs/*.access.log
> /home/username/logs/example.com.access.log:193.201.227.112 - - [01/Nov/2015:19:26:25 +0000] "GET / HTTP/1.1" 200 6722 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0" 0
> /home/username/logs/example.com.access.log:193.201.227.112 - - [02/Nov/2015:15:10:55 +0000] "POST /wp-content/themes/picolight/style.css/xmlrpc.php HTTP/1.1" 404 267 "http://example.com/wp-content/themes/picolight/style.css/xmlrpc.php" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36" 0
> /home/username/logs/example.com.access.log:193.201.227.112 - - [03/Nov/2015:00:51:55 +0000] "POST /wp-content/themes/picolight/style.css/xmlrpc.php HTTP/1.1" 404 267 "http://example.com/wp-content/themes/picolight/style.css/xmlrpc.php" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36" 0
> /home/username/logs/example.com.access.log:193.201.227.112 - - [02/Nov/2015:13:44:25 +0000] "POST /wp-content/themes/market/style.css/xmlrpc.php HTTP/1.1" 404 266 "http://example.com/wp-content/themes/market/style.css/xmlrpc.php" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36" 0
> /home/username/logs/example.com.access.log:193.201.227.112 - - [02/Nov/2015:23:40:17 +0000] "POST /wp-content/themes/market/style.css/xmlrpc.php HTTP/1.1" 404 266 "http://example.com/wp-content/themes/market/style.css/xmlrpc.php" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36" 0
> /home/username/logs/example.com.access.log:193.201.227.112 - - [05/Nov/2015:08:00:19 +0000] "POST /wp-content/themes/market/style.css/xmlrpc.php HTTP/1.1" 404 243 "http://example.com/wp-content/themes/market/style.css/xmlrpc.php" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36" 0

.. and here's what fail2ban.log has to say about all this:

> 2015-11-05 08:00:20,049 fail2ban.actions[1993]: WARNING [apache-xmlrpc] Ban 193.201.227.112
> 2015-11-05 08:21:36,278 fail2ban.filter [1993]: WARNING Determined IP using DNS Lookup: 8a.1a.adb8.ip4.static.sl-reverse.com = ['184.173.26.138']
> 2015-11-05 08:21:39,333 fail2ban.filter [1993]: WARNING Determined IP using DNS Lookup: 8a.1a.adb8.ip4.static.sl-reverse.com = ['184.173.26.138']
> 2015-11-05 08:21:39,858 fail2ban.actions[1993]: WARNING [ssh] Ban 184.173.26.138

The same jail is happily including the equivalent log lines on Debian Wheezy Fail2Ban v0.8.6

**Comment by superian** [comment]
Nope, if I change the ssh jail to have a wildcard in its logfile line, it still includes the relevant lines. There is only one logfile the wildcard matches though...

**Comment by jbaxley** [comment]
I actually got this to work by using the old logfile regular expression.
I'm only using this on Redhat, so after reverting - it seemed to work for
everything that I was using.


[image: --]
Jeb Baxley
[image: http://]about.me/jeb.baxley
<http://about.me/jeb.baxley>

**Comment by superian** [comment]
Looking at some emails... 

*Includes extracts from the relevant file(s):* 

    ssh - /var/log/auth.log
    sasl - /var/log/mail.warn
    dovecot - /var/log/mail.log
    wordpress-spam - /home/*/public_html/*/wp-content/spam.log

*Doesn't:*

    ssh-ddos - /var/log/auth.log
    apache-xmlrpc - /home/*/logs/*access.log
    apache-wp-login - /home/*/logs/*access.log
    apache-badbots - /home/*/logs/*access.log
    apache-dos - /home/*/logs/*access.log

.. so at least one with a wildcard works, and at least one without one doesn't.

**Comment by sebres** [comment]
should be fixed in #1622, please test with newer version
