### ISSUE TITLE
dbpurgeage won't be honored when be set in fail2ban.local

### ISSUE THREAD

**Issue by atueting** [fail2ban/fail2ban#1048]
Setting dbpurgeage = 691200 in fail2ban.local has no effect.
fail2ban-client get dbpurgeage still respond with the Default value of 86400seconds

**Comment by yarikoptic** [comment]
I bet you forgot to define it within a [Definition] or [DEFAULT] section. it must work. reopen if my guiess is incorrect

**Comment by leeclemens** [comment]
It may be honored, but `fail2ban-client get dbpurgeage` does not display what is defined and there seems to be some odd behavior with it. I haven't had time to look into it any further:
```
# cat /etc/fail2ban/fail2ban.local
[Definition]

dbpurgeage = 691200
```

```
# fail2ban-client get dbpurgeage
Current database purge age is:
`- 86400seconds
# fail2ban-client -d | grep dbpurgeage
['set', 'dbpurgeage', 691200]
```

`fail2ban-client set dbpurgeage` seems to work:
```
# fail2ban-client set dbpurgeage 123456
Current database purge age is:
`- 123456seconds
# fail2ban-client get dbpurgeage
Current database purge age is:
`- 123456seconds
```

but then....
```
# fail2ban-client -d | grep dbpurge
['set', 'dbpurgeage', 691200]
```

**Comment by atueting** [comment]
I concur with Lee's findings.  In addition every option I'm putting in fail2band.local won't be reflected either.

**Comment by sebres** [comment]
see https://github.com/fail2ban/fail2ban/pull/1050#issuecomment-100832885

**Comment by leeclemens** [comment]
@sebres that's a huge PR...can you reference the commit which fixes this issue?

**Comment by sebres** [comment]
@leeclemens is unfortunately not a single commit, because located in module observer, that can run timed tasks.
