### ISSUE TITLE
fail2ban.log doesn't exist..

### ISSUE THREAD

**Issue by techpulse** [fail2ban/fail2ban#1052]
i can not find fail2ban.log? i would like to see real time actions by tailing it, however it doesnt exist

in /var/log/

im using centos 6.4 or so

i expect to see "banned ip." etc

**Comment by sebres** [comment]
Can you dump the configuration with `fail2ban-client -d` and search for errors there. And also in the output of `fail2ban-client status`.
Hereafter you can stop f2b and then start it again with `fail2ban-client -v -v start` (increased verbosity) to see all parameters send to fail2ban-server.

**Comment by techpulse** [comment]
i want action log, to see the actions

such as ..

"banned ip address: 127.0.0.1 for reaching request limit". .

**Comment by leeclemens** [comment]
Ban and Unban messages are logged as NOTICE.

Did you perform the steps @sebres provided?

**Comment by techpulse** [comment]
http://pastebin.com/X9wMQ1Jh configuration

Status
|- Number of jail:      2
`- Jail list:           nginx-req-limit, ssh-iptables


+ detailed startup: http://pastebin.com/60z4XAte

**Comment by techpulse** [comment]
Had to change logtarget to 

logtarget = /var/log/fail2ban.log

**Comment by leeclemens** [comment]
Glad it seems resolved, `logtarget = /var/log/fail2ban.log` is the default value provided by fail2ban - although it may be altered by package maintainers, apparently.

**Comment by leeclemens** [comment]
default is supposed to be STDERR according to comments in fail2ban.conf
