### ISSUE TITLE
reject vs drop?

### ISSUE THREAD

**Issue by techpulse** [fail2ban/fail2ban#1054]
From what I know, drop uses no resources at all. Reject does, is this true?

How can I make it drop instead of reject, if so?

**Comment by leeclemens** [comment]
I wouldn't say 'no resources', but I believe it is preferable when it comes to resource usage.  That said, it is no longer the default.

You can change it with:

```
/etc/fail2ban/action.d/iptables-blocktype.local
[Init]

blocktype = DROP
```

**Comment by yarikoptic** [comment]
@techpulse please use mailing list for support questions/requests . Thanks @leeclemens
