### ISSUE TITLE
sshd jail: ignore/reset failed attempts when publickey has been accepted

### ISSUE THREAD

**Issue by blueyed** [fail2ban/fail2ban#1055]
It would be nice, if "Accepted publickey ... from $IP" would unban that IP
again, and not consider it for the recidive filter, too.

I've managed to blacklist myself, because I've not had the ssh-agent setup
properly and use autossh etc and/or dismissed the popup asking for the
password/passphrase.

This might also happen when normal authentication succeeds, not just for
"Accepted publickey".

My current workaround for this might be to automatically add my current IP to
the whitelist - although that would be easier with something like "whitelist
for X minutes" to automatically get it purged again.  Is this worth a new
feature request?

From the logs:

auth.log:May 18 03:53:20 HN sshd[101638]: Failed password for user from X.X.X.X port 59214 ssh2
auth.log:May 18 03:53:20 HN sshd[101638]: Failed password for user from X.X.X.X port 59214 ssh2
auth.log:May 18 03:53:20 HN sshd[101638]: Connection closed by X.X.X.X [preauth]
auth.log:May 18 03:53:25 HN sshd[101700]: Accepted publickey for user from X.X.X.X port 59222 ssh2
auth.log:May 18 03:53:25 HN sshd[101702]: Received disconnect from X.X.X.X: 11: disconnected by user
auth.log:May 18 03:53:36 HN sshd[101807]: Accepted publickey for user from X.X.X.X port 59225 ssh2
auth.log:May 18 03:54:03 HN sshd[101809]: Received disconnect from X.X.X.X: 11: disconnected by user
auth.log:May 18 03:54:13 HN sshd[101887]: Accepted publickey for user from X.X.X.X port 59235 ssh2
auth.log:May 18 03:54:31 HN sshd[101930]: Accepted publickey for user from X.X.X.X port 49400 ssh2
auth.log:May 18 03:59:35 HN sshd[101889]: Received disconnect from X.X.X.X: 11: disconnected by user
auth.log:May 18 03:59:45 HN sshd[101932]: Received disconnect from X.X.X.X: 11: disconnected by user
auth.log:May 18 03:59:45 HN sshd[112301]: Failed password for user from X.X.X.X port 59378 ssh2
auth.log:May 18 03:59:45 HN sshd[112301]: Failed password for user from X.X.X.X port 59378 ssh2
auth.log:May 18 03:59:45 HN sshd[112301]: Connection closed by X.X.X.X [preauth]
auth.log:May 18 03:59:51 HN sshd[112311]: Failed password for user from X.X.X.X port 59384 ssh2
auth.log:May 18 03:59:51 HN sshd[112311]: Failed password for user from X.X.X.X port 59384 ssh2
auth.log:May 18 03:59:51 HN sshd[112311]: Connection closed by X.X.X.X [preauth]

fail2ban.log:2015-05-18 03:53:20,870 fail2ban.filter         [31372]: INFO    [sshd] Found X.X.X.X
fail2ban.log:2015-05-18 03:53:20,871 fail2ban.filter         [31372]: INFO    [sshd] Found X.X.X.X
fail2ban.log:2015-05-18 03:59:46,261 fail2ban.filter         [31372]: INFO    [sshd] Found X.X.X.X
fail2ban.log:2015-05-18 03:59:46,261 fail2ban.filter         [31372]: INFO    [sshd] Found X.X.X.X
fail2ban.log:2015-05-18 03:59:51,396 fail2ban.filter         [31372]: INFO    [sshd] Found X.X.X.X
fail2ban.log:2015-05-18 03:59:51,396 fail2ban.filter         [31372]: INFO    [sshd] Found X.X.X.X
fail2ban.log:2015-05-18 03:59:52,369 fail2ban.actions        [31372]: NOTICE  [sshd] Ban X.X.X.X
fail2ban.log:2015-05-18 03:59:52,961 fail2ban.filter         [31372]: INFO    [recidive] Found X.X.X.X

**Comment by leeclemens** [comment]
Since the ban usually involves blocking the IP via a firewall, you normally wouldn't be able to connect successfully while being banned. That being said, having successful logins reset the fail counter, etc has been brought up before - although I can't seem to find a previous issue about it.

**Comment by blueyed** [comment]
In the case above I've successfully logged in, while fail2ban was increasing its counter.
The successful action should have reset it.

It would be even more helpful in this regard to have an option to auto-whitelist IPs for a certain amount of time, if they successfully logged in.

**Comment by leeclemens** [comment]
You didn't successfully log in after you were banned; I was responding directly to your first sentence where you said "unban".

**Comment by sebres** [comment]
I believe, we have every now and then discussed about success-match.
It would be indeed nice inside #716 (ban-time-incr) for ips already known as "bad", and I wrote already about that: https://github.com/fail2ban/fail2ban/pull/716#issuecomment-45867103

But I think, it would be also helpful just as forget IP attempts (reset failure counter).

**Comment by tomgreen66** [comment]
Hi - I also hit this problem and put together a little branch which seems to handle a regex to identify with to reset counter (i.e. add a option "resetregex" similar to "failregex" and "ignoreregex").  Seems to work hopefully nothing glaringly bad in it but I put it together just by looking at how the other options were plumbed in.  See [reset counter branch in tomgreen66/fail2ban](/tomgreen66/fail2ban/tree/successregex)

**Comment by sebres** [comment]
further in #1243

**Comment by durnin** [comment]
Hello, was this feature (resetregex) merged? Seems quite useful for a bunch of situations...specially when working with application logs.
