### ISSUE TITLE
Slow scraping?

### ISSUE THREAD

**Issue by techpulse** [fail2ban/fail2ban#1057]
Hi,

I am using: https://rtcamp.com/tutorials/nginx/fail2ban/

I set maxretry = 10 to 3, however i still see that some managed to access the site and reach the limit:

15 times, and some 800+ times (for some reason it did not get blocked)

2015/05/24 20:13:29 [error] 5990#0: *62015 limiting requests, excess: 5.028 by zone "firewall", client: 200.111.155.67, server: mydomain.com, request: "GET / HTTP/1.1", host: "centralgamingzone.com"
2015/05/24 20:13:29 [error] 5990#0: *62016 limiting requests, excess: 5.028 by zone "firewall", client: 200.111.155.67, server: mydomain.com, request: "GET / HTTP/1.1", host: "centralgamingzone.com"
2015/05/24 20:13:29 [error] 5990#0: *62016 limiting requests, excess: 5.028 by zone "firewall", client: 200.111.155.67, server: mydomain.com, request: "GET / HTTP/1.1", host: "centralgamingzone.com"

Any idea why this happens, is this a bug? Some of them gets throughw ithout getting blocked, i got 2gb ram and 8 cores..

**Comment by techpulse** [comment]
Also high ram usage.

System Load: 12%
Ram Usage: 95%
Disk Usage: 11%

fail2ban-server 10.2% 1.5 GB root (1)

**Comment by techpulse** [comment]
Status for the jail: nginx-req-limit
|- filter
|  |- File list:        /home/nginx/domains/domain.com/log/error.log
|  |- Currently failed: 4
|  `- Total failed:     4103087





wow, 4103087.. i assume it must be stored in ram?

**Comment by yarikoptic** [comment]
For support of some 3rd party filters -- please ask those 3rd parties.  Otherwise, if there is a bug in fail2ban, please describe actual problem and follow http://www.fail2ban.org/wiki/index.php/HOWTO_Seek_Help

**Comment by techpulse** [comment]
This is using fail2ban, and that filter is just like any other filter fail2ban offers.. just custom regex..
