### ISSUE TITLE
dovecot: login attempts not matched (auth-worker with sql; SASL LOGIN authentication failed)

### ISSUE THREAD

**Issue by blueyed** [fail2ban/fail2ban#1059]
The following attempts are not matched by fail2ban's Dovecot filter:

```
May 31 03:49:45 mailhost dovecot: auth-worker(1668): sql(user@domain.com,X.Y.Z.Z): unknown user (given password: XXX)
May 31 03:49:45 mailhost dovecot: auth-worker(1668): sql(user@anotherdomain.com,X.Y.Z.Z): unknown user (given password: XXX)
May 31 03:49:47 mailhost postfix/smtpd[4516]: warning: unknown[X.Y.Z.Z]: SASL LOGIN authentication failed: UGFzXXX
May 31 03:49:47 mailhost postfix/smtpd[4513]: warning: unknown[X.Y.Z.Z]: SASL LOGIN authentication failed: UGFzXXX
```

I am using this in dovecot/conf.d/10-logging.conf:

```
# Log unsuccessful authentication attempts and the reasons why they failed.
auth_verbose = yes

# In case of password mismatches, log the attempted password. Valid values are
# no, plain and sha1. sha1 can be useful for detecting brute force password
# attempts vs. user simply trying the same password over and over again.
# You can also truncate the value to n chars by appending ":n" (e.g. sha1:6).
auth_verbose_passwords = plain
```

For the "unknown user" case fail2ban seems to expect something with/from "pam":

```
^%(__prefix_line)sauth-worker\(\d+\): pam\(\S+,<HOST>\): unknown user\s*$
```

That could be fixed as follows:

```
^%(__prefix_line)sauth-worker\(\d+\): (pam|sql)\(\S+,<HOST>\): unknown user\s*$
```

I am using a MySQL database/provider for authentication.
There might be other strings that could be there maybe (apart from "pam" and "sql").

The other lines get matched by postfix-sasl, but this does not appear to block them properly.

```
May 31 03:49:47 elfe postfix/smtpd[4516]: warning: unknown[X.Y.Z.Z]: SASL LOGIN authentication failed: UGFzXXX
```

I am using fail2ban 0.9.2-1 on Debian.

**Comment by blueyed** [comment]
See also 56e5821c.

**Comment by leeclemens** [comment]
The dovecot filter notes that it "Probably doesn't do dovecot sql/ldap backends properly", but obviously it would be good for it to.

I tweaked this a little based on the `auth_verbose_passwords` settings (I was using the default of no):

`failregex = ^%(__prefix_line)sauth: Info: sql\(\S+,<HOST>\): (Password mismatch|unknown user)( \((SHA1 of given password: [0-9a-f]{5,40}|given password: \w*)\))?$`

```
May 31 10:36:02 auth: Info: sql(nouser@example.com,1.2.3.4): unknown user
May 31 11:40:39 auth: Info: sql(validuser@example.com,1.2.3.4): Password mismatch
May 31 11:05:53 auth: Info: sql(validuser@example.com,1.2.3.4): Password mismatch (given password: badpassword)
May 31 11:03:53 auth: Info: sql(validuser@example.com.net,1.2.3.4): Password mismatch (SHA1 of given password: e92fba7ccbb2647fe9743219cd97a20486d3bd71)
```

There are some variations with auth, dovecot-auth, auth-worker out there too.

**Comment by leeclemens** [comment]
Regarding postfix/postfix-sasl, It may be better to create a seperate issue. The postfix-sasl filter works (and you said it works) and also blocks failed smtp auth attempts (as does the dovecot regex I provided above) for me. With the two jails blocking their respective service's ports, failed smtp auth results in fail2ban blocking both postfix and dovecot services (since postfix is using `smtpd_sasl_type = dovecot` in my case).

**Comment by blueyed** [comment]
@leeclemens 
Thanks!

Regarding postfix-sasl, it was an issue with using the wrong iptables chain (see https://github.com/fail2ban/fail2ban/issues/1060 for a suggestion to address this).

**Comment by ztjuh** [comment]
I'm trying to figure out what is wrong with my dovecot-sql-conf, trying to find: 
`Apr 30 12:09:40 Hostname dovecot: auth-worker(622071): sql(email,123.456.789.123): unknown user`

```
# Fail2Ban filter Dovecot authentication and pop3/imap server
#

[INCLUDES]

before = common.conf

[Definition]

_auth_worker = (?:dovecot: )?auth(?:-worker)?
_daemon = (?:dovecot(?:-auth)?|auth)

prefregex = ^%(__prefix_line)s(?:%(_auth_worker)s(?:\([^\)]+\))?: )?(?:%(__pam_auth)s(?:\(dovecot:auth\))?: |(?:pop3|imap)-login: )?(?:Info: )?<F-CONTENT>.+</F-CONTENT>$

failregex = ^%(__prefix_line)sauth-worker\(\d+\): (pam|sql)\(\S+,<HOST>\): unknown user\s*$
            <mdre-<mode>>

mdre-aggressive = ^(?:Aborted login|Disconnected)(?::(?: [^ \(]+)+)? \((?:no auth attempts|disconnected before auth was ready,|client didn't finish \S+ auth,)(?: (?:in|waited) \d+ secs)?\):(?: user=<[^>]*>,)?(?: method=\S+,)? rip=<HOST>(?:[^>]*(?:, session=<\S+>)?)\s*$

mdre-normal = 

mode = normal

ignoreregex = 

journalmatch = _SYSTEMD_UNIT=dovecot.service

datepattern = {^LN-BEG}TAI64N
              {^LN-BEG}
```

`sudo fail2ban-regex /var/log/mail.log /etc/fail2ban/filter.d/dovecot-sql.conf`: 
> Lines: 79735 lines, 0 ignored, 0 matched, 79735 missed
