### ISSUE TITLE
Multiple chains (INPUT+FORWARD; via intermediate chain) / PREROUTING?

### ISSUE THREAD

**Issue by blueyed** [fail2ban/fail2ban#1060]
I would like to use multiple chains (INPUT and FORWARD) by default, but
especially for the "recidive" jail.

I am trying the following now, where I use an intermediate chain
(`my-f2b-main-chain`), which is added as a first rule into INPUT and FORWARD
then:

    iptables -N my-f2b-main-chain
    iptables -A my-f2b-main-chain -j RETURN
    iptables -I INPUT -j my-f2b-main-chain
    iptables -I FORWARD -j my-f2b-main-chain

This chain then gets used for fail2ban, when both chains should get handled.

Does this make sense?
Can something like this get provived/shipped with fail2ban?

I've also thought about using the PREROUTING chain, but that might not make
sense, and then there seems to be no way currently to pass the '-t nat'
argument.
Although "chain = PREROUTING -t nat" might work?

**Comment by leeclemens** [comment]
This discussion may be better suited for the mailing list, since it's not really an issue with fail2ban (i.e. bug). Providing the action configuration you are using and the jail config, at a minimum, seem necessary to help further.

**Comment by blueyed** [comment]
It seems to be a common scenario, where you have the host route most traffic to containers (through iptable's FORWARD, using nat), but should block it at the front (INPUT).
fail2ban runs on the host and reads log output from the containers.

My jail config is pretty much the default for Debian, with several jails enabled via `jails.local`.

**Comment by leeclemens** [comment]
Like I said, more specific information is required to address your concern here (your information will not work with the default iptables action, and "pretty much the default" doesn't help anyone know how you have it configured). I'd suggest checking this out:
http://www.fail2ban.org/wiki/index.php/HOWTO_Seek_Help

Since this doesn't seem to be a bug per se, I'm going to close this issue.

**Comment by blueyed** [comment]
The relevant config is to change the default (or specific) chain to `my-f2b-main-chain` (instead of INPUT).
This was not meant to report a bug, but to discuss / suggest a new feature/action.
