### ISSUE TITLE
http://www.fail2ban.org/wiki/index.php/Fail2Ban is out of date

### ISSUE THREAD

**Issue by reikoNeko** [fail2ban/fail2ban#1061]
It's still the README.md file from 0.8.4 and needs to be updated to show that the python dependency is 2.4 (because decorators) as reflected in 0.8.14's readme file.

**Comment by leeclemens** [comment]
@yarikoptic, do you have control over the wiki?

**Comment by yarikoptic** [comment]
On Tue, 02 Jun 2015, Lee Clemens wrote:

>    @yarikoptic, do you have control over the wiki?

yes... will check it out/fix later on

majority of wiki though is available to anyone registered -- are you
registered?
-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by sebres** [comment]
Close now, because not really an issue (in sense of fail2ban here), and because we've the github-wiki now (that I'll currently prefer).
