### ISSUE TITLE
fail2ban.actions.action: ERROR, returned 200.

### ISSUE THREAD

**Issue by enoch85** [fail2ban/fail2ban#1064]
I've been googling this issue for a while now and I'm sure there is a simple answer but I can't find it.

Get this in my fail2banlog.log:

```
2015-06-03 23:03:37,286 fail2ban.actions.action: ERROR  ipset --create fail2ban-ssh-iptables-ipset4 iphash
iptables -I INPUT -p tcp -m multiport --dports ssh -m set --match-set fail2ban-ssh-iptables-ipset4 src -j REJECT --reject-with icmp-port-unreachable returne$
2015-06-03 23:03:37,288 fail2ban.actions.action: ERROR  ipset create fail2ban-ssh-iptables-ipset6 hash:ip timeout 600
iptables -I INPUT -p tcp -m multiport --dports ssh -m set --match-set fail2ban-ssh-iptables-ipset6 src -j REJECT --reject-with icmp-port-unreachable returne$
2015-06-04 02:23:08,490 fail2ban.actions.action: ERROR  ipset --create fail2ban-ssh-iptables-ipset4 iphash
iptables -I INPUT -p tcp -m multiport --dports ssh -m set --match-set fail2ban-ssh-iptables-ipset4 src -j REJECT --reject-with icmp-port-unreachable returne$
2015-06-04 02:23:08,505 fail2ban.actions.action: ERROR  ipset create fail2ban-ssh-iptables-ipset6 hash:ip timeout 600
iptables -I INPUT -p tcp -m multiport --dports ssh -m set --match-set fail2ban-ssh-iptables-ipset6 src -j REJECT --reject-with icmp-port-unreachable returne$

```

Is something wrong, or is it just a bad configuration? And if it's wrong - what should I change?

Thanks!

**Comment by leeclemens** [comment]
On 06/04/2015 04:02 PM, Daniel Hansson wrote:
> I've been googling this issue for a while now and I'm sure there is a simple answer but I can't find it.

It would be helpful to get some additional information (version of Fail2ban, system/platform, relevant fail2ban configs (your jail(s), custom fail2ban.local, jail.local, etc)).

>
> Get this in my fail2banlog.log:
>
> |2015-06-03 23:03:37,286 fail2ban.actions.action: ERROR  ipset --create fail2ban-ssh-iptables-ipset4 iphash
> iptables -I INPUT -p tcp -m multiport --dports ssh -m set --match-set fail2ban-ssh-iptables-ipset4 src -j REJECT --reject-with icmp-port-unreachable returne$
> 2015-06-03 23:03:37,288 fail2ban.actions.action: ERROR  ipset create fail2ban-ssh-iptables-ipset6 hash:ip timeout 600
> iptables -I INPUT -p tcp -m multiport --dports ssh -m set --match-set fail2ban-ssh-iptables-ipset6 src -j REJECT --reject-with icmp-port-unreachable returne$
> 2015-06-04 02:23:08,490 fail2ban.actions.action: ERROR  ipset --create fail2ban-ssh-iptables-ipset4 iphash
> iptables -I INPUT -p tcp -m multiport --dports ssh -m set --match-set fail2ban-ssh-iptables-ipset4 src -j REJECT --reject-with icmp-port-unreachable returne$
> 2015-06-04 02:23:08,505 fail2ban.actions.action: ERROR  ipset create fail2ban-ssh-iptables-ipset6 hash:ip timeout 600
> iptables -I INPUT -p tcp -m multiport --dports ssh -m set --match-set fail2ban-ssh-iptables-ipset6 src -j REJECT --reject-with icmp-port-unreachable returne$
>

Can you run `ipset version` and provide the output?

> |
>
> Is something wrong, or is it just a bad configuration? And if it's wrong - what should I change?

Not sure, would need to see your configuration before suggesting you change something :)

>
> Thanks!
>

**Comment by enoch85** [comment]
@leeclemens Thanks for your reply.

I can't provide the jails right now. But I did't change anything except changing jail.conf to jail.local and changed the jail.local and enabled "true" on those I wanted to be active.
```
root@en0ch:~# ipset version
The program 'ipset' is currently not installed. You can install it by typing:
apt-get install ipset
root@en0ch:~#
```

Do I need to install ipset as well to get it working?

#### Platform

Ubuntu Server 14.04

Fail2Ban v0.8.11 (Ubuntu Repo)

**Comment by leeclemens** [comment]
I suspect you are overriding the `action`, since the default, iirc, has been iptables for a long time.

From the log you appear to be trying to use `ipset`, but you do not have `ipset` installed (from the error you just posted).

`iptables-multiport` is the default, but ipset has some advantages to it. You can run `ipset version` again after installing it to confirm the protocol version and make sure you use the appropriate `action` (`iptables-ipset-proto4` or `iptables-ipset-proto6`) for your jail.

**Comment by enoch85** [comment]
@leeclemens Yes, that fixed it. Thanks!

**Comment by leeclemens** [comment]
@enoch85 glad to hear it :)  Beware if using iptables-ipset-proto6, I have encountered some issues in the latest version 0.9.2. Not sure if they were present in your version.
