### ISSUE TITLE
iptables-ipset-proto6: multiple issues

### ISSUE THREAD

**Issue by leeclemens** [fail2ban/fail2ban#1065]
In its current form, iptables-ipset-proto6 allows IPs to connect before the jail's `bantime` expires (when the jail is configured with a longer bantime than the default/action's default). This is a silent failure to protect the system and should be considered very serious, imho. (e.g. I told fail2ban to block an IP for 1 day, fail2ban ignored my config and told ipset to block the IP for 10 minutes. (1 day - 10 minutes) later fail2ban will tell ipset to ignore the IP which ipset may no longer care about. No error.)

Additionally, the action doesn't seem to start and stop cleanly given the simplest of test-cases (start, then stop).

---

1) The issue #540 most clearly described the biggest part of the underlying problem, but was closed.

It seems rational to expect the jail's `bantime` to be used by the action's `<bantime>` parameter in the commands.  Even if those are not the same, it seems even less rational to use a separate parameter of the same name in the action: https://github.com/fail2ban/fail2ban/blob/abd5984234dec44efe1f98c05d124501a60bb146/config/action.d/iptables-ipset-proto6.conf#L63.

2) When stopping fail2ban, multiple rules remain:

```
2015-06-04 20:57:18,335 fail2ban.action         [3191]: ERROR   iptables -D INPUT -p tcp -m multiport --dports ssh -m set --match-set f2b-sshd src -j DROP
ipset flush f2b-sshd
ipset destroy f2b-sshd -- stderr: 'iptables: Bad rule (does a matching rule exist in that chain?).\nipset v6.11: Set cannot be destroyed: it is in use by a kernel component\n'
```

```
# iptables -L INPUT | grep f2b
DROP       tcp  --  anywhere             anywhere            multiport dports ssh match-set f2b-sshd src 
DROP       tcp  --  anywhere             anywhere            multiport dports ssh match-set f2b-sshd src 
DROP       tcp  --  anywhere             anywhere            multiport dports ssh match-set f2b-sshd src 
DROP       tcp  --  anywhere             anywhere            multiport dports ssh match-set f2b-sshd src 
DROP       tcp  --  anywhere             anywhere            multiport dports ssh match-set f2b-sshd src 
DROP       tcp  --  anywhere             anywhere            multiport dports ssh match-set f2b-sshd src 
DROP       tcp  --  anywhere             anywhere            multiport dports ssh match-set f2b-sshd src 
DROP       tcp  --  anywhere             anywhere            multiport dports ssh match-set f2b-sshd src 
DROP       tcp  --  anywhere             anywhere            multiport dports ssh match-set f2b-sshd src 
DROP       tcp  --  anywhere             anywhere            multiport dports ssh match-set f2b-sshd src 
DROP       tcp  --  anywhere             anywhere            multiport dports ssh match-set f2b-sshd src 
DROP       tcp  --  anywhere             anywhere            multiport dports ssh match-set f2b-sshd src
```

This occurs after a single start/stop:

```
# service fail2ban stop
Stopping fail2ban:                                         [  OK  ]
```

```
2015-06-04 21:33:32,780 fail2ban.action         [11527]: ERROR   iptables -D INPUT -p tcp -m multiport --dports ssh -m set --match-set f2b-sshd src -j DROP
ipset flush f2b-sshd
ipset destroy f2b-sshd -- stdout: ''
2015-06-04 21:33:32,780 fail2ban.action         [11527]: ERROR   iptables -D INPUT -p tcp -m multiport --dports ssh -m set --match-set f2b-sshd src -j DROP
ipset flush f2b-sshd
ipset destroy f2b-sshd -- stderr: 'iptables: Bad rule (does a matching rule exist in that chain?).\nipset v6.11: Set cannot be destroyed: it is in use by a kernel component\n'
2015-06-04 21:33:32,780 fail2ban.action         [11527]: ERROR   iptables -D INPUT -p tcp -m multiport --dports ssh -m set --match-set f2b-sshd src -j DROP
ipset flush f2b-sshd
ipset destroy f2b-sshd -- returned 1
2015-06-04 21:33:32,781 fail2ban.actions        [11527]: ERROR   Failed to stop jail 'sshd' action 'iptables-ipset-proto6': Error stopping action
2015-06-04 21:33:32,781 fail2ban.jail           [11527]: INFO    Jail 'sshd' stopped
2015-06-04 21:33:32,782 fail2ban.server         [11527]: INFO    Exiting Fail2ban
```

```
# ipset list
Name: f2b-sshd
Type: hash:ip
Header: family inet hashsize 1024 maxelem 65536 timeout 600 
Size in memory: 16504
References: 1
Members:
# iptables -L -n | grep f2b
DROP       tcp  --  0.0.0.0/0            0.0.0.0/0           multiport dports 22 match-set f2b-sshd src 
```

---

iptables v1.4.7
ipset v6.11, protocol version: 6
Python 2.7.9
fail2ban 0.9.2.dev commit ab74a35b8acea5c7b9e2cd3d624b0b51851ea9de

**Comment by pgnd** [comment]
I've still see these same behaviors.

On restarts, I'm seeing no rescanning of logs at all.  Have to clear the iptables rules manually 1st, then restart.

The use of bantimes is confusing at best.  Some in jail.local, some in the action files, and in either case unpredictable behavior.  

In current form, ipsets in fail2ban are unusable; I've had to drop all rules back to much mre stable/predictable, iptables-multiport etc.

Of course, rule performance suffers as a result.

Need to take a closer look at fail2ban+ipsets here, and see if some sensible solution can be put together.

**Comment by yarikoptic** [comment]
@leeclemens : Was this issue anyhow addressed and I have missed that?

**Comment by leeclemens** [comment]
@yarikoptic I may have closed this by mistake, it has not been addressed that I am aware of.

**Comment by sebres** [comment]
No longer an issue, at least in the major branches in should be fixed now.
