### ISSUE TITLE
Error in FilterPyinotify callback: Failed to create a valid datetime record

### ISSUE THREAD

**Issue by TitovLab** [fail2ban/fail2ban#1066]
CentOS 6.6 2.6.32-504.16.2.el6.x86_64
Fail2ban 0.8.14-2.el6
In Fail2ban log many entries:
Error in FilterPyinotify callback: Failed to create a valid datetime record due to: day is out of range for month
In jail.conf backend set to auto.
Installed python-inotify-0.9.1-1.el6.noarch and gamin-0.1.10-9.el6.x86_6.
If you need additional information, please let me know.

**Comment by leeclemens** [comment]
Was there a stacktrace printed in the log?

**Comment by leeclemens** [comment]
There may be some malformed log line in your log that fail2ban is monitoring, or an unknown date pattern (is this a new setup, or had it been working?)

**Comment by TitovLab** [comment]
There is no stacktrace in the log.
Fail2ban monitor only 3 logs:
/var/log/secure (ssh-iptables)
/var/log/fail2ban.log (recidive)
/var/log/httpd/error_log (apache-auth)
I will check time of errors in FilterPyinotify if they match entries in these log files.
All works fine before May 20, no updates and configuration changes was near this date.

**Comment by TitovLab** [comment]
The problem was in Apache log.
OTRS helpdesk system write string "Invalid Date '2015-04-31 23:59:59'".
After removal of these lines FilterPyinotify error no longer occurs.
Are there any ways to avoid repeat of this error?

**Comment by leeclemens** [comment]
fail2ban needs to find the log line's timestamp data, if your custom application is printing arbitrary timestamps to a log fail2ban is monitoring, it's hard to say without more information. Have you provided the entire log line?

It's possible using an ignoreregex would avoid this, but I'd have to check the code to be sure. You can certainly test it out though.
