### ISSUE TITLE
processing old log entries, before new???

### ISSUE THREAD

**Issue by roos-it** [fail2ban/fail2ban#1069]
i think the approach and logics is totaly wrong with processing a log file from the start, and not practical at all!

Goal of fail2ban is to block abuse traffic. So if you have a big log file and you restart fail2ban or enable a jail with  fail2ban-client set smtp-auth-rbl idle off. You want immediate action, not have to wait 10 minutes before it finaly is at a current time.
This is very important in case you are tweaking entries or not having jails on by default. 
Having jails not on by default is very normal, because of the false positives it is sometimes better to enable jails in distributed brute force abuse situations.

The default approach is not to care about old entries, but start processing current ones those are most important.

**Comment by roos-it** [comment]
hahahah, fail2ban-client reload smtp-auth-rbl 

 PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
 7459 root      20   0  710m  24m 2124 S 99.7  2.4  12:18.57 fail2ban-server
 2917 root      20   0 13136 1296  948 R  1.0  0.1   0:00.01 top

starts processing again the log file from start?????

**Comment by sebres** [comment]
Agree, fell a few times already on it...

Meanwhile fail2ban saves the last position of log-file (since db support), but if it is too big or was rotated - it will indeed parse the whole file.
To remedy this, I have implemented half-interval-seek-scan inside of #716, that seeks to line with date (search using half-interval search algorithm), to start polling from it.

**Comment by roos-it** [comment]
why not just 'tail' the logs. These are some disadvantages of the current situation

- no immediate action
- lots of hosts can try passwords, before the botnet 'discovers' it is getting blocked
- incorrect logging of banning, you should include some timestamp when this was found in the log file, if it is not blocked 'realtime'
- incorrect handling of unbanning? can you imagine banning a host on tail -100000 and then unban it at tail -80000, totally useless processing. 
- do you 'spawn' ban processes, like with '&' for faster concurrent processing?


you have to make a decision if fail2ban is for blocking hosts at 'realtime' processing or if should process archived logs. Your current approach is not consistent with realtime. 

You can always make a flag process from last known history. That would be good having the realtime protection, and then concurrently process history.
