### ISSUE TITLE
systemd: Failed at step NAMESPACE spawning /usr/bin/fail2ban-client: No such file or directory

### ISSUE THREAD

**Issue by Swashy** [fail2ban/fail2ban#1073]
I cannot start the systemd fail2ban.service. When I try, I get this issue's title as an error upon investigating the PID through the journalctl _PID=<PID> command.
I am running arch linux with the latest updates (6/17/15) on a Linode VPS.

Following the advice of this older post: http://blog.laufeyjarson.com/2014/09/systemd-failed-at-step-namespace-spawning-operation-not-permitted/
I tried removing the /var/tmp symlink, and making a new directory, but it doesn't change the error.

Using the remount command did not work, but that may be because I apparently do not have a tempfs file device, and adding the tmpfs entry into /etc/fstab breaks my kernel. I'm not sure how or if my tmpfs directory is mounted in some other way.

Here are the error outputs, bold emphasis on the problem areas.

**systemctl status fail2ban**
>fail2ban.service - Fail2Ban Service
>   Loaded: loaded (/usr/lib/systemd/system/fail2ban.service; enabled; vendor preset: disabled)
>  Drop-In: /etc/systemd/system/fail2ban.service.d
>           `-capabilities.conf
>   Active: failed (Result: start-limit) since Wed 2015-06-17 10:33:57 EDT; 1min 48s ago
>     Docs: man:fail2ban(1)
> ** Process: 2458 ExecStart=/usr/bin/fail2ban-client -x start (code=exited, status=226/NAMESPACE)**

>Jun 17 10:33:57 swashyirc systemd[1]: **fail2ban.service: control process exited, code=exited status=226**
>Jun 17 10:33:57 swashyirc systemd[1]: Failed to start Fail2Ban Service.
>Jun 17 10:33:57 swashyirc systemd[1]: Unit fail2ban.service entered failed state.
>Jun 17 10:33:57 swashyirc systemd[1]: fail2ban.service failed.
>Jun 17 10:33:57 swashyirc systemd[1]: fail2ban.service holdoff time over, scheduling restart.
>Jun 17 10:33:57 swashyirc systemd[1]: start request repeated too quickly for fail2ban.service
>Jun 17 10:33:57 swashyirc systemd[1]: Failed to start Fail2Ban Service.
>Jun 17 10:33:57 swashyirc systemd[1]: Unit fail2ban.service entered failed state.
>Jun 17 10:33:57 swashyirc systemd[1]: fail2ban.service failed.
>Warning: fail2ban.service changed on disk. Run 'systemctl daemon-reload' to reload units.

**journalctl _PID=(pid#)**
>-- Logs begin at Mon 2015-06-08 12:00:48 EDT, end at Wed 2015-06-17 10:35:46 EDT. --
>Jun 17 10:33:57 swashyirc systemd[2458]: **Failed at step NAMESPACE spawning /usr/bin/fail2ban->client: No such file or directory**

**/usr/lib/systemd/system/fail2ban.sevice**
>[Unit]
>Description=Fail2Ban Service
>Documentation=man:fail2ban(1)
>After=network.target iptables.service firewalld.service
>
>[Service]
>Type=forking
>ExecStart=/usr/bin/fail2ban-client -x start
>ExecStop=/usr/bin/fail2ban-client stop
>ExecReload=/usr/bin/fail2ban-client reload
>PIDFile=/var/run/fail2ban/fail2ban.pid
>Restart=always
>
>[Install]
>WantedBy=multi-user.target

**Comment by Swashy** [comment]
So the problem was /etc/systemd/system/fail2ban.service/capabilities.conf. I inserted lines that I pulled directly from the archlinux wiki page: https://wiki.archlinux.org/index.php/Fail2ban

Namely, these lines:
>[Service]
>CapabilityBoundingSet=CAP_DAC_READ_SEARCH CAP_NET_ADMIN CAP_NET_RAW

>ReadOnlyDirectories=/
>ReadWriteDirectories=/var/run/fail2ban /var/lib/fail2ban /var/spool/postfix/maildrop /tmp

I had the last two directories modified to **/var/tmp** and **/var/log**. 
I've removed those two lines and added in /usr/bin/fail2ban-client as a read/write directory, but it still fails with the file.

**Comment by sebres** [comment]
If you can start it with `fail2ban-client start`, then the maintainer of archlinux made a bug somewhere in service round about.
If you can't start it also, so take a look on some errors in fail2ban.log.
You can also increase a verbosity through starting of fail2ban with `fail2ban-client -v -v start` to see some debug info, for example you can check some paths, may be wrong.

**Comment by cj3kim** [comment]
I can run fail2ban-client start. Sebres is right. The maintainer of archlinux made a bug somewhere.

**Comment by sebres** [comment]
I will close it, because seems to be archlinux issue, so long as nothing other known.

**Comment by mindstormer12** [comment]
@Swashy Did you ever figure out which combination of paths in capabilities.conf for `ReadWriteDirectories=` fixes the issue?

**Comment by vindicatorr** [comment]
I'll add my penny to this issue.
I submitted the (non-bug?) to archlinux: https://bugs.archlinux.org/task/52892
The short of it is the missing file or directory relates to the directories one would add in the "capabilities.conf" file.
If you don't use postfix, or the path isn't the same as what was mentioned in the wiki (/var/spool/postfix/maildrop), adjust that path accordingly (remove it if you don't use postfix).

The same goes for the path "/var/log/fail2ban". The log file path default to "/var/log", so you probably want to change to "logtarget = /var/log/fail2ban/fail2ban.log" in "/etc/fail2ban/fail2ban.conf"
