### ISSUE TITLE
fail2ban cannot handle hundreds log entries

### ISSUE THREAD

**Issue by squidetc** [fail2ban/fail2ban#1074]
Hello. Could you please help (or advice) us to solve problem with fail2ban and varnish logs. 

Problem: We configured and tested using fail2ban-regex filter for banning 403 varnish responses - it working fine. When we moved it to production - it was working fine as well, but after 6-13 hours it just stopped to ban IPs using provided filter. After restart - it goes back and start work property for next 6-24 hours and stuck again.... Other filter working without problems (ssh). 

What we try to do: 
- Changed  backed to polling,auto,gamin,pyinotify
- Redirect all 403 responses to separate file (it increasing ban time to 20-30 hours but stuck after...)
- Update fail2ban to latest version (0.8.13)
Nothing helped.... 

Additional info:
OS: Ubuntu 12.04
Varnish writing about 800 log entries per second.
 
Could you please advise how to improve banning in such case? 
Logs sample:
####################
109.96.146.77           -       2015-06-10 12:03:12 +0300       196             0.002336        miss    403     GET     http://somesite.com/linkname   "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36"
109.96.146.77           -       2015-06-10 12:03:12 +0300       196             0.000458        hit     403     GET     http://somesite.com/linkname   "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36"
109.96.146.77           -       2015-06-10 12:03:13 +0300       196             0.000330        hit     403     GET     http://somesite.com/linkname   "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36"
109.96.146.77           -       2015-06-10 12:03:13 +0300       196             0.000486        hit     403     GET     http://somesite.com/linkname   "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36"
109.96.146.77           -       2015-06-10 12:03:13 +0300       196             0.000412        hit     403     GET     http://somesite.com/linkname   "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36"
109.96.146.77           -       2015-06-10 12:03:13 +0300       196             0.000524        hit     403     GET     http://somesite.com/linkname   "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36"
109.96.146.77           -       2015-06-10 12:03:13 +0300       196             0.000415        hit     403     GET     http://somesite.com/linkname   "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36"
109.96.146.77           -       2015-06-10 12:03:13 +0300       196             0.000420        hit     403     GET     http://somesite.com/linkname   "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36"
109.96.146.77           -       2015-06-10 12:03:13 +0300       196             0.000426        hit     403     GET     http://somesite.com/linkname   "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36"
####################

Filter config:
####################
[Definition]
failregex = ^<HOST>.*miss\s*403\s*GET.*"$

ignoreregex =
####################

**Comment by leeclemens** [comment]
Can you perform a load test in development/staging to rule out any system related changes inadvertently introduced?

The latest version of fail2ban is 0.9., I would suggest upgrading in general.
What action are you using for this jail? How did you determine fail2ban stopped banning IPs?
What backend are you using? I would suggest pyinotify if supported or at least gamin, polling should be a last resort/fallback.

It looks like none of those log lines should match your regex (the quote after GET.) ? Are those examples of logs that should result in an IP being banned? Assuming the quote was removed when you sanitized them, there is still only one "miss" logline. Does fail2ban-regex match them?

Can you explain in more technical terms what "stuck" means in your case?

**Comment by squidetc** [comment]
Hello. Thanks for reply. 
* Can you perform a load test in development/staging to rule out any system related changes inadvertently introduced?

We try to enable debug logs but it writes billions of logs per minute, so we just  moved to INFO log level. 

* What action are you using for this jail? 
```
[varnish_403]
enabled = true
filter = varnish403
action   = iptables-multiport[name=varnish_403,port="80,443",protocol=tcp]
logpath = /mnt/ramfs/varnish/access.log
maxretry = 10
findtime = 20
bantime = 800
```
* How did you determine fail2ban stopped banning IPs?
* Can you explain in more technical terms what "stuck" means in your case?

First we are checking **fail2ban.log** to see if filter are working fine:
```
fail2ban.actions[18581]: WARNING [varnish_403] Ban 80.246.130.243
fail2ban.actions[18581]: WARNING [varnish_403] Ban 2.54.1.55
fail2ban.actions[18581]: WARNING [varnish_403] Unban 80.246.130.243
fail2ban.actions[18581]: WARNING [varnish_403] Unban 2.54.1.55  
```
On next day we saw that there is  no Ban logs for this filter at all. So we just opened **varnish access.log** to check. **Then we found hundreds of IPs that are matching varnish403 rule but wasn't BANNED** (IPs are missing in fail2ban.log and rotated logs). Then we additionally copied this logs to separate file and run **fail2ban-regex** and it worked - it showed that this IPs are matching rules and should be banned but fail2ban didn't handle that. 

* What backend are you using?

I've already wrote about it - we were using **polling,auto,gamin,pyinotify**  (each one for couple days) but it didn't helped.  

* It looks like none of those log lines should match your regex (the quote after GET.) ? Are those examples of logs that should result in an IP being banned? Assuming the quote was removed when you sanitized them, there is still only one "miss" logline. Does fail2ban-regex match them?

Sorry, I didn't see that github didn't recognized Asterisk symbol. Here is the rule:
```
[Definition]
failregex = ^<HOST>.*miss\s*403\s*GET.*"$

ignoreregex =
```

You suggest to enable DEBUG logs to check why it doesn't BAN ?

**Comment by yarikoptic** [comment]
was the log file rotated meanwhile?

**Comment by leeclemens** [comment]
You seemed concerned about the frequency of writes to the log file (varnish/nginx/whatever), so I was asking if you've performed a load test in another environment. That doesn't necessarily have anything to do with enabling DEBUG in fail2ban - but load testing your system (of which fail2ban is a part).

Unless I'm not reading this correctly, there is only one log line with "miss" in it. And the `failregex` is checking for the "miss" lines...not the "hit" lines, correct?

Since you didn't specify a backed, but rather listed them all, I just wanted to clarify. Did you see the same behavior after similar amount of time with fail2ban being "stuck"?

@yarikoptic brings up a good point; log rotation did cause issues with pyinotify, but that should have been fixed before 0.9. I wouldn't guess polling would be affected by rotation, but it is certainly worth checking if your system rotated logs meanwhile.

**Comment by squidetc** [comment]
> You seemed concerned about the frequency of writes to the log file (varnish/nginx/whatever), so I was asking if you've performed a load test in another environment. That doesn't necessarily have anything to do with enabling DEBUG in fail2ban - but load testing your system (of which fail2ban is a part).

Ok, understood. We will test it on less loaded environment to check. 

> Unless I'm not reading this correctly, there is only one log line with "miss" in it. And the failregex is checking for the "miss" lines...not the "hit" lines, correct?

Sorry, I've taken wrong piece of huge log - filter are only for cache miss:
```
79.180.1.6              -       2015-06-22 08:55:08 +0300       351             0.002937        miss    403     GET     http://somecached-page.com/path     "Yes Streamer 1.5.7.2 Indexer (powered by TVersity)"
79.180.1.6              -       2015-06-22 08:55:08 +0300       352             0.003122        miss    403     GET     http://somecached-page.com/path    "Yes Streamer 1.5.7.2 Indexer (powered by TVersity)"
79.180.1.6              -       2015-06-22 08:55:08 +0300       341             0.003066        miss    403     GET     http://somecached-page.com/path -       "Yes Streamer 1.5.7.2 Indexer (powered by TVersity)"
79.180.1.6              -       2015-06-22 08:55:08 +0300       336             0.002173        miss    403     GET     http://somecached-page.com/path      -       "Yes Streamer 1.5.7.2 Indexer (powered by TVersity)"
79.180.1.6              -       2015-06-22 08:55:08 +0300       337             0.002924        miss    403     GET     http://somecached-page.com/path    -       "Yes Streamer 1.5.7.2 Indexer (powered by TVersity)"
79.180.1.6              -       2015-06-22 08:55:09 +0300       349             0.003435        miss    403     GET     http://somecached-page.com/path -     "Yes Streamer 1.5.7.2 Indexer (powered by TVersity)"
79.180.1.6              -       2015-06-22 08:55:09 +0300       342             0.004087        miss    403     GET     http://somecached-page.com/path        -     "Yes Streamer 1.5.7.2 Indexer (powered by TVersity)"
```
> was the log file rotated meanwhile?
> @yarikoptic brings up a good point; log rotation did cause issues with pyinotify, but that should have been fixed before 0.9. I wouldn't guess polling would be affected by rotation, but it is certainly worth checking if your system rotated logs meanwhile.

Logs are rotated frequently. We will disable rotation and monitor it for couple days. 
Thank you for advise.

**Comment by yarikoptic** [comment]
On Sun, 21 Jun 2015, squidetc wrote:
>      was the log file rotated meanwhile?
>      @yarikoptic brings up a good point; log rotation did cause issues with
>      pyinotify, but that should have been fixed before 0.9. I wouldn't guess
>      polling would be affected by rotation, but it is certainly worth
>      checking if your system rotated logs meanwhile.

>    Logs are rotated frequently. We will disable rotation and monitor it for
>    couple days.

any peculiarity of the file system (what is the python, kernel, FS and
their versions) where the logs reside?

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by squidetc** [comment]
OS: **Ubuntu 12.04**
Kernel: **3.8.0-26-generic**
Log are stored in **ramfs**

**Comment by davidfavor** [comment]
Keep in mind what happens during log rotation, as this just bit me too.

For every file rotation, good to also add - service fail2ban restart - to run after file rotation, so new files are picked up + old files are dropped from tracking.

Likely there's a "better" way to do this, as doing a bunch of - service fail2ban restarts - back to back is inefficient + does the job.

**Comment by leeclemens** [comment]
I would recommend restarting fail2ban as least times as makes sense for your environment - same rule with any service (and OS). If you need to restart frequently, there is probably something else wrong or lacking with your system or application.

**Comment by squidetc** [comment]
Thanks for reply. After long testing on systems with different loading the best way was to redirect 403 logs to <b>separate file</b> and use <b>pyinotify</b> backend. 
Thank you all for advise and tips.

**Comment by leeclemens** [comment]
Thanks for the update, glad to hear you found a solution!
