### ISSUE TITLE
The good config

### ISSUE THREAD

**Issue by MisterM74** [fail2ban/fail2ban#1084]
hello
The good config for this error in the logs.
warning: unknown[XXX.XX.XXX.XXX]: SASL LOGIN authentication failed: UGFzc3dvcmQ6

Mz

**Comment by sebres** [comment]
???
Which service? Which log? Will you create new filter? Are you looking for a filter?

I found exact this line within postfix-sasl filter. See https://github.com/fail2ban/fail2ban/search?utf8=%E2%9C%93&q=SASL+LOGIN
Can be also pam-generic...

Please talk in full sentences next time... (and reopen this issue if was not answered)
