### ISSUE TITLE
apache-botsearch isn't detecting anything

### ISSUE THREAD

**Issue by joey102030** [fail2ban/fail2ban#1086]
I'm using fail2ban version 0.8.14, Apache 2.2.24 on Centos 6.5

I'm definitely pointing to the correct error log, and I've set the webroot variable correctly.

The error log format is this:
[Fri Jul 03 00:39:58 2015] [error] [client 5.64.233.252] File does not exist: /home/account/public_html/phpmyadmin

I can only assume the issue is with _apache_error_client in apache-common.conf, but how do I go about diagnosing and fixing this?

**Comment by leeclemens** [comment]
First, anyone would need some configs to see how your system is setup. This type of question is probably better suited for the mailing list, and please see the link below for more info on how to get help: 
http://www.fail2ban.org/wiki/index.php/HOWTO_Seek_Help
