### ISSUE TITLE
Enhancement Request: fail2ban seek to end of log files, rather than reading them

### ISSUE THREAD

**Issue by davidfavor** [fail2ban/fail2ban#1087]
I'm using - Fail2Ban v0.8.14 - so maybe this has been fixed + I see no mention in changelogs (that I found) or open issues, so defining problem here.

In the case of systems which produce large log files every day (multi-gigabyte files), fail2ban can take many minutes to get to end of files.

This occurs on servers hosting several high traffic sites.

When fail2ban starts, it must vie for CPU + I/O resource. I've seen situations where fail2ban can run at 100% CPU usage for better part of an hour, then go to low CPU usage.

My guess is this CPU usage indicates fail2ban is reading all logs. If I remove all apache logs (for all sites) + restart, fail2ban begins processing new rules instantly, based on fail2ban logs of block/unblock messages.

If fail2ban did a seek to the end of log files, rather than reading each record, initial startup time required to begin banning new IPs would be very fast.

Thanks for your consideration of this enhancement request.

**Comment by leeclemens** [comment]
@davidfavor that would work if fail2ban only needed to process new requests, but when it first starts it needs to check back `findtime` to determine if any bans need to be made from previous logs (presumably while fail2ban was stopped).

Persistent storage was added in 0.9, which includes log file position for fail2ban to start processing at after a restart. I'd upgrade to 0.9.2 and see if you still see resource consumption or performance issues.

**Comment by davidfavor** [comment]
Great. I'll do upgrade + look into "persistent storage" + retest.

Thanks!

**Comment by leeclemens** [comment]
Sounds good. As long as your Python has sqlite, it should be enabled by default; feel free to comment or send the mailing list questions you run into.

If you still run into performance/resource problems, feel free to re-open this issue on github.

**Comment by davidfavor** [comment]
Thanks!

**Comment by davidfavor** [comment]
I've installed latest fail2ban from git + problem has greatly improved.

Thanks!

**Comment by davidfavor** [comment]
I was wrong. Reason fail2ban started quickly was I changed apache logrotate from weekly to daily + did a logrotate -dv /etc/logrotate.d/apache2 which created an empty access.log file.

After running for a few minutes access.log is now only 69M + fail2ban once started has been running @ 100% CPU for nearly an hour now.

Also trying to do a - service fail2ban stop - does not work, as the Debian/Ubuntu init script tries using fail2ban-client to stop the server.

It appears fail2ban-client stop requests are ignored, until fail2ban-server finishes its first read of all log files, so only recourse is to - kill -9 - on the fail2ban-server + remove the dangling socket file.

So fail2ban seems to be unusable for large log files.

This is very ugly for systems running 1000s of LXC containers, where a single fail2ban-server ingesting all logs in all containers is far better than an instance of fail2ban-server running in all containers.

Unsure how to proceed.

**Comment by davidfavor** [comment]
This isn't a CPU resource problem either. This is a multi-core system running at a load of around 2.5 where...

One CPU is 100% running fail2ban-server for over an hour trying to get it started.

One CPU is 100% running fail2ban-regexp running timing resource check against one filter file.

One CPU is 50%ish running normal load.

Five CPUs idle.

**Comment by sebres** [comment]
I see you're a best test candidate for my new feature branch #1116. I'm really interested, if you could try it out (I mean with the big log files and interim stop/start). Thx in advance.

**Comment by davidfavor** [comment]
Finally had to kill both fail2ban-server + fail2ban-regexp as they both had run 4+ hour on a 70M logfile + never finished processing the file.

This is git version 0.9.2-93-g7a011fc which is latest.

**Comment by davidfavor** [comment]
I've looked at #1116 + it appears this code is in the latest branch. There appear to be no options to give fail2ban-server to utilize this feature.

There is a --fast in fail2ban-testcases + no --fast in fail2ban-server, so let me know how to test this + I'll let you know.

Till fail2ban can handle large logs I'm just going cobble together a fail2ban-esque server using inotail + perl, to start at end of log files, rather than reading them.

This is a requirement for high traffic sites.

Some machines I'm hosting are running 100K uniques/hour + the volume of logging requires a log camper like fail2ban to start instantly.

**Comment by kwirk** [comment]
@davidfavor Fail2ban version 0.9.x comes with a feature to start at the end of log files. (See man page, _logpath_ option: https://www.mankier.com/5/jail.conf#Jail_Configuration_File%28s%29_%28jail.conf%29)

Have you tried this?

**Comment by davidfavor** [comment]
Adding 'tail' to the logpath entries did the trick.

Thanks!

**Comment by sebres** [comment]
Nice, that it works with 'tail' :)

About the #1116 - I mean, it contains a feature "seek to time", so search for a `now - findtime` with "half-interval-search" algorithm, what should be very fast. Additionally this branch should be several times faster as original (for example search of failures 2x faster etc.).
