### ISSUE TITLE
badips.py and smtp.py removal

### ISSUE THREAD

**Issue by leeclemens** [fail2ban/fail2ban#1100]
It doesn't seem like anything uses these two modules, sitting in the config/action.d directory.

The badips action uses curl directly.

Other than tests, I see no occurrence of either class (BadIPsAction and SMTPAction) anywhere else in the repo - but I wanted to get a second opinion before removing them in case I'm missing some use-case. Are these just obsolete bits of code sitting in /config?

**Comment by yarikoptic** [comment]
Those are complete actions definitions.  badips even have a jail within jail.conf.  smpt.py is more of an example which is referenced in the jail.conf.5 manpage etc.  So nothing to remove imho (thus closing)

**Comment by leeclemens** [comment]
@yarikoptic The only instances of "badips" in jail.conf are comments and the assignment of the action `action_badips` - of which there are no other occurrences in the repo. But I recognize they're there for ppl to utilize in their custom/local configs (like overloaded method signatures), so thank you for responding (and closing).
