### ISSUE TITLE
Improvement: iptables CHAIN name length warning and multiple log file support

### ISSUE THREAD

**Issue by imran-uk** [fail2ban/fail2ban#1105]
I am using `Version: 0.8.6-3wheezy3` on Debian Wheezy

My jails were not working in that the iptables rules were not being executed, on looking in the fail2ban log I saw this:

    2015-07-06 18:18:16,273 fail2ban.actions.action: ERROR  iptables -N fail2ban-<jail name>

On trying the `iptables -N` command on the command line I got an error saying the rule name must be <29 chars! It appear that fail2ban takes the jailname and prefixes it with `fail2ban-`

So maybe an improvement is on fail2ban start-up to check for jailnames which take it over the limit and show an error on STDERR.

Another improvement I'd like to see is the ability to define multiple logpaths (or multiple files for the logpath param) per jail. I think it is common for a filter to apply against multiple files. eg. I want to block `POST xmlrpc.php` Wordpress DoS attacks in Apache and have multiple Apache vhosts running Wordpress. Rather than define a jail for each vhost/logpath I'd like to define one jail `wp-xmlrpc` and have the associated filter work against multiple access logs. In fact I think you should support multiple filters for one jail perhaps.

Lastly - thanks very much for fail2ban!

**Comment by sebres** [comment]
1. Pro rata a solution for this will #980 (because, it should also check an error at start).
I would not like the solution with fixed constraint of jail-name to 29-8 chars (because it depending on platform, version etc.)

2. Multiple log files are already supported (don't ask me about the version, just check changelog).

P.S. Next time please describe always one problem in one issue.

**Comment by leeclemens** [comment]
Also, version 0.9 changed jail names to use "f2b-" prefix, which saves some space. You can also keep long jail names and define the chain name separately in your action config. So upgrade (always a recommendation) or at least defined your own shorter names.

**Comment by yarikoptic** [comment]
Altogether I would close this issue as  "closed a while back".  As for the version in wheezy -- unikely any changes would get uploaded to wheezy (unless grave issue fix).  Backports are available from NeuroDebian. Cheers!
