### ISSUE TITLE
RFC: Remove bin/fail2ban-server

### ISSUE THREAD

**Issue by leeclemens** [fail2ban/fail2ban#1107]
Since `fail2ban-client start` is the preferred way (and possibly the only supported way) of starting fail2ban, does it make sense to keep the "script" `bin/fail2ban-server`? It seems to add confusion and ambiguity into how to start fail2ban.

Removal of `bin/fail2ban-server` would obviously require other updates, which could subsequently resolve the issues exposed by #951. If `bin/fail2ban-server` were a module, it may be simpler to control in a Pythonic way. Thoughts?

**Comment by yarikoptic** [comment]
overall -- YES -- we should move all the functionality from bin/fail2ban-* tools under fail2ban/ module and then only have "entry points" created by setuptools.  Example, see https://github.com/datalad/datalad/blob/master/setup.py#L30
which upon installation (or ```pip install -e .```) for development "deployment" would create such scripts as 

```
$> cat venv-test/bin/datalad 
#!/home/yoh/proj/datalad/datalad/venv-test/bin/python2
# EASY-INSTALL-ENTRY-SCRIPT: 'datalad==0.0.1.dev','console_scripts','datalad'
__requires__ = 'datalad==0.0.1.dev'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('datalad==0.0.1.dev', 'console_scripts', 'datalad')()
    )
```

```
$> cat venv-test/bin/git-annex-remote-dl+archive 
#!/home/yoh/proj/datalad/datalad/venv-test/bin/python2
# EASY-INSTALL-ENTRY-SCRIPT: 'datalad==0.0.1.dev','console_scripts','git-annex-remote-dl+archive'
__requires__ = 'datalad==0.0.1.dev'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('datalad==0.0.1.dev', 'console_scripts', 'git-annex-remote-dl+archive')()
    )
```

Additional obscure benefit (besides being able to unit-test code of those scripts) of such setup would be ability to easily install fail2ban on Windows ! ;-) (it would generate e.g. fail2ban.exe )

**Comment by leeclemens** [comment]
Yes, moving all bin/fail2ban- to Python modules would be next step, agreed :)
