### ISSUE TITLE
Expose filter regex group captures in actions

### ISSUE THREAD

**Issue by ar45** [fail2ban/fail2ban#1110]
I think that if regular expressions are searched and we have already parsed all the data and captured groups, why aren't those available in the action commands.  It would be really useful so that one can do very complex actions and analytics.

**Comment by yarikoptic** [comment]
very logical!  the only gotchas I  foresee is possible shading of those groups with  identically named  variables in action definitions
 care to send a  pr  if one of @fail2ban/developers  hacked it all up  during breakfast?

**Comment by sebres** [comment]
I've already implemented it in my own 0.10th derivat... 
Will try to rebase it.
