### ISSUE TITLE
<ip>, <time> and <failures> not replaced in action

### ISSUE THREAD

**Issue by AstashovAndrey** [fail2ban/fail2ban#1115]
Hello

Fail2Ban see changes in the log to react to them. Starts the specified action, but does not change the settings. No one can tell why?

jail.conf
>[SERVICE]
>#==============================
>enabled  = true
>
>findtime = 3600
>maxretry = 6
>filter   = SERVICE
>logpath  = /var/log/service/log.log
>bantime  = 86400
>
>action   = iptables[name="SERVICE", protocol="tcp", port="6654"]

Action SERVICE
>...
>actioncheck = /etc/fail2ban/action.d/iptables.sh "check" "`<name>`" "`<ip>`" "`<protocol>`" "`<port>`" "`<time>`" "`<failures>`"
>...

Change only the values that I have clearly indicated in the config SERVICE

Fail2Ban log
>2015-07-15 17:34:58,428 fail2ban.actions[16741]: WARNING [SERVICE] Ban 12.34.56.78
>2015-07-15 17:34:58,429 fail2ban.actions.action[16741]: DEBUG   /etc/fail2ban/action.d/iptables.sh "check" "SERVICE" "`<ip>`" "tcp" "6654" "`<time>`" "`<failures>`"

Please help with the decision. Thanks.

Fail2Ban v0.8.13

**Comment by yarikoptic** [comment]
I guess we don't pass any ip or time into actioncheck since it can be ran before any command so but necessarily would have any ip associated etc.if you need to run it when banning, run in actionban

On July 15, 2015 7:48:17 AM EDT, AstashovAndrey <notifications@github.com> wrote:
>Hello
>
>Fail2Ban see changes in the log to react to them. Starts the specified
>action, but does not change the settings. No one can tell why?
>
>jail.conf
>>[SERVICE]
>>#==============================
>>enabled  = true
>>
>>findtime = 3600
>>maxretry = 6
>>filter   = SERVICE
>>logpath  = /var/log/service/log.log
>>bantime  = 86400
>>
>>action   = iptables[name="SERVICE", protocol="tcp", port="6654"]
>
>Action SERVICE
>>...
>>actioncheck = /etc/fail2ban/action.d/iptables.sh "check" "`<name>`"
>"`<ip>`" "`<protocol>`" "`<port>`" "`<time>`" "`<failures>`"
>>...
>
>Change only the values that I have clearly indicated in the config
>SERVICE
>
>Fail2Ban log
>>2015-07-15 17:34:58,428 fail2ban.actions[16741]: WARNING [SERVICE] Ban
>12.34.56.78
>>2015-07-15 17:34:58,429 fail2ban.actions.action[16741]: DEBUG  
>/etc/fail2ban/action.d/iptables.sh "check" "SERVICE" "`<ip>`" "tcp"
>"6654" "`<time>`" "`<failures>`"
>
>Please help with the decision. Thanks.
>
>Fail2Ban v0.8.13
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/fail2ban/fail2ban/issues/1115

-- 
Sent from a phone which beats iPhone.
