### ISSUE TITLE
Add support for nftables

### ISSUE THREAD

**Issue by mrueg** [fail2ban/fail2ban#1118]
It would be great if fail2ban could add support for nftables. [1]
Maybe it is even possible to replace all iptables calls with a corresponding nftables call making all actions switchable between both implementations?

[1] http://netfilter.org/projects/nftables/

**Comment by leeclemens** [comment]
Interesting, just glossed over the main page...do you have any info about what distros ship it? or replace {ip,ip6}tables with it? Seems to be geared for backwards compatibility, should fail2ban even care which underlying libs/infrastructure are used?

**Comment by mrueg** [comment]
I don't know which distributions ship it by default, but it's available for many distributions:
https://packages.debian.org/search?keywords=nftables
https://admin.fedoraproject.org/pkgdb/package/nftables/
https://wiki.gentoo.org/wiki/Nftables
https://wiki.archlinux.org/index.php/Nftables

**Comment by pfactum** [comment]
+1 for the feature request.

I've tried to adapt existing iptables fail2ban configs, but the obstacle is that nftables doesn't (currently, as they state in docs) allow removing specific rule using rule definition (only using handle number). I guess I may workaround it with some script that converts rule into handle, but that is cumbersome.

**Comment by am1github** [comment]
@pfactum 
Any news?

I try to port iptables-allports.conf to nftables.conf in Gentoo.

actionban/actioncheck seems working fine, but actionunban needs to remove rules over handles - that a kind of difficult (workaround)

**Comment by pfactum** [comment]
@ambiente1
No news, I've ended up with writing script that parses handles, but that is not the proper solution, so I've given up.

**Comment by ambiente1** [comment]
@pfactum 
Okay, looking into the documentation of nftables, they wrote:
>### Note: There are plans to support rule deletion by passing:
>% nft delete rule filter output ip saddr 192.168.1.1 counter
>
>**but this is not yet implemented. So you'll have to use the handle to delete rules until that feature is implemented.**

[Nftables WIKI - Simple rule management - Removing rules](http://wiki.nftables.org/wiki-nftables/index.php/Simple_rule_management#Removing_rules)

**Comment by ambiente1** [comment]
Ok tested many things on Gentoo using nftables and find out a working solution for me. :+1:

```
# Fail2Ban configuration file
#
# Block IPs over nftables chain
#
# Author: Alexander Meinhardt <hello@ambiente.one>
#
#

[Definition]

# Option:  actionstart
# Notes.:  command executed once at the start of Fail2Ban.
# Values:  CMD
#
actionstart =

# Option:  actionstop
# Notes.:  command executed once at the end of Fail2Ban
# Values:  CMD
#
actionstop =

# Option:  actioncheck
# Notes.:  command executed once before each actionban command
# Values:  CMD
#
actioncheck =

# Option:  actionban
# Notes.:  command executed when banning an IP. Take care that the
#          command is executed with Fail2Ban user rights.
# Tags:    See jail.conf(5) man page
# Values:  CMD
#
actionban = if [[ ! $(nft list table ip filter | grep '<ip>') ]]; then nft insert rule ip filter blacklist ip saddr <ip> counter drop; fi

# Option:  actionunban
# Notes.:  command executed when unbanning an IP. Take care that the
#          command is executed with Fail2Ban user rights.
# Tags:    See jail.conf(5) man page
# Values:  CMD
#
actionunban = ID=$(nft list table ip filter -a | grep '<ip>' | cut -d " " -f 12); nft delete rule ip filter input handle ${ID}

[Init]
```

I separated all bans into a separate chain called **blacklist**. Edit yourself

Using kernel 4.0.5-gentoo and fail2ban-0.9.2.

PS: Don't know, why files with extension **.conf** are not possible to attach - anyway.

Cheers

**Comment by vodik** [comment]
Might be easier to setup a set and add and remove IPs into that: http://wiki.nftables.org/wiki-nftables/index.php/Sets

~~~bash
nft add set filter blackhole { type ipv4_addr\;}
nft add rule ip input ip saddr @blackhole drop
~~~

And then the rules are a matter of manipulating that set:

~~~
actionban = nft add element filter blackhole {<ip>}
actionunban = nft delete element filter blackhole {<ip>}
~~~

**Comment by sebres** [comment]
Was done in #1292, so I close this issue
