### ISSUE TITLE
Investigate possibilit to parametrize filters in jails

### ISSUE THREAD

**Issue by yarikoptic** [fail2ban/fail2ban#1120]
Ran into this originally in a recent PR: https://github.com/fail2ban/fail2ban/pull/1112#issuecomment-121396698 .  If we parametrize any filter definition in a jail, it fails some logic in the tests... very worth investigating and adjusting pass2allow-ftp jail to use smth like

```
filter = apache-pass[knocking_url="%(knocking_url)s"]
knocking_url = /secret
```

@szepeviktor interested to get hands dirty? ;)

**Comment by szepeviktor** [comment]
My hands are already dirty.

**Comment by szepeviktor** [comment]
Investigate possibilit**Y** to parametrize filters in jails

**Comment by szepeviktor** [comment]
- [ ] Detect kwargs
- [ ] Strip them
- [ ] Declare variables from kwargs

**Comment by sebres** [comment]
It is already possible a long time ago... Or I had not understood something in this issue?

If I create a jail looks like:
```
[test-knocking]
filter = apache-pass[knocking_url="%(knocking_url)s"]
knocking_url = /my-secret-url?foo&bar
enabled = true
```
As result we'll see:
```
['set', 'test-knocking', 'addfailregex', '^<HOST> - \\w+ \\[\\] "GET /my-secret-url?foo&bar HTTP/1\\.[01]" 200 \\d+ ".*" "[^-].*"$']
```

Changing of jail `pass2allow-ftp` in jail.conf has no effect in `samplestestcase.FilterSamplesRegex` at all, all tests passed...
```
[pass2allow-ftp]
# knocking_url variable must be overridden to some secret value in jail.local
knocking_url = /knocking/
filter       = apache-pass[knocking_url="%(knocking_url)s"]
```
