### ISSUE TITLE
Move all bin/fail2ban- functionality under fail2ban/cmdline/ module

### ISSUE THREAD

**Issue by yarikoptic** [fail2ban/fail2ban#1121]
And possibly rely on setuptools entrypoints mechanism to establish command line "scripts".

See #1107 for initial discussion

@sebres You don't carry substantial changes within bin/fail2ban- scripts do you?

**Comment by sebres** [comment]
Yes, but I think, this is not so problematic (because have few references). 
If that can wait - I'm be happy, if not - so what, that's bad luck.

**Comment by sebres** [comment]
done in 0.10-branch per #1413
