### ISSUE TITLE
Here is more information about <IP> plus one colon

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#1124]
Could we strip off the colon at the end?
It would be convenient to copy the IP by selecting it from the end.
But the colon is always there.

**Comment by yarikoptic** [comment]
could you please provide more specifics, since I am not sure what colon in what "setting" you are talking about here

**Comment by szepeviktor** [comment]
"Here is more information about" is in
https://github.com/fail2ban/fail2ban/blob/master/config/action.d/sendmail-whois-lines.conf#L26

It would be nice to be able to copy&paste the IP more easily.

**Comment by szepeviktor** [comment]
Don't you receive tons of these emails daily?

**Comment by yarikoptic** [comment]
What about just adding a space before ":"? PR

I have used to use that action but then found other ways to fill up my mailbox ;)

**Comment by szepeviktor** [comment]
The thing is I copy strings from the end towards the beginning.
If the string (IP) does not end at the end of the line then it takes extra effort to select it.

**Comment by szepeviktor** [comment]
On double-clicking the dot in the IP stops the selection.

**Comment by szepeviktor** [comment]
So I end up:
`fail2ban-client set jailname unbanip 46.119.125.167:`

**Comment by yarikoptic** [comment]
On Thu, 23 Jul 2015, Viktor Szépe wrote:

>    On double-clicking the dot in the IP stops the selection.

choose better terminal program (I use urxvt) or adjust your
*term.cutchars in .Xresources to get yourself more proficient with
cut/pasting ;)

**Comment by yarikoptic** [comment]
FWIW -- here is mine: 
http://git.onerussian.com/?p=etc/base.git;a=blob;hb=HEAD;f=.Xresources

**Comment by szepeviktor** [comment]
Horde + Firefox is my mail reader. It turned out there are two settings:
`layout.word_select.stop_at_punctuation` and `layout.word_select.eat_space_to_next_word`
So there is no fine-grained (char-by-char) control over double-click selection.

http://kb.mozillazine.org/Layout.word_select.stop_at_punctuation

**Comment by szepeviktor** [comment]
Done: https://github.com/fail2ban/fail2ban/pull/1128
