### ISSUE TITLE
not sending email with mutt

### ISSUE THREAD

**Issue by leo4183** [fail2ban/fail2ban#1125]
fail2ban 0.8.14 not sending email alerts using mutt under Centos 6.5 (mutt works normally in command line)

/etc/fail2ban/jail.conf:

    [ssh-iptables]
    enabled  = true
    filter   = sshd
    action   = iptables[name=SSH, port=ssh, protocol=tcp]
               mutt[name=SSH, dest=xxx@xxx.com]
    logpath  = /var/log/secure
    maxretry = 3

/etc/fail2ban/action.d/mutt.conf

    [Definition]

    # Option:  actionstart
    # Notes.:  command executed once at the start of Fail2Ban.
    # Values:  CMD
    #
    actionstart = echo "The jail <name> has been started successfully." | /usr/bin/mutt -F /root/.muttrc -s "[Fail2Ban] <name>: started on `uname -n`" <dest>

    # Option:  actionstop
    # Notes.:  command executed once at the end of Fail2Ban
    # Values:  CMD
    #
    actionstop = echo "The jail <name> has been stopped." | /usr/bin/mutt -F /root/.muttrc -s "[Fail2Ban] <name>: stopped on `uname -n`" <dest>

    # Option:  actioncheck
    # Notes.:  command executed once before each actionban command
    # Values:  CMD
    #
    actioncheck =

    # Option:  actionban
    # Notes.:  command executed when banning an IP. Take care that the
    #          command is executed with Fail2Ban user rights.
    # Tags:    See jail.conf(5) man page
    # Values:  CMD
    #
    actionban = echo "The IP <ip> has just been banned by Fail2Ban after <failures> attempts against <name>" | /usr/bin/mutt /root/.muttrc -s "[Fail2Ban] <name>: banned <ip> from `uname -n`" <dest>

    # Option:  actionunban
    # Notes.:  command executed when unbanning an IP. Take care that the
    #          command is executed with Fail2Ban user rights.
    # Tags:    See jail.conf(5) man page
    # Values:  CMD
    #
    actionunban =

    [Init]

    # Default name of the chain
    #
    name = default

**Comment by yarikoptic** [comment]
On Thu, 23 Jul 2015, leo4183 wrote:

>    fail2ban 0.8.14 is not sending email alerts using mutt under Centos 6.5.

>    /etc/fail2ban/jail.conf:
>    [ssh-iptables]
>    enabled = true
>    filter = sshd
>    action = iptables[name=SSH, port=ssh, protocol=tcp]
>    mutt[name=SSH, dest=xxx@xxx.com]

yikes... mutt is a mail client, and we have no such action... closing 

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by yarikoptic** [comment]
i,e, for "support" of custom obscure setups use mailing list -- there is enough of issues to figure out in stock fail2ban, besides figuring out what was the idea of attaching a console mail reader in the action
