### ISSUE TITLE
fail2ban not recognising journalmatch

### ISSUE THREAD

**Issue by cortopy** [fail2ban/fail2ban#1126]
For the filters `ssh-ddos` , `selinux-ssh`, `postfix-sasl` and `recidive`, my fail2ban log is showing:

`Jail started without 'journalmatch' set. Jail regexs will be checked against all journal entries, which is not advised for performance reasons.`

But the thing is they do have journalmatch defined in their corresponding filter files. They are core filters already provided by fail2ban and I've not modified them.

I'm a bit lost as to why the log says there is no journalmatch defined

**Comment by AlexanderSk** [comment]
Hi, i believe it has to do with this issue but i am not exactly positive.
https://github.com/fail2ban/fail2ban/issues/959
Try to place at each filter
backend  = polling
journalmatch =
This worked for me for recidive rule and all the httpd rules... btw postfix-sasl -sshd were working without it.

**Comment by sebres** [comment]
Try to dump your current config, to see which config files are affected ("Loading" in verbose mode) and which jails have really the journalmatch:
```bash
fail2ban-client -v -d | grep "journalmatch"
```
