### ISSUE TITLE
Managing Jails - support .d directories with customizations

### ISSUE THREAD

**Issue by beilber** [fail2ban/fail2ban#114]
Hello, I was doing research to see if it was possible to split the jails.conf into multiple files or have an include directory for managing jails but have had no such luck.

What I am currently trying to accomplish is having the ability to enable/disable jails with independent files so that I can enable a jail simply by putting that file in the include directory or something similar.  And vice versa, removing the file disables the jail.  If I can accomplish this it opens up the possibility of having packages for activating jails, which would be the end goal I am looking to achieve.

An example would be vsftpd-iptables disabled in jail.conf:

[vsftpd-iptables]
enabled  = false
......

However in jail.d we have a vsftpd-iptables.conf that would override the default with the following:

[vsftpd-iptables]
enabled  = true
......

This would work well with a package that drops a file in jails.d and when restarted f2b activates the jail and all the directives in the new file are used.  

Is this even possible or has someone accomplished something along these lines?

**Comment by spacecwoboy** [comment]
I'm interested in seeing a simple, working example of how to incorporate an external file to the ignoreip whitelist.  I've read the howto/READ.me, but didnt quite get the best grip of it.

Let's say I start with this:
- [x] The whitelist of IP Addresses /etc/fail2ban/jail.d/list_of_ipaddresses_to_Whitelist.txt
* 127.0.0.1/32
* some.domainname.us
* 192.168.0.0/16

I need to understand:
- [ ] Other configs required to reference "/etc/fail2ban/jail.d/list_of_ipaddresses_to_Whitelist.txt"
