### ISSUE TITLE
Regex for roundcube.conf in freebsd 10.1

### ISSUE THREAD

**Issue by edupinhata** [fail2ban/fail2ban#1140]
I found out that the regex for the filter ipfw.conf was not working in freebsd 10.1. 

I changed a little bit the regular expression as follow bellow and it works for me now.

failregex = ^\s*(\[\])?(.* IMAP Error)?: (FAILED login|Login failed) for .*? from <HOST>(\. .* in .*?/rcube_imap\.php on line \d+ \(\S+ \S+\))?$

**Comment by yarikoptic** [comment]
On Tue, 28 Jul 2015, edupinhata wrote:

> I found out that the regex for the filter ipfw.conf was not working in freebsd 10.1. 

> I changed a little bit the regular expression as follow bellow and it works for me now.

> failregex = ^\s*(\[\])?(.* IMAP Error)?: (FAILED login|Login failed) for .*? from <HOST>(\. .* in .*?/rcube_imap\.php on line \d+ \(\S+ \S+\))?$

your regexp looks like already behind what we have in master and to be
scheduled for 0.9.3 release.   what is the sample log line?

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by edupinhata** [comment]
I'm sorry, I wrote the wrong file. I changed the failregex from
filter.d/roundcube.conf.

ipfw.conf is working perfectly.

The log line that I'm receiving in roundcube is as the following:
[16-Jun-2015 17:15:59 +0000]: <c68h07au> IMAP Error: Login failed for
blueguardian from 192.168.56.103. Could not connect to localhost:143:
Connection refused in
/usr/local/www/apache24/data/roundcube/program/lib/Roundcube/rcube_imap.php
on line 198 (POST /roundcube/?_task=login?_task=login&_action=login)



On Tue, Jul 28, 2015 at 4:32 PM, Yaroslav Halchenko <
notifications@github.com> wrote:

>
> On Tue, 28 Jul 2015, edupinhata wrote:
>
> > I found out that the regex for the filter ipfw.conf was not working in
> freebsd 10.1.
>
> > I changed a little bit the regular expression as follow bellow and it
> works for me now.
>
> > failregex = ^\s*(\[\])?(.* IMAP Error)?: (FAILED login|Login failed) for
> .*? from <HOST>(\. .* in .*?/rcube_imap\.php on line \d+ \(\S+ \S+\))?$
>
> your regexp looks like already behind what we have in master and to be
> scheduled for 0.9.3 release. what is the sample log line?
>
> --
> Yaroslav O. Halchenko, Ph.D.
> http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
> Research Scientist, Psychological and Brain Sciences Dept.
> Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
> Phone: +1 (603) 646-9834 Fax: +1 (603) 646-1419
> WWW: http://www.linkedin.com/in/yarik
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fail2ban/fail2ban/issues/1140#issuecomment-125759409>.
>



-- 
Eduardo Pinhata

**Comment by yarikoptic** [comment]
this one is already caught -- just wait for a fresh release/upadte
```
$> PYTHONPATH=$PWD bin/fail2ban-regex "[16-Jun-2015 17:15:59 +0000]: <c68h07au> IMAP Error: Login failed for blueguardian from 192.168.56.103. Could not connect to localhost:143: Connection refused in /usr/local/www/apache24/data/roundcube/program/lib/Roundcube/rcube_imap.php on line 198 (POST /roundcube/?_task=login?_task=login&_action=login)"  co
nfig/filter.d/roundcube-auth.conf 

Running tests
=============

Use   failregex filter file : roundcube-auth, basedir: config
Use      single line : [16-Jun-2015 17:15:59 +0000]: <c68h07au> IMAP Erro...


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] ^\s*(\[\])?(\S+\s*(roundcube:)?\s*(<[\w]+>)? IMAP Error)?: (FAILED login|Login failed) for .*? from <HOST>(\. .* in .*?/rcube_imap\.php on line \d+ \(\S+ \S+\))?$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] Day(?P<_sep>[-/])MON(?P=_sep)Year[ :]?24hour:Minute:Second(?:\.Microseconds)?(?: Zone offset)?
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed [processed in 0.00 sec]
```

**Comment by edupinhata** [comment]
Okay. Thank you!

On Tue, Jul 28, 2015 at 5:04 PM, Yaroslav Halchenko <
notifications@github.com> wrote:

> this one is already caught -- just wait for a fresh release/upadte
>
> $> PYTHONPATH=$PWD bin/fail2ban-regex "[16-Jun-2015 17:15:59 +0000]: <c68h07au> IMAP Error: Login failed for blueguardian from 192.168.56.103. Could not connect to localhost:143: Connection refused in /usr/local/www/apache24/data/roundcube/program/lib/Roundcube/rcube_imap.php on line 198 (POST /roundcube/?_task=login?_task=login&_action=login)"  co
> nfig/filter.d/roundcube-auth.conf
>
> Running tests
> =============
>
> Use   failregex filter file : roundcube-auth, basedir: config
> Use      single line : [16-Jun-2015 17:15:59 +0000]: <c68h07au> IMAP Erro...
>
>
> Results
> =======
>
> Failregex: 1 total
> |-  #) [# of hits] regular expression
> |   1) [1] ^\s*(\[\])?(\S+\s*(roundcube:)?\s*(<[\w]+>)? IMAP Error)?: (FAILED login|Login failed) for .*? from <HOST>(\. .* in .*?/rcube_imap\.php on line \d+ \(\S+ \S+\))?$
> `-
>
> Ignoreregex: 0 total
>
> Date template hits:
> |- [# of hits] date format
> |  [1] Day(?P<_sep>[-/])MON(?P=_sep)Year[ :]?24hour:Minute:Second(?:\.Microseconds)?(?: Zone offset)?
> `-
>
> Lines: 1 lines, 0 ignored, 1 matched, 0 missed [processed in 0.00 sec]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fail2ban/fail2ban/issues/1140#issuecomment-125766687>.
>



-- 
Eduardo Pinhata
