### ISSUE TITLE
Fail2ban git fails to install from PKGBUILD on Arch Linux /var/run/ exists

### ISSUE THREAD

**Issue by AndrzejL-eu** [fail2ban/fail2ban#1142]
Hi there.

I wrote (re-wrote / modified / plagiarized...) PKGBUILD a while back:

http://pastebin.com/raw.php?i=5E4cpjNq

It used to work fine and sweet... but now:

[andrzejl@andrzejl fail2ban-git]$ makepkg -s -i ./
==> WARNING: Cannot find the sudo binary. Will use su to acquire root privileges.
==> Making package: fail2ban-git 0.9.2.r132.gc37009a-1 (Thu Jul 30 18:25:25 IST 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating fail2ban-git git repo...
Fetching origin
==> Validating source files with sha512sums...
    fail2ban-git ... Skipped
==> Extracting sources...
  -> Creating working copy of fail2ban git repo...
Switched to a new branch 'makepkg'
==> Starting pkgver()...
==> WARNING: A package has already been built, installing existing package...
==> Installing package fail2ban-git with pacman -U...
Password:
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) fail2ban-git-0.9.2.r132.gc37009a-1

Total Installed Size:  1.87 MiB
Net Upgrade Size:      0.03 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                                              [##########################################] 100%
(1/1) checking package integrity                                            [##########################################] 100%
(1/1) loading package files                                                 [##########################################] 100%
(1/1) checking for file conflicts                                           [##########################################] 100%
error: failed to commit transaction (conflicting files)
fail2ban-git: /var/run exists in filesystem
Errors occurred, no packages were upgraded.
==> WARNING: Failed to install built package(s).
[andrzejl@andrzejl fail2ban-git]$ 

The problem is that:

[root@andrzejl andrzejl]# ls --full /var/ | grep run
lrwxrwxrwx  1 root       root          11 2015-02-15 21:58:46.000000000 +0000 lock -> ../run/lock
lrwxrwxrwx  1 root       root           6 2015-02-15 21:58:46.000000000 +0000 run -> ../run
[root@andrzejl andrzejl]# 

/var/run is a symlink pointing to /run.

Anyone knows how to bite this thing?

Cheers.

Andrzej

**Comment by sebres** [comment]
I doubt, that this would be a thing of fail2ban... may be `python setup install`, but I don't see it...
Can you somehow debug this? I mean a more info about the error self.

**Comment by yarikoptic** [comment]
Theoretically it is the issue of the packaging helpers/infrastructure.  We just need to have /var/run/fail2ban, which is we initiate in our setup.py.  Since apparently arch tools then freak out (although again -- path /var/run/fail2ban is legit, just canonical would be /run/fail2ban) you can either patch setup.py or if your init script takes care about creating that directory -- just remove that creation completely.  But alternatively -- we could within setup.py resolve the path for /var/run and use what it resolves to as the target directory (so might end up in /run).  Let me cook up a PR quickly

**Comment by AndrzejL-eu** [comment]
Hi

Just tested the latest git code - issue persists.

Can you please help me with debugging / patching this?

Thanks in advance.

Andrzej

**Comment by yarikoptic** [comment]
@AndrzejL-eu "latest git code" -- is that from the PR #1142 or just current master (not yet patched)?  with the patch it might persist but message must be different

**Comment by AndrzejL-eu** [comment]
Apologies. I meant current master. I will figure out how to test PR #1142 repo and let you know...

Cheers.

Andrzej

**Comment by yarikoptic** [comment]
On Fri, 31 Jul 2015, AndrzejL wrote:

>    Apologies. I meant current master. I will figure out how to test PR #1142
>    repo and let you know...

fwiw if you use my ghpr
http://git.onerussian.com/?p=etc/bash.git;a=blob;f=.bash/bashrc/30_aliases_sh;hb=HEAD#l790

you could just 

ghpr co https://github.com/fail2ban/fail2ban/issues/1142
within your fail2ban git clone and end up in the pr-1142 branch which
has that pr merged into master

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by AndrzejL-eu** [comment]
Sorry but I cannot figure out how to add the pull request 1142 as a source= line in my PKGBUILD. Tried to get some help but failed so far. I am not abandoning this thread neither am I ignoring it - I just need more time to figure this stuff out... When I do - I will let you know how it went. It may not be "soon".

Cheers.

Andrzej

**Comment by AndrzejL-eu** [comment]
I tried this:

http://pastebin.com/raw.php?i=nNzt6Zwg

but it fails.

Any idea how to source= pull request 1142 in PKGBUILD?

Cheers.

Andrzej

**Comment by sebres** [comment]
just use as source this one:
https://github.com/yarikoptic/fail2ban/archive/bf-realpath-var-run-1142.tar.gz
or if you necessarily need git path - origin: https://github.com/yarikoptic/fail2ban.git, branch: bf-realpath-var-run-1142

**Comment by AndrzejL-eu** [comment]
I used the tar.gz - thanks a lot for that btw.

Packaging and installation worked so the original issue is fixed but:

http://pastebin.com/raw.php?i=GbipJYVc

I am guessing it has something to do with systemd upgrade to version 223...

[root@andrzejl andrzejl]# pacman -Q | grep systemd
libsystemd 223-1
systemd 223-1
systemd-sysvcompat 223-1
[root@andrzejl andrzejl]# 

So the 1142 will be added to master soonish right?

Should I close this issue and open another one that faces up the new challenge?

Cheers.

Andrzej
