### ISSUE TITLE
Fail2ban-git (PR 1142) systemd 223-1 Arch Linux issues

### ISSUE THREAD

**Issue by AndrzejL-eu** [fail2ban/fail2ban#1145]
Hello guys.

After fixing issue described here https://github.com/fail2ban/fail2ban/issues/1142 (thanks a lot for that by the way) and installing fail2ban-git on my Arch Linux machine I've noticed that its not starting properly.

http://pastebin.com/raw.php?i=GbipJYVc

I am guessing it has something to do with the new version of systemd:

[root@andrzejl andrzejl]# pacman -Q | grep systemd
libsystemd 223-1
systemd 223-1
systemd-sysvcompat 223-1
[root@andrzejl andrzejl]#

How do I make it usable again?

Please do not hesitate to ask for additional information. I will provide it if I will be able to.

Thanks in advance.

Cheers.

Andrzej

**Comment by yarikoptic** [comment]
On Fri, 31 Jul 2015, AndrzejL wrote:

>    Hello guys.

>    After fixing issue described here #1142 (thanks a lot for that by the way)
>    and installing fail2ban-git on my Arch Linux machine I've noticed that its
>    not starting properly.

>    http://pastebin.com/raw.php?i=GbipJYVc

>    I am guessing it has something to do with the new version of systemd:

>    [root@andrzejl andrzejl]# pacman -Q | grep systemd
>    libsystemd 223-1
>    systemd 223-1
>    systemd-sysvcompat 223-1
>    [root@andrzejl andrzejl]#


>    How do I make it usable again?

install systemd python bindings I guess

ERROR   Backend 'systemd' failed to initialize due to No module named 'systemd'

says that there is no systemd python module.

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by AndrzejL-eu** [comment]
[root@andrzejl andrzejl]# pacman -Ss systemd python
community/python2-systemd 221-1
    Python2 bindings for systemd
[root@andrzejl andrzejl]# pacman -S python2-systemd
resolving dependencies...
looking for conflicting packages...

Packages (2) python2-lxml-3.4.4-1  python2-systemd-221-1

Total Download Size:   1.17 MiB
Total Installed Size:  6.29 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages ...
 python2-lxml-3.4.4-1-i686                         757.0 KiB  1097K/s 00:01 [##########################################] 100%
 python2-systemd-221-1-i686                        436.4 KiB  1247K/s 00:00 [##########################################] 100%
(2/2) checking keys in keyring                                              [##########################################] 100%
(2/2) checking package integrity                                            [##########################################] 100%
(2/2) loading package files                                                 [##########################################] 100%
(2/2) checking for file conflicts                                           [##########################################] 100%
(2/2) checking available disk space                                         [##########################################] 100%
(1/2) installing python2-lxml                                               [##########################################] 100%
Optional dependencies for python2-lxml
    python2-beautifulsoup3: support for parsing not well formed HTML
    python-lxml-docs: offline docs
(2/2) installing python2-systemd                                            [##########################################] 100%
[root@andrzejl andrzejl]# 

Rebuilding the PR 1142.

Will let you know if it fixed it. Just installing the package and rebooting the fail2ban on its own didn't worked.

Cheers.

Andrzej

**Comment by AndrzejL-eu** [comment]
Nope... That didn't do it...

http://pastebin.com/raw.php?i=bvhvjGPX

Cheers.

Andrzej

**Comment by AndrzejL-eu** [comment]
Actually -  yarikoptic was right...

I used this: https://aur4.archlinux.org/packages/python-systemd/

and the issues are fixed... so I need the python systemd binding - just not the ones from the repository but newer ones from Arch Aur...

Cheers.

Andrzej
