### ISSUE TITLE
F2B not compatible with systemd 223?

### ISSUE THREAD

**Issue by aLostEngineer** [fail2ban/fail2ban#1150]
I'm running Arch Linux, and have been using fail2ban (0.9.2.1) successfully for a couple weeks. Restarted this morning after upgrading systemd to v223, and now I'm flooded with:

`fail2ban-client[2321]: ERROR  NOK: ("Failed to initialize any backend for Jail 'dovecot-sasl'",)`
`fail2ban-client[2321]: ERROR  NOK: ('dovecot-sasl',)`

I'm using `backend = systemd` and it seems to think that `systemd` is not a real backend. Also, it has stopped writing to `/var/log/fail2ban.log`. (The above errors are printed to systemd). This behavior started at the exact same time.

So it appears to completely break with systemd 223? I can't think of anything else it may be? It's been banning fine for a while, and now it just... doesn't do anything. For any of my jails.

EDIT: Downgraded to systemd 222, and f2b works again.

**Comment by sebres** [comment]
Can you provide an output of executing of the following code?
```bash
python -c 'from systemd import journal; print "OK"'
```
If it says OK, can you please test a loading of the systemd-filter:
```bash
## test fail2ban path is correct (fail2ban was installed properly):
python -c 'from fail2ban.server.filter import Filter; print "OK"'
## test fail2ban systemd-filter can be loaded:
python -c 'from fail2ban.server.filtersystemd import FilterSystemd; print "OK"'
```

**Comment by aLostEngineer** [comment]
With systemd 223
    # python -c 'from systemd import journal; print("OK")'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named 'systemd'

With systemd 222
    # python -c 'from systemd import journal; print("OK")'
    OK

Maybe it's something in my systemd python package?

**Comment by sebres** [comment]
<blockquote>Maybe it's something in my systemd python package?</blockquote>
Not maybe - unfortunately that is definitely. 

You can report a bug to maintainers of Arch Linux (or python systemd module). So long it's not fixed, just use previous systemd version, or another backend of fail2ban (ex.: polling, pyinotify, etc.)

Because I don't know how we can help here further, I will close this issue.

**Comment by sebres** [comment]
I have received a tip: you can try to reinstall (or rebuild) a python systemd module, after upgrading to new version of systemd, supposedly sometimes should help (wrong dependencies resp. evaluation of it).

**Comment by rumpelsepp** [comment]
It is an own module now: https://github.com/systemd/python-systemd
http://lists.freedesktop.org/archives/systemd-devel/2015-July/033443.html

**Comment by carteriii** [comment]
I realize this is a bit old, but I just hit a problem where running `python -c 'from systemd import journal; print("OK")'` would not work. I then found another post (https://www.shellandco.net/fail2ban-fakegooglebot-jail-bug/) which for me properly identified the problem as being python 2 vs. 3. For me, running this command worked: `python3 -c 'from systemd import journal; print("OK")'`

**Comment by trisweb** [comment]
Chiming in with a potential help for this issue in Debian 12 - it could be you simply need to install python3-systemd: `apt install python3-systemd` - or the equivalent for your distribution.

Potentially needs to be added as a dependency for the fail2ban package on Debian.

**Comment by sebres** [comment]
> Potentially needs to be added as a dependency for the fail2ban package on Debian.

No idea what is again wrong with the deb-package and whether it is not updated (debian was always and is still sluggish with the updates), but here is how it looks in current release:
- release in this repo:
https://github.com/fail2ban/fail2ban/blob/8902a2b884c4912d24221f3eda272c5de7bb0978/debian/control#L23
- debian release:
https://salsa.debian.org/python-team/packages/fail2ban/-/blob/master/debian/control?ref_type=heads#L24

**Comment by trisweb** [comment]
That would do the trick. Looks like it was fixed in this commit in Jan 2024: https://salsa.debian.org/python-team/packages/fail2ban/-/commit/47a2ffa95ac787382f439505a257468ea666d17d

However, I promise I `apt install fail2ban` on a fully updated Debian 12, and definitely did not get `python3-systemd` with it.

So I expect you're right about it never making it to the 12 release. I'll take this up with Debian if I find that's true. Thanks.
