### ISSUE TITLE
banning IPs after service restarts

### ISSUE THREAD

**Issue by leo4183** [fail2ban/fail2ban#1152]
environment: `RedHat 6.5`, `fail2ban 0.9.2-1.el6`

every time after `fail2ban` service restarted, some previously banned IPs in jail `ssh-iptables` (although they have been moved out of the jail before the restart) would be banned automatically.  have to manually lift those bans.  any thoughts?

**Comment by sebres** [comment]
It's not a bug, is a feature...

Fail2ban will restore active bans after restart (the bans having end of ban larger as now).

Newer version of fail2ban (0.10th) have additional functionality (resp. parameters) across reload/restart/unbanning:
```
fail2ban-client restart [--unban] [--if-exists] <JAIL>
    restarts the jail <JAIL> (alias for 'reload --restart ... <JAIL>')
fail2ban-client reload [--restart] [--unban] [--all]
    reloads the configuration without restarting of the server, 
    the option '--restart' activates completely restarting of affected jails, 
    thereby can unban IP addresses (if option '--unban' specified)
fail2ban-client reload [--restart] [--unban] [--if-exists] <JAIL>
    reloads the jail <JAIL>, or restarts it (if option '--restart' specified)
fail2ban-client unban --all
    unbans all IP addresses (in all jails and database)
fail2ban-client unban <IP> ... <IP>
    unbans <IP> (in all jails and database)
```
