### ISSUE TITLE
fail2ban not working after iptable restarted

### ISSUE THREAD

**Issue by leo4183** [fail2ban/fail2ban#1153]
environment: `Redhat 6.5`, `fail2ban 0.9.2-1.el6`

the working `fail2ban` service will be stopped (although the service status would remain `on`) after `iptables` service restarted

**Comment by yarikoptic** [comment]
there is 0.9.3 now, and amount of information provided is not sufficient to figure out anything.  See http://www.fail2ban.org/wiki/index.php/HOWTO_Seek_Help
