### ISSUE TITLE
fail2ban "rewritten" in PHP

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#1156]
I am missing fail2ban so much on cheap shared hosting that I've _rewritten_ it in PHP.

There are several kinds of banning (I call them methods, not actions)
- Apache RewriteMap + RewriteRule [F]
- Apache SetEnvIf + Deny
- CloudFlare API
- Respond with HTTP 403 (and no further banning)
- Nginx user config (TODO)
- Tarpit (and no further banning)
- WordPress plugin based

https://github.com/szepeviktor/wordpress-fail2ban/tree/master/miniban
- whitelist
- ban time
- unban
- etc.

Is it possible to add a link to it?

**Comment by sebres** [comment]
I'll close it because not really an issue...
If you want, you can add a new wiki-page with reference to your project to our [wiki](https://github.com/fail2ban/fail2ban/wiki) (you should have write permissions there).

**Comment by szepeviktor** [comment]
OK.
