### ISSUE TITLE
Validate cidr addresses in ignoreip list

### ISSUE THREAD

**Issue by dpash** [fail2ban/fail2ban#1158]
I've just spent a while trying to debug an issue with fail2ban not banning addresses. I tracked it down to the filter stopping somewhere in ipIgnoreIpList and it turned out to be the line 

    s[1] = long(s[1])

 The reason is because s[1] was "8,", because in my config I'd put 

    ignorelist = 127.0.0.1/8, 1.2.3.4

The comma in there threw the function and everything silently stopped. It would be useful to either accept comma separated lists or to validate the entries in that list and throw an error when there's a problem.

**Comment by sebres** [comment]
see https://github.com/fail2ban/fail2ban/issues/880#issuecomment-65794315
