### ISSUE TITLE
High Load & hundreds of Entries in iptables

### ISSUE THREAD

**Issue by virtualweb-at** [fail2ban/fail2ban#1163]
On one of my Servers i have a Load of ~0.70 - after stopping fail2ban the Load goes down to ~0.05
Ubuntu Server 15.04, f2b 0.9.1 from Repository

Then i figured out that in iptables all f2b Rules in the INPUT Chain are listed hundred times
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
DROP       all  --  **.**.**.**        0.0.0.0/0           
f2b-apache-bot_for_jce  tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 80,443
f2b-pureftpd  tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 21
f2b-apache-post-flood  tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 80,443
f2b-postfix-sasl  tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 25,465,587,220,993,110,995
f2b-dovecot  tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 110,995,143,993,587,465,4190
f2b-apache-shellshock  tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 80,443
f2b-apache-botsearch  tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 80,443
f2b-apache-overflows  tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 80,443
f2b-apache-auth  tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 80,443
f2b-sshd   tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 22

-> the Block above repeats 100 time, i think on each restart of fail2ban the same block is appended to the existing one instead of replacing it.

What could be the cause for this? I use the standard setup but enhanced the Chains in my jail.local with separate maxretry/bantime entries.

**Comment by yarikoptic** [comment]
Clues will be in the fail2ban.log

On August 19, 2015 4:37:11 PM CEST, "virtualweb.at online services" <notifications@github.com> wrote:
>On one of my Servers i have a Load of ~0.70 - after stopping fail2ban
>the Load goes down to ~0.05
>Ubuntu Server 15.04, f2b 0.9.1 from Repository
>
>Then i figured out that in iptables all f2b Rules in the INPUT Chain
>are listed hundred times
>Chain INPUT (policy ACCEPT)
>target     prot opt source               destination         
>DROP       all  --  **.**.**.**        0.0.0.0/0           
>f2b-apache-bot_for_jce  tcp  --  0.0.0.0/0            0.0.0.0/0        
>   multiport dports 80,443
>f2b-pureftpd  tcp  --  0.0.0.0/0            0.0.0.0/0           
>multiport dports 21
>f2b-apache-post-flood  tcp  --  0.0.0.0/0            0.0.0.0/0         
>  multiport dports 80,443
>f2b-postfix-sasl  tcp  --  0.0.0.0/0            0.0.0.0/0           
>multiport dports 25,465,587,220,993,110,995
>f2b-dovecot  tcp  --  0.0.0.0/0            0.0.0.0/0           
>multiport dports 110,995,143,993,587,465,4190
>f2b-apache-shellshock  tcp  --  0.0.0.0/0            0.0.0.0/0         
>  multiport dports 80,443
>f2b-apache-botsearch  tcp  --  0.0.0.0/0            0.0.0.0/0          
> multiport dports 80,443
>f2b-apache-overflows  tcp  --  0.0.0.0/0            0.0.0.0/0          
> multiport dports 80,443
>f2b-apache-auth  tcp  --  0.0.0.0/0            0.0.0.0/0           
>multiport dports 80,443
>f2b-sshd   tcp  --  0.0.0.0/0            0.0.0.0/0            multiport
>dports 22
>
>-> the Block above repeats 100 time, i think on each restart of
>fail2ban the same block is appended to the existing one instead of
>replacing it.
>
>What could be the cause for this? I use the standard setup but enhanced
>the Chains in my jail.local with separate maxretry/bantime entries.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/fail2ban/fail2ban/issues/1163

-- 
Sent from a phone which beats iPhone.

**Comment by virtualweb-at** [comment]
f2b starts, jails are getting created.
then it gives many errors like the one below. after that, the jails are created a second time. this happens on each restart of f2b. all jails are *appended* to iptables twice. on each start.

one of the errors is (SSHD but there are similar errors for the Stock Apache Jails):

2015-08-19 17:16:11,456 fail2ban.actions        [21777]: ERROR   Failed to execute ban jail 'sshd' action 'iptables-multiport' info 'CallingMap({'failures': 3, 'ipjailfailures': <function Actions.__checkBan.<locals>.<lambda> at 0x7fc15ed322f0>, 'ipfailures': <function Actions.__checkBan.<locals>.<lambda> at 0x7fc15ed32268>, 'matches': 'Aug 19 15:15:39 myhostname sshd[23100]: Failed password for root from 182.100.67.113 port 60965 ssh2\nAug 19 15:15:45 myhostname sshd[23106]: Failed password for root from 182.100.67.113 port 60213 ssh2', 'ip': '182.100.67.113', 'time': 1439997369.496184, 'ipmatches': <function Actions.__checkBan.<locals>.<lambda> at 0x7fc15ed321e0>, 'ipjailmatches': <function Actions.__checkBan.<locals>.<lambda> at 0x7fc15ed32048>})': need more than 0 values to unpack

Looks like the List isn't correct and has 0 Values. But why? Maybe because the \n between the 3 Logfile entries?

**Comment by yarikoptic** [comment]
ah -- missed that you are using 0.9.1 ... if you want that one fixed -- asked for support from ubuntu folks.  otherwise, try 0.9.3 (e.g. this .deb http://neuro.debian.net/debian-devel/pool/main/f/fail2ban/fail2ban_0.9.3-1~nd15.04+1_all.deb) and if persists, reopen/re-report.  Cheers

**Comment by virtualweb-at** [comment]
thanks, the duplicate entries in firewall are gone now with that version. but the "high" load is still present (around 1.3).
* when fail2ban is stopped, the load goes down to ~0.03
* each enabled filter generates about 0.20 more load
* htop says that fail2ban uses 2878M VIRT and 31420 RES
* the log files are not really big (the biggest has 5MB)

any tips how i can get that optimized?
