### ISSUE TITLE
recidive jail allowing udp through

### ISSUE THREAD

**Issue by johnfawcett** [fail2ban/fail2ban#1166]
If using the default iptables-allports in recidive, I've noticed a dangerous behaviour on my asterisk server. After the bans from the asterisk jail become recidive, fail2ban starts allowing udp traffic through again. The rules in the recidive chain don't include the protocol, but at startup the rule that defines the jump to the recidive chain seems to take tcp as a default, leaving udp not protected by the recidive jail at all.

If my reasoning is correct, in action.d/iptables-allports.conf the line that sets up the jump to the f2b-recidive chain should not include the protocol, but should be valid for all protocols.

that is

```
actionstart = <iptables> -N f2b-<name>
              <iptables> -A f2b-<name> -j <returntype>
              <iptables> -I <chain> -p <protocol> -j f2b-<name>
```

should become

```
actionstart = <iptables> -N f2b-<name>
              <iptables> -A f2b-<name> -j <returntype>
              <iptables> -I <chain> -j f2b-<name>
```

The corresponding change should be done in actionstop else firewall rules we be left around after stopping and start

```
actionstop = <iptables> -D <chain> -p <protocol> -j f2b-<name>
             <iptables> -F f2b-<name>
             <iptables> -X f2b-<name>
```

should become

```
actionstop = iptables -D <chain> -j f2b-<name>
             iptables -F f2b-<name>
             iptables -X f2b-<name>
```

**Comment by sebres** [comment]
You can simply add `protocol = all` for recidive jail in your `jail.local`, that will right away work for iptables action:

```
[recidive]
protocol = all
enabled = true
```

**Comment by arnold-b** [comment]
Hello, 

sorry. i want to do the same but if i try 
protocol = all 

it don´t have any function
ip tables will be still only call chain on tcp

thanks arnold
