### ISSUE TITLE
openSUSE: Failing testExecuteTimeoutWithNastyChildren 

### ISSUE THREAD

**Issue by weberhofer** [fail2ban/fail2ban#1171]
In openSUSE's build environment I see the following error:

[   29s] + ./fail2ban-testcases-all --no-network
[   29s] Testing using /usr/bin/python2.7
[   29s] Fail2ban 0.9.3 test suite. Python 2.7.8 (default, Sep 30 2014, 15:34:38) [GCC]. Please wait...
[  111s] ........................s............................F...........................................................................................................................................................................................
[  111s] ======================================================================
[  111s] FAIL: testExecuteTimeoutWithNastyChildren (fail2ban.tests.actiontestcase.CommandActionTest)
[  111s] ----------------------------------------------------------------------
[  111s] Traceback (most recent call last):
[  111s]   File "./fail2ban/tests/actiontestcase.py", line 226, in testExecuteTimeoutWithNastyChildren
[  111s]     RuntimeError, CommandAction.executeCmd, 'bash %s' % tmpFilename, timeout=.1)
[  111s] AssertionError: RuntimeError not raised
[  111s] 
[  111s] ----------------------------------------------------------------------
[  111s] Ran 241 tests in 82.260s
[  111s] 
[  111s] FAILED (failures=1, skipped=1)
[  111s] E: Failed with  /usr/bin/python2.7
[  111s] error: Bad exit status from /var/tmp/rpm-tmp.N5gSeV (%check)
[  111s] 
[  111s] 
[  111s] RPM build errors:
[  111s]     Bad exit status from /var/tmp/rpm-tmp.N5gSeV (%check)

**Comment by yarikoptic** [comment]
seems to be another remification of #1155 with a detailed analysis.  I only wonder indeed now why it passes reliably on Debians - will look into it soon, ideally after I manage to replicate it (may be it would replicate in opensuse's docker container...)

**Comment by weberhofer** [comment]
Closed this issue this issue has been fixed with #1155. The test is now correctly running on all current openSUSE and SUSE versions. Thank you for fixing it!
