### ISSUE TITLE
fail2ban failing on lines with many (10.000+) characters

### ISSUE THREAD

**Issue by mrosic** [fail2ban/fail2ban#1173]
We had obscure database errors with roundcube and the errors were over 10.000 characters in a single line. The resulting file was 150MB and fail2ban never finished reading that file, not even after 650 CPU hours. During those 650 CPU hours fail2ban also didn't ban anybody because apparently it never finished starting.

I used fold -w 100 on the file, restarted fail2ban and it finished reading the file in less than 2 CPU Minutes.

I suggest that fail2ban only reads the first 500 characters (or whatever) of each line and then goes to the next line AND/OR shows an error message when it notices lines with an obscene amount of characters.

PS
It would be interesting to see whether one could force roundcube (or other programs, for that matter) to create such errors on-demand. In that case one could remotely disable fail2ban and brute-force away at the server.

**Comment by yarikoptic** [comment]
On Fri, 28 Aug 2015, mrosic wrote:

>    I suggest that fail2ban only reads the first 500 characters (or whatever)
>    of each line and then goes to the next line AND/OR shows an error message
>    when it notices lines with an obscene amount of characters.

Many regexes require end of the line anchoring, so just trimming the
logline for all jails might lead  to injection attacks -- if those lines
didn't actually contain any relevant to be matched entries (did
they?), we better be just skipping those.  But again I think it should
be an option per jail.

**Comment by mrosic** [comment]
They did not contain relevant entries. And I agree, this should be a per jail option.

**Comment by sebres** [comment]
Additionally me interested a question - why it hangs, because independent of new option exists or not - it should process such lines (possible a little bit slower, but not endless). Possible we have a not optimal regexp here, and I think that are a (non greedy) regexp parts like `.*?`.

Additionally I think this filter resp. jail expect an new `ignoreregex` rule.
Can you provide a pair examples or at least some common begin of such lines?

As regards a new option:
Per jail or not, can be controlled within DEFAULT. If it will be added (uncommented) inside default, so it applies to all jails, otherwise it can be (re)defined for single jail.
So we can add an option `maxchars`, here is a config example:
```
# "maxchars_mode" specified the mode to process lines longer as "maxchars_len" characters:
# crop: truncate line (add a new line) and try to match this line.
# ignore: ignore lines longer as N characters
maxchars_mode = ignore

# A maximum line length "maxchars_len" to be matched (if "ignore") or truncated (if "crop").
maxchars_len = 500

# "maxchars" contains combined formula to be used for special processing of long lines (see above)
maxchars = %(maxchars_mode)s %(maxchars_len)s
```

BTW: we should check that all filters don't contain some non conditional non greedy regexp's. That's really not good idea to use such regexp for log matching.

**Comment by mrosic** [comment]
This is an example of the lines that cause fail2ban to break:
[25-Jun-2014 13:19:15 +0200]: DB Error: [1062] Duplicate entry '292-INBOX' for key 1 (SQL Query: INSERT INTO cache_thread (user_id, mailbox, data, changed) VALUES ('292', 'INBOX', 'TzoxOToicmN1YmVfcmVzdWx0X3RocmVhZCI6NDp7czoxMToiACoAcmF3X2RhdGEiO3M6MjUwNDE6IjUwIDUzIDk2N34xOjk2OH4yOjk3[...]

This is the regex that we use:
failregex = .*IMAP Error: Login failed for .* from <HOST>\S+

**Comment by sebres** [comment]
Hm, strange. Gone to think...
BTW why not the `failregex` of standard roundcube filter? It is really only this regexp?
Can you provide please a excerpt of config dump for your jail? I mean output of:
```bash
# fail2ban-client -d | grep <jail>.*regex
fail2ban-client -d | grep roundcube.*regex
```

**Comment by yarikoptic** [comment]
and just to make sure -- what is the version of fail2ban and on which system and what are entries in fail2ban.log at DEBUG level (pretty much following http://www.fail2ban.org/wiki/index.php/HOWTO_Seek_Help

**Comment by mrosic** [comment]
@sebres 
root@xyz ~ $ fail2ban-client -d | grep roundcube.*regex
['set', 'roundcubemail', 'addfailregex', '.*IMAP Error: Login failed for .* from <HOST>\\S+']

@yarikoptic 
Fail2Ban v0.8.6
We've patched roundcube so the long error messages are gone. I'll see if I can give you the output of DEBUG on Monday, will have to copy back the old, dangerous logfiles first.

**Comment by yarikoptic** [comment]
for 0.8.6 I would say we shouldn't bother trying to dig it out... may be for 0.8.14, ideally for 0.9.3 -- too many things got changed since that ancient version.  Is there a chance you could try any of those?

**Comment by sebres** [comment]
@yarikoptic agree, but I will not remove "grave" as long as not clear, that this does not occur in the new version also, because may be vulnerable.
Python self? I mean any old version on CentOS that may hangs on some expr/string?

**Comment by yarikoptic** [comment]
I would've (if had time) created a unittest which would use aforementioned example regex and huge line (verbatim).  If passes in current version -- cool and close... such issue wasn't reported before since 0.8.6 so unlikely to occur or was already addressed.

**Comment by mrosic** [comment]
Here comes the output of debug. This is as far as fail2ban gets, nothing more is being logged and nobody is being banned, just 100% CPU usage.
2015-09-14 10:52:24,832 fail2ban.filter : DEBUG  Processing line with time:1437259542.0 and ip:XXX
2015-09-14 10:52:24,832 fail2ban.filter : DEBUG  Ignore line since time 1437259542.0 < 1442220744.83 - 600
2015-09-14 10:52:24,833 fail2ban.filter : DEBUG  Processing line with time:1437259543.0 and ip:XXX
2015-09-14 10:52:24,833 fail2ban.filter : DEBUG  Ignore line since time 1437259543.0 < 1442220744.83 - 600
2015-09-14 10:52:24,836 fail2ban.filter : DEBUG  Processing line with time:1437259550.0 and ip:XXX
2015-09-14 10:52:24,841 fail2ban.filter : DEBUG  Ignore line since time 1437259550.0 < 1442220744.84 - 600
2015-09-14 10:52:24,841 fail2ban.filter : DEBUG  Processing line with time:1437259551.0 and ip:XXX
2015-09-14 10:52:24,844 fail2ban.filter : DEBUG  Ignore line since time 1437259551.0 < 1442220744.84 - 600
2015-09-14 10:52:24,847 fail2ban.filter : DEBUG  Processing line with time:1437259552.0 and ip:XX
2015-09-14 10:52:24,848 fail2ban.filter : DEBUG  Ignore line since time 1437259552.0 < 1442220744.85 - 600

Now the funny thing is that the ip address from the last line is from a non-problematic log file with short lines. The offending line that causes fail2ban to break is from another file and the offending line doesn't even have an ip address. So fail2ban isn't even telling us what file/line is causing it to break.

**Comment by sebres** [comment]
1437259552 is "2015-07-19 00:45:52", so too old (almost 2 months) - no wonder it bans nothing.
Still v.0.8.6? 
Because, I doubt that v.0.9 will process such old file (if already processed).

**Comment by sebres** [comment]
@yarikoptic What's about new filter options `filterregex` and `preregex` (to specify in filter or direct in jail).

1) Option `filterregex` can be used to modify (also truncate) the log lines:
```
maxlen = 200
filterregex = ^(.{%(maxlen)s}).*$ \1
```
Used on bord something like:
```python
re.sub(r'^(.{10}).*$', r'\1', 'very very very long text')
```
Benefit would be not trimming only, but also opportunity to do it targeted, if for example it should be trimmed after known mark or if the log line is very dynamical (impossible using the fixed length). 

For example something like:
```
maxlen = 200
filterregex = ^(.*?(?:FAILED login|Login failed) for .*? from HOST.{%(maxlen)s}).*$ \1...
```

Here is an py-example:
```python
re.sub(
  r'^(.*?(?:FAILED login|Login failed) for .*? from HOST.{20}).*$',  r'\1...', 
  '[datetime] server anything else ... Login failed for USER from HOST : hier may be very very very long text'
)
# result:
'[datetime] server anything else ... Login failed for USER from HOST : hier may be very ...'
```
---
2) Additionaly we can introduce another one option like `preregex` as counterpart to `ignoreregex`, that will pre-match with shorter common regex, to determine the most of the time more complexer `failregex` should be used at all (as high-performance positive filter to ignore all not-matched lines).
With other words, search failure only in lines, that are match `preregex`. Example:
```
preregex = \s(?:(?:FAILED|Failed) login|Login failed) for\s
failregex = ^\s*(\[\])?(%(__hostname)s\s*(roundcube:)?\s*(<[\w]+>)? IMAP Error)?: (FAILED login|Login failed) for .*? from <HOST>(\. .* in .*?/rcube_imap\.php on line \d+ \(\S+ \S+\))?$
            ^\[\]:\s*(<[\w]+>)? Failed login for [\w\-\.\+]+(@[\w\-\.\+]+\.[a-zA-Z]{2,6})? from <HOST> in session \w+( \(error: \d\))?$
```
Proposals for better name as `preregex`?
