### ISSUE TITLE
Manual banning with custom expiration

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#1174]
I'd like to have iptables rules with custom expiration.
Now I use a chain called `MYATTACKER` and a small shell script:
https://github.com/szepeviktor/debian-server-tools/blob/master/tools/deny-ip.sh
But is provides no expiration mechanism.

Could fail2ban expire non-uniform (all ports, HTTP only, SMTP only etc.) iptables rules?

**Comment by sebres** [comment]
> Could fail2ban expire

fail2ban does not expire bans via iptables or another action, lastly it will execute an unban-action if time of ban exceeded (it removes an iptable entry created in ban-action).
So you need to rewrite banning part of your script as action, create an jail(s), add this action to this jail(s). And in your script you should call `fail2ban-client set <jail> banip <ip>` to ban it and then it will be unbanned automatically if configured ban time was reached.

PS. currently we don't have ipranges (if I correct understood your script).

**Comment by szepeviktor** [comment]
Thank you. It suites my needs.
Do you plan to add IP range support?

**Comment by sebres** [comment]
> Do you plan to add IP range support? 

We can't get around, at the latest for good implementation of IPv6.
So yes.
