### ISSUE TITLE
Prevent unbanning IP with non-zero traffic

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#1175]
Iptables has packet counter also in DENY rules. Is it possible to skip unbanning IP-s with non-zero pocket counter?
And restart bantime.

**Comment by sebres** [comment]
A controversial decision: if some "good" user-ip will be banned and he will try again to communicate inside the ban time, his ban will be "prolonged".

But at the moment, the scenario to consider counter in deny, would be to write such IPs by means of iptables using something like `iptables -A LOGGING -m limit --limit NN/min -j LOG --log-prefix "IPTables-Dropped: " --log-level ...` and write a custom filter to ban it with a custom jail and longer bantime (I will recommend hier a heigher maxretry as for original jail self).

I have already such filter on some server of me, must search through my config directories...

**Comment by szepeviktor** [comment]
Thank you.
Writing log to a file and another jail seems to be an overhead.
I try first a home made shell script to do all these (this and https://github.com/fail2ban/fail2ban/issues/1174).

**Comment by szepeviktor** [comment]
- sigle IP or IP range
- selectable ports: ALL, SMTP, HTTP, SSH
- manual ban: default=1d, 1m, permanent
- ban from a list
- manual unban
- cron job unban: expired & zero traffic

**Comment by szepeviktor** [comment]
For anyone who is interested:
https://github.com/szepeviktor/debian-server-tools/blob/master/security/myattackers.sh
