### ISSUE TITLE
reload command empty current ban list

### ISSUE THREAD

**Issue by gerbier** [fail2ban/fail2ban#1182]
'reload' is not ''restart' : fail2ban-client reload should not empty current ban list.
Maybe could be 
- save current ban list
- stop
- start
- restore ban list

**Comment by sebres** [comment]
But exactly that does it... Although the bans will not be saved (all this are in the table `bans` of sqlite database of fail2ban), but all still active bans (timeOfBan + banTime < now) schould be restored after restart.
Which version of fail2ban did you mean? Is database active?

**Comment by gerbier** [comment]
I'm using fail2ban-0.8.13-5, from my linux distribution repository (Mageia 5). But I may backport a 0.9.

**Comment by sebres** [comment]
The scenario about I wrote affects v0.9, since the sqlite database was introduced. So, try it.
