### ISSUE TITLE
IP info HTML app

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#1202]
Would you link/use/something a **customizable** HTML IP info app?
http://szepeviktor.github.io/ip-info/?62.210.206.219

Detects your IP: http://szepeviktor.github.io/ip-info/
I've written it for the fail2ban action email.

Opens any website. Sites with X-FRAME-OPTIONS opens outside. Also searches text lists.
https://github.com/szepeviktor/ip-info

**Comment by sebres** [comment]
closed as not real issue...

**Comment by szepeviktor** [comment]
Yes.
