### ISSUE TITLE
Fail2ban and jetty server - recognition of request log timestamp 

### ISSUE THREAD

**Issue by 1technophile** [fail2ban/fail2ban#1208]
Hello,

I was trying to read the request log (ncsa format) coming from a jetty server, here is a sample line:
192.168.1.255 -  -  [02/oct./2015:00:15:19 +0200] "line to monitor"
Unfortunately fail2ban doesn't recognize the timestamp natively due to the dot after the month, so as to make it recognizing this date format I had to change the datedetector.py by adding:

                        # Jetty format [02/oct./2015:00:15:19 +0200]
                        template = DateStrptime()
                        template.setName("Day/MONTH./Year:Hour:Minute:Second")
                        template.setRegex("\d{2}/\S{3}./\d{4}:\d{2}:\d{2}:\d{2}")
                        template.setPattern("%d/%b./%Y:%H:%M:%S")
                        self.__templates.append(template)

This add is ok, nevertheless sometimes the month is with 4 letters, example "Sept" and in this case this modification doesn't work.

Some ideas

Regards

**Comment by sebres** [comment]
Just replace `\S{3}` with `\S{3,4}`.
BTW if after month is really a point it should be escaped `\.`, because otherwise the regexp `.` will match any char.

**Comment by 1technophile** [comment]
Hello,

Thanks for your help

nevertheless when I replace \S{3} with \S{3,4} or \S{4} and try a fail2ban-regex I got the error below:

Traceback (most recent call last):
  File "/usr/bin/fail2ban-regex", line 372, in <module>
    fail2banRegex.testRegex(line)
  File "/usr/bin/fail2ban-regex", line 225, in testRegex
    ret = self.__filter.processLine(line)
  File "/usr/share/fail2ban/server/filter.py", line 268, in processLine
    return self.findFailure(timeLine, logLine)
  File "/usr/share/fail2ban/server/filter.py", line 318, in findFailure
    date = self.dateDetector.getUnixTime(timeLine)
  File "/usr/share/fail2ban/server/datedetector.py", line 183, in getUnixTime
    date = self.getTime(line)
  File "/usr/share/fail2ban/server/datedetector.py", line 172, in getTime
    date = template.getDate(line)
  File "/usr/share/fail2ban/server/datetemplate.py", line 148, in getDate
    date = list(time.strptime(conv, pattern))
  File "/usr/lib/python2.7/_strptime.py", line 467, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib/python2.7/_strptime.py", line 308, in _strptime
    format_regex = _TimeRE_cache.compile(format)
  File "/usr/lib/python2.7/_strptime.py", line 265, in compile
    return re_compile(self.pattern(format), IGNORECASE)
  File "/usr/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 242, in _compile
    raise error, v # invalid expression
sre_constants.error: redefinition of group name 'Y' as group 7; was group 3

Here is the line I test:
192.168.1.255 -  -  [02/sept./2015:00:14:34 +0200] "...

Here are the modifications on datedetector.py

                        # Jetty format 2 [31/sept./2006:09:22:55 +0200]
                        template = DateStrptime()
                        template.setName("Day/MONTH./Year:Hour:Minute:Second")
                        template.setRegex("\d{2}/\S{3,4}./\d{4}:\d{2}:\d{2}:\d{2}")
                        template.setPattern("%d/%b./%Y:%H:%M:%S")

For info escaping the . by \ give me an error in both cases (with three and four digits)

**Comment by sebres** [comment]
Which version of f2b you try to customize? I have not found any reference of `DateStrptime` you have used in current releases. 
Which version of python?

**Comment by 1technophile** [comment]
fail2ban 0.8.6
python 2.7

**Comment by sebres** [comment]
Well, I have not such old version, to test it.
But in current version (0.9) you don't need to customize any source code, just add `datepattern = %d/%b[^/]*/%Y:%H:%M:%S %z` into your `jail.local` for this jetty jail or in your filter if you have it.
I don't know since which version that was first time implemented.

In current version testing of next both lines works fine:
```bash
bin/fail2ban-regex -d "%d/%b[^/]*/%Y:%H:%M:%S %z" "127.0.0.1 -- [02/oct./2015:00:15:19 +0200] test" "<HOST> --\s*\[\]\s*test"
bin/fail2ban-regex -d "%d/%b[^/]*/%Y:%H:%M:%S %z" "127.0.0.1 -- [02/sept./2015:00:15:19 +0200] test" "<HOST> --\s*\[\]\s*test"
```
Notice about the `failregexp` - the datetime string, extracted using `datepattern`, will be removed from line before it will be parsed with `failregexp`, so you should not put it there. See my example for failregexp above.

**Comment by 1technophile** [comment]
Hello,

Thanks for your help :-), it worked by installing 0.9.3 and adding this to the filter:
datepattern = %%d/%%b[^/]*/%%Y:%%H:%%M:%%S %%z

Regards
