### ISSUE TITLE
Lost imap2( tcp143) from jail.conf

### ISSUE THREAD

**Issue by bes-internal** [fail2ban/fail2ban#1214]
Wrong BF https://github.com/fail2ban/fail2ban/commit/549f64e86c92f38569cb08d74861e560585db23f (from 0.9.0) removes imap2 from jail.conf. Yes, imap2 not an IANA but this is alias to imap:

```
$grep imap /etc/services 
imap            143/tcp         imap2           # Internet Message Access Protocol
imap            143/udp         imap2
imap3           220/tcp                         # Interactive Mail Access
imap3           220/udp
imaps           993/tcp                         # imap4 protocol over TLS/SSL
imaps           993/udp
```

it was necessary to change the imap2 to imap. Port 143 must be returned to all these services

**Comment by bes-internal** [comment]
cast @grooverdan

**Comment by sebres** [comment]
@fail2ban/contributors any ideas? 
@grooverdan maybe did you want to replace imap2 against imap?

**Comment by sebres** [comment]
In newest jail.conf-files "restored" as `imap`, thus closed. 
BTW. I've several systems where `imap2` actually is not defined in `/etc/services `... So if someone need it (other as `imap`), should extend it self in jail.local, e. g. like:
```INI
port = %(known/port)s,imap2
```
