### ISSUE TITLE
Postfix login failures not recognized under reverse lookup (overspecific <HOST>?)

### ISSUE THREAD

**Issue by toolforger** [fail2ban/fail2ban#1217]
Example log line:

```
Oct  9 11:01:45 5 postfix/smtpd[8556]: warning: 44.188.11.37.dynamic.jazztel.es[37.11.188.44]: SASL LOGIN authentication failed: authentication failure
```

`postfix-sasl.conf` has this:

```
failregex = ^%(__prefix_line)swarning: [-._\w]+\[<HOST>\]: SASL (?:LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed(: [ A-Za-z0-9+/]*={0,2})?\s*$
```

I suspect that <HOST> does not recognize `44.188.11.37.dynamic.jazztel.es[37.11.188.44]`.

**Comment by sebres** [comment]
Hm. Strange, According to expression it should be matched, of course it will ban 37.11.188.44 (not the IP from Dyn-DNS resolution).

Which version of fail2ban you are using?

I have added as test following lines to `fail2ban\tests\files\logs\postfix-sasl` - all test cases are passed in current master.
```
# failJSON: { "time": "2004-10-09T11:01:45", "match": true , "host": "37.11.188.44" }
Oct  9 11:01:45 5 postfix/smtpd[8556]: warning: 44.188.11.37.dynamic.jazztel.es[37.11.188.44]: SASL LOGIN authentication failed: authentication failure
```

```bash
fail2ban-testcases Filter
Fail2ban 0.9.3.dev test suite. Python 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]. Please wait...
..................................................................................................
----------------------------------------------------------------------
Ran 98 tests in 1.424s
OK
```

So closed now, please reopen again If I misunderstood something.

**Comment by toolforger** [comment]
Yes, I found the regex is just fine, but for some reason it simply does not trigger on my machine.

BTW I can't reopen. Reopening requires Collaborator status on GitHub.

**Comment by sebres** [comment]
>  but for some reason it simply does not trigger on my machine

Detailed? 
Do you see "Found 37.11.188.44" in log? Do you see "Ban 37.11.188.44" in log?

Have you tried `fail2ban-regex /var/log/mail.warn /etc/fail2ban/filter.d/postfix-sasl.conf`, where `mail.warn` is a log file contains this failure line?

BTW. Hmm, I thought an issue creater can reopen an issue...

**Comment by toolforger** [comment]
(Version)
I'm using fail2ban v0.8.11

(Log checking)
I'm not seeing the IP mentioned in fail2ban.log at all.

I suspected that I didn't have postfix-sasl activated.
Adding
```
[postfix-sasl] 
enabled  = true
```
to my jail.local did not help:
```
 * Restarting authentication failure monitor fail2ban
WARNING 'logpath' not defined in 'postfix-sasl'. Using default one: '/var/log/messages'
WARNING 'filter' not defined in 'postfix-sasl'. Using default one: ''
ERROR  Failed during configuration: Bad value substitution:
	section: [postfix-sasl]
	option : action
	key    : port
	rawval : ", protocol="%(protocol)s", chain="%(chain)s"]
%(mta)s-whois-lines[name=%(__name__)s, dest="%(destemail)s", logpath=%(logpath)s, chain="%(chain)s", sendername="%(sendername)s"]
```
I don't know what "bad value substitution" means, nor does it tell me what part of the configuration is wrong, so I'm hitting a dead end here.

(Reopening)
Heh. That's the reason why I set up a test account for each role on my own GitHub project - so that I can test these things :-)

**Comment by sebres** [comment]
`Bad value substitution` means that some variable `%(var)s` could not be substituted.
I think in your configuration is something wrong. For example `logpath` as well as `filter` are not defined.
You can check the configuration will be transfered to server using client dump:
```
fail2ban-client -vv -d | grep postfix-sasl
```

Appart from that I can't help you with the version 0.8 (I know the many linux maintaners still use this version, but it's very old).

**Comment by toolforger** [comment]
Okay, I'll uninstall it then.
Thanks.
