### ISSUE TITLE
CRITICAL Unhandled exception in Fail2Ban:#012 (illegal IP address string passed to inet_aton)

### ISSUE THREAD

**Issue by greenthreads** [fail2ban/fail2ban#1222]
Dear all,

Fail2Ban is not recognizing the IP in <HOST> and throwing the folllowing error:

```
CRITICAL Unhandled exception in Fail2Ban:
#012Traceback (most recent call last):
#012  File "/usr/lib/python2.7/site-packages/fail2ban/server/jailthread.py", line 66, in run_with_except_hook
#012    run(*args, **kwargs)
#012  File "/usr/lib/python2.7/site-packages/fail2ban/server/filterpoll.py", line 97, in run
#012    self.getFailures(filename)
#012  File "/usr/lib/python2.7/site-packages/fail2ban/server/filter.py", line 690, in getFailures
#012    self.processLineAndAdd(line)
#012  File "/usr/lib/python2.7/site-packages/fail2ban/server/filter.py", line 432, in processLineAndAdd
#012    if self.inIgnoreIPList(ip, log_ignore=True):
#012  File "/usr/lib/python2.7/site-packages/fail2ban/server/filter.py", line 371, in inIgnoreIPList
#012    "(?<=b)1+", bin(DNSUtils.addr2bin(s[1]))).group())
#012  File "/usr/lib/python2.7/site-packages/fail2ban/server/filter.py", line 928, in addr2bin
#012    return struct.unpack("!L", socket.inet_aton(ipstring))[0]
#012error: illegal IP address string passed to inet_aton
```

our log line looks like this:

```
[2015-10-14 14:02:09] failtoban.WARNING: Authentication Failure: user=bla ip=x.x.x.x [] []
```
and the failregex is as follows:
```
failregex = failtoban.WARNING: Authentication Failure: user=.* ip=<HOST> .*\[.*\] \[.*\]
```

edit1 by yoh: reformatted to see clearer

what is going wrong here. any help will be highly appreciated.
thank you and best regards.

**Comment by yarikoptic** [comment]
It might help to know version of Fail2Ban

On October 14, 2015 8:56:34 AM EDT, greenthreads <notifications@github.com> wrote:
>Dear all,
>
>Fail2Ban is not recognizing the IP in <HOST> and throwing the
>folllowing error:
>
>CRITICAL Unhandled exception in Fail2Ban:#012Traceback (most recent
>call last):#012  File
>"/usr/lib/python2.7/site-packages/fail2ban/server/jailthread.py", line
>66, in run_with_except_hook#012    run(*args, **kwargs)#012  File
>"/usr/lib/python2.7/site-packages/fail2ban/server/filterpoll.py", line
>97, in run#012    self.getFailures(filename)#012  File
>"/usr/lib/python2.7/site-packages/fail2ban/server/filter.py", line 690,
>in getFailures#012    self.processLineAndAdd(line)#012  File
>"/usr/lib/python2.7/site-packages/fail2ban/server/filter.py", line 432,
>in processLineAndAdd#012    if self.inIgnoreIPList(ip,
>log_ignore=True):#012  File
>"/usr/lib/python2.7/site-packages/fail2ban/server/filter.py", line 371,
>in inIgnoreIPList#012    "(?<=b)1+",
>bin(DNSUtils.addr2bin(s[1]))).group())#012  File
>"/usr/lib/python2.7/site-packages/fail2ban/server/filter.py", line 928,
>in addr2bin#012    return struct.unpack("!L",
>socket.inet_aton(ipstring))[0]#012error: illegal IP address string
>passed
>  to inet
> _aton
>
>our log line looks like this:
>
>[2015-10-14 14:02:09] failtoban.WARNING: Authentication Failure:
>user=bla ip=x.x.x.x [] []
>
>and the failregex is as follows:
>
>failregex = failtoban.WARNING: Authentication Failure: user=.*
>ip=<HOST> .*\[.*\] \[.*\]
>
>
>
>what is going wrong here. any help will be highly appreciated.
>thank you and best regards.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/fail2ban/fail2ban/issues/1222

-- 
Sent from a phone which beats iPhone.

**Comment by greenthreads** [comment]
Dear Yaroslav,

thank you for your quick reply. It is the latest 0.9.3 version running on
CentOS 7
best regards,
Adnan

Sent from a mobile device. Please excuse typos and shortcuts
Am 14.10.2015 15:00 schrieb "Yaroslav Halchenko" <notifications@github.com>:

**Comment by yarikoptic** [comment]
since problem is related to the IP reported, not sure what we could figure out without knowing that IP (i.e. logged line(s) verbatim, and may be not just this one).
But regardless which one triggered this behavior it points to the weakness in fail2ban while reacting to incorrect IPs, adjusting title accordingly

**Comment by sebres** [comment]
see https://github.com/fail2ban/fail2ban/issues/880#issuecomment-65794315 for the same problem...
short: use spaces instead of `,` in `ignoreip`

PS. will close issue, please reopen if got wrong.

**Comment by sebres** [comment]
BTW. And please next time use markdown block \`\`\` ... \`\`\` to add log excerpts etc.

**Comment by greenthreads** [comment]
Yes, that was it. It resolved the problem. Thank you very much.
@sebres , thank you for the reminder. I will take care of this next time.

Thanks again to both of you ...

**Comment by sebres** [comment]
@fail2ban/developers  Because it is meanwhile already 5th issue with the same misconfiguration of `ignoreip` it will be time to "fix" it, see my quote below:
> I think we should validate ignoreip values are correct direct by start (possibly already in fail2ban-client).
> It's not so good if the error occurred first so deep and through failure processing or banning.

**Comment by sebres** [comment]
Since #1198 (and thx @yarikoptic) it will be better... and to realize perfect parsing (detecting all of ignoreip) on client side, the logic implemented in `Filter::inIgnoreIPList` should be duplicated/moved to the fail2ban-client or rewriten as helper.
I think, we leave it for the first time at that.
