### ISSUE TITLE
iptables error or fail2ban error?

### ISSUE THREAD

**Issue by sechacking** [fail2ban/fail2ban#1227]
[24090]: ERROR   iptables -w -n -L INPUT | grep -q 'f2b-SSH[ \t]' -- stderr: "iptables v1.4.7: option `-w' requires an argument\nTry `iptables -h' or 'iptables --help' for more information.\n"
2015-10-19 18:03:26,379 fail2ban.action         [24090]: ERROR   iptables -w -n -L INPUT | grep -q 'f2b-SSH[ \t]' -- returned 1
2015-10-19 18:03:26,379 fail2ban.CommandAction  [24090]: ERROR   Invariant check failed. Trying to restore a sane environment
2015-10-19 18:03:26,484 fail2ban.action         [24090]: ERROR   iptables -w -D INPUT -p tcp --dport ssh -j f2b-SSH
iptables -w -F f2b-SSH
iptables -w -X f2b-SSH -- stdout: ''
2015-10-19 18:03:26,484 fail2ban.action         [24090]: ERROR   iptables -w -D INPUT -p tcp --dport ssh -j f2b-SSH
iptables -w -F f2b-SSH

**Comment by imp1sh** [comment]
Same error here, too. Totally in despair. Is there a workaround?

My error with highest debug level:
Oct 19 14:11:19 myhostname fail2ban.jail[16952]: INFO Jail 'sshiptables' started
Oct 19 14:11:19 myhostname fail2ban.action[16952]: ERROR iptables -w -N f2b-SSH#012iptables -w -A f2b-SSH -j RETURN#012iptables -w -I INPUT -p tcp --dport ssh -j f2b-SSH -- stdout: ''
Oct 19 14:11:19 myhostname fail2ban.action[16952]: ERROR iptables -w -N f2b-SSH#012iptables -w -A f2b-SSH -j RETURN#012iptables -w -I INPUT -p tcp --dport ssh -j f2b-SSH -- stderr: "iptables v1.4.7: option `-w' requires an argument\nTry 
`iptables -h' or 'iptables --help' for more information.\niptables v1.4.7: option `-w' requires an argument\nTry `iptables -h' or 'iptables --help' for more information.\niptables v1.4.7: option `-w' requires an argument\nTry `iptables -
h' or 'iptables --help' for more information.\n"
Oct 19 14:11:19 myhostname fail2ban.action[16952]: ERROR iptables -w -N f2b-SSH#012iptables -w -A f2b-SSH -j RETURN#012iptables -w -I INPUT -p tcp --dport ssh -j f2b-SSH -- returned 2```
Oct 19 14:11:19 myhostname fail2ban.actions[16952]: ERROR Failed to start jail 'sshiptables' action 'iptables': Error starting action#012Traceback (most recent call last):#012  File "/usr/lib/python2.6/site-packages/fail2ban/server/actions.py", line 221, in run#012    action.start()#012  File "/usr/lib/python2.6/site-packages/fail2ban/server/action.py", line 281, in start#012    raise RuntimeError("Error starting action")#012RuntimeError: Error starting action
Oct 19 14:11:21 myhostname kernel: __ratelimit: 1056 callbacks suppressed

**Comment by imp1sh** [comment]
I found this issue:
https://github.com/fail2ban/fail2ban/issues/1122

You can circumvent the problem by editing /etc/fail2ban/action.d/iptables-common.conf and in the last line replace:
iptables = iptables <lockingopt>
with
iptables = iptables

**Comment by yarikoptic** [comment]
No, just create iptables-common.local with
```
[Init]
lockingopt=
```
and do not modify any file to ease your upgrades later on

**Comment by imp1sh** [comment]
Well yeah, know we have a workaround, but the problem persists.

As a matter of fact if someone just installs CentOS 6 latest and with it via epel, fail2ban just wouldn't work out of the box.

In my opinion that's why this ticket should be reopened.

**Comment by sechacking** [comment]
yeah ,it's not work for me...


i see iptables 


[root@news fail2ban]# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
f2b-SSH    tcp  --  anywhere             anywhere            tcp dpt:ssh 

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain f2b-SSH (1 references)
target     prot opt source               destination         
REJECT     all  --  122.14.112.103       anywhere            reject-with icmp-port-unreachable 
RETURN     all  --  anywhere             anywhere            



but 122.14.112.103 can connect server yet.....

**Comment by sebres** [comment]
See https://bugzilla.redhat.com/show_bug.cgi?id=1272681 and https://github.com/fail2ban/fail2ban/issues/1228#issuecomment-150016933

**Comment by RomSocial** [comment]
Experiencing the same as @sechacking
Finally, after removing -w got the rules created in the IPTABLES, but the connections do not get rejected.

Here's the complete dump:

'''Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
f2b-wordpress  tcp  --  anywhere             anywhere            tcp dpt:http 
cphulk     all  --  anywhere             anywhere            
acctboth   all  --  anywhere             anywhere            
...
ACCEPT     tcp  --  anywhere             anywhere            state NEW tcp dpt:http 
...

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
acctboth   all  --  anywhere             anywhere            

Chain acctboth (2 references)
target     prot opt source               destination         
           tcp  --  mydomain.ca  anywhere            tcp dpt:http 
           tcp  --  anywhere             mydomain.ca tcp spt:http 
...        

Chain cphulk (1 references)
target     prot opt source                    destination         
...
DROP       all  --  some.spammy.ip.here       anywhere            state NEW TIME until date 2015-11-03 19:44:30 UTC 
DROP       all  --  some.spammy.ip.here       anywhere            state NEW TIME until date 2015-11-03 22:58:57 UTC 

Chain f2b-wordpress (1 references)
target     prot opt source               destination         
REJECT     all  --  5.254.65.2           anywhere            reject-with icmp-port-unreachable 
REJECT     all  --  220.72.216.133       anywhere            reject-with icmp-port-unreachable 
RETURN     all  --  anywhere             anywhere    '''

And still, 5.254.65.2 is able to connect to all ports etc. (that's my test ip)
