### ISSUE TITLE
fail2ban and owncloud

### ISSUE THREAD

**Issue by CuoreSportivo** [fail2ban/fail2ban#1230]
Hello everyone,

I have installed on a CentOS 7 machine ownCloud 8.2 (upgraded from 8.1.3) and latest fail2ban.
I have also installed ownCloud 8.2 and fail2ban on RaspberryPi (Rasbian). Even though the configuration files are similar on both systems, fail2ban has a weird behavior on my CentOS machine, but on the Rasbian everything is working as it should.

To be more specific about this weird behavior, if I go to https://myip/owncloud and try to enter wrong usernames/passwords, nothing will happen. I can type as many passwords as I want. But If I close and reopen my browser (any browser), then I will get a connection time out, cause apparently I am banned.

On my raspberry, after 4 failed attempts, I automatically get banned and face the connection time out.

I installed fail2ban via epel repos, but also (and after a yum purge) by downloading fail2ban-master.zip from github. 

I made a thread on CentOS forums about this and the same behavior was reported by another user, after he upgraded to latest fail2ban version. So, I'd firstly like to report this issue, and ask if anyone knows if there is a fix about this, and if not, how I could downgrade to another version.

Any help is appreciated.

**Comment by szepeviktor** [comment]
What filter do you use?

**Comment by CuoreSportivo** [comment]
Hi szepeviktor,
I am using the one for owncloud 8.2, proposed at owncloud forums.


[Definition]
failregex={"reqId":".*","remoteAddr":".*","app":"core","message":"Login failed: '.*' \(Remote IP: '<HOST>'\)","level":2,"time":".*"}

ignoreregex =

(https://forum.owncloud.org/viewtopic.php?f=8&t=28678)

**Comment by szepeviktor** [comment]
See if it's matching with `fail2ban-regex` (built-in tool).

**Comment by CuoreSportivo** [comment]
....
"Lines: 213 lines, 0 ignored, 19 matched, 194 missed [processed in 0.05 sec]"
....

I think the problem is not the filter itself, cause it would have been reported to owncloud forums. Plus that I had the same problem with fail2ban and owncloud 8.1.3 (different filter), plus that on my Raspberry the same filter is operating as it should.

The user gets banned, but you have to close the browser and reopen it, in order to get connection timed out. After every failed authentication attempt, even though the browser refreshes, I will not get a connection timed out, so I can try as many username/password combinations as I want. 

Another user informed me he didn't have this problem with fail2ban-0.9.1-4.el7.noarch in CentOS and ownCloud, but he did have it after upgrading via repo to the latest fail2ban available (0.9.3 if I am not mistaken). Is it somehow possible to downgrade to this version in CentOS?

**Comment by valerio-bozzolan** [comment]
(If nobody have other troubles with that filter itself... I think it could be added in the `filter.d` :)

**Comment by benrubson** [comment]
This is what #1646 tries to help with.
Instead of having one Fail2ban filter configuration per web application, web-apps should use default message patterns, as proposed in #1646.
Same as with #1913 :)

**Comment by sebres** [comment]
> This is what #1646 tries to help with.

Nope. As I correct understand the issue - the filter is not a problem at all, just the backend of owncloud does not close the connection and the default action does not reset/reject it also (still trying the brute-force after ban).

@CuoreSportivo which action do you use here?

**Comment by CuoreSportivo** [comment]
@sebres I remember I had spent too much on this, but never found a solution. The problem indeed seemed not to be the filter, since it was fully operational on other distros.

I don't anymore have the above setup, so I can't really provide any more info.

**Comment by sebres** [comment]
Pity.
Thus I'm closing this as long as someone provides more info about same problem.

**Comment by CuoreSportivo** [comment]
Hi All,

I am re-opening this, since during the weekend I recreated a CentOS 7 machine with ownCloud 10 and fail2ban. Just for the record, everything is fully updated.
After some digging, I finally made it work, but not completely.

Regarding the setup, I have a a reverse proxy in front of owncloud, so, in order to avoid having the IP of the reverse proxy banned by fail2ban, I have the reverse proxy forward the external IPs to the owncloud server.

I have noticed though that if I enter from a local (192.168.1x.) machine wrong credentials, I will face a browser timeout, since the IP gets successfully banned.
If I provide wrong credentials from a machine outside the local network, even though its public IP will appear as banned after three failed attempts, the client will get no timeout at all so it will be capable of brute forcing.

Any ideas?

**Comment by sebres** [comment]
Well, I repeat my question: which banning action do you use here?

**Comment by CuoreSportivo** [comment]
As in below, the selected banaction is firewallcmd-ipset, which if I am not mistaken, is also the default one.
Removing the banaction field from below, has no effect.

```
[owncloud]
enabled = true
filter = owncloud
port = https
logpath = /var/log/owncloud.log
banaction = firewallcmd-ipset
```

Local IPs are banned, so I don't know if this is a banaction issue. 
As an update, I forwarded the router's public port directly to the owncloud server (bypassing the reverse proxy) and it did banned public IPs too. So, it is not clear to me if this is a fail2ban issue, or if there is something wrong with the traffic, since it is routed through the reverse proxy.

If i don't forward the public IPs from the reverse proxy, then, as expected, the reverse proxy's IP is banned, and no one can access owncloud. But it does get banned. 
If I forward the public IPs, even though they seem to get banned, the client continues to be able to try as password attempts as he likes.
That's why I am not pretty sure if this one is indeed a fail2ban issue.

**Comment by sebres** [comment]
Well it looks indeed as a 3rd party issue.
Just as notice: possibly you should find some way to reject the active connection that going banned. to "fixup" the ban process and then extend your banning action (or append it as new action after firewallcmd-ipset). 
I don't know how your reverse proxying does look, so I cannot help you here, sorry.
Possibly you should just use some another banning action. For example, if the nginx does proxying - something like [nginx-block-map](https://github.com/fail2ban/fail2ban/blob/0.10/config/action.d/nginx-block-map.conf)...

**Comment by CuoreSportivo** [comment]
Thank sebres. 
I will keep looking at it (fyi reverse proxy is Apache based) and will get back once I have a solution (if any).
