### ISSUE TITLE
custom action.d?

### ISSUE THREAD

**Issue by JimOct** [fail2ban/fail2ban#1231]
hello, are there any action.d for nginx.conf? so we can map deny users using nginx.conf, instead of using CSF/IPTables?

or deny 127.0.0.1; way ...then unban same way?

**Comment by sebres** [comment]
With modifying of nginx.conf (or include) and reload hereafter? I don't know such action. 
But you can write own one. I remember me about an issue for apache #1177.
Just change print lines and add `&& service nginx reload` or `&& /etc/init.d/nginx reload` at end of `actionban` and `actionunban`

**Comment by JimOct** [comment]
Yeah, not sure how to use that one.

This is the format I need:

deny 127.0.0.1;
deny 127.0.0.2;

i can add a comment

#ipsunderhere

if needed

**Comment by JimOct** [comment]
map $remote_addr $denied {
    default 0;
    2.18.216.110 1;
}

any help? how to add it after default 0;

and remove of course when unban..

**Comment by JimOct** [comment]
actionunban = sed -i '/<ip> 1;$/d' "<htaccess>" && ngxreload


It logs succesfully, however does not reload.

**Comment by JimOct** [comment]
Neither does

actionunban = sed -i '/<ip> 1;$/d' "<htaccess>"
	service nginx reload

**Comment by JimOct** [comment]
Neither does

#
actionban = printf %%b "<ip> 1;\n" >> "<htaccess>" && /etc/init.d/nginx reload

# Option:  actionunban
# Notes.:  command executed when unbanning an IP. Take care that the
#          command is executed with Fail2Ban user rights.
# Tags:    <ip>  IP address
#          <failures>  number of failures
#          <time>  unix timestamp of the ban time
# Values:  CMD
#
actionunban = sed -i '/<ip> 1;$/d' "<htaccess>" && /etc/init.d/nginx reload

**Comment by sebres** [comment]
Not so fast :)
You must declare variable htaccess, ex.: `htaccess = /etc/nginx/denied.lst`
Then you should include that, something like:
```
map $remote_addr $denied {
  default 0;
  include denied.lst;
}
```

And if still "Neither does" please checks:
- the entry was saved into your config file `/etc/nginx/denied.lst`;
- the nginx reload command was executed (you see it in error.log, corresponding log level);

**Comment by JimOct** [comment]
Hello again.

Yes, i declared it. It adds the IP's fine to my ip.conf, however it does not reload nginx.

**Comment by sebres** [comment]
any new insights? what says for example a fail2ban log?

**Comment by JimOct** [comment]
hi i solved it using llua redis to block ip's.

**Comment by JimOct** [comment]
@sebres 

issue still occurs

before restarting: 170
after restarting: 270

(no, logs did not increase or decrease.. i stopped nginx to make sure it wouldnt change).

**Comment by sebres** [comment]
> hi i solved it using llua redis to block ip's.
> issue still occurs

Well, maybe your way to "solve" it is the problem :)
Or did you mean something others? "wrong" issue selected?

**Comment by JimOct** [comment]
posted it on wrong issue, cant find the other one @sebres 

it was the one where it wouldn't block properly, i was under http attack yesterday
the log obviously increases
and during that time, fail2ban is having issues blocking all ip's..

**Comment by sebres** [comment]
https://github.com/fail2ban/fail2ban/issues?q=author%3AJimOct+
