### ISSUE TITLE
Wrong install path `/usr/share/doc/` for some platform (install fails on Mac OS 10.11 "El Capitan")

### ISSUE THREAD

**Issue by sibrcode** [fail2ban/fail2ban#1233]
Due to El Capitan's new "System Integrity Protection", there is no way to create the directory at /usr/share/doc/fail2ban, even as root:

> % sudo python setup.py install
> running install
> Checking .pth file support in /Library/Python/2.7/site-packages/
> ...
> running install_data
> creating /usr/share/doc/fail2ban
> error: could not create '/usr/share/doc/fail2ban': Operation not permitted

However, /usr/local is modifiable, so changing line 151 of setup.py from

> '/usr/share/doc/fail2ban'

to

> '/usr/local/doc/fail2ban'

allowed the installer to proceed.

**Comment by sibrcode** [comment]
Apple's info on SIP: https://developer.apple.com/library/prerelease/mac/documentation/Security/Conceptual/System_Integrity_Protection_Guide/Introduction/Introduction.html

**Comment by sebres** [comment]
@fail2ban/developers any idea to fix it (make it configurable)?

**Comment by yarikoptic** [comment]
Should we just install under /usr/local/doc/fail2ban on osx, or not install those doc files at all there?
