### ISSUE TITLE
fail2ban - stopped detecting new?

### ISSUE THREAD

**Issue by JimOct** [fail2ban/fail2ban#1235]
i added a filter to detect limit requests, however once it reaches around 30-45, it seems like it stopped scraping? i am scraping error.log, which gets insanely big each second.. up to 1mb a minute or less..

are there some kind of memory limit? i have 32GB DDR Ram, and it's not using much cpu.

even when the 'attack' stopped, its not scraping the latest ones... its like it froze

[root@aa~]# service fail2ban status
fail2ban-server (pid  12652) is running...
Status
|- Number of jail:      1
`- Jail list:   nginx-req-limit

not sure if it's just too slow to scrape, or froze?

**Comment by sebres** [comment]
Something flashy in fail2ban.log (errors, warning, jail goes idle etc.)?
No more failures will be found? or just no bans?
What says `fail2ban-client status nginx-req-limit`?
Was possibly error.log rotated in the meantime?

**Comment by sebres** [comment]
Oh yeah, forgotten: Did you have a custom filter to parse limit_req in nginx log?
Possible an expression, that you used, does no more match (the lines should be matched are little bit different as lines that f2b has already matched).
You can test it using `fail2ban-regex <line or logfile> <regex or filter conf file>`

**Comment by JimOct** [comment]
Fail2ban shows:
`- Actions
   |- Currently banned: 0
   |- Total banned:     45
   `- Banned IP list:



Regex:
limiting requests, excess:.* by zone.*client: <HOST>


Failed on this text:
2015/10/29 19:24:05 [error] 12684#12684: *22174 limiting requests, excess: 1.495 by zone "one", client: 95.34.238.157, server: domain.com, request: "GET /index.php HTTP/1.1", host: "domain.com", referrer: "https://domain.com"



Using your line, it matched fine. 
Lines: 1 lines, 0 ignored, 1 matched, 0 missed [processed in 0.00 sec]

**Comment by JimOct** [comment]
I am running CentOS 6.7 x64, i can not find fail2ban.log in /var/log

**Comment by sebres** [comment]
To get a log target configured for your f2b, use:
```bash
sudo fail2ban-client -d | grep logtarget
```
> Failed on this text:

What do you mean exactly under "Failed"?

Additionally, your regexp is really very-very "bad" (not ask why, because all is bad). 
This one would be much better:
```
failregex = ^\s*\[error\] \d+#\d+: \*\d+ limiting requests, excess: [\d\.]+ by zone "[^"]+", client: <HOST>, server: \S*, request: "\S+ \S+ HTTP/\d+\.\d+", host: "\S+"(, referrer: "\S+")?\s*$
```

**Comment by sebres** [comment]
I think your regexp find something wrong in error.log, for example something large, where it is extremely splutter or even totally hang up.

I will close this issue, please reopen if i'm wrong (for example if it occurred again also with my regexp).
Or if you will find something flashy in fail2ban log file.

**Comment by sebres** [comment]
Because of too many community demands and many issues with wrong regular expression like this, now added as filter and jail. See #1236, will merge it tomorrow in master.

**Comment by JimOct** [comment]
Hello.

Same issue with your regex... It's not banning this:

2015/10/30 15:53:56 [error] 11815#11815: *1127 limiting requests, excess: 1.500 by zone "one", client: 151.246.195.177, server: domain.com, request: "POST /login.php HTTP/1.1", host: "domain.com"

**Comment by sebres** [comment]
This line will be perfect matched with my regexp. Something other goes wrong here.
You should really inspect your system logs (and check what says fail2ban within).

I don't know which log files uses CentOS, possible /var/log/messages or /var/log/syslog. But if your logging daemon is `syslogd`, the list of log messages maintained by syslogd can be found in the /etc/syslog.conf configuration file.

Additionally please provide an output of `fail2ban-client -d | grep nginx-req-limit`

**Comment by JimOct** [comment]
[root@ns3009754 ~]# fail2ban-client -d | grep nginx-req-limit
['add', 'nginx-req-limit', 'auto']
['set', 'nginx-req-limit', 'usedns', 'warn']
['set', 'nginx-req-limit', 'addlogpath', '/home/nginx/domains/manage.jorens.co/log/error.log', 'head']
['set', 'nginx-req-limit', 'addlogpath', '/home/nginx/domains/pscentral.net/log/error.log', 'head']
['set', 'nginx-req-limit', 'maxretry', 3]
['set', 'nginx-req-limit', 'addignoreip', '127.0.0.1/8']
['set', 'nginx-req-limit', 'logencoding', 'auto']
['set', 'nginx-req-limit', 'bantime', 800]
['set', 'nginx-req-limit', 'ignorecommand', '']
['set', 'nginx-req-limit', 'findtime', 800]
['set', 'nginx-req-limit', 'addfailregex', '^\\s*\\[error\\] \\d+#\\d+: \\*\\d+ limiting requests, excess: [\\d\\.]+ by zone "[^"]+", client: <HOST>, server: \\S*, request: "\\S+ \\S+ HTTP/\\d+\\.\\d+", host: "\\S+"(, referrer: "\\S+")?\\s*$']
['set', 'nginx-req-limit', 'addaction', 'htaccess']
['set', 'nginx-req-limit', 'action', 'htaccess', 'actionban', 'redis-cli SADD ip_blacklist <ip>']
['set', 'nginx-req-limit', 'action', 'htaccess', 'actionstop', '']
['set', 'nginx-req-limit', 'action', 'htaccess', 'actionstart', '']
['set', 'nginx-req-limit', 'action', 'htaccess', 'actionunban', 'redis-cli SREM ip_blacklist <ip>']
['set', 'nginx-req-limit', 'action', 'htaccess', 'actioncheck', '']


Here is messages, from TODAY:
https://anonfiles.com/file/94589f793f29a4470a45845665754178 (Please remove this once you saw it, or let me know that I have to remove it)


If you had skype, or other Im we'd be able to communicate and I could show you it in action.

**Comment by sebres** [comment]
He say **always** `fail2ban.actions[11830]: NOTICE [nginx-req-limit] x.x.x.x already banned`. This situation is not normal. It seems to be not really banned.

I think, your action `htaccess` does not work properly.
PS. You can remove the log file (downloaded).

**Comment by JimOct** [comment]
Yes, that is because nginx lua is not quitting the connection (even after banning, it's limiting connections).

That's another issue but not with fail2ban, do you believe that is causing it?

**Comment by sebres** [comment]
This does not ban! A ban is if the IP can not connect to this/all port for a bantime (and does no more failures at this time).
I've still found nothing else.

**Comment by JimOct** [comment]
Well, either way. It prevents the user from accessing the site for x amount of time, which works fine. However it's also limiting requests of those again, which is a issue.. 

Can't imagine that being the issue for fail2ban stopping to scrape logs after certain amount of traffic. 

Reason for using this way is because i use CloudFlare, and reloading nginx under attacks would be quiet intensive. I found no other ways of doing it, as iptables/csf wouldn't ban the visitor / block, since cloudflare is proxifying the traffic.. so only web server can block it

**Comment by sebres** [comment]
Unfortunately it still generates failures in the sense of fail2ban. That is not good, but I did understood.
I think, that is because `limit_req` will be processed from nginx inside the earlier phase, just before you shrink it (within lua or something else in nginx).

**Comment by sebres** [comment]
Can you try it with standard actions like iptables, firewall etc? Because if it will work, you have really a problem with your custom action.

**Comment by sebres** [comment]
Well, I see before you have restarted a fail2ban almost only "already banned" notices.
Between 15:47:00 and 15:56:11 (shortly before restart) you have 510 such messages.
And only 64 normal messages (Found and Ban).

During the "bantime" you should prevent nginx to log "banned" IPs again (somehow disable `limit_req` for this IPs). I don't know some method to do that.

**Comment by JimOct** [comment]
Indeed, i'll come back when I figured out how to do that and see if that will make fail2ban more stable.

**Comment by JimOct** [comment]
@sebres 

here we go, issue still occurs even when using csf or any kind of other block

**Comment by sebres** [comment]
And how looks the log out with another action? Did you seen something like https://github.com/fail2ban/fail2ban/issues/1235#issuecomment-152558418 again?

**Comment by JimOct** [comment]
@sebres 

I am using Lua, which returns 403 to the visitor. It may take up to 15 seconds for the "block" to take effect, but when it does it will not log any more or limit requests from that specific IP. However, during that time, it might log limit requests - even after block (within those 15 seconds).

Now, would that matter?
