### ISSUE TITLE
CPU load 100% issue on fail2ban 0.8.13-1

### ISSUE THREAD

**Issue by franksz** [fail2ban/fail2ban#1252]
Hi, I installed fail2ban from Jessie repository and applied the same configuration I had on wheezy with fail2ban 0.8.4-SVN but I saw that cpu load for two f2b process was very high (100% and over).
So I started to understand where was the problem. I restored the original jail.conf and all goes well, I added only one of my rules and it goes again to 100%. At this point I tested every single configuration within the rule and found that the CPU stay at 100% depending on the log file size to monitor. 
For example, by setting a log file of 3MB it stay 100% for few second, while if I try with a log file of 50MB it stay 100% for 2 minutes! 
I also tried to remove again my rule and set these log file on ssh default rule, the behaviour it's the same.
Is it a known bug? How can I try to solve this issue?
Thanks

**Comment by sebres** [comment]
Unfortunately it's no possibility to "fix" it in version 0.8.

You have only one opportunity to bypass this - using logrotate make the logs smaller :(

In 0.9 we made the several things to make a start of fail2ban faster and fewer cpu hungry, for example 
the database, that holds the last processed position of the log file. And much more.

Similar issues were already posted here, end with the same conclusion (logrotate or newer version of fail2ban).

BTW I see still one possibility, but its would be very tricky: once I made a solution to the fast seek of `now - findtime` position inside a log file (but also in v.0.9). You can find it as a part here - https://github.com/fail2ban/fail2ban/pull/1116/files#diff-017caab67b292502b7fc624a060d108fR692
But it should be very complex merged in version 0.8 :(
