### ISSUE TITLE
firewallcmd-multiport.conf and firewallcmd-allports.conf have iptables-blocktype.conf dependency but that file is not installed by EPEL v7 fail2ban RPMs

### ISSUE THREAD

**Issue by shadowym** [fail2ban/fail2ban#1254]
On the latest stable EPEL v7 RPM after installing fail2ban (v0.9.3-1), using firewallcmd-multiport.conf and firewallcmd-allports.conf fails because they have a 
before = iptables-blocktype.conf

statement.  However that file is missing from the RPM's.  That file should either be added to the RPMs or the dependency changed to iptables-common.conf which already defines the blocktype.

I am currently using this file the get around it for now.
https://github.com/breauxaj/puppet-fail2ban/blob/master/files/original/rhel/action.d/iptables-blocktype.conf

**Comment by opoplawski** [comment]
It's not just the rpm - it's in current master branch, and introduced by the original commit 50e5fd9ed71164aa545a4757cd72ded5c5aa86d4

**Comment by opoplawski** [comment]
Ping?

**Comment by yarikoptic** [comment]
https://github.com/fail2ban/fail2ban/pull/1359
