### ISSUE TITLE
When using firewalld jail I get error when rebooting

### ISSUE THREAD

**Issue by shadowym** [fail2ban/fail2ban#1256]
fail2ban is unable to remove the firewalld created chains when rebooting on CentOS v7 using Fail2ban v0.9.3-1 installed from EPEL v7.  That is what I was able to conclude from the errors in the fail2ban.log file.  I do not get those errors when I just restart the fail2ban service.  The error implied that the root cause was because fail2ban was not able to communicate with dbus on a rebooting system.

I was able to correct the problem by adding "dbus.service" in the "After" line in the fail2ban.service systemd  start/stop script.

**Comment by yarikoptic** [comment]
thanks @shadowym 
@opoplawski -- assigned you as the most knowledgeable on this one ;)
I do not quite grasp though why we anyhow depend on dbus. we do specify After firewalld so that should have already taken care of proper ordering i.e. shutting fail2ban down before shutting down firewalld, which if using dbus should specify that in its .service

**Comment by shadowym** [comment]
Perhaps someone else can verify if they can duplicate it.  All I know is if I add dbus.service the error goes away.

**Comment by shadowym** [comment]
Here is the error.  Sorry about the formatting but that's the way it shows up.

```
firewall-cmd --direct --remove-chain ipv4 filter f2b-asterisk-udp -- stderr: 'Traceback (most recent call last):\n  File "/usr/bin/firewall-cmd", line 703, in <module>\n    fw = FirewallClient()\n  File "<string>", line 2, in __init__\n  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 52, in handle_exceptions\n    return func(*args, **kwargs)\n  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 1594, in __init__\n    self.bus = dbus.SystemBus()\n  File "/usr/lib64/python2.7/site-packages/dbus/_dbus.py", line 194, in __new__\n    private=private)\n  File "/usr/lib64/python2.7/site-packages/dbus/_dbus.py", line 100, in __new__\n    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)\n  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 122, in __new__\n    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)\ndbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused\nTraceback (most recent call last):\n  File "/usr/bin/firewall-cmd", line 703, in <module>\n    fw = FirewallClient()\n  File "<string>", line 2, in __init__\n  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 52, in handle_exceptions\n    return func(*args, **kwargs)\n  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 1594, in __init__\n    self.bus = dbus.SystemBus()\n  File "/usr/lib64/python2.7/site-packages/dbus/_dbus.py", line 194, in __new__\n    private=private)\n  File "/usr/lib64/python2.7/site-packages/dbus/_dbus.py", line 100, in __new__\n    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)\n  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 122, in __new__\n    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)\ndbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused\nTraceback (most recent call last):\n  File "/usr/bin/firewall-cmd", line 703, in <module>\n    fw = FirewallClient()\n  File "<string>", line 2, in __init__\n  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 52, in handle_exceptions\n    return func(*args, **kwargs)\n  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 1594, in __init__\n    self.bus = dbus.SystemBus()\n  File "/usr/lib64/python2.7/site-packages/dbus/_dbus.py", line 194, in __new__\n    private=private)\n  File "/usr/lib64/python2.7/site-packages/dbus/_dbus.py", line 100, in __new__\n    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)\n  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 122, in __new__\n    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)\ndbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused\n'
```

**Comment by yarikoptic** [comment]
THANKS! which confirms that it is firewall-cmd's issue I guess UNLESS
firewalld did get shutdown before fail2ban went down... could you check
on that ?

On Fri, 20 Nov 2015, shadowym wrote:

> Here is the error. Sorry about the formatting but that's the way it shows up.

> firewall-cmd --direct --remove-chain ipv4 filter f2b-asterisk-udp -- stderr: 'Traceback (most recent call last):\n  File "/usr/bin/firewall-cmd", line 703, in <module>\n    fw = FirewallClient()\n  File "<string>", line 2, in __init__\n  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 52, in handle_exceptions\n    return func(*args, **kwargs)\n  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 1594, in __init__\n    self.bus = dbus.SystemBus()\n  File "/usr/lib64/python2.7/site-packages/dbus/_dbus.py", line 194, in __new__\n    private=private)\n  File "/usr/lib64/python2.7/site-packages/dbus/_dbus.py", line 100, in __new__\n    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)\n  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 122, in __new__\n    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)\ndbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socke
-- 
Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by yarikoptic** [comment]
On Fri, 20 Nov 2015, Yaroslav Halchenko wrote:

> THANKS! which confirms that it is firewall-cmd's issue I guess UNLESS
> firewalld did get shutdown before fail2ban went down... could you check
> on that ?

from http://www.freedesktop.org/software/systemd/man/systemd.unit.html

Note that when two units with an ordering dependency between them are shut down, the inverse of the start-up order is applied. i.e. if a unit is configured with After= on another unit, the former is stopped before the latter if both are shut down.

so, unless firewall.service doesn't have After=dbus.service (which it seems it should and that would be the bug if it doesn't), fail2ban should be stopped before firewall, and thus before dbus

**Comment by shadowym** [comment]
You could probably argue that firewalld.service should have dbus.service in the after statement but they may disagree or may not see a need to do anything about it.  The problem still remains regardless.

Doing a firewallcmd operation like this on shutdown is probably somewhat unique to fail2ban although I could be wrong.

**Comment by marcosfrm** [comment]
Already reported and fixed in firewalld:

https://github.com/t-woerner/firewalld/issues/48

**Comment by sebres** [comment]
Well, I will close it now, since seems to be fixed (Thx @marcosfrm).
Reopen, if it yet does not work.

**Comment by maq123** [comment]
I am getting this one again on CentOS 7.2.
Fail2ban pkgs
```
[root@narwhal ~]# rpm -qa | grep fail2ban
fail2ban-sendmail-0.9.5-3.el7.noarch
fail2ban-server-0.9.5-3.el7.noarch
fail2ban-firewalld-0.9.5-3.el7.noarch
fail2ban-0.9.5-3.el7.noarch

```

Error : 

```

2016-12-08 12:07:38,087 fail2ban.server         [1920]: INFO    Stopping all jails
2016-12-08 12:07:39,157 fail2ban.action         [1920]: ERROR   firewall-cmd --direct --remove-rule ipv4 filter INPUT 0 -p tcp -m multiport --dports ssh -m set --match-set fail2ban-sshd src -j REJECT --reject-with icmp-port-unreachable
ipset flush fail2ban-sshd
ipset destroy fail2ban-sshd -- stdout: 'Not using slip\n'
2016-12-08 12:07:39,157 fail2ban.action         [1920]: ERROR   firewall-cmd --direct --remove-rule ipv4 filter INPUT 0 -p tcp -m multiport --dports ssh -m set --match-set fail2ban-sshd src -j REJECT --reject-with icmp-port-unreachable
ipset flush fail2ban-sshd
ipset destroy fail2ban-sshd -- stderr: 'error: cannot open Packages database in /var/lib/rpm\nTraceback (most recent call last):\n  File "/usr/bin/firewall-cmd", line 703, in <module>\n    fw = FirewallClient()\n  File "<string>", line 2, in __init__\n  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 52, in handle_exceptions\n    return func(*args, **kwargs)\n  File "/usr/lib/python2.7/site-packages/firewall/client.py", line 1594, in __init__\n    self.bus = dbus.SystemBus()\n  File "/usr/lib64/python2.7/site-packages/dbus/_dbus.py", line 194, in __new__\n    private=private)\n  File "/usr/lib64/python2.7/site-packages/dbus/_dbus.py", line 100, in __new__\n    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)\n  File "/usr/lib64/python2.7/site-packages/dbus/bus.py", line 122, in __new__\n    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)\ndbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused\nipset v6.19: Set cannot be destroyed: it is in use by a kernel component\n'
2016-12-08 12:07:39,158 fail2ban.action         [1920]: ERROR   firewall-cmd --direct --remove-rule ipv4 filter INPUT 0 -p tcp -m multiport --dports ssh -m set --match-set fail2ban-sshd src -j REJECT --reject-with icmp-port-unreachable
ipset flush fail2ban-sshd
ipset destroy fail2ban-sshd -- returned 1
2016-12-08 12:07:39,158 fail2ban.actions        [1920]: ERROR   Failed to stop jail 'sshd' action 'firewallcmd-ipset': Error stopping action
2016-12-08 12:07:39,158 fail2ban.jail           [1920]: INFO    Jail 'sshd' stopped
2016-12-08 12:07:39,159 fail2ban.server         [1920]: INFO    Exiting Fail2ban


```

**Comment by marcosfrm** [comment]
@maq123 firewalld was updated to current 0.4.x versions in RHEL 7.3. You can wait for CentOS 7.3 or temporarily create a systemd drop-in config in 7.2:

```
mkdir /etc/systemd/system/firewalld.service.d
echo -e '[Unit]\nAfter=dbus.service' > /etc/systemd/system/firewalld.service.d/temp.conf
systemctl daemon-reload
```

Once updated to CentOS 7.3, you should remove this file and run `systemctl daemon-reload` again.
