### ISSUE TITLE
test failure with python 3.5

### ISSUE THREAD

**Issue by opoplawski** [fail2ban/fail2ban#1268]
When building with python 3.5 I get the following test failure:
~~~~~
FAIL: testTraceBack (fail2ban.tests.misctestcase.TestsUtilsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/misctestcase.py", line 160, in testTraceBack
    self.assertFalse('>' in s, msg="'>' present in %r" % s)
AssertionError: True is not false : '>' present in 'fail2ban-testcases:129>misctestcase:150'
----------------------------------------------------------------------
~~~~~
I'm not sure what the output it as it doesn't show it, but probably a different traceback format in python3.

**Comment by sebres** [comment]
I think, you've made the test with redirecting output to a file `f2b-test > out.txt`, that is normal then.

**Comment by opoplawski** [comment]
I'm simply running: ./fail2ban-testcases-all-python3 --no-network

**Comment by yarikoptic** [comment]
On Tue, 08 Dec 2015, Orion Poplawski wrote:

> When building with python 3.5 I get the following test failure:

> FAIL: testTraceBack (fail2ban.tests.misctestcase.TestsUtilsTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "./fail2ban/tests/misctestcase.py", line 160, in testTraceBack
>     self.assertFalse('>' in s, msg="'>' present in %r" % s)
> AssertionError: True is not false : '>' present in 'fail2ban-testcases:129>misctestcase:150'
> ----------------------------------------------------------------------

> I'm not sure what the output it as it doesn't show it, but probably a different
> traceback format in python3.

interestingly doesn't replicate for me with python 3.5 on debian.  but I
somewhat wonder why I expected misctestcase not to be listed there?  I
wish I could have reproduce to get a clearer idea ;)

**Comment by opoplawski** [comment]
Appears to be working fine for me now.
