### ISSUE TITLE
port is not inherited from [DEFAULT] section in jail.local

### ISSUE THREAD

**Issue by wodry** [fail2ban/fail2ban#1270]
fail2ban 0.9.2

I copied
/etc/fail2ban/jail.conf
to
/etc/fail2ban/jail.local
There is written:
```
[DEFAULT]
port = 0:65535
```
In the [sshd] section is no port defined, so I would guess the default is inherited. But looking at iptables, I see

-A INPUT -p tcp -m multiport --dports 22 -j f2b-sshd

So I added
port = 0:65535

to the [sshd] section.

Now it works:
-A INPUT -p tcp -m multiport --dports 0:65535 -j f2b-sshd

So the default port definition is not inherited. Please fix code or documentation.

**Comment by yarikoptic** [comment]
Copying entire jail.conf into . local is a sin ;-)

port is defined per jail (this overriding the default), this if you want to change it for sshd have it overridden in sshd section, cheers

**Comment by wodry** [comment]
I think the subject is pretty clear.
I think You did not understand the subject.
I do _not_ want to change the port defined in the [DEFAULT] section.
In the [DEFAULT] section port is defined as 0:65535.
But if I do not define port in the [sshd] Jail (so I should _not_ overwrite the default port definition), only port 22 is blocked.

**Comment by sebres** [comment]
The subject is pretty clear.
I think You did not understand the fail2ban works (resp. reads its config files).
Firstly it will always load `x.conf` and substitutes it using `[default]` from `x.conf`.
Hereafter it loads `x.local`, substitutes it exact the same way and only then overwrites entries from `x.conf`.
In [sshd] of `jail.conf` we have `port=ssh`, so no matter which port you will have in `[default]` of your `jail.local`.
Secondly, if you really want to block all ports, you can use `banaction = %(banaction_allports)s` in your local changeset for sshd jail (or/and you can just enable jail `pam-generic`).

**Comment by wodry** [comment]
I think values defined in the [DEFAULT] section of jail.local should overwrite the values in the [DEFAULT] section of jail.conf _before_ the other sections of jail.conf are parsed (and afterwards the other sections of jail.local).

Otherwise, as of my understanding now, values in the [DEFAULT] section of jails.local have only impact on jail sections, that are not defined in jail.conf which is pretty confusing, IMHO.

But that would be another issue because the port is needed in sshd jail.local section anyway because it is already set explicit in jail.conf sshd section.

**Comment by sebres** [comment]
> I think values defined in the [DEFAULT] section of jail.local should overwrite the values in the [DEFAULT] section of jail.conf before the other sections of jail.conf are parsed (and afterwards the other sections of jail.local).

Imho, matter of taste... But in your case it changes nothing...

`[jail.local/DEFAULT]` overwrites `[jail.conf/DEFAULT]`, `[jail.local/sshd]` overwrites `[jail.conf/sshd]`, substitution of `[sshd]` leave `port=ssh` if you will not specify it in `[jail.local/sshd]`. 

If you don't need any standard setting - you can create your own jail, something like this:
```
[wodry-sshd]
enabled = true
filter = sshd
logpath = %(sshd_log)s
backend = %(sshd_backend)s
```
