### ISSUE TITLE
In action "blocklist_de.conf" is hardcoded user-agent "fail2ban v0.8.12"

### ISSUE THREAD

**Issue by wodry** [fail2ban/fail2ban#1271]
Version 0.9.2 and current dev code

In file
/etc/fail2ban/action.d/blocklist_de.conf
is the line
```
actionban = curl --fail --data-urlencode 'server=<email>' --data 'apikey=<apikey>' --data 'service=<service>' --data 'ip=<ip>' --data-urlencode 'logs=<matches>' --data 'format=text' --user-agent "fail2ban v0.8.12" "https://www.blocklist.de/en/httpreports.html"
```
The user-agent setting is wrong.
I would suggest to determine the fail2ban version on runtime and use that value instead of hardcoded version, since, like in this case, it will probably be wrong in the future.

**Comment by yarikoptic** [comment]
I guess we indeed could just use 
```bash
"`fail2ban-client --version | head -n 1`"
```

**Comment by yarikoptic** [comment]
or may be better we expose smth like `<fail2ban_agent_string>` from within.  I will send a PR shortly
