### ISSUE TITLE
No route to host but brute force continues

### ISSUE THREAD

**Issue by Tech01** [fail2ban/fail2ban#1276]
I've seen this problem before with iptables and now I'm using route to dump the user to neverland however even though the server cannot see this IP the IP was still showing status code 200s until I used .htaccess to block him, now I see status 403s but the brute force is still moving on. I don't think it has a significant impact on my host server but I don't know how they are getting through.....The route blocks both ways for a period of time so I'm baffled how they are still able to maintain a connection even after a reboot of the server. This works on 99% of the IPs out there but every now and again we get this reaction to the block and need to take some manual actions, eventually the attacker gives up. 

ip route add unreachable 95.172.133.131

# ping 95.172.133.131
connect: Network is unreachable

95.172.133.131 - - [TIMEOBSCURED] "POST /wp-login.php HTTP/1.0" 403 1185 "-" "-" www.example.com
95.172.133.131 - - [TIMEOBSCURED] "POST /wp-login.php HTTP/1.0" 403 1185 "-" "-" www.example.com
95.172.133.131 - - [TIMEOBSCURED] "POST /wp-login.php HTTP/1.0" 403 1186 "-" "-" www.example.com
95.172.133.131 - - [TIMEOBSCURED] "POST /wp-login.php HTTP/1.0" 403 1186 "-" "-" www.example.com
95.172.133.131 - - [TIMEOBSCURED] "POST /wp-login.php HTTP/1.0" 403 1184 "-" "-" www.example.com
95.172.133.131 - - [TIMEOBSCURED] "POST /wp-login.php HTTP/1.0" 403 1186 "-" "-" www.example.com
95.172.133.131 - - [TIMEOBSCURED] "POST /wp-login.php HTTP/1.0" 403 1186 "-" "-" www.example.com
95.172.133.131 - - [TIMEOBSCURED] "POST /wp-login.php HTTP/1.0" 403 1186 "-" "-" www.example.com
95.172.133.131 - - [TIMEOBSCURED] "POST /wp-login.php HTTP/1.0" 403 1185 "-" "-" www.example.com
95.172.133.131 - - [TIMEOBSCURED] "POST /wp-login.php HTTP/1.0" 403 1185 "-" "-" www.example.com
95.172.133.131 - - [TIMEOBSCURED] "POST /wp-login.php HTTP/1.0" 403 1185 "-" "-" www.example.com

TIMEOBSCURED fail2ban.filter         [6653]: INFO    [apache] Found 95.172.133.131
TIMEOBSCURED fail2ban.filter         [6653]: INFO    [apache] Found 95.172.133.131
TIMEOBSCURED fail2ban.filter         [6653]: INFO    [apache] Found 95.172.133.131
TIMEOBSCURED fail2ban.filter         [6653]: INFO    [apache] Found 95.172.133.131
TIMEOBSCURED fail2ban.filter         [6653]: INFO    [apache] Found 95.172.133.131
TIMEOBSCURED fail2ban.actions        [6653]: NOTICE  [apache] 95.172.133.131 already banned

**Comment by yarikoptic** [comment]
I don't see here any problem with fail2ban since no adequate information provided. Better ask on mailing list first after also consulting that http://www.fail2ban.org/wiki/index.php/HOWTO_Seek_Help

Host can be not pingable fit so many reasons. You can misconfigure fail2ban banking so many ways. When you know there is a bug, file here
