### ISSUE TITLE
How to add new regex?

### ISSUE THREAD

**Issue by twixi** [fail2ban/fail2ban#1279]
![image](https://cloud.githubusercontent.com/assets/7196070/11946317/e86a0728-a861-11e5-93c2-8a58c0f7676c.png)

**Comment by sebres** [comment]
Names resolution may have sporadically temporary problems, so it's no failure in sense of "failed login attempts" and should not be blocked.

But back to the subject - you can add a new regex with 2 ways:
- add it direct in filter of your jail as new line in `failregex`, for example here is it for all jails used sshd-filter https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/sshd.conf#L37
- add it direct in your `jail.local` as new entry `failregex`:
```
[sshd]
...
failregex = %(known/failregex)s
            ... your new regex ...
```
