### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by kyle95wm** [fail2ban/fail2ban#1281]
Hey I'm about to install the fail2ban directly from the github build and was wondering if there was an easy way to remove fail2ban after it is installed. Im running Raspbian Jessie by the way

**Comment by yarikoptic** [comment]
dpkg --purge fail2ban


This is not a support page but bug reports. Please consult http://www.fail2ban.org/wiki/index.php/HOWTO_Seek_Help
