### ISSUE TITLE
does fail2ban change network adapter profile?

### ISSUE THREAD

**Issue by GreatFireWall** [fail2ban/fail2ban#1282]
Before install fail2ban, my network adapter: 
---------------------------------------------------------------------------------------------------------------------------->
[root@xxx~]# ip addr
    1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
  2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:16:3c:13:f5:15 brd ff:ff:ff:ff:ff:ff
    inet 118.193.244.221/26 brd 118.193.244.255 scope global dynamic ens3
       valid_lft 21599714sec preferred_lft 21599714sec
    inet6 fe80::216:3cff:fe13:f515/64 scope link 
       valid_lft forever preferred_lft forever
----------------------------------------------------------------------------------------------------------------------------->

I install fail2ban then do nothing and reboot my vps immediately.
after boot, i can't connect to my vps via ssh anymore.
Then I use the vps's control pannel, i see my network adapter was changed, ip address is lost:
----------------------------------------------------------------------------------------------------------------------------->
[root@xxx~]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN qlen 1000
    link/ether 00:16:3c:13:f5:15 brd ff:ff:ff:ff:ff:ff
----------------------------------------------------------------------------------------------------------------------------->

CentOS 7, kernel 3.10.0-123.4.2.el7.x86_64.
Fail2ban:
Name        : fail2ban
Arch        : noarch
Version     : 0.9.3
Release     : 1.el7
Size        : 9.7 k
Repo        : epel/x86_64

**Comment by yarikoptic** [comment]
Consult centos support. AFAIK we don't change anything
