### ISSUE TITLE
Recidive and systemd journal

### ISSUE THREAD

**Issue by beurle** [fail2ban/fail2ban#1283]
I can't get recidive filter to work on my Fedora system. I am using 9.0 but it seems to be the same for later versions, fail2ban logs to /var/log/fail2ban.log and not the systemd journal.

Using journalmatch in the filters it gets application logs (this works). Using logpath is invalid for systemd configs? This means the recidive filter can never work because its looking in the journal for stuff thats in the log file?

Is there something I am missing here?

**Comment by rumpelsepp** [comment]
Using that for a while now:

```
[recidive]
enabled   = true
backend   = systemd
# https://github.com/fail2ban/fail2ban/issues/698#issuecomment-40725863
banaction = iptables-allports
bantime   = 604800  ; 1 week
findtime  = 86400   ; 1 day
maxretry  = 5
```

**Comment by beurle** [comment]
What does your recidive.conf filter look like?

**Comment by rumpelsepp** [comment]
It is the default, I have not altered that file.

**Comment by jackwilsdon** [comment]
I'm having the same issue. After doing some searching around, it looks like the recidive filter uses fail2ban's journald log.

It looks like fail2ban isn't logging the attempts to systemd (at least for me), so it never detects the attempts.

Here's the output from `journalctl -u fail2ban.service`:

```
-- Reboot --
Jun 01 13:26:30 hostname systemd[1]: Starting Fail2Ban Service...
Jun 01 13:26:30 hostname fail2ban-client[478]: 2016-06-01 13:26:30,568 fail2ban.server         [533]: INFO    Starting Fail2ban v0.9.4
Jun 01 13:26:30 hostname fail2ban-client[478]: 2016-06-01 13:26:30,568 fail2ban.server         [533]: INFO    Starting in daemon mode
Jun 01 13:26:30 hostname systemd[1]: Started Fail2Ban Service.
```

**Comment by jackwilsdon** [comment]
I found a solution! You need to change "logtarget" in your configuration to `SYSLOG`, which allows fail2ban to log to journald.

I created a file in `fail2ban.d` called `logtarget.local` with the following contents:

```ini
[Definition]

# Option: logtarget
# Notes.: Set the log target. This could be a file, SYSLOG, STDERR or STDOUT.
#         Only one log target can be specified.
#         If you change logtarget from the default value and you are
#         using logrotate -- also adjust or disable rotation in the
#         corresponding configuration file
#         (e.g. /etc/logrotate.d/fail2ban on Debian systems)
# Values: [ STDOUT | STDERR | SYSLOG | FILE ]  Default: STDERR
#
logtarget = SYSLOG
```

**Comment by beurle** [comment]
This has been added as a comment to the jail.conf file since the version I used and its also a solution.

"if systemd backend is chosen as the default but you enable a jail for which logs are present only in its own log files, specify some other backend for that jail (e.g. polling) and provide empty value for
journalmatch. See https://github.com/fail2ban/fail2ban/issues/959#issuecomment-74901200"
