### ISSUE TITLE
Two `sender`-s

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#1285]
We have two `sender`-s. One in jail.conf and another one in sendmail-common.conf.
And the jail.conf `sender` is set - given to an action - only in `action_xarf`.
https://github.com/fail2ban/fail2ban/blob/master/config/jail.conf#L166-L169

I propose to keep the `[Init]` value in sendmail-common.conf and have it set in all actions to provide a way to overwrite it.

**Comment by sebres** [comment]
Outdated? Can not find `sender = ...` elsewhere outside of jail.conf...
Please reopen if I'm wrong...

**Comment by szepeviktor** [comment]
OK!
https://github.com/fail2ban/fail2ban/blob/0.10/config/action.d/sendmail-common.conf#L69

**Comment by sebres** [comment]
And? 
It will be overwritten through the use of `action = some-action[..., sender="%(sender)s", ...]` from the jail config.
So if you'll provide another sender in the jail.local (default or per jail) - jailreader transfers this sender parameter to the action...
Where is exactly the problem?

**Comment by szepeviktor** [comment]
> And?

It works OK.
