### ISSUE TITLE
Error in FilterPyinotify callback: illegal IP address string passed to inet_aton

### ISSUE THREAD

**Issue by MightySlaytanic** [fail2ban/fail2ban#1289]
Hi,
I've just configured fail2ban v0.8.13 from NeuroDebian repository (previous one was matching failure events but it didn't take any action) and when an apache authentication failure happens I have the following error, can you give me any hint? I'm on Ubuntu 12.04LTS.

2016-01-01 13:22:00,609 fail2ban.filter [26634]: DEBUG   Processing line with time:1451650374.0 and ip:87.2.253.127
2016-01-01 13:22:00,611 fail2ban.filter [26634]: ERROR   Error in FilterPyinotify callback: illegal IP address string passed to inet_aton
Traceback (most recent call last):
  File "/usr/share/fail2ban/server/filterpyinotify.py", line 213, in process_default
    self.__FileFilter.callback(event, origin='Default ')
  File "/usr/share/fail2ban/server/filterpyinotify.py", line 94, in callback
    self._process_file(path)
  File "/usr/share/fail2ban/server/filterpyinotify.py", line 103, in _process_file
    self.getFailures(path)
  File "/usr/share/fail2ban/server/filter.py", line 545, in getFailures
    self.processLineAndAdd(line)
  File "/usr/share/fail2ban/server/filter.py", line 353, in processLineAndAdd
    if self.inIgnoreIPList(ip):
  File "/usr/share/fail2ban/server/filter.py", line 293, in inIgnoreIPList
    "(?<=b)1+", bin(DNSUtils.addr2bin(s[1]))).group())
  File "/usr/share/fail2ban/server/filter.py", line 735, in addr2bin
    addr2bin = staticmethod(addr2bin)
error: illegal IP address string passed to inet_aton

**Comment by yarikoptic** [comment]
I guess we should let 0.8.x series let go soon since 0.9.x is in a good shape note IMHO. If you replace debian with debian-devel in your apt file for NeuroDebian you should be able to get 0.9.x
In your case if you like to troubleshoot, increase loglevel to debug and see in which line of your log if gets triggered... Most probably some incorrect ip

**Comment by MightySlaytanic** [comment]
You can see from the output above, which is debug output, the IP that triggers the error and it is a correct IP address. I'll try tomorrow with v0.9, thank you for the hint

**Comment by yarikoptic** [comment]
d'oh -- sorry, have missed it... but now I think it is probably just a side-effect of incorrect ignoreip setting -- should be separated by space not by ',' (in recent 0.9.x could be by any of those ;) )

**Comment by MightySlaytanic** [comment]
Hi @yarikoptic , great hint! It was the ignores setting with commas that was not working!

May I ask you another info? Maybe the answer will be "move to 0.9 :)

I've tested the apache jail and it works like a charm... 3 failures and I'm banned... Then I've tested SSH jail and after the first 3 login attempt I've got this in auth.log, which is not matched by any SSH jail regex:

> Jan  2 09:42:39 myserver sshd[1239]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=6.40.41.188  user=testuser
Jan  2 09:42:39 myserver sshd[1239]: pam_winbind(sshd:auth): user 'testuser' denied access (incorrect password or invalid membership)
Jan  2 09:42:46 myserver sshd[1241]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=6.40.41.188  user=testuser
Jan  2 09:42:46 myserver sshd[1241]: pam_winbind(sshd:auth): user 'testuser' denied access (incorrect password or invalid membership)
Jan  2 09:42:51 myserver sshd[1243]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=6.40.41.188  user=testuser
Jan  2 09:42:51 myserver sshd[1243]: pam_winbind(sshd:auth): user 'testuser' denied access (incorrect password or invalid membership)

I've tried other three times and I've got the following in auth.log, which was matched by the jail filter and correctly banned my IP:

> Jan  2 09:43:00 myserver sshd[1236]: Failed keyboard-interactive/pam for testuser from 6.40.41.188 port 25100 ssh2
Jan  2 09:43:09 myserver sshd[1236]: Failed keyboard-interactive/pam for testuser from 6.40.41.188 port 25100 ssh2
Jan  2 09:43:17 myserver sshd[1236]: Failed keyboard-interactive/pam for testuser from 6.40.41.188 port 25100 ssh2

Should I ask another question about this or do you have a quick reply for me?

**Comment by MightySlaytanic** [comment]
@yarikoptic how should I change the following lines in order to point to the 0.9 repositories?

> deb http://neuroimaging.sakura.ne.jp/neurodebianl data main
> deb http://neuroimaging.sakura.ne.jp/neurodebian trusty main

**Comment by yarikoptic** [comment]
Need to run... On NeuroDebian website choose NH mirror, and start from those apt lines

**Comment by yarikoptic** [comment]
Closing since original issue resolved
