### ISSUE TITLE
upcoming firewalld 0.4.0 gains ipset support

### ISSUE THREAD

**Issue by aboe76** [fail2ban/fail2ban#1290]
The upcoming 0.4.0 version of firewalld will gain ipset support which in turn can benefit fail2ban:
see: http://www.firewalld.org/2015/12/ipset-support/

new commands that can be used for creation:
firewall-cmd --permanent --new-ipset=fail2ban-<name> --type=hash:ip
firewall-cmd --add-rich-rule='rule source ipset=fail2ban-<name> drop'
firewall-cmd --reload

new commands that can be actionban:
firewalll-cmd --ipset=fail2ban-<name> --add-entry=<ip>

Only downside so far is that they have a limitation on timeout option.

please take look and see if this can be added next to the other firewalld actions.

**Comment by t-woerner** [comment]
You can also use the ipset with a timeout:
firewall-cmd --permanent --new-ipset=fail2ban- --type=hash:ip --option=timeout=300
firewall-cmd --permanent --add-rich-rule='rule source ipset=fail2ban- drop'
firewall-cmd --reload

You can then use ipset directly to add entries to the ipset like you did before.

The command "firewalll-cmd --ipset=fail2ban- --add-entry=....." is not usable on ipsets with timeouts, as entries will time out in the ipset itself and I did not want to add an extra timer for the entries to firewalld just to be able to remove the entries in firewalld also to give a correct ipset listing and feedback.

**Comment by aboe76** [comment]
@t-woerner thanks for the clarification.
