### ISSUE TITLE
nginx-http-auth does not work for empty server address

### ISSUE THREAD

**Issue by andreaskoelsch** [fail2ban/fail2ban#1296]
Hi,
The nginx-http-auth jail did not work for me so I tried a few things. The failregex has to be changed so it also works for empty server address.
```
failregex = ^ \[error\] \d+#\d+: \*\d+ user "\S+":? (password mismatch|was not found in ".*"), client: <HOST>, server: \S*, request: "\S+ \S+ HTTP/\d+\.\d+", host: "\S+"\s*$
```
Not really worth a pull request. Would be cool, if someone could fix this for everyone.

**Comment by sebres** [comment]
Can you provide a log excerpt with such failure (line)?

**Comment by andreaskoelsch** [comment]
Nevermind. I just noticed, it is already fixed here. My version was taken from the repository.
