### ISSUE TITLE
postfix-sasl: ignore "Invalid authentication mechanism"

### ISSUE THREAD

**Issue by blueyed** [fail2ban/fail2ban#1297]
Fail2ban should not consider the following entries as errors:

> Jan 14 16:18:16 elfe postfix/smtpd[14933]: warning: host[IP]: SASL CRAM-MD5 authentication failed: Invalid authentication mechanism

It should probably get ignored in https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/postfix-sasl.conf:

``` diff
diff --git i/fail2ban/filter.d/postfix-sasl.conf w/fail2ban/filter.d/postfix-sasl.conf
index 199e29b..a869539 100644
--- i/fail2ban/filter.d/postfix-sasl.conf
+++ w/fail2ban/filter.d/postfix-sasl.conf
@@ -11,7 +11,9 @@ _daemon = postfix/(submission/)?smtp(d|s)

 failregex = ^%(__prefix_line)swarning: [-._\w]+\[<HOST>\]: SASL ((?i)LOGIN|PLAIN|(?:CRAM|DIGES│
T)-MD5) authentication failed(: [ A-Za-z0-9+/:]*={0,2})?\s*$

-ignoreregex = authentication failed: Connection lost to authentication server$
+ignoreregex =
+  authentication failed: Connection lost to authentication server$
+  authentication failed: Invalid authentication mechanism$

 [Init]
```

This gets triggered for me when using https://github.com/corecode/dma, which tries CRAM-MD5 unconditionally.. :/

**Comment by sebres** [comment]
Thx for the notice, 
it may be indeed better to ignore such "failures" by default, at least as long as we don't support `successregex` for resetting of failure counter (#1243).

**Comment by blueyed** [comment]
> it may be indeed better to ignore such "failures" by default

Isn't that what I am suggesting?!
Would you achieve it in a different way?

**Comment by sebres** [comment]
> Isn't that what I am suggesting?!

Sure. That was quasi a confirmation... and we can also do it.
Interested to provide a PR? (just apply your patch, add a simple test case and changelog/thanks entry :))
> Would you achieve it in a different way?

Exactly that not. 
The way I've described above, would be not to ignore such failures (not exact this one, but I don't like to ignore at all), but to reset failure counter after succesfull login, so this will never reach a `maxretry` (if that not 1)...
Of course under condition, that we get finished #1243.

That was more a wish-flag for me (and other developer of us)...
