### ISSUE TITLE
Fail2Ban Emails

### ISSUE THREAD

**Issue by Jakrr** [fail2ban/fail2ban#1298]
I can send mail to gmail from command line and webmin etc, but it wont send emails of logs to gmail it will only send to my domain.
Any suggestions on how to fix this?

**Comment by sebres** [comment]
Can be an issue will be fixed with PR #1295 (sender missing)...
Can you test if it helps (see jail.conf in "files changed" tab) ?

**Comment by Jakrr** [comment]
This didnt work

**Comment by sebres** [comment]
Well, can you switch debugging on `loglevel = DEBUG` and wait for one ban (or produce one self with something like `logger -t 'test:auth' ...`), and then take a look in fail2ban.log, what would be wrong in command the fail2ban used for sending mail.
