### ISSUE TITLE
[Question]: apache webdav jail

### ISSUE THREAD

**Issue by sgiannulli** [fail2ban/fail2ban#1299]
Hi all,
I'm running Raspian Wheezy on my raspberry with apache 2.2 for webdav service with ssl encryption; fail2ban installed from official repository ( version 0.8.xx )
That's the jail I'm using trying to detect wrong authentication on webdav https page:
```
[apache]
enabled  = true
filter   = apache-auth
action   = iptables-multiport[name=auth, port="http,https"]
logpath  = /var/log/fail2ban.log
bantime  = 3600
maxretry = 3
```
but nothing happens
is apache-auth filter working with webdav service or a new filter needs to be witten?
Thanks in advance

**Comment by sebres** [comment]
Have you an example log-line you mean it may be a failure, that should be banned?
Because currently you've said almost nothing in the description of your issue...

**Comment by sgiannulli** [comment]
```
[Fri Jan 15 12:26:00 2016] [error] [client 206.153.121.202] user pi: authentication failure for "/": Password Mismatch
[Fri Jan 15 12:26:09 2016] [error] [client 206.153.121.202] user pi: authentication failure for "/": Password Mismatch
[Fri Jan 15 12:26:13 2016] [error] [client 206.153.121.202] user pi: authentication failure for "/": Password Mismatch
[Fri Jan 15 12:26:17 2016] [error] [client 206.153.121.202] user pi: authentication failure for "/": Password Mismatch
[Fri Jan 15 12:37:04 2016] [error] [client 206.153.121.202] user pi: authentication failure for "/": Password Mismatch
[Fri Jan 15 12:37:10 2016] [error] [client 206.153.121.202] user pi: authentication failure for "/": Password Mismatch
[Fri Jan 15 12:37:18 2016] [error] [client 206.153.121.202] user pi: authentication failure for "/": Password Mismatch
[Fri Jan 15 12:37:22 2016] [error] [client 206.153.121.202] user pi: authentication failure for "/": Password Mismatch
```
done some tests: above what my webdav_error log file reports
on fail2ban log nothing + no ip address banned

**Comment by sebres** [comment]
Well, the newest version (current master) seems to be alright, and your example-line will be matched also:
```
$ fail2ban-regex '[Fri Jan 15 12:37:22 2016] [error] [client 206.153.121.202] user pi: authentication failure for "/": Password Mismatch' <path-to-config-in-etc...>/filter.d/apache-auth

/usr/bin/python | (2, 7, '2.7.6 (default, Jun 22 2015, 17:58:13) \n[GCC 4.8.2]')

Running tests
=============
Use   failregex filter file : apache-auth, basedir: ./config
Use      single line : [Fri Jan 15 12:37:22 2016] [error] [client 206.153...

Results
=======
Failregex: 1 total
|-  #) [# of hits] regular expression
|   2) [1] ^\[\] \[(:?error|\S+:\S+)\]( \[pid \d+(:\S+ \d+)?\])? \[client <HOST>(:\d{1,5})?\] (AH01617: )?user .*? authentication failure for "\S*": Password Mismatch(, referer: \S+)?$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.00 sec]
```
0.8 is a very old version (almost everything has changed ...)

Maybe to take a look into a fail2ban.log? Some errors, something other is conspicuous?

**Comment by sgiannulli** [comment]
nothing in fail2ban.log and no errors occurred
....and I was wondering the debian official repo version could really be outdated and still "buggy"
I will remove 0.8 version and trying with this github current master version
Many thanks for your help

**Comment by sebres** [comment]
We have a database support (sqlite) since 0.9, where f2b will save the bans with failures ...
If you do not want to use it (under raspberry:), you can disable the database in your `fail2ban.local`, see https://github.com/fail2ban/fail2ban/blob/master/config/fail2ban.conf#L58

**Comment by sgiannulli** [comment]
Thanks a lot
