### ISSUE TITLE
iptables v1.4.14: unknown option "-w"

### ISSUE THREAD

**Issue by sgiannulli** [fail2ban/fail2ban#1300]
Hi all,
I've just installed 0.9.3 version and configured a jail.local file on my raspberry
after service restar my fail2ban log file is full of errors
log file is attached
can anyone help please?

Thanks
[fail2ban.pdf](https://github.com/fail2ban/fail2ban/files/92432/fail2ban.pdf)

**Comment by yarikoptic** [comment]
provide  /etc/fail2ban/action.d/iptables-common.local
with 
```
[Init]
lockingopt =
```
