### ISSUE TITLE
Nginx & phpmyadmin conf

### ISSUE THREAD

**Issue by Arnaud31500** [fail2ban/fail2ban#1301]
Hi

I'm trying to find the best way to configure a jail that would stop every people tring to find the location of my phpmyadmin folder. I'm running on nginx.

The goal is to block this kind of stuff:
XXX.XXX.0.254 - - [15/Jan/2016:20:09:38 +0100] "GET /myadmin/ HTTP/1.1" 404 39 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:43.0) Gecko/20100101 Firefox/43.0"
I'm a newbie with fail2ban and I tried to write this configuration:

badadmin = PMA|phpmyadmin|myadmin|mysql|mysqladmin|sqladmin|mypma|admin|xampp|mysqldb|mydb|db|pmadb|phpmyadmin1|phpmyadmin2|administra$
failregex =  ^\"GET /(?:%(badadmin)) HTTP/1.+\" 404$
ignoreregex =

When I activate it, it doesn't work at all and fail2ban stops sending me usual activation of the jails emails.

Any idea to help ? Any idea to build something that would also block people trying to auth phpmyadmin by brute force ? I can't find anything working on the net about nginx+phpmyadmin+fail2ban, it could be the moment to give people a solution that is working :)

Thanks a lot

Arnaud from France

**Comment by sebres** [comment]
In the current version of f2b, we have already a filter for this purposes: `nginx-botsearch`.

If you use older version, you can find the regexp in https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/nginx-botsearch.conf (and for the definitions https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/botsearch-common.conf).

Close now, please reopen if I'm wrong.
