### ISSUE TITLE
Fail2ban and arpwatch

### ISSUE THREAD

**Issue by Nassz** [fail2ban/fail2ban#1304]
Hi to all, 

If it is possible to implement arpwatch and fail2ban for preventing arp-spoofing?

**Comment by sebres** [comment]
Yes it is... (prerequisite it writes a log or something like log-file)...
To generate a correct regular expressions, we will need the log lines for the failures (or excerpt of the messages logging from arpwatch), resp. log lines should be ignored (whether some exists).

**Comment by Nassz** [comment]
from /var/log/messages on RHEL 6 
from /var/log/syslog on Debian,Ubuntu

Jan 19 19:29:13 server arpwatch: changed ethernet address 10.1.1.13 6e:b0:20:66:86:a8 (6e:b0:20:66:85:b6)
Jan 19 19:32:24 server arpwatch: changed ethernet address 10.1.1.13 6e:b0:20:66:86:8a (6e:b0:20:66:86:a8)

**Comment by sebres** [comment]
Thx,

As long as we've not implemented a new filter for arpwatch, you can easy use as new jail (just add it to your `jail.local`) in jails area (and reload fail2ban):
```
[arpwatch]
enabled = true
filter =
failregex = ^\s*\S+\s+arpwatch: changed ethernet address <HOST>
#logpath = %(syslog_local0)s
logpath = /var/log/syslog
```
Just a first shot...

**Comment by Nassz** [comment]
Thanks @sebres , 
Filter works: 

Results
=======

Failregex: 2 total
|-  #) [# of hits] regular expression
|   1) [2] ^\s*\S+\s+arpwatch: changed ethernet address <HOST>
|      10.1.1.13  Tue Jan 19 19:29:13 2016
|      10.1.1.13  Tue Jan 19 19:32:24 2016
`-

**Comment by sebres** [comment]
Well, is not really a filter - is a jail with direct specified `failregex`... 
A filter needs a bit more work.
But glad it works (was a blind shot =).

**Comment by sebres** [comment]
Thus issue is closed it as solved.
