### ISSUE TITLE
fail2ban-client status ERROR unsupported pickle protocol: 4 - is back now

### ISSUE THREAD

**Issue by davidfavor** [fail2ban/fail2ban#1305]
net4-dev# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily

net4-dev# python --version
Python 2.7.10

net4-dev# fail2ban-client --version
Fail2Ban v0.9.3.dev

Copyright (c) 2004-2008 Cyril Jaquier, 2008- Fail2Ban Contributors
Copyright of modifications held by their respective authors.
Licensed under the GNU General Public License v2 (GPL).

Written by Cyril Jaquier <cyril.jaquier@fail2ban.org>.
Many contributions by Yaroslav O. Halchenko <debian@onerussian.com>.

To recreate, I did the following:

1) apt-get purge fail2ban

2) rm -rfv /etc/fail2ban

3) apt-get install fail2ban

4) fail2ban-client status -> ERROR  unsupported pickle protocol: 4

So fresh install, with no custom jails returns protocol error.

**Comment by davidfavor** [comment]
In fact, Python docs suggest protocol number should match Python version...

So for Python 2.7.10 protocol number should be == 2.

Since there is no Python 4 yet... Unsure where protocol == 4 is coming from.

Be great if someone can tell me where to fix this in the code.

Thanks.

**Comment by yarikoptic** [comment]
Let's first make sure that no mix-match of pythons is going on

What is output of 

which fail2ban-server

which fail2ban-client

head -1 /usr/bin/fail2ban-*

on your system it should use /usr/bin/python3 I believe

**Comment by davidfavor** [comment]
Ah protocol == 4 was added in Python 3.4 per...

https://docs.python.org/3/library/pickle.html#data-stream-format

So I'm guessing, for fail2ban to work (all cases) requires changing the alternative...

net4-dev# update-alternatives --install /usr/bin/python python /usr/bin/python3.4 2
net4-dev# python --version
Python 3.4.3+

Now fail2ban-client barfs...

net4-dev# service fail2ban restart

net4-dev# fail2ban-client status
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (fail2ban 0.9.3 (/usr/lib/python3/dist-packages), Requirement.parse('fail2ban==0.9.3.dev0'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/fail2ban-client", line 4, in <module>
    __import__('pkg_resources').run_script('fail2ban==0.9.3.dev0', 'fail2ban-client')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3080, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3066, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3093, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 653, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 666, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'fail2ban==0.9.3.dev0' distribution was not found and is required by the application

**Comment by yarikoptic** [comment]
On Thu, 21 Jan 2016, David Favor wrote:

>    Ah protocol == 4 was added in Python 3.4 per...

>    https://docs.python.org/3/library/pickle.html#data-stream-format

>    So I'm guessing, for fail2ban to work (all cases) requires changing the
>    alternative...

>    net4-dev# update-alternatives --install /usr/bin/python python
>    /usr/bin/python3.4 2

NO!  

>    Traceback (most recent call last):
>    File "/usr/local/bin/fail2ban-client", line 4, in

so here you go -- you aren't running fail2ban installed from the package
but your own whatever.... hence incompatibilities etc

just return python back to default what is the default on your ubuntu

remove traces of manually installed fail2ban

be happy and close this issue 


-- 
Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by sebres** [comment]
I think it would be the same as #1259, so will close now...

**Comment by davidfavor** [comment]
Changing alternative fails in a different way.

net4-dev# update-alternatives --install /usr/bin/python python /usr/bin/python3.4 30
update-alternatives: using /usr/bin/python3.4 to provide /usr/bin/python (python) in auto mode

net4-dev# python --version
Python 3.4.3+

net4-dev# fail2ban-client status
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (fail2ban 0.9.3 (/usr/lib/python3/dist-packages), Requirement.parse('fail2ban==0.9.3.dev0'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/fail2ban-client", line 4, in <module>
    __import__('pkg_resources').run_script('fail2ban==0.9.3.dev0', 'fail2ban-client')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3080, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3066, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3093, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 653, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 666, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'fail2ban==0.9.3.dev0' distribution was not found and is required by the application

**Comment by davidfavor** [comment]
https://github.com/fail2ban/fail2ban/issues/1259 instructions do not work. I'll do this all again...

Please note the last line, which appears to be the problem...

    pkg_resources.DistributionNotFound: The 'fail2ban==0.9.3.dev0' distribution was not found and is required by the application


net4-dev# apt-get -yqq purge fail2ban

net4-dev# rm -rf /etc/fail2ban

net4-dev# apt-get -yqq install fail2ban
Selecting previously unselected package fail2ban.
(Reading database ... 142955 files and directories currently installed.)
Preparing to unpack .../fail2ban_0.9.3-1_all.deb ...
Unpacking fail2ban (0.9.3-1) ...
Processing triggers for man-db (2.7.4-1) ...
Processing triggers for systemd (225-1ubuntu9) ...
Setting up fail2ban (0.9.3-1) ...
Processing triggers for systemd (225-1ubuntu9) ...

net4-dev# python --version
Python 3.4.3+

net4-dev# fail2ban-client status
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (fail2ban 0.9.3 (/usr/lib/python3/dist-packages), Requirement.parse('fail2ban==0.9.3.dev0'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/fail2ban-client", line 4, in <module>
    __import__('pkg_resources').run_script('fail2ban==0.9.3.dev0', 'fail2ban-client')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3080, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3066, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3093, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 653, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 666, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'fail2ban==0.9.3.dev0' distribution was not found and is required by the application

**Comment by davidfavor** [comment]
Please update this ticket with how to fix this problem.

Thanks.

**Comment by sebres** [comment]
Still again - the main problem you have, that the `fail2ban-client` and `fail2ban-server` will be started using different python version (but one communicates with another using pickle proto).

The second issue - for the one python version the fail2ban was not installed at all (no fail2ban module).

You (or your system) just have not your python versions under control... (and I don't know why..., that may be possibly a maintainer issue)

The solution is technically very easy: you get your system to start both with the same python-version (but with such version, where fail2ban was installed also).
This can be made with different ways, among other things as an example using a direct path to the python (for example just with replacing `#!/usr/bin/python` with `#!/usr/bin/python2` or `#!/usr/bin/python3`).

Where it is currently installed you can check for example with:
```
/usr/bin/python3 -c 'from fail2ban.version import version; print(version)'
/usr/bin/python2 -c 'from fail2ban.version import version; print(version)'
```

And of course, during of your tests, if you switch between versions, be sure, that you have not any fail2ban still running (no python processes with fail2ban)... at a pinch just kill it.

**Comment by yarikoptic** [comment]
@davidfavor I have replied via email in https://github.com/fail2ban/fail2ban/issues/1305#issuecomment-173586800, just formatting got garbled.  You have a cocktail of fail2ban installed manually and from packages. Remove manually installed, install from packages and you should be all set

**Comment by davidfavor** [comment]
@sebres - Problem does appear to be a versioning problem.

Er... Looks like this problem is of my own making.

I was building fail2ban at a previous time so I had a version running out of both...

/usr/bin + /usr/local/bin

Embarrassing.

I shall now shuffle of into the corner + meditate upon how I could have missed such a simple problem.

Thanks for everyone's assistance.
