### ISSUE TITLE
HAProxy / CentOS (Firewalld) Filters

### ISSUE THREAD

**Issue by carose** [fail2ban/fail2ban#1307]
Hi all, 

I've been trying to find some examples of a filter/jail so that any visits through the haproxy for **/admin/index.php** but theres nothing out there.

I have F2B set up and running for **SSH on CentOS 7 (FirewallD)** and its working perfectly.

Can anyone point me in the right direction? I have no idea about Regex :-(

I have a bot that keeps trying to brute force a URL and at present I am having to manually block the IP in firewall-cmd. If Fail2Ban could do this, it would be a life saver!

**Comment by ouafnico** [comment]
Hello

I think in filter.d you can create a file like haproxy.conf:

[Definition]

failregex = ^<HOST> -.*"(GET|POST).*/admin/index.php
ignoreregex =

and create the jail:

[haproxy]
port    = http,https
logpath = /yourlogfile
bantime = yourbantime
maxretry = yourmaxretry
enabled = true

**Comment by sebres** [comment]
It is not necessary to create a filter file for a simple regexp's.
Just specify `filter =` and `failregex = ...` **direct in jail**.

Example:
```
[haproxy]
filter =
failregex = 1st-regexp-for-match...
            2nd-regexp-for-match...
            3th-regexp-for-match...
...
enabled = true
```
For all possible jail settings see documentation or https://github.com/fail2ban/fail2ban/blob/master/config/jail.conf

**Comment by sebres** [comment]
It seems to be answered, thus close.
