### ISSUE TITLE
Expand sshd jail for Centos failures

### ISSUE THREAD

**Issue by giorgio79** [fail2ban/fail2ban#1308]
Encountered this issue http://serverfault.com/questions/632774/fail2ban-on-centos-6-5-never-bans

and the posted solution works. Can we add this line to sshd.conf?

`^.*authentication failure;.*rhost=<HOST>`

**Comment by sebres** [comment]
We have already such regex, see https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/sshd.conf#L37
