### ISSUE TITLE
0.9.3 wildcard logs not working

### ISSUE THREAD

**Issue by Deepcuts** [fail2ban/fail2ban#1313]
Hello,

Using Ubuntu server 14.04.3 64bit with Fail2ban 0.9.3
Apache 2.4.7
Several domains hosted on the server.
Up until several days I used to work with the latest Fail2Ban version from Ubuntu repo 0.8.x and everything worked good.
Then, I decided it is time to upgrade to the latest version.

**Problem**
Although I enabled apache-auth, nothing seems to be logged or banned, even if there are multiple matches in logs.(by looking myself in the logs)
Because I have multiple domains, I am trying to use wildcard in log file name:
I am using  the following rule definition
`logpath = /var/log/apache2/*_error_log`

So I ran a manual regex check:

`fail2ban-regex -v "/var/log/apache2/*_log" "/etc/fail2ban/filter.d/apache-auth.conf"`
```
Lines: 1 lines, 0 ignored, 0 matched, 1 missed [processed in 0.00 sec]
|- Missed line(s):
|  /var/log/apache2/*_log
```

As you can see nothing gets matched.

I ran a manual regex check again, but without using wildcard for log file:

`fail2ban-regex -v "/var/log/apache2/realdomain.com_error_log" "/etc/fail2ban/filter.d/apache-auth.conf"
`
`Lines: 637 lines, 0 ignored, 32 matched, 605 missed [processed in 0.15 sec]`

This time it found 32 matches
I searched for changes in the 0.9.x series but found nothing has changed regarding wildcard file names.

Am I missing something or using wildcard file names doesn't work anymore?

**Comment by sebres** [comment]
First, `fail2ban-regex` works only with a string or exact one file name (in your case it think, it would be a string, because no file with this name). Still again, no wildcard for `fail2ban-regex`, but...

Second, fail2ban self normally works with wildcard in logpath. For example, I've nginx logpath like `/var/log/nginx/*error.log` and it works.

Can you provide more info? Something conspicuous in the fail2ban.log? Which backend?
What says `?sudo? fail2ban-client -d | grep apache-auth`?

**Comment by Deepcuts** [comment]
I think it had something to do with pyinotify not installing properly although I cannot say for sure.
I have removed Fail2Ban and all optional dependencies and started again from scratch and now wildcard file names are working again.
If the problem arises again, I'll be sure to increase log level and report back.
Please consider the issue closed.

**Comment by sebres** [comment]
How it works now, with pyinotify or polling?
```
?sudo? grep "' uses " /var/log/fail2ban.log | tail -n 10
```
Just to exclude that would be pyinotify (or backend) bug on some platforms?

**Comment by Deepcuts** [comment]
```
2016-01-29 18:48:32,529 fail2ban.jail           [4421]: INFO    Jail 'postfix-rbl' uses pyinotify
2016-01-29 18:48:32,570 fail2ban.jail           [4421]: INFO    Jail 'postfix-honeypot' uses pyinotify
2016-01-29 18:48:32,605 fail2ban.jail           [4421]: INFO    Jail 'sendmail-auth' uses pyinotify
2016-01-29 18:48:32,641 fail2ban.jail           [4421]: INFO    Jail 'sendmail-reject' uses pyinotify
2016-01-29 18:48:32,691 fail2ban.jail           [4421]: INFO    Jail 'dovecot' uses pyinotify
2016-01-29 18:48:32,736 fail2ban.jail           [4421]: INFO    Jail 'sieve' uses pyinotify
2016-01-29 18:48:32,771 fail2ban.jail           [4421]: INFO    Jail 'courier-auth' uses pyinotify
2016-01-29 18:48:32,806 fail2ban.jail           [4421]: INFO    Jail 'postfix-sasl' uses pyinotify
2016-01-29 18:48:32,842 fail2ban.jail           [4421]: INFO    Jail 'cyrus-imap' uses pyinotify
2016-01-29 18:48:32,878 fail2ban.jail           [4421]: INFO    Jail 'mysqld-auth' uses pyinotify

```

No mention about several other jails, like sshd or proftpd, even tho they are enabled.

**Comment by sebres** [comment]
Ok (I've just truncated with `tail` the output to the last 10 occurrences)

**Comment by dmak** [comment]
I observe the same problem (missing log lines for Apache in my case) for wildcards:
```
apache_error_log = /var/log/httpd/*error_log                                                                  
apache_access_log = /var/log/httpd/*access_log                                                                
```
How to debug the problem?
fail2ban v0.10.2.

**Comment by sebres** [comment]
> missing log lines for Apache in my case

missing where?

1. If you mean fail2ban may not consider NEW logs (created after start of fail2ban), then it is indeed still an issue in fail2ban (see  #1379), glob search takes place in client only (by start of fail2ban), so at the moment a reload of fail2ban is required to consider new logs (or switch to systemd journal).
You can obtain your current (runtime) list of files with ` fail2ban-client get "$jail" logpath`.

2. If you mean no one file is monitored or fail2ban does not recognize some lines as failures (cannot be found, does not match, etc) - follow FAQ in https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works

3. If you mean the lines are missing in mail of some mailing action (like `sendmail-whois-lines`) then see https://github.com/fail2ban/fail2ban/issues/2305#issuecomment-448342316 etc.

**Comment by dmak** [comment]
Thanks for reply. The log lines are missing in emails which are sent by fail2ban so it looks like (3) but I still I am not sure.

Successful report:
```
Subject: [Fail2Ban] apache-badbots: banned 91.97.249.120
Date: Sun, 28 Feb 2021 22:47:44 +0100

Hi,

The IP 91.97.249.120 has just been banned by Fail2Ban after 8 attempts against apache-badbots.

Here is more information about 91.97.249.120:
...
Lines containing failures of 91.97.249.120 in /var/log/apache2/*access.log
/var/log/apache2/access.log:91.97.249.120 - - [28/Feb/2021:22:47:43 +0100] "HEAD http://77.173.206.162:80/1phpmyadmin/ HTTP/1.1" 404 191 "-" "Mozilla/5.0 Jorgee"
/var/log/apache2/access.log:91.97.249.120 - - [28/Feb/2021:22:47:43 +0100] "HEAD http://77.173.206.162:80/2phpmyadmin/ HTTP/1.1" 404 190 "-" "Mozilla/5.0 Jorgee"
...
```
Problematic report (on same date):
```
Subject: [Fail2Ban] apache-noscript: banned 193.200.241.160
Date: Sun, 28 Feb 2021 21:31:07 +0100

Hi,

The IP 193.200.241.160 has just been banned by Fail2Ban after 2 attempts against apache-noscript.

Here is more information about 193.200.241.160:
...
Lines containing failures of 193.200.241.160 in /var/log/apache2/*error.log
```
However the lines are there:
```
# grep 193.200.241.160 /var/log/apache2/error.log
[Sun Feb 28 21:31:06.791149 2021] [:error] [pid 1278] [client 193.200.241.160:50650] script '/var/www/elrekt.php' not found or unable to stat
[Sun Feb 28 21:31:06.825626 2021] [:error] [pid 4221] [client 193.200.241.160:51078] script '/var/www/index.php' not found or unable to stat
```
My way of thinking is the following: if fail2ban was able to "sense" apache-noscript rule violation by listening the log, it should be able to recover corresponding lines from it.
P.S. Email template in `/etc/fail2ban/action.d/sendmail-whois-lines.conf` is the following:
```
actionban = ( printf %%b "Subject: [Fail2Ban] <name>: banned <ip>
            Date: `LC_ALL=C date +"%%a, %%d %%h %%Y %%T %%z"`
            From: <sendername> <<sender>>
            To: <dest>\n
            Hi,\n
            The IP <ip> has just been banned by Fail2Ban after <failures> attempts against <name>.\n
            Here is more information about <ip>:\n
            `/usr/bin/whois <ip> || echo missing whois program`\n\n
            Lines containing failures of <ip> in <logpath>\n";
            %(_grep_logs)s;
            printf %%b "\n
```

**Comment by sebres** [comment]
> if fail2ban was able to "sense" apache-noscript rule violation by listening the log, it should be able to recover corresponding lines from it.

Sure, and this is exactly the case with actions like `sendmail-whois-matches` using tag `<matches>` which gets directly interpolating to the values containing matched lines that caused ban.
However action `sendmail-whois-lines` uses grep to find the matches (what is a bit ugly, let alone not really performant, therefore this actions are obsolete, again see https://github.com/fail2ban/fail2ban/issues/2305#issuecomment-448342316)

[`%(_grep_logs)s` is normally substituted](https://github.com/fail2ban/fail2ban/blob/960e30cfcdae7e2c81f74046efdbff1606f9774e/config/action.d/helpers-common.conf#L7) to something like this:
```
ip="192.0.2.1"; logpath="/var/log/apache2/*error.log"
grep -m 1000 -wF "$ip" $logpath | tail -n 1000
```
where `-w` represents word boundary (selects only lines containing matches that form whole words) and  `-F` interprets pattern (IP) as a fixed string.
This seems to work in my case:
```bash
$ ip="192.0.2.1"; echo "... [client 192.0.2.1:50650] script ..." | grep -m 1000 -wF "$ip"
... [client 192.0.2.1:50650] script ...
```
I don't really know why it doesn't work on your side.
