### ISSUE TITLE
Error after upgrade to 0.9.3

### ISSUE THREAD

**Issue by joaonl** [fail2ban/fail2ban#1314]
Hi there,

Every time i get an email stating the error below: 

```
/etc/cron.daily/logrotate:
Traceback (most recent call last):
  File "/usr/local/bin/fail2ban-client", line 5, in <module>
    pkg_resources.run_script('fail2ban==0.9.3', 'fail2ban-client')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/fail2ban-0.9.3-py2.7.egg/EGG-INFO/scripts/fail2ban-client", line 470, in <module>
    if client.start(sys.argv):
  File "/usr/local/lib/python2.7/dist-packages/fail2ban-0.9.3-py2.7.egg/EGG-INFO/scripts/fail2ban-client", line 440, in start
    return self.__processCommand(args)
  File "/usr/local/lib/python2.7/dist-packages/fail2ban-0.9.3-py2.7.egg/EGG-INFO/scripts/fail2ban-client", line 281, in __processCommand
    return self.__processCmd([cmd])
  File "/usr/local/lib/python2.7/dist-packages/fail2ban-0.9.3-py2.7.egg/EGG-INFO/scripts/fail2ban-client", line 185, in __processCmd
    client.close()
  File "/usr/local/lib/python2.7/dist-packages/fail2ban-0.9.3-py2.7.egg/fail2ban/client/csocket.py", line 55, in close
    self.__csock.sendall(CSPROTO.CLOSE + CSPROTO.END)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 32] Broken pipe
error: error running non-shared postrotate script for /var/log/fail2ban.log of '/var/log/fail2ban.log '
run-parts: /etc/cron.daily/logrotate exited with return code 1
```

Any idea what i could be?

Cheers,

**Comment by sebres** [comment]
Can you check you have postrotate equal `/usr/bin/fail2ban-client flushlogs 1>/dev/null || true` configured in logrotate for fail2ban.

Imho, it is directly not a bug, just the server closes a socket faster as the client "expects" it... 
But by `... || true` you should never get this error.
Can you find and provide here a log excerpt from fail2ban.log, that corresponds to this time?
Or just execute following and look hereafter at tail of fail2ban.log:
```
?sudo? /usr/bin/fail2ban-client flushlogs 1>/dev/null || true
```

**Comment by joaonl** [comment]
Hi Sebres,

I reinstalled Fail2Ban and will wait untill tomorrow to see if it occurs again.

This is now in the logrotate:

`
#!/bin/sh

# Clean non existent log file entries from status file
cd /var/lib/logrotate
test -e status || touch status
head -1 status > status.clean
sed 's/"//g' status | while read logfile date
do
    [ -e "$logfile" ] && echo "\"$logfile\" $date"
done >> status.clean
mv status.clean status

test -x /usr/sbin/logrotate || exit 0
/usr/sbin/logrotate /etc/logrotate.conf

`

**Comment by sebres** [comment]
I mean the config of logrotate for fail2ban, I think it should be in `/etc/logrotate.d/fail2ban`

**Comment by joaonl** [comment]
Sorry, got it now.

`/var/log/fail2ban.log {
   
    weekly
    rotate 4
    compress

    delaycompress
    missingok
    postrotate
	fail2ban-client set logtarget /var/log/fail2ban.log >/dev/null
    endscript

    # If fail2ban runs as non-root it still needs to have write access
    # to logfiles.
    # create 640 fail2ban adm
    create 640 root adm
}
`

**Comment by sebres** [comment]
Well, it seems to be old (maintainer) version... Please update a postrotate to:
https://github.com/fail2ban/fail2ban/blob/master/files/fail2ban-logrotate#L14

**Comment by joaonl** [comment]
Thanks, but I think something went wrong in the install process, if I try the command from terminal the log file shows:

`2016-01-31 16:33:19,846 fail2ban.comm   : WARNING Command ['flushlogs'] has failed. Received Exception('Invalid command',)`

Could it be something else?

**Comment by sebres** [comment]
Oh, strange, your version seems to be older (it was firstly introduced in b5d6310d281c1c45112ffb285c77a858da99d6f6 two years ago...)

Well, if you use any stock version, it will be a issue of the maintainer your linux distribution...
Close now.

**Comment by joaonl** [comment]
Hi Sebres,

I used apt-get for fail2ban, looks like the version there is outdated.
I removed it and installed from github.

Working great now. Thank you for the support and tip.

Cheers,
