### ISSUE TITLE
What is the deal with dbpurgeage?

### ISSUE THREAD

**Issue by powerpbx** [fail2ban/fail2ban#1315]
Not necessarily a bug.  I have not changed dbpurgeage from default so it is still 86400 in fail2ban.conf and not overriden anywhere else.

However, I have global bantime set to 2592000

Looking at /var/lib/fail2ban/fail2ban.sqlite3 it is retaining the last 60days worth of data.  That is just fine.  My question is why?  I did a search and could not find any info about this.  Everything I have read says it should only be saving the last 86400 seconds worth of data.  Is this a bug or a feature?  If a feature where is the info describing this?

**Comment by sebres** [comment]
see https://github.com/fail2ban/fail2ban/issues/1316#issuecomment-178796884
