### ISSUE TITLE
apache-fakegooglebot: whitelist

### ISSUE THREAD

**Issue by jomu78** [fail2ban/fail2ban#1318]
Some ips are banned, because they report to be GoogleBot compatible - e.g. OnPage.org uses agent "OnPageBot (compatible; Googlebot 2.1; +https://onpage.org/bot/)". The current ignore command searches only for Googlebot and by this blocks the above agent whereby the above agent does not really fake to be Google.  

I tried to add a ignore regex but this seems to be ignored when ignore command is set. So enabling the ignore regex, revising the filter inside the ignore command or a white list would help.

**Comment by jomu78** [comment]
for the moment I added a quick hack into my ignorecommands/apache-fakegooglebot

```
def is_googlebot(ip):
    import re
    from fail2ban.server.filter import DNSUtils

    #
    # check for whitelisted ips
    #
    white_list = ['xxx.xxx.xxx.xxx', 'xxx.xxx.xxx.xxx']
    if any(ip in s for s in white_list):
      sys.exit(0)


    host = DNSUtils.ipToName(ip)
    sys.exit(0 if (host and re.match('crawl-.*\.googlebot\.com', host)) else 1)

```

**Comment by sebres** [comment]
Can be realized via `ignoreip` (additionally to `ignorecommand`):
```
# file: jail.local
[apache-fakegooglebot]
ignoreip = 192.0.2.1 192.0.2.2 192.0.2.3 some.dns.example.org
```
Addresses matched `ignoreip` will be ignored immediately without execution of `ignorecommand`.
