### ISSUE TITLE
Cannot unban IP

### ISSUE THREAD

**Issue by vsespb** [fail2ban/fail2ban#132]
Fail2Ban 0.8.6 Ubuntu 12.04

Cannot get it to unban single IP

```
# fail2ban-client status
Status
|- Number of jail:  2
`- Jail list:       ssh, nginx-naxsi
```

```
# fail2ban-client -vvv get nginx-naxsi  actionunban 10.0.2.2
DEBUG  Reading /etc/fail2ban/fail2ban
DEBUG  Reading files: ['/etc/fail2ban/fail2ban.conf', '/etc/fail2ban/fail2ban.local']
INFO   Using socket file /var/run/fail2ban/fail2ban.sock
DEBUG  NOK: ()
DEBUG  Beautify (error) KeyError() with ['get', 'nginx-naxsi', 'actionunban', '10.0.2.2']
```

**Comment by cjella** [comment]
As they have already explained, in old versions of fail2ban it is complicated (not impossible) to unban an IP, looking for solutions I came here and I want to leave this for those who have a problem like this: Solution
Run as sudo or root: **iptables -nvL** will appear something like the following:
cjm# iptables -nvL
Chain INPUT (policy ACCEPT 1360K packets, 1009M bytes)
 pkts bytes target     prot opt in     out     source               destination         
25878 3218K fail2ban-ssh  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           multiport dports 2022 
25826 3215K fail2ban-ssh-ddos  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           multiport dports 2022 

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 1043K packets, 1308M bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain fail2ban-ssh (1 references)
 pkts bytes target     prot opt in     out     source               destination         
   36  2160 DROP       all  --  *      *       200.134.103.100      0.0.0.0/0           
    0     0 DROP       all  --  *      *       45.146.165.72        0.0.0.0/0           
    3   152 DROP       all  --  *      *       45.135.232.165       0.0.0.0/0           
   13   748 DROP       all  --  *      *       218.31.39.157        0.0.0.0/0           
25826 3215K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain fail2ban-ssh-ddos (1 references)
 pkts bytes target     prot opt in     out     source               destination         
25826 3215K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           
We want to unban the IP ** 200.134.103.100 ** that is in the fail2ban ssh cage, so we count the lines, in this case it is line 1 that contains the IP that we want to unban. For this we execute the following command:
cjm# iptables -D fail2ban-ssh 1
Remember that number 1 is the line where the IP to unban is.

Sorry my bad english
