### ISSUE TITLE
firewallcmd-ipset fails to create ipset for large timeouts

### ISSUE THREAD

**Issue by jerlich** [fail2ban/fail2ban#1320]
I tried to increase the `bantime` to 1 year (in seconds). This prevented the ipset from being created and resulted in the following error:

`Feb 09 17:23:50 <HOSTNAME> firewalld[23958]: 2016-02-09 17:23:50 ERROR: COMMAND_FAILED: '/sbin/iptables -t filter -I INPUT_direct 1 -p tcp -m multiport --dports ssh -m set --match-set fail2ban-sshd src -j REJECT --reject-with icmp-port-unreachable' failed: iptables v1.4.21: Set fail2ban-sshd doesn't exist.`

Changing the `bantime` back to 1 day solved the problem

**Comment by jerlich** [comment]
The max timeout is 4294967
`# ipset create foo hash:ip timeout 9999999999
ipset v6.19: Syntax error: '9999999999' is out of range 0-4294967
`

**Comment by sebres** [comment]
Some actions used by fail2ban, expect the timeout (bantime) will be passed to the tool on start or on ban. I thought firewallcmd with ipset had 48h max time.

You can use an `iptables-multiport` or another ban action, that supports from your system, that will use internal mechanism to control a banning (and thus also a ban-time).

The list of all actions, whose bantime will controled by tool (firewall) self:
`grep -l "action.*<bantime>" /etc/fail2ban/action.d/*.conf`

The list of actions, whose bantime will controled by fail2ban only:
`grep -L "action.*<bantime>" /etc/fail2ban/action.d/*.conf`

**Comment by jerlich** [comment]
could there be some way to more clearly indicate that an error occurred and to pass the error message along? 
`journalctl -xe | grep ERROR` only found the `iptables` error not the original `ipset` error.

**Comment by sebres** [comment]
Fail2ban logs only errors returned from action direct in stderr or stdout.
I don't know how we can log some error, that will apparently eaten inside the firewall self.
