### ISSUE TITLE
Error trying to unban after reloading iptables

### ISSUE THREAD

**Issue by fastest963** [fail2ban/fail2ban#1323]
After I added the `PartOf=` to the service file, fail2ban gets restarted along with iptables and everything works file. But neither `PartOf` or `Requires` reloads when iptables is reloaded and so you need to add

```
ReloadPropagatedFrom=iptables.service firewalld.service
```

But after I added that, I noticed fail2ban was erroring when trying to unban and remove the jails on reload. Presumably because iptables has already reloaded and flushed the rules (and table). Besides failing to unban, it actually reloads fine otherwise.

Here are the errors:

```
Feb 16 21:56:11 fail2ban.server[797]: INFO Stopping all jails
Feb 16 21:56:11 fail2ban.actions[797]: NOTICE [sshd-long] Unban 185.110.132.54
Feb 16 21:56:11 fail2ban.action[797]: ERROR iptables -w -n -L INPUT | grep -q 'f2b-sshd-long[ \t]' -- stdout: ''
Feb 16 21:56:11 fail2ban.action[797]: ERROR iptables -w -n -L INPUT | grep -q 'f2b-sshd-long[ \t]' -- stderr: ''
Feb 16 21:56:11 fail2ban.action[797]: ERROR iptables -w -n -L INPUT | grep -q 'f2b-sshd-long[ \t]' -- returned 1
Feb 16 21:56:11 fail2ban.CommandAction[797]: ERROR Invariant check failed. Trying to restore a sane environment
Feb 16 21:56:11 fail2ban.action[797]: ERROR iptables -w -D INPUT -p tcp -m multiport --dports ssh -j f2b-sshd-long
                                                         iptables -w -F f2b-sshd-long
                                                         iptables -w -X f2b-sshd-long -- stdout: ''
Feb 16 21:56:11 fail2ban.action[797]: ERROR iptables -w -D INPUT -p tcp -m multiport --dports ssh -j f2b-sshd-long
                                                         iptables -w -F f2b-sshd-long
                                                         iptables -w -X f2b-sshd-long -- stderr: "iptables v1.4.21: Couldn't load target `f2b-sshd-long':No such file or directory\n\nTry `iptables -h' or 'iptables --help' for more information.\niptables: No chain/target/match by that name.\niptables: No chain/target/match by that name.\n"
Feb 16 21:56:11 fail2ban.action[797]: ERROR iptables -w -D INPUT -p tcp -m multiport --dports ssh -j f2b-sshd-long
                                                         iptables -w -F f2b-sshd-long
                                                         iptables -w -X f2b-sshd-long -- returned 1
Feb 16 21:56:11 fail2ban.actions[797]: ERROR Failed to execute unban jail 'sshd-long' action 'iptables-multiport' info '{'matches': ... , 'time': 1455659534.892837, 'failures': 165}': Error stopping action
```

Can the unban action check to see if the table is there before trying to unban and if its not, just skip any unbanning?

**Comment by chiWahWong** [comment]
The problem I have is very similar to yours. I am trying this solution (https://github.com/fail2ban/fail2ban/issues/1227) now and tomorrow I should know if this solution work or not.

**Comment by chiWahWong** [comment]
https://sourceforge.net/p/fail2ban/bugs/47/

**Comment by iqlinuxadmin** [comment]
I too have this problem and would love to see it patched.

**Comment by sebres** [comment]
> Can the unban action check to see if the table is there before trying to unban and if its not, just skip any unbanning?

Hmm... would be really controversial enhancement:
- either one want to see an error if unban failed (e. g. also if chain/table is missing);
- or another (like you) want to silently ignore it...

I link it to #980 and will think about this issue in further development in gh-980.
