### ISSUE TITLE
nginx syslog server

### ISSUE THREAD

**Issue by TheDeadCode** [fail2ban/fail2ban#1335]
My nginx log target goes as follow:
`access_log syslog:server=127.0.0.1:3423 main;`

Is it possible for `logpath` to listen on that port, or listen to a log unix socket from nginx?

**Comment by sebres** [comment]
If that will be accessible by listening of systemd journal, then I think - yes (I don't know about the port)...
Just try to specify for this jail:
```bash
[nginx-...]
logpath = 
backend = systemd
# set correct parameters for the journalmatch ...
journalmatch = _COMM=... + _SYSTEMD_UNIT=... _UID=...
```

Read more https://github.com/fail2ban/fail2ban/blob/master/config/jail.conf#L68
