### ISSUE TITLE
Fai2ban consumes 100% CPU in debian wheezy

### ISSUE THREAD

**Issue by zenny** [fail2ban/fail2ban#1339]
Encountered a similar situation like the guy at the thread https://sourceforge.net/p/fail2ban/mailman/message/33228397/, but in Debian wheezy:

> dpkg -l | grep ii | grep fail2ban    
> ii  fail2ban                         0.8.6-3wheezy3                all          ban hosts that cause multiple authentication errors

top shows fail2ban using all CPU (minimum 95% to 100%):

> 8886 root      20   0 51800 5872 2104 S  95.4  0.2   6:15.09 fail2ban-server

Fail2ban log with loglevel=4 outputs consistent lines that read as follows:

> 2016-02-29 11:23:42,988 fail2ban.filter : DEBUG  Processing line with time:1435595504.0 and ip:195.154.154.42
> 2016-02-29 11:23:42,988 fail2ban.filter : DEBUG  Ignore line since time 1435595504.0 < 1456741422.99 - 600
> 2016-02-29 11:23:42,989 fail2ban.filter : DEBUG  Processing line with time:1435595504.0 and ip:195.154.154.42
> 2016-02-29 11:23:42,990 fail2ban.filter : DEBUG  Ignore line since time 1435595504.0 < 1456741422.99 - 600
> 2016-02-29 11:23:42,991 fail2ban.filter : DEBUG  Processing line with time:1435595504.0 and ip:195.154.154.42

There is no special configs except for asterisk server.

At loglevel=3, the log reads like:

> tail -f /var/log/fail2ban.log
> 2016-02-29 11:26:17,263 fail2ban.filter : INFO   Set findtime = 600
> 2016-02-29 11:26:17,264 fail2ban.actions: INFO   Set banTime = 600
> 2016-02-29 11:26:17,334 fail2ban.jail   : INFO   Creating new jail 'asterisk11-iptables'
> 2016-02-29 11:26:17,334 fail2ban.jail   : INFO   Jail 'asterisk11-iptables' uses Gamin
> 2016-02-29 11:26:17,337 fail2ban.filter : INFO   Added logfile = /var/log/asterisk/fail2ban2
> 2016-02-29 11:26:17,339 fail2ban.filter : INFO   Set maxRetry = 3
> 2016-02-29 11:26:17,342 fail2ban.filter : INFO   Set findtime = 600
> 2016-02-29 11:26:17,343 fail2ban.actions: INFO   Set banTime = 600
> 2016-02-29 11:26:17,355 fail2ban.jail   : INFO   Jail 'ssh' started
> 2016-02-29 11:26:17,361 fail2ban.jail   : INFO   Jail 'asterisk11-iptables' started

Appreciate any input how to reduce the high CPU devouring by fail2ban?!

**Comment by sebres** [comment]
- logrotate large log files 
- you can try my branch #1321 (https://github.com/sebres/fail2ban/tree/f2b-perfom-prepare-716-cs). But it will very probably remain as fork (too many changes)

**Comment by zenny** [comment]
> you can try my branch #1321 (https://github.com/sebres/fail2ban/tree/f2b-perfom-prepare-716-cs). But it will very probably remain as fork (too many changes)

Yep this worked for me. Thanks!

**Comment by sebres** [comment]
Glad it works... 
I'll close the issue, still we have no another solution (except using logrotate or `tail`) relating to the current repository, as long as I (or someone else) will not find any opportunity to "merge" corresponding part of my fork here.

**Comment by larssn** [comment]
Could you outline what the changes are? We're looking to use this in a production setup, as we've had high CPU when it comes to big log files (like under a DDOS attack).

**Comment by sebres** [comment]
Please take a look on our new 10th branch (pre-released), see #1410 or release info for details
