### ISSUE TITLE
Unable to match nginx logs

### ISSUE THREAD

**Issue by cortopy** [fail2ban/fail2ban#1347]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.9.3
- OS, including release name/version: CentOS 7
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Not even the simplest regex matches nginx error log. As per the last section below, configuration and encoding issues have already been discarded as possible culprits.

My strategy to create the jail was to go from a regex which is too generic to the more specific. However, even writing specific strings seems not to work.

#### Steps to reproduce

1. Create a jail with the following

```
failregex = ^.*access forbidden by rule.*<HOST>.*$
```

2. Run: 

```
fail2ban-regex /var/log/nginx/error.log /etc/fail2ban/filter.d/nginx-conf-spider.conf
```

#### Expected behavior

Entries in the log like the following should be matched:

```
2016/03/07 16:32:44 [error] 31215#0: *3142 access forbidden by rule, client: 1.123.456.789, server: example.com, request: "GET /path/to/file HTTP/1.1", host: "server.com"

```

However no matches are reported by fail2ban-regex. Reloading fail2ban doesn't work either

#### Observed behavior

There should be tens of matches. The only way to get any match is with the following regex. Since a catch-all regex works on the log file, I have discarded any possible issues with encoding or configuration.

```
failregex = ^.*<HOST>.*$
```
This 'catch-all' regex returns the following report

```
Running tests
=============

Use   failregex filter file : nginx-conf-spider, basedir: /etc/fail2ban
Use         log file : /var/log/nginx/error.log
Use         encoding : UTF-8


Results
=======

Failregex: 682 total
|-  #) [# of hits] regular expression
|   1) [682] ^.*<HOST>.*$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [23800] Year(?P<_sep>[-/.])Month(?P=_sep)Day 24hour:Minute:Second(?:,Microseconds)?
`-

Lines: 23866 lines, 0 ignored, 682 matched, 23184 missed [processed in 248.22 sec]
Missed line(s): too many to print.  Use --print-all-missed to print all 23184 lines
```

**Comment by sebres** [comment]
The IP in the log line is wrong (`1.123.456.789`) please test it with correct IP.

**Comment by sebres** [comment]
In addition I've extended the filter `nginx-http-auth` with regexp (second line), that you need, and it works successful by the line from your excerpt.
```
failregex = ^ \[error\] \d+#\d+: \*\d+ user "\S+":? (password mismatch|was not found in ".*"), client: <HOST>, server: \S*, request: "\S+ \S+ HTTP/\d+\.\d+", host: "\S+"(, referrer: "\S+")?\s*$
            ^ \[error\] \d+#\d+: \*\d+ access forbidden by rule, client: <HOST>,
```

Because it is ahead anchored (and has neither greedy nor non-greedy catch-alls, you don't really need something after `<HOST>,`

**Important:** using ahead anchor `^` you should allways match **all** from begin, excerpt the datepattern that will be excluded from line before match...

**Comment by cortopy** [comment]
Mathing the first part worked, thanks for that! I wasn't aware of fail2ban managing date and time so efficiently

**Comment by andyforceno** [comment]
In case anyone comes across as I did, the regex above didn't work on my Ubuntu 17.10 server. However, this regex does work:

`^ \[error\] \d+#\d+: \*\d+ directory .* is forbidden, client: <HOST>,`

**Comment by sebres** [comment]
> `^ \[error\] \d+#\d+: \*\d+ directory .* is forbidden, client: <HOST>,`

JFYI, it is very very vulnerable regex... Better change `.*` into `\S*` if you don't use directories with spaces, otherwise `.*?`, which is although better as greedy catch-all (but can sometimes be really slow).

**Comment by SpareSimian** [comment]
I don't see the "access forbidden by rule" regex in master. Is it in a branch? I'm looking here:
https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/nginx-http-auth.conf

**Comment by sebres** [comment]
No (this RE was never in the filter). 
The issue here was about "RE doesn't match" (and it was not correct due to other reasons).

You can add your own RE either to `filter.d/nginx-http-auth.local` or directly to jail:
```
failregex = %(known/failregex)s
            ^ \[error\] \d+#\d+: \S+ access forbidden by rule, client: <HOST>,
```

**Comment by SpareSimian** [comment]
I added it to my .local filter and it's now catching them. I'd suggest adding that to the stock filter. Do you need a new issue for that? I'm now monitoring my logs to see if any other patterns should be added.

**Comment by sebres** [comment]
One can surely make a new filter request (issue) for all that. But we'd need examples of log messages.
