### ISSUE TITLE
mysql log path for fedora (Fedora 23 SE)

### ISSUE THREAD

**Issue by GitzJoey** [fail2ban/fail2ban#1354]
### Environment:
Fedora 23 Server Edition
Fail2Ban installed via OS/distribution mechanisms

### The issue:
I know it override-able via path-overrides.local but it would be better since the paths file already specific to each os, The correct log path for mysql, for fedora distributions is /var/log/mysqld.log

so changes required in file paths-fedora.conf

**Comment by sebres** [comment]
The question is - it also applies to most another versions of Fedora?

**Comment by GitzJoey** [comment]
been using fedora since 17, the actual log always in /var/log/mysqld.log, 
i think its also depend on the mysql version, i'm using mysql since version 5.6 (now 5.7.11) and the log in fedora dist is always /var/log/mysqld.log

require other to verify.
thanks for the fast attention, appreciate it :)

**Comment by opoplawski** [comment]
Another twist is that the default DB in Fedora is actually mariadb and that logs to /var/log/mariadb/mariadb.log.

**Comment by weberhofer** [comment]
Isn't mysql/mariadb using the systemd-backend on fedora? This is globally set in paths-fedora.conf and should work with the latest version 0.9.4.

**Comment by opoplawski** [comment]
No, mysql/mariadb do not log the failed login attempts to the journal, only to the log file.

**Comment by sebres** [comment]
fixed in #1356
