### ISSUE TITLE
filter.d/monit.conf failregex values do not match what monit outputs anymore

### ISSUE THREAD

**Issue by jerrac** [fail2ban/fail2ban#1355]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): v0.8.11
- OS, including release name/version: Ubuntu 14.04.3
- [x ] Fail2Ban installed via OS/distribution mechanisms
- [x ] You have not applied any additional foreign patches to the codebase

### The issue:
The checks in https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/monit.conf do not appear to match the messages that up to date versions of monit log. See: https://bitbucket.org/tildeslash/monit/src/6905335aa903d425cae732cab766bd88ea5f2d1d/src/http/processor.c?at=master&fileviewer=file-view-default#processor.c-728

Example entries monit sent to syslog:

    Mar  9 09:18:28 hostname monit[5731]: HttpRequest: access denied -- client 10.10.10.10: missing or invalid Authorization header
    Mar  9 09:18:32 hostname monit[5731]: HttpRequest: access denied -- client 10.10.10.10: unknown user 'testuserasdf'
    Mar  9 09:18:51 hostname monit[5731]: HttpRequest: access denied -- client 10.10.10.10: wrong password for user 'testuser'
    Mar  9 09:19:00 hostname monit[5731]: HttpRequest: access denied -- client 10.10.10.10: unknown user ''
    Mar  9 09:19:09 hostname monit[5731]: HttpRequest: access denied -- client 10.10.10.10: wrong password for user 'testuser'
    Mar  9 09:19:15 hostname monit[5731]: HttpRequest: access denied -- client 10.10.10.10: missing or invalid Authorization header

For now I'll see about writing my own custom filter.

**Comment by sebres** [comment]
@jerrac Thanks. As long as not merged, you can try the filter from branch/PR above
