### ISSUE TITLE
Sendmail notifications not RFC 5322 compliant issue

### ISSUE THREAD

**Issue by nimuytan** [fail2ban/fail2ban#1361]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): _Fail2Ban v0.8.14_
- OS, including release name/version: _CentOS release 5.11 (Final) Kernel: 2.6.32-042stab088.4_
- [ x] Fail2Ban installed via OS/distribution mechanisms
- [ x] You have not applied any additional foreign patches to the codebase
- [ x] Some customizations were done to the configuration (provide details below is so)

### The issue:
Basically I can't use a gmail account to send the notifications since I'm receiving the following message:

Mymail@gmail.com F=<fail2ban@myserver.com> P=<fail2ban@myserver.com> R=lookuphost T=remote_smtp: SMTP error from remote mail server after end of data: host gmail-smtp-in.l.google.com [64.233.186.26]: 550-5.7.1 [my_public_IP      11] Our system has detected that this message is not\n550-5.7.1 RFC 5322 compliant. To reduce the amount of spam sent to Gmail, this\n550-5.7.1 message has been blocked. Please review\n550 5.7.1  RFC 5322 specifications for more information. 9si2964841vko.136 - gsmtp

_Summary here_

#### Steps to reproduce
I just configured the jail.local with my email account and the port for the [ssh-iptables]:

action   = iptables[name=SSH, port=1891, protocol=tcp]
           sendmail-whois[name=SSH, dest=myemail@gmail.com, sender=fail2ban@myserver.com, sendername="Fail2Ban"]

#### Expected behavior
I should receive the notifications via email
#### Observed behavior
I get in the logs the RFC 5322 compliant message.
#### Any additional information

I know the sendmail is working because if I change the email with my corporate email account (from o365) I start receiving the notifications.

The weird part is this:
If I enable the debug, I can check from the log the generated printf message to sendmail the email:
```
printf %b "Subject: [Fail2Ban] SSH: started on `uname -n`
Date: `LC_TIME=C date -u +"%a, %d %h %Y %T +0000"`
From: Fail2Ban <fail2ban@myserver.com>
To: myemail@gmail.com\n
Hi,\n
The jail SSH has been started successfully.\n
Regards,\n
Fail2Ban" | /usr/sbin/sendmail -f fail2ban@myserver.com myemail@gmail.com
```
If try that on the terminal, I receive the message successfully.... so I lost I don't know what to check right now...

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
Please provide (forgotten) 2 lines:
- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version:

<sub>We will be very grateful, if your problem was described as completely as possible ...</sub>

**Comment by nimuytan** [comment]
Thanks for the prompt response:
-Fail2Ban v0.8.14 
-CentOS release 5.11 (Final) Kernel: 2.6.32-042stab088.4

**Comment by sebres** [comment]
Well, v0.8.14 is too old, so it would not fixed here.
BTW, in 0.9 (master) not reproducible for me;

You've 2 options:
- to achieve support by maintainers of CentOS resp. fail2ban for CentOS (I really don't know why all use this old version);
- to try the newest release of 0.9 (resp. master branch)

Closed now, please reopen if same issue occurs in the mainline version also.
