### ISSUE TITLE
Apache default vhost

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#1363]
Maybe you would also like to ban vulnerability scanners ~~hitting~~ hammering you default vhost.

apache-default.local

```
[Definition]

failregex = ^<HOST> \S+ \S+ \[\] ".+" [345]\d{2} \d+ ".+" ".+"$

ignoreregex = ^<HOST> \S+ \S+ \[\] "GET /robots\.txt HTTP/[0-9.]+" 200 \d{3} ".+" ".+"$
              ^<HOST> \S+ \S+ \[\] "-" 408 0 "-" "-"$

# Author: Viktor Szépe
```

jail.local

```
[apache-default]
enabled  = true
logpath  = /var/log/apache2/access.log
maxretry = 3
bantime  = 86400 ; 24h
```

**Comment by sebres** [comment]
You will certainly replace `\d{3}` with something like `[345]\d{2}`... (mean error case:)))

In addition we have special filters like apache-botsearch.conf (and other derivates of botsearch-common.conf like nging-botsearch.conf) for such purposes...

BTW. Such all-catching filters may be dangerous, for example see https://github.com/fail2ban/fail2ban/pull/1070#issuecomment-113232258

**Comment by szepeviktor** [comment]
Thank you.
I am aware of that. I get emails of every ban to my personal email box.

Maybe I haven't mentioned:
```apache
    # "Bad Request" for everyone, only robots.txt is allowed
    RewriteCond "%{REQUEST_URI}" "!=/robots.txt"
    RewriteRule "^" - [R=400]
```

**Comment by sebres** [comment]
close as howto (no issue)
