### ISSUE TITLE
/etc/init.d/fail2ban: line 34: 19182 Hangup   ${FAIL2BAN} -x start > /dev/null

### ISSUE THREAD

**Issue by VinceIH** [fail2ban/fail2ban#1377]
### Environment:

 Fail2Ban version : Fail2Ban v0.9.3
 OS : CentOS release 6.7 (Final) -- cPanel server
 Fail2Ban installed via yum
 Not applied any additional foreign patches to the codebase
 Some customizations were done to the configuration (provided details below is so)

Added the below jail stanza to jail.conf
```
[apache-wp-login]
enabled = true
action = csf-ip-deny[name=wp-login]
filter = apache-wp-login
logpath = /usr/local/apache/domlogs*/*.*
maxretry = 5
```

Added the below action to block the IP's in csf firewall.
```
[Definition]
actionstart =
actionstop =
actioncheck =
actionban = csf -d <ip> Added by DoS mitigation for <name> attack
actionunban = csf -dr <ip>
```

### The issue:

Hi,

I have installed fail2ban in a centos6-cpanel container residing in a OpenVZ node server. Since this is a cPanel server the logpath should be /usr/local/apache/domlogs/ ,since each domain have its own log under this folder. The server is having around 1600 websites and there is that much logs on the mentioned folder. 

The issue is that the restart take too much time and after few hours it shows the below error in command shell

```
/etc/init.d/fail2ban: line 34: 19182 Hangup                  ${FAIL2BAN} -x start > /dev/null
```

#### Steps to reproduce

Restart fail2ban service .

#### Any customizations done to /etc/fail2ban/ configuration

```
[apache-wp-login]
enabled = true
action = csf-ip-deny[name=wp-login]
filter = apache-wp-login
logpath = /usr/local/apache/domlogs*/*.*
maxretry = 5
```

Added the below action to block the IP's in csf firewall.
```
[Definition]
actionstart =
actionstop =
actioncheck =
actionban = csf -d <ip> Added by DoS mitigation for <name> attack
actionunban = csf -dr <ip>
```

#### Relevant parts of /var/log/fail2ban.log file:

Below is a sample log generated when fail2ban starts. The same is generated for all the domains and no particular errors were reported when the error occurs. The log just stops.

```
2016-03-30 03:56:45,281 fail2ban.filter         [9917]: INFO    Added logfile = /usr/local/apache/domlogs/domain.log
2016-03-30 03:56:45,282 fail2ban.filterpyinotify[9917]: DEBUG   Added file watcher for /usr/local/apache/domlogs/domain.log
2016-03-30 03:56:45,285 fail2ban.datedetector   [9917]: DEBUG   Sorting the template list
2016-03-30 03:56:45,285 fail2ban.datedetector   [9917]: DEBUG   Winning template: (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)? with 0 hits
2016-03-30 03:56:51,585 fail2ban.transmitter    [9917]: DEBUG   Command: ['set', 'apache-wp-login', 'addlogpath', '/usr/local/apache/domlogs/domain.com', 'head']
```

**Comment by sebres** [comment]
Several similar issues occur if the log files are too large (missing or wrong log-rotation). 
In the case you have 2 options: log-rotate or append to the logpath option a `tail` parameter at end of line.

Another issues (I rememer me one of which was almost exact like yours) occur if the log files contain a long resp. inappropriate line(s) where the regular expression stagnate. If you have some own failregex, please check your expressions.
Another one similar would be #1173 (however for older fail2ban version).

I've fixed several performance issues (up to hangup of f2b) in my future branch "f2b-perfom-prepare-716-cs".
Just to be sure that would be a known issue can you please test a newest version from here "https://github.com/sebres/fail2ban/tree/f2b-perfom-prepare-716-cs".

**Comment by VinceIH** [comment]
Hi Sebres,

Thank you for the information.

I would like to know if there is any way to exclude some particular type of logs from the directory in logpath. As I have already said , individual logs are for each domain in this folder.

logpath = /usr/local/apache/domlogs/.*

Is there anything I can add to the particular jail stanza in jail.conf so that it won't read the below type of logs ?

/usr/local/apache/domlogs/domain.com-bytes_log

root@server [/usr/local/apache/domlogs]# ll *bytes_log* |wc -l
1733

**Comment by sebres** [comment]
> Is there anything I can add to the particular jail ...

Unfortunately not, we have not an ingnore expression for logpath. Possible write precise positive expression?

**Comment by VinceIH** [comment]
Sorry, doesn't have any idea about precise positive expression  : (

**Comment by sebres** [comment]
unix glob?

BTW: I don't understand why this should be found by your pattern `/usr/local/apache/domlogs/.*`

Please execute:
```bash
sudo python -c "import glob; print('\n'.join(glob.glob('/usr/local/apache/domlogs/.*')))"
```
I believe you will not find there... (resp. find only "hidden" files begin with `.`)

**Comment by VinceIH** [comment]
Hi  Sebres ,

I appreciate your help in this case.

Executed the python command ,but it didn't give any results.

====
root@server [~]# python -c "import glob; print('\n'.join(glob.glob('/usr/local/apache/domlogs/.*')))"

root@server [~]# 
====

**Comment by sebres** [comment]
Well, as I already said, it looking for files begin with `.` only (according to unix glob) and you did not have such a files...

**Comment by VinceIH** [comment]
Okay. Understood.

Since there is currently no way to ignore logs, I am going ahead with Apache error log itself. We have modsecurity installed in our server and failed attempts will be reported to apache error log. But it only deny acces, doesn't block IP address.

I have tried several failregex to block using the below logs ,but it didn't worked.

I know its no related to the topic I have reported here, but it will be great if you can help me in creating a failregex

Please see the log generated when an attack occurs.

====
[Wed Apr 06 00:09:22.029840 2016] [:error] [pid 2147:tid 139882385057536] [client 5.135.191.28] ModSecurity: Access denied with code 403 (phase 2). Operator GT matched 5 at IP:multiple_username_count. [file "/var/cpanel/cwaf/rules/cwaf_06.conf"] [line "119"] [id "230011"] [msg "COMODO WAF: Multiple Username Violation: Too Many Usernames Submitted for Authentication."] [data "Current Username: jose"] [hostname "domain.com"] [uri "/wp-login.php"] [unique_id "VwS2IkPebOgAAAhjA-0AAAEP"]
====

**Comment by sebres** [comment]
Here you go:
```
failreex = ^\[\] \[:error\] \[[^\]]+\] \[client <HOST>\] ModSecurity: Access denied with code 40\d
```
Test:
```bash
v='[Wed Apr 06 00:09:22.029840 2016] [:error] [pid 2147:tid 139882385057536] [client 5.135.191.28] ModSecurity: Access denied with code 403 (phase 2). Operator GT matched 5 at IP:multiple_username_count. [file "/var/cpanel/cwaf/rules/cwaf_06.conf"] [line "119"] [id "230011"] [msg "COMODO WAF: Multiple Username Violation: Too Many Usernames Submitted for Authentication."] [data "Current Username: jose"] [hostname "domain.com"] [uri "/wp-login.php"] [unique_id "VwS2IkPebOgAAAhjA-0AAAEP"]'
fail2ban-regex  "$v" "^\[\] \[:error\] \[[^\]]+\] \[client <HOST>\] ModSecurity: Access denied with code 40\d"
```
Result is:
```
Running tests
=============

Use   failregex line : ^\[\] \[:error\] \[[^\]]+\] \[client <HOST>\] ModS...
Use      single line : [Wed Apr 06 00:09:22.029840 2016] [:error] [pid 21...


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] ^\[\] \[:error\] \[[^\]]+\] \[client <HOST>\] ModSecurity: Access denied with code 40\d
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.00 sec]
```

**Comment by VinceIH** [comment]
Sebres,

Thanks Bud. I appreciate your help and this gonna help me a lot in blocking the attacks. I have implemented it and now its working. 

But there is a problem that the firewall is blocking whoever triggering a " ModSecurity: Access denied with code 403" . There is a high chance of false positives if we give it like that since even an upload by a customer may trigger modsecurity.

I only need to block the wp-login and xmlrpc attacks. I have searched the logs and confirmed that only 2 type of logs will be generated when an attack occurs

Type 1: 
====
[Thu Apr 07 01:13:28.355866 2016] [:error] [pid 7872:tid 139882385057536] [client 12.34.56.78] ModSecurity: Access denied with code 403 (phase 2). Operator GT matched 5 at IP:multiple_username_count. [file "/var/cpanel/cwaf/rules/cwaf_06.conf"] [line "119"] [id "230011"] [msg "COMODO WAF: Multiple Username Violation: Too Many Usernames Submitted for Authentication."] [data "Current Username: admin"] [hostname "www.domain.com.au"] [uri "/wp-login.php"] [unique_id "VwYWqEPebOgAAB7AZiQAAAHP"]
====

Type 2:
====
[Thu Apr 07 02:05:02.553574 2016] [:error] [pid 30476:tid 139882395547392] [client 12.23.34.56] ModSecurity: Warning. Operator GE matched 2 at IP:brute_force_burst_counter. [file "/var/cpanel/cwaf/rules/cwaf_06.conf"] [line "92"] [id "230007"] [msg "COMODO WAF: Potential Brute Force Attack from 12.23.34.56 - # of Request Bursts: 3"] [hostname "domain.com"] [uri "/wp-login.php"] [unique_id "VwYivkPebOgAAHcMKeUAAADO"]
====

I have tried to write the rest of the lines after seeing your code, but it failed. I am not that good in regular expressions.

Also, if this gonna work it will help is implementing fail2ban many out there who are using cPanel with the help of modsecurity +cwaf

Again, thanks for your help.

**Comment by sebres** [comment]
```
failregex = ^\[\] \[:error\] \[[^\]]+\] \[client <HOST>\] ModSecurity: (?:Access denied with code 403 \(phase \d+\). Operator GT matched \d+ at IP:multiple_username_count\.|Warning\. Operator GE matched \d+ at IP:brute_force_burst_counter\.)
```

```bash
fail2ban-regex ./test.txt "^\[\] \[:error\] \[[^\]]+\] \[client <HOST>\] ModSecurity: (?:Access denied with code 403 \(phase \d+\). Operator GT matched \d+ at IP:multiple_username_count\.|Warning\. Operator GE matched \d+ at IP:brute_force_burst_counter\.)"
```

```
Results
=======

Failregex: 2 total
|-  #) [# of hits] regular expression
|   1) [2] ^\[\] \[:error\] \[[^\]]+\] \[client <HOST>\] ModSecurity: (?:Access denied with code 403 \(phase \d+\). Operator GT matched \d+ at IP:multiple_username_count\.|Warning\. Operator GE matched \d+ at IP:brute_force_burst_counter\.)
`-
```

BTW. The next time you write in markdown, please use \`\`\` instead of ==== as block prefix/suffix.
(because too large font, word wrap etc, so I have to fix all your comments here...)

**Comment by VinceIH** [comment]
Thanks dude. That worked like a charm.

I think you can create a thread here for implementing fail2ban in a cPanel server. 

Fail2ban + Modsecurity.

**Comment by VinceIH** [comment]
Hi Serbes,

I have checked some more log archives to see any more logs are generated when an **wp-login or xmlrpc attack **occurs. I could see some more types when modsecurity is triggered. So, I am trying to block any host who is trying to evoke such type of a log.

The other logs are below. I have tried to add the remaining regex by checking the regex format you have provided . Please verify whether I am correct.

``` [Thu Apr 07 01:21:14.065435 2016] [:error] [pid 10401:tid 139882416527104] [client 46.118.117.51] ModSecurity: collection_store: Failed to write to DBM file "/tmp/ip": Invalid argument [hostname "domain.com"] [uri "/wp-login.php"] [unique_id "VwYYeUPebOgAACihaMkAAABM"]```

```[Sat Apr 02 06:59:33.418206 2016] [:error] [pid 22683:tid 140558051759872] [client 178.62.23.198] ModSecurity: Access denied with code 403 (phase 2). Invalid URL Encoding: Non-hexadecimal digits used at REQUEST_BODY. [file "/var/cpanel/cwaf/rules/cwaf_01.conf"] [line "279"] [id "210380"] [msg "COMODO WAF: URL Encoding Abuse Attack Attempt"] [severity "WARNING"] [hostname "www.domain.be"] [uri "/wp-login.php"] [unique_id "Vv9fxbkueMIAAFibCDIAAAAV"]```

```[Sat Apr 02 11:01:43.815009 2016] [:error] [pid 20917:tid 140558114699008] [client 185.87.121.69] ModSecurity: Access denied with code 403 (phase 1). Match of "rx ^0{0,1}$" against "REQUEST_HEADERS:Content-Length" required. [file "/var/cpanel/cwaf/rules/cwaf_01.conf"] [line "193"] [id "210270"] [msg "COMODO WAF: GET or HEAD Request with Body Content."] [data "134"] [severity "CRITICAL"] [hostname "domain.co.uk"] [uri "/wp-login.php"] [unique_id "Vv@Yh7kueMIAAFG1me0AAACP"]```

This is the regex I have added. Please verify.

```failregex = ^\[\] \[:error\] \[[^\]]+\] \[client <HOST>\] ModSecurity: (?:Access denied with code 403 \(phase \d+\). Operator GT matched \d+ at IP:multiple_username_count\.|Warning\. Operator GE matched \d+ at IP:brute_force_burst_counter\.|collection_store: Failed to write to DBM file |Access denied with code 403 \(phase \d+\). Invalid URL Encoding:Non-hexadecimal digits used at REQUEST_BODY\.|Access denied with code 403 \(phase \d+\). Match of "rx ^0{0,1}$" against "REQUEST_HEADERS:Content-Length" required\.)``` 

Also, I am trying to add a separate jail for xmlrpc attacks.

``` [Thu Apr 07 02:49:27.240379 2016] [:error] [pid 11679:tid 139900154246912] [client 93.174.93.151] ModSecurity: Warning. Match of "eq 0" against "REQBODY_ERROR" required. [file "/var/cpanel/cwaf/rules/cwaf_01.conf"] [line "163"] [id "210230"] [msg "COMODO WAF: The request body could not be parsed. Possibility of an impedance mismatch attack. This is not a false positive."] [data "XML parser error: XML: Failed parsing document."] [severity "CRITICAL"] [hostname "domain.com"] [uri "/xmlrpc.php"] [unique_id "VwYtJ0XC5jsAAC2fBvgAAAEJ"]``` 

``` [Thu Apr 07 01:58:39.510338 2016] [:error] [pid 11679:tid 139900059838208] [client 93.174.93.151] ModSecurity: XML parser error: XML: Failed parsing document. [hostname "domain.com"] [uri "/xmlrpc.php"] [unique_id "VwYhP0XC5jsAAC2f-sMAAAES"]```

``` [Thu Apr 07 21:22:24.853375 2016] [:error] [pid 1011:tid 140647319189248] [client 108.162.229.173] ModSecurity: Rule 3370ae8 <--this rule varies [id "600175"][file "/usr/local/apache/conf/modsec2.user.conf"][line "227"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "domain.com"] [uri "/xmlrpc.php"] [unique_id "Vwcx-8BF6zoAAAPztLAAAAFJ"]``` 

``` [Thu Apr 07 22:49:07.034075 2016] [:error] [pid 3959:tid 140261319956224] [client 185.89.100.225] ModSecurity: Warning. Operator GE matched 5 at TX:incoming_points. [file "/var/cpanel/cwaf/rules/cwaf_04.conf"] [line "572"] [id "214930"] [msg "COMODO WAF: Inbound Points Exceeded (Total Incoming Points: 5)"] [hostname "domain.com"] [uri "/xmlrpc.php"] [unique_id "VwdGUcBF68UAAA93XOYAAAIA"]```

Regex I have added for the above 4 logs.

```failregex = ^\[\] \[:error\] \[[^\]]+\] \[client <HOST>\] ModSecurity: (?:Warning. Match of "eq 0" against "REQBODY_ERROR" required\.|XML parser error: XML: Failed parsing document\.|Warning\. Operator GE matched \d+ at TX:incoming_points\.)```

Thanks for the help.

**Comment by sebres** [comment]
For the first jail:

./test.conf:
```
[Definition]

failregex = ^\[\] \[:error\] \[[^\]]+\] \[client <HOST>\] ModSecurity: (?:Access denied with code 403 \(phase \d+\). (?:Operator GT matched \d+ at IP:multiple_username_count\.|Invalid URL Encoding: |Match of \"rx \^0\{0,1\}\$\" against \"REQUEST_HEADERS:)|Warning\. Operator GE matched \d+ at IP:brute_force_burst_counter\.|collection_store: Failed to write to DBM file)
```
./test.txt
```
[Thu Apr 07 01:13:28.355866 2016] [:error] [pid 7872:tid 139882385057536] [client 12.34.56.78] ModSecurity: Access denied with code 403 (phase 2). Operator GT matched 5 at IP:multiple_username_count. [file "/var/cpanel/cwaf/rules/cwaf_06.conf"] [line "119"] [id "230011"] [msg "COMODO WAF: Multiple Username Violation: Too Many Usernames Submitted for Authentication."] [data "Current Username: admin"] [hostname "www.domain.com.au"] [uri "/wp-login.php"] [unique_id "VwYWqEPebOgAAB7AZiQAAAHP"]
[Thu Apr 07 02:05:02.553574 2016] [:error] [pid 30476:tid 139882395547392] [client 12.23.34.56] ModSecurity: Warning. Operator GE matched 2 at IP:brute_force_burst_counter. [file "/var/cpanel/cwaf/rules/cwaf_06.conf"] [line "92"] [id "230007"] [msg "COMODO WAF: Potential Brute Force Attack from 12.23.34.56 - # of Request Bursts: 3"] [hostname "domain.com"] [uri "/wp-login.php"] [unique_id "VwYivkPebOgAAHcMKeUAAADO"]
[Thu Apr 07 01:21:14.065435 2016] [:error] [pid 10401:tid 139882416527104] [client 46.118.117.51] ModSecurity: collection_store: Failed to write to DBM file "/tmp/ip": Invalid argument [hostname "domain.com"] [uri "/wp-login.php"] [unique_id "VwYYeUPebOgAACihaMkAAABM"]
[Sat Apr 02 06:59:33.418206 2016] [:error] [pid 22683:tid 140558051759872] [client 178.62.23.198] ModSecurity: Access denied with code 403 (phase 2). Invalid URL Encoding: Non-hexadecimal digits used at REQUEST_BODY. [file "/var/cpanel/cwaf/rules/cwaf_01.conf"] [line "279"] [id "210380"] [msg "COMODO WAF: URL Encoding Abuse Attack Attempt"] [severity "WARNING"] [hostname "www.domain.be"] [uri "/wp-login.php"] [unique_id "Vv9fxbkueMIAAFibCDIAAAAV"]
[Sat Apr 02 11:01:43.815009 2016] [:error] [pid 20917:tid 140558114699008] [client 185.87.121.69] ModSecurity: Access denied with code 403 (phase 1). Match of "rx ^0{0,1}$" against "REQUEST_HEADERS:Content-Length" required. [file "/var/cpanel/cwaf/rules/cwaf_01.conf"] [line "193"] [id "210270"] [msg "COMODO WAF: GET or HEAD Request with Body Content."] [data "134"] [severity "CRITICAL"] [hostname "domain.co.uk"] [uri "/wp-login.php"] [unique_id "Vv@Yh7kueMIAAFG1me0AAACP"]
```

```
fail2ban-regex ./test.txt $(pwd)/test.conf
```
```
Results
=======

Failregex: 5 total
|-  #) [# of hits] regular expression
|   1) [5] ^\[\] \[:error\] \[[^\]]+\] \[client <HOST>\] ModSecurity: (?:Access denied with code 403 \(phase \d+\). (?:Operator GT matched \d+ at IP:multiple_username_count\.|Invalid URL Encoding: |Match of \"rx \^0\{0,1\}\$\" against \"REQUEST_HEADERS:)|Warning\. Operator GE matched \d+ at IP:brute_force_burst_counter\.|collection_store: Failed to write to DBM file)
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [5] (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
`-

Lines: 5 lines, 0 ignored, 5 matched, 0 missed
[processed in 0.00 sec]
```

**Comment by sebres** [comment]
To made a regex for the second jail I should know what you mean with "this rule varies":
```
... ModSecurity: Rule 3370ae8 <--this rule varies ...
```
The best easy provide 2-3 exact examples (without your manual changes) of this log lines...

**Comment by VinceIH** [comment]
```
[Mon Apr 11 23:16:01.925937 2016] [:error] [pid 16110:tid 139838613137152] [client 195.154.236.233] ModSecurity: Rule 3dbb248 [id "600175"][file "/usr/local/apache/conf/modsec2.user.conf"][line "227"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "www.domain.com"] [uri "/xmlrpc.php"] [unique_id "VwySoMBF6zkAAD7uSzgAAAA2"]
```
```
[Mon Apr 11 23:24:33.873924 2016] [:error] [pid 20949:tid 139839158609664] [client 195.154.250.118] ModSecurity: Rule 3095950 [id "220041"][file "/var/cpanel/cwaf/rules/cwaf_05.conf"][line "109"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "domain.com"] [uri "/xmlrpc.php"] [unique_id "VwyUocBF6zkAAFHVYI4AAAAC"]
```

```
[Mon Apr 11 23:24:33.888026 2016] [:error] [pid 20949:tid 139839158609664] [client 195.154.250.118] ModSecurity: Rule 3cdabc8 [id "220042"][file "/var/cpanel/cwaf/rules/cwaf_05.conf"][line "117"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "domain.com"] [uri "/xmlrpc.php"] [unique_id "VwyUocBF6zkAAFHVYI4AAAAC"]
```
```
[Mon Apr 11 23:24:33.922196 2016] [:error] [pid 20949:tid 139839158609664] [client 195.154.250.118] ModSecurity: Rule 3067de8 [id "600175"][file "/usr/local/apache/conf/modsec2.user.conf"][line "227"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "domain.com"] [uri "/xmlrpc.php"] [unique_id "VwyUocBF6zkAAFHVYI4AAAAC"]
```

**Comment by sebres** [comment]
For the second jail:

./test.conf:
```
[Definition]

failregex = ^\[\] \[:error\] \[[^\]]+\] \[client <HOST>\] ModSecurity: (?:Warning\. )?(?:Match of "eq 0" against "REQBODY_ERROR" required\.|XML parser error: XML: Failed parsing document\.|Operator GE matched \d+ at TX:incoming_points\.|Rule \w+ \[id "[^"]*"\]\[file "[^"]*"\]\[line "[^"]*"\] - Execution error - PCRE limits exceeded)
```
./test.txt
```
[Thu Apr 07 02:49:27.240379 2016] [:error] [pid 11679:tid 139900154246912] [client 93.174.93.151] ModSecurity: Warning. Match of "eq 0" against "REQBODY_ERROR" required. [file "/var/cpanel/cwaf/rules/cwaf_01.conf"] [line "163"] [id "210230"] [msg "COMODO WAF: The request body could not be parsed. Possibility of an impedance mismatch attack. This is not a false positive."] [data "XML parser error: XML: Failed parsing document."] [severity "CRITICAL"] [hostname "domain.com"] [uri "/xmlrpc.php"] [unique_id "VwYtJ0XC5jsAAC2fBvgAAAEJ"]
[Thu Apr 07 01:58:39.510338 2016] [:error] [pid 11679:tid 139900059838208] [client 93.174.93.151] ModSecurity: XML parser error: XML: Failed parsing document. [hostname "domain.com"] [uri "/xmlrpc.php"] [unique_id "VwYhP0XC5jsAAC2f-sMAAAES"]
[Thu Apr 07 21:22:24.853375 2016] [:error] [pid 1011:tid 140647319189248] [client 108.162.229.173] ModSecurity: Rule 3370ae8 [id "600175"][file "/usr/local/apache/conf/modsec2.user.conf"][line "227"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "domain.com"] [uri "/xmlrpc.php"] [unique_id "Vwcx-8BF6zoAAAPztLAAAAFJ"]
[Thu Apr 07 22:49:07.034075 2016] [:error] [pid 3959:tid 140261319956224] [client 185.89.100.225] ModSecurity: Warning. Operator GE matched 5 at TX:incoming_points. [file "/var/cpanel/cwaf/rules/cwaf_04.conf"] [line "572"] [id "214930"] [msg "COMODO WAF: Inbound Points Exceeded (Total Incoming Points: 5)"] [hostname "domain.com"] [uri "/xmlrpc.php"] [unique_id "VwdGUcBF68UAAA93XOYAAAIA"]
[Mon Apr 11 23:16:01.925937 2016] [:error] [pid 16110:tid 139838613137152] [client 195.154.236.233] ModSecurity: Rule 3dbb248 [id "600175"][file "/usr/local/apache/conf/modsec2.user.conf"][line "227"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "www.domain.com"] [uri "/xmlrpc.php"] [unique_id "VwySoMBF6zkAAD7uSzgAAAA2"]
[Mon Apr 11 23:24:33.873924 2016] [:error] [pid 20949:tid 139839158609664] [client 195.154.250.118] ModSecurity: Rule 3095950 [id "220041"][file "/var/cpanel/cwaf/rules/cwaf_05.conf"][line "109"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "domain.com"] [uri "/xmlrpc.php"] [unique_id "VwyUocBF6zkAAFHVYI4AAAAC"]
[Mon Apr 11 23:24:33.888026 2016] [:error] [pid 20949:tid 139839158609664] [client 195.154.250.118] ModSecurity: Rule 3cdabc8 [id "220042"][file "/var/cpanel/cwaf/rules/cwaf_05.conf"][line "117"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "domain.com"] [uri "/xmlrpc.php"] [unique_id "VwyUocBF6zkAAFHVYI4AAAAC"]
[Mon Apr 11 23:24:33.922196 2016] [:error] [pid 20949:tid 139839158609664] [client 195.154.250.118] ModSecurity: Rule 3067de8 [id "600175"][file "/usr/local/apache/conf/modsec2.user.conf"][line "227"] - Execution error - PCRE limits exceeded (-8): (null). [hostname "domain.com"] [uri "/xmlrpc.php"] [unique_id "VwyUocBF6zkAAFHVYI4AAAAC"]
```

```
fail2ban-regex ./test.txt $(pwd)/test.conf
```
```
Results
=======

Failregex: 8 total
|-  #) [# of hits] regular expression
|   1) [8] ^\[\] \[:error\] \[[^\]]+\] \[client <HOST>\] ModSecurity: (?:Warning\. )?(?:Match of "eq 0" against "REQBODY_ERROR" required\.|XML parser error: XML: Failed parsing document\.|Operator GE matched \d+ at TX:incoming_points\.|Rule \w+ \[id "[^"]*"\]\[file "[^"]*"\]\[line "[^"]*"\] - Execution error - PCRE limits exceeded)
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [8] (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
`-

Lines: 8 lines, 0 ignored, 8 matched, 0 missed
[processed in 0.00 sec]
```

**Comment by VinceIH** [comment]
Everything going fine for a while. But I could see one of the log is not matching the regex.

``` failregex = ^\[\] \[:error\] \[client <HOST>\].*/wp-login
```

Log
```[Tue Nov  8 09:31:20 2016] [error] [client 195.154.243.31] ModSecurity: Access denied with code 403, [Rule: 'REQUEST_URI' '!(/wp-login\.php\?vaultpress=true|/site-content/|^/admin/editform)'] [id "340195"] [msg "Atomicorp.com UNSUPPORTED DELAYED Rules: Possible Base64 Encoded PHP function in Argument - this may be an attack."]
[Tue Nov  8 09:36:28 2016] [error] [client 27.159.224.30] ModSecurity: Access denied with code 403, [Rule: 'REQUEST_URI' '!(/wp-login\.php\?vaultpress=true|/site-content/|^/admin/editform)'] [id "340195"] [msg "Atomicorp.com UNSUPPORTED DELAYED Rules: Possible Base64 Encoded PHP function in Argument - this may be an attack."]
[Tue Nov  8 12:50:59 2016] [error] [client 192.0.101.75] ModSecurity: Access denied with code 403, [Rule: 'REQUEST_URI' '!(/wp-login\.php\?vaultpress=true|/site-content/|^/admin/editform)'] [id "340195"] [msg "Atomicorp.com UNSUPPORTED DELAYED Rules: Possible Base64 Encoded PHP function in Argument - this may be an attack."]
[Tue Nov  8 12:51:00 2016] [error] [client 192.0.101.75] ModSecurity: Access denied with code 403, [Rule: 'REQUEST_URI' '!(/wp-login\.php\?vaultpress=true|/site-content/|^/admin/editform)'] [id "340195"] [msg "Atomicorp.com UNSUPPORTED DELAYED Rules: Possible Base64 Encoded PHP function in Argument - this may be an attack."]
[Tue Nov  8 14:19:30 2016] [error] [client 91.211.16.144] ModSecurity: Access denied with code 403, [Rule: 'REQUEST_URI' '!(/wp-login\.php\?vaultpress=true|/site-content/|^/admin/editform)'] [id "340095"] [msg "Atomicorp.com UNSUPPORTED DELAYED Rules: Possible PHP function in Argument - this may be an attack."]
[Tue Nov  8 19:49:27 2016] [error] [client 195.154.233.177] ModSecurity: Access denied with code 403, [Rule: 'REQUEST_URI' '!(/wp-login\.php\?vaultpress=true|/site-content/|^/admin/editform)'] [id "340195"] [msg "Atomicorp.com UNSUPPORTED DELAYED Rules: Possible Base64 Encoded PHP function in Argument - this may be an attack."]
```

**Comment by sebres** [comment]
See you a difference between `[:error]` and `[error]`?

So in this case make a `:` optional:
```diff
-failregex = ^\[\] \[:error\] \[client <HOST>\].*/wp-login
+failregex = ^\[\] \[:?error\] \[client <HOST>\].*/wp-login
```

**Comment by sebres** [comment]
Please don't throw anymore all the concerns in this one issue, which original subject is totally different and means something else...

**Comment by VinceIH** [comment]
Okay. Sure
