### ISSUE TITLE
Slow ban/unban

### ISSUE THREAD

**Issue by Deepcuts** [fail2ban/fail2ban#1382]
- Fail2Ban version: 0.9.3
- OS: Ubuntu Server 14.04 (3.19.0.58)
- Fail2Ban installed from sources.

The issue:

On `service fail2ban stop` or machine reboot, fail2ban takes a very long time to unban IPs.
Starting the service behaves the same: slow ban, at ~5 IPs/second.
Having over 6000 IPs can take over 20 minutes at ~ 5 IPs/second ban/unban.
No errors are logged in fail2ban.log.
loglevel is set to NOTICE
dbpurgeage is set to 1 year (31546000)
banaction is set to iptables-multiport
No emails are being sent (setup this way).

The machine is a dual Xeon with 32 GB RAM and SSD and no other processes are hogging resources.

Some jails used to have bantime set to one year, but had to lower it to 1 week otherwise the start stop would take forever.
Searching for users with the same problem I could not find any so I am thinking this must be an isolated case specific to this machine, but I am unable to locate the root of the problem.

**Comment by sebres** [comment]
Nice one...

Can you try please my branch from here (to verify it would be already fixed issue):
https://github.com/sebres/fail2ban/tree/f2b-perfom-prepare-716-cs

I've still one idia, when it would be not effective...

BTW. we should really think about "bulk" actions like bulk-ban resp. bulk-unban.

**Comment by sebres** [comment]
Definitely fixed in 0.10, so I recommend to test it...
I will close it now, just reopen if I'm wrong
