### ISSUE TITLE
SSL_accept 

### ISSUE THREAD

**Issue by juergschwarz** [fail2ban/fail2ban#1385]
### Environment:

Debian 7.10
Fail2ban v0.8.6
### The issue:

This are the lines in may /var/log/mail.log:

 Apr  3 07:45:38 web4you-server-02 postfix/smtpd[3474]: SSL_accept error from unknown[204.93.154.203]: lost connection

And this lines never are matched to this regex in /etc/fail2ban/filter.d/postfix.conf:

 `failregex` = ^%(__prefix_line)sSSL_accept error from `unknow` `.*\[<HOST>\]$`

 checked it with

 fail2ban-regex /var/log/mail.log /etc/fail2ban/filter.d/postfix.conf

and got

Running tests
=============

Use regex file : /etc/fail2ban/filter.d/postfix.conf
Use log file   : /var/log/mail.log

Results
=======

```Failregex
|- Regular expressions:
|  [1] ^\s*(?:\S+ )?(?:@vserver_\S+ )?(?:(?:\[\d+\])?:\s+[\[\(]?postfix/smtpd(?:\(\S+\))?[\]\)]?:?|[\[\(]?postfix/smtpd(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:)?\s*SSL_accept error from unknown .*\[<HOST>\]$
|
- Number of matches:
   [1] 0 match(es)

Ignoreregex
|- Regular expressions:
|
- Number of matches:

Summary
=======

Sorry, no match




Any hints??

**Comment by binarykitchen** [comment]
Me too, seeing many of those warnings in my logs and would like fail2ban block them.

**Comment by sebres** [comment]
In the regular expression, the character `$` is an end-anchor (should match up to end), so you should write more precisely expression. `^...$` means - should match the whole string.
The correct failregex may be:
```
failregex = ^%(__prefix_line)sSSL_accept error from \S+\s*\[<HOST>\]: lost connection$
```

I think, that is not directly an authentication failure, thus I tend to close the issue, if your request is 	therewith cleared.
Please reopen if I'm wrong.
