### ISSUE TITLE
Dovecot regex suggestion

### ISSUE THREAD

**Issue by aryklein** [fail2ban/fail2ban#1387]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): Fail2Ban v0.8.13
- OS, including release name/version: Debian 8 
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
There is a log entrie for dovecot-pop3 that is not picked up by the Dovecot filter and it should be an attack. It happens when someone performs a pop3 connection without auth attempt and then disconnect.

This is an example log:
```
Apr 08 11:53:20 jerry dovecot[15540]: pop3-login: Aborted login (no auth attempts in 45 secs): user=<>, rip=10.10.7.77, lip=10.10.10.26, session=<lh8gW/ovTgAKCgdN>
Apr 08 11:54:20 jerry dovecot[15540]: pop3-login: Disconnected (no auth attempts in 56 secs): user=<>, rip=10.10.7.77, lip=10.10.10.26, session=<tCKzXvovUAAKCgdN>
```

Please consider modify the dovecot regex. Below is my recommended modification.

Change the line:

```
^%(__prefix_line)s(pop3|imap)-login: (Info: )?(Aborted login|Disconnected)(: Inactivity)? \(((auth failed, \d+ attempts)( in \d+ secs)?|tried to use (disabled|disallowed) \S+ auth)\):( user=<\S*>,)?( method=\S+,)? rip=<HOST>(, lip=(\d{1,3}\.){3}\d{1,3})?(, TLS( handshaking(: SSL_accept\(\) failed: error:[\dA-F]+:SSL routines:[TLS\d]+_GET_CLIENT_HELLO:unknown protocol)?)?(: Disconnected)?)?(, session=<\S+>)?\s*$
```

By this line:

```
^%(__prefix_line)s(pop3|imap)-login: (Info: )?(Aborted login|Disconnected)(: Inactivity)? \(((auth failed, \d+ attempts|no auth attempts)( in \d+ secs)?|tried to use (disabled|disallowed) \S+ auth)\):( user=<\S*>,)?( method=\S+,)? rip=<HOST>(, lip=(\d{1,3}\.){3}\d{1,3})?(, TLS( handshaking(: SSL_accept\(\) failed: error:[\dA-F]+:SSL routines:[TLS\d]+_GET_CLIENT_HELLO:unknown protocol)?)?(: Disconnected)?)?(, session=<\S+>)?\s*$
```

### Additional information
I think that if this kind of attack is not treated, it could induce this problem:

```
Apr 07 18:20:24 jerry dovecot[15536]: master: Warning: service(pop3-login): process_limit (100) reached, client connections are being dropped
```

**Comment by sebres** [comment]
>  it should be an attack. It happens when someone performs a pop3 connection without auth attempt and then disconnect.

I see a small "conflict" in your words here (attack / without auth attempt)... 

Joking apart, see #600 for discussion about this (resp. #601 as final solution). There it was explicit removed 2 years ago, so I think, it should not be recognized as "bad" now...

I'll close the issue, as long as no other findings...
