### ISSUE TITLE
A Script to remove the IP from fail2ban

### ISSUE THREAD

**Issue by hbk-linuxmaster** [fail2ban/fail2ban#1388]
Well this would be my first post, where I would be posting about the requirement , where in User should be able to remove the IP from fail2ban in single-shot.

Script is working fine but I am not able to get exact jail details of IP where its ban.If anyone provide some improvement in the script , I would be able to re-vamp the script again.

Suggestions are welcome

Script tried and tested on centos +Postfix environment.

https://github.com/hbk-linuxmaster/scripts/blob/master/hemant.sh

**Comment by yarikoptic** [comment]
so the point is to unban IP from all jails... I guess the easiest would be to implement straight in fail2ban server since it has all necessary information

**Comment by hbk-linuxmaster** [comment]
I can implement,but I want to get the details of chain in which it's blocked so that I can provide details to user in which chain its Block and user will input from which one it should unblocked.


According to script it's just straight away remove from all jail
