### ISSUE TITLE
Uncorrect actionstart in bsd-ipfw action

### ISSUE THREAD

**Issue by schors** [fail2ban/fail2ban#1389]
### Environment:
- 0.9.3, 0.9.4, 0.8.14:
- Testing on FreeBSD 8.2 RELEASE amd64: 
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)
### The issue:

File config/action.d/bsd-ipfw.conf 
String:

```
actionstart = ipfw show | fgrep -q 'table(<table>)' || ....
```

not correct

fgrep with "-q" option cause 141 exit code in some cases

Synopsys: http://stackoverflow.com/questions/19120263/why-exit-code-141-with-grep-q
#### Steps to reproduce

Its a theoretical error )
#### Any additional information

String can be:

```
actionstart = ipfw show | fgrep -s 'table(<table>)' >/dev/null || ....
```
#### Any customizations done to /etc/fail2ban/ configuration

```
```
#### Relevant parts of /var/log/fail2ban.log file:

_preferably obtained while running fail2ban with `loglevel = 4`_

```
```
#### Relevant lines from monitored log files in question:

```
```

**Comment by yarikoptic** [comment]
Learn something new each day ;-) thanks for sharing. Indeed we should probably just start to rely on a redirect without quieting grep... Unless someone would have even better ideas

**Comment by sebres** [comment]
I ask myself how did it work at all for 0.9.x in relation to #1417 resp. #1419

**Comment by sebres** [comment]
Corresponding documentation:

> Suppress error messages about nonexistent or unreadable files. Portability note: unlike GNU grep, 7th Edition Unix grep did not conform to POSIX , because it lacked `-q` and its `-s` option behaved like GNU grep's `-q` option. USG -style grep also lacked `-q` but its `-s` option behaved like GNU grep. Portable shell scripts should avoid both `-q` and `-s` and should redirect standard and error output to /dev/null instead. (`-s` is specified by POSIX .) 

Thus may be following would be better for all platforms (especially some non-100% compatible boxes):
```bash
... | fgrep -c -m 1 'table(<table>)' &> /dev/null || ....
```

But because we are POSIX-compatible (and `-s` is specified by POSIX), thus I'll make a PR with silent flag `-s`:
```bash
... | fgrep -c -m 1 -s 'table(<table>)' &> /dev/null || ....
```
Not posix-compliant boxes using ipfw can create own actions, compatible to the box...
