### ISSUE TITLE
SSHD-DDOS Filter missing

### ISSUE THREAD

**Issue by takenek** [fail2ban/fail2ban#1392]
Hey i saw new type of DDoS attack on my sshd:

Apr 14 20:27:16 taken sshd[31944]: Connection closed by 115.29.248.XXx port 44604 [preauth]
Apr 14 20:27:19 taken sshd[4484]: Connection closed by 115.29.248.XXx port 48265 [preauth]
Apr 14 20:27:23 taken sshd[5043]: Connection closed by 72.45.205.XXX port 47330 [preauth]
Apr 14 20:27:25 taken sshd[9598]: Connection closed by 115.29.248.XXX port 51921 [preauth]
Apr 14 20:27:49 taken sshd[9810]: Connection closed by 2.35.83.XX port 47353 [preauth]
Apr 14 20:27:59 taken sshd[14231]: Connection closed by 115.29.248.XXX port 55588 [preauth]

There is no failregex for this one.
Thanks!

**Comment by sebres** [comment]
For some [preauth] "failures" we would build a new filter `sshd-aggressive` (see #1209), but exact this kind of "failure" is not there.
@fail2ban/contributors:
I'm not sure it should be really counted (can be an aftereffect of other failure?).
If we should implement it yet, would be a `sshd-ddos` or `sshd-aggressive` a gut place for this failregex?

**Comment by yarikoptic** [comment]
I think we had this discussion already, and indeed this is too far from being a authentication failure, and indeed could probably qualify only for sshd-aggressive... since we have a record for such possible addition, I will close this specific report just to tidy up
