### ISSUE TITLE
Inquiry regarding the latest version of fail2ban

### ISSUE THREAD

**Issue by ItsAdventureTime** [fail2ban/fail2ban#1399]
Hello,

Good thing that I was informed about the "neuro" repository of debian through https://github.com/fail2ban/fail2ban/pull/1398

How about for CentOS?

> we are shipping configuration files as if fail2ban installed system wide not under /usr/local so I don't see us merging this PR, and in general those files should be installed by the distribution package, nothing for user to worry about. If you want recent package of fail2ban for 16.04 -- use pkg from neurodebian: http://neuro.debian.net/pkgs/fail2ban.html?highlight=fail2ban

> Thanks for providing the link for this http://neuro.debian.net/install_pkg.html?p=fail2ban (How about if I am using CentOS and would like to use the latest version (unstable) of fail2ban? Do you have something similar to the neuro debian thing? I'm guessing the neuro debian thing is like PPAs for Ubuntu?

**Comment by sebres** [comment]
> How about for CentOS?

This is not a general support group here, so I'll close this "issue".
You can contact the maintainer of fail2ban packet for CentOS or ask on several mailing lists in this respect...
