### ISSUE TITLE
Feature Suggestion: expanded docs for sshd integration and additional jails

### ISSUE THREAD

**Issue by jvanasco** [fail2ban/fail2ban#1402]
I've had a handful of botnets target a machine and found some deficiencies with the default setups (in source and the ubuntu16.04 package)

I'd like to make a few suggestions for docs to educate users, and suggest some additional jails for situations that suggest the connecting IP is not legitimate and should be treated more harshly than the standard sshd jail:
1. The sshd jail really depends on how sshd is configured, especially in terms of the loglevel and max retries.  on many system defaults, an attacker can provide 3 invalid passwords during a single logged sshd attempt.  this means max retries of 3 in fail2ban could really be 9 password attempts.
2. If loglevel on sshd is set to VERBOSE, one can catch invalid users and block differently.  botnets seem to test for accounts like "ubuntu@" ,  "redhat@", "sysadmin@" .  
   
   failregex = ^%(__prefix_line)sInvalid user .+ from <HOST>(?: port \d*)?$
3. botnets also seem to favor certain "system accounts" and try to login as them
   
   failregex = ^%(__prefix_line)sFailed (?:password|publickey) for (?:root|redis|postfix|apache) from <HOST>(?: port \d_)?(?: ssh\d_)?$
4. If the sshd config blocks password access to a server, the loglevel will decide whether or not this info is logged; so ips trying to `ssh root@example.com` might never get seen by fail2ban.

I don't know how this could be handled, but fail2ban should really make some recommendations on sshd logging and how to ensure certain types of login attempts are handled.

**Comment by sebres** [comment]
> 1. an attacker can provide 3 invalid passwords during a single logged sshd attempt. this means max retries of 3 in fail2ban could really be 9 password attempts.

what exactly "single logged sshd attempt" does mean? single session? if so, I'd like to see an example log excerpt for that.

> 2. one can catch invalid users and block differently ...

2.1. fail2ban already knows if user (in authentication attempt) is valid or not (just not clear what you're expecting, with other words what exactly "block differently" should mean.
2.2. it is not always advisable to do such detection in order to ban earlier - due to prematurely blocking an intruder will get to know that user is not valid (usually the intention is to avoid informing other side about that, so large botnet wouldn't be able to taste it or to search for a known legitimate accounts).

Normally a best practice would be avoiding that (so an intruder shall better never know whether the account or password is not valid).
But we have `mode = aggressive` in newer fail2ban versions even to ban aggressively, may be you'd try this.

> 3. botnets also seem to favor certain "system accounts" and try to login as them

Also here I don't really follow what you're trying to say us. What exactly is expected or what you want to do here?

> 4. If the sshd config blocks password access to a server, the loglevel will decide whether or not this info is logged; so ips trying to ssh root@example.com might never get seen by fail2ban.

Hmm... if you disable root access or password access, sshd would normally anyway log something like `Failed password for root from 192.0.2.1 port 12345 ...` in auth-log (or sshd journal). And fail2ban would properly recognize this as a failed attempt.
So again I still not follow what do you mean. Please provide a detailed example (and related log excerpt).

**Comment by jvanasco** [comment]
@sebres thanks for your reply. much of this may have been solved by `mode=aggressive` and I'm a bit out-of-date on this material, but I'll answer everything as best I can from my old notes and memory for clarity. i didn't note the install instructions I had followed at the time and was referencing, so I apologize for losing this context.

I believe I understood what was going on from the docs and source, but I could be very very wrong; feel free to just say "you're wrong! don't worry!" and not elaborate on an explanation.

To clarify this... my intent on this ticket was "recommendations to configure sshd so fail2ban can work better" that may make the fail2ban docs better; and not about configuring fail2ban itself.

I think the core recommendation is:

* Ensure sshd_config has the `LogLevel` set to `ERROR` at the least; you can do more with `VERBOSE`

I'm not sure how to show this on a log. In sshd_config there is `MaxAuthTries`, which covers how many failed authentications are allowed in a connection before the server disconnects.  It defaults to 6 and some additional logging activity happens after the third - but IIRC the first three are slurped into one log report.  IIRC, a few attempts are typically used up by private keys and other challenges with the `ssh` client - but a person can script something to just try passwords.  It is my understanding this means the information which fail2ban relies upon via scanning the authlog is somewhat hindered, because what fail2ban sees as 3 attempts (separate connections) can mean there were either 3 connections from that IP (with 3 guesses each, that is 9 attempts at the password) or 1 connection with 5 attempts (3 via regular logging; 2 additional logs).

If this doesn't make sense, hopefully someone with more experience than me can address the potential for 'miscounting' based on the `MaxAuthTries` setting.

> 2.2. it is not always advisable to do such detection in order to ban earlier 
> Also here I don't really follow what you're trying to say us. What exactly is expected or what you want to do here?

Responding to these both... I agree that we do not want to ban earlier.  I was trying to suggest that any IP which attempts certain accounts is definitely malicious and we may want to drop them into a specific jail for longer periods of time.  IIRC, for this to happen, the sshd loglevel must be set to `VERBOSE`.

>  if you disable root access or password access, sshd would normally anyway log something like Failed password for root from 192.0.2.1 port 12345 ... in auth-log (or sshd journal). And fail2ban would properly recognize this as a failed attempt

sshd only logs that on ERROR or above; it will not log on FATAL (or QUIET).  While the default is INFO, people often change it.

So my concern is not with configuring fail2ban, but telling users to ensure that ERROR is the minimum level but additional things can be done with VERBOSE.

**Comment by sebres** [comment]
> what fail2ban sees as 3 attempts (separate connections) can mean there were either 3 connections

Hmm... I see pretty good each failed authentication attempt in every connect (all of them found by fail2ban, no matter which method is used)... 
And exceeding of `MaxAuthTries` causes yet additional message `maximum authentication attempts exceeded`, which is counted by fail2ban as still one attempt.
So again please provide excerpt from your log...

> we may want to drop them into a specific jail for longer periods of time. 

Maybe you'd try newest fail2ban (0.11) with incremental banning (set `bantime.increment = true`).
Every IP known as "bad" (trying again and again) next time going banned earlier and for longest (incremented) period.
So it does not really matter which accounts are "malicious"...

> So my concern is not with configuring fail2ban, but telling users to ensure that ERROR is the minimum level but additional things can be done with VERBOSE.

Then this should be rather a part of wiki, not an issue. If you want you can create a new [wiki](https://github.com/fail2ban/fail2ban/wiki) page/article there.
