### ISSUE TITLE
Monit files are moved to /etc/monit/conf-available

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#1406]
/etc/monitrc.d -> /etc/monit/conf-available
http://anonscm.debian.org/cgit/collab-maint/monit.git/commit/?id=0bcc9189cb4f43863f08b2423cc54097a3e124ef

Was #896

**Comment by sebres** [comment]
Could you then add it as comment to the PR #896 (or just change the first comment there).
If you mean we should change something (docu, files/monit/fail2ban, changelog, etc), please PR.
If you want, you can also add a wiki-page with howto.
Thx!

**Comment by szepeviktor** [comment]
@yarikoptic It needs to be changed in the Debian package.

**Comment by szepeviktor** [comment]
Here I think https://github.com/fail2ban/fail2ban/blob/debian/debian/rules#L37

**Comment by sebres** [comment]
Just make a PR for debian branch as target...

**Comment by szepeviktor** [comment]
Seems to be outdated
https://github.com/fail2ban/fail2ban/commits/debian
https://anonscm.debian.org/cgit/collab-maint/monit.git/log/
