### ISSUE TITLE
No option to enable jails!

### ISSUE THREAD

**Issue by williclarkam** [fail2ban/fail2ban#1411]
_We will be very grateful, if your problem was described as completely as possible,
enclosing excerpts from logs (if possible within DEBUG mode, if no errors evident
within INFO mode), and configuration in particular of effected relevant settings
(e.g., with ` fail2ban-client -d | grep 'affected-jail-name' ` for a particular
jail troubleshooting).
Thank you in advance for the details, because such issues like "It does not work" 
alone could not help to resolve anything!
Thanks! (remove this paragraph and other comments upon reading)_

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): 0.9.3-1
- OS, including release name/version: Ubuntu 16.04 X64 (Xenial Xerus)
- [x] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Hello, 

I have updated my server to Ubuntu 16.04 and installed fail2ban using `apt install fail2ban`
I have checked ubuntu's repository and it looks like that they have updated fail2ban version, it was `0.8.11-1` on Ubuntu 14.04 and now I am using `0.9.3-1`
I have done the following: 

`cp -pf /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
`
now when I want to edit the `nano /etc/fail2ban/jail.local` there is **NO** `enabled = true`
before it was something like this and I just changed it to true or false but now there is nothing.

How should I configure the jails now?
I couldn't find any information on the first page either!

Thanks

**Comment by yarikoptic** [comment]
1. `cp -pf /etc/fail2ban/jail.conf /etc/fail2ban/jail.local` -- bad practice.  only introduce your changes in jail.local.  `man jail.conf`
2. enabled -- is there, defined in DEFAULT section so by default is that value in the others (later releases have it fixed and removed from the jail definitions) -- again somewhat of RTFM -- man jail.conf:
```shell
$> docker run -it --rm --entrypoint=/bin/bash ubuntu:16.04
root@a4ea23d67bb6:/# apt-get update -qqq; apt-get install -y -q fail2ban
...
root@a4ea23d67bb6:/# grep  enabled /etc/fail2ban/jail.conf 
# enabled = true
# "enabled" enables the jails.
# true:  jail will be enabled and log files will get monitored for changes
# false: jail is not enabled
enabled = false
enabled  = false
enabled = false
enabled = false
enabled  = false
```
