### ISSUE TITLE
Howto upgrade: info required

### ISSUE THREAD

**Issue by sgiannulli** [fail2ban/fail2ban#1416]
Hi all,
just a dummy question: I need to update from 0.9.3 to 0.9.4 version on my raspbian jessie but git pull not working
which the correct procedure: download + unzip new version and then make a new setup?
thanks

**Comment by yarikoptic** [comment]
It depends on how you installed it.
This is not a general support group here though, please ask on the mailing list after giving details

On May 12, 2016 11:36:02 AM EDT, sgiannulli <notifications@github.com> wrote:
>Hi all,
>just a dummy question: I need to update from 0.9.3 to 0.9.4 version on
>my raspbian jessie but git pull not working
>which the correct procedure: download + unzip new version and then make
>a new setup?
>thanks
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/fail2ban/fail2ban/issues/1416

-- 
Sent from a phone which beats iPhone.
