### ISSUE TITLE
wrong recursion check in some constellation within substituteRecursiveTags

### ISSUE THREAD

**Issue by sebres** [fail2ban/fail2ban#1417]
Just to reminder for me...

Invalid recursion check in substituteRecursiveTags.

For example action `bsd-ipfw` produced ValueError('properties contain self referencing definitions and cannot be resolved...')

Almost fixed in 0.10 (building test cases)

chery-pick to 0.9 (master)

**Comment by sebres** [comment]
Because it is very evil resp. grave bug, I've directly fixed it in 0.10
I'll cherrypick it now into 0.9, and make a PR for master.

**Comment by yarikoptic** [comment]
I still would appreciate if even out especially for 0.10 changes going through PRs. Thanks for fixing it! Please add closes #1417 statement on the PR against master
