### ISSUE TITLE
SMTP attacks not being catched

### ISSUE THREAD

**Issue by rlaboiss** [fail2ban/fail2ban#1430]
The rules for Exim have been extended in fe1475be952c8d76527bbe4b0c1249b0e6b10bf4 and further refined in 1eb51b1bc2cfb2b0c37016cad9fe665a843eba73 for catching some SMTP attacks.  This is great, but the failregex is not working for me. In my Exim4 log file `/var/log/exim4/mainlog`, I see lines like this:

    2016-05-17 06:25:27 SMTP protocol error in "AUTH LOGIN" H=(ylmf-pc) [69.10.61.61] AUTH command used when not advertised

which are ignored by fail2ban. Removing the part `\:\d+ I=\[\S*\]\:\d+` from the failregex in `exim.conf` seems to fix the problem for me.

I am using Exim4 version  4.87 in a Debian Gnu/Linux system ("testing" distribution).

**Comment by yarikoptic** [comment]
I think we should indeed make that portion optional. Thanks for the report

**Comment by szepeviktor** [comment]
I also have a rule for unadvertised authentication methods:
https://github.com/szepeviktor/debian-server-tools/blob/master/security/fail2ban-conf/filter.d/courier-smtp.local#L15
