### ISSUE TITLE
Courier MTA appends the decoded username

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#1440]
`May 19 00:52:10 mail.server courieresmtpd[26762]: error,relay=::ffff:86.59.234.158,msg="535 Authentication failed.",cmd: AUTH PLAIN AGFkbWluAGZhaWxlZA== admin`

Current filter checks up to the end of base64:
` ^%(__prefix_line)serror,relay=<HOST>,msg="535 Authentication failed\.",cmd:( AUTH \S+)?( [0-9a-zA-Z\+/=]+)?$`

Courier v0.73.1

**Comment by yarikoptic** [comment]
Thanks. I will add optional stub for username without spaces

On May 21, 2016 12:53:14 PM EDT, "Viktor Szépe" <notifications@github.com> wrote:
>`May 19 00:52:10 mail.radiomedinstruments.hu courieresmtpd[26762]:
>error,relay=::ffff:86.59.234.158,msg="535 Authentication failed.",cmd:
>AUTH PLAIN AGFkbWluAGZhaWxlZA== admin`
>
>Current filter checks till the end of base64:
>` ^%(__prefix_line)serror,relay=<HOST>,msg="535 Authentication
>failed\.",cmd:( AUTH \S+)?( [0-9a-zA-Z\+/=]+)?$`
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/fail2ban/fail2ban/issues/1440

-- 
Sent from a phone which beats iPhone.
