### ISSUE TITLE
xarf-login-attack action fails to generate email

### ISSUE THREAD

**Issue by K2DLS** [fail2ban/fail2ban#1448]
I am running fail2ban on Fedora fc23 using the Fedora packages as follows:

fail2ban-server-0.9.3-1.fc23.noarch
fail2ban-sendmail-0.9.3-1.fc23.noarch
fail2ban-systemd-0.9.3-1.fc23.noarch

fail2ban will properly block sshd failures when using %(action_)s in jail.local.  However, when I attempt to use %(action_xarf), the connections appear to be blocked but the email fails.

Here is a sample log line:

2016-05-24 08:01:37,129 fail2ban.actions        [2177]: ERROR   Failed to execute ban jail 'sshd' action 'xarf-login-attack' info 'CallingMap({'ipjailmatches': <function <lambda> at 0x7f4e5b5d95f0>, 'matches': '2016-05-23T12:01:18.367609 somehost.private sshd[688]: Invalid user support from 113.163.33.114\n2016-05-23T12:01:18.984635 somehost sshd[688]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=113.163.33.114\n2016-05-23T12:01:21.181929 somehost.private sshd[688]: Failed password for invalid user support from 113.163.33.114 port 56896 ssh2', 'ip': '113.163.33.114', 'ipmatches': <function <lambda> at 0x7f4e5b5d9578>, 'ipfailures': <function <lambda> at 0x7f4e5b5d9668>, 'time': 1464091295.814411, 'failures': 3, 'ipjailfailures': <function <lambda> at 0x7f4e5b5d96e0>})': 'bool' object is not iterable

It appears that ipjailmatches and matches are not being found or passed to the action script.

From jail.local:

[DEFAULT]
bantime = 86400
findtime = 14400
maxretry = 3
ignoreip = 127.0.0.0/8 192.168.0.0/24
banaction = firewallcmd-ipset
action = %(action_)s
sender = fail2ban@myhost.com
destemail = me@me..com

[sshd]
enabled = true
action = %(action_xarf)s

This was reported to the mailing list and no appropriate suggestions offered, therefore I propose that this is a reportable issue.

Glad to provide further information toward resolution, would like to get xarf-login-attack working.  Fedora maintainers have suggested that these issues be brought upstream from Fedora.

**Comment by sebres** [comment]
Unfortunately the error `'bool' object is not iterable` is a 	subsequent error. 
We have fixed the loss of the actual error in 0.10, but for 0.9 would be currently too many changes necessary...

But the actual error can be something wrong in your configuration... For example real cyclic recursive substitution... Or this one #1419, that was fixed in current master (0.9.5-dev).

Just post dump of your parameters, to check it:
```bash
fail2ban-client -vv -d
```

**Comment by K2DLS** [comment]
Serg, thanks for your response.

Output of fail2ban-client -vv -d:

INFO   Loading configs for fail2ban under /etc/fail2ban 
DEBUG  Reading configs for fail2ban under /etc/fail2ban 
DEBUG  Reading config files: /etc/fail2ban/fail2ban.conf
INFO     Loading files: ['/etc/fail2ban/fail2ban.conf']
INFO     Loading files: ['/etc/fail2ban/fail2ban.conf']
INFO   Using socket file /var/run/fail2ban/fail2ban.sock
INFO   Loading configs for jail under /etc/fail2ban 
DEBUG  Reading configs for jail under /etc/fail2ban 
DEBUG  Reading config files: /etc/fail2ban/jail.conf, /etc/fail2ban/jail.d/00-systemd.conf, /etc/fail2ban/jail.local
INFO     Loading files: ['/etc/fail2ban/jail.conf']
INFO     Loading files: ['/etc/fail2ban/paths-fedora.conf']
INFO     Loading files: ['/etc/fail2ban/paths-common.conf']
INFO     Loading files: ['/etc/fail2ban/paths-overrides.local']
INFO     Loading files: ['/etc/fail2ban/jail.d/00-systemd.conf']
INFO     Loading files: ['/etc/fail2ban/jail.local']
INFO     Loading files: ['/etc/fail2ban/paths-common.conf', '/etc/fail2ban/paths-fedora.conf', '/etc/fail2ban/jail.conf', '/etc/fail2ban/jail.d/00-systemd.conf', '/etc/fail2ban/jail.local']
INFO   Loading configs for filter.d/sshd under /etc/fail2ban 
DEBUG  Reading configs for filter.d/sshd under /etc/fail2ban 
DEBUG  Reading config files: /etc/fail2ban/filter.d/sshd.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/sshd.conf']
INFO     Loading files: ['/etc/fail2ban/filter.d/common.conf']
INFO     Loading files: ['/etc/fail2ban/filter.d/common.local']
INFO     Loading files: ['/etc/fail2ban/filter.d/common.conf', '/etc/fail2ban/filter.d/sshd.conf']
INFO   Loading configs for action.d/firewallcmd-ipset under /etc/fail2ban 
DEBUG  Reading configs for action.d/firewallcmd-ipset under /etc/fail2ban 
DEBUG  Reading config files: /etc/fail2ban/action.d/firewallcmd-ipset.conf
INFO     Loading files: ['/etc/fail2ban/action.d/firewallcmd-ipset.conf']
INFO     Loading files: ['/etc/fail2ban/action.d/iptables-common.conf']
INFO     Loading files: ['/etc/fail2ban/action.d/iptables-blocktype.local']
INFO     Loading files: ['/etc/fail2ban/action.d/iptables-common.local']
INFO     Loading files: ['/etc/fail2ban/action.d/iptables-common.conf', '/etc/fail2ban/action.d/firewallcmd-ipset.conf']
INFO   Loading configs for action.d/xarf-login-attack under /etc/fail2ban 
DEBUG  Reading configs for action.d/xarf-login-attack under /etc/fail2ban 
DEBUG  Reading config files: /etc/fail2ban/action.d/xarf-login-attack.conf
INFO     Loading files: ['/etc/fail2ban/action.d/xarf-login-attack.conf']
INFO     Loading files: ['/etc/fail2ban/action.d/xarf-login-attack.conf']
['set', 'syslogsocket', 'auto']
['set', 'loglevel', 'INFO']
['set', 'logtarget', '/var/log/fail2ban.log']
['set', 'dbfile', '/var/lib/fail2ban/fail2ban.sqlite3']
['set', 'dbpurgeage', 86400]
['add', 'sshd', 'systemd']
['set', 'sshd', 'usedns', 'warn']
['set', 'sshd', 'maxretry', 3]
['set', 'sshd', 'addignoreip', '127.0.0.0/8']
['set', 'sshd', 'addignoreip', '192.168.0.0/24']
['set', 'sshd', 'logencoding', 'auto']
['set', 'sshd', 'bantime', 86400]
['set', 'sshd', 'ignorecommand', '']
['set', 'sshd', 'findtime', 14400]
['set', 'sshd', 'maxlines', '10']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*(?:error: PAM: )?[aA]uthentication (?:failure|error) for .* from <HOST>( via \\S+)?\\s*$']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*(?:error: PAM: )?User not known to the underlying authentication module for .* from <HOST>\\s*$']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*Failed \\S+ for .*? from <HOST>(?: port \\d*)?(?: ssh\\d*)?(: (ruser .*|(\\S+ ID \\S+ \\(serial \\d+\\) CA )?\\S+ (?:[\\da-f]{2}:){15}[\\da-f]{2}(, client user ".*", client host ".*")?))?\\s*$']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*ROOT LOGIN REFUSED.* FROM <HOST>\\s*$']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*[iI](?:llegal|nvalid) user .* from <HOST>\\s*$']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*User .+ from <HOST> not allowed because not listed in AllowUsers\\s*$']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*User .+ from <HOST> not allowed because listed in DenyUsers\\s*$']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*User .+ from <HOST> not allowed because not in any group\\s*$']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*refused connect from \\S+ \\(<HOST>\\)\\s*$']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*Received disconnect from <HOST>: 3: \\S+: Auth fail$']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*User .+ from <HOST> not allowed because a group is listed in DenyGroups\\s*$']
['set', 'sshd', 'addfailregex', "^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*User .+ from <HOST> not allowed because none of user's groups are listed in AllowGroups\\s*$"]
['set', 'sshd', 'addfailregex', '^(?P<__prefix>\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*)User .+ not allowed because account is locked<SKIPLINES>(?P=__prefix)(?:error: )?Received disconnect from <HOST>: 11: .+ \\[preauth\\]$']
['set', 'sshd', 'addfailregex', '^(?P<__prefix>\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*)Disconnecting: Too many authentication failures for .+? \\[preauth\\]<SKIPLINES>(?P=__prefix)(?:error: )?Connection closed by <HOST> \\[preauth\\]$']
['set', 'sshd', 'addfailregex', '^(?P<__prefix>\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*)Connection from <HOST> port \\d+(?: on \\S+ port \\d+)?<SKIPLINES>(?P=__prefix)Disconnecting: Too many authentication failures for .+? \\[preauth\\]$']
['set', 'sshd', 'addfailregex', '^\\s*(<[^.]+\\.[^.]+>)?\\s*(?:\\S+ )?(?:kernel: \\[ *\\d+\\.\\d+\\] )?(?:@vserver_\\S+ )?(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)?\\s(?:\\[ID \\d+ \\S+\\])?\\s*pam_unix\\(sshd:auth\\):\\s+authentication failure;\\s*logname=\\S*\\s*uid=\\d*\\s*euid=\\d*\\s*tty=\\S*\\s*ruser=\\S*\\s*rhost=<HOST>\\s.*$']
['set', 'sshd', 'addjournalmatch', '_SYSTEMD_UNIT=sshd.service', '+', '_COMM=sshd']
['set', 'sshd', 'addaction', 'firewallcmd-ipset']
['set', 'sshd', 'action', 'firewallcmd-ipset', 'actionban', 'ipset add fail2ban-<name> <ip> timeout <bantime> -exist']
['set', 'sshd', 'action', 'firewallcmd-ipset', 'actionstop', 'firewall-cmd --direct --remove-rule ipv4 filter <chain> 0 -p <protocol> -m multiport --dports <port> -m set --match-set fail2ban-<name> src -j <blocktype>\nipset flush fail2ban-<name>\nipset destroy fail2ban-<name>']
['set', 'sshd', 'action', 'firewallcmd-ipset', 'actionstart', 'ipset create fail2ban-<name> hash:ip timeout <bantime>\nfirewall-cmd --direct --add-rule ipv4 filter <chain> 0 -p <protocol> -m multiport --dports <port> -m set --match-set fail2ban-<name> src -j <blocktype>']
['set', 'sshd', 'action', 'firewallcmd-ipset', 'actionunban', 'ipset del fail2ban-<name> <ip> -exist']
['set', 'sshd', 'action', 'firewallcmd-ipset', 'iptables', 'iptables <lockingopt>']
['set', 'sshd', 'action', 'firewallcmd-ipset', 'known/chain', 'INPUT']
['set', 'sshd', 'action', 'firewallcmd-ipset', 'known/lockingopt', '-w']
['set', 'sshd', 'action', 'firewallcmd-ipset', 'protocol', 'tcp']
['set', 'sshd', 'action', 'firewallcmd-ipset', 'name', 'sshd']
['set', 'sshd', 'action', 'firewallcmd-ipset', 'chain', 'INPUT']
['set', 'sshd', 'action', 'firewallcmd-ipset', 'known/__name__', 'Init']
['set', 'sshd', 'action', 'firewallcmd-ipset', 'known/protocol', 'tcp']
['set', 'sshd', 'action', 'firewallcmd-ipset', 'known/port', 'ssh']
['set', 'sshd', 'action', 'firewallcmd-ipset', 'known/returntype', 'RETURN']
['set', 'sshd', 'action', 'firewallcmd-ipset', 'known/iptables', 'iptables <lockingopt>']
['set', 'sshd', 'action', 'firewallcmd-ipset', 'lockingopt', '-w']
['set', 'sshd', 'action', 'firewallcmd-ipset', 'known/name', 'default']
['set', 'sshd', 'action', 'firewallcmd-ipset', 'known/blocktype', 'REJECT --reject-with icmp-port-unreachable']
['set', 'sshd', 'action', 'firewallcmd-ipset', 'returntype', 'RETURN']
['set', 'sshd', 'action', 'firewallcmd-ipset', 'blocktype', 'REJECT --reject-with icmp-port-unreachable']
['set', 'sshd', 'action', 'firewallcmd-ipset', 'port', 'ssh']
['set', 'sshd', 'action', 'firewallcmd-ipset', 'bantime', '86400']
['set', 'sshd', 'addaction', 'xarf-login-attack']
['set', 'sshd', 'action', 'xarf-login-attack', 'actionban', 'oifs=${IFS}; IFS=.;SEP_IP=( <ip> ); set -- ${SEP_IP}; ADDRESSES=$(dig +short -t txt -q $4.$3.$2.$1.abuse-contacts.abusix.org); IFS=${oifs}\nIP=<ip>\nFROM=<sender>\nSERVICE=<service>\nFAILURES=<failures>\nREPORTID=<time>@`uname -n`\nTLP=<tlp>\nPORT=<port>\nDATE=`LC_ALL=C date --date=@<time> +"%a, %d %h %Y %T %z"`\nif [ ! -z "$ADDRESSES" ]; then\n(printf -- %b "<header>\\n<message>\\n<report>\\n";\ndate \'+Note: Local timezone is %z (%Z)\';\nprintf -- %b "<ipmatches>\\n\\n<footer>") | <mailcmd> <mailargs> ${ADDRESSES//,/\\" \\"}\nfi']
['set', 'sshd', 'action', 'xarf-login-attack', 'actionstop', '']
['set', 'sshd', 'action', 'xarf-login-attack', 'actionstart', '']
['set', 'sshd', 'action', 'xarf-login-attack', 'actionunban', '']
['set', 'sshd', 'action', 'xarf-login-attack', 'actioncheck', '']
['set', 'sshd', 'action', 'xarf-login-attack', 'tlp', 'green']
['set', 'sshd', 'action', 'xarf-login-attack', 'sender', 'fail2ban@islenet.com']
['set', 'sshd', 'action', 'xarf-login-attack', 'service', 'sshd']
['set', 'sshd', 'action', 'xarf-login-attack', 'footer', '\\n\\n--Abuse-bfbb0f920793ac03cb8634bde14d8a1e--']
['set', 'sshd', 'action', 'xarf-login-attack', 'logpath', '/var/log/secure']
['set', 'sshd', 'action', 'xarf-login-attack', 'mailcmd', '/usr/sbin/sendmail']
['set', 'sshd', 'action', 'xarf-login-attack', 'header', 'Subject: abuse report about $IP - $DATE\\nAuto-Submitted: auto-generated\\nX-XARF: PLAIN\\nContent-Transfer-Encoding: 7bit\\nContent-Type: multipart/mixed; charset=utf8;\\n  boundary=Abuse-bfbb0f920793ac03cb8634bde14d8a1e;\\n\\n--Abuse-bfbb0f920793ac03cb8634bde14d8a1e\\nMIME-Version: 1.0\\nContent-Transfer-Encoding: 7bit\\nContent-Type: text/plain; charset=utf-8;\\n']
['set', 'sshd', 'action', 'xarf-login-attack', 'report', '--Abuse-bfbb0f920793ac03cb8634bde14d8a1e\\nMIME-Version: 1.0\\nContent-Transfer-Encoding: 7bit\\nContent-Type: text/plain; charset=utf-8; name=\\"report.txt\\";\\n\\n---\\nReported-From: $FROM\\nCategory: abuse\\nReport-ID: $REPORTID\\nReport-Type: login-attack\\nService: $SERVICE\\nVersion: 0.2\\nUser-Agent: Fail2ban v0.9\\nDate: $DATE\\nSource-Type: ip-address\\nSource: $IP\\nPort: $PORT\\nSchema-URL: http://www.x-arf.org/schema/abuse_login-attack_0.1.2.json\\nAttachment: text/plain\\nOccurances: $FAILURES\\nTLP: $TLP\\n\\n\\n--Abuse-bfbb0f920793ac03cb8634bde14d8a1e\\nMIME-Version: 1.0\\nContent-Transfer-Encoding: 7bit\\nContent-Type: text/plain; charset=utf8; name=\\"logfile.log\\";']
['set', 'sshd', 'action', 'xarf-login-attack', 'message', 'Dear Sir/Madam,\\n\\nWe have detected abuse from the IP address $IP, which according to abusix.com is on your network. We would appreciate if you would investigate and take action as appropriate.\\n\\nLog lines are given below, but please ask if you require any further information.\\n\\n(If you are not the correct person to contact about this please accept our apologies - your e-mail address was extracted from the whois record by an automated process.)\\n\\n This mail was generated by Fail2Ban in a X-ARF format! You can find more information about x-arf at http://www.x-arf.org/specification.html.\\n\\nThe recipient address of this report was provided by the Abuse Contact DB by abusix.com. abusix.com does not maintain the content of the database. All information which we pass out, derives from the RIR databases and is processed for ease of use. If you want to change or report non working abuse contacts please contact the appropriate RIR. If you have any further question, contact abusix.com directly via email (info@abusix.com). Information about the Abuse Contact Database can be found here: https://abusix.com/global-reporting/abuse-contact-db\\nabusix.com is neither responsible nor liable for the content or accuracy of this message.\\n']
['set', 'sshd', 'action', 'xarf-login-attack', 'loglines', '9000']
['set', 'sshd', 'action', 'xarf-login-attack', 'port', 'ssh']
['set', 'sshd', 'action', 'xarf-login-attack', 'mailargs', '-f <sender>']
['start', 'sshd']

**Comment by sebres** [comment]
I've found in your config no cyclic substitution, therefore I suspect that in your case it is indeed the fix #1419.
Would be nice If you can test it...

If you are not familiar with git, possibly just make manually the changes in your `fail2ban/server/action.py` like here (make a backup before):
https://github.com/fail2ban/fail2ban/pull/1419/files

**Comment by K2DLS** [comment]
I manually grabbed a copy of action.py.  It has mostly solved the issue.  Emails are being sent.  Thank you very much for this.

An outstanding issue is that the while number of login violations are being sent in the report.txt attachment, the logfile.log attachment is empty.   I am using the journal for sshd.

**Comment by sebres** [comment]
Thx for testing...

I'll take a look later regarding empty matches (report.txt attachment). It should be no matters whether journal or not, because this action should use `<matches>` run-time tag, that contains all the failures (not grep logfile like many other actions). But something seems to be not correct here...

@fail2ban/contributors someone knows something about this kind of action?
@fail2ban/developers some issues with substitution of `<ipmatches>` known?

**Comment by sebres** [comment]
As regards the bug-fix #1419, the story was continued, so please see https://github.com/fail2ban/fail2ban/pull/1419#issuecomment-221816192
For a new diff, look at fail2ban/server/action.py
in https://github.com/fail2ban/fail2ban/compare/bdc2d07946d2b10ccf4634db6117e798ab079555...a80043ce808cfb96ae5908c056ce8ccb969d9bc0

**Comment by sebres** [comment]
seems to be fixed.
