### ISSUE TITLE
RFC:  do not use coveralls and only codecov

### ISSUE THREAD

**Issue by yarikoptic** [fail2ban/fail2ban#1449]
Since on various occasions obscure reporting of coverage decreases is more pain than gain (forbids merging PRs from the phone etc), I would vote to remove coveralls and leave only codecov since it provides super cool integration with github etc.  @fail2ban/contributors  -- any votes to keep coveralls?

**Comment by sebres** [comment]
No! 
Sometimes it's more informative as codecov.
I think it can be, because of dual processing (one checks relative another, or something several):
- continuous-integration/travis-ci/push
- continuous-integration/travis-ci/pr

**Comment by sebres** [comment]
I suspect many of the strange occasions was in relation to broken travis builds (badips, etc).
After it is more stable (also badps-timeout) the last time both coverage tools are plausible enough.

So I'll close it. Reopen if I'm wrong or if we've again this strange behavior.
