### ISSUE TITLE
Filter works when testing as argument, but fails when placed in file

### ISSUE THREAD

**Issue by corbanCloud** [fail2ban/fail2ban#1462]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): Fail2Ban v0.9.3
- OS, including release name/version: Ubuntu 16.04 
- [X ] Fail2Ban installed via OS/distribution mechanisms
- [X ] You have not applied any additional foreign patches to the codebase
- [X ] Some customizations were done to the configuration (provide details below is so)

### The issue:
fail2ban-regex behavior is confusing on Ubuntu 16.04
When creating a new filter to block brute force attacks on Joomla login I have some very strange (to me at least) behaviors with the fail2ban-regex tester. Filters passed as CLI arg work fine, does not work when defined in a filter.

#### Steps to reproduce
When I test with the filter like this (as CLI arg)
`fail2ban-regex /usr/share/nginx/logs/error.php ".*INFO <HOST>.*joomlafailure.*Username and password.*"`

It works and i get the following output:
```
Running tests
=============

Use   failregex line : .*INFO <HOST>.*joomlafailure.*Username and password.*
Use         log file : /usr/share/nginx/logs/error.php
Use         encoding : UTF-8


Results
=======

Failregex: 18 total
|-  #) [# of hits] regular expression
|   1) [18] .*INFO <HOST>.*joomlafailure.*Username and password.*
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [18] Year-Month-Day[T ]24hour:Minute:Second(?:\.Microseconds)?(?:Zone offset)?
`-
```
When I insert that filter into a filter definition as such:

and run the test referencing the jail file I get this:
run: `fail2ban-regex /usr/share/nginx/logs/error.php /etc/fail2ban/filter.d/joomla-error.conf`
```
Running tests
=============

Use   failregex line : /etc/fail2ban/filter.d/joomla-error.conf
Traceback (most recent call last):
  File "/usr/bin/fail2ban-regex", line 549, in <module>
    fail2banRegex.readRegex(cmd_regex, 'fail') or sys.exit(-1)
  File "/usr/bin/fail2ban-regex", line 319, in readRegex
    'add%sRegex' % regextype.title())(regex.getFailRegex())
  File "/usr/lib/python3/dist-packages/fail2ban/server/filter.py", line 110, in addFailRegex
    raise e
  File "/usr/lib/python3/dist-packages/fail2ban/server/filter.py", line 102, in addFailRegex
    regex = FailRegex(value)
  File "/usr/lib/python3/dist-packages/fail2ban/server/failregex.py", line 215, in __init__
    raise RegexException("No 'host' group in '%s'" % self._regex)
fail2ban.server.failregex.RegexException: No 'host' group in '/etc/fail2ban/filter.d/joomla-error.conf'
```
My filter file looks like this:
```
[Definition]
failregex = .*INFO ([0-9a-f.:]{4,}).*joomlafailure.*Username and password.*
ignoreregex =

```

Given how simple this rule is I cannot understand how it is not working.

This is the relevant section from my jail.local file that enables this definition, I have places it at the top of the web applications section as shown below

```
# 
# Web Applications
#
# 

[joomla-error]

enabled = true
port = http,https
filter = joomla-error
logpath = /usr/share/nginx/logs/error.php
maxretry = 7
```

#### Expected behavior
That the fail2ban regex would accept the filter rule from the filer definition the same as it would from a CLI arg. If there was an error in my regex syntax it would show that error on the CLI as well ... right?
#### Any additional information
I have also tried begining the regular expression for the filter with a start anchor instead of a wildcard.

#### Any customizations done to /etc/fail2ban/ configuration
```
Created local config jail.local, enabled some nginx filters and I am working on creating a custom filter.
```
#### Relevant parts of /var/log/fail2ban.log file:
No related items in log.

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
You have lost a tag `<HOST>` (what is mandatory) in your filter definition...

BTW 1: You don't need a filter config - you can define failregex directly in jail:
```
[joomla-error]
enabled = true
port = http,https
filter = 
failregex = INFO <HOST>.*joomlafailure.*Username and password
logpath = /usr/share/nginx/logs/error.php
```

BTW 2: Your failregex is very - very dangerous (not anchored, many greedy catch-alls, etc).
Additionally not anchored catch-alls `.*` left and right of whole expression make no sense at all.

**Comment by corbanCloud** [comment]
Yea it was more refined anchored etc, but I couldn't make sense of the error coming out of the fail2ban-regex so I kept opening it up. 

And sorry, I did have the <HOST> tag in the CLI version, I and must be going crazy because I swear I had it in the filter file, but obviously not.
