### ISSUE TITLE
Suggestion for unauthorized Access 

### ISSUE THREAD

**Issue by saakhan** [fail2ban/fail2ban#1468]
Hi Guys,

We have one scenario, where we using AWS server & SG doesnt allow (0.0.0.0/0 port 22 ) ssh from internet. 

But sometimes if because of internal network issue in organisation. We would have to open (0.0.0.0/0 port 22 ) ssh from internet. 

So during that time Can we get alert for all successful login & all failed login. 

How its possible ? is it possible on fail2ban  ??

Please suggest if you have scripts for it & Help me solve this please.

**Comment by sebres** [comment]
If you mean something like knocking, then fail2ban has a feature called pass2allow (see #1112)

But you can do that of course with another instruments, for example just with some script allows that using remove of a block iptables rule. In this case you have just to enable the sshd jail...

No Idea what you mean with "AWS & SG".

**Comment by saakhan** [comment]
Hi 

Aws means Amazon web service & Sg means Security group which is like firewall>

Could you please let me know how i can get mail  alert for blocked IP.  As i configure 

bantime  = 60000
findtime  = 60
maxretry = 3

So if anyone tried more than that.  I should get alert via mail. so where i can configure email setting in fail2ban. pls share doc if you have & Any idea. pls suggest. 

Thanks & regards
Saalim khan

**Comment by sebres** [comment]
We've 2 simple actions that send mails - `mail` and `sendmail` (for the list of all actions see https://github.com/fail2ban/fail2ban/tree/master/config/action.d)

Parameter `bantime` is relevant for banning actions only, if you don't need to ban (mail only), it looks like here for example:
```
# file jail.local:

[sshd]

enabled = true

# 3 failures in 1 minute:
findtime = 60
maxretry = 3

# sender and dest mails:
sender = ...@...
destemail = ...@...

# mail action:
mta = sendmail

# for mail only:
action = %(mta)s[name=%(__name__)s, sender="%(sender)s", dest="%(destemail)s", protocol="%(protocol)s", chain="%(chain)s"]
```
If you need banning and mail, change action like this:
```
# for ban and mail:
action = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
         %(mta)s[name=%(__name__)s, sender="%(sender)s", dest="%(destemail)s", protocol="%(protocol)s", chain="%(chain)s"]
```

**Comment by saakhan** [comment]
Hi Sebres,

Thanks a lot for your support & help. 

I will get back to you for further assistance :-) 

Thanks & Regards 
saalim khan

**Comment by saakhan** [comment]
Hi Guys,

One of my IP has been blocked by fail2ban & i tried below commands for unblocking.

sudo fail2ban-client set ssh-iptables unbanip <MyPublicIP>
iptables -D f2b-SSH -s <MyPublicIP> -j DROP

But output is giving like below 

ERROR  NOK: ('Invalid command',)
Invalid command

Please suggest correct cmd 

Thanks & regards 
Saalim khan

**Comment by sebres** [comment]
You miss an ip address after unbanip:
```
sudo fail2ban-client set ssh-iptables unbanip 1.2.3.4
```
