### ISSUE TITLE
action_mwl does not seem to support SystemD logging

### ISSUE THREAD

**Issue by spacecowboy** [fail2ban/fail2ban#1469]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): `0.9.4`
- OS, including release name/version: Debian Jessie
- Fail2Ban downloaded directly from latest releases
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

Setting default action to `action_mwl` causes fail2ban service to error out on startup.

#### Steps to reproduce

* Use configuration mentioned below
* Try to start fail2ban service

#### Expected behavior

Fail2Ban starts correctly and sends emails with relevant log lines.

#### Observed behavior

Fail2Ban fails to start with an error.

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

Loglevel = DEBUG

```
Jun 27 22:22:13 mail fail2ban-client[2018]: WARNING 'syslogsocket' not defined in 'Definition'. Using default one: 'auto'
Jun 27 22:22:13 mail fail2ban-client[2018]: WARNING 'dbfile' not defined in 'Definition'. Using default one: '/var/lib/fail2ban/fail2ban.sqlite3'
Jun 27 22:22:13 mail fail2ban-client[2018]: WARNING 'dbpurgeage' not defined in 'Definition'. Using default one: 86400
Jun 27 22:22:13 mail fail2ban-client[2018]: ERROR  Failed during configuration: Bad value substitution:
Jun 27 22:22:13 mail fail2ban-client[2018]: section: [dockerpost-postfix]
Jun 27 22:22:13 mail fail2ban-client[2018]: option : action
Jun 27 22:22:13 mail fail2ban-client[2018]: key    : logpath
Jun 27 22:22:13 mail fail2ban-client[2018]: rawval : , chain="%(chain)s"]
```

#### Any additional information

The logs reference this filter, which does *not* define any custom action:

```ini
# Fail2Ban filter for postfix authentication failures
#

[INCLUDES]

before = common.conf

[Definition]

failregex = warning: [-._\w]+\[<HOST>\]: SASL ((?i)LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed(: [ A-Za-z0-9+/:]*={0,2})?\s*$

ignoreregex = authentication failed: Connection lost to authentication server$

[Init]

journalmatch = _SYSTEMD_UNIT=dockerpost-postfix.service
```

And this is my `jail.local`

```ini
[DEFAULT]
backend = systemd
# "bantime" is the number of seconds that a host is banned.
bantime  = 86400
# A host is banned if it has generated "maxretry" during the last "findtime"
# seconds.
findtime  = 2000
# "maxretry" is the number of failures before a host get banned.
maxretry = 3
# UDP as well
protocol = all
# Always block all ports
banaction = iptables-allports 
banaction_allports = iptables-allports

# E-mail action. Since 0.8.1 Fail2Ban uses sendmail MTA for the
# mailing. Change mta configuration parameter to mail if you want to
# revert to conventional 'mail'.
mta = mail

# Choose default action.  To change, just override value of 'action' with the
# interpolation to the chosen action shortcut (e.g.  action_mw, action_mwl, etc) in jail.local
# globally (section [DEFAULT]) or per specific section
action = %(action_mwl)s

[sshd]
enabled = true

[dockerpost-postfix]
enabled  = true

[dockerpost-dovecot]
enabled  = true

# Repeat offenders get very long bantimes
[recidive]
enable = true
# If you get banned 3 times
maxretry = 3
# Over 3 days
findtime = 259200
# You're banned for 10 years
bantime = 315360000
```

**Comment by sebres** [comment]
Indeed, the `action_mwl` uses `%(mta)s-whois-lines` per default, that expected a log-file(s) (which of course not available by systemd).

You've currently two options:
- either you use another action, that does not expected a log-file(s), 
e.g. <a href="https://github.com/fail2ban/fail2ban/blob/master/config/action.d/mail-buffered.conf">mail-buffered</a> or <a href="https://github.com/fail2ban/fail2ban/blob/master/config/action.d/sendmail-buffered.conf">sendmail-buffered</a>
Example:
```ini
action = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
         %(mta)s-mail-buffered[lines=50, name=%(__name__)s, sender="%(sender)s", dest="%(destemail)s", tmpfile="/var/run/fail2ban/tmp-mail-%(__name__)s.txt"]
```
- or write your own mail-action, that will get failure messages, e. g. from run-time substitution variable `<matches>` (newline separated failures since last ban) or even using command `journalctl` from journal or something similar...

**Comment by spacecowboy** [comment]
Thanks for the response!
