### ISSUE TITLE
ERROR - Failed during configuration, Bad Value Substitution 

### ISSUE THREAD

**Issue by austinzon** [fail2ban/fail2ban#1473]
Fresh installation of fail2ban on ubuntu Apache 14.04 server, any idea what this error message means?

```
$ sudo service fail2ban restart
 * Restarting authentication failure monitor fail2ban     
ERROR  Failed during configuration: Bad value substitution:
        section: [ssh]
        option : action
        key    : action_
        rawval :

```
Pastebin of my jail.local file: http://pastebin.com/zKKLLRM4
Thanks

**Comment by sebres** [comment]
You have defined `action = %(action_)s`, but no definition for action_.

BTW jail.local should contains your customizations only, not the whole jail.conf, that can be incompatible with newer fail2ban version (it seems to be exactly your case).

**Comment by austinzon** [comment]
Thank you
This cleaned up that error message when I changed the action to action = %(action_mw)s = 

Now I am seeing:

```
 * Restarting authentication failure monitor fail2ban                           ERROR  Error in action definition mail-whois[name=ssh, dest="<<my email>>", protocol="tcp", chain="INPUT", sendername="Fail2Ban"] =
ERROR  Errors in jail 'ssh'. Skipping...
```

**Comment by sebres** [comment]
what says the log? some errors?

**Comment by austinzon** [comment]
Reinstalled fail2ban and all is working now.
Thanks

**Comment by hayden-t** [comment]
I had error 
```Failed during configuration: Bad value substitution: option 'maxmatches' in section 'sshd' contains an interpolation key 'maxretry' which is not a valid option name. Raw value: '%(maxretry)s'```

max retry was missing from my jail.conf:

# "maxretry" is the number of failures before a host get banned.
maxretry = 3

**Comment by hayden-t** [comment]
no idea, not me, maybe a glitch in virtualmin / webmin

**Comment by peterahunt** [comment]
I know this is old, but for clarity, I ran into the same missing line with a Virtualmin install.  It did not show up or cause problems until I edited the jail.local file through the Webmin interface, then the server would not start, same error as you, which led me here.  FYI.
