### ISSUE TITLE
ignoreregex: does not work

### ISSUE THREAD

**Issue by uweng** [fail2ban/fail2ban#1488]
Fail2Ban (0.9.3-1) ignores expression "Ignoreregex" in filter config file. The IP's are banned anyway!

**ssl_access_log**:

ssl_access.log:201.153.66.208 - - [19/Jul/2016:15:37:15 +0200] "POST /autodiscover/autodiscover.xml HTTP/1.1" 404 46346 "-" "Microsoft Office/14.0 (Windows NT 6.1; Microsoft Outlook 14.0.7166; Pro)" "-"
ssl_access.log:201.153.66.208 - - [19/Jul/2016:15:37:43 +0200] "POST /autodiscover/autodiscover.xml HTTP/1.1" 404 46346 "-" "Microsoft Office/14.0 (Windows NT 6.1; Microsoft Outlook 14.0.7166; Pro)" "-"
ssl_access.log:201.153.66.208 - - [19/Jul/2016:15:37:45 +0200] "POST /autodiscover/autodiscover.xml HTTP/1.1" 404 46346 "-" "Microsoft Office/14.0 (Windows NT 6.1; Microsoft Outlook 14.0.7166; Pro)" "-"
ssl_access.log:201.153.66.208 - - [19/Jul/2016:15:37:51 +0200] "POST /autodiscover/autodiscover.xml HTTP/1.1" 404 46346 "-" "Microsoft Office/14.0 (Windows NT 6.1; Microsoft Outlook 14.0.7166; Pro)" "-"
ssl_access.log:201.153.66.208 - - [19/Jul/2016:15:37:53 +0200] "POST /autodiscover/autodiscover.xml HTTP/1.1" 404 46346 "-" "Microsoft Office/14.0 (Windows NT 6.1; Microsoft Outlook 14.0.7166; Pro)" "-"

--------------------------------------------------------------------------------------------------------------------
**/etc/fail2ban/filter.d/nginx-dos.conf**:

failregex = <HOST> - - \[.*\] "[A-Z]+ /.* HTTP/1\.[01]" (502|500|417|416|415|414|413|412|404|405|403|401|400) [0-9\-]+.*$

ignoreregex = .*(robots\.txt|favicon\.ico|autodiscover\.xml)
--------------------------------------------------------------------------------------------------------------------
**fail2ban-client get nginx-dos ignoreregex**

The following regular expression are defined:
`- [0]: .*(robots\.txt|favicon\.ico|autodiscover\.xml)

--------------------------------------------------------------------------------------------------------------------
**fail2ban-regex -v ~/test_log /etc/fail2ban/filter.d/nginx-dos /etc/fail2ban/filter.d/nginx-dos**

Running tests
=============

Use   failregex filter file : nginx-dos, basedir: /etc/fail2ban
Use ignoreregex filter file : nginx-dos, basedir: /etc/fail2ban
Use         log file : /root/test_log
Use         encoding : UTF-8

Results
=======

Failregex: 0 total
|-  #) [# of hits] regular expression
|   1) [0] <HOST> - - (502|500|417|416|415|414|413|412|404|405|403|401|400) [0-9\-]+.*$
`-

Ignoreregex: 5 total
|-  #) [# of hits] regular expression
|   1) [5] .*(robots\.txt|favicon\.ico|autodiscover\.xml)
`-

Date template hits:
|- [# of hits] date format
|  [5] Day(?P<_sep>[-/])MON(?P=_sep)Year[ :]?24hour:Minute:Second(?:\.Microseconds)?(?: Zone offset)?
|  [0] (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
|  [0] Year(?P<_sep>[-/.])Month(?P=_sep)Day 24hour:Minute:Second(?:,Microseconds)?
|  [0] Day(?P<_sep>[-/])Month(?P=_sep)(?:Year|Year2) 24hour:Minute:Second
|  [0] Month/Day/Year:24hour:Minute:Second
|  [0] Month-Day-Year 24hour:Minute:Second\.Microseconds
|  [0] TAI64N
|  [0] Epoch
|  [0] Year-Month-Day[T ]24hour:Minute:Second(?:\.Microseconds)?(?:Zone offset)?
|  [0] ^24hour:Minute:Second
|  [0] ^<Month/Day/Year2@24hour:Minute:Second>
|  [0] ^Year2MonthDay  ?24hour:Minute:Second
|  [0] MON Day, Year 12hour:Minute:Second AMPM
|  [0] ^MON-Day-Year2 24hour:Minute:Second
`-

Lines: 5 lines, 5 ignored, 0 matched, 0 missed [processed in 0.00 sec]
|- Ignored line(s):
|  201.153.66.208 - - [19/Jul/2016:15:37:15 +0200] "POST /autodiscover/autodiscover.xml HTTP/1.1" 404 46346 "-" "Microsoft Office/14.0 (Windows NT 6.1; Microsoft Outlook 14.0.7166; Pro)" "-"
|  201.153.66.208 - - [19/Jul/2016:15:37:43 +0200] "POST /autodiscover/autodiscover.xml HTTP/1.1" 404 46346 "-" "Microsoft Office/14.0 (Windows NT 6.1; Microsoft Outlook 14.0.7166; Pro)" "-"
|  201.153.66.208 - - [19/Jul/2016:15:37:45 +0200] "POST /autodiscover/autodiscover.xml HTTP/1.1" 404 46346 "-" "Microsoft Office/14.0 (Windows NT 6.1; Microsoft Outlook 14.0.7166; Pro)" "-"
|  201.153.66.208 - - [19/Jul/2016:15:37:51 +0200] "POST /autodiscover/autodiscover.xml HTTP/1.1" 404 46346 "-" "Microsoft Office/14.0 (Windows NT 6.1; Microsoft Outlook 14.0.7166; Pro)" "-"
|  201.153.66.208 - - [19/Jul/2016:15:37:53 +0200] "POST /autodiscover/autodiscover.xml HTTP/1.1" 404 46346 "-" "Microsoft Office/14.0 (Windows NT 6.1; Microsoft Outlook 14.0.7166; Pro)" "-"
`-

--------------------------------------------------------------------------------------------------------------------
/var/log/fail2ban.log:

2016-07-19 15:37:16,856 fail2ban.filter         [6364]: INFO    [nginx-dos] Found 201.153.66.208
2016-07-19 15:37:36,359 fail2ban.filter         [6364]: INFO    [nginx-dos] Ignore 194.77.47.240 by ip
2016-07-19 15:37:43,529 fail2ban.filter         [6364]: INFO    [nginx-dos] Found 201.153.66.208
2016-07-19 15:37:46,607 fail2ban.filter         [6364]: INFO    [nginx-dos] Found 201.153.66.208
2016-07-19 15:37:51,667 fail2ban.filter         [6364]: INFO    [nginx-dos] Found 54.208.0.70
2016-07-19 15:37:51,670 fail2ban.filter         [6364]: INFO    [nginx-dos] Found 201.153.66.208
2016-07-19 15:37:54,764 fail2ban.filter         [6364]: INFO    [nginx-dos] Found 201.153.66.208
2016-07-19 15:37:55,023 fail2ban.actions        [6364]: NOTICE  [nginx-dos] Ban 201.153.66.208

--------------------------------------------------------------------------------------------------------------------

**Comment by sebres** [comment]
Strange is that we've already get some similar issues with 0.9.3, for example #1471
What distro is it?

Possible somewhat has redefined (overrode) it in other config files (e.g. includes or direct in jail)?.. 
I mean something like:
```
# jail
[nginx-dos]
filter = nginx-dos
ignoreregex =
```

You can also use a verbose dump to see which config files are included by starting of fail2ban, and which ignoreregex will be really used there:
```
fail2ban-client -v -d
```
What you see by executing of `fail2ban-client -d | grep -e "nginx-dos.*ignoreregex"`?

I cannot reproduce described situation in current 0.9 (master) and I can not remember that we've fixed something like this...

**Comment by uweng** [comment]
fail2ban-client -d | grep -e "nginx-dos.*ignoreregex"
['set', 'nginx-dos', 'addignoreregex', '.*(robots\\.txt|favicon\\.ico|autodiscover\\.xml)']

I've checked actually and it worked. No idea why. I think the IP's from the database were blocked after fail2ban restart anyway, but new entries in the logfile not. 

Thanks for your very fast and competent response.
