### ISSUE TITLE
Typo in /etc/fail2ban/action.d/badips.conf

### ISSUE THREAD

**Issue by rasnauf** [fail2ban/fail2ban#1496]
Line 3: "Note: This reports and IP only and does not actually ban traffic."
-----------------------------^an

Blatant vulnerability. Patch ASAP.

**Comment by yarikoptic** [comment]
thanks fixed... next time feel welcome to send a PR ;)

On Thu, 04 Aug 2016, John Bernard wrote:

>    Line 3: "Note: This reports and IP only and does not actually ban
>    traffic."
>    -----------------------------^an

>    Blatant vulnerability. Patch ASAP.

>    -
>    You are receiving this because you are subscribed to this thread.
>    Reply to this email directly, view it on GitHub, or mute the thread.

>    Link: https://github.com/fail2ban/fail2ban/issues/1496

-- 
Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik
