### ISSUE TITLE
postfix-sasl is not matching failed authentication attempts after upgrade to Ubuntu 16.04.1 LTS

### ISSUE THREAD

**Issue by maksyms** [fail2ban/fail2ban#1497]
### Environment:
- Fail2Ban version 0.9.3, although according to source code, the issue is also in 0.9.5 and 0.10
- Ubuntu 16.04.1 LTS: 
- [x] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

After an upgrade to Ubuntu 16.04.1 LTS, fail2ban stopped matching certain postfix-sasl entries. 

#### Steps to reproduce
Example (below is malicious activity, the named server is not supposed to be able to authenticate):

Aug  3 14:28:17 ksusha postfix/smtpd[31211]: warning: mail.foldsandwalker.com[98.191.84.74]: SASL Plain authentication failed: 
Aug  3 15:30:49 ksusha postfix/smtpd[17041]: warning: mail.foldsandwalker.com[98.191.84.74]: SASL Plain authentication failed:

The first line is matched by fail2ban-regex, the second isn't. The reason is that the first line has space after "failed:" and the second doesn't.

#### Any additional information
The issue is in failregex in /etc/fail2ban/filter.d/postfix-sasl.conf. The current value for it is:

failregex = ^%(__prefix_line)swarning: [-._\w]+\[<HOST>\]: SASL ((?i)LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed(: [ A-Za-z0-9+/:]*={0,2})?\s*$

The fix is trivial, to delete space between ":" and "[" at the end of regex:

failregex = ^%(__prefix_line)swarning: [-._\w]+\[<HOST>\]: SASL ((?i)LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed(:[ A-Za-z0-9+/:]*={0,2})?\s*$

I hope this helps someone.

**Comment by yarikoptic** [comment]
Great, thanks for the detailed report and analysis! So we just need to make trailing space optional `\s*$`.  Should we do it or you would like to send a PR?

On August 6, 2016 6:27:29 AM EDT, maksyms <notifications@github.com> wrote:
>### Environment:
>- Fail2Ban version 0.9.3, although according to source code, the issue
>is also in 0.9.5 and 0.10
>- Ubuntu 16.04.1 LTS: 
>- [X] Fail2Ban installed via OS/distribution mechanisms
>- [X] You have not applied any additional foreign patches to the
>codebase
>- [ ] Some customizations were done to the configuration (provide
>details below is so)
>
>### The issue:
>
>After an upgrade to Ubuntu 16.04.1 LTS, fail2ban stopped matching
>certain postfix-sasl entries. 
>
>#### Steps to reproduce
>Example (below is malicious activity, the named server is not supposed
>to be able to authenticate):
>
>Aug  3 14:28:17 ksusha postfix/smtpd[31211]: warning:
>mail.foldsandwalker.com[98.191.84.74]: SASL Plain authentication
>failed: 
>Aug  3 15:30:49 ksusha postfix/smtpd[17041]: warning:
>mail.foldsandwalker.com[98.191.84.74]: SASL Plain authentication
>failed:
>
>The first line is matched by fail2ban-regex, the second isn't. The
>reason is that the first line has space after "failed:" and the second
>doesn't.
>
>#### Any additional information
>The issue is in failregex in /etc/fail2ban/filter.d/postfix-sasl.conf.
>The current value for it is:
>
>failregex = ^%(__prefix_line)swarning: [-._\w]+\[<HOST>\]: SASL
>((?i)LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed(: [
>A-Za-z0-9+/:]*={0,2})?\s*$
>
>The fix is trivial, to delete space between ":" and "[" at the end of
>regex:
>
>failregex = ^%(__prefix_line)swarning: [-._\w]+\[<HOST>\]: SASL
>((?i)LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed(:[
>A-Za-z0-9+/:]*={0,2})?\s*$
>
>I hope this helps someone.
>
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/fail2ban/fail2ban/issues/1497

-- 
Sent from a phone which beats iPhone.

**Comment by sebres** [comment]
if I understood it correct, it is not trailing space, but a space after colon before bracket... So if optional, then without anchor `$`

**Comment by maksyms** [comment]
No, it is not a trailing space. It is the space at the end of "authentication failed: ". Sometimes it is there, sometimes it isn't - but the failregex expects it to always be there.

I will send a PR, I was just looking at the right place to put a test case and couldn't find it yet. I can send it now without a test case though.

**Comment by yarikoptic** [comment]
Since there were not specific endings after : in your sample log lines, I assumed it could add well be the trailing one, which we also should make optional. Don't place it inside [] but just make optional and any space `\s?`

**Comment by maksyms** [comment]
I'm not keen on taking the space out of [], as it was there before and I don't know what that () is supposed to match. So I suggest I leave space within [], but take it as a mandatory one from right outside of it. I also don't think that \s is the right option, as I'd be concerned if there were any kinds of \t, etc, at the end of the line.

I'm going to run unit tests today and submit pull request. Still haven't found the right place to add a unit test if required...
