### ISSUE TITLE
dovecot enabled breaks fail2ban on ubuntu 16.04.01

### ISSUE THREAD

**Issue by WilfulTravesty** [fail2ban/fail2ban#1499]
Ubuntu 16.04.01
fail2ban 0.9.3-1

[x] Fail2Ban installed via OS/distribution mechanisms
[x] You have not applied any additional foreign patches to the codebase
[x] Some customizations were done to the configuration (provide details below is so)

Created /etc/fail2ban/jail.local and added:
[dovecot]
enabled = true

Service fails to start:
%# service fail2ban start
Job for fail2ban.service failed because the control process exited with error code. See "systemctl status fail2ban.service" and "journalctl -xe" for details.

%# systemctl status fail2ban.service
● fail2ban.service - Fail2Ban Service
   Loaded: loaded (/lib/systemd/system/fail2ban.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Sun 2016-08-07 21:53:54 CDT; 13s ago
     Docs: man:fail2ban(1)
  Process: 7497 ExecStop=/usr/bin/fail2ban-client stop (code=exited, status=0/SUCCESS)
  Process: 8041 ExecStart=/usr/bin/fail2ban-client -x start (code=exited, status=255)
 Main PID: 7396 (code=killed, signal=TERM)

Aug 07 21:53:53 titan systemd[1]: Failed to start Fail2Ban Service.
Aug 07 21:53:53 titan systemd[1]: fail2ban.service: Unit entered failed state.
Aug 07 21:53:53 titan systemd[1]: fail2ban.service: Failed with result 'exit-code'.
Aug 07 21:53:54 titan systemd[1]: fail2ban.service: Service hold-off time over, scheduling restart.
Aug 07 21:53:54 titan systemd[1]: Stopped Fail2Ban Service.
Aug 07 21:53:54 titan systemd[1]: fail2ban.service: Start request repeated too quickly.
Aug 07 21:53:54 titan systemd[1]: Failed to start Fail2Ban Service.
Exit 3

/var/log/fail2ban.log is empty.

syslog contains:

Aug  7 22:01:31 titan fail2ban-client[9375]: ERROR  No file(s) found for glob /var/log/mail.warn
Aug  7 22:01:31 titan fail2ban-client[9375]: ERROR  Failed during configuration: Have not found any log file for dovecot jail
Aug  7 22:01:31 titan systemd[1]: fail2ban.service: Control process exited, code=exited status=255
Aug  7 22:01:31 titan systemd[1]: fail2ban.service: Unit entered failed state.
Aug  7 22:01:31 titan systemd[1]: fail2ban.service: Failed with result 'exit-code'.
Aug  7 22:01:31 titan systemd[1]: fail2ban.service: Service hold-off time over, scheduling restart.
Aug  7 22:01:31 titan fail2ban-client[9384]: ERROR  No file(s) found for glob /var/log/mail.warn
Aug  7 22:01:31 titan fail2ban-client[9384]: ERROR  Failed during configuration: Have not found any log file for dovecot jail
Aug  7 22:01:32 titan systemd[1]: fail2ban.service: Control process exited, code=exited status=255
Aug  7 22:01:32 titan systemd[1]: fail2ban.service: Unit entered failed state.
Aug  7 22:01:32 titan systemd[1]: fail2ban.service: Failed with result 'exit-code'.
Aug  7 22:01:32 titan systemd[1]: fail2ban.service: Service hold-off time over, scheduling restart.
Aug  7 22:01:32 titan fail2ban-client[9387]: ERROR  No file(s) found for glob /var/log/mail.warn
Aug  7 22:01:32 titan fail2ban-client[9387]: ERROR  Failed during configuration: Have not found any log file for dovecot jail
Aug  7 22:01:32 titan systemd[1]: fail2ban.service: Control process exited, code=exited status=255
Aug  7 22:01:32 titan systemd[1]: fail2ban.service: Unit entered failed state.
Aug  7 22:01:32 titan systemd[1]: fail2ban.service: Failed with result 'exit-code'.
Aug  7 22:01:32 titan systemd[1]: fail2ban.service: Service hold-off time over, scheduling restart.
Aug  7 22:01:32 titan fail2ban-client[9390]: ERROR  No file(s) found for glob /var/log/mail.warn
Aug  7 22:01:32 titan fail2ban-client[9390]: ERROR  Failed during configuration: Have not found any log file for dovecot jail
Aug  7 22:01:32 titan systemd[1]: fail2ban.service: Control process exited, code=exited status=255
Aug  7 22:01:32 titan systemd[1]: fail2ban.service: Unit entered failed state.
Aug  7 22:01:32 titan systemd[1]: fail2ban.service: Failed with result 'exit-code'.
Aug  7 22:01:33 titan systemd[1]: fail2ban.service: Service hold-off time over, scheduling restart.
Aug  7 22:01:33 titan fail2ban-client[9398]: ERROR  No file(s) found for glob /var/log/mail.warn
Aug  7 22:01:33 titan fail2ban-client[9398]: ERROR  Failed during configuration: Have not found any log file for dovecot jail
Aug  7 22:01:33 titan systemd[1]: fail2ban.service: Control process exited, code=exited status=255
Aug  7 22:01:33 titan systemd[1]: fail2ban.service: Unit entered failed state.
Aug  7 22:01:33 titan systemd[1]: fail2ban.service: Failed with result 'exit-code'.
Aug  7 22:01:33 titan systemd[1]: fail2ban.service: Service hold-off time over, scheduling restart.
Aug  7 22:01:33 titan systemd[1]: fail2ban.service: Start request repeated too quickly.

**Comment by mitchellkrogza** [comment]
Looks like you have not specified the location of your dovecot log files.

Aug 7 22:01:32 titan fail2ban-client[9387]: *ERROR No file(s) found for 
glob /var/log/mail.warn*
Aug 7 22:01:32 titan fail2ban-client[9387]: *ERROR Failed during 
configuration: Have not found any log file for dovecot jail*

Quicker way to find errors is to run

*sudo fail2ban-client -vvv -x start*

**Comment by WilfulTravesty** [comment]
I'm fine with that answer, but I'll note that by default a newly 
installed dovecot is set to log to syslog, so for the Ubuntu fail2ban 
package you could set the dovecot log to that instead of leaving it 
blank to match the default setup. If you do not maintain the Ubuntu 
package, then I guess I can find somewhere to file this as an issue with 
Ubuntu.

Thanks for the alternate command!

-Wolf


------ Original Message ------

**Comment by sebres** [comment]
It is not direct a bug of fail2ban, not more than an issue of maintainer of package for Ubuntu (or just a configuration error)...  (BTW the logged error was clear - "Failed during configuration: Have not found any log file for dovecot jail").
Currently it is critical error during starting of fail2ban. It will change after implementing of #1379 - the jail goes idle and fail2ban will periodically check the log files are available (to reactivate the jail again).

I'll close this issue, because I don't know what we can do here...

**Comment by unixweb-info** [comment]
I fixed this error by installing and configuring rsyslog. If anyone is interested, write to me!
