### ISSUE TITLE
freswitch's regexp

### ISSUE THREAD

**Issue by davidcsi** [fail2ban/fail2ban#1500]
- Fail2Ban version (including any possible distribution suffixes):
{code}
root@tester ~# fail2ban-server -V
Fail2Ban v0.8.13

Copyright (c) 2004-2008 Cyril Jaquier, 2008- Fail2Ban Contributors
Copyright of modifications held by their respective authors.
Licensed under the GNU General Public License v2 (GPL).

Written by Cyril Jaquier <cyril.jaquier@fail2ban.org>.
Many contributions by Yaroslav O. Halchenko <debian@onerussian.com>.
{code}

- OS, including release name/version: 
Debian Jessie
- [X ] Fail2Ban installed via OS/distribution mechanisms
- [ X] You have not applied any additional foreign patches to the codebase
- [ X] Some customizations were done to the configuration (provide details below is so)
changed the log file path for freeswitch from "/var/log/freeswitch.log" to "/var/log/freeswitch/freeswitch.log".

### The issue:
hello guys, I have a problem with Freeswitch's regex, by default it is 

"failregex = ^\.\d+ \[WARNING\] sofia_reg\.c:\d+ SIP auth (challenge|failure) \((REGISTER|INVITE)\) on sofia profile \'[^']+\' for \[.*\] from ip <HOST>$" 

But that "(challenge|failure)" will match when Freeswitch is sending out auth challenge (before failing) as well as when it fails... i think it should be "failure", taking out the "challenge" part 

_Summary here_

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
Thx for report.

Indeed logging of "auth challenge" seems to be not a failure.
See http://lists.freeswitch.org/pipermail/freeswitch-users/2011-February/068733.html

Possibly the author want in this case to ban flooding IPs, or IPs doing dos-attack etc (all the IPs doing multiple uncompleted authentication tries, so it induces not a failure). 
If so, it should be IMHO optional (or separate jail like freeswitch-dos) and `maxretry` should be increased, resp. `findtime` should be decreased.
This was first time introduced from @grooverdan in 04d28fd2e1bb2be5ac82555fb8898fb5239ca658

**Comment by davidcsi** [comment]
Hello,

I hadn't thought of that, good point. I will see what happens.

Thanks

David
