### ISSUE TITLE
sending mail syntax

### ISSUE THREAD

**Issue by jungle-boogie** [fail2ban/fail2ban#1505]
### Environment:

- OS, including release name/version: 
raspberry pi with fail2ban installed from source with python 2.7

### The issue:

Is this the correct syntax for sending emails when a ban happens:

my jail.local
```
[freeswitch]
enabled  = true
port     = 5060,5061,5080,5081
filter   = freeswitch
logpath  = /usr/local/freeswitch/log/freeswitch.log
maxretry = 3
action   = iptables-allports[name=freeswitch, protocol=all]
action_mwl = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
             %(mta)s-whois-lines[name=%(__name__)s, sender="%(sender)s", dest="%(destemail)s", logpath=%(logpath)s, chain="%(chain)s"]
```

I don't see any entries in /var/log/fail2ban.log when an entry is blocked with iptables that fail2ban is sending the email.

**Comment by jungle-boogie** [comment]
still don't know the correct syntax to send emails.

**Comment by sebres** [comment]
You have misconfigured your jail: the `action_mwl` is a config variable, that will be used in substitution of the complex variable `action` (that used for all the actions, and you overwrite it without usage of `action_mwl`).

Therefore it execute only one action, namely `iptables-allports`...

The correct config would be:
```
...
protocol=all
banaction = iptables-allports
action = %(action_mwl)s
```
or even if you want to overwrite default `action_mwl`, just set it direct to `action`:
```
...
protocol=all
banaction = iptables-allports
action = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
         %(mta)s-whois-lines[name=%(__name__)s, sender="%(sender)s", dest="%(destemail)s", logpath=%(logpath)s, chain="%(chain)s"]
```

BTW. The definition of `port` does not matter for `iptables-allports`...
