### ISSUE TITLE
Date parse failure if hostname begins with digits

### ISSUE THREAD

**Issue by Sut3kh** [fail2ban/fail2ban#1507]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.9.3
- OS, including release name/version: CentOS Linux release 7.2.1511 (Core)
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

Using a log format like `Aug 8 11:25:50 hostname ...` causes the date parsing to fail if the hostname begins with digits.

#### Steps to reproduce

- Create logfile in the format of `Aug 4 18:19:37 14430f2329b8 ...`
- Add logfile to a jail
- Run fail2ban

#### Expected behavior

In a perfect world:

- fail2ban-regex should confirm the template as `(?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?`
- it should note that there is no space after '1443' and parse the date as `Aug 4 18:19:37 2016`

#### Observed behavior

The date matches the template `(?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?` but assumes the first 4 digits of the hostname are the year, flooding fail2ban.log with errors every tick.

#### Any additional information

I know this seems like a very rare/strange use case and it probably is in a way but i came across it by running multiple wordpress sites each in their own docker container (hence the random hostnames) and each with the [WP fail2ban](https://en-gb.wordpress.org/plugins/wp-fail2ban/) plugin installed which outputs the date without a year, thereby randomly causing this situation now and then depending on the GUID generated by docker.

It was simple to workaround by updating the plugin to use `$date->format('M j H:i:s Y')` (excluding the year doesn't seem like a great idea anyway) but i figured i should at least report it for others to find, even if its not worth fixing.

#### Any customizations done to /etc/fail2ban/ configuration

n/a

#### Relevant parts of /var/log/fail2ban.log file:

```
2016-08-10 15:45:05,540 fail2ban.filter         [19785]: ERROR   findFailure failed to parse timeText: Aug 8 11:25:50 1443
```

#### Relevant lines from monitored log files in question:

```
Aug 8 11:25:50 14430f2329b8 Authentication attempt for unknown user test_p43jBhTw from 1.2.3.4
```

**Comment by sebres** [comment]
> I know this seems like a very rare/strange use case

Nothing about this use case, but if the date-pattern can match ambiguous values, you should always specify it direct in your jail, to prevent such kind of confusions. BTW it is always a good practice. 

So define `datepattern = %b %d %H:%M:%S` in your jail and enjoy...

Here is a test with fail2ban-regex, using this datepattern:
```bash
$ fail2ban-regex -d '%b %d %H:%M:%S' 'Aug 8 11:25:50 14430f2329b8 Authentication attempt for unknown user test_p43jBhTw from 1.2.3.4' 'from <HOST>$'

Running tests
=============

Use      datepattern : MON Day 24hour:Minute:Second
Use   failregex line : from <HOST>$
Use      single line : Aug 8 11:25:50 14430f2329b8 Authentication attempt...


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] from <HOST>$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] MON Day 24hour:Minute:Second
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.00 sec]
```
