### ISSUE TITLE
monit and systemd

### ISSUE THREAD

**Issue by staehler** [fail2ban/fail2ban#1525]
When I use systemd (on debian) to look for my process, is monit than a good addition or do they disturb each other?
If it is a good addition, than the monit file should change to something like this

> start program = "/fullpath/service fail2ban start"
> stop program = "/fullpath/service fail2ban stop"

What do you think about it?
I'm quite unsure, if I should use both.

**Comment by szepeviktor** [comment]
They can work together.

If you learn systemd it is possible to substitute monit.
https://github.com/szepeviktor/debian-server-tools/blob/master/mail/courier-mta-smarthost.sh#L46-L66

**Comment by sebres** [comment]
Closed as answered, 
do not hesitate to notify us if it should be reopened resp. welcome with PR...
