### ISSUE TITLE
fail2ban-client pointing to old location

### ISSUE THREAD

**Issue by joaonl** [fail2ban/fail2ban#1528]
Hi there,

Recently I upgraded to 16.04.1.
One downside was that fail2ban needed to be reinstalled. I was using the core files and got the chance to use apt.

After installing everything is working smooth except the command fail2ban-client.
This command is pointing to: 

Usage: /usr/local/bin/fail2ban-client
Instead of
/usr/bin/fail2ban-client

Does anyone know how to make sure fail2ban-client command in Linux is going to the correct path?

Thanks in advance.

Cheers,

**Comment by sebres** [comment]
duplicate of #1524
