### ISSUE TITLE
fail2ban.system improvement

### ISSUE THREAD

**Issue by staehler** [fail2ban/fail2ban#1531]
As fail2ban needs the sockfile /var/run/fail2ban/fail2ban.sock, the regarding directory must exist.
My fail2ban fail to start because of this lack.
Maybe you should include this:

> ExecStartPre="/usr/bin/test -d /var/run/fail2ban || /bin/mkdir /var/run/fail2ban"

**Comment by mrc0mmand** [comment]
This directory should be created automatically by systemd via [tmpfiles.d configuration file](https://github.com/fail2ban/fail2ban/blob/0.10/files/fail2ban-tmpfiles.conf). I guess your issue is the same as mentioned in the issue #1384.

**Comment by movalex** [comment]
By the way, this automatic folder creation does not work on OSX. On mac I use this configuration on startup (placed in `/Library/LaunchDaemons/org.fail2ban.init.plist`:  
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>Label</key>
        <string>org.fail2ban.init</string>
        <key>RunAtLoad</key>
        <true/>
        <key>ProgramArguments</key>
        <array>
                <string>mkdir</string>
                <string>-p</string>
                <string>/var/run/fail2ban</string>
        </array>
</dict>
</plist>

```

**Comment by edesz** [comment]
I am having this kind of problem on CentOS 7. I cannot install `fail2ban` from a package manager, so I am installing from source.

So far  successfully I installed from source with this:

    tar xvfj fail2ban-0.10.0.tar.bz2
    cd fail2ban-0.10.0
    python setup.py install

Then I copied the service file:

    sudo cp fail2ban-0.10/files/fail2ban.service /etc/systemd/system/fail2ban.service
    sudo systemctl daemon-reload

However, after every reboot of the system I have to currently use this:

    mkdir /var/run/fail2ban && sudo systemctl restart fail2ban

like they mentioned [here](https://github.com/mantl/mantl/issues/1687). If I don't do this, the service does not start.

#### Question

I am not sure where I should add this:

    `ExecStartPre=/bin/mkdir -p /run/fail2ban`

In which file should I add this lilne?

**Comment by edesz** [comment]
I am having this kind of problem on CentOS 7. I cannot install `fail2ban` from a package manager, so I am installing from source.

So far  successfully I installed from source with this:

    tar xvfj fail2ban-0.10.0.tar.bz2
    cd fail2ban-0.10.0
    python setup.py install

Then I copied the service file:

    sudo cp fail2ban-0.10/files/fail2ban.service /etc/systemd/system/fail2ban.service
    sudo systemctl daemon-reload

However, after every reboot of the system I have to currently use this:

    mkdir /var/run/fail2ban && sudo systemctl restart fail2ban

like they mentioned [here](https://github.com/mantl/mantl/issues/1687). If I don't do this, the service does not start.

I have tried these:

```
[user@mysyst ~]# ls /etc/tmpfiles.d
python.conf
[user@mysyst ~]# ls /usr/lib/tmpfiles.d
etc.conf          iscsi.conf   libselinux.conf  mdadm.conf     pam.conf          rpcbind.conf  samba.conf  screen.conf   systemd-nologin.conf  var.conf
initscripts.conf  legacy.conf  lvm2.conf        net-snmp.conf  portreserve.conf  rpm.conf      sap.conf    systemd.conf  tmp.conf              x11.conf
```

but there does not appear to be any files related to `fail2ban` there.

#### Question

I am not sure where I should add this:

    ExecStartPre="/usr/bin/test -d /var/run/fail2ban || /bin/mkdir /var/run/fail2ban"

In which file should I add this lilne?

**Comment by sebres** [comment]
@edesz please take a look at #1618 (https://github.com/fail2ban/fail2ban/pull/1618/files#diff-6b34b0af6722bba99d81fc8d8aad13fdR9)

**Comment by edesz** [comment]
@sebres: Thank you for your reply!

I made these changes so now my `fail2ban.service` file looks like this:

```
[root@localhost ~]# cat /etc/systemd/system/fail2ban.service
[Unit]
Description=Fail2Ban Service
Documentation=man:fail2ban(1)
After=network.target iptables.service firewalld.service
PartOf=iptables.service firewalld.service

[Service]
Type=simple
ExecStartPre=mkdir -p /var/run/fail2ban
ExecStart=/usr/bin/fail2ban-server -xf start
ExecStop=/usr/bin/fail2ban-client stop
ExecReload=/usr/bin/fail2ban-client reload
PIDFile=/var/run/fail2ban/fail2ban.pid
Restart=on-failure
RestartPreventExitStatus=0 255
```

I then copied this and tried to restart the service:

```
sudo cp fail2ban-0.10/files/fail2ban.service /etc/systemd/system/fail2ban.service
sudo systemctl daemon-reload
```

Next, I restarted the service with:

```
systemctl stop fail2ban
systemctl start fail2ban
systemctl enable fail2ban
```

I then rebooted the server, but when I check the status I get:

```
[user@mysyst ~]# systemctl status fail2ban
● fail2ban.service - Fail2Ban Service
   Loaded: loaded (/etc/systemd/system/fail2ban.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2016-11-23 13:57:01 PST; 1min 33s ago
     Docs: man:fail2ban(1)
  Process: 1314 ExecStop=/usr/bin/fail2ban-client stop (code=exited, status=255)
  Process: 1038 ExecStart=/usr/bin/fail2ban-server -xf start (code=exited, status=255)
 Main PID: 1038 (code=exited, status=255)
```

Also, it is still not creating the `/var/run/fail2ban` path after reboot:

```
[user@mysyst ~]# ls /var/run/fail2ban
ls: cannot access /var/run/fail2ban: No such file or directory
```

In your post, I see this line `ExecStartPre....` in yellow hilighting. Is this line needed in `fail2ban.service`?

**Comment by sebres** [comment]
If you start then again via `systemctl start fail2ban`, is directory created? Is fail2ban started?
What you see by `journalctl -r -u fail2ban.service`?

**Comment by sebres** [comment]
Fixed now in #1618, I suspect it misses absolute path by `mkdir`, so:
```
ExecStartPre=/bin/mkdir -p /var/run/fail2ban
```

**Comment by edesz** [comment]
Ok, thanks! This works now.

Before I made the change to `/bin/mkdir`, I found that `/var/run/fail2ban` directory did not exist after reboot.

Now, I made this change to `/bin/mkdir` - the directory is created after reboot. Also, the service is now successfully started and is running after reboot.

Thanks again for your help @sebres.

**Comment by sebres** [comment]
Glad it works, so I'll merge #1618... 
If someone needs it in 0.9 (@fail2ban/maintainers), this one line can be cherry picked there (other changes are possible in 0.10 only).

**Comment by sebres** [comment]
I'll close this, although currently fixed for systemd service only... But I believe normally it is an issue of the maintainers of corresponding distribution... 
We can not (and want not really) take care of all possible systems in *nix- and linux-zoo in frame of fail2ban development...
