### ISSUE TITLE
Requesting correct git incantation to work with 0.10.x experimental branch

### ISSUE THREAD

**Issue by davidfavor** [fail2ban/fail2ban#1535]
Searched docs + must have missed the info.

Someone let me know the correct incantation to work with latest experimental branch.

Thanks.

**Comment by davidfavor** [comment]
Looks like, this defaults to trunk, so is sufficient...

git clone https://github.com/fail2ban/fail2ban

**Comment by sebres** [comment]
BTW. Note the trunk is indeed experimental, so the released or even pre-released may be more stable (but the other way around some current bugs may be not fixed there ;)

For released and (pre-)released see:
- either https://github.com/fail2ban/fail2ban/releases 
- or https://github.com/fail2ban/fail2ban/tags
