### ISSUE TITLE
python setup.py install --prefix=/foo places config files in /etc rather than /foo/etc

### ISSUE THREAD

**Issue by davidfavor** [fail2ban/fail2ban#1536]
net4# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

net4# python --version
Python 2.7.12

Let me know if this is something broken in setup.py or some config setting which requires being set after initial git clone is done.

Thanks.

**Comment by mrc0mmand** [comment]
`--prefix` only affects script files (`bin/fail2ban-client`, `bin/fail2ban-server`, etc.). If you want to install all fail2ban's data under your own root directory, you should use `--root` option.

Eg:
```
$ python setup.py install --root testinstall
<...>
$ ls -l testinstall{,/etc}
testinstall:
total 16
drwxrwxr-x. 3 fsumsal fsumsal 4096 Sep  2 20:14 etc
drwxrwxr-x. 3 fsumsal fsumsal 4096 Sep  2 20:14 run
drwxrwxr-x. 5 fsumsal fsumsal 4096 Sep  2 20:14 usr
drwxrwxr-x. 3 fsumsal fsumsal 4096 Sep  2 20:14 var

testinstall/etc:
total 4
drwxrwxr-x. 6 fsumsal fsumsal 4096 Sep  2 20:14 fail2ban
```

**Comment by davidfavor** [comment]
That did the trick.

Thanks!

**Comment by davidfavor** [comment]
Frantisek Sumsal wrote:
> |--prefix| only affects script files (|bin/fail2ban-client|, 
> |bin/fail2ban-server|, etc.). If you want to install all fail2ban's data 
> under your own root directory, you should use |--root| option.
> 
> Eg:
> 
> |$ python setup.py install --root testinstall
> <...>
> $ ls -l testinstall{,/etc}
> testinstall:
> total 16
> drwxrwxr-x. 3 fsumsal fsumsal 4096 Sep  2 20:14 etc
> drwxrwxr-x. 3 fsumsal fsumsal 4096 Sep  2 20:14 run
> drwxrwxr-x. 5 fsumsal fsumsal 4096 Sep  2 20:14 usr
> drwxrwxr-x. 3 fsumsal fsumsal 4096 Sep  2 20:14 var
> 
> testinstall/etc:
> total 4
> drwxrwxr-x. 6 fsumsal fsumsal 4096 Sep  2 20:14 fail2ban
> |
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <http://links.davidfavor.com/wf/click?upn=npdP0-2FMHcGNgMeleDP-2B5C2OKSi7NbJV8-2Fxugocgfb1D-2FyKua6cSnyH9rcqxXR857qlK1Hk-2BfmjHG9lF8ZCgQK5pFmvYqLU4k4x679l-2F-2FIXg-3D_s5UH8bhnBaopYjthcNSRcV7Isr-2B1tlgt24TxgWhEafSkG-2FD7gmhnKY5EgWCKp-2Fb6iwxeSw-2BxfHo4VgxYs4mBQ-2FtS-2BqTMC-2BWW95E-2BDqj1dEIv6qRlFmKNqw8gz7PSqDQPWr9fCtnmgoC1lU-2FED5RP-2FwdI61CfUVnDVA811nTvJOH668uV8B9CMzQthx77r6IFETtDWcp0LktiwH5hTc8g7EOcGtm8376Iy-2F4NfW7Z1O1dMZwH2DW0z8udb0gMkAI5zcATD62luThVMwY-2FVQlavzSSOOynVRY0Cbc6mB8mQ-2FxEtEikuTMvLy5i92wmzIrRqDznzCLTRAeLVmOKzJ3ygg-3D-3D>, 
> or mute the thread 
> <http://links.davidfavor.com/wf/click?upn=npdP0-2FMHcGNgMeleDP-2B5C7AVBorP-2FKY4ck16dAhGxXUvybq1WQryduaQBV4jETF9WItEvplVYgyd0dDgbIfOODq9h-2B-2BivBabxjOXNSwrAKhBaMyytKh8TE83rJr7MPTWOzk71dJc-2Fh0-2FqBlhkLQMKA-3D-3D_s5UH8bhnBaopYjthcNSRcV7Isr-2B1tlgt24TxgWhEafSkG-2FD7gmhnKY5EgWCKp-2Fb6iwxeSw-2BxfHo4VgxYs4mBQ-2FtS-2BqTMC-2BWW95E-2BDqj1dEIv6qRlFmKNqw8gz7PSqDQPWr9fCtnmgoC1lU-2FED5RP-2FwdI61CfUVnDVA811nTvJOH668uV8B9CMzQthx77r6IFwJveEBPLeUJifww1bFqfVqmjDnJJulCeDmSavzpC7lxFSJMnt0hskBHkcOpT-2BciHkWY4xn7sqm0naYA1MZDCOywIZYiuxVa0CMZgJceSAzEAQFdAfVkOYsLEKpXfBmfJ-2B4dqIQwKs9VHzosWQ4Kplg-3D-3D>.
> 

--root did the trick.

Thanks.
