### ISSUE TITLE
0.9.5: python-3.4 incompatible `except Exception, e` instances

### ISSUE THREAD

**Issue by lkraav** [fail2ban/fail2ban#1537]
Upgrading from python 3.3 > 3.4 caused syntax errors.

https://github.com/gabrielfalcao/lettuce/issues/476 blames `except` keyword syntax changes, should be `except Exception as e`, which fail2ban codebase already has in most cases.

Not sure if these are random leftovers? Anyway, here's the catalog:

```
fail2ban.git $ ag --py "except Exception, e"
fail2ban/client/jailreader.py
174:                            except Exception, e:

fail2ban/server/filter.py
671:            except Exception, e: # pragma: no cover - Requires implemention error in FileContainer to generate

fail2ban/server/filterpyinotify.py
47:except Exception, e:

fail2ban/server/transmitter.py
59:             except Exception, e:

fail2ban/server/database.py
45:             except Exception, e: # pragma: no cover
54:             except Exception, e: # pragma: no cover
73:             except Exception, e: # pragma: no cover
82:             except Exception, e: # pragma: no cover

fail2ban/tests/clientreadertestcase.py
413:            except Exception, e: # pragma: no cover - failed if reachable

fail2ban/tests/utils.py
186:    except Exception, e: # pragma: no cover
192:    except Exception, e: # pragma: no cover
201:    except Exception, e: # pragma: no cover
```

**Comment by yarikoptic** [comment]
thanks. not sure where is the root of your trouble is since our codebase is not natively python3 compatible yet and needs to go through 2to3 conversion (usually done by setup.py or fail2ban-2to3 helper), so those all should have been replaced for you.  Just since it would only be helpful, sent a #1538 to close this issue since specifically concerns with old fashioned exepts ;)

**Comment by lkraav** [comment]
> thanks. not sure where is the root of your trouble is since our codebase is not natively python3 compatible yet and needs to go through 2to3 conversion (usually done by setup.py or fail2ban-2to3 helper), so those all should have been replaced for you.

Yeah, I was in the middle of a system-wide 3.3 > 3.4 update. Perhaps 2to3 site-package for 3.4 hadn't gotten installed yet, or something similar. I did think it was weird to get that error.
