### ISSUE TITLE
fail2ban not working in FIPS mode

### ISSUE THREAD

**Issue by dzila** [fail2ban/fail2ban#1540]
### Environment:
: 
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

When RHEL6.8 is configured in FIPS mode, fail2ban will complain during startup that: 

hostname fail2ban.transmitter[0000]: WARNING Command ['set', 'sshd', 'addlogpath', '/var/log/secure', 'head'] has failed. Received ValueErrr('error:060800A3:digital envelope routes:EVP_DigestInit_ex:disabled for fips',)

Subsequently fail2ban fails to ban brute force ssh attacks.

I suspect that this may be due to fail2ban using MD5 in https://github.com/fail2ban/fail2ban/blob/00c08f0cfa52b9205e2663cabc1b9d9a9fb569bf/fail2ban/server/filter.py . MD5 is not allowed by FIPS. Some information can be found at https://niranjanmr.wordpress.com/2011/11/15/rhel6-fips/

fail2ban version is fail2ban-0.9.3-1.el6.1
 
#### Steps to reproduce

Configure RHEL 6.8 in FIPS mode 

Install and start fail2ban with sshd enabled

Do some brute force ssh logins

#### Expected behavior

fail2ban should detect and ban IPs trying to brute force

#### Observed behaviour

fail2ban does not block any IP that is performing the brute force attack.

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
Thx for info,

Indeed fail2ban uses MD5 hash value as marker for the last log-line, that it has processed.
That will be used only after restart of fail2ban for testing the log-file is still the same (imho secure enough by 128-bit, and yes, I know about the "collision" probability).
If such quirky standards like FIPS forbid it completely (but in sense of our work case here we speak only about hashing value, not cryptography), so what... of course, we can implement another "better" convenient algorithm for this. 
But, imho, it would be prio 100500... sorry for such conclusion.

If you want to contribute self, you are welcome with an PR :) 
(but I think, it will be not the last constraint)

**Comment by dzila** [comment]
Hi,

Thank you for your reply. I suspect it would be a matter of replacing md5 with sha1 for example, judging from https://docs.python.org/2/library/hashlib.html. Or make this a user configurable option.

Cheers

**Comment by sebres** [comment]
> I suspect it would be a matter of replacing md5 with sha1

The value will be saved in the sqlite-database, but if the value is once differ (after upgrade/restart), fail2ban will think it has another log-file (what is not so bad as long as it occurs once).

> Or make this a user configurable option.

Well I think, sufficient enough (and easy going) would be (e. g. in filter.py) something like:
```diff
try:
	import hashlib
-	md5sum = hashlib.md5
+	try:
+		md5sum = hashlib.md5
+		# try to use it (several standards like FIPS forbid it):
+		md5sum(' ').hexdigest()
+	except: # pragma: no cover
+		md5sum = hashlib.sha1
except ImportError: # pragma: no cover
	# hashlib was introduced in Python 2.5.  For compatibility with those
	# elderly Pythons, import from md5
	import md5
	md5sum = md5.new
```

You can try it, and say know, if the test-cases are passed (you know, I think - it is not the last one)...

For testing use ...
```bash
cd /tmp/
git clone https://github.com/fail2ban/fail2ban.git -b 0.10; # or tar xvfj ...
cd fail2ban
#fail2ban-2to3; # expected if you use python 3.x
PYTHONPATH=. bin/fail2ban-testcases
```

**Comment by dzila** [comment]
Thanks! I have tested the patch and it appears to work fine!

Cheers,
