### ISSUE TITLE
fail2ban/config/filter.d/sshd.conf: match "Unable to negotiate with <ip> port <port>: no matching cipher found. Their offer: <ciphers>,none [preauth]"

### ISSUE THREAD

**Issue by lkraav** [fail2ban/fail2ban#1545]
Stupid bots are annoying. Log example: `sept  12 13:03:29 conversionready sshd[45]: Unable to negotiate with 31.168.172.145 port 55419: no matching cipher found. Their offer: aes256-cbc,rijndael-cbc@lysator.liu.se,aes192-cbc,aes128-cbc,arcfour128,arcfour,3des-cbc,none [preauth]`

**Comment by sebres** [comment]
It is not really an authentication failure, so goes to sshd-aggressive. Too few time to complete it... unfortunately.
Thus, to be implemented in #1209

**Comment by lkraav** [comment]
Thanks, subscribed it.

**Comment by K2DLS** [comment]
I just saw issue.  Before I did I had added this case as part of pull request #1662.
