### ISSUE TITLE
variables <matches> has no data in my custom action.  how do I fix it?

### ISSUE THREAD

**Issue by dedetok** [fail2ban/fail2ban#1564]
I create simple fail2ban dashboard using php and mysql to store attack history. I create custom action called localdb and parse `<matches>` parameter to php.
But variables `<matches>` has no data.  how do I fix it?
It is work on blocklist_de, but not in my custom action localdb.

### Environment:
Fail2Ban v0.8.13 
Debian 8.6

### The issue:
variables `<matches>` has no data in my custom action.  

#### Steps to reproduce
I create custom action called localdb
/etc/fail2ban/action.d/localdb.conf
```
...
actionban = curl --data 'logipv4=<ip>' --data-urlencode 'logmsg=<matches>' --user-agent 'fail2ban v0.8.12' 'http://www.garasiku.web.id/web/kci/kci_log.php' >> /home/user/test/curlfail2ban.log
...
```

I triggered my action in ssh-iptables-ipset4 and ssh-iptables-ipset6, I edit /etc/fail2ban/jail.conf
```
...
[ssh-iptables-ipset4]

enabled = true
port     = ssh
filter   = sshd
banaction = iptables-ipset-proto4
   blocklist_de[email="mymail@garasiku.web.id", apikey="xxxx", service="ssh"]
   localdb
logpath = /var/log/auth.log
maxretry = 3

[ssh-iptables-ipset6]

enabled = true
port     = ssh
filter   = sshd
banaction = iptables-ipset-proto6
   blocklist_de[email="mymail@garasiku.web.id", apikey="xxxx", service="ssh"]
   localdb
logpath = /var/log/auth.log
maxretry = 3
...
```

Here is php script to insert fail2ban log [rootdir]/web/kci/kci_log.php
```
<?php 
if ($_SERVER['SERVER_ADDR'] != $_SERVER['REMOTE_ADDR']){
  die('Internal Server Error maybe service -end-');
}

/*
database: database
table: kci_logipv4
logdate datetime
logipv4 int(11)
logmsg varchar(1000)
logfrom int 
*/

$logipv4;
$logmsg;
$isprocess = false;

// host, user, password, database, [port]
$mysqli = new mysqli("localhost", "user", "pass", "database");
if ($mysqli->connect_errno) {
  die('database error -end-');
}

// POST
if (isset($_POST["logipv4"]) && isset($_POST["logmsg"] ))
{
	$isprocess = true;
	$logipv4 = ip2long($_POST["logipv4"]); //sanitize
	$logmsg = mysqli_real_escape_string($_POST["logmsg"]); // sanitize
}

// GET
if (isset($_GET["logipv4"]) && isset($_GET["logmsg"] ))
{
	$isprocess = true;
	$logipv4 = ip2long($_GET["logipv4"]); // sanitize
	$logmsg = mysqli_real_escape_string($_GET["logmsg"]);  // sanitize
}

if ($isprocess) {
	echo "Insert \n";
	echo "matches: $logmsg \n";
	if (!$mysqli->query("INSERT INTO kci_logipv4(logdate, logipv4, logmsg, logfrom) VALUES (now(), ".$logipv4.", '".$logmsg."', 1);")) {
		echo "fail insert -end- \n";
	} else {
		echo "done -end- \n";
	}
} else {
	echo "not Process -end- \n";
}
?> 
```

The output of action
```
~$ tail /home/user/test/curlfail2ban.log
done -end-

Insert
matches:
done -end-

Insert
matches:
done -end-
```

#### Expected behavior
The output of action should be 
```
~$ tail /home/user/test/curlfail2ban.log
Insert
matches: Oct 3 03:49:28 mars sshd[21139]: Did not receive identification string from 223.197.235.94
Oct 3 04:45:47 mars sshd[693]: reverse mapping checking getaddrinfo for 223-197-235-94.static.imsbiz.com [223.197.235.94] failed - POSSIBLE BREAK-IN ATTEMPT!
Oct 3 04:45:47 mars sshd[693]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=223.197.235.94 user=root
Oct 3 04:45:48 mars sshd[693]: Failed password for root from 223.197.235.94 port 36489 ssh2
Oct 3 04:45:48 mars sshd[693]: Connection closed by 223.197.235.94 [preauth]
Oct 3 06:18:34 mars sshd[18817]: reverse mapping checking getaddrinfo for 223-197-235-94.static.imsbiz.com [223.197.235.94] failed - POSSIBLE BREAK-IN ATTEMPT!
Oct 3 06:18:34 mars sshd[18817]: Invalid user admin from 223.197.235.94
Oct 3 06:18:34 mars sshd[18817]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=223.197.235.94
Oct 3 06:18:36 mars sshd[18817]: Failed password for invalid user admin from 223.197.235.94 port 42854 ssh2
Oct 3 06:18:38 mars sshd[18817]: Connection closed by 223.197.235.94 [preauth]
done -end-
```

**Comment by sebres** [comment]
v.0.8.13 is too old, so I'll close the issue... You can try some newer version like 0.9 or 0.10...

BTW Have you tested your command, specified in `actionban`, via command line (not from fail2ban)?

**Comment by dedetok** [comment]
0.9 in testing (sid) repository :(

**Comment by sebres** [comment]
http://neuro.debian.net/pkgs/fail2ban.html

Have you tested your command itself (I mean the same `curl ...`)?

**Comment by dedetok** [comment]
yes, parameters <IP> is work properly. but <MATCHES> does not work. Here is the result http://www.garasiku.web.id/web/kci/kci_logread.php. <MATCHES> should filled in comment.
I'm to test it on Debian Jessie SID Package fail2ban with version 0.9.5-1.
Thank for your time to respond it.

**Comment by dedetok** [comment]
SOLVED
mysqli_real_escape_string($_POST["logmsg"]); 
should be replace with 
$mysqli->escape_string($logmsg); // sanitize;

**Comment by sharif779** [comment]
I have used following command.
**curl http://localhost/tools/insert_block_table/<ip>/block/<name>/<matches>
and thats the output.
ERROR iptables  -I f2b-FREESWITCH 1 -s 192.168.30.58 -j REJECT --reject-with icmp-port-unreachable#012curl http://localhost/tools/insert_block_table/192.168.30.58/block/FREESWITCH/2018-06-10 00:11:13.328901 \[WARNING\] sofia_reg.c:1744 SIP auth challenge \(REGISTER\) on sofia profile \'default\' for \[12244@192.168.30.188\] from ip 192.168.30.58#0122018-06-10 00:11:13.594170 \[WARNING\] sofia_reg.c:2849 Can\'t find user \[12244@192.168.30.188\] from 192.168.30.58#0122018-06-10 00:11:13.594170 \[WARNING\] sofia_reg.c:1689 SIP auth failure \(REGISTER\) on sofia profile \'default\' for \[12244@192.168.30.188\] from ip 192.168.30.58#0122018-06-10 00:11:19.968872 \[WARNING\] sofia_reg.c:1744 SIP auth challenge \(REGISTER\) on sofia profile \'default\' for \[12244@192.168.30.188\] from ip 192.168.30.58#0122018-06-10 00:11:20.153222 \[WARNING\] sofia_reg.c:2849 Can\'t find user \[12244@192.168.30.188\] from 192.168.30.58#0122018-06-10 00:11:20.153222 \[WARNING\] sofia_reg.c:1689 SIP auth failure \(REGISTER\) on sofia profile \'default\' for \[12244@192.168.30.188\] from ip 192.168.30.58 -- timed out after 60 seconds.
