### ISSUE TITLE
Debian 8.6 fail2ban failregex incorrect for guacamole 

### ISSUE THREAD

**Issue by coldfire84** [fail2ban/fail2ban#1574]
Running Debian 8.6, fail2ban installed 10/10 as below - intended to front guacamole / apache2 HTTPS proxy on same client.

```
cd ~
git clone https://github.com/fail2ban/fail2ban
cd fail2ban
python setup.py install
cp files/debian-initd /etc/init.d/fail2ban
systemctl daemon-reload
```

jail.local file:

```
[guacamole]
enabled = true
port     = http,https,8080
logpath  = /var/log/tomcat*/catalina.out
```

Guacamole also installed from source (via git clone), as-per [here.](http://www.cb-net.co.uk/linux/debian-8-6-jessie-installing-guacamole/)

With default configuration failed logins are not detected, with a revised failregex in the guacamole.conf failed logins are detected. 

```
# This does not work (default)
# failregex = ^.*\nWARNING: Authentication attempt from <HOST> for user "[^"]*" failed\.$ to this:

# correct failregex
failregex = \bAuthentication attempt from \[<HOST>(?:,.*)?\] for user ".*" failed\.
```

I found the revised failregex [here.](https://sourceforge.net/p/guacamole/discussion/1110833/thread/899ea997/)

**Comment by sebres** [comment]
Can you supply here a log-line resp. excerpt for the failure? 
BTW in the original fail2ban configuration it is multi-line (2 lines), see https://github.com/fail2ban/fail2ban/blob/master/fail2ban/tests/files/logs/guacamole
