### ISSUE TITLE
double space on line 26 of sendmail-reject.conf

### ISSUE THREAD

**Issue by mgrant0** [fail2ban/fail2ban#1578]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): v0.9.3
- OS, including release name/version: debian (testing)
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

There is a double-space after the word 'from' in sendmail-reject.conf:

            ^%(__prefix_line)s\w{14}: rejecting commands from  (\S+ )?\[<HOST>\] due to pre-greeting traffic after \d+ seconds$

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by mgrant0** [comment]
sample line from the log file:

Oct  9 20:17:01 strange sm-mta[18001]: u9A0GtpL018001: rejecting commands from unallocated-static.rogers.com [1.2.3.4] due to pre-greeting traffic after 6 seconds

**Comment by sebres** [comment]
Thx, fixed in #1579
