### ISSUE TITLE
Bans in database won't be removed when unbanning

### ISSUE THREAD

**Issue by L4rS6** [fail2ban/fail2ban#1582]
A banned IP will be added to the sqlite database when it gets banned[1]. When the IP gets unbanned, this records still exists (fail2ban version 0.9.5).

[1]
sqlite> select * from bans;
....
ssh|banned-ip|1476644580|{"matches": ["match-string"], "failures": 5}

**Comment by mitchellkrogza** [comment]
If you want to simply clear the database and start from scratch, it is very simple. (assuming you are on Ubuntu these are the commands) I have found a reset is needed some time to get everything working smoothly again. 

sudo service fail2ban stop
sudo truncate -s 0 /var/log/fail2ban.log
sudo rm /var/lib/fail2ban/fail2ban.sqlite3
sudo service fail2ban restart

This resets both the fail2ban.log file and deletes the database which gets re-created on startup.

KR
Mitchell

**Comment by sebres** [comment]
The obsolete IPs will be deleted after purgeage (but currently the purge will never called in current master, see #1267).
Fixed in #1460 (sebres:0.10-full)
