### ISSUE TITLE
Fail2ban 0.8.13 using filter from version 0.10

### ISSUE THREAD

**Issue by LeonardoGentile** [fail2ban/fail2ban#1584]
The current pre-packaged debian version is 0.8.13.
I've seen some changes in the `filter.d` directory that are of course not available in previous releasees.
 
If I just replace my old filter.d with the new one (say from release 0.10) would it just work? Meaning, were there any breaking changes that will prevent my current release to work with new/updated filters?

**Comment by sebres** [comment]
> The current pre-packaged debian version is 0.8.13.

Unfortunately, but you can install it direct from github or from neurodebian...

> If I just replace my old filter.d with the new one (say from release 0.10) would it just work?

Short - no, all the changes in the new filter.d (and another config files) are partially compatible between 0.9 and 0.10 branches only (currently 0.10 accepts time input like `24h` where 0.9 expected integer in seconds). 
But both in contrast to 0.8 have many newer config reader possibilities (better and recursive interpolation, special substitution like `%(known/...)s` or `<known/...>`, etc)...

But some particular changes (e. g. in `failregex` etc) may be done 0.8 compatible, if made decent (missing substitution variables and methods, etc.). We have no intention of support such old versions resp. do the further development compatible for all versions... 
We can also not help, if maintainers of your distribution do not get out to release the newer versions...

**Comment by LeonardoGentile** [comment]
👍  Thanks
