### ISSUE TITLE
fail2ban unduly bans ssh users that log with public key

### ISSUE THREAD

**Issue by briceandre** [fail2ban/fail2ban#1585]
I have a debian server with fail2ban out-the-box configuration. 

clients are performing ssh tunnels to this server and, to do so, they use public key authentication. 

My problem is that each correct authentication is considered by fail2ban as failed. So, if configured for maximum 3 retries, after three successful connections, the client is banned from server.

Here is the useful auth.log extract where public key authentication is performed:
Oct 20 14:42:41 vps329792 sshd[5843]: Received disconnect from 81.241.184.11: 11: disconnected by user
Oct 20 14:42:41 vps329792 sshd[5841]: pam_unix(sshd:session): session closed for user tunnel
Oct 20 14:42:42 vps329792 sshd[5905]: Accepted publickey for tunnel from 81.241.184.11 port 39609 ssh2
Oct 20 14:42:42 vps329792 sshd[5905]: pam_unix(sshd:session): session opened for user tunnel by (uid=0)
Oct 20 14:42:43 vps329792 sshd[5907]: Received disconnect from 81.241.184.11: 11: disconnected by user
Oct 20 14:42:43 vps329792 sshd[5905]: pam_unix(sshd:session): session closed for user tunnel
Oct 20 14:42:43 vps329792 sshd[5908]: Accepted publickey for tunnel from 81.241.184.11 port 39610 ssh2
Oct 20 14:42:43 vps329792 sshd[5908]: pam_unix(sshd:session): session opened for user tunnel by (uid=0)
Oct 20 14:42:44 vps329792 sshd[5910]: Received disconnect from 81.241.184.11: 11: disconnected by user
Oct 20 14:42:44 vps329792 sshd[5908]: pam_unix(sshd:session): session closed for user tunnel

And here is corresponding fail2ban log:
2016-10-20 14:42:43,591 fail2ban.filter : DEBUG  Got event: 1 for /var/log/auth.log
2016-10-20 14:42:43,591 fail2ban.filter : DEBUG  File changed: /var/log/auth.log
2016-10-20 14:42:43,592 fail2ban.filter.datedetector: DEBUG  Sorting the template list
2016-10-20 14:42:44,593 fail2ban.filter : DEBUG  Got event: 1 for /var/log/auth.log
2016-10-20 14:42:44,593 fail2ban.filter : DEBUG  File changed: /var/log/auth.log
2016-10-20 14:42:44,594 fail2ban.filter.datedetector: DEBUG  Sorting the template list
2016-10-20 14:42:45,595 fail2ban.filter : DEBUG  Got event: 1 for /var/log/auth.log
2016-10-20 14:42:45,596 fail2ban.filter : DEBUG  File changed: /var/log/auth.log
2016-10-20 14:42:45,596 fail2ban.filter.datedetector: DEBUG  Sorting the template list

Thanks in advance for help,
Brice

**Comment by sebres** [comment]
> My problem is that each correct authentication is considered by fail2ban as failed

Where did you see that?
Please precise your issue... Because in your excerpt is neither failure (INFO [jail] Found IP) nor ban (NOTICE [jail] Ban IP) visible...

BTW. Fail2ban version? which jail? your customizations (e. g. in jail.local)?

**Comment by briceandre** [comment]
I saw it because each time I do three consecutive connections, I am banned for 60 seconds (which corresponds to my jail configuration).
I am using the default configuration of Debian.
Fail2ban version :  v0.8.6

**Comment by sebres** [comment]
> I saw it because each time I do three consecutive connections, I am banned for 60 seconds ...

But according to your fail2ban.log file it is not banned. As I already wrote, I don't see something like:
```
2016-10-20 16:04:33,007 fail2ban.filter          INFO    [sshd] Found 81.241.184.11
2016-10-20 16:04:33,045 fail2ban.actions         NOTICE  [sshd] Ban   81.241.184.11
```

So first check it is really fail2ban (e. g. stop fail2ban and try your test again).
Secondly search who is it really... (check iptables resp. another firewall settings, sshd configuration, etc).

BTW. 0.8.6 is very very old version.
