### ISSUE TITLE
Documentation: Regular Expressions

### ISSUE THREAD

**Issue by AlexisWilke** [fail2ban/fail2ban#1591]
On this page:

http://fail2ban.readthedocs.io/en/latest/filters.html

You have this paragraph:

> If the format is like `<date...> error 1.2.3.4 is evil` then you need to match the `<` at the start so regex should be similar to ‘^<> <HOST> is evil$’ using <HOST> where the IP/domain name appears in the log line.

and it looks like the regular expression should be:

> `^<> error <HOST> is evil$`

With the extra "error" keyword.

**Comment by sebres** [comment]
Thx, fixed
