### ISSUE TITLE
Please add new regexp for postfix-sasl

### ISSUE THREAD

**Issue by takenek** [fail2ban/fail2ban#1592]
Hey,
Please addd regexp to detect something like this:
Oct 24 06:58:51 taken postfix/smtps/smtpd[25795]: connect from unknown[62.4.15.68]
Oct 24 06:58:53 taken postfix/smtps/smtpd[25795]: warning: unknown[62.4.15.68]: SASL LOGIN authentication failed: authentication failure
Oct 24 06:58:54 taken postfix/smtps/smtpd[25795]: lost connection after AUTH from unknown[62.4.15.68]
Oct 24 06:58:54 taken postfix/smtps/smtpd[25795]: disconnect from unknown[62.4.15.68] ehlo=1 auth=0/1 commands=1/2

Thanks,

**Comment by sebres** [comment]
We've already a filter to find such failures (see https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/postfix-sasl.conf), you can activate jail `postfix-sasl` to use it directly...

Below an example how f2b find your failure...
```bash
fail2ban-regex "Oct 24 06:58:53 taken postfix/smtps/smtpd[25795]: warning: unknown[62.4.15.68]: SASL LOGIN authentication failed: authentication failure" /etc/fail2ban/filter.d/postfix-sasl.conf
```
```
Running tests
=============

Use   failregex filter file : postfix-sasl, basedir: config
Use      datepattern : Default Detectors
Use      single line : Oct 24 06:58:53 taken postfix/smtps/smtpd[25795]: ...


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] ^(?:\[\])?\s*(?:<[^.]+\.[^.]+>\s+)?(?:\S+\s+)?(?:kernel: \[ *\d+\.\d+\]\s+)?(?:@vserver_\S+\s+)?(?:(?:(?:\[\d+\])?:\s+[\[\(]?postfix(-\w+)?/(?:submission/|smtps/)?smtp[ds](?:\(\S+\))?[\]\)]?:?|[\[\(]?postfix(-\w+)?/(?:submission/|smtps/)?smtp[ds](?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)\s+)?(?:\[ID \d+ \S+\]\s+)?warning: [-._\w]+\[<HOST>\]: SASL ((?i)LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed(:[ A-Za-z0-9+/:]*={0,2})?\s*$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] {^LN-BEG}(?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: ExYear)?
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.00 sec]
