### ISSUE TITLE
How to create my own fail2ban configuration?

### ISSUE THREAD

**Issue by metroyanno** [fail2ban/fail2ban#1608]
Hello, I have **rinetd** server on Ubuntu 14.04 on port **8374** to redirect TCP packets to some server, can I create **my own** configuration to filtering ingoing traffic to **my rinetd server**? Can you give instructions, URI, examples? Thanks.

P.S. I'm russian, please don't say to me for my bad English, ok?

**Comment by sebres** [comment]
- **here is not a common forum resp. FAQ**, to seek for "non-support" help resp. to discuss support-irrelevant wish-requests, please try to find an answer or help somewhere in internet.
For example such communities like [stackoverflow](http://stackoverflow.com/search?q=fail2ban) or as russian speaking you can try to seek help on [тостер](https://toster.ru/search?q=fail2ban)
- you've not specified which log-lines are failures (no examples resp. log-excerpts at all provided), so also if someone want help you, he cannot do that
- you can try to write self your configuration (almost a regex), just create a new jail in your `jail.local` like here:
```
[rinetd]
filter =
failregex = ^your regex 1 that match failure 1 from <HOST>$
            ^your regex 2 that match failure 2 from <HOST>$
enabled = true
```
For more information see `man jail.conf` or e. g. https://manned.org/jail.conf.5
- to test your expression use `fail2ban-regex`, e. g.:
```bash
fail2ban-regex /path/to/log/file.log "^your regex 1 that match failure 1 from <HOST>$"
```
