### ISSUE TITLE
apache-noscript does not work

### ISSUE THREAD

**Issue by georgesuba** [fail2ban/fail2ban#1612]
Hi guys,

Thank you for fail2ban beauty! I have setup apache-noscript on and tested my rule.. which produces output: Lines: 118 lines, 0 ignored, 0 matched, 118 missed however when I test it from another ip to load cgi which does not exist 4 times the ip is still not get banned. 

OS: #1 Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

**Comment by sebres** [comment]
- we have made an issue template not for nothing, please provide more info (e. g. you've not specified your fail2ban version)
- you've not specified which log-lines are failures (no examples resp. log-excerpts at all provided), so also if someone want help you, he cannot do that

I'll close this issue (as impossible to handle) as long as you don't give here more informations
