### ISSUE TITLE
journalmatch = _SYSTEMD_UNIT=proftpd.service in proftpd.conf

### ISSUE THREAD

**Issue by kberry** [fail2ban/fail2ban#1613]
Suggest adding

[Init]
journalmatch = _SYSTEMD_UNIT=proftpd.service

in filter.d/proftpd.conf, exactly analogous to postfix.conf and others. This is on CentOS 7, fail2ban 0.9.5 (the available package), but I suppose it is the same for any systemd-using system.

Thanks for the great software.

**Comment by sebres** [comment]
Done in 6110ba9cc34e212d0ff6ac5be4b3d5bebadef794.

Thank you!
