### ISSUE TITLE
Q: Possibility to extend failregex in local filter

### ISSUE THREAD

**Issue by defkev** [fail2ban/fail2ban#1617]
I tried

`failregex += myregex`

in my filter.local, which doesn't get picked up at all.

Having to copy the failregex from config to local, including my additions, imho defeats the point of the local config in the first place.

CentOS Linux release 7.2.1511 (Core) running Fail2Ban v0.9.5 installed from epel

**Comment by sebres** [comment]
`failregex += myregex` would be not proper syntax for python configuration ini-file...

We have own extension for that - substitution for last known value of parameter - `%(known/param)s`.
So in your case:
```
failregex = %(known/failregex)s
           ^your 1st custom regex$
           ^your 2nd custom regex$
```

BTW. There is not obligatory to write this in `filter.local` - you could specify this in your `jail.local` also.

**Comment by defkev** [comment]
Perfect
Thanks!
