### ISSUE TITLE
Help,  How to correct install fail2ban 0.10 on CentOS5.6 ?

### ISSUE THREAD

**Issue by nottellyou** [fail2ban/fail2ban#1621]
Hi, all:
     I install python3 in /usr/local/python3, and I do not modify the system default python environment.

    This is my install process:

wget --no-check-certificate https://github.com/fail2ban/fail2ban/archive/0.10.zip
mv 0.10 0.10.zip
unzip 0.10.zip
cd fail2ban-0.10/
python3 setup.py install
cp files/debian-initd /etc/init.d/fail2ban

ln -s /usr/local/python3/bin/fail2ban-client /usr/bin/fail2ban-client
ln -s /usr/local/python3/bin/fail2ban-server  /usr/bin/fail2ban-server
ln -s /usr/local/python3/bin/fail2ban-testcases  /usr/bin/fail2ban-testcases
ln -s /usr/local/python3/bin/fail2ban-regex  /usr/bin/fail2ban-regex

service fail2ban start

But,  I can't find fail2ban-server process , and I don't known fail2ban is working or not.

**Comment by sebres** [comment]
> cp files/debian-initd /etc/init.d/fail2ban

I don't know which initd-script is more suitable for centos... In the case if it not startable via `service fail2ban start` resp. `/etc/init.d/fail2ban` you can get this script from default fail2ban-packet from the centos distribution.
If you've systemd, you should install fail2ban.service.

> But, I can't find fail2ban-server process , and I don't known fail2ban is working or not.

Fail2ban log-file (normally `/var/log/fail2ban.log`) is your friend...

You can also try to start it verbose via client:
```bash
# start with increased verbosity:
fail2ban-client -v start
# increase verbosity more:
fail2ban-client -vv start
```

You can also try to start fail2ban-server direct in foreground mode (to look what goes wrong):
```bash
fail2ban-server -f --logtarget=STDOUT start
# or with debug level:
fail2ban-server -f --logtarget=STDOUT --loglevel=DEBUG start

# use ctrl+c to stop it...
```

BTW. Take a look to [Properly-fail2ban-configuration](https://github.com/sebres/fail2ban/wiki/Properly-fail2ban-configuration).

**Comment by nottellyou** [comment]
@sebres  

Thanks,  I use redhat-initd to solve  it .·
