### ISSUE TITLE
fail2ban fails with error trying to import common.version w/ fix

### ISSUE THREAD

**Issue by ed45626** [fail2ban/fail2ban#1628]
If there's a module named 'common' in the search path before fail2ben starts, it tries to load common.version, fails, inserts it's path but python still recognizes the old module.

changed in fail2ban-client and fail2ban-server the import try/except to:

```
try:
    from common.version import version
except ImportError, e:
    sys.path.insert(1, "/usr/share/fail2ban")
    import common
    common = reload(common)
    from common.version import version
```

which officially loads common (can't reload until it's there even though python has cached it's location), reloads it (get's the new path) and then imports version.

**Comment by sebres** [comment]
Not really understood what you need.

If you want check fail2ban version:
```python
from fail2ban.version import version
```

If you miss path in this python instance:
```bash
cd /path/to/fail2ban-root-folder/
PYTHONPATH=. bin/fail2ban-client --help
PYTHONPATH=. bin/fail2ban-server --help
```

Otherwise please clarify what you need...

**Comment by sebres** [comment]
Closed as answered, just let me know if I'm wrong
