### ISSUE TITLE
fail2ban stop working on log rotate (using pyinotify)

### ISSUE THREAD

**Issue by Mayhem30** [fail2ban/fail2ban#1629]
I'm having an issue with fail2ban - it's stops working immediately after my mail log is rotated. Once the log is rotated, this shows up in fail2ban.log file :

`2016-11-29 00:00:00,017 fail2ban.filter         [60129]: INFO    Log rotation detected for /var/log/maillog`

Nothing else shows up in the log file / no more bans happen until I restart fail2ban.

Setting "backend = polling" in jail.local solves the issue. However, this is not a desired option I would like to use on any permanent basis.

I'm using: 

- FreeBSD 10.3-RELEASE-p12
- python27-2.7.12
- py27-fail2ban-0.9.5 
- py27-pyinotify-0.9.6

**Comment by sebres** [comment]
Already fixed in 0.10th, no plan how to fix it in 0.9th stand (resp. not really feel like to fix in there, because of great difference in the code base).

Just compare:
https://github.com/fail2ban/fail2ban/compare/master...0.10?w=1#diff-c39443ec7a0a65afa3c20feb3ceb9c32
