### ISSUE TITLE
timeout in nftables sets

### ISSUE THREAD

**Issue by Smoque** [fail2ban/fail2ban#1633]
nftables has ability to set timeouts same as recent ipset. Here is some kind of patch for /etc/fail2ban/action.d/nftables-common.conf.

First of all, enable timeout flag in f2b-set:
```
- actionstart = <nftables> add set <nftables_family> <nftables_table> f2b-<name> \{ type <nftables_type>\; \}
+ actionstart = <nftables> add set <nftables_family> <nftables_table> f2b-<name> \{type <nftables_type>\; flags timeout\;\}
```

Another way to find appropriate rule inside input chain:
```
- _nft_get_handle_id = grep -m1 'ip saddr @f2b-<name> <blocktype> # handle' | grep -oe ' handle [0-9]*'
+ _nft_get_handle_id = awk -F'#' '/ip saddr @f2b-<name> .* # handle/{print $2}'
```

Now ban IP with timeout:
```
- actionban = <nftables> add element <nftables_family> <nftables_table> f2b-<name> \{ <ip> \}
+ actionban = <nftables> add element <nftables_family> <nftables_table> f2b-<name> \{<ip> timeout <bantime>s\}
```

Finally, remove banned IP:
```
- actionunban = <nftables> delete element <nftables_family> <nftables_table> f2b-<name> \{ <ip> \}
+ actionunban = <nftables> delete element <nftables_family> <nftables_table> f2b-<name> \{<ip> timeout <bantime>s\}
```
or even better:
```
+ actionunban =
```
as banned IPs will automagically disappear after timeout.

PS: tested on Debian Jessie & Stretch and on ALT Linux P8 & Sisyphus.

**Comment by AnTiZ** [comment]
Set element timeouts were added in nftables 0.5 so while I haven't tested it I'd expect it to work fine on Ubuntu 16.04 - Xenial installations as well (they don't have 0.6 packaged).

Careful with the empty `actionunban`, though. While the timeouts would handle normal operation without a problem, IPs can also be unbanned manually through the fail2ban-client utility. An empty `actionunban` would remove that possiblity.

**Comment by sebres** [comment]
Why it should be more preferable as the control of unban time point via fail2ban?
BTW. Newer version of fail2ban will get dynamic ban-time, which depending on the bad-factor of IP.
Additionally as @AnTiZ already correct said, it removes the possibility of manually unbanning.
