### ISSUE TITLE
Complain action - define sender

### ISSUE THREAD

**Issue by wioxjk** [fail2ban/fail2ban#1635]
I am using fail2ban with SSH jail and it works perfect. Everything someone is blocked, the owner of the IP address of the offender does get a email regarding the issue. That works perfekt and I have got several email that the provider has taken action.

Anyway, fail2ban do send thoose complain email from the user root@$HOSTNAME, where can I change it? Or is it even possible?

Thanks

**Comment by sebres** [comment]
Dependent on your configs resp. mail-actions you use either you should set parameter `sender` in your `jail.local` or (if it will not be used in action) add it to the action:
```bash
# set sender:
sender = fail2ban

# pass it to action:
action = %(banaction)s[...]
         %(mta)s-whois[..., sender="%(sender)s", ..."]
```
For examples see `jail.conf`

**Comment by wioxjk** [comment]
Hi,

This did not solve it.

**Comment by sebres** [comment]
Can you follow please our issue template, that we've made not for nothing (e. g. I miss fail2ban version, system version, some customization you've done, log excerpts etc.).

You can try to verbose dump your configuration (you see there all the config files loaded, and ready parameters used):
```bash
fail2ban-client -vv -d
```

Or post here an excerpt round about action:
```bash
fail2ban-client -d | grep 'action'
```

For typically resp. properly configuration please see https://github.com/sebres/fail2ban/wiki/Properly-fail2ban-configuration

If you've no changes and customization in `.conf` files, it is enough (as already said) to overwrite `sender` parameter in default or jail section in your `jail.local` (same place as `jail.conf`):
```bash
# jail.local

[DEFAULT]
# overwrite default sender:
sender = fail2ban@localhost

# sshd jail using standard banaction and mail-action:
[sshd]
action = %(action_mw)s
enabled = true

# custom jail using custom mail action:
[other-jail]
sender = other-sender@localhost
action = %(action_)s
         my-custom-mail-action[sender="%(sender)s"]
enabled = true
```
