### ISSUE TITLE
fail2ban-client status --> Broken pipe

### ISSUE THREAD

**Issue by quantonganh** [fail2ban/fail2ban#1641]
### Environment:

- Fail2Ban version: 0.9.6
- OS, including release name/version: Ubuntu 14.04
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Fail2Ban failed to restart after upgrading from 0.8.14 to 0.9.6

#### Steps to reproduce

- install 0.8.14 (`python setup.py install --install-scripts=/usr/bin`)
- upgrade to 0.9.6

then we cannot restart the service using the init script (which is the same as `files/debian-initd` except that we change the `DAEMON` to `/usr/bin/$NAME-client`).

`bash -x /etc/init.d/fail2ban stop`:

```
+ echo ' * Stopping authentication failure monitor' fail2ban
 * Stopping authentication failure monitor fail2ban
+ COL=
+ do_stop
+ /usr/bin/fail2ban-client status
+ return 1
+ log_end_msg_wrapper 1 2 ''
+ '[' '' '!=' no ']'
+ '[' 1 -lt 2 ']'
+ value=0
+ log_end_msg 0
+ '[' -z 0 ']'
+ '[' '' ']'
+ '[' 0 -eq 0 ']'
+ echo '   ...done.'
   ...done.
+ return 0
```

problem:

```
fail2ban-client status
Status
|- Number of jail:      1
`- Jail list:   ssh
Traceback (most recent call last):
  File "/usr/bin/fail2ban-client", line 4, in <module>
    __import__('pkg_resources').run_script('fail2ban==0.9.6', 'fail2ban-client')
  File "/usr/local/fail2ban/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 726, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/fail2ban/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1484, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/fail2ban/lib/python2.7/site-packages/fail2ban-0.9.6-py2.7.egg/EGG-INFO/scripts/fail2ban-client", line 472, in <module>
    if client.start(sys.argv):
  File "/usr/local/fail2ban/lib/python2.7/site-packages/fail2ban-0.9.6-py2.7.egg/EGG-INFO/scripts/fail2ban-client", line 442, in start
    return self.__processCommand(args)
  File "/usr/local/fail2ban/lib/python2.7/site-packages/fail2ban-0.9.6-py2.7.egg/EGG-INFO/scripts/fail2ban-client", line 281, in __processCommand
    return self.__processCmd([cmd])
  File "/usr/local/fail2ban/lib/python2.7/site-packages/fail2ban-0.9.6-py2.7.egg/EGG-INFO/scripts/fail2ban-client", line 185, in __processCmd
    client.close()
  File "/usr/local/fail2ban/local/lib/python2.7/site-packages/fail2ban-0.9.6-py2.7.egg/fail2ban/client/csocket.py", line 55, in close
    self.__csock.sendall(CSPROTO.CLOSE + CSPROTO.END)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 32] Broken pipe
```

```
    stop)
        [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
        do_stop
        log_end_msg_wrapper $? 2 "$VERBOSE"
        ;;
```

`do_stop()` returned 1.

```
log_end_msg_wrapper()
{
    if [ "$3" != "no" ]; then
        [ $1 -lt $2 ] && value=0 || value=1
        log_end_msg $value
    fi
}
```

```
+ log_end_msg_wrapper 1 2 ''
+ '[' '' '!=' no ']'
+ '[' 1 -lt 2 ']'
+ value=0
+ log_end_msg 0
```

Question: why `log_end_msg 0` while the return value of `do_stop()` = 1?

#### Expected behavior

`fail2ban-client status` returns 0 --> fail2ban service can be restarted.

**Comment by sebres** [comment]
> Steps to reproduce ...
```
    install 0.8.14 (python setup.py install --install-scripts=/usr/bin)
    upgrade to 0.9.6
```

In-between a stupid question: Are you sure that before it was upgraded, the version 0.8 was stopped firstly? Just to be sure... Because if not it may be a setup-issue (missing `fail2ban-client stop` in setup.py)...

**Comment by quantonganh** [comment]
> Are you sure that before it was upgraded, the version 0.8 was stopped firstly?

You're right. I didn't stop the service before upgrading.
I'm trying to handle it by using [SaltStack](https://github.com/saltstack/salt).

> Because if not it may be a setup-issue (missing fail2ban-client stop in setup.py)...

Did you mean that this should be done in the `setup.py`?

**Comment by sebres** [comment]
> Did you mean that this should be done in the setup.py?

Well, after upgrade the protocol (client/server communication) could be incompatible... So someone should shut down previous version of fail2ban during upgrade... `setup.py` would be just a good candidate to do this.

**Comment by quantonganh** [comment]
> I'm trying to handle it by using SaltStack.

In case someone want to know how can I do this:

```
{%- if salt['file.file_exists']('/usr/bin/fail2ban-client') -%}
  {%- set current_version = salt['cmd.run']('/usr/bin/fail2ban-client --version | head -1') -%}
  {%- if salt['service.status']('fail2ban') and current_version != 'Fail2Ban v' ~ version %}
fail2ban_old_version:
  cmd:
    - run
    - name: /usr/bin/fail2ban-client stop
    - require_in:
      - archive: fail2ban
  {%- endif -%}
{%- endif %}

fail2ban:
  archive:
    - extracted
    - name: /usr/local/fail2ban/src
    - source: https://github.com/fail2ban/fail2ban/archive/{{ version }}.tar.gz
    - source_hash: md5=8758789d40366f5e212b4e6b629297d1
    - if_missing: /usr/local/fail2ban/src/fail2ban-{{ version }}
    - archive_format: tar
    - tar_options: z
    - require:
      - file: /usr/local/fail2ban/src
```
