### ISSUE TITLE
Default message patterns to protect web apps

### ISSUE THREAD

**Issue by benrubson** [fail2ban/fail2ban#1642]
Hello,

Would be nice if we could find some default message patterns which could be used by web applications to trigger Fail2Ban, without having to deploy new rules.
These patterns would have to be integrated to existing Apache / Nginx / Lighttpd filters (the auth ones).

I propose the following patterns, which are not far from the already existing ones in Apache & Nginx :
```
user "bob" not found: My Protected Web Application
user "bob" password mismatch: My Protected Web Application
client used invalid token: My Protected Web Application
```

Edit : see [this message](#issuecomment-269220121) below for an update.

Thank you 👍 

Ben

**Comment by benrubson** [comment]
Solved by #1643 👍

**Comment by szepeviktor** [comment]
How would your app tell e.g. Apache to log these messages?

**Comment by benrubson** [comment]
As an example, if it's a PHP app, you can use [error_log()](http://php.net/manual/en/function.error-log.php).

**Comment by szepeviktor** [comment]
That looks like this
```apache
[Fri Dec 23 14:58:26.955220 2016] [proxy_fcgi:error] [pid 8494:tid 139854318851840] [client 54.240.157.87:18275] AH01071: Got error 'PHP message: 404 error: URL not found: https://www.chickenbanana.com/assets/css/lightbox/close.png\n'
```

**Comment by szepeviktor** [comment]
`URL not found: https://www.chickenbanana.com/assets/css/lightbox/close.png\n`
is the output of error_log()

**Comment by szepeviktor** [comment]
I don't see `Got error 'PHP message:` anywhere in your PR.

**Comment by benrubson** [comment]
I did not mention `PHP` because the app could also use Perl etc...
These are intended to be generic messages every app (written in PHP, in Perl... in every langage) could adopt / use as their default auth failure messages.

In PHP, if you do :
`error_log("user \"$username\" not found: MyApp");`
You'll find the corresponding entry in the Apache error log file :
`[Mon Dec 19 19:00:31 2016] [error] [client 1.2.3.4] user "bob" not found: MyApp`

It will then be caught by the generic new rules of this PR 👍

**Comment by szepeviktor** [comment]
> You'll find the corresponding entry in the Apache error log file :

Could you tell me what SAPI are you using? I think it is mod_php.

Please think about production installs where MPM event + PHP-FPM is in use an has this part prepended: `Got error 'PHP message:`

**Comment by szepeviktor** [comment]
I do not know whether Python and Rudy prepend something...

**Comment by benrubson** [comment]
Yep in this example it is `mod_php`.

We were thinking about some message patterns to adopt (or anything else) with the author of php-remote-storage application, in [this ticket](https://github.com/fkooman/php-remote-storage/issues/54).
This is the reason of this PR.
I also implemented these messages individually in other applications before, so I think it could be nice to try to adopt a "common way".

**Comment by benrubson** [comment]
See PR #1646 for an alternative solution to PR #1643.

It allows the following messages :
```
user "bob" not found: My Protected Web Application
user "bob" not authorized: My Protected Web Application
user "bob" password mismatch: My Protected Web Application
user sent invalid token: My Protected Web Application
user misbehaved: My Protected Web Application
```
Giving the following rule :
```
user \S* ?(not found|not authorized|password mismatch|sent invalid token|misbehaved): .+
```

I also added the MPM event / PHP-FPM Apache prepending.

I think it's much better 👍

**Comment by sebres** [comment]
further in PR #1646
