### ISSUE TITLE
IPv6 logo

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#1647]
Adding the ipv6 logo to the readme would be nice
http://www.worldipv6launch.org/wp-content/themes/ipv6/downloads/World_IPv6_launch_logo.svg

Modifying size parameters: `width="512px" height="512px" viewBox="0 0 512 512" enable-background="new 0 0 512 512"`

**Comment by sebres** [comment]
[Click to see how it looks](https://github.com/fail2ban/fail2ban/blob/ipv6-logo-gh-1647/README.md)
