### ISSUE TITLE
Why using uname -n instead of hostname -f ?

### ISSUE THREAD

**Issue by Dual-Boot** [fail2ban/fail2ban#1653]
Hi,

why using uname -n into sendmail-*.conf instead of hostname -f ?
When I receive mail I only have the short name of the server which is not clear when you have multiple domain.
 In my opinion, it is clearer to use hostname -f to have the FQDN into the mail subject.
For exemple in sendmail-common.conf : 
```actionstart = printf %%b "Subject: [Fail2Ban] <name>: started on `uname -n` ```
So I override it by using in sendmail-common.local
```actionstart = printf %%b "Subject: [Fail2Ban] <name>: started on $(hostname -f)```

 Regards,

And Thank you for the job.

**Comment by sebres** [comment]
I think `uname`  is a POSIX/SUSv4-compliant command, whereas `hostname` is not.

But we could indeed add it optionally with something like this:
```
[DEFAULT]
_host_fqdn = `if hash hostname 2>/dev/null; then hostname -f; else uname -n; fi`
hostname = `uname -n`
```
So it can be overridden in `jail.local`:
```
[DEFAULT]
...
hostname = %(_host_fqdn)s
```

**Comment by Dual-Boot** [comment]
Nice tips.
Thank you.
