### ISSUE TITLE
fail2ban-regex broken against journal in 0.9.6

### ISSUE THREAD

**Issue by opoplawski** [fail2ban/fail2ban#1657]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): 0.9.6
- OS, including release name/version: Fedora 25
- [ X] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

```
breaks fail2ban-regex when testing against systemd-journal.

fail2ban-regex "systemd-journal" /etc/fail2ban/filter.d/sshd.conf

Running tests
=============

Use   failregex filter file : sshd, basedir: /etc/fail2ban
Use         maxlines : 10
Use    journal match : _SYSTEMD_UNIT=sshd.service + _COMM=sshd

Traceback (most recent call last):
  File "/bin/fail2ban-regex", line 34, in <module>
    exec_command_line()
  File "/usr/lib/python3.5/site-packages/fail2ban/client/fail2banregex.py", line 599, in exec_command_line
    if not fail2banRegex.start(opts, args):
  File "/usr/lib/python3.5/site-packages/fail2ban/client/fail2banregex.py", line 538, in start
    self.process(test_lines)
  File "/usr/lib/python3.5/site-packages/fail2ban/client/fail2banregex.py", line 370, in process
    for line_no, line in enumerate(test_lines):
  File "/usr/lib/python3.5/site-packages/fail2ban/client/fail2banregex.py", line 93, in journal_lines_gen
    yield FilterSystemd.formatJournalEntry(entry)
TypeError: formatJournalEntry() missing 1 required positional argument: 'logentry'
```
#### Any additional information

https://bodhi.fedoraproject.org/updates/FEDORA-2017-33e3a599fa

**Comment by sebres** [comment]
Thx Orion, 

same for 0.10th, I'll take a look a bit later

**Comment by sebres** [comment]
@opoplawski Fixed and merged in master now.

**Comment by opoplawski** [comment]
Great, thanks.

**Comment by opoplawski** [comment]
What's the 0.9 backport fix? Because we're still seeing the problem with 2009f1c4346597dcc4fd27151d220ea4a7806fdd

**Comment by sebres** [comment]
Which message exactly? Seems to be correct, and by me this works

**Comment by opoplawski** [comment]
Sorry - it was a mistake by a tester.  Should be okay now.

**Comment by sebres** [comment]
Glad it finally worked out. ;)
