### ISSUE TITLE
Fail2Ban banning wrong IPv6

### ISSUE THREAD

**Issue by oliverdorn** [fail2ban/fail2ban#1658]
Today I tested fail2ban 0.10 on my server by entering wrong passwords for sshd. Connection was established via IPv6. The ban was set after 3 failed login attempts, but the wrong IP has been banned, as you can see in the report mail:

> The IP aaaa:bbbb:cccc:1287::1 has just been banned by Fail2Ban after
3 attempts against sshd.
...
monitoring sshd[23903]: Failed password for administrator from aaaa:bbbb:cccc:1287::1:1 port 60910 ssh

aaaa:bbbb:cccc:1287 **::1** <--> aaaa:bbbb:cccc:1287 **::1:1**

Regards Oli

**Comment by sebres** [comment]
Thx @oliverdorn 
I've fixed it now for both major branches (missing space character after colon, see 7019640eb3d1f901e52b4c00cb6d029e82fdda17). But it concerns to 0.10th branch only.
