### ISSUE TITLE
Modifying or improving [nginx-botsearch]

### ISSUE THREAD

**Issue by mitchellkrogza** [fail2ban/fail2ban#1659]
_We will be very grateful, if your problem was described as completely as possible,
enclosing excerpts from logs (if possible within DEBUG mode, if no errors evident
within INFO mode), and configuration in particular of effected relevant settings
(e.g., with ` fail2ban-client -d | grep 'affected-jail-name' ` for a particular
jail troubleshooting).
Thank you in advance for the details, because such issues like "It does not work" 
alone could not help to resolve anything!
Thanks! (remove this paragraph and other comments upon reading)_

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): 0.9.3
- OS, including release name/version: Ubuntu 16.04
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

Using [nginx-botsearch] jail out of box without any modifications, no wp-login brute force attempts are being picked up. The regex for [nginx-botsearch] scans for:

(GET|POST|HEAD) with a 404 error

and

(GET|POST|HEAD) with a (failed|is not found) / No such file or directory error

But it does not detect wp-login attempts as per log line(s) below:

```1.1.1.1 - - [09/Jan/2017:10:50:27 +0200] "POST /wp-login.php HTTP/1.1" 500 4332 "https://www.myweb.com/wp-login.php" "Opera/9.80 (Windows NT 6.2; Win64; x64) Presto/2.12.388 Version/12.17" "-"PORT:443 0.271 0.271 . "GZIP:-" ```

```1.1.1.1 - - [09/Jan/2017:10:50:31 +0200] "POST /wp-login.php HTTP/1.1" 503 206 "https://www.myweb.com/wp-login.php?redirect_to=https%3A%2F%2Fwww.myweb.com%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dcategory&reauth=1" "Opera/9.80 (Windows NT 6.2; Win64; x64) Presto/2.12.388 Version/12.17" "-"PORT:443 0.000 - . "GZIP:-" ```

Would adding below into [nginx-botsearch] deal with this accurately?

```failregex = 
^<HOST> \- \S+ \[[^\]]*\] \"(\w+) /wp-login.php \S+\" 500
^<HOST> \- \S+ \[[^\]]*\] \"(\w+) /wp-login.php \S+\" 503```


#### Steps to reproduce



#### Expected behavior

#### Observed behavior

#### Any additional information

### Configuration, dump and another helpful excerpts

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```1.1.1.1 - - [09/Jan/2017:10:50:27 +0200] "POST /wp-login.php HTTP/1.1" 500 4332 "https://www.myweb.com/wp-login.php" "Opera/9.80 (Windows NT 6.2; Win64; x64) Presto/2.12.388 Version/12.17" "-"PORT:443 0.271 0.271 . "GZIP:-" ```

```1.1.1.1 - - [09/Jan/2017:10:50:31 +0200] "POST /wp-login.php HTTP/1.1" 503 206 "https://www.myweb.com/wp-login.php?redirect_to=https%3A%2F%2Fwww.myweb.com%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dcategory&reauth=1" "Opera/9.80 (Windows NT 6.2; Win64; x64) Presto/2.12.388 Version/12.17" "-"PORT:443 0.000 - . "GZIP:-" ```

**Comment by sebres** [comment]
> Would adding below into [nginx-botsearch] deal with this accurately?

I don't think so.
To match it successfully it would be sufficient enough:
```diff
- failregex = ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) \/<block> \S+\" 404 .+$
+ failregex = ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) \/<block> \S+\" [45]0\d .+$
# or
+ failregex = ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) \/<block> \S+\" 404|50\d .+$
```

But legitimate question would be, why this returns 500 (or 503) if it is in really IMHO 401 (Unauthorized) or something similar.
Or I missed something?

**Comment by mitchellkrogza** [comment]
Perfect thanks @sebres I think the `failregex = ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) \/<block> \S+\" 404|50\d .+$` looks like the one that might do it. I will disable my wp-login jail completely and add this regex to [nginx-botsearch] and see how it goes. Thanks for your help

**Comment by sebres** [comment]
I've corrected it above to `(?:404|50\d)`.
But why 500?

**Comment by mitchellkrogza** [comment]
I have Nginx configured this way, first few attempts to wp-login.php generates a 403 then rate limiting kicks in and starts generating 500 errors.

**Comment by sebres** [comment]
Uh-huh!

The you should use another jail/filter - `nginx-limit-req`, see https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/nginx-limit-req.conf

**Comment by mitchellkrogza** [comment]
Thanks @sebres I'll check that out. I don't want to block everything that gets rate limited only those doing wp-login brute force attempts. I have a filter that rate limits some crawlers but just to slow them down when they get agressive, those one's I do not want to ever permanently block.

**Comment by sebres** [comment]
Just use different zone-names

**Comment by mitchellkrogza** [comment]
Just figured that out but you beat me to comment 😄

**Comment by mitchellkrogza** [comment]
I must move to 0.10 because the nginx-limit-req is not in 0.9.3 branch. I manually put it into my 0.9.3 and configured the jail and will see how it works. Thanks again 😉

**Comment by sebres** [comment]
Don't use it from 0.10 (it could be incompatible, e. g. `datepattern = {^LN-BEG}`), just take the same filter from latest master (0.9) branch.

**Comment by mitchellkrogza** [comment]
Great thanks @sebres I have take it now from 0.9 and restarted Fail2Ban and will monitor it.
Is this the correct way of specifying the zone
`ngx_limit_req_zones = wp-login` ??

**Comment by sebres** [comment]
Depends on where it is: if in block `Definition` of your nginx-limit-req.local, then - yes.
Otherwise, not. But I don't know how 0.9th branch will manage it.
For example in 0.10 it would be sufficient enough to write in filter-declaration in jail.local:
```
[wp-login]
filter = nginx-limit-req[ngx_limit_req_zones="wp-login"]
```
But I think in 0.9 you can redefine parameters of the Init-block only. Then `ngx_limit_req_zones` goes into Init-block and the regex should use another convention, so instead of `%(ngx_limit_req_zones)s` it should be `<ngx_limit_req_zones>`. Because Init-parameters are runtime-parameters, and will be substituted implicit before regex-usage (see #1509 for more information).

In any case you can check whether it was correct interpolated using following dump command (without restart of fail2ban)...
```bash
fail2ban-client -d | grep "wp-login"
```

I think in your case you should create a two-lines local-filter `nginx-limit-req.local` and overwrite there the value of ngx_limit_req_zones only, for example:
```
# nginx-limit-req.local
[Definition]
ngx_limit_req_zones = wp-login|f2b-block

# jail.local:
[wp-login]
...
filter = nginx-limit-req
...
```

**Comment by mitchellkrogza** [comment]
Thanks @sebres here is my output of `fail2ban-client -d | grep "wp-login"`

`['set', 'nginx-limit-req', 'addfailregex', '^\\s*\\[error\\] \\d+#\\d+: \\*\\d+ limiting requests, excess: [\\d\\.]+ by zone "(?:wp-login|one)", client: <HOST>']`

I have the nginx-limit-req filter configured as:

`ngx_limit_req_zones = wp-login|one`

where "wp-login" is the new renamed zone and "one" was the old one.

My jail.local is setup as follows:

```[nginx-limit-req]
enabled = true
port    = http,https
filter = nginx-limit-req
logpath = %(nginx_error_log)s
maxretry = 1```

I will change it to a nginx-limit-req.local file .... I must get into that habit and stop messing with core files 😬

**Comment by mitchellkrogza** [comment]
And Happiness is !!! It is working

`Lines containing IP:65.191.10.48 in /var/log/nginx/*error.log 

/var/log/nginx/mitchellkrog.com-error.log:2017/01/10 16:20:44 [error] 31382#31382: *1201328 limiting requests, excess: 2.264 by zone "wp-login", client: 65.191.10.48, server: mitchellkrog.com, request: "GET /wp-login.php HTTP/1.1", host: "mitchellkrog.com" `

Thank you @sebres 👍

**Comment by mitchellkrogza** [comment]
It's working like an absolute charm, have nailed 10 IP's in the last hour that were previously slipping past my nginx-login filter. Excellent !!!
