### ISSUE TITLE
Question regarding .local files for filters

### ISSUE THREAD

**Issue by mitchellkrogza** [fail2ban/fail2ban#1664]
If I wanted to modify or add to the regex for the nginx-botsearch filter. I create a nginx-botsearch.local file in the filter.d folder.

Must the .local file ONLY contain additional regex's to be added or must I specify all of them including what's in the original filter?

So for instance should my nginx-botsearch.local file look like this

```
failregex = ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) \/<block> \S+\" 404 .+$
            ^ \[error\] \d+#\d+: \*\d+ (\S+ )?\"\S+\" (failed|is not found) \(2\: No such file or directory\), client\: <HOST>\, server\: \S*\, request: \"(GET|POST|HEAD) \/<block> \S+\"\, .*?$
			^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) \/<block> \S+\" (?:403|444) .+$
```

or just like this

```
failregex = ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) \/<block> \S+\" (?:403|444) .+$
```

**Comment by sebres** [comment]
Since we support an extensions called "known" with syntax `%(known/option)s` (I think, I've introduced it somewhere 0.9.3 or 0.9.4), it allows to use the same last known option (from includes resp. from corresponding `.conf` file for local usage)...

So you can try to use in your `.local` file:
```
failregex = %(known/failregex)s
            ^your custom additionally regex 1$
            ^your custom additionally regex 2$
```
If your version does not support "known", you'll get an interpolation error by testing it with 
`fail2ban-client -d`.

See fail2ban manpages `jail.conf.5` resp. #1509 for more information about parameters substitution.

**Comment by mitchellkrogza** [comment]
Thanks @sebres that does work using `%(known/failregex)s` on 0.9.3 however is there any way to tell it not to add what is in "before = botsearch-common.conf" and just put my regex in exactly as I have put it ?

Instead of it adding this regex

`^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) \/<block> \S+\" (?:403|444) .+$`

It's adding it like this

`^<HOST> \\- \\S+ \\[\\] \\"(GET|POST|HEAD) \\/\\/?(roundcube|(ext)?mail|horde|(v-?)?webmail|(typo3/|xampp/|admin/|)(pma|(php)?[Mm]y[Aa]dmin)|wp-(login|signup)\\.php|cgi-bin|mysqladmin)[^,]* \\S+\\" (?:403|444) .+$`

**Comment by sebres** [comment]
Well it expands `<block>` run-time substitution as expected. 
If you don't want it, just don't use `<block>`...

Or I don't understand what you want.

**Comment by sebres** [comment]
You can also overwrite `block` in jail, by specifying:
```
[my-jail]
my-own-block-list = admin\.htm|(?:very-)?bad\.php|login\.php
filter = nginx-botsearch[block="%(my-own-block-list)s"]
```
At least in 0.10 it should work so, no idea it works in 0.9.3...

Then you should overwrite it in the section `Init` of your `nginx-botsearch.local`

**Comment by mitchellkrogza** [comment]
Sorry @sebres silly me I changed it to:

`^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) \/ \S+\" (?:403|444) .+$` I was inlcuding the <block>
