### ISSUE TITLE
Wrong paths for apache and nginx log files under FreeBSD

### ISSUE THREAD

**Issue by chtheis** [fail2ban/fail2ban#1667]
In the files config/paths-freebsd.conf the pathes to the log files of apache and nginx are wrong.
They should read as:
apache_error_log = /var/log/httpd-error.log
apache_access_log = /var/log/httpd-access.log
and
nginx_error_log = /var/log/nginx/error.log
nginx_access_log = /var/log/nginx/access.log

**Comment by sebres** [comment]
fixed in #1673
