### ISSUE TITLE
Action MWL, change order and limit log lines

### ISSUE THREAD

**Issue by kevin-olbrich** [fail2ban/fail2ban#1672]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): Fail2Ban v0.9.3
- OS, including release name/version: Debian GNU/Linux stretch/sid
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

Mails generated by "action_mwl" are long if an attack is in progress even after several bans. It would also be great if message order could be modified to help in automatic abuse mailings.

#### Steps to reproduce

Activate action_mwl.

#### Expected behavior

Option to change text order from intro, whois and unlimited log lines to intro, 10 log lines and whois.

#### Any customizations done to /etc/fail2ban/ configuration

Created new custom config for asterisk.

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
Example for v.0.10 (in your `jail.local`):

```INI
[some-jail]
# last 10 lines forwards ordered:
action = %(action_mwl)s[grepmax=10]
# last 10 lines backwards ordered:
action = %(action_mwl)s[grepmax=10, greplimit="tail -n <grepmax> | tac"]
```

For v.0.9 it is not so easy using default configs, rather you can write your own custom action mail-whois-lines.local (or another you need), and rewrite [line with grep](https://github.com/fail2ban/fail2ban/blob/master/config/action.d/mail-whois-lines.conf#L49) with `-m 10 ... | tail ... | tac`, etc.
