### ISSUE TITLE
Server won't start if socket folder doesn't exist

### ISSUE THREAD

**Issue by Neraste** [fail2ban/fail2ban#168]
Hey fail2ban development team!

Using systemd on a openSuse 12.2 system, it seems fail2ban cannot start if there is no ```fail2ban``` folder in ```/var/run```.

So, I have made a small directory creation instruction in ```fail2ban-client``` at line 187:
```python

# Create socket folder if it doesn't exist
try:
        os.mkdir(os.path.dirname(self.__conf["socket"]))
except OSError:
        logSys.info("Socket folder already exists")
```
It is probably in the wrong place and I am not sure it occurs in any Linux distribution, but hope it helps.

Edit: I am sorry I have missed to notice post (https://github.com/fail2ban/fail2ban/issues/72) before posting...

**Comment by leeclemens** [comment]
This seems like the package maintainers' responsibility, which we can certainly add to our "files/" scripts. And #399 may also be closable...which may make this closable as well.

**Comment by leeclemens** [comment]
While maintainer and script should deal with this, imho, distutils/setuputils does now too (thanks to #1068), closing.

**Comment by leeclemens** [comment]
Maybe over zealously closed...

**Comment by yarikoptic** [comment]
I think it is ok to let this issue die indeed, especially with #1068 addition in place, so you weren't over zealous @leeclemens ;)
