### ISSUE TITLE
Need help with Datepattern

### ISSUE THREAD

**Issue by basildane** [fail2ban/fail2ban#1681]
I'm just getting started with Fail2ban and I'm completely stuck on the datepattern.  This seems simple but I can't get it to recognize my log.  I simplified it to just the date and host as follows.  What am I doing wrong?

`fail2ban-regex -d "%%Y:%%m:%%d-%%H:%%M:%%S" "2017:02:02-16:45:09 basil srcip=208.89.211.170" "srcip=<HOST>"`

Running tests

Use      datepattern : %Y:%m:%d-%H:%M:%S
Use   failregex line : srcip=<HOST>
Use      single line : 2017:02:02-16:45:09 basil srcip=208.89.211.170

Results

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:

Lines: 1 lines, 0 ignored, 0 matched, 1 missed
[processed in 0.00 sec]

|- Missed line(s):
|  2017:02:02-16:45:09 basil srcip=208.89.211.170
`-

**Comment by sebres** [comment]
Percent-char escape (doubly `%`) is necessary in config files only.

By testing from the shell you should give it as is:
```bash
fail2ban-regex -d "%Y:%m:%d-%H:%M:%S" ....
```
