### ISSUE TITLE
Postfix logfile on Ubuntu/debian is not mail.warn so it fails to start

### ISSUE THREAD

**Issue by rigtersys** [fail2ban/fail2ban#1687]
In the file **fail2ban/paths-common.conf** it states that:
 
     postfix_log = %(syslog_mail_warn)s

however on Ubuntu systems the file /var/log/mail.warn is not used anymore by the default rsyslogd. In the default /etc/rsyslog.d/50-default.conf the mail.warn line is commented:
       #mail.warn			-/var/log/mail.warn

Everything is logged to /var/log/mail.log  

That means that if you want to use the Postfix jail with the default settings in fail2ban on Ubuntu/debian it won't start since it can't find the logfile for postfix, since the file /var/log/mail.warn isn't created anymore.

     rvl@ub05 /etc/fail2ban $ /usr/bin/fail2ban-client -x start 
     ERROR  No file(s) found for glob /var/log/mail.warn
     ERROR  Failed during configuration: Have not found any log file for postfix jail

the default setting of **postfix_log** in **fail2ban/paths-common.conf** should be :

    postfix_log = %(syslog_mail)s

**Comment by sebres** [comment]
`paths-common.con` is even common. If you meant debian, then it belongs rather to `paths-debian.conf`

**Comment by gaia** [comment]
Is it ok to just change the target log in jail.conf?

```
[postfix]

port     = smtp,465,submission,2525
logpath  = %(syslog_mail)s
enabled = true
filter = postfix-sasl
```

**Comment by jult** [comment]
Whoever decided journalctl was a better idea than the established rsyslog must be, well, not too smart.

**Comment by sebres** [comment]
> Whoever decided journalctl was a better idea than the established rsyslog must be, well, not too smart.

This may surely help:
```ini
[postfix]
backend = systemd
```
but about which system do you speak exactly?
Do I understand correct that by default debians postfix would log to systemd journal now?
