### ISSUE TITLE
ERROR: COMMAND_FAILED: '/sbin/iptables ...

### ISSUE THREAD

**Issue by z--aszlo** [fail2ban/fail2ban#1691]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): v0.9.6
- OS, including release name/version: CentOS 7
- [ X ] Fail2Ban installed via OS/distribution mechanisms
- [ X ] You have not applied any additional foreign patches to the codebase
- [ X ] Some customizations were done to the configuration (provide details below is so)

jail.conf
```
banaction = firewallcmd-ipset
#banaction_allports = iptables-allports
```
jail.local
```
banaction = firewallcmd-ipset
```
### The issue:

Looking at the status of my firewalld from systemctl lists errors like bellow for each fail2ban rule that I have set. Maybe it is rather a firewalld issue, but I can't get it what it is, I installed fail2ban awhile ago and I see it just now that it is not functioning.

2017-02-15 09:19:15 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t filter -I INPUT_direct 1 -p tcp -m multiport --dports http,https -m set --match-set fail2ban-apache-auth src -j REJECT --reject-with icmp-port-unreachable' failed: iptables v1.4.21: Set fail2ban-apache-auth doesn't exist.

#### Steps to reproduce
```
systemctl stop fail2ban
systemctl restart firewalld
systemctl start fail2ban
systemctl status -l firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: active (running) since Mi 2017-02-15 09:34:00 CET; 33min ago
 Main PID: 10535 (firewalld)
   CGroup: /system.slice/firewalld.service
           └─10535 /usr/bin/python -Es /usr/sbin/firewalld --nofork --nopid

feb 15 09:34:10 CentOS7 firewalld[10535]: 2017-02-15 09:34:10 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t filter -I INPUT_direct 1 -p tcp -m multiport --dports http,https -m set --match-set fail2ban-apache-auth src -j REJECT --reject-with icmp-port-unreachable' failed: iptables v1.4.21: Set fail2ban-apache-auth doesn't exist.
                                                            
                                                            Try `iptables -h' or 'iptables --help' for more information.
feb 15 09:34:10 CentOS7 firewalld[10535]: 2017-02-15 09:34:10 ERROR: COMMAND_FAILED: '/sbin/iptables -w2 -t filter -I INPUT_direct 1 -p tcp -m multiport --dports http,https -m set --match-set fail2ban-apache-overflows src -j REJECT --reject-with icmp-port-unreachable' failed: iptables v1.4.21: Set fail2ban-apache-overflows doesn't exist.
                                                            
                                                            Try `iptables -h' or 'iptables --help' for more information.
```
#### Expected behavior
No errors in firewalld.. don't know why it wants to run iptable commands when in banaction it is given firewalld.

**Comment by sebres** [comment]
I'm sure you've some rules in your firewalld script, relating to some fail2ban jails. I cannot say what and whether they are to be needed (you should know it better ;).
If so you should rename it, because in the newer version (I think somewhere in 0.9.3) the chains of jails have received new names. So instead of `fail2ban-apache-auth` -\> `f2b-apache-auth`.

Because 3rd party issue, I'll close it now...

**Comment by z--aszlo** [comment]
Checking on my firewalld rules I get:
```
firewall-cmd --list-all
public (default)
  interfaces: 
  sources: 
  services: dhcpv6-client ftp http https imaps pop3s smtp ssh
  ports: 110/tcp 465/tcp 587/tcp 143/tcp
  masquerade: no
  forward-ports: 
  icmp-blocks: 
  rich rules: 
```
@sebres I see it is a firewalld related 3d party issue, but please help out on fixing this. Where should I look to see for ex. the `fail2ban-apache-auth` and replace it with `f2b-apache-auth`?

**Comment by sebres** [comment]
I didn't say that you should rename they imperative (do it if wanted only).

If not just try to delete it:
```bash
firewall-cmd –delete-ipset=<name>
```

I'm not a friend of firewalld (never understand why iptables/ipsec needs such construct as firewalld), therefore I cannot say, where and why it should be expected to cache some sets of fail2ban there.

I knew not that we somewhere create permanent rules...

@fail2ban/contributors, @fail2ban/maintainers Any ideas?

**Comment by z--aszlo** [comment]
I would like to do whatever it takes to make it work ;)... so your approach would be to remove firewalld and use just iptables.. I'm a bit more familiar with that but wanted to use firewalld as that is the standard on RHEL from now on.
