### ISSUE TITLE
Custom action not allowing nested curls for Cloudflare

### ISSUE THREAD

**Issue by wpbullet** [fail2ban/fail2ban#1704]
### Environment:

- Fail2Ban version 0.9.3 
- OS, Ubuntu 16.04: 
- [X ] Fail2Ban installed via OS/distribution mechanisms
- [X ] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

I updated the Cloudflare action to work with the v4 API ([new script here](https://guides.wp-bullet.com/integrate-fail2ban-cloudflare-api-v4-guide/)) which works well with fail2ban 0.8.6. On fail2ban 0.9.3

#### Steps to reproduce

Use the Cloudflare action linked to above

#### Expected behavior

See cloudflare action active

#### Observed behavior

These errors are displayed when testing with fail2ban-client -d -vvv
```

DEBUG  Reading configs for filter.d/nginx-limit-req under /etc/fail2ban
DEBUG  Reading config files: /etc/fail2ban/filter.d/nginx-limit-req.conf
INFO     Loading files: ['/etc/fail2ban/filter.d/nginx-limit-req.conf']
INFO     Loading files: ['/etc/fail2ban/filter.d/nginx-limit-req.conf']
INFO   Loading configs for action.d/cloudflare under /etc/fail2ban
DEBUG  Reading configs for action.d/cloudflare under /etc/fail2ban
DEBUG  Reading config files: /etc/fail2ban/action.d/cloudflare.conf
INFO     Loading files: ['/etc/fail2ban/action.d/cloudflare.conf']
ERROR  Error in action definition cloudflare
DEBUG  Caught exception: While reading from '/etc/fail2ban/action.d/cloudflare.conf' [line 57]: option '-h "x-auth-email' in section 'Definition' already exists
ERROR  Errors in jail 'nginx-limit-req'. Skipping...
```

#### Any customizations done to /etc/fail2ban/ configuration

See Cloudflare action file above

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
You should add at least one space by the multi-line parameters.
So this is wrong:
```
actionunban = 1st line
2nd line
3th line
```

But this is correct:
```
actionunban = 1st line
              2nd line
              3th line
```

**Comment by wpbullet** [comment]
That did work, not sure why the other formatting works on .8 and not on .9.3 but I've updated the guide to reflect this formatting.

Thanks

**Comment by sebres** [comment]
No idea why it should work in 0.8, because it is the way the python ConfigParser as default parses the parameters (possibly some option did that, but I don't know another behavior at all)...

**Comment by wpbullet** [comment]
I just double checked my Debian 7 installation since that is where I copied from to confirm, not sure why either but very happy you were able to point out the issue so quickly. If I find time to make a python version of the cloudflare ban and unban actions I'll be sure to do a PR.
