### ISSUE TITLE
The email sender configured in jail.conf is ignored

### ISSUE THREAD

**Issue by CogumelosMaravilha** [fail2ban/fail2ban#1706]
Hi,

The MTA is sender emails using the sender fail2ban@ when in jail.conf destemail = me@me.com
I think nothing special in the config:
```
destemail = me@me.com
action_mw = %(banaction)s[name=%(__name__)s, port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
              %(mta)s-whois[name=%(__name__)s, dest="%(destemail)s", protocol="%(protocol)s", chain="%(chain)s", sendername="%(sendername)s"]

action = %(action_mw)s
```
Thanks

**Comment by sebres** [comment]
Please review the guidelines for contributing to this repository.
We've not for nothing made an issue template, especially:

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 

Additionally please provide a dump for this jail (where it is supposedly wrong):
```bash
fail2ban-client -d | grep <jail-name>
# e. g. fail2ban-client -d | grep sshd
```

**Comment by CogumelosMaravilha** [comment]
Sorry,
Nothing wrong with Fail2Ban. It was a nullmailer issue.
Can close ticket.
Thanks
