### ISSUE TITLE
cyrus-imap filter not recognizing some "badlogin: " log entries

### ISSUE THREAD

**Issue by fuxjezz** [fail2ban/fail2ban#1707]
- Fail2Ban version (including any possible distribution suffixes):
0.9.5 (fail2ban-fail2ban-0.9.5-d6eae28_GH0)
- OS, including release name/version: 
FreeBSD 10.3 
- [x] Fail2Ban installed via OS/distribution mechanisms
py27-fail2ban-0.9.5 compiled from port, everything set to default
- [X] You have not applied any additional foreign patches to the codebase
None relevant, only the ones from the port (if any, did not check the port)

### The issue:

Hi,

This line is correctly found by the cyrus-imap filter: 
```
Mar  8 05:25:40 $myHostName imap[22130]: badlogin: customer-187-237-56-222.$domain.$tld [$IPV4_address] plain [SASL(-13): authentication failure: Password verification failed]
```
but this one : 
```
Mar  8 05:25:21 $myHostName imap[22130]: badlogin: [$IPV4_address] plain [SASL(-13): authentication failure: Password verification failed]
```
not. Note that i've subtituted some info ($) . I did not find any reference to a change to this filter in the changelog to 0.9.6, seems a simple regex issue.

Regards,

Ruben

**Comment by sebres** [comment]
Fixed in #1708... Thanks!
