### ISSUE TITLE
ERROR  No file(s) found for glob /var/log/apache2/*access.log

### ISSUE THREAD

**Issue by juri775** [fail2ban/fail2ban#1711]
http://pastebin.com/cv4uuARm

**Comment by sebres** [comment]
1. If you don't have apache, just not enable apache jail (enabling of all jails in default section is wrong as well)
2. If your apache access.log belongs another path as configured in your stock fail2ban, see our wiki how you can change it (`logpath`) - https://github.com/fail2ban/fail2ban/wiki/Properly-fail2ban-configuration
