### ISSUE TITLE
phpMyAdmin has syslog output of failed authentication attempts

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#1713]
> Log failed authentication attempts to syslog (useful for parsing by fail2ban, for example)

https://www.phpmyadmin.net/news/2017/3/8/phpmyadmin-470-rc-released/

We may add a filter for it.

**Comment by sebres** [comment]
Are you in the mood for PR? :)

**Comment by szepeviktor** [comment]
I don't even know the log format :)

**Comment by sebres** [comment]
Could be similar as #1695
