### ISSUE TITLE
Starting of fail2ban from init.d fails

### ISSUE THREAD

**Issue by EgonFrerich** [fail2ban/fail2ban#1714]
- Fail2Ban version (including any possible distribution suffixes): Downloaded version 0.10 from 2017-03-09
- OS, including release name/version: Linux Mint 18.1 as VirtualBox VM
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

installed with setup.py
debian-init.d copied
### The issue:

jails not activated

Start of the VM in the log:
```
Mar 12 18:26:03 cupido fail2ban[1444]:  * Starting authentication failure monitor fail2ban
....
Mar 12 18:26:06 cupido fail2ban[1444]: find: "/proc/net/xt_recent": Datei oder Verzeichnis nicht gefunden
...

Mar 12 18:26:52 cupido fail2ban[1444]:  Could not start server. Maybe an old socket file is still present. Try to remove /var/run/fail2ban/fail2ban.sock. If you used fail2ban-client to start the server, adding the -x option will do it
Mar 12 18:26:52 cupido fail2ban[1444]:    ...fail!
```
But /var/run/fail2ban has a socket at 2017-03-12 18:26:53

The fail2ban log shows:
```
2017-03-12 18:26:53,274 fail2ban.server         [1844]: INFO    --------------------------------------------------
2017-03-12 18:26:53,282 fail2ban.server         [1844]: INFO    Starting Fail2ban v0.10.0a2
2017-03-12 18:26:53,284 fail2ban.server         [1844]: INFO    Daemon started
 ```
But no jail is created.

fail2ban-client shows the running server with no jails. Then I stopped and started the server:
```
egon@xfServer181 ~ $ sudo fail2ban-client status
Status
|- Number of jail:	0
`- Jail list:	
egon@xfServer181 ~ $ sudo fail2ban-client -x start
 Server already running
egon@xfServer181 ~ $ sudo fail2ban-client status
Status
|- Number of jail:	0
`- Jail list:	
egon@xfServer181 ~ $ sudo fail2ban-client stop
Shutdown successful
egon@xfServer181 ~ $ sudo fail2ban-client start
Server ready
egon@xfServer181 ~ $ sudo fail2ban-client status
Status
|- Number of jail:	4
`- Jail list:	apache-auth, dovecot, postfix, sshd
egon@xfServer181 ~ $ 
```

**Comment by sebres** [comment]
So starting via `fail2ban-client` seems to work.

Now you can test to start it via service resp. init.d script. If does not work, it would be a init.d issue. 
You may need to get it from your original distribution packet (debian-init.d may not work for the mint-distro).
If you've systemd just install `fail2ban.service` instead of `init.d` script.

**Comment by EgonFrerich** [comment]
With fail2ban.service the issue is gone. But I had to change paths to /usr/**local**/bin.

Thanks
 
Egon

**Comment by sebres** [comment]
> But I had to change paths to /usr/local/bin.

This is distribution depended and normally is subject to responsibility of its maintainer.
Installing direct from github expects to change such things self-employed (we can't do it for each possible *nux distribution of the world).
