### ISSUE TITLE
fail2ban blocked own server ip

### ISSUE THREAD

**Issue by AmFearLiath** [fail2ban/fail2ban#1718]
- Fail2Ban version: 1:0.9.2-debian8.0.16102516
- Debian 8.0.16
- [x ] Fail2Ban installed via OS/distribution mechanisms

### The issue:

Today, after some small attacks, my server blocked the own server ip and caused an 502 Bad Gateway. Someona who can say me how this can happen? For now i've whitelistet my server ip, but i think this isn't thought so

Best regards

**Comment by sebres** [comment]
Of course you can ban itself (e. g. if corresponding the failregex the own IP address will be matched with <HOST> capture and if it even not whitelisted)...
Normally it should block outgoing connections only (but it depends on the chosen banning actions).

which jail?
which failregex? (has the jail any custom filter?)

> i've whitelistet my server ip, but i think this isn't thought so

Well if you use some absurd filter this is currently the one you can do.

BTW. You can whitelist it also via the hostname

**Comment by AmFearLiath** [comment]
it was blocked for apache with standard jail, except limit and ban time

```

[plesk-apache]
enabled = true
filter = apache-auth
action = iptables-multiport[name=apache, port="http,https,7080,7081"]
iptables-allports[chain="INPUT", name="default", port="ssh", protocol="tcp", blocktype="REJECT --reject-with icmp-port-unreachable"]
logpath = /var/www/vhosts/system/*/logs/error_log
/var/log/apache2/*error.log
maxretry = 3
```

**Comment by sebres** [comment]
What you'll see here:
```bash
fail2ban-regex --print-all-matched /path/to/your/apache.log /etc/fail2ban/filter.d/apache-auth.conf | grep your-IP-address
```

**Comment by AmFearLiath** [comment]
nothing

**Comment by sebres** [comment]
Hmm... 
I hope you've replaced:
- `your-IP-address` with your IP address
- `/path/to/your/apache.log` with path to the apache error log (fail2ban-regex cannot wildcards)

Additionally take a look in `/var/log/fail2ban.log` for `Ban your-IP-address`. Then you'll find the time of failure.
Then you should find it in your logs...

Please take a look in our wiki - https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works by corresponding QA.
E. g. you can try following (replace 192.0.2.25 with yours):
```
?sudo? python -c "ip='192.0.2.25'; db='/var/lib/fail2ban/fail2ban.sqlite3';  import sys, logging; logging.basicConfig(stream=sys.stdout, level=logging.ERROR); from fail2ban.server.database import Fail2BanDb; db = Fail2BanDb(db); t = db.getBansMerged(ip=ip); print(('%d attempts, matches:\n  %s' % (t.getAttempt(), '\n  '.join(t.getMatches())) ) if t else 'NOT FOUND')"
```

**Comment by AmFearLiath** [comment]
of course...
fail2ban-regex --print-all-matched /var/log/apache2/error.log  /etc/fail2ban/filter.d/apache-auth.conf | grep xx.xx.xx.xxx

> 2017-03-14 20:44:34,051 fail2ban.filter         [5013]: INFO    [plesk-apache] Found xx.xx.xx.xxx
2017-03-14 20:44:40,900 fail2ban.filter         [5013]: INFO    [plesk-apache] Found xx.xx.xx.xxx
2017-03-14 20:44:41,820 fail2ban.filter         [5013]: INFO    [plesk-apache] Found xx.xx.xx.xxx
2017-03-14 20:44:42,476 fail2ban.actions        [5013]: NOTICE  [plesk-apache] Ban xx.xx.xx.xxx

i've found this already, it was just in time the attacks began

the error occured while i was modifying some downloads...

>   [Tue Mar 14 20:44:34.049981 2017] [access_compat:error] [pid 4055] [client xx.xx.xx.xxx:47542] AH01797: client denied by server configuration: /var/www/vhosts/myurl.com/httpdocs/wp-content/uploads/delightful-downloads/2016/02/jquery_wysiwyg_editor.zip
  [Tue Mar 14 20:44:40.899431 2017] [access_compat:error] [pid 4861] [client xx.xx.xx.xxx:47545] AH01797: client denied by server configuration: /var/www/vhosts/myurl.com/httpdocs/wp-content/uploads/delightful-downloads/2016/02/jquery_wysiwyg_editor.zip
  [Tue Mar 14 20:44:41.819503 2017] [access_compat:error] [pid 4054] [client xx.xx.xx.xxx:47553] AH01797: client denied by server configuration: /var/www/vhosts/myurl.com/httpdocs/wp-content/uploads/delightful-downloads/2016/02/jquery_wysiwyg_editor.zip

ugly

**Comment by sebres** [comment]
So you've really made authentication failure (connection from own server to server with "denied by configuration"? some "proxies" like nginx?)
Error by design :)

BTW anyway iptables-allports may be possibly a bad choice for http-server?

**Comment by AmFearLiath** [comment]
> BTW anyway iptables-allports may be possibly a bad choice for http-server?

maybe xD i'll change this

> some "proxies" like nginx?

no

thank you for your time and help, it was my own fault, so this topic can be closed :)

**Comment by sebres** [comment]
I think about some option like `ignoreself = true` instead of `ignoreip = 127.0.0.1/8 ::1`.
So I leave it open...

If someone really needs to ban itself, he can disable this...
