### ISSUE TITLE
How to edit sendmail-whois-lines.conf for multiple logpaths?

### ISSUE THREAD

**Issue by 7starsone** [fail2ban/fail2ban#1721]
Hello,
at the moment my email doesn't write the "lines containing IP"

because the logpath is something like /var/log/*_access_log

so the email content is truncated as
`Lines containing IP:xxx.xxx.xxx.xx in /var/log/*_access_log`

and nothing more, so eg. for badbots jail I can't see what bot and what pages it requested...

please, how to do it?
thanks

p.s.: I'm on CentOS 7 with Fail2ban 0.9.6

**Comment by sebres** [comment]
Actually fixed for 0.10 in #1622.
I've no interest to touch (resp. to fix) it in v.0.9 (further development of 0.9 stopped).
See in previous issues about multiple logs in actions e. g. #976, #727 for possible "hacks" how-to's for the 0.9 branch.

**Comment by 7starsone** [comment]
thank you, using whois-matches for now...
