### ISSUE TITLE
fail2ban Reinstalled - command not found

### ISSUE THREAD

**Issue by fastesol** [fail2ban/fail2ban#1722]
Hi, I removed the fail2ban module a week ago for some reason, now I decided to install it again but, I see /etc/fail2ban is the older one, and each time I tried to stop, it was saying "Successfully Shutdown" but the service was never started So, I removed the directory in order to get the fresh installation/files. Now, tried to reinstall, everything looks ok, but /etc/fail2ban is not being generated with fresh installation. 

when I tried the following command, I'm getting the error below

[username@host ~]# sudo fail2ban-client start
sudo: fail2ban-client: command not found

I'm using CentOS 7.3

**Comment by sebres** [comment]
I assume that you've installed fail2ban packaged for your distribution (from original centos repo)?
If yes then you should rather try to seek for help by the CentOS maintainers...

Our default install mechanism works with `setup.py`, that will definitely create and overwrite a folder `/etc/fail2ban` and `fail2ban-client`. But on top of your distro-packet you can have some special coating from centos guys (or totally different resp. rewritten installer), that prevents to do this. 
No idea what it could be.

@fail2ban/maintainers Any thoughts?
