### ISSUE TITLE
Add deluge jail

### ISSUE THREAD

**Issue by EWouters** [fail2ban/fail2ban#1730]
Hi, i'm trying to make a `failregex` for this error message:

    [ERROR   ] 14:06:02 auth:329 Login failed (ClientIP 127.0.0.1)

I tried these but they didn't work:

    failregex = .*ERROR.* Login failed (ClientIP <HOST>)
    failregex = .*ERROR.* Login failed \(ClientIP <HOST>\)

Can anyone help me find the correct `failregex`?

**Comment by sebres** [comment]
1. Don't use catch-all's.
2. The date will be cutted out before usage of failregex.
3. I think we don't have default date pattern for time only (in this format). So it should be specified in jail as well as fail2ban-regex by testing.
You can do it also more precise. for example:
```bash
fail2ban-regex -vv -d '^\[ERROR\s*\]\s+%H:%M:%S' '[ERROR   ] 14:06:02 auth:329 Login failed (ClientIP 127.0.0.1)' '^\s+auth:\S+ Login failed \(ClientIP <HOST>\)$'
```
Thus the result (percent char should be escaped as `%%` in configs):
```
datepattern = ^\[ERROR\s*\]\s+%%H:%%M:%%S
failregex = ^\s+auth:\S+ Login failed \(ClientIP <HOST>\)$
```

**Comment by EWouters** [comment]
Thank you @sebres,

I'm still doing something wrong however.

My log looks like this:
```
# tail /var/log/deluge/web/error.log
[ERROR   ] 13:57:31 auth:329 Login failed (ClientIP 127.0.0.1)
```

And the config file:
```

# cat /etc/fail2ban/filter.d/deluge-web.conf
[INCLUDES]

# Read common prefixes. If any customizations available -- read them from
# common.local
before = common.conf

[Definition]

_daemon = deluge-daemon

datepattern = ^\[ERROR\s*\]\s+%%H:%%M:%%S
failregex = ^\s+auth:\S+ Login failed \(ClientIP <HOST>\)$
ignoreregex =

```

But when I check the regex it shows _0 matched_:
```
# fail2ban-regex /var/log/deluge/web/error.log /etc/fail2ban/filter.d/deluge-web.conf

Running tests
=============

Use   failregex file : /etc/fail2ban/filter.d/deluge-web.conf
Use         log file : /var/log/deluge/web/error.log


Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:

Lines: 1 lines, 0 ignored, 0 matched, 1 missed
|- Missed line(s):
|  [ERROR   ] 13:57:31 auth:329 Login failed (ClientIP 127.0.0.1)
`-

```

I have Fail2Ban v0.8.13 installed.

**Comment by sebres** [comment]
> still doing something wrong

Yes, using the old version (0.8 is very old)
- I don't know since which version fail2ban supported `datepattern`
- But I'm sure that at least `fail2ban-regex` does not support `datepattern` in 0.8
- In the older versions (before 0.10) the datepattern belongs to the `[Init]` section

Following filter works in current 0.9 as well as in 0.10:
```
[Definition]
failregex = ^\s+auth:\S+ Login failed \(ClientIP <HOST>\)$
ignoreregex =

[Init]
datepattern = ^\[ERROR\s*\]\s+%%H:%%M:%%S
```
BTW. You don't need the include and daemon because unused...

In your old version you've a small chance to make it running with manually adding a new date-template in addDefaultTemplate (datedetector.py).
Or just upgrade...

**Comment by EWouters** [comment]
This is unfortunately the [version](https://packages.debian.org/stable/net/fail2ban) `apt-get` installs on my system. I upgraded to Fail2Ban v0.10.0a2 and that made it work! Thank you.

**Comment by sebres** [comment]
Glad it works
