### ISSUE TITLE
fail2ban fails with error trying to import common.version w/ fix

### ISSUE THREAD

**Issue by ed45626** [fail2ban/fail2ban#1731]
Reopening -- didn't see the comment (sorry I missed replying).

To clarify, I'm not trying to import fail2ban.  Simply running from the command line.

On one server there's a module already installed named 'common' (not from fail2ban).

If there's a module named 'common' in the search path before fail2ban starts, it tries to load common.version, fails, inserts it's path but python still recognizes the old module.

changed in fail2ban-client and fail2ban-server the import try/except to:

```
try:
    from common.version import version
except ImportError, e:
    sys.path.insert(1, "/usr/share/fail2ban")
    import common
    common = reload(common)
    from common.version import version
```

which officially loads common (can't reload until it's there even though python has cached it's location), reloads it (get's the new path) and then imports version.

**Example of the problem:**
```
user@firewall:/etc/fail2ban/filter.d$ fail2ban-regex /var/log/auth.log /etc/fail2ban/filter.d/sshd.conf
Traceback (most recent call last):
  File "/usr/bin/fail2ban-regex", line 40, in <module>
    from common.version import version
ImportError: No module named version

```

Line 40 of fail2ban-regex can't import version -- it doesn't exist in the default common module (non-fail2ban module).  The try/except block fails because after altering the path the common module is already cached, it won't load the proper one.  Explicitly importing and then reloading forces it to grab the correct version.

**Comment by sebres** [comment]
I assume it's a continuation of #1628... You don't need to create a new issue (we can reopen it and you can write into closed issues also).

Which fail2ban version you are using?
I can neither reproduce it in 0.9 resp. 0.10 nor we've `from common.version import version` somewhere in the source code...

I could find only following lines:
```
from fail2ban.version import version
from ..version import version
from .. import version
```

Thus closed as invalid / obsolete (I guess it would be something 0.8)...
