### ISSUE TITLE
Patch for postfix.conf for AUTH failing and relaying hosts

### ISSUE THREAD

**Issue by time4tea** [fail2ban/fail2ban#1734]
version 0.8.11-1 ubuntu

bans stupid bots who cant handle auth and hosts that try to relay.

this is a diff against my local version - it seems the file format has changed recently, but the regexes should work.

hope its useful, if not, no bother!

```
diff --git a/fail2ban/filter.d/postfix.conf b/fail2ban/filter.d/postfix.conf
index fd8519c..c79f1c9 100644
--- a/fail2ban/filter.d/postfix.conf
+++ b/fail2ban/filter.d/postfix.conf
@@ -14,7 +14,9 @@ _daemon = postfix/smtpd
 
 failregex = ^%(__prefix_line)sNOQUEUE: reject: RCPT from \S+\[<HOST>\]: 554 5\.7\.1 .*$
             ^%(__prefix_line)sNOQUEUE: reject: RCPT from \S+\[<HOST>\]: 450 4\.7\.1 : Helo command rejected: Host not found; from=<> to=<> proto=ESMTP helo= *$
+            ^%(__prefix_line)sNOQUEUE: reject: RCPT from \S+\[<HOST>\]: 454 4\.7\.1 .*$
             ^%(__prefix_line)sNOQUEUE: reject: VRFY from \S+\[<HOST>\]: 550 5\.1\.1 .*$
+            ^%(__prefix_line)slost connection after AUTH from \S+\[<HOST>\].*$
 
 ignoreregex = 
```

**Comment by sebres** [comment]
We've already covered this kind of failures in the newer version of filter (see https://github.com/fail2ban/fail2ban/blob/0.9/config/filter.d/postfix.conf or https://github.com/fail2ban/fail2ban/blob/0.10/config/filter.d/postfix.conf).

BTW `.*$` makes at all no sense (anchoring of the greedy catch-all does not really anchor).

**Comment by time4tea** [comment]
Cool. 

I was following the style that was already there.
