### ISSUE TITLE
Custom date within logpath to fit cronolog for Apache2 (with no symlink)

### ISSUE THREAD

**Issue by vincent-guesnard** [fail2ban/fail2ban#1735]
Hello,

I encounter an issue on specifying custom date within logpath. Here is what i would like : 

[apache]

enabled  = true
port     = http,https
filter   = apache-auth
logpath  = /path/to/apache2/%Y%m%d/error*.log
maxretry = 6

Which return me : ERROR  Failed during configuration: '%' must be followed by '%' or '(', found: '%Y%m%d/error*.log'

I would like to not create a rotate symlinks on this temp directory.

Do you have any idea ?

Thanks you,

Best regards,

Vincent

**Comment by sebres** [comment]
Percent character should be escaped in config files with `%%`.

**Comment by sebres** [comment]
BTW If you hope that `%Y%m%d` will be interpolated to something like `20170327`, it will not work (we've not such kind of interpolation for the `logpath`).

**Comment by vincent-guesnard** [comment]
Thank you very much for this very quick reply, so i will use a rotate symlink.

Is there a way to avoid failed start because no file to analyse ? (in case you actually have 0 error when fail2ban is launched ?)

**Comment by sebres** [comment]
It is planned (#1379). Unfortunately I had over and over again another highest prio tasks...

**Comment by vincent-guesnard** [comment]
I was looking for a quick solution to force cronolog to create empty files. (it works flawlessly with web servers) and it seems that there is no solution.

I'll switch back to logrotate. (in case you got an idea, it would be great)

**Comment by sebres** [comment]
Well, which idea? IMHO:
- if the logrotate deletes (renames) the log-file, then it can/should also be able to (re)create an empty one;
- the sub-directory like `%Y%m%d` should be used for rotated files only. Not for the current log-file.

You can also switch to the systemd-journals (where you'll not have all this problems, that's a reason why #1379 was deferred).
