### ISSUE TITLE
Fail2ban won't ban a custom filter but it finds it in fail2ban-regex

### ISSUE THREAD

**Issue by illectronic** [fail2ban/fail2ban#1737]
### Environment:

- Fail2Ban version (including any possible distribution suffixes):  0.10
- OS, including release name/version:  Amazon Linux AMI 2016.09
- [x] Fail2Ban installed via OS/distribution mechanisms
- [X ] You have not applied any additional foreign patches to the codebase
- [X ] Some customizations were done to the configuration (provide details below is so)

### The issue:

I am trying to ban this in ssh:
sshd[5870]: error: Received disconnect from <IP>: 14: No supported authentication methods available [preauth]

I have added this to filter.d/sshd.conf:
`^<F-NOFAIL>Received <F-MLFFORGET>disconnect</F-MLFFORGET></F-NOFAIL> from <HOST>: 14:`

fail2ban-regex finds these but fail2ban does not ban. fail2ban does ban invalid username however for example

There are no errors in the fail2ban.log at this time in debug mode.

#### Steps to reproduce
Install latest version on AMZN linux with that filter. It will not ban you for logging in to a user that only has an ssh key for method of login.

#### Expected behavior
It should ban.
#### Observed behavior
It is finding regex but it is not banning
#### Any customizations done to /etc/fail2ban/ configuration
I modified action.d/iptables-common.local:

lockingopt =

in order to get it to work with the older iptables version. 

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

The log file looks good.

**Comment by sebres** [comment]
> `sshd[5870]: error: Received disconnect from : 14: No supported authentication methods available [preauth]`

This line alone (without another helper regex) cannot be processed with fail2ban (because no HOST resp. IP addresses in this line).

So please provide an output from your log for:
```
tail ... | grep sshd[5870]
```

Which exact version of fail2ban do you using? (you write your 0.10 was installed via OS/distribution mechanisms).
But the feature that makes possible to use `<F-NOFAIL>` (together with `prefregex`) is relative new.
And the config files (e. g. sshd-filter) are not compatible to previous version.

**Comment by illectronic** [comment]
The version:

fail2ban-client --version
Fail2Ban v0.10.0a2

I removed the IP: Here is the secure log

[root@ip-10-6-0-185 action.d]# tail -n 50 /var/log/secure
Mar 27 16:55:10 ip-10-6-0-185 sshd[5108]: error: Received disconnect from <IP REMOVED>: 14: No supported authentication methods available [preauth]

Thanks

**Comment by sebres** [comment]
Now I understand. So:
- tag `<F-NOFAIL>` means that is not a failure (where you've found it with this regex?)... Thus it's a helper-regex.
- this regex already included in our stock sshd-filter (*without* `<F-NOFAIL>`) but only for the `mode=extra`, see https://github.com/fail2ban/fail2ban/blob/0.10/config/filter.d/sshd.conf#L57;

So either you'll add in your `jail.local` (see https://github.com/fail2ban/fail2ban/blob/0.10/config/jail.conf#L239):
```
[sshd]
# mode = aggressive
mode = extra
```

Or if you need only this single regex additionally to normal mode regex's, add it **without** `<F-NOFAIL>` in your custom new file `filter.d/sshd.local`:
```
[Definition]
failregex = %(known/failregex)s
            ^Received <F-MLFFORGET>disconnect</F-MLFFORGET> from <HOST>%(__on_port_opt)s:\s*14: No supported authentication methods available%(__suff)s$
```
You can do the same in section `[sshd]` of `jail.local`, but you should then resolve parameters like `%(__on_port_opt)s`, that are not available in jail-config file (belongs to sshd-filter only).
