### ISSUE TITLE
python3 setup.py build in branch 0.10

### ISSUE THREAD

**Issue by gracinet** [fail2ban/fail2ban#1738]
### Environment:

Clean checkout of 0.10 branch:

```
~/divers/fail2ban $ git remote -v
origin	https://github.com/fail2ban/fail2ban (fetch)
origin	https://github.com/fail2ban/fail2ban (push)
~/divers/fail2ban $ git checkout origin/0.10
HEAD is now at c8249535... Update mysqld-auth.conf (#1725)
~/divers/fail2ban $ git status            
HEAD detached at origin/0.10
nothing to commit, working tree clean
```

### The issue:

The derivation introduced in `setup.py` in order not to run 2to3 if the `install` subcommand gets launched from tests (according to comments therein) successfully preserves the normal invocation of `2to3` in `python3 setup.py install`, but breaks `python3 setup.py build`. 

#### Steps to reproduce

```
~/divers/fail2ban $ python3 setup.py build
running build
running build_py
running build_scripts
```

#### Expected behavior

`2to3` runs as part of the build under Python 3. This can be seen, e.g, by using `iteritems()` as a marker. After `2to3`, it appears only in one file (in comments actually)::

```
~/divers/fail2ban $ grep -rl --include '*.py' iteritems build        
build/lib/fail2ban/server/ticket.py
```

#### Observed behavior
For quick display here, I'm using `iteritems()` as a marker that `2to3` didn't run

```
~/divers/fail2ban $ grep -rl --include '*.py' iteritems build | wc -l
18
```

#### Any additional information

``python3 setup.py build`` is used in particular during Debian packaging (`gpg buildpackage` in the `debian` branch). 

I'm trying to build Debian packages for fail2ban 0.10 for my own purposes so that it'll be more convenient for me to deploy on a bunch of servers (and will be transparently upgraded to 0.10.0 final if it lands in backports at some point). The major feature I'm looking forward to, compared to the 0.9 series, is IPv6 support.

Since in that context I'm not interested in building with Python 2, I tried bypassing the exception to `2to3` altogether, and it worked::

```
~/divers/fail2ban $ git checkout  0.10-quickfix-setup 
Switched to branch '0.10-quickfix-setup'
~/divers/fail2ban $ git diff origin/0.10 -- setup.py
diff --git a/setup.py b/setup.py
index 5754db49..eba0ecb5 100755
--- a/setup.py
+++ b/setup.py
@@ -168,7 +168,7 @@ setup(
        license = "GPL",
        platforms = "Posix",
        cmdclass = {
-               'build_py': build_py, 'build_scripts': build_scripts, 
+               'build_py': build_py_2to3, 'build_scripts': build_scripts_2to3,
                'install_scripts': install_scripts_f2b, 'install': install_command_f2b
        },
        scripts = [
```

Of course I suppose it's definitely not how you'd want to fix this

```
~/divers/fail2ban $ rm -r build
~/divers/fail2ban $ python3 setup.py build                           
running build
running build_py
creating build
creating build/lib
creating build/lib/fail2ban
copying fail2ban/helpers.py -> build/lib/fail2ban
(...)
(...)
copying fail2ban/tests/config/filter.d/test.conf -> build/lib/fail2ban/tests/config/filter.d
Skipping optional fixer: buffer
Skipping optional fixer: idioms
Skipping optional fixer: set_literal
Skipping optional fixer: ws_comma
running build_scripts
creating build/scripts-3.5
copying and adjusting bin/fail2ban-client -> build/scripts-3.5
copying and adjusting bin/fail2ban-server -> build/scripts-3.5
copying and adjusting bin/fail2ban-regex -> build/scripts-3.5
copying and adjusting bin/fail2ban-testcases -> build/scripts-3.5
changing mode of build/scripts-3.5/fail2ban-client from 644 to 755
changing mode of build/scripts-3.5/fail2ban-server from 644 to 755
changing mode of build/scripts-3.5/fail2ban-regex from 644 to 755
changing mode of build/scripts-3.5/fail2ban-testcases from 644 to 755
Skipping optional fixer: buffer
Skipping optional fixer: idioms
Skipping optional fixer: set_literal
Skipping optional fixer: ws_comma
```

…and I get the expected behaviour

```
~/divers/fail2ban $ grep -rl --include '*.py' iteritems build
build/lib/fail2ban/server/ticket.py
```

Notably, while launching the tests ``gbp buildpackage`` doesn't get obvious Python 3 issues anymore.

I'm not sure it'd be efficient if I proposed some solution, but tell me, I'm willing to help

**Comment by sebres** [comment]
Because fail2ban is executable within all python versions, we've provided `fail2ban-2to3`, so you should run `fail2ban-2to3` (just direct after download or clone) to make the whole sources 3x-capable.

See https://github.com/fail2ban/fail2ban/wiki/How-to-test-newer-fail2ban-version-resp.-use-fail2ban-standalone-instance for more info.

BTW I think that running via 3.x makes not really much sense (as long py-2x still available), because fail2ban is a lot faster under python2.x...

**Comment by gracinet** [comment]
@sebres thank you for the quick answer, (and thank you for all the hard work you seem to be doing for this very useful peace of software), but I think there's a bit of confusion:
that choice of python3 isn't mine, it's the one of the debian packaging provided by the `debian` branch of this very repo. 

Unless I missed something, it's the one that led to the current package of 0.9.6 in Debian 9 (soon-to-be stable) by @yarikoptic (I did recheck that this package indeed uses python3)

**Comment by sebres** [comment]
Well this was my personal opinion, that can deviate from @yarikoptic's opinion about usage of py-3x :)

But you can easy check it's true:
- clone fail2ban into 2 separate directories:
- run `fail2ban-2to3` in one and leave another unchanged
- then execute there the test-cases (using corresponding python-version), `-fng` means fast (fewer sleeping), no-network, no-gamin:
```bash
cd f2b-dir-py-X.X
PYTHONPATH=. pythonX.X bin/fail2ban-testcases -fng
```
Below you'll find my results:
```
Fail2ban 0.10.0a2 test suite. Python 2.7.12+ (default, Sep 17 2016, 12:08:02) [GCC 6.2.0 20160914]. Please wait...
Ran 429 tests in 5.374s
OK (skipped=34)
```
```
Fail2ban 0.10.0a2 test suite. Python 3.5.2+ (default, Sep 22 2016, 12:18:14) [GCC 6.2.0 20160927]. 
Ran 429 tests in 7.096s
OK (skipped=34)
```
```
Fail2ban 0.10.0a2 test suite. Python 3.6.0b2 (default, Oct 11 2016, 05:27:10) [GCC 6.2.0 20161005]. 
Ran 422 tests in 7.509s
OK (skipped=36)
```

And note to `Ran XXX` and `skipped=` - should be the same for the clean comparison, because of the possible missing modules in some version).  e. g. in my result you see that the py-3.6 skipped additionally 9 (7+2) tests (but nevertheless slower).

**Comment by gracinet** [comment]
Thanks for the figures !

As far as I'm concerned, it's just that I figured that building the Debian package for the current 0.10 branch seemed to me the best way to start using it (on a dozen systems) while providing a clean and smooth upgrade path for my coworkers and myself.

The bug report is after all something that will show up at release time, unless fail2ban's packaging rules for Debian gets changed to run the commands you're displaying, but I understand it's a bit ahead of time.

Anyway, I got it working by quickfixing 2 additional glitches in tests for that context (among them one that I can PR right away)
