### ISSUE TITLE
Custom Fail2Ban 0.10.0 Jail, Filter and Action Failure.....

### ISSUE THREAD

**Issue by scampuza** [fail2ban/fail2ban#1744]
Fail2Ban Version -> Fail2Ban v0.10.0a2

OS-> CentOS Linux release 7.3.1611 (Core)

Kernel -> Linux graylog 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

I installed fail2ban cloning the most current repository and then typing "setup.py install"

- [ ] Fail2Ban installed via OS/distribution mechanisms
- [X ] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

I have configured a Jail that triggers a ban action whenever a user hits more than 20 times in a minute our WebServers.  

This is the configuration:

jail.local
```
[http-get-dos]
enabled = true
port = http,https
filter = http-get-dos
logpath = %(apache_access_log)s
maxretry = 20
findtime = 20
bantime = 60
action = brocade-update-acl
```

filter configuration
```
[Definition]
failregex = ^<HOST> -.*"(GET|POST).*
```

action configuration
```
[Definition]

actionstart = /root/ip_blocking/webcat_ban_unban.sh apply 1
actionstop = /root/ip_blocking/webcat_ban_unban.sh apply 1
actioncheck = /root/ip_blocking/webcat_ban_unban.sh find <ip>
actionban = /root/ip_blocking/webcat_ban_unban.sh ban <ip> "HTTP DOS user Ban. IP has reached max requests per minute"
actionunban = /root/ip_blocking/webcat_ban_unban.sh unban <ip> "HTTP DOS user UnBan. Ban time has passed."

[Init]
```
#### ERROR>

When fail2ban triggers the ban action, executing the custom SH /root/ip_blocking/webcat_ban_unban.sh, the following error is triggered...
```
2017-04-06 15:13:27,808 fail2ban.filter         [15262]: INFO    [http-get-dos] Found 190.29.68.61 - 2017-04-06 15:13:25
2017-04-06 15:13:29,944 fail2ban.utils          [15262]: Level 39 1fcd818 -- exec: /root/ip_blocking/webcat_ban_unban.sh find <ip>
2017-04-06 15:13:29,945 fail2ban.utils          [15262]: ERROR   1fcd818 -- stderr: "/bin/sh: -c: line 0: syntax error near unexpected token `newline'"
2017-04-06 15:13:29,945 fail2ban.utils          [15262]: ERROR   1fcd818 -- stderr: "/bin/sh: -c: line 0: `/root/ip_blocking/webcat_ban_unban.sh find <ip>'"
2017-04-06 15:13:29,945 fail2ban.utils          [15262]: ERROR   1fcd818 -- returned 1
```

#### Expected behavior

When I execute the custom built script /root/ip_blocking/webcat_ban_unban.sh, from command line, the IP is banned in the Corporate Load Balancer (Brocade ADX 1000)

#### Observed behavior

When fail2ban executes the script /root/ip_blocking/webcat_ban_unban.sh with the parameters it expects, the fail2ban log register a really weird error .

ERROR   1fcd818 -- stderr: "/bin/sh: -c: line 0: syntax error near unexpected token `newline'"

#### Any additional information

If you like, I can attach the script /root/ip_blocking/webcat_ban_unban.sh

**Comment by sebres** [comment]
`actioncheck` does not designed for supplying of the IP-address (never been so since it was introduced).
`actioncheck` verifies that the jail is still sane (chain still available etc.), but it is not IP related;
In this case fail2ban execute really `/root/ip_blocking/webcat_ban_unban.sh find <ip>`, where `<` as well as `>` both present in the command line.

You should rewrite your action somehow like so:
```
_webcatcmd = /root/ip_blocking/webcat_ban_unban.sh

actionstart = %(_webcatcmd)s apply 1
actionstop = %(_webcatcmd)s apply 1
actioncheck = 
_webcatcheck = %(_webcatcmd)s find <ip>
actionban =   %(_webcatcheck)s
              %(_webcatcmd)s ban <ip> "HTTP DOS user Ban. IP has reached max requests per minute"
actionunban = %(_webcatcheck)s
              %(_webcatcmd)s unban <ip> "HTTP DOS user UnBan. Ban time has passed."
```
Believe me, it will work...

**Comment by scampuza** [comment]
Sebres, 

Thanks a lot for your help, it was my mistake for not reading the docs,,,,!!!

Thanks anyway!
