### ISSUE TITLE
It blocks successful logged in ip's

### ISSUE THREAD

**Issue by mrez-ir** [fail2ban/fail2ban#1747]
This is not really a issue but it's a suggestion to improve security and usability.

The problem is where if you set your fail2ban options for example to block 3 failed logins in last 5 minutes if you had 10 successful logins in last 5 minutes it doesn't care and blocks you although in such situation we know the 3 failed ones should be accidental because there are successful logins from same ip and it should not be counted as a brute-force-attack. 

It can simply subtract number of successful logins from failed ones for decision orelse It would be good idea to include an automated whitelist with options (for example be in whitelist for some minutes) for ip's which have successful logins.

I'm saying this can improve security because we will be able to choose more coercion options for calculation periods of login attempts (because brute-force attackers try to increase time distance from each login attempt to not be blocked automatically for their next ips - or simply they find out or guess fail2ban options - but the important factor to distinguish a brute-force attaker from a normal user is that the attacker never logs in successfully).

So a change to core AI and including successful logins would help to experience a better fail2ban software.

**Comment by sebres** [comment]
close as duplicate of #1263

BTW Think about, that the user having access to service (so can make successful login) should not be able to do brute-force attack using another logins as target. 
So as you describe, it would be possible (just do one successful login after each misleading attempt).

**Comment by mrez-ir** [comment]
And what about including "login name" beside "ip address" in detection algorithm?

**Comment by sebres** [comment]
> And what about including "login name"

Yes, this is correct, but it's not so trivial (and e. g. this is the main reason why #1243 still not yet merged)

**Comment by mrez-ir** [comment]
So if you planned big changes, maybe for next versions, It would be a good advance.
I'm very thankful and satisfied with what you delivered to the world till now. God bless you.
