### ISSUE TITLE
Allow configuration to express times with units instead of only seconds? [improvement] [request]

### ISSUE THREAD

**Issue by cerlestes** [fail2ban/fail2ban#1748]
Hey. I've been using fail2ban for years, and it's a really great software! But something has bugged me since I've started using it: Most other software that has similiar time-related settings in their configuration allow for units to be specified instead of seconds-only. Latter sadly is the case with f2b.

The problem:
```
findtime  = 172800
bantime   = 1209600
```
It's absolutely not clear how many hours/days/weeks that actually is, without using a calculator. After seeing a lot of seconds-values, you'll get to know that 3600 is an hour, 86400 is day, and so on. But I'd love to write it in a way similiar to this:
```
findtime  = 2d
bantime   = 2w
```

I think that should be easy to implement (it's basically only a string-transformation when reading the config file) and would benefit a lot of users.

Here's a list of what units could be translated, with their respective seconds-factor:
```
s	seconds = 1
m	minutes = 60
h	hours = 3600
d	days = 86400
w	weeks = 604800
```

Here's a regular expression for matching both the value and an optional unit, assuming this would be the easiest way to implement it in python:
```
/(\d+)(?:\s?([smhdw]))?/
```

I'm not a python programmer and I have no idea about the f2b source code, so I'm opening this ticket in the hope that somebody capable of implementing this likes the idea just as much as me. Would love to hear feedback. Thanks guys!

**Comment by sebres** [comment]
This was implemented in 0.10 already long time ago.

**Comment by cerlestes** [comment]
Oh, really? I've never found any mention of that in any part of the documentation (just rechecked `MANUAL_0_8` in the official wiki - not once mentioned there). Would be awesome to get that updated then :) Thanks!

**Comment by sebres** [comment]
See [jail.conf](https://github.com/fail2ban/fail2ban/blob/0.10/config/jail.conf#L63)
But only v.0.10 (this syntax will not work neither in 0.8.x nor in 0.9.x).
But indeed, we can add a small documentation section in our man (jail.conf.5) about all time entries.
Thx.

**Comment by NatoBoram** [comment]
@sebres That's the only useful line hinting at the possibility of doing this, but where is the documentation on the subject? Where am I supposed to refer to if I want to know the correct way to type months, or any other time units?

**Comment by sebres** [comment]
> but where is the documentation on the subject

Have you time and mood to write it? Please note, fail2ban is not commercial project, all the changes here cost a lot of time (what is not paid). So ready to spend a bit of your time?

https://github.com/fail2ban/fail2ban/blob/d23d103f967440942ff598e7543153a54be3f738/fail2ban/server/mytime.py#L103-L116

Here you go:

unit | abbreviation *
---- | -----
days | days?, da, dd?
weeks | weeks?, wee?, ww?
months | months?, mon?
years | years?, yea?, yy?
seconds | seconds?, sec?, ss?
minutes | minutes?, min?, mm?
hours | hours?, hou?, hh?

\* `?` mean the char is optional, so by `days?` it accepts `day` as well as `days`.

**Comment by sebres** [comment]
I can remember me now, I made the docu already a year ago - see `man jail.conf.5`.

Exactly here:
https://github.com/fail2ban/fail2ban/blob/00456b8270aed2a0c1c2433f19c676ef52fe938d/man/jail.conf.5#L281-L299

So RTFM. :)

**Comment by NatoBoram** [comment]
Thanks! That's what I needed!
