### ISSUE TITLE
Multiple <HOST> tags on a multiline regex fails to compile - ssh filter

### ISSUE THREAD

**Issue by flixman** [fail2ban/fail2ban#1761]
### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): 0.9.6
- OS, including release name/version: Centos 7.2
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Unexpected visitors to my ssh server try to connect and just disconnect. Therefore, a sequence of log lines similar to this shows up:

   May 01 08:06:06 test-mac sshd[43660]: Connection from 221.194.44.195 port 45700 on 10.0.0.26 port 22
   May 01 08:06:08 test-mac sshd[43660]: Received disconnect from 221.194.44.195: 11:  [preauth]
   May 01 08:07:06 test-mac sshd[43660]: Connection from 221.194.44.195 port 45700 on 10.0.0.26 port 22
   May 01 08:07:08 test-mac sshd[43660]: Received disconnect from 221.194.44.195: 11:  [preauth]
   May 01 08:08:06 test-mac sshd[43660]: Connection from 221.194.44.195 port 45700 on 10.0.0.26 port 22
   May 01 08:08:08 test-mac sshd[43660]: Received disconnect from 221.194.44.195: 11:  [preauth]
   May 01 08:09:06 test-mac sshd[43660]: Connection from 221.194.44.195 port 45700 on 10.0.0.26 port 22
   May 01 08:09:08 test-mac sshd[43660]: Received disconnect from 221.194.44.195: 11:  [preauth]
   May 01 08:10:06 test-mac sshd[43660]: Connection from 221.194.44.195 port 45700 on 10.0.0.26 port 22
   May 01 08:10:08 test-mac sshd[43660]: Received disconnect from 221.194.44.195: 11:  [preauth]
   May 01 08:11:06 test-mac sshd[43660]: Connection from 221.194.44.195 port 45700 on 10.0.0.26 port 22
   May 01 08:11:08 test-mac sshd[43660]: Received disconnect from 221.194.44.195: 11:  [preauth]

I would expect that such pattern is detected, and the host banned, with the following filter:

    ^(?P<__prefix>%(__prefix_line)s)Connection from <HOST> port \d+(?: on \S+ port \d+)?<SKIPLINES>(?P=__prefix)Received disconnect from <HOST>: .*

Which fails to compile because there are two named groups with the same tag ('host'). However, if I try to use the \<number> to reference the 'host'-named group in the second match, it does not work neither:

    ^(?P<__prefix>%(__prefix_line)s)Connection from <HOST> port \d+(?: on \S+ port \d+)?<SKIPLINES>(?P=__prefix)Received disconnect from \\10: .*

#### Steps to reproduce
1. store the previous log lines into a file test.txt
2. copy filter.d/sshd.conf to filter.d/sshd-test.conf
3. add the patterns stated before as additional failregexes to filter.d/sshd-test.conf
4. run fail2ban-regex test.txt filter.d/sshd-test.conf

#### Expected behavior
Lines in test.txt are identified as offending lines against the sshd-test filter.

#### Observed behavior
No lines are identified as offending.

#### Relevant lines from monitored log files in question:

**Comment by sebres** [comment]
- multiple tags with same name in single RE are not allowed per definition (python restriction), but ...
- in your case it will bring nothing, because you want not capture the second IP, but rather compare with the first IP;
- but also this is not needed at all, because you've another unique identifier (`sshd[43660]`) to group the failures, see RE part `(?P=__prefix)`;

So just remove second IP (resp. replace it with `\S+`) for example: 
```diff
- ^(?P<__prefix>%(__prefix_line)s)Connection from <HOST> port \d+(?: on \S+ port \d+)?<SKIPLINES>(?P=__prefix)Received disconnect from <HOST>: .*
+ ^(?P<__prefix>%(__prefix_line)s)Connection from <HOST> port \d+(?: on \S+ port \d+)?<SKIPLINES>(?P=__prefix)Received disconnect from\b
```
> However, if I try to use the <number> to reference the 'host'-named group in the second match ...

If you need nevertheless to compare the IP, you can add it using similar way `(?P=...)`:
```regex
# ... (?P<__host><HOST>) ... (?P=__host) ...
^(?P<__prefix>%(__prefix_line)s)Connection from (?P<__host><HOST>) port \d+(?: on \S+ port \d+)?<SKIPLINES>(?P=__prefix)Received disconnect from (?P=__host):
```

BTW in v.10 of fail2ban we have already more "aggressive" modes to find such failures.
