### ISSUE TITLE
minor exim filter change

### ISSUE THREAD

**Issue by eximmer** [fail2ban/fail2ban#1762]
Added `|Unrouteable address` to the 3rd failregex line in my exim.conf, so it now looks like this:
```
^%(pid)s %(host_info)sF=(?:<>|[^@]+@\S+) rejected RCPT [^@]+@\S+: (?:relay not permitted|Sender verify failed|Unknown user|Unrouteable address)\s*$
```
It now catches exim log messages like:
```
2017-05-01 07:42:42 H=some.rev.dns.if.found (the.connector.reports.this.name) [xxx.xxx.xxx.xxx] F=<some.name@some.domain> rejected RCPT <some.invalid.name@a.domain>: Unrouteable address
```
... and xxx.xxx.xxx.xxx is banned appropriately.

Thanks for a really useful tool.

**Comment by sebres** [comment]
I'm not sure that this should be really recognized as "authentication failure" (which is normally default by fail2ban).
But I can add it in v.10 as "aggressive" mode.
Thx.

**Comment by sebres** [comment]
I'll add it as suggested (like default regex), because we accept already "Unrouteable address" in sender verification regexp (1st expression) as failure.
