### ISSUE TITLE
Wishlist - Progressive banning

### ISSUE THREAD

**Issue by plutocrat** [fail2ban/fail2ban#1763]
Hi,
It would be a nice feature if fail2ban could give out progressively longer ban periods to repeat offenders. 
eg. 1st time, IP is banned for one hour. If it comes back again it gets banned for 6 hours. If it comes back again it gets banned for a week. 

I have implemented this myself with a jail that goes through the fail2ban log and bans IPs which are banned x times in a day. But it would be nice to have this available with config file flags.
ProgressiveBan = yes
BanTime2 = 60000
Ban Time3 = 600000

**Comment by sebres** [comment]
We've it already, see #1460.
I merge it soon to v.10.
