### ISSUE TITLE
minor change to exim.conf filter failregex

### ISSUE THREAD

**Issue by eximmer** [fail2ban/fail2ban#1766]
The filter was not catching many "no MAIL in SMTP connection" log entries.
The problem was that an element of the regular expression `D=\d+s` only selected lines which reported a duration of some seconds.  Many such connections last for minutes and would be reported as something like D=2m42s C=QUIT.
I made a simple change to match anything after D=.  I think that the particulars of this portion of the log message are irrelevant to fail2ban.

Changed the 7th failregex line from:
` ^%(pid)s no MAIL in SMTP connection from (?:\S* )?(?:\(\S*\) )?%(host_info)sD=\d+s(?: C=\S*)?\s*$`
to:
` ^%(pid)s no MAIL in SMTP connection from (?:\S* )?(?:\(\S*\) )?%(host_info)sD=.*$`

This change is working well in my exim deployment.  Thanks for a really useful tool.

**Comment by sebres** [comment]
Thx for reporting.

Just the regex `.*$` makes no sense (anchor does not act).
I guess, better would be to change `D=\d+` to something like `D=\d\S+`.

**Comment by eximmer** [comment]
For my deployment, `D=` is enough of an anchor to differentiate from `%(host_info)s` and the rest of the line is irrelevant.
