### ISSUE TITLE
exim.conf regex not detecting 'DROP in ACL' log message 

### ISSUE THREAD

**Issue by eximmer** [fail2ban/fail2ban#1771]
Log entries like:
`2017-05-08 07:42:42 SMTP connection from (some.domain) [xxx.xxx.xxx.xxx] closed by DROP in ACL`

Are not being caught by this regular expression:
`^%(pid)s \S+ SMTP connection from (?:\S* )?(?:\(\S*\) )?%(host_info)sclosed by DROP in ACL\s*$`
because there's nothing for ` \S+` to match following the time stamp and before ` SMTP`.

Removing `\S+ ` from the regex corrects this problem:
`^%(pid)s SMTP connection from (?:\S* )?(?:\(\S*\) )?%(host_info)sclosed by DROP in ACL\s*$`

 Thanks for such a useful program.

**Comment by sebres** [comment]
Not reproduceable, neither with current 0.10 nor within 0.9...

BTW. Above mentioned expression `^%(pid)s ... ACL\s*$` does not exists [in this form](https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/exim.conf#L23) anymore. See #1751

**Comment by eximmer** [comment]
Thanks, I'm using the Debian version in production which is not as current, the Ubuntu version looks like it's even further behind.

I'll keep my version of this regex: I think it's a waste of CPU cycles to include the regular expression component `(?:[\w\-]+ )?` that always has to be evaluated but always ends up matching the null string.

**Comment by sebres** [comment]
> I think it's a waste of CPU cycles

You're right, but that's the thing with the backwards compatibility resp. supporting of all program versions/platforms. 
We should just do it as default. And you can of course customize the tool the way you want. :)
