### ISSUE TITLE
Enhancement ? default time zones

### ISSUE THREAD

**Issue by gracinet** [fail2ban/fail2ban#1773]
Fail2ban needs to understand properly the time stamps from matching log lines, and in particular, the timezones must be correctly interpreted, but there are some cases in which the log lines do not specify in which timezones they are to be understood. 

As far as I understand it, in that case, fail2ban interprets the time zone as its own default one, and there is no way to specify otherwise (at least, I couldn't find one), yet it can actually differ.

While I agree it's better for the applications to be very explicit about time zones in logs, even in the most frequent case of logging in UTC, it can be outside the scope of fail2ban users to fix that, or simply a long process, during which they still would like the protection fail2ban offers.

So, am I right that there's no way to specify a default timezone ?
In that case, I believe that a default timezone option alongside ``datepattern`` would be useful, and I can see myself working on a PR towards that. 

Thanks,

Note: in my immediate use-case, the logs are emitted in a LXC guest container, and watched from the host. Actually the container's time zone is identical to the host's but the application logs are in UTC with no indication of that (this is hardcoded) and changing that won't be immediate.

**Comment by gracinet** [comment]
Forgot to tell I'm on the 0.10 branch

**Comment by gracinet** [comment]
FYI, I started working on this, with the new option been called `defaulttimezone`.

However, I noticed that fail2ban has no dependencies outside of the Python standard library, and I suspect this is no accident, but the standard library is rather weak with respect to time zones.

The feature would already be useful in the case of fixed offset time zones in watched logs, since I believe UTC itself would be the most common use-case. 

So I intend to support that first and postpone the case of named time zones (such as e.g, Europe/Paris) and DST in watched logs.

**Comment by sebres** [comment]
> I started working on this ... So I intend to support that first 

Please note, that numerical zones are already implemented by fail2ban (using pattern `%z`).

> since I believe UTC itself would be the most common use-case.

Please note additionally, that we already support UTC/GMT also (as well as Z as special case) in our v.10 version (using patterns `%z` resp. `%Z`),
If interested, see major fix #1583 ... from the changelog:
* Fixed UTC/GMT named time zone, using `%Z` and `%z` patterns

```bash
testfn=/tmp/test-f2b-zones
echo '2017-05-18 01:02:03 +0500 failure 192.2.0.1' >  $testfn
echo '2017-05-18 01:02:03 GMT   failure 192.2.0.2' >> $testfn
fail2ban-regex -v $testfn '^\s*failure <HOST>$'
```
```
Running tests
=============

Use   failregex line : ^\s*failure <HOST>$
Use         log file : /tmp/test-f2b-zones
Use         encoding : UTF-8


Results
=======

Failregex: 2 total
|-  #) [# of hits] regular expression
|   1) [2] ^\s*failure <HOST>$
|      192.2.0.1  Wed May 17 22:02:03 2017
|      192.2.0.2  Thu May 18 03:02:03 2017
`-

Date template hits:
|- [# of hits] date format
|  [2] {^LN-BEG}ExYear(?P<_sep>[-/.])Month(?P=_sep)Day[T ]24hour:Minute:Second(?:[.,]Microseconds)?(?:\s*Zone offset)?
| ...
`-

Lines: 2 lines, 0 ignored, 2 matched, 0 missed
```

**Comment by sebres** [comment]
> the new option been called `defaulttimezone`

I guess `logtimezone` would be more matching for the name of option (corresponds to another log-options like `logpath`, etc.).

So it can be resolved in each jail. And for the default value just pass it to default section:
```
[DEFAULT]
logtimezone = UTC
...
[jail]
logtimezone = +0500
```

**Comment by gracinet** [comment]
> Please note, that numerical zones are already implemented by fail2ban (using pattern %z).

Yes I know that, do you imply that the simplest and preferred implementation for numerical time zones and GMT would be to append something like `UTC+0200` to matching patterns that don't specify the time zone ?

**Comment by sebres** [comment]
No, I think to append something (and hereafter to parse it again into zone) would be not so good.

I see the algorithm like:
- adding `logtimezone` into JailReader;
- in the filter (backend) append current offset `tzoffset` of the `logtimezone` value to parsed-date, somewhere in `findFailure`:
```python
...
self.dateDetector.getTime(..., self.logtimezone)
```
- in the date-detector or round about:
```python
if self.logtimezone is not None:
  tzoffset = None _convert_zone2offs(self.logtimezone)
  time += tzoffset
```
- or you can just add it into `found_dict` for `reGroupDictStrptime`.

**Comment by gracinet** [comment]
Thank you for all these indications, I'll look into it later this evening or tomorrow afternoon (for now I'm only introducing and validating the new config option).

**Comment by gracinet** [comment]
>  I guess logtimezone would be more matching for the name of option (corresponds to another log-options like logpath, etc.).
> 
> So it can be resolved in each jail. And for the default value just pass it to default section (...)
> 

as you wish. For the record, with "default", I intended to stress that this doesn't supersede an explicit timezone in log lines. This is slightly different than using the default section of ConfigParser files.

**Comment by gracinet** [comment]
work is in progress, not ready for review yet. I'll continue on monday, won't be very active this we

**Comment by gracinet** [comment]
@sebres a reminder, just in case you didn't notice PR #1792 on this topic, nothing more implied.

**Comment by sebres** [comment]
Thanks, I've seen it before. 
Looks not bad, I had no time to make detailed review, and there is a small performance regression (even by unused option logtimezone), that I must resolve before it continues...
I'll try to take a look soon.

**Comment by gracinet** [comment]
@sebres thank you for the feedback. Don't hesitate to indicate what's the perf regression is and how to measure it, I could try and come up with an improvement.
