### ISSUE TITLE
Ban immediately after 2nd retry...is this possible?

### ISSUE THREAD

**Issue by 7starsone** [fail2ban/fail2ban#1781]
Hello,

please consider
```
[jail]
enabled = true
port    = port(s)
logpath = %(my_log)s
bantime  = 86400
findtime  = 300
maxretry = 2
action = ...
```
if it retries for the 2nd time **after** 5 mins

is `findtime  = 86400` during one day banning it after a 2nd retry regardless of the exact moment?

OR...how to do it?
I need to ban that IP just a bit after the 2nd retry, In this specific case I can't wait much longer for a 3rd retry...

Thank you

**Comment by 7starsone** [comment]
ok, nevermind...found it here
https://serverfault.com/posts/810839/revisions

thanks

**Comment by sebres** [comment]
The parameter `findtime` means a time-window where failures are counted. Fail2ban "remembers" failures that occurred only within this interval and forgets failures outside of this window (that are occurred earlier as `now - findtime`).
If during this interval the offender (ticket with same failure-ID, mostly IP) makes exactly `maxretry` failures, the ticket goes banned for a time specified in `bantime`. 
After unbanning of the ticket all falures of it are "forgotten" and this "cycle" repeats after first new failure again.

For more information see our [wiki :: how fail2ban works](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works).
