### ISSUE TITLE
Does not add chains to iptables

### ISSUE THREAD

**Issue by EXANIX** [fail2ban/fail2ban#1785]
Hello.
When I started fail2ban , then fail2ban does not add chains to iptables. But log files fail2ban.log have not any error.
But I have any errors after "fail2ban-testcases  --verbosity=4 --full-traceback"
My OS is CentOS Linux release 7.1.1503 (Core).
Linux hostname  3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
iptables v1.4.21
Python 2.7.5

I have only one monitor
/etc/fail2ban/jail.local
[asterisk]
enabled = true
port     = 5060,5061
action   = %(banaction)s[name=%(__name__)s-tcp, port="%(port)s", protocol="tcp", chain="%(chain)s", actname=%(banaction)s-tcp]
           %(banaction)s[name=%(__name__)s-udp, port="%(port)s", protocol="udp", chain="%(chain)s", actname=%(banaction)s-udp]
           %(mta)s-whois[name=%(__name__)s, dest="%(destemail)s"]
logpath  = /var/log/asterisk/security_log
maxretry = 4
bantime = 10000m
findtime = 10m

I see in log file what fail2ban did not try execute command for add new chain in iptables.

fail2ban-testcases  --verbosity=4 --full-traceback
log - https://pastebin.com/pK9QBXvQ
fail2ban-client start
fail2ban.log - https://pastebin.com/vKuAvaNv
fail2ban-client -d 
log - https://pastebin.com/kQb3TcpN

I have this trouble with about 10 servers, but I don't have the trouble other 10 servers with CentOS 7. And I don't know what I should make.

**Comment by sebres** [comment]
May be a time-related issue: something uses iptables-restore or similar to rewrite all rules **after** fail2ban was started. In this case you should add a dependency between both services.
Or interim save all the chains starting with `f2b-` and apply it after iptables-restore.

BTW Usage of pastebin is questionable (some peoples behind corporate firewall cannot open it :). Github allows you to attach files directly here.

**Comment by EXANIX** [comment]
Thank you for your answer! 
Good working 0.9.7 version at 11 may 2017.

**Comment by sebres** [comment]
Thus I'll close issue, as long as no news...
