### ISSUE TITLE
Ban IPs as soon as they fail when many already failed login with the same user in short time

### ISSUE THREAD

**Issue by darknight7** [fail2ban/fail2ban#1791]
fail2ban 0.9.6 on Gentoo linux

I'm experiencing attacks with a very clear pattern: username stays fixed and a pool of non-related IPs attempt login, sometimes the same pool will switch username and so on:
```
       authentication failure; logname= uid=0 euid=0 tty=dovecot ruser=user@my.domain rhost=ip1 : 1 Time(s)
       authentication failure; logname= uid=0 euid=0 tty=dovecot ruser=user@my.domain rhost=ip2 : 1 Time(s)
       authentication failure; logname= uid=0 euid=0 tty=dovecot ruser=user@my.domain rhost=ip3 : 1 Time(s)
       authentication failure; logname= uid=0 euid=0 tty=dovecot ruser=user@my.domain rhost=ip4 : 1 Time(s)
       authentication failure; logname= uid=0 euid=0 tty=dovecot ruser=user@my.domain rhost=ip5 : 1 Time(s)
       authentication failure; logname= uid=0 euid=0 tty=dovecot ruser=user@my.domain rhost=ip6 : 1 Time(s)
       authentication failure; logname= uid=0 euid=0 tty=dovecot ruser=user@my.domain rhost=ip7 : 1 Time(s)
       authentication failure; logname= uid=0 euid=0 tty=dovecot ruser=user@my.domain rhost=ip8 : 1 Time(s)
       authentication failure; logname= uid=0 euid=0 tty=dovecot ruser=user@my.domain rhost=ip9 : 1 Time(s)
```

I understand that a rule banning new IPs on the basis of recent failures may result in a DOS, however I'm inclined to try and see what happens on my system. I'm not confident enough with the inner workings of fail2ban to attempt a self made solution, I'm not even sure it can be done with the current architecture.

Your insight is much appreciated.

**Comment by sebres** [comment]
> Ban IPs as soon as they fail when many already failed login with the same user in short time

I think you've no chance by distributed brute-force attack if you'll involve a user-name - such botnets will change the logic very fast, and you'll get different user-names.

The only way I see is to use my ban-time-incr version (#1460) and to specify initial short bantime/maxretry values. The `bantime` will grows for such "bad" IPs with each attempt (ban).
And the short initial bantime avoids banning for long time by some typos of "good" users.
```
bantime = 1m
bantime.increment = true
bantime.factor = 2
bantime.maxtime = 10w

maxretry = 3
findtime = 1d
```
