### ISSUE TITLE
gentoo init script should use --retry XX to stop daemon

### ISSUE THREAD

**Issue by novazur** [fail2ban/fail2ban#1793]
net-analyzer/fail2ban-0.9.6 init script should use --retry XX in start-stop-daemon --stop

As reported https://bugs.gentoo.org/show_bug.cgi?id=618138

When I try to stop, or restart fail2ban (or when I restart shorewall), fail2ban init script tells that fail2ban couldn't be stopped, even if it is really stopped, but seems too late :

# service fail2ban stop
 * Caching service dependencies ...                                                          [ ok ]
 * Stopping fail2ban ...
 * start-stop-daemon: 1 process refused to stop
 * Failed to stop fail2ban                                                                   [ !! ]
 * ERROR: fail2ban failed to stop

I have no error in /var/log/fail2ban.log, juste fail2ban which takes too much time to stop. Just 1 or 2 seconds more than waited by start-stop-daemon.

And I haven't any more problem if I add --retry 20 in /etc/init.d/fail2ban :
stop() {
 ebegin "Stopping fail2ban"
 start-stop-daemon --stop --retry 20 --pidfile /run/fail2ban/fail2ban.pid \
 -- ${FAIL2BAN} stop
 eend $? "Failed to stop fail2ban"
}

**Comment by sebres** [comment]
@fail2ban/maintainers Any suggestions/objections?

**Comment by yarikoptic** [comment]
I guess it shouldn't hurt.. too much 😀

**Comment by bes-internal** [comment]
deban (ipset at least) at shutdown is really slow

**Comment by sebres** [comment]
> deban (ipset at least) at shutdown is really slow

In our newest version (0.10) we've bulk unbanning at shutdown (flush, see #1743), so it is very fast now also using ipset.

**Comment by bes-internal** [comment]
sounds awesome :)
In gentoo fail2ban release at 0.9.7, but i will try to work on new gentoo ebuilt by the time of release 0.10

**Comment by sebres** [comment]
fixed within #1648
