### ISSUE TITLE
Block SSH Bruteforce before they even reach Fail2Ban

### ISSUE THREAD

**Issue by mitchellkrogza** [fail2ban/fail2ban#1795]
This is not an issue, merely a tip.

I recently reviewed my default iptables rules after many years of running with what I had created some years ago. 

A new simple set of rules added to the rules.v4 and rules.v6 that get loaded by iptables after reboot completely deal with all SSH attacks before they even reach Fail2Ban. I've been using these new rules for several weeks now and no longer get any notifications from Fail2Ban on any SSH / SSHD bans. Might be useful for some wanting to block SSH attacks at firewall level before they even reach Fail2Ban.

To add into rules.v4

```
-N SSHBRUTE
-A SSHBRUTE -m recent --name SSH --set
-A SSHBRUTE -m recent --name SSH --update --seconds 300 --hitcount 10 -m limit --limit 1/second --limit-burst 100 -j LOG --log-prefix "iptables[SSH-brute]: "
-A SSHBRUTE -m recent --name SSH --update --seconds 300 --hitcount 10 -j DROP
-A SSHBRUTE -j ACCEPT
```

To add into rules.v6

```
-N SSHBRUTE
-A SSHBRUTE -m recent --name SSH --set
-A SSHBRUTE -m recent --name SSH --update --seconds 300 --hitcount 10 -m limit --limit 1/second --limit-burst 100 -j LOG --log-prefix "ip6tables[SSH-brute]: "
-A SSHBRUTE -m recent --name SSH --update --seconds 300 --hitcount 10 -j DROP
-A SSHBRUTE -j ACCEPT 
```

**Comment by sebres** [comment]
I'm not sure that this should be really a part of fail2ban... Then this belongs IMHO rather to the configuration of something like firewall.

What indeed could be done, would be to create a rule-set (filter) for logging of such failures within iptables and then observe it with fail2ban (to ban such attackers more aggressive, especially if ban-time-incr merged and they will be recognized as "bad").

**Comment by mitchellkrogza** [comment]
I agree @sebres just thought it might help some people who want stricter control over SSH. I still use Fail2ban for many many things, but found this little set of rules to be super effective for me 👍
