### ISSUE TITLE
Cannot manually ban IPs with fail2ban-client but unbanning and status work OK

### ISSUE THREAD

**Issue by LexMajor** [fail2ban/fail2ban#1802]
### Environment:

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 
- [X] Fail2Ban installed via OS/distribution mechanisms (Debian 8.8 stable, fail2ban version 0.8.13-1 ). 
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:
- I cannot manually ban IPs with fail2ban-client. Running the client with the command to ban _looks_ like it works (error code 0), but doesn't add it to the relevant chain.
- Manually UNbanning IPs with the client works well. 
- Automatic banning (from logs) happens normally. 
- It does not work for any jails.

cat abanner_dovecot.txt  | xargs -l fail2ban-client -v set dovecot banip
#### Steps to reproduce

Here's the transcript to reproduce. 
root@mybox:/home/me# fail2ban-client -vvvv set "dovecot" banip "61.153.49.210"
DEBUG  Reading configs for /etc/fail2ban/fail2ban under /etc/fail2ban
DEBUG  Reading config files: /etc/fail2ban/fail2ban.conf
DEBUG  Reading files: ['/etc/fail2ban/fail2ban.conf']
INFO   Using socket file /var/run/fail2ban/fail2ban.sock
DEBUG  OK : '61.153.49.210'
DEBUG  Beautify '61.153.49.210' with ['set', 'dovecot', 'banip', '61.153.49.210']
61.153.49.210

#### Expected behavior
That the banned IP gets added to the iptables chain. 

#### Observed behavior
The banned IP does not get added to the iptables chain (see status before/after below)

root@mybox:/home/me# fail2ban-client status dovecot
Status for the jail: dovecot
|- filter
|  |- File list:        /var/log/mail.log
|  |- Currently failed: 0
|  `- Total failed:     4
`- action
   |- Currently banned: 3
   |  `- IP list:       60.6.229.50 176.104.99.97 89.218.84.214
   `- Total banned:     4
root@mybox:/home/me# fail2ban-client -vvvv set "dovecot" banip "61.153.49.210"
DEBUG  Reading configs for /etc/fail2ban/fail2ban under /etc/fail2ban
DEBUG  Reading config files: /etc/fail2ban/fail2ban.conf
DEBUG  Reading files: ['/etc/fail2ban/fail2ban.conf']
INFO   Using socket file /var/run/fail2ban/fail2ban.sock
DEBUG  OK : '61.153.49.210'
DEBUG  Beautify '61.153.49.210' with ['set', 'dovecot', 'banip', '61.153.49.210']
61.153.49.210
root@mybox:/home/me# fail2ban-client status dovecot
Status for the jail: dovecot
|- filter
|  |- File list:        /var/log/mail.log
|  |- Currently failed: 0
|  `- Total failed:     4
`- action
   |- Currently banned: 3
   |  `- IP list:       60.6.229.50 176.104.99.97 89.218.84.214 [IT SHOULD BE HERE, DAMMIT!]
   `- Total banned:     4

### Configuration, dump and another helpful excerpts
I've created a custom postfix jail that parses mail.log for unresolveable adresses. It works fine, there are no errors when starting/restarting fail2ban. 

#### Any customizations done to /etc/fail2ban/ configuration
Not really (see above). 

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_
There are NO entries in the log when I try to banip (unsettling). Tried loglevel 4, to no avail.

#### Relevant lines from monitored log files in question:
2017-06-12 21:47:57,735 fail2ban.actions[13526]: WARNING [postfix-alex] Ban 199.116.113.232

That's the previous line (a normal, working ban).
```

**Comment by sebres** [comment]
Not reproducible on 0.9 / 0.10.
Sorry but no interest to fix for 0.8.x (very obsolete).

**Comment by LexMajor** [comment]
Understook, thanks. Once that's said, I don't suppose you have any idea at which door I could knock to have the packages put closer to current versions?

**Comment by sebres** [comment]
No idea. Is a good question to @fail2ban/maintainers!
BTW @yarikoptic maintains another debian-repo [(neurodebian)](http://neuro.debian.net/pkgs/fail2ban.html)...

**Comment by sebres** [comment]
If you want to try it unpackaged, just download resp. git checkout latest version and install via `python setup.py install` as suggested in [README](https://github.com/fail2ban/fail2ban/blob/0.10/README.md).
Or/and take a look on our [wiki](https://github.com/fail2ban/fail2ban/wiki/How-to-test-newer-fail2ban-version-resp.-use-fail2ban-standalone-instance).
