### ISSUE TITLE
Logging in server/filter.py line 521 cannot be output

### ISSUE THREAD

**Issue by daviessm** [fail2ban/fail2ban#1810]
`logSys.log(7, "Working on line %r", line)`

I was troubleshooting a mktime exception thrown and couldn't get this log line to output anything to give a hint as to what the problem was. Changing it to `logSys.debug("Working on line %r", line)` showed the output.

Is level 7 supposed to be TRACE level which isn't configurable in the conf file?

Line 521 in current 0.10 branch.

**Comment by sebres** [comment]
We have custom log-level for such purposes - HEAVYDEBUG (for all messages with level >= 5).
In v.0.10 you can also use numeric log-level...
