### ISSUE TITLE
Unable to pass `tablename` to `pf` action

### ISSUE THREAD

**Issue by moisseev** [fail2ban/fail2ban#1815]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): py27-fail2ban-0.9.7
- OS, including release name/version: FreeBSD 11.0-RELEASE-p2 amd64
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

Unable to pass `tablename` to `pf` action due to incorrect configuration parsing

#### Steps to reproduce

1. Set `banaction_allports = pf[tablename=recidive]`
2. Check `fail2ban-client -d` output

#### Expected behavior

```
# fail2ban-client -d | grep '^\[.set., .recidive., .action., .pf., .tablename.'
['set', 'recidive', 'action', 'pf', 'tablename', 'recidive']
```

#### Observed behavior

```
# fail2ban-client -d | grep '^\[.set., .recidive., .action., .pf., .tablename.'
['set', 'recidive', 'action', 'pf', 'tablename', 'recidive][name=recidive']
```

#### Any customizations done to /etc/fail2ban/ configuration

/usr/local/etc/fail2ban/jail.local:
```
[DEFAULT]
banaction_allports = pf[tablename=recidive]

[recidive]
enabled = true
```

**Comment by sebres** [comment]
Such syntax is only extension of v.0.10 and will be accepted only there.
In fail2ban v.0.9 you cannot join arguments with multiple `[...]`...
```INI
[DEFAULT]
banaction_allports = pf[tablename=recidive]
action_ = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
action = %(action_)s
[jail]
banaction = %(banaction_allports)
```
results to 
```INI
action = pf[tablename=recidive][name=%(__name__)s, ...]
```

In v.0.9, you should extend it in `action_` substitution or just directly set `action = pf[param1=..., param2=]`.
