### ISSUE TITLE
adding a wildcard IPs to fail2ban

### ISSUE THREAD

**Issue by ofog-bartar** [fail2ban/fail2ban#1818]
hello
Package: fail2ban (0.8.13-1) 
I want to add IPs starting with specific digits to accept or ban lists. (for example in ignoreip = )
I want to say all the IPs started with aa should be allowed or ban in fail2ban local.jail file.
aa.xx.xx.xx
how?

**Comment by sebres** [comment]
> how?

No way for wildcard.

You can use subnet resp. CIDR mask for `ignoreip`:
```
ignoreip = 127.0.0.0/8 172.16.0.0/12 192.168.0.0/16
```
BTW. Please note we are not a common forum for the questions like "how-to". So better seek for help there...

**Comment by ofog-bartar** [comment]
@sebres: could you give me the link for the place you're referring to.
