### ISSUE TITLE
Difference between fail2ban-client and fail2ban

### ISSUE THREAD

**Issue by JamesJGoodwin** [fail2ban/fail2ban#1829]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.9.3
- OS, including release name/version: Ubuntu 16.04.2 LTS
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Hello. I've just installed fail2ban with [this guide](http://linux-sys-adm.com/ubuntu-16.04-lts-how-to-configure-firewall-iptables-fail2ban/). After configuring `[sshd]` section in `/etc/fail2ban/jail.conf` i tried to restart fail2ban by typing `service fail2ban restart` and the console says:
```
Job for fail2ban.service failed because the control process exited with error code. See "systemctl status fail2ban.service" and "journalctl -xe" for details.
```
After that, i'll try to run fail2ban via fail2ban-client restart and it started. But when i typed `systemctl status fail2ban`, it says that fail2ban is failed to start. Am i doing something wrong?

### Configuration, dump and another helpful excerpts
Just changed [sshd] section:
```
#
# SSH servers
#
[sshd]
enabled = true
port = ssh
filter = sshd
action = iptables-allports[name=ssh]
logpath = /var/log/auth.log
maxretry = 3
bantime = 13
```

#### Relevant parts of /var/log/fail2ban.log file:

```
2017-07-11 14:59:55,853 fail2ban.transmitter    [1185]: WARNING Command ['restart'] has failed. Received Exception('Invalid command',)
```

**Comment by sebres** [comment]
I assume that `fail2ban-client status` says no errors... So it looks like wrong fail2ban.service file resp. init.d-script.

>  See "systemctl status fail2ban.service" and "journalctl -xe" for details.

What says the output of both?

Did you noticed our wiki page [Troubleshooting](https://github.com/fail2ban/fail2ban/wiki/Troubleshooting)?

BTW:
- changing of `jail.conf` is not desirable at all, please do your customization in `jail.local`. See [Proper fail2ban configuration](https://github.com/fail2ban/fail2ban/wiki/Properly-fail2ban-configuration) for more info.
- If you installed fail2ban over distribution mechanisms, you should rather seek support by the Ubuntu maintainers...

**Comment by JamesJGoodwin** [comment]
> Did you noticed our wiki page Troubleshooting?

Oh, i'm so sorry, i didn't mention that there's the page like this. After doing the last **Q&A** instructions at [Troubleshooting](https://github.com/fail2ban/fail2ban/wiki/Troubleshooting) i get fail2ban service working just fine: 
```
Jul 11 16:00:26 flaut systemd[1]: Starting Fail2Ban Service...
Jul 11 16:00:27 flaut fail2ban-client[1713]: 2017-07-11 16:00:27,086 fail2ban.server         [1714]: INFO    Starting Fail2ban v0.9.3
Jul 11 16:00:27 flaut fail2ban-client[1713]: 2017-07-11 16:00:27,086 fail2ban.server         [1714]: INFO    Starting in daemon mode
Jul 11 16:00:27 flaut systemd[1]: Started Fail2Ban Service.
```

Thank you!
