### ISSUE TITLE
datepattern problem

### ISSUE THREAD

**Issue by kensuendgs** [fail2ban/fail2ban#1831]
- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 
OS: Red Hat Enterprise Linux Server release 6.9
Fail2Ban v0.10.0a2
- [X] Fail2Ban installed via git clone and setup.py install 
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

_Summary here_f
After i start the fail2ban
First it has problem on the log show below

----------------------------------------------------------------------------------------
```
2017-07-12 04:12:11,451 fail2ban.filter         [25756]: WARNING Found a match for u'2a02:908:e67d:4260:d857:3933:15e5:2bbb - - [12/Jul/2017:04:12:10 +0000] 1045610 "GET /foto-and-camcorder/objektive/fujifilm-de-2/page-2/ HTTP/1.1" 200 33549 "https://www.test.com/foto-and-camcorder/objektive/fujifilm-de-2/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0"' but no valid date/time found for u'2a02:908:e67d:4260:d857:3933:15e5:2bbb - - [12/Jul/2017:04:12:10 +0000] 1045610 "GET /foto-and-camcorder/objektive/fujifilm-de-2/page-2/ HTTP/1.1" 200 33549 "https://www.test.com/foto-and-camcorder/objektive/fujifilm-de-2/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0"'. Please try setting a custom date pattern (see man page jail.conf(5)). If format is complex, please file a detailed issue on https://github.com/fail2ban/fail2ban/issues in order to get support for this format.
```
----------------------------------------------------------------------------------------

Then i added  `datepattern = %d/%b/%Y:%H:%M:%S` in my custom jail file and try to start fail2ban, it become below error.

----------------------------------------------------------------------------------------

Loading files: ['/etc/fail2ban/filter.d/common.conf', '/etc/fail2ban/filter.d/apache-cloudflare.conf']
 Failed during configuration: '%' must be followed by '%' or '(', found: '%d/%b/%Y:%H:%M:%S'
 Async configuration of server failed

----------------------------------------------------------------------------------------

# customizations done to /etc/fail2ban/ configuration

custom filter conf file (apache-cloudflare.conf)

--------------------------------------
[INCLUDES]

before = common.conf
[Definition]

failregex =  ^<HOST> -.*GET.*\.html*
             ^<HOST> -.*GET.*/search/*
             ^<HOST> -.*GET.*/page/*

ignoreregex = 

-----------------------------------------------------------------------------------

custom action conf (cloudflare-blacklist.conf) , MYKEY was my own cloudflare API key

-----------------------------------------------------------------------------------
[Definition]

actionstart =

actionstop =

actioncheck =

actionban = curl -s "https://www.cloudflare.com/api.html?a=ban&key=<ip>&u=MYKEY"

actionunban = curl -s "https://www.cloudflare.com/api.html?a=nul&key=<ip>&u=MYKEY"

-----------------------------------------------------------------------------------

custom jail conf file (apache-cloudflare-test.conf)
-----------------------------------------------------------------------------------

[apache-cloudflare-test]

enabled  = true
filter   = apache-cloudflare
action   = iptables-allports[name=cloudflare-test, protocol=tcp]
           cloudflare-blacklist
logpath = /var/log/httpd/test.com-access.log
findtime = 30
maxretry = 25
bantime  = 604800

-----------------------------------------------------------------------------------

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_
It was default, i haven't made any change
loglevel = INFO

**Comment by kensuendgs** [comment]
I have fixed the problem with doubling the % with datepattern = %%d/%%b/%%Y:%%H:%%M:%%S and place it in filter conf instead of jail conf

If anyone has better suggest, please do share it.

**Comment by sebres** [comment]
> I have fixed the problem with doubling the `%`

That is exactly right way - python ini-files use `%` character for variable interpolation and it should be escaped as `%%` to be a simple character.

**Comment by sebres** [comment]
Since version v.0.10 you can use `datepattern` directly in jail also.
