### ISSUE TITLE
The test cases should use RFC 1918 non-routed netblocks

### ISSUE THREAD

**Issue by herrold** [fail2ban/fail2ban#1832]
rather than 'live' ones

The test case uses:  193.168.x.x ... this is a potentially routable block

RFC 1918 enumerates that 192.168.x.x is a better choice

I will provide a PR in a moment based on a diff against a current pull

**Comment by sebres** [comment]
Thanks for review and PR, but...
All mentioned test cases does nothing with the IP (that is just a string there).
Unfortunately too many open branches resp. PR's currently, that all will get affected if #1833 will be merged (conflicts, etc). 
Thus I'll close this issue, but leave the PR still open for the future time...

Note also, that RFC says that 192.0.2.x would be possibly much better... And we using it already everywhere.
> 192.0.2.0/24 - This block is assigned as "TEST-NET-1" for use in documentation and example code.
