### ISSUE TITLE
3-4 MB/s write of fail2ban on Ubuntu 16.04

### ISSUE THREAD

**Issue by SvenAbels** [fail2ban/fail2ban#1835]
### Environment:
Ubuntu 16.04 LTS
Fail2Ban v0.9.3
running within a KVM QEMU VM

### The issue:
While fail2ban is started, iotop tells me that its threads use 3-4MB of disk write by 3 threads.

Please note that those are disk writes. Fail2Ban is running on our mail server but the logs are not big enough to cause 3-4MB by far - especially because this seems to be write activity.

Does anyone have an idea why fail2ban may cause this amount of write activity?

**Comment by sebres** [comment]
1. One thing I can imagine this situation would be `loglevel = DEBUG` (or higher), especially together with enabled jail `recidive` (which is very bad idea).
If so, then please change loglevel to `INFO` or `NOTICE` in your `fail2ban.local`.

2. Can you try newer version (v0.9.3 is a bit outdated)?

**Comment by sebres** [comment]
Not reproducible, thus I'll close until further notice resp. more info provided.
