### ISSUE TITLE
systemd tmfile point to /var/run/ (symlink) instead of /run (directory)

### ISSUE THREAD

**Issue by sl1pkn07** [fail2ban/fail2ban#1836]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.9.7
- OS, including release name/version: Archlinux
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

systemd tmpfile should be change from /var/run/fail2ban to /run/fail2ban

#### Steps to reproduce

install fail2ban
see the contents of /usr/lib/tmfiles.d/fail2ban.conf

#### Expected behavior

point to /run/fail2ban instead of /var/run/fail2ban

#### Observed behavior

in some distros (for not say all), /var/run is a symlink for /run. tmpfile install the directory fail2ban in symlink (/var/run) instead of real directory (/run)

```
└───╼  ls /var/run
lrwxrwxrwx 1 root root 6 mar 26 23:57 /var/run -> ../run
```

also, is a minor typo, if is possible, add new line in the end of document

greetings

**Comment by sebres** [comment]
The setup-scripts resp. some distribution-specified settings are not really part of main fail2ban repository, resp. we've universal config running on most popular distributions, but don't support it for all kinds of distributions (It is the thing of the corresponding maintainer).

You should rather contact the maintainers of fail2ban for archlinux to fix it.

@fail2ban/maintainers Any suggestions?
