### ISSUE TITLE
Failed to start fail2ban.service: Unit fail2ban.service is masked

### ISSUE THREAD

**Issue by poidstotal** [fail2ban/fail2ban#1837]
While Installing from the repo  I received the error "Failed to start fail2ban.service: Unit fail2ban.service is masked"
I had to run "systemctl unmask fail2ban" for the service to start correctly. Hope this help someone

**Comment by sebres** [comment]
I assume you've installed it not from your distribution and hereafter manually copied fail2ban.service to /etc/systemd/system.
This (copy init- resp. systemd-scripts, unmasking, etc) is distribution relevant and belongs normally to the tasks of corresponding distribution package (will be untouched by python install). 
Thus I'll close it as no issue (if someone creates a systemd service, he should be able to unmask it).

**Comment by poidstotal** [comment]
Yes, I did install through the github repo

**Comment by jl2035** [comment]
@sebres How am I able to "unmask" it?
