### ISSUE TITLE
QQ: STIX/TAXII

### ISSUE THREAD

**Issue by mgaulton** [fail2ban/fail2ban#1840]
I'm curious if 
1. STIX/TAXII import is on the roadmap
2. If anyone has a working way to import said IOCs into fail2ban in a meaningful way.

I'd rather not have to roll my own :)

**Comment by sebres** [comment]
1. currently no (too many tasks, todo's etc, that are more important as any industry standard).
Thus I mean - rather I would like implement some new feature (so everyone gets a profit) if I get time, as to implement (resp. lose my time by) supporting of some industry standards.
2. Indicators of compromise is too vague term, so can you please be more precise, what you meant as import here.
