### ISSUE TITLE
non-FHS path issue with tag: 0.9.7 current

### ISSUE THREAD

**Issue by herrold** [fail2ban/fail2ban#1842]
tag (0.9.7) has a non-compliant FHS logging path which breaks a 'hands off'startup -- it should probably be disabled or commented out

That vendor specific path, sitting in home !! is just wrong ;)  IBM needs to 'clean up its act, register with LANANA, and get a /opt/ibm  or use: /var/log/ibm  which is designed for such
```
# [domino-smtp]
# port    = smtp,ssmtp
# filter  = domino-smtp 
# logpath = /home/domino01/data/IBM_TECHNICAL_SUPPORT/console.log

[root@router fail2ban]# service fail2ban restart
Stopping fail2ban:                                         [  OK  ]
Starting fail2ban: ERROR  No file(s) found for glob /home/domino01/data/IBM_TECHNICAL_SUPPORT/console.log
ERROR  Failed during configuration: Have not found any log file for domino-smtp jail
                                                           [FAILED]
[root@router fail2ban]# j
```

**Comment by sebres** [comment]
> it should probably be disabled or commented out

All jails are disabled per definition, see [`enabled = false`](https://github.com/fail2ban/fail2ban/blob/master/config/jail.conf#L113).
Enabling of all jails (e. g. in default section of `jail.local`) is just a bad idea. You should enable only jails that you really need to protect and services you really have.
