### ISSUE TITLE
Jail assign port to all and exclude some specific ports

### ISSUE THREAD

**Issue by eromoe** [fail2ban/fail2ban#1845]
Hi, 

I am trying to use fail2ban and ufw to anti portscan. I have 3 service running on my vps,  I want to block any  ip access all port exclude the 3 ones. 

From some example, I know jail on all port can looks like:
```
 [ufw-port-scan]
 enabled   = true
 ignoreip  = 127.0.0.1/8
 port      = all   # it would be nice to exclude port like  all[3699, 8899]
 filter    = ufw-port-scan
 banaction = ufw
 logpath   = /var/log/ufw.log
 maxretry  = 1
```

But I didn't find how to exclude some port from all,  so I may have to use something as below
```
 [ufw-port-scan]
 enabled   = true
 ignoreip  = 127.0.0.1/8
 port      = all
 filter    = ufw-port-scan
 banaction = ufw
 logpath   = /var/log/ufw.log
 maxretry  = 4
```
This is weaker than previous, because it allow a scanner  scan 4 port at least.

**Comment by sebres** [comment]
If you know any way to block, reject etc with option to ignore some ports using ufw, let us know...
I know only one way to specify ports for ufw like range `1:1000`.
You can write your own action, that will explicitly allow needed ports e.g. in `actionstart`.
