### ISSUE TITLE
Fail2ban environment variables

### ISSUE THREAD

**Issue by maldo** [fail2ban/fail2ban#1847]
Hi

### The issue:

I'm trying to run a custom jail which consists of a python script accessing AWS. The issue is that when fail2ban runs the script, the environment variables that go to the python script are:

```{'LANG': '', 'LC_IDENTIFICATION': '', 'TERM': '', 'LC_MESSAGES': '', 'LANGUAGE': '', 'LC_NUMERIC': '', 'LC_MONETARY': '', 'LC_COLLATE': '', 'LC_MEASUREMENT': '', 'LC_CTYPE': '', 'LC_TELEPHONE': '', 'LC_ADDRESS': '', 'PWD': '/', 'LC_PAPER': '', 'PATH': '/usr/sbin:/usr/bin:/sbin:/bin', 'LC_NAME': '', 'HOME': '/root', 'LC_TIME': '', 'LC_ALL': ''}```

while executing the command directly from bash 

```
NJS_VERSION=1.13.3.0.1.11-1~stretch
AWS_SECRET_ACCESS_KEY=XXXXX
NGINX_VERSION=1.13.3-1~stretch
HOME=/root
AWS_ACCESS_KEY_ID=XXXX
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env
OLDPWD=/root/.aws
```
I'm trying to figure out how to set the OS environment to fail2ban, any ideas?

### Environment:

Debian 9 - Fail2Ban v0.9.6

### Custom action
```
actionban = python /opt/acl.py -b -i <ip>
actionunban = python /opt/acl.py -u -i <ip>
```
Inside the script we just play around with boto3 and aws. If we execute the script directly trought the termninal it works but when fail2ban run it it fails to load the environment variables?

**Comment by sebres** [comment]
Banned by google? if seriously, fail2ban running as service (system daemon), thus only few environment vars are set, see https://www.google.com/search?q=systemd+setting+env+variable
If you using systemd (fail2ban.service). But similar way could be used for init.d script.
