### ISSUE TITLE
IPv6 regex parser is broken

### ISSUE THREAD

**Issue by tonyhain** [fail2ban/fail2ban#1848]
### Environment:

- Fail2Ban version (including any possible distribution suffixes):
fail2ban-client --version
Fail2Ban v0.9.7    
- OS, including release name/version: 
FreeBSD 11.0-STABLE r318134: Wed May 10 15:16:21 UTC 2017 
- [ x ] Fail2Ban installed via OS/distribution mechanisms
- [ x ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

IPv6 parser is broken. Otherwise identical strings pass &/or fail the HOST parser based on the second character of the IPv6 address. Clearly the current HOST parser was written before the current blocks were being allocated from.

#### Steps to reproduce

grep "2a0.:" site-error.log > /tmp/failure.log
edit /tmp/failure.log --- 
       duplicate each line and change second char of one copy to < 2a..: range
in this example:
---
[Sat Jul 22 06:55:43.631808 2017] [php7:error] [pid 96528] [client 2a01:e34:ecb3:20c0:e401:cd5:fff8:a845:60040] script '/usr/local/www/tndh/wp-login.php' not found or unable to stat
[Sat Jul 22 06:55:43.631808 2017] [php7:error] [pid 96528] [client 2001:e34:ecb3:20c0:e401:cd5:fff8:a845:60040] script '/usr/local/www/tndh/wp-login.php' not found or unable to stat
[Sat Jul 22 07:34:15.756691 2017] [php7:error] [pid 5356] [client 2a02:1811:517:1800:c49f:2af7:25a9:53e:49426] script '/usr/local/www/tndh/wp-login.php' not found or unable to stat
[Sat Jul 22 07:34:15.756691 2017] [php7:error] [pid 5356] [client 2602:1811:517:1800:c49f:2af7:25a9:53e:49426] script '/usr/local/www/tndh/wp-login.php' not found or unable to stat
---
above 1st & 2nd / 3rd & 4th  lines are identical other than replacing 2a with 20 or 26.  
fail2ban-regex as above, all 2a0.:: prefixes will miss while all <2a00:: will match

#### Expected behavior

all valid IPv6 prefixes need to work

#### Observed behavior

fail2ban-regex --print-all-matched /tmp/failure.log "client <HOST>.*script.*wp-login\.php\' not found" "forbidden" 

Running tests
=============

Use   failregex line : client <HOST>.*script.*wp-login\.php\' not found
Use ignoreregex line : forbidden
Use         log file : /tmp/failure.log
Use         encoding : US-ASCII

Results
=======

Failregex: 2 total
|-  #) [# of hits] regular expression
|   1) [2] client <HOST>.*script.*wp-login\.php\' not found
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [4] (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
`-

Lines: 4 lines, 0 ignored, 2 matched, 2 missed
[processed in 0.01 sec]

|- Matched line(s):
|  [Sat Jul 22 06:55:43.631808 2017] [php7:error] [pid 96528] [client 2001:e34:ecb3:20c0:e401:cd5:fff8:a845:60040] script '/usr/local/www/tndh/wp-login.php' not found or unable to stat
|  [Sat Jul 22 07:34:15.756691 2017] [php7:error] [pid 5356] [client 2602:1811:517:1800:c49f:2af7:25a9:53e:49426] script '/usr/local/www/tndh/wp-login.php' not found or unable to stat
`-
|- Missed line(s):
|  [Sat Jul 22 06:55:43.631808 2017] [php7:error] [pid 96528] [client 2a01:e34:ecb3:20c0:e401:cd5:fff8:a845:60040] script '/usr/local/www/tndh/wp-login.php' not found or unable to stat
|  [Sat Jul 22 07:34:15.756691 2017] [php7:error] [pid 5356] [client 2a02:1811:517:1800:c49f:2af7:25a9:53e:49426] script '/usr/local/www/tndh/wp-login.php' not found or unable to stat

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
IPv6 supported since fail2ban v.0.10 only.
