### ISSUE TITLE
Extend dovecot auth regex with sql

### ISSUE THREAD

**Issue by yamlfd** [fail2ban/fail2ban#1849]
### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): 0.9.6-2 all
- OS, including release name/version: Debian 9.0
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

Dovecot rules are missing auth via SQL. They only look for `PAM` and `passwd-file`

#### Steps to reproduce
Try to authenticate with invalid user against dovecot imap.

#### Expected behavior
Connection should be blocked as this are only tries to find valid users.

#### Observed behavior
User is not blocked as rexex only expects `(?:pam|passwd-file)`, but mysql auth is used and this changes the string to `sql`

### Configuration, dump and another helpful excerpts

Original:
`
^%(__prefix_line)s(?:auth|auth-worker\(\d+\)): (?:pam|passwd-file)\(\S+,<HOST>\): unknown user\s*$
`

Patched:
`
^%(__prefix_line)s(?:auth|auth-worker\(\d+\)): (?:pam|passwd-file|sql)\(\S+,<HOST>\): unknown user\s*$
`

#### Any customizations done to /etc/fail2ban/ configuration
```
[dovecot]
enabled = true
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
not available
```

#### Relevant lines from monitored log files in question:

```
Jul 29 13:54:06 auth-worker(22401): Info: sql(haine@example.de,70.165.93.163,<n4JLdHNVngZGpV2j>): unknown user
Jul 29 13:54:09 imap-login: Info: Disconnected (auth failed, 1 attempts in 5 secs): user=<haine@example.de>, method=PLAIN, rip=70.165.93.163, lip=62.75.123.123, TLS: Disconnected, session=<n4JLdHNVngZGpV2j>
```

**Comment by sebres** [comment]
Already fixed in current 0.9 and 0.10 (Note the second line from your excerpt will be recognized as failure).

```bash
$ git checkout 0.9
Switched to branch '0.9'

$ fail2ban-regex 'Jul 29 13:54:09 imap-login: Info: Disconnected (auth failed, 1 attempts in 5 secs): user=<haine@example.de>, method=PLAIN, rip=70.165.93.163, lip=62.75.123.123, TLS: Disconnected, session=<n4JLdHNVngZGpV2j>' ./config/filter.d/dovecot.conf
...
Failregex: 1 total
|-  #) [# of hits] regular expression
|   2) [1] ^(?:\[\])?\s*(?:<[^.]+\.[^.]+>\s+)?(?:\S+\s+)?(?:kernel: \[ *\d+\.\d+\]\s+)?(?:@vserver_\S+\s+)?(?:(?:(?:\[\d+\])?:\s+[\[\(]?(auth|dovecot(-auth)?|auth-worker)(?:\(\S+\))?[\]\)]?:?|[\[\(]?(auth|dovecot(-auth)?|auth-worker)(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)\s+)?(?:\[ID \d+ \S+\]\s+)?(?:pop3|imap)-login: (?:Info: )?(?:Aborted login|Disconnected)(?::(?: [^ \(]+)+)? \((?:auth failed, \d+ attempts( in \d+ secs)?|tried to use (disabled|disallowed) \S+ auth)\):( user=<[^>]*>,)?( method=\S+,)? rip=<HOST>(?:, lip=\S+)?(?:, TLS(?: handshaking(?:: SSL_accept\(\) failed: error:[\dA-F]+:SSL routines:[TLS\d]+_GET_CLIENT_HELLO:unknown protocol)?)?(: Disconnected)?)?(, session=<\S+>)?\s*$
...
Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.00 sec]
```
```bash
$ git checkout 0.10
Switched to branch '0.10'

$ fail2ban-regex 'Jul 29 13:54:09 imap-login: Info: Disconnected (auth failed, 1 attempts in 5 secs): user=<haine@example.de>, method=PLAIN, rip=70.165.93.163, lip=62.75.123.123, TLS: Disconnected, session=<n4JLdHNVngZGpV2j>' dovecot
...
Failregex: 1 total
|-  #) [# of hits] regular expression
|   2) [1] ^(?:Aborted login|Disconnected)(?::(?: [^ \(]+)+)? \((?:auth failed, \d+ attempts( in \d+ secs)?|tried to use (disabled|disallowed) \S+ auth)\):( user=<[^>]*>,)?( method=\S+,)? rip=<HOST>(?:, lip=\S+)?(?:, TLS(?: handshaking(?:: SSL_accept\(\) failed: error:[\dA-F]+:SSL routines:[TLS\d]+_GET_CLIENT_HELLO:unknown protocol)?)?(: Disconnected)?)?(, session=<\S+>)?\s*$
...
Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.00 sec]
```

**Comment by yamlfd** [comment]
I do not see you testing "auth-worker(22401): Info: sql(haine". This does not match. The SQL is not in the regex...

**Comment by yamlfd** [comment]
This case was NOT opened for the imap-login line!

**Comment by sebres** [comment]
Yes, I know, but. as I said this belong to same attempt... 

In between I made a PR where it is accepted also (similar another methods), but 1 attempt will be therefore counted twice now. See #1857.
