### ISSUE TITLE
OpenBSD port?

### ISSUE THREAD

**Issue by GhostSquad57** [fail2ban/fail2ban#1851]
Are there any plans to bring fail2ban to OpenBSD's ports?

fail2ban already compiles and works fine on the latest OpenBSD version (tested it myself).

The only changes I've had to make were log locations, e.g. OpenBSD logs ssh requests to /var/authlog instead of auth.log.

**Comment by GhostSquad57** [comment]
OpenBSD has a very comprehensive documentation on creating/maintaining ports: https://www.openbsd.org/faq/ports/

**Comment by sebres** [comment]
Here is a wrong place for this question. Please contact maintainers of OpenBSD...

@fail2ban/maintainers (resp. someone that want to maintain fail2ban for OpenBSD): Please reopen, if I'm wrong.

PR's for some openbsd-related configuration are welcome anytime. 
Also our wiki is open for things like "how to install fail2ban under OpenBSD", resp. similar...
