### ISSUE TITLE
Apache BasicAuth - every client is banned

### ISSUE THREAD

**Issue by rucksman** [fail2ban/fail2ban#1853]
Im am using fail2ban 0.9.3 from the standard Ubuntu repos (running Ubuntu 16.04 LTS). I have a problem with apache-auth.

I am using BasicAuth with a vhost. This brings a lot of entrys in the error.log of this vhost (client denied by server configuration) even if the client is logging in correctly which can be seen in the access.log. The same client generates two entries even if he has logged in already a long time before: First there is ""GET /path/to/file.html HTTP/1.1" 401" immediately followed by "GET /path/to/file.html HTTP/1.1" 200.

So EVERY client will be immediately banned with the standard rules because every page he successfully opens generates a 401 in the error.log. How can I avoid this behaviour?

**Comment by sebres** [comment]
> The same client generates two entries ... 401 ... 200

The filter `apache-auth` matches only the authorization failures of Apache (written in error log). 
This does not check access-log as you meant.
Please note also https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/apache-auth.conf#L35

I'll close it as long as you do not provide more information (please provide log-excerpt **with complete lines**, and/or output of `fail2ban-regex` over this log, resp. `fail2ban-client -d | grep apache-auth`).

**Comment by rucksman** [comment]
OK, so here is more info:
I open a browser (Firefox lastest version) and enter the url "my.website.tld". This website is protected by an Apache BasicAuth. This generates one line in the error log:
`[Mon Aug 07 15:47:19.670439 2017] [access_compat:error] [pid 9095] [client XXX.XXX.XXX.XXX:57590] AH01797: client denied by server configuration: /var/www/my.website.tld/`
I enter my credentials, and the homepage is loaded. This generates one entry in the error log for each file that has to be loaded to show the homepage (html, css, jpg, js, ...), although the homepage is loaded without problems as I have entered the correct credentials:
```
[Mon Aug 07 15:47:50.577815 2017] [access_compat:error] [pid 8332] [client XXX.XXX.XXX.XXX:57598] AH01797: client denied by server configuration: /var/www/my.website.tld/
[Mon Aug 07 15:47:50.578426 2017] [access_compat:error] [pid 8332] [client XXX.XXX.XXX.XXX:57598] AH01797: client denied by server configuration: /var/www/my.website.tld/index.php
[Mon Aug 07 15:47:50.617247 2017] [access_compat:error] [pid 8332] [client XXX.XXX.XXX.XXX:57598] AH01797: client denied by server configuration: /var/www/my.website.tld/css/styles.css
```
The same goes if I then click on link in the menu of the homepage to visit another page (which is again loaded without problems as I have entered the correct credentials in the beginning):
```
[Mon Aug 07 15:48:25.097865 2017] [access_compat:error] [pid 9095] [client XXX.XXX.XXX.XXX:57610] AH01797: client denied by server configuration: /var/www/my.website.tld/my_subpage.html, referer: http://old.pvxchange.com/index.php
[Mon Aug 07 15:48:25.225258 2017] [access_compat:error] [pid 9095] [client XXX.XXX.XXX.XXX:57610] AH01797: client denied by server configuration: /var/www/old.pvxchange.com/img/menu.png, referer: http://old.pvxchange.com/index.php
```
So this makes it clear that every user is immediately banned.

**Comment by sebres** [comment]
I'm not really familiar with apache, but I readed about many similar problems after upgrade from 2.2 to 2.4...
So please read "[Upgrading to 2.4 from 2.2 - Apache HTTP Server Version 2.4](http://httpd.apache.org/docs/2.4/upgrading.html)", I think you've still old access control idioms there (resp. a mix of both).

Anyway surely this is not normal, that any URL produces an error entry in error-log.
