### ISSUE TITLE
Not banning - pureftpd

### ISSUE THREAD

**Issue by OscarAkaElvis** [fail2ban/fail2ban#1855]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.9.6-2
- OS, including release name/version: Debian 9 (stretch)
- [ X] Fail2Ban installed via OS/distribution mechanisms <- installed by apt
- [ X] You have not applied any additional foreign patches to the codebase
- [ X] Some customizations were done to the configuration (provide details below is so)

### The issue:

I'm using pureftpd (1.0.46) and fail2ban but is not working. It seems is able to read the log but the fail2ban.filter event is not triggered. I must say I already have on the same maching running ok fail2ban against apache and ssh. The problem is only with pureftpd.

Note: fail2ban is installed on debian host and the services (apache, pureftpd, etc) are inside docker containers with the ports and the logs mapped to the host. I think this is not relevant for the detail of the issue because the services are working and the logs are accessed by fail2ban, and as I said, I have other same scenarios working (apache for example is working and is inside a container too).

#### Steps to reproduce

I make a failed login to the ftp from a different machine.

#### Expected behavior

I expect the fail2ban.filter event in the log but it doesn't appear.

#### Observed behavior

I put the loglevel into debug mode. This is the log when I connect to the ftp failing a login:

    2017-08-03 03:31:10,163 fail2ban.filterpoll     [4429]: DEBUG   /var/log/ftp/ftp.log has been modified
    2017-08-03 03:31:10,164 fail2ban.datedetector   [4429]: DEBUG   Matched time template (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
    2017-08-03 03:31:10,165 fail2ban.datedetector   [4429]: DEBUG   Got time 1470231069.000000 for "'Aug  3 08:31:09'" using template (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
    2017-08-03 03:31:10,165 fail2ban.datedetector   [4429]: DEBUG   Sorting the template list
    2017-08-03 03:31:10,166 fail2ban.datedetector   [4429]: DEBUG   Winning template: (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)? with 2 hits

#### Any additional information

Comparing the log with the apache (what is working fine) logs, we can see on apache the `fail2ban.filter` is appearing in the logs: 

    2017-08-03 03:43:37,024 fail2ban.filterpoll     [4429]: DEBUG   /var/log/apache2/error.log has been modified
    2017-08-03 03:43:37,025 fail2ban.datedetector   [4429]: DEBUG   Matched time template (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
    2017-08-03 03:43:37,026 fail2ban.datedetector   [4429]: DEBUG   Got time 1501767816.000000 for "'Thu Aug 03 08:43:36.224686 2017'" using template (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
    2017-08-03 03:43:37,026 fail2ban.filter         [4429]: DEBUG   Processing line with time:1501767816.0 and ip:192.168.0.154
    2017-08-03 03:43:37,027 fail2ban.filter         [4429]: INFO    [apache] Found 192.168.0.154

At first sight, this suggests the problem could be the filter rule or the regexp... will see is not the problem I think.

#### Any customizations done to /etc/fail2ban/ configuration

This is the part of the pureftp on the `jail.local` file:
```
[pureftpd]
enabled = true
port = 21
filter = pure-ftpd
logpath = /var/log/ftp/ftp.log
backend = polling
maxretry = 5
```

#### Relevant lines from monitored log files in question:
My `/var/log/ftp/ftp.log` is receiving ok the login attemps into the ftp, some lines as example:
```
Aug  3 08:31:01 88a4998e8b37 pure-ftpd: (?@192.168.0.159) [INFO] New connection from 192.168.0.159
Aug  3 08:31:09 88a4998e8b37 pure-ftpd: (?@192.168.0.159) [WARNING] Authentication failed for user [testinguser]
```

This is my `/etc/fail2ban/filter.d/pure-ftpd.conf` file:
```
[INCLUDES]
before = common.conf
[Definition]
_daemon = pure-ftpd
__errmsg = Authentication failed for user
failregex = ^.*pure-ftpd: \(\?@<HOST>\) \[WARNING\] %(__errmsg)s .*$
ignoreregex =
```

#### Things I already tested

I tested "playing" with `/etc/fail2ban/filter.d/pure-ftpd.conf` file with different failregex. Letting only `__errmsg` and `failregex` removing the rest (includes, _daemon, etc). Same result.

If I launch `fail2ban-regex /var/log/ftp/ftp.log /etc/fail2ban/filter.d/pure-ftpd.conf`,  it returns some hits so I guess the regex is ok. Anyway, I did some tests... I prepared it even with datepattern: `fail2ban-regex /var/log/ftp/ftp.log /etc/fail2ban/filter.d/pure-ftpd.conf -v -v -d "%b %d %H:%M:%S" --print-all-matched` and returned:
```
Running tests
=============

Use      datepattern : MON Day 24hour:Minute:Second
Use   failregex filter file : pure-ftpd, basedir: /etc/fail2ban
Use         log file : /var/log/ftp/ftp.log
Use         encoding : UTF-8

Results
=======

Failregex: 4 total
|-  #) [# of hits] regular expression
|   1) [4] pure-ftpd: \(\?@<HOST>\) \[WARNING\] Authentication failed for user \[.+\](.*)?$
|      192.168.0.159  Wed Aug 03 09:48:43 2016
|      192.168.0.159  Wed Aug 03 10:23:51 2016
|      192.168.0.159  Wed Aug 03 10:32:15 2016
|      192.168.0.159  Wed Aug 03 10:39:18 2016
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [15] MON Day 24hour:Minute:Second
`-

Lines: 15 lines, 0 ignored, 4 matched, 11 missed
[processed in 0.00 sec]

|- Matched line(s):
|  Aug  3 09:48:43 88a4998e8b37 pure-ftpd: (?@192.168.0.159) [WARNING] Authentication failed for user [testinguser]
|  Aug  3 10:23:51 88a4998e8b37 pure-ftpd: (?@192.168.0.159) [WARNING] Authentication failed for user [othertest]
|  Aug  3 10:32:15 88a4998e8b37 pure-ftpd: (?@192.168.0.159) [WARNING] Authentication failed for user [xd]
|  Aug  3 10:39:18 88a4998e8b37 pure-ftpd: (?@192.168.0.159) [WARNING] Authentication failed for user [asdf]
`-
|- Missed line(s):
|  Aug  3 09:13:46 88a4998e8b37 liblogging-stdlog:  [origin software="rsyslogd" swVersion="8.24.0" x-pid="8" x-info="http://www.rsyslog.com"] start
|  Aug  3 09:14:33 88a4998e8b37 pure-ftpd: (?@192.168.0.159) [INFO] New connection from 192.168.0.159
|  Aug  3 09:14:33 88a4998e8b37 pure-ftpd: (?@192.168.0.159) [INFO] Logout.
|  Aug  3 09:48:36 88a4998e8b37 pure-ftpd: (?@192.168.0.159) [INFO] New connection from 192.168.0.159
|  Aug  3 10:03:43 88a4998e8b37 pure-ftpd: (?@192.168.0.159) [INFO] Timeout - try typing a little faster next time
|  Aug  3 10:23:44 88a4998e8b37 pure-ftpd: (?@192.168.0.159) [INFO] New connection from 192.168.0.159
|  Aug  3 10:32:02 88a4998e8b37 pure-ftpd: (?@192.168.0.159) [INFO] Logout.
|  Aug  3 10:32:07 88a4998e8b37 pure-ftpd: (?@192.168.0.159) [INFO] New connection from 192.168.0.159
|  Aug  3 10:39:07 88a4998e8b37 pure-ftpd: (?@192.168.0.159) [INFO] Logout.
|  Aug  3 10:39:12 88a4998e8b37 pure-ftpd: (?@192.168.0.159) [INFO] New connection from 192.168.0.159
|  Aug  3 10:54:18 88a4998e8b37 pure-ftpd: (?@192.168.0.159) [INFO] Timeout - try typing a little faster next time
`-
```

More tests... adding the designed date patern to the `[pureftpd]` section on `/etc/fail2ban/jail.local` file makes no effect. This added: `datepattern = %b %d %H:%M:%S`. Same result.

I tested with `polling` backend and also with `auto`. Same result on everything (ssh and apache working but pureftpd is not banning anybody).

#### Final note

I know very well if you have fail2ban on host and the services in docker containers, once the ban is triggered, the machine can be still hit because it hits a FORWARD rule before fail2ban rule... I know how to fix that (I already have it for apache working)... but that's another story... at least it should appear in the log as trying to ban.

Not sure if this could be a bug, it seems so. Any help? Thank you.

**Comment by sebres** [comment]
Corresponding your debug output, fail2ban recognized too old date there (here diff to my test, compared to our v.0.9):
```diff
Working on line 'Aug  3 08:31:09 88a4998e8b37 pure-ftpd: (?@192.168.0.159) [WARNING] Authentication failed for user [testinguser]'
Matched time template (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
-Got time 1470231069.000000 for "'Aug  3 08:31:09'" using template (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
+Got time 1501741869.000000 for "'Aug  3 08:31:09'" using template (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
```
Posix-time `1470231069` belong to the year 2016, so recognized as too old...
```bash
$ date -d @1470231069
Wed Aug  3 15:31:09 CEST 2016
```

> More tests... adding the designed date patern to the [pureftpd] section on /etc/fail2ban/jail.local file makes no effect. This added: datepattern = %b %d %H:%M:%S. Same result.

Firstly adding a date-pattern in jail works only since v.0.10, in v.0.9 you can extend it in the filter only.
Secondly the python init-config expects escaped `%` character (as dual `%%`).
```INI
# filter.d/pure-ftpd.local
[Init]
datepattern = %%b %%d %%H:%%M:%%S
```

Closed, because not reproduceable in current 0.9 / 0.10 versions.

**Comment by OscarAkaElvis** [comment]
Ok thank you for you comments and tips. I solved the "problem" of the server date... same result, it's obvious for fail2ban it doesn't care if you are in 2016 or 2017.

I tried setting the datepattern using double %% as you said under a `[Init]` clause on the filter file... same result. I tested without it again... same result. I must say I only tested the datepattern because of desperation. Of course, after each change I'm doing a `/etc/init.d/fail2ban restart`.

Can't you reproduce this? I have working flawlessly on the same machine fail2ban with other services... but I can't make it working with pureftp... not sure why. Did you REALLY tested with the versions I'm using? I know sometimes is complicated to replicate the entire environment but each change or test I do over this I'm more sure this is some kind of bug.

I did another test cleaning logs and only with one failed attempt. Ftp log:
```
Aug  7 20:41:43 88a4998e8b37 liblogging-stdlog:  [origin software="rsyslogd" swVersion="8.24.0" x-pid="8" x-info="http://www.rsyslog.com"] start
Aug  7 20:48:12 88a4998e8b37 pure-ftpd: (?@192.168.0.159) [INFO] New connection from 192.168.0.159
Aug  7 20:48:21 88a4998e8b37 pure-ftpd: (?@192.168.0.159) [WARNING] Authentication failed for user [ftptest]
```

My regex-fail2ban result using the datepattern which seems to work, here is the command and the output:
```
fail2ban-regex /var/log/ftp/ftp.log /etc/fail2ban/filter.d/pure-ftpd.conf --print-all-matched

Running tests
=============

Use   failregex filter file : pure-ftpd, basedir: /etc/fail2ban
Use      datepattern : MON Day 24hour:Minute:Second
Use         log file : /var/log/ftp/ftp.log
Use         encoding : UTF-8


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] ^.*pure-ftpd: \(\?@<HOST>\) \[WARNING\] Authentication failed for user .*$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [3] MON Day 24hour:Minute:Second
`-

Lines: 3 lines, 0 ignored, 1 matched, 2 missed
[processed in 0.00 sec]

|- Matched line(s):
|  Aug  7 20:48:21 88a4998e8b37 pure-ftpd: (?@192.168.0.159) [WARNING] Authentication failed for user [sdaf]
`-
|- Missed line(s):
|  Aug  7 20:41:43 88a4998e8b37 liblogging-stdlog:  [origin software="rsyslogd" swVersion="8.24.0" x-pid="8" x-info="http://www.rsyslog.com"] start
|  Aug  7 20:48:12 88a4998e8b37 pure-ftpd: (?@192.168.0.159) [INFO] New connection from 192.168.0.159
`-
```

The output of fail2ban log in debug mode:

```
2017-08-07 22:48:13,529 fail2ban.filterpoll     [1808]: DEBUG   /var/log/ftp/ftp.log has been modified
2017-08-07 22:48:13,530 fail2ban.datedetector   [1808]: DEBUG   Matched time template MON Day 24hour:Minute:Second
2017-08-07 22:48:13,531 fail2ban.datedetector   [1808]: DEBUG   Got time 1502131692.000000 for "'Aug  7 20:48:12'" using template MON Day 24hour:Minute:Second
2017-08-07 22:48:13,532 fail2ban.datedetector   [1808]: DEBUG   Sorting the template list
2017-08-07 22:48:13,533 fail2ban.datedetector   [1808]: DEBUG   Winning template: MON Day 24hour:Minute:Second with 1 hits
2017-08-07 22:48:21,541 fail2ban.filterpoll     [1808]: DEBUG   /var/log/ftp/ftp.log has been modified
2017-08-07 22:48:21,542 fail2ban.datedetector   [1808]: DEBUG   Matched time template MON Day 24hour:Minute:Second
2017-08-07 22:48:21,542 fail2ban.datedetector   [1808]: DEBUG   Got time 1502131701.000000 for "'Aug  7 20:48:21'" using template MON Day 24hour:Minute:Second
2017-08-07 22:48:21,542 fail2ban.datedetector   [1808]: DEBUG   Sorting the template list
2017-08-07 22:48:21,542 fail2ban.datedetector   [1808]: DEBUG   Winning template: MON Day 24hour:Minute:Second with 2 hits
```

I insist, everything seems to be set up correctly but there is no `fail2ban.filter` event... I think could be interesting to dig on this more deeply.

Thank you and regards.

**Comment by sebres** [comment]
> Did you REALLY tested with the versions I'm using?

No, I tested it with current 0.9 and 0.10 branches. This means - it is surely fixed. But I've just no time to retrieve which commit exactly does it.
For the case, that is some constellation (your server, config, etc.) just to be sure, could you please test it with our newest version (without installation):
Download and unpack [0.9](https://github.com/fail2ban/fail2ban/archive/master.zip) or [0.10](https://github.com/fail2ban/fail2ban/archive/0.10.zip) to "/tmp/fail2ban-test/" or use git clone...
```bash
cd /tmp/fail2ban-test/
PYTHONPATH=. bin/fail2ban-regex -v 'Aug  3 08:31:09 88a4998e8b37 pure-ftpd: (?@192.168.0.159) [WARNING] Authentication failed for user [testinguser]' ./config/filter.d/pure-ftpd.conf  | grep 192
```
Which date you'll see there?

**Comment by sebres** [comment]
I think, I know what it is...
If you take a look to the following line, you'll see that fail2ban find the attempt at `03:31:10`, but the time written from pureftpd is `08:31:09` (thus in the future +5 hours).
```
2017-08-03 03:31:10,165 fail2ban.datedetector   [4429]: DEBUG   Got time 1470231069.000000 for "'Aug  3 08:31:09'" ...
```
Could it be, the pureftpd acts within another timezone as fail2ban? 
Because this date format has no year. In this case the date can be recognized as date from the last year...

If so, please see similar issue https://github.com/fail2ban/fail2ban/issues/1804#issuecomment-308698338
So you've currently two options:
- either you bring your pureftpd-service to write the log-entries in the same TZ, where fail2ban works also (normally it is system-TZ, not UTC).
- or (if you can't), then you can try to use our latest version (v. 0.10 only), where you've a new option, that could be used for this jail:
```
[pureftpd]
logtimezone = UTC+0700
# or abbreviation zone like CXT
# logtimezone = CXT
...
```

**Comment by OscarAkaElvis** [comment]
Yeah, you rock dude! the problem was the timezone. Inside the docker container was different. Now I configured the timezone inside the container to be the same that what is set on host, in my case with `Europe/Madrid` value. I'll put my sentences done on the Dockerfile, maybe could be useful for others:

    ENV TZ=Europe/Madrid
    RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

Sorry for bothering you believing it was a bug. Thank you so much, now everything is working! 😄
