### ISSUE TITLE
<fq-hostname> vs %(hostname)s if specified in actionstart, etc.

### ISSUE THREAD

**Issue by mtompkins** [fail2ban/fail2ban#1859]
### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): 0.11 commit 409de18
- OS, including release name/version: Ubuntu 17.04
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

It seems there has been a change from using `%(hostname)s` to `<fq-hostname>` however the new `<fq-hostname>` does not resolve to the host and comes across as pure text.

#### Steps to reproduce
Any initiation of fail2ban with emailing enabled

#### Expected behavior
`<fq-hostname>` should resolve to `hostname`

#### Observed behavior
Produces the string `<fq-hostname>` and not the actual `hostname`

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
What did you meant exactly: which config-file, which action, etc. ?

What do you see, if you calls this:
```bash
python -c 'from fail2ban.server.ipdns import DNSUtils; print("fq: %s, sh: %s" % (DNSUtils.getHostname(fqdn=True), DNSUtils.getHostname(fqdn=False)))'
```
And what says this test case:
```bash
fail2ban-testcases -fn -l 10 testComplexMailActionMultiLog | grep -E 'banned [0-9\.]+ from'
```

Do you see your server-name in both cases?

**Comment by mtompkins** [comment]
What did you meant exactly: which config-file, which action, etc. ?
- The tag was produced as a string in emails

`python -c 'from fail2ban.server.ipdns import DNSUtils; print("fq: %s, sh: %s" % (DNSUtils.getHostname(fqdn=True), DNSUtils.getHostname(fqdn=False)))'
`
- `fq: zeus.marktompkins.me, sh: zeus` <- This is correct hostname

`fail2ban-testcases -fn -l 10 testComplexMailActionMultiLog | grep -E 'banned [0-9\.]+ from'
`

```
----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

```

Do you see your server-name in both cases?
- As shown, no result on fail2ban-testcases call

**Comment by sebres** [comment]
> fq: zeus.marktompkins.me, sh: zeus <- This is correct hostname

Well, the `fq` means here full-qualified hostname and was introduced in #1758 .

> fail2ban-testcases does not execute testcases...

I'm not sure it runnable if installed. Can you please do that from the installation folder:
```
cd /tmp/install/fail2ban-0.11/
PYTHONPATH=. bin/fail2ban-testcases -fn -l 10 testComplexMailActionMultiLog
```

**Comment by mtompkins** [comment]
Thank you - I did see that commit. 
Also - the tag is incorrect in the email subject, not sure if the test covers that?

Here is the result:

Fail2ban 0.11.0dev0 test suite. Python 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]. Please wait...
 +  247 7F74BA2F9700 fail2ban.datetemplate     DEBUG   constructed regex (?:^|\b|\W)((?P<Y>\d\d\d\d)-(?P<m>1[0-2]|0[1-9]|[1-9])-(?P<d>3[0-1]|[1-2]\d|0[1-9]|[1-9]| [1-9])[T ](?P<H>2[0-3]|[0-1]\d|\d):(?P<M>[0-5]\d|\d):(?P<S>6[0-1]|[0-5]\d|\d)(?:\.(?P<f>[0-9]{1,6}))?(?P<z>Z|UTC|GMT|[+-][01]\d(?::?\d{2})?))(?=\b|\W|$)
 +  306 7F74BA2F9700 fail2ban                  WARNI Skipping gamin backend testing. Got exception 'Skip, fast: True, no_gamin: True'
testComplexMailActionMultiLog (fail2ban.tests.servertestcase.ServerConfigReaderTests) ... 
 +  317 7F74BA2F9700 fail2ban                  DEBUG ========== fail2ban.tests.servertestcase.ServerConfigReaderTests.testComplexMailActionMultiLog ====================
 +  318 7F74BA2F9700 fail2ban.configreader     INFO  Loading configs for action.d/mail-whois-lines under config 
 +  318 7F74BA2F9700 fail2ban.configreader     DEBUG Reading configs for action.d/mail-whois-lines under config 
 +  318 7F74BA2F9700 fail2ban.configreader     DEBUG Reading config files: config/action.d/mail-whois-lines.conf
 +  318 7F74BA2F9700 fail2ban.configparserinc  INFO    Loading files: ['config/action.d/mail-whois-lines.conf']
 +  318 7F74BA2F9700 fail2ban.configparserinc  INFO    Loading files: ['config/action.d/mail-whois-common.conf']
 +  318 7F74BA2F9700 fail2ban.configparserinc  INFO    Loading files: ['config/action.d/mail-whois-common.local']
 +  318 7F74BA2F9700 fail2ban.configparserinc  INFO    Loading files: ['config/action.d/helpers-common.conf']
 +  319 7F74BA2F9700 fail2ban.configparserinc  INFO    Loading files: ['config/action.d/mail-whois-common.conf', 'config/action.d/helpers-common.conf', 'config/action.d/mail-whois-lines.conf']
 +  319 7F74BA2F9700 fail2ban.jail             INFO  Creating new jail 'j-mail-whois-lines'
 +  319 7F74BA2F9700 fail2ban.jail             INFO  Jail 'j-mail-whois-lines' uses poller {}
 +  319 7F74BA2F9700 fail2ban.filter           DEBUG Setting usedns = warn for FilterPoll(Jail('j-mail-whois-lines'))
 +  320 7F74BA2F9700 fail2ban.filter           DEBUG Created FilterPoll(Jail('j-mail-whois-lines'))
 +  320 7F74BA2F9700 fail2ban.filterpoll       DEBUG Created FilterPoll
 +  320 7F74BA2F9700 fail2ban.jail             INFO  Initiated 'polling' backend
 +  320 7F74BA2F9700 fail2ban.CommandAction    DEBUG Created <class 'fail2ban.server.action.CommandAction'>
 +  320 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set actionunban = ''
 +  320 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set norestored = True
 +  320 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set actionstop = 'printf %b "Hi,\\n\nThe jail j-mail-whois-lines has been stopped.\\n\nRegards,\\n\nFail2Ban" | mail -s "[Fail2Ban] j-mail-whois-lines: stopped on <fq-hostname>" root'
 +  320 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set actionstart = 'printf %b "Hi,\\n\nThe jail j-mail-whois-lines has been started successfully.\\n\nRegards,\\n\nFail2Ban" | mail -s "[Fail2Ban] j-mail-whois-lines: started on <fq-hostname>" root'
 +  320 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set actionban = '( printf %b "Hi,\\n\nThe IP <ip> has just been banned by Fail2Ban after\n<failures> attempts against j-mail-whois-lines.\\n\\n\nHere is more information about <ip> :\\n"\necho \'-- information about <ip> --\';\nprintf %b "\\nLines containing failures of <ip> (max 2)\\n";\nlogpath="./fail2ban/tests/files/testcase01.log\n         ./fail2ban/tests/files/testcase01a.log"; grep -m 1 -E "(^|[^0-9a-fA-F:])$(echo \'<ip>\' | sed \'s/\\./\\\\./g\')([^0-9a-fA-F:]|$)" $logpath | tail -n 2;\nprintf %b "\\n\nRegards,\\n\nFail2Ban" ) | mail -s "[Fail2Ban] j-mail-whois-lines: banned <ip> from <fq-hostname>" root'
 +  320 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set actioncheck = ''
 +  320 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set known/mailcmd = 'mail -s'
 +  320 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set name = 'j-mail-whois-lines'
 +  320 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set dest = 'root'
 +  320 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set known/grepopts = '-m <grepmax>'
 +  320 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set logpath = './fail2ban/tests/files/testcase01.log\n         ./fail2ban/tests/files/testcase01a.log'
 +  320 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set grepmax = '2'
 +  320 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set known/dest = 'root'
 +  320 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set mailcmd = 'mail -s'
 +  321 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set grepopts = '-m 1'
 +  321 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set known/name = 'default'
 +  321 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set known/logpath = '/dev/null'
 +  321 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set known/greplimit = 'tail -n <grepmax>'
 +  321 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set greplimit = 'tail -n <grepmax>'
 +  321 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set actname = 'mail-whois-lines'
 +  321 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set known/grepmax = '1000'
 +  321 7F74BA2F9700 fail2ban.configreader     INFO  Loading configs for action.d/complain under config 
 +  321 7F74BA2F9700 fail2ban.configreader     DEBUG Reading configs for action.d/complain under config 
 +  321 7F74BA2F9700 fail2ban.configreader     DEBUG Reading config files: config/action.d/complain.conf
 +  321 7F74BA2F9700 fail2ban.configparserinc  INFO    Loading files: ['config/action.d/complain.conf']
 +  321 7F74BA2F9700 fail2ban.configparserinc  INFO    Loading files: ['config/action.d/helpers-common.conf', 'config/action.d/complain.conf']
 +  322 7F74BA2F9700 fail2ban.jail             INFO  Creating new jail 'j-complain-abuse'
 +  322 7F74BA2F9700 fail2ban.jail             INFO  Jail 'j-complain-abuse' uses poller {}
 +  322 7F74BA2F9700 fail2ban.filter           DEBUG Setting usedns = warn for FilterPoll(Jail('j-complain-abuse'))
 +  322 7F74BA2F9700 fail2ban.filter           DEBUG Created FilterPoll(Jail('j-complain-abuse'))
 +  322 7F74BA2F9700 fail2ban.filterpoll       DEBUG Created FilterPoll
 +  322 7F74BA2F9700 fail2ban.jail             INFO  Initiated 'polling' backend
 +  322 7F74BA2F9700 fail2ban.CommandAction    DEBUG Created <class 'fail2ban.server.action.CommandAction'>
 +  322 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set actionunban = ''
 +  322 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set norestored = True
 +  322 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set actionstop = ''
 +  322 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set actionstart = ''
 +  322 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set actionban = 'oifs=${IFS};\nRESOLVER_ADDR="<ip-rev>abuse-contacts.abusix.org"\nif [ "1" -gt 0 ]; then echo "try to resolve $RESOLVER_ADDR"; fi\nADDRESSES=$(dig +short -t txt -q $RESOLVER_ADDR | tr -d \'"\')\nIFS=,; ADDRESSES=$(echo $ADDRESSES)\nIFS=${oifs}\nIP=<ip>\nif [ ! -z "$ADDRESSES" ]; then\n( printf %b "Dear Sir/Madam,\\n\\nWe have detected abuse from the IP address $IP, which according to a abusix.com is on your network. We would appreciate if you would investigate and take action as appropriate.\\n\\nLog lines are given below, but please ask if you require any further information.\\n\\n(If you are not the correct person to contact about this please accept our apologies - your e-mail address was extracted from the whois record by an automated process.)\\n\\n This mail was generated by Fail2Ban.\\nThe recipient address of this report was provided by the Abuse Contact DB by abusix.com. abusix.com does not maintain the content of the database. All information which we pass out, derives from the RIR databases and is processed for ease of use. If you want to change or report non working abuse contacts please contact the appropriate RIR. If you have any further question, contact abusix.com directly via email (info@abusix.com). Information about the Abuse Contact Database can be found here: https://abusix.com/global-reporting/abuse-contact-db\\nabusix.com is neither responsible nor liable for the content or accuracy of this message.\\n\\n"; date \'+Note: Local timezone is %z (%Z)\';\nprintf %b "\\nLines containing failures of <ip> (max 2)\\n";\nlogpath="./fail2ban/tests/files/testcase01.log\n         ./fail2ban/tests/files/testcase01a.log"; grep -m 1 -E "(^|[^0-9a-fA-F:])$(echo \'<ip>\' | sed \'s/\\./\\\\./g\')([^0-9a-fA-F:]|$)" $logpath | tail -n 2;\n) | mail -s \'Hostname: <ip-host>, family: <family>\' - "Abuse from <ip>"  $ADDRESSES\nfi'
 +  322 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set actioncheck = ''
 +  322 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set name = 'j-complain-abuse'
 +  322 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set known/grepopts = '-m <grepmax>'
 +  322 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set logpath = './fail2ban/tests/files/testcase01.log\n         ./fail2ban/tests/files/testcase01a.log'
 +  323 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set grepmax = '2'
 +  323 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set mailcmd = "mail -s 'Hostname: <ip-host>, family: <family>' -"
 +  323 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set greplimit = 'tail -n <grepmax>'
 +  323 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set grepopts = '-m 1'
 +  323 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set known/greplimit = 'tail -n <grepmax>'
 +  323 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set debug = '1'
 +  323 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set actname = 'complain'
 +  323 7F74BA2F9700 fail2ban.CommandAction    DEBUG   Set known/grepmax = '1000'
 +  323 7F74BA2F9700 fail2ban.jail             INFO  Creating new jail 'DummyJail #140139243039632 with 0 tickets'
 +  323 7F74BA2F9700 fail2ban                  DEBUG # ==================================================
 +  323 7F74BA2F9700 fail2ban                  DEBUG # == j-mail-whois-lines - mail-whois-lines        ==
 +  323 7F74BA2F9700 fail2ban                  DEBUG # ==================================================
 +  323 7F74BA2F9700 fail2ban                  DEBUG ===== # === ip4-ban === =====
 +  328 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a3cba0 -- stdout: 'Hi,'
 +  328 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a3cba0 -- stdout: ''
 +  328 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a3cba0 -- stdout: 'The IP 87.142.124.10 has just been banned by Fail2Ban after'
 +  328 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a3cba0 -- stdout: '100 attempts against j-mail-whois-lines.'
 +  328 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a3cba0 -- stdout: ''
 +  328 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a3cba0 -- stdout: ''
 +  328 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a3cba0 -- stdout: 'Here is more information about 87.142.124.10 :'
 +  328 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a3cba0 -- stdout: '-- information about 87.142.124.10 --'
 +  329 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a3cba0 -- stdout: ''
 +  329 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a3cba0 -- stdout: 'Lines containing failures of 87.142.124.10 (max 2)'
 +  329 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a3cba0 -- stdout: './fail2ban/tests/files/testcase01.log:Dec 31 11:59:59 [sshd] error: PAM: Authentication failure for kevin from 87.142.124.10'
 +  329 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a3cba0 -- stdout: './fail2ban/tests/files/testcase01a.log:Dec 31 11:55:01 [sshd] error: PAM: Authentication failure for test from 87.142.124.10'
 +  329 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a3cba0 -- stdout: ''
 +  329 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a3cba0 -- stdout: ''
 +  329 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a3cba0 -- stdout: 'Regards,'
 +  329 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a3cba0 -- stdout: ''
 +  329 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a3cba0 -- stdout: 'Fail2Ban'
 +  329 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a3cba0 -- stdout: '... | mail -s [Fail2Ban] j-mail-whois-lines: banned 87.142.124.10 from zeus.marktompkins.me root'
 +  329 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a3cba0 -- returned successfully 0
 +  329 7F74BA2F9700 fail2ban                  DEBUG # ==================================================
 +  329 7F74BA2F9700 fail2ban                  DEBUG # == j-complain-abuse - complain                  ==
 +  329 7F74BA2F9700 fail2ban                  DEBUG # ==================================================
 +  329 7F74BA2F9700 fail2ban                  DEBUG ===== # === ip4-ban === =====
 +  333 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a44d30 -- stdout: 'try to resolve 10.124.142.87.abuse-contacts.abusix.org'
 +  333 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a44d30 -- stdout: 'Dear Sir/Madam,'
 +  333 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a44d30 -- stdout: ''
 +  333 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a44d30 -- stdout: 'We have detected abuse from the IP address 87.142.124.10, which according to a abusix.com is on your network. We would appreciate if you would investigate and take action as appropriate.'
 +  333 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a44d30 -- stdout: ''
 +  333 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a44d30 -- stdout: 'Log lines are given below, but please ask if you require any further information.'
 +  333 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a44d30 -- stdout: ''
 +  333 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a44d30 -- stdout: '(If you are not the correct person to contact about this please accept our apologies - your e-mail address was extracted from the whois record by an automated process.)'
 +  333 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a44d30 -- stdout: ''
 +  333 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a44d30 -- stdout: ' This mail was generated by Fail2Ban.'
 +  333 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a44d30 -- stdout: 'The recipient address of this report was provided by the Abuse Contact DB by abusix.com. abusix.com does not maintain the content of the database. All information which we pass out, derives from the RIR databases and is processed for ease of use. If you want to change or report non working abuse contacts please contact the appropriate RIR. If you have any further question, contact abusix.com directly via email (info@abusix.com). Information about the Abuse Contact Database can be found here: https://abusix.com/global-reporting/abuse-contact-db'
 +  333 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a44d30 -- stdout: 'abusix.com is neither responsible nor liable for the content or accuracy of this message.'
 +  333 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a44d30 -- stdout: ''
 +  333 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a44d30 -- stdout: 'Note: Local timezone is +0200 (CEST)'
 +  333 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a44d30 -- stdout: ''
 +  333 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a44d30 -- stdout: 'Lines containing failures of 87.142.124.10 (max 2)'
 +  334 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a44d30 -- stdout: './fail2ban/tests/files/testcase01.log:Dec 31 11:59:59 [sshd] error: PAM: Authentication failure for kevin from 87.142.124.10'
 +  334 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a44d30 -- stdout: './fail2ban/tests/files/testcase01a.log:Dec 31 11:55:01 [sshd] error: PAM: Authentication failure for test from 87.142.124.10'
 +  334 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a44d30 -- stdout: ''
 +  334 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a44d30 -- stdout: '... | mail -s Hostname: test-host, family: inet4 - Abuse from 87.142.124.10 abuse-1@abuse-test-server abuse-2@abuse-test-server'
 +  334 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a44d30 -- returned successfully 0
 +  334 7F74BA2F9700 fail2ban                  DEBUG ===== # === ip6-ban === =====
 +  338 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a43530 -- stdout: 'try to resolve 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2.abuse-contacts.abusix.org'
 +  338 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a43530 -- stdout: 'Dear Sir/Madam,'
 +  338 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a43530 -- stdout: ''
 +  338 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a43530 -- stdout: 'We have detected abuse from the IP address 2001:db8::1, which according to a abusix.com is on your network. We would appreciate if you would investigate and take action as appropriate.'
 +  338 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a43530 -- stdout: ''
 +  338 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a43530 -- stdout: 'Log lines are given below, but please ask if you require any further information.'
 +  338 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a43530 -- stdout: ''
 +  338 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a43530 -- stdout: '(If you are not the correct person to contact about this please accept our apologies - your e-mail address was extracted from the whois record by an automated process.)'
 +  338 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a43530 -- stdout: ''
 +  338 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a43530 -- stdout: ' This mail was generated by Fail2Ban.'
 +  338 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a43530 -- stdout: 'The recipient address of this report was provided by the Abuse Contact DB by abusix.com. abusix.com does not maintain the content of the database. All information which we pass out, derives from the RIR databases and is processed for ease of use. If you want to change or report non working abuse contacts please contact the appropriate RIR. If you have any further question, contact abusix.com directly via email (info@abusix.com). Information about the Abuse Contact Database can be found here: https://abusix.com/global-reporting/abuse-contact-db'
 +  338 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a43530 -- stdout: 'abusix.com is neither responsible nor liable for the content or accuracy of this message.'
 +  338 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a43530 -- stdout: ''
 +  338 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a43530 -- stdout: 'Note: Local timezone is +0200 (CEST)'
 +  338 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a43530 -- stdout: ''
 +  338 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a43530 -- stdout: 'Lines containing failures of 2001:db8::1 (max 2)'
 +  338 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a43530 -- stdout: ''
 +  338 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a43530 -- stdout: '... | mail -s Hostname: test-host, family: inet6 - Abuse from 2001:db8::1 abuse-1@abuse-test-server abuse-2@abuse-test-server'
 +  338 7F74BA2F9700 fail2ban.utils            DEBUG 1d63a43530 -- returned successfully 0
 0.021s -- ok

----------------------------------------------------------------------
Ran 1 test in 0.021s

**Comment by sebres** [comment]
Seems to work (at least in the testcase by testing jail "j-mail-whois-lines") - the subject looks like:
```
[Fail2Ban] j-mail-whois-lines: banned 87.142.124.10 from zeus.marktompkins.me root
```

No idea why it does not work in running fail2ban-server...

Broken or not completed installation?

**Comment by mtompkins** [comment]
Everything else seems ok - couldn't say easily. When time allows I'll try a "new" install and copy the `*.local` files and see if that corrects it and update.

**Comment by sebres** [comment]
> [Fail2Ban] apache-invalidscheme: started on `<fq-hostname>`

Now understood: this is actionstart, still no ticket resp. ban there. Currently implemented for actionban/actionunban only, thus a bug.

Fix follows later... Thanks!

**Comment by mtompkins** [comment]
Awesome - thanks for update/info. I appreciate your effort - such a useful solution.

**Comment by sebres** [comment]
Easy fix (and already test-covered), thus d1de20d committed directly to trunk's (0.10, merged to 0.11)

**Comment by xoroz** [comment]
i get this same problem on a fresh ubuntu 20 install
ubuntu20template:~# python -c 'from fail2ban.server.ipdns import DNSUtils; print("fq: %s, sh: %s" % (DNSUtils.getHostname(fqdn=True), DNSUtils.getHostname(fqdn=False)))'
fq: localhost, sh: ubuntu20template

how can I fix it?

**Comment by sebres** [comment]
Looks like your host configuration may be not quite valid. 
What do you see with `hostname -f`? If it also returns localhost, see https://stackoverflow.com/questions/19173962/hostname-f-returns-localhost/19175419 .
