### ISSUE TITLE
[Question] Proper way of upgrading

### ISSUE THREAD

**Issue by matteocontrini** [fail2ban/fail2ban#1860]
I currently have fail2ban 0.9.3 installed on some Ubuntu 16.04 systems through apt-get, and I'd like to upgrade fail2ban to 0.9.7. What's the correct way for upgrading, given that newer versions aren't available through apt?
Should I just run `python setup.py install` with the newer release, or should I first uninstall the Ubuntu package and then install manually with that Python command?

**Comment by sebres** [comment]
You should firstly uninstall the package from distribution, but ...
Before I would have to save the original configuration `/etc/fail2ban` (to compare resp. to find hereafter some distribution-related configs) as well as the original `fail2ban.service` resp. `init-d`-script (Note also that setup.py does not install this, you should do it manually).
