### ISSUE TITLE
Conflict during removal of nftables-allports when used in more than one jail

### ISSUE THREAD

**Issue by leak** [fail2ban/fail2ban#1861]
I'm not quite sure if this is actually an error or just misconfiguration on my side, if so, please do enlighten me.

### Environment:
- net-analyzer/fail2ban-0.9.7::gentoo
- Gentoo  default/linux/amd64/13.0
- [x] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

When using nftables-allports in two different jails there is a conflict during stopping fail2ban (see log below)

```
table ip fail2ban {
        set f2b-default {
                type ipv4_addr
                elements = { 116.31.116.24}
        }

        chain input {
                type filter hook input priority 100; policy accept;
                ip protocol tcp ip saddr @f2b-default drop
                ip protocol tcp ip saddr @f2b-default drop
        }
}
```

During startup the `ip protocol tcp ip saddr @f2b-default drop` gets added twice, once per jail. This causes a conflict during stopping.

#### Steps to reproduce
Configure two jails with nftables-allports

#### Expected behavior
`ip protocol tcp ip saddr @f2b-default drop` should be added only once, no matter how many jails use the `nftables-allports` action. Additionally I believe during stopping the nftables-allports injections should just be removed once and not per invidiual jail.

#### Observed behavior
Errors during stopping (see below). It does stop cleanly though and the nft table is completely empty at the end.

#### Any customizations done to /etc/fail2ban/ configuration
```
[DEFAULT]
ignoreip = 127.0.0.1/8
chain    = input
backend  = auto

[sshd]
enabled  = true
filter   = sshd
logpath  = /var/log/sshd
maxretry = 4
bantime  = 900
action   = nftables-allports

[postfix]
enabled  = true
filter   = postfix
logpath  = /var/log/postfix
maxretry = 6
findtime  = 60
bantime  = 3600
action   = nftables-allports
```

#### Relevant parts of /var/log/fail2ban.log file:
```
Aug 13 17:22:25 mail fail2ban.action[2015]: ERROR HANDLE_ID=$(nft --handle --numeric list chain ip fail2ban input | grep -m1 'ip saddr @f2b-default drop # handle' | grep -oe ' handle [0-9]*')
nft delete rule ip fail2ban input $HANDLE_ID
nft delete set ip fail2ban f2b-default -- stdout: ''
Aug 13 17:22:25 mail fail2ban.action[2015]: ERROR HANDLE_ID=$(nft --handle --numeric list chain ip fail2ban input | grep -m1 'ip saddr @f2b-default drop # handle' | grep -oe ' handle [0-9]*')
nft delete rule ip fail2ban input $HANDLE_ID
nft delete set ip fail2ban f2b-default -- stderr: '<cmdline>:1:1-35: Error: Could not process rule: Device or resource busy\ndelete set ip fail2ban f2b-default\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n'
Aug 13 17:22:25 mail fail2ban.action[2015]: ERROR HANDLE_ID=$(nft --handle --numeric list chain ip fail2ban input | grep -m1 'ip saddr @f2b-default drop # handle' | grep -oe ' handle [0-9]*')
nft delete rule ip fail2ban input $HANDLE_ID
nft delete set ip fail2ban f2b-default -- returned 1
Aug 13 17:22:25 mail fail2ban.actions[2015]: ERROR Failed to stop jail 'postfix' action 'nftables-allports': Error stopping action
```

**Comment by sebres** [comment]
Looks like the jail `name` does not supplied to the action, thus still f2b-default for all chains.
You should rather use banaction instead of action:
```diff
-action = nftables-allports
+banaction = nftables-allports
```
or if action, then with all expected parameters, like here:
```
action = nftables-allports[name=%(__name__)s, port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]```

**Comment by leak** [comment]
````
[DEFAULT]
action   = nftables-allports[name=%(__name__)s]
````

This actually did the trick for me, thank you a lot for the pointers.
