### ISSUE TITLE
pfctl -f

### ISSUE THREAD

**Issue by distler** [fail2ban/fail2ban#1863]
Fail2ban 0.10.x revamps the behaviour of the `pf` firewall (in `action.d/pf.conf`). While it's a commendable effort to improve the flexibility of the pf support, the current implementation has a fatal flaw: it makes extensive use of the command `pfctl -f`. This has the unfortunate effect of:

* wiping out all previously-existing firewall rules (leaving the unsuspecting user wide-open and vulnerable).
* even stomping on the firewall rules created by fail2ban itself: if `jail.d/a.local` and `jail.b/b.local` both invoke the `pf` action, the invocation of the second will wipe out the firewall rules created by the invocation of the first.

The only solution (as best as I can see) is to replace "`pfctl ...`" by "`pfctl -a f2b/<name> ...` everywhere in `action.d/pf.conf` (and then, in the main pf ruleset have an

```
anchor f2b {
  name1
  name2
  ...
}
```

This will load the dynamically-created rules produced by fail2ban, while preventing them from stomping on each other or on pre-existing rulesets.

**Comment by sebres** [comment]
I'm not very familiar with PF, thus just couple of thoughts by the way...

> it makes extensive use of the command `pfctl -f`

This will be called once on start (resp. by the first ban) and once on stop of the jail. You call that extensive?

> wiping out all previously-existing firewall rules

Why pipe of new table and block proto rules to `pfctl -f-` should flush any existing rules? (I found no documentation about such behavior).

> the invocation of the second will wipe out the firewall rules created by the invocation of the first.

Are you sure that you specified `banaction = pf` and not `action = pf`?
Because if you touch parameter action, all other parameters configured in `jail.conf` (inclusively name of jail) will be not supplied to the action, resp. you should do it explicit. Thus:
```diff
[jail]
- action = pf
+ banaction = pf
+ # or:
+ #action = pf[name=%(__name__)s, port="%(port)s", protocol="%(protocol)s", chain="%(chain)s", ...]
```

@koeppea Any ideas resp. objections?

**Comment by distler** [comment]
>This will be called once on start (resp. by the first ban) and once on stop of the jail. You call that extensive?

Yes, because each such invocation will wipe out all existing firewall rules (at the moment of invocation).

>Why pipe of new table and block proto rules to pfctl -f- should flush any existing rules? (I found no documentation about such behavior).

Because *that's what `pfctl -f` **does***. Read the [manpage](http://man.openbsd.org/pfctl.8).

>Are you sure that you specified `banaction = pf` and not `action = pf`?
Because if you touch parameter action, all other parameters configured in jail.conf (inclusively name of jail) will be not supplied to the action, resp. you should do it explicit.

Ah. Now I see.

Previously, neither the `name` or `port` parameter  was *required* in order for the `pf` action to function properly. Now they *are* required. Hence, whereas `action = pf` worked before, now it doesn't. `banaction = pf` would be gentler. But, curiously, the `protocol` parameter is preserved (despite what you say):
```
action   = pf[port={80 443}, name=http]
```
yields the firewall rules
```
% pfctl -a f2b/http -s rules
No ALTQ support in kernel
ALTQ related functions disabled
block drop proto tcp from <f2b-http> to any port = 80
block drop proto tcp from <f2b-http> to any port = 443
```

**Comment by sebres** [comment]
@distler Would you like to contribute? I mean to create a PR (for 0.10th branch) for the anchoring via `pfctl -a f2b/<name>`?

@fail2ban/maintainers Any suggestions?

**Comment by distler** [comment]
>  I mean to create a PR...

If that's desired, I certainly could.

But, really, the change can be succinctly summarized as
```
  s/pfctl/pfctl -a f2b\/<name>/g
```
which hardly seems to merit a PR.

**Comment by sebres** [comment]
Why `-a f2b\/<name>/g` and not just a `-a f2b/<name>` (without escape of `/` and `g`)?

Belong it only to actionstart/actionstop (so for lines contains `-f-` only)? Or also for other values like actionban, etc?

**Comment by koeppea** [comment]
@distler so if I understand you correctly that the issue is, that `actionstart` flushes your existing rules?

**Comment by sebres** [comment]
@koeppea Welcome back, long time no hear :)

**Comment by koeppea** [comment]
> Why -a f2b\/<name>/g and not just a -a f2b/<name> (without escape of / and g)?
> 

Because `/` is the separator for the substitute command, hence need to be escaped. `/g` is just the final separator for the substitute command with the repeat flag set.

> Belong it only to actionstart/actionstop (so for lines contains -f- only)? Or also for other values like actionban, etc?
> 

All calls. -a creates an own anchor used for *f2b* so that all the calls leave other and the default anchor untouched.

**Comment by distler** [comment]
>@distler so if I understand you correctly that the issue is, that actionstart flushes your existing rules?

It flushes my existing (prior to launching fail2ban) firewall rules *and* any rules set by other jails (which ran previously).

The first is a *major* issue, the second a minor one. Solving both requires nested anchors, i.e `f2b/<name>`, so that each jail's rules are isolated from each other and from the main pf ruleset.

**Comment by koeppea** [comment]
Thanks @distler. This is exactly what we want to address with #1866.
Would you be able to test this pull request?

**Comment by distler** [comment]
> Would you be able to test this pull request?

I can, with the caveats that:

1. I am on MacOSX, not FreeBSD.
2. The tests, on that platform, don't run clean on 0.10.0 (5 failures and 1 error). They do run with no failures and 1 error on 0.9.7.
3. I'm not familiar enough with your software, or your test framework, to offer any help in debugging the failures.

Applying your patches to 0.10.0 and rerunning the tests introduces *no* failures or errors that weren't there before. So I would call that a "success."

The error (in `fail2ban/tests/misctestcase.py`) is a fairly stupid one: `/usr/local/bin` doesn't seem to be in the PATH when `_sh_call()` is invoked.

For what it's worth, here is the output of running the tests, with your PR applied (actually, identical to the output on a stock 0.10.0):
```
% bin/fail2ban-testcases
Fail2ban 0.10.0 test suite. Python 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]. Please wait...
........................s.......................F................F........F.......................................................................s................fail2ban-python: realpath couldn't resolve "/usr/bin/fail2ban-python"
E......................................................F.......................F..................................................................................................................
......................................................s..
======================================================================
ERROR: testSetupInstallRoot (fail2ban.tests.misctestcase.SetupTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/misctestcase.py", line 98, in setUp
    sysVer = _getSysPythonVersion()
  File "./fail2ban/tests/misctestcase.py", line 83, in _getSysPythonVersion
    return _sh_call("fail2ban-python -c 'import sys; print(tuple(sys.version_info))'")
  File "./fail2ban/tests/misctestcase.py", line 74, in _sh_call
    ret = subprocess.check_output(cmd, shell=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'fail2ban-python -c 'import sys; print(tuple(sys.version_info))'' returned non-zero exit status 1

======================================================================
FAIL: testComplexMailActionMultiLog (fail2ban.tests.servertestcase.ServerConfigReaderTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/servertestcase.py", line 1852, in testComplexMailActionMultiLog
    self.assertLogged(*tests[test], all=True)
  File "./fail2ban/tests/utils.py", line 687, in assertLogged
    self.fail("%r was not found in the log: ===\n%s===" % (s_, logged))
AssertionError: 'testcase01a.log:Dec 31 11:55:01 [sshd] error: PAM: Authentication failure for test from 87.142.124.10' was not found in the log: ===
===== # === ip4-ban === =====
( printf %b "Hi,\n
The IP 87.142.124.10 has just been banned by Fail2Ban after
100 attempts against j-mail-whois-lines.\n\n
Here is more information about 87.142.124.10 :\n"
echo '-- information about 87.142.124.10 --';
printf %b "\nLines containing failures of 87.142.124.10 (max 2)\n";
logpath="./fail2ban/tests/files/testcase01.log
         ./fail2ban/tests/files/testcase01a.log"; grep -m 1 -E "(^|[^0-9a-fA-F:])$(echo '87.142.124.10' | sed 's/\./\\./g')([^0-9a-fA-F:]|$)" $logpath | tail -n 2;
printf %b "\n
Regards,\n
Fail2Ban" ) | cat; printf "\n... | "; echo mail  -s "[Fail2Ban] j-mail-whois-lines: banned 87.142.124.10 from tin-can.local" root
7f8586cd5940 -- stdout: 'Hi,'
7f8586cd5940 -- stdout: ''
7f8586cd5940 -- stdout: 'The IP 87.142.124.10 has just been banned by Fail2Ban after'
7f8586cd5940 -- stdout: '100 attempts against j-mail-whois-lines.'
7f8586cd5940 -- stdout: ''
7f8586cd5940 -- stdout: ''
7f8586cd5940 -- stdout: 'Here is more information about 87.142.124.10 :'
7f8586cd5940 -- stdout: '-- information about 87.142.124.10 --'
7f8586cd5940 -- stdout: ''
7f8586cd5940 -- stdout: 'Lines containing failures of 87.142.124.10 (max 2)'
7f8586cd5940 -- stdout: './fail2ban/tests/files/testcase01.log:Dec 31 11:59:59 [sshd] error: PAM: Authentication failure for kevin from 87.142.124.10'
7f8586cd5940 -- stdout: ''
7f8586cd5940 -- stdout: ''
7f8586cd5940 -- stdout: 'Regards,'
7f8586cd5940 -- stdout: ''
7f8586cd5940 -- stdout: 'Fail2Ban'
7f8586cd5940 -- stdout: '... | mail -s [Fail2Ban] j-mail-whois-lines: banned 87.142.124.10 from tin-can.local root'
7f8586cd5940 -- returned successfully 0
===

======================================================================
FAIL: testExecuteWithVars (fail2ban.tests.actiontestcase.CommandActionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/actiontestcase.py", line 407, in testExecuteWithVars
    ' -- `Very | very $(bad & worst hacker)` --', all=True)
  File "./fail2ban/tests/utils.py", line 687, in assertLogged
    self.fail("%r was not found in the log: ===\n%s===" % (s_, logged))
AssertionError: ' -- `Very | very $(bad & worst hacker)` --' was not found in the log: ===
Created <class 'fail2ban.server.action.CommandAction'>
printf %b "foreign input:\n -- $f2bV_A --\n -- $f2bV_B --\n -- $(echo -n $f2bV_C) --"
102bb3758 -- stdout: 'foreign input:'
102bb3758 -- stdout: " -- I'm a hacker; && $(echo $f2bV_B) --"
102bb3758 -- stdout: ' -- I"m very bad hacker --'
102bb3758 -- stdout: ' -- -n `Very | very $(bad & worst hacker)` --'
102bb3758 -- returned successfully 0
===

======================================================================
FAIL: testActionsOutput (fail2ban.tests.actionstestcase.ExecuteActions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/actionstestcase.py", line 85, in testActionsOutput
    self.assertTrue( Utils.wait_for(lambda: (f.read() == "ip start 64\n"), 3) )
AssertionError: False is not true

======================================================================
FAIL: testIgnoreCmdApacheFakegooglebot (fail2ban.tests.filtertestcase.IgnoreIPDNS)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/filtertestcase.py", line 463, in testIgnoreCmdApacheFakegooglebot
    self.assertTrue(self.filter.inIgnoreIPList(str(ip)), "test of googlebot ip %s failed" % ip)
AssertionError: test of googlebot ip 66.249.66.1 failed

======================================================================
FAIL: testIPAddr_CIDR (fail2ban.tests.filtertestcase.DNSUtilsNetworkTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/filtertestcase.py", line 1826, in testIPAddr_CIDR
    self.assertEqual(str(IPAddr('2606:2800:220:1:248:1893:25c8::', 120)), '2606:2800:220:1:248:1893:25c8:0/120')
AssertionError: '2606:2800:220:1:248:1893:25c8::/120' != '2606:2800:220:1:248:1893:25c8:0/120'

----------------------------------------------------------------------
Ran 414 tests in 127.181s

FAILED (failures=5, errors=1, skipped=3)
```

**Comment by sebres** [comment]
> Applying your patches to 0.10.0 and rerunning the tests introduces no failures or errors that weren't there before. So I would call that a "success."

Great news... Thanks! Thus will merge...

What's about the test-cases:
- the test cases (covering the mentioned PR) are anyway artificial (just mock-up, do not really something just echoing);
- all test cases can run only on the clean-copy (without making any adjustments on configs, creating .local files, etc).
- but possibly some platform-specified changes (or even rewritten cases) expected to run the whole test-suite flawless.

**Comment by distler** [comment]
>Great news... Thanks! Thus will merge...

Thank you!

>the test cases (covering the mentioned PR) are anyway artificial (just mock-up, do not really something just echoing);

Well, I can add that I am running the new code in production on three different machines and it does do what it's supposed to (without disabling my firewall).

The only thing I notice that's amiss (i.e., which didn't occur  in 0.9.7) is a bunch of warnings on my laptop

```
2017-08-16 10:45:44,456 fail2ban.ipdns          [134]: WARNING Unable to find a corresponding IP address for tin-can.local: [Errno 8] nodename nor servname provided, or not known
```

when running on a private LAN (192.168.*.*). Not really a serious issue...
