### ISSUE TITLE
Failed to open fail2ban service

### ISSUE THREAD

**Issue by redapple0204** [fail2ban/fail2ban#1870]
Hello 
When I tried to start the fail2ban service, I got an error.
> * Restarting authentication failure monitor fail2ban                           ERROR  No file(s) found for glob /var/log/secure
ERROR  Failed during configuration: Have not found any log file for ssh-iptables jail

How can I do?
Thanks for your help.

**Comment by sebres** [comment]
You've a jail `ssh-iptables` in your `jail.local` (jail.conf)...
This jail observes `/var/log/secure` corresponding setting `logpath`, this is not available (resp. not accessible for user fail2ban running).
Either you should specify another logpath for this jail, or disable this jail if not needed.
If this file was deleted by logrotate, you should adjust logrotate-setting for it to recreate an empty file after logrotate.

For more info, see [our wiki](https://github.com/fail2ban/fail2ban/wiki/Properly-fail2ban-configuration), how you can configure fail2ban.
