### ISSUE TITLE
maintenance release?

### ISSUE THREAD

**Issue by qcybb** [fail2ban/fail2ban#1875]
Is there any chance we'll see a 0.10.1 maintenance release sometime on the near future?

There are quite a few fixes that have been addressed, and I would like to get an official release so it can be uploaded to the FreeBSD ports system. The 0.10 release right now floods the fail2ban.log with all sorts of errors (which have been fixed in the latest commits) and will not be accepted until it's sorted out.

It really needs to be an official release before it will be accepted on the ports system.

**Comment by sebres** [comment]
>  floods the fail2ban.log with all sorts of errors

Could you supply an example?
If I look [here](https://github.com/fail2ban/fail2ban/compare/0.10.0...0.10), I see there no critical fix (that cannot be resolved via configuration, possibly excepting the action `pf`)

> Is there any chance we'll see a 0.10.1 maintenance release sometime on the near future?
> It really needs to be an official release before it will be accepted on the ports system.

It was although not planed so shortly after last 0.10 release... But we are open to listen any arguments, why it should be necessarily released. 
Note that the reason like "shifting responsibility" will be definitively not accepted (particularly for software contains "without any warranty" in the license).
Especially interresting the answer for question: if current 0.10 branch is too fresh for maintainers of FreeBSD to update their packet, why it should be not "too fresh" if it will be released from us forcibly?
Thus why they cannot pick it up into their distribution as a patch?

P.S. I close the issue (as not really an issue), just to hold the issue-tracker clean, but leave still open for further discussions...

**Comment by sebres** [comment]
Did you mean "Retrieving own IPs" from #1865?

**Comment by qcybb** [comment]
on FreeBSD, the error logs are **flooded** with these message using 0.10

> 2017-08-15 12:04:18,637 fail2ban.ipdns [90363]: WARNING Retrieving own IPs of localhost failed: inet_pton() argument 2 must be string, not int

2017-08-16 00:00:00,079 fail2ban.filterpyinotify[5012]: ERROR rm_watch: cannot remove WD=2, Errno=Invalid argument (EINVAL)

**Comment by sebres** [comment]
So yes, first one was fixed in 786722814682a7279314505ad2a1602e52e997c8 (why it alone could not be picked as patch?)

And the second message ocurred only by log-rotate (right?), but although it is not really an error (this message writes logger from pyinotify module), neither it floods (causes one time per day?), nor something was "fixed" in this direction... 
Commit e5169d8f8421b3736c4610ad84c3953596b6d4b3 does not really resolve this (rather it was made precautionary for possible unhandled errors).

**Comment by qcybb** [comment]
Yes, the second error happens during log rotate.

I believe the first error issue was picked up as a patch, but there is still this second error message issue to deal with. With that said, it's not being accepted on to the ports system the way the release stands right now.

Surely other distros (Linux) are having these issue as well? That's why I was asking for a maintenance release, then no one has to mess with patches to fix these issues.

**Comment by sebres** [comment]
Well, then we should firstly find the way to "fix" this second problem, because as already said it is currently not yet resolved.
I had already [asked you](https://github.com/fail2ban/fail2ban/issues/1865#issuecomment-322711305) how exactly this log will be rotated (file- or directory-based)?...

**Comment by qcybb** [comment]
Sorry, I missed that. The log is file-based rotated.

``rotate  /var/log/fail2ban.log  to  /var/log/fail2ban.log.0.bz2``

**Comment by qcybb** [comment]
I just want to clarify that this error happens when rotating the maillog file, not fail2ban.log - not sure if that makes any difference or not.

> 2017-08-17 00:00:00,031 fail2ban.filterpyinotify[20591]: ERROR rm_watch: cannot remove WD=2, Errno=Invalid argument (EINVAL)
>  2017-08-17 00:00:00,031 fail2ban.filterpyinotify[20591]: DEBUG New <Watch wd=3 path=/var/log/maillog mask=2 proc_fun=None auto_add=False exclude_filter=<function at 0x803959aa0> dir=False >

> watching /var/log/maillog
> rotate /var/log/maillog to /var/log/maillog.0.bz2

**Comment by qcybb** [comment]
With the patch for the issue below now complete, can we expect a maintenance release?

https://github.com/fail2ban/fail2ban/issues/1865

**Comment by sebres** [comment]
yes, you can :)

**Comment by qcybb** [comment]
Thank you! :)

**Comment by sebres** [comment]
Here you go... [releases/0.10.1](https://github.com/fail2ban/fail2ban/releases/tag/0.10.1)

**Comment by qcybb** [comment]
This was a nice surprise to wake up to this morning - thank you!

**Comment by qcybb** [comment]
Just wanted to give you a heads up that the new 10.1 version is working perfectly.  No more warnings or error messages when logs get rotated. Thanks again!
