### ISSUE TITLE
Log format setting

### ISSUE THREAD

**Issue by IdleGandalf** [fail2ban/fail2ban#1876]
Currently running 0.10, but I think its the same with 0.9.x.

When logging to file the current log format is all fine, but if you decide to redirect fail2ban log to systemd-journal it becomes quite a mess:

```
Aug 27 04:22:42 example.host.fqdn fail2ban-server[12655]: 2017-08-27 04:22:42,625 fail2ban.actions        [12655]: NOTICE  [sshd] Restore Ban X.X.X.X
```

Is it possible to change the log format somewhere in fail2ban.conf where I missed it or is it just not possible at the moment?

**Comment by sebres** [comment]
> if you decide to redirect fail2ban log to systemd-journal

How you did it? (Running as systemd unit and logging to stdout?)...

> Is it possible to change the log format...

Unfortunately it's impossible currently.

Just as link - #1403

**Comment by IdleGandalf** [comment]
Oh right. Yes its runs as unit with log to stdout. 

If the linked pr would get merged I assume that this wouldn't be a huge problem.

**Comment by ygoe** [comment]
This is an old issue but it's the closest I could find. @ghost asked about the "verbose" log line format and explained it with usage in journal. I'm doing the same now. The SYSOUT log method is already much better but there's still room for improvement. For example, the process ID is redundant, and the "fail2ban." prefix is also unnecessary. Removing these would make the log lines shorter and thus easier to read.

As to the log format, @sebres, you just said it's impossible currently. Can I take that for a "won't fix"? Or was this issue accidently closed after there was a partial implementation of the improvement?

Also, it seems that log priorities are not properly passed to syslog/journal. I have lines with "INFO" and "NOTICE" but both have the info priority set.

**Comment by sebres** [comment]
> For example, the process ID is redundant, and the "fail2ban." prefix is also unnecessary.

Hmm... normally it should not have redundant info if sysout log-target is used.
Can you provide an example excerpt of journalctl?

> Can I take that for a "won't fix"?...

The issue has been closed automatically as 4fa0f48fa151dcf76ca6e8af138a4e2b0be2fb2e got merged.

Also note there is also a PR #1403 which implements logging to systemd-journal via handler. Maybe we should indeed continue that.

**Comment by ygoe** [comment]
Here's some recent output in journal:

```
Nov 28 18:00:55 df-db1 systemd[1]: Started Fail2Ban Service.
Nov 28 18:00:56 df-db1 fail2ban-server[5773]: fail2ban.server         [5773]: INFO    --------------------------------------------------
Nov 28 18:00:56 df-db1 fail2ban-server[5773]: fail2ban.server         [5773]: INFO    Starting Fail2ban v0.10.2
Nov 28 18:00:56 df-db1 fail2ban-server[5773]: fail2ban.database       [5773]: INFO    Connected to fail2ban persistent database '/var/lib/fail2ban/fail2ban.sqlite3'
Nov 28 18:00:56 df-db1 fail2ban-server[5773]: fail2ban.jail           [5773]: INFO    Creating new jail 'sshd'
Nov 28 18:00:56 df-db1 fail2ban-server[5773]: fail2ban.jail           [5773]: INFO    Jail 'sshd' uses systemd {}
Nov 28 18:00:56 df-db1 fail2ban-server[5773]: fail2ban.jail           [5773]: INFO    Initiated 'systemd' backend
Nov 28 18:00:56 df-db1 fail2ban-server[5773]: fail2ban.filter         [5773]: INFO      maxLines: 1
Nov 28 18:00:56 df-db1 fail2ban-server[5773]: fail2ban.filtersystemd  [5773]: INFO    [sshd] Added journal match for: '_SYSTEMD_UNIT=sshd.service + _COMM=sshd'
Nov 28 18:00:56 df-db1 fail2ban-server[5773]: fail2ban.filter         [5773]: INFO      encoding: UTF-8
Nov 28 18:00:56 df-db1 fail2ban-server[5773]: fail2ban.filter         [5773]: INFO      maxRetry: 5
Nov 28 18:00:56 df-db1 fail2ban-server[5773]: fail2ban.filter         [5773]: INFO      findtime: 600
Nov 28 18:00:56 df-db1 fail2ban-server[5773]: fail2ban.actions        [5773]: INFO      banTime: 3600
Nov 28 18:00:56 df-db1 fail2ban-server[5773]: fail2ban.filter         [5773]: INFO    [sshd] Found 103.125.191.106 - 2019-11-28 17:56:19
Nov 28 18:00:56 df-db1 fail2ban-server[5773]: fail2ban.jail           [5773]: INFO    Jail 'sshd' started
Nov 28 18:00:56 df-db1 fail2ban-server[5773]: fail2ban.filter         [5773]: INFO    [sshd] Found 103.125.191.106 - 2019-11-28 17:56:19
Nov 28 18:00:56 df-db1 fail2ban-server[5773]: fail2ban.filter         [5773]: INFO    [sshd] Found 103.125.191.106 - 2019-11-28 17:56:21
Nov 28 18:00:56 df-db1 fail2ban-server[5773]: fail2ban.filter         [5773]: INFO    [sshd] Found 103.125.191.106 - 2019-11-28 17:56:21
Nov 28 18:00:56 df-db1 fail2ban-server[5773]: fail2ban.filter         [5773]: INFO    [sshd] Found 103.125.191.106 - 2019-11-28 17:56:24
Nov 28 18:00:56 df-db1 fail2ban-server[5773]: fail2ban.filter         [5773]: INFO    [sshd] Found 103.125.191.106 - 2019-11-28 17:56:26
Nov 28 18:00:56 df-db1 fail2ban-server[5773]: Server ready
Nov 28 18:00:56 df-db1 fail2ban-server[5773]: fail2ban.actions        [5773]: NOTICE  [sshd] Restore Ban 103.125.191.106
Nov 28 18:00:56 df-db1 fail2ban-server[5773]: fail2ban.actions        [5773]: NOTICE  [sshd] Restore Ban 187.1.57.210
Nov 28 18:19:03 df-db1 fail2ban-server[5773]: fail2ban.actions        [5773]: NOTICE  [sshd] Unban 187.1.57.210
Nov 28 18:19:45 df-db1 fail2ban-server[5773]: fail2ban.filter         [5773]: INFO    [sshd] Found 187.1.57.210 - 2019-11-28 18:19:45
Nov 28 18:19:48 df-db1 fail2ban-server[5773]: fail2ban.filter         [5773]: INFO    [sshd] Found 187.1.57.210 - 2019-11-28 18:19:47
Nov 28 18:25:36 df-db1 fail2ban-server[5773]: fail2ban.filter         [5773]: INFO    [sshd] Found 187.1.57.210 - 2019-11-28 18:25:36
Nov 28 18:25:36 df-db1 fail2ban-server[5773]: fail2ban.filter         [5773]: INFO    [sshd] Found 187.1.57.210 - 2019-11-28 18:25:36
Nov 28 18:25:38 df-db1 fail2ban-server[5773]: fail2ban.filter         [5773]: INFO    [sshd] Found 187.1.57.210 - 2019-11-28 18:25:37
Nov 28 18:25:38 df-db1 fail2ban-server[5773]: fail2ban.actions        [5773]: NOTICE  [sshd] Ban 187.1.57.210
```

**Comment by ygoe** [comment]
Even if an output method specifically for journald seems nice, I'm not sure if that's absolutely necessary. The SYSOUT method is intended to be used with some form of syslog, right? Every syslog already shows the service name and PID. So the message format for SYSOUT could just be reduced by these parts.

A real advantage would still be the correct priority though. That can be colour-highlighted with journal, which normal stdout-to-syslog can't do.

**Comment by sebres** [comment]
As for PID ([5773]) sure, we can do that.
As for "fail2ban." prefix... Well, it is the name of pythons module the message was logged from. So I'm still not sure it should be removed per default.

Also since I implemented #1989 (v.0.10.2), you can specify your own format for the log...
So if you would use something like `sysout[format="%(levelname)-7s %(message)s"]` instead of `sysout`, you'd overwrite default logging format (e. g. only `NOTICE  [sshd] Ban 187.1.57.210` going to journal in this case).

**Comment by ygoe** [comment]
> ERROR: bad interpolation variable reference '%(levelname)-7s %(message)s"]'

> ERROR: bad interpolation variable reference '%(levelname) %(message)s"]'

That format doesn't seem to be correct. And I couldn't fix it myself by reading your merged diff. Is there a documentation about the possible formats somewhere? Or are they buried in the depth of the internal data structures?

**Comment by sebres** [comment]
> That format doesn't seem to be correct.

Nope.
Of course it is correct only if supplying via command line with option `--logtarget`, e. g. in service file, like in this commit:
https://github.com/fail2ban/fail2ban/blob/4fa0f48fa151dcf76ca6e8af138a4e2b0be2fb2e/files/fail2ban.service.in#L12

If you want to provide it in `fail2ban.conf` (which is python's config file), you have to escape `%` as dual percent `%%`, because otherwise trying to interpolate this as config variables (which are bad) resulting in substitution error.

So this should work in `fail2ban.conf`:
```ini
logtarget = sysout[format="%%(levelname)-7s %%(message)s"]
```

**Comment by ygoe** [comment]
Nice. This is what I get now:

```
11-29 21:50:27.975 systemd │ Starting Fail2Ban Service...
11-29 21:50:27.977 systemd │ Started Fail2Ban Service.
11-29 21:50:28.074 fail2ban-server│ %(message)s
11-29 21:50:28.074 fail2ban-server│ %(message)s
11-29 21:50:28.079 fail2ban-server│ %(message)s
11-29 21:50:28.081 fail2ban-server│ %(message)s
11-29 21:50:28.094 fail2ban-server│ %(message)s
11-29 21:50:28.094 fail2ban-server│ %(message)s
11-29 21:50:28.095 fail2ban-server│ %(message)s
11-29 21:50:28.111 fail2ban-server│ %(message)s
11-29 21:50:28.112 fail2ban-server│ %(message)s
11-29 21:50:28.112 fail2ban-server│ %(message)s
11-29 21:50:28.112 fail2ban-server│ %(message)s
11-29 21:50:28.112 fail2ban-server│ %(message)s
11-29 21:50:28.116 fail2ban-server│ %(message)s
11-29 21:50:28.116 fail2ban-server│ %(message)s
11-29 21:50:28.116 fail2ban-server│ %(message)s
11-29 21:50:28.117 fail2ban-server│ %(message)s
11-29 21:50:28.117 fail2ban-server│ %(message)s
11-29 21:50:28.117 fail2ban-server│ %(message)s
11-29 21:50:28.118 fail2ban-server│ Server ready
11-29 21:50:28.118 fail2ban-server│ %(message)s
11-29 21:50:28.314 fail2ban-server│ %(message)s
```

**Comment by sebres** [comment]
Hmm... I never used it from config file. Looks like a bug...
You could try it from service (and/or command line, of course using single `%` char there).

**Comment by ygoe** [comment]
Sorry, I edited my comment, see above.

**Comment by sebres** [comment]
> Is the now-missing first part (fail2ban.actions, fail2ban.database etc.) of any importance to the user?

Sure, it can be. For example in case of some error without traceback (call stack) one could at least see where it's occurred. 
We could think about to trim the prefix `fail2ban.`...
But also backwards compatibility can be important - there are for example some filters parsing fail2ban.log, like `recidive` (which we can rewrite, but not the filters of users;).

How about implementation of some new option, like `short`?
```ini
logtarget = sysout[short=1]
```

**Comment by ygoe** [comment]
A "short" option would certainly make it easier to get this running. I'd use it if it contains a trimmed prefix, the levelname and message. :-) And as soon as the new option appears in the Ubuntu package. I'm currently setting up a box with 18.04 but will be migrating this and another server to 20.04 next year.

Another idea for a trimmed prefix would be to provide it as a separate field in the custom format, if that's possible.
