### ISSUE TITLE
ERROR: cannot import name 'mapTag2Opt'

### ISSUE THREAD

**Issue by rikmos** [fail2ban/fail2ban#1881]
_We will be very grateful, if your problem was described as completely as possible,
enclosing excerpts from logs (if possible within DEBUG mode, if no errors evident
within INFO mode), and configuration in particular of effected relevant settings
(e.g., with ` fail2ban-client -d | grep 'affected-jail-name' ` for a particular
jail troubleshooting).
Thank you in advance for the details, because such issues like "It does not work" 
alone could not help to resolve anything!
Thanks! (remove this paragraph and other comments upon reading)_

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

/etc/fail2ban # /etc/init.d/fail2ban start
fail2ban          | * Starting fail2ban ...
fail2ban          |ERROR: cannot import name 'mapTag2Opt'
fail2ban          | Init of command line failed
fail2ban          | * start-stop-daemon: failed to start `/usr/bin/fail2ban-client'
fail2ban          | * Failed to start fail2ban                                                                  [ !! ]
fail2ban          | * ERROR: fail2ban failed to start

#### Steps to reproduce
This was overtop 

do install from source files as per readme 

jail.conf
paths-common.conf
paths-gentoo.conf

#### Expected behavior
should start fail2ban after upgrade
#### Observed behavior
fails to start
#### Any additional information
should the DB sqllite3 be flushed ?
### Configuration, dump and another helpful excerpts
overtop of fail2ban-0.9.6
#### Any customizations done to /etc/fail2ban/ configuration
more fail2ban.conf 
[Definition]
loglevel = INFO
logtarget = /var/log/fail2ban.log
syslogsocket = auto
socket = /var/run/fail2ban/fail2ban.sock
pidfile = /var/run/fail2ban/fail2ban.pid
dbfile = /var/lib/fail2ban/fail2ban.sqlite3
dbpurgeage = 1d

more paths-common.conf
[INCLUDES]
after  = paths-gentoo.conf
[DEFAULT]
sshd_log = /var/log/auth.log
auditd_log = /var/log/audit.log
ignorecommands_dir = /etc/fail2ban/filter.d/ignorecommands

more paths-gentoo.conf 
# Debian
[INCLUDES]
before = paths-common.conf
[DEFAULT]
owncloud_log = /var/www/localhost/htdocs/NX/data/nextcloud.log 
named_security_log = /var/log/named/security.log
modsecurity_log = /var/log/apache2/modsec_audit_log
apache_ssl_access_log=/var/log/apache2/ssl_access_log
apache_access_log = /var/log/apache2/access_log
apache_error_log = /var/log/apache2/error_log
apache_ssl_error_log = /var/log/apache2/ssl_error_log
apache_agent_log = /var/log/apache2/ssl_agent_log
postfix_log =  /var/log/mail.log
syslog_mail = /var/log/mail.log
syslog_mail_warn = /var/log/mail.warn
syslog_authpriv = /var/log/auth.log
syslog_user  =  /var/log/user.log
syslog_daemon =  /var/log/daemon.log
syslog_local0 =  /var/log/messages

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
People, we've made an issue template not for nothing...
- f2b version? from what to what upgraded... please exactly as possible.
- distribution?
- can you start it via fail2ban-client instead of init.d?
- can you dump config with `fail2ban-client -d`? or the same error?

**Comment by rikmos** [comment]
0.9.6 > 0.10.6 
Gentoo , fail2ban from git source 
Not sure see below 
Sorry I had to revert I'll check again tonight

**Comment by sebres** [comment]
Note that our 0.10 does not install init.d nor the systems unit scripts... Thus this can be from your original distributed... Additionally the common release have not distribution related configs and paths... Thus can be installed into different path (like here https://github.com/fail2ban/fail2ban/issues/1524). This meant you could have used still old bin-scripts, but new python modules...

**Comment by rikmos** [comment]
I've installed 0.9.6 from git source (and 0.10.0 was done the same way), the init scripts and configs are mine by hand , I'll check the 0.10.0 installs path tonight and if it's correct turn-up the logs and -d

**Comment by sebres** [comment]
Please notify if issue still acute
