### ISSUE TITLE
Fail2ban after install

### ISSUE THREAD

**Issue by kenkit** [fail2ban/fail2ban#1892]
I'm using the default setting after installing via setup.py
Why is the default config files broken ?

```
 service fail2ban start
 * Starting authentication failure monitor fail2ban
WARNING Wrong value for 'loglevel' in 'Definition'. Using default one: '1'
WARNING 'logpath' not defined in 'INCLUDES'. Using default one: '/var/log/messages'
WARNING Wrong value for 'findtime' in 'INCLUDES'. Using default one: '600'
WARNING Wrong value for 'bantime' in 'INCLUDES'. Using default one: '600'
ERROR  Failed during configuration: Bad value substitution:
	section: [sshd]
	option : backend
	key    : default/backend
	rawval : 

   ...fail!
```

**Comment by sebres** [comment]
Fail2ban and OS versions?

The substitution `default/backend` used to interpolate a value of backend from default section (jail.conf).
I don't see something wrong there and I can't reproduce this, neither with current 0.10 nor with 0.11.

> after installing via setup.py

As mentioned in README, the system init/service script (as well as systemd service file) is not automatically installed. Thus I think you've both versions now (together with older one that still pointed from service).
If you want install our common version, you should ~know what you do~, sat least previously uninstall your distributed fail2ban package.
And after installing manually create init.d-script (resp. systemd unit file).

**Comment by kenkit** [comment]
Okay I removed previous fail2ban service script and installed the one for debian-init
the update-rc and it works.
Thanks for the hint
