### ISSUE TITLE
nftables action does not support ipv4 and ipv6 simultaneously

### ISSUE THREAD

**Issue by sbraz** [fail2ban/fail2ban#1893]
Hello,
I am running Fail2ban v0.10.0 and I have created a jail which uses `nftables-multiport` as `banaction`. This works fine for banning IPv4 addresses, however ipv6 addresses trigger a failure:
```
[17793]: Level 39 7fc76c084e40 -- exec: nft add element inet filter f2b-sshd \{ 2001:xxx \}
[17793]: ERROR   7fc76c084e40 -- stderr: '<cmdline>:1:36-60: Error: Could not resolve hostname: Address family for hostname not supported'                                                                            
```
I understand that this is because the nftables set is configured to contain  `ipv4_addr` as set [here](https://github.com/fail2ban/fail2ban/blob/fbd46f29f2d47954ab3507a9d2be993a86302379/config/action.d/nftables-common.conf#L73) but I don't see how I could make my action work for both IPv4 and IPv6.

I guess something can be worked out with `[Init?family=inet6]` but I am not exactly sure how. Perhaps @albel727 will be interesting in adding this feature?

**Comment by sbraz** [comment]
It's actually easier than I thought. I'll file a PR when I have time.
```diff
--- /etc/fail2banold/action.d/nftables-common.conf	2017-08-09 16:53:05.000000000 +0200
+++ nftables-common.conf	2017-09-11 13:06:06.486950721 +0200
@@ -28,11 +28,11 @@
 # Notes.:  command executed once at the start of Fail2Ban.
 # Values:  CMD
 #
-actionstart = <nftables> add set <nftables_family> <nftables_table> f2b-<name> \{ type <nftables_type>\; \}
-              <nftables> insert rule <nftables_family> <nftables_table> <chain> %(nftables_mode)s ip saddr @f2b-<name> <blocktype>
+actionstart = <nftables> add set <nftables_family> <nftables_table> <set_name> \{ type <nftables_type>\; \}
+              <nftables> insert rule <nftables_family> <nftables_table> <chain> %(nftables_mode)s <ip_version> saddr @<set_name> <blocktype>
 
 _nft_list = <nftables> --handle --numeric list chain <nftables_family> <nftables_table> <chain>
-_nft_get_handle_id = grep -m1 'ip saddr @f2b-<name> <blocktype> # handle' | grep -oe ' handle [0-9]*'
+_nft_get_handle_id = grep -m1 '<ip_version> saddr<ip_version> @<set_name> <blocktype> # handle' | grep -oe ' handle [0-9]*'
 
 # Option:  actionstop
 # Notes.:  command executed once at the end of Fail2Ban
@@ -40,13 +40,13 @@
 #
 actionstop = HANDLE_ID=$(%(_nft_list)s | %(_nft_get_handle_id)s)
              <nftables> delete rule <nftables_family> <nftables_table> <chain> $HANDLE_ID
-             <nftables> delete set <nftables_family> <nftables_table> f2b-<name>
+             <nftables> delete set <nftables_family> <nftables_table> <set_name>
 
 # Option:  actioncheck
 # Notes.:  command executed once before each actionban command
 # Values:  CMD
 #
-actioncheck = <nftables> list chain <nftables_family> <nftables_table> <chain> | grep -q '@f2b-<name>[ \t]'
+actioncheck = <nftables> list chain <nftables_family> <nftables_table> <chain> | grep -q '@<set_name>[ \t]'
 
 # Option:  actionban
 # Notes.:  command executed when banning an IP. Take care that the
@@ -54,7 +54,7 @@
 # Tags:    See jail.conf(5) man page
 # Values:  CMD
 #
-actionban = <nftables> add element <nftables_family> <nftables_table> f2b-<name> \{ <ip> \}
+actionban = <nftables> add element <nftables_family> <nftables_table> <set_name> \{ <ip> \}
 
 # Option:  actionunban
 # Notes.:  command executed when unbanning an IP. Take care that the
@@ -62,7 +62,7 @@
 # Tags:    See jail.conf(5) man page
 # Values:  CMD
 #
-actionunban = <nftables> delete element <nftables_family> <nftables_table> f2b-<name> \{ <ip> \}
+actionunban = <nftables> delete element <nftables_family> <nftables_table> <set_name> \{ <ip> \}
 
 [Init]
 
@@ -117,3 +117,11 @@
 # Notes.:  Actual command to be executed, including common to all calls options
 # Values:  STRING
 nftables = nft
+
+set_name = f2b-<name> 
+ip_version = ip
+
+[Init?family=inet6]
+nftables_type = ipv6_addr
+set_name = f2b-<name>6
+ip_version = ip6

```

**Comment by sebres** [comment]
Looks as proper solution... Thx!

**Comment by Cistoge** [comment]
Hello,

I was just reading about this (former) bug, because I have what I think is the same problem, "nftables action does not support ipv4 and ipv6 simultaneously". But I have the problem though I am already using the newest nftables action scripts and I wonder why you think that your solution is really a solution, because for me it seems not suitable for handling IPv4 and IPv6 simultaneously, but only as an either/or solution depending on a value "family" defined in the [Init] section.

Regards

**Comment by sebres** [comment]
Which version of fail2ban do you use?
As you can see #1894 is targeting fail2ban 0.10.
And since 0.10 fail2ban automatically does differentiates IPs family and uses values family-conditional (from corresponding section).

> it seems not suitable for handling IPv4 and IPv6 simultaneously,

If your version >= 0.10, which issue exactly do you have?

**Comment by Cistoge** [comment]
Ah ok, I read somewhere that I only have to update the nftables action scripts to get IPv6 support, but then that is not enough when using an older version.

**Comment by sebres** [comment]
Well indirectly it is true, so in case of older f2b-version, you should just use some custom action that could differentiate IP-families.
Note that fail2ban's command-actions could use all that what a posix-shell (or your default platform-shell) can use. 
So it could be something like:
```ini
...
actionstart = echo 'start IPv4'
              echo 'start IPv6'

actionban =   case <ip> in
              *.*)
                echo "ban IPv4" ;;
              *)
                echo "ban IPv6" ;;
              esac
...
```

0.10th actions considering already this info and are working a bit differently (e. g. `actionstart` is family-related and does start on demand, the actions are compatible for systems without IPv6-support, because the sections are independent, etc).

Please understand that we have basically no interest to implement this all for all actions of older versions too (and then still support two incompatible frameworks).
