### ISSUE TITLE
[meta] announce mailing list

### ISSUE THREAD

**Issue by Eig8phei** [fail2ban/fail2ban#1895]
Hello,

What do you think about having a classic announce mailing list?

I think there is/was one at sourceforce but it looks neglected.

Github is not very friendly with monitoring a project for important milestones.

**Comment by sebres** [comment]
> Github is not very friendly with monitoring a project for important milestones.

Can you explain here a bit more what you meant? 

If you belong to stargazers of fail2ban, did you not received the announcement for releases?
Or what did you mean with "important milestones" resp. wish we should publish?

**Comment by Eig8phei** [comment]
My goal is to receive announcements for new versions or anything else important enough.

Here is a classic announcements mailing list: https://lists.freedesktop.org/archives/mesa-announce/2017-September/thread.html. Those are emails sent to anyone subscribed.

I'm not sure what "stargazers of fail2ban" means but it sounds close enough to a mailing list. If so could you please tell me how to subscribe to that?

**Comment by sebres** [comment]
> stargazers of fail2ban

... are the people, that set "star" on the project (it looks like you are).

**Comment by Eig8phei** [comment]
Hmm, I see. Indeed I starred many projects on Github but I don't remember ever seeing an announcement from any of them.

Maybe it's missing configuration item on my side, I looked at Github preferences and I can't see anything related.

**Comment by sebres** [comment]
@yarikoptic Any thoughts?

**Comment by yarikoptic** [comment]
Never saw announcements from github either
I think we should reincarnate the sourceforge list , unless it is malfunctioning. @sebres do you have permissions there? If not what is your login there

**Comment by sebres** [comment]
> do you have permissions there? If not what is your login there

Not that I knew... And it's the same login-name.

**Comment by yarikoptic** [comment]
@sebres you now a god there too now ;)

**Comment by sebres** [comment]
Hmm... I'm... a god... :godmode:

**Comment by sebres** [comment]
Therefore here is a link to [Subscribe](https://sourceforge.net/projects/fail2ban/lists/fail2ban-announce).

Thus I'm closing this.

**Comment by Eig8phei** [comment]
Thank you all for the effort.

**Comment by sebres** [comment]
New 0.10th release: [0.10.2 (2018/01/18) - nothing-burns-like-the-cold](https://github.com/fail2ban/fail2ban/releases/tag/0.10.2)

**Comment by sebres** [comment]
New 0.10th release: [0.10.3 (2018/04/04) - the-time-is-always-right-to-do-what-is-right](https://github.com/fail2ban/fail2ban/releases/tag/0.10.3)

**Comment by sebres** [comment]
New 0.10th release: [0.10.4 (2018/10/04) - ten-four-on-due-date-ten-four](https://github.com/fail2ban/fail2ban/releases/tag/0.10.4)

**Comment by sebres** [comment]
JFYI. github provides now a new feature - "Release-only subscription"

> You can now limit a repository's notifications exclusively to releases. Use it to follow your favorite repositories!
