### ISSUE TITLE
Won't there be a 0.10.1?

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#1899]
Up to now we usually don't bump minor version number.
How come that 0.11 is planned?

**Comment by szepeviktor** [comment]
I see https://github.com/fail2ban/fail2ban/blob/e0fede621e3a2fd15ce0a814c9d6a75fde404a70/ChangeLog#L44
Will we hugely diverge from 0.10?

**Comment by sebres** [comment]
> Won't there be a 0.10.1?

The next release will get 0.10.1 (See https://github.com/fail2ban/fail2ban/releases).

> Will we hugely diverge from 0.10? That is why the new minor version?

0.11 will get newest development features (at the moment 0.10 with ban-time-incr);
0.10 is frozen (so no major future development), thus minor enhancements and bug-fixing only (resp. new filter and/or rules, etc.);
0.9 critical bug-fixing only (resp. easy going simple filter enhancements).

Previously the master branch was the development branch...

> How come that 0.11 is planned?

You mean release of 0.11? If so I've still small todo-list there, if get ready I'll release it.

**Comment by szepeviktor** [comment]
Thanks for clarifying.

It is nice to hear that 0.11 has *major future development*.
