### ISSUE TITLE
addIgnoreIP should not produce duplicates

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#1900]
Adding an IP to ignore list could produce duplicates.

Could we loop through the current list to check for the IP being added?

**Comment by sebres** [comment]
> Adding an IP to ignore list could produce duplicates.

Yes, but only correct way would be like [here](https://github.com/fail2ban/fail2ban/blob/b5dd5adb08f9fd3496f8c63b1d53b0e3c6aabbf1/fail2ban/server/filter.py#L501) - using `isInNet` to recognize the sub-nets... Something like:
```python
if ip.isInNet(net):
  continue
if net.isInNet(ip):
  # replace:
  self.__ignoreIpList[neti] = ip
```
Just, it can be too risky for dyn-dns entries and similar...

Or did you meant exact duplicates?

**Comment by szepeviktor** [comment]
> Or did you meant exact duplicates?

Of course!
