### ISSUE TITLE
Fail2ban sas doesn't work

### ISSUE THREAD

**Issue by duleandro** [fail2ban/fail2ban#1902]
Sorry for my bad english.... i have one problem with my fail2ban.... 
>    I'm using fail2ban with sasl (postfix/smtp) but he don't working. My log
>    line have another field that does not exist in general logs...

>    Eg:  common log:   May 20 16:18:20 mail3 postfix/smtpd[28095]: warning:
>    unknown[163.177.41.68]: SASL LOGIN authentication failed: authentication
>    failure

>            My log:   Sep 29 16:47:52 mail3 postfix/smtpd[31152]: warning: unknown[179.179.181.237]:55729: SASL LOGIN authentication failed: authentication failure

>    I think that because this part of log (55729:) , fail2ban not work
>    properly. 

>    55729:  is an aleatory number

Fail2ban v0.7.4 - Debian 6.0
Filter: sasl.conf
log: /var/log/mail.log

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 
- [x ] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

**Comment by sebres** [comment]
Thanks!

Fixed in a2120a9de5ba6211e42aae24252e860a62d9d4fa (for v.0.9) / in 8c804a229036c45b92fc17437899d28b853d0ebf (>= 0.10)
