### ISSUE TITLE
Each write into a file in  /var/run/fail2ban/ needs to confirm that the directory exists and is writeable 

### ISSUE THREAD

**Issue by herrold** [fail2ban/fail2ban#1905]
This was filed on a closed bug by @WagnerGMD and so you may not see if:

> https://github.com/fail2ban/fail2ban/issues/1890

as the '@' did not pull that user up in my edit window ... :
> https://github.com/WagnerGMD

> **PS :**
> - After a reboot I had met one trouble with Fail2Ban... The solution was to
> recreate it : `mkdir /var/run/fail2ban`.
> - It woudn't be better to store them ? Because in the aim to restart
> Fail2Ban, I need to run the both commands :
> ```
> fail2ban-client stop;
> fail2ban-client start;
> ## I avoid to use "fail2ban-client reload;" because no it doesn't work and
> it's sound complicated...
> ```
> That's why the list of IP was clean (entirely) and despite the fact I had
> installed the package **iptables-persistent**.

This implies that some process is trying to write in that ephemeral directory without first checking that the path exists and is writable

I do not have details -- perhaps @wagnerGMD will comment

**Comment by sebres** [comment]
> This implies that some process is trying to write in that ephemeral directory

This is not a "ephemeral directory", but just configured path (default for many linux-distributions).
If your `/var/run` is mapped to virtual drive (empty after reboot), you've two options:
- either reconfigure it to another persistent path;
- or create it using `/bin/mkdir -p /var/run/fail2ban` in your init-script e. g. like in our [fail2ban.service](https://github.com/fail2ban/fail2ban/blob/e3b061e94b54067525c5e7f2ac716d1c838c9f20/files/fail2ban.service.in#L9)

> without first checking that the path exists

This (configured) path **should** exists before fail2ban started, therefore no auto-creation resp. checking that the path exists.

P.S. As regards the issue #1890 - of course we see all the comments also on closed issues.

**Comment by herrold** [comment]
ehh?

/var/run is required to be emptied by the FHS

> http://www.pathname.com/fhs/2.2/fhs-5.13.html

and to be 'cleaned out' of files, here, a directory, at boot time.  This is not some artifact of a non-present file-system.  Trying to write to a non-present path should at least provoke a warning when the expectation of it existing is not met.  adding an 'assert' 

This '/var/run' path is copiously hard-coded into the code -- how is it NOT owned to check the accuracy of assumptions by fail2ban?

> fail2ban/setup.py:if os.path.exists('/var/run'):
fail2ban/setup.py:      # if we are on the system with /var/run -- we are to use it for having fail2ban/
fail2ban/setup.py:      # realpath is used to possibly resolve /var/run -> /run symlink
fail2ban/setup.py:      data_files_extra += [(realpath('/var/run/fail2ban'), '')]
fail2ban/fail2ban/client/csocket.py:    def __init__(self, sock="/var/run/fail2ban/fail2ban.sock"):
fail2ban/fail2ban/client/fail2banreader.py:             opts = [["string", "socket", "/var/run/fail2ban/fail2ban.sock"],
fail2ban/fail2ban/client/fail2banreader.py:                             ["string", "pidfile", "/var/run/fail2ban/fail2ban.pid"]]
fail2ban/fail2ban/server/asyncserver.py:                self.__sock = "/var/run/fail2ban/fail2ban.sock"
fail2ban/fail2ban/server/server.py:                     'Darwin':  '/var/run/syslog',
fail2ban/fail2ban/server/server.py:

**Comment by sebres** [comment]
> This '/var/run' path is copiously hard-coded into the code

If you write such things, then please take a look in source code - all this are default values! Overwritten with values from command-line, resp. from fail2ban.conf.

This path will be used for pid and sock files (both are expected run-time only for communication between client and server (resp. service or init.d script). Both can be reconfigured in fail2ban.conf (and via command line from corresponding service or init.d script).

Thus again - why this path cannot be created **once by start** of the fail2ban in corresponding service or init.d script?

**Comment by WagnerGMD** [comment]
Today, I had repeat the process and I got the same trouble. Then the first message was : "**There is no directory /var/run/fail2ban to contain the socket file /var/run/fail2ban/fail2ban.sock.**" It's happened right after this command : ` fail2ban-client start`

So I won't have a lot to comment. But If you need more informations let me know and I will see.
