### ISSUE TITLE
Variable interpolation appears to be broken for actioncheck

### ISSUE THREAD

**Issue by robsheldon** [fail2ban/fail2ban#1907]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.9.3, 0.11.0
- OS, including release name/version: Ubuntu 16.04.3 x64
- [-] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

Variable interpolation doesn't appear to be working for actioncheck. I configured /etc/fail2ban/actions.d/iptables-multiport to echo the ip and matching lines to the log file for both actionban and actioncheck; actionban shows the correct information, actioncheck displays the <variables>. I checked this against the distributed package, and then purged that and reinstalled from the current 0.11.0 version on Github.

Here's an excerpt of the iptables-multiport action config:

```
# Option:  actioncheck
# Notes.:  command executed once before each actionban command
# Values:  CMD
#
actioncheck = echo check: "<ip>" "<matches>" >> /var/log/fail2ban.log

# Option:  actionban
# Notes.:  command executed when banning an IP. Take care that the
#          command is executed with Fail2Ban user rights.
# Tags:    See jail.conf(5) man page
# Values:  CMD
#
actionban = echo ban: "<ip>" "<matches>" >> /var/log/fail2ban.log
```

and here's sample output in /var/log/fail2ban.log:

```
check: <ip> <matches>
ban: 160.202.161.29 Oct  4 16:01:02 rsa-sandbox sshd[2497]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=160.202.161.29  user=root
```

#### Steps to reproduce

Use the configuration above, restart fail2ban, trigger the action and watch the log for output.

#### Expected behavior

Variable interpolation in the actioncheck action.

#### Observed behavior

No variable interpolation in the actioncheck action.

#### Any customizations done to /etc/fail2ban/ configuration

None relevant, as far as I can tell.

#### Relevant parts of /var/log/fail2ban.log file:

See above.

#### Relevant lines from monitored log files in question:

etc.

**Comment by sebres** [comment]
Parameter `actioncheck` opposite to `actionban` is not ticket-related. 
In this case it is similar to `actionstart`/`actionstop`, but called each time an IP going banned.
The sense of `actioncheck` is to check sane action state (availability of the chain, etc.). If it fails (returns not zero), the pair `actionstop` / `actionstart` will be called to restart jail action.
Thus `actioncheck` cannot interpolate IP-related info...

If you want to check something IP-related, you can use the shell script or write direct in `actionban` as multiline, e. g.:
```INI
actionban = if [ "$(check-ip '<ip>')" = '1' ]; then exit 0; fi;
            banip '<ip>'
            failure-to-log '<ip>' "<matches>"
```
