### ISSUE TITLE
uwf.conf should be edited anyway

### ISSUE THREAD

**Issue by IaroslavR** [fail2ban/fail2ban#1909]
due to https://github.com/fail2ban/fail2ban/pull/1532 and https://github.com/fail2ban/fail2ban/issues/656#issuecomment-38027046 actions should be edited for normal operation. I can't understand the meaning of the current template. Whats wrong with simplest solution like this?
```init
actionunban = ufw delete <blocktype> from <ip> to <destination>
actionban = ufw insert <insertpos> <blocktype> from <ip> to <destination>
```

**Comment by sebres** [comment]
Closed as no issue, please do the discussion in corresponding ticket (or PR)...
See https://github.com/fail2ban/fail2ban/pull/1532#issuecomment-336856558
