### ISSUE TITLE
sshd filter ignores login failure log entries

### ISSUE THREAD

**Issue by tadwiew** [fail2ban/fail2ban#1910]
_We will be very grateful, if your problem was described as completely as possible,
enclosing excerpts from logs (if possible within DEBUG mode, if no errors evident
within INFO mode), and configuration in particular of effected relevant settings
(e.g., with ` fail2ban-client -d | grep 'affected-jail-name' ` for a particular
jail troubleshooting).
Thank you in advance for the details, because such issues like "It does not work" 
alone could not help to resolve anything!
Thanks! (remove this paragraph and other comments upon reading)_

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes):
fail2ban-0.8.10-3.6.amzn1.noarch
- OS, including release name/version: 
4.9.51-10.52.amzn1.x86_64
[Amazon's Linux]
- [x ] Fail2Ban installed via OS/distribution mechanisms
- [ x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
fail2ban does not work correctly with ssh logs generated by 
openssh-7.4p1-11.68.amzn1.x86_64
openssh-clients-7.4p1-11.68.amzn1.x86_64
openssh-server-7.4p1-11.68.amzn1.x86_64
It ignores login failed lines and therefore does not blocks repeated login failures from the same IP.
_Summary here_
After checking into that issue I have found that OpenSSH has changed some log entries.
As a result sshd filter is not "catching" them. 
We need update to sshd.conf filter.
#### Steps to reproduce
Try to do ssh-login with invalid user name to the server with openssh 7.4 or newer.
It will generate following log entries 
```
Oct  8 04:16:31 ip-172-31-3-32 sshd[26759]: Invalid user test11 from 114.31.90.40 port 37886
Oct  8 04:16:31 ip-172-31-3-32 sshd[26759]: input_userauth_request: invalid user test11 [preauth]
Oct  8 04:16:32 ip-172-31-3-32 sshd[26759]: Connection closed by 114.31.90.40 port 37886 [preauth]
On the server with older versions of ssh you get:
Oct  9 18:06:25 ip-172-31-12-153 sshd[32197]: Invalid user test from 5.188.10.182
Oct  9 18:06:25 ip-172-31-12-153 sshd[32197]: input_userauth_request: invalid user test [preauth]
Oct  9 18:06:25 ip-172-31-12-153 sshd[32197]: Connection closed by 5.188.10.182 [preauth]
```
Please note that in the newer SSH log entry we have addl info "port 37886"  on 2 lines.
That causes filter sshd to IGNORE them.
#### Expected behavior
These log entries should be "catched" and trigger "ban" action.
#### Observed behavior
These log entries are not  "matched" by current regex.
#### Any additional information
seems that fairly simple change to regex will fix it ...
from
 ^%(__prefix_line)s[iI](?:llegal|nvalid) user .* from <HOST>\s*$
to
 ^%(__prefix_line)s[iI](?:llegal|nvalid) user .* from <HOST>.*$
### Configuration, dump and another helpful excerpts
Pls see openSSH release notes:
---
* The format of several log messages emitted by the packet code has
   changed to include additional information about the user and
   their authentication state. Software that monitors ssh/sshd logs
   may need to account for these changes. For example:

   Connection closed by user x 1.1.1.1 port 1234 [preauth]
   Connection closed by authenticating user x 10.1.1.1 port 1234 [preauth]
   Connection closed by invalid user x 1.1.1.1 port 1234 [preauth]

   Affected messages include connection closure, timeout, remote
   disconnection, negotiation failure and some other fatal messages
   generated by the packet code.
-----
#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_
```
Oct  8 17:29:16 ip-172-31-3-32 fail2ban.server : INFO   Changed logging target to SYSLOG for Fail2ban v0.8.10
Oct  8 17:29:16 ip-172-31-3-32 fail2ban.jail   : INFO   Creating new jail 'ssh-iptables-ipset4'
Oct  8 17:29:16 ip-172-31-3-32 fail2ban.jail   : INFO   Jail 'ssh-iptables-ipset4' uses pyinotify
Oct  8 17:29:16 ip-172-31-3-32 fail2ban.jail   : INFO   Initiated 'pyinotify' backend
Oct  8 17:29:16 ip-172-31-3-32 fail2ban.filter : INFO   Added logfile = /var/log/secure
Oct  8 17:29:16 ip-172-31-3-32 fail2ban.filter : INFO   Set maxRetry = 3
Oct  8 17:29:16 ip-172-31-3-32 fail2ban.filter : INFO   Set findtime = 600
Oct  8 17:29:16 ip-172-31-3-32 fail2ban.actions: INFO   Set banTime = 600
Oct  8 17:29:16 ip-172-31-3-32 fail2ban.jail   : INFO   Jail 'ssh-iptables-ipset4' started
```

#### Relevant lines from monitored log files in question:
see above ...
```
```

**Comment by sebres** [comment]
This will be already correct matched in all manner of fail2ban versions (e. g. latest 0.9, as well as 0.10, 0.11)...

Proof:
```bash
$ fail2ban-regex 'Oct  8 04:16:31 ip-172-31-3-32 sshd[26759]: Invalid user test11 from 114.31.90.40 port 37886' /etc/fail2ban/filter.d/sshd.conf

Running tests
=============

Use   failregex filter file : sshd, basedir: ./config
Use         maxlines : 10
Use      single line : Oct  8 04:16:31 ip-172-31-3-32 sshd[26759]: Invali...


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   5) [1] ^(?:\[\])?\s*(?:<[^.]+\.[^.]+>\s+)?(?:\S+\s+)?(?:kernel: \[ *\d+\.\d+\]\s+)?(?:@vserver_\S+\s+)?(?:(?:(?:\[\d+\])?:\s+[\[\(]?sshd(?:\(\S+\))?[\]\)]?:?|[\[\(]?sshd(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)\s+)?(?:\[ID \d+ \S+\]\s+)?(?:(?:error|fatal): (?:PAM: )?)?[iI](?:llegal|nvalid) user .*? from <HOST>(?: port \d+)?(?: on \S+(?: port \d+)?)?\s*$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.00 sec]
```

Your fail2ban version is just not up-to-date... (v. 0.8 is very old).

**Comment by blndev** [comment]
Seems still not to work on CentOS Linux release 7.4.1708 

Installed Packages
Name        : fail2ban
Arch        : noarch
Version     : 0.9.7
Release     : 1.el7
Size        : 0.0
Repo        : installed
From repo   : epel


I had to add the following RegEx to _/etc/fail2ban/filter.d/sshd.conf_ to fix the issue:
`^%(__prefix_line)sConnection closed by <HOST> port \d+ \[preauth\]$`

My RegEx looks now that way:

````
[DEFAULT]

_daemon = sshd

# optional prefix (logged from several ssh versions) like "error: ", "error: PAM: " or "fatal: "
__pref = (?:(?:error|fatal): (?:PAM: )?)?
# optional suffix (logged from several ssh versions) like " [preauth]"
__suff = (?: \[preauth\])?\s*
__on_port_opt = (?: port \d+)?(?: on \S+(?: port \d+)?)?

# single line prefix:
__prefix_line_sl = %(__prefix_line)s%(__pref)s
# multi line prefixes (for first and second lines):
__prefix_line_ml1 = (?P<__prefix>%(__prefix_line)s)%(__pref)s
__prefix_line_ml2 = %(__suff)s$<SKIPLINES>^(?P=__prefix)%(__pref)s

mode = %(normal)s

normal = ^%(__prefix_line_sl)s[aA]uthentication (?:failure|error|failed) for .* from <HOST>( via \S+)?\s*%(__suff)s$
         ^%(__prefix_line_sl)sUser not known to the underlying authentication module for .* from <HOST>\s*%(__suff)s$
         ^%(__prefix_line_sl)sFailed \S+ for (?P<cond_inv>invalid user )?(?P<user>(?P<cond_user>\S+)|(?(cond_inv)(?:(?! from ).)*?|[^:]+)) from <HOST>%(__on_port_opt)s(?: ssh\d*)?(?(cond_user): |(?:(?:(?! from ).)*)$)
         ^%(__prefix_line_sl)sROOT LOGIN REFUSED.* FROM <HOST>\s*%(__suff)s$
         ^%(__prefix_line_sl)s[iI](?:llegal|nvalid) user .*? from <HOST>%(__on_port_opt)s\s*$
         ^%(__prefix_line_sl)sUser .+ from <HOST> not allowed because not listed in AllowUsers\s*%(__suff)s$
         ^%(__prefix_line_sl)sUser .+ from <HOST> not allowed because listed in DenyUsers\s*%(__suff)s$
         ^%(__prefix_line_sl)sUser .+ from <HOST> not allowed because not in any group\s*%(__suff)s$
         ^%(__prefix_line_sl)srefused connect from \S+ \(<HOST>\)\s*%(__suff)s$
         ^%(__prefix_line_sl)sReceived disconnect from <HOST>%(__on_port_opt)s:\s*3: .*: Auth fail%(__suff)s$
         ^%(__prefix_line_sl)sUser .+ from <HOST> not allowed because a group is listed in DenyGroups\s*%(__suff)s$
         ^%(__prefix_line_sl)sUser .+ from <HOST> not allowed because none of user's groups are listed in AllowGroups\s*%(__suff)s$
         ^%(__prefix_line_sl)spam_unix\(sshd:auth\):\s+authentication failure;\s*logname=\S*\s*uid=\d*\s*euid=\d*\s*tty=\S*\s*ruser=\S*\s*rhost=<HOST>\s.*%(__suff)s$
         ^%(__prefix_line_sl)s(error: )?maximum authentication attempts exceeded for .* from <HOST>%(__on_port_opt)s(?: ssh\d*)? \[preauth\]$
         ^%(__prefix_line_ml1)sUser .+ not allowed because account is locked%(__prefix_line_ml2)sReceived disconnect from <HOST>: 11: .+%(__suff)s$
         ^%(__prefix_line_ml1)sDisconnecting: Too many authentication failures for .+?%(__prefix_line_ml2)sConnection closed by <HOST>%(__suff)s$
         ^%(__prefix_line_ml1)sConnection from <HOST>%(__on_port_opt)s%(__prefix_line_ml2)sDisconnecting: Too many authentication failures for .+%(__suff)s$
         ^%(__prefix_line)sConnection closed by <HOST> port \d+ \[preauth\]$

ddos =   ^%(__prefix_line_sl)sDid not receive identification string from <HOST>%(__suff)s$
         ^%(__prefix_line_sl)sReceived disconnect from <HOST>%(__on_port_opt)s:\s*14: No supported authentication methods available%(__suff)s$
         ^%(__prefix_line_sl)sUnable to negotiate with <HOST>%(__on_port_opt)s: no matching (?:cipher|key exchange method) found.
         ^%(__prefix_line_ml1)sConnection from <HOST>%(__on_port_opt)s%(__prefix_line_ml2)sUnable to negotiate a (?:cipher|key exchange method)%(__suff)s$
         ^%(__prefix_line_ml1)sSSH: Server;Ltype: (?:Authname|Version|Kex);Remote: <HOST>-\d+;[A-Z]\w+:.*%(__prefix_line_ml2)sRead from socket failed: Connection reset by peer%(__suff)s$

aggressive = %(normal)s
             %(ddos)s
````

**Comment by sebres** [comment]
> Seems still not to work on CentOS Linux release 7.4.1708

This issue concerns to the ` Invalid user ... from ... port X` (because in the newer version of sshd it logs with `port X` at end of message).
This is definitively fixed (also in your version, because I see `%(__on_port_opt)s` there).

Message `Connection closed ...`:
a) is not a failure in sense of fail2ban (it's a second message after another one with the same id)
b) otherwise will cause dual counting of the same failure.

**Comment by blndev** [comment]
Yes, your are right. It's occurring when an attacker try multiple private keys with a correct user name.
My fault.
