### ISSUE TITLE
Feature request: fail2ban-client get <JAIL> banip

### ISSUE THREAD

**Issue by iredmail** [fail2ban/fail2ban#1916]
Dear developers,

How about implement `fail2ban-client get <JAIL> banip`?

I know we can get the banned ip addresses with command `fail2ban-client status <JAIL>`, but it still requires some shell commands to get a list of banned ip addresses. With `fail2ban-client get <JAIL> banip`, it will be much simpler.

**Comment by gitbls** [comment]
Indeed, I tried this exact command today, only to find out that it wasn't implemented. It would be a very convenient addition.
