### ISSUE TITLE
action.d/pf.conf wrong multiport syntax 

### ISSUE THREAD

**Issue by mkeilwaldbrunn** [fail2ban/fail2ban#1922]
### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): 0.10.1
- OS, including release name/version:  FreeSBD 11.1
- [ ] Fail2Ban installad via port

### The issue:
The FreeBS packet filter requires lists to be set in curly bracets, 
The multiport option doesn't respect this and generates an invalid rule, when multiports are defined in a jail. port = porta, portb,portc

block quick ...... to any port porta, port, portc

#### Steps to reproduce
Define a multiport jail action an trigger it 

#### Expected behavior
multiport option in ./action.d/pf.conf has to be enclosed by curly bracets.
`multiport = any port { <port> }`

**Comment by sebres** [comment]
closed as duplicate, further in #1915
