### ISSUE TITLE
Wrong error codes in default postfix-rbl.conf

### ISSUE THREAD

**Issue by darren12345** [fail2ban/fail2ban#1932]
Not sure if this is the right place for this, but there seems to be a typo in the package provided postfix-rbl.conf filter file.

### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.9.6-2
- OS, including release name/version:  Debian 9.1
- [X] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase

### The issue:

The default postfix-rbl.conf regex looks like this:

`failregex = ^%(__prefix_line)sNOQUEUE: reject: RCPT from \S+\[<HOST>\]: 454 4\.7\.1 Service unavailable; Client host \[\S+\] blocked using .* from=<\S*> to=<\S+> proto=ESMTP helo=<\S*>$`

The error code 454 seems to indicate "relay access denied" and doesn't match up with the situation where a mail is blocked due to a match on an RBL. Indeed:

```
$ fail2ban-regex  /var/log/mail.log  /etc/fail2ban/filter.d/postfix-rbl.conf

Running tests
=============

Use   failregex filter file : postfix-rbl, basedir: /etc/fail2ban
Use         log file : /var/log/mail.log
Use         encoding : UTF-8


Results
=======

Failregex: 0 total

Ignoreregex: 0 total
```
The lines in my mail.log that I'm expecting a hit against are:

`Oct 19 12:42:58 hostname postfix/smtpd[1034]: NOQUEUE: reject: RCPT from unknown[113.161.72.167]: 554 5.7.1 Service unavailable; Client host [113.161.72.167] blocked using bl.spamcop.net; Blocked - see http://www.spamcop.net/bl.shtml?113.161.72.167; from=<Gordonwblr@static.vnpt.vn> to=<email@mydomain.co.uk> proto=ESMTP helo=<static.vnpt.vn>`

So I need to change the filter file to error code 554 5.7.1:

`failregex = ^%(__prefix_line)sNOQUEUE: reject: RCPT from \S+\[<HOST>\]: 554 5\.7\.1 Service unavailable; Client host \[\S+\] blocked using .* from=<\S*> to=<\S+> proto=ESMTP helo=<\S*>$`

And then we get matches:

```
$ fail2ban-regex  /var/log/mail.log  /etc/fail2ban/filter.d/postfix-rbl.conf

Running tests
=============

Use   failregex filter file : postfix-rbl, basedir: /etc/fail2ban
Use         log file : /var/log/mail.log
Use         encoding : UTF-8


Results
=======

Failregex: 40 total
|-  #) [# of hits] regular expression
|   1) [40] ^(?:\[\])?\s*(?:<[^.]+\.[^.]+>\s+)?(?:\S+\s+)?(?:kernel: \[ *\d+\.\d+\]\s+)?(?:@vserver_\S+\s+)?(?:(?:(?:\[\d+\])?:\s+[\[\(]?postfix(-\w+)?/smtpd(?:\(\S+\))?[\]\)]?:?|[\[\(]?postfix(-\w+)?/smtpd(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)\s+)?(?:\[ID \d+ \S+\]\s+)?NOQUEUE: reject: RCPT from \S+\[<HOST>\]: 554 5\.7\.1 Service unavailable; Client host \[\S+\] blocked using .* from=<\S*> to=<\S+> proto=ESMTP helo=<\S*>$
`-

Ignoreregex: 0 total
```

**Comment by sebres** [comment]
Checked against newer version, e. g. current v.0.10 (with combined postfix and postfix-rbl):
```bash
$ fail2ban-regex "$line" postfix

Running tests
=============

Use   failregex filter file : postfix, basedir: /etc/fail2ban
Use      datepattern : Default Detectors
Use      single line : Oct 19 12:42:58 hostname postfix/smtpd[1034]: NOQU...


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] ^RCPT from [^[]*\[<HOST>\](?::\d+)?: 55[04] 5\.7\.1\s
`-
...
Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.00 sec]
```
