### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by Alex-Vaduva** [fail2ban/fail2ban#1939]
Hi,
I have a question regarding the licenses applicable to 5 files from fail2ban. 
Please give me more info about the licenses for the following files: 
man/fail2ban.1
man/fail2ban-client.1
man/fail2ban-regex.1
man/fail2ban-server.1
files/solaris-svc-fail2ban
It is my understanding that the first 4 files are under GPL-2.0 only: 
man/fail2ban.1
man/fail2ban-client.1
man/fail2ban-regex.1
man/fail2ban-server.1
And looks like the following file is under GPL with no version: files/solaris-svc-fail2ban
Now, if I want to combine fail2ban with a library under GPL-3.0, it could help to have all the files from the package under GPL- 2.0 or any later version. 
Any additional info about the licensing of these 5 files could really help.
Thank you,
Alex

**Comment by yarikoptic** [comment]
All those are autogenerated from running fail2ban-command --help, so output could be considered to be under the same license as fail2ban itself (GPLv2+)
```shell
$> grep -l help2man man/fail2ban*1
man/fail2ban-client.1
man/fail2ban-regex.1
man/fail2ban-server.1
man/fail2ban-testcases.1
```

In any case -- my take is that it is the default wording of the GPL license which allows for "any later version" (if that license statement used as is from the GPL-2 wording), so whenever it is noted that it is under GPL, it assumes "any later version" unless explicit version is noted and stated "no later version".
Thus, the files/solaris-svc-fail2ban IMHO is under the same terms, and could be used with the later version.

If still in doubt, you are welcome to strip/replace any questionable files from your distribution

**Comment by Alex-Vaduva** [comment]
Thank you very much for the clarifications.
Alex
