### ISSUE TITLE
getHost always runs to produce <ip-host>

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#1947]
As DNS lookups may take a long time - I do not know Python's timeouts.

Please add an option do disable automatic `<ip-host>` population.
Thanks.

**Comment by sebres** [comment]
We had already such option a long time (if I correct understood what you need):
```INI
# jail.local
[DEFAULT]
usedns = no
```
New in v.0.10 (compared to v.0.9):
- if dns-resolving disabled, the tag `<HOST>` wraps to IPv4/IPv6 matches only (no dns match in regex);
- if dns-resolving enabled, this will be cached for 5 minutes (max 1000 entries cache);

Please reopen if I'm wrong

**Comment by szepeviktor** [comment]
Populating `<ip-host>` seems to be totally new, and it is for actions, not filters:

https://github.com/fail2ban/fail2ban/blob/099e35103fa08e1192aa1a4e9883847268f00286/fail2ban/server/actions.py#L296

https://github.com/fail2ban/fail2ban/blob/870a33247b48fc834dad50af91533fbb6862d29c/fail2ban/server/ipdns.py#L88-L100

@sebres I am unable to repoen it.

**Comment by sebres** [comment]
"Read carefully before write..."
I found now what you meant (tag `<ip-host>` indeed retrieves the host of IP in ticket)...
The question is: if someone need the host in action (using tag `<ip-host>` how it should work without dns-resolving)?

**Comment by szepeviktor** [comment]
Currently I am using `host -W 3 -t PTR '<ip>' 2>&1` which I know I can control.

- I can think of disabling `<ip-host>` AND other DNS-related tags
- or somehow set the timeout making sure it will not take more than 3 seconds to handle the ban

**Comment by sebres** [comment]
Oh, you've not understood - all actions parameters (ActionInfo/CallingMap) are on demand - does not executed until not affected (not used in action).
Thus no option needed at all!

**Comment by szepeviktor** [comment]
Oh! Thank you.

For example. What could be the source of this knowledge for me?

**Comment by sebres** [comment]
> For example. What could be the source of this particular knowledge for me?

Here? For example the `lambda` prefix and the in-line docu for [CallingMap](https://github.com/fail2ban/fail2ban/blob/099e35103fa08e1192aa1a4e9883847268f00286/fail2ban/server/action.py#L70).

But if you've a question, you can ask (and will get an answer) 😄

**Comment by szepeviktor** [comment]
Thanks.

I do not speak Python, so lambda is a Greek letter for me.
