### ISSUE TITLE
Incorrect behaviour after bantime change and jail reload.

### ISSUE THREAD

**Issue by yahuaska** [fail2ban/fail2ban#1952]
I'll try to describe in two different cases.

We have a jail with ban time set to 180 seconds for example. Ok, we've banned some ip-address (we even can see the row in f2b's database with a value of 180 in the column). 

1. Let's change ban time to, for example, 480 seconds. What do we see in the database? Right - the same 180 seconds. Ok. And when will ip be unbanned? After 480 from the moment, it was banned.

2. We change ban time to 60 seconds. What will we get? Will the ip be unbanned after 60 seconds? **No**, it will be unbanned after 180 as if we didn't change ban time.

It's a very unintuitive behavior. Also, externally we have no clue when ip will be removed from ban-list.

Tested on 0.11 version (commit hash 93634dd822d7696d3c523581310c2acd0789f03e).

**Comment by sebres** [comment]
1. It's is not really "unintuitive behavior" - especially in v.0.11 version (with ban-time-incr) many factors play a role which end-of-ban time will be used (it was prolonged or not, it is already known as bad IP, etc.). It is also different how the new bantime was applied (reload config/jail, or just set the value of bantime in jail, or do the complete restart)...
**The simplest rule here - always the longest ban-time will be applied (between default, already known, calculated).**
2. Actually no matter which value you see in the database (it is to see as a fail2ban internal storage). The value in database is changed only at the moment of ban (or auto-increase), so by time of occurrence.
3. And last but not least, how often you changes the bantime (normally it will be set once and never touched)? And why fail2ban should necessarily respond by already banned tickets (or how it should do it in your opinion)?

BTW If you'll get really clean state, just use `fail2ban-client reload --restart --unban <jail>|--all` to reset jail (unban all IPs).
Or just do `fail2ban-client unban --all` after reload configuration to unban all IPs (which will get banned again after it will make more failures).

**Comment by yahuaska** [comment]
> And last but not least, how often you change the bantime (normally it will be set once and never touched)? 
 Not so often, but if it happens I want to know when ip will be unbanned, Is there any to get that info now?

>  And why fail2ban should necessarily respond by already banned tickets (or how it should do it in your opinion)?
But why already banned tickets in some cases are left untouched, in others - they're changed? It is what we've got now.

**Comment by sebres** [comment]
>  Is there any way to get that info now?

In your case unfortunately not. Normally the entry in fail2ban.log will give you an info:
```
2017-11-01 00:00:00,477 fail2ban.actions        [30622]:	[jail] Ban   	192.0.2.1
2017-11-01 00:00:00,480 fail2ban.observer       [30622]:	[jail] Increase Ban   	192.0.2.1 (2 # 1 day, 12:00:00 -> 2017-11-02 12:00:00)
```
You see it in parenthesis (bancount # bantime -> endofban).
But by interim change of the bantime (with reload), there is still only rule - "longest ban-time will be applied"...
