### ISSUE TITLE
Auto report

### ISSUE THREAD

**Issue by xlucasonepvp** [fail2ban/fail2ban#1953]
Hey

I have a Ubuntu sever 14.04 that runs fail2ban.
I want fail2ban to auto report failed ssh logins to abuseipdb.
How?
I need help

**Comment by thezoggy** [comment]
configure and read `fail2ban/action.d/abuseipdb.conf`

also this isnt the ideal place to seek for help but a good way to anger devs :)

**Comment by sebres** [comment]
:) Yep, here is not stackoverflow... 

But just because I should anyway answer:
```INI
# jail.local:

[my-jail]
# add abuseipdb to jail actions:
action = %(action_)s
         abuseipdb[abuseipdb_apikey="your-api-key", abuseipdb_category="my-jail-category"]
```
Thus closed.
