### ISSUE TITLE
Error Fail2Ban - CENTOS

### ISSUE THREAD

**Issue by rfminelli** [fail2ban/fail2ban#1958]
Good morning, I'd like to report an error in installing fail2ban.
It installs normally but does not create the service to start.
You were only able to correct the error by doing the following.

cp -Rf /tmp/fail2ban/build/fail2ban.service /usr/lib/systemd/system/fail2ban.service

then run the command
systemctl enable fail2ban.service
systemctl restart fail2ban.service

After that everything was 100%.

Test performed with CENTERS 7.

**Comment by sebres** [comment]
> It installs normally but does not create the service to start.

<ol>
<li> Installed from github:

  Works as "designed"... Please read the [README](https://github.com/fail2ban/fail2ban/blob/0.10/README.md):<br>

> Please note that the system init/service script is not automatically installed. To enable fail2ban as an automatic service, simply copy the script for your distro from the `files` directory to `/etc/init.d`. ...

This belongs to the distribution tasks and definitely not the part of this repository.
</li>
<li>Installed from some distribution (packet manager, etc.):

Then you should seek support from the distribution you obtained Fail2Ban from...
</li>
</ol>
Thus closed.
