### ISSUE TITLE
customizing nginx-limit-req.conf

### ISSUE THREAD

**Issue by mitchellkrogza** [fail2ban/fail2ban#1962]
Is there any way to customise the nginx-limit-req.conf filter? 

I get a lot of bans per day (400+) all seeking out wp-login.php and would like to be able to write all these IP's into a simple text file for further actioning. This would be easier than going through a current 1200+ emails over the past 3 days.

**Comment by sebres** [comment]
Filter `nginx-limit-req` is actually for another purposes (bans failures from limit-zone, so by requests count).
Rather you may need [nginx-botsearch](https://github.com/fail2ban/fail2ban/blob/0.10/config/filter.d/nginx-botsearch.conf). Although wp-login case is already covered, you can extend it with overwriting of `block` parameters (see include [botsearch-common](https://github.com/fail2ban/fail2ban/blob/0.10/config/filter.d/botsearch-common.conf) for details)

Please note that the observing of nginx access.log directly may be too heavy for your server (if too many entries it produces high load by fail2ban). 
Thus I would recommend create a new nginx internal location (with extra access-log) which will get all the requests with 404/403/401/500 etc. Therefore restrict it to extra location via postaction resp. conditional access_log, resp. via error_page extra location:

1. Via conditional [access_log](http://nginx.org/en/docs/http/ngx_http_log_module.html#access_log):
```nginx
map $status $loggable {
    ~^[23]  0;
    default 1;
}

# to log the requests excepting response codes 2xx and 3xx: 
access_log /var/log/nginx/access_for_fail2ban.log combined if=$loggable;
# all requests will not be logged:
access_log /var/log/nginx/access.log combined;
```

2. E. g. in error location, for example:
```nginx
...
fastcgi_intercept_errors on;
proxy_intercept_errors on;
error_page 404 = @fallback;
...
location @fallback {
    access_log /var/log/nginx/access_for_fail2ban.log;
    return $status;
}
```

**Comment by mitchellkrogza** [comment]
Thanks @sebres I'll give that a try 👍

**Comment by sebres** [comment]
This how-to was rewritten as part of new wiki article [Best practice :: wiki](https://github.com/fail2ban/fail2ban/wiki/Best-practice).
