### ISSUE TITLE
Older version "/usr/bin/fail2ban-client" binary self-modified behind firewall

### ISSUE THREAD

**Issue by Joel-Mckay** [fail2ban/fail2ban#1963]
//The repo reinstalled package version (old Ubuntu 12.04 server)
sha1sum /usr/bin/fail2ban-client
a6375fd4457ce5d9da2a73ac8649f9bed38c4967  /usr/bin/fail2ban-client

//The modified version that failed signature checking
sha1sum ./fail2ban-client
990961ed98dd5fcfc1556a98d8b01ca6f7a27fb0  ./fail2ban-client

//compressed to contain the payload
tar czf fail2ban-client.tar.gz fail2ban-client

//I scanned the file with
ClamAV update process started at Mon Nov 13 19:02:10 2017
main.cvd is up to date (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
daily.cvd is up to date (version: 24041, sigs: 1779634, f-level: 63, builder: neo)
bytecode.cvd is up to date (version: 318, sigs: 75, f-level: 63, builder: raynman)

//Clamav does not register a virus, but can someone confirm if this binary is malicious or not?
//It may just be bit rot, but I'd like to know how to handle the server image in question.
//
//Best regards,
//J

**Comment by sebres** [comment]
> Clamav does not register a virus, but can someone confirm if this binary is malicious or not?

😄 
fail2ban-client is not a binary (it's a shell script), you can view it in the text-editor (resp. compare the changes via dif).

Well, I've no idea what for version has this sha-hash. Rather you should seek support by maintainers for Ubuntu...
