### ISSUE TITLE
More info about ipv6

### ISSUE THREAD

**Issue by madri2** [fail2ban/fail2ban#1965]
Hello i would like some info about how fail2ban 0.10+ handles ipv6.
does it ban a /128 ipv6 ? a /64 ?
if someone use a /64range to flood with a different /128 ipv6 at each request, will fail2ban detect something ? block the /64range ? nothing ?

**Comment by sebres** [comment]
Currently if nothing extra configured it will ban only the exact address. You can rewrite your action configuration to ban a subnet's instead of the IP.
The automatically subnet banning is planned, but still not implemented. 
Related tickets -  #1123, #927

**Comment by SpareSimian** [comment]
Using fail2ban 0.11.2 on CentOS 7, I'm trying out this iptables-multiport.local:

```
# override default IPv6 single-address ban and ban whole /64

[Definition?family=inet6]

actionban = <iptables> -I f2b-<name> 1 -s <ip>/64 -j <blocktype>

actionunban = <iptables> -D f2b-<name> -s <ip>/64 -j <blocktype>
```
