### ISSUE TITLE
Verbose logging during startup with log level = 2

### ISSUE THREAD

**Issue by SRFurst** [fail2ban/fail2ban#1968]
I note that fail2ban is logging DEBUG and HEAVY message to syslog on startup. A lot. I have log level set to 2 (confirmed by get log level) and would not expect this behavior.

Debian 8 (Jessie)
fail2ban v0.11.0.dev0

Thank you

**Comment by sebres** [comment]
Set it to INFO... Pythons log level are backwards, see https://docs.python.org/2/library/logging.html#levels
