### ISSUE TITLE
filter statement no longer working in 0.11dev

### ISSUE THREAD

**Issue by timreeves** [fail2ban/fail2ban#1971]
This was noticed with 0.11dev downloaded on 05.11.2017.
Fail2ban was failing to start up, the error was displayed on stdout.

This construction fails in 0.11 jails.local:
[webmin]
filter = webmin-auth.conf

This succeeds:
[webmin-auth]

I did not make any other change, the file filter.d/webmin-auth.conf was always present and readable (the unmodified distribution file).
Using the former "filter" statement, fail2ban was stating that the filter file did not exist or was not readable, which was plain wrong, it was quoting the correct path elements to the file.

For compatibility with previous versions it would be great if the alternative construction would still work.

Thanks for the IPv6 version, to all who put in great work!

**Comment by sebres** [comment]
> For compatibility with previous versions it would be great if the alternative construction would still work.

Well this "alternative" construction is a bit wrong - the filter name should don't contain the file-extension `.conf`. The corresponding filter will be loaded, but firstly `filter.conf` hereafter `filter.local`.
Additionally the filter-name construct is more complex as in older fail2ban versions. 
For example you can supply some parameter to the filter-config, like
`filter = sshd[mode=aggressive, datepatern="...", ...]`.

Therefore just make:
```diff
[webmin]
-filter = webmin-auth.conf
+filter = webmin-auth
```

**Comment by timreeves** [comment]
Of course you are right, and I'm sorry to have posted a wrong feedback. Still perhaps the error message could be improved, which was what mislead me: Because I had used the file name with extension, it told me that the file "filter.d/webmin-auth.conf" was missing. This could be improved to say:
filter.d/webmin-auth.conf{.conf|.local} is missing.
With that hint, I'm sure I would have noticed the problem right away.
Anyway, thx for the prompt reply!
