### ISSUE TITLE
 python-central (>= 0.6.11) but it is not installable

### ISSUE THREAD

**Issue by wisdo0** [fail2ban/fail2ban#1973]
### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

_Summary here_

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
What do you want to say us with this issue? Your "description" is too short to understand what do you meant.
Please provide more info... Closed as long no further info available.

BTW Rather we know something about `python-central` here, nor this will be used somewhere in fail2ban code-base.

**Comment by sebres** [comment]
@fail2ban/maintainers Has someone of you "wrong" dependency (to `python-central`) in your distributions?

@wisdo0 which distribution did you meant?
BTW: If it concerns the maintained fail2ban distribution, then better seek support from the distribution you obtained fail2ban from.
