### ISSUE TITLE
fail2ban block shutdown / slow startup...

### ISSUE THREAD

**Issue by noci2012** [fail2ban/fail2ban#1985]
During shutdown/startup fail2ban is capable to remove/add entries at a rate of about 1-3 per second.
This caused a reboot to stall for 30+ minutes (about 8000 entries appearantly) before fail2ban removed all entries. Not quite the expected time for a regular shutdown.

During startup it will take the better part of an hour to reprotect all known entries.
IMHO this should be handled more elegantly, by not removing entry by entry but by clearing ALL entries from chains... Should be possible by using:
ipset flush f2b-..... chains && ipset destroy f2b-.....
by first doing a ipset save   & ipset restore on boot this could be greatly sped up.

filling the set using ipset restore with input from a pipe on boot might seriously speed up operations.

**Comment by sebres** [comment]
See #1588 (resp. #1743) for more info.
