### ISSUE TITLE
firewallcmd-ipset doesn't ban clients (v0.11)

### ISSUE THREAD

**Issue by adbario** [fail2ban/fail2ban#1994]
Hi, testing the latest 0.11 version and firewallcmd-ipset doesn't correctly ban clients. This seems to be a problem with "ipset create" command.

OS: CentOS 7.4
Fail2Ban version: 0.11 from GitHub

```
$ cat /etc/fail2ban/jail.local

[DEFAULT]
bantime   = 3600
findtime  = 600
maxretry  = 3
banaction = firewallcmd-ipset

[sshd]
enabled = true
mode    = aggressive
backend = systemd
```

```
$ cat /var/log/fail2ban.log

2017-12-05 22:54:08,317 fail2ban.actions        [1099]: NOTICE  [sshd] Ban xx.xx.xx.xx
2017-12-05 22:54:08,615 fail2ban.utils          [1099]: Level 39 10b4090 -- exec: ipset add f2b-sshd xx.xx.xx.xx timeout 3600 -exist
2017-12-05 22:54:08,616 fail2ban.utils          [1099]: ERROR   10b4090 -- stderr: 'ipset v6.29: Kernel error received: Unknown error -1'
2017-12-05 22:54:08,616 fail2ban.utils          [1099]: ERROR   10b4090 -- returned 1
2017-12-05 22:54:08,617 fail2ban.actions        [1099]: ERROR   Failed to execute ban jail 'sshd' action 'firewallcmd-ipset' info 'ActionInfo({'bancount': 1, 'ip-rev': 'xx.xx.xx.xx.', 'family': 'inet4', 'ipmatches': '', 'matches': '', 'ip': 'xx.xx.xx.xx', 'ipjailmatches': '', 'ipfailures': 3, 'F-*': {'matches': [], 'failures': 3, 'mlfid': 'example.com sshd[1495]: ', 'ip4': 'xx.xx.xx.xx', 'user': 'root2'}, 'fid': 'xx.xx.xx.xx', 'time': 1512514448.220071, 'failures': 3, 'ip-host': 'xxx.cable.virginm.net', 'ipjailfailures': 3, 'restored': 0, 'bantime': 3600})': Error banning xx.xx.xx.xx
```

Same issue is found if trying directly the ipset commands from test-cases on https://github.com/fail2ban/fail2ban/blob/0.11/fail2ban/tests/servertestcase.py#L1669

```
$ ipset create f2b-j-w-fwcmd-ipset hash:ip
$ ipset add f2b-j-w-fwcmd-ipset 192.0.2.1 timeout 600 -exist

ipset v6.29: Kernel error received: Unknown error -1
```

If timeout is added to "ipset create" command, it works fine on command line:
```
$ ipset create f2b-j-w-fwcmd-ipset hash:ip timeout 600
$ ipset add f2b-j-w-fwcmd-ipset 192.0.2.1 timeout 600 -exist
```
Timeout exists there on 0.10 but it was removed on 0.11, but when putting it back there it gives another error:
```
# firewallcmd-ipset.conf
...
actionstart = ipset create <ipmset> hash:ip timeout <bantime><familyopt>
...

$ cat /var/log/fail2ban.log

2017-12-05 23:32:27,746 fail2ban.utils          [11274]: Level 39 eea830 -- exec: ipset create f2b-sshd hash:ip timeout <bantime>
firewall-cmd --direct --add-rule ipv4 filter INPUT_direct 0 -p tcp -m multiport --dports ssh -m set --match-set f2b-sshd src -j REJECT --reject-with icmp-port-unreachable
2017-12-05 23:32:27,746 fail2ban.utils          [11274]: ERROR   eea830 -- stderr: "/bin/sh: -c: line 0: syntax error near unexpected token `newline'"
2017-12-05 23:32:27,746 fail2ban.utils          [11274]: ERROR   eea830 -- stderr: "/bin/sh: -c: line 0: `ipset create f2b-sshd hash:ip timeout <bantime>'"
```

I guess this all happens because of changes in c21b4e4d56ebf44e7df250b382aac004df089551, timeout value is not picked up anymore.

**Comment by sebres** [comment]
v.0.11 has dynamic ban-time, thus the parameter `bantime` don't exists by `actionstart` (only actionban because dynamically now), thus option `timeout` cannot be used there.

If there some ipset versions (kernel?) that do not support this, then a fixed maximal possible timeout (or another option like persistent etc.) should be used here instead of.
If you can find it, please let me know.

BTW on my systems it works fine without timeout.

**Comment by sebres** [comment]
Well, I found one system where it produces exactly the same error.
There I found now a good workaround for this problem:
```bash
ipset create f2b-test hash:ip timeout 0
# ban:
ipset add f2b-test 192.0.2.1 timeout 600 -exist
# prolong:
ipset add f2b-test 192.0.2.1 timeout 1200 -exist
# dump:
ipset list f2b-test
  ...
  Members:
  192.0.2.1 timeout 1197
# end:
ipset flush f2b-test
ipset destroy f2b-test
```
Corresponding documentation:
>  Zero timeout value means the entry is added permanent to the set

Thus it creates a set with default permanent timeout, and the timeout will be set for each entry separately (by ban or by prolong).

**Comment by adbario** [comment]
Could you open a bit what the dynamic actually means on this context?

If I understand correctly, "ipset create" with timeout sets a default value for future added entries, which can be overwritten by individual entry timeout values. Timeout should be optional, but for my ipset/kernel version it only works if both "create" and "add" have timeout value or neither of them have it. Only one of them having timeout always gives an error.

I couldn't find any info about ipset/kernel compatibility with this, maybe I'm missing the correct terms to look for.

**Comment by adbario** [comment]
So basically the timeout could be set the same way it was on v0.10 as it will be overwritten anyway per entry?

**Comment by sebres** [comment]
Dynamic meant that the ban-time is variable, v.0.11 has a new feature "ban-time-incr" that increase ban-time dynamically for bad-ips (with repeated fail attempts).

**Comment by adbario** [comment]
Great, thanks for clarification.

**Comment by sebres** [comment]
Of course you should enable (per jail or in default section) it using `bantime.increment = true`.
https://github.com/fail2ban/fail2ban/blob/7e5d8f37fd0ff4a0569fbc5f2af8d2dd518a6309/config/jail.conf#L49

**Comment by adbario** [comment]
Should there be a failsafe timeout value set when using "ipset create", so it would get ie. value from jail or default section bantime and then keep increasing it if needed when adding new entries? Just to have there some other value than 0 for permanent jail.

**Comment by sebres** [comment]
Agree

**Comment by sebres** [comment]
Fixed in 309a1cb337604e03f764bf50839bdd3cb8280757

**Comment by davama** [comment]
@sebres  Of course this change was just done, but curious

Does the fail2ban org update the EPEL Centos fail2ban rpms files? Or is that someone else?
If so, how frequent?

thanks!

**Comment by adbario** [comment]
@davama EPEL is a project maintained by Fedora, so they will choose the versions what they want to offer.
