### ISSUE TITLE
Asterisk filter matches the wrong address

### ISSUE THREAD

**Issue by amorsen** [fail2ban/fail2ban#1999]
- Fail2Ban version (including any possible distribution suffixes):
fail2ban-0.10.0-1.fc27.noarch

- OS, including release name/version:
Fedora 27
 
- [X] Fail2Ban installed via OS/distribution mechanisms

- [X] You have not applied any additional foreign patches to the codebase

- [X] Some customizations were done to the configuration (provide details below is so)

Just the obvious, enabling the asterisk rule and such.

### The issue:

The default asterisk filter tries to make up a host to ban:
            ^Failed to authenticate (?:user|device) [^@]+@<HOST>\S*$

Unfortunately Asterisk logs:

dec 14 12:19:53 [hostname redacted] asterisk[16272]: [Dec 14 12:19:53] NOTICE[52666][C-00003dc8]: chan_sip.c:26355 handle_request_invite: Failed to authenticate device <sip:156@[my.public.server.ip redacted]>;tag=1522204535

This log entry does not contain the IP address of the host that is causing the problem (an annoying bug in itself, but that is an Asterisk problem, not a fail2ban problem). However, fail2ban somehow gets a hostname out of that, tries to look it up in DNS, and ends up banning 0.0.0.101 or 0.0.0.200 or 0.0.0.201.

This is obviously a bad idea.

**Comment by sebres** [comment]
Fixed in #1929.
Thus close... Thanks.
