### ISSUE TITLE
hostsdeny.conf: actionunban has wrong syntax

### ISSUE THREAD

**Issue by vvxvv** [fail2ban/fail2ban#2000]
1. actionunban has wrong syntax and garbage <br>   [Link]( https://github.com/fail2ban/fail2ban/blob/0.11/config/action.d/hostsdeny.conf)
2. `ed` is not installed by default on Debian 9
3. ` actionunban = sed -i '/^<daemon_list>: <ip>$/d' <file>`  works fine

**Comment by sebres** [comment]
Fixed in 7e05976ead14984a0c10d76f2e49713762479039 now.
