### ISSUE TITLE
ignoreip requirements

### ISSUE THREAD

**Issue by i300220** [fail2ban/fail2ban#2007]
Hi,
I'm running fail2ban 0.9.6-1 on debian 8.10

Don't know whether this is possible or not but I would have the possibility to include files for ignoreip into jail.local

Something like
```INI
[DEFAULT]
[INCLUDES]
ignoreip = bing-ips.txt
ignoreip += bell-ips.txt
ignoreip += local-ips.txt
```
The idea is that I change/add new ips or lists constantly and by now I have a long string of ips on my jail.local which is a nightmare to maintain.

I have a way to do it manually e.g.
```
#cat local-ips.txt bell-ips.txt bing-ips.txt
10.8.60.0/24 127.0.0.1/8 192.168.140.0/24 209.108.18.190/31 70.24.0.0/13 70.48.0.0/13 40.74.0.0/15 40.76.0.0/14 40.80.0.0/12 40.96.0.0/12 40.112.0.0/13 40.120.0.0/14 40.124.0.0/16 40.125.0.0/17 157.54.0.0/15 157.60.0.0/16 157.56.0.0/14
```
and then paste that into the jail.local ignoreip line to replace what was originally there.
Just an idea. That would be very appreciated.

Another idea. Don't know whether that would work or not:
```INI
[DEFAULT]
ignoreip = `cat local-ips.txt bell-ips.txt bing-ips.txt`
```
or
```INI
[DEFAULT]
ignoreip = `cat *-ips.txt`
```
Would any of this be possible?

**Comment by i300220** [comment]
Somehow my formatting was lost
- [DEFAULT] [INCLUDES] and the 3 ignoreip lines were indented to whow they belong to each other
- my backticks were lost fort the ignoreip = cat commands.

**Comment by sebres** [comment]
> The idea is that I change/add new ips or lists constantly 

The list specified with `ignoreip` is a "static" list (will be actualized after restart/reload only).

> and by now I have a long string of ips on my jail.local which is a nightmare to maintain.

You can write it also multiline in the python ini-files (use space as prefix in the second lines):
```INI
ignoreip = 10.8.60.0/24 127.0.0.1/8 192.168.140.0/24 209.108.18.190/31
           70.24.0.0/13 70.48.0.0/13 40.74.0.0/15 40.76.0.0/14 
           40.80.0.0/12 40.96.0.0/12 40.112.0.0/13 40.120.0.0/14
           ...
```

Taken a look on this RFE again, I think we have already similar feature that would be enough here:
```INI
ignorecommand = /path/to/ignorecommand.sh <ip>
```
will execute `/path/to/command` with IP to check it should be ignored.

In opposite to `ignoreip` (which is read from config-files once by start), the command `ignorecommand` will be executed each time before IP will be banned.

Thus I close it, if someone has a PR, so welcome...
