### ISSUE TITLE
can't set up fail2ban on LAMP stack Ubuntu 16.04 

### ISSUE THREAD

**Issue by benjaone1** [fail2ban/fail2ban#2009]
I run:

    sudo apt-get update
    sudo apt-get install fail2ban
    sudo cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local

With out activating any jails or anything else:

    sudo systemctl restart fail2ban

    Job for fail2ban.service failed because the control process exited with 
    error code. See "systemctl status fail2ban.service" and "journalctl -xe" for 
    details.

    sudo service fail2ban status
    ● fail2ban.service - Fail2Ban Service
    Loaded: loaded (/lib/systemd/system/fail2ban.service; enabled; vendor 
    preset: enabled)
    Active: inactive (dead) (Result: exit-code) since Mon 2018-01-01 15:04:10 
    UTC; 24s ago
    Docs: man:fail2ban(1)
    Process: 9828 ExecStop=/usr/bin/fail2ban-client stop (code=exited, 
    status=0/SUCCESS)
    Process: 14906 ExecStart=/usr/bin/fail2ban-client -x start (code=exited, 
    status=255)
    Main PID: 647 (code=killed, signal=TERM)

    Jan 01 15:04:10 benja2 systemd[1]: fail2ban.service: Control process exited, 
    code=exited status=255
    Jan 01 15:04:10 benja2 systemd[1]: Failed to start Fail2Ban Service.
    Jan 01 15:04:10 benja2 systemd[1]: fail2ban.service: Unit entered failed 
    state.
    Jan 01 15:04:10 benja2 systemd[1]: fail2ban.service: Failed with result 
    'exit-code'.
    Jan 01 15:04:10 benja2 systemd[1]: fail2ban.service: Service hold-off time 
    over, scheduling restart.
    Jan 01 15:04:10 benja2 systemd[1]: Stopped Fail2Ban Service.
    Jan 01 15:04:10 benja2 systemd[1]: fail2ban.service: Start request repeated 
    too quickly.
    Jan 01 15:04:10 benja2 systemd[1]: Failed to start Fail2Ban Service.

How do I set up fail2ban so it can start?

**Comment by sebres** [comment]
1. Please use the issue template, we made it not for nothing (your distro, fail2ban-version, fail2ban.log excerpt, etc).
2. If `fail2ban-client -x start` failed, possibly fail2ban.log will say you something about what is wrong.
Note also https://github.com/fail2ban/fail2ban/wiki/Troubleshooting.
3. Never do `sudo cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local`.
See [Proper fail2ban configuration](https://github.com/fail2ban/fail2ban/wiki/Proper-fail2ban-configuration).
