### ISSUE TITLE
blocking source IP network addresses

### ISSUE THREAD

**Issue by takeda** [fail2ban/fail2ban#201]
Perhaps this is just specific to me, it feels like script kiddies adapt to whatever I do. I initially set up fail2ban only to filter sshd. This resolved the issue temporarily but soon I noticed bruteforce attacks through SMTP. I created rule to detect and block those as well. Next I noticed that after blocking the attacks resume once again after ban expires. So I set up a rule that looks at file2ban log and bans repeated offenders.

It was quiet for some time, but now I see that the attacks are becoming much sophisticates. Currently the attackers are using hosts that have multiple IPs to perform scans therefore avoid being banned, for example:

May  1 05:31:22 chinatsu sshd[22262]: Invalid user supports from 42.121.73.2
May  1 05:31:22 chinatsu sshd[22262]: input_userauth_request: invalid user supports [preauth]
May  1 05:31:24 chinatsu sshd[22264]: Invalid user support from 42.121.73.18
May  1 05:31:24 chinatsu sshd[22264]: input_userauth_request: invalid user support [preauth]
May  1 05:31:25 chinatsu sshd[22267]: Invalid user support from 42.121.73.23
May  1 05:31:25 chinatsu sshd[22267]: input_userauth_request: invalid user support [preauth]
May  1 05:31:27 chinatsu sshd[22270]: Invalid user support from 42.121.73.29
May  1 05:31:27 chinatsu sshd[22270]: input_userauth_request: invalid user support [preauth]
May  1 05:31:29 chinatsu sshd[22272]: Invalid user support from 42.121.73.21
May  1 05:31:29 chinatsu sshd[22272]: input_userauth_request: invalid user support [preauth]
May  1 05:31:31 chinatsu sshd[22277]: Invalid user support from 42.121.73.20
May  1 05:31:31 chinatsu sshd[22277]: input_userauth_request: invalid user support [preauth]
May  1 05:31:33 chinatsu sshd[22279]: Invalid user support from 42.121.73.13
May  1 05:31:33 chinatsu sshd[22279]: input_userauth_request: invalid user support [preauth]
May  1 05:31:34 chinatsu sshd[22281]: Invalid user supporttest from 42.121.73.22
May  1 05:31:34 chinatsu sshd[22281]: input_userauth_request: invalid user supporttest [preauth]
May  1 05:31:36 chinatsu sshd[22283]: Invalid user supportuser from 42.121.73.13
May  1 05:31:36 chinatsu sshd[22283]: input_userauth_request: invalid user supportuser [preauth]
May  1 05:31:38 chinatsu sshd[22285]: Invalid user supportuser from 42.121.73.17

Are there plans to add support of ranges of IPs to fail2ban?

**Comment by leeclemens** [comment]
`whois` is not reliable. You really want to know the RIR's network in which the banned IP resides. There is no fuzzy logic, as those networks are absolutely defined. Caveat, if someone from Philly's Comcast subnet attacks you, should everyone using Comcast in Philly be banned?

I understand the intent and it has come up many times, but I've also seen someone block over 1/8th of the world in an attempt to block attacks using similar logic. For any bad actor within a subnet, there are exponentially more good actors (and potential customers, friends, etc).

I wish github had a "duplicate" flag. This type of thing has come up quite a bit, but the fundamental issue has never been resolved.

I suggest this be closed, as soon as fail2ban over-aggressively starts banning /8's is when it is no longer useful. Without a logical approach to banning subnets, this is counter productive.

**Comment by sebres** [comment]
Let's avoid duplicates, further in #927 (common issue for all subnet banning stuff now, WiP).
