### ISSUE TITLE
Purge database event occurred, message appearing each hour... 

### ISSUE THREAD

**Issue by scampuza** [fail2ban/fail2ban#2012]
_We will be very grateful, if your problem was described as completely as possible,
enclosing excerpts from logs (if possible within DEBUG mode, if no errors evident
within INFO mode), and configuration in particular of effected relevant settings
(e.g., with ` fail2ban-client -d | grep 'affected-jail-name' ` for a particular
jail troubleshooting).
Thank you in advance for the details, because such issues like "It does not work" 
alone could not help to resolve anything!
Thanks! (remove this paragraph and other comments upon reading)_

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

Fail2Ban v0.11.0.dev0
CentOS Linux release 7.4.1708 (Core)
Linux graylog1 3.10.0-693.11.1.el7.x86_64 #1 SMP Mon Dec 4 23:52:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Compiled from Sources

### The issue:

After I upgraded fail2ban to version 0.11.0, the following message is appearing each hour in the fail2ban log file:

"Purge database event occurred"

I kind of understand what this means, but I don't know for sure how this can affect fail2ban behavior.  

#### Steps to reproduce

Normal working of fail2ban

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
> but I don't know for sure how this can affect fail2ban behavior.

This is just informative, it says that observer thread is alive and got a purge event (fail2ban tries hourly to find obsolete entries in the database and deletes some entries older as `dbpurgeage`).

Changed to DEBUG level now (in 2deb356356f9cdebc940ad41964cf8045060ed27).
