### ISSUE TITLE
[apache filter] Hostname %s provided via SNI...

### ISSUE THREAD

**Issue by benrubson** [fail2ban/fail2ban#2017]
Hello,

Apache logs the following messages, I think it would be nice to add them into one of the Apache filters :
```
Hostname %s provided via SNI, but no hostname provided in HTTP request
Hostname %s provided via SNI and hostname %s provided via HTTP are different
Hostname %s provided via SNI and hostname %s provided via HTTP have no compatible SSL setup
```

I think it could definitely be a one-line rule :
`Hostname .* provided via SNI`

Many thanks 👍 

Ben

**Comment by sebres** [comment]
1. It is not really a failure in sence of fail2ban, we could add it optionally (e. g. for mode = aggressive), but...
2. As I can see, you don't be able to get the IP from this error lines (and the host-name from the request is a faked resp. foreign-input)...
```
[ssl:error] [pid 12345] AH02032: Hostname ... provided via SNI and hostname ... provided via HTTP are different
```
Thus, close. Let me know if I'm wrong.

**Comment by benrubson** [comment]
Thank you Serge for your answer.

1. well, I have plenty of them in my logs since about 3 months, and according to their timestamps, the domain given... these are clearly attack attempts.

2. you're right, in Apache 2.2 where I get these lines, client IP is not given. I just made the test with Apache 2.4, same behavior. I thought I had some log extracts with client IP available, but definitely no :)

Time for an Apache request then to add client IP, I'll come back here when/if done.

Thx 👍

**Comment by benrubson** [comment]
Hi @sebres,
Could we re-open this please ?
Apache has been patched accordingly : https://github.com/apache/httpd/commit/5300675e5ddd47b34073b949c9669d10fb0d0c9c
Patch tested, it works :
https://bz.apache.org/bugzilla/show_bug.cgi?id=62003#c8
Thank you 👍

**Comment by benrubson** [comment]
Thank you @sebres 👍 
Do you perhaps plan to add these 3 new rules ?
Or do you want me to push a PR ?
Thx !

**Comment by benrubson** [comment]
I've finally pushed a PR, #2097.
Thx 👍
