### ISSUE TITLE
Filter by emailinstaed of host/ip

### ISSUE THREAD

**Issue by pfarley1** [fail2ban/fail2ban#2033]
_We will be very grateful, if your problem was described as completely as possible,
enclosing excerpts from logs (if possible within DEBUG mode, if no errors evident
within INFO mode), and configuration in particular of effected relevant settings
(e.g., with ` fail2ban-client -d | grep 'affected-jail-name' ` for a particular
jail troubleshooting).
Thank you in advance for the details, because such issues like "It does not work" 
alone could not help to resolve anything!
Thanks! (remove this paragraph and other comments upon reading)_

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 
- [x] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

_Summary here_
I am trying to parse a listserv log for brute force logins. The error is a two line error and has no IP address. It looks like this
```
25 Jan 2018 21:34:41 From [ANONYMOUS]: X-LOGIN user@domain.com
25 Jan 2018 21:34:41 To   [ANONYMOUS]: ***BADPW***
```
#### Steps to reproduce
I started with version .8 but had problems with the date format so now I am at version .10
fail2ban-regex 0.10.3.dev1
I have not even setup the jail yet because I can not get the message to parse in regex. 
This is as far I have have got.
```
-bash-4.2$ fail2ban-regex -D -d "%d %b %Y %H:%M:%S" -v "/vendor/listserv/listserv.log" "From \[ANONYMOUS\]: X-LOGIN\s<F-ID>.*@.*<F-ID/>"

Running tests
=============

Use      datepattern : Day MON Year 24hour:Minute:Second
Use   failregex line : From \[ANONYMOUS\]: X-LOGIN\s<F-ID>.*@.*<F-ID/>
ERROR: Unable to compile regular expression 'From \[ANONYMOUS\]: X-LOGIN\s(?P<fid>.*@.*(?P<fid>\S+)'
```

#### Expected behavior
I would have thought this would matched on pretty much anything that has a @ in it. So far everything I have tried has given me this error. If I just use <F-ID/>to get the email address I don't get the error but I also do not get any matches.

#### Any additional information
All I am trying to do is count the number of bad logins per email and then I can block the email from further logins with another tool.
#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by pfarley1** [comment]
fail2ban-regex -D -d "%d %b %Y %H:%M:%S" -v "/vendor/listserv/listserv.log" "From \[ANONYMOUS\]: X-LOGIN\s<F-ID>.*@.*<F-ID/>"

**Comment by sebres** [comment]
1. you have used a wrong syntax in the close-tag: change `<F-ID/>` into `</F-ID>`...
2. Per default `fail2ban-regex` will try to resolve host-name to IP, so specify raw-option `-r`:
```bash
fail2ban-regex -r -d "%d %b %Y %H:%M:%S" -v "25 Jan 2018 21:34:41 From [ANONYMOUS]: X-LOGIN user@domain.com" "^\s*From \[ANONYMOUS\]: X-LOGIN\s<F-ID>.+</F-ID>$"
```
I've rewritten it a bit (anchored now, thus fewer vulnerable).

In the corresponding jail you should then also specify `usedns = raw`.

**Comment by pfarley1** [comment]
Thanks

**Comment by pfarley1** [comment]
I think I have this almost done but I am not seeing a problem with the action. I want to pass the <FID> to a shell script. I set the actions to 
My action file is 
/etc/fail2ban/action.d/ban_user.conf
[Definition]

actionban = /nfshome/pfarley/fail2ban/mail_test.sh <FID>

actionunban = /nfshome/pfarley/fail2ban/mail_test.sh <FID>


That runs but the bash shell in interpreter the < >  causes an error
Removing the <> just sends the literal string FID

How do I pass the FID as an argument to the script?

**Comment by sebres** [comment]
It is actually pretty good described in our wiki [How to ban something other as host (IP address), like user or mail, etc.](https://github.com/fail2ban/fail2ban/wiki/How-to-ban-something-other-as-host-(IP-address),-like-user-or-mail,-etc.)

But, you can use `<fid>` (note the **lower-case**, it's historical) as well as old tag `<ip>` (which is equal failure-id because you don't have ip address).
Only new tags (comming from filter) are available with newest tag prefox `<F-*>`.

For example, you can also take a look into my latest non-IP action - [action.d/nginx-block-map.conf](https://github.com/fail2ban/fail2ban/blob/0.10/config/action.d/nginx-block-map.conf#L106).

**Comment by pfarley1** [comment]
I made this change.

[Definition]

actionban = /nfshome/pfarley/fail2ban/mail_test.sh <fid> banned

actionunban = /nfshome/pfarley/fail2ban/mail_test.sh <fid> unbanned

Now my script returns

User FID was

It should be an my email address

So it is being passed FID instead of the email address am I missing something?

**Comment by pfarley1** [comment]
Got it, it required a restart to take effect

**Comment by sebres** [comment]
Note that if you've spaces in failure id better would be to use failure-id in double-qoutes:
```
[Definition]
actionban = /nfshome/pfarley/fail2ban/mail_test.sh "<fid>" banned 
actionunban = /nfshome/pfarley/fail2ban/mail_test.sh "<fid>" unbanned
```
> Got it, it required a restart to take effect

Nope, reload would be enough (reloads configs only, without stop/start):
```bash
?sudo? fail2ban-client reload
```

**Comment by pfarley1** [comment]
Thanks you have been great at helping this Newbe get it working
