### ISSUE TITLE
Reverse <ip> tag

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#2042]
My actions include an abuse contact:
https://toolbox.googleapps.com/apps/dig/#TXT/4.3.2.1.abuse-contacts.abusix.org

Could we add the reverse-ordered IP that is DNS lookup compatible?
For example `<rev-ip>`

It is easy to do it in shell for IPv4 but for IPv6 it's almost impossible.

https://github.com/fail2ban/fail2ban/blob/faab77cc7911135ceb9f90326c20cf3b454eab80/fail2ban/server/actions.py#L294-L314

**Comment by sebres** [comment]
How it should be different to already existing tag `<ip-rev>`?
Is this not DNS lookup compliant?
```bash
$ fail2ban-python -c 'from fail2ban.server.ipdns import IPAddr; print(IPAddr("1.2.3.4").getPTR(""))'
4.3.2.1.
```

**Comment by szepeviktor** [comment]
I think you line generates DNS traffic.
All I need is a reverse-ordered IP address.

**Comment by szepeviktor** [comment]
Is it possible to get python code in actions? I think you have to put it in a separate file.
A simple `<rev-ip>` would be straight-forward.

**Comment by sebres** [comment]
> I think you line generates DNS traffic.

Nope. 
It returns exactly reverse-ordered IP (no DNS involved here)...

https://github.com/fail2ban/fail2ban/blob/0.10/fail2ban/server/ipdns.py#L421-L440

> A simple `<rev-ip>` would be straight-forward.

You did not understood:
To get `command-needed-rev-ip '4.3.2.1.abuse-contacts.abusix.org.' `, you should just specify:
```
actionban = command-needed-rev-ip "<ip-rev>abuse-contacts.abusix.org."
```
Thats it.

**Comment by szepeviktor** [comment]
Oh!
Sorry.

Thanks.
