### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by weverp** [fail2ban/fail2ban#2045]
Having Fail2ban v0.9.6 installed on 17 machines (10 vps, 7 metal, web servers and db servers, ranging from hardly used to full production with 8Gb up to 64Gb RAM) with Centos 6 and 7 with the following jails

Status
|- Number of jail:      14
`- Jail list:   apache-auth, apache-badbots, apache-fakegooglebot, apache-modsecurity, apache-nohome, apache-noscript, apache-overflows, apache-shellshock, mysqld-auth, proftpd, recidive, selinux, sshd, sshd-ddos

it shows that on every(!) machine fail2ban uses around 2.4Gb of memory.
That seems quite a lot to me.

Disabling jails one by one seems that any jail uses around 100-150Mb (independent of type of backend).
Fail2ban with 1 jail (any of them) = 400Mb

Is this normal behavior?

**Comment by sebres** [comment]
> Fail2ban with 1 jail (any of them) = 400Mb

No matter which jail?

How many IP-addresses and failures do you've in this "example" jail?

How large is your fail2ban-sqlite database?

Version v.0.9 have a "bug" (no purge-db will be executed at all), so can you try to call it manually:
```bash
?sudo? python -c "dbpath='/var/lib/fail2ban/fail2ban.sqlite3'; import sys, logging; logging.basicConfig(stream=sys.stdout, level=logging.DEBUG); from fail2ban.server.database import Fail2BanDb; db = Fail2BanDb(dbpath); db.purge()"
```
Do you've some changes on memory usage hereafter?

**Comment by weverp** [comment]
Yes, I tried several on several machines, all around 400Mb with 1 random choosen jail.

Funny example: web servers don't have local mysql server. To keep jail.local the same for all machines for easy deployment I just create an empty /var/log/mysqld.log. Fail2ban with only mysqld-auth jail: 424Mb

```
fail2ban-server` (pid  25573) is running...
Status
|- Number of jail:      1
`- Jail list:   mysqld-auth
```
```
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
25573 root      20   0  424m 9932 2372 S  0.0  0.1   0:00.18 /usr/bin/python -Es /usr/bin/fail2ban-server -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid -x -b
```
The sqlite db was 70kb (before and after purge).
The command did not help.

**Comment by sebres** [comment]
> VIRT: 424m, RES: 9932, SHR: 2372 ...

So start of fail2ban with exactly one "dummy" jail (mysqld-auth) over empty log causes 9m/2m RES/SHR memory usage. 
VIRT (424m) represents how much memory the program is **able to access** at the present moment, so is virtual memory mapped into itself, so sum of all: files on disk that have been mapped into it (most notably shared libraries), memory shared with other processes, the video card’s RAM for the X server, etc.

Although it looks really unusually high (I tried the v. 0.9.6 with single jail and get VIRT=30288 only, on debian-server with 32GB).
Just to be sure this is not any kernel/or similar issue - what will you see if you just start python (e. g. as root)?

**Comment by weverp** [comment]
Starting a little python script gives me VIRT: 114m RES: 3780 SHR: 1780.
Little perl script: VIRT: 119m RES: 1768 SHR: 1404.
Just running sleep 25: VIRT: 98.5m  RES: 616  SHR: 532.

Guess I was a bit shocked by the 2Gb... but you're right, guess is some kind of other issue why VIRT is that high. Thanks!

**Comment by sebres** [comment]
Because fail2ban is multi-threaded, I assume that the VIRT (2Gb you see) is just a sum over all threads.

**Comment by r4kan** [comment]
I have a server running fail2ban v0.9 which has over 4GB in SQLite with logs prior 2018 in it. 

> ```shell
> ?sudo? python -c "dbpath='/var/lib/fail2ban/fail2ban.sqlite3'; import sys, logging; logging.basicConfig(stream=sys.stdout, level=logging.DEBUG); from fail2ban.server.database import Fail2BanDb; db = Fail2BanDb(dbpath); db.purge()"
> ```

I tried running it and it creates a fail2ban.sqlite3-journal file that grows to the same size as the original file and when the script ends the journal is deleted and the sqlite file has the same size as before. 

Any clues on what that could be? Is the whole db.purge() function broken in this version?

Thanks in advance!

**Comment by sebres** [comment]
1. Either you can try [vacuum](https://www.sqlite.org/draft/lang_vacuum.html) in hope it'll go smaller (I don't know the content of your database after purge, for example what exactly has been deleted):
```bash
?sudo? sqlite3 '/var/lib/fail2ban/fail2ban.sqlite3' 'vacuum;'
```
2. Or if you don't need the list of old banned tickets at all, you could copy jails/logs tables into new database:
```bash
## enter sudo shell:
?sudo -s?

## create new empty database (/tmp/fail2ban.sqlite3):
python -c "dbpath='/tmp/fail2ban.sqlite3'; import sys, logging; logging.basicConfig(stream=sys.stdout, level=logging.DEBUG); from fail2ban.server.database import Fail2BanDb; db = Fail2BanDb(dbpath);"

## then you will see something like this:
#  INFO:fail2ban.database:Connected to fail2ban persistent database '/tmp/fail2ban.sqlite3'
#  WARNING:fail2ban.database:New database created. Version '...'

## copy jails/logs tables:
sqlite3 /tmp/fail2ban.sqlite3 "attach database '/var/lib/fail2ban/fail2ban.sqlite3' AS orgdb; insert into jails select * from orgdb.jails; insert into logs select * from orgdb.logs;"

## now replace fail2ban database with new one:
mv -f /tmp/fail2ban.sqlite3 /var/lib/fail2ban/fail2ban.sqlite3
```
3. Or if you don't need everything, stop fail2ban and simply delete a database, it will be created by start.
Just note if your logs are large (and you don't use `tail` option by `logpath`), the initial scan can take a long time (especially in v.0.9). So better use variant 2 in this case.

And last but not least - upgrade to the newest fail2ban version (0.9 is too old) and also note #2402 as a solution for similar issue #2118.

**Comment by r4kan** [comment]
Thanks I'll try that tomorrow!

I'm also considering the update, is this problem fixed in 0.10?

**Comment by sebres** [comment]
> is this problem fixed in 0.10?

What "this problem" exactly is? If you mean the database/memory growth, then yes (it is "fixed", if you'd set `dbmaxmatches` and `maxmatches` in the configs as described in #2402). Note this version is not yet release (but you could try the version from github).
If you mean the auto-purge - no, I think, it got "fixed" firstly in 0.11.

**Comment by r4kan** [comment]
Can you tell the difference between dbfile equals `:memory:` and `None` and any of those two impact in the memory consumption? Maybe i can just disable it if it's only task is keeping logs and saving ip's to re-list on restart/reboot. 

Thanks for all the answers!

**Comment by sebres** [comment]
Memory? Nothing of both would help against high memory usage (vise versa `:memory:` would eat still more). In order to save the memory, only `maxmatches = 0`  of newest version would help at the moment.
The database holds the failures of IP and also used to save the last positions of logs, to avoid rescan in restart case.
If you don't need the IP/tickets info, `dbmaxmatches = 0` would be your choice (and it saves the database size).
If you mean disk size, then you could disable the database, but the restart could then take longer (log-rotate or usage of `tail` option of `logpath` in each jails could help here).
