### ISSUE TITLE
Failed to change log target

### ISSUE THREAD

**Issue by zhenqidong** [fail2ban/fail2ban#2047]
====version===========
$ fail2ban-client -V
Fail2Ban v0.9.7

Copyright (c) 2004-2008 Cyril Jaquier, 2008- Fail2Ban Contributors
Copyright of modifications held by their respective authors.
Licensed under the GNU General Public License v2 (GPL).

Written by Cyril Jaquier <cyril.jaquier@fail2ban.org>.
Many contributions by Yaroslav O. Halchenko <debian@onerussian.com>.

====configuration (default) ===============

```
[Definition]

# Option: loglevel
# Notes.: Set the log level output.
#         CRITICAL
#         ERROR
#         WARNING
#         NOTICE
#         INFO
#         DEBUG
# Values: [ LEVEL ]  Default: ERROR
#
loglevel = INFO

# Option: logtarget
# Notes.: Set the log target. This could be a file, SYSLOG, STDERR or STDOUT.
#         Only one log target can be specified.
#         If you change logtarget from the default value and you are
#         using logrotate -- also adjust or disable rotation in the
#         corresponding configuration file
#         (e.g. /etc/logrotate.d/fail2ban on Debian systems)
# Values: [ STDOUT | STDERR | SYSLOG | FILE ]  Default: STDERR
#
###logtarget = /var/log/fail2ban.log
logtarget = /var/log/fail2ban.log
```

====os ==============
   Static hostname: ip-172-31-49-66.ec2.internal
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 609bbd29e32a4898e604f49bff82a88c
           Boot ID: 46524ce817734f8b9cca1ba8f3f3aa62
    Virtualization: xen
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-693.11.6.el7.x86_64
      Architecture: x86-64
====issue==============

INFO   Loading configs for fail2ban under /etc/fail2ban 
DEBUG  Reading configs for fail2ban under /etc/fail2ban 
DEBUG  Reading config files: /etc/fail2ban/fail2ban.conf
INFO     Loading files: ['/etc/fail2ban/fail2ban.conf']
Level 7     Reading file: /etc/fail2ban/fail2ban.conf
INFO     Loading files: ['/etc/fail2ban/fail2ban.conf']
Level 7     Shared file: /etc/fail2ban/fail2ban.conf
INFO   Using socket file /var/run/fail2ban/fail2ban.sock
DEBUG  OK : 'pong'
INFO   Loading configs for jail under /etc/fail2ban 
DEBUG  Reading configs for jail under /etc/fail2ban 
DEBUG  Reading config files: /etc/fail2ban/jail.conf, /etc/fail2ban/jail.d/00-firewalld.conf
INFO     Loading files: ['/etc/fail2ban/jail.conf']
Level 7     Reading file: /etc/fail2ban/jail.conf
INFO     Loading files: ['/etc/fail2ban/paths-fedora.conf']
Level 7     Reading file: /etc/fail2ban/paths-fedora.conf
INFO     Loading files: ['/etc/fail2ban/paths-common.conf']
Level 7     Reading file: /etc/fail2ban/paths-common.conf
INFO     Loading files: ['/etc/fail2ban/paths-overrides.local']
Level 7     Reading file: /etc/fail2ban/paths-overrides.local
INFO     Loading files: ['/etc/fail2ban/jail.d/00-firewalld.conf']
Level 7     Reading file: /etc/fail2ban/jail.d/00-firewalld.conf
INFO     Loading files: ['/etc/fail2ban/paths-common.conf', '/etc/fail2ban/paths-fedora.conf', '/etc/fail2ban/jail.conf', '/etc/fail2ban/jail.d/00-firewalld.conf']
Level 7     Shared file: /etc/fail2ban/paths-common.conf
Level 7     Shared file: /etc/fail2ban/paths-fedora.conf
Level 7     Shared file: /etc/fail2ban/jail.conf
Level 7     Shared file: /etc/fail2ban/jail.d/00-firewalld.conf
DEBUG  OK : None
DEBUG  OK : 'auto'
DEBUG  OK : 'INFO'
ERROR  NOK: ('Failed to change log target',)
DEBUG  OK : '/var/lib/fail2ban/fail2ban.sqlite3'
DEBUG  OK : 86400

btw, setting logtarget to STDERR is okay though

**Comment by sebres** [comment]
fail2ban-client -d | grep logtarget

what is the output?
