### ISSUE TITLE
Several badips.py actions, but ban only one time

### ISSUE THREAD

**Issue by benrubson** [fail2ban/fail2ban#2053]
Hi,

Let's imagine the following configuration :
```
action = %(action_)s
         badips.py[actname="b1", category="ssh", banaction="%(banaction)s", score="3", age="24h"]
         badips.py[actname="b2", category="ssh", banaction="%(banaction)s", score="0", age="48h", bankey="01234ABCDE"]
```

Goal is to retrieve and ban "community" bans with score 3, and retrieve and ban _all_ my bans.
It works perfectly.
However, when action is launched to ban an IP newly detected by fail2ban, 2 banips API calls are made to report the IP, which is useless and counter-productive.

I did not found a way to keep both badips.py actions, but report only once.

Any way ?

Thank you very much 👍 

Ben

**Comment by benrubson** [comment]
I went with the following workaround :
- a jail which bans and report ;
- a _dummy_ jail with no filter, but which retrieves all "community" bans (see #2056) ;
- a second _dummy_ jail with no filter, which retrieves my bans.

So feel free to close this is there is no other solution.

Thx 👍

**Comment by sebres** [comment]
I believe specifying of 2 actions here is wrong.
If you really need it, rather `badips.py` should be extended to act with different set of parameters on local/community bans.
I mean something like:
```INI
action = %(action_)s
         badips.py[category="ssh", banaction="%(banaction)s", score="3", age="24h", local-score="0", local-age="48h" ....]
```

But, I don't understand at all, why do you need to "retrieve and ban all my bans" via badips.
Fail2ban has own mechanism to hold (e. g. restore after restart) all active bans (in local sqlite database), which works well.
Could you explain please for which purposes do you need it exactly?

**Comment by benrubson** [comment]
I share the same `bankey` on several servers.
As soon as one server bans an IP, the IP is retrieved by all the other servers thanks too the `bankey` and `score=0`, which is really convenient 👍 
However, I don't want to retrieve all other "community" with score 0, this is why I use 2 badips.py actions.

**Comment by sebres** [comment]
Admittedly I don't think the preventive banning (without any attempt on the other servers) is a good idea at all (because it just clutters your ip-sets/ip-tables with many unneeded values, which will possible never do any attempt on all this servers)... 
Surely do you know, that this makes your whole network sub-system slower?

But I'll check later, what we can do here.

**Comment by benrubson** [comment]
Don't bother with this and feel free to close if I'm the only requester, as I implemented solution described in my second post.

I was also curious about performance.
I did a test between 2 FreeBSD servers, with `ipfw` containing about 25000 (!) banned IPs loaded in its lookup table : I did not notice any performance degradation, nor CPU or memory usage increase, at a sustained 40 Gb/s throughput.
Unfortunately I currently don't have the hardware / software to perform the same test on Linux/iptables.

**Comment by sebres** [comment]
> I did not notice any performance degradation

You should measure connection buildup process only (because only new connections are affected, so for example you will be not able to see anything on keep-alive connections).

On the other hand, what, do you think, happens if your jail start to ban this 25000 community-IP's? 
I've my doubt, it will immediately ban real failed attempts, occurred in this time on your server. 
At least if I correct interpret the source code of badips.py.

**Comment by benrubson** [comment]
Sure, 25000 IPs was for testing purpose with `score=0` and `age=48h`.
With `score=1` and `age=24h`, we have less than 200 IPs.

**Comment by benrubson** [comment]
> You should measure connection buildup process only (because only new connections are affected, so for example you will be not able to see anything on keep-alive connections).

At this time, my `ipfw` was looking through the lookup table before checking state :

```
# ipfw show
00111         0              0 deny ip from table(1) to me
10301      1974         191897 allow ip from any to any in via lo0
10302       384         128297 allow ip from any to any out via lo0
20001         0              0 check-state
(...)
```

**Comment by benrubson** [comment]
Let's close this for the moment to avoid bothering U with such a specific configuration.
And thank you for your feedback Sergey 👍
