### ISSUE TITLE
Deluge - Filter config

### ISSUE THREAD

**Issue by yannCRSR** [fail2ban/fail2ban#2063]
Hi,

I want to create a filter for Deluge (Thin Client).
This is a failed login:
```
[INFO    ] 16:19:58 rpcserver:206 Deluge Client connection made from: 1.2.3.4:12345
[ERROR   ] 16:19:58 rpcserver:268 Password does not match
```

My deluge.conf looks as follows:
```
[INCLUDES]
before = commmon.conf

[DEFINITION]
_daemon = deluge
failregex = .*Deluge Client connection made from: <HOST>.*\n.*Password does not match
```

Now when I try to test it, I get this output:
```
Running tests
=============

Use   failregex filter file : deluge, basedir: /etc/fail2ban
Use         log file : /var/log/deluge/daemon.log
Use         encoding : UTF-8


Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:

Lines: 519 lines, 0 ignored, 0 matched, 519 missed [processed in 0.04 sec] 
Missed line(s): too many to print.  Use --print-all-missed to print all 519 lines
```

The logfile contained several entries (failed logins) like the one shown above. But zero matched. 
I'm running Ubuntu 16.04 with Fail2Ban v0.9.3. Is my RegEx wrong or am I missing something else?

Any help greatly appreciated,
Cheers!

**Comment by sebres** [comment]
This is not possible for exactly this case (also not via multiline syntax).
You'll need some unique identifier (connection-id, session-id, pid, etc.) for the connection.

Just imagine you get 2 connections (one from good user and one from the offender):
```
[INFO    ] 16:19:57 rpcserver:206 Deluge Client connection made from: 4.2.3.1:12345
[INFO    ] 16:19:58 rpcserver:206 Deluge Client connection made from: 1.2.3.4:12345
[ERROR   ] 16:19:59 rpcserver:268 Password does not match
[INFO    ] 16:19:59 rpcserver:XXX Password accepted
```
Which IP address had authentication failure?

If you can change log-format (to log additionally something like socket-id), please change it and see  #1966 for good example how you can configure such filter.
If you cannot organize logging of connection-id, you should create a change-request for this rpcserver, e. g.:
```diff
- Password does not match
+ Authentication failed from 1.2.3.4: Password does not match
```
