### ISSUE TITLE
IPv6: hostsdeny actionban writes IP in the wrong format

### ISSUE THREAD

**Issue by iain-buclaw-sociomantic** [fail2ban/fail2ban#2066]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): v0.10.2
- OS, including release name/version: Ubuntu 
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

IPv6 addresses are not added correctly to host.deny file.

#### Steps to reproduce

Configure ban action as `hostsdeny`, then ssh over IPv6 multiple times to trigger it.

#### Expected behavior

You get banned, and is observable on the next ssh attempt.

#### Observed behavior

You don't get banned.

#### Any additional information

Looking in `/etc/hosts.deny`, I can see the IPv6 address was added, but it's in the wrong format.

```
ALL: IP:6:ADDRESS::
```
The correct format as per hosts_access manpage is:
```
ALL: [IP:6:ADDRESS::]
```
Note the addition of square brackets.

### Configuration, dump and another helpful excerpts

Looking at hostsdeny.conf, I can see how it writes new entries.

```
actionban = IP=<ip> && printf %%b "<daemon_list>: $IP\n" >> <file>
actionunban = IP=$(echo <ip> | sed 's/\./\\./g') && sed -i "/^<daemon_list>: $IP$/d" <file>
```

Both of these could be updated to handle both IPv4 and IPv6.

But I suspect it would be easier to add an `actionban6` and `actionunban6` setting to handle the address format explicitly, as per #1123.

**Comment by iain-buclaw-sociomantic** [comment]
This would be one way, and that doesn't require `actionban6`/`actionunban6`.  However the line is getting rather long now.

```
actionban = IP=$(echo <ip> | awk '/:/{print "["$0"]"; next}{print}') && printf %%b "<daemon_list>: $IP\n" >> <file>
actionunban = IP=$(echo <ip> | awk '/:/{print "\\["$0"\\]"; next}{print}' | sed 's/\./\\./g') && sed -i "/^<daemon_list>: $IP$/d" <file>
```

**Comment by sebres** [comment]
We've conditional sections that allow to use parameters corresponding family.
In this case it should be something like:
```INI
[Definition]
...
actionban = <_set_ip_var> && printf %%b "<daemon_list>: $IP\n" >> <file>

[Init]
_set_ip_var = IP=<ip>

[Init?family=inet6]
_set_ip_var = IP=[<ip>]
```

**Comment by iain-buclaw-sociomantic** [comment]
Good to know!  That would make it easier to add then.

**Comment by iain-buclaw-sociomantic** [comment]
So I think this would be:
```
actionban = <_set_ip_var> && printf %%b "<daemon_list>: $IP\n" >> <file>
actionunban = IP=$(echo <_set_ip_var> | sed 's/\([][\.]\)/\\\1/g') && sed -i "/^<daemon_list>: $IP$/d" <file>
```
Just needs an adjustment in the unban action to escape the square brackets.
