### ISSUE TITLE
jails for mulitple ports

### ISSUE THREAD

**Issue by Anju-Krish** [fail2ban/fail2ban#2076]
_We will be very grateful, if your problem was described as completely as possible,
enclosing excerpts from logs (if possible within DEBUG mode, if no errors evident
within INFO mode), and configuration in particular of effected relevant settings
(e.g., with ` fail2ban-client -d | grep 'affected-jail-name' ` for a particular
jail troubleshooting).
Thank you in advance for the details, because such issues like "It does not work" 
alone could not help to resolve anything!
Thanks! (remove this paragraph and other comments upon reading)_

### Environment: 

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 
- [x ] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

_Summary here_

I am trying to see if its possible to have 2 differnt jails for the same service, but using different ports.

#### Steps to reproduce
```
[proftpd-iptables]

enabled  = false
filter   = proftpd
action   = iptables[name=ProFTPD, port=xyz, protocol=tcp]
           sendmail-whois[name=ProFTPD, dest=you@example.com]
logpath  = /var/log/proftpd/proftpd.log
maxretry = 6

[proftpd-iptables]

enabled  = false
filter   = proftpd
action   = iptables[name=ProFTPD, port=abc, protocol=tcp]
           sendmail-whois[name=ProFTPD, dest=you@example.com]
logpath  = /var/log/proftpd/proftpd.log
maxretry = 6
```

#### Expected behavior

Ideally i want fail2ban to block an IP if they try 6 invalid attempts to  port abc.

And same behaviour only if invalid attempts perfromed to port xyz.

#### Observed behavior

In this case it picks up only the first jail. 

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
> if they try 6 invalid attempts to port abc.
> same behaviour only if invalid attempts perfromed to port xyz.

1. Apparently the actions do nothing with filter: filter detects failures, action does the handling e. g. bans only). 
You should rewrite regular expression `failregex` of the filter (or specify different logpath for both ports).
Anyway your change must affect the filter, not the action only.

2. If you want to use 2 jails, you should get different names (sections) for both jail. Otherwise as in your case currently one section overwrites another.
```INI
[proftpd-iptables1]
...
[proftpd-iptables2]
...
```
BTW. Note we've iptables-multiport action (which can ban multiple ports at the same time).
