### ISSUE TITLE
sshd filter regex "ROOT LOGIN REFUSED"

### ISSUE THREAD

**Issue by thelegy** [fail2ban/fail2ban#2080]
### Environment:

- Fail2Ban version (including any possible distribution suffixes):
  - Fail2Ban v0.10.3.dev1 (built from this git repo with branch 0.10)
  - Fail2Ban v0.11.0.dev1 (built from this git repo with branch 0.11)
- OS, including release name/version:
```
 # cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

When someone tries to log into my server with the root user it does not get registered by fail2ban. I believe it is caused by the logmessages not being covered by the regex.

#### Steps to reproduce

1. install fail2ban
2. enable sshd jail
3. disable root login in ssh. e.g. add `PermitRootLogin forced-commands-only` to the `/etc/ssh/sshd_config`
3. try to ssh on the server as root

#### Expected behavior

I would expect to see an `fail2ban.filter  [xyz]: INFO [sshd] Found a.b.c.d - timestamp` line in the logs and finally a ban after some tries.

#### Observed behavior

Fail2ban does not care.

#### Any additional information

The logs from sshd look like: (taken from the journal)
```
Mar 15 16:11:27 myserver sshd[1234]: ROOT LOGIN REFUSED FROM 1.2.3.4 port 12345
Mar 15 16:11:27 myserver sshd[1234]: ROOT LOGIN REFUSED FROM 1.2.3.4 port 12345 [preauth]
```

The regex provided at [config/filter.d/sshd.conf#L38](https://github.com/fail2ban/fail2ban/blob/master/config/filter.d/sshd.conf#L38) is almost cathing the lines. It looks like
```
^<F-USER>ROOT</F-USER> LOGIN REFUSED.* FROM <HOST>\s*%(__suff)s$
```
When I change the line to
```
^<F-USER>ROOT</F-USER> LOGIN REFUSED.* FROM <HOST>\s*%(__on_port_opt)s%(__suff)s$
```
it catches my logs. But this time both lines will be counted, so one login try results in 2 strikes. I think a change like that sould be in the default configs, but maybe someone knows how to fix the double counting before...

**Comment by sebres** [comment]
Thanks for notice.
I'll fix it later.

As regards the dual counting: it would be indeed possible, two ways:
- either the suffix (`[preauth]`) becomes mandatory, but unfortunatelly it would be not fully backwards-compatible;
- or (>=0.10 only) if this regex will not count direct failure (using `<F-NOFAIL>`) and causes failure later if still not logged; but this is too cumbersome, in my opinion.

I think, if root is disallowed at all, and someone still want to login as root, it does no matter when such intruders will be banned a bit earlier.
