### ISSUE TITLE
How does the application read error logs?

### ISSUE THREAD

**Issue by OlegNKor** [fail2ban/fail2ban#2086]
How does the application read error logs?

### Environment:
- Fail2Ban v0.11.0.dev1
- Ubuntu Server 16.04: 
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:
I do not understand the mechanism for reading logs while restarting the application

#### Steps to reproduce

# fail2ban-client restart

#### Relevant lines from monitored log files in question:
During the restart Fail2Ban, the log is written with information

`INFO    Added logfile: '/var/log/nginx/access.log' (pos = 292489, hash = 2d0bd29eac5d1bef09d6d55ca2edb173)`

This information in the error log leads me to the idea that Fail2Ban v0.11.0.dev1 does not read error logs from the beginning of the file when restarting, but starts scanning them from some position (parameter - pos = 292489).

If this is the case, then force Fail2Ban v0.11.0.dev1 when **fail2ban-client restart** to scan the error log from the beginning of the file, or not?.

I can not test any line of a regular expression. While all the regular expression editors find my desired value, except fail2ban ... For example, from the line:
```
124.238.60.129 - - [18/Mar/2018:12:02:55 +0200] "GET /?option=com_k2&view=itemlist&task=user&id= HTTP/1.1" 303 5 "-" "Mozilla/5.0 (Wind
```
My regular expression does **not find anything**, although this entry is in the error log.
```
^<HOST> - .*(GET|POST|HEAD).*?option=com_k2&view=itemlist&task=user&id=.* 303 .*$
```
I will be grateful to everyone ...
Oleg

**Comment by sebres** [comment]
> Fail2Ban does not read error logs from the beginning of the file

This is right since 0.9.x (since fail2ban supports sqlite-database, where it holds the last log-offset).
The question is why it need to read the log-lines, which were already processed before restarted.
Note also, you don't need to restart fail2ban to supply new configuration - use `fail2ban-client reload` instead of. And to test your regex you could use `fail2ban-regex`.

> My regular expression does not find anything, although this entry is in the error log.

You can use `fail2ban-regex <log-file|log-line> <expr>` to check it works.

Your expression (although IMHO a bit vulnerable) works for me on this log-line:
```bash
log='124.238.60.129 - - [18/Mar/2018:12:02:55 +0200] "GET /?option=com_k2&view=itemlist&task=user&id= HTTP/1.1" 303 5 "-" "Mozilla/5.0 (Wind'
fail2ban-regex "$log" '^<HOST> - .*(GET|POST|HEAD).*?option=com_k2&view=itemlist&task=user&id=.* 303 .*$'
```
results in:
```
Lines: 1 lines, 0 ignored, 1 matched, 0 missed
```
<details>

```
Running tests
=============

Use   failregex line : ^<HOST> - .*(GET|POST|HEAD).*?option=com_k2&view=i...
Use      single line : 124.238.60.129 - - [18/Mar/2018:12:02:55 +0200] "G...


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] ^<HOST> - .*(GET|POST|HEAD).*?option=com_k2&view=itemlist&task=user&id=.* 303 .*$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] Day(?P<_sep>[-/])MON(?P=_sep)ExYear[ :]?24hour:Minute:Second(?:\.Microseconds)?(?: Zone offset)?
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.06 sec]
```
</details>
<br/>

Note:

- `.*$` makes no sense at all, so either remove it or do it more precise
- don't use catch-alls like `.*`
- don't use capture groups `(...)`, use `(?:...)` instead of

```diff
- ^<HOST> - .*(GET|POST|HEAD).*?option=com_k2&view=itemlist&task=user&id=.* 303 .*$
+ ^<HOST> - [^"]*"(?:GET|POST|HEAD) [^"]*?option=com_k2&view=itemlist&task=user&id=[^"]*" 303\b

**Comment by OlegNKor** [comment]
**Thank you for your reply** You helped me a lot.

> The question is why it need to read the log-lines, which were already processed before restarted.

**This was not necessary for fail2ban, it was necessary for me**.
I wanted to connect a new Regular expression to the string filter that occurs in my error logs, and I wanted to test it to make sure that it works, because that line does not hit often and there is simply no time to wait.
I thought that when you restart, fail2ban rereads the log first.
Now I understand why I could not immediately verify the performance of my "JAIL's".

I must specially initialize the error from another host to make sure it works. Or expect when this will happen next time from hacking
And it would not be bad that fail2ban the test mode, which would read the magazine first, should not be expected when the collar again knock at you ... and notice that your RegEx works or does not work.

Thank you for the clarification, now I understand how it works.
**I'll try your advice on testing RegEx**
Regards,
Oleg

**Comment by sebres** [comment]
> And it would not be bad that fail2ban the test mode, which would read the magazine first, should not be expected when the collar again knock at you ... 

But we've it already:
```
fail2ban-regex single-log-line        your-filter
fail2ban-regex /path/to/your-log-file your-filter
fail2ban-regex systemd-journal        your-filter
```
Or what did you meant exactly as test mode?

**Comment by OlegNKor** [comment]
**Thank you for your reply** You helped me a lot.

> The question is why it need to read the log-lines, which were already processed before restarted.

**This was not necessary for fail2ban, it was necessary for me**.
I wanted to connect a new Regular expression to the string filter that occurs in my error logs, and I wanted to test it to make sure that it works, because that line does not hit often and there is simply no time to wait.
I thought that when you restart, fail2ban rereads the log first.
Now I understand why I could not immediately verify the performance of my "JAIL's".

I must specially initialize the error from another host to make sure it works. Or expect when this will happen next time from hacking
And it would not be bad that fail2ban the test mode, which would read the magazine first, should not be expected when the collar again knock at you ... and notice that your RegEx works or does not work.

Thank you for the clarification, now I understand how it works.
I'll try your advice on testing RegEx
Regards,
Oleg

**Comment by OlegNKor** [comment]
Yes, thank you, I understand.

What you indicated to me, it is suitable for a test of regular expressions. I now use it. And my problem is solved, there are no questions.

**As a wish:**
But in my opinion, it would not be bad if the application can have one "JAIL" for the test (by default) so that it can be tested from the system. Not only how will the regular expression work on it, but how will the "action" or "banaction" work so that it can be made to read the entire error log for a more accurate test of the whole mechanism.

**Comment by sebres** [comment]
> As a wish...

This was already desired here - #2036

**Comment by OlegNKor** [comment]
I think that everything could be easier.

Simply it is necessary to enter parameters in "JAILS" parameters:

> # status = test     
(or comment line, delete line, status = normal)

If you install any "jail" in the jail.local ---- status = test, the application should emulate the real work, go through the entire real (working) cycle without performing any changes in the system (reading the real error log from the first line), and would generate a separate error log file, for example, a file2ban-test.log in which to describe all possible behavioral or erroneous actions of the tested object.

Everything must happen when the system is restarted, preferably in the form:

> # fail2ban-client-test restart

or  in the usual way:

>  # fail2ban-client restart

But to the elements marked with the flag of the status test, only test actions would be performed.

A kind of masquerade, with all the possibilities for writing errors in the test log. This error log could be analyzed in a text editor, or just like a real one:

> # tail -f -n +20 /var/log/fail2ban-test.log

Thus, you can not use command line restrictions, or the command line, and test the Element normally in the application workflow.

For example, such a test mode, you could specify any error log file, even if it's old, so that it still reads it all from the first line (just as an array of rows for the test), and not as a working system, with the " status = normal "or let it be called" working "and" test ", it does not matter.

I think this will give an opportunity to try everything you like without fear of badly affecting the system as a whole, at the same time having an imitation of the workflow with documenting a separate "JAIL's"

In addition, you will be able to see how the application reacts to all included in the fileregex, ALL conditions of regular expressions simultaneously, for everything in general and for one pass of the test.

**Comment by sebres** [comment]
> I think that everything could be easier.

You're wrong - the way you decribe is not easier.

> If you install any "jail" in the jail.local ---- status = test, the application should emulate the real work, 

I think you just don't imagine which cost has such kind of "emulation"...

Back to the log-file possition after restart resp. action-test possibility: you can do it also with many another ways:
- using option `head` after log file name in option `logpath`;
- using logging-simulation (via direct write or command `logger`), for example to simulate pam-generic:
```bash
logger -t 'test:auth' -i -p auth.info "pam_unix(test:auth): authentication failure; logname= uid=0 euid=0 tty=test ruser= rhost=192.0.2.1"
```
- using manually ban/unban like:
```bash
fail2ban-client set "$jail" banip "$ip";
sleep 2;
fail2ban-client set "$jail" unbanip "$ip"
```
- using restart by some active bans - after restart all active bans will be restored (banned again);
