### ISSUE TITLE
ssh-iptables pattern doesn't match 'Invalid user' line which includes port

### ISSUE THREAD

**Issue by aa599** [fail2ban/fail2ban#2094]
### Environment:

- Fail2Ban version (including any possible distribution suffixes):
0.8.10-3.6.amzn1

- OS, including release name/version: 
Amazon Linux AMI / 2017.09 (4.9.85-38.58.amzn1.x86_64)

- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

ssh invalid user logs aren't matched in this environment due to remote port information on the log line

#### Steps to reproduce

enable ssh-iptables in jail.local
attempt ssh login as user not listed in sshd_config "AllowUsers"

#### Expected behavior

Excessive attempts to ssh as invalid users should be banned

#### Observed behavior

They aren't

#### Any additional information

In filter.d/sshd.conf, replacing

            ^%(__prefix_line)s[iI](?:llegal|nvalid) user .* from <HOST>\s*$

with

            ^%(__prefix_line)s[iI](?:llegal|nvalid) user .* from <HOST>(?: port \d*)\s*$

matches the lines as expected

#### Relevant lines from monitored log files in question:
Mar 24 15:01:19 hostname sshd[11480]: Invalid user admin from 191.96.249.80 port 60581

**Comment by sebres** [comment]
Already fixed, see 7805f9972d361eeb9ded6eabd69d84a7618c0fe7.

BTW. Version 0.8 is too old and should be really updated.

**Comment by aa599** [comment]
Thanks for the reply.
I suspected I wouldn't have been the first to find it :-)
v0.8 is the version in the amazon main repo, so I suppose I need to try to get amazon to include a later version in there.
