### ISSUE TITLE
Fail2ban AbuseIPBD with deferred send ... how???

### ISSUE THREAD

**Issue by OlegNKor** [fail2ban/fail2ban#2095]
Greetings to all.

Somewhere I met here a conversation about the possibility of sending automatic messages with a delay for a specified time or putting it on the queue with deferred sending ...

The fact is that AbuseIPDB receives reports of wrecking not more often than one in fifteen minutes. In this regard, when you turn on

# action = % (action_abuseipdb)s ................

  the system simply overwhelms with errors ...

> Level 39 b59e4020 -- exec: curl --fail --ciphers ecdhe_ecdsa_aes_256_sha --data 'key=yWhdNwi3yVp7******YPtupLbphOQWEdTq4' --data-urlencode 'comment=Automatically reported by fail2ban report script.' --data 'ip=92.212.36.9' --data 'category=4,18,22' "https://www.abuseipdb.com/report/json"
>**ERROR   b6320a88 -- stderr: 'curl: (22) The requested URL returned error: 429 Too Many Requests'**

Tell me how to implement postponed sending of reports on wrecking. Or give a link to a topic about this.

I will be grateful to everyone for their help.

**Comment by sebres** [comment]
> Tell me how to implement postponed sending of reports on wrecking.

Write to a file and send with latency via cron?
