### ISSUE TITLE
fail2ban-server  ERROR: invalid syntax (ipdns.py, line 288)

### ISSUE THREAD

**Issue by tpgxyz** [fail2ban/fail2ban#2096]
### Environment:

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version:  OpenMandriva Lx 3.03
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

fail2ban does not work with python3 with 2to3 use.

[tgajc@abf-monkey ~]$ fail2ban-server 
ERROR: invalid syntax (ipdns.py, line 288)

#### Observed behavior
[tgajc@abf-monkey ~]$ fail2ban-server 
ERROR: invalid syntax (ipdns.py, line 288)

#### Any additional information
Sources for RPM
https://github.com/OpenMandrivaAssociation/fail2ban

#### Any customizations done to /etc/fail2ban/ configuration
2to3

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
You've installed Fail2Ban via distribution mechanisms? So why you want to switch python version for Fail2Ban?

> fail2ban does not work with python3 with 2to3 use.

You're wrong - this work pretty good (each time someone pushed a PR or new commits here, our test-suite does it again and again for several python3 versions, for example see [last build of 0.10](https://travis-ci.org/fail2ban/fail2ban/jobs/356781750#L520)).

Please note that 2to3 should be executed inside the installation directory (before you install it) and then you should start setup.py with python3 also.

**Comment by tpgxyz** [comment]
@sebres Thanks for your answer. Well at least you could wait with closing this after my response.

Anyways i've provided a link to our fail2ban sources, and if you could only look on it you could find in fail2ban.spec file :

2to3 --write --nobackups .
find -type f -exec sed -i -e '1s,^#!/usr/bin/python *,#!/usr/bin/python3,' {} +

%build
%serverbuild_hardened
env CFLAGS="%{optflags}" %{__python3} setup.py build

%install
%{__python3} setup.py install --root=%{buildroot}


Please tell me what i'm doing wrong, and why fail2ban does not start with py3 ?

**Comment by sebres** [comment]
> Well at least you could wait with closing this after my response.

I could, but I was and I'm still sure - it works, at least if it will be normally installed.
As already said exactly this way it works in our CI test-suite with all kinds of python3 versions (3.3 - 3.7).

> Please tell me what i'm doing wrong

Normally the fail2ban-server (as well as the client) uses the default python version.
Please note also 2to3 does not update execve-interpreter header.
So what do you see if you do `/usr/bin/env python --version`?
If it returns 2.x, it will try to execute your updated to 3.x version of fail2ban under python2 (and fails surely).
So in this case you should replace execve-interpreter header (the first line) of any script fail2ban-* in bin folder with something like `#!/usr/bin/python3` (or with our helper `fail2ban-python`, see below).

Could you also check please which python-version you'll see if you execute `fail2ban-python --version`.
The helper `fail2ban-python` should be installed as link to your current python version (used with install).
If it returns 2.x, so indeed it can be an issue of our setup.py (and I'll reopen this).
Additionally check which version you'll see by calling of `%{buildroot}/bin/fail2ban-python`.

I don't know (and have no time to check) what exactly may be wrong with your setup scripts...
But can you please get the clean copy and check it as in example below:
```bash
cd /tmp/
git clone -b 0.10 https://github.com/fail2ban/fail2ban.git
cd fail2ban
./fail2ban-2to3
python3 bin/fail2ban-testcases -fn
```
If it works, then it may be indeed something wrong with the scripts you used.

**Comment by sebres** [comment]
I extended fail2ban-2to3 in 5bf80fefa9dee02aae0fa64a865ec2a8ca529b07... 
Could you please check this amendment solves your issue?
