### ISSUE TITLE
testCymruInfoNxdomain test fails on CentOS 7

### ISSUE THREAD

**Issue by Ziris85** [fail2ban/fail2ban#2098]
Hello,

### Environment:

- Fail2Ban version (including any possible distribution suffixes): `0.10.2`
- OS, including release name/version: `CentOS Linux release 7.4.1708 (Core)`
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

This looks to be the same problem as #1841, but since I'm using the latest version (`0.10.2`), I figured I'd open a new issue ticket. Situation is the same - creating an RPM package and test fails on:
```
testCymruInfoNxdomain (fail2ban.tests.banmanagertestcase.StatusExtendedCymruInfo) ... FAIL

======================================================================
FAIL: testCymruInfoNxdomain (fail2ban.tests.banmanagertestcase.StatusExtendedCymruInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/scl/rpmbuild/BUILD/fail2ban-0.10.2/fail2ban/tests/banmanagertestcase.py", line 209, in testCymruInfoNxdomain
    "rir": ["nxdomain", "arin"]}, level=-1, key=str)
  File "/home/scl/rpmbuild/BUILD/fail2ban-0.10.2/fail2ban/tests/utils.py", line 542, in assertSortedEqual
    self.fail(msg)
AssertionError: ['nxdomain', 'US', 'US'] != ['nxdomain', 'US']
- {'asn': ['nxdomain', '3356', '3356'],
?                      --------

+ {'asn': ['nxdomain', '3356'],
-  'country': ['nxdomain', 'US', 'US'],
?                          ------

+  'country': ['nxdomain', 'US'],
-  'rir': ['nxdomain', 'arin', 'arin']}
?                      --------

+  'rir': ['nxdomain', 'arin']}

----------------------------------------------------------------------
```
I'm attempting to build this as an SCL, but if I build it without defining that it produces the same error, so that doesn't appear to be related.

#### Steps to reproduce
    python setup.py test
#### Expected behavior
Tests complete and build proceeds
#### Observed behavior
Tests fail with above messages
#### Any additional information
Tests only fail if `dnspython` is present - otherwise it appears to skip them. I started with the OS-provided package:

    python-dns-1.12.0-4.20150617git465785f.el7.noarch

I tried to pip install the latest version of `1.15.0`, but made no difference in results.
### Configuration, dump and another helpful excerpts
None
#### Any customizations done to /etc/fail2ban/ configuration
None
#### Relevant parts of /var/log/fail2ban.log file:
None
#### Relevant lines from monitored log files in question:
None

**Comment by sebres** [comment]
> This looks to be the same problem as #1841 ...

Nope, it is not the same...

> but since I'm using the latest version (0.10.2) ...

Are you sure? Because in the latest (corresponding this 98f4d70371c4d168df86af2653f314ea6ad60a0d) it is impossble at all (e. g. `country` can never be an array of 3 elements for 2 tickets "banned" in the test testCymruInfoNxdomain).
So `'country': ['nxdomain', 'US', 'US']` is just an impossible value for both IPs `['0.0.0.0', '8.0.0.0']` used in this test-case.

Can you please clone the latest version (0.10 or 0.11) and check it via `./bin/fail2ban-testcases Cymru`

**Comment by Ziris85** [comment]
Well, when I say "latest version", I suppose I'm referring to the [latest point release](https://github.com/fail2ban/fail2ban/releases). I just downloaded it again to confirm the issue was present and it was; however, if I patch that with the commit you referenced, this issue is indeed resolved (though a new one appears in its wake).

I usually try to stick with point releases when I create RPM's to use unless I have a reason not to, so I guess I'll have to make a decision here. Sorry to bother - I'll try to refrain from posting issues until I confirm them against latest bleed. Thanks again.

**Comment by sebres** [comment]
> Sorry to bother - I'll try to refrain from posting issues until I confirm them against latest bleed. 

No problem at all. I thought also it was already fixed before the latest release. Checked now - it is indeed too young. 
So the next release will get it.
Glad it work basically. Thank you for the verification.
