### ISSUE TITLE
New default Syslog format since 0.10.2 has superfluous padding

### ISSUE THREAD

**Issue by creideiki** [fail2ban/fail2ban#2099]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.10.2
- OS, including release name/version: Gentoo Linux, unstable
- [x] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

After upgrading fail2ban to 0.10.2, I noticed that my Syslog analysis tools stopped reporting anything regarding fail2ban.

This turned out to be because #1970 changed [the default Syslog logging format](https://github.com/fail2ban/fail2ban/pull/1970/files#diff-278844de51ec45e12e6955a69cd9accbL567) from the machine-readable
```
%(name)s[%(process)d]: %(levelname)s %(message)s
```
to the human-readable, whitespace-padded
```
%(name)-24s[%(process)d]: %(levelname)-7s %(message)s
```

The Syslog format is famously loosely defined, but that looks more unusual than most.

1. The default [Logstash Syslog plugin](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-syslog.html) apparently gives up on parsing when it sees the whitespace padding in the process name, and thinks everything after that is an unstructured message.
2. I checked my entire Syslog archive for 2018 for similar padding (`grep` with the extended regexp `[a-zA-Z] +\[[0-9]+]: `). The only program which had produced such padding was fail2ban 0.10.2.

My current workaround is to set the old log format explicitly in `fail2ban.conf`:
```
logtarget = SYSLOG[format="%%(name)s[%%(process)d]: %%(levelname)s %%(message)s"]
```

Could we please have the non-padded format back as default for Syslog? Or at least a note in the example configuration on how to change to it?

#### Steps to reproduce

Run fail2ban 0.10.2 with `logtarget = SYSLOG`.

#### Expected behavior

Syslog lines without whitespace padding:
```
2018-03-31T22:19:06+02:00 bastion fail2ban.server[29625]: INFO Starting Fail2ban v0.10.2
```

#### Observed behavior

Syslog lines with whitespace padding:
```
2018-03-31T22:00:13+02:00 bastion fail2ban.server         [26783]: INFO    Starting Fail2ban v0.10.2
```

**Comment by sebres** [comment]
closed in e786dbf132689133c29671871718a97f93b8912a
