### ISSUE TITLE
Py3 compatibility

### ISSUE THREAD

**Issue by andypost** [fail2ban/fail2ban#2105]
_We will be very grateful, if your problem was described as completely as possible,
enclosing excerpts from logs (if possible within DEBUG mode, if no errors evident
within INFO mode), and configuration in particular of effected relevant settings
(e.g., with ` fail2ban-client -d | grep 'affected-jail-name' ` for a particular
jail troubleshooting).
Thank you in advance for the details, because such issues like "It does not work" 
alone could not help to resolve anything!
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.10.3.1
- OS, including release name/version: Alpinelinux
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Trying to build Alpinelinux package with latest 0.10.3.1 with python3 I got 4 errors in log https://github.com/alpinelinux/aports/pull/3916#issuecomment-378924642

#### Steps to reproduce

Using docker container
```
docker run --rm -it alpine:edge ash
apk add --no-cache python3 py3-setuptools
wget https://github.com/fail2ban/fail2ban/archive/0.10.3.1.tar.gz
tar xzf 0.10.3.1.tar.gz
cd fail2ban-0.10.3.1/
python3 setup.py build
python3 setup.py install --root "/tmp"
```

#### Expected behavior

No errors

#### Observed behavior

While install script running in log I see syntax errors
```
byte-compiling /tmp/usr/lib/python3.6/site-packages/fail2ban/tests/misctestcase.py to misctestcase.cpython-36.pyc
  File "/usr/lib/python3.6/site-packages/fail2ban/tests/misctestcase.py", line 212
    print deep_function(3)
                      ^
SyntaxError: invalid syntax

byte-compiling /tmp/usr/lib/python3.6/site-packages/fail2ban/tests/filtertestcase.py to filtertestcase.cpython-36.pyc
  File "/usr/lib/python3.6/site-packages/fail2ban/tests/filtertestcase.py", line 1449
    % m for m in 53, 54, 57, 58])
                   ^
SyntaxError: invalid syntax

byte-compiling /tmp/usr/lib/python3.6/site-packages/fail2ban/server/server.py to server.cpython-36.pyc
  File "/usr/lib/python3.6/site-packages/fail2ban/server/server.py", line 98
    os.umask(0077)
                ^
SyntaxError: invalid token

byte-compiling /tmp/usr/lib/python3.6/site-packages/fail2ban/server/ipdns.py to ipdns.cpython-36.pyc
  File "/usr/lib/python3.6/site-packages/fail2ban/server/ipdns.py", line 276
    mask = ~(0xFFFFFFFFL >> cidr)
                       ^
SyntaxError: invalid syntax

```

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
Have you executed 2to3 before the build? If not, please add a following line in your script:
```diff
...
cd fail2ban-0.10.3.1/
+ ./fail2ban-2to3
python3 setup.py build
...
```
Additionally also note https://github.com/fail2ban/fail2ban/issues/2096#issuecomment-378540634
If python3 is not a default python version on target system, you have to replace execve-interpreter header (the first line) of any script fail2ban-* in bin folder with something like `#!/usr/bin/env python3`. Or just try an amendment from 5bf80fefa9dee02aae0fa64a865ec2a8ca529b07

**Comment by andypost** [comment]
Thanx a lot! I will try and report later today

**Comment by andypost** [comment]
Works for me!

**Comment by sebres** [comment]
> Works for me!

Glad it works, one interim question: the execution of fail2ban-2to3 was enough? Or did you needed to replace the interpreter in the headers of bin-scripts also?
