### ISSUE TITLE
Update filter.d/sshd.conf?

### ISSUE THREAD

**Issue by Neko-Chang-Taiwan** [fail2ban/fail2ban#2110]
Hi All

I found one of jail rule doesn't match log pattern under attack.
Protect server: openssh-portable-7.7.p1
Attacker log
`Did not receive identification string from 107.170.228.101 port 41516`
Pattern in filter.d/sshd.conf line 64
`^Did not receive identification string from <HOST>`
Because port XXXXX doesn't match, so can't ban.

I tried to modify pattern as below
`^Did not receive identification string from <HOST>%(__on_port_opt)s`
It is work fine.

So can fail2ban:
1. If port XXXXX is general case, update it?
2. If port XXXXX is special case, how can I overwrite the rule?

Thanks a lot.

### Environment:
- Fail2Ban version : 0.10.3
- OS, FreeBSD 11.1-RELEASE

**Comment by chtheis** [comment]
Am 10.04.2018 um 07:57 schrieb Neko-Chang-Taiwan:
> Hi All
> 
> I found one of jail rule doesn't match log pattern under attack.
> Protect server: openssh-portable-7.7.p1
> Attacker log
> |Did not receive identification string from 107.170.228.101 port 41516|
> Pattern in filter.d/sshd.conf line 64
> |^Did not receive identification string from <HOST>|
> Because port XXXXX doesn't match, so can't ban.
> 
> I tried to modify pattern as below
> |^Did not receive identification string from <HOST>%(__on_port_opt)s|
> It is work fine.
> 
> So can fail2ban:
> 
>  1. If port XXXXX is general case, update it?
>  2. If port XXXXX is special case, how can I overwrite the rule?
> 
> Thanks a lot.
> 
> 
>       Environment:
> 
>   * Fail2Ban version : 0.10.3
>   * OS, FreeBSD 11.1-RELEASE
> 

I'm using FreeBSD 11.1 with stock sshd, and I don't see the "port"-part 
in the log.

I think you can overwrite failregex in your own file filter.d/sshd.local 
or in jail.local secton [sshd]. Though I don't see a problem if we 
extended the pattern with the on_port_opt - Part, but I'm not a 
regex-pert :)


Christoph

**Comment by Neko-Chang-Taiwan** [comment]
Hi Christoph

Thanks your suggestion.
Sorry, I forgot to explain about mode, I set `mode =aggressive`.
The issue rule activated in mdre-ddos.

I had been test for confirm about the issue.
`fail2ban-regex /var/log/auth.log /usr/local/etc/fail2ban/filter.d/sshd.conf`

And got result like below
=================================================================
Running tests
=============

Use   failregex filter file : sshd, basedir: /usr/local/etc/fail2ban
Use         maxlines : 1
Use      datepattern : Default Detectors
Use         log file : /var/log/auth.log
Use         encoding : UTF-8

Results
=======

Failregex: 45 total
|-  #) [# of hits] regular expression
|   6) [10] ^[iI](?:llegal|nvalid) user <F-USER>.*?</F-USER> from <HOST>(?: (?:port \d+|on \S+|\[preauth\])){0,3}\s*$
|  18) [14] ^<F-NOFAIL>Received <F-MLFFORGET>disconnect</F-MLFFORGET></F-NOFAIL> from <HOST>(?: (?:port \d+|on \S+)){0,2}:\s*11:
|  19) [15] ^<F-NOFAIL>Connection <F-MLFFORGET>closed</F-MLFFORGET></F-NOFAIL> by <HOST>
|  20) [6] ^<F-MLFFORGET><F-NOFAIL>Accepted \w+</F-NOFAIL></F-MLFFORGET> for <F-USER>\S+</F-USER> from <HOST>(?:\s|$)
 -

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [153] {^LN-BEG}(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
 -

Lines: 153 lines, 0 ignored, 45 matched, 108 missed
[processed in 0.94 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all 108 lines
=================================================================
Sorry, I can't show result as plain text.
Confirmed, attacker log doesn't match rule.

I have a question.
Pattern's regexp doesn't end of "$", shall be match even _ports XXXXX_ exist or not.
But doesn't match actually.
May I missing something, can you help me?

Thanks you a lot.

**Comment by sebres** [comment]
I don't understood why it does not work for you out of the box. 
Because regex `^Did not receive identification string from <HOST>` is not end-anchored, so perfect matchs `Did not receive identification string from ... port ...`.

Additionally exactly this string is already proper test-covered in our test-suite:
https://github.com/fail2ban/fail2ban/blob/a3bcbe2d1b7ebe3897894ddc2c400f48806d0a66/fail2ban/tests/files/logs/sshd#L222-L223

Possibly you've overlooked that this regex used only in ddos/aggressive mode, if so just define mode in your jail.local:
```INI
[sshd]
mode = aggressive
# or alternatively:
filter = sshd[mode=aggressive, ...other-params-if-needed...]
```

**Comment by sebres** [comment]
You test call of fail2ban-regex is a bit wrong, just try:
```bash
fail2ban-regex /var/log/auth.log 'sshd[mode=aggressive]'
```

**Comment by Neko-Chang-Taiwan** [comment]
Hi sebres

Thanks you very much.
I had been test your suggest, and got new result below.
`
|  21) [8] ^Did not receive identification string from <HOST>
`
Issue rule match!

In fact, I putted `mode = aggressive` into my local file `/usr/local/etc/fail2ban/jail.d/jail.local` as global default like below.

[DEFAULT]
bantime  = 2678400 ; 1 month
findtime  = 86400  ; 1 day
maxretry = 1
backend = gamin
**mode = aggressive**
banaction = pf
banaction_allports = pf
action = %(action_mwl)s

And enable sshd.conf's local file `/usr/local/etc/fail2ban/jail.d/sshd.local` below.
[sshd]
enabled  = true
port     = ssh
logpath  = %(sshd_log)s
backend  = %(sshd_backend)s

I got something mistake / misunderstanding I think.
I will trace and try again :)

Thank a lot.

**Comment by sebres** [comment]
I tried your settings and I see pretty good the regex was added:
```bash
fail2ban-client --dp | grep 'Did not receive identification string'
    '^Did not receive identification string from <HOST>',
```
Does it help, if you try to put the mode directly in `[sshd]` section?

**Comment by sebres** [comment]
Oh... I see your problem now: your path to `jail.local` is wrong, it should be in root of etc/fail2ban parallel resp. in same level as `jail.conf`
```diff
- /etc/fail2ban/jail.d/jail.local
+ /etc/fail2ban/jail.local
```
Folder `jail.d` is provided only for the single jails.

**Comment by Neko-Chang-Taiwan** [comment]
Hi sebres

Rule start work after move jail.local to  etc/fail2ban folder.
It is my mistake...
I've learnt a valuable lesson.

Thanks you and  chtheis cvery much.
