### ISSUE TITLE
Syntax errors in action.d/hostsdeny.conf

### ISSUE THREAD

**Issue by chtheis** [fail2ban/fail2ban#2114]
_We will be very grateful, if your problem was described as completely as possible,
enclosing excerpts from logs (if possible within DEBUG mode, if no errors evident
within INFO mode), and configuration in particular of effected relevant settings
(e.g., with ` fail2ban-client -d | grep 'affected-jail-name' ` for a particular
jail troubleshooting).
Thank you in advance for the details, because such issues like "It does not work" 
alone could not help to resolve anything!
Thanks! (remove this paragraph and other comments upon reading)_

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): 0.10.3.1
- OS, including release name/version: FreeBSD 11.1
- [X ] Fail2Ban installed via OS/distribution mechanisms
- [X ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

To make action.d/hostsdeny IPv6-capable a new variable named _ip_value was introduced which is defined as 
```INI
_ip_value = <ip>

[Init?family=inet6]
_ip_value = [<ip>]
```
It looks like fail2ban sees this as a duplicate or invalid entry and thus "<_ip_value>" is treated literally in actionban and actionunban. This leads that "<_ip_value>" is written into hosts.deny instead of the real IP address.
When I comment out the second definition (the last 2 lines for IPv6), everything works.

See also https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=227577

Some other remark: stock "sed" from FreeBSD has a different semantic with the "-i" option than that of e.g. Debian. 
The correct syntax for actionunban would be `... && sed -i "" "/^<daemon_list>: $IP$/d" <file>`

If this is correct for Debian / GNU sed as well I would recommend to change it that way.
If not I have to patch that line during installation, no big deal.

#### Steps to reproduce

Activate hostsdeny action

#### Expected behavior

A correct line is put into /etc/hosts.deny

#### Observed behavior

Instead of the IP address the literal string "<_ip_value>" is written

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

**Comment by sebres** [comment]
Indeed it's broken currently. This going to the first `_`-char which is not allowed by regex matches variable name in the pattern `<var-name>` (currently it should start with a letter).
I'll fix this soon. Thank you!

**Comment by sebres** [comment]
Following code is responsible for the ignore action-parameters starting with underscore:
https://github.com/fail2ban/fail2ban/blob/b16aafe2334e7897c2048a9c48205340af9e80c9/fail2ban/server/action.py#L314

But I'm afraid to allow it (IMHO too dangerous for minor update, I'll try to rewrite it later or possibly in 0.11)...
Thus I'll simply rename `_ip_value` to `ip_value`.

**Comment by sebres** [comment]
Fixed in bba7a6c5cfa24c15c639ad2e28adfef45662b85f.

> The correct syntax for actionunban would be `... && sed -i "" "/^<daemon_list>: $IP$/d" <file>`

Unfortunatelly not possible on most linux-systems (you'll get an error "cannot read ... : no such file or directory").
In opposite to FreeBSD the correct syntax is to put the option and suffix together:
```diff
- # FreeBSD:
- [-i extension] ...
+ # Linux:
+ -i[SUFFIX], --in-place[=SUFFIX]
```

Thus close. 
Thanks.

**Comment by chtheis** [comment]
Am 17.04.2018 um 19:01 schrieb Sergey G. Brester:
 >     The correct syntax for actionunban would be |... && sed -i ""
 >     "/^<daemon_list>: $IP$/d" <file>|
 >
 > Unfortunatelly not possible on most linux-systems (you'll get an error
 > "cannot read ... : no such file or directory").
OK, I will deal with it in FreeBSD specifically.

And many thanks for resolving the _ip_value / ip_value


Best regards

Christoph

**Comment by chtheis** [comment]
Hello Sergey!

One more question:
What is the purpose of
IP=$(echo "<ip_value>" | sed 's/[][\.]/\\\0/g')
or more specific, the purpose of the sed part in actionunban?

On Linux it will replace the "." in the IP address with "\.", I guess 
because the result is used as a pattern in the next sed expression.
On FreeBSD the output is different, I don't know why yet.

If it is just to replace the "." with "\.", why not do something like
sed 's/\./\\\./g' ?


Best regards

Christoph

**Comment by sebres** [comment]
> I guess because the result is used as a pattern in the next sed expression.

Yes it is, seen in this way as escape, otherwise '.'-char will match any character in next expression.
The next expression is anchored so precise enough, so the dot-char would not be a problem.
But still worse it affects the brackets of IPv6 - they should be definitely escaped.

> On FreeBSD the output is different

If I can remember FreeBSD-sed does not have capture-group `\0` (for whole match), so it is just a string.

It should be then explicitly captured (as first group), thus something like that:
```diff
- IP=$(echo "<ip_value>" | sed 's/[][\.]/\\\0/g')
+ IP=$(echo "<ip_value>" | sed 's/\([][\.]\)/\\\1/g'
```
Linux can this certainly and I assume latest FreeBSD-versions also. 
Could you check it for your system?
```bash
$ echo "1.2.3.4"  | sed 's/\([][\.]\)/\\\1/g'
1\.2\.3\.4
$ echo "[1:2::4]" | sed 's/\([][\.]\)/\\\1/g'
\[1:2::4\]
```

**Comment by chtheis** [comment]
Am 18.04.2018 um 12:14 schrieb Sergey G. Brester:
> It should be then explicitly captured (as first group), thus something 
> like that:
> 
> - IP=$(echo "<ip_value>" | sed 's/[][\.]/\\\0/g')
> + IP=$(echo "<ip_value>" | sed 's/\([][\.]\)/\\\1/g'
> 
> Linux can this certainly and I assume latest FreeBSD-versions also.
> Could you check it for your system?
> 
> $echo  "1.2.3.4"   |  sed's/\([][\.]\)/\\\1/g'
> 1\.2\.3\.4
> $echo  "[1:2::4]"  |  sed's/\([][\.]\)/\\\1/g'
> \[1:2::4\]

Both work, thanks a lot!


Christoph
