### ISSUE TITLE
Log rotation does not work 0.10

### ISSUE THREAD

**Issue by joe-average-user** [fail2ban/fail2ban#2121]
Using 
# fail2ban-client version
0.10.0a2

log rotation is done by logrotate with settings from the fail2ban manual. But fail2ban continues to write to  the old logfile and does not change back to the original file name.

# fail2ban-client set logtarget /log/fail2ban/fail2ban.log
Current logging target is:
`- /log/fail2ban/fail2ban.log

.. But it writes in fact into 
/log/fail2ban/fail2ban.log-20180501

The log contains no lines like former:

2018-04-01 18:00:13,897 fail2ban.server         [19204]: INFO    Changed logging target to /log/fail2ban/fail2ban.log for Fail2ban v0.9.6.dev0

**Comment by sebres** [comment]
> 0.10.0a2
> Changed logging target to ... v0.9.6.dev0

So which version is affected exactly?

**Comment by joe-average-user** [comment]
As said version 0.10.0a2 has the problem.
The log line shows that 0.9.6.dev0 worked.

**Comment by sebres** [comment]
1. Do you see `rollover performed on /var/log/fail2ban.log` in fail2ban log-file?

2. Do you have `fail2ban-client flushlogs` configured in log-rotate script, like:
https://github.com/fail2ban/fail2ban/blob/869d99dd377ff45efa5796bb3be2500e41f32dc3/files/fail2ban-logrotate#L11-L12

If you execute `?sudo? fail2ban-client flushlogs` manually, do you see:

3. `logs: rolled over` in the console?
4. `rollover performed on /var/log/fail2ban.log` in log-file?
5. The rotation takes place?

**Comment by joe-average-user** [comment]
Ok, this seems a manual problem.
Here
https://www.fail2ban.org/wiki/index.php/MANUAL_0_8
is stated to log rotate with this:

    postrotate
      /usr/local/bin/fail2ban-client set logtarget /var/log/fail2ban.log >/dev/null
    endscript

But obviously this does not work any longer in 0.10.
Your "flushlogs" command _does_ work. 
Thank you very much.

**Comment by sebres** [comment]
Out-dated, just to link https://github.com/fail2ban/fail2ban/issues/2120#issuecomment-385381344

@yarikoptic, @lostcontrol Guys, we should do something with this out-dated info on main fail2ban page...
