### ISSUE TITLE
Custom jails match when using fail2ban-regex, but do not ban when daemon is running

### ISSUE THREAD

**Issue by mkrahal** [fail2ban/fail2ban#2134]
Fail2ban is able to match ips when I using the command line fail2ban-regex, but is not banning any ips when running in background. My other jails do ban ips as they are supposed to but custom jails don't seem to work.

This jail is meant to catch apache-400 errors and ban them via ufw.

Output of: fail2ban-client -d | grep 'apache-400'
['add', 'apache-400', 'auto']
['set', 'apache-400', 'usedns', 'warn']
['set', 'apache-400', 'addlogpath', '/var/log/apache2/access.log']
['set', 'apache-400', 'maxretry', 3]
['set', 'apache-400', 'addignoreip', '127.0.0.1/8']
['set', 'apache-400', 'ignorecommand', '']
['set', 'apache-400', 'findtime', 604800]
['set', 'apache-400', 'bantime', 604800]
['set', 'apache-400', 'addfailregex', '^<HOST> -.*"(GET|POST|HEAD).*HTTP.*" 400']
['set', 'apache-400', 'addignoreregex', "''"]
['set', 'apache-400', 'addaction', 'ufw-action']
['set', 'apache-400', 'actionban', 'ufw-action', 'ufw insert 1 deny from <ip> to any']
['set', 'apache-400', 'actionstop', 'ufw-action', '']
['set', 'apache-400', 'actionstart', 'ufw-action', '']
['set', 'apache-400', 'actionunban', 'ufw-action', 'ufw delete deny from <ip> to any']
['set', 'apache-400', 'actioncheck', 'ufw-action', '']
['set', 'apache-400', 'setcinfo', 'ufw-action', 'protocol', 'tcp']
['set', 'apache-400', 'setcinfo', 'ufw-action', 'name', 'apache-400']
['set', 'apache-400', 'setcinfo', 'ufw-action', 'chain', 'INPUT']
['set', 'apache-400', 'setcinfo', 'ufw-action', 'port', '80,443']
['start', 'apache-400']

Excerpt from /var/log/apache2/access.log
193.112.77.149 - - [18/May/2018:13:31:41 +0200] "GET /index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:31:42 +0200] "GET /phpmyadmin/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:31:42 +0200] "GET /phpMyAdmin/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:31:43 +0200] "GET /pmd/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:31:45 +0200] "GET /PMA/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:31:46 +0200] "GET /PMA2/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:31:46 +0200] "GET /pmamy/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:31:47 +0200] "GET /pmamy2/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:31:49 +0200] "GET /mysql/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:31:50 +0200] "GET /admin/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:31:50 +0200] "GET /db/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:31:51 +0200] "GET /dbadmin/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:31:53 +0200] "GET /admin/pma/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:31:54 +0200] "GET /admin/PMA/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:31:54 +0200] "GET /admin/mysql/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:31:55 +0200] "GET /admin/mysql2/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:31:57 +0200] "GET /admin/phpMyAdmin/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:31:58 +0200] "GET /admin/phpmyadmin2/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:31:58 +0200] "GET /mysqladmin/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:31:59 +0200] "GET /mysql-admin/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:32:01 +0200] "GET /phpmyadmin0/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:32:02 +0200] "GET /phpmyadmin1/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:32:02 +0200] "GET /phpmyadmin2/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:32:03 +0200] "GET /myadmin/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:32:05 +0200] "GET /xampp/phpmyadmin/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:32:06 +0200] "GET /phpMyadmin_bak/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:32:06 +0200] "GET /www/phpMyAdmin/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:32:07 +0200] "GET /tools/phpMyAdmin/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:32:09 +0200] "GET /phpMyAdminold/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:32:10 +0200] "GET /phpMyAdmin.old/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:32:10 +0200] "GET /pma-old/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:32:11 +0200] "GET /claroline/phpMyAdmin/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:32:13 +0200] "GET /phpma/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:32:14 +0200] "GET /phpmyadmin/phpmyadmin/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"
193.112.77.149 - - [18/May/2018:13:32:14 +0200] "GET /phpMyAdmin/phpMyAdmin/index.php HTTP/1.1" 400 206 "-" "Mozilla/5.0"

**Comment by unixpro** [comment]
I have found this exact same problem.  I have spent ages trying to track down the problem with heavydebug, simplifying filters etc.  In fact I came here to find how to help by contributing what I have found out.
CentOS 7.4, fail2ban-server-0.9.7-1.el7, iptables no firewalld.
I have found that on daemon start, the filter works fine but regex detection stops after fail2ban has run through the log file on initial startup.  Tried pyinotify, gamin and polling backends.

I've tracked the problem to be something to do with findtime detection - I think the problem is the time unit detection when using normal rsyslog custom logfiles instead of systemd journal.  I think 

To confirm I set `findtime = 32000000` and now I am seeing the expected Found and Ban entries in my /var/log/fail2ban.log.

Therefore I think the problem is with the detection of timestamps in the logfile - possibly/probably with time log units.

**Comment by unixpro** [comment]
Ok after more testing I have confirmed that my setup (centOS 7.4, fail2ban-server-0.9.7-1.el7) is interpreting the findtime parameter in **microseconds** for my custom jail/logfile.
I think this is a result of the awful messy / partial move to systemd journal.

In my case I am examining a logfile from a mailserver (actually running debian jessie) that is forwarding it's mail logging to a front-end haproxy server.  The cause could be down to different local and backend logging units perhaps although I would expect the timestamp detection to also detect units used in the logfile.

**Comment by mkrahal** [comment]
Thanks for the input @unixpro, after further testing I have come to realise that the banning does in fact work, but with a delay. 

Meaning that custom jails for some reason do not work immediately when fail2ban daemon is started but rather seem to kick-in about 40mins - 1hr later, retroactively banning all the previous regex matches found in the log file. I am closing this thread as this does not appear to be a major issue.

**Comment by sebres** [comment]
> Meaning that custom jails for some reason do not work immediately when fail2ban daemon is started but rather seem to kick-in about 40mins - 1hr later

Looks like your log-files are very large?!
Tried log-rotate?
Which version of fail2ban do you use?

**Comment by SpareSimian** [comment]
I'm running into this today with 0.11.2-2 from EPEL on CentOS. It's banning new attempts, but it fails to identify any of the 250 attempts in a 272-line log file in the last day, with findtime set to 1w.

**Comment by sebres** [comment]
@SpareSimian Take a look for FAQ in https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works (first QA).

**Comment by SpareSimian** [comment]
That I knew. But I thought when first started it would scan back from the end of the log for findtime+bantime to discover recent hits. It doesn't seem to do that. Issue #30 suggests that this should happen.

**Comment by sebres** [comment]
> it would scan back from the end of the log for findtime+bantime

Not to `findtime+bantime`, but to `min(findtime,bantime)`... This is because the end of ban for found tickets calculated from time of last attempt + bantime (otherwise they become obsolete immediately after ban, that makes no sense).
Why you need such old entries? If the recidive evildoers trying it again - they get banned soon, if not - they are gone (or are dynamic IPs etc).
