### ISSUE TITLE
Stopped recieving events after journald restart

### ISSUE THREAD

**Issue by smith153** [fail2ban/fail2ban#2139]
### Environment:

- Fail2Ban version (including any possible distribution suffixes):
fail2ban_0.9.7-1_all.deb
- OS, including release name/version: 
Debian Stretch 9.4

- [x ] Fail2Ban installed via OS/distribution mechanisms
- [x ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

I have the following as a filter (using systemd journal) to block any port scanners:

```
[INCLUDES]
before = common.conf
[Definition]
failregex = ^%(__prefix_line)s.*DROP:IN=eth1 OUT= MAC=\S* SRC=<HOST> DST=\S* LEN=\S*
ignoreregex =
[Init]
journalmatch = _TRANSPORT=kernel

```
The other day, I changed some of the journald configurations and restarted the journal via `systemctl restart systemd-journald.service` Everything seemed fine, but about a week later I just happened to notice the fail2ban was no longer adding blocking rules, after digging more , I realized that fail2ban was not receiving any new events from the journal. I don't know how fail2ban gets data from journald but I assume it connects to a unix socket and when I restarted the journal, that left fail2ban following a deleted socket (just my theory). This could also be an issue with the upstream package ([python-systemd](https://github.com/systemd/python-systemd)), I am using version 233.

I know this is short on details, I will try to investigate more. For now, I would just like to bring this issue to attention.

#### Steps to reproduce

Issue `systemctl restart systemd-journald.service` and noticed fail2ban stops receiving journal events

#### Expected behavior

Fail2ban should continue to follow the new journal process

#### Observed behavior

Fail2ban did not follow the new journald process

**Comment by smith153** [comment]
Ok, it looks like the issue was not caused by a simple restart of the journald. I have verified that restarting the journal was not the issue that caused this.

What I did originally was enabled journald persistent storage by adding the correct directory `mkdir  /var/log/journal` and then restarting the journal. See the `Storage` option over at https://www.freedesktop.org/software/systemd/man/journald.conf.html  (but I did not restart fail2bad afterwards) The end result was fail2ban stopped receiving journal events.

So perhaps this is an edge case, but might be worth looking into.

**Comment by sebres** [comment]
> but I did not restart fail2ban afterwards

Well, I don't know how it should be "fixed" without restart (in addition, I don't see some way the python-systemd module as well as other monitoring tools can detect such changes inplace).
Thus closed.
