### ISSUE TITLE
datepattern for ubuntu[/deb?] apache 2.4 logs - working in 0.8x, broken in 0.10x

### ISSUE THREAD

**Issue by dsmithdewarcom** [fail2ban/fail2ban#2142]
- Fail2Ban version (including any possible distribution suffixes):10.1-1
- OS, including release name/version: Ubuntu 16.04.4
**Fail2Ban installed via ppa backport**
- [* ] You have not applied any additional foreign patches to the codebase
- [* ] Some customizations were done to the configuration (provide details below is so)

### The issue:
apache -* jails including my custom jail definition (see below) were working in Fail2Ban (F2B) v. 0.8.11-1, but are throwing errors since upgrading to a backported F2B v 0.10.1-1.

I tried adding "datepattern = %%d/%%m/%%Y:%%H:%%M:%%S" to my custom jail. which fail2ban-client reloads "OK".

After comparing the two F2B versions, I tried commenting-out "datepattern = {^LNBEG}" in v0.10x /filter.d/apache-common.conf (which was not present in v 0.8x).

The dates in my apache access.log are rendered as, e.g.
115.159.186.223 - - [28/May/2018:00:38:36 -0400] "GET /phpmyadmin/index.php HTTP/1.1" 301 518 "-" "Mozilla/5.0"

The corresponding F2B log error for above entry is:
2018-05-28 00:38:36,627 fail2ban.filter         [18373]: WARNING Found a match for u'115.159.186.223 - - [28/May/2018:00:38:36 -0400] "GET /phpMyAdmin/index.php HTTP/1.1" 301 518 "-" "Mozilla/5.0"' but no valid date/time found for u'115.159.186.223 - - [28/May/2018:00:38:36 -0400] "GET /phpMyAdmin/index.php HTTP/1.1" 301 518 "-" "Mozilla/5.0"'. Please try setting a custom date pattern (see man page jail.conf(5)). If format is complex, please file a detailed issue on https://github.com/fail2ban/fail2ban/issues in order to get support for this format.

**edit:** I found an error in my datepattern, it should be "%%d/%%**b**/%%Y:%%H:%%M:%%S"

and "fail2ban-regex /etc/fail2ban/filter.d/apache-adminrsc.conf /var/log/apache2/access.log" is returning:
```
Running tests
=============

Use   failregex filter file : apache-adminrsc, basedir: /etc/fail2ban
Use      datepattern : Day/MON/Year:24hour:Minute:Second
Use         log file : /var/log/apache2/access.log
Use         encoding : UTF-8

Results
=======

Failregex: 24 total
|-  #) [# of hits] regular expression
|   1) [24] ^<HOST> - - .*("GET \/phpmyadmin|"GET \/phpMyAdmin|"GET \/pma\/|"GET \/myadmin|"GET \/admin|"GET \/mysql|"GET \/lfm.php|"GET \/sftp|"GET \/file|"GET \/site|"GET \/winscp|"POST \/ HTTP).*$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [146] Day/MON/Year:24hour:Minute:Second
`-

Lines: 146 lines, 0 ignored, 24 matched, 122 missed
[processed in 0.23 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all 122 lines
```
However, reloading the jail has not thus far resulted in any retroactive bans.

I'm also puzzled about what changed between the two F2B versions that (apparently) caused this issue.

**Comment by sebres** [comment]
1. File `apache-common.conf` is a common include for apache error-logs (not for the access-log), therefore I don't know which sence it should make in your configs.
2. Proper universal date pattern-anchor for apache-access-log could be found in some apache-filters observing access-log, like here: https://github.com/fail2ban/fail2ban/blob/b185e7cb04206aac48f33414685f4d54662dfdf0/config/filter.d/apache-badbots.conf#L17-L18
3. Better if you'll always specify `datepattern` as exactly as possible in your own custom jails/filters.
See #1583 for more details.

And last but not least, many things could be incompatible between 0.8 and 0.10 (especially some includes), see ChangeLog: https://github.com/fail2ban/fail2ban/blob/9f3a80a21a12dc1f6559f37f0269528d8163892c/ChangeLog#L27-L29

**Comment by dsmithdewarcom** [comment]
Thanks, it's started working again with datepattern fix in my edit.

Note I did not need any custom datepatterns in v 0.08x. That part ain't "incorrect" :-)

**Comment by sebres** [comment]
> Note I did not need any custom datepatterns in v 0.08x. That part ain't "incorrect" :-)

That was exactly the vulnerability, which was fixed in #1583. Unfortunatelly not compatible for you (because you've used an include for the apache error-log, which is more precise/anchored now).

**Comment by sebres** [comment]
Oh yeah, regarding "incorrect" :) - the apache-common include makes no sense for access.log (so your custom filter would be not affected, if this include doesn't have been used).
The fix provided within 0.10 was exactly correct for the `apache-common` (for the error.log).

So another possible solution for your issue - to remove the include of `apache-common` at all (section include) from your custom filter.

**Comment by dsmithdewarcom** [comment]
Thank you for explaining the reasons for updates you made in newer version, and advising on how I can fix and optimize the datepattern. failregex, etc. in my custom include.

**Comment by MortimerCat** [comment]
> datapattern = ^[^\[]*\[(%%d/%%b/%%Y:%%H:%%M:%%S %%z)\]

I am highlighting the misspelt command above for anyone like me who copied it as a basis for their script. It should say

datepattern = ^[^\[]*\[(%%d/%%b/%%Y:%%H:%%M:%%S %%z)\]
