### ISSUE TITLE
recidive jail may not be enabled prior to an initial start of fail2ban.

### ISSUE THREAD

**Issue by mmsaffari** [fail2ban/fail2ban#2147]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): **0.9.7-1.el7**
- OS, including release name/version: **Centos 7.5.1804 (DigitalOcean)**
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:
The recidive jail may not be enabled prior to an initial start of fail2ban. I need to comment out the recidive lines, start fail2ban, un-comment recidive lines and restart the service to get it to work.

#### Steps to reproduce
1. yum -y install fail2ban-all
2. create the jail.local as provided below, next to jail.conf
3. systemctl start fail2ban.service
#### Expected behavior
The service must start without errors.
#### Observed behavior
The service fails to start due to not being able to find the log files required by recidive.
### Configuration, dump and another helpful excerpts
This is my jail.local
```
[DEFAULT]
bantime = 3600
destemail = myemail@mail.com
sender = fail2ban@mydomain.tld
action = %(action_mwl)s

[sshd]
enabled = true
port = 12345

[recidive]
enabled = true

```
#### Any customizations done to /etc/fail2ban/ configuration
No files were touched. I just created a jail.local.

#### Relevant parts of /var/log/fail2ban.log file:
This is what I get from journalctl -xe
```
Jun 01 06:12:22 host.mydomain.tld fail2ban-client[1392]: ERROR  Failed during configuration: Have not found any log file for recidive jail
Jun 01 06:12:22 host.mydomain.tld systemd[1]: fail2ban.service: control process exited, code=exited status=255
Jun 01 06:12:22 host.mydomain.tld systemd[1]: Failed to start Fail2Ban Service.
-- Subject: Unit fail2ban.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit fail2ban.service has failed.
--
-- The result is failed.
Jun 01 06:12:22 host.mydomain.tld systemd[1]: Unit fail2ban.service entered failed state.
Jun 01 06:12:22 host.mydomain.tld systemd[1]: fail2ban.service failed.
Jun 01 06:12:22 host.mydomain.tld systemd[1]: fail2ban.service holdoff time over, scheduling restart.
Jun 01 06:12:22 host.mydomain.tld systemd[1]: start request repeated too quickly for fail2ban.service
Jun 01 06:12:22 host.mydomain.tld systemd[1]: Failed to start Fail2Ban Service.
-- Subject: Unit fail2ban.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit fail2ban.service has failed.
--
-- The result is failed.
Jun 01 06:12:22 host.mydomain.tld systemd[1]: Unit fail2ban.service entered failed state.
Jun 01 06:12:22 host.mydomain.tld systemd[1]: fail2ban.service failed.
```

**Comment by sebres** [comment]
This going to #1379 (and it's impossible to fix in v.0.9 without completely rewriting the handling).
So will be fixed in newer version. 
Thx.
