### ISSUE TITLE
debian packages updates

### ISSUE THREAD

**Issue by stratege1401** [fail2ban/fail2ban#2148]
Hello,

it would be nice to have some debian packages updates:

wheezy and jessie are 0.8.13-1 and as they are OLDOLD and OLD distro, updates are not needed.

stretch (Actual stable) is 0.9.6-2 and need an update to your latest stable version witch is branch 0.11 since you merge it.

buster (testing) and sid (unstable)  both are on 0.10.2-2 obsolete ? ( very usefull for testing ).

Any planning ?

Thank you.

**Comment by dsmithdewarcom** [comment]
There are backports available.

**Comment by stratege1401** [comment]
the backport are not .11 but .10 ...

**Comment by stratege1401** [comment]
as you can see, my first ticket is on the right spot, as Yarikoptic is the maintainer. Thanks to Sebres, he knows now he has to do some action on the packages list ...

**Comment by dsmithdewarcom** [comment]
I'm sure he just forgot...

**Comment by stratege1401** [comment]
yes, i am pretty sure he is busy. Just a friendly reminder ...

**Comment by dsmithdewarcom** [comment]
Though it looks like installing from source is fairly trivial.

**Comment by stratege1401** [comment]
it is, but not for all users as my students ... or newbee

**Comment by yarikoptic** [comment]
I would proceed with updating sid/testing (and neurodebian  backports) with 0.10.4 (whenever that one is out), and possibly experimental (and debian-devel of NeuroDebian) with 0.11 series

**Comment by yarikoptic** [comment]
anyways -- since this is not something for "Fail2Ban upstream" to fix, I will close it.  For distribution specific updates, use distribution-specific channels (e.g. reportbug in Debian) but please check first if a similar issue is not filed already ;-)
