### ISSUE TITLE
ignoreself option is not working

### ISSUE THREAD

**Issue by hrkzhrsw** [fail2ban/fail2ban#2158]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): fail2ban/bionic,now 0.10.2-2
- OS, including release name/version: Ubuntu 18.04 LTS
- [o] Fail2Ban installed via OS/distribution mechanisms
- [o] You have not applied any additional foreign patches to the codebase
- [o] Some customizations were done to the configuration (provide details below is so)

### The issue:
To monitor "authentication failure” at sudo in auth.log, I made original sudo filter and logger action.
For \<HOST\> in failregex, I applied own-hostname, so I defined "ignoreself = false" in the jail.
By the DEBUG log, failures have detected, but ban doesn't work.

#### Steps to reproduce
Run fail2ban and fail authentication at sudo.

#### Expected behavior
Ban (logger action) when authentication failure at sudo caused

#### Observed behavior
Detected failure but no ban
(seems like ignored because own IP)

#### Any additional information
- IPv6 is disabled

### Configuration, dump and another helpful excerpts
- action.d/logger.conf
```INI
[Definition]
actionban = logger -i -p local0.crit -t fail2ban "Authentication failure name=<name> ip=<ip>"
```
- filter.d/sudo.conf
```INI
[Definition]
failregex = <HOST> sudo:.*pam_unix\(sudo:auth\): authentication failure
```
- jail.d/jail.local
```INI
[DEFAULT]
usedns = yes
[sudo]
enabled  = true
ignoreself = false
logpath  = /var/log/auth.log
filter   = sudo
maxretry = 1
findtime = 300
bantime  = 0
action = logger[name=%(__name__)s]
```
#### Any customizations done to /etc/fail2ban/ configuration
- loglevel = DEBUG

#### Relevant parts of /var/log/fail2ban.log file:
```
2018-06-20 18:15:48,727 fail2ban.filter         [36592]: DEBUG   Processing line with time:1529486133.0 and ip:xx.xx.xx.xx(own IP)
2018-06-20 18:15:48,731 fail2ban.filter         [36592]: DEBUG   Processing line with time:1529486133.0 and ip:::1
```
- detected auth.log
```
Jun 20 18:15:33 <hostname> sudo: [notice]  pam_unix(sudo:auth): authentication failure; logname=sesuser uid=1002 euid=0 tty=/dev/pts/1 ruser=test rhost=  user=test
```

**Comment by sebres** [comment]
Thx for the notice.
This is already fixed in 60b36c421380b1ded02c5c6118f9e6dda070249d.

BTW. Because the host is not really a failure-id (always the same), you could use here something other as `<host>` e. g. user name or uid, so simply using `<F-ID>` tag instead of the `<HOST>`...
```diff
-<HOST> sudo:.*pam_unix\(sudo:auth\): authentication failure
# or user-id as failure-id:
+^\s*\S+ sudo: \[[^]]*\]\s+pam_unix\(sudo:auth\): authentication failure; logname=<F-USER>\S+</F-USER> uid=<F-ID>\S+</F-ID>
# or user-name as failure-id also:
+^\s*\S+ sudo: \[[^]]*\]\s+pam_unix\(sudo:auth\): authentication failure; logname=<F-ID><F-USER>\S+</F-USER></F-ID>
```

So jail.local section looks like:
```INI
[sudo]
enabled   = true
logpath   = /var/log/auth.log
filter    =
failregex = ^\s*\S+ sudo: \[[^]]*\]\s+pam_unix\(sudo:auth\): authentication failure; logname=<F-USER>\S+</F-USER> uid=<F-ID>\S+</F-ID>
...
```

Although in the action the variable interpolation `<ip>` will be wrapped to failure-id in this case (because of the compatibility mode), but you could use `<fid>`, `<F-ID>` or `<F-USER>` there in accordance with failregex matching groups.

**Comment by sebres** [comment]
Small amend:
- of course the capturing failure-id via `F-ID` is not affected by `ignoreself`;
- to get in action the host-name, where the failure occurred, you could use `<fq-hostname>` or `<sh-hostname>` tags (current host, fully-qualified or short name).

**Comment by hrkzhrsw** [comment]
Thanks a lot !
I confirmed that I could do what I expected.
I should study about tags <F-ID>, <F-USER> and so on.
