### ISSUE TITLE
Feature Request: failregex capture group to match URI

### ISSUE THREAD

**Issue by ambiguities** [fail2ban/fail2ban#2159]
Hi,

As a long time user of fail2ban it has always suited my needs. Recently I came upon a use case with NGINX where I was unable to implement jailing adequately.

### Use case:
- successive attempts to access a single static file (images, css, etc.) that doesn't exist causing a 404 (bad/malicious traffic)
- a monolothic website with aging components that throw 404's trying to access old resources (legitimate traffic / bots).

### Problem:
I would like to be able to configure fail2ban to jail ip's that are repeatedly trying to access the same non-existent resource within a set amount of time (3+ tries in a second) without jailing legitmate traffic using the application appropriately

### Attempts:
I tried to implement a capture group on a uri where the logs shows a 404 and fail2ban just matches the whole line and doesn't seem to acknowledge the capture group.

### Comment:
I don't know if it is due to my lack of experience with fail2ban that is causing me to be unable able to tackle this use case or if it is a legitimate lack of feature in the application. I feel as though this feature would be a valuable addition but If this feature is infact present I apologize for opening this issue.

**Comment by sebres** [comment]
You can do it using fail2ban, but it could be a bit simpler and faster if you'll configure a special location (with special access- or error-log) as described https://github.com/fail2ban/fail2ban/issues/1962#issuecomment-343856328

As regards the simple capture group (with URI-match), you can take a look for example in https://github.com/fail2ban/fail2ban/blob/0.10/config/filter.d/nginx-botsearch.conf

There is an interpolation variable `block` which describes the URI's to be matched (normally from include botsearch-common.conf, but you can sure overwrite it).

So the simplest filter may look like:
```INI
[Definition]
# allowed method to ban (e. g. : GET|POST|HEAD)
method = [A-Z]+
# http error codes:
code = 404|403|500
# block any uri:
block = \S+
# URI suffix, e.g. any optional path segment after block:
blocksuffix = (?:/\S*)?

failregex = ^<HOST> - \S+ \[\] "(?:<method>) /(?:<block>)<blocksuffix> \S+" (?:<code>)\b
```

For example if you'll set `block` to `(?:(?:php)?[Mm]y[Aa]dmin|(?:[Ss]ql)?adm(?:in)?)` this will ban only URI's starting with this (like phpMyAdmin, admin or sqladm, etc).

But as already said, better it would be if you create special logging-location in nginx (see link above).

**Comment by wirelessmundi** [comment]
Hi,
did you solve your issue whit the capture group? 
I'm trying to do something similar, i want to extract the from the regular expression filter the result with capture group tags but i can't. 
my regular expression is:
"invalid \[(?P<username>[^\]]*)\] from ip <HOST>$"

In my action i try to access to the tag using <username> but is not replaced with the value from the log entry.

**Comment by sebres** [comment]
@wirelessmundi 

> In my action i try to access to the tag ...

1. In version <= 0.9.x it is rather impossible (at least together with host/ip), so try your luck with way described in our wiki [How to ban something other as host (IP-address), like user or mail, etc.](https://github.com/fail2ban/fail2ban/wiki/How-to-ban-something-other-as-host-(IP-address),-like-user-or-mail,-etc.)
2. In version >= 0.10.x, the tag name in filter that is resolvable in action **must be prefixed with `F-`**, without this prefix only reserved tags are usable in actions.

So then your failregex looks like:
```ini
failregex = "invalid \[<F-USER>[^\]]+</F-USER>\] from ip <HOST>$"
```
and your action:
```ini
actionban = do-something-with-user.sh "<F-USER>" ... "<ip>"
```

**Comment by wirelessmundi** [comment]
It works!
 i had try that before but my error was putting the tag name in lower case, <F-user>, it must be all in upper case, the correct is <F-USER>.

thank you!
