### ISSUE TITLE
mistake in fail2ban/config/filter.d/freeswitch.conf

### ISSUE THREAD

**Issue by remdragon** [fail2ban/fail2ban#2163]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.8.13 ( but the bug exists in version 11 in github code tree )
- OS, including release name/version: Debian 8
- [X] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

fail2ban blocks remote workers after a few dial attempts

#### Steps to reproduce

Register a phone from outside the network

#### Expected behavior

An authenticated user should not get banned by fail2ban

#### Observed behavior

Authenticated users are getting banned erroneously.

#### Any additional information

The SIP protocol normally sends a SIP Invite without auth so that it can get a nonce from the FreeSWITCH server.

This causes a "SIP auth challenge (REGISTER)" or "SIP auth challenge (INVITE)" to occur in the logs.

Then FreeSWITCH replies with the authentication "failure" including the nonce information so that client can resend their REGISTER/INVITE with valid credentials.

The default filter in fail2ban/config/filter.d/freeswitch.conf line 24 is blocking users because of the SIP auth challenge.

### Configuration, dump and another helpful excerpts

my jail.local:

```
[ssh]
action = iptables-allports[name=ssh, protocol=all]

[freeswitch]
enabled=true
logpath = /usr/local/freeswitch/log/freeswitch.log

ignoreip = 127.0.0.0/8

maxretry = 4 ; for a total of five failures
findtime = 3600
bantime = 1200 ; 1200=20m

action = iptables-allports[name=freeswitch, protocol=all]

[recidive]
enabled=true
action = iptables-allports[name=recidive, protocol=all]
```

line 24 of filter.d/freeswitch.conf needs to change from this:

failregex = %(_pref_line)s \[WARNING\] sofia_reg\.c:\d+ SIP auth (failure|challenge) \((REGISTER|INVITE)\) on sofia profile \'[^']+\' for \[[^\]]*\] from ip <HOST>$

to this:

failregex = %(_pref_line)s \[WARNING\] sofia_reg\.c:\d+ SIP auth failure \((REGISTER|INVITE)\) on sofia profile \'[^']+\' for \[[^\]]*\] from ip <HOST>$

A "SIP auth challenge" in FreeSWITCH is not an indication by itself that an IP needs to be banned.

#### Any customizations done to /etc/fail2ban/ configuration

nothing other than my jail.local above

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

(n/a)

#### Relevant lines from monitored log files in question:

Here's an example from the logs of a legitimate user's phone registering:

```
2018-06-22 00:36:00.631789 [WARNING] sofia_reg.c:1792 SIP auth challenge (REGISTER) on sofia profile 'internal' for [1047@(SNIP)] from ip (SNIP)
2018-06-22 00:36:21.851823 [WARNING] sofia_reg.c:1792 SIP auth challenge (REGISTER) on sofia profile 'internal' for [1047@(SNIP)] from ip (SNIP)
2018-06-22 00:36:24.371815 [WARNING] sofia_reg.c:1792 SIP auth challenge (REGISTER) on sofia profile 'internal' for [1047@(SNIP)] from ip (SNIP)
```

and here's an illegitimate attempt:

```
2018-06-22 01:17:51.551772 [WARNING] sofia_reg.c:1792 SIP auth challenge (REGISTER) on sofia profile 'internal' for [88888888@(SNIP)] from ip 37.49.231.10
2018-06-22 01:17:55.431781 [WARNING] sofia_reg.c:1792 SIP auth challenge (REGISTER) on sofia profile 'internal' for [88888888@(SNIP)] from ip 37.49.231.10
2018-06-22 01:17:55.611792 [WARNING] sofia_reg.c:2906 Can't find user [88888888@(SNIP)] from 37.49.231.10
You must define a domain called '(SNIP)' in your directory and add a user with the id="88888888" attribute
and you must configure your device to use the proper domain in it's authentication credentials.
2018-06-22 01:17:55.611792 [WARNING] sofia_reg.c:1737 SIP auth failure (REGISTER) on sofia profile 'internal' for [88888888@(SNIP)] from ip 37.49.231.10
2018-06-22 01:17:55.611792 [WARNING] sofia_reg.c:2906 Can't find user [88888888@(SNIP)] from 37.49.231.10
You must define a domain called '(SNIP)' in your directory and add a user with the id="88888888" attribute
and you must configure your device to use the proper domain in it's authentication credentials.
2018-06-22 01:17:55.611792 [WARNING] sofia_reg.c:1737 SIP auth failure (REGISTER) on sofia profile 'internal' for [88888888@(SNIP)] from ip 37.49.231.10
```

**Comment by sebres** [comment]
Strange is that despite this has been implemented since begin of this filter, nobody until now has any problem with the "auth challenge"...
@grooverdan, @fail2ban/contributors any idea?

**Comment by sebres** [comment]
> if you have phones deployed at employee's houses who don't have a static IP address you can trust.

You can use a fqdn (hostname) also (e. g. own or free DNS service for dynamic IP)

> There are scammer that send INVITE but never respond to the challenge, so an "auth failure" never occurs and they can continue hammering the server.

Well, the only way I see currently is to make this regex configurable (to let user decide), like in other filters using mode parameter, similar our other filters, so `mode=ddos` to include this (or if ddos will be default, rather `mode=normal` to avoid match of auth challenge).

>  if fail2ban had a way of asking freeswitch for it's list of SIP registrations so it can auto-ignore those IP addresses.

Too complicated IMHO, especially if it's also dynamical (and should be refreshed periodically).

> I would be willing to help write the code to get the information from freeswitch, but I'd be lost in the fail2ban codebase.

You've 2 simple ways to do that:
- besides `ignoreip` and `ignoreself` fail2ban has also `ignorecommand` parameter, that can be used to check if the failure should be ignored;
- you could use cron or systemd timer-unit to set/actualize ignored IP list using
```bash
fail2ban-client set freeswitch ignoreip "$list"
```

**Comment by sebres** [comment]
I have extended freeswitch-filter with parameter `mode` for both major branches 0.10/0.11
https://github.com/fail2ban/fail2ban/blob/606761b3c7a96328424834e1056a48004f168ad0/config/filter.d/freeswitch.conf#L21-L29 

So you can simply deactivate matching of "challenge register" using mode `normal` in your jail.local as described above.

**Comment by xopr** [comment]
> Strange is that despite this has been implemented since begin of this filter, nobody until now has any problem with the "auth challenge"...
> @grooverdan, @fail2ban/contributors any idea?

Just wanted to add that I had this problem as well (from the beginning and abandoned fail2ban for FreeSWITCH for this reason):
My setup allows external calls to a small set of 'public' numbers/domains, as well as default context calling for registered extensions with dynamic IP addresses.

I came across this issue and since my custom script hangs after a certain amount of time, I'm picking up on fail2ban with the addition of an extra check (next to @remdragon's addition):

In `public.xml` before the subdirectory includes
```<extension name="IP based call">
  <condition field="${acl(${network_addr} trunks)}" expression="false"/>
  <condition field="${sip_to_host}" expression="${local_ip_v4}">
    <action application="log" data="WARNING IP based INVITE not from trunk ${network_addr}"/>
    <action application="respond" data="403"/>
  </condition>
</extension>
```
In `jail.local` (extra, verify logpath)
```[freeswitch-ip]
enabled  = true
port     = 5060,5061,5080,5081
filter   = freeswitch-ip
logpath  = /var/log/freeswitch/freeswitch.log
findtime = 300
maxretry = 0
# ban for a week
bantime  = 604800
action   = iptables-allports[name=freeswitch, protocol=all]
```
and `freeswitch-ip.conf`
```[Definition]
# Remote is calling us by IP in stead of name
#failregex = \[DEBUG\] sofia_reg\.c:\d+ sofia\/external\/.+@\d+\.\d+\.\d+\.\d+\ receiving invite from <HOST> version
failregex = ^.*IP based INVITE not from trunk <HOST>$
ignoreregex =
```
Now, this might not be the best solution (I'm not fail2ban savvy), but it seems to pay off well at first sight.
