### ISSUE TITLE
"ERROR: No failure-id group" from fail2ban-regex on custom filter but <HOST> is specified in failregex=

### ISSUE THREAD

**Issue by andofrjando** [fail2ban/fail2ban#2165]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): Fail2Ban v0.10.2
- OS, including release name/version: Ubuntu 18.04
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

When attempting to create a custom filter and verifying it with `fail2ban-regex`, I receive an error:
```
$ fail2ban-regex -v systemd-journal filter.d/sabnzbd.local

Running tests
=============

Use   failregex line : filter.d/sabnzbd.local
ERROR: No failure-id group in 'filter.d/sabnzbd.local'
```

#### Steps to reproduce
Here's my `filter.d/sabnzbd.local`:
```
[Definition]
failregex = .*API key incorrect.*X-Forwarded-For: <HOST>.*
ignoreregex =
journalmatch = _SYSTEMD_UNIT=sabnzbd.service
```

### Configuration, dump and another helpful excerpts
Here's some output from the journald logs I'm trying to monitor (the `xx.xx.xx.xx` addresses are valid IPs, just removed for the purposes of this post):
```
$ sudo journalctl -f -u sabnzbd.service
Jun 23 18:36:25 io sabnzbdplus[26932]: 2018-06-23 18:36:25,537::WARNING::[interface:331] API key incorrect, Use the API key from Config->General in your 3rd party program: 127.0.0.1 (X-Forwarded-For: xx.xx.xx.xx)>SABmini/388 CFNetwork/901.1 Darwin/17.6.0
Jun 23 18:36:25 io sabnzbdplus[26932]: 2018-06-23 18:36:25,540::WARNING::[interface:331] API key incorrect, Use the API key from Config->General in your 3rd party program: 127.0.0.1 (X-Forwarded-For: xx.xx.xx.xx)>SABmini/388 CFNetwork/901.1 Darwin/17.6.0
Jun 23 18:36:25 io sabnzbdplus[26932]: 2018-06-23 18:36:25,549::WARNING::[interface:331] API key incorrect, Use the API key from Config->General in your 3rd party program: 127.0.0.1 (X-Forwarded-For: xx.xx.xx.xx)>SABmini/388 CFNetwork/901.1 Darwin/17.6.0
Jun 23 18:36:35 io sabnzbdplus[26932]: 2018-06-23 18:36:35,546::WARNING::[interface:331] API key incorrect, Use the API key from Config->General in your 3rd party program: 127.0.0.1 (X-Forwarded-For: xx.xx.xx.xx)>SABmini/388 CFNetwork/901.1 Darwin/17.6.0
```
#### Any customizations done to /etc/fail2ban/ configuration
None

**Comment by sebres** [comment]
> fail2ban-regex -v systemd-journal filter.d/sabnzbd.local

`fail2ban-regex` expects either full-qualified path `/etc/fail2ban/filter.d/sabnzbd.local` or only filter name like `sabnzbd` (works only in fail2ban >= v.0.10).
In your case it causes switch to second syntax variant and performs it as failregex (which indeed does not contain any failure-id group).

**Comment by Jolly-Pirate** [comment]
Also, the same error happens when creating a new filter without reloading or restarting fail2ban. This must be done for the changes to take effect.
