### ISSUE TITLE
Fail2Ban on Ubuntu 18.04.LTS fails to create any chains

### ISSUE THREAD

**Issue by joho1968** [fail2ban/fail2ban#2167]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.10.2
- OS, including release name/version: Ubuntu 18.04.LTS
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

Regardless of how many jails I enable or disable, I do not see any chains creates when listing with iptables --list. We have made modifications only to jail.local (copied from jail.conf). I've re-started F2B a number of times, no difference.

#### Steps to reproduce

Ehrm ... install, enable SSHD (on port 2222) and webmin-auth (on port 10000)

#### Expected behavior

At least two chains to be created :)

#### Observed behavior

Zero chains created.

#### Any additional information

There is no error in the fail2ban log file. Doing a fail2ban-client status shows two jails configured which matches the configuration.

**Comment by sebres** [comment]
Is not a bug, it's a feature: fail2ban v.0.10 has lazy initialization (on demand, thus by the first ban...)
There already enough issues like that, see https://github.com/fail2ban/fail2ban/issues/1755#issuecomment-295286513, #1834 etc.

**Comment by joho1968** [comment]
Just a comment. For things that restore iptables upon reboot, will F2B also restore these chains if there are jailed IPs in its database, upon reboot?

**Comment by sebres** [comment]
Yes, but only for active bans, so if `now < endofban (endofban = startofban + bantime)`.

**Comment by lemieuxl** [comment]
At system reboot, the *recidive* chain is not restored, even though F2B is trying to restore some bans.

For example, according to `fail2ban-client`, right after a system reboot, I see 4 banned IPs in the *recidive* jail, but the *f2b-recidive* iptables chain was not created. Only when I manually restart F2B (using `systemctl restart`), the chain is created and I see the 4 banned IPs.

I'm using F2B version 0.10.3 on a Fedora 28 system.

**Comment by sebres** [comment]
> Only when I manually restart F2B ...

So it works basically. The manually restart does not differ to start (by server restart) in any way...
Therefore I'm pretty sure - either some of your services flushes the iptables chains at start (initiate it after fail2ban going started), or you simply miss some dependency (fail2ban should be started definitelly after this services).

> f2b-recidive iptables chain was not created

I believe it was created, but has been deleted later (from some service), otherwise you should see some error messages in fail2ban.log after first restart.

**Comment by lemieuxl** [comment]
Excellent point. There are no errors in the log until I restart the service. I'll try to investigate a bit, and comment only if relevant.
