### ISSUE TITLE
Starting via systemd gives error: could not read files

### ISSUE THREAD

**Issue by zypA13510** [fail2ban/fail2ban#2169]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 
```
$ yum list installed | grep fail2ban
fail2ban-server.noarch             0.9.7-1.el7               @epel
fail2ban-systemd.noarch            0.9.7-1.el7               @epel
```
- OS, including release name/version: CentOS 7 with custom kernel (see below for more info on a test machine with stock kernel and clean system)
```
$ yum list installed kernel
kernel.x86_64                         3.10.0-862.2.3.el7                         installed
kernel.x86_64                         4.9.86-30.el7                              @centos-virt-xen-46

$ uname -r
4.9.86-30.el7.x86_64
```
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### Steps to reproduce
1. Install fail2ban via `yum install fail2ban-server fail2ban-systemd`
1. Configure the `jail.local` without [shadowsocks] jail
1. Start fail2ban via `systemctl start fail2ban`
    - Without error, fail2ban running.
1. Add the [shadowsocks] jail to the `jail.local`, and create `/etc/fail2ban/filter.d/shadowsocks.conf`, then run `systemctl restart fail2ban`, or reboot the system, if fail2ban service is enabled
    - Error in systemd journal. Fail2ban not started
1. Without any configuration change from last step, run `fail2ban-client -x start` or `fail2ban-client -vvv start`
    - No error, fail2ban running, all 4 jails listed in `fail2ban-client status`

### The issue:

My fail2ban (without too much customization except enabling sshd) worked fine, until I added a custom filter in `/etc/fail2ban/filter.d/` and created a new jail in `jail.local` that use the filter.

Now, whenever I start fail2ban via `sudo systemctl start fail2ban`, it gives the error in systemd journal listed below. **Note: strangely, starting via `sudo /usr/bin/fail2ban-client -x start` will work, despite being the exact same command specified in `/lib/systemd/system/fail2ban.service`.**

#### Any customizations done to /etc/fail2ban/ configuration
====== /etc/fail2ban/jail.local (empty lines removed to save space) ======
```
[DEFAULT]
dbpurgeage = 8640000
bantime  = 3600
findtime  = 600
maxretry = 5
destemail = root@localhost
sender = root@localhost
mta = sendmail
[recidive]
enabled = true
backend = auto
logpath = /var/log/fail2ban.log
banaction = iptables-allports
bantime = 7889238 ; 1 quarter
findtime = 604800 ; 1 week
maxretry = 7
[sshd]
enabled = true
[sshd-ddos]
enabled = true
[shadowsocks]
enabled = true
filter = shadowsocks
banaction = iptables-allports
backend = auto
logpath = /var/log/shadowsocks-*.log
```
====== /etc/fail2ban/filter.d/shadowsocks.conf ======
```
[INCLUDES]
before = common.conf
[Definition]
_daemon = shadowsocks
failregex = ^\s+ERROR\s+can not parse header when handling connection from <HOST>:\d+$
ignoreregex =
```
also tried: [shadowsocks/shadowsocks/master : /utils/fail2ban/shadowsocks.conf](https://github.com/shadowsocks/shadowsocks/blob/0edae7069f6087e6c25b9809ee0a5f651866f154/utils/fail2ban/shadowsocks.conf)

### Configuration, dump and another helpful excerpts
Systemd journal
```
Jun 30 15:57:46 localhost systemd[1]: Starting Fail2Ban Service...
Jun 30 15:57:47 localhost fail2ban-client[1290]: ERROR  Could not read config files: /etc/fail2ban/filter.d/shadowsocks.conf
Jun 30 15:57:47 localhost fail2ban-client[1290]: ERROR  Found no accessible config files for 'filter.d/shadowsocks' under /etc/fail2ban
Jun 30 15:57:47 localhost fail2ban-client[1290]: ERROR  No section: 'Definition'
Jun 30 15:57:47 localhost fail2ban-client[1290]: ERROR  No section: 'Definition'
Jun 30 15:57:47 localhost fail2ban-client[1290]: ERROR  Unable to read the filter
Jun 30 15:57:47 localhost fail2ban-client[1290]: ERROR  Errors in jail 'shadowsocks'.
Jun 30 15:57:47 localhost systemd[1]: fail2ban.service: control process exited, code=255
Jun 30 15:57:47 localhost systemd[1]: Failed to start Fail2Ban Service.
Jun 30 15:57:47 localhost systemd[1]: Unit fail2ban.service entered failed state.
Jun 30 15:57:47 localhost systemd[1]: fail2ban.service failed.
```
**Clean system with stock kernel**: cannot find log file in /var/log/shadowsocks-*.log, despite `ls /var/log/shadowsocks-*.log` showing multiple log files. The exact error output is not saved unfortunately. I'm not sure if this is the same issue, but it seems very similar.

#### Relevant parts of /var/log/fail2ban.log file:
There is no log in `/var/log/fail2ban.log`.

#### Any additional information
```
# exactly the same permission and ownership as other filters
$ ls -la /etc/fail2ban/filter.d/
...
-rw-r--r--. 1 root root  170 Jun 30 16:53 shadowsocks.conf
...
```

**Comment by sebres** [comment]
Can you test starting via command-line as root/sudoer (or simply dump arguments, that loads config-files also)?
```bash
?sudo? fail2ban-client -d
```
If it works, then something may be wrong with the permissions if started as systemd unit.

@fail2ban/maintainers some known issues with fail2ban systemd-unit on CentOS?

**Comment by zypA13510** [comment]
I tried the command
```
sudo fail2ban-client -d > ./fail2ban
```
It finished without error. And I checked the file, it contains the new rule
```
['set', 'shadowsocks', 'addlogpath', '/var/log/shadowsocks-blahblahblah.log', 'head']
...
['set', 'shadowsocks', 'addfailregex', '^\\s+ERROR\\s+can not parse header when handling connection from <HOST>:\\d+$']
...
['start', 'shadowsocks']
```

But if it's related to the permissions, wouldn't it be strange because other files with the same permission and ownership can be read?
And could this be related to SELinux in any way?
