### ISSUE TITLE
fail2ban shows ban but allows accces

### ISSUE THREAD

**Issue by nikhilshah28** [fail2ban/fail2ban#2183]
I am having some issues with fail2ban, it shows that the ip address is banned. 

2018-07-17 00:28:15,204 fail2ban.actions: WARNING [wordpress] Ban 96.234.40.171
2018-07-17 00:28:20,215 fail2ban.actions: INFO   [wordpress] 96.234.40.171 already banned
2018-07-17 00:28:25,221 fail2ban.actions: INFO   [wordpress] 96.234.40.171 already banned

```
iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
fail2ban-wordpress  tcp  --  anywhere             anywhere            

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain fail2ban-wordpress (1 references)
target     prot opt source               destination         
REJECT     all  --  pool-96-234-40-171.nwrknj.fios.verizon.net  anywhere             reject-with icmp-port-unreachable
RETURN     all  --  anywhere             anywhere            

```

however, i can still navigate to the page and try to login. It should throw a connection refused page or something, not allowing users to continue to brute force attack login page.

**Comment by sebres** [comment]
I don't know why it does not work on your server, but it is not a fail2ban issue if you see the corresponding rules in iptables listing.
Possibly your iptables does not work at all (resticted or does not supported in kernel if it's VPS or something else). Rather you should try other ban-action which is supported for you, or find the bug with iptables on your host.

So the question is not "why fail2ban does not work", but "why iptables does not work".
Thus closed as 3rd party issue.
