### ISSUE TITLE
Dovecot regex not detecting attack

### ISSUE THREAD

**Issue by JoshuaaMichael** [fail2ban/fail2ban#2184]
### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

We're running fail2ban (0.9.7) on our mail server here, a CentOS Dovecot/Postfix box. It forwards login requests to our various mail servers on our users behalf.

We were under attack this morning, a few IPs from Russia hit us half a million times and our users couldn't access their accounts.
After a quick look at the logs I could see clearly which IPs were hitting the server so I added them into iptables manually, and stopped the issue.

I've checked the default regex in filter.d for dovecot.conf, and confirmed through fail2ban-regex that it's not picking up on the maillog lines indicating the issue.

I've attached the dovecot.conf and an excerpt from our maillog, the attacking IP addresses are clearly these: 146.185.222.0/24

[dovecot.txt](https://github.com/fail2ban/fail2ban/files/2200377/dovecot.txt)
[maillog.txt](https://github.com/fail2ban/fail2ban/files/2200380/maillog.txt)

#### Expected behavior
That dovecot.conf filter would pickup on this attack and block IPs.

#### Observed behavior
Not blocking IPs.

Any ideas of a direction forward would be great. Not sure if I'd be better for me to just write myself some regex to solve my problem for me, or if it's worth getting in touch with you guys to see if this auth error should be added to fail2ban itself.

**Comment by sebres** [comment]
Well, at least with mode `aggressive` it'll catch some failures here:
```bash
fail2ban-regex -v gh-2184-maillog.txt 'dovecot[mode=aggressive]'
```
<details>

```
Running tests
=============

Use   failregex filter file : dovecot, basedir: /etc/fail2ban
Use   filter options : {'mode': 'aggressive'}
Use      datepattern : Default Detectors
Use         log file : gh-2184-maillog.txt
Use         encoding : UTF-8


Results
=======

Failregex: 17 total
|-  #) [# of hits] regular expression
|   1) [0] ^authentication failure; logname=<F-ALT_USER1>\S*</F-ALT_USER1> uid=\S* euid=\S* tty=dovecot ruser=<F-USER>\S*</F-USER> rhost=<HOST>(?:\s+user=<F-ALT_USER>\S*</F-ALT_USER>)?\s*$
|   2) [0] ^(?:Aborted login|Disconnected)(?::(?: [^ \(]+)+)? \((?:auth failed, \d+ attempts(?: in \d+ secs)?|tried to use (?:disabled|disallowed) \S+ auth)\):(?: user=<<F-USER>[^>]*</F-USER>>,)?(?: method=\S+,)? rip=<HOST>(?:[^>]*(?:, session=<\S+>)?)\s*$
|   3) [0] ^pam\(\S+,<HOST>(?:,\S*)?\): pam_authenticate\(\) failed: (?:User not known to the underlying authentication module: \d+ Time\(s\)|Authentication failure \(password mismatch\?\)|Permission denied)\s*$
|   4) [0] ^[a-z\-]{3,15}\(\S*,<HOST>(?:,\S*)?\): (?:unknown user|invalid credentials|Password mismatch)\s*$
|   5) [17] ^(?:Aborted login|Disconnected)(?::(?: [^ \(]+)+)? \((?:no auth attempts|disconnected before auth was ready,|client didn't finish \S+ auth,)(?: (?:in|waited) \d+ secs)?\):(?: user=<[^>]*>,)?(?: method=\S+,)? rip=<HOST>(?:[^>]*(?:, session=<\S+>)?)\s*$
|      146.185.222.2  Tue Jul 17 09:21:13 2018
|      146.185.222.16  Tue Jul 17 09:21:14 2018
|      146.185.222.16  Tue Jul 17 09:21:14 2018
|      146.185.222.16  Tue Jul 17 09:21:14 2018
|      146.185.222.2  Tue Jul 17 09:21:14 2018
|      146.185.222.2  Tue Jul 17 09:21:14 2018
|      146.185.222.16  Tue Jul 17 09:21:16 2018
|      146.185.222.16  Tue Jul 17 09:21:16 2018
|      146.185.222.2  Tue Jul 17 09:21:16 2018
|      146.185.222.3  Tue Jul 17 09:21:19 2018
|      146.185.222.5  Tue Jul 17 09:21:19 2018
|      146.185.222.2  Tue Jul 17 09:21:20 2018
|      146.185.222.2  Tue Jul 17 09:21:20 2018
|      146.185.222.5  Tue Jul 17 09:21:20 2018
|      146.185.222.2  Tue Jul 17 09:21:22 2018
|      146.185.222.3  Tue Jul 17 09:21:22 2018
|      146.185.222.5  Tue Jul 17 09:21:22 2018
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [100] {^LN-BEG}(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
...
`-

Lines: 100 lines, 0 ignored, 17 matched, 83 missed
[processed in 0.02 sec]
```
</details><br/>

But I'll extend dovecot-filter to cover "proxy dest auth failed" case for failures like:
```
Jul 17 09:21:22 mailproxy dovecot: imap-login: Disconnected (proxy dest auth failed): user=<rtomes@acenet.com.au>, method=PLAIN, rip=192.0.2.1, lip=..., session=<NTI4FiZxcQCSud4G>
```
Please note, v.0.9 will get no updates anymore.

**Comment by sebres** [comment]
So fixed now in mainline (thx), for 0.9 you could use this patch:
```diff
-^%(__prefregex)s(?:Aborted login|Disconnected)(?::(?: [^ \(]+)+)? \((?:auth failed, \d+ attempts(?: in \d+ secs)?|tried to use (?:disabled|disallowed) \S+ auth)\):(?: user=<[^>]*>,)?(?: method=\S+,)? rip=<HOST>(?:[^>]*(?:, session=<\S+>)?)\s*$
+^%(__prefregex)s(?:Aborted login|Disconnected)(?::(?: [^ \(]+)+)? \((?:auth failed, \d+ attempts(?: in \d+ secs)?|tried to use (?:disabled|disallowed) \S+ auth|proxy dest auth failed)\):(?: user=<[^>]*>,)?(?: method=\S+,)? rip=<HOST>(?:[^>]*(?:, session=<\S+>)?)\s*$

**Comment by JoshuaaMichael** [comment]
Sebres,

I appreciate the quick response.
I'll use that patch for now, and I'll see the mainline when it comes through!

Cheers mate,

**Comment by JoshuaaMichael** [comment]
Sebres,

I didn't have __prefregex available (assuming since we're on an older version?) so this didn't work for me straight away. I had to change it to the below by just fixing up just the first part of the command. I checked with the regex testing of fail2ban to verify it works. I'll just leave this here in case someone else comes along. Thanks again for getting back so quickly this morning though.

`^%(__prefix_line)s(?:pop3|imap)-login: (?:Info: )?(?:Aborted login|Disconnected)(?::(?: [^ \(]+)+)? \((?:auth failed, \d+ attempts( in \d+ secs)?|tried to use (disabled|disallowed) \S+ auth)\):( user=<[^>]+>,)?( method=\S+,)? rip=<HOST>(?:, lip=\S+)?(?:, TLS(?: handshaking(?:: SSL_accept\(\) failed: error:[\dA-F]+:SSL routines:[TLS\d]+_GET_CLIENT_HELLO:unknown protocol)?)?(: Disconnected)?)?(, session=<\S+>)?\s*$
`

**Comment by sebres** [comment]
Hmm... I was pretty sure it is old... and in latest 0.9 at least one year:

https://github.com/fail2ban/fail2ban/blob/ea36e1b3fc22f67b2faedb8cb57ae1b19d9f6e08/config/filter.d/dovecot.conf#L13-L16

Anyway you can see the crucial part to extend:
```diff
-... \((?:auth failed, \d+ attempts(?: in \d+ secs)?|tried to use (?:disabled|disallowed) \S+ auth)\) ...
+... \((?:auth failed, \d+ attempts(?: in \d+ secs)?|tried to use (?:disabled|disallowed) \S+ auth|proxy dest auth failed)\) ...
```
