### ISSUE TITLE
Failing to start service returns 0

### ISSUE THREAD

**Issue by Uwila** [fail2ban/fail2ban#2187]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): Fail2Ban v0.10.2
- OS, including release name/version: Ubuntu 18.04
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase

### The issue:
When starting the service fails (using `service fail2ban start` or `/etc/init.d/fail2ban start`, the error code is still 0. This is quite a problem for automation, for example using Ansible, as failing programs are meant to return non-zero codes. The program properly compains over `stderr`, but `stderr` is not a proper way to check for errors in the sense that it can be reliably used by other programs (it is normal for programs to succeed but return debugging info or warnings over `stderr` for example). It would be nice if fail2ban could properly return a non-zero exit code.

#### Steps to reproduce
Start a Docker container using the `ubuntu:18.04` image, and install fail2ban using the package manager. Now run `service fail2ban start` or `/etc/init.d/fail2ban start`.

#### Expected behavior
It expects to find a file at `/var/log/auth.log`, so we should get some error and a non-zero exit code.

#### Observed behavior
We do get an error:
```
 * Starting authentication failure monitor fail2ban
 No file(s) found for glob /var/log/auth.log
 Failed during configuration: Have not found any log file for sshd jail
   ...fail!
```

But the exit code (`echo $?`) is `0`.

**Comment by sebres** [comment]
I cannot reproduce it, I get always `255` as error code in such case, no matter how I try to start it (via client, via server, as fork as well as in foreground):
```
$ sudo fail2ban-client start; echo $?
ERROR   Failed during configuration: Have not found any log file for exim jail
255

$ sudo fail2ban-server; echo $?
ERROR   Failed during configuration: Have not found any log file for exim jail
ERROR   Async configuration of server failed
255

$ sudo fail2ban-server -f; echo $?
ERROR   Failed during configuration: Have not found any log file for exim jail
ERROR   Async configuration of server failed
255
```

So how your init-script does start the fail2ban-service?

We have also client-parameter `-t, --test` to check you've no one error in configuration of fail2ban.
What do you see here:
```
fail2ban-client --test; echo $?
```

**Comment by Uwila** [comment]
The exit code of this line https://github.com/fail2ban/fail2ban/blob/b5dd5adb08f9fd3496f8c63b1d53b0e3c6aabbf1/files/debian-initd#L193 is `2`, but that of the next line is `0`.

Changing this line https://github.com/fail2ban/fail2ban/blob/b5dd5adb08f9fd3496f8c63b1d53b0e3c6aabbf1/files/debian-initd#L194 to `return $?` fixes it to me. I'm not sure what it's trying to achieve right now, it calls `log_end_msg_wrapper` which calls `log_end_msg` which seems undefined; I can't find it in any case.

**Comment by sebres** [comment]
@yarikoptic Can you take a look here, please...

**Comment by yarikoptic** [comment]
eh, its been awhile for that script... may be even the planet was flat then? In #2189 I've suggested some changes you are welcome to try (note that the initd script in repository references /usr/local/bin for the location of fail2ban-client).

**Comment by Uwila** [comment]
@yarikoptic I left a comment in the PR describing one problem I have with it, but that seems like a very small thing to fix.

**Comment by yarikoptic** [comment]
Yeah, fixed there... Better leave comments in that PR relating to changes
