### ISSUE TITLE
Fail2Ban with SERV-U

### ISSUE THREAD

**Issue by Hi-Speed** [fail2ban/fail2ban#2191]
Hi there, sorry I'm new to this group
Just wondering if anyone can help me with what I need to put into the local config file to get f2b to work with a product from Solarwinds called Serv-U

I Think its just the labelling of the section name directive, that I need to match the daemon name.

eg for ssh I know its
[ssh]
enabled  = true
port     = ssh
filter   = sshd
logpath  = /var/log/auth.log
maxretry = 6

I have tried labels from [serv-u] to the daemon name I find when looking at the process name, but nothings seems to make it work, yet I have no issues with ssh, ftp, telnet, everything else seems fine,

I think I'm missing something simple here

Any ideas would be much appreciated.

Im running F2B V0.9.7 on Cent OS 7   with Serv-U 15.1.6

Thanks in advance

**Comment by Hi-Speed** [comment]
Awesome thanks, I have been reading man pages but must have missed this. Will give it a go and come back if I fail at writing this.

**Comment by sebres** [comment]
Then let us know, if I should reopen the issue
