### ISSUE TITLE
'ignorself' variable misspelled in jail.conf config file

### ISSUE THREAD

**Issue by jaychangmcs** [fail2ban/fail2ban#2198]
From line 85 of config/jail.conf:

```
# "ignorself" specifies whether the local resp. own IP addresses should be ignored
# (default is true). Fail2ban will not ban a host which matches such addresses.
#ignorself = true

```
The 'ignorself' variable is misspelled in two places. It should say 'ignoreself'. Setting the variable as 'ignorself' will not work.

**Comment by sebres** [comment]
Fixed in e2a255d104f947f149cc34b17e778c05175e9f78.
Thanks!
