### ISSUE TITLE
Send email only when ban occurs

### ISSUE THREAD

**Issue by marciofoz** [fail2ban/fail2ban#2199]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): fail2ban-0.9.7-1.el7.noarch
- OS, including release name/version: Centos 7.5
- [x] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

I need fail2ban to send email **only** when the ban occurs in SSH section, but what is happening is that it also sends email when the service is started or stopped.

### Desired behavior:
Email is sent only when ban and / or unban happens.

All options in jail.local is default, I only touch the bellow code:
```ini
[sshd]
enabled = true
action = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
         %(mta)s-whois[name=%(__name__)s, sender=fail2ban@example.com, dest=marcio@example.com, protocol="%(protocol)s", chain="%(chain)s"]
maxretry = 2 
logpath = /var/log/messages
```

See a small part of fail2ban.log in debug mode:
```
2018-08-14 08:58:45,847 fail2ban.action         [17536]: DEBUG   printf %b "Subject: [Fail2Ban] sshd: started on `uname -n`
Date: `LC_ALL=C date +"%a, %d %h %Y %T %z"`
From: Fail2Ban <fail2ban@example.com>
To: marcio@example.com\n
Hi,\n
The jail sshd has been started successfully.\n
Regards,\n
Fail2Ban" | /usr/sbin/sendmail -f fail2ban@example.com marcio@example.com
2018-08-14 08:58:45,955 fail2ban.action         [17536]: DEBUG   printf %b "Subject: [Fail2Ban] sshd: started on `uname -n`
Date: `LC_ALL=C date +"%a, %d %h %Y %T %z"`
From: Fail2Ban <fail2ban@example.com>
To: marcio@example.com\n
Hi,\n
The jail sshd has been started successfully.\n
Regards,\n
Fail2Ban" | /usr/sbin/sendmail -f fail2ban@example.com marcio@example.com -- stdout: ''
2018-08-14 08:58:45,955 fail2ban.action         [17536]: DEBUG   printf %b "Subject: [Fail2Ban] sshd: started on `uname -n`
Date: `LC_ALL=C date +"%a, %d %h %Y %T %z"`
From: Fail2Ban <fail2ban@example.com>
To: marcio@example.com\n
Hi,\n
The jail sshd has been started successfully.\n
Regards,\n
Fail2Ban" | /usr/sbin/sendmail -f fail2ban@example.com marcio@example.com -- stderr: ''
2018-08-14 08:58:45,956 fail2ban.action         [17536]: DEBUG   printf %b "Subject: [Fail2Ban] sshd: started on `uname -n`
Date: `LC_ALL=C date +"%a, %d %h %Y %T %z"`
From: Fail2Ban <fail2ban@example.com>
To: marcio@example.com\n
Hi,\n
The jail sshd has been started successfully.\n
Regards,\n
Fail2Ban" | /usr/sbin/sendmail -f fail2ban@example.com marcio@example.com -- returned successfully
```

This is the received email:

Hi,

The jail sshd has been started successfully.

Regards,

Fail2Ban

**Comment by sebres** [comment]
You can simply overwrite `actionstart` and `actionstop` with empty values...

1. No idea this way will work for v.0.9.x (possibly >= 0.10 only), but you can try it, so in your jail.local:
```diff
-         %(mta)s-whois[name=%(__name__)s, sender=fail2ban@example.com, dest=marcio@example.com, protocol="%(protocol)s", chain="%(chain)s"]
+         %(mta)s-whois[name=%(__name__)s, sender=fail2ban@example.com, dest=marcio@example.com, protocol="%(protocol)s", chain="%(chain)s", actionstart="", actionstart=""]
```
2. If it doesn't work for your version, you can create a local file for your `...-whois.conf`, so for example if your `mta` is equal `sendmail`, just create `action.d/sendmail-whois.local` (otherwise `mail-whois.local`) with following content:
```ini
[Definition]
actionstart = 
actionstop =
```

To test the result without restart, just take a look at dump output:
```bash
?sudo? fail2ban-client -d | grep 'sshd.*actionstart'
```
If actionstart is empty - it was overwritten successfully, and you can reload fail2ban.
