### ISSUE TITLE
Fail2ban + Dovecot only bans for invalid usernames

### ISSUE THREAD

**Issue by arnonerba** [fail2ban/fail2ban#2206]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.9.7
- OS, including release name/version: Red Hat Enterprise Linux Server release 7.5 (Maipo)
- [ X ] Fail2Ban installed via OS/distribution mechanisms
- [ X ] You have not applied any additional foreign patches to the codebase

### The issue:

Fail2ban fails to ban Dovecot brute-force attempts when valid usernames are tried. Failed logins with invalid usernames are banned correctly. The provided Dovecot regex matches in either case (tested with fail2ban-regex) since the Dovecot log lines do not differ. The server is using SSSD for user authentication.

#### Steps to reproduce

Attempt to guess passwords for a valid username over IMAP

#### Expected behavior

`fail2ban.filter         [6310]: INFO    [dovecot] Found <redacted>` in /var/log/fail2ban.log

#### Observed behavior

Nothing is written to /var/log/fail2ban.log and no IP addresses are banned.

#### Any additional information

Fail2ban behaves normally with invalid user accounts. The Dovecot logs do not differ except for the username, but the /var/log/secure logs do:

##### Case 1: valid username

`auth: pam_sss(dovecot:auth): authentication failure; logname= uid=0 euid=0 tty=dovecot ruser=valid rhost=<redacted> user=valid`

##### Case 2: invalid username

`auth: pam_unix(dovecot:auth): authentication failure; logname= uid=0 euid=0 tty=dovecot ruser=bogus rhost=<redacted>`

Valid usernames write a `pam_sss` line, while invalid usernames fall back to file authentication and write a `pam_unix` line. Does Fail2ban use additional system log files instead of just the Dovecot log file?

#### Any customizations done to /etc/fail2ban/ configuration
```
[DEFAULT]
bantime = 604800
findtime = 43200
maxretry = 15

backend = systemd

[dovecot]
enabled = true
port = pop3,pop3s,imap,imaps
```

**Comment by sebres** [comment]
This can be just an interim message (for example if dovecot tries several authentication methods) and normally followed by something like `pam_authenticate ... Authentication failure` or `password mismatch`.
Can you provide please an excerpt with all messages that belong to one attempt of the intruder IP?

Additionally note that per default `__pam_auth` is `pam_unix`, like specified in include https://github.com/fail2ban/fail2ban/blob/52377984cd415c089438bdfbcc2c86e344f8ca59/config/filter.d/common.conf#L60-L62
Even to avoid multiple counting of failures by same attempt (faster overflow of `maxretry`).

If you want you can overwrite this value :
- in jail.local
```ini
[dovecot]
filter = dovecot[__pam_auth="pam_\S+"]
```
but no idea this method will work in v.0.9.x (possibly >= v.0.10 only);
- or in filter.d/dovecot.local
```ini
[Definition]
__pam_auth = pam_\S+
```

Since 0.10 you can also test the filter-options using fail2ban-regex like here...
<details>

```bash
$ fail2ban-regex --version
fail2ban-regex 0.10.4.dev1

$ fail2ban-regex 'Aug 23 18:38:50 mail dovecot: auth: pam_sss(dovecot:auth): authentication failure; logname= uid=0 euid=0 tty=dovecot ruser=valid rhost=192.0.2.1 user=valid' dovecot

Running tests
=============

Use   failregex filter file : dovecot, basedir: /etc/fail2ban
Use      datepattern : Default Detectors
Use      single line : Aug 23 18:38:50 mail dovecot: auth: pam_sss(doveco...
...
Lines: 1 lines, 0 ignored, 0 matched, 1 missed

$ fail2ban-regex 'Aug 23 18:38:50 mail dovecot: auth: pam_sss(dovecot:auth): authentication failure; logname= uid=0 euid=0 tty=dovecot ruser=valid rhost=192.0.2.1 user=valid' 'dovecot[__pam_auth="pam_\S+"]'

Running tests
=============

Use   failregex filter file : dovecot, basedir: /etc/fail2ban
Use   filter options : {'__pam_auth': 'pam_\\S+'}
Use      datepattern : Default Detectors
Use      single line : Aug 23 18:38:50 mail dovecot: auth: pam_sss(doveco...
...
Lines: 1 lines, 0 ignored, 1 matched, 0 missed
```
</details>

**Comment by arnonerba** [comment]
You're right, there is a follow-up line in /var/log/secure for valid accounts:

`auth: pam_sss(dovecot:auth): received for user valid: 7 (Authentication failure)`

**However,** your note about the value of `__pam_auth` was extremely helpful. I manually edited the `common.conf` file to say `__pam_auth = pam_sss` and Fail2ban now works properly again. Since this is obviously not the greatest way to solve this I'll see if one of the other config options you mentioned works for my old version of Fail2ban.

Thanks for the quick and simple fix! I had no idea Fail2ban cared whether the system used `pam_sss` or `pam_unix` on the backend.
