### ISSUE TITLE
Nested jails / Increasing bantime / Repeating offenders

### ISSUE THREAD

**Issue by klonos** [fail2ban/fail2ban#221]
I realize that there already exist similar requests in the issue queue but they are all closed and I have no permission to reopen them. So sorry beforehand for filing a duplicate issue, but I'm afraid I had no other choice...

Among the proposed solutions in these other closed issues is the suggestion to resort to permanent bans instead. Since there exist ISPs that rotate the IPs assigned to their customers every 12 or 24h, what one day was an offender IP might the very next day be a perfectly legit one. In the case of DDoS, where zombie hosts are used, we could be talking about several dozens or even hundreds of such potentially "temporary guilty" IPs. So, the permanent ban is no real solution IMO.

I've also had a use case where password change was enforced but a couple of users did not receive their new ones in time. Their failed efforts to login with the old credentials of course caused a ban and having the bantime set to -1 (permanent) resulted in having to then manually remove these banned legit IPs. That's more work for the sys admin and you'll have to admit that this does not scale good.

Allowing to progressively ban an offending IP for an initial duration of say 3h, then for an additional 6, 12, 24h and then move to days and so forth seems like the best solution for such cases. This ensures that these IPs get a lengthier bantime but they do get unbanned eventually. Now, if it were so that the IP was dynamic and indeed rotated at some point by the ISP and there are no attacks from it, it'd stay unbanned - if it still misbehaved, it would get banned for even longer. Providing fine-grained configurability to sys admins seems like the way to do it.

I'm not the person to decide how this would be implemented, but my point is that it is a perfectly legit feature request. Personally, so far I was using 2nd and 3rd tier jails monitoring fail2ban.log, but that stopped working for our servers after upgrading Ubuntu to 13.04 (fail2ban fails to restart).

If this was to implemented internally, I'd suggest to allow the bantime variable in the jail config to accept multiple, comma-separated list of values:

`bantime = 3600, 10800, 21600, 43200, 86400`

That would provide better UX since one would not have to define multiple similar jails.

Now, as for the back-end and the logging/monitoring, I'd either keep separate log files for each jail (now that we have `jail.d/{confilefile}` in 0.8.9, we could also have `jail.d/{logfilefile}`) or have some separate, internal fail2ban.jailhistory.log file or sqlite db. I guess though that if an IP is malicious, then it makes sense to have its ban history be "public" to the rest of the jails.

Thanx for taking the time to read this admittedly lengthy report and for reconsidering this one.

**Comment by sebres** [comment]
implemented in #1460

**Comment by smeijer** [comment]
Is this activated by simple setting `bantime = 3600, 10800, 21600, 43200, 8640` in the `jail.local`? I can't find it in the docs.

**Comment by sebres** [comment]
This currently only in stand of the branch #1460, but I'll merge it as soon as possible in our stock v.10 branch.
@smeijer To the question how activate - see `jail.conf` in https://github.com/fail2ban/fail2ban/pull/1460/files#diff-04e245e7ddfd46056df5e124cd8d5c11R47
```
bantime.increment = true
```

**Comment by vbrozik** [comment]
Will the progressive bantime be ever merged into version 0.10? It would be really useful if this long awaited feature gets into Linux distributions.

**Comment by sebres** [comment]
Nope, it'd violate the versioning rules for certain platforms - v.0.10 gets only updates (fixes and minor changes), all "large" features targeting v.0.11 (where progressive bantime already merged several years ago).

So we will rather release 0.11 - just a lot of things that still bothering me to release it right now (and I simply don't get time to fulfill all this). 
But somehow we should release it (so may be begin of next year).
