### ISSUE TITLE
New install fails - No such file or directory - template.py 

### ISSUE THREAD

**Issue by useronemillion** [fail2ban/fail2ban#2210]
### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: Solaris 11.3 
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Unable to install fail2ban.  When I execute setup.py -install , the script runs, then fails:

Processing fail2ban-0.9.4-py2.7.egg
removing '/usr/lib/python2.7/site-packages/fail2ban-0.9.4-py2.7.egg' (and everything under it)
creating /usr/lib/python2.7/site-packages/fail2ban-0.9.4-py2.7.egg
Extracting fail2ban-0.9.4-py2.7.egg to /usr/lib/python2.7/site-packages
fail2ban 0.9.4 is already the active version in easy-install.pth
error: [Errno 2] No such file or directory: '/usr/lib/python2.7/vendor-packages/setuptools/script template.py'

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
Your python "setuptools" module seems to be broken or you have python versions conflict.
Note that before you try to install something manually, **you MUST unistall the packet previously installed via OS/distribution mechanisms.**
Additionally you should have enough permissions to do all this.

Anyway, closed as third party issue.
