### ISSUE TITLE
WARNING Unable to retrieve Watch object in the log file

### ISSUE THREAD

**Issue by wdrussell** [fail2ban/fail2ban#2216]
### Environment:

- Fail2Ban version (including any possible distribution suffixes):
fail2ban Version 0.10.2
- OS, including release name/version: 
Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-33-generic x86_64)

- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

I have noticed that after setting up fail2ban I get WARNING Unable to retrieve Watch object in the log file

#### Any customizations done to /etc/fail2ban/ configuration
I have used notes from http://lucamattarozzi.blogspot.com/2018/07/ubuntu-1804-fail2ban.html

I have placed files in /etc/fails2ban/jail.d/

```
/etc/fails2ban/jail.d/ssh.conf
[ssh]
enabled  = true
port     = ssh
filter   = sshd
logpath  = /var/log/auth.log
maxretry = 5
/etc/fails2ban/jail.d/sshd.conf
[sshd]
mode = aggressive
enabled = true
port     = ssh
filter   = sshd
logpath  = /var/log/auth.log
maxretry = 2
/etc/fails2ban/jail.d/web.conf
[apache-auth]
enabled  = true
port     = http,https
filter   = apache-auth
logpath  = /var/log/apache*/*error.log
maxretry = 3

[apache-badbots]
enabled  = true
port     = http,https
filter   = apache-badbots
logpath  = /var/log/apache*/*error.log
bantime  = 48h
maxretry = 1

[apache-noscript]
enabled  = true
port     = http,https
filter   = apache-noscript
logpath  = /var/log/apache*/*error.log
maxretry = 3

[apache-overflows]
enabled  = true
port     = http,https
filter   = apache-overflows
logpath  = /var/log/apache*/*error.log
maxretry = 2

[apache-nohome]
enabled  = true
port     = http,https
filter   = apache-nohome
logpath  = /var/log/apache*/*error.log
maxretry = 2

[apache-botsearch]
enable   = true
port     = http,https
filter   = apache-botsearch
logpath  = /var/log/apache*/*error.log
maxretry = 2

[apache-fakegooglebot]
enable   = true
port     = http,https
filter   = apache-fakegooglebot
logpath  = /var/log/apache*/*access.log
maxretry = 1
ignorecommand = %(ignorecommands_dir)s/apache-fakegooglebot 

[apache-modsecurity]
enable   = true
port     = http,https
filter   = apache-modsecurity
logpath  = /var/log/apache*/*error.log
maxretry = 2

[apache-shellshock]
enable   = true
port     = http,https
filter   = apache-shellshock
logpath  = /var/log/apache*/*error.log
maxretry = 1

[php-url-fopen]
enabled = true
port    = http,https
filter  = php-url-fopen
logpath = /var/log/apache*/*access.log
/etc/fails2ban/jail.d/recidive.conf
[recidive]
enabled  = true
logpath  = /var/log/fail2ban.log
filter   = recidive
banaction =  iptables-allports
findtime = 604800  ; 1 week
bantime  = 604800  ; 1 week
maxretry = 3

/etc/fails2ban/jail.d/vsftpd.conf
[vsftpd]

enabled  = true
port     = ftp,ftp-data,ftps,ftps-data
filter   = vsftpd
logpath  = /var/log/vsftpd.log
maxretry = 5
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```

```

#### Relevant lines from monitored log files in question:

```
2018-09-09 06:25:05,700 fail2ban.filterpyinotify[41278]: WARNING Unable to retrieve Watch object associated to <_RawEvent cookie=0 mask=0x2 name='' wd=2 >
2018-09-09 06:25:05,702 fail2ban.filterpyinotify[41278]: WARNING Unable to retrieve Watch object associated to <_RawEvent cookie=0 mask=0x2 name='' wd=2 >
2018-09-09 06:25:05,703 fail2ban.filterpyinotify[41278]: WARNING Unable to retrieve Watch object associated to <_RawEvent cookie=0 mask=0x2 name='' wd=2 >
2018-09-09 06:25:05,705 fail2ban.filterpyinotify[41278]: WARNING Unable to retrieve Watch object associated to <_RawEvent cookie=0 mask=0x2 name='' wd=2 >
```

**Comment by sebres** [comment]
When have you seen this (06:25:05)? Is it a fail2ban restart time? Or possibly the logrotate?

**Comment by wdrussell** [comment]
I am still commissioning this server, I have to reboot a couple of time and have not noticed it recently.
I will check again tomorrow and let you know if its related to the restart time or logrotate.

One other point that I have also noticed is getting this message:
2018-09-10 14:49:44,129 fail2ban.server         [704]: INFO    Jail ssh is not a JournalFilter instance
2018-09-10 14:49:44,130 fail2ban.filter         [704]: INFO    Added logfile: '/var/log/auth.log' (pos = 65325, hash = f106dda4b2826bdc53008deb7327e7f91a003ff2)
What does this relate to?
Do I need to make changes to my config?

**Comment by sebres** [comment]
> One other point that I have also noticed is getting this message
> What does this relate to?

Both are just info (sometimes a bit more info is better as no-info).
Perhaps this belongs rather to DEBUG level... Anyway info is not a warning/error, so just ignore it.

> Do I need to make changes to my config?

No.

**Comment by wdrussell** [comment]
Hi 
I am using fail2ban and also webmin but have noticed in the  /var/webmin/miniserv.error file (within webmin) that there are a lot of messages relating to fail2ban, a subset is shown below:
Subroutine find_value redefined at /usr/share/webmin/fail2ban/fail2ban-lib.pl line 404.
Subroutine find redefined at /usr/share/webmin/fail2ban/fail2ban-lib.pl line 411.
Subroutine filename_to_name redefined at /usr/share/webmin/fail2ban/fail2ban-lib.pl line 421.
Subroutine find_jail_by_filter redefined at /usr/share/webmin/fail2ban/fail2ban-lib.pl line 431.
Subroutine find_jail_by_action redefined at /usr/share/webmin/fail2ban/fail2ban-lib.pl line 447.
Subroutine start_fail2ban_server redefined at /usr/share/webmin/fail2ban/fail2ban-lib.pl line 466.
Subroutine stop_fail2ban_server redefined at /usr/share/webmin/fail2ban/fail2ban-lib.pl line 485.
Subroutine restart_fail2ban_server redefined at /usr/share/webmin/fail2ban/fail2ban-lib.pl line 503.
Subroutine list_all_config_files redefined at /usr/share/webmin/fail2ban/fail2ban-lib.pl line 511.
Subroutine lock_all_config_files redefined at /usr/share/webmin/fail2ban/fail2ban-lib.pl line 527.
Subroutine unlock_all_config_files redefined at /usr/share/webmin/fail2ban/fail2ban-lib.pl line 535.
Subroutine get_fail2ban_version redefined at /usr/share/webmin/fail2ban/fail2ban-lib.pl line 545.

Does this have any relevance and could they be suppressed?

**Comment by sebres** [comment]
This is a fail2ban repository, so we have nothing with webmin. For webmin-related issues you should contact to maintainers of webmin.
