### ISSUE TITLE
Client -status 

### ISSUE THREAD

**Issue by soydepr** [fail2ban/fail2ban#2219]
Have another box and Fail2ban-client status gives me this 

root@coqui:/home/soydepr# fail2ban-client status
 unsupported pickle protocol: 4
root@coqui:/home/soydepr#

I removed and reinstalled Fail2ban and same issue 

I guess main problem is server is running python 3 but reading here i thought reinstall would solve the problem running raspbian stretch

**Comment by sebres** [comment]
It looks like you have still another fail2ban-client that used other python version as the server (check all directories from PATH variable), e. g. you have one in /usr/local/sbin and another in /usr/local/bin.
Simply delete the wrong one (the correct is placed in folder where your fail2ban server started from), so take a look in your init-script / systemd-service or just via `sudo ps -aux | grep fail2ban`.

Also note that it looks like fail2ban-modules are still installed for another version of python (otherwise you had get another error like `ImportError: No module named fail2ban`).

**Comment by soydepr** [comment]
So which one i should delete ?


Last login: Wed Sep 12 07:36:39 2018 from 192.168.1.18
soydepr@coqui:~$ ps aux |grep fail2ban
root      1902  0.1  1.6  48556 15852 ?        Sl   Sep11   1:02 /usr/bin/python3 /usr/bin/fail2ban-server -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid -b
soydepr  10388  0.0  0.0   4376   528 pts/0    S+   09:23   0:00 grep fail2ban
soydepr@coqui:~$ ls -lash /usr/bin/python3
0 lrwxrwxrwx 1 root root 9 Jan 20  2017 /usr/bin/python3 -> python3.5
soydepr@coqui:~$
soydepr@coqui:~$ ls -lash /usr/bin/pyth*
   0 lrwxrwxrwx 1 root root    9 Jan 24  2017 /usr/bin/python -> python2.7
   0 lrwxrwxrwx 1 root root    9 Jan 24  2017 /usr/bin/python2 -> python2.7
3.1M -rwxr-xr-x 1 root root 3.1M Nov 24  2017 /usr/bin/python2.7
   0 lrwxrwxrwx 1 root root    9 Jan 20  2017 /usr/bin/python3 -> python3.5
3.8M -rwxr-xr-x 2 root root 3.8M Jan 19  2017 /usr/bin/python3.5
   0 lrwxrwxrwx 1 root root   36 Jan 19  2017 /usr/bin/python3.5-config -> arm-linux-gnueabihf-python3.5-config
3.8M -rwxr-xr-x 2 root root 3.8M Jan 19  2017 /usr/bin/python3.5m
   0 lrwxrwxrwx 1 root root   37 Jan 19  2017 /usr/bin/python3.5m-config -> arm-linux-gnueabihf-python3.5m-config
   0 lrwxrwxrwx 1 root root   16 Jan 20  2017 /usr/bin/python3-config -> python3.5-config
   0 lrwxrwxrwx 1 root root   10 Jan 20  2017 /usr/bin/python3m -> python3.5m
   0 lrwxrwxrwx 1 root root   17 Jan 20  2017 /usr/bin/python3m-config -> python3.5m-config
soydepr@coqui:~$ ls /usr/local/bin/py*
ls: cannot access '/usr/local/bin/py*': No such file or directory
soydepr@coqui:~$

Confused

**Comment by sebres** [comment]
You should not delete the python, but the `fail2ban-client` (that was installed elsewhere in other bin-folder);
Your server seems to be in `/usr/bin/` (see the output of ps `/usr/bin/python3 /usr/bin/fail2ban-server ...`),
so your `/usr/bin/fail2ban-client` seems to be the correct one.

But if you call `fail2ban-client` not fully qualified one from PATH is found before, therefore you should find and remove it.

What do you see, if you invoke this:
```
?sudo? whereis fail2ban-client
```

Additionally your python version (that fail2ban uses currently) is 3. 
So to completelly cleanup the previous "install", you can also remove fail2ban-directory from 2.7 python library folder (somewhere in `/usr/lib/python2.7/`).
