### ISSUE TITLE
openvpn not logged in fail2vbn.log [pivpn]

### ISSUE THREAD

**Issue by soydepr** [fail2ban/fail2ban#2220]
trying to add pivpn to fail2ban 
when i connect i dont see wny entry in fail2ban log 
however i do see in openvpn.log
how can i confirm this is working 

```
Sep 12 12:30:52 foo ovpn-server[365]: mobile/1xxx.xx.xx.xxx.IV_GUI_VER=net.openvpn.connect.ios_3.0.1-770
```
here is my config 
```ini
# Fail2Ban filter for selected OpenVPN rejections
#
#

[Definition]

# Example messages (other matched messages not seen in the testing server's logs):
# Fri Sep 23 11:55:36 2016 TLS Error: incoming packet authentication failed from [AF_INET]59.90.146.160:51223
# Thu Aug 25 09:36:02 2016 117.207.115.143:58922 TLS Error: TLS handshake failed

failregex = ^ TLS Error: incoming packet authentication failed from \[AF_INET\]<HOST>:\d+$
            ^ <HOST>:\d+ Connection reset, restarting
            ^ <HOST>:\d+ TLS Auth Error
            ^ <HOST>:\d+ TLS Error: TLS handshake failed$
            ^ <HOST>:\d+ VERIFY ERROR

ignoreregex =
```

```ini
[openvpn]
enabled  = true
port     = 1194
protocol = udp
filter   = openvpn
logpath  = /var/log/openvpn.log
maxretry = 2
```

**Comment by sebres** [comment]
> however i do see in openvpn.log

What do you see? This single entry from your log excerpt that you provided, is not an authentication failure, corresponding your filter (failregex).

So if the failure has not yet occurred, why you expect to see something in the fail2ban.log?

> how can i confirm this is working

For example fail2ban-regex is your friend.
```bash
# fail2ban version >= v.0.10 (filter name is enough):
fail2ban-regex /var/log/openvpn.log openvpn
fail2ban-regex 'DATE single log line from IP that is failure you want to check' openvpn
# fail2ban version <= v.0.9 (fully-qualified path to filter):
fail2ban-regex /var/log/openvpn.log /etc/fail2ban/filter.d/openvpn.conf
```

Please note, that this is a development repository and not a stackoverflow or other similar forums and places where you can better ask for how to's.
Also note our [wiki](https://github.com/fail2ban/fail2ban/wiki) where is good described the case "[Fail2ban does not detect some authentication failures resp. banning does not occurred](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works)".
