### ISSUE TITLE
Why isn't fail2ban log sent to the systemd journal?

### ISSUE THREAD

**Issue by ericandrewlewis** [fail2ban/fail2ban#2227]
This is my first issue opened on this repository. Thanks a lot for fail2ban 😃 

### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.9.3
- OS, including release name/version: Ubuntu 16.04
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

I notice that the systemd journal entries for fail2ban are logs for when the fail2ban-server goes up and down:

```
Sep 16 22:41:27 eric-NUC7CJYH systemd[1]: Started Fail2Ban Service.
Sep 16 22:54:33 eric-NUC7CJYH systemd[1]: Stopping Fail2Ban Service...
Sep 16 22:54:34 eric-NUC7CJYH fail2ban-client[6562]: Shutdown successful
Sep 16 22:54:34 eric-NUC7CJYH systemd[1]: Stopped Fail2Ban Service.
Sep 16 22:54:34 eric-NUC7CJYH systemd[1]: Starting Fail2Ban Service...
Sep 16 22:54:34 eric-NUC7CJYH fail2ban-client[6569]: 2018-09-16 22:54:34,596 fail2ban.server         [6570]: INFO    Starting Fail2ban v0.9.3
Sep 16 22:54:34 eric-NUC7CJYH fail2ban-client[6569]: 2018-09-16 22:54:34,596 fail2ban.server         [6570]: INFO    Starting in daemon mode
Sep 16 22:54:34 eric-NUC7CJYH systemd[1]: Started Fail2Ban Service.
```

And that the application logs for fail2ban are kept in `/var/log/fail2ban.log`.

Why aren't the application logs sent to the systemd journal? I know I probably don't understand what the separation of systemd logs and separate `/var/log/` files are for, but hopefully y'all can shed some light.

**Comment by sebres** [comment]
> Why aren't the application logs sent to the systemd journal? 

Because you can self configure whereto fail2ban should log, e. g. in your /etc/fail2ban/fail2ban.local:
```ini
# logging into stdout causes logging to systemd journal, if it running as service.
logtarget = STDOUT
```
Note also the dual date-time issue #1876 you will get in your v.0.9.
Since #1970 (>= v.0.10) you can use `logtarget = SYSOUT` to avoid this (only one date logged in this case).

Just to link - #1403.

**Comment by ericandrewlewis** [comment]
Thank you!
