### ISSUE TITLE
domino-smtp: new filter regex

### ISSUE THREAD

**Issue by jdeniau35** [fail2ban/fail2ban#2228]
### Environment:

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

Many connections from smtp client/server without reverse IP address in DNS. So we want to ban smtp servers or clients without any reverse IP address in DNS.

Domino logs this message:
```
# 19-09-2018 17:25:52   SMTP Server [000527:000013-0000001227564800] Connection from [185.143.223.110] rejected for policy reasons. IP address of connecting host not found in reverse DNS lookup.
```

Domino is configured (configuration document) to reject servers with no reverse IP address.

#### Any customizations done to /etc/fail2ban/filter.d/domino-smtp.conf configuration
```ini
failregex=.....
 ^%(__prefix)sSMTP Server (?:\[[^\]]+\])?\s+Connection from (?:[^\[]+ )*\[<HOST>\]?\s+rejected for policy reasons.*$
```

**Comment by sebres** [comment]
Provided in 58b510a5be3b2399a602680d62a15118dad45cd3, thus closed.
Thx.
