### ISSUE TITLE
Traefik in Docker support

### ISSUE THREAD

**Issue by gurabli** [fail2ban/fail2ban#2240]
Recently migrated to Docker and Traefik (from plain server and nginx). I can't really locate any reference if fail2ban supports Traefik, except some snippets here: [Traefik fail2ban](https://gist.github.com/acundari/9bdcf2ba0c0f8a4bf59a21d06da35612)
I have the Traefik access logs on my host. I also read that botsearch is not recommended.
Anyway, will fail2ban properly capture events from the logs, and implement the proper firewall rules even if using Docker?
Thanks

**Comment by sebres** [comment]
>  I don't need to ban IPs on my server. I would rather ban in my pfSense router or Cloudflare ...

There is a filter proposal, but you talk about actions...
- filter - configuration with set of rules how fail2ban parses logs to find failures;
- action - configuration round about banning (ban, inform admin. etc);

Both have only few things in common. This means you need an action for pfSense or Cloudflare.

**Comment by onedr0p** [comment]
My solution was to send the banned IPs to Cloudflare. Moreover, I am working on a docker image that accesses those banned IPs from Cloudflare API and serves them on a port in my local network as a firewall blocklist. I'll then configure pfSense to read that URL and block incoming requests from those IPs.

**Comment by crazy-max** [comment]
I think we can close this issue in favor of [this](https://github.com/crazy-max/docker-fail2ban/tree/master/examples/jails/traefik) ?

@sebres Apart from this subject, perhaps we could work together to set up an official Docker image for Fail2Ban based on [this one](https://github.com/crazy-max/docker-fail2ban) ?

**Comment by sebres** [comment]
Could you provide a PR for 0.10th branch (filter, entry in jail.conf, test cases = file with same name as filter/jail in fail2ban/tests/files/logs)?

**Comment by crazy-max** [comment]
@sebres ofc

**Comment by sebres** [comment]
Just as an example of new filter PR, see https://github.com/fail2ban/fail2ban/pull/1236/files

**Comment by ThyMYthOS** [comment]
Talking about Docker it would be nice to have special actions for that as well. Recent versions of Docker provide the chain DOCKER-USER for user defined rules. See also https://unrouted.io/2017/08/15/docker-firewall/
