### ISSUE TITLE
Fail2ban-regex works from CLI, but not filter file

### ISSUE THREAD

**Issue by altjx** [fail2ban/fail2ban#2242]
### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): Not sure, but just installed it an hour ago with `apt get install fail2ban`
- OS, including release name/version: Ubuntu 18.04 LTS
- [x] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

I am trying to set up a custom Fail2Ban filter, and I am trying to use an example that I found online just to test things out, and I can't get that to work properly.

For example, here's my log file:
`123.45.67.89 - - [01/Oct/2015:12:46:34 -0400] "POST /wp-login.php HTTP/1.1" 200`

and here's my filter file:
```
[INCLUDES]
before = common.conf

[Definition]
failregex = <HOST> - - \[
```

Now if I run use the failregex entry in the CLI, it works fine:
```
[myuser:ubuntu:/etc/fail2ban]$ fail2ban-regex /home/rails/Documents/rails_app/devise.log "<HOST> - - \["

Running tests
=============

Use   failregex line : <HOST> - - \[
Use         log file : /home/rails/Documents/rails_app/devise.log
Use         encoding : UTF-8


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] <HOST> - - \[
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] Day(?P<_sep>[-/])MON(?P=_sep)ExYear[ :]?24hour:Minute:Second(?:\.Microseconds)?(?: Zone offset)?
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.02 sec]
```
but when I run it with the filter file, it misses it:

```
[myuser:ubuntu:/etc/fail2ban]$ fail2ban-regex /home/rails/Documents/rails_app/devise.log /etc/fail2ban/filter.d/core.conf                                              6:35PM/09.26

Running tests
=============

Use   failregex filter file : core, basedir: /etc/fail2ban
Use      datepattern : Default Detectors
Use         log file : /home/rails/Documents/rails_app/devise.log
Use         encoding : UTF-8


Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:

Lines: 1 lines, 0 ignored, 0 matched, 1 missed
[processed in 0.01 sec]

|- Missed line(s):
|  123.45.67.89 - - [01/Oct/2015:12:46:34 -0400] "POST /wp-login.php HTTP/1.1" 200

```

I'm not sure what the difference is. I ran across another post here as well that referenced something similar, but he had obvious differences in his failregex command vs what his filter was showing. In my case, I literally copied and pasted.

**Comment by altjx** [comment]
Nevermind. Just figured it out. After setting `datepattern = ` to empty in the filter file, everything works fine now.

**Comment by sebres** [comment]
Thus closed
