### ISSUE TITLE
fail2ban using the old log file after logrotate has been run 

### ISSUE THREAD

**Issue by apathyuk** [fail2ban/fail2ban#2243]
### Environment:

- Fail2Ban version:  0.11.0.dev2
- OS, including release name/version:  Ubuntu 14.04.5 LTS (Trusty) 
- [ ] Fail2Ban installed via OS/distribution mechanisms

Installed via git clone (not via the OS distribution means)

- [X] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

When logrotate rotates the fail2ban.log file, it runs `fail2ban-client set logtarget /var/log/fail2ban.log` to point to the new log file.

The new log file is created but the existing fail2ban processes continue to log to the old file which is called fail2ban.log.1 at this point.

The logrotate's postrotate command of fail2ban-client set logtarget /var/log/fail2ban.log worked as the logtarget is correct:

`fail2ban-client  --dp | grep logtarget`
['set', 'logtarget', '/var/log/fail2ban.log']

lsof shows the fail2ban processes are writing to /var/log/fail2ban.log.1

`lsof | grep fail2ban.log`
tail       7342                  root    6r      REG                9,0         0   52166896 /var/log/fail2ban.log
fail2ban- 18875                  root    3w      REG                9,0     62985   52167253 /var/log/fail2ban.log.1
fail2ban- 18875 16689            root    3w      REG                9,0     62985   52167253 /var/log/fail2ban.log.1
fail2ban- 18875 18876            root    3w      REG                9,0     62985   52167253 /var/log/fail2ban.log.1
fail2ban- 18875 18890            root    3w      REG                9,0     62985   52167253 /var/log/fail2ban.log.1
fail2ban- 18875 18891            root    3w      REG                9,0     62985   52167253 /var/log/fail2ban.log.1
fail2ban- 18875 18892            root    3w      REG                9,0     62985   52167253 /var/log/fail2ban.log.1
fail2ban- 18875 18893            root    3w      REG                9,0     62985   52167253 /var/log/fail2ban.log.1

I noticed this issue because I am watching /var/log/fail2ban.log via multitail and tail switched to the new log file but no log info appeared there.  Fail2ban was working fine but was logging to fail2ban.log.1

**Comment by sebres** [comment]
> When logrotate rotates the fail2ban.log file, it runs fail2ban-client set logtarget ...

Nope, it should use `flushlogs`, see
https://github.com/fail2ban/fail2ban/blob/869d99dd377ff45efa5796bb3be2500e41f32dc3/files/fail2ban-logrotate#L11-L12

Thus closed.
