### ISSUE TITLE
Can not override journalmatch entry

### ISSUE THREAD

**Issue by flixman** [fail2ban/fail2ban#2249]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.10.2
- OS, including release name/version: Debian stable/testing
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

In Debian, postfix is started as a systemd's templated service (so postfix@-.service). In my local fail2ban configuration I have this entry:

    [postfix-extra]
    enabled = true
    journalmatch = _SYSTEMD_UNIT=postfix@-.service
    filter = postfix[mode=extra]
    port = smtp,smtps,submission
    backend = systemd

But when showing the status I get:

    |  `- Journal matches:  _SYSTEMD_UNIT=postfix.service

So no entries are banned. If I perform the change to filter.d/postfix.conf file, in the client status I get 

    |  `- Journal matches:  _SYSTEMD_UNIT=postfix@-.service

and offending IPs are properly banned,

#### Steps to reproduce
1. Add a block in jail.d/test.conf containing:

    [postfix-extra]
    enabled = true
    journalmatch = _SYSTEMD_UNIT=postfix@-.service
    filter = postfix[mode=extra]
    port = smtp,smtps,submission
    backend = systemd

2. Restart fail2ban, with a log with offending entries.

#### Expected behavior
Offending entries are banned.

#### Observed behavior
The systemd log for postfix@- is not parsed, no offending entries are banned.

**Comment by sebres** [comment]
the correct way to overwrite filter parameters in jail:
```ini
filter = postfix[mode=extra, journalmatch="_SYSTEMD_UNIT=postfix@-.service"]
```
Anyway if it is a standard name of unit for postfix now, we should possibly append it to the default journalmatch...

**Comment by flixman** [comment]
Right! Thank you very much!

**Comment by FSeidinger** [comment]
Although this issue is closed, I still came across it with the default in Ubuntu LTS 20.04.

After reading the jail.conf(5) manual page, there is another solution. Add the file `/etc/fail2ban/filter.d/postfix.local` with the content:

``` ini
[Init]
# In Debian/Ubuntu, postfix is started as a systemd's templated service
# So match must be done in 'postfix@-.service'
journalmatch = _SYSTEMD_UNIT=postfix@-.service
```

Then the default jail configuration works as expected

**Comment by sebres** [comment]
> Although this issue is closed, I still came across it with the default in Ubuntu LTS 20.04.

This is neither ubuntu nor debian maintainer repository. This contains upstream version regardless distribution related stuff and configurations.
Just a note for @fail2ban/maintainers

I don't really know whether it a standard name of unit for postfix now (and for which versions and distributions it is valid)...

As regards "default", this is either what one expects from "default" for a fully configurable tool like fail2ban. I guess it is impossible to provide a completely working out of the box configuration for every service or software of every distribution.
Consider fail2ban as a tool which must be configured and each jail validated whether it works.

**Comment by seanm** [comment]
I hit the same problem on Debian 12 (current newest). @FSeidinger solution worked for me.

Anyone know if the same is needed for `[postfix-sasl]` and `[postfix-rbl]`?

Is there nothing the fail2ban project can do to make this work out of the box?  Latest Debian is not exactly an obscure edge-case environment...

**Comment by sebres** [comment]
> Anyone know if the same is needed for `[postfix-sasl]` and `[postfix-rbl]`?

The jails use the same filter:
https://github.com/fail2ban/fail2ban/blob/2d736ad7550c766efc56976cfb731ebf8acd008b/config/jail.conf#L593-L595
https://github.com/fail2ban/fail2ban/blob/2d736ad7550c766efc56976cfb731ebf8acd008b/config/jail.conf#L679-L681

By the way, one can use `postfix` jail with `mode = extra` (or `mode = aggressive`) to combine all 3 jails to single one.

> Is there nothing the fail2ban project can do to make this work out of the box? 
> Latest Debian is not exactly an obscure edge-case environment...

It is already done in d260ed31d2f39480929c2d8502f070eeb4480e2d (#3692)...

Neither we are not responsible for maintainer distributions, nor for their updates, the fail2ban project also releases [deb-packets](https://github.com/fail2ban/fail2ban/releases/tag/1.1.0). 
However such stuff is rather a configuration issue and can surely be done by oneself.
It is not about Debian - we simply cannot provide the complete and up-to-date configuration for all services across all distributions and any of their versions. It is impossible.

**Comment by seanm** [comment]
> By the way, one can use `postfix` jail with `mode = extra` (or `mode = aggressive`) to combine all 3 jails to single one.

Thanks, I'll try aggressive mode.
 
> It is already done in [d260ed3](https://github.com/fail2ban/fail2ban/commit/d260ed31d2f39480929c2d8502f070eeb4480e2d) ([#3692](https://github.com/fail2ban/fail2ban/pull/3692))...

Oh sorry, I somehow missed that.

That was almost a year ago, and my Debian is fully up-to-date. Strange/disappointing that the fix is not there yet. :(  (I'm more accustomed to FreeBSD where keeping packages up-to-date is easier.)
