### ISSUE TITLE
[Question] Log Format

### ISSUE THREAD

**Issue by zero77** [fail2ban/fail2ban#2250]
Where can I find information of what format logs have to be in to be compatible with Fail2Ban.
Thanks

**Comment by sebres** [comment]
To be compatible? It doesn't need to be "compatible"... All you need is:
- a date-time when is failure occurred, better in the system time zone (fail2ban supports several date-time formats, but it can be also configured separately via `datepattern` parameter);
- an unique identifier of the intruder (most the IP address, but if not IP-related it could be also an e-mail, or user, etc);
- some message part that obviously identifies a failed attempt (like `Authentication failed: invalid password`);

#### As an example:
```
2018-09-30 23:05:55 WARN AUTH-ERROR: 192.0.2.1 - Authentication failed for user "tester": user unknown
2018-09-30 23:15:03 WARN AUTH-ERROR: 192.0.2.5 - Authentication failed for user "root": user disallowed
2018-09-30 23:18:05 WARN AUTH-ERROR: 192.0.2.8 - Authentication failed for user "admin": invalid password
```
#### Note the best practices also:
- the unique characteristic of failure (here `AUTH-ERROR`) as well as the identifier (here IPs) as early as possible in the message (could be found faster and with fewer load during the search);
- foreign data (user input), if needed to be logged, should be escaped (if possible) and/or placed at end of line (so the parser does not need to traverse this info to find all expected failure characteristics)
- if possible write it into separate log-file (or log-file with few errors) or if logged into systemd-journal resp. rsyslog provide it with some unique marks (e. g. severity: warning/critical, facility: security/auth, etc), to make possible to use selectors (to avoid parasite "traffic" by searching of the failures).

**Comment by zero77** [comment]
@sebres 
Thanks
