### ISSUE TITLE
fail2ban ImapSSLServer

### ISSUE THREAD

**Issue by rickygm** [fail2ban/fail2ban#2251]
I am trying to make fail2ban work with zimbra, I have many accounts that are blocked by failed attempts, add this filter to fail2ban, but I can not block the ip.

see log of Zimbra:
```
      1 2018-10-06 12:32:23,142 WARN  [ImapSSLServer-1] [ip=192.168.20.50;oip=177.128.120.174;via=192.168.20.52(nginx/1.7.1);ua=Zimbra/8.8.8_GA_3008;cid=234;] security - cmd=Auth; account=usuario1@domain.com.org; protocol=imap; error=authentication failed for [usuario1@domain.com.org], invalid password;
      1 2018-10-06 12:31:54,512 WARN  [ImapSSLServer-1] [ip=192.168.20.50;oip=77.45.74.161;via=192.168.20.52(nginx/1.7.1);ua=Zimbra/8.8.8_GA_3008;cid=233;] security - cmd=Auth; account=usuario1@domain.com.org; protocol=imap; error=authentication failed for [usuario1@domain.com.org], invalid password;
      1 2018-10-06 12:31:26,050 WARN  [ImapSSLServer-1] [ip=192.168.20.50;oip=85.236.8.74;via=192.168.20.52(nginx/1.7.1);ua=Zimbra/8.8.8_GA_3008;cid=232;] security - cmd=Auth; account=usuario1@domain.com.org; protocol=imap; error=authentication failed for [usuario1@domain.com.org], invalid password;
      1 2018-10-06 12:30:59,038 WARN  [ImapSSLServer-1] [ip=192.168.20.50;oip=198.179.56.254;via=192.168.20.52(nginx/1.7.1);ua=Zimbra/8.8.8_GA_3008;cid=231;] security - cmd=Auth; account=usuario1@domain.com.org; protocol=imap; error=authentication failed for [usuario1@domain.com.org], invalid password;
      1 2018-10-06 12:30:30,786 WARN  [ImapSSLServer-1] [ip=192.168.20.50;oip=71.43.136.234;via=192.168.20.52(nginx/1.7.1);ua=Zimbra/8.8.8_GA_3008;cid=230;] security - cmd=Auth; account=usuario1@domain.com.org; protocol=imap; error=authentication failed for [usuario1@domain.com.org], invalid password;
      1 2018-10-06 12:27:40,473 WARN  [ImapSSLServer-1] [ip=192.168.20.50;oip=177.53.74.33;via=192.168.20.52(nginx/1.7.1);ua=Zimbra/8.8.8_GA_3008;cid=226;] security - cmd=Auth; account=usuario2@domain.com.org; protocol=imap; error=authentication failed for [usuario2@domain.com.org], invalid password;
      1 2018-10-06 12:27:11,410 WARN  [ImapSSLServer-1] [ip=192.168.20.50;oip=177.130.55.230;via=192.168.20.52(nginx/1.7.1);ua=Zimbra/8.8.8_GA_3008;cid=225;] security - cmd=Auth; account=usuario2@domain.com.org; protocol=imap; error=authentication failed for [usuario2@domain.com.org], invalid password;
      1 2018-10-06 12:26:41,687 WARN  [ImapSSLServer-1] [ip=192.168.20.50;oip=201.11.180.146;via=192.168.20.52(nginx/1.7.1);ua=Zimbra/8.8.8_GA_3008;cid=224;] security - cmd=Auth; account=usuario2@domain.com.org; protocol=imap; error=authentication failed for [usuario2@domain.com.org], invalid password;
```
**I** show the filter that I added to fail2ban

imap.conf
```ini
[Definition]
failregex = \[ip=<HOST>;\] imap - authentication failed for .* \(invalid password\)$
ignoreregex =
```
jail.conf 
```ini
[imap]
enabled = true
port = imaps
filter = imap
action = iptables-multiport[name=Imap, port=imaps, protocol=tcp]
logpath = /opt/zimbra/log/mailbox.log
bantime = 628800
maxretry = 3
```
fail2ban-regex /opt/zimbra/log/mailbox.log /etc/fail2ban/filter.d/imap.conf
```
Running tests
=============

Use   failregex filter file : imap, basedir: /etc/fail2ban
Use         log file : /opt/zimbra/log/mailbox.log
Use         encoding : UTF-8


Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [152829] Year(?P<_sep>[-/.])Month(?P=_sep)Day 24hour:Minute:Second(?:,Microseconds)?
`-

Lines: 153050 lines, 0 ignored, 0 matched, 153050 missed
[processed in 23.69 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all 153050 lines
```
some idea or help?, these guys have me tired

regards

**Comment by sebres** [comment]
If you'll change it like here:
```diff
- failregex = \[ip=<HOST>;\] imap - authentication failed for .* \(invalid password\)$
+ failregex = \[ip=<HOST>;.*\] .*authentication failed for .* invalid password;$
```
it will work, but this regex would be too vulnerable. 

So use something like this:
```ini
filter = \[ip=<HOST>;[^\]]*\] security - cmd=Auth; account=[^;]*; protocol=\w+; error=authentication failed for \[[^\]]*\], invalid password;\s*$
```

**Comment by rickygm** [comment]
Hi , I made the change, but I can not ban 

look:

iptables -w -X f2b-Imap -- stderr: "iptables v1.4.21: Couldn't load target `f2b-Imap':No such file or directory\n\nTry `iptables -h' or 'iptables --help' for more information.\niptables: No chain/target/match by that name.\niptables: No chain/target/match by that name.\n"

2018-11-04 20:26:14,692 fail2ban.actions        [30345]: ERROR   Failed to stop jail 'imap' action 'iptables-multiport': Error stopping action
2018-11-04 20:26:14,713 fail2ban.jail           [30345]: INFO    Jail 'imap' stopped

**Comment by sebres** [comment]
Your excerpt is too short, so I don't see why the jail can not properly **stop** the action (possibly the iptables chains was flushed from some script/service outside of fail2ban)...
Anyway this said nothing about "can not ban", it was solely the stop of the imap jail... Not a start (a jail should be started to do the job).

Take a look to our [wiki](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works) and FAQ there, it can help you by troubleshooting.

At least is interesting - do you see some errors, if you start/restart fail2ban (in console as well as in fail2ban log, but really after restart - so new timestamp and after pid of process has been changed there)...

**Comment by rickygm** [comment]
ok , You're right, I have some warning inside the config of fail2ban, I'll check and tell you how to act after making the change.

● fail2ban.service - Fail2Ban Service
   Loaded: loaded (/usr/lib/systemd/system/fail2ban.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2018-11-09 17:09:42 CST; 1s ago
     Docs: man:fail2ban(1)
  Process: 8796 ExecStop=/usr/bin/fail2ban-client stop (code=exited, status=0/SUCCESS)
  Process: 8839 ExecStart=/usr/bin/fail2ban-client -x start (code=exited, status=0/SUCCESS)
 Main PID: 8842 (fail2ban-server)
   CGroup: /system.slice/fail2ban.service
           └─8842 /usr/bin/python2 -s /usr/bin/fail2ban-server -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid -x -b

Nov 09 17:09:41 node-01.fomav.gob.ni systemd[1]: Starting Fail2Ban Service...
Nov 09 17:09:41 node-01.fomav.gob.ni fail2ban-client[8839]: WARNING 'failregex' not defined in 'Definition'. Using default one: ''
Nov 09 17:09:41 node-01.fomav.gob.ni fail2ban-client[8839]: WARNING 'failregex' not defined in 'Definition'. Using default one: ''
Nov 09 17:09:42 node-01.fomav.gob.ni fail2ban-client[8839]: 2018-11-09 17:09:42,168 fail2ban.server         [8840]: INFO    Starting Fail2ban v0.9.7
Nov 09 17:09:42 node-01.fomav.gob.ni fail2ban-client[8839]: 2018-11-09 17:09:42,169 fail2ban.server         [8840]: INFO    Starting in daemon mode
Nov 09 17:09:42 node-01.fomav.gob.ni systemd[1]: Started Fail2Ban Service.
