### ISSUE TITLE
action abuseipdb.conf

### ISSUE THREAD

**Issue by CHazz** [fail2ban/fail2ban#2253]
if you have your own web server with PHP available, you can  use my (Shaun's) helper PHP script by commenting out the first actionban line below, uncommenting the second one, and pointing the URL at wherever you install the helper script.

its great .. but second line not exist .. 

please help me with config to latest f2b .. old configs not work :(

thanks

**Comment by sebres** [comment]
If you look further:
https://github.com/fail2ban/fail2ban/blob/d01fe9d22a717a0122143cde41ce5c18a1790f6e/config/action.d/abuseipdb.conf#L80-L81
you can open the URL and you'll see the commented second line that calls php-script `report-api.php` on your site:
```ini
actionban = curl --fail --ciphers ecdhe_ecdsa_aes_256_sha --data 'key=<abuseipdb_apikey>' --data-urlencode 'comment=<matches>' --data 'ip=<ip>' --data 'category=<abuseipdb_category>' "https://www.abuseipdb.com/report/json"
#actionban = curl --fail --data 'key=<abuseipdb_apikey>' --data 'comment=<matches>' --data 'ip=<ip>' --data 'category=<abuseipdb_category>' "http://yoursite.example.com/abuseipdb/report-api.php"
```

> please help me with config to latest f2b .. old configs not work :(

Please read our issue template attentively - "not work" does not help us.
Thus closed until more infos provided.
