### ISSUE TITLE
fail2ban-0.10.4 fails to install under python3

### ISSUE THREAD

**Issue by smitelli** [fail2ban/fail2ban#2255]
Trying to install fail2ban-0.10.4, from the GitHub release tarball, using Python 3.5.3 as packaged in Debian Stretch, I receive:

    # /usr/bin/python3 setup.py install --force

    Traceback (most recent call last):
      File "setup.py", line 58, in <module>
        from fail2ban.setup import updatePyExec
      File "/usr/local/src/fail2ban-0.10.4/fail2ban/__init__.py", line 88, in <module>
        _init()
      File "/usr/local/src/fail2ban-0.10.4/fail2ban/__init__.py", line 85, in _init
        for i in xrange(50):
    NameError: name 'xrange' is not defined

Installs correctly if I switch back to Python 2.7. The setup worked properly in 0.10.3.1, which leads me to think that I shouldn't need to downgrade back to python2 to get this to work.

I haven't tried patching the source to see if that is the only place where python3 complains about python2-style code (I don't have a non-production install readily available to experiment on).

**Comment by sebres** [comment]
Hmm, strange... normally our setup.py uses a 2to3 internally, but it seems to be too late now (dependency issue). Thanks for your feedback, I'll fix it. 
While it is still not fixed, simply call `2to3` in fail2ban install-folder manually **before** you call setup.

**Comment by sebres** [comment]
fixed in 657b147c0d7830f3600f3dc7feaa4815a7e19fde

**Comment by angeloc** [comment]
@sebres : I'm using the latest stable release for packaging in buildroot, and I'm having trouble with this issue. Could you release a new stable release with this fix included?
Thanks!
