### ISSUE TITLE
help : error ban no valid date/time found for XXXXX

### ISSUE THREAD

**Issue by fbclol** [fail2ban/fail2ban#2265]
Hello,

I come to you for help I got this result in fail2ban the latest version 0.11 in the debian distribution
I do my test on a wordpress test to do it later in production on different servers in the company in which I work.

I can not do the right method for the date
I saw on several places that we had to add something like this
```ini
datepattern = %d-%b-%Y%H:%M:%S.%N
```
but I have another mistake:
```
Failed during configuration: '%' must be followed by '%' or '(', found: '% N'
```
moreover I have another problem is the recovery of the ip of the host is distorted because I use docker + traefik to solve my different web application. if a person has a solution for this I am a taker.
```
[29809]: WARNING Found a match for u'172.18.0.2 - - [28/Oct/2018:16:04:52 +0000] "POST /wp-login.php HTTP/1.1" 200 1918 "https://wordpress.fbclol.fr/wp-login.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"' but no valid date/time found for u'172.18.0.2 - - [28/Oct/2018:16:04:52 +0000] "POST /wp-login.php HTTP/1.1" 200 1918 "https://wordpress.fbclol.fr/wp-login.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"'. Please try setting a custom date pattern (see man page jail.conf(5)). If format is complex, please file a detailed issue on https://github.com/fail2ban/fail2ban/issues in order to get support for this format.
```

**Comment by sebres** [comment]
However the `datepattern` for checking via `fail2ban-regex` is to specify with single `%`-char, within python-config files (which are fail2ban configs also) the percent-character should be escaped (as dual percent-char `%%`).
Additionally the proper value for `[28/Oct/2018:16:04:52 +0000]` would be something like:
```ini
datepattern = %%d/%%b/%%Y:%%H:%%M:%%S %%z
```

**Comment by fbclol** [comment]
It's okey 

Perfect ! 👍

**Comment by MrCrap** [comment]
> However the `datepattern` for checking via `fail2ban-regex` is to specify with single `%`-char, within python-config files (which are fail2ban configs also) the percent-character should be escaped (as dual percent-char `%%`).
> Additionally the proper value for `[28/Oct/2018:16:04:52 +0000]` would be something like:
> 
> ```ini
> datepattern = %%d/%%b/%%Y:%%H:%%M:%%S %%z
> ```

thats work for me too !!
Thanks

**Comment by e1nh4nd3r** [comment]
Can this be thrown into documentation somewhere?  It'd be super nice to be able to find this a lot more easily in the future.

**Comment by sebres** [comment]
> Can this be thrown into documentation somewhere?

Hmm... is it not already?

[jail,.conf(5)](https://manpages.debian.org/experimental/fail2ban/jail.conf.5.en.html#FILTER_FILES_(filter.d/*.conf))

> NOTE: due to config file string substitution, that %'s must be escaped by an % in config files.

Or our man-sources: https://github.com/fail2ban/fail2ban/blob/46fc4c461588118b0c617de0528f095ccf7d9e4f/man/jail.conf.5#L446-L451
