### ISSUE TITLE
Ban not added to database/iptables

### ISSUE THREAD

**Issue by clontarfx** [fail2ban/fail2ban#2268]
Fail2Ban v0.10.2

Default postfix-ddos match rules.

Ban is not being added to either fail2ban.sqlite3 or iptables despite being matched more than 3 times in the past 2 hours.

```# cat fail2ban.log | grep 185.234.219.254
...
[postfix-ddos] Found 185.234.219.254 - 2018-11-02 14:30:10
[postfix-ddos] Found 185.234.219.254 - 2018-11-02 14:48:25
[postfix-ddos] Found 185.234.219.254 - 2018-11-02 15:06:22
```

```
root@###:/etc/fail2ban/filter.d# fail2ban-regex /var/log/mail.log postfix --print-all-matched | grep 185.234.219.254
|  Nov  2 04:40:25 ### postfix/smtpd[24757]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 05:05:54 ### postfix/smtpd[25146]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 05:23:32 ### postfix/smtpd[25469]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 05:41:14 ### postfix/smtpd[25779]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 05:59:19 ### postfix/smtpd[26110]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 06:17:26 ### postfix/smtpd[26416]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 06:35:22 ### postfix/smtpd[26926]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 06:53:15 ### postfix/smtpd[27244]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 07:11:32 ### postfix/smtpd[27946]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 07:29:33 ### postfix/smtpd[28173]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 07:47:37 ### postfix/smtpd[28488]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 08:05:33 ### postfix/smtpd[28748]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 08:23:23 ### postfix/smtpd[29105]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 08:41:20 ### postfix/smtpd[29395]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 08:59:20 ### postfix/smtpd[29659]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 09:17:22 ### postfix/smtpd[29964]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 09:35:25 ### postfix/smtpd[30229]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 09:53:19 ### postfix/smtpd[30580]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 10:11:24 ### postfix/smtpd[30900]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 10:49:35 ### postfix/smtpd[31514]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 11:07:35 ### postfix/smtpd[31767]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 11:25:32 ### postfix/smtpd[32123]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 12:41:33 ### postfix/smtpd[995]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 12:59:38 ### postfix/smtpd[1302]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 13:17:52 ### postfix/smtpd[1899]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 13:36:01 ### postfix/smtpd[2169]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 13:53:57 ### postfix/smtpd[2474]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 14:12:01 ### postfix/smtpd[2789]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 14:30:10 ### postfix/smtpd[3056]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 14:48:25 ### postfix/smtpd[3384]: lost connection after AUTH from unknown[185.234.219.254]
|  Nov  2 15:06:22 ### postfix/smtpd[5625]: lost connection after AUTH from unknown[185.234.219.254]
```

![image](https://user-images.githubusercontent.com/470233/47893792-d5046e00-de99-11e8-8f7e-505db50ae3b6.png)

```
# /var/lib/fail2ban# iptables -L -n | grep 185.234.219.254
# /var/lib/fail2ban#
```

```
bantime  = -1
findtime = 7200
maxretry = 3
```

**Comment by sebres** [comment]
Hmm, very weird.
Do you see something else by `?sudo? grep 185.234.219.254 /var/log/fail2ban.log`?
Have you checked ignoreip (ignoreself, ignorecommand) values?

Do you have changed `findtime` and if yes does this change occurred before 14:30 (first failure time) and was fail2ban reloaded after the change?
To get the current realtime value:
```
?sudo? fail2ban-client get postfix-ddos findtime
```

Also note that fail2ban will ignore too old failures, so be sure that the TZ in log-file is correct (the same as the system time zone, resp. timezone fail2ban work at the moment), no restart of fail2ban in-between happens, etc.

By the way, I'm pretty sure you would not really like to do persistent ban after 3 failures like this - for example a network error (unstable connection) could theoretically cause the same error, so you can ban this way a legitimate users (resp. their IPs).

**Comment by clontarfx** [comment]
Checked ignore settings, only ignoring localhost.

I did change the findtime setting only after I found that it wasn't working. Previously findtime was set to 3600 which wasn't capturing these particular attempts (every 18 minutes).

These types of connections have stopped occurring though and I have since created a simple postfix-helo jail and filter and this seems to be working OK. I note that the format for postfix filter has changed since I last looked at it (fail2ban 0.93) so I am not too comfortable with troubleshooting this new format.

For now I recommend closing this, and if I see something similar happen again I'll follow the diagnosis steps above 👍

**Comment by sebres** [comment]
> I am not too comfortable with troubleshooting this new format.

Well the format (resp. regex's) is almost the same, just it has got a `prefregex`, which does the pre-filtering and regex's are mode-related now (`failregex` as well as `prefregex` are interpolated corresponding parameter `mode`).
To see which real regex-list is used, just execute `fail2ban-client -d | grep postfix-ddos`.

Anyway if you see `[postfix-ddos] Found <IP> ...` the jail (as well as the filter) is working properly (the message is written from FailManager that captures the failure), just something seems to avoid execute ban (date is too old, wrong TZ, something else).

BTW you don't need an extra jail (postfix-ddos) to use ddos rules (if other parameters like `findtime`/`bantime` are the same), simply set `mode` of jail `postfix` to `aggressive`, it will cumulate all the rules in single jail:
```ini
[postfix]
mode = aggressive
enabled = true
```

> For now I recommend closing this...

Ok, thus closed until more info known.
