### ISSUE TITLE
IP ignore list does not use regex ?

### ISSUE THREAD

**Issue by HappyUncle** [fail2ban/fail2ban#2269]
when I add ip ignore list , I have found

```
[root@ai fail2ban]# fail2ban-client get sshd ignoreip
These IP addresses/networks are ignored:
|- 127.0.0.1/8
|- and
`- 192.168.222.1
```

is that ok?

I think add IP regex is better.

**Comment by sebres** [comment]
> is that ok?

What you are expecting?

> I think add IP regex is better.

A list of IP address (resp. a subnet mask) is totally enough for ignore purposes.
For an ignore entry as DNS (FQDN) a regexp or grep match would be possibly interesting, but in this case fail2ban have to do a reverse DNS lookup each time it founds a failure, thus it is simply more expensive.
But if you have own DNS service locally, you can simply create a zone that have several IPs and simply add this FQDN to ignore list.

Furthermore fail2ban has still another handling `ignorecommand` for any other purposes you may need.
See for example https://github.com/fail2ban/fail2ban/issues/2013#issuecomment-426940189
