### ISSUE TITLE
Log detalization

### ISSUE THREAD

**Issue by mmazay** [fail2ban/fail2ban#2270]
Hi.
When I used fail2ban 0.9.x I had such log: 
```
2018-10-30 01:38: 54,648 fail2ban.filter [8827]: INFO [sshd] Found 178.128.63.158
2018-10-30 01:38: 56,425 fail2ban.filter [8827]: INFO [sshd] Found 178.128.63.158
2018-10-30 01:38: 56,429 fail2ban.filter [8827]: INFO [sshd] Found 178.128.63.158
2018-10-30 01:38: 58,003 fail2ban.filter [8827]: INFO [sshd] Found 178.128.63.158
2018-10-30 01:38: 58,355 fail2ban.actions [8827]: NOTICE [sshd] Ban 178.128.63.158
```
Now I have installed version 0.10 and now I have this log:
```
2018-11-08 13:16: 51,039 fail2ban.filter [20377]: INFO [sshd] Found 217.61.104.180 - 2018-11-08 13: 16: 50
2018-11-08 13:16: 54,134 fail2ban.filter [20377]: INFO [sshd] Found 217.61.104.180 - 2018-11-08 13: 16: 53
2018-11-08 13:16: 54,294 fail2ban.filter [20377]: INFO [sshd] Found 217.61.104.180 - 2018-11-08 13: 16: 54
2018-11-08 13:16: 54,586 fail2ban.actions [20377]: NOTICE [sshd] Ban 217.61.104.180
```
Could you please tell me, how can I remove from the log duplicate information about the date and (or) time at the end of the line, and bring the log to the form that was 0.9.x ?
Thanks.

**Comment by sebres** [comment]
Shortly - you can not remove this extra data (this is fest coded).
But this is not the "duplicate" information (despite both could be the same):
- left part is the time as fail2ban found the failure (logged in fail2ban.log)
- right part is the time the fail2ban parses the date in the log-file (or journal)

This info helps to resolve some issues, like wrong time-zone resp. bypass of some failures (which belongs rather to the restored tickets, etc).
If this info's bother you, you can set your fail2ban log-level (in fail2ban.local) to NOTICE (and reload), so you will not see INFO messages anymore.

**Comment by mmazay** [comment]
Bad luck, I was hoping it could be removed.
Thank you very much for your prompt response.

**Comment by sebres** [comment]
> Bad luck, I was hoping it could be removed.
Well, it is possible:
- either completely (as described above with higher log-level)
- or, if you really want, by applying of patch like this:
```diff
				logSys.info(
-					"[%s] Found %s - %s", self.jailName, ip, datetime.datetime.fromtimestamp(unixTime).strftime("%Y-%m-%d %H:%M:%S")
+					"[%s] Found %s", self.jailName, ip
				)
```
Why actually this 10 bytes extra are bothering you so?

**Comment by mmazay** [comment]
Did I understand correctly that I need to make this replacement in the file /usr/lib/python2.6/site-packages/fail2ban/server/filter.py? I found this line only there (I have Centos 6.10).
When I make a replacement, after the restart I get the message " ERROR invalid syntax (filter.py, line 604)"

**Comment by sebres** [comment]
Yes... but if you get this error, it looks like something was done wrong.

And I'll try again: why actually this 10 bytes extra are bothering you so?

**Comment by mmazay** [comment]
> And I'll try again: why actually this 10 bytes extra are bothering you so?

You see... it may not seem important to you. All Windows on my desktop have the traditional size and location, including the window Notepad++ in which I view logs. The old log was placed in my window without line breaks, the new one — does not fit. It makes me a little annoyed. I understand that 99% of users will not pay attention to this :)

**Comment by sebres** [comment]
> The old log was placed in my window without line breaks, the new one — does not fit.

and the horizontal scrollbar simply does not the job (by disabled "word wrap" in Notepad++)?
