### ISSUE TITLE
Using multiple jails without interference

### ISSUE THREAD

**Issue by johnramsden** [fail2ban/fail2ban#2271]
### Environment:

- Fail2Ban version 0.8 and 0.10:
- OS, Ubuntu 14.04
- Fail2Ban installed via PPA for 0.10, and via regular package for 0.8
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration

### The issue:

I'm using multiple jails to have several threshold when banning IP addresses and have noticed some interference where one jail will ban an IP address which should also be banned in a different jail, but is not because fail2ban sees it as already banned. What is the recommended way of avoiding this problem?

For example, I have the jail which bans for 30 seconds, and a jail the bans for an hour. Sometimes they will both be triggered but the 30 second ban will be executed first and the hour-long ban will say "```[<jail>] <ip> already banned```". 

I noticed recently the ban time increment functionality was added https://github.com/fail2ban/fail2ban/pull/1460, this is probably the long-term solution for me, but unfortunately it is not yet in 0.10.

#### Steps to reproduce

Run multiple jails with multiple thresholds.

#### Expected behavior

One jail does not cause another jail to not ban.

#### Any customizations done to /etc/fail2ban/ configuration

Filters:

```nginx-request.local```

```
[Definition]

failregex = ^<HOST> .*
ignoreregex =
```

```jail.local``` (v0.10 version):

```
[DEFAULT]

ignoreip = 127.0.0.1/8 

bantime  = 10m

findtime = 6m
maxretry = 3

backend = auto

#
# ACTIONS
#

# Default banning action
banaction = iptables-ipset-proto6-allports

# Default protocol
protocol = all

# Specify chain where jumps would need to be added in iptables-* actions
chain = ban

#
# Action shortcuts. To be used to define action parameter

action_ipset6_ = %(banaction)s[name=%(__name__)s, protocol="%(protocol)s", bantime="%(bantime)s", chain="%(chain)s"]
action = %(action_ipset6_)s

www_error_logs_ = /var/www/log/error/*error.log
www_access_logs_ = /var/www/log/access/*access.log

[nginx-aggr-00-30]

enabled  = true
filter   = nginx-request
logpath  = %(www_access_logs_)s
maxretry = 10
findtime = 30s
bantime = 2m

[nginx-aggr-5]

enabled  = true
filter   = nginx-request
logpath  = %(www_access_logs_)s
maxretry = 50
findtime = 5m
bantime = 1m

[nginx-aggr-30]

enabled  = true
filter   = nginx-request
logpath  = %(www_access_logs_)s
maxretry = 250
findtime = 30m
bantime = 5m

[nginx-aggr-60]

enabled  = true
filter   = nginx-request
logpath  = %(www_access_logs_)s
maxretry = 400
findtime = 1h
bantime = 1h

[nginx-aggr-120]

enabled  = true
filter   = nginx-request
logpath  = %(www_access_logs_)s
maxretry = 600
findtime = 2h
bantime = 24h

[nginx-aggr-1440]

enabled  = true
filter   = nginx-request
logpath  = %(www_access_logs_)s
maxretry = 750
findtime = 24h
bantime = 6h
```

**Comment by sebres** [comment]
> 30 second ban will be executed first and the hour-long ban will say `[<jail>] <ip> already banned`.

This is not correct, the jails in fail2ban can not overlap, so one can't talk about interference across jails.
The message `[<jail>] <ip> already banned` is triggered only in cases:
- the IP has been already banned in this jail (so you have already `[<jail>] Ban <ip>` message in the fail2ban.log before). This can occur because of the certain latency between the found failure and ban action execution. Normally the latency between last ban and message "already banned" is not so large (up to few seconds). If it is the case, simply ignore this warning.
- or the banning action does not really work (or because of the wrong configuration - e. g. not all ports are protected from banaction), so after ban, the intruder is still able to connect, resp. the current session is not rejected so he can attempt further until connection not closed from nginx. In this case you should check the configuration (ports, etc) or choice another banaction that will real reject/drop the active connection.

**Comment by johnramsden** [comment]
@sebres That makes sense. The IPs _are_ being banned, since the traffic does slow down, and I see them in my ipsets. It must be latency, we buffer our logs, so maybe that's related since fail2ban will get them in batches?

If jails don't overlap, does that mean they will get banned in all jails matching the failed amount?

**Comment by sebres** [comment]
> If jails don't overlap, does that mean they will get banned in all jails matching the failed amount?

Yes, therefore so many jails, that are doing almost "the same", make little sense.
Possibly you would like to try 0.11-version (with ban-time-incr enabled)...

Additionally parsing of access_log directly can be too aggressive (too slow, especially by high-load or if too many failures / DDOS-similar circumstances)... see https://github.com/fail2ban/fail2ban/issues/1962#issuecomment-343856328 for possible pre-filtering / or how to write failures into extra log-file.

Thus closed as resolved.

**Comment by johnramsden** [comment]
Thanks!

**Comment by johnramsden** [comment]
@sebres By the way, when is the expected 0.11 release date?

**Comment by sebres** [comment]
As soon as I find time to implement resp. get close all migration relevant issues (I would like to avoid eventual migration updates in the feature).
The tendency going to end of this year.
