### ISSUE TITLE
apache-fakegooglebot errors

### ISSUE THREAD

**Issue by Blisk** [fail2ban/fail2ban#2293]
### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 0.9.0
- [ ] Fail2Ban installed via OS/distribution mechanisms: Centos 7.6
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
```
Dec  7 11:39:51 localhost fail2ban.action[15274]: ERROR /etc/fail2ban/filter.d/ignorecommands/apache-fakegooglebot 66.249.69.175 -- stdout: ''
Dec  7 11:39:51 localhost fail2ban.action[15274]: ERROR /etc/fail2ban/filter.d/ignorecommands/apache-fakegooglebot 66.249.69.175 -- stderr: 'Traceback (most recent call last):\n  File "/etc/fail2ban/filter.d/ignorecommands/apache-fakegooglebot", line 8, in <module>\n    from fail2ban.server.ipdns import DNSUtils, IPAddr\nImportError: No module named ipdns\n'
Dec  7 11:39:51 localhost fail2ban.action[15274]: ERROR /etc/fail2ban/filter.d/ignorecommands/apache-fakegooglebot 66.249.69.175 -- returned 1
Dec  7 11:39:51 localhost fail2ban.filter[15274]: INFO [apache-fakegooglebot] Found 66.249.69.175
```
#### Steps to reproduce
I have log full of these errors. Python 2.7 is installed
#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
This is a known python-version conflict (that was already fixed in newer versions, since #1508).
As workaround you could change the shebang in `filter.d/ignorecommands/apache-fakegooglebot` to the python version (where fail2ban-modules are really installed), for example like this if the version 2.7 is correct one:
```diff
- #!/usr/bin/env python
+ #!/usr/bin/env python2.7
```
to check it works, you can try this:
```bash
/etc/fail2ban/filter.d/ignorecommands/apache-fakegooglebot 192.2.0.1
```

**Comment by sebres** [comment]
Please, read my comment above attentive.
I don't know which python version is used for fail2ban on your system.
So just try it self:
```bash
$ ls -l /usr/bin/python*
$ python2.7 -c 'from fail2ban.server.ipdns import DNSUtils, IPAddr' && echo OK
ImportError: No module named fail2ban.server.ipdns
...
$ python3.5 -c 'from fail2ban.server.ipdns import DNSUtils, IPAddr' && echo OK
OK
```
some version must work, the you have to enter it as proper shebang (and you can test whether apache-fakegooglebot works from command line as described above).

**Comment by Blisk** [comment]
ls -l /usr/bin/python*
lrwxrwxrwx. 1 root root    7 dec  4 17:40 /usr/bin/python -> python2
lrwxrwxrwx. 1 root root    9 dec  4 17:40 /usr/bin/python2 -> python2.7
-rwxr-xr-x. 1 root root 7216 okt 31 00:46 /usr/bin/python2.7
-rwxr-xr-x. 1 root root 1835 okt 31 00:46 /usr/bin/python2.7-config
-rwxr-xr-x. 1 root root  304 dec 15  2017 /usr/bin/python2.7-futurize
-rwxr-xr-x. 1 root root  308 dec 15  2017 /usr/bin/python2.7-pasteurize
lrwxrwxrwx. 1 root root   16 dec  4 17:40 /usr/bin/python2-config -> python2.7-config
lrwxrwxrwx. 1 root root   14 dec  4 17:40 /usr/bin/python-config -> python2-config


 python2.7 -c 'from fail2ban.server.ipdns import DNSUtils, IPAddr' && echo OK
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named ipdns

 python3.5 -c 'from fail2ban.server.ipdns import DNSUtils, IPAddr' && echo OK
bash: python3.5: command not found...

**Comment by sebres** [comment]
which fail2ban version it exactly is?
where your apache-fakegooglebot-config coming from?
Because if I take a look to [apache-fakegooglebot](https://github.com/fail2ban/fail2ban/blob/0.9/config/filter.d/ignorecommands/apache-fakegooglebot) from 0.9th branch I don't see `ipdns` and `IPAddr` at all.
Looks like it is some mix with 0.10th (with IPv6 support), or it is an issue of maintainer of your packet-distribution...
