### ISSUE TITLE
No lines from Apache's error log in mails

### ISSUE THREAD

**Issue by chtheis** [fail2ban/fail2ban#2299]
_We will be very grateful, if your problem was described as completely as possible,
enclosing excerpts from logs (if possible within DEBUG mode, if no errors evident
within INFO mode), and configuration in particular of effected relevant settings
(e.g., with ` fail2ban-client -d | grep 'affected-jail-name' ` for a particular
jail troubleshooting).
Thank you in advance for the details, because such issues like "It does not work" 
alone could not help to resolve anything!
Thanks! (remove this paragraph and other comments upon reading)_

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): 0.10.4
- OS, including release name/version: FreeBSD 11.2
- [X ] Fail2Ban installed via OS/distribution mechanisms
- [X ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
For some fail2ban jails I use use an action to include the log lines in the mail. This works except for apache-noscript: Apache appends the port to the IP address but the grep command could not deal with it. In action.d/helpers-common.conf I changed _grep_log_args to include an optional port number, as seen in the PR #2298. 
I'm not sure if this is the best way to do it, I'm not a regex-pert ;)
And I don't know if it would work with IPv6, I don't have access to it. But as far as I have seen Apache would write "::1:12345" into the log, just like "127.0.0.1:12345" for IPv4

One remark: I couldn't make a action.d/helper-common.local file work, not even if I copied and edited the entire file. Should the ".local" way work, too, when the file is included as "before" in an action? And if so, should it also possible to change just one variable, in this case, just _grep_logs_args? 

#### Steps to reproduce
See the log line in the PR

#### Expected behavior
The mail should include all lines from that IP address

#### Observed behavior
The mail did not include any lines from the log file.

#### Relevant lines from monitored log files in question:
[Fri Dec 07 06:18:24.826187 2018] [php7:error] [pid 87678] [client 127.0.0.1:12345] script '/usr/local/www/apache24/data/test.php' not found or unable to stat

**Comment by sebres** [comment]
BTW, the error "`.local` configs are ignored by includes" is fixed now (in c1ccabc1f922506a8f01fbe9551762e15f965068).

**Comment by chtheis** [comment]
Am 11.12.2018 um 15:45 schrieb Sergey G. Brester:
> BTW, the error "|.local| configs are ignored by includes" is fixed now 

Thanks!

**Comment by sebres** [comment]
Both of them are fixed now, so let close it.
