### ISSUE TITLE
_grep_logs_arg does not work correctly if hostname header equals malicious IP

### ISSUE THREAD

**Issue by welljsjs** [fail2ban/fail2ban#2305]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): __Fail2Ban v0.10.2__
- OS, including release name/version: __Linux x 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux__
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below if so)

### The issue:
Fail2Ban mails the wrong log lines when a malicious client gets blocked by any __Apache__-Jail. <br>
This problem occurs if any client provides the server's IP in the _hostname_ header (numeric _hostname_) and (for what reason ever) the server's IP gets blocked (f.ex. this can happen if the server is behind a NAT and a client that shares the same local network with the server gets blocked (and therefore has the same public IP)).<br>
Then, Fail2Ban sends (if the action for the jail is configured to do so) an email to the system administrator containing the relevant log lines. As the `_grep_logs_args` variable within `helpers-common.conf` does only look for lines in which the blocked IP occurs at all, it'll send the lines with the client that set the _hostname_ header to the server's IP.

So, in general, if the _hostname_ header (which appears in the Apache Log file) contains an IP that gets blocked later by Fail2Ban, Fail2Ban will send this line with the hostname although it should send the line that contains `"client: xxx.xxx.xxx.xxx"` and not only the IP (for a concrete example, see below).

#### Expected behavior
Fail2Ban shall grep the correct lines of the Apache log. 

#### Observed behavior
_Example:_
The IP yyy.yyy.yyy.yyy gets blocked by Fail2Ban. Fail2Ban sends an email to the sys admin.
It'll search the log files for the blocked IP:
<img width="846" alt="bildschirmfoto 2018-12-18 um 15 31 05" src="https://user-images.githubusercontent.com/25301977/50174150-b64b2100-02f9-11e9-9b97-b421b6fc6ecc.png">
This line contains the IP Fail2Ban is looking for, however, the line has nothing to do with the reason why the IP got blocked. It's pure coincidence that the _hostname_ header contains the blocked IP (more or less). 
This is due to `_grep_logs_arg` doing a very general, basic search for the blocked IP in the log files.

### Configuration, dump and another helpful excerpts
This is the mail which, obviously, is not related to the real blocking reason.
<img width="1181" alt="bildschirmfoto 2018-12-18 um 15 31 54" src="https://user-images.githubusercontent.com/25301977/50174496-a122c200-02fa-11e9-87af-86a17355a83e.png">

**Comment by sebres** [comment]
Shortly: don't use the mail-actions like this, see for example my https://github.com/fail2ban/fail2ban/pull/2298#issuecomment-446235989.

> I don't like actions like this - IMHO parsing of log-files (via grep) to find matched lines containing failures, that is already available in the ticket self as well as within the action (with tags `<matches>` and `<ipmatches>`), looks very strange.
> There are already several mail-actions that are using this tags.

So this is rather an obsolete actions, and if you want to see more precise results in the mail (that contains failure attempts only), use some actions like [sendmail-whois-matches.conf](https://github.com/fail2ban/fail2ban/blob/0.10/config/action.d/sendmail-whois-matches.conf#L32)
