### ISSUE TITLE
fail2ban bans its own IP (when connected to from internet)

### ISSUE THREAD

**Issue by mbDK1** [fail2ban/fail2ban#2311]
So I just installed fail2ban on a ubuntu 18.04 LTS server with apache.

I added the: enabled = true
in the jail.local file under phpmyadmin.

I then entered my site where it the phpadmin was, and tried to make som wrong logins...
correctly it banned my IP adress... (it was from inside the network) so it actually banned its own IP adress...

I then requested a friend to do the same, from his IP... but then I found out, that it still bans its own IP.

I havent done any changes to any files, other than adding the enabled = true line at phpmyadmin.

and I cant figure out why it keeps banning its own IP adress instead of my friends IP adress??

Any ideas?.... I am no expert, so I might a liiiiittle step by step help....

kinds regards...

**Comment by sebres** [comment]
>  if anybody connects from the internet... it bans my outter ip.. 194.239.XXX.XXX

Fail2ban bans the IP-address that was found in log-files (matched with filter) for corresponding jail, thus:
- either you have some transparent proxy (or network router/firewall) filtering original IP-address from network packets)
- or the filters rules are wrong for your network configuration;

See also our [wiki-page](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works) for the subject (the second QA).

**Comment by mbDK1** [comment]
the first one actually makes good sence, which might also explain some issues I couldn't find the reason to on an earlier project...... I might have to buy some new equitment to fix the issue....
