### ISSUE TITLE
monitor sudo, su, local logins, with instant or summary emails

### ISSUE THREAD

**Issue by imthenachoman** [fail2ban/fail2ban#2326]
I was going to use the mailing lists but https://sourceforge.net/projects/fail2ban/support says to post here. Let me know if I should send this to the mailing lists instead.

I have fail2ban installed and running on my Debian system. I am trying to figure out how to do a few things:

- monitor `sudo` -- no ban, instant email whenever there is an attempt, a success, or a failure
- monitor `su` -- no ban, instant email whenever there is an attempt, a success, or a failure
- monitor `local logins` -- no ban, instant email whenever there is an attempt, a success, or a failure
- for all the other jails, either email whenever there is an attempt/success/failure or some kind of daily status report

I know I need to set up jails in `/etc/fail2ban/jails.d/` but I'm not sure what the jail configurations would need to be.

Any help/guidance is greatly appreciated

**Comment by sebres** [comment]
> Let me know if I should send this to the mailing lists instead.

Indeed, this is a developer repository, so normally not the place for howto's etc. 
You could try also stackoverflow or similar instead.

As for monitor sudo etc - yes, you need to configure a jail. For possible example see - [wiki](https://github.com/fail2ban/fail2ban/wiki/How-to-ban-something-other-as-host-(IP-address),-like-user-or-mail,-etc.)
So just to show you the direction - it may look like something similar (put it in your `jail.local`):
```ini
[sudo]
logpath = /usr/var/auth.log
filter =
failregex = ^\s*\S+ sudo: pam_unix\(sudo:session\): session opened for user \S+ by <F-ID><F-USER>\S+</F-USER></F-ID>\(uid=\d+\)$
usedns = raw
action = my-mail-action[name=%(__name__)s, sender="%(sender)s", dest="%(destemail)s"]
maxretry = 1
bantime = 1
enabled = true
```
would search for following entries and generate a mail (by ban and unban in 1 second at once) on each attempt:
```
Jan 28 08:35:17 srv sudo: pam_unix(sudo:session): session opened for user root by user(uid=0)
```
As my-mail-action you can use any mail-action fail2ban already has (see `/etc/fail2ban/action.d/*`), for example `mail` or `sendmail`.

Also note #2304 (which is not yet implemented).

**Comment by imthenachoman** [comment]
Got it. Thank you! And sorry for posting here. I wasn't sure where to go cause the  https://sourceforge.net page said to come here.
