### ISSUE TITLE
Restarting fail2ban rebans IPs with a new bantime

### ISSUE THREAD

**Issue by MatthiasKuehneEllerhold** [fail2ban/fail2ban#2333]
Rebanning IPs after a restart of fail2ban reset the bantime. (See longer explanation below)

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): 0.9.6-2
- OS, including release name/version: Debian GNU/Linux 9.7 (stretch)
- [x] Fail2Ban installed via OS/distribution mechanisms: apt-get install fail2ban
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

Rebanning IPs after a restart of fail2ban reset the bantime.

Say the IP 1.2.3.4 was banned at 12:30 for 10 minutes. This mean the IP can access the blocked port again at 12:40.
If I restart fail2ban (or the machine) at 12:35 fail2ban will re-ban the IP as soon as it start again (if dbfile and dbpurgeage is set). The problem is this ban will be again for 10 minutes making the end-time to 12:45. Which totals the bantime to 15 minutes.

This example may not be "that much of a problem" but imagine higher bantimes like half a year. If you restart your servers regularly (e. g. to apply kernel updates) an IP may be banned permanently.

#### Steps to reproduce

* Have a jail thats banning you for 10 minutes
* Get yourself banned (e. g. at 12:30)
* Restart fail2ban in between (e. g. at 12:35)

#### Expected behavior

The ban should be lifted at 12:40.

#### Observed behavior

The ban will be lifted at 12:45.

#### Any additional information

Tested with this configuration for the "sshd" jail (content of jail.local):
```
[sshd]
enabled = true
# Ban this IP for 10 minutes if it triggered more than 20 auth errors in a minute
bantime  = 600
findtime = 60
maxretry = 20
```

**Comment by sebres** [comment]
Same answer as the question lately in https://github.com/fail2ban/fail2ban/pull/480#issuecomment-458973944

Shortly, it is already fixed in major releases long time ago, 0.9.6 is too old (and the development for 0.9th is discontinued).
Please update to 0.10.

**Comment by MatthiasKuehneEllerhold** [comment]
Thank you for your information and sorry for this duplicate issue. Didnt find the one you mentioned. 

Upgrading to 0.10.2-2~bpo9+1 via stretch-backports fixed this issue! Nice!

**Comment by sebres** [comment]
> Thank you for your information and sorry for this duplicate issue. Didnt find the one you mentioned.

You are welcome and no problems. Myself has also often troubles to find some issue/comment here.
