### ISSUE TITLE
setting failregex for phpmyadmin?

### ISSUE THREAD

**Issue by murdocklawless** [fail2ban/fail2ban#2335]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.10.2
- OS, including release name/version: ubuntu 18.04 LTS
- [x] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

I want to use fail2ban for phpmyadmin logins but I couldn't figured it out how I could make right failregex expression for apache2 access.log file.

here is an example for my apache2 access.log file;

155.158.210.51 - - [07/Feb/2019:21:17:12 +0300] "GET /phpmyadmin/index.php?lang=en&pma_username=root&pma_password=monkey HTTP/1.1" 200 12599 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"

I've tried;

failregex = ^.+?:\d+ <HOST> -.*"(GET|POST|HEAD) /phpmyadmin/index.php.*$

but this won't work.

how can set right failregex expression for access.log file?

**Comment by murdocklawless** [comment]
this worked.

failregex = ^<HOST> -.*"(GET|POST).*/phpmyadmin/index\.php

**Comment by sebres** [comment]
Please don't do that - this regex may work but is vulnerable (due to both catch-all's `.*`). 
See https://github.com/fail2ban/fail2ban/issues/2332#issuecomment-460985248 and below for more info why and how it is affected.

**Comment by murdocklawless** [comment]
thank you for your comment.

you offer expression below in #2332 (comment) for http 40x errors.

failregex = ^<HOST>\s+\S+\s+\S+\s+(?:\[\])?\s*"(?:GET|POST|HEAD)\s\S+\s[A-Z]+/\d+.\d+" 40\d
# _ignore_uri = favicon\.ico|robot\.txt
_ignore_uri = favicon\.ico
ignoreregex = ^<HOST>\s+\S+\s+\S+\s+(?:\[\])?\s*"[A-Z]+\s\S*/(?:%(_ignore_url)s)\s[A-Z]+/\d+.\d+"

as I understood this failregex expression catches all 40x errors, am I right?

could you please tell us what are these **\s+\S+\s+\S+\s+(?:\[\])?\s** meaing for understanding expressions better?

**Comment by sebres** [comment]
Yes, `40\d` means 400..409...

> could you please tell us what are these ... are meaning for understanding expressions better?

I could (e. g. `\s+` means  non-zero number of spaces, `\S+` - non-zero number of NOT spaces, so until next space coming), but better you read about it [here](https://docs.python.org/2/library/re.html#regular-expression-syntax). 
The point is to don't use catch-all (`.*`), so the following regex-parts are to find only at the place where it is really expected and it would stop to search for the rest, if it is not matches from start to expected position. A dual catch-all (`.*`) as you has it initially is still worse, so would quasi cause the loss of the anchoring (`^`) as well as search for your `GET|POST` or `/phpmyadmin/index\.php` **everywhere** in hope this would fit, no matter how long the string is (and whether it is user/foreign input or not, etc).
