### ISSUE TITLE
Fail2ban PLUS ConfigServer Security & Firewall (CSF)

### ISSUE THREAD

**Issue by TomasHurtz** [fail2ban/fail2ban#2340]
Basic question - can't find any FAQ that answers this;

Is Fail2ban compatible with CSF in an apache / linux environment?

If so, what are the installation steps (to avoid any issues)

If not - please offer brief explanation why?

Thanks

**Comment by sebres** [comment]
If I correct understand, here is a pull request #1351 which action could be used in your configuration.
I use neither apache nor CSF, so I cannot say it is basically working.

The steps to "install":
1. copy `csf.conf` to your `/etc/fail2ban/action.d/`
Here is it from PR - [csf.conf](https://github.com/fail2ban/fail2ban/blob/38d3f01a511d168328e310f8c441698969ec1d5f/config/action.d/csf.conf) (*click to raw-button to get URL for download file*)
2. set banaction to csf in your `jail.local` for jails you want,for example:
```ini
[some-apache-jail]
enabled = true
...
banaction = csf
```
3. reload fail2ban.

That's it. As for "to avoid any issues", I cannot tell you something about (perhaps the author @tjikkun), or just try it yourself.
