### ISSUE TITLE
Help with new 'banaction' for nginx

### ISSUE THREAD

**Issue by acs-ferreira** [fail2ban/fail2ban#2342]
I would like to implement something like using a `/etc/nginx/hosts-deny.conf` file for nginx placed in the `http {}` context to block IP addresses reported by `fail2ban`.

So for each `actionban` a new line would be added to that file and an `actionunban` would remove the corresponding line.

Line format _(to be added or removed)_:
`deny 1.2.3.4;`

I believe that the `nginx-block-map` action could be adapted to this as all the logic remains the same _(specially the part of reloading the web-server each time a line is added/removed)_ so only the actions would be updated.

https://github.com/fail2ban/fail2ban/blob/0.10/config/action.d/nginx-block-map.conf

Thanks for any help provided.

**Comment by sebres** [comment]
Why then adapting at all?

Firstly I don't think a deny-list is really suitable for lot of IPs (allow/deny is a simple blacklisting and only "fast" in network/mask black- resp. white-listing), where map is a hash table (thus very fast).
Also note if you will use allow/deny somewhere in nested locations, the local values could win over your fail2ban-black list.

So why not something like this:
```nginx
map $remote_addr $blck_ip { include blacklisted-sessions.map; }
if ($blck_ip) {
  error_log /dev/null;
  access_log  off;
  # try_files "" @f2b-banned;
  deny all;
}
```
So just use this action as is and simply jump to the location which will deny (or rewrite to "You are banned" static page or something else).

And yes, I know that `if` is "evil" in nginx (but it is not always so and anyway not here) - in this case it acts similar to a location (and you should anyway disable logging, if your nginx also initiate a failures via log, to avoid multiple triggering etc).

This way you can implement also several maps (or even more complex - with decision per location, etc):
```nginx
map $cookie_session_id $blck_ses_ip { include blacklisted-sessions.map; }
map $cookie_token_id $blck_tok_ip   { include blacklisted-tokens.map; }
location /secure {
  # deny if IP, session or token is banned:
  if ($blck_ip$blck_ses_ip$blck_tok_ip) { deny all; ... }
}
location /sessions/ {
  if ($blck_ses_ip) { deny all; ... }
}
location /tokens/ {
  if ($blck_tok_ip) { deny all; ... }
}
```

**Comment by acs-ferreira** [comment]
Thanks for the advice, i'll go forward with that.
