### ISSUE TITLE
Does [recidive] filter work with Cloudflare action only?

### ISSUE THREAD

**Issue by acs-ferreira** [fail2ban/fail2ban#2345]
All my jails are blocked using Cloudflare _(this is the only option when proxing websites trough Cloudflare, as blocking IPs with another method like `iptables` is useless, otherwise we should block Cloudflare IPs...)_.

So, does `[recidive]` work on this case or is it useless with Cloudflare action?

More precisely, when a `[recidive]` IP is found, does the `actionunban` take in account the jail `bantime` or the `[recidive]` `bantime` when it decides to unban an IP?

**Take this case:**

```
fail2ban.filter         [1478]: INFO    [jail] Found 91.196.99.174
fail2ban.actions        [1478]: NOTICE  [jail] Ban 91.196.99.174
fail2ban.filter         [1478]: INFO    [recidive] Found 91.196.99.174
```

For this to work correctly, it should IMO:

1. Check if the `banaction` is the same (`===`) for both `[jail]` and `[recidive]`
2. If yes, increase the `bantime` to match the `[recidive]` `bantime` and not the common `[jail]` `bantime` _(normally, a lot more permissive/less long)_
3. If not the same `banaction`, apply a new rule trough the `[recidive]` `banaction`.

Asking this because the `[recidive]` filter specify that we should use a separate blocking method when using it.

https://github.com/fail2ban/fail2ban/blob/1647d0090ebdbc152d064cdff99a028365c015b2/config/filter.d/recidive.conf#L10-L14

Thanks.

**Comment by sebres** [comment]
> *this is the only option when proxing websites trough Cloudflare, as blocking IPs with another method like `iptables` is useless, otherwise we should block Cloudflare IPs...*

Well this is false.
Cloudflare, if it is correctly configured, functioned as a reverse proxy, so I expect the `X-Forwarded-For` or even `CF-Connecting-IP` headers with correct real IP of the user.
Thus what you need is the the action (similar `nginx-block-map`) which could reject banned IP's requests considering this headers (e. g. in nginx they would be related to `$http_x_forwarded_for` or `$http_cf_connecting_ip` variables).

> So, does `[recidive]` work on this case or is it useless with Cloudflare action?

I have no idea about Cloudflare blocking system.

But Fail2ban self does not differentiate resp. consider ban/unban across several jails. This means if Cloudflare does not have any "anchor" to identify different jails (`<name>` or `<actname>` tags) or some  counter per IP, then the earlier unban of `jail` would cause a total unban and `recidive` become totally uninteresting this way.

Here is a similar issue with another action (without anchoring) - #2031

**Comment by sebres** [comment]
Also note that `recidive` is an atavism (scanning own logs to find info what is already there, is ugly) and we have no plans to extend fail2ban to provide some mechanisms considering all ban-times across jails.

The incremental prolongation of ban-time was introduced for this purposes in 0.11 (`bantime.increment = true`). So I'd suggest - try this version instead.
