### ISSUE TITLE
Feature Request: Multiple Ban-Stages per Rule

### ISSUE THREAD

**Issue by beli42** [fail2ban/fail2ban#2346]
It would be nice to have staged ban ratings for each rule.

Like this

STAGE 1
{
   service abc
   ip i
   connects: 3
   time :60 seconds
   ban
      {
         services: abc
         ip: i
         netmask: 255.255.255.255
}

STAGE 2
{
   service abc
   ip i
   STAGE 1: 2 matches
   time: 1000 seconds
   ban
      {
         services: abc, xyz, ... (all)
         ip: i
         netmask: 255.255.255.0
}

Stage 2 is configured the same but extends the block time and/or the blocked services.
So if an ip is banned and tries to connect again: push it in the rating for STAGE 2. And if the hammering goes on: fire the rules of STAGE2.

This way it would reduce filling the logfiles with short ban periods and lock out evil source ips for a longer time range and maybe for more services running on the local machine.

**Comment by sebres** [comment]
This feature is already implemented (called progressive or incremental banning) and usable since version 0.11.

Take a look for:
https://github.com/fail2ban/fail2ban/blob/1647d0090ebdbc152d064cdff99a028365c015b2/config/jail.conf#L47-L81

**Comment by sebres** [comment]
Oh, as for this one:
> maybe for more services running on the local machine.

Since the incremental banning, many other tags like `<bantime>`, `<bancount>`, etc are available in actions. So one could extend the actions with something like:
```ini
actionban = %(known/actionban)s
            if [ <bancount> -gt 1 ]
            then
               do_something_additionally_for_intruder <ip>;
            elif [ <bancount> -gt 5 ]
            then
               send_abuse <ip> <bancount> ...;
            fi
```

**Comment by beli42** [comment]
really nice. thanks a lot!
