### ISSUE TITLE
Email Failing to Send

### ISSUE THREAD

**Issue by dutchvanderlinde** [fail2ban/fail2ban#2358]
### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: Ubuntu 18.04.1 LTS
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

_Summary here_

Essentially, it appears that the it keeps failing on sending the email to me when it bans someone. Relevant log files are below.

#### Relevant parts of /var/log/fail2ban.log file:
```2019-02-25 01:57:19,486 fail2ban.utils          [9707]: ERROR   7fd9b81f7490 -- exec: ( printf %b "Subject: [Fail2Ban] sshd: banned 61.184.247.8 from edu-libraryofcode
Date: `LC_ALL=C date +"%a, %d %h %Y %T %z"`
From: Fail2Ban <root@linux.edu.libraryofcode.us>
To: matthew_ray@myemail.com\n
Hi,\n
The IP 61.184.247.8 has just been banned by Fail2Ban after
5 attempts against sshd.\n\n
Here is more information about 61.184.247.8 :\n
`/usr/bin/whois 61.184.247.8 || echo missing whois program`\n\n
Lines containing failures of 61.184.247.8\n";
logpath="/var/log/auth.log"; grep -m 1000 -E "(^|[^0-9a-fA-F:])$(echo '61.184.247.8' | sed 's/\./\\./g')([^0-9a-fA-F:]|$)" $logpath | tail -n 1000;
printf %b "\n
Regards,\n
Fail2Ban" ) | /usr/sbin/sendmail -f root@linux.edu.libraryofcode.us matthew_ray@myemail.com
2019-02-25 01:57:19,487 fail2ban.utils          [9707]: ERROR   7fd9b81f7490 -- timed out after 60 seconds.
```

**Comment by sebres** [comment]
What does happen if you try this via command line (direct from shell)? 
Your excerpt is too short, you should find the open parenthesis where the command is started. It looks like `( printf %%b "Subject:`...

In the moment it looks like a 3rd party issue to me:
- either sendmail gets a timeout by send;
- or whois reach a timeout by retrieve IP info;
- or your `auth.log` is extremely large (not rotated?), so the grep takes too long time.

You can avoid the latter using another action which does not search failures of IP in log-file (the failures are already known in fail2ban and could be retrieved using tags `<matches>`), e. g. `sendmail-whois-matches`. Just in case of 2 first reasons, it'll not help. Increase timeout is an another option, just it is not good at all if the actions take very long time (banning of another IPs will be affected with it).

**Comment by dutchvanderlinde** [comment]
Oops, sorry yes. Here it is: 
```exec: ( printf %b "Subject: [Fail2Ban] sshd: banned 177.140.44.113 from edu-libraryofcode
Date: `LC_ALL=C date +"%a, %d %h %Y %T %z"`
From: Fail2Ban <root@linux.edu.libraryofcode.us>
To: matthew_ray@corporate.tssservicecollc.com\n
Hi,\n
The IP 177.140.44.113 has just been banned by Fail2Ban after
5 attempts against sshd.\n\n
Here is more information about 177.140.44.113 :\n
`/usr/bin/whois 177.140.44.113 || echo missing whois program`\n\n
Lines containing failures of 177.140.44.113\n";
logpath="/var/log/auth.log"; grep -m 1000 -E "(^|[^0-9a-fA-F:])$(echo '177.140.44.113' | sed 's/\./\\./g')([^0-9a-fA-F:]|$)" $logpath | tail -n 1000;
printf %b "\n
Regards,\n
Fail2Ban" ) | /usr/sbin/sendmail -f root@linux.edu.libraryofcode.us matthew_ray@corporate.tssservicecollc.com
2019-02-25 18:46:25,674 fail2ban.utils          [1342]: ERROR   7f64741f7d80 -- timed out after 60 seconds.
2019-02-25 18:46:25,875 fail2ban.utils          [1342]: ERROR   ( printf %b "Subject: [Fail2Ban] sshd: banned 177.140.44.113 from edu-libraryofcode
```
Also what do you mean trying it from the command line?

The `auth.log` file is rather large but not too large.

**Comment by sebres** [comment]
No, above the line `Date: ...` you'd find still the line containing `( printf %b "Subject: ...`
Then you should try to call it from command-line shell (root or user fail2ban running under). something like:
```bash
$ ( printf %b "Subject: ... 
Date: `LC_ALL=C date +"%a, %d %h %Y %T %z"`
From: Fail2Ban ...
...
Regards,\n
Fail2Ban" ) | /usr/sbin/sendmail -f ...
```
And show how long it works.
If it is too long also, you could try to find what it is exactly, e. g. test separately try both others sub-commands:
```
$ /usr/bin/whois 177.140.44.113 || echo missing whois program
```
and
```
$ logpath="/var/log/auth.log"; grep -m 1000 -E "(^|[^0-9a-fA-F:])$(echo '177.140.44.113' | sed 's/\./\\./g')([^0-9a-fA-F:]|$)" $logpath | tail -n 1000;
````
If both are fast enough, your sendmail seems to be a malefactor.
