### ISSUE TITLE
Failing to send complain notices

### ISSUE THREAD

**Issue by acosonic** [fail2ban/fail2ban#2360]
### Environment:
Ubuntu server 16.04
Fail2ban 0.11.0.dev0

### The issue:

tried to configure fail2ban to send complain to IP owner in sshd rule by adding 
complain[logpath=/var/log/auth.log]
didn't work, tried replacing action with 
xarf-login-attack
also didn't work, I am only getting emails to my localhost

#### Steps to reproduce
set in jail.conf 
action = %(action_xarf)s

#### Expected behavior
send email to IP owner

#### Observed behavior
sends only emails from root@hostname to root@localhost

#### Any additional information
I am monitoring tail -f /var/log/mail.log and ripe abuse email (on which I was getting fail2ban notices from other hosts, when my servers were infected and attacking others...)

### Configuration, dump and another helpful excerpts
fail2ban-client -d | grep 'sshd'
['add', 'sshd', 'auto']
['set', 'sshd', 'maxlines', 1]
['set', 'sshd', 'prefregex', '^<F-MLFID>(?:\\[\\])?\\s*(?:<[^.]+\\.[^.]+>\\s+)?(?:\\S+\\s+)?(?:kernel: \\[ *\\d+\\.\\d+\\]\\s+)?(?:@vserver_\\S+\\s+)?(?:(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)\\s+)?(?:\\[ID \\d+ \\S+\\]\\s+)?</F-MLFID>(?:(?:error|fatal): (?:PAM: )?)?<F-CONTENT>.+</F-CONTENT>$']
['multi-set', 'sshd', 'addfailregex', ['^[aA]uthentication (?:failure|error|failed) for <F-USER>.*</F-USER> from <HOST>( via \\S+)?\\s*(?: \\[preauth\\])?\\s*$', '^User not known to the underlying authentication module for <F-USER>.*</F-USER> from <HOST>\\s*(?: \\[preauth\\])?\\s*$', '^Failed \\S+ for (?P<cond_inv>invalid user )?<F-USER>(?P<cond_user>\\S+)|(?(cond_inv)(?:(?! from ).)*?|[^:]+)</F-USER> from <HOST>(?: port \\d+)?(?: on \\S+(?: port \\d+)?)?(?: ssh\\d*)?(?(cond_user): |(?:(?:(?! from ).)*)$)', '^<F-USER>ROOT</F-USER> LOGIN REFUSED.* FROM <HOST>\\s*(?: \\[preauth\\])?\\s*$', '^[iI](?:llegal|nvalid) user <F-USER>.*?</F-USER> from <HOST>(?: port \\d+)?(?: on \\S+(?: port \\d+)?)?\\s*$', '^User <F-USER>.+</F-USER> from <HOST> not allowed because not listed in AllowUsers\\s*(?: \\[preauth\\])?\\s*$', '^User <F-USER>.+</F-USER> from <HOST> not allowed because listed in DenyUsers\\s*(?: \\[preauth\\])?\\s*$', '^User <F-USER>.+</F-USER> from <HOST> not allowed because not in any group\\s*(?: \\[preauth\\])?\\s*$', '^refused connect from \\S+ \\(<HOST>\\)\\s*(?: \\[preauth\\])?\\s*$', '^Received <F-MLFFORGET>disconnect</F-MLFFORGET> from <HOST>(?: port \\d+)?(?: on \\S+(?: port \\d+)?)?:\\s*3: .*: Auth fail(?: \\[preauth\\])?\\s*$', '^User <F-USER>.+</F-USER> from <HOST> not allowed because a group is listed in DenyGroups\\s*(?: \\[preauth\\])?\\s*$', "^User <F-USER>.+</F-USER> from <HOST> not allowed because none of user's groups are listed in AllowGroups\\s*(?: \\[preauth\\])?\\s*$", '^pam_unix\\(sshd:auth\\):\\s+authentication failure;\\s*logname=\\S*\\s*uid=\\d*\\s*euid=\\d*\\s*tty=\\S*\\s*ruser=<F-USER>\\S*</F-USER>\\s*rhost=<HOST>\\s.*(?: \\[preauth\\])?\\s*$', '^(error: )?maximum authentication attempts exceeded for <F-USER>.*</F-USER> from <HOST>(?: port \\d+)?(?: on \\S+(?: port \\d+)?)?(?: ssh\\d*)?(?: \\[preauth\\])?\\s*$', '^User <F-USER>.+</F-USER> not allowed because account is locked(?: \\[preauth\\])?\\s*', '^<F-MLFFORGET>Disconnecting</F-MLFFORGET>: Too many authentication failures(?: for <F-USER>.+?</F-USER>)?(?: \\[preauth\\])?\\s*', '^<F-NOFAIL>Received <F-MLFFORGET>disconnect</F-MLFFORGET></F-NOFAIL> from <HOST>: 11:', '^<F-NOFAIL>Connection <F-MLFFORGET>closed</F-MLFFORGET></F-NOFAIL> by <HOST>(?: \\[preauth\\])?\\s*$', '^<F-NOFAIL>Connection from</F-NOFAIL> <HOST>']]
['set', 'sshd', 'datepattern', '{^LN-BEG}']
['set', 'sshd', 'addjournalmatch', '_SYSTEMD_UNIT=sshd.service', '+', '_COMM=sshd']
['set', 'sshd', 'usedns', 'warn']
['set', 'sshd', 'addlogpath', '/var/log/auth.log', 'head']
['set', 'sshd', 'maxretry', 2]
['set', 'sshd', 'logencoding', 'auto']
['set', 'sshd', 'bantime', '86400']
['set', 'sshd', 'ignorecommand', '']
['set', 'sshd', 'findtime', '43200']
['set', 'sshd', 'addaction', 'iptables-multiport']
['multi-set', 'sshd', 'action', 'iptables-multiport', [['actionunban', '<iptables> -D f2b-sshd -s <ip> -j <blocktype>'], ['actionflush', '<iptables> -F f2b-sshd'], ['actionstop', '<iptables> -D INPUT -p tcp -m multiport --dports ssh -j f2b-sshd\n<iptables> -F f2b-sshd\n<iptables> -X f2b-sshd'], ['actionstart', '<iptables> -N f2b-sshd\n<iptables> -A f2b-sshd -j RETURN\n<iptables> -I INPUT -p tcp -m multiport --dports ssh -j f2b-sshd'], ['actionban', '<iptables> -I f2b-sshd 1 -s <ip> -j <blocktype>'], ['actioncheck', "<iptables> -n -L INPUT | grep -q 'f2b-sshd[ \\t]'"], ['iptables', 'iptables <lockingopt>'], ['lockingopt', '-w'], ['known/lockingopt', '-w'], ['blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unreachable'], ['protocol', 'tcp'], ['name', 'sshd'], ['chain', 'INPUT'], ['known/blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unreachable'], ['known/protocol', 'tcp'], ['known/port', 'ssh'], ['known/returntype', 'RETURN'], ['known/iptables', 'iptables <lockingopt>'], ['known/chain', 'INPUT'], ['returntype', 'RETURN'], ['known/name', 'default'], ['known/blocktype', 'REJECT --reject-with icmp-port-unreachable'], ['iptables?family=inet6', 'ip6tables <lockingopt>'], ['known/iptables?family=inet6', 'ip6tables <lockingopt>'], ['blocktype', 'REJECT --reject-with icmp-port-unreachable'], ['actname', 'iptables-multiport'], ['port', 'ssh']]]
['set', 'sshd', 'addaction', 'xarf-login-attack']
['multi-set', 'sshd', 'action', 'xarf-login-attack', [['actionunban', ''], ['actionstop', ''], ['actionstart', ''], ['actioncheck', ''], ['norestored', True], ['actionban', 'oifs=${IFS}; IFS=.;SEP_IP=( <ip> ); set -- ${SEP_IP}; ADDRESSES=$(dig +short -t txt -q $4.$3.$2.$1.abuse-contacts.abusix.org); IFS=${oifs}\nIP=<ip>\nFROM=root@<fq-hostname>\nSERVICE=sshd\nFAILURES=<failures>\nREPORTID=<time>@<fq-hostname>\nTLP=green\nPORT=ssh\nDATE=`LC_ALL=C date --date=@<time> +"%a, %d %h %Y %T %z"`\nif [ ! -z "$ADDRESSES" ]; then\n(printf -- %b "Subject: abuse report about $IP - $DATE\\nAuto-Submitted: auto-generated\\nX-XARF: PLAIN\\nContent-Transfer-Encoding: 7bit\\nContent-Type: multipart/mixed; charset=utf8;\\n  boundary=Abuse-bfbb0f920793ac03cb8634bde14d8a1e;\\n\\n--Abuse-bfbb0f920793ac03cb8634bde14d8a1e\\nMIME-Version: 1.0\\nContent-Transfer-Encoding: 7bit\\nContent-Type: text/plain; charset=utf-8;\\n\\nDear Sir/Madam,\\n\\nWe have detected abuse from the IP address $IP, which according to abusix.com is on your network. We would appreciate if you would investigate and take action as appropriate.\\n\\nLog lines are given below, but please ask if you require any further information.\\n\\n(If you are not the correct person to contact about this please accept our apologies - your e-mail address was extracted from the whois record by an automated process.)\\n\\n This mail was generated by Fail2Ban in a X-ARF format! You can find more information about x-arf at http://www.x-arf.org/specification.html.\\n\\nThe recipient address of this report was provided by the Abuse Contact DB by abusix.com. abusix.com does not maintain the content of the database. All information which we pass out, derives from the RIR databases and is processed for ease of use. If you want to change or report non working abuse contacts please contact the appropriate RIR. If you have any further question, contact abusix.com directly via email (info@abusix.com). Information about the Abuse Contact Database can be found here: https://abusix.com/global-reporting/abuse-contact-db\\nabusix.com is neither responsible nor liable for the content or accuracy of this message.\\n\\n--Abuse-bfbb0f920793ac03cb8634bde14d8a1e\\nMIME-Version: 1.0\\nContent-Transfer-Encoding: 7bit\\nContent-Type: text/plain; charset=utf-8; name=\\"report.txt\\";\\n\\n---\\nReported-From: $FROM\\nCategory: abuse\\nReport-ID: $REPORTID\\nReport-Type: login-attack\\nService: $SERVICE\\nVersion: 0.2\\nUser-Agent: Fail2ban v0.9\\nDate: $DATE\\nSource-Type: ip-address\\nSource: $IP\\nPort: $PORT\\nSchema-URL: http://www.x-arf.org/schema/abuse_login-attack_0.1.2.json\\nAttachment: text/plain\\nOccurances: $FAILURES\\nTLP: $TLP\\n\\n\\n--Abuse-bfbb0f920793ac03cb8634bde14d8a1e\\nMIME-Version: 1.0\\nContent-Transfer-Encoding: 7bit\\nContent-Type: text/plain; charset=utf8; name=\\"logfile.log\\";\\n\\n";\ndate \'+Note: Local timezone is %z (%Z)\';\nprintf -- %b "\\n<ipmatches>\\n\\n\\n\\n--Abuse-bfbb0f920793ac03cb8634bde14d8a1e--") | /usr/sbin/sendmail -f root@<fq-hostname> ${ADDRESSES//,/\\" \\"}\nfi'], ['known/mailargs', '-f <sender>'], ['header', 'Subject: abuse report about $IP - $DATE\\nAuto-Submitted: auto-generated\\nX-XARF: PLAIN\\nContent-Transfer-Encoding: 7bit\\nContent-Type: multipart/mixed; charset=utf8;\\n  boundary=Abuse-bfbb0f920793ac03cb8634bde14d8a1e;\\n\\n--Abuse-bfbb0f920793ac03cb8634bde14d8a1e\\nMIME-Version: 1.0\\nContent-Transfer-Encoding: 7bit\\nContent-Type: text/plain; charset=utf-8;\\n'], ['known/mailcmd', '/usr/sbin/sendmail'], ['known/header', 'Subject: abuse report about $IP - $DATE\\nAuto-Submitted: auto-generated\\nX-XARF: PLAIN\\nContent-Transfer-Encoding: 7bit\\nContent-Type: multipart/mixed; charset=utf8;\\n  boundary=Abuse-bfbb0f920793ac03cb8634bde14d8a1e;\\n\\n--Abuse-bfbb0f920793ac03cb8634bde14d8a1e\\nMIME-Version: 1.0\\nContent-Transfer-Encoding: 7bit\\nContent-Type: text/plain; charset=utf-8;\\n'], ['known/loglines', '9000'], ['message', 'Dear Sir/Madam,\\n\\nWe have detected abuse from the IP address $IP, which according to abusix.com is on your network. We would appreciate if you would investigate and take action as appropriate.\\n\\nLog lines are given below, but please ask if you require any further information.\\n\\n(If you are not the correct person to contact about this please accept our apologies - your e-mail address was extracted from the whois record by an automated process.)\\n\\n This mail was generated by Fail2Ban in a X-ARF format! You can find more information about x-arf at http://www.x-arf.org/specification.html.\\n\\nThe recipient address of this report was provided by the Abuse Contact DB by abusix.com. abusix.com does not maintain the content of the database. All information which we pass out, derives from the RIR databases and is processed for ease of use. If you want to change or report non working abuse contacts please contact the appropriate RIR. If you have any further question, contact abusix.com directly via email (info@abusix.com). Information about the Abuse Contact Database can be found here: https://abusix.com/global-reporting/abuse-contact-db\\nabusix.com is neither responsible nor liable for the content or accuracy of this message.\\n'], ['port', 'ssh'], ['service', 'sshd'], ['known/sender', 'fail2ban@<fq-hostname>'], ['known/report', '--Abuse-bfbb0f920793ac03cb8634bde14d8a1e\\nMIME-Version: 1.0\\nContent-Transfer-Encoding: 7bit\\nContent-Type: text/plain; charset=utf-8; name=\\"report.txt\\";\\n\\n---\\nReported-From: $FROM\\nCategory: abuse\\nReport-ID: $REPORTID\\nReport-Type: login-attack\\nService: $SERVICE\\nVersion: 0.2\\nUser-Agent: Fail2ban v0.9\\nDate: $DATE\\nSource-Type: ip-address\\nSource: $IP\\nPort: $PORT\\nSchema-URL: http://www.x-arf.org/schema/abuse_login-attack_0.1.2.json\\nAttachment: text/plain\\nOccurances: $FAILURES\\nTLP: $TLP\\n\\n\\n--Abuse-bfbb0f920793ac03cb8634bde14d8a1e\\nMIME-Version: 1.0\\nContent-Transfer-Encoding: 7bit\\nContent-Type: text/plain; charset=utf8; name=\\"logfile.log\\";'], ['logpath', '/var/log/auth.log'], ['known/service', 'unspecified'], ['actname', 'xarf-login-attack'], ['known/logpath', '/dev/null'], ['mailcmd', '/usr/sbin/sendmail'], ['known/tlp', 'green'], ['report', '--Abuse-bfbb0f920793ac03cb8634bde14d8a1e\\nMIME-Version: 1.0\\nContent-Transfer-Encoding: 7bit\\nContent-Type: text/plain; charset=utf-8; name=\\"report.txt\\";\\n\\n---\\nReported-From: $FROM\\nCategory: abuse\\nReport-ID: $REPORTID\\nReport-Type: login-attack\\nService: $SERVICE\\nVersion: 0.2\\nUser-Agent: Fail2ban v0.9\\nDate: $DATE\\nSource-Type: ip-address\\nSource: $IP\\nPort: $PORT\\nSchema-URL: http://www.x-arf.org/schema/abuse_login-attack_0.1.2.json\\nAttachment: text/plain\\nOccurances: $FAILURES\\nTLP: $TLP\\n\\n\\n--Abuse-bfbb0f920793ac03cb8634bde14d8a1e\\nMIME-Version: 1.0\\nContent-Transfer-Encoding: 7bit\\nContent-Type: text/plain; charset=utf8; name=\\"logfile.log\\";'], ['mailargs', '-f <sender>'], ['sender', 'root@<fq-hostname>'], ['tlp', 'green'], ['name', 'sshd'], ['footer', '\\n\\n--Abuse-bfbb0f920793ac03cb8634bde14d8a1e--'], ['known/port', '0'], ['known/footer', '\\n\\n--Abuse-bfbb0f920793ac03cb8634bde14d8a1e--'], ['known/message', 'Dear Sir/Madam,\\n\\nWe have detected abuse from the IP address $IP, which according to abusix.com is on your network. We would appreciate if you would investigate and take action as appropriate.\\n\\nLog lines are given below, but please ask if you require any further information.\\n\\n(If you are not the correct person to contact about this please accept our apologies - your e-mail address was extracted from the whois record by an automated process.)\\n\\n This mail was generated by Fail2Ban in a X-ARF format! You can find more information about x-arf at http://www.x-arf.org/specification.html.\\n\\nThe recipient address of this report was provided by the Abuse Contact DB by abusix.com. abusix.com does not maintain the content of the database. All information which we pass out, derives from the RIR databases and is processed for ease of use. If you want to change or report non working abuse contacts please contact the appropriate RIR. If you have any further question, contact abusix.com directly via email (info@abusix.com). Information about the Abuse Contact Database can be found here: https://abusix.com/global-reporting/abuse-contact-db\\nabusix.com is neither responsible nor liable for the content or accuracy of this message.\\n'], ['loglines', '9000']]]
['start', 'sshd']

#### Any customizations done to /etc/fail2ban/ configuration
```
in jail.conf
action = %(action_xarf)s

```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:
Feb 26 09:12:41 host2 postfix/qmgr[2284]: 4230D2700DB: from=<root@host2.myhost.com>, size=466, nrcpt=1 (queue active)
Feb 26 09:12:41 host2 postfix/local[99811]: 0B52E2700D6: to=<root@localhost>, relay=local, delay=0.34, delays=0.05/0/0/0.29, dsn=2.0.0, status=sent (delivered to command: /usr/bin/procmail-wrapper -o -a $DOMAIN -d $LOGNAME)
Feb 26 09:12:41 host2 postfix/qmgr[2284]: 0B52E2700D6: removed
Feb 26 09:12:41 host2 postfix/pickup[95648]: 604EF2700D6: uid=0 from=<root@host2.myhost.com>
Feb 26 09:12:41 host2 postfix/cleanup[99789]: 604EF2700D6: message-id=<20190226081241.604EF2700D6@host2.myhost.com>
Feb 26 09:12:41 host2 postfix/qmgr[2284]: 604EF2700D6: from=<root@host2.myhost.com>, size=466, nrcpt=1 (queue active)
Feb 26 09:12:41 host2 postfix/local[100696]: 4230D2700DB: to=<root@localhost>, relay=local, delay=0.37, delays=0.05/0/0/0.32, dsn=2.0.0, status=sent (delivered to command: /usr/bin/procmail-wrapper -o -a $DOMAIN -d $LOGNAME)
Feb 26 09:12:41 host2 postfix/qmgr[2284]: 4230D2700DB: removed
Feb 26 09:12:41 host2 postfix/local[99811]: 604EF2700D6: to=<root@localhost>, relay=local, delay=0.45, delays=0.05/0/0/0.4, dsn=2.0.0, status=sent (delivered to command: /usr/bin/procmail-wrapper -o -a $DOMAIN -d $LOGNAME)
Feb 26 09:12:41 host2 postfix/qmgr[2284]: 604EF2700D6: removed

```
```

**Comment by sebres** [comment]
> sends only emails from root@hostname to root@localhost

You should also supply to action all the parameters it expects (e. g. `sender` and `dest`), see here for example:
https://github.com/fail2ban/fail2ban/blob/b49c1ab4b3dcbd9728e05292da01c7357e19b3e1/config/jail.conf#L216-L217

**Comment by sebres** [comment]
Also note, that your mail-subsystem (but also command which is used in action) must be able to send mails to the outside.
E. g. for xarf-login-attack it is controlled by `mailcmd` parameter (default `sendmail`), for `complain` default `mailcmd` is `mail -s`. But you can overwrite it via `complain[..., mailcmd="sendmail"]`, if you want.

So only if you can send mail from the console (of root or user fail2ban running under), then fail2ban will be able to send it too.

**Comment by acosonic** [comment]
So, complain action should look like this:

complain[logpath=/var/log/auth.log, mailcmd="sendmail"]

For example ?

**Comment by sebres** [comment]
Yes, but I don't know your smtp-server resp. sendmail may need some other params too (in case of root), for example valid sender or something else.

**Comment by acosonic** [comment]
Looks like I've got it with complain, but it's missing sender and title... Trying to add it...

**Comment by acosonic** [comment]
I can't set title and sender properly, however abuse email is received... 

I have tried adding  complain[name=%(__name__)s, sender="%(sender)s", logpath=/var/log/auth.log, mailcmd="sendmail"]
but it's not setting sender or title...

**Comment by acosonic** [comment]
This wass all generated in mail.log

```
620642700D6: uid=0 from=<root>
Feb 27 14:04:44 host2 postfix/cleanup[11291]: 620642700D6: message-id=<20190227130444.620642700D6@host2.domdistrict.com>
Feb 27 14:04:44 host2 postfix/qmgr[1744]: 620642700D6: from=<root@host2.domdistrict.com>, size=13375, nrcpt=7 (queue active)
Feb 27 14:04:44 host2 postfix/trivial-rewrite[11292]: warning: do not list domain host2.domdistrict.com in BOTH mydestination and virtual_alias_domains
Feb 27 14:04:44 host2 postfix/trivial-rewrite[11292]: message repeated 5 times: [ warning: do not list domain host2.domdistrict.com in BOTH mydestination and virtual_alias_domains]
Feb 27 14:04:44 host2 postfix/local[11295]: 620642700D6: to=<94.247.200.75@host2.domdistrict.com>, orig_to=<94.247.200.75>, relay=local, delay=0.18, delays=0.16/0.01/0/0.01, dsn=5.1.1, status=bounced (unknown user: "94.247.200.75")
Feb 27 14:04:44 host2 postfix/local[11295]: 620642700D6: to=<from@host2.domdistrict.com>, orig_to=<from>, relay=local, delay=0.18, delays=0.16/0.01/0/0, dsn=5.1.1, status=bounced (unknown user: "from")
Feb 27 14:04:44 host2 postfix/error[11293]: 620642700D6: to=<--@host2.domdistrict.com>, orig_to=<-->, relay=none, delay=0.19, delays=0.16/0.02/0/0, dsn=5.1.3, status=bounced (bad address syntax)
Feb 27 14:04:44 host2 postfix/error[11293]: 620642700D6: to=<-f@host2.domdistrict.com>, orig_to=<-f>, relay=none, delay=0.19, delays=0.16/0.02/0/0, dsn=5.1.3, status=bounced (bad address syntax)
Feb 27 14:04:44 host2 spamd[992]: spamd: connection from ::1 [::1]:33536 to port 783, fd 5
Feb 27 14:04:44 host2 spamd[992]: spamd: setuid to host2 succeeded
Feb 27 14:04:44 host2 spamd[992]: spamd: processing message <20190227130444.620642700D6@host2.domdistrict.com> for host2:1085
Feb 27 14:04:44 host2 postfix/smtp[11294]: warning: nsinfo.co.rs: dane configured with dnssec lookups disabled
Feb 27 14:04:44 host2 spamd[993]: spamd: connection from ::1 [::1]:33538 to port 783, fd 5
Feb 27 14:04:44 host2 spamd[993]: spamd: setuid to fail2ban.host2 succeeded

```

**Comment by acosonic** [comment]
Eventually I was able to add subject and sender by installing mail utils, and adding parameters to mailarguments....

**Comment by sorolock** [comment]
hi, im having similar case, but mine was the sender is root@domain.com, i did some configuration for complain at action.d/complain.conf

> [Init]
message = Dear Sir/Madam,\n\nWe have detected abuse from the IP address $IP, which according to a whois lookup is on your network$

# Path to the log files which contain relevant lines for the abuser IP
#
logpath = /dev/null

# Option:  mailcmd
# Notes.:  Your system mail command. Is passed 2 args: subject and recipient
# Values:  CMD  Default: mail -s
# 
mailcmd = mail -s

# Option:  mailargs
# Notes.:  Additional arguments to mail command. e.g. for standard Unix mail:
#          CC reports to another address:
#              -c me@example.com
#          Appear to come from a different address - the '--' indicates
#          arguments to be passed to Sendmail:
#              -- -f me@example.com
# Values:  [ STRING ]  Default: (empty)
#
mailargs = jail@domain.com

**Comment by sorolock** [comment]
hi, im having similar case, but mine was the sender is root@domain.com, i did some configuration for complain at action.d/complain.conf

```
[Init]
message = Dear Sir/Madam,\n\nWe have detected abuse from the IP address $IP, which according to a whois lookup is on your network$

# Path to the log files which contain relevant lines for the abuser IP
#
logpath = /dev/null

# Option:  mailcmd
# Notes.:  Your system mail command. Is passed 2 args: subject and recipient
# Values:  CMD  Default: mail -s
# 
mailcmd = mail -s

# Option:  mailargs
# Notes.:  Additional arguments to mail command. e.g. for standard Unix mail:
#          CC reports to another address:
#              -c me@example.com
#          Appear to come from a different address - the '--' indicates
#          arguments to be passed to Sendmail:
#              -- -f me@example.com
# Values:  [ STRING ]  Default: (empty)
#
mailargs = jail@domain.com


```

here is my jail.local 

```
[postfix-auth]
enabled     = true
action      = iptables-multiport[name=postfix, port="http,https,smtp,submission,pop3,pop3s,imap,imaps,sieve", protocol=tcp]
               	complain[logpath=/var/log/maillog]
logpath     = /var/log/maillog

```

I expect jail@domain.com to be the sender, but it keep sending email from root@domain.com, maybe you can help me?

**Comment by sebres** [comment]
Do you see a pair lines above:
https://github.com/fail2ban/fail2ban/blob/d01fe9d22a717a0122143cde41ce5c18a1790f6e/config/action.d/complain.conf#L111-L113

I don't know which args your sendmail would allow. But may be the `-f` option is your choice, and it's easy to check it from console, so try something like this:
```
echo "Test..." | mail -f jail@domain.com -s "Test for F2B" recipent@example.com
```
Otherwise looks in your manpage for `mail` command for proper arguments.

If it works, you can then specify this args directly in `jail.local` without adjusting of complain.conf:
```ini
[postfix-auth]
...
action = iptables-multiport[name=postfix, port="http,https,smtp,submission,pop3,pop3s,imap,imaps,sieve", protocol=tcp]
         complain[mailargs="-f jail@domain.com", logpath=/var/log/maillog]
```
