### ISSUE TITLE
Fail2ban not banning existing user

### ISSUE THREAD

**Issue by doliG** [fail2ban/fail2ban#2361]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): v0.9.6
- OS, including release name/version: Debian 9.8
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:
Fail2ban doesn't ban existing user.
It works well for user that doesn't exist.

#### Steps to reproduce
Install fail2ban and my conf in a VM with debian, then from another machine do

```bash
while [ true ]; do ssh user@ip; done
```

If user exist (root for example), no matter how much he fails to connect, he won't be banned.
If user doesn't exists, fail2ban do the job correctly.

#### Expected behavior
Ban existing AND non existing user after x failures as defined in `jail.local`.

#### Observed behavior
Ban only non existing user.

#### Any additional information
In my ssh config, I just change these lines : 
```
Port 42
PermitRootLogin no
PasswordAuthentication no
```

#### Any customizations done to /etc/fail2ban/ configuration
My config file  `/etc/fail2ban/jail.local` : 
```
[sshd]
enabled = true
port = 42
maxfailures = 3
```

Thanks you for helping :)

**Comment by sebres** [comment]
Because it may be configuration and version-related, please provide the log-lines that are produced if failed to login/authenticate (auth.log or systemd-journal) for both existing and not existing users.

Additionally because 0.9.6 is too old, possibly update of filter to latest 0.9th version may help you here:
https://github.com/fail2ban/fail2ban/blob/0.9/config/filter.d/sshd.conf
(don't try 0.10th/0.11th filters, that are incompatible).

**Comment by sebres** [comment]
closed until more info provided.

**Comment by apiotrowski312** [comment]
I had the same problem.  I added `^%(__prefix_line)sConnection closed by <HOST> port \d+ \[preauth\]$` to sshd failregex and now it works.

**Comment by apiotrowski312** [comment]
I have simmilar problem. With 
```
PermitRootLogin no
PasswordAuthentication no
```

F2B not banning attempts like this one: (auth.log)
```
Apr  2 15:23:02 SERVER sshd[20316]: Connection from XXX.XXX.XX.XXX port 58186 on YYY.YYY.YY.YYY port 42
Apr  2 15:23:04 SERVER sshd[20316]: Connection closed by XXX.XXX.XX.XXX port 58186 [preauth]
```

**Comment by sebres** [comment]
1. This is not similar problem.
2. The first message is not a failure at all, the second is not an authentication failure in sense of fail2ban (so it is not activated per default), in newer versions (>= 0.10) we've modes (`ddos` and `aggressive`) where this will be activated (see https://github.com/fail2ban/fail2ban/blob/1c1d2cc435d6e8f1eb4a1b60c935a1385a82e295/config/filter.d/sshd.conf#L69)

So if you use newer fail2ban version, just add wanted mode in your `jail.local` in section of jail `sshd`:
```ini
[sshd]
mode = aggressive
```
