### ISSUE TITLE
IPv6 subnet support

### ISSUE THREAD

**Issue by mdavids** [fail2ban/fail2ban#2365]
It seems as if IPv6 addresses are blocked as an /128. This is only partly useful, because an attacker can easily use new addresses from the same subnet and continue to do this almost indefinitely 

My suggestion would be to create a configurable option that allows to block an entire IPv6 subnet, like an entire /48, /56 or (the default?) an entire /64, rather than just a single /128 as it is now.

This touches https://github.com/fail2ban/fail2ban/issues/927

**Comment by sebres** [comment]
We have already several issues about this with good stuff in discussions inside.
Please let us continue there. Thus closed in order to avoid duplicates.
