### ISSUE TITLE
Postfix mode=agressive generates errors

### ISSUE THREAD

**Issue by techexo** [fail2ban/fail2ban#2370]
### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): 0.10.2-2~bpo9+1 (from stretch-backports)
- OS, including release name/version: Debian Stable
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

Hello everyone,

I have trouble setting up the `postfix` jail on my mail server.
On debian, `/etc/fail2ban/filter.d/postfix.conf` indicates:

> \# Parameter "mode": more (default combines normal and rbl), auth, normal, rbl, ddos, extra or aggressive (combines all)
> \# Usage example (for jail.local):
> **\#   [postfix]**
> **\#   mode = aggressive**
> \#   \# or another jail (rewrite filter parameters of jail):
> \#   [postfix-rbl]
> \#   filter = postfix[mode=rbl]
> \#
> mode = more

So I use on my server the followin in `/etc/fail2ban/jail.local`:
```
[postfix]
enabled = true
mode = agressive
banaction = ufw[application=Mail]
port = smtp, smtps
maxretry = 3
bantime = 86400
findtime = 18000
```
(the `Mail` app is defined by myself in ufw's configuration, which shouldn't be relevant to this issue)

In the log, an ERROR appears: `ERROR   No failure-id group in '<mdre-agressive>'`; which shouldn't be there I suppose. I have absolutely no idea if the jail works afterwards or not.

Please feel free to ask for more information if needed and thanks for the good work 👍 

#### Relevant parts of /var/log/fail2ban.log file:
```
fail2ban.jail           [7041]: INFO    Jail 'postfix' uses pyinotify {}
fail2ban.jail           [7041]: INFO    Initiated 'pyinotify' backend
fail2ban.server         [7041]: INFO    Jail postfix is not a JournalFilter instance
fail2ban.filter         [7041]: ERROR   No failure-id group in '<mdre-agressive>'
fail2ban.transmitter    [7041]: WARNING Command ['set', 'postfix', 'addfailregex', '<mdre-agressive>'] has failed. Received RegexException("No failure-id group in '<mdre-agressive>'",)
fail2ban                [7041]: ERROR   NOK: ("No failure-id group in '<mdre-agressive>'",)
```

**Comment by sebres** [comment]
If you take a closer look in https://github.com/fail2ban/fail2ban/blob/8c804a229036c45b92fc17437899d28b853d0ebf/config/filter.d/postfix.conf#L58
you could possibly see a difference...

So following change would solve it for you :)
```diff
-mode = agressive
+mode = aggressive
```

**Comment by techexo** [comment]
Sure it does solve the issue... Sorry, "agressif" takes only one "g" in French 😏 
Thanks 😄
