### ISSUE TITLE
fail2ban-tmpfiles.conf points to /var/run/ instead of /run

### ISSUE THREAD

**Issue by wizwuz** [fail2ban/fail2ban#2371]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): Fail2Ban v0.10.2
- OS, including release name/version: Debian buster/sid via Raspbian
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
Warning message in syslog:
```
systemd-tmpfiles[134]: [/usr/lib/tmpfiles.d/fail2ban-tmpfiles.conf:1] Line references path below legacy directory /var/run/, updating /var/run/fail2ban → /run/fail2ban; please update the tmpfiles.d/ drop-in file accordingly.
```
The warning has been added in the latest systemd tmpfiles.d to highlight issues in owner's config files.

#### Expected behavior
fail2ban-tmpfiles.conf needs to be updated with the new /run path instead of /var/run.

#### Observed behavior
tmpfiles.d corrects the path but the config needs to be updated with the new /run path instead of /var/run.

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:
```
systemd-tmpfiles[134]: [/usr/lib/tmpfiles.d/fail2ban-tmpfiles.conf:1] Line references path below legacy directory /var/run/, updating /var/run/fail2ban → /run/fail2ban; please update the tmpfiles.d/ drop-in file accordingly.
```

**Comment by sebres** [comment]
Thx, but there is already a PR about that. Thus further in #2174.
