### ISSUE TITLE
failregex bug? 

### ISSUE THREAD

**Issue by kang000feng** [fail2ban/fail2ban#2375]
below is the output that i test my regex 
```
^\w+\s+\d+ \d+:\d+:\d+\s+%(__prefix_line)sERROR:\s+failed to handshake with <HOST>: authentication error$
```

NOT MATHCED, BUT I DIDN'T SEE ANYTHING error.  any advice would be appreciated. 
```
# fail2ban-regex 'Aug 15 08:59:07 <hostname> ss-server[1382]: 2018-08-15 08:59:07 ERROR: failed to handshake with <HOST>: authentication error' '^\w+\s+\d+ \d+:\d+:\d+\s+%(__prefix_line)sERROR:\s+failed to handshake with <HOST>: authentication error$'
```
Running tests
=============

Use failregex line : ^\w+\s+\d+ \d+:\d+:\d+\s+%(__prefix_line)sERROR:\s...
Use single line : Aug 15 08:59:07 <hostname> ss-server[1382]: 2018-0...

Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
| [1] (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
`-

Lines: 1 lines, 0 ignored, 0 matched, 1 missed
[processed in 0.00 sec]

|- Missed line(s):
| Aug 15 08:59:07 <hostname> ss-server[1382]: 2018-08-15 08:59:07 ERROR: failed to handshake with <HOST>: authentication error
`-

**Comment by sebres** [comment]
You don't see any error, because there is simply no error (at least not an error in sense of regex or fail2ban).

Just the interpolation does not work here, so `%(__prefix_line)s` will be not substituted as it would be in the case of filter-file (and how even it should be possible without any config-file included), so it will be simply interpreted as a part of regex.

Please use filter file instead of regex:
```
fail2ban-regex 'line or file to check' '/path/to/your-filter.conf'
```

**Comment by kang000feng** [comment]
> You don't see any error, because there is simply no error (at least not an error in sense of regex or fail2ban).
> 
> Just the interpolation does not work here, so `%(__prefix_line)s` will be not substituted as it would be in the case of filter-file (and how even it should be possible without any config-file included), so it will be simply interpreted as a part of regex.
> 
> Please use filter file instead of regex:
> 
> ```
> fail2ban-regex 'line or file to check' '/path/to/your-filter.conf'
> ```

hello Sebres
thx for your time..  as u advised, i use fail2ban-regex 'line or file to check' '/path/to/your-filter.conf'
but unfortunately it doesn't work either. 

here is my filter file's conf for your reference. thx again:  
 
[INCLUDES]
before = common.conf
[Definition]
_daemon = ss-server
failregex = ^\w+\s+\d+ \d+:\d+:\d+\s+%(__prefix_line)sERROR:\s+failed to handshake with <HOST>: authentication error$
ignoreregex =
datepattern = %%Y-%%m-%%d %%H:%%M:%%S

**Comment by sebres** [comment]
Use real log-line to test:
change `<HOST>` in *your test-line* to the real IP, it works to me then with your filter as it is:
```diff
-Aug 15 08:59:07 <hostname> ss-server[1382]: 2018-08-15 08:59:07 ERROR: failed to handshake with <HOST>: authentication error
+Aug 15 08:59:07 host ss-server[1382]: 2018-08-15 08:59:07 ERROR: failed to handshake with 192.0.2.1: authentication error
```

<details>

```
fail2ban.master/bin/fail2ban-regex -c /home/bcadmin/Projects/fail2ban.master/config/ ../test-filters/gh-2375-ss-srv.txt /home/bcadmin/Projects/fail2ban.master/../test-filters/gh-2375-ss-srv.conf

Running tests
=============

Use   failregex file : /test-filters/gh-2375-ss-srv.conf
Use      datepattern : Year-Month-Day 24hour:Minute:Second
Use         log file : /test-filters/gh-2375-ss-srv.txt
Use         encoding : UTF-8

Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] ^\w+\s+\d+ \d+:\d+:\d+\s+(?:\[\])?\s*(?:<[^.]+\.[^.]+>\s+)?(?:\S+\s+)?(?:kernel: \[ *\d+\.\d+\]\s+)?(?:@vserver_\S+\s+)?(?:(?:(?:\[\d+\])?:\s+[\[\(]?ss-server(?:\(\S+\))?[\]\)]?:?|[\[\(]?ss-server(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)\s+)?(?:\[ID \d+ \S+\]\s+)?ERROR:\s+failed to handshake with <HOST>: authentication error$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] Year-Month-Day 24hour:Minute:Second
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.00 sec]
```
</details>

**Comment by kang000feng** [comment]
> th-Day 24hour:Minute:Secon

omg.. what is going wrong?.. seriously it doesnt work for me.  can u please take a look for me?

# fail2ban-regex 'Aug 15 08:59:07 <hostname> ss-server[1382]: 2018-08-15 08:59:07 ERROR: failed to handshake with 152.19.169.185: authentication error' /etc/fail2ban/filter.d/shadowsocks-libev.conf --print-all-matched

Running tests
=============

Use   failregex filter file : shadowsocks-libev, basedir: /etc/fail2ban
Use      single line : Aug 15 08:59:07 <hostname> ss-server[1382]: 2018-0...


Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
`-

Lines: 1 lines, 0 ignored, 0 matched, 1 missed
[processed in 0.00 sec]

|- Missed line(s):
|  Aug 15 08:59:07 <hostname> ss-server[1382]: 2018-08-15 08:59:07 ERROR: failed to handshake with 152.19.169.185: authentication error
`-

**Comment by kang000feng** [comment]
> Use real log-line to test:
> change `<HOST>` in _your test-line_ to the real IP, it works to me then with your filter as it is:
> 
> ```diff
> -Aug 15 08:59:07 <hostname> ss-server[1382]: 2018-08-15 08:59:07 ERROR: failed to handshake with <HOST>: authentication error
> +Aug 15 08:59:07 host ss-server[1382]: 2018-08-15 08:59:07 ERROR: failed to handshake with 192.0.2.1: authentication error
> ```
> 
> ```
> fail2ban.master/bin/fail2ban-regex -c /home/bcadmin/Projects/fail2ban.master/config/ ../test-filters/gh-2375-ss-srv.txt /home/bcadmin/Projects/fail2ban.master/../test-filters/gh-2375-ss-srv.conf
> 
> Running tests
> =============
> 
> Use   failregex file : /test-filters/gh-2375-ss-srv.conf
> Use      datepattern : Year-Month-Day 24hour:Minute:Second
> Use         log file : /test-filters/gh-2375-ss-srv.txt
> Use         encoding : UTF-8
> 
> Results
> =======
> 
> Failregex: 1 total
> |-  #) [# of hits] regular expression
> |   1) [1] ^\w+\s+\d+ \d+:\d+:\d+\s+(?:\[\])?\s*(?:<[^.]+\.[^.]+>\s+)?(?:\S+\s+)?(?:kernel: \[ *\d+\.\d+\]\s+)?(?:@vserver_\S+\s+)?(?:(?:(?:\[\d+\])?:\s+[\[\(]?ss-server(?:\(\S+\))?[\]\)]?:?|[\[\(]?ss-server(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)\s+)?(?:\[ID \d+ \S+\]\s+)?ERROR:\s+failed to handshake with <HOST>: authentication error$
> `-
> 
> Ignoreregex: 0 total
> 
> Date template hits:
> |- [# of hits] date format
> |  [1] Year-Month-Day 24hour:Minute:Second
> `-
> 
> Lines: 1 lines, 0 ignored, 1 matched, 0 missed
> [processed in 0.00 sec]
> ```

AND i also use the log file to test, here it is:  

~# fail2ban-regex /var/log/syslog /etc/fail2ban/filter.d/shadowsocks-libev.conf --print-all-matched

Running tests
=============

Use   failregex filter file : shadowsocks-libev, basedir: /etc/fail2ban
Use         log file : /var/log/syslog
Use         encoding : UTF-8


Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [139] (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
`-

Lines: 139 lines, 0 ignored, 0 matched, 139 missed
[processed in 0.01 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all 139 lines

**Comment by kang000feng** [comment]
> Use      datepattern : Year-Month-Day 24hour:Minute:Second

hello Sebres,  the only difference i can see from ur result is that u used fail2ban-regex -c   and u have one more line:   Use      datepattern : Year-Month-Day 24hour:Minute:Second

can u please tell me what is going wrong? thx

**Comment by sebres** [comment]
People, we have our issue template not for nothing. 
Which version of fail2ban do you use?

If it is 0.9, the `datepattern` should be provided in `[Init]` section:

```ini
[INCLUDES]
before = common.conf
[Definition]
_daemon = ss-server
failregex = ^\w+\s+\d+ \d+:\d+:\d+\s+%(__prefix_line)sERROR:\s+failed to handshake with <HOST>: authentication error$
ignoreregex =

[Init]
datepattern = %%Y-%%m-%%d %%H:%%M:%%S
```
Otherwise I don't know why wrong date-pattern is actually used.

**Comment by kang000feng** [comment]
**HELLO @sebres ,thanks for your help very much!  YES, my Fail2Ban is v0.9.7, and now i add the  [Init] section, i set the maxtry= 1,  When I run this command fail2ban-client status shadowsocks-libev  I got this:** 
 Status for the jail: shadowsocks-libev
|- Filter
|  |- Currently failed: 2
|  |- Total failed:     4
|  `- File list:        /var/log/syslog
`- Actions
   |- Currently banned: 0
   |- Total banned:     0
   `- Banned IP list:

**However when I check with sudo iptables -L INPUT -v -n I got this:**
3393  589K f2b-shadowsocks-libev  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:23

fail2ban-regex /var/log/syslog /etc/fail2ban/filter.d/shadowsocks-libev.conf --print-all-matched

Running tests
=============

Use   failregex filter file : shadowsocks-libev, basedir: /etc/fail2ban
Use      datepattern : Year-Month-Day 24hour:Minute:Second
Use         log file : /var/log/syslog
Use         encoding : UTF-8


Results
=======

Failregex: 11 total
|-  #) [# of hits] regular expression
|   1) [11] ^\w+\s+\d+ \d+:\d+:\d+\s+(?:\[\])?\s*(?:<[^.]+\.[^.]+>\s+)?(?:\S+\s+)?(?:kernel: \[ *\d+\.\d+\]\s+)?(?:@vserver_\S+\s+)?(?:(?:(?:\[\d+\])?:\s+[\[\(]?ss-server(?:\(\S+\))?[\]\)]?:?|[\[\(]?ss-server(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)\s+)?(?:\[ID \d+ \S+\]\s+)?ERROR:\s+failed to handshake with <HOST>: authentication error$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [86] Year-Month-Day 24hour:Minute:Second
`-

Lines: 258 lines, 0 ignored, 11 matched, 247 missed
[processed in 0.01 sec]


**Q1: What am I doing wrong here?  WHY there is not Currently banned but Currently failed? btw there is no such file fail2ban.log under var/log/ .** 

i have added below section in jail.local  
[DEFAULT]
banaction = iptables

**Q2:  CAN i  set bantime= -3600 as negative number ?  as the documentation is stating that  Negative number for "permanent" ban.  http://www.fail2ban.org/wiki/index.php/MANUAL_0_8#Jail_Options**

thank you very much!

**Comment by kang000feng** [comment]
Q3: WHY there is only 4 in Total failed in Status for the jail ? but there is 11 matched line with 8 different IPs in the  /var/log/syslog?  

here it is: 

|- Matched line(s):
|  Mar 21 07:31:09 instance-2 ss-server[856]:  2019-03-21 07:31:09 ERROR: failed to handshake with 182.101.53.40: authentication error
|  Mar 21 09:48:09 instance-2 ss-server[856]:  2019-03-21 09:48:09 ERROR: failed to handshake with 14.204.122.40: authentication error
|  Mar 21 10:03:09 instance-2 ss-server[856]:  2019-03-21 10:03:09 ERROR: failed to handshake with 164.52.24.167: authentication error
|  Mar 21 10:03:49 instance-2 ss-server[856]:  2019-03-21 10:03:49 ERROR: failed to handshake with 164.52.24.167: authentication error
|  Mar 21 10:03:50 instance-2 ss-server[856]:  2019-03-21 10:03:50 ERROR: failed to handshake with 164.52.24.167: authentication error
|  Mar 21 10:03:50 instance-2 ss-server[856]:  2019-03-21 10:03:50 ERROR: failed to handshake with 164.52.24.167: authentication error
|  Mar 21 10:40:16 instance-2 ss-server[856]:  2019-03-21 10:40:16 ERROR: failed to handshake with 221.232.218.31: authentication error
|  Mar 21 16:08:50 instance-2 ss-server[856]:  2019-03-21 16:08:50 ERROR: failed to handshake with 219.142.245.167: authentication error
|  Mar 21 17:19:34 instance-2 ss-server[856]:  2019-03-21 17:19:34 ERROR: failed to handshake with 125.76.61.219: authentication error
|  Mar 22 03:06:15 instance-2 ss-server[856]:  2019-03-22 03:06:15 ERROR: failed to handshake with 182.101.59.98: authentication error
|  Mar 22 03:06:29 instance-2 ss-server[856]:  2019-03-22 03:06:29 ERROR: failed to handshake with 171.37.204.118: authentication error

**Comment by kang000feng** [comment]
BY the way  I have run the command sudo systemctl restart fail2ban for any change below

**Comment by sebres** [comment]
> Q1
> i set the maxtry= 1

I know nothing about `maxtry`... Do you mean `maxretry`.

> Q2: CAN i set bantime= -3600 as negative number ?

Dunno. Better you should use `bantime = -1` for permanent banning.

> what is the meaning of permanent ' in this doc

Permanent is permanent. This means the ban is never expired, so remain eternally until manually removed.

> Q3.

See our [wiki](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works) for more info.

**Comment by kang000feng** [comment]
> > Q1
> > i set the maxtry= 1
> 
> I know nothing about `maxtry`... Do you mean `maxretry`.
> 
> > Q2: CAN i set bantime= -3600 as negative number ?
> 
> Dunno. Better you should use `bantime = -1` for permanent banning.
> 
> > what is the meaning of permanent ' in this doc
> 
> Permanent is permanent. This means the ban is never expired, so remain eternally until manually removed.
> 
> > Q3.
> 
> See our [wiki](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works) for more info.

HELLO  , YES, i did set the maxretry= 1 correctly,   What am I doing wrong here? WHY there is not value in Currently banned but 4 counted in Currently failed? btw there is no such file fail2ban.log under var/log/ . and I have gone through the wiki , but can not find solution, can you please help me out?  thanks in advance.

**Comment by kang000feng** [comment]
Fail2ban does  detect 4 OF all 11 authentication failures resp.  BUT banning does not occur ,  I have check all the likely reasons with your wiki, but it doesn't work.

**Comment by sebres** [comment]
>  btw there is no such file fail2ban.log under var/log/

I don't know what the maintainer of your fail2ban distribution have been configured per default for the logging.
May be it is systemd-journal where you should try take a look.

Normally, if your jail was set to `maxretry = 1`, each found failure should cause a ban.
What do you see here:
```
fail2ban-client get shadowsocks-libev maxretry
```

**Comment by kang000feng** [comment]
> systemd-journal

hello Sebres, may i ask how should i take a look  with  systemd-journal?  what to check?  i can  read many log with command journalctl   

i see 1 when i run fail2ban-client get shadowsocks-libev maxretry. 

thanks for ur help

**Comment by sebres** [comment]
> may i ask how should i take a look with systemd-journal?

Oh dude, really? This is a developer repository/community, not a stackoverflow etc.
Are you banned by google?
```
journalctl -u fail2ban.service --since today
```
> what to check?

I don't know at the moment, possibly you'd see some errors or similar.
Anyway if you'd see `[shadowsocks-libev] Found ...`, it **must** be followed by `[shadowsocks-libev] Ban ...` by `maxretry = 1`. If not, I don't know what may be wrong here.

Please provide your config dump for jail:
```
fail2ban-client -d | grep shadowsocks-libev
```
May be one sees there something.

**Comment by kang000feng** [comment]
> > may i ask how should i take a look with systemd-journal?
> 
> Oh dude, really? This is a developer repository/community, not a stackoverflow etc.
> Are you banned by google?
> 
> ```
> journalctl -u fail2ban.service --since today
> ```
> > what to check?
> 
> I don't know at the moment, possibly you'd see some errors or similar.
> Anyway if you'd see `[shadowsocks-libev] Found ...`, it **must** be followed by `[shadowsocks-libev] Ban ...` by `maxretry = 1`. If not, I don't know what may be wrong here.
> 
> Please provide your config dump for jail:
> 
> ```
> fail2ban-client -d | grep shadowsocks-libev
> ```
> May be one sees there something.

hello seres, 

FYI , THANKS SO MUCH. I REALLY APPRECIATE IT . 

# fail2ban-client -d | grep shadowsocks-libev
['add', 'shadowsocks-libev', 'auto']
['set', 'shadowsocks-libev', 'addlogpath', '/var/log/syslog', 'head']
['set', 'shadowsocks-libev', 'logencoding', 'auto']
['set', 'shadowsocks-libev', 'maxretry', 1]
['set', 'shadowsocks-libev', 'findtime', 3600]
['set', 'shadowsocks-libev', 'bantime', -1]
['set', 'shadowsocks-libev', 'usedns', 'warn']
['set', 'shadowsocks-libev', 'ignorecommand', '']
['set', 'shadowsocks-libev', 'addignoreip', '127.0.0.1/8']
['set', 'shadowsocks-libev', 'addfailregex', '^\\w+\\s+\\d+ \\d+:\\d+:\\d+\\s+(?:\\[\\])?\\s*(?:<[^.]+\\.[^.]+>\\s+)?(?:\\S+\\s+)?(?:kernel: \\[ *\\d+\\.\\d+\\]\\s+)?(?:@vserver_\\S+\\s+)?(?:(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?ss-server(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?ss-server(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)\\s+)?(?:\\[ID \\d+ \\S+\\]\\s+)?ERROR:\\s+failed to handshake with <HOST>: authentication error$']
['set', 'shadowsocks-libev', 'datepattern', '%Y-%m-%d %H:%M:%S']
['set', 'shadowsocks-libev', 'addaction', 'iptables']
['set', 'shadowsocks-libev', 'action', 'iptables', 'actionstart', '<iptables> -N f2b-<name>\n<iptables> -A f2b-<name> -j <returntype>\n<iptables> -I <chain> -p <protocol> --dport <port> -j f2b-<name>']
['set', 'shadowsocks-libev', 'action', 'iptables', 'actionstop', '<iptables> -D <chain> -p <protocol> --dport <port> -j f2b-<name>\n<iptables> -F f2b-<name>\n<iptables> -X f2b-<name>']
['set', 'shadowsocks-libev', 'action', 'iptables', 'actioncheck', "<iptables> -n -L <chain> | grep -q 'f2b-<name>[ \\t]'"]
['set', 'shadowsocks-libev', 'action', 'iptables', 'actionban', '<iptables> -I f2b-<name> 1 -s <ip> -j <blocktype>']
['set', 'shadowsocks-libev', 'action', 'iptables', 'actionunban', '<iptables> -D f2b-<name> -s <ip> -j <blocktype>']
['set', 'shadowsocks-libev', 'action', 'iptables', 'name', 'shadowsocks-libev']
['set', 'shadowsocks-libev', 'action', 'iptables', 'bantime', '-1']
['set', 'shadowsocks-libev', 'action', 'iptables', 'port', '443']
['set', 'shadowsocks-libev', 'action', 'iptables', 'protocol', 'tcp']
['set', 'shadowsocks-libev', 'action', 'iptables', 'chain', 'INPUT']
['set', 'shadowsocks-libev', 'action', 'iptables', 'known/chain', 'INPUT']
['set', 'shadowsocks-libev', 'action', 'iptables', 'known/name', 'default']
['set', 'shadowsocks-libev', 'action', 'iptables', 'known/port', 'ssh']
['set', 'shadowsocks-libev', 'action', 'iptables', 'known/protocol', 'tcp']
['set', 'shadowsocks-libev', 'action', 'iptables', 'known/blocktype', 'REJECT --reject-with icmp-port-unreachable']
['set', 'shadowsocks-libev', 'action', 'iptables', 'blocktype', 'REJECT --reject-with icmp-port-unreachable']
['set', 'shadowsocks-libev', 'action', 'iptables', 'known/returntype', 'RETURN']
['set', 'shadowsocks-libev', 'action', 'iptables', 'returntype', 'RETURN']
['set', 'shadowsocks-libev', 'action', 'iptables', 'known/lockingopt', '-w']
['set', 'shadowsocks-libev', 'action', 'iptables', 'lockingopt', '-w']
['set', 'shadowsocks-libev', 'action', 'iptables', 'known/iptables', 'iptables <lockingopt>']
['set', 'shadowsocks-libev', 'action', 'iptables', 'iptables', 'iptables <lockingopt>']
['set', 'shadowsocks-libev', 'action', 'iptables', 'known/known/chain', 'INPUT']
['set', 'shadowsocks-libev', 'action', 'iptables', 'known/known/name', 'default']
['set', 'shadowsocks-libev', 'action', 'iptables', 'known/known/port', 'ssh']
['set', 'shadowsocks-libev', 'action', 'iptables', 'known/known/protocol', 'tcp']
['set', 'shadowsocks-libev', 'action', 'iptables', 'known/known/blocktype', 'REJECT --reject-with icmp-port-unreachable']
['set', 'shadowsocks-libev', 'action', 'iptables', 'known/known/returntype', 'RETURN']
['set', 'shadowsocks-libev', 'action', 'iptables', 'known/known/lockingopt', '-w']
['set', 'shadowsocks-libev', 'action', 'iptables', 'known/known/iptables', 'iptables <lockingopt>']
['start', 'shadowsocks-libev']

**Comment by sebres** [comment]
So the regex and datepattern look still correct, at least fail2ban-regex using both give me following result: <details>

```
fail2ban-regex -v -d '%Y-%m-%d %H:%M:%S' /test-filters/gh-2375-ss-srv.txt '^\w+\s+\d+ \d+:\d+:\d+\s+(?:\[\])?\s*(?:<[^.]+\.[^.]+>\s+)?(?:\S+\s+)?(?:kernel: \[ *\d+\.\d+\]\s+)?(?:@vserver_\S+\s+)?(?:(?:(?:\[\d+\])?:\s+[\[\(]?ss-server(?:\(\S+\))?[\]\)]?:?|[\[\(]?ss-server(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)\s+)?(?:\[ID \d+ \S+\]\s+)?ERROR:\s+failed to handshake with <HOST>: authentication error$'

Running tests
=============

Use      datepattern : Year-Month-Day 24hour:Minute:Second
Use   failregex line : ^\w+\s+\d+ \d+:\d+:\d+\s+(?:\[\])?\s*(?:<[^.]+\.[^...
Use         log file : /test-filters/gh-2375-ss-srv.txt
Use         encoding : UTF-8


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] ^\w+\s+\d+ \d+:\d+:\d+\s+(?:\[\])?\s*(?:<[^.]+\.[^.]+>\s+)?(?:\S+\s+)?(?:kernel: \[ *\d+\.\d+\]\s+)?(?:@vserver_\S+\s+)?(?:(?:(?:\[\d+\])?:\s+[\[\(]?ss-server(?:\(\S+\))?[\]\)]?:?|[\[\(]?ss-server(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)\s+)?(?:\[ID \d+ \S+\]\s+)?ERROR:\s+failed to handshake with <HOST>: authentication error$
|      192.0.2.1  Wed Aug 15 08:59:07 2018
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] Year-Month-Day 24hour:Minute:Second
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.00 sec]
```
</details>

Then, let check following:
```
fail2ban-regex -v '/var/log/syslog' /etc/fail2ban/filter.d/shadowsocks-libev.conf
```

1. Control the timestamp you'd see in Result section if you test it.
In my example above you see `192.0.2.1  Wed Aug 15 08:59:07 2018`.
Is the time correct? (just to exclude timezone issues).
Do you see any IP with an attempt time older than time of last restart of fail2ban - 1 hour? (since your `findtime` is 3600)

2. Are this IPs not belonging to '127.0.0.1/8'? (as your ignoreip)

3. Have you found the fail2ban.log/journal?
Are there some entries `[shadowsocks-libev] Found ...`?
Are there some entries `[shadowsocks-libev] Ban ...`?
At least the IPs you'd see above should be found there.

4. Do you see any error after Ban?
