### ISSUE TITLE
Custom action randomly triggered

### ISSUE THREAD

**Issue by tenjohnx** [fail2ban/fail2ban#2379]
I have two Samba related jails and I noticed that my custom action randomly triggered roughly once in a week. Almost everything works except this.

I've been running Fail2ban in debug mode for some time. I compared the time of the event triggered with the Fail2ban log files and everything was completely normal. Also the status of my jails looks fine. There is absolutely no sign that my custom action was triggered, the other iptables action was untouched. So I don't have a clue what was caused this.

Tested with both version of Fail2ban (0.9.4 and 0.10.2) on Ubuntu Server 18.04. Thanks for all of your suggestions!

Here are my two jails, filters and my custom action config files:

#### Jail - /etc/fail2ban/jail.d/samba.conf

```
[samba]

enabled = true
filter = samba
action = iptables-allports[name=SAMBA,protocol=all]
         push-the-red-button
logpath = /var/log/samba/log.audit
maxretry = 50
findtime = 120
bantime = 86400
```
#### Filter - /etc/fail2ban/filter.d/samba.conf

```
[Definition]

failregex = ^\ssamba-server\ssmbd_audit\s<HOST>\|.+\|.+\|rename\|ok\|.+\|.+$

ignoreregex = ^\ssamba-server\ssmbd_audit\s<HOST>\|.+\|.+\|rename\|ok\|.+\|.+\.tmp$
              ^\ssamba-server\ssmbd_audit\s<HOST>\|.+\|.+\|rename\|ok\|.+\.tmp\|.+$
              ^\ssamba-server\ssmbd_audit\s<HOST>\|.+\|.+\|rename\|ok\|.+\|.+\.TMP$
              ^\ssamba-server\ssmbd_audit\s<HOST>\|.+\|.+\|rename\|ok\|.+\.TMP\|.+$
```

#### Custom action - /etc/fail2ban/action.d/push-the-red-button.conf

```
[Definition]

actionstart =
actionstop =
actioncheck =
actionban = /usr/bin/ssh -i /home/ssh/remoteuser_id_rsa remoteuser@172.16.10.20 'touch red_button_pushed'
actionunban =
```
#### Jail - /etc/fail2ban/jail.d/samba-one-shot.conf

```
[samba-one-shot]

enabled = true
filter = samba-one-shot
action = iptables-allports[name=SAMBA-ONE-SHOT,protocol=all]
         push-the-red-button
logpath = /var/log/samba/log.audit
maxretry = 0
findtime = 300
bantime = 8640
```
#### Filter - /etc/fail2ban/filter.d/samba-one-shot.conf

```
[Definition]

failregex = ^\ssamba-server\ssmbd_audit\s<HOST>\|.+\|.+\|pwrite\|ok\|(wall-1.txt|wall-2.txt)$

ignoreregex =
```

**Comment by sebres** [comment]
> I noticed that my custom action randomly triggered roughly once in a week.
> I compared the time of the event triggered with the Fail2ban log files and everything was completely normal. Also the status of my jails looks fine.

This is simply impossible - current implementation of action in mentioned fail2ban versions does not have timers or delayed execution at all, so if you don't see `[samba-one-shot] Ban ...` in the fail2ban.log, the action would not be triggered.

So I'm pretty sure you should try to find something on your own side, e. g. some cron possibly or something else locally or on remote side (172.16.10.20) that executes the same once in a week.

To be sure the fail2ban has this only in actionban check the dump of config:
```
fail2ban-client -d | grep 'touch red_button_pushed'
```
