### ISSUE TITLE
consolidated failure counts

### ISSUE THREAD

**Issue by grooverdan** [fail2ban/fail2ban#238]
With centralised authentication mechanisms one way that an attacker can gain authentication without the inconvenience of being hit by fail2ban is to distribute the attack against multiple hosts that have the same backend authentication.

A defence mechanism against this is to add a new jail level configuration item for a distributed memcache configuration so the network can push failures to the central location.

Using memcached incr (https://code.google.com/p/memcached/wiki/NewCommands#incr/decr) to keep a fail count, and the "append" command for fail data will store similar data to what's needed.

This will allow a network centric single point for referencing failures detected on a network.

Need to consider #67 with this.

Thoughts?

**Comment by ar45** [comment]
Am also in need for such use. I started to look into logstash, it is definitely able to solve this. However it it is some new learning curve and takes time ;)

**Comment by sebres** [comment]
Let's avoid duplicates (further in #881)
