### ISSUE TITLE
Add hostname for reverse proxies

### ISSUE THREAD

**Issue by modem7** [fail2ban/fail2ban#2384]
Heya, 

As an addon to #2144 would it be possible for the fail2ban email system to show which subdomain/domain that the failed IP came from? 

E.g. Let's say I run an nginx server w/ fail2ban. 5 domains are pointed to the same IP address, but different ports. 

Failed IP hits bob.mydomain.com and gets banned. 

Email report says: Banned IP 5.5.5.5 due to jail nginx-auth from bob.mydomain.com?

This should be doable relatively easily. In the nginx error log, the following is logged:

> 2019/03/27 19:52:05 [error] 21690#21690: *4508 user "admin" was not found in "/etc/nginx/.htpasswd", client: 5.5.5.5, server: bob.mydomain.com, request: "GET / HTTP/1.1", host: "7.7.7.7", referrer: "https://7.7.7.7:443/"

**Comment by sebres** [comment]
> would it be possible for the fail2ban email system to show which subdomain/domain that the failed IP came from?

Theoretically yes. But it depends.

> 5 domains are pointed to the same IP address, but different ports.

If you want to use the server from the failure log-line,
you can rewrite failregex to capture this info like `server: <F-SERVER>\S*</F-SERVER>` and use it in action hereafter...

Jail.local or filter.d/*.local:
```ini
failregex = ^ \[error\] \d+#\d+: \*\d+ user "(?:[^"]+|.*?)":? (?:password mismatch|was not found in "[^\"]*"), client: <HOST>, server: <F-SERVER>\S*</F-SERVER>, request: "\S+ \S+ HTTP/\d+\.\d+", host: "\S+"(?:, referrer: "\S+")?\s*$
```
Then the new tag `<F-SERVER>` would be usable for actions:
```ini
actionban = ... echo "Banned IP <ip> due to jail <name> from <F-SERVER>" ...
```

**Comment by sebres** [comment]
Just note this would contain only a server-name from message of last attempt, so for example if you've configured `maxretry = 5`, and the intruder tried 4 times on `foo.example.com` and then 1 time on `bar.example.com`, at end it contains only `bar.example.com` (and not both).

So possibly you should simply use already available tag `<matches>` to obtain servers of all failures... Something like this:
```
echo $(echo "<matches>" | grep -oE ' server:\s(\S+),' | sort -u)
```
