### ISSUE TITLE
Feature: Email Sending @blocking

### ISSUE THREAD

**Issue by thE-iNviNciblE** [fail2ban/fail2ban#2389]
i know i could send the "/var/log/fail2ban.log" to my imap but, i want a more flexible solution without "grep", regex... is it possible to use "mail" preconfigured email settings?

i hope not to much work, would be very cool for supporting @Plesk 17.x ... 18.x where your tool is super easy to use, i mean voice.plesk would do that for ya if you could to the pre work...

**Comment by sebres** [comment]
I can not follow at all what you'd say with this request.

Can you describe your concern a bit more precise?
