### ISSUE TITLE
Set journalflags to 6 (SYSTEM_ONLY + RUNTIME_ONLY) by default

### ISSUE THREAD

**Issue by opoplawski** [fail2ban/fail2ban#2392]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.10.4
- OS, including release name/version: EL7
- [X ] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase

### The issue:

By default, fail2ban opens a journal Reader with no flags.  This open every file under /var/log/journal/MACHINE-ID, which can include a *lot* of user session files (my mail server has almost 500 for instance).  This can lead to "Too many open files" errors like #2208 

Since it is *highly* unlikely that any services that fail2ban is interested in are running under user sessions, and we start reading from Now - FindTime (probably at most 1d for recidive), I propose that we make journalflags=6 (SYSTEM_ONLY + RUNTIME_ONLY) the default.  At least on my test machine this does not open any files in /var/log/journal, presumably streaming just from the running journald process.

**Comment by opoplawski** [comment]
Except for the fact that fail2ban appears to not find anything at all with journalflags=6, at least on EL7.  Seems to work with journalflags=4.  I wonder what is up with that.

**Comment by sebres** [comment]
Hmm... possibly a flag `RUNTIME_ONLY(2)` wins over `SYSTEM_ONLY(4)`.
But related to documentation:
>  a set of constants which maybe bitwise OR-ed together and passed to the Journal constructor.

So I don't really know which combination is proper or better to use per default.

BTW, there is also another flag `LOCAL_ONLY(1)`
> `LOCAL_ONLY(1)` - Only open journal files generated on the local machine.
