### ISSUE TITLE
Feature: clear IP on success (enables long findtimes to combat slow-burn botnets)

### ISSUE THREAD

**Issue by cepheid666** [fail2ban/fail2ban#2394]
Feature request: for an IP that is being "tracked" (has failed but has not yet been banned), provide an option to reset its counter (clear tracking) on successful login.

**Example:**
1) Legit user from IP 1.2.3.4 mistypes password and fails against `sshd` filter 3 times, with `maxretry = 4` and `findtime = 3600`.
2) Next connection, user manages to successfully connect, is logged in for 15 minutes, logs out.
3) User attempts reconnect 5 minutes later, mistypes password again.
--> Under current f2b, user will be locked out for 4th failure within an hour.
--> Under this feature request, user's failcount will have reset to 0 upon successful login, so this failure will NOT lock out and user can try again.

**Reasoning:** a lot of botnets have lately been using widely distributed attacks, where brute-force attempts will come from hundreds or possibly thousands of IPs, with a given IP repeating only every many hours or few days. (This is particularly an issue for spambots attacking SMTP AUTH and worms attacking SSHD.)

Most "reasonable" findtimes (minutes or 1-3 hours) will not catch these IPs because they fail slowly. Longer findtimes (days or more) run a significant risk of false positives, catching legitimate users who have a few "oopsies" that are distributed in time (e.g., above example).

These distributed attacks may use many different subnets, so even subnet matching (which is not yet a feature) may not work well unless findtimes are very long, which, again, runs a significant risk of catching legit users.  (See related feature request #927 related to subnet matching.)

BUT one can mitigate the false-positive situation by resetting the counter (clearing the IP from the list) when a login is successful.  This would mean users with a few "oopsies" will get forgiven immediately upon their next success, but spambots would not.  That means we could use a findtime of (say) 1 week, to combat these widely-distributed botnet attacks, but with little risk of catching legitimate users who make the occasional mistake.

**Proposed implementation:**
This would require a "successregex" for each filter where this option is to be enabled, and also longer dbpurgeage (at least as long as the findtime we want).

This feature also makes the progressive bantimes more powerful, because it enables catching more of the distributed botnets, more often.

CPU/RAM impact would be minimal because f2b already checks every log line for regexp match and already checks every IP against its DB... so this adds only one more regex check (match against successregex) and one more IP check (if IP found, clear it; if not found, ignore), equivalent to adding a new filter.

**Comment by sebres** [comment]
This RFE is partially implemented:
- within #1728 and continuations (new tag `<F-MLFFORGET>`, user/session differentiation etc)
- within #1243 (although not yet merged due to several reasons, for example https://github.com/fail2ban/fail2ban/pull/1243#issuecomment-262255515, but we have a possible solution now, because fail2ban can distinguish users/sessions after #1728, #2014 and #2090 got merged).

Anyway I'll close it as duplicate, so please further in #1243.

**Comment by cepheid666** [comment]
Thanks @sebres. Can you tell me what parts of this RFE are not yet implemented within the other PRs?  Obviously subnet testing, but that's a separate problem.  Just curious since I don't quite understand the language of #1728 and how that quite fits in (I guess because of the issue mentioned in #1243 regarding a legit user attempting to brute-force other logins).  Anyway just wondering whether #1728 and #1243 cover this RFE completely or if additional code is needed.

Thanks!!

**Comment by sebres** [comment]
> Obviously subnet testing, but that's a separate problem.

Yes, and again yes (and there is also already an open issue, so let's avoid duplicates).

> Anyway just wondering whether #1728 and #1243 cover this RFE completely 

Yes, if the current implementation of #1243 gets updated to solve all known issues which this PR would open (inclusive mentioned https://github.com/fail2ban/fail2ban/pull/1243#issuecomment-262255515), since it is possible now to obtain all necessary information (missing previously).
The only problem is - "persistent shortage of time".

**Comment by cepheid666** [comment]
> Yes, and again yes (and there is also already an open issue, so let's avoid duplicates).

Right, did not intend to make that a duplicate -- I merely meant to reference that it wouldn't solve this problem.

> The only problem is - "persistent shortage of time".

An ever-present problem with no known solution... 😄 
Thanks!
