### ISSUE TITLE
sendmail-reject extra filter regex mismatching MTA/MSP instead of MTA/MSA

### ISSUE THREAD

**Issue by drwonky** [fail2ban/fail2ban#2396]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): fail2ban-server-0.10.3.1-2.fc28.noarch
- OS, including release name/version: Fedora 28
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

The sendmail-reject mdre-extra regex fails to match log entries ending in ```did not issue MAIL/EXPN/VRFY/ETRN during connection to MSA```

#### Steps to reproduce

Port knock the MSA port instead of the MTA port

#### Expected behavior

log entries for "did not issue .... during connection to ..." should trigger mdre-extra regex

#### Observed behavior

regex is written to capture MTA/MSP instead of MTA/MSA.  I cannot find any examples via google of "during connection to MSP", I'm guessing this is an error.

#### Any customizations done to /etc/fail2ban/ configuration
jail.local
```
[DEFAULT]
bantime = 1h
findtime = 1h
maxretry = 1
ignoreip = 127.0.0.1/8 ::1 192.168.1.0/24

[sshd]
enabled = true
maxretry = 2
filter = sshd[mode=aggressive]

[uwimap-auth]
enabled = true

[sendmail-auth]
enabled = true

[sendmail-reject]
filter = sendmail-reject[mode=aggressive]
enabled = true
maxretry=2

[apache-shellshock]
enabled = true

[apache-auth]
enabled = true

[apache-badbots]
enabled = true

[apache-overflows]
enabled = true

[wp-auth]
enabled = true  
filter = wp-auth  
action = iptables-multiport[name=NoAuthFailures, port="http,https"]  
logpath = /var/log/httpd/access_log  

[dovecot]
enabled=true
filter = dovecot[mode=aggressive]

```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_
Nothing was logged because regex didn't match
```
```

#### Relevant lines from monitored log files in question:

```
Apr  3 17:18:14 foo sendmail[415539]: x340IDR4415539: 79.214.158.27.broad.zz.fj.dynamic.163data.com.cn [27.158.214.79] (may be forged) did not issue MAIL/EXPN/VRFY/ETRN during connection to MSA
Apr  3 17:18:15 foo sendmail[415542]: x340IE0r415542: 79.214.158.27.broad.zz.fj.dynamic.163data.com.cn [27.158.214.79] (may be forged) did not issue MAIL/EXPN/VRFY/ETRN during connection to MSA
```

**Comment by drwonky** [comment]
The following change fixes the problem:
```diff
-mdre-extra = ^(?:\S+ )?\[(?:IPv6:<IP6>|<IP4>)\](?: \(may be forged\))? did not issue (?:[A-Z]{4}[/ ]?)+during connection to M(?:TA|SP)(?:-\w+)?$
+mdre-extra = ^(?:\S+ )?\[(?:IPv6:<IP6>|<IP4>)\](?: \(may be forged\))? did not issue (?:[A-Z]{4}[/ ]?)+during connection to M(?:TA|SA)(?:-\w+)?$
```
```
Apr  3 17:33:14 foo sendmail[415330]: x340G9Ps415330: 232.50.186.60.broad.hz.zj.dynamic.163data.com.cn [60.186.50.232] (may be forged) did not issue MAIL/EXPN/VRFY/ETRN during connection to MSA
```
```
2019-04-03 17:33:14,872 fail2ban.filter         [323793]: INFO    [sendmail-reject] Found 60.186.50.232 - 2019-04-03 17:33:14
```

**Comment by sebres** [comment]
Looks like PR #2388 would fix it, thus closed.
Please reopen if I'm wrong.
