### ISSUE TITLE
identify file type based on content

### ISSUE THREAD

**Issue by ritadcc126** [fail2ban/fail2ban#2398]
Creating an application that selects only mail box files with any or no extension. User can select any or all the files of any type, but the application will filter only mail box files

Some mail box files have extension .mbox, some have .mbs and some are txt files.
 static  class NativeMethod
    {
        [StructLayout(LayoutKind.Sequential)]
        public struct SHFILEINFO
        {
            public IntPtr hIcon;
            public int iIcon;
            public uint dwAttributes;
            [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 260)]
            public string szDisplayName;
            [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 80)]
            public string szTypeName;
        };

        public static class FILE_ATTRIBUTE
        {
            public const uint FILE_ATTRIBUTE_NORMAL = 0x80;
        }

        public static class SHGFI
        {
            public const uint SHGFI_TYPENAME = 0x000000400;
            public const uint SHGFI_USEFILEATTRIBUTES = 0x000000010;
        }

        [DllImport("shell32.dll")]
        public static extern IntPtr SHGetFileInfo(string pszPath, uint dwFileAttributes, ref SHFILEINFO psfi, uint cbSizeFileInfo, uint uFlags);

    }
 private void button1_Click(object sender, EventArgs e)
        {
            NativeMethod.SHFILEINFO info = new NativeMethod.SHFILEINFO();

            // string fileName = @"C:\Impersonation.mbox";
            openFileDialog1.ShowDialog();
            string fileName = openFileDialog1.FileName;
            uint dwFileAttributes = NativeMethod.FILE_ATTRIBUTE.FILE_ATTRIBUTE_NORMAL;
            uint uFlags = (uint)(NativeMethod.SHGFI.SHGFI_TYPENAME | NativeMethod.SHGFI.SHGFI_USEFILEATTRIBUTES);
            NativeMethod.SHGetFileInfo(fileName, dwFileAttributes, ref info, (uint)Marshal.SizeOf(info), uFlags);
                          MessageBox.Show(info.szTypeName + "," + info.szDisplayName);
                  Console.WriteLine(info.szTypeName);
        }
This is the code I had written but it does not solve my purpose, is there any other way to do the meaningful. Please help

**Comment by sebres** [comment]
I'm sure you've confused the repository (this is fail2ban-repo).
