### ISSUE TITLE
Ban while processing?

### ISSUE THREAD

**Issue by Tsaukpaetra** [fail2ban/fail2ban#2400]
### Environment:

- Fail2Ban version (including any possible distribution suffixes):  Fail2Ban v0.9.3
- OS, including release name/version: Ubuntu 16 by DigitalOcean
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

So, I'm setting up basic DDoS protection after getting attacked (naturally), and installed fail2ban from the distro repo. Now that I got my filters and jail lined up, I start everything and.... wait. Because an ongoing attack was generating about 100MB of logs per second, fail2ban was having trouble keeping up at all, and filling its log with:

And I thought to myself, "Well, that's certainly more than the limit of `maxretry=5` , why isn't it banning it already?"
Meanwhile CPU was spiked as it continued grepping the log file, and the log file continued growing ad-nauseum.
I did manage to "fix" it by adding the  `tail` hint at the end of `logpath` , but that just tells me it's likely to miss entries from other attackers (I presume?) as it's monitoring.

#### Steps to reproduce

Get a log file that's continuously being appended at a very high rate (thanks, nginx).
Match almost every line to an enabled filter.

#### Expected behavior

As soon as the maxretry limit was discovered to have been met inside the findtime window, enact the action.

#### Observed behavior

Churn through the log file, never ending, taking up 100% CPU and never completing the scan.

#### Any additional information

It's possible this issue has been mitigated in a newer version. I noticed (upon coming here) that the repo version is not so recent, and if it's been resolved in a newer version I'll attempt to replace the packaged version with a source-built one. Additionally, if there was a way to tell nginx to not be so spammy when it's rate-limiter is in effect, that would probably also work just as well.

### Configuration, dump and another helpful excerpts
nginx parameters:

```
limit_req_zone "$binary_remote_addr$request_uri" zone=sameuriip:10m rate=1r/s;
limit_req zone=sameuriip burst=5;
```

#### Any customizations done to /etc/fail2ban/ configuration
Filter
```
[Definition]
failregex = limiting requests, excess:.* by zone.*client: <HOST>
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
2019-04-12 07:29:56,744 fail2ban.filter         [24685]: INFO    [nginx-req-limit] Found ?.78.132.50
2019-04-12 07:29:56,744 fail2ban.filter         [24685]: INFO    [nginx-req-limit] Found ?.78.132.50
2019-04-12 07:29:56,744 fail2ban.filter         [24685]: INFO    [nginx-req-limit] Found ?.78.132.50
2019-04-12 07:29:56,745 fail2ban.filter         [24685]: INFO    [nginx-req-limit] Found ?.78.132.50
2019-04-12 07:29:56,747 fail2ban.filter         [24685]: INFO    [nginx-req-limit] Found ?.78.132.50
2019-04-12 07:29:56,748 fail2ban.filter         [24685]: INFO    [nginx-req-limit] Found ?.78.132.50
2019-04-12 07:29:56,748 fail2ban.filter         [24685]: INFO    [nginx-req-limit] Found ?.78.132.50
2019-04-12 07:29:56,763 fail2ban.filter         [24685]: INFO    [nginx-req-limit] Found ?.78.132.50
2019-04-12 07:29:56,763 fail2ban.filter         [24685]: INFO    [nginx-req-limit] Found ?.78.132.50
2019-04-12 07:29:56,764 fail2ban.filter         [24685]: INFO    [nginx-req-limit] Found ?.78.132.50
2019-04-12 07:29:56,764 fail2ban.filter         [24685]: INFO    [nginx-req-limit] Found ?.78.132.50
2019-04-12 07:29:56,765 fail2ban.filter         [24685]: INFO    [nginx-req-limit] Found ?.78.132.50
2019-04-12 07:29:56,767 fail2ban.filter         [24685]: INFO    [nginx-req-limit] Found ?.78.132.50
2019-04-12 07:29:56,767 fail2ban.filter         [24685]: INFO    [nginx-req-limit] Found ?.78.132.50
2019-04-12 07:29:56,768 fail2ban.filter         [24685]: INFO    [nginx-req-limit] Found ?.78.132.50
```

#### Relevant lines from monitored log files in question:

```
2019/04/12 07:31:07 [error] 24914#24914: *3648484 limiting requests, excess: 5.426 by zone "sameuriip", client: ?.78.132.50, server: www.mysite.com, request: "GET https://www.mysite.com HTTP/1.1", host: "www.mysite.com"
2019/04/12 07:31:08 [error] 24914#24914: *3648376 limiting requests, excess: 5.352 by zone "sameuriip", client: ?.78.132.50, server: www.mysite.com, request: "GET https://www.mysite.com HTTP/1.1", host: "www.mysite.com"
2019/04/12 07:31:08 [error] 24914#24914: *3647321 limiting requests, excess: 5.335 by zone "sameuriip", client: ?.78.132.50, server: www.mysite.com, request: "GET https://www.mysite.com HTTP/1.1", host: "www.mysite.com"
2019/04/12 07:31:08 [error] 24914#24914: *3648527 limiting requests, excess: 5.315 by zone "sameuriip", client: ?.78.132.50, server: www.mysite.com, request: "GET https://www.mysite.com HTTP/1.1", host: "www.mysite.com"
2019/04/12 07:31:08 [error] 24914#24914: *3648528 limiting requests, excess: 5.315 by zone "sameuriip", client: ?.78.132.50, server: www.mysite.com, request: "GET https://www.mysite.com HTTP/1.1", host: "www.mysite.com"
2019/04/12 07:31:08 [error] 24914#24914: *3648529 limiting requests, excess: 5.303 by zone "sameuriip", client: ?.78.132.50, server: www.mysite.com, request: "GET https://www.mysite.com HTTP/1.1", host: "www.mysite.com"
2019/04/12 07:31:08 [error] 24914#24914: *3647708 limiting requests, excess: 5.271 by zone "sameuriip", client: ?.78.132.50, server: www.mysite.com, request: "GET https://www.mysite.com HTTP/1.1", host: "www.mysite.com"
2019/04/12 07:31:08 [error] 24914#24914: *3648453 limiting requests, excess: 5.236 by zone "sameuriip", client: ?.78.132.50, server: www.mysite.com, request: "GET https://www.mysite.com HTTP/1.1", host: "www.mysite.com"
2019/04/12 07:31:08 [error] 24914#24914: *3648452 limiting requests, excess: 5.235 by zone "sameuriip", client: ?.78.132.50, server: www.mysite.com, request: "GET https://www.mysite.com HTTP/1.1", host: "www.mysite.com"
2019/04/12 07:31:08 [error] 24914#24914: *3648464 limiting requests, excess: 5.231 by zone "sameuriip", client: ?.78.132.50, server: www.mysite.com, request: "GET https://www.mysite.com HTTP/1.1", host: "www.mysite.com"
2019/04/12 07:31:08 [error] 24914#24914: *3648455 limiting requests, excess: 5.219 by zone "sameuriip", client: ?.78.132.50, server: www.mysite.com, request: "GET https://www.mysite.com HTTP/1.1", host: "www.mysite.com"
2019/04/12 07:31:08 [error] 24914#24914: *3648428 limiting requests, excess: 5.212 by zone "sameuriip", client: ?.78.132.50, server: www.mysite.com, request: "GET https://www.mysite.com HTTP/1.1", host: "www.mysite.com"
2019/04/12 07:31:08 [error] 24914#24914: *3648447 limiting requests, excess: 5.209 by zone "sameuriip", client: ?.78.132.50, server: www.mysite.com, request: "GET https://www.mysite.com HTTP/1.1", host: "www.mysite.com"
2019/04/12 07:31:08 [error] 24914#24914: *3648477 limiting requests, excess: 5.199 by zone "sameuriip", client: ?.78.132.50, server: www.mysite.com, request: "GET https://www.mysite.com HTTP/1.1", host: "www.mysite.com"
2019/04/12 07:31:08 [error] 24914#24914: *3648478 limiting requests, excess: 5.199 by zone "sameuriip", client: ?.78.132.50, server: www.mysite.com, request: "GET https://www.mysite.com HTTP/1.1", host: "www.mysite.com"
2019/04/12 07:31:08 [error] 24914#24914: *3648434 limiting requests, excess: 5.168 by zone "sameuriip", client: ?.78.132.50, server: www.mysite.com, request: "GET https://www.mysite.com HTTP/1.1", host: "www.mysite.com"
2019/04/12 07:31:08 [error] 24914#24914: *3648522 limiting requests, excess: 5.859 by zone "sameuriip", client: ?.78.132.50, server: www.mysite.com, request: "GET https://www.mysite.com HTTP/1.1", host: "www.mysite.com"
2019/04/12 07:31:08 [error] 24914#24914: *3648519 limiting requests, excess: 5.827 by zone "sameuriip", client: ?.78.132.50, server: www.mysite.com, request: "GET https://www.mysite.com HTTP/1.1", host: "www.mysite.com"
2019/04/12 07:31:08 [error] 24914#24914: *3648525 limiting requests, excess: 5.776 by zone "sameuriip", client: ?.78.132.50, server: www.mysite.com, request: "GET https://www.mysite.com HTTP/1.1", host: "www.mysite.com"
2019/04/12 07:31:08 [error] 24914#24914: *3648521 limiting requests, excess: 5.735 by zone "sameuriip", client: ?.78.132.50, server: www.mysite.com, request: "GET https://www.mysite.com HTTP/1.1", host: "www.mysite.com"
2019/04/12 07:31:08 [error] 24914#24914: *3648530 limiting requests, excess: 5.631 by zone "sameuriip", client: ?.78.132.50, server: www.mysite.com, request: "GET https://www.mysite.com HTTP/1.1", host: "www.mysite.com"
2019/04/12 07:31:08 [error] 24914#24914: *3648448 limiting requests, excess: 5.479 by zone "sameuriip", client: ?.78.132.50, server: www.mysite.com, request: "GET https://www.mysite.com HTTP/1.1", host: "www.mysite.com"
```

**Comment by sebres** [comment]
> And I thought to myself, "Well, that's certainly more than the limit of maxretry=5 , why isn't it banning it already?"

Well it may be for example because of obsolete ban (it is calculated from last attempt + `bantime`).
Or because of the `findtime` (`maxretry` attempts in `findtime`)...Or even both.
This behavior is changed since v.0.10 (scanning starts there from lines that are `now` - `findtime`). But 0.9 will process all entries regardless they are obsolete.

> I did manage to "fix" it by adding the tail hint at the end of logpath , but that just tells me it's likely to miss entries from other attackers (I presume?) as it's monitoring.

Why you would still need this old entries? 
If an intruder is still active, he will generate new failures (and get banned then).

The issue looks to me like all intruders generates so BIG log-files that fail2ban is unable to scan the logs so fast...
Anyway, fail2ban v0.9.3 is simply unsuitable to prevent a large DDoS attacks and there are several reasons, beginning with "too slow"...

Thus I'll close it as obsolete. You could try newer version and reopen with new insights.

**Comment by Tsaukpaetra** [comment]
Yeah, I was thinking if it could chunk its processing so at least some bans would get handed out (and the reducing the logs and thence reducing the workload), but I'm not sure how that's implemented in the first place so who knows?
I have no idea what constitutes a "large" attack, since this is my first one out in the wild. Only reason I saw it in the first place was that I got an alert that the CPU was being pegged trying to respond to all the connections.

**Comment by sebres** [comment]
Although I don't know what `nginx-req-limit` is (our "default" jail/filter is called `nginx-limit-req`), but...
possibly I have one advice for you: 
- the default jail `nginx-limit-req` does monitoring of an error-log (if your jail does it too);
- and if your error-log has many other messages (which are parasitic traffic in sense of fail2ban) 
- and the nginx and jail are configured "per default" (you don't have customized it e. g. like an extra log-file).
It could be high time to do such customization :)

See for example - [Best practice :: Fail2Ban :: wiki](https://github.com/fail2ban/fail2ban/wiki/Best-practice) for more info.

---

In nginx, I do it sometimes simply via own access-log and extra map and `loggable_denied` or `loggable_ddos` switch-variables. 
For example possible simplest status-related schema may look like this:
```nginx
# http-section of nginx:

# For denied extra log (nginx-denied jail of fail2ban):
log_format logdenied '$time_local denied with $status from $remote_addr "$remote_user" '
                '"$request" $body_bytes_sent '
                '"$http_referer" "$http_user_agent"';

map $status $loggable_denied { ~^40[13] 1; default 0; }

# http-, server- or location-section where you need it:

access_log /var/log/nginx/denied.log logdenied if=$loggable_denied;
```
This will produce additional log-file with messages nginx would generate for all requests ended with 401/403 status only (so mostly many times shorter as an error-log or an access-log).
And you can configure your limit-req to produce 403 for limiting requests.

And then the simplest jail for this looks like:
```ini
[nginx-denied]

enabled = true
port   = http,https
usedns = no
logpath = /var/log/nginx/denied.log tail
filter =
# exact date-pattern (if known, for v.0.10 only, matches `12/Apr/2019:13:40:15 +0200` and similar):
datepattern = ^%%d/%%b/%%ExY[ :]?%%H:%%M:%%S(?:\.%%f)?(?: %%z)?
# all dienied (403 and 401) requests, where 401 (conditional _uauth) only with username not "-":
failregex = ^\s*denied with 40(?:3|(?P<_uauth>1)) from <ADDR>(?(_uauth) "(?!-").+")
```
*\* failregex interpolation of `<ADDR>` is v.0.10 only, replace `<ADDR>` with `<HOST>` for 0.9.x.*

**Comment by sebres** [comment]
And better switch to newest fail2ban versions (which are constellation-related up-to 100 times faster as 0.9.x:).
