### ISSUE TITLE
Improved/fixed abuseipdb.conf

### ISSUE THREAD

**Issue by dominicraf** [fail2ban/fail2ban#2401]
Here is a fixed abuseipdb.conf file which works with their APIv2 and does not upload sensitive information by default. I have also updated the comments to show a complete list of categories and remove now irrelevant references. Note that APIv1 has a 'sunset date' of 2020-02-01.

I have remove the [Init] section which optionally defines abuseipdb_apikey as my experience is that this doesn't work (though I don't know why).

[abuseipdb.conf.txt](https://github.com/fail2ban/fail2ban/files/3075833/abuseipdb.conf.txt)

**Comment by IIPoliII** [comment]
By what do i remplace <ip>?

**Comment by dominicraf** [comment]
sorry an [Init] section is also required to set abuseipdb_commentsuffix to a default ZLS:
```
[Init]
abuseipdb_commentsuffix =

```

**Comment by sebres** [comment]
Thank you for your proposal.

> Here is a fixed abuseipdb.conf file which works with their APIv2 

This seems to be fixed in PR #2302 (and going merged recently).
Thus close.

However, if you want provide some updates, please rebase your changes against new version and welcome with PR (for branch >= 0.10).
