### ISSUE TITLE
Issue with a failregex, possible wrong datepattern?

### ISSUE THREAD

**Issue by gilbN** [fail2ban/fail2ban#2403]
### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

Using fail2ban 0.10.3
### The issue:

Hi! I'm having and issue with a failregex Im trying to use. 
The failregex is: 
`failregex = Failed\sLogin: .* ip=<HOST>`

The datepattern I have  tried is: 
`datepattern = %%B %%d, %%Y %%H:%%M `
`datepattern = ^%%B %%d, %%Y %%H:%%M `

#### Relevant lines from monitored log files in question:
The log looks like this
```
April 19, 2019 20:58: Failed Login: username=asdasdssaas ip=46.246.123.33
April 19, 2019 22:02: Failed Login: username=asdasdssaashgghhg ip=46.246.123.33
```

#### Observed behavior
I'm am not getting any warnings in the fail2ban.log so I guess the datepattern is correct? But its not logging any failed login attempts. 

I'm pretty new at this so I'm sure there is some stupid error somewhere :)

It is logging that the log has been modified

```
2019-04-20 00:49:03,254 fail2ban.filterpoll     [329]: DEBUG   /gitlab/application.log has been modified
```

**Comment by sebres** [comment]
I don't know what the issue currently is. The `datepattern` as well as `failregex` are valid (just the `failregex` is a bit vulnerable).
If I'm trying this with `fail2ban-regex` it works well.

Better filter would be something like:
```
fail2ban-regex -d '^%B %d, %Y %H:%M:' 'April 19, 2019 20:58: Failed Login: username=asdasdssaas ip=192.0.2.1' '^\s*Failed\sLogin: username=\S+ ip=<HOST>'
...
Lines: 1 lines, 0 ignored, 1 matched, 0 missed
```
I don't know which version of fail2ban is used, so for v.0.9 one cannot specify `datepattern` directly in jail (I think it is supported only in filter in the `[Init]` section). For fail2ban v.0.10 you can define it directly in jail (`jail.local` file).
So the filter for v.0.9 would look like this (for example `/etc/fail2ban/filter.d/my-filter.conf`):
```ini
[Definition]
failregex = ^\s*Failed\sLogin: username=\S+ ip=<HOST>

[Init]
datepattern = ^%%B %%d, %%Y %%H:%%M:
```
Then you could try it with:
```
fail2ban-regex /gitlab/application.log /etc/fail2ban/filter.d/my-filter.conf
```
