### ISSUE TITLE
Feature Request : Control  ban actions on Restore

### ISSUE THREAD

**Issue by StephenAtty** [fail2ban/fail2ban#2408]
If you stop and restart fail2ban it re-runs the ban actions and logs a "Restore Ban" into the log file.

If you are using something like abuseipdb this restart resends all the bans to abuseipdb which starts rejecting the submissions as you are making too many calls. It also seriously slows down a restart for obvious reasons.

It would be good if you could indicate if an action should happen on initial ban and restore or just on initial or restore.

**Comment by sebres** [comment]
Such option is already available - it is called `norestored` and if set would avoid processing of restored tickets after restart (see #1669).

I'll add it to `abuseipdb` action. For other action one can add it via `jail.local` like here:
```ini
[jail]
action = some-action[norestored=1]
```
or in corresponding `action.d/some-action.local`:
```ini
[Definition]
norestored = 1
```

**Comment by sebres** [comment]
closed in b318eb7e33b5a571e1354f56d0f39185960efeee

**Comment by StephenAtty** [comment]
Not sure how I missed that when I was searching around!

Thanks

**Comment by srulikuk** [comment]
I am not sure how to use it in my case will be grateful for some help
my actionban is "actionban = ipset add <ipmset> <ip> timeout <bantime> -exist && python3 /root/add2db.py -j <name> -pr <protocol> -p <port> -i <ip>"
after the ban I am passing the params to a python script to add to a DB (so I can share the IP's between all my servers).

On restore I dont want to execute the python script as I don't want to add it to the DB again.
Where should I place the "norestore" option in this case?

**Comment by StephenAtty** [comment]
Its in the doc for the change:

https://github.com/fail2ban/fail2ban/commit/b318eb7e33b5a571e1354f56d0f39185960efeee


```
[Definition]

# bypass action for restored tickets
norestored = 1
```

**Comment by srulikuk** [comment]
yes, but that will skip all actions no? I have 2 actions in actionban and on restore i only want to run the first

**Comment by srulikuk** [comment]
Ok, i figured it out, for anyone else that might need this 
BEFORE:
`actionban = ipset add timeout -exist && python3 /root/add2db.py -j name -pr protocol -p port -i ip`
AFTER:
`actionban = ipset add <ipmset> <ip> timeout <bantime> -exist &&
            if [ '<restored>' = '0' ]; then
              python3 /root/add2db.py -j <name> -pr <protocol> -p <port> -i <ip>
            fi`
Whatever is in the IF statement will only get executed if the condition is true (in this case if the ban is NOT a restore)
