### ISSUE TITLE
Is the maillatency option available in stable branch?

### ISSUE THREAD

**Issue by laczik** [fail2ban/fail2ban#2413]
I would like to use the maillatency option with fail2ban.noarch 0.9.6-1.el6.1 (CentOS 6) - is it available? (See post below by @sebres from years ago.) If not, where can I find the source for it to create a patch?
Thanks,
John

_Originally posted by @sebres in https://github.com/fail2ban/fail2ban/issues/832#issuecomment-60483697_

If you question was "How we can stop sending _too many_ notification emails from fail2ban?":
It is possible with adding a latency for send a mail, grouping all of bans inside this latency.
I have a private branch doing that, but written relative #716, and will this disclose for fail2ban community after #716 is in master and I'm ready within.
Scenario I have realized, configured `maillatency = 5m 15m`:
- after each ban, it will be added to the report, resets a timer for send email again to 5 minutes;
- if no more bans occurred inside a last 5 minutes, email will be send; but at the latest 15 minutes after last sending.

So, it sends a mail with report within interval 5 to 15 minutes;
Rare sending will be if it configured `maillatency = 30m 12h`:
Sends a report after last ban after 30 minutes (if no more bans within this time) or since last sending a 12 hours are gone;

**Comment by sebres** [comment]
Shortly: no, there is still no such option at the moment in public versions of fail2ban.
Just no time to rebase it to major versions (too many dependencies as well as tasks with higher precedence). And then it will be rather a feature of 0.11th version.

But let us avoid duplicates (please use #832 for further discussions), thus closed.
