### ISSUE TITLE
Slow startup with huge filter list

### ISSUE THREAD

**Issue by tokudan** [fail2ban/fail2ban#2416]
### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): 0.9.7
- OS, including release name/version: Red Hat Enterprise Linux Server release 7.6
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

I'm using fail2ban 0.9.7-1 (from RedHat EPEL) to protect my samba server from some known ransomware by filtering for known ransomware files.
With a small filter list (~130 entries), startup time is below one second.
With a big filter list (~2400 entries), the startup time is about 10 minutes instead of a couple of seconds.
The scale seems to be non-linear here, assuming that 130 entries take one second, 2400 entries should be done within about 20 seconds, yet it takes about 10 minutes to process the 2400 entries.

#### Steps to reproduce

Use the "samba.local huge" from https://gist.github.com/tokudan/6223c2abca6f530c80477d5b4b291fdb as /etc/fail2ban/filters.d/samba.local, together with the jail config listed below.

#### Expected behavior

Startup of fail2ban within a couple of seconds

#### Observed behavior

Startup takes about 10 minutes, with the fail2ban-server process only using about 4% CPU time, while the fail2ban-client uses about 95 - 96% during these 10 minutes.
Having a short filter list works perfectly fine and fail2ban starts fine without any notable delay with about 128 filters.
Once the filter list grows, there is a very noticable delay in startup. Fail2ban needs about 10 minutes to start with ~2400 entries:
Mai 03 19:12:11 myserver.example.com fail2ban.actions[21378]: INFO Set banTime = 86400
Mai 03 19:21:59 myserver.example.com fail2ban.filtersystemd[21378]: INFO Added journal match for: '_SYSTEMD_UNIT=smb.service _COMM=smbd SYSLOG_IDENTIFIER=smbd_audit'

With log level DEBUG I can watch that fail2ban starts adding about 82 filters per second and then slowing down to about 1 to 2 filters per second around the 2100 mark.

#### Any customizations done to /etc/fail2ban/ configuration
I've uploaded the small and huge filter lists in a gist, as they are too long to be included in this issue: https://gist.github.com/tokudan/6223c2abca6f530c80477d5b4b291fdb
```
# cat /etc/fail2ban/jail.d/samba.local
[samba]
enabled = true
filter = samba
backend = systemd
action = iptables-multiport[name=samba, port="135,139,445,137,138", protocol=tcp]
         mail[name=samba, dest=root]
maxretry = 1
findtime = 600
bantime = 86400
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
Mai 06 13:36:25 myserver.example.com fail2ban.actions[7289]: INFO Set banTime = 86400
Mai 06 13:36:25 myserver.example.com fail2ban.transmitter[7289]: DEBUG Command: ['set', 'samba', 'addfailregex', 'IP=<HOST>\\|.*\\.verasto']
Mai 06 13:36:25 myserver.example.com fail2ban.transmitter[7289]: DEBUG Command: ['set', 'samba', 'addfailregex', 'IP=<HOST>\\|.*\\.moresa\\!Ransom']
Mai 06 13:36:25 myserver.example.com fail2ban.transmitter[7289]: DEBUG Command: ['set', 'samba', 'addfailregex', 'IP=<HOST>\\|READ_ME\\.cube']
Mai 06 13:36:25 myserver.example.com fail2ban.transmitter[7289]: DEBUG Command: ['set', 'samba', 'addfailregex', 'IP=<HOST>\\|.*\\.COLORIT\\!Ransom']
Mai 06 13:36:25 myserver.example.com fail2ban.transmitter[7289]: DEBUG Command: ['set', 'samba', 'addfailregex', 'IP=<HOST>\\|.*\\.sambo,']
[severall hundred lines omitted]
Mai 06 13:46:10 myserver.example.com fail2ban.transmitter[7289]: DEBUG Command: ['set', 'samba', 'addfailregex', 'IP=<HOST>\\|.*\\.Silent']
Mai 06 13:46:10 myserver.example.com fail2ban.transmitter[7289]: DEBUG Command: ['set', 'samba', 'addfailregex', 'IP=<HOST>\\|.*\\.RSNSlocked']
Mai 06 13:46:11 myserver.example.com fail2ban.transmitter[7289]: DEBUG Command: ['set', 'samba', 'addfailregex', 'IP=<HOST>\\|.*\\.RAD']
Mai 06 13:46:12 myserver.example.com fail2ban.transmitter[7289]: DEBUG Command: ['set', 'samba', 'addfailregex', 'IP=<HOST>\\|.*\\.porno']
Mai 06 13:46:12 myserver.example.com fail2ban.transmitter[7289]: DEBUG Command: ['set', 'samba', 'addfailregex', 'IP=<HOST>\\|.*\\.pornoransom']
Mai 06 13:46:13 myserver.example.com fail2ban.transmitter[7289]: DEBUG Command: ['set', 'samba', 'addfailregex', 'IP=<HOST>\\|.*\\.odcodc']
Mai 06 13:46:14 myserver.example.com fail2ban.transmitter[7289]: DEBUG Command: ['set', 'samba', 'addfailregex', 'IP=<HOST>\\|_ryp']
Mai 06 13:46:14 myserver.example.com fail2ban.transmitter[7289]: DEBUG Command: ['set', 'samba', 'addfailregex', 'IP=<HOST>\\|.*\\.helpdecrypt\\@ukr.*\\.net']
Mai 06 13:46:15 myserver.example.com fail2ban.transmitter[7289]: DEBUG Command: ['set', 'samba', 'addfailregex', 'IP=<HOST>\\|.*\\.only\\-we_can\\-help_you']
Mai 06 13:46:16 myserver.example.com fail2ban.transmitter[7289]: DEBUG Command: ['set', 'samba', 'addfailregex', 'IP=<HOST>\\|.*\\.cryp1']
Mai 06 13:46:17 myserver.example.com fail2ban.transmitter[7289]: DEBUG Command: ['set', 'samba', 'addfailregex', 'IP=<HOST>\\|.*\\.fileiscryptedhard']
Mai 06 13:46:17 myserver.example.com fail2ban.transmitter[7289]: DEBUG Command: ['set', 'samba', 'addfailregex', 'IP=<HOST>\\|.*\\.blocatto']
Mai 06 13:46:18 myserver.example.com fail2ban.transmitter[7289]: DEBUG Command: ['set', 'samba', 'addfailregex', 'IP=<HOST>\\|.*\\.8lock8']
Mai 06 13:46:19 myserver.example.com fail2ban.transmitter[7289]: DEBUG Command: ['set', 'samba', 'addfailregex', 'IP=<HOST>\\|.*\\.777']
```
The messages are just the regular start/stop messages in DEBUG mode.

#### Relevant lines from monitored log files in question:
Filtering/banning works fine without any delays, so I guess this is not relevant.

**Comment by sebres** [comment]
> The scale seems to be non-linear here, assuming that 130 entries take one second, 2400 entries should be done within about 20 seconds, yet it takes about 10 minutes to process the 2400 entries.

How it could be? 
Let us assume:
- the number of configured `failregex` is `FRn`';
- number of messages in log that would match is `Mm`;
- number of messages in log that would not match at all is `Mnm`

then the time you should "calculate" will be something like:
```
O(FRn, Mm, Mnm) = Mm * SomeAverageTimeMatchedReIsFound(FRn) + Mnm * TimeToCheckAllRe(FRn)
```
which is clearly not linear considering `O(FRn)` only.

Please see [Best practice :: fail2ban wiki](https://github.com/fail2ban/fail2ban/wiki/Best-practice) for more info - shortly: for each parasite message (message that does not match), fail2ban would try to check whether it matches any failregex.

Additionally your failregex's are weird and "vulnerable", because not anchored, contain catch-all's etc. This would make it more slower (and as said above multiplied by number of RE) .

You did not provide any example (how the failure looks in log), so I cannot recommend you better variant for an regex.
Just as possible example how you can "combine" multiple RE's it to single RE, take a look in your gist - https://gist.github.com/tokudan/6223c2abca6f530c80477d5b4b291fdb#gistcomment-2909550.

Additionally 0.9.x is outdated (and also too slow), there is already v.0.10, which is faster and where at least you could use some features to improve your filter (like `prefregex` for common part of regex etc).

**Comment by tokudan** [comment]
@sebres The slowness is just about the startup time of fail2ban. I would have assumed that the speed at which fail2ban reads in and compiles the regular expressions does not go down with the number of regular expressions, as it just has to compile each regular expression and add them to the list.
I don't see where the number of messages in the log are relevant for the startup phase of a jail.

The matching (or non-matching) seems to be perfectly fine and actually works fast.
I'll see if I can work around this by changing the script that generates the regular expressions from glob pattern matching to generate one big regular expression and improve them.

**Comment by sebres** [comment]
Yes, you are right (as regards the init-time).
I got it now (noticed now the debug output).

I'm sure, this behavior is changed in 0.10 - all regex's are supplied as a single array (`multi-set`) now and should not grow the initialization time non-linearly.
Anyway with latest 0.10 it takes almost 1 second in my test environment with your original (huge) filter.

> The matching (or non-matching) seems to be perfectly fine and actually works fast.

Hmm... It could be fine - though if I were you, I would not use this as it is currently designed anyway (for above-mentioned reasons).
