### ISSUE TITLE
Issue with nginx-noscript

### ISSUE THREAD

**Issue by cyberghostbg** [fail2ban/fail2ban#2417]
Hi, i installed fail2ban and added nginx-noscript, but i have a problem.
When I browse my site I or another person gets a ban, why not. Uses the default regex and I do not know where the problem is.
Is there a way to make it work only for non-existent files? That is, not to block pages that actually exist?

**Comment by sebres** [comment]
> Hi, i installed fail2ban and added nginx-noscript, but i have a problem.

There is no such "official" filter `nginx-noscript` in our repository.

> Is there a way to make it work only for non-existent files? That is, not to block pages that actually exist?

Yes, somewhere in your failregex you have to extend it with `404`.
But you should be sure, that no one regular page of you does not use some "broken" reference (to image or scripts matching from your regex), so no 404 would be generated there.

Dunno what exactly you're using, but you should do something like this:
```diff
-^<HOST> - \S+ \[\] "(?:[A-Z]+) /[^"]+(?:\.(?:php|asp|exe|pl|cgi|scgi)) \S+"
+^<HOST> - \S+ \[\] "(?:[A-Z]+) /[^"]+(?:\.(?:php|asp|exe|pl|cgi|scgi)) \S+" 404\b
```
Or see similar issues like https://github.com/fail2ban/fail2ban/issues/2159#issuecomment-399079118

Another possibility would be to disable access-log in nginx for locations with scripts that you really have (no log - no failure).

**Comment by cyberghostbg** [comment]
Im use this:

[Definition]

failregex = ^<HOST> -.*GET.*(\.php|\.asp|\.exe|\.pl|\.cgi|\.scgi)

ignoreregex =

but some peoples get ban for nothing and im just want to ban only for non-existent files
