### ISSUE TITLE
UFW and possible fail2ban issue (need help to debug)

### ISSUE THREAD

**Issue by techexo** [fail2ban/fail2ban#2418]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): 0.10.2-2
- OS, including release name/version: Debian Stretch
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

Hi everyone,

This is not (yet) so much an issue with fail2ban, but a call for help to know how to be sure it's not fail2ban :pray:. I have on my dedicated server installed fail2ban with UFW backend. Beside, I block all incoming and outgoing traffic by default, and only allow in or out what's of interest for me.

Here's the core of the issue: more or less regularly, I am losing some of the `ALLOW OUT` rules in UFW, causing my server to loose its ability to send mails, reach DNS etc. I don't understand why it only occurs with some of the rules or the periodicity of it... The only service tinkering with UFW rules on a regular basis is fail2ban on my server, and I would like to be absolutely sure it's not coming from it!

What possible way do I have to identify the origin of these rules disappearing? Thank you very much for your help :smiley:

**Comment by sebres** [comment]
>  I am losing some of the ALLOW OUT rules in UFW
> ...
> and I would like to be absolutely sure it's not coming from it!

How it can be if the only one command in ufw-action (deleting rules) looks like below:
https://github.com/fail2ban/fail2ban/blob/7ae0ef24082a118b7addcfb9907281b24ff1081c/config/action.d/ufw.conf#L20

In my opinion it is simply impossible, unless `blocktype` is not `ALLOW OUT` (which would be a nonsense, despite other arguments identifying the rule)... or even ufw self has some issues like race condition or something similar. 
Thus closed, please reopen if I'm wrong.
