### ISSUE TITLE
Always warning: "fail2ban.service changed on disk..." on boot

### ISSUE THREAD

**Issue by rieje** [fail2ban/fail2ban#2421]
On every boot, `sudo systemctl status fail2ban.service` shows:
```

May 11 22:04:20 epsi systemd[1]: Starting Fail2Ban Service...
May 11 22:04:22 epsi fail2ban-client[493]: 2019-05-11 22:04:22,741 fail2ban.server         [507]: INFO    Starting Fail2ban v0.9.6
May 11 22:04:22 epsi fail2ban-client[493]: 2019-05-11 22:04:22,741 fail2ban.server         [507]: INFO    Starting in daemon mode
May 11 22:04:23 epsi systemd[1]: Started Fail2Ban Service.
Warning: fail2ban.service changed on disk. Run 'systemctl daemon-reload' to reload units.

```
`systemctl daemon-reload` will then remove that warning, until I reboot the system. I did a lot of trial and error and it appears the the culprit is using a systemd drop-in file. The contents of the file /etc/systemd/system/fail2ban.service.d/override.conf based [here](https://wiki.archlinux.org/index.php/Systemd#Drop-in_files):

```
[Service]
PrivateDevices=yes
PrivateTmp=yes
ProtectHome=read-only
ProtectSystem=strict
NoNewPrivileges=yes
ReadWritePaths=-/var/run/fail2ban
ReadWritePaths=-/var/lib/fail2ban
ReadWritePaths=-/var/log/fail2ban
CapabilityBoundingSet=CAP_AUDIT_READ CAP_DAC_READ_SEARCH CAP_NET_ADMIN CAP_NET_RAW
```
Even when I comment the entire `override.conf` by prepending each line with `#`, do a `systemctl daemon-reload`, then restart the system, the warning still occurs. I don't understand why the warning only appears after I start the system and disappears after a `systemctl daemon-reload` until the next reboot.

I'm on Raspbian on fail2ban version 0.9.6-2 (latest version).

**Comment by sebres** [comment]
This has basically nothing with fail2ban... 

There are several other services causing the issue on rPi, for example see [I have to manually run systemctl daemon-reload everytime my rPi reboots](https://forums.plex.tv/t/i-have-to-manually-run-systemctl-daemon-reload-everytime-my-rpi-reboots/229775) or [Run 'systemctl daemon-reload' to reload units - Raspberry Pi Forums](https://www.raspberrypi.org/forums/viewtopic.php?t=219025).

Seems to be a bug or some misconfiguration of raspbian (or an issue of SD-card / mount system)...

**Comment by rieje** [comment]
It should be harmless and fail2ban is running properly as expected given the `Started Fail2Ban Service` line, right? Have yet to find any solution or even discussion regarding the issue with Raspbian and/or systemd other than the links you've mentioned, though the issue seems to be quite specific.
