### ISSUE TITLE
How can I install fail2ban version 0.10 in centos 6? This package is not available in EPEL, only 0.9.6 version.

### ISSUE THREAD

**Issue by komatsu002** [fail2ban/fail2ban#2422]
_We will be very grateful, if your problem was described as completely as possible,
enclosing excerpts from logs (if possible within DEBUG mode, if no errors evident
within INFO mode), and configuration in particular of effected relevant settings
(e.g., with ` fail2ban-client -d | grep 'affected-jail-name' ` for a particular
jail troubleshooting).
Thank you in advance for the details, because such issues like "It does not work" 
alone could not help to resolve anything!
Thanks! (remove this paragraph and other comments upon reading)_

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 
- [x] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

_Summary here_

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
If you are familiar with manual installation you can install the github version.
If not - wait for release or try to find a repository for your distribution or to seek help by your maintainers.
There are also forums like StackOverflow, ServerFault etc, which could help you.

**Comment by sebres** [comment]
BTW, Here is a similar issue #1621 with small howto (fail2ban 0.10 from github on CentOS5.6).
And this [google search](https://www.google.com/search?q=%22centos+6%22+%22fail2ban+0.10%22) would navigate you to some YUM-repositories with repackaged 0.10 version for CentOS 6.
