### ISSUE TITLE
Fail2ban does not backlist the client which attempts to send email to the user which does not exist

### ISSUE THREAD

**Issue by dmak** [fail2ban/fail2ban#2426]
### Environment

- Fail2Ban version: 0.10.2-2.1
- OS: Debian buster
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase

### The issue

Fail2ban does not backlist the client which attempts to send email to several non-existing users, e.g. resulting the log lines like this:

```
May 13 15:45:46 server postfix/smtpd[13844]: 00ADB3C0899: reject: RCPT from mail-serv.info[185.222.211.30]: 550 5.1.1 <sales@server.com>: Recipient address rejected: User unknown in local recipient table; from=<poy5hkbxow0mle7u@ukon34.ru> to=<sales@server.com> proto=ESMTP helo=<mail-serv.info>
```

### Possible solution

The solution was posted [here](https://github.com/fail2ban/fail2ban/issues/1078#issuecomment-116371920) and similar is [here](https://github.com/fail2ban/fail2ban/issues/322#issuecomment-22832309).

```
--- /etc/fail2ban/filter.d/postfix.conf.orig   2018-01-18 14:49:01.000000000 +0100
+++ /etc/fail2ban/filter.d/postfix.conf        2019-05-13 23:34:15.750013949 +0200
@@ -20,7 +20,7 @@
             ^RCPT from [^[]*\[<HOST>\]%(_port)s: 45[04] 4\.7\.1 (?:Service unavailable\b|Client host rejected: cannot find your (reverse )?hostname\b)
             ^RCPT from [^[]*\[<HOST>\]%(_port)s: 450 4\.7\.1 (<[^>]*>)?: Helo command rejected: Host not found\b
             ^EHLO from [^[]*\[<HOST>\]%(_port)s: 504 5\.5\.2 (<[^>]*>)?: Helo command rejected: need fully-qualified hostname\b
-            ^VRFY from [^[]*\[<HOST>\]%(_port)s: 550 5\.1\.1\s
+            ^(RCPT|VRFY) from [^[]*\[<HOST>\]%(_port)s: 550 5\.1\.1\s
             ^RCPT from [^[]*\[<HOST>\]%(_port)s: 450 4\.1\.8 (<[^>]*>)?: Sender address rejected: Domain not found\b
             ^from [^[]*\[<HOST>\]%(_port)s:?
```

**Comment by sebres** [comment]
I don't like it as default regex in normal mode (because it is not really an authentication issue), but this filter contains another 5.1.1 rule already several years, so I dot't see any reason why not accept it with another "flag" RCPT too.

BTW, your changes seems to be insufficient (because of some session-id `00ADB3C0899` instead of `NOQUEUE`), see the diff in 0426a24719c13e795d3cf8b68eaea20d2723b41f.

Thus fixed. Thx!
