### ISSUE TITLE
Question: How does 'dbpurgeage' exactly work in v. 0.11 (latest github)?

### ISSUE THREAD

**Issue by quicktrick** [fail2ban/fail2ban#2428]
E.g., I set in my /usr/local/etc/fail2ban/fail2ban.local (FreeBSD):
```
dbpurgeage = 1mo
```
and in my /usr/local/etc/fail2ban/jail.local:
```
[DEFAULT]
banaction = pf[actiontype=<multiport>]
findtime  = 30m
maxretry = 3
bantime = 1d
bantime.increment = true
bantime.rndtime = 12h
bantime.maxtime = 6mo
bantime.factor = 1
```
What will be after an `Unban` action?  Will the previously banned IP be purged from `/var/db/fail2ban/fail2ban.sqlite3` in just `1mo`, or maybe in `3*last_bantime + 1mo` (as it is said [here](https://habr.com/ru/post/238303/))?

**Comment by sebres** [comment]
> in just 1mo, or maybe in 3*last_bantime + 1mo 

Well fail2ban v.0.11 has 2 tables one for "active" or rather last bans (which will be purged if end of ban is older as `dbpurgeage`)... The formula is:
`(timeofban + bantime) < (now - purgeAge)`
And still another table which contains bad (recidive) IPs, where it will be purged later (considering triple bantime), so corresponding this formula: 
`(timeofban + (bantime * outdateFactor)) < (now - purgeAge)`.
Currently the outdateFactor is 3 (and not yet configurable).
