### ISSUE TITLE
jail.conf vs jail.local configuration

### ISSUE THREAD

**Issue by keramaisa** [fail2ban/fail2ban#2430]
Hi :) I just have a question, it is not an issue.
If let's say I won't copy the content of jail.conf to my jail.local, and leave jail.local empty and after add there my desired configuration, would the rest will be taken from jail.conf? Exactly what I mean if in my ssh service in `jail.local` I will only add that:
``` 
[ssh]
port= 23224
```
Will that be "added" to default conf of `jail.conf`? Or being more exact replaced with the section `port` in the default `jail.conf` on my from `jail.local`?

That was an example, but what bothers me if in the end if I will have my `jail.local` file with things I only want to change )and without copied jail.conf into jail.local) would my configs would be added and in case they already exists in `jail.conf` replaced?

Thank you so much in advance for any help

**Comment by sebres** [comment]
> I won't copy the content of jail.conf to my jail.local

You shouldn't copy. This is definitely a bad practice, take a look in our [wiki](https://github.com/fail2ban/fail2ban/wiki/Proper-fail2ban-configuration) (answer for first question).

> would the rest will be taken from jail.conf? 

Yes. Local overwrites the values section related and replacement would take place before the whole (merged) file content going interpolated (single values going substituted).

> Will that be "added" to default conf of jail.conf?

It will replace the value.
If you will add it, you should use `%(known/param)s` (static/config time) or `<known/param>` (dynamic run-time or conditional) substitution for an amendment like that, so if you'd write:
```ini
[sshd]
port = %(known/port)s 23224
```
it would do the job. (Also note, our standard jail is called `sshd` not `ssh`)

No idea which fail2ban version do you use, this feature was introduced somewhere in 0.9.3 or so...
Just try `fail2ban-client -d | grep ssh` to check or see your real values that would be submitted to the server got replaced (or amended).
