### ISSUE TITLE
Backend systemd can't be activated with issue "requires systemd >= 204"

### ISSUE THREAD

**Issue by guillaumefenollar** [fail2ban/fail2ban#2436]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): v0.9.6
- OS, including release name/version: Debian 9.9 - kernel 4.9.0
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

With following systemd version :
```
# systemd --version
systemd 232
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```
I'm trying to create a jail with systemd backend but the jail is not activated at fail2ban startup with following errors in logs : 
```
INFO    Creating new jail 'nginx-wordpress'
ERROR   Backend 'systemd' failed to initialize due to Fail2Ban requires systemd >= 204
ERROR   Failed to initialize any backend for Jail 'nginx-wordpress'
WARNING Command ['add', 'nginx-wordpress', 'systemd'] has failed. Received RuntimeError("Failed to initialize any backend for Jail 'nginx-wordpress'",)
```

#### Steps to reproduce

Here's my jail drop-in:
```
[nginx-wordpress]
enabled = true
backend = systemd
action = route
```
Installed journal and systemd python libraries thanks to pip. Before this issue, I had the error that these libraries were missing. This was fixed with proper installation.

If I try using 'auto', backend fallback to 'pyinotify', which is not wanted (all my logs are going to systemd-journal.

BTW thanks for this brilliant piece of software :)

**Comment by sebres** [comment]
What would you see calling this:
```
python -c 'from systemd import journal; print(getattr(journal, "__version__", "0"))'
```
**Important:** you should execute it with the python for which fail2ban was installed (so if it is 3.x you should use python3 instead).
To check the version is proper, try following:
```
python -c 'import fail2ban.server.filtersystemd'
python3 -c 'import fail2ban.server.filtersystemd'
```
An error "ImportError: No module ..." signaling wrong python version.

> Installed systemd python libraries thanks to pip

Hmm... why via pip, if your distribution does already have this packets for [py2.x](https://packages.debian.org/en/stretch/python-systemd) and [py3.x](https://packages.debian.org/en/stretch/python3-systemd)? Both with version 233-1 if I'm not wrong.
So why just not `?sudo? apt-get install python-systemd`?

I'm pretty sure it simply wrong (or may be outdated systemd-packet) which got installed using pip.
Thus closed. Please reopen if a reinstall using apt would not help.
