### ISSUE TITLE
getHostname(fqdn=True) returning wrong FQDN

### ISSUE THREAD

**Issue by raubv0gel** [fail2ban/fail2ban#2438]
### Environment:

- Fail2Ban version: Fail2Ban v0.10.4
- OS version: Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-50-generic x86_64)
- Python version: 3.6.7
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

`<fq-hostname>` returns `ip6-localhost` instead of `sub.domain.tld` while `hostname -f` doing it right. The issue seems to be located in [ipdns.py#L135](https://github.com/fail2ban/fail2ban/blob/ca49f2c71cad38ebb8c96deeba050a98ad5b7ae4/fail2ban/server/ipdns.py#L135)
```
(socket.getfqdn, socket.gethostname) if fqdn else (socket.gethostname, socket.getfqdn)
```

You can test it by doing
```
python3 -c 'from fail2ban.server.ipdns import DNSUtils; print("fq: %s, sh: %s" % (DNSUtils.getHostname(fqdn=True), DNSUtils.getHostname(fqdn=False)))'
```
which returns `fq: ip6-localhost, sh: mail`.

If I do
```
 python3 -c 'from fail2ban.server.ipdns import DNSUtils, socket; print(socket.getfqdn())'
```
The Python function `socket.getfqdn` returns `ip6-localhost`. It seems to be an issue with this Python function.

#### Steps to reproduce

`
python3 -c 'from fail2ban.server.ipdns import DNSUtils; print("fq: %s, sh: %s" % (DNSUtils.getHostname(fqdn=True), DNSUtils.getHostname(fqdn=False)))'
`

#### Expected behavior

`<fq-hostname>` should return `sub.domain.tld` like `hostname -f`.

#### Observed behavior

`<fq-hostname>` returns `ip6-localhost`.

### Configuration, dump and another helpful excerpts

My host `/etc/hosts` contains
```
# nameserver config
# IPv4
127.0.0.1 localhost
127.0.0.1 mail.domain.tld mail
127.0.0.1 domain.tld
#
# IPv6
::1     ip6-localhost ip6-loopback
::1     mail.domain.tld mail
::1     domain.tld
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
```

**Comment by sebres** [comment]
Related [python issue](https://bugs.python.org/issue5004).

I saw it never on real machines.
This works also fine on my side (tested on several hosts with IPv6, different distributions):
```
$ python3 -c 'import socket; print(socket.getfqdn())
srv.domain.tld
```

>\# IPv6
>::1     ip6-localhost ip6-loopback

May be something like this would change the behavior (basically the `localhost` is always part of first entry on all hosts I checked):
``` 
::1     localhost ip6-localhost ip6-loopback
```

Do you have yet another IPs as the loopback-IPs? Or they are dynamical (retrieved via dhcp)?

**Comment by sebres** [comment]
And what is the defined (short) name of host (what exactly contains `/etc/hostname`)?

**Comment by raubv0gel** [comment]
Changed part of `/etc/hosts` to 
```
# IPv6
::1     localhost ip6-localhost ip6-loopback
```
After, `python3 -c 'import socket; print(socket.getfqdn())` outputs `localhost`. So it does not work either.

`ipconfig` returns
```
enp0s31f6: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 144.76.XXX.XXX  netmask 255.255.255.255  broadcast 0.0.0.0
        inet6 2a01:XXX:XXX:XXXX::2  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::XXXX:XXX:XXX:311c  prefixlen 64  scopeid 0x20<link>
        ether 90:1b:XX:XX:XX:1c  txqueuelen 1000  (Ethernet)
        RX packets 754812  bytes 111657461 (111.6 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1062390  bytes 808213294 (808.2 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 16  memory 0xef200000-ef220000

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 432244  bytes 233666216 (233.6 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 432244  bytes 233666216 (233.6 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 10.8.0.1  netmask 255.255.255.255  destination 10.8.0.2
        inet6 fe80::4738:54cd:668:b6f8  prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 100  (UNSPEC)
        RX packets 405  bytes 60725 (60.7 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 437  bytes 279637 (279.6 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

DHCP is not installed.

``/etc/hostname`` contains ``mail``.

Really weird issue …

**Comment by raubv0gel** [comment]
Another project had the same [issue](https://github.com/borgbackup/borg/pull/3484/commits/9b0d0f3127289fc3bbe620e8adce8038ed594e9f#diff-4b53f84e19a3bb376bf2202371ed269aR189-R206) and fixed it with:
```python
import socket

# patched socket.getfqdn() - see https://bugs.python.org/issue5004
def getfqdn(name=''):
    """Get fully qualified domain name from name.
    An empty argument is interpreted as meaning the local host.
    """
    name = name.strip()
    if not name or name == '0.0.0.0':
        name = socket.gethostname()
    try:
        addrs = socket.getaddrinfo(name, None, 0, socket.SOCK_DGRAM, 0, socket.AI_CANONNAME)
    except socket.error:
        pass
    else:
        for addr in addrs:
            if addr[3]:
                name = addr[3]
                break
    return name


# for performance reasons, only determine hostname / fqdn / hostid once.
# XXX this sometimes requires live internet access for issuing a DNS query in the background.
hostname = socket.gethostname()
fqdn = getfqdn(hostname)

print(hostname)
print(fqdn)
```
Works on my system!

**Comment by raubv0gel** [comment]
`python3 -c 'import socket; print(socket.getfqdn(socket.gethostname()))'` returns `localhost` (do not forget: I changed the `/etc/hosts` according to `localhost` and IPv6).

**Comment by sebres** [comment]
Hmm... 
So `socket.gethostname()` also returns `localhost` to you?!

**Comment by raubv0gel** [comment]
`python3 -c 'import socket; print(socket.gethostname())'` returns `mail` which is right (same as in `/etc/hostname`). `socket.getfqdn(…)` returns wrong.

**Comment by raubv0gel** [comment]
As you notice and linked above, the issue up to Python. It’s not fail2ban’s bad, I believe.

**Comment by sebres** [comment]
Weird. I don't even think it is really an issue of python.
Just it looks like a local resolve (of unix domain name) is preferred for some reasons on your system before the primary DNS/resolver.
May be some speedup rule (like prefer loopback) in dns cache or something similar is involved here.

Oh, wait... How it looks with this?
```python
socket.getnameinfo((socket.gethostname(), 0), socket.AI_CANONNAME)[0]
```

**Comment by raubv0gel** [comment]
`python3 -c 'import socket; print(socket.getnameinfo((socket.gethostname(), 0), socket.AI_CANONNAME)[0])'` failed
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by raubv0gel** [comment]
> Just it looks like a local resolve (of unix domain name) is preferred for some reasons on your system before the primary DNS/resolver.
May be some speedup rule (like prefer loopback) in dns cache or something similar is involved here.

Do you know any Ubuntu/Linux commands to test it?

**Comment by sebres** [comment]
Oh, right - python3 does not allow host name there (only IP), can you try it with `python2` please?

**Comment by raubv0gel** [comment]
```
python2 -c 'import socket; print(socket.getnameinfo((socket.gethostname(), 0), socket.AI_CANONNAME)[0])'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.error: sockaddr resolved to multiple addresses
```
Oh! `sockaddr resolved to multiple addresses` seems to interesting, right?

**Comment by sebres** [comment]
I hope it is fixed now in feba50e3c2c18868303968917640b66ae0561221.
Can you please test it on your system (test-suite only, as portable temp without installation):
```bash
mkdir /tmp/f2b-test && cd /tmp/f2b-test
wget https://github.com/sebres/fail2ban/archive/0.10.zip
unzip 0.10.zip
cd fail2ban-0.10
# for 3.x:
./fail2ban-2to3
python3 bin/fail2ban-testcases -vv DNSUtilsNetworkTests
# for 2.x:
python2 bin/fail2ban-testcases -vv DNSUtilsNetworkTests
```
Especially interesting is this one (affected by the fix):
```
...
testFQDN (fail2ban.tests.filtertestcase.DNSUtilsNetworkTests) ... ok
...
----------------------------------------------------------------------
Ran 16 tests in 0.373s

OK
```
And of course you can test the FQDN for your server is correct:
```
PYTHONPATH=. python3 -c 'from fail2ban.server.ipdns import DNSUtils; print(DNSUtils.getHostname(fqdn=1))'
```

If it would work for you, I'll merge it to all upstream branches.

**Comment by raubv0gel** [comment]
@sebres, nice one! It work’s for me. Many thanks!

**Comment by sebres** [comment]
Thank you.
Merged in 0.10/0.11.

**Comment by xoroz** [comment]
Hello everyone,
I have ubuntu20 with ipv6 disabled and fail2ban version 0.11.1-1 and I have the issue above.


root@ubuntu20template:~# python3 -c 'import socket; print(socket.gethostname())'
ubuntu20template

root@ubuntu20template:~# python3 -c 'import socket; print(socket.getfqdn())'
localhost

Any change we could have the variable <hostname> and <fq-hostname>
As is I am unable to change how the variables are created.
thank you

**Comment by sebres** [comment]
See https://github.com/fail2ban/fail2ban/issues/1859#issuecomment-648045955.

Also note that gethostname returns short hostname in your sub-net, whereas getfqdn must return a fully-qualified domain name up to TLD.
