### ISSUE TITLE
Please help me to create filter for jira(tomcat)

### ISSUE THREAD

**Issue by vsevlo** [fail2ban/fail2ban#2441]
### OS SUSE 15, file2ban 0.10.3.fix1
i have jira-security log:

```
2019-06-06 14:30:07,393 http-nio-8080-exec-26 anonymous 870x758x1 - \100.100.100.100,127.0.0.1 /login.jsp The user 'test' is required to answer a CAPTCHA elevated security check.  Failure count equals 35
2019-06-06 14:30:20,918 http-nio-8080-exec-22 anonymous 870x763x1 c6k98a \100.100.100.100,127.0.0.1 /login.jsp The user 'test' is required to answer a CAPTCHA elevated security check.  Failure count equals 36
2019-06-06 14:30:33,213 http-nio-8080-exec-6 anonymous 870x768x1 c6k98a \100.100.100.100,127.0.0.1 /login.jsp login : 'test' tried to login but they do not have USE permission or weren't found. Deleting remember me cookie.
2019-06-06 14:30:33,218 http-nio-8080-exec-6 anonymous 870x768x1 c6k98a \100.100.100.100,127.0.0.1 /login.jsp The user 'test' has FAILED authentication.  Failure count equals 37
```
### jail for jira:
```ini
[INCLUDES]
before = paths-opensuse.conf

[jira]
ignoreip = 127.0.0.1/8
ignorecommand =
bantime  = 60h
findtime  = 1m
logpath = /opt/jira-home/log/atlassian-jira-security.log
maxretry = 5
usedns = warn
logencoding = auto
enabled = true
mode = normal
filter = jira
protocol = tcp
chain = <known/chain>
port = http,https
fail2ban_agent = Fail2Ban/%(fail2ban_version)s
banaction = iptables-multiport
banaction_allports = iptables-allports
action_ = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
action = %(action_)s
```
### Filter jira.conf:
```ini
[Definition]
failregex =  HOST Failure count equals
 
ignoreregex =
```

But failregex not work, i try use `^.+?((?:\d+\.){3}\d+) \b(\w*FAILED authentication\w*)\b`, too not work. Please help me creat working failregex for my log.

**Comment by sebres** [comment]
Your log excerpt seems to contain 2 IPs in failure messages (100.100.100.100 and 127.0.0.1).
I suppose the intruders IP is 100.100.100.100, then:
```ini
failregex = ^\s+(?:\S+\s+){4}\\<HOST>.*Failure count equals \d+$
```
I don't think the backslash within message is correct (I never saw this in tomcat logs...), if it is not - simply remove `\\` before `<HOST>`.
```ini
failregex = ^\s+(?:\S+\s+){4}<HOST>.*Failure count equals \d+$
```
If it is rather the second IP, simply amend `(?:[^,]+,)?` before `<HOST>`, like:
```ini
failregex = ^\s+(?:\S+\s+){4}(?:[^,]+,)?<HOST>.*Failure count equals \d+$
```

Note that this regex should be obligatory anchored from both sides via `^...$`, because of the usage of catch-all `.*`, otherwise it becomes vulnerable (could be affected with injections on foreign input).

Also note, if fail2ban >= 0.10, it is better to use `<ADDR>` instead of `<HOST>` if only IPs (no hostnames) are expected.

**Comment by sebres** [comment]
If the intention is to match `FAILED authentication` only, simply insert it before `Failure count ...` like here:
```diff
- ...Failure count equals \d+$
+ ...\s+has FAILED authentication.\s+Failure count equals \d+$
```

**Comment by vsevlo** [comment]
> If the intention is to match `FAILED authentication` only, simply insert it before `Failure count ...` like here:
> 
> ```diff
> - ...Failure count equals \d+$
> + ...\s+has FAILED authentication.\s+Failure count equals \d+$
> ```

Thank you very much. On Monday I will try.

**Comment by vsevlo** [comment]
> Your log excerpt seems to contain 2 IPs in failure messages (100.100.100.100 and 127.0.0.1).
> I suppose the intruders IP is 100.100.100.100, then:
> 
> ```ini
> failregex = ^\s+(?:\S+\s+){4}\\<HOST>.*Failure count equals \d+$
> ```
> 
> I don't think the backslash within message is correct (I never saw this in tomcat logs...), if it is not - simply remove `\\` before `<HOST>`.
> 
> ```ini
> failregex = ^\s+(?:\S+\s+){4}<HOST>.*Failure count equals \d+$
> ```
> 
> If it is rather the second IP, simply amend `(?:[^,]+,)?` before `<HOST>`, like:
> 
> ```ini
> failregex = ^\s+(?:\S+\s+){4}(?:[^,]+,)?<HOST>.*Failure count equals \d+$
> ```
> 
> Note that this regex should be obligatory anchored from both sides via `^...$`, because of the usage of catch-all `.*`, otherwise it becomes vulnerable (could be affected with injections on foreign input).
> 
> Also note, if fail2ban >= 0.10, it is better to use `<ADDR>` instead of `<HOST>` if only IPs (no hostnames) are expected.

I tried `^\s+(?:\S+\s+){4}<HOST>.*\s+has FAILED authentication.\s+Failure count equals \d+$`
But finds nothing.
If I try another expression `^\s+(?:\S+\s+){4}(?:[^,]+,)?<HOST>.*\s+has FAILED authentication.\s+Failure count equals \d+$`
Finds 127.0.0.1
Log:

>  2019-06-10 10:53:07,851 http-nio-8080-exec-12 anonymous 653x1222x1 1qyzhno \176.59.12.22,127.0.0.1 /login.jsp The user 'test' has FAILED authentication.  Failure count equals 92
> 2019-06-10 11:31:08,471 http-nio-8080-exec-2 anonymous 691x1228x1 1qyzhno \176.59.12.22,127.0.0.1 /login.jsp The user 'test' is required to answer a CAPTCHA elevated security check.  Failure count equals 93
> 2019-06-10 11:31:20,108 http-nio-8080-exec-15 anonymous 691x1233x1 1qyzhno \176.59.12.22,127.0.0.1 /login.jsp login : 'test' tried to login but they do not have USE permission or weren't found. Deleting remember me cookie.
> 2019-06-10 11:31:20,113 http-nio-8080-exec-15 anonymous 691x1233x1 1qyzhno \176.59.12.22,127.0.0.1 /login.jsp The user 'test' has FAILED authentication.  Failure count equals 94
> 2019-06-10 11:31:33,962 http-nio-8080-exec-33 anonymous 691x1238x1 1qyzhno \176.59.12.22,127.0.0.1 /login.jsp login : 'test' tried to login but they do not have USE permission or weren't found. Deleting remember me cookie.
> 2019-06-10 11:31:33,967 http-nio-8080-exec-33 anonymous 691x1238x1 1qyzhno \176.59.12.22,127.0.0.1 /login.jsp The user 'test' has FAILED authentication.  Failure count equals 95
> 2019-06-10 11:31:45,923 http-nio-8080-exec-1 anonymous 691x1243x1 1qyzhno \176.59.12.22,127.0.0.1 /login.jsp login : 'test' tried to login but they do not have USE permission or weren't found. Deleting remember me cookie.
> 2019-06-10 11:31:45,928 http-nio-8080-exec-1 anonymous 691x1243x1 1qyzhno \176.59.12.22,127.0.0.1 /login.jsp The user 'test' has FAILED authentication.  Failure count equals 96
> 2019-06-10 11:31:59,027 http-nio-8080-exec-25 anonymous 691x1248x1 1qyzhno \176.59.12.22,127.0.0.1 /login.jsp The user 'test' is required to answer a CAPTCHA elevated security check.  Failure count equals 97
> 2019-06-10 11:32:10,732 http-nio-8080-exec-2 anonymous 692x1253x1 1qyzhno \176.59.12.22,127.0.0.1 /login.jsp login : 'test' tried to login but they do not have USE permission or weren't found. Deleting remember me cookie.
> 2019-06-10 11:32:10,737 http-nio-8080-exec-2 anonymous 692x1253x1 1qyzhno \176.59.12.22,127.0.0.1 /login.jsp The user 'test' has FAILED authentication.  Failure count equals 98
> 2019-06-10 11:32:14,929 http-nio-8080-exec-15   -   HttpSession created [1e8wn6v]
> 2019-06-10 11:32:15,161 http-nio-8080-exec-28 anonymous 692x1259x1 - \176.59.12.22,127.0.0.1 /login.jsp HttpSession created [d721mn]
> 2019-06-10 11:32:20,326 http-nio-8080-exec-33 anonymous 692x1263x1 d721mn \176.59.12.22,127.0.0.1 /login.jsp login : 'Gshdjd' tried to login but they do not have USE permission or weren't found. Deleting remember me cookie.
> 2019-06-10 11:32:24,694 http-nio-8080-exec-23 anonymous 692x1267x1 d721mn \176.59.12.22,127.0.0.1 /login.jsp login : 'Gshdjd' tried to login but they do not have USE permission or weren't found. Deleting remember me cookie.
> 2019-06-10 11:32:29,308 http-nio-8080-exec-8 anonymous 692x1271x1 d721mn \176.59.12.22,127.0.0.1 /login.jsp login : 'Gshdjd' tried to login but they do not have USE permission or weren't found. Deleting remember me cookie.
> 2019-06-10 11:32:32,528 http-nio-8080-exec-9 anonymous 692x1275x1 d721mn \176.59.12.22,127.0.0.1 /login.jsp login : 'Gshdjd' tried to login but they do not have USE permission or weren't found. Deleting remember me cookie.
>

**Comment by sebres** [comment]
Add `\\` before `<HOST>`.

**Comment by vsevlo** [comment]
> Add `\\` before `<HOST>`.
`Use   failregex line : ^\s+(?:\S+\s+){4}\<HOST>.*\s+has FAILED authentica...
ERROR: Unable to compile regular expression '^\s+(?:\S+\s+){4}\(?:(?:::f{4,6}:)?(?P<ip4>(?:\d{1,3}\.){3}\d{1,3})|\[?(?P<ip6>(?:[0-9a-fA-F]{1,4}::?|::){1,7}(?:[0-9a-fA-F]{1,4}|(?<=:):))\]?|(?P<dns>[\w\-.^_]*\w)).*\s+has FAILED authentication.\s+Failure count equals \d+$'`

**Comment by vsevlo** [comment]
> Add `\\` before `<HOST>`.
if it doesn't work out, then no problem. I found a way out of this situation. This all works through the nginx proxy, I took the captcha and host request from there. Of course, this is not entirely correct, but it works.

**Comment by vsevlo** [comment]
> logpath = /var/log/nginx/access.log

> failregex = <HOST> -.*GET /captcha.*$

After five captcha requests, the address is banned.

**Comment by sebres** [comment]
You cannot really read: add two slashes.

**Comment by vsevlo** [comment]
> You cannot really read: add two slashes.

two slashes cause an error

**Comment by vsevlo** [comment]
[https://ibb.co/1s7hWBW](url)

**Comment by sebres** [comment]
Because `\\` in bash in double quotes is a single slash (let alone \* will be interpolated too), either use it in filter or use '...' instead of "...".

**Comment by vsevlo** [comment]
> Because `\\` in bash in double quotes is a single slash (let alone * will be interpolated too), either use it in filter or use '...' instead of "...".

Oh, i'm sorry, i'm stupid, thanks a lot. everything is working.

**Comment by vsevlo** [comment]
oh.. i have new problem. fileregex working very nice.

> |      159.28.142.126  Mon Jun 10 13:44:54 2019
> |      159.28.142.126  Mon Jun 10 13:45:08 2019
> |      77.111.247.191  Tue Jun 11 10:00:38 2019
> |      77.111.247.191  Tue Jun 11 10:00:58 2019
> |      77.111.247.191  Tue Jun 11 10:01:30 2019
> |      77.111.247.191  Tue Jun 11 10:02:11 2019
> |      77.111.247.191  Tue Jun 11 10:02:30 2019
> |      77.111.247.191  Tue Jun 11 10:02:51 2019
> |      77.111.247.191  Tue Jun 11 10:04:03 2019

banaction does not work

> Status for the jail: jira
> |- Filter
> |  |- Currently failed:	1
> |  |- Total failed:	7
> |  `- File list:	/opt/jira-home/log/atlassian-jira-security.log
> 
> 

does not add an ip address to the ban

jail.local

> [INCLUDES]
> 
> before = paths-opensuse.conf
> 
> 
> [jira]
> 
> ignoreip = 127.0.0.1/8
> 
> ignorecommand =
> 
> bantime  = 60h
> 
> findtime  = 1m
> 
> logpath = /opt/jira-home/log/atlassian-jira-security.log
> 
> maxretry = 5
> 
> usedns = warn
> 
> logencoding = auto
> 
> enabled = true
> 
> mode = normal
> 
> filter = jira
> 
> protocol = tcp
> 
> port = http,https
> 
> fail2ban_agent = Fail2Ban/%(fail2ban_version)s
> 
> banaction = ufw

**Comment by sebres** [comment]
Take a look in your jail settings:
```ini
findtime = 1m
maxretry = 5
```
This means an IP should produce 5 failures in 1 minute to be banned.
People, please read [fail2ban wiki](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works) (e. g. FAQ there) before you are asking for help.
