### ISSUE TITLE
Unban IP from my country only

### ISSUE THREAD

**Issue by dungvaph03374** [fail2ban/fail2ban#2443]
Hi, i'm using Nginx behind Cloudflare with IP Geolocation enabled
How can i set unban action to unban ip from my country only, thanks!
```
actionban = curl -s -o /dev/null -X POST "https://api.cloudflare.com/client/v4/user/firewall/access_rules/rules" -H "X-Auth-Email: <cfemail>" -H "X-Auth-Key: <cfapikey>" -H "Content-Type: application/json" --data '{"mode":"block","configuration":{"target":"ip","value":"<ip>"},"notes":"<time>"}'
actionunban = curl -s -o /dev/null -X DELETE -H 'X-Auth-Email: <cfemail>' -H 'X-Auth-Key: <cfapikey>' https://api.cloudflare.com/client/v4/user/firewall/access_rules/rules/$(curl -s -X GET -H 'X-Auth-Email: <cfemail>' -H 'X-Auth-Key: <cfapikey>' 'https://api.cloudflare.com/client/v4/user/firewall/access_rules/rules?mode=block&configuration_target=ip&configuration_value=<ip>&page=1&per_page=1' | tr -d '\n' | cut -d'"' -f6)
```

**Comment by sebres** [comment]
> How can i set unban action to unban ip from my country only, thanks!

Rather you want not ban such IPs...

So if you can log this Geo-Info to nginx-log within the message which would be recognized as failure by filter, you'd be able to capture this info in filter, using special tags `<F-*>` in regex like:
```ini
failregex = ^... failed <ADDR>, geo-country: <F-COUNTRY>\S*</F-COUNTRY> ...$
```
Then you'd be able to use this in action as an exclusion clause:
```ini
actionban = if [ "<F-COUNTRY>" != "My Country" ]; then
               # do ban ...
            fi
```

Another possibility is to use `ignorecommand`, which could obtain geo-data for IP and would check it belongs to your country to ignore it.
Note that you can use cache for this facility (to avoid too often call of this command), see #2176. 

If neither custom filter nor `ignorecommand` are according to your desires, please be patient and wait for #1854.
