### ISSUE TITLE
ERROR when f2b sends start/stop email using msmtp as mta

### ISSUE THREAD

**Issue by ikwyl6** [fail2ban/fail2ban#2447]
### The issue:
I use msmtp as my mta. Searching to how to use msmtp within fail2ban instead of sendmail, I followed the directions on this site:

https://unix.stackexchange.com/questions/233866/fail2ban-send-email-with-msmtp

Once I start (or restart f2b) I get the following error in the fail2ban.log file when f2b wants to email  me that he service/daemon has stopped or started:

```
2019-06-15 12:11:07,025 fail2ban.utils          [17270]: #39-Lev. b1c1f310 -- exec: printf %b "Subject: [Fail2Ban] sshd: started on alarm
2019-06-15 12:11:07,027 fail2ban.utils          [17270]: ERROR   b1c1f310 -- stderr: '/bin/sh: -c: line 8: unexpected EOF while looking for matching `"\''
2019-06-15 12:11:07,029 fail2ban.utils          [17270]: ERROR   b1c1f310 -- stderr: '/bin/sh: -c: line 9: syntax error: unexpected end of file'
2019-06-15 12:11:07,031 fail2ban.utils          [17270]: ERROR   b1c1f310 -- returned 1

```
I still get the actual email to my inbox.

### Environment:

uname: ```Linux alarm 4.4.176-1-ARCH #1 PREEMPT Sat Feb 23 19:23:10 UTC 2019 armv5tel GNU/Linux```
fail2ban version: ```Fail2Ban v0.10.4```

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 
- [ x] Fail2Ban installed via OS/distribution mechanisms
- [ x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

#### Steps to reproduce
1. Install msmtp as mta agent.
2. Follow steps on https://unix.stackexchange.com/questions/233866/fail2ban-send-email-with-msmtp
3. restart f2b and review log for 'ERROR'

#### Expected behavior
1. Mail should be sent (which it is) but no errors showing in log file
#### Observed behavior
1. ERRORs in log file as per above
#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
Here is the output when I restart the service using systemd with no loglevel set:
https://paste.rs/MrR

I changed my ```loglevel = DEBUG``` and I now have this output from restart:
https://paste.rs/hZx

Changing ```loglevel = 4``` gives:
https://paste.rs/6tN

#### Relevant lines from monitored log files in question:
```
2019-06-15 12:25:32,329 fail2ban.utils          [17389]: #39-Lev. b1c8b8f0 -- exec: printf %b "Subject: [Fail2Ban] sshd: started on alarm
2019-06-15 12:25:32,331 fail2ban.utils          [17389]: ERROR   b1c8b8f0 -- stderr: '/bin/sh: -c: line 8: unexpected EOF while looking for matching `"\''
2019-06-15 12:25:32,333 fail2ban.utils          [17389]: ERROR   b1c8b8f0 -- stderr: '/bin/sh: -c: line 9: syntax error: unexpected end of file'
2019-06-15 12:25:32,334 fail2ban.utils          [17389]: ERROR   b1c8b8f0 -- returned 1
```

**Comment by sebres** [comment]
> Follow steps on https://unix.stackexchange.com/questions/233866/fail2ban-send-email-with-msmtp

Really?
Why then you did not seek for help for this issues there, on stackexchange?

> stderr: '/bin/sh: -c: line 8: unexpected EOF while looking for matching `"\''
> ...

This means that the new action you generating "following the directions" on SE is wrong (seems to contain a syntax error now, like unmatched quotes).

Either provide an action you're really using (neither I want guess which action exactly it is, nor the **real** resulting action of such "generation" is obvious to me).
Or provide a dump of fail2ban config for any jail using this action, like:
```bash
?sudo? fail2ban-client -d | grep sshd
```
Closed unless more info provided.

**Comment by sebres** [comment]
BTW, in PR #2448 I have normalized `sendmail` actions like (they are more similar `mail` action now, which allow to overwrite mailing command with parameter `mailcmd`).

You can download this actions (place it in `/etc/fail2ban/action.d`, but firstly backup the folder) and use sendmail action as is, just overwrite `mailcmd`:
- either in your own `sendmail-common.local` (it would work in any sendmail action using this include):
```ini
[Definition]
[Init]
mailcmd = msmtp "<dest>"
```
- or in your `jail.local` (rewrite `action_mw*` with amend of parameter `mailcmd`):
```ini
[DEFAULT]

action_mw = %(action_)s
            sendmail-whois[mailcmd='msmtp "<dest>"', name=%(__name__)s, sender="%(sender)s", dest="%(destemail)s", protocol="%(protocol)s", chain="%(chain)s"]

action = %(action_mw)s
```

**Comment by ikwyl6** [comment]
thank you for additional info on msmtp. My bad on this submitted issue. Sorry for wasted time as I had thought the whole time it was f2b when it was not.
