### ISSUE TITLE
Add Optional "Label" for each Trusted IP - Feature Request

### ISSUE THREAD

**Issue by advantipro-gmbh** [fail2ban/fail2ban#2449]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): Unsure
- OS, including release name/version: 
- [x] Installed within Plesk on Host Europe Web Server

### The issue:
I have added several Trusted IP Addresses, but at this point, I have no idea why each IP Address is trusted...

#### Steps to reproduce
- Go to "IP Address Banning"
- Click "Trusted IP Addresses" tab

#### Expected behavior
- See list of trusted IP addresses, along with a label explaining why that IP address is trusted

#### Observed behavior
- See long list of trusted IP addresses, but have no idea why any address is in that list

#### Any additional information
Examples of optional labels would be something like "CEO Computer", "IT Support", "Jane's Home PC", etc.  This allows for invaluable historic data.  Imagine the person that inherits a website, or fleet of websites, and sees this list of 20+ IP addresses, but no idea what each one represents, when each can be removed, etc.

### Configuration, dump and another helpful excerpts
N/A

#### Any customizations done to /etc/fail2ban/ configuration
None I am aware of

#### Relevant parts of /var/log/fail2ban.log file:
N/A

#### Relevant lines from monitored log files in question:
N/A

**Comment by sebres** [comment]
See https://github.com/fail2ban/fail2ban/issues/2450#issuecomment-503931244
