### ISSUE TITLE
Allow Multiple Trusted IP Addresses in One Submission - Feature Request

### ISSUE THREAD

**Issue by advantipro-gmbh** [fail2ban/fail2ban#2450]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): Unsure
- OS, including release name/version: 
- [x] Installed within Plesk on Host Europe Web Server

### The issue:
I have several Trusted IP Addresses that I need to add, but I am required to add each IP Address individually...

#### Steps to reproduce
- Go to "IP Address Banning"
- Click "Trusted IP Addresses" tab
- Click "Add Trusted IP" button

#### Expected behavior
- See a textarea allowing me to enter a single IP address, or multiple IP addresses, either comma-separated, or one address per line in the textarea

#### Observed behavior
- See a single textbox, allowing a single IP address to be entered

#### Any additional information
When you need to enter 15-20 trusted addresses per site, and have 8 sites, you get the idea...  :-)

### Configuration, dump and another helpful excerpts
N/A

#### Any customizations done to /etc/fail2ban/ configuration
None I am aware of

#### Relevant parts of /var/log/fail2ban.log file:
N/A

#### Relevant lines from monitored log files in question:
N/A

**Comment by sebres** [comment]
> Click "Trusted IP Addresses" tab

Where you are clicking on any tab?...
Fail2ban is a server application and what you are describing looks like some foreign GUI application.

Please open your RFE in the ticket system of related application.
