### ISSUE TITLE
Fail2Ban Fails To Start On Boot or Manual Start (After Upgrade)

### ISSUE THREAD

**Issue by andygmorris** [fail2ban/fail2ban#2453]
### Environment:

- Fail2Ban v0.9.3
- Ubuntu Server 16.04.6 (on OpenVZ)
- [ Manual ] Fail2Ban installed via OS/distribution mechanisms
- [ N ] You have not applied any additional foreign patches to the codebase
- [ N ] Some customizations were done to the configuration (provide details below is so)

### The issue:

After an apt-get upgrade.

#### Steps to reproduce

I don't know what version fail2ban was on prior to upgrade to v0.9.3

#### Expected behavior

No detrimental affect was epected to happen to fail2ban

#### Observed behavior

fail2ban stopped loading with the following error report:

$ systemctl status fail2ban.service
● fail2ban.service - Fail2Ban Service
   Loaded: loaded (/etc/systemd/system/fail2ban.service; enabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since Thu 2019-06-27 01:23:14 UTC; 1h 43min ago
     Docs: man:fail2ban(1)
  Process: 3566 ExecStart=/usr/bin/fail2ban-client -x start (code=exited, status=255)

Jun 27 01:23:14 s493 systemd[1]: Failed to start Fail2Ban Service.
Jun 27 01:23:14 s493 systemd[1]: fail2ban.service: Unit entered failed state.
Jun 27 01:23:14 s493 systemd[1]: fail2ban.service: Failed with result 'exit-code'.
Jun 27 01:23:14 s493 systemd[1]: fail2ban.service: Service hold-off time over, scheduling restart.
Jun 27 01:23:14 s493 systemd[1]: Stopped Fail2Ban Service.
Jun 27 01:23:14 s493 systemd[1]: fail2ban.service: Start request repeated too quickly.
Jun 27 01:23:14 s493 systemd[1]: Failed to start Fail2Ban Service.
Jun 27 01:23:14 s493 systemd[1]: fail2ban.service: Unit entered failed state.
Jun 27 01:23:14 s493 systemd[1]: fail2ban.service: Failed with result 'start-limit-hit'.

#### Any additional information

Try to run it manually:
$ /usr/bin/fail2ban-client -x start
ERROR  There is no directory /var/run/fail2ban to contain the socket file /var/run/fail2ban/fail2ban.sock.

Check that folder (which seems a strange folder to use anyway)
$ cd /var/run/fail2ban
-bash: cd: /var/run/fail2ban: No such file or directory

Tested a few times, uninstalling (purge), reinstalling fail2ban.
Even clean install fails, UNLESS you create the /var/run/fail2ban folder BEFORE installing!

#### RESOLVED

On reboot, the folder /var/run/fail2ban is removed, and it's needed for fail2ban to run without errors.

I added the following line to crontab, for on-boot fix (hack!)
@reboot ( sleep 1 ; mkdir /var/run/fail2ban )

Problem solved (for me).
Hope the above notes help someone else.

**Comment by sebres** [comment]
See #1618.
