### ISSUE TITLE
Not able to create a regex

### ISSUE THREAD

**Issue by thomase1993** [fail2ban/fail2ban#2457]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): v0.10.2
- OS, including release name/version: Ubuntu 18.04
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
I try to create a blacklist of ip-addresse called blacklist.txt and use this list as source to match them like this:  fail2ban-regex /var/lists/blacklist.txt /etc/fail2ban/filter.d/blacklist.conf

Before I create the config I want a working regex. But I am not able to create one (already read the issue https://github.com/fail2ban/fail2ban/issues/2078 and tried \<ADDR\>). I expected, that this should match:

$ fail2ban-regex "'10.1.1.1'" "'\<HOST\>'"
Running tests

=============
Use   failregex line : '\<HOST\>'
Use      single line : '10.1.1.1'

Results

=======
Failregex: 0 total
Ignoreregex: 0 total
Date template hits:
Lines: 1 lines, 0 ignored, 0 matched, 1 missed
[processed in 0.02 sec]
|- Missed line(s):
|  '10.1.1.1'

**Comment by sebres** [comment]
There is no date-time in your log "line", which is mandatory in fail2ban.

Also note the date/time (matching `datepattern`) will be cutted out before failregex search started.

**Comment by thomase1993** [comment]
Thank you for your help.
