### ISSUE TITLE
failregex not working with epoch time in the middle

### ISSUE THREAD

**Issue by idarlund** [fail2ban/fail2ban#2463]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): v0.9.7 (also tested on 0.10.4 on mac with homebrew)
- OS, including release name/version: CentOS Linux release 7.6.1810 (Core)
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

There seem to be a bug when matching timestamp with epoch time and when that epoch time is not at the beginning of the log line.

#### Steps to reproduce

This one works (epoch time at the beginning):
```
fail2ban-regex '1562587574.698213 1.2.3.4 asd' '.* <HOST> asd'
```

This one does not work (epoch time in the middle somewhere):
```
fail2ban-regex 'asd 1562587574.698213 1.2.3.4 asd' 'asd .* <HOST> asd'
```

However, when using other timestamp template it works:
```
fail2ban-regex 'asd 13/Feb/2017:02:47:44 1.2.3.4 asd' 'asd .* <HOST> asd'
```

#### Expected behavior

All of the examples should have worked.

#### Observed behavior

```
$ fail2ban-regex '1562587574.698213 1.2.3.4 asd' '.* <HOST> asd'

Running tests
=============

Use   failregex line : .* <HOST> asd
Use      single line : 1562587574.698213 1.2.3.4 asd


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] .* <HOST> asd
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] Epoch
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.00 sec]
```

```
$ fail2ban-regex 'asd 1562587574.698213 1.2.3.4 asd' 'asd .* <HOST> asd'

Running tests
=============

Use   failregex line : asd .* <HOST> asd
Use      single line : asd 1562587574.698213 1.2.3.4 asd


Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:

Lines: 1 lines, 0 ignored, 0 matched, 1 missed
[processed in 0.00 sec]

|- Missed line(s):
|  asd 1562587574.698213 1.2.3.4 asd
`-
```

```
$ fail2ban-regex 'asd 13/Feb/2017:02:47:44 1.2.3.4 asd' 'asd .* <HOST> asd'

Running tests
=============

Use   failregex line : asd .* <HOST> asd
Use      single line : asd 13/Feb/2017:02:47:44 1.2.3.4 asd


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] asd .* <HOST> asd
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] Day(?P<_sep>[-/])MON(?P=_sep)Year[ :]?24hour:Minute:Second(?:\.Microseconds)?(?: Zone offset)?
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.00 sec]
```

**Comment by sebres** [comment]
Shortly: it is correct, because an epoch-pattern is per default strictly anchored (begin of line, square brackets or audit(...), etc)... Just because to parse any long number in the middle may be too error prune.

No idea it work in 0.9 (because too old and the date-template handling is completely rewritten in 0.10), but for version >= 0.10 you can specify a `datepattern` like that:

```bash
fail2ban-regex -d '{Epoch}' -v --VD 'asd 1562587574.698213 1.2.3.4 asd' 'asd \s*<HOST> asd'
```

<details>

```
Running tests
=============

Use      datepattern : {Epoch}
Use   failregex line : asd \s*<HOST> asd
Use      single line : asd 1562587574.698213 1.2.3.4 asd


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] asd \s*<HOST> asd
|      1.2.3.4  Mon Jul 08 14:06:14 2019
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] {Epoch}
|      # weight: 0.333 (1.000), pattern:
|      # regex:   (?:^|\b|\W)((\d{10,11}\b(?:\.\d{3,6})?))(?=\b|\W|$)
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.00 sec]
```
</details>
Here it is anchored using word boundaries only (left and right).

Or you can write it still more precise (move left part of regex into datepattern and anchor it at begin):
```ini
[jail]
datepattern = ^asd\s{Epoch}\s+
failregex = ^<HOST> asd
```
