### ISSUE TITLE
Help needed with regex

### ISSUE THREAD

**Issue by cbrandlehner** [fail2ban/fail2ban#2469]
I would like to build a ruleset for a server prompting a login error to two lines.

An example looks like this:
```
[28325:00010-3735542592] 03-07-2019 16:45:00   imap: noreply@github.com [] authentication failure using internet password
[28325:00010-3735542592] 03-07-2019 16:45:01.75 IMAP CITask StateMachine> Sent 49 bytes to 1.1.1.2
```
Between the [brackets] is a string representing the process. It is always the same format of 5-numbers:5-numbers-10-numbers. That process identifier would be the same for both lines.

The best I came up yet was this one, but I know it is not good that's why I am asking for help:
`
failregex =		^.*authentication failure using internet password[^\n]*<SKIPLINES>\S* IMAP CITask StateMachine> Sent 49 bytes to <HOST>$`

**Comment by sebres** [comment]
> The best I came up yet was this one, but I know it is not good:

Indeed, also obsolete multi-line filter regex (which you're trying to apply) expected a usage of the same prefix for both lines.

> that's why I am asking for help:

Then why you're ignoring our issue template (which can help us to help you)?
Please provide the info we asking there. At least your fail2ban version.

**Comment by cbrandlehner** [comment]
I was under the impression that the template is being used to describe bugs and steps to reproduce, which I thought do not apply here. My fault. Here is the template:

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): 0.8.11
- OS, including release name/version: Linux Mint 4.4.0 (based on Ubuntu Trusty Tahr)
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [X ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
I am trying to build a filter for the IBM Domino IMAP task for a future pull request.

#### Steps to reproduce
n/a, not having a working filter yet.

#### Expected behavior
to identify a login failure which is spread across two lines.

#### Observed behavior
Missing the lines in the log.

#### Any additional information

### Configuration, dump and another helpful excerpts
Log I would like to catch:
```
[28325:00010-3735542592] 03-07-2019 16:45:00   imap: noreply@github.com [] authentication failure using internet password
[28325:00010-3735542592] 03-07-2019 16:45:01.75 IMAP CITask StateMachine> Sent 49 bytes to 1.1.1.2
```

This is the filter:

```
# Fail2Ban configuration file for IBM Domino IMAP4 task authentication failures
[Init]
maxlines = 5
# In some situations, if the server is under some load, the second part of the log is not on the very next line.

[INCLUDES]
before = common.conf

[Definition]
failregex =		^.*authentication failure using internet password[^\n]*<SKIPLINES>\S* IMAP CITask StateMachine> Sent 49 bytes to <HOST>$
ignoreregex =
```

fail2ban-regex output:

```
Running tests
=============

Use   failregex file : config/filter.d/domino-imap.conf
Use         log file : fail2ban/tests/files/logs/domino-imap


Results
=======

Failregex: 0 total
|-  #) [# of hits] regular expression
|   1) [0] ^.*authentication failure using internet password[^\n]*<SKIPLINES>\S* IMAP CITask StateMachine> Sent 49 bytes to <HOST>$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [0] WEEKDAY MONTH Day Hour:Minute:Second[.subsecond] Year
|  [0] WEEKDAY MONTH Day Hour:Minute:Second Year
|  [0] WEEKDAY MONTH Day Hour:Minute:Second
|  [0] MONTH Day Hour:Minute:Second
|  [0] Year/Month/Day Hour:Minute:Second
|  [0] Day/Month/Year Hour:Minute:Second
|  [0] Day/Month/Year2 Hour:Minute:Second
|  [0] Day/MONTH/Year:Hour:Minute:Second
|  [0] Month/Day/Year:Hour:Minute:Second
|  [0] Year-Month-Day Hour:Minute:Second[,subsecond]
|  [0] Year-Month-Day Hour:Minute:Second
|  [0] Year.Month.Day Hour:Minute:Second
|  [0] Day-MONTH-Year Hour:Minute:Second[.Millisecond]
|  [4] Day-Month-Year Hour:Minute:Second
|  [0] Month-Day-Year Hour:Minute:Second[.Millisecond]
|  [0] TAI64N
|  [0] Epoch
|  [0] ISO 8601
|  [0] Hour:Minute:Second
|  [0] <Month/Day/Year@Hour:Minute:Second>
|  [0] YearMonthDay Hour:Minute:Second
|  [0] Month-Day-Year Hour:Minute:Second
`-

Lines: 4 lines, 0 ignored, 0 matched, 4 missed
|- Missed line(s):
|  [07798:00012-00007F77ADBCD700] 03-07-2019 16:43:31   imap: noreply@github.com [] authentication failure using internet password
|  [07798:00012-00007F77ADBCD700] 03-07-2019 16:43:35.75 IMAP CITask StateMachine> Sent 49 bytes to 1.1.1.1
|  03-07-2019 16:45:00   imap: noreply@github.com [] authentication failure using internet password
|  03-07-2019 16:45:01.75 IMAP CITask StateMachine> Sent 49 bytes to 1.1.1.2
`-

```

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
n/a / currently working with fail2ban-regex
```

#### Relevant lines from monitored log files in question:

```
[28325:00010-3735542592] 03-07-2019 16:45:00   imap: noreply@github.com [] authentication failure using internet password
[28325:00010-3735542592] 03-07-2019 16:45:01.75 IMAP CITask StateMachine> Sent 49 bytes to 1.1.1.2
```

**Comment by sebres** [comment]
0.8.11?! oh my God...

Ok... Here you go (no idea it would work within 0.8 but it should work in 0.9):
```ini
[Definition]

__prefix_line = ^\[[^\]]+\]
__prefix_line_ml1 = (?P<__prefix>%(__prefix_line)s)
__prefix_line_ml2 = $<SKIPLINES>^(?P=__prefix)

failregex = ^%(__prefix_line_ml1)s\s+imap: [^\n]+ authentication failure using internet password%(__prefix_line_ml2)s\s*(?:\.\d+)?\s+IMAP CITask StateMachine> Sent \d+ bytes to <HOST>$

maxlines = 10
```

But for several reasons it'd be better for you to upgrade to 0.10 (or 0.11) and rewrite this buffering obsolete multi-liner to newest handling with `prefregex` and  multi-line identifier using tags `<F-MLFID>...</F-MLFID>`...

**Comment by sebres** [comment]
I had get some free time, so here is the config for same log using new multi-line handling (fail2ban >= 0.10):
```ini
[Definition]

datepattern = (?<=\])\s+%%d-%%m-%%ExY %%H:%%M:%%S(?:\.%%f)?

prefregex = ^<F-MLFID>\[[^\]]+\]</F-MLFID>\s+<F-CONTENT>.+</F-CONTENT>$

failregex = ^imap: [^\n]+ authentication failure using internet password
            ^<F-NOFAIL>IMAP</F-NOFAIL> CITask StateMachine> Sent \d+ bytes to <ADDR>$
```

**Comment by cbrandlehner** [comment]
Thank you so much, I will look into it soon.
Regarding the version: I pulled directly from github, seems I have choosen the wrong branch. I was trying to use the most recent code.

**Comment by cbrandlehner** [comment]
I have a production server running fail2ban 0.9.10. Your first regex works fine with this version.

I am going to test the younger update on a another server with fail2ban 0.10.x the next days.
THANK YOU!

**Comment by sebres** [comment]
0.9.10? 
Hmm... where you did obtain it from? 
We have never released such version (0.9.7 is and remains our last release of 0.9th branch).

**Comment by cbrandlehner** [comment]
I never gave feedback to this one. Missed it probably as it was closed.
I was successfully able to get it work with version 0.10.4 using this config:
```

[Definition]

datepattern = (?<=\])\s+%%d-%%m-%%ExY %%H:%%M:%%S(?:\.%%f)?

prefregex = ^<F-MLFID>\[[^\]]+\]</F-MLFID>\s+<F-CONTENT>.+</F-CONTENT>$

failregex = ^imap: [^\n]+ authentication failure using internet password
            ^<F-NOFAIL>IMAP</F-NOFAIL> CITask StateMachine> Sent \d+ bytes to <ADDR>$
```

**Comment by sebres** [comment]
Thx for the feedback.
