### ISSUE TITLE
PIDFile= references path below legacy directory on Debian Buster

### ISSUE THREAD

**Issue by gaia** [fail2ban/fail2ban#2474]
### Environment:

- OS, including release name/version: Debian Buster 10
- [X] Fail2Ban installed via OS/distribution mechanisms

### The issue:

upon `systemctl enable fail2ban`

`systemd[1]: /lib/systemd/system/fail2ban.service:12: PIDFile= references path below legacy directory /var/run/, updating /var/run/fail2ban/fail2ban.pid → /run/fail2ban/fail2ban.pid; please update the unit file accordingly.`

shows up in the logs. both files exist

#### Expected behavior

no warning

#### Observed behavior

warning

#### Any additional information

`uname -r` is `5.0.15-1-pve` (proxmox 6.0.4)

**Comment by sebres** [comment]
Fixed in d5a5efcd5af272372153e86436d7c8cde2ddf66d.
Thanks!

**Comment by slrslr** [comment]
Hello, @sebres sorry for bumping this, but i got this error:

> systemd[1]: /lib/systemd/system/fail2ban.service:12: PIDFile= references path below legacy directory /var/run/, updating /var/run/fail2ban/fail2ban.pid → /run/fail2ban/fail2ban.pid; please update the unit file accordingly.

On Raspberry Pi 4 with Raspbian 10 buster, 4.19.93-v7l+. "apt info fail2ban" shows:

> Package: fail2ban
> Version: 0.10.2-2.1
> Priority: optional
> Section: net
> ...
> APT-Manual-Installed: yes
> APT-Sources: http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages

You can do something about this, or i should ask somewhere else?

**Comment by sebres** [comment]
This is not an error (rather a warning)...
Should be updated by next release... If you want to update it right now by yourself:
- patch your `fail2ban.service` like in the fix d5a5efcd5af272372153e86436d7c8cde2ddf66d
- run `systemctl daemon-reload`

and by next start you'd not see that anymore.

You could also search in `/etc/fail2ban` for `/var/run/` and replace all occurrences with `/run/`.

**Comment by conandrum** [comment]
HI, I have 0.11.1 version. Recently upgraded to Ununtu 20.04 from 18.04.
This line now appears in the log.
`systemd[1]: /etc/systemd/system/fail2ban.service:15: PIDFile= references a path below legacy directory /var/run/, updating /var/run/fail2ban/fail2ban.pid â†’ /run/fail2ban/fail2ban.pid; please update the unit file accordingly.`
Should I wait for an updrade to fix it or 
is it already breaking the functionality of F2B and I should manually fix it?

**Comment by sebres** [comment]
> Should I wait for an updrade to fix it or
> is it already breaking the functionality of F2B and I should manually fix it?

Neither the former: you could change it by yourself, but not need to do that. 
Nor the later: this is just a warning that /var/run is deprecated now and can be removed in following releases, but everything is still working as it should.
