### ISSUE TITLE
regex passes external tests but fails in fail2ban

### ISSUE THREAD

**Issue by callahan22** [fail2ban/fail2ban#2485]
### Environment:

- Fail2Ban version: 0.10.2-2 (Ubuntu 18.04)
- Fail2Ban installed via apt install fail2ban
- Nexcloud (the log I'm trying to analyse) runs on a docker stack on a different physical box.
- I've got the docker container mapped to a mount point on my NAS (/mnt/nfs/logs/nextcloud.log). The same mount is set up on the server running fail2ban. Permissions are all correct and I can tail -f the log from the fail2ban server and see the log filling as I attempt to log onto Nextcloud with random usernames/passwords.
### The issue:

Testing my regex on the fail2ban regex tester at: https://www.regextester.com produces a positive result. Applying the same regex in fail2ban-regex test does not. Perfetly lightly it's my regex but I've verified it with a 3rd party so I'm kinda at a loss. Not expecting anyone to write it for me, just a pointer in the right direction would be appreciated.

LOG:
`{"reqId":"Hhw2nI6IdgYm9GATd7CB","level":2,"time":"2019-07-29T22:05:54+00:00","remoteAddr":"192.168.100.1","user":"--","app":"core","method":"POST","url":"\/login?user=dfdf25","message":"Login failed: 'dfdf25' (Remote IP: '192.168.100.1')","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":"16.0.3.0"}`

REGEX:
`^{"reqId":".*","level":2,"time":".*","remoteAddr":".*","user":".*","app":"core","method":"POST","url":"\\\/login\?user=.*","message":"Login failed: '.*' \(Remote IP: '<HOSTNAME>'\).*}$`

Equally, this is valid (according to the site and from my limited experience)
`^.*"Login failed: '.*' \(Remote IP: '<HOSTNAME>'\).*}$`

However:
`fail2ban-regex /tmp/test.log /etc/fail2ban/filter.d/nextcloud.conf`

```
Running tests
=============

Use   failregex filter file : nextcloud, basedir: /etc/fail2ban
Use         log file : /tmp/test.log
Use         encoding : UTF-8


Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] ExYear(?P<_sep>[-/.])Month(?P=_sep)Day(?:T|  ?)24hour:Minute:Second(?:[.,]Microseconds)?(?:\s*Zone offset)?
`-

Lines: 1 lines, 0 ignored, 0 matched, 1 missed
[processed in 0.08 sec]

|- Missed line(s):
|  {"reqId":"Hhw2nI6IdgYm9GATd7CB","level":2,"time":"2019-07-29T22:05:54+00:00","remoteAddr":"192.168.100.1","user":"--","app":"core","method":"POST","url":"\/login?user=dfdf25","message":"Login failed: 'dfdf25' (Remote IP: '192.168.100.1')","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":"16.0.3.0"}
`-
```

If anyone could help point out what I'm missing, I'd really appreciate it.

**Comment by sebres** [comment]
Firstly, I don't see the content of your nextcloud filter, but `<HOSTNAME>` is unknown to me, so not valid tag in my opinion (if not interpolated in filter by some substitution). fail2ban has the tags `<HOST>` or `<ADDR>` for this purposes.

Secondly, due to many catch-all's it can find something else if running in fail2ban (e. g. it can resolve dns-hostname due to `usedns = warn` as default setting in fail2ban, etc).
As well as the different RE-engines can search differently (I don't know the engine you've tested is python-RE compatible, and all the internal substitutions are interpolated in the same way).

And last but not least, we have already several issues with similar log-file, so for example take a look in #2330 for a working filter.
Just in your case the logged timestamp is different, so your filter would look like this either:
```ini
[Definition]

_groupsre = (?:(?:,?\s*"\w+":(?:"[^"]+"|\w+))*)
failregex = ^\{%(_groupsre)s,?\s*"remoteAddr":"<HOST>"%(_groupsre)s,?\s*"message":"Login failed:

datepattern = ,?\s*"time"\s*:\s*"%%Y-%%m-%%d[T ]%%H:%%M:%%S(%%z)?"
```

**Comment by callahan22** [comment]
Thanks for your reply. Some of what you said led me to look again at the regex The test now matches as expected. It doesn't however fire when the log is populated with matching entries.

For those that arrive here looking for the same answer in terms of why they can't match NExcloud logs, I had to replace <HOST> with <ADDR>. This now fires when testing (although not when running):

/etc/fail2ban/jail.local
```
#
# Nextcloud
#
[nextcloud]
enabled = true
port = http,https
filter = nextcloud
logpath = /mnt/nfs/logs/nextcloud.log
maxretry = 3
```


/etc/fail2ban/filter.d/nextcloud.conf
```
[Definition]
failregex = ^{.*Login failed: '.*' \(Remote IP: '<ADDR>'\).*}$
ignoreregex =
```


Log file:
```
{"reqId":"sXcw25Ojj6Z7gNygnfFT","level":2,"time":"2019-07-30T15:22:13+00:00","remoteAddr":"192.168.1.2","user":"--","app":"core","method":"POST","url":"\/login?user=rt45","message":"Login failed: 'rt45' (Remote IP: '192.168.1.2')","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":"16.0.3.0"}
{"reqId":"sXcw25Ojj6Z7gNygnfFT","level":1,"time":"2019-07-30T15:22:14+00:00","remoteAddr":"192.168.1.2","user":"--","app":"core","method":"POST","url":"\/login?user=rt45","message":"Bruteforce attempt from \"192.168.1.2\" detected for action \"login\".","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":"16.0.3.0"}
```

Test:
```
fail2ban-regex /mnt/nfs/logs/nextcloud.log /etc/fail2ban/filter.d/nextcloud.conf
Running tests
=============

Use   failregex filter file : nextcloud, basedir: /etc/fail2ban
Use         log file : /mnt/nfs/logs/nextcloud.log
Use         encoding : UTF-8


Results
=======

Failregex: 105 total
|-  #) [# of hits] regular expression
|   1) [105] ^{.*Login failed: '.*' \(Remote IP: '<ADDR>'\).*}$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [278] ExYear(?P<_sep>[-/.])Month(?P=_sep)Day(?:T|  ?)24hour:Minute:Second(?:[.,]Microseconds)?(?:\s*Zone offset)?
`-

Lines: 348 lines, 0 ignored, 105 matched, 243 missed
[processed in 0.45 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all 243 lines
```

Hopefully the above helps someone get this far. I'd still like to make Fail2ban fire when running. Not sure why it won't when the config test has passed and fired as expected.

**Comment by sebres** [comment]
You're welcome.

> For those that arrive here looking for the same answer ...
> failregex = ^{.*Login failed: '.*' \(Remote IP: '<ADDR>'\).*}$

Nope. 
Your `failregex` is vulnerable in extreme:
- regex `^{.*Login failed: '.*' \(Remote IP: '<ADDR>'\).*}$` is not really anchored, so both following are almost the same:
```
`^{.*Login failed: '.*' \(Remote IP: '<ADDR>'\).*}$`
`Login failed: '.*' \(Remote IP: '<ADDR>'\)`
```
- 3 catch-all's (especially without anchors) allows to inject into everything;
- etc.

So for "those that arrive here looking for the same answer", I'd suggest to take a look at already provided correct filter in my first comment.

And please rewrite your comment above using my filter suggestion (or more precise example).

> Hopefully the above helps someone get this far. 

What are the arguments against usage of already suggested filter?

**Comment by callahan22** [comment]
> Nope.
Your failregex is vulnerable in extreme:

Yep, you're 100% correct. I'm not (clearly) a regex expert so I'm learning as I go. I see what you are saying about the number of catch-alls I've used. My argument here (not that I really have one as I agree with what you're saying!), is that I only care about the "Failed Login" string so it's not as important that it's air tight. Again, I would far rather nail it down so there is no chance of picking up a line I don't want though.

> And please rewrite your comment above using my filter suggestion (or more precise example).

The truth is, I did use yours while at work and I clearly didn't pay enough attention as it failed (though an error by me) so I went looking and found things like:
https://gist.github.com/GAS85/957e0b1a4f30120225a7be09b173eb24
and:
https://www.c-rieger.de/nextcloud-installation-guide-apache2/#c103
so I went off track a little.
I've now used your expression and as suggested, it also works. I'll have to read up more on regex to understand entirely what your expression is doing mind you.
So, I've used your filter. Details below:

/etc/fail2ban/filter.d/nextcloud.conf
```
[Definition]

_groupsre = (?:(?:,?\s*"\w+":(?:"[^"]+"|\w+))*)
failregex = ^\{%(_groupsre)s,?\s*"remoteAddr":"<HOST>"%(_groupsre)s,?\s*"message":"Login failed:

datepattern = ,?\s*"time"\s*:\s*"%%Y-%%m-%%d[T ]%%H:%%M:%%S(%%z)?"
```

/etc/fail2ban/jail.local
```
#
# Nextcloud
#
[nextcloud]

enabled = true
port = http,https
protocol = tcp
filter = nextcloud
logpath = /mnt/nfs/ogs/nextcloud.log
maxretry = 3

[DEFAULT]
bantime  = 24h
findtime  = 10m
maxretry = 5
```
Test:
fail2ban-regex /mnt/nfs/logs/nextcloud.log /etc/fail2ban/filter.d/nextcloud.conf
```
Running tests
=============

Use   failregex filter file : nextcloud, basedir: /etc/fail2ban
Use      datepattern : ,?\s*"time"\s*:\s*"Year-Month-Day[T ]24hour:Minute:Second(Zone offset)?"
Use         log file : /mnt/nfs/logs/nextcloud.log
Use         encoding : UTF-8


Results
=======

Failregex: 123 total
|-  #) [# of hits] regular expression
|   1) [123] ^\{(?:(?:,?\s*"\w+":(?:"[^"]+"|\w+))*),?\s*"remoteAddr":"<HOST>"(?:(?:,?\s*"\w+":(?:"[^"]+"|\w+))*),?\s*"message":"Login failed:
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [316] ,?\s*"time"\s*:\s*"Year-Month-Day[T ]24hour:Minute:Second(Zone offset)?"
`-

Lines: 386 lines, 0 ignored, 123 matched, 263 missed
[processed in 0.28 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all 263 lines
```
sudo tail -f /mnt/nfs/logs/nextcloud.log
```
{"reqId":"AgDSGr9h6zxicxociFzR","level":2,"time":"2019-07-30T21:04:36+00:00","remoteAddr":"85.255.237.88","user":"--","app":"core","method":"POST","url":"\/login?user=Jsbsb","message":"Login failed: 'Jsbsb' (Remote IP: '85.255.237.88')","userAgent":"Mozilla\/5.0 (Android 9; Mobile; rv:68.0) Gecko\/68.0 Firefox\/68.0","version":"16.0.3.0"}
{"reqId":"AgDSGr9h6zxicxociFzR","level":1,"time":"2019-07-30T21:04:36+00:00","remoteAddr":"85.255.237.88","user":"--","app":"core","method":"POST","url":"\/login?user=Jsbsb","message":"Bruteforce attempt from \"85.255.237.88\" detected for action \"login\".","userAgent":"Mozilla\/5.0 (Android 9; Mobile; rv:68.0) Gecko\/68.0 Firefox\/68.0","version":"16.0.3.0"}
{"reqId":"xl8lxtsW3P0tdL3B9hg9","level":2,"time":"2019-07-30T21:04:41+00:00","remoteAddr":"85.255.237.88","user":"--","app":"core","method":"POST","url":"\/login?user=Jsbsb","message":"Login failed: 'Jsbsb' (Remote IP: '85.255.237.88')","userAgent":"Mozilla\/5.0 (Android 9; Mobile; rv:68.0) Gecko\/68.0 Firefox\/68.0","version":"16.0.3.0"}
{"reqId":"xl8lxtsW3P0tdL3B9hg9","level":1,"time":"2019-07-30T21:04:41+00:00","remoteAddr":"85.255.237.88","user":"--","app":"core","method":"POST","url":"\/login?user=Jsbsb","message":"Bruteforce attempt from \"85.255.237.88\" detected for action \"login\".","userAgent":"Mozilla\/5.0 (Android 9; Mobile; rv:68.0) Gecko\/68.0 Firefox\/68.0","version":"16.0.3.0"}
{"reqId":"h8gzpEuuPRsmOP6Zs2kB","level":2,"time":"2019-07-30T21:04:46+00:00","remoteAddr":"85.255.237.88","user":"--","app":"core","method":"POST","url":"\/login?user=Jsbsb","message":"Login failed: 'Jsbsb' (Remote IP: '85.255.237.88')","userAgent":"Mozilla\/5.0 (Android 9; Mobile; rv:68.0) Gecko\/68.0 Firefox\/68.0","version":"16.0.3.0"}
{"reqId":"h8gzpEuuPRsmOP6Zs2kB","level":1,"time":"2019-07-30T21:04:46+00:00","remoteAddr":"85.255.237.88","user":"--","app":"core","method":"POST","url":"\/login?user=Jsbsb","message":"Bruteforce attempt from \"85.255.237.88\" detected for action \"login\".","userAgent":"Mozilla\/5.0 (Android 9; Mobile; rv:68.0) Gecko\/68.0 Firefox\/68.0","version":"16.0.3.0"}
{"reqId":"R4xgNcvzFMMibTbXtoLd","level":2,"time":"2019-07-30T21:04:51+00:00","remoteAddr":"85.255.237.88","user":"--","app":"core","method":"POST","url":"\/login?user=Jsbsb","message":"Login failed: 'Jsbsb' (Remote IP: '85.255.237.88')","userAgent":"Mozilla\/5.0 (Android 9; Mobile; rv:68.0) Gecko\/68.0 Firefox\/68.0","version":"16.0.3.0"}
{"reqId":"R4xgNcvzFMMibTbXtoLd","level":1,"time":"2019-07-30T21:04:52+00:00","remoteAddr":"85.255.237.88","user":"--","app":"core","method":"POST","url":"\/login?user=Jsbsb","message":"Bruteforce attempt from \"85.255.237.88\" detected for action \"login\".","userAgent":"Mozilla\/5.0 (Android 9; Mobile; rv:68.0) Gecko\/68.0 Firefox\/68.0","version":"16.0.3.0"}
{"reqId":"GZO71Bydr0ulfLRHkUDj","level":2,"time":"2019-07-30T21:04:57+00:00","remoteAddr":"85.255.237.88","user":"--","app":"core","method":"POST","url":"\/login?user=Jsbsb","message":"Login failed: 'Jsbsb' (Remote IP: '85.255.237.88')","userAgent":"Mozilla\/5.0 (Android 9; Mobile; rv:68.0) Gecko\/68.0 Firefox\/68.0","version":"16.0.3.0"}
{"reqId":"GZO71Bydr0ulfLRHkUDj","level":1,"time":"2019-07-30T21:04:59+00:00","remoteAddr":"85.255.237.88","user":"--","app":"core","method":"POST","url":"\/login?user=Jsbsb","message":"Bruteforce attempt from \"85.255.237.88\" detected for action \"login\".","userAgent":"Mozilla\/5.0 (Android 9; Mobile; rv:68.0) Gecko\/68.0 Firefox\/68.0","version":"16.0.3.0"}
```
Other jails, specifically nginx-http-auth in the jail.local file as defined below work fine.
```
[nginx-http-auth]

enabled  = true
filter   = nginx-http-auth
port     = http,https
logpath  = /var/log/nginx/error.log

Status of the nextcloud jail:

```
Status for the jail: nextcloud
|- Filter
|  |- Currently failed:	0
|  |- Total failed:	0
|   - File list:	/mnt/nfs/logs/nextcloud.log
  Actions
   |- Currently banned:	0
   |- Total banned:	0
    - Banned IP list:
```
So, any ideas?! :-)

**Comment by sebres** [comment]
> So, any ideas?!

Maybe... Just to exclude timezone issue (somehow is it too often last time) - which timezone do you have, and also provide a timestamp do you see (e.g. in your tail-f output) together with real time on your system...
For example time `21:04:36+00:00` (+00 meant UTC) corresponds `23:04:36 CET`.

So if you would notice they are deviating - see https://github.com/fail2ban/fail2ban/issues/2486#issuecomment-516533007

**Comment by callahan22** [comment]
Feeling like a idiot now. I've just noticed that the timestamp on the log entries are 1 hour behind my timezone (Europe/London) which is GMT+1 at the moment. I've just read your link and I think I understand now things are playing out. Fail2ban sees my log as in the past so as it doesn't fall within a timeframe (I'm not sure where that timeframe is defined, maybe it has to have a timestamp within the last few seconds? As I'm have the year in the timestamp, it's not classifying it as coming from last year but still in the past so ignores it.
2 questions, 1 out of curiousity and 1 to help me fix this issue.

1). what timeframe do the logs have to be within the current system time to be counted as "now"?

2). Is there a preferred timestap that fail2ban works best with as I can proably configure Nextcloud to output the best format for fail2ban.

Thanks for your continued help, really apprecite you taking time to help.

**Comment by sebres** [comment]
1) if you mean timezone - fail2ban is working with system timezone (same as init.d/systemd/etc)...
The logger (or service) may use another for some reasons (or due to some bug/refresh issue/misconfiguration).
If you mean the string representation, it depends, but if you don't have TZ in timestamp (or the datepattern doesn't consider it) - the system TZ (or rather fail2ban TZ) is used. Otherwise fail2ban uses TZ from string (log) by time conversion.

2) No... But the right way is always to find and correct time or TZ where it is wrong... e.g. because TZ is specified in timestamp (I assume real time of nextcloud is wrong), so better would be to correct its time (or logging of timestamp, no matter in which format).
As a workaround (to adjust a time offset) one can use an option `logtimezone` (and date pattern without TZ) to specify default TZ for log (see #1792) in order to force fail2ban to calculate another "correct" offset. But it is a bit ugly (e.g. could become incorrect later once the real time of service (nextclode or fail2ban) will be adjusted (corrected).

**Comment by sebres** [comment]
If you mean as timeframe the time fail2ban uses to cumulate failures - it is `findtime`.
But as already said for several reasons to increase it would be not good idea. This is used basically to control the threshold how many atempts (`maxretry`) the IP/ID should make to be banned. This options are definitely not for the time correction issues.

**Comment by callahan22** [comment]
Ok so I've managed to change the timestamp's format and ensure it is stemping the system time.
Log lines now look like:

`{"reqId":"SGe8etqkRPnarN5oKNFd","level":2,"time":"2019-07-31 01:26:29","remoteAddr":"85.255.237.88","user":"--","app":"core","method":"POST","url":"\/login?user=Jsbsbj","message":"Login failed: 'Jsbsbj' (Remote IP: '85.255.237.88')","userAgent":"Mozilla\/5.0 (Android 9; Mobile; rv:68.0) Gecko\/68.0 Firefox\/68.0","version":"16.0.3.0"}`

The test can match the lines but I still can't get it to fire. I can change the date format to anything now so is there a particular date format that would work best with fail2ban (presuming the date field is the issue)?

**Comment by sebres** [comment]
> I can change the date format to anything now so is there a particular date format that would work best with fail2ban 

As already said, not really, as long as it matches and the time you see in log is correct and matched by fail2ban each format is good enough.

> (presuming the date field is the issue)?

To be sure: just pick some last message you know the time and follow this test https://github.com/fail2ban/fail2ban/issues/2149#issuecomment-395046240
in verbose output you would see the time converted in timezone of fail2ban (normally system timezone) - if it is also your time, you have something different.

Another variant is to put fail2ban temporary to HEAVYDEBUG mode (see https://github.com/fail2ban/fail2ban/issues/2486#issuecomment-516448897), so we'd be able to see more.
