### ISSUE TITLE
sshd jail does not work (Ubuntu 18.04; v0.10.2)

### ISSUE THREAD

**Issue by supriyo-biswas** [fail2ban/fail2ban#2486]
### Description of issue:

I have installed Fail2ban on Ubuntu 18.04 but am unable to get it to work. When I check the iptables rules, I do not see the `f2b-sshd` rule being inserted into the INPUT chain. I also have failed auth attempts in `/var/log/auth.log`, and I also don't see these IPs being banned either.

### System details and configuration:

- Fail2Ban version: v0.10.2
- OS: Ubuntu 18.04
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration: Minimal changes, which just include enabling the filter and adjusting the findtime and bantime:

```
$ cat /etc/fail2ban/jail.local
[sshd]
enabled    = true
findtime   = 86400
bantime    = 86400
maxretry   = 15
```

* Output of `fail2ban-client -d | grep sshd`: https://pastebin.com/7KZx9W78
* Output of `fail2ban-client -vvv start`: https://pastebin.com/R3GvUV9p
* Contents of `/var/log/fail2ban.log` file: https://pastebin.com/8avEFcd5
* Excerpt from `/var/log/auth.log` showing that there are indeed entries in the log with failed login attempts: https://pastebin.com/sqFPGdvP

**Comment by sebres** [comment]
> When I check the iptables rules, I do not see the f2b-sshd rule being inserted into the INPUT chain

This happens on demand since v.0.10 (#1742), see https://github.com/fail2ban/fail2ban/issues/1755#issuecomment-295286513 as answer for similar question.
But it does nothing currently with your main issue (because fail2ban seems to don't find the failures, so no bans occurred).

> I also have failed auth attempts in /var/log/auth.log, and I also don't see these IPs being banned either.

[In our wiki](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works) you'll find possible reasons for that.

Although your filter is a bit outdated, but I don't see what should avoid proper recognition.

Anyway your filter (restored from dump) as well as latest 0.10 version find 2086 matches in your log-excerpt:
<details>

#### 0.10.2-filter (restored from your dump):
```bash
$ fail2ban-regex gh-2486.txt gh-2486.conf


Running tests
=============

Use   failregex file : gh-2486.conf
Use         log file : gh-2486.txt
Use         encoding : UTF-8


Results
=======

Failregex: 2639 total
|-  #) [# of hits] regular expression
|   3) [553] ^Failed \S+ for invalid user <F-USER>(?P<cond_user>\S+)|(?:(?! from ).)*?</F-USER> from <HOST>(?: port \d+)?(?: on \S+(?: port \d+)?)?(?: ssh\d*)?(?(cond_user): |(?:(?:(?! from ).)*)$)
|   4) [2086] ^Failed \b(?!publickey)\S+ for (?P<cond_inv>invalid user )?<F-USER>(?P<cond_user>\S+)|(?(cond_inv)(?:(?! from ).)*?|[^:]+)</F-USER> from <HOST>(?: port \d+)?(?: on \S+(?: port \d+)?)?(?: ssh\d*)?(?(cond_user): |(?:(?:(?! from ).)*)$)
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [2088] {^LN-BEG}(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
`-

Lines: 2088 lines, 0 ignored, 2086 matched, 2 missed
[processed in 0.28 sec]
```
#### 0.10.5:
```bash
$ fail2ban-regex gh-2486.txt sshd

Running tests
=============

Use   failregex filter file : sshd, basedir: /etc/fail2ban/
Use         maxlines : 1
Use      datepattern : Default Detectors
Use         log file : gh-2486.txt
Use         encoding : UTF-8


Results
=======

Failregex: 2088 total
|-  #) [# of hits] regular expression
|   4) [2086] ^Failed \b(?!publickey)\S+ for (?P<cond_inv>invalid user )?<F-USER>(?P<cond_user>\S+)|(?(cond_inv)(?:(?! from ).)*?|[^:]+)</F-USER> from <HOST>(?: (?:port \d+|on \S+)){0,2}(?: ssh\d*)?(?(cond_user): |(?:(?:(?! from ).)*)$)
|  21) [2] ^<F-MLFFORGET><F-MLFGAINED>Accepted \w+</F-MLFGAINED></F-MLFFORGET> for <F-USER>\S+</F-USER> from <HOST>(?:\s|$)
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [2088] {^LN-BEG}(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
`-

Lines: 2088 lines, 2 ignored, 2086 matched, 0 missed
[processed in 0.22 sec]
```
</details>

What do you see by `fail2ban-regex /var/log/auth.log sshd`?

Maybe your auth.log is simply too large / not rotated (so usage of `head` is not good in such case).
It looks like fail2ban processed 4MB (4006456) in-between (12:40:51 ... 12:46:25), but you've used grep, so I don't know its real size and whether it has reached already a time corresponding your `findtime` parameter (1day).

If your fail2ban-regex test would find the failures (similar like above), may be a run within DEBUG mode could help, you can temporary activate DEBUG (or even HEAVYDEBUG)...
To put fail2ban into DEBUG mode:
```
sudo fail2ban-client set loglevel DEBUG
```
Or if it does not work for some reason, just start within DEBUG level (set it fail2ban.conf and restart).

Then wait for failures in auth.log and switch back:
```
sudo fail2ban-client set loglevel INFO
```

**Comment by supriyo-biswas** [comment]
> What do you see by `fail2ban-regex /var/log/auth.log sshd`?

Here you go:

```bash
# fail2ban-regex /var/log/auth.log sshd

Running tests
=============

Use   failregex filter file : sshd, basedir: /etc/fail2ban
Use         maxlines : 1
Use      datepattern : Default Detectors
Use         log file : /var/log/auth.log
Use         encoding : UTF-8


Results
=======

Failregex: 14738 total
|-  #) [# of hits] regular expression
|   3) [946] ^Failed \S+ for invalid user <F-USER>(?P<cond_user>\S+)|(?:(?! from ).)*?</F-USER> from <HOST>(?: port \d+)?(?: on \S+(?: port \d+)?)?(?: ssh\d*)?(?(cond_user): |(?:(?:(?! from ).)*)$)
|   4) [7118] ^Failed \b(?!publickey)\S+ for (?P<cond_inv>invalid user )?<F-USER>(?P<cond_user>\S+)|(?(cond_inv)(?:(?! from ).)*?|[^:]+)</F-USER> from <HOST>(?: port \d+)?(?: on \S+(?: port \d+)?)?(?: ssh\d*)?(?(cond_user): |(?:(?:(?! from ).)*)$)
|   6) [886] ^[iI](?:llegal|nvalid) user <F-USER>.*?</F-USER> from <HOST>(?: port \d+)?(?: on \S+(?: port \d+)?)?\s*$
|  14) [5422] ^pam_unix\(sshd:auth\):\s+authentication failure;\s*logname=\S*\s*uid=\d*\s*euid=\d*\s*tty=\S*\s*ruser=<F-USER>\S*</F-USER>\s*rhost=<HOST>\s.*(?: \[preauth\])?\s*$
|  15) [366] ^(error: )?maximum authentication attempts exceeded for <F-USER>.*</F-USER> from <HOST>(?: port \d+)?(?: on \S+(?: port \d+)?)?(?: ssh\d*)?(?: \[preauth\])?\s*$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [34429] {^LN-BEG}(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
`-

Lines: 34429 lines, 0 ignored, 14738 matched, 19691 missed
[processed in 3.77 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all 19691 lines
```

The full auth.log content is available here: https://supriyo.dynu.com/paste/?d1c76bed66e12f63#CgW7PYF+zBrM2qQTDgX9ty3mHiAWYHsY9jHNMmSawQY=

I tried enabling both DEBUG and HEAVYDEBUG, but `/var/log/fail2ban.log` just seems to contain regular stuff: https://supriyo.dynu.com/paste/?502b06222be358a5#eav4B5aWiTdWphFpbeFG7R/OJYtko/154h/PSRNtvjo=

Can you take a look?

**Comment by sebres** [comment]
> Can you take a look?

Nope... I cannot open your paste's ("PrivateBin requires a modern browser to work.")... 
Use github to attach a file (see at bottom of comment part - _attach files by dragging & dropping, selecting or pasting them._).
Or even simple download url (without "modern" stuff).

**Comment by supriyo-biswas** [comment]
[logs.zip](https://github.com/fail2ban/fail2ban/files/3447940/logs.zip)

**Comment by sebres** [comment]
Something is strange there...
Debug log said continuously that the log has been modified, but does not detect something.
But log level is too low for that (next message would be `Found ...` if it really found something).

And heavy debug log excerpt is too short, there is no changes detected between 15:51:41 and 15:52:07.
```
2019-07-30 15:51:41,712 fail2ban.filterpoll     [24142]: HEAVY   Checking /var/log/auth.log for being modified. Previous/current stats: (1564501872.1153636, 5133, 4395110) / (1564501872.1153636, 5133, 4395110). dt: 0.0
2019-07-30 15:52:07,774 fail2ban.filterpoll     [24142]: HEAVY   Checking /var/log/auth.log for being modified. Previous/current stats: (1564501872.1153636, 5133, 4395110) / (1564501872.1153636, 5133, 4395110). dt: 0.0
```
Time 1564501872 is 2019-07-30 15:51:12 (in GMT/UTC). 
**Do you really have UTC timezone?**

Normal flow in heavy debug after `has been modified` would look like:
```
 +  108 fail2ban.filter           TRACE |          filter-7 : processLine          | Working on line ...
 +  108 fail2ban.datedetector     HEAVY |    datedetector-5 : matchTime            | try to match time for line: ...
 +  108 fail2ban.datedetector     #06-L |    datedetector-6 : matchTime            |  search template (17) ...
 +  109 fail2ban.datedetector     HEAVY |    datedetector-5 : matchTime            |   try template #00: 
...
 +  110 fail2ban.datedetector     #06-L |    datedetector-6 : getTime              |   got time ...
 +  110 fail2ban.filter           HEAVY |          filter-5 : findFailure          | Looking for match of ...
 +  110 fail2ban.filter           HEAVY |          filter-5 : findFailure          |   Looking for prefregex ...
 +  110 fail2ban.filter           TRACE |          filter-7 : findFailure          |   Pre-filter matched {'content': '...
 +  110 fail2ban.filter           HEAVY |          filter-5 : findFailure          |   Looking for failregex 0 - ...
 +  110 fail2ban.filter           HEAVY |          filter-5 : findFailure          |   Looking for failregex 1 - ...
...
 +  110 fail2ban.filter           TRACE |          filter-7 : findFailure          |   Matched failregex 10: {'ip6': None, 'user': 'myhlj1374', 'dns': None, 'ip4': '192.0.2.1'}
 +  110 fail2ban.filter           INFO  |          filter-20: processLineAndAdd    | [sshd] Found 192.0.2.1 ...
 ```

Anyway nothing similar is visible at the moment (I think heavy debug excerpt is simply too short, so nothing happens at this time).

**Comment by sebres** [comment]
The wiki (link I provided you) says:
> note the time of values that fail2ban recognizes from the log-file will be converted using the system time zone (if not specified different) - be sure that the times, written from the corresponding service into the log, are not too old for the fail2ban;

The question about a timezone is extremely important, because:
- your timestamp in auth.log doesn't contain year (so fail2ban assumes current year, unless the time is in the future, then it would guess a previous year)
- let assume fail2ban works in UTC timezone and we have 15:51 (GMT)
- if your sshd works in CET, so it generates a message with `Jul 30 17:51` (in CET)
- fail2ban got this message (but it contains neither a year nor TZ), the datedetector thinks because `Jul 30 17:51` would be in the future - it assumes old log entry from last year so `Jul 30 17:51 2018` instead of `Jul 30 17:51 2019`.
- because the interval (1 year) exceeds `findtime` (as well as `bantime`) the messages are ignored as outdated.

See https://github.com/fail2ban/fail2ban/issues/2149#issuecomment-395042102 for similar issue.

If so be sure your system timezone is correct and refreshed across all services fail2ban monitoring (inclusive fail2ban itself).

**Comment by supriyo-biswas** [comment]
Thank you for pointing me in the right direction. I restarted my server to force all processes to run in the same timezone, and I also deleted `/var/log/auth.log*` to prevent any confusion. I'm now able to get attackers banned:

```bash
# fail2ban-client status sshd
Status for the jail: sshd
|- Filter
|  |- Currently failed:	3
|  |- Total failed:	50
|  `- File list:	/var/log/auth.log
`- Actions
   |- Currently banned:	3
   |- Total banned:	3
   `- Banned IP list:	5.189.140.71 112.85.42.194 153.36.236.151
```

**Comment by cljk** [comment]
OMG! Thank you guys - especially @sebres 

I had a similiar problem: A docker container with SSH logging to the host. I invested HOURS in investigating, why fail2ban (on the host) does not recognize and ban failed logins. I even posted on stackoverflow:
https://stackoverflow.com/questions/57593463/fail2ban-creating-second-sshd-jail-for-docker-container-log-does-not-work

The docker container simply used a different timezone....

Fast solution for me: set host timezone to UTC - so now both use UTC.
Perhaps I find a solution to switch dateformats of `rsyslog` to output TZ-info.

**Comment by nryc** [comment]
phew, same here.

So much time wasted to try to figure out why fail2ban isn't jailing anything and it was all because of a changed time zone.
