### ISSUE TITLE
ipset fails with bantime=-1

### ISSUE THREAD

**Issue by dadosch** [fail2ban/fail2ban#2487]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.10.4
- OS, including release name/version:  Arch Linux
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Fail2ban directly sets the bantime parameter to the ipset command, but ipset doesn't accept -1

#### Steps to reproduce
set bantime to -1, use ipset based banaction

#### Expected behavior
In this case (bantime=-1), fail2ban should set the bantime internally to 0, as the ipset documentation states:

> Zero timeout value means the entry is added permanent to the set.
> http://ipset.netfilter.org/ipset.man.html

**Comment by sebres** [comment]
This is fixed in newer version. See #2179 for details as well as workaround to fix it for you.
