### ISSUE TITLE
filter catching sshd kex_exchange_identification

### ISSUE THREAD

**Issue by Knudch** [fail2ban/fail2ban#2492]
I am looking for a filter which can catch the below shown issue
from secure log:
```
Aug  4 04:30:14 dns1 sshd[23936]: Connection from 159.89.41.181 port 60312 on 10.2.1.7 port 22
Aug  4 04:30:14 dns1 sshd[23936]: error: kex_exchange_identification: banner line contains invalid characters
```
What exactly the hackers are trying I dont know but maybe something with TLS
Port 443 WAN side are mapped to port 22
Both password and key auth are enabled.

With my limit filter knowledge I dont know how deal with that the attacker IP address is on a different line than the error message, the related lines can be found by the sshd[number]

Knud

### Environment:
- Fail2Ban version:  0.10.4-3.fc30
- OS: FC30 , 5.1.18-300.fc30.x86_64 
- [ X] Fail2Ban installed via OS/distribution mechanisms
- [ X] You have not applied any additional foreign patches to the codebase
- [ X] Some customizations were done to the configuration (provide details below is so)

### The issue:

_Summary here_

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
> What exactly the hackers are trying I dont know but maybe something with TLS
Port 443 WAN side are mapped to port 22

Hmm... would expect something like `Bad protocol version identification`, see #2404 in this case.

Anyway, for fail2ban >= 0.10 something like this would do the job:
```ini
[sshd]
mode = aggressive
failregex = %(known/failregex)s
            ^kex_exchange_identification: banner line contains invalid characters
```

**Comment by Knudch** [comment]
I have allready a filter running for Bad protocol....so it must be something else they are trying.
Anyway:
Your proposal.... shall that be in a new filter file or shall it be added to existing one ?
Sorry I have some trouble with the filter structure of fail2ban

**Comment by sebres** [comment]
> Sorry I have some trouble with the filter structure of fail2ban

Oh God, people... 
But you see the section name `[sshd]`? (filter's sections are `Definition` and `Init`).

> shall that be in a new filter file or shall it be added to existing one ?

Neither one nor other. 
Above it was an example for sshd-jail in `jail.local`.

Although if you want, you can extend the filter instead, here `filter.d/sshd.local`:
```ini
[Definition]
failregex = %(known/failregex)s
            ^kex_exchange_identification: banner line contains invalid characters
```

**Comment by Knudch** [comment]
Ok....It just seems not logical for me to put a filter function in a jail definition.
I made the filter.d/sshd.local solution then it also survives an update and it is clear it is extension.
Tested it..works perfect
Thanks
