### ISSUE TITLE
Wrong monit log path for Monit 5.20.0?

### ISSUE THREAD

**Issue by pierre-alain-b** [fail2ban/fail2ban#2495]
Hi,

Is this on purpose that the log file for monit is /var/log/monit and not /var/log/monit.log ?
https://github.com/fail2ban/fail2ban/blob/15734a923b226cac53e9a9fd606efa58a7be009c/config/jail.conf#L485

On Debian Buster, I had to change this so that it works.

**Comment by sebres** [comment]
Fixed in 5cf064a1126416b1143ea3925b290e824355170e.
Thx!
