### ISSUE TITLE
Unable process large log files

### ISSUE THREAD

**Issue by WHK102** [fail2ban/fail2ban#2497]
For httpd on CentOS7, have a example jail:

```
[demo]
enabled  = true
port     = 0:65535
logpath  = /home/small-site.com/logs/access_log_2019-08
maxretry = 1
action   = iptables-allports
bantime  = 10
findtime = 600
```

And example filter:

```
[Definition]
failregex = ^<HOST> -.*?".+?8aae25baff2ef9e3da0ac9ff82467823
```

In small-site.com httpd log file with 30kb of size and 2< request per seconds works fine, but in other virtual host with large log file (1gb using rotatelog) with 300< request per seconds no work.

I test using wget from my personal computer:

`$ wget -O- 'https://small-site.com/?x=8aae25baff2ef9e3da0ac9ff82467823'`

It's ok, the server ban me using iptables, but make same test on large log but no work. I try parse log using tail:

```
# tail -f /home/large-site.com/logs/access_log_2019-08 | grep 8aae25baff2ef9e3da0ac9ff82467823
x.x.x.x - - [06/Aug/2019:18:50:04 -0400] "GET /?x=31e58e064ad185a8d6228fc20f0995af HTTP/1.1" 200 33612 "-" "Wget/1.19.4 (linux-gnu)"
```

The request works fine but the fail2ban can no detect the payload:

```
# fail2ban-client status demo
Status for the jail: demo
|- Filter
|  |- Currently failed:	0
|  |- Total failed:	0
|  `- File list:	/home/large-site.com/logs/access_log_2019-08
`- Actions
   |- Currently banned:	0
   |- Total banned:	0
   `- Banned IP list:
```

The fail2ban service start fine without problems, load the log file, etc, but no detect the payload.

Small and large log files are same permission but different users:

```
# ls -lah /home/small-site.com/logs/access_log_2019-08 
-rw-r--r-- 1 root root 32K Aug  6 19:29 /home/small-site.com/logs/access_log_2019-08
# ls -lah /home/large-site.com/logs/access_log_2019-08 
-rw-r--r-- 1 root root 1.4G Aug  6 20:09 /home/large-site.com/logs/access_log_2019-08
```

My enviroment:

```
# uname -a
Linux whk.cl 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
# apachectl -v
Server version: Apache/2.4.6 (CentOS)
Server built:   Jul 29 2019 17:18:49
# fail2ban-client --version
Fail2Ban v0.9.7
```

Maybe it can be the size of the byte buffer written in the access log by apache? Maybe it's because Apache does not write line by line but a group of lines for each log write.

**Comment by sebres** [comment]
You have 2 non-greedy catch-all's in your regex - this is quasi doomed to fail (on long lines or large log-files)...
Just rewrite it more precise:
```ini
failregex = ^<HOST> [^"]*"[A-Z]+ /\S*[&?]x=8aae25baff2ef9e3da0ac9ff82467823
```
Additionally 0.9 is an outdated and slow version. So better upgrade it too.
