### ISSUE TITLE
_apache_error_client in apache-common.conf does not match my log

### ISSUE THREAD

**Issue by Nottulrut** [fail2ban/fail2ban#2499]
## Environment:
Tested on 2 differents environnements

### Env1
- Fail2Ban version (including any possible distribution suffixes): 0.10.2-2 
- OS, including release name/version: Ubuntu 18.04
- [x] Fail2Ban installed via OS/distribution mechanisms : Ubuntu repository
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)
- Apache2 version: 2.4.29-1ubuntu4.8
- Apache2 modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 headers_module (shared)
 mime_module (shared)
 mpm_event_module (shared)
 negotiation_module (shared)
 proxy_module (shared)
 proxy_http_module (shared)
 reqtimeout_module (shared)
 rewrite_module (shared)
 security2_module (shared)
 setenvif_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)
 unique_id_module (shared)

### Env2
- Fail2Ban version (including any possible distribution suffixes): 0.8.13-1
- OS, including release name/version: Debian8
- [x] Fail2Ban installed via OS/distribution mechanisms : Debian repository
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)
- Apache2 version:  2.4.10-10+deb8u14
- Apache2 modules:
core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 headers_module (shared)
 mime_module (shared)
 mpm_event_module (shared)
 negotiation_module (shared)
 proxy_module (shared)
 proxy_html_module (shared)
 proxy_http_module (shared)
 reqtimeout_module (shared)
 rewrite_module (shared)
 security2_module (shared)
 setenvif_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)
 unique_id_module (shared)
 xml2enc_module (shared)

## Explanation

I was testing the apache-modsecurity filter with :
`fail2ban-regex /var/log/apache2/error.log /etc/fail2ban/filter.d/apache-modsecurity.conf`
And it seems, that, in `filter.d/apache-common.conf`, `_apache_error_client` does not match what I have in my apache error log.

The value of `_apache_error_client`:
`_apache_error_client = <apache-prefix>\[(:?error|\S+:\S+)\]( \[pid \d+(:\S+ \d+)?\])? \[client <HOST>(:\d{1,5})?\]`

Whereas I have 2 [client ] block in `/var/log/apache2/error.log`, as in this example:
`[Wed Aug 07 10:07:29.931049 2019] [:error] [pid 1505:tid 140585855850240] [client XXX.XXX.XXX.XXX:YYYYY] [client XXX.XXX.XXX.XXX] ModSecurity: Access denied with code 403 ...`

I have modified the `apache_error_client` for test, like the following:
`_apache_error_client = <apache-prefix>\[(:?error|\S+:\S+)\]( \[pid \d+(:\S+ \d+)?\])? \[client <HOST>(:\d{1,5})?\] \[client (\d{1,3}.){3}\d{1,3}\]`
And then I have the expected matches with :
`fail2ban-regex /var/log/apache2/error.log /etc/fail2ban/filter.d/apache-modsecurity.conf`.

I'm using fail2ban / modsecurity with apache, on a WAF / Proxy server.

**Comment by Nottulrut** [comment]
Just to be sure, I have grep 'ErrorLog' and 'ErrorLogFormat' in my apache configuration, resulting in no match. I haven't modified it from the default. I don't know where the default is defined though.

**Comment by sebres** [comment]
Fixed in #2247
