### ISSUE TITLE
Difference between "fail2ban-client start" and "service fail2ban start" && how i can know fail2ban service is running

### ISSUE THREAD

**Issue by GaneshKandu** [fail2ban/fail2ban#2500]
``Question``
Difference between ``fail2ban-client start`` and ``service fail2ban start`` ?

**Comment by GaneshKandu** [comment]
Hi,
how i can know ``fail2ban`` service is running
``service fail2ban start`` command run with no error
``service fail2ban status`` shows its active
```
● fail2ban.service - LSB: Start/stop fail2ban
   Loaded: loaded (/etc/init.d/fail2ban; generated)
   Active: active (exited) since Wed 2019-08-14 04:11:03 PDT; 26s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 16162 ExecStart=/etc/init.d/fail2ban start (code=exited, status=0/SUCCESS)

Aug 14 04:11:03 132.compilor.com systemd[1]: Starting LSB: Start/stop fail2ban...
Aug 14 04:11:03 132.compilor.com systemd[1]: Started LSB: Start/stop fail2ban.
```
but ``ps aux | grep fail2ban`` shows no process where running

**Comment by sebres** [comment]
`fail2ban-client` is a client tool to control fail2ban, `fail2ban.service` is a wrapper for init-script (unit) to control the service (daemon)...
It looks like `/etc/init.d/fail2ban` or `fail2ban.service` generated for your distribution has some bug recognizing the fail2ban errors during the start process.
This is a matter of maintainers for your distribution.
