### ISSUE TITLE
Filter sshd not catching "Did not receive identification string...."

### ISSUE THREAD

**Issue by trupf** [fail2ban/fail2ban#2505]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.10.2-2.1
- OS, including release name/version: Debian Buster
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

I use the parameter "mode = aggressive" and the filter line 
`mdre-ddos = ^Did not receive identification string from <HOST>%(__suff)s$`
does not match any line in my auth.log file altough it contains lines which should match.

#### Steps to reproduce

activate the sshd filter and use "mode = ddos" or "mode = aggressive"

#### Expected behavior

A line like this one from my logfile should be matched:
`Jul 27 09:57:04 nas sshd[30922]: Did not receive identification string from 141.70.45.131 port 41656`

#### Observed behavior
filter does not match the above line

#### Any additional information

The reason for not matching is that the port number is included in the logfile line. Therfore the filter line should be changed to (see the "(__on_port_opt)s"-part):
`mdre-ddos = ^Did not receive identification string from <HOST>%(__on_port_opt)s%(__suff)s$`

**Comment by sebres** [comment]
Already fixed, see 8028d3940d0173582adede443f8692b510465917.
