### ISSUE TITLE
Ability to pass log line data to actions, or maybe just better documentation for it

### ISSUE THREAD

**Issue by raimondi1337** [fail2ban/fail2ban#2508]
### Environment:

- Fail2Ban version: **0.9.3-1**
- OS version: **Ubuntu 16.04.6 LTS**
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Being that fail2ban is a log parser, I expected that capturing and using data parsed from log lines would be a first party feature. I have been unable to find any documentation in the developer docs or on third party tutorials that indicates how to move data other than the built-ins (<ip>, <name, etc) from log lines to actions.

I am positive this must already a feature, but as I have been unable to find anything at all about how to do it, perhaps others would also benefit from some more obvious documentation.

#### Expected behavior

Given some specifically formatted log line such as:
`72.11.55.224 - - [01/Jan/2000:00:00:00 +0000] "POST 200 http://website.com/login address="email@domain.com" location="New York, NY United States"`
I would like to parse `address` and `location` into variables and pass them to my `slack-notify` action.

Then, in my `slack-notify` action:
`banaction = /bin/bash slack_notify.sh "<ip>" "<name>" "<address>" "<location>"`

This will give my script additional information about the log line that invoked that ban, which I can then include in my Slack message for everyone to not read.

#### Observed behavior

The documentation for the variables available in actions is pretty sparse in and of itself, and I can not find a single word about extracting data from log lines, creating custom variables, passing additional log data to actions, etc. None of those search terms appear to yield anything relevant.

It's readily apparent how to pass a static variable from a jail to an action:
```
[my-jail]
ban-action = slack-notify[my_var=somestring]
```
But it is not apparent how to pass data from the filter(?) up to the jail(?) or even how to just pass the whole log line so that I can parse it myself in a bash script.

**Comment by sebres** [comment]
> But it is not apparent how to pass data from the filter(?) up to the jail(?) or even how to just pass the whole log line so that I can parse it myself in a bash script.

Well it is possible directly but this feature is implemented in fail2ban >= 0.10 only. See #1698 for details.
And this is well documented in our [wiki](https://github.com/fail2ban/fail2ban/wiki) as well as in the man page jail.conf.5.

> Fail2Ban version: 0.9.3-1

As already said it is firstly introduced in v.0.10 so you cannot do it this way (directly) in v.0.9, but...
You can use tag `<matches>` and grep/parse it in the action (which is a shell script) by yourself.

Here you can find an example how you can specify that for both versions - https://github.com/fail2ban/fail2ban/issues/1935#issuecomment-339113985.

**Comment by raimondi1337** [comment]
I appreciate the prompt response!

> You can use tag `<matches>` and grep/parse it in the `actionban`/`actionunban` (which are the shell scripts) by yourself.

Where is the documentation for the <matches> tag?
I can not find any references to it, or a list of available tags even, on fail2ban.org/wiki or on fail2ban.readthedocs.io

**Comment by sebres** [comment]
> Where is the documentation for the `<matches>` tag?

Banned by `man`?.. :smile:

https://manpages.debian.org/unstable/fail2ban/jail.conf.5.en.html#Action_Tags

<pre><b>matches</b>
           concatenated string of the log file lines of the matches that generated the ban. Many characters interpreted by shell get escaped to prevent injection, nevertheless use with caution.
</pre>

**Comment by raimondi1337** [comment]
> > Where is the documentation for the `<matches>` tag?
> 
> Banned by `man`?.. 
> 
> https://manpages.debian.org/unstable/fail2ban/jail.conf.5.en.html#Action_Tags
> 
> matches
>            concatenated string of the log file lines of the matches that generated the ban. Many characters interpreted by shell get escaped to prevent injection, nevertheless use with caution.

I write JavaScript for a living what is a man page :laughing: 
Thank you!
