### ISSUE TITLE
Enhance documentation for usage in combination with published docker containers

### ISSUE THREAD

**Issue by cljk** [fail2ban/fail2ban#2511]
I have no really issue with fail2ban (not anymore since it´s solved) but as me there are several people out there who came over the same problem:

That `fail2ban` is detecting and banning an IP - but connections to published docker containers are still possible - at least when using the `iptables` banaction.

Compare:
* http://blog.amigapallo.org/2016/04/14/configuring-fail2ban-and-iptables-to-get-along-with-docker/
* https://github.com/fail2ban/fail2ban/issues/2292
* https://serverfault.com/questions/943262/fail2ban-with-dockerhost-mode-networking-is-making-iptables-entry-but-not-stop

I know that the problem really is located in docker or the way it implements the networking functionality (it inserts its own iptables chain in FORWARD) - but with a simple documentation enhancement we could prevent people to run into the same issue again and again.

@hcderaad suggested in https://github.com/fail2ban/fail2ban/issues/2292 to just add `chain = DOCKER-USER` to the jail config - and this really did it for me. I duplicated `recidive` and some other rules with the different chain and now my docker containers are protected too.

So my suggestion is (since the wiki is protected) to insert a paragraph about specialities in combination with docker-containers published to the network.

There should be mentioned two things:
* filtering logfiles from containers written to the host: 
   * logfiles have to be of same timezone in container and host (had this issue) OR 
   * the logfile timestamps should contain a timezone-info
* when using `iptables` the jail has to be configured to block traffic to docker containers - like by adding parameter `chain = DOCKER_USER`

€dit:
For the timezone problem perhaps you could link to 
https://bobcares.com/blog/change-time-in-docker-container/ - I think the most useful method is to mount the `timezone` 
```
docker run \
    -v /etc/timezone:/etc/timezone:ro \
    -v /etc/localtime:/etc/localtime:ro \
```

AGAIN
I KNOW it´s not the problem of fail2ban itself - but docker is not so uncommon today...

**Comment by sebres** [comment]
> since the wiki is protected

What do you mean? The [wiki](https://github.com/fail2ban/fail2ban/wiki) here is open for everyone registered on github.
Don't you see "New page" (green) button there?

Also github says:
> Any GitHub user can create and edit pages to use for documentation, examples, support, or anything you wish.

So I'd appreciate if this is moved to the wiki and this "not issue" gets closed.

**Comment by cljk** [comment]
> > since the wiki is protected
> 
> What do you mean? The [wiki](https://github.com/fail2ban/fail2ban/wiki) here is open for everyone registered on github.
> Don't you see "New page" (green) button there?
> 
> Also github says:
> 
> > Any GitHub user can create and edit pages to use for documentation, examples, support, or anything you wish.
> 
> So I'd appreciate if this is moved to the wiki and this "not issue" gets closed.

Oh... I´m sorry. You´re right.

I´ve been on 
http://www.fail2ban.org/wiki/index.php/MANUAL_0_8

Sorry... I´ll try to add my suggestions there.
