### ISSUE TITLE
Unable to set blocktype and returntype in jail configuration (IPv6 version)

### ISSUE THREAD

**Issue by GingkoFr** [fail2ban/fail2ban#2512]
Hello,

I have the same problem than in [issue 1884](https://github.com/fail2ban/fail2ban/issues/1884), that is, being able to specify a **blocktype** value that is different for each jail configuration.

The given solution works effectively, but only in **IPv4**.

There seems to be solution for **IPv6**, in [issue 2278](https://github.com/fail2ban/fail2ban/issues/2278), but this solution is likely to work for all jails, not for any specific jail configuration.

So I want to know :
How can a specify a blocktype value which will be active in IPv6 **AND** in a specific jail configuration?

Actually,I would like, instead of specifying a blocking method, redirect to several specific **iptable** chains which implement groups of blocking and logging commands.

Regards.

**Comment by sebres** [comment]
> How can a specify a blocktype value which will be active in IPv6 AND in a specific jail configuration?

Some parameters of actions belong to conditional section (like `Init?family=inet6`).
So for parameter `blocktype` normally it will create a parameter with name `blocktype?family=inet6` internally, but you'd not be able to specify it from jail (the name contains `=` character).

I working on different conditional parameter handling, but unless it is implemented...
The simplest way would be create own action derivative and overwrite both block types like in #2278, for example `action.d/iptables-blocktype.conf`: 
```ini
[INCLUDES]
before = iptables.conf

[Definition]
[Init]
blocktype = DROP
blocktype6 = %(blocktype)s
[Init?family=inet6]
blocktype = %(Init/blocktype6)s
```
this should allow to specify the value from any jail:
```ini
# both IP-types at once:
[jail1]
action = iptables-blocktype[blocktype="ACCEPT"]
# or blocktype for both IP-types differently:
[jail2]
action = iptables-blocktype[blocktype="REJECT --reject-with icmp-port-unreachable", blocktype6="REJECT --reject-with icmp6-port-unreachable"]
```

**Comment by GingkoFr** [comment]
Ok. If I understand well, lines beginning by “[” and ending by “]” are the starting of sections.

But here you write “[Init…]” sections like if they were nested inside the “[Definition]” section.

Does this mean that there is a hierarchy between sections, in such a way than some type of sections are expected to (or only can) be nested inside other type of sections?

Are there other type of sections which are expected to be nested?

**Comment by sebres** [comment]
> Does this mean that there is a hierarchy between sections...
> Are there other type of sections which are expected to be nested?

This mean that default value of `blocktype6` is the same as `blocktype`.

Nothing is expected. This is simply an example, in this way it is allowed to set both values `blocktype` and `blocktype6` (if they are equal) by supplying only a single parameter `blocktype` (like in example above with `ACCEPT`).

**Comment by GingkoFr** [comment]
Ok, but you didn't answer to my question : is there a hierarchical relation between [Definition] and [Init…] sections? I'd like to understand how this could actually work.

Anyway, I tried to create a action.d/iptables-blocktype.local _(there is no iptables-blocktype.conf file)_, with the following, like you did with some variations:

> [INCLUDES]
> before = iptables.conf
> 
> [Definition]
> [Init]
> blocktype = REJECT --reject-with icmp-port-unreachable
> blocktype6 = %(blocktype)s
> 
> [Init?family=inet6]
> blocktype = %(Init/blocktype6)s
 
… and next in my jail.local file, I put

> [apache-proxy]
> action = iptables-blocktype[blocktype="http.REJ"]
> 
> [sshd]
> action = iptables-blocktype[blocktype="serv.REJ"]

(those blocktype values are names of iptables chains created elsewhere; apache-proxy is a custom created jail for blocking proxy connections attempts on normal http server as there are thousands of them on one of my servers).

As a result, I get the following error in systemctl, and fail2ban doesn't restart :

> Failed during configuration: Error in action definition 'iptables-blocktype[blocktype="serv.REJ"]': Bad value substitution: option 'blocktype?family=inet6' in section 'Init' contains an interpolation key 'init/blocktype6' which is not a valid option name. Raw value: '%(Init/blocktype6)s'

System is Linux Debian 10 buster (using systemd); fail2ban version is 0.10.2-2.1.

Gingko

**Comment by sebres** [comment]
> I'd like to understand how this could actually work.

Parameters supplied to action (in jail) overwrites values of Init and Definition sections.
Init section is just for compatibility purposes (I did not know your fail2ban version) and overwrites values or usable in substitutions of Definition section.

> I get the following error in systemctl, and fail2ban doesn't restart :

Looks like section values named convention does not work in your version (I don't know exactly the 0.10th version where it was firstly implemented). Additionally you should possibly use run-time interpolation (`<param>` instead of config interpolation `%(param)s`).
Also note your version can have an issue with recursive interpolation.

So rewrite it rather like here:
```ini
[INCLUDES]
before = iptables.conf

[Definition]

[Init]
common-blocktype = DROP
blocktype = <common-blocktype>
blocktype6 = <common-blocktype>

[Init?family=inet6]
blocktype6 = <common-blocktype>
blocktype = <blocktype6>
```
So to set both, use 
`iptables-blocktype[common-blocktype="http.REJ"]` 
or even 
`iptables-blocktype[blocktype="http.REJ", blocktype6="http.REJ"]` 

Also perhaps you should use another include here as common (either `iptables-allports` or `iptables-multiport` instead of `iptables.conf`).
