### ISSUE TITLE
Are there plans for a Ubuntu specific path config file?

### ISSUE THREAD

**Issue by AdamPerkins** [fail2ban/fail2ban#2515]
If just have installed fail2ban on different Ubuntu-Mate systems and have seen some problems.
I guess Debian and Ubuntu are similar but not equal in their philosophy of log filenames.

F. ex. in path-common.conf: syslog_local0 = /var/log/messages
I checked that on my Rasberry Pi3 (a Debian derivat) and the log really exists. But on different Ubuntu systems I checked this log is not existing.

I came to the above problem because I wanted to enable mySQL and failed. 
Here what I found:
path-common.conf: mysql_log = %(syslog_daemon)s
path-debian.conf: syslog_daemon =  /var/log/daemon.log
daemon.log exist only on Debian not on Ubuntu systems.

Anyway, mySQL logs on Ubuntu into: /var/log/mysql/error.log

Here are 2 links which may can help:
https://www.plesk.com/blog/featured/linux-logs-explained/
https://mkleine.de/blog/2017/08/11/fail2ban-und-mysql-5-7-filter-funktioniert-nicht-direkt/

**Comment by sebres** [comment]
Normally it should be a matter of maintainers of fail2ban packet for Ubuntu (may be better would be to ask directly there).

I have neither Ubuntu nor the time to check or fix that.
Thus the issue going to @fail2ban/maintainers resp. @fail2ban/contributors.
But if someone would provide proper `path-ubuntu.conf`, welcome with PR.

**Comment by AdamPerkins** [comment]
PR done in: https://github.com/fail2ban/fail2ban/pull/2517

**Comment by sebres** [comment]
further in #2517
