### ISSUE TITLE
Sonarr/Radarr support

### ISSUE THREAD

**Issue by gurabli** [fail2ban/fail2ban#2516]
Hi,
Support for login logs are just added to Sonarr (hopefully will get to Radarr soon). 

https://github.com/Sonarr/Sonarr/issues/2760#issuecomment-525499152

What jail should be used? 
Thanks!

**Comment by sebres** [comment]
> What jail should be used?

Don't know we have such jail ever.

But you can write your own, e. g. for v.0.10 (or higher) it looks like new simple section in `jail.local`:
```ini
[sonarr]
filter =
failregex = ^\s*[Warn] Auth: Auth-Failure ip <ADDR> username '<F-USER>[^']+</F-USER>'
#           ^\s*[Info] Auth: <F-MLFFORGET><F-MLFGAINED>Auth-Success</F-MLFGAINED></F-MLFFORGET> ip <ADDR> username '<F-USER>[^']+</F-USER>'
```
The last commented rule (with tag `<F-MLFFORGET>...`) is optional and simply allowing to "forget" possible invalid auth-attempts (e. g. up to `maxrerty` typo's) when an authentication succeeds (for the same user), in case multi-line handling is expected (you need to react on some messages without IP, etc).

You should still specify another parameters, like port, banaction, etc (and don't forget `enabled = true`) for the jail.

**Comment by sebres** [comment]
And I don't see which date time format is used here, so perhaps you have to set proper `datepattern` for that.
Or provide here an excerpt with log examples, so we could take a look later.

**Comment by gurabli** [comment]
Many thanks, I really appreciate your errorts! I'm not an expert at all, I can enable and configure already made jails and actions. I monitored thr situation for long time, and finally the logging was added to Sonarr. All thr users should use it behind a reverse proxy. I would suggest, the best would be if you could comment at Sonarr so that the implementation is done properly from Sonarr's side.

**Comment by jt196** [comment]
Folks just having a little play around with Sonarr and F2B, the filter provided above doesn't seemed to have worked. 

My logs show the following:

`20-9-2 16:16:01.5|Warn|Auth|Auth-Failure ip <ip_address> username '<username>'`

It's a bit of a handful getting these regex right, am I missing the datepattern from the above and/or is it related to the pipes at the start? I need to have a bit of a dig back into regex as it's been a while. My amateur attempt with the pipes updated:

```
[Definition]
filter =
failregex = ^\s*Warn|Auth|Auth-Failure ip <ADDR> username '<F-USER>[^']+</F-USER>'
```

**Comment by jt196** [comment]
@sebres don't know if you're able to chime in and help here?

**Comment by sebres** [comment]
1. You have to specify datepattern.
2. You have to escape pipes with backslash, so `|` as `\|` in regex (otherwise it means **or**, so `A|B` - match A or B).
```
$ fail2ban-regex -d '^%y-%m-%d %H:%M:%S\.%f\|' "20-9-2 16:16:01.5|Warn|Auth|Auth-Failure ip 192.0.2.1 username 'tester'" "^\s*Warn\|Auth\|Auth-Failure ip <ADDR> username '<F-USER>[^']+</F-USER>'"
...
Lines: 1 lines, 0 ignored, 1 matched, 0 missed
```
And jail could be enough (you don't necessarily need a filter):
```ini
[sonarr]
filter =
datepattern = ^%%y-%%m-%%d %%H:%%M:%%S\.%%f\|
failregex = ^\s*Warn\|Auth\|Auth-Failure ip <ADDR> username '<F-USER>[^']+</F-USER>'
```
Note that in some old versions datepattern cannot be specified in jail, and in filter (of v.0.9) it belongs to the `Init` section and not to `Definition` section.

**Comment by jt196** [comment]
@sebres thanks for the quick reply! 

OK, so I tested my error log inside the Docker container as per your commands above, and it's showing the same output code i.e. success. Checking the sonarr.txt log tail and this error message shows up. 

After restarting the container, when I run `fail2ban-client status sonarr` it's showing up as Currently Failed: 0. Another filter shows up as 1, so I guess it's working. Any suggestions to debug this?

**Comment by sebres** [comment]
> After restarting the container, when I run fail2ban-client status sonarr it's showing up as Currently Failed: 0

Once already processed messages are normally ignored in fail2ban, so you have to repeat a failure after restart (wait for some new messages) or delete fail2ban.sqlite database where the last log-position is saved (before you start it).

> Any suggestions to debug this?

It is good described in our [wiki](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works).

You can debug the parameters fail2ban gets obtained from config with `fail2ban-client -d | grep sonarr` (control datepattern and failregex).
Otherwise (if nothing other helps) set `loglevel` to 5 and repeat (but produce or wait for new failure messages) and check `/var/log/fail2ban.log` hereafter.

**Comment by jt196** [comment]
OK just wrestled a bit with the filters there - changed the `[Definition]` bit to `[sonarr]` as above and it broke things till I changed it back. 

Here's the output from the grep command:

```
['add', 'sonarr', 'auto']
['set', 'sonarr', 'usedns', 'warn']
['set', 'sonarr', 'addfailregex', "^\\s*Warn\\|Auth\\|Auth-Failure ip <ADDR> username '<F-USER>[^']+</F-USER>'"]
['set', 'sonarr', 'datepattern', '^%y-%m-%d %H:%M:%S\\.%f\\|']
['set', 'sonarr', 'maxretry', 3]
['set', 'sonarr', 'maxmatches', 3]
['set', 'sonarr', 'findtime', '10m']
['set', 'sonarr', 'bantime', '10800']
['set', 'sonarr', 'ignorecommand', '']
['set', 'sonarr', 'logencoding', 'auto']
['set', 'sonarr', 'addlogpath', '/var/log/sonarr.txt', 'head']
['set', 'sonarr', 'addaction', 'iptables-multiport']
['multi-set', 'sonarr', 'action', 'iptables-multiport', [['actionstart', '<iptables> -N f2b-sonarr\n<iptables> -A f2b-sonarr -j RETURN\n<iptables> -I INPUT -p tcp -m multiport --dports 80,443 -j f2b-sonarr'], ['actionstop', '<iptables> -D INPUT -p tcp -m multiport --dports 80,443 -j f2b-sonarr\n<iptables> -F f2b-sonarr\n<iptables> -X f2b-sonarr'], ['actionflush', '<iptables> -F f2b-sonarr'], ['actioncheck', "<iptables> -n -L INPUT | grep -q 'f2b-sonarr[ \\t]'"], ['actionban', '<iptables> -I f2b-sonarr 1 -s <ip> -j <blocktype>'], ['actionunban', '<iptables> -D f2b-sonarr -s <ip> -j <blocktype>'], ['name', 'sonarr'], ['port', '80,443'], ['protocol', 'tcp'], ['chain', '<known/chain>'], ['actname', 'iptables-multiport'], ['blocktype', 'REJECT --reject-with icmp-port-unreachable'], ['returntype', 'RETURN'], ['lockingopt', '-w'], ['iptables', 'iptables <lockingopt>'], ['blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unreachable'], ['iptables?family=inet6', 'ip6tables <lockingopt>']]]
['start', 'sonarr']
```

**Comment by jt196** [comment]
Fixed it! The Sonarr container had a different timezone set up, so was showing 1hr before. I seemed to have broken the Nextcloud filter now but I think that's it for the day. Cheers for your help Sergey / @sebres. Have a good evening, Sir!

**Comment by sebres** [comment]
Glad it works now. 

By the way...
> changed the [Definition] bit to [sonarr] as above and it broke things

Beside `[DEFAULT]` section, filter file operates with sections `[Definition]` and `[Init]`, whereas in jail file every section (like `[sonarr]`) means a jail (which can, but not must include a filter).
I wrote above that you can use it directly in jail (don't need a filter file) in newer versions (>= 0.10), so my example above was for `jail.local`, not for `filter.d/*.conf`.

**Comment by sebres** [comment]
> however there is an error in the datepattern. %y in Python is a 2 digit year (I.E. 26 for 2026) so it should be %Y (2026 for 2026):

Don't you see which timestamp it was intended to parse? In `20-9-2 16:16:01.5` the year is 2 digit.
