### ISSUE TITLE
apache-autu it does not work

### ISSUE THREAD

**Issue by flybirdkh** [fail2ban/fail2ban#2522]
it does not work when I use apache-auth to fail2ban the ip.
now the jail.conf is like this 
![image](https://user-images.githubusercontent.com/53069666/64305897-7a5d0680-cfc3-11e9-84cd-df9444f20583.png)
and the error log at /var/log/httpd24/error_log
![image](https://user-images.githubusercontent.com/53069666/64305997-db84da00-cfc3-11e9-9cd9-744638fa52b3.png)
but it does not work
![image](https://user-images.githubusercontent.com/53069666/64306067-1850d100-cfc4-11e9-84eb-3430dc22f601.png)
The system is CentOS 7.5 and the vision of fail2ban is 
![image](https://user-images.githubusercontent.com/53069666/64306144-4afac980-cfc4-11e9-8cc7-24bcf23cdb1d.png)

also sshd does work sucessfully
![image](https://user-images.githubusercontent.com/53069666/64306204-88f7ed80-cfc4-11e9-812d-f7bc4bb112ba.png)

how to solve this problem?

**Comment by sebres** [comment]
Filter (tested with current 0.9) matches the log line without any issue:
```
$ fail2ban-regex -vv '[Thu Sep 05 09:27:54.434737 2019] [auth_basic:error] [pid 131525] [client 192.0.2.1:62345] AH01618: user adasd not found: /pun/sys/dashboard' /etc/fail2ban/filter.d/apache-auth.conf

...
Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
| ...
|   3) [1] ^\[\] \[(:?error|\S+:\S+)\]( \[pid \d+(:\S+ \d+)?\])? \[client <HOST>(:\d{1,5})?\] (AH01618: )?user .*? not found(: )?\S*(, referer: \S+)?\s*$
|      192.0.2.1  Thu Sep 05 09:27:54 2019
| ...
`-
...
Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.00 sec]
```
Please provide the whole log-line as text (don't use an image).

For more details or possible reason see FAQ in our wiki - [Fail2ban does not detect some authentication failures resp. banning does not occurred](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works).
Especially check how many attempts (compared with `maxretry`) the IP doing in time of `findtime` as well as whether the time in log corresponding the real time of server (wrong timezone issue).

**Comment by flybirdkh** [comment]
1 matched,but still does not work.what i change can make it work?
which log i can show

**Comment by sebres** [comment]
You understand that "still does not work" does not help to solve the issue at all.

I asked for the full log-line (not a truncated like in screenshot) from the apache error_log.
Also I showed you a command that could check it for you. 
Have you tried it? Does it show a match with your fail2ban version (and full line)?
Have you read the first entry in link to wiki I provided?

You can also check fail2ban.log, whether some entries `INFO [apache-auth] Found ...` are available. 
If yes - filter works basically.
Then take a look how many entries are recognized (consider your `maxretry`) in some period (`findtime`) to cause a ban.
(If your fail2ban log-level is NOTICE, set it to INFO and restart fail2ban).

Additionally an excerpt from fail2ban config-dump may help, so provide result of:
```
fail2ban-client -d | grep apache-auth
```

**Comment by flybirdkh** [comment]
The httpd24's error_log
[Mon Sep 09 16:56:37.979576 2019] [auth_basic:error] [pid 172025] [client 202.120.3.248:63969] AH01618: user adsad not found: /pun/sys/dashboard
[Mon Sep 09 16:56:40.470330 2019] [auth_basic:error] [pid 172025] [client 202.120.3.248:63969] AH01618: user adsad not found: /pun/sys/dashboard
[Mon Sep 09 16:56:41.899879 2019] [auth_basic:error] [pid 172025] [client 202.120.3.248:63969] AH01618: user adsad not found: /pun/sys/dashboard
[Mon Sep 09 16:56:43.331650 2019] [lua:info] [pid 164601] [client 202.120.3.248:63972] req_protocol="HTTP/1.1" req_handler="proxy-server" req_method="GET" req_accept="text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01" req_user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763" res_content_length="" req_content_type="" res_content_encoding="" req_status="200" req_origin="" time_user_map="106.159" local_user="hpccf" req_referer="http://202.120.58.243/pun/sys/dashboard/batch_connect/sessions" res_content_language="" req_port="80" log_time="2019-09-09T08:56:43.331390Z" req_server_name="202.120.58.243" log_hook="ood" req_accept_charset="" req_hostname="202.120.58.243" res_content_location="" res_content_disp="" req_is_websocket="false" remote_user="hpccf" res_location="" req_user_ip="202.120.3.248" req_is_https="false" req_filename="proxy:http://localhost/pun/sys/dashboard/batch_connect/sessions.js?_=1567746552583" req_uri="/pun/sys/dashboard/batch_connect/sessions.js" time_proxy="14.112" res_content_type="text/javascript; charset=utf-8" req_accept_language="zh-cn" req_cache_control="" req_accept_encoding="gzip, deflate", referer: http://202.120.58.243/pun/sys/dashboard/batch_connect/sessions
[Mon Sep 09 16:56:43.689427 2019] [auth_basic:error] [pid 172025] [client 202.120.3.248:63969] AH01618: user adsad not found: /pun/sys/dashboard
[Mon Sep 09 16:56:47.364763 2019] [auth_basic:error] [pid 172025] [client 202.120.3.248:63969] AH01618: user adsad not found: /pun/sys/dashboard
[Mon Sep 09 16:56:50.165292 2019] [auth_basic:error] [pid 172025] [client 202.120.3.248:63969] AH01618: user adsad not found: /pun/sys/dashboard
[Mon Sep 09 16:56:53.033198 2019] [auth_basic:error] [pid 172025] [client 202.120.3.248:63969] AH01618: user adsad not found: /pun/sys/dashboard
[Mon Sep 09 16:56:54.329696 2019] [lua:info] [pid 164605] [client 202.120.3.248:63978] req_protocol="HTTP/1.1" req_handler="proxy-server" req_method="GET" req_accept="text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01" req_user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763" res_content_length="" req_content_type="" res_content_encoding="" req_status="200" req_origin="" time_user_map="99.058" local_user="hpccf" req_referer="http://202.120.58.243/pun/sys/dashboard/batch_connect/sessions" res_content_language="" req_port="80" log_time="2019-09-09T08:56:54.329440Z" req_server_name="202.120.58.243" log_hook="ood" req_accept_charset="" req_hostname="202.120.58.243" res_content_location="" res_content_disp="" req_is_websocket="false" remote_user="hpccf" res_location="" req_user_ip="202.120.3.248" req_is_https="false" req_filename="proxy:http://localhost/pun/sys/dashboard/batch_connect/sessions.js?_=1567746552584" req_uri="/pun/sys/dashboard/batch_connect/sessions.js" time_proxy="13.058" res_content_type="text/javascript; charset=utf-8" req_accept_language="zh-cn" req_cache_control="" req_accept_encoding="gzip, deflate", referer: http://202.120.58.243/pun/sys/dashboard/batch_connect/sessions
[Mon Sep 09 16:56:54.490916 2019] [auth_basic:error] [pid 172025] [client 202.120.3.248:63969] AH01618: user adsad not found: /pun/sys/dashboard
[Mon Sep 09 16:56:57.566320 2019] [auth_basic:error] [pid 172025] [client 202.120.3.248:63969] AH01618: user adsad not found: /pun/sys/dashboard
[Mon Sep 09 16:56:59.799259 2019] [auth_basic:error] [pid 172025] [client 202.120.3.248:63969] AH01618: user adsad not found: /pun/sys/dashboard
[Mon Sep 09 16:57:01.984239 2019] [auth_basic:error] [pid 172025] [client 202.120.3.248:63969] AH01618: user adsad not found: /pun/sys/dashboard

The fail2ban's log 
2019-09-08 03:48:01,322 fail2ban.server         [229214]: INFO    rollover performed on /var/log/fail2ban.log
2019-09-08 03:52:33,846 fail2ban.filter         [229214]: INFO    [sshd] Found 179.151.4.91
2019-09-08 03:52:35,841 fail2ban.filter         [229214]: INFO    [sshd] Found 179.151.4.91
2019-09-08 03:58:28,674 fail2ban.filter         [229214]: INFO    [sshd] Found 103.79.143.216
2019-09-08 03:58:30,401 fail2ban.filter         [229214]: INFO    [sshd] Found 103.79.143.216
2019-09-08 04:00:08,028 fail2ban.actions        [229214]: NOTICE  [sshd] Unban 51.89.151.214
2019-09-08 04:05:59,745 fail2ban.filter         [229214]: INFO    [sshd] Found 204.48.19.178
2019-09-08 04:05:59,756 fail2ban.filter         [229214]: INFO    [sshd] Found 204.48.19.178
2019-09-08 04:06:01,392 fail2ban.filter         [229214]: INFO    [sshd] Found 204.48.19.178
2019-09-08 04:06:06,543 fail2ban.filter         [229214]: INFO    [sshd] Found 88.214.26.8
2019-09-08 04:06:06,551 fail2ban.filter         [229214]: INFO    [sshd] Found 88.214.26.8
2019-09-08 04:06:08,483 fail2ban.filter         [229214]: INFO    [sshd] Found 88.214.26.8
2019-09-08 04:20:13,616 fail2ban.filter         [229214]: INFO    [sshd] Found 40.76.65.78
2019-09-08 04:20:15,499 fail2ban.filter         [229214]: INFO    [sshd] Found 40.76.65.78
2019-09-08 04:22:04,725 fail2ban.filter         [229214]: INFO    [sshd] Found 204.48.19.178
2019-09-08 04:22:04,735 fail2ban.filter         [229214]: INFO    [sshd] Found 204.48.19.178
2019-09-08 04:22:07,185 fail2ban.filter         [229214]: INFO    [sshd] Found 204.48.19.178
2019-09-08 04:25:51,961 fail2ban.filter         [229214]: INFO    [sshd] Found 204.48.19.178
2019-09-08 04:25:51,972 fail2ban.filter         [229214]: INFO    [sshd] Found 204.48.19.178
2019-09-08 04:25:52,965 fail2ban.actions        [229214]: NOTICE  [sshd] Ban 204.48.19.178
2019-09-08 04:25:53,582 fail2ban.filter         [229214]: INFO    [sshd] Found 204.48.19.178
2019-09-08 05:01:45,872 fail2ban.filter         [229214]: INFO    [sshd] Found 92.63.194.90
2019-09-08 05:01:45,881 fail2ban.filter         [229214]: INFO    [sshd] Found 92.63.194.90
2019-09-08 05:01:48,202 fail2ban.filter         [229214]: INFO    [sshd] Found 92.63.194.90
2019-09-08 05:16:03,344 fail2ban.filter         [229214]: INFO    [sshd] Found 40.76.65.78
2019-09-08 05:16:04,789 fail2ban.filter         [229214]: INFO    [sshd] Found 40.76.65.78
2019-09-08 05:20:56,297 fail2ban.filter         [229214]: INFO    [sshd] Found 88.214.26.171
2019-09-08 05:20:56,307 fail2ban.filter         [229214]: INFO    [sshd] Found 88.214.26.171
2019-09-08 05:20:58,306 fail2ban.filter         [229214]: INFO    [sshd] Found 88.214.26.171
2019-09-08 05:23:40,178 fail2ban.actions        [229214]: NOTICE  [sshd] Unban 51.158.120.115
2019-09-08 05:32:31,144 fail2ban.actions        [229214]: NOTICE  [sshd] Unban 202.5.19.42
2019-09-08 05:33:30,381 fail2ban.actions        [229214]: NOTICE  [sshd] Unban 186.103.223.10
2019-09-08 05:37:46,324 fail2ban.filter         [229214]: INFO    [sshd] Found 157.245.104.124
2019-09-08 05:37:46,336 fail2ban.filter         [229214]: INFO    [sshd] Found 157.245.104.124
2019-09-08 05:37:47,653 fail2ban.filter         [229214]: INFO    [sshd] Found 157.245.104.124
2019-09-08 05:37:49,873 fail2ban.filter         [229214]: INFO    [sshd] Found 157.245.104.124
2019-09-08 05:37:49,883 fail2ban.filter         [229214]: INFO    [sshd] Found 157.245.104.124
2019-09-08 05:37:50,831 fail2ban.actions        [229214]: NOTICE  [sshd] Ban 157.245.104.124
2019-09-08 05:37:51,615 fail2ban.filter         [229214]: INFO    [sshd] Found 157.245.104.124

sshd works seccessfully but apache-auth does not.

[root@mu15 ~]# fail2ban-client -d | grep apache-auth
['add', 'apache-auth', 'systemd']
['set', 'apache-auth', 'usedns', 'warn']
['set', 'apache-auth', 'maxretry', 3]
['set', 'apache-auth', 'addignoreip', '127.0.0.1/8']
['set', 'apache-auth', 'logencoding', 'auto']
['set', 'apache-auth', 'bantime', 86400]
['set', 'apache-auth', 'ignorecommand', '']
['set', 'apache-auth', 'findtime', 600]
['set', 'apache-auth', 'addfailregex', '^\\[\\] \\[(:?error|\\S+:\\S+)\\]( \\[pid \\d+(:\\S+ \\d+)?\\])? \\[client <HOST>(:\\d{1,5})?\\] (AH(01797|01630): )?client denied by server configuration: (uri )?\\S*(, referer: \\S+)?\\s*$']
['set', 'apache-auth', 'addfailregex', '^\\[\\] \\[(:?error|\\S+:\\S+)\\]( \\[pid \\d+(:\\S+ \\d+)?\\])? \\[client <HOST>(:\\d{1,5})?\\] (AH01617: )?user .*? authentication failure for "\\S*": Password Mismatch(, referer: \\S+)?$']
['set', 'apache-auth', 'addfailregex', '^\\[\\] \\[(:?error|\\S+:\\S+)\\]( \\[pid \\d+(:\\S+ \\d+)?\\])? \\[client <HOST>(:\\d{1,5})?\\] (AH01618: )?user .*? not found(: )?\\S*(, referer: \\S+)?\\s*$']
['set', 'apache-auth', 'addfailregex', '^\\[\\] \\[(:?error|\\S+:\\S+)\\]( \\[pid \\d+(:\\S+ \\d+)?\\])? \\[client <HOST>(:\\d{1,5})?\\] (AH01614: )?client used wrong authentication scheme: \\S*(, referer: \\S+)?\\s*$']
['set', 'apache-auth', 'addfailregex', '^\\[\\] \\[(:?error|\\S+:\\S+)\\]( \\[pid \\d+(:\\S+ \\d+)?\\])? \\[client <HOST>(:\\d{1,5})?\\] (AH\\d+: )?Authorization of user \\S+ to access \\S* failed, reason: .*$']
['set', 'apache-auth', 'addfailregex', '^\\[\\] \\[(:?error|\\S+:\\S+)\\]( \\[pid \\d+(:\\S+ \\d+)?\\])? \\[client <HOST>(:\\d{1,5})?\\] (AH0179[24]: )?(Digest: )?user .*?: password mismatch: \\S*(, referer: \\S+)?\\s*$']
['set', 'apache-auth', 'addfailregex', "^\\[\\] \\[(:?error|\\S+:\\S+)\\]( \\[pid \\d+(:\\S+ \\d+)?\\])? \\[client <HOST>(:\\d{1,5})?\\] (AH0179[01]: |Digest: )user `.*?' in realm `.+' (not found|denied by provider): \\S*(, referer: \\S+)?\\s*$"]
['set', 'apache-auth', 'addfailregex', '^\\[\\] \\[(:?error|\\S+:\\S+)\\]( \\[pid \\d+(:\\S+ \\d+)?\\])? \\[client <HOST>(:\\d{1,5})?\\] (AH01631: )?user .*?: authorization failure for "\\S*":(, referer: \\S+)?\\s*$']
['set', 'apache-auth', 'addfailregex', '^\\[\\] \\[(:?error|\\S+:\\S+)\\]( \\[pid \\d+(:\\S+ \\d+)?\\])? \\[client <HOST>(:\\d{1,5})?\\] (AH01775: )?(Digest: )?invalid nonce .* received - length is not \\S+(, referer: \\S+)?\\s*$']
['set', 'apache-auth', 'addfailregex', "^\\[\\] \\[(:?error|\\S+:\\S+)\\]( \\[pid \\d+(:\\S+ \\d+)?\\])? \\[client <HOST>(:\\d{1,5})?\\] (AH01788: )?(Digest: )?realm mismatch - got `.*?' but expected `.+'(, referer: \\S+)?\\s*$"]
['set', 'apache-auth', 'addfailregex', "^\\[\\] \\[(:?error|\\S+:\\S+)\\]( \\[pid \\d+(:\\S+ \\d+)?\\])? \\[client <HOST>(:\\d{1,5})?\\] (AH01789: )?(Digest: )?unknown algorithm `.*?' received: \\S*(, referer: \\S+)?\\s*$"]
['set', 'apache-auth', 'addfailregex', "^\\[\\] \\[(:?error|\\S+:\\S+)\\]( \\[pid \\d+(:\\S+ \\d+)?\\])? \\[client <HOST>(:\\d{1,5})?\\] (AH01793: )?invalid qop `.*?' received: \\S*(, referer: \\S+)?\\s*$"]
['set', 'apache-auth', 'addfailregex', '^\\[\\] \\[(:?error|\\S+:\\S+)\\]( \\[pid \\d+(:\\S+ \\d+)?\\])? \\[client <HOST>(:\\d{1,5})?\\] (AH01777: )?(Digest: )?invalid nonce .*? received - user attempted time travel(, referer: \\S+)?\\s*$']
['set', 'apache-auth', 'addaction', 'firewallcmd-ipset']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'actionban', 'ipset add fail2ban-<name> <ip> timeout <bantime> -exist']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'actionstop', 'firewall-cmd --direct --remove-rule ipv4 filter <chain> 0 -p <protocol> -m multiport --dports <port> -m set --match-set fail2ban-<name> src -j <blocktype>\nipset flush fail2ban-<name>\nipset destroy fail2ban-<name>']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'actionstart', 'ipset create fail2ban-<name> hash:ip timeout <bantime>\nfirewall-cmd --direct --add-rule ipv4 filter <chain> 0 -p <protocol> -m multiport --dports <port> -m set --match-set fail2ban-<name> src -j <blocktype>']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'actionunban', 'ipset del fail2ban-<name> <ip> -exist']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'protocol', 'tcp']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'chain', 'INPUT']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'lockingopt', '-w']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'known/known/name', 'default']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'blocktype', 'REJECT --reject-with icmp-port-unreachable']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'known/lockingopt', '-w']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'known/known/port', 'ssh']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'known/protocol', 'tcp']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'known/known/lockingopt', '-w']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'port', 'http,https']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'known/known/chain', 'INPUT']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'known/name', 'default']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'known/known/protocol', 'tcp']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'known/bantime', '600']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'bantime', '86400']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'iptables', 'iptables <lockingopt>']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'known/__name__', 'Init']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'returntype', 'RETURN']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'known/returntype', 'RETURN']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'known/known/__name__', 'Init']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'known/known/returntype', 'RETURN']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'name', 'apache-auth']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'known/known/blocktype', 'REJECT --reject-with icmp-port-unreachable']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'known/port', 'ssh']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'known/iptables', 'iptables <lockingopt>']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'known/chain', 'INPUT_direct']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'known/blocktype', 'REJECT --reject-with icmp-port-unreachable']
['set', 'apache-auth', 'action', 'firewallcmd-ipset', 'known/known/iptables', 'iptables <lockingopt>']
['start', 'apache-auth']

**Comment by sebres** [comment]
> `['add', 'apache-auth', 'systemd']`

Your jail `apache-auth` uses systemd backend (so it monitoring systemd journal), but you need monitor a log file.
So change your backend, like this:
```ini
[apache-auth]
backend = auto
```

**Comment by flybirdkh** [comment]
Thank you very much ,it works

**Comment by ajax0103** [comment]
In my case, my older version 8 install needed the apache-common.conf from version 9.

**v8 line**
_apache_error_client = \[[^]]*\] \[(:?error|\S+:\S+)\]( \[pid \d+(:\S+ \d+)?\])? \[client <HOST>(:\d{1,5})?\]

**v9 line**
_apache_error_client = \[\] \[(:?error|\S+:\S+)\]( \[pid \d+(:\S+ \d+)?\])? \[client <HOST>(:\d{1,5})?\]

While I know keeping at latest version would have fixed this, my production server's OS can't be updated at this time.
