### ISSUE TITLE
sshd filter not work with failled publickey authentication

### ISSUE THREAD

**Issue by yet-a-teapot** [fail2ban/fail2ban#2533]
Hello,

### Environment:

- Fail2Ban v0.10.2
- OS, including release name/version: 
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customization were done to the configuration (provide details below is so)

### The issue:

The regex for matching publickey authentication failure in sshd filter : 
```
^Failed \b(?!publickey)\S+ for (?P<cond_inv>invalid user )?<F-USER>(?P<cond_user>\S+)|(?(cond_inv)(?:(?! from ).)*?|[^:]+)</F-USER> from <HOST>%(__on_port_opt)s(?: ssh\d*)?(?(cond_user): |(?:(?:(?! from ).)*)$)
```

not work. It seem it's because the regex use negative lookahead assertion `(?!publickey)`.

#### Steps to reproduce

 Set `LogLevel VERBOSE` in sshd_config and log to server with bad private key, we obtain a line line like this in sshd log : 
 ```
Failed publickey for xxxxxx from xxxx::xxxx port 54910 ssh2: RSA SHA256:b/uj8GcUQY5S4kJ8FTwo9khA/98G/ighT4QCCOdUtus
```

But `fail2ban-regex systemd-journal --print-all-matched -m '_SYSTEMD_UNIT=ssh.service + _COMM="/usr/sbin/sshd -D"' /etc/fail2ban/filter.d/sshd.conf ` don't find it.

#### Expected behavior
 
Use `fail2ban-regex systemd-journal --print-all-matched -m '_SYSTEMD_UNIT=ssh.service + _COMM="/usr/sbin/sshd -D"' /etc/fail2ban/filter.d/sshd.conf` find line like : 

```
Failed publickey for xxxxxx from xxxx::xxxx port 54910 ssh2: RSA SHA256:b/uj8GcUQY5S4kJ8FTwo9khA/98G/ighT4QCCOdUtus
```

#### Observed behavior

I resolved the problem by replacing negative lookahead assertions `(?!publickey)` by positive assertion `(?=publickey)`, now fail2ban-regex find it : 

```
fail2ban-regex systemd-journal --print-all-matched -m '_SYSTEMD_UNIT=ssh.service + _COMM="/usr/sbin/sshd -D"' /etc/fail2ban/filter.d/sshd.conf

Running tests
=============

Use   failregex filter file : sshd, basedir: /etc/fail2ban
Use         maxlines : 1
Use      datepattern : Default Detectors
Use         systemd journal
Use         encoding : UTF-8
Use    journal match : _SYSTEMD_UNIT=ssh.service + _COMM=/usr/sbin/sshd -D


Results
=======

Failregex: 70 total
|-  #) [# of hits] regular expression
|   4) [32] ^Failed \b(?=publickey)\S+ for (?P<cond_inv>invalid user )?<F-USER>(?P<cond_user>\S+)|(?(cond_inv)(?:(?! from ).)*?|[^:]+)</F-USER> from <HOST>(?: port \d+)?(?: on \S+(?: port \d+)?)?(?: ssh\d*)?(?(cond_user): |(?:(?:(?! from ).)*)$)
|  20) [4] ^<F-MLFFORGET><F-NOFAIL>Accepted publickey</F-NOFAIL></F-MLFFORGET> for \S+ from <HOST>(?:\s|$)
|  21) [34] ^<F-NOFAIL>Connection from</F-NOFAIL> <HOST>
`-

Ignoreregex: 0 total

Date template hits:

Lines: 282 lines, 0 ignored, 70 matched, 212 missed
[processed in 0.09 sec]

|- Matched line(s):
...
|  2019-09-29T10:09:17.337444backup sshd[5578]: Failed publickey for xxxxx from xxxx::xxxx port 43562 ssh2: RSA SHA256:b/uj8GcUQY5S4kJ8FTwo9khA/98G/ighT4QCCOdUtus
...
```

#### Any customizations done to /etc/fail2ban/ configuration

I use *systemd-journal* and i modify `journalmatch` in `/etc/fail2ban/filter.d/sshd.conf`  for use with Debian : 

```
journalmatch =  _SYSTEMD_UNIT=ssh.service + _COMM="/usr/sbin/sshd -D"
```

In my `/etc/fail2ban/jail.local` : 

```
[DEFAULT]
backend = systemd
```

**Comment by sebres** [comment]
>  It seem it's because the regex use negative lookahead assertion (?!publickey).

Sure, and this is exactly the intention... see https://github.com/fail2ban/fail2ban/issues/2188#issuecomment-407425179 for details.

Shortly, there are several public keys one could try before an authentication takes place.

Thus closed as duplicate.
