### ISSUE TITLE
Apache-common.conf

### ISSUE THREAD

**Issue by Azertyker** [fail2ban/fail2ban#2544]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): 0.10.2-2~bpo9+1
- OS, including release name/version: debian stretch
- [x] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
After we reload fail2ban, we have this issue:
```
Oct 13 09:03:09 CX6 fail2ban-server[60190]:  No section: 'Definition'
Oct 13 09:03:10 CX6 fail2ban-server[60190]: Server ready
Oct 13 09:03:30 CX6 systemd[1]: Reloading Fail2Ban Service.
Oct 13 09:03:30 CX6 fail2ban-client[60281]:  No section: 'Definition'
Oct 13 09:03:30 CX6 fail2ban-client[60281]:  No section: 'Definition'
Oct 13 09:03:30 CX6 fail2ban-client[60281]:  No section: 'Definition'
Oct 13 09:03:54 CX6 fail2ban-client[60281]:  NOK: ("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",)
Oct 13 09:03:54 CX6 fail2ban-client[60281]: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Oct 13 09:03:54 CX6 systemd[1]: fail2ban.service: Control process exited, code=exited status=255
Oct 13 09:03:54 CX6 systemd[1]: Reload failed for Fail2Ban Service.
```

_Summary here_

#### Steps to reproduce
apt-get install -t stretch-backports fail2ban
add this part to /etc/fail2ban/jail.d/defaults-debian.conf:
```
[apache-common]
enabled = true
bantime = 1200
```
systemctl restart fail2ban.service
systemctl reload fail2ban.service

#### Any additional information
```
fail2ban-regex /var/log/apache2/website.net-access.log /etc/fail2ban/filter.d/apache-common.conf -vvvvv

Running tests
=============

Use   failregex filter file : apache-common, basedir: /etc/fail2ban
Traceback (most recent call last):
  File "/usr/bin/fail2ban-regex", line 34, in <module>
    exec_command_line()
  File "/usr/lib/python3/dist-packages/fail2ban/client/fail2banregex.py", line 685, in exec_command_line
    if not fail2banRegex.start(args):
  File "/usr/lib/python3/dist-packages/fail2ban/client/fail2banregex.py", line 586, in start
    if not self.readRegex(cmd_regex, 'fail'): # pragma: no cover
  File "/usr/lib/python3/dist-packages/fail2ban/client/fail2banregex.py", line 368, in readRegex
    self.setMaxLines(optval)
  File "/usr/lib/python3/dist-packages/fail2ban/client/fail2banregex.py", line 275, in setMaxLines
    self._filter.setMaxLines(int(v))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
```
2019-10-13 09:03:54,300 fail2ban.transmitter    [60190]: WARNING Command ['reload', '--all', [], [['set', 'syslogsocket', 'auto'], ['set', 'loglevel', 'DEBUG'], ['set', 'logtarget', '/var/log/fail2ban.log'], ['set', 'dbfile', '/var/lib$
['start', 'apache-common']]] has failed. Received TypeError("int() argument must be a string, a bytes-like object or a number, not 'NoneType'",)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/fail2ban/server/transmitter.py", line 57, in proceed
    ret = self.__commandHandler(command)
  File "/usr/lib/python3/dist-packages/fail2ban/server/transmitter.py", line 102, in __commandHandler
    self.__commandHandler(cmd)
  File "/usr/lib/python3/dist-packages/fail2ban/server/transmitter.py", line 127, in __commandHandler
    return self.__commandSet(command[1:])
  File "/usr/lib/python3/dist-packages/fail2ban/server/transmitter.py", line 274, in __commandSet
    self.__server.setMaxLines(name, int(value))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
> add this part to /etc/fail2ban/jail.d/defaults-debian.conf ... 
> `[apache-common]`
> `enabled = true`

What you're trying to do?
1. Either you should create jail-file with the same name (so section and file names should be the same) or you should create `/etc/fail2ban/jail.local` where you can define/enable multiple jails.
2. There is no such default jail with this name in fail2ban (see `jail.conf` for all known jails), so you need to set a filter/failregex and other expected parameters if you want create your own jail.

See [wiki :: Proper fail2ban configuration](https://github.com/fail2ban/fail2ban/wiki/Proper-fail2ban-configuration) for more info.

**Comment by letoff** [comment]
I had the same problem on Debian: No section: 'Definition' in apache-common.conf into the logfile.

So I manually updated the file and changed '[DEFAULT]' with 'Definition' and daemon is now running. Not sure if it's a bug or Debian related

**Comment by sebres** [comment]
[apache-common.conf](https://github.com/fail2ban/fail2ban/blob/0.10/config/filter.d/apache-common.conf) indeed doesn't have section `Definition`, but it is not expected especially because it is an include file.
Which version exactly it is (fail2ban and fail2ban-python)?

But all tests of all apache jails passing with this config (current 0.10 ... 1.0 with any python versions), so I don't think it is fail2ban or python related thing.

If you try to use `apache-common` as a jail, it is not correct - as already said, it is just a helper and used only as an include in other apache filters (jails). See [jail.conf](https://github.com/fail2ban/fail2ban/blob/8f83242c25a957d34478e9604600066695be7998/config/jail.conf#L255) for available apache jails.

**Comment by letoff** [comment]
I should have read better sorry for that and thanks for you explanation sebres.
