### ISSUE TITLE
Checking log with Cyrillic chars in date. 

### ISSUE THREAD

**Issue by ibsteklodom** [fail2ban/fail2ban#2551]
### Environment:
- Fail2Ban version 0.11.0.dev3
- Ubuntu 16.04.5 LTS

### The issue:

If log have date with cyrillic chars then regex will not success.
If we will add new string without cyrillic chars in start this log then regex will success. 
All this check in fail2ban-regex

#### Steps to reproduce
1) create log file with strings(CHECK.log):
```
82.221.105.6 - - [15/**окт**/2019:03:56:15 +0000] "GET https://1.12.13.14/favicon.ico HTTP/1.0" 404 1816 "-" "python-requests/2.6.0" 10
185.53.88.92 - - [17/**окт**/2019:09:59:37 +0000] "GET https://1.12.13.14/vtigerservice.php HTTP/1.0" 404 1816 "-" "python-requests/2.19.1 CPython/2.7.5 Linux/3.10.0-1062.1.2.el7.x86_64" 7
```
2) create new filter in filter.d(badbots.conf):
```ini
[Definition]
badbot = python-requests/2.6.0|python-requests/2.19.1
failregex = <HOST>.*GET.*HTTP.*"(?:badbot)s).*$
```
3) run check:
fail2ban-regex -v CHECK.log "badbots.conf" --print-all-matched
4) Result will be:
Failregex: 0 total
5) Add string in log file:
```
102.221.105.77 - - [14/**oct**/2019:04:56:20 +0000] "GET https://1.12.13.14/favicon.ico HTTP/1.0" 404 1816 "-" "python-requests/2.6.0" 10
```
6) Run check again:
fail2ban-regex -v CHECK.log "badbots.conf" --print-all-matched
7) Result will be:
Failregex: 3 total

#### Expected behavior
Result will be one:
Failregex: 3 total

#### Observed behavior
Different results

#### Relevant lines from monitored log files in question:
```
102.221.105.77 - - [14/oct/2019:04:56:20 +0000] "GET https://1.12.13.14/favicon.ico HTTP/1.0" 404 1816 "-" "python-requests/2.6.0" 10
82.221.105.6 - - [15/окт/2019:03:56:15 +0000] "GET https://1.12.13.14/favicon.ico HTTP/1.0" 404 1816 "-" "python-requests/2.6.0" 10
185.53.88.92 - - [17/окт/2019:09:59:37 +0000] "GET https://1.12.13.14/vtigerservice.php HTTP/1.0" 404 1816 "-" "python-requests/2.19.1 CPython/2.7.5 Linux/3.10.0-1062.1.2.el7.x86_64" 7
```

**Comment by sebres** [comment]
see https://github.com/fail2ban/fail2ban/issues/2477#issuecomment-514190185
