### ISSUE TITLE
Bash script banning on UFW, not on Fail2ban (Cloudflare)

### ISSUE THREAD

**Issue by acs-ferreira** [fail2ban/fail2ban#2552]
- Ubuntu 18.04
- Fail2Ban v0.10.2

I have a script that reads some IPs and try to ban them.
It works fine with UFW, but not with Fail2ban, which bans on Cloudflare.

Here is the script:

```
# UFW
for line in `cat /usr/local/src/drop_full`; do
  /usr/sbin/ufw insert 1 deny from "$line"
done

# Cloudflare (trough Fail2ban jail)
for line in `cat /usr/local/src/drop_full`; do
  /usr/bin/fail2ban-client set proxy banip "$line"
done
```

Fail2ban log says it is banning the IPs, one by one (correct IPs appears), but nothing appears on Cloudflare...

```
2019-10-21 22:30:29,319 fail2ban.actions        [1051]: NOTICE  [proxy] Ban 168.205.72.0/22
2019-10-21 22:30:29,654 fail2ban.actions        [1051]: NOTICE  [proxy] Ban 168.206.0.0/16
```

but if i issue the exact same command **manually**, it works. Fail2ban log is the same and IP appears on Cloudflare:

`/usr/bin/fail2ban-client set proxy banip 1.2.3.4`

**Comment by sebres** [comment]
I guess it does nothing with **manually**, rather it is subnet you're trying to ban in your batch (as I see `[proxy] Ban 168.205.72.0/22` in log, and manually you're trying single IP)... 
Looks like either the action or the Cloudflare self does not support subnets banning.
(Let alone fail2ban still does not officially supports subnets too, so it can work with some actions and don't with other, see #927).

**Comment by acs-ferreira** [comment]
You are right, the Cloudflare action is written to block only single IPs and nothing else supported by Cloudflare, like subnets or ASN.
