### ISSUE TITLE
setup.py does not copy man pages

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [fail2ban/fail2ban#2561]
## Environment

I download fail2ban from git repository and install it by
`python2 setup.py install`. There is no additional steps involve before or after
the setup script. I use 0.10.4 version of fail2ban on CentOS 7.

## The issue

I realized that there is no man pages that are copied from the `man`
directory. Do I need to take another steps before or after the setup script in
order to install manuals?

**Comment by sebres** [comment]
> I realized that there is no man pages that are copied from the man
directory. 

It does not install several things, for example service-unit resp. init-script, logrotate, etc.
But also distribution related fail2ban-configuration (include `/etc/fail2ban/paths-distro.conf` and related jail.conf adjustment).
Normally it is a matter of maintainers of corresponding distribution...

If you're not familiar, it'd be better to install it from repository suitable for your distribution.

> Do I need to take another steps before or after the setup script in
order to install manuals?

In debian it looks like:
```bash
dh_installman man/*.[15]
```
Related fail2ban.spec in EPEL package it is:
```
mkdir -p %{buildroot}%{_mandir}/man{1,5}
install -p -m 644 man/*.1 %{buildroot}%{_mandir}/man1
install -p -m 644 man/*.5 %{buildroot}%{_mandir}/man5
```
No idea where `_mandir` points in centos resp. rhel (`/usr/share/man` or `/usr/local/share/man`?).

**Comment by BerkhanBerkdemir** [comment]
> > I realized that there is no man pages that are copied from the man
> > directory.
>
> It does not install several things, for example service-unit resp.
> init-script, logrotate, etc.
> But also distribution related fail2ban-configuration (include
> `/etc/fail2ban/paths-distro.conf` and related jail.conf adjustment).
> Normally it is a matter of maintainers of corresponding distribution...
>
> If you're not familiar, it'd be better to install it from repository suitable
> for your distribution.
>
> > Do I need to take another steps before or after the setup script in
> > order to install manuals?
>
> In debian it looks like:
>
> ```bash
> dh_installman man/*.[15]
> ```
>
> Related fail2ban.spec in EPEL package it is:
>
> ```bash
> mkdir -p %{buildroot}%{_mandir}/man{1,5}
> install -p -m 644 man/*.1 %{buildroot}%{_mandir}/man1
> install -p -m 644 man/*.5 %{buildroot}%{_mandir}/man5
> ```
>
> No idea where `_mandir` points in CentOS resp. RHEL (`/usr/share/man`
> or `/usr/local/share/man`?).

Thank you for the suggestion, @sebres!

I wanted to ask that question because I'm writing an Ansible role, and I was
curious either would be a way to install man pages via `setup.py` or it is a
distro specific, therefore, did not implemented.
