### ISSUE TITLE
Sendmail filter regexes fail for PIDs > 999999

### ISSUE THREAD

**Issue by hensema** [fail2ban/fail2ban#2562]
In config/filter.d/sendmail-auth.conf the following line will fail:
```
failregex = ^%(__prefix_line)s\w{14}: (\S+ )?\[(?:IPv6:<IP6>|<IP4>)\]( \(may be forged\))?: possible SMTP attack: command=AUTH, count=\d+$
```
It limits sendmail queue IDs to max 14 chars. However when sendmail as a pid > 999999 then the queue id will get longer and therefore the line will never match.

I recommend supporting at least 20 characters for queue ids.

**Comment by hvanmegen** [comment]
Added a pull request for this issue: https://github.com/fail2ban/fail2ban/pull/2563
