### ISSUE TITLE
Is it possible to set findtime lower than one second?

### ISSUE THREAD

**Issue by AlphaJack** [fail2ban/fail2ban#2571]
### Environment: 
- fail2ban 0.10.4-2

### The issue:
I'm testing my webserver with a DoS tool, and I can read on the logs the flood of requests returning a status code of 400 or 408.  
While I can work on my webserver configuration to limit the requests it can accept, I was wondering if I could use fail2ban to help (among other things) mitigating a DDoS attack.
Unfortunately, It seems that the minimum time frame for the `findtime` parameter is 1s.
Is it possible to lower it? 
How would it impact the performances and the resource usage?
Webserver logs reports up to 250 requests per second, and not even 20 are normal for a regular user.

**Comment by sebres** [comment]
> Is it possible to lower it?

For which purposes it'd be needed? 
Parameter `findtime` is only important in combination with `maxretry`, so if you cannot decrease `findtime`, simply increase a value of `maxretry`.

Although I don't think that 20 rps is "normal for a regular user", but...
Following configuration use a time "burst" of 5 seconds and bans an IP after 100 requests in 5 seconds (so by 20 rps in average).
```ini
findtime = 5
maxretry = 100
```
And on 250 rps it would ban immediately - already after 100 attempts (no matter how fast they occurring), they should be just in the time window of 5 second).

But better use some tools or modules/plugins for your web-server already signaling an attack (or at least some violation). Counting requests by yourself (fail2ban) is ugly.
For example if you use nginx, you can use `ngx_http_limit_req_module` and filter `nginx-limit-req` (#1236), and following jail configuration:
```ini
[ddos]
logpath = /var/log/...path-to-log-with-limits-violations.log
port = http,https
...
filter = nginx-limit-req
findtime = 1
maxretry = 1
```
so the module inside a web-server would count the requests, not the fail2ban... and if fail2ban noticed summarized log-message like this:
```
2019/12/12 20:01:02 [error] 256554#0: *99927 limiting requests, excess: 1.852 by zone "one", client: 192.0.2.1, server: example.com, request: "POST /index.htm HTTP/1.0", host: "exmaple.com"
```
it could be already recognized as a signal to ban it (you'd not capture thousands of log entries for each request to notice a DoS attempts) and shouldn't ignore "parasite" log-traffic from legitimate users.
Also note stuff from [wiki :: Best practice](https://github.com/fail2ban/fail2ban/wiki/Best-practice), it is especially important under DDoS circumstances.

If your web-server does not have such functionality, iptables (or some other netfilters) have also proper mechanisms to recognize "bad" traffic and signal it to the log as summarized entry after some burst/analyse (e. g. for multiple connections or too "high" incoming traffic or too many packets from single IP or subnet). Sure, the keep-alive may bother good recognition here, but it is nevertheless possible.
