### ISSUE TITLE
fail2ban bind log parsing

### ISSUE THREAD

**Issue by chifu1234** [fail2ban/fail2ban#2576]
Hi guys

Im using fail2ban 0.10.4, to parse my security log from the bind (BIND 9.11.5-P4-5.1-Debian)services. 
I deployed fail2ban with latest Docker conatiner from https://github.com/crazy-max/docker-fail2ban. 
I made the following custom patterns: 

**fail2ban/filter.d/bind.conf**
```
[Definition]

failregex = ^ client @0x.{12} <HOST>#[0-9]{5} \([a-zA-Z.-]*\): query \(cache\) '[a-zA-Z.-]*/[A|AAAA]/IN' denied$
```
**fail2ban/jail.d/named.conf**
```
[bind]
action = dummy
filter   = bind
enabled  = true
logpath  = /var/named/log/security.log
```

Now im adding the following line to the /var/named/log/security.log file:
```
16-Dec-2019 22:18:27.175 client @0x7fedac0b8200 1.1.1.1#36926 (live.github.com): query (cache) 'live.github.com
/A/IN' denied
```
But now i cant see that the dummy action is triggered in the logs. I can just see the following lines from the DEBUG logs:
```
fail2ban    | 2019-12-16 23:40:21,241 fail2ban.filterpyinotif [1]: DEBUG   Event queue size: 16
fail2ban    | 2019-12-16 23:40:21,242 fail2ban.filterpyinotif [1]: DEBUG   <_RawEvent cookie=0 mask=0x2 name='' wd=2 >
```
Does anybody have any guess what Im doing wrong here?
I did tried to use the filters from named-refused but I had the behavior as with my own.
I also use fail2ban with my ssh log and had no issues there :dancer: 

Thank you for your help guys ;)
Cheers, Kevin

**Comment by sebres** [comment]
Time (zone) issue?

The time in log you added is `22:18:27` but the logs of fail2ban that you provided shows `23:40:21`.
If your `findtime` for the jail is below 1.5h this log line will be ignored as obsolete.

Anyway the log line is matched with current filter `named-refused` as well as with regex you provided above.
