### ISSUE TITLE
Does not work on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by stanislavromanov** [fail2ban/fail2ban#2577]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): Fail2Ban v0.10.2
- OS, including release name/version: Ubuntu 18.04 LTS
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Since Ubuntu 18.04 does not create/use `/var/log/auth.log` fail2ban refuses to start. Ubuntu 18.04 have access log via systemd, you can check them with `journalctl -u ssh.service`. 

#### Steps to reproduce
1. Have ubuntu 18.04 lts
2. `sudo apt-get update && sudo apt-get install fail2ban`
3. It will never start/work

#### Expected behavior
I suppose it should read the logs from `journalctl -u ssh.service` instead of `/var/log/auth.log`.

### Configuration, dump and another helpful excerpts
```
● fail2ban.service - Fail2Ban Service
   Loaded: loaded (/lib/systemd/system/fail2ban.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2019-12-21 12:32:59 UTC; 8min ago
     Docs: man:fail2ban(1)
  Process: 3707 ExecStart=/usr/bin/fail2ban-server -xf start (code=exited, status=255)
  Process: 3698 ExecStartPre=/bin/mkdir -p /var/run/fail2ban (code=exited, status=0/SUCCESS)
 Main PID: 3707 (code=exited, status=255)

Dec 21 12:32:59 SERVER-01 systemd[1]: Starting Fail2Ban Service...
Dec 21 12:32:59 SERVER-01 systemd[1]: Started Fail2Ban Service.
Dec 21 12:32:59 SERVER-01 fail2ban-server[3707]:  No file(s) found for glob /var/log/auth.log
Dec 21 12:32:59 SERVER-01 fail2ban-server[3707]:  Failed during configuration: Have not found any log file for sshd jail
Dec 21 12:32:59 SERVER-01 fail2ban-server[3707]:  Async configuration of server failed
Dec 21 12:32:59 SERVER-01 systemd[1]: fail2ban.service: Main process exited, code=exited, status=255/n/a
Dec 21 12:32:59 SERVER-01 systemd[1]: fail2ban.service: Failed with result 'exit-code'.
```

Sorry if this is not the right place to report it, however I thought I should tell that it does not work on latest lts release of ubuntu server.

**Comment by sebres** [comment]
It is rather a matter of @fail2ban/maintainers for Ubuntu (or debian) distribution (expected changes in packet for `paths-debian.conf`).

But it may be also considered as configuration issue (the backend or logpath parameters are definitely belonging to).
Anyway you can fix it simply by yourself, just set the `backend` parameter in your jail.local for sshd jail:
```ini
[sshd]
backend = systemd
enabled = true
```

**Comment by stanislavromanov** [comment]
@sebres 

Thank you very much, I got it running by using this config you provided.
