### ISSUE TITLE
Option to skip banning on startup

### ISSUE THREAD

**Issue by brianjmurrell** [fail2ban/fail2ban#2584]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.9.7
- OS, including release name/version: Fedora 31
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

It would be nice to have an option to disable fail2ban from installing bans that existed prior to a restart.  I.e. It should assume that the bans that were in place before it restarted are still there because they are done in a manner that persists it restarting.

In my case, I have an action which installs the IPs to be banned into ipsets (which of course are referenced by iptables rules) on my router, not on the host running fail2ban, so when the fail2ban host restarts, the banned IPs on the router are still active across the reboot.

Therefore, fail2ban does not need to re-instate them.  The most it should do it remove any bans that expired while it was stopped.

#### Steps to reproduce
Pretty obvious I think.

#### Expected behavior
Bans are not re-instated on restart, but expired bans are removed.

#### Observed behavior
Bans are added to ipsets on the remote node where they already exist.  Because each ban is an ssh round-trip to the router, this turns out to be very expensive to do.

#### Any additional information
None.

### Configuration, dump and another helpful excerpts
N/A

#### Any customizations done to /etc/fail2ban/ configuration
Probably not necessary to see exactly how I am doing it.  I think the explanation above should be sufficient to understand the issue.

#### Relevant parts of /var/log/fail2ban.log file:
N/A

#### Relevant lines from monitored log files in question:
N/A

**Comment by brianjmurrell** [comment]
More, or most generically, this option would probably be best named as `persistent_bans` or somesuch since it could be applied in many situations.

One could probably even do it on the `fail2ban` running machine by wrapping the `actionban`/`actionunban` with a script that did an `iptables-save` and then having the machine do an `iptables-restore` (or all equivalent actions with `ipset`s if one uses those instead -- which one should for anything more than a trivial number of rules) on restart.

I'm not sure that the above scenario is more efficient than just having `fail2ban` re-instate the bans itself, but it is just another example of a configuration where an `persistent_bans` option would be useful.

It seems to me like this would need to be an option set per action.

**Comment by sebres** [comment]
Every ticket that is already banned gets a `restored` flag:

- so you could check `<restored>` in `actionban` to ignore that;
- or you'd set `norestored = true` in this action, then fail2ban would ignore it for you.

Implemented in first versions of v.0.10. See #1669 for more information.
