### ISSUE TITLE
Ban the Bots

### ISSUE THREAD

**Issue by lonniegecko** [fail2ban/fail2ban#2585]
I think almost all bots should be banned.  I do think the major search engines are OK.  However, I feel that all the other bots have no purpose other than to create an inventory of your site or they are scraping information, and that if they asked I would say NO.

This would be an enhancement request but I did not see anywhere to mark it as such.

### Environment:
- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

Why would I want someone coming up to my house and if the door was open to go in and inventory all of my assets?  In terms of a webserver, the door has to remain open to provide service, but bots should not be allowed unless they are from a legitimate search engine.

I have no regex experience and only recently began to use fail2ban for sshd blocking.

```
```

**Comment by sebres** [comment]
There are already several filters in fail2ban as well as certain approaches to ban some kind of the bots.
And NO - this is impossible to have a common thing allowing you to ban everything.
This issue neither asking for particular approach nor helping to solve some certain "attacking" scenario.
But note also this is fail2ban development repository and not a place for HowTo's.
