### ISSUE TITLE
Release 0.11

### ISSUE THREAD

**Issue by yorickvP** [fail2ban/fail2ban#2586]
It's been over a year since the latest release. [People are asking distros](https://github.com/NixOS/nixpkgs/pull/67931) to include versions from git, because of all the new features. We would love to have these new features, so it might be time for a new stable release :).

cc: @Izorkin

**Comment by sebres** [comment]
0.12? This is unknown to me.
0.11 were the current development version that would be released next time.

**Comment by yorickvP** [comment]
Oh, sorry. Edited :)

**Comment by szepeviktor** [comment]
@yarikoptic Could it be that Debian packaging was lat done 1 year ago?
https://packages.qa.debian.org/f/fail2ban.html

Thank you.

**Comment by sebres** [comment]
Well, the last release was 1 year ago :( https://github.com/fail2ban/fail2ban/releases ).
I'll try to make a new release for both (0.10 / 0.11) as soon as possible.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by sebres** [comment]
Yrsssss. 
Been released today [0.10.5](https://github.com/fail2ban/fail2ban/releases/tag/0.10.5) version has.

For 0.11th version reserved tomorrow is.
Hrrrm, yes!

**Comment by szepeviktor** [comment]
Thank Yu Yoda!

![kép](https://user-images.githubusercontent.com/952007/72155332-30da5900-33b3-11ea-9aed-688a278e6d33.png)

**Comment by sebres** [comment]
Release [0.11.1](https://github.com/fail2ban/fail2ban/releases/tag/0.11.1) is out!

**Comment by rnestler** [comment]
http://www.fail2ban.org/wiki/index.php/Downloads Probably needs updating to reflect the new release, right?

**Comment by sebres** [comment]
Yeah, see https://github.com/fail2ban/fail2ban/issues/2580#issuecomment-569666123.
