### ISSUE TITLE
False positive apache-auth IP bans

### ISSUE THREAD

**Issue by hajes** [fail2ban/fail2ban#2587]
### Environment:

- Fail2Ban version 0.10.2
- Debian Buster with kernel 4.9.0-8-amd64:
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
I have default apache-auth ban rules supplied with fail2ban. It is simple MediaWiki website [https://eh.hajes.org](url)

For some unknown reason fail2ban keeps blocking me from accessing my website. I assume that apache-auth keeps an eye on failed login attempts but there is no login on my website...it is simple web browsing until I get banned for no reason.

jail.local setting

`[apache-auth]'

`enabled = true`
`port     = http,https`
`logpath = /var/log/apache2/*error.log`
`findtime = 3600`
`bantime  = -1`
`maxretry = 6`

**There is nothing in any -access.log and there is no reason for ban because there is no login attempts anyway. It is simply blocked just by browsing.**

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

Since I had nothing in logs, I have switched on DEBUG mode. Last ban in fail2ban.log

`2020-01-04 11:17:20,014 fail2ban.filter         [9821]: DEBUG   Processing line with time:1578133039.0 and ip:178.165.128.186`

`2020-01-04 11:17:20,014 fail2ban.filter         [9821]: INFO    [apache-auth] Found 178.165.128.186 - 2020-01-04 11:17:19`

`2020-01-04 11:17:20,014 fail2ban.failmanager    [9821]: DEBUG   Total # of detected failures: 62. Current failures from 1 IPs (IP:count): 178.165.128.186:1`

`2020-01-04 11:17:20,028 fail2ban.actions        [9821]: NOTICE  [apache-auth] Ban 178.165.128.186`

**Comment by sebres** [comment]
`fail2ban-regex` is your friend.
Try to find the matched line that causes a failure:
```
fail2ban-regex --print-all-matched --print-no-missed /var/log/apache2/error.log apache-auth | grep 178.165.128.186
```
Without this info it is almost impossible to solve your issue.

**Comment by hajes** [comment]
thanks for reply. I have used fail2ban regex and It looks like misconfigured mod_evasive

`|  [Sat Jan 04 13:17:27.845060 2020] [evasive20:error] [pid 10612] [client 178.165.128.186:3977] client denied by server configuration: /var/www/hajes_org/humanica/load.php, referer: https://eh.hajes.org/humanica/Index`

I have checked `/etc/apache2/mods-available/evasive.conf` and default config has been commented out. Of course `mod_evasive` is already active.

That may be cause why f2b kicked me out. I will report if issue remains.

**Comment by sebres** [comment]
OK, closed unless until that (I'll reopen if you'd report it's still remaining).
