### ISSUE TITLE
postfix filter rules apply to the wrong log file

### ISSUE THREAD

**Issue by com2** [fail2ban/fail2ban#2589]
_### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): v0.9.6
- OS, including release name/version: Debian 4.9.30-2+deb9u5 (2017-09-19)
- [X ] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ X ] Some customizations were done to the configuration (provide details below is so)
.. but they are not relevant here.
### The issue:

Default jail filter rules do not work because fail2ban monitors the wrong log file. 

#### Steps to reproduce
1. include /etc/postfix/main.cf with smtpd_client_restrictions that include a valid and working reject_rbl_client
2. wait for some traffic causing a rbl rejection in your /var/log/mail.log
3. verify that same rbl rejection does not appear in /var/log/mail.warn 
4. check /var/log/fail2ban to see which log file is actually being checked:  INFO    Added logfile = /var/log/mail.warn
5. check that in fact the first postfix filter rule in fact is referring to rbl rejection
6. do the same for other postfix filter rules to check whether their related log lines in fact appear the "Added logfile"
6. conclude that apparently the wrong log file is chosen for fail2ban functionalilty. 

#### Expected behavior
That fail2ban would add the relevant log file where all log lines appear that are filtered. 
#### Observed behavior
Fail2ban adds a postfix log file that only provides summary information that is insufficient for the functionality of its own default filter rules. 
#### Any customizations done to /etc/fail2ban/ configuration
Not relevant. 

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
2019-12-31 09:22:07,495 fail2ban.filter         [8661]: INFO    Added logfile = /var/log/mail.warn
```

#### Relevant lines from monitored log files in question:

```
/var/log/mail.log:
Jan  5 10:28:35 (anonymised) postfix/smtpd[14689]: NOQUEUE: reject: RCPT from unknown[(anonymised)]: 554 5.7.1 ... (anonymised) ...

/var/log/mail.warn (only demonstrating missing log entries):
Jan  5 10:28:34  postfix/smtpd[14689]: warning: hostname (anymised) does not resolve to address (anonymised): Name or service not known
Jan  5 10:29:16 (anonymised) postfix/smtpd[14689]: warning: unknown[(anonymised)]: SASL LOGIN authentication failed: UGFzc3dvcmQ6


```

**Comment by sebres** [comment]
dup of #1687;
fixed in 57ea38c342b2caa17b61a8cd17f142c218fd0742;
Until your version is not upgraded, add `logpath` in your jail.local to the postfix jail:
```ini
[postfix]
logpath = /var/log/mail.log
```
