### ISSUE TITLE
Codespell report for the "fail2ban" project

### ISSUE THREAD

**Issue by jschleus** [fail2ban/fail2ban#2595]
As administrator of the FOSS server fossies.org I have just created for testing purposes a codespell based analysis for the new `fail2ban` release "0.11.1":

https://fossies.org/linux/misc/fail2ban/codespell.html

That version-independent (not linked) URL should always redirect to the last report (if available), so currently to

https://fossies.org/linux/misc/fail2ban-0.11.1.tar.gz/codespell.html

Although after a first review some obviously wrong matches ("False Positives" = FPs) are already filtered out (ignored) please inform me if you find more of them so that I can force a new improved check if applicable.

Just for information there are also two supplemental pages https://fossies.org/linux/misc/fail2ban/codespell_conf.html (showing some used "codespell" configurations) and https://fossies.org/linux/misc/fail2ban/codespell_fps.html (showing all resulting obvious "False Positives").

If meaningful I could also generate in a special Fossies "test" folder a supplemental codespell analysis for the last `fail2ban` master version.

**Comment by sebres** [comment]
Correct spelling is nice, but...
as a subsequent correction it has a large cons: it causes too many conflicts for all the PRs and some development branches.
Although I don't say we should ignore this, but the prio of that is very low right now.
From the other side the new mainline development starts with version 1.0, so possibly it is time to do that here.

**Comment by jschleus** [comment]
Ok.

Just as a small  completion here the spelling errors resp. typos that I found at a first glance not to be in a comment:

[fail2ban/client/fail2banserver.py](https://fossies.org/linux/misc/fail2ban-0.11.1.tar.gz/fail2ban-0.11.1/fail2ban/client/fail2banserver.py?M=48#l_48)
deamon -> daemon

[fail2ban/server/actions.py](https://fossies.org/linux/misc/fail2ban-0.11.1.tar.gz/fail2ban-0.11.1/fail2ban/server/actions.py?M=639#l_639)
individaully -> individually

[fail2ban/tests/files/logs/nginx-limit-req](https://fossies.org/linux/misc/fail2ban-0.11.1.tar.gz/fail2ban-0.11.1/fail2ban/tests/files/logs/nginx-limit-req?M=3#l_3)
exmaple -> example

[fail2ban/tests/fail2banclienttestcase.py](https://fossies.org/linux/misc/fail2ban-0.11.1.tar.gz/fail2ban-0.11.1/fail2ban/tests/fail2banclienttestcase.py?M=442#l_442)
fot -> for

[fail2ban/tests/files/logs/postfix](https://fossies.org/linux/misc/fail2ban-0.11.1.tar.gz/fail2ban-0.11.1/fail2ban/tests/files/logs/postfix?M=33#l_33)
nonexistant -> nonexistent

[fail2ban/protocol.py](https://fossies.org/linux/misc/fail2ban-0.11.1.tar.gz/fail2ban-0.11.1/fail2ban/protocol.py?M=133#l_133)
patern -> pattern

[man/fail2ban-client.1](https://fossies.org/linux/misc/fail2ban-0.11.1.tar.gz/fail2ban-0.11.1/man/fail2ban-client.1?M=399#l_399)
patern -> pattern

[man/jail.conf.5](https://fossies.org/linux/misc/fail2ban-0.11.1.tar.gz/fail2ban-0.11.1/man/jail.conf.5?M=446#l_446)
adresses -> addresses

[fail2ban/tests/misctestcase.py](https://fossies.org/linux/misc/fail2ban-0.11.1.tar.gz/fail2ban-0.11.1/fail2ban/tests/misctestcase.py?M=220#l_212)
[fail2ban/tests/misctestcase.py](https://fossies.org/linux/misc/fail2ban-0.11.1.tar.gz/fail2ban-0.11.1/fail2ban/tests/misctestcase.py?M=217#l_217)
[fail2ban/tests/misctestcase.py](https://fossies.org/linux/misc/fail2ban-0.11.1.tar.gz/fail2ban-0.11.1/fail2ban/tests/misctestcase.py?M=220#l_220)
represenation -> representation

By the way, the original match

 [MANIFEST](https://fossies.org/linux/misc/fail2ban-0.11.1.tar.gz/fail2ban-0.11.1/MANIFEST?M=266#l_266)
substition -> substitution

is  now classified as a FP since the file fail2ban/tests/files/filter.d/substition.conf really exists.

**Comment by vinc17fr** [comment]
Note that those under `config` are more important, as visible by the end user

**Comment by jschleus** [comment]
You are right, that I have overseen.

**Comment by yarikoptic** [comment]
#3630 is to introduce the CI running `codespell`.

**Comment by sebres** [comment]
Thus let's close it here now, further in #3630
