### ISSUE TITLE
Cannot install testcases with 0.11.1

### ISSUE THREAD

**Issue by opoplawski** [fail2ban/fail2ban#2604]
### Environment:

_- Fail2Ban version (including any possible distribution suffixes): 0.11.1

### The issue:

It appears to be impossible to install the testcases anymore.  There is a --without-testcases option, but it appears to be active by default and there is no --with-testcases option.

#### Steps to reproduce

python3 setup.py install

#### Expected behavior

fail2ban-testcases and tests are installed.

#### Observed behavior
fail2ban-testcases and tests are not install.

#### Any additional information

Also, the fail2ban-testcases.1 man page does not appear to be handled by the switch.  It is still currently installed, and setting --without-testcases I do not think would change that.

**Comment by chtheis** [comment]
I think the name of the switch is --without-test, not --without-testcases. I'm using the switch for the FreeBSD port and it doesn't install the tests, at leats not fail2ban-testcases and its man page.

But yes, there is no switch --with-test. Unfortunately. It could make it easier to have an option to install the tests: FreeBSD offers an automatic translation from "selecting option x" to "--with-x" / "--without-x".

**Comment by sebres** [comment]
Indeed this issue can be introduced by PR #2287 (0.11 only), but as long as I can see per default option `--without-test` is disabled (None), so without this option setup shall install the tests.
At least I see that if I try install manually from source (no idea at the moment there is a different to a build or how it could affect built distribution).

**Comment by sebres** [comment]
Well this PR moves setting of `packages` and `package_data` from `setup` to a handler `install.finalize_options`, but build process does not involve install (or am I wrong?), so if the assumption correct, it will be simply not executed and both `packages` and `package_data` does not contain test related stuff.
At least this can explain why it's different by install from source and by build.

In this case it should get whole data in `setup` and some filter removing unneeded packages in `finalize_options`.

**Comment by angeloc** [comment]
@sebres : I think you are right. The correct approach here is to leave the files in the setup section and filter out in the finalize_option. I'll do a pr as soon as I can.

**Comment by sebres** [comment]
Thx! 
don't forget to select proper branch (0.11) as source and target for PR, default is master now (which is 1.0 basically).

**Comment by sebres** [comment]
Should be fixed now.
Thx @angeloc et al.

**Comment by opoplawski** [comment]
Looks good, thanks!
