### ISSUE TITLE
Which is the latest stable version?

### ISSUE THREAD

**Issue by vipinharidas** [fail2ban/fail2ban#2612]
According to the release notes, I think ver. 0.10.2 is the latest stable version of fail2ban. Please confirm.

**Comment by benrubson** [comment]
See the releases : https://github.com/fail2ban/fail2ban/releases
You have both 0.10.5 and 0.11.1 for now.

**Comment by sebres** [comment]
Definition of "stable" may depend from many factors, among others from your distribution.
This is also a matter of maintainer of certain distribution (to specify distribution related config entries and provide a "stable" or "testing" release), we have no influence on that process.

So our releases are common releases (and may expect more configuration as the packages provided by maintainers as well as don't exclude some issues in some distribution).
Don't use it if you're not familiar.

@yarikoptic I think I know which distribution is meant here :).
