### ISSUE TITLE
Action firewallcmd-ipset using native firewalld ipset implementation

### ISSUE THREAD

**Issue by mpolitaev** [fail2ban/fail2ban#2614]
@grooverdan @sebres Created this issue just for curious to know why actions in [firewallcmd-ipset.conf](https://github.com/fail2ban/fail2ban/blob/master/config/action.d/firewallcmd-ipset.conf) fail2ban config do not use native firewalld ipset implementation? As described here for example.

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-setting_and_controlling_ip_sets_using_firewalld

Also with warning in the end: 

> Red Hat does not recommend using IP sets that are not managed through firewalld

**Comment by sebres** [comment]
> why?

Well, because nobody implemented that yet.
<sub>Как там была поговорка про инициву и инициатора?</sub> :)

**Comment by mpolitaev** [comment]
Got it.
Намёк понял)

**Comment by mpolitaev** [comment]
@sebres https://github.com/fail2ban/fail2ban/pull/2620

**Comment by sebres** [comment]
OK, then closing (further in #2620 directly)
