### ISSUE TITLE
postfix-rbl for postscreen

### ISSUE THREAD

**Issue by agabellini** [fail2ban/fail2ban#2616]
### Description:
The postfix-rbl jail doesn't match log generated by postscreen rbl

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (0.10.4):
- OS, CentOS 7.7: 
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

The postfix-rbl jail doesn't match log generated by postscreen rbl

#### Steps to reproduce
log from postscreen:
`Jan 24 09:29:56 xxx postfix/postscreen[8195]: NOQUEUE: reject: RCPT from [x.x.x.x]:57187: 450 4.7.1 Service unavailable; client [x.x.x.x] blocked using zen.spamhaus.org; from=<xxxi@xxx>, to=<xxx@xxx>, proto=ESMTP, helo=<PCk>`

#### Expected behavior
Filter match

#### Observed behavior
Filter doesn't match

### Configuration, dump and another helpful excerpts
Original config from filter.d/postfix.conf: 
`mdre-rbl  = ^RCPT from [^[]*\[<HOST>\]%(_port)s: [45]54 [45]\.7\.1 Service unavailable; Client host \[\S+\] blocked\b`
Modified (working) config from filter.d/postfix.local:
`mdre-rbl  = ^RCPT from [^[]*\[<HOST>\]%(_port)s: [45]5[04] [45]\.7\.1 Service unavailable; [Cc]lient( host)? \[\S+\] blocked\b`

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

#### The patch ####
```diff
--- postfix.conf	2020-01-24 12:03:08.467729679 +0100
+++ postfix.local	2020-01-24 12:03:10.026743494 +0100
@@ -1 +1 @@
-mdre-rbl  = ^RCPT from [^[]*\[<HOST>\]%(_port)s: [45]54 [45]\.7\.1 Service unavailable; Client host \[\S+\] blocked\b
+mdre-rbl  = ^RCPT from [^[]*\[<HOST>\]%(_port)s: [45]5[04] [45]\.7\.1 Service unavailable; [Cc]lient( host)? \[\S+\] blocked\b

```

**Comment by sebres** [comment]
Since 0.10.1 jail this message should be captured directly by `postfix` jail with this regex:

https://github.com/fail2ban/fail2ban/blob/8c804a229036c45b92fc17437899d28b853d0ebf/config/filter.d/postfix.conf#L20

BTW, since 0.10 you can use jail `postfix` with mode `aggressive` to find all failures in single jail:
```ini
[postfix]
mode = aggressive
enabled = true
# don't needed (postfix mode rbl included above):
#[postfix-rbl]
#enabled = false
```
