### ISSUE TITLE
where can I find the latest documentation?

### ISSUE THREAD

**Issue by thegeeksalive** [fail2ban/fail2ban#2617]
Can someone please help me with the latest documentation?

**Comment by sebres** [comment]
The question is which kind of documentation do you need...

As the README said:

> More documentation, FAQ, and HOWTOs
to be found on fail2ban(1) manpage, [Wiki](https://github.com/fail2ban/fail2ban/wiki),
[Developers documentation](https://fail2ban.readthedocs.io/)

For the online man pages, see for example - https://manpages.debian.org/experimental/fail2ban/jail.conf.5.en.html
