### ISSUE TITLE
recidive not working well

### ISSUE THREAD

**Issue by basti12203** [fail2ban/fail2ban#2619]
Fail2Ban v0.10.2

config look like:

cat /etc/fail2ban/fail2ban.d/local.conf
`[Definition]`
`# see recidive jail`
`dbpurgeage = 8d`

cat /etc/fail2ban/jail.d/local.conf
`[DEFAULT]`
`bantime = 3h`
`maxretry = 3`
`banaction = iptables-ipset-proto6`
`banaction_allports = iptables-ipset-proto6-allports`
` `
`[sshd]`
`enabled = true`
` `
`# Jail for more extended banning of persistent abusers`
`# !!! WARNINGS !!! `
`# 1. Make sure that your loglevel specified in fail2ban.conf/.local`
`#    is not at DEBUG level -- which might then cause fail2ban to fall into`
`#    an infinite loop constantly feeding itself with non-informative lines`
`# 2. If you increase bantime, you must increase value of dbpurgeage`
`#    to maintain entries for failed logins for sufficient amount of time.`
`#    The default is defined in fail2ban.conf and you can override it in fail2ban.local`
`[recidive]`
`enabled = true`
`bantime = 7d`
`findtime = 24h`

tail -n 50 /var/log/fail2ban.log
...
`2020-01-29 08:46:43,780 fail2ban.filter         [15427]: INFO    [recidive] Found 218.88.164.159 - 2020-01-29 08:46:43`
...

`root@srv:/etc/fail2ban# ipset list -t`
`Name: f2b-sshd`
`Type: hash:ip`
`Revision: 4`
`Header: family inet hashsize 1024 maxelem 65536 timeout 10800`
`Size in memory: 41272`
`References: 1`
`Number of entries: 35`
` `
`Name: f2b-recidive`
`Type: hash:ip`
`Revision: 4`
`Header: family in`et hashsize 1024 maxelem 65536 timeout 604800`
`Size in memory: 11512`
`References: 1`
`Number of entries: 120`
` `
`ipset list f2b-recidive | grep 218.88.164.159`
`ipset list f2b-sshd | grep 218.88.164.159`
`218.88.164.159 timeout 8856`

cat /etc/logrotate.d/fail2ban 
`/var/log/fail2ban.log {`
`   `
`    weekly`
`    rotate 4`
`    compress`
` `
`    delaycompress`
`    missingok`
`    postrotate`
`	     fail2ban-client flushlogs 1>/dev/null`
`    endscript`
` `
`    # If fail2ban runs as non-root it still needs to have write access`
`    # to logfiles.`
`    # create 640 fail2ban adm`
`    create 640 root adm`
`}`
Why is the IP 218.88.164.159 only found in f2b-sshd and not in f2b-recidive?

**Comment by sebres** [comment]
> Why is the IP 218.88.164.159 only found in f2b-sshd and not in f2b-recidive?

The answer is pretty good described in the documentation as well as in our [wiki](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works):

"the IP goes to ban if it makes at least `maxretry` failures within `findtime` seconds. So if you've configured `maxretry = 5` and `findtime = 10m` (default values) then it needs at least 5 failures (5 attempts) within 10 minutes to ban an IP."

Corresponding your config the recidive jail has default `maxretry` (I assume 3), so fail2ban has to find 3 bans in other jails for the IP to ban it.
