### ISSUE TITLE
fail2ban-regex not working

### ISSUE THREAD

**Issue by vikk** [fail2ban/fail2ban#2628]
_We will be very grateful, if your problem was described as completely as possible,
enclosing excerpts from logs (if possible within DEBUG mode, if no errors evident
within INFO mode), and configuration in particular of effected relevant settings
(e.g., with ` fail2ban-client -d | grep 'affected-jail-name' ` for a particular
jail troubleshooting).
Thank you in advance for the details, because such issues like "It does not work" 
alone could not help to resolve anything!
Thanks! (remove this paragraph and other comments upon reading)_

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 
- [x] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
Os:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

Fail2Ban v0.10.2

does not match:
`fail2ban-regex '2020/02/07 11:05:06 http: TLS handshake error from 176.113.115.95:52761: tls:' "^\d{4}\/\d{2}\/\d{2} \d{2}:\d{2}:\d{2} http: TLS handshake error from <HOST>:([0-9]{1,5}):[ \t]"`

match:
`fail2ban-regex '2020/02/07 11:05:06 http: TLS handshake error from 176.113.115.95:52761: tls:' "http: TLS handshake error from <HOST>:([0-9]{1,5}):[ \t]"`

#### Expected behavior

The first expression should match as well. I got this:
Running tests

Use failregex line : ^\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2} http: TLS h...
Use single line : 2020/02/07 11:05:06 http: TLS handshake error from...

Results

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
| [1] {^LN-BEG}ExYear(?P<_sep>[-/.])Month(?P=_sep)Day(?:T| ?)24hour:Minute:Second(?:[.,]Microseconds)?(?:\s*Zone offset)?

Lines: 1 lines, 0 ignored, 0 matched, 1 missed
[processed in 0.00 sec]

|- Missed line(s):
| 2020/02/07 11:05:06 http: TLS handshake error from 176.113.115.95:52761: tls:

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
Fail2ban cuts out (bypass) the part of failure line matched `datepattern` before `failregex` (and `prefregex`) is applied. This is default behavior since begin of fail2ban and is well described in documentation and [wiki](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works):

> Note: fail2ban tries to search the match not the original string - the datetime value (matched datepattern) will be cut out from it before searching.
