### ISSUE TITLE
/var/run/fail2ban in not created during port start - FreeBSD 

### ISSUE THREAD

**Issue by fkoczan** [fail2ban/fail2ban#2634]
/var/run/fail2ban folder is necessary for fail2ban start. I am using  tmpfs (ramdisk) as /var/run which can be beneficial in my use case so after reboot all data inside /var/run are gone. /var/run/fail2ban  is created during port install - ad I know it should be recreated during script start.

Just simple fix in rc script is needed:
/usr/local/etc/rc.d/fail2ban is missing 
start_precmd="install -d -m 640 /var/run/fail2ban"
or something more sophisticated?

### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.11.1
- OS, including release name/version:  FreeBDS 12.1 p2
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
fail2ban is not starting when /var/run/fail2ban folder is missing

#### Steps to reproduce
delete /var/run/fail2ban and try to start fail2ban

#### Expected behavior
/var/run/fail2ban is recreated by rc script

**Comment by chtheis** [comment]
On 12.02.2020 09:14, Florian Koczan wrote:
> Just simple fix in rc script is needed:
> /usr/local/etc/rc.d/fail2ban is missing
> start_precmd="install -d -m 640 /var/run/fail2ban"
> or something more sophisticated?

I checked how other services deal with that and at least some take the
same approach.

But: carfull, the pid file and thus the directory may be changed in
/etc/rc.conf, so instead of an absolute path $(basename ${pidfile})
(haven't checked the syntax) should be used.

**Comment by sebres** [comment]
It is rather a matter of maintainers, and I don't think rc-unit of FreeBSD is a part of our repository...

But it can be simply solved like here:
https://github.com/fail2ban/fail2ban/blob/824afbf52d951844ebaff1cc93c990867f60ffd2/files/debian-initd#L113-L114

I'll close it as 3rd party issue.
If someone wants to provide a FreeBSD command script, welcome with PR.

**Comment by chtheis** [comment]
On 12.02.2020 14:03, Sergey G. Brester wrote:
> If someone wants to provide a FreeBSD command script, welcome with PR.

That script is already part of the FreeBSD port.

**Comment by sebres** [comment]
Sure :)... I meant to provide it in main repo (in [files/](https://github.com/fail2ban/fail2ban/tree/master/files) folder).

**Comment by ttm-tt** [comment]
Can do. 
But another problem: the pidfile can be configured with full path but the socket name is hard coded. Shouldn't both files reside in the same directory? Which could make communication between client and server complicated ...

**Comment by chtheis** [comment]
Sorry, used a wrong account ...

**Comment by sebres** [comment]
Duno... (no idea how it made in FreeBSD port)... 
Normally both the config (`fail2ban.conf` / `fail2ban.local`) allow to set `pidfile` and `socket`,
as well as the commands (`fail2ban-server` and `fail2ban-client`) support supplying of that via command line:
`?-p pidfile? ?-s socket?`.
The parameters from command line win (overwrite config values).

**Comment by chtheis** [comment]
On 12.02.2020 19:10, Sergey G. Brester wrote:
> Normally both the config (|fail2ban.conf| / |fail2ban.local|) allow to set |pidfile| and |socket|

I forgot you can do that, that simplifies the tasks of the init script.

Usually init scripts care only about the pid files so they know if the
daemons are still running, but they do not necessarily pass
configurations on to the daemons itself. Though there are means to do
so. Which means I can leave it to the user / admin to ensure all the
config files are consistent :)

**Comment by sebres** [comment]
Thinking a bit about that, I don't find arguments against doing it directly in server by start (excepting that it could create some "wrong" folder by misconfiguration).
But at least we could more or less "safe" do that for the not existing folder of last level only (so it will auto-create `/run/fail2ban` if `/run` exists).
I'll do this for >= 0.10 now.

**Comment by sebres** [comment]
OK, 91eca4fdeb728fa0fd2d6cf55db8eb7baa2a39a2 would solve this (and similar issues):
- automatically create not-existing path (last level folder only) for pidfile, socket and database (with default permissions)

I hope it is good enough... 
@chtheis probably you don't need to extend the BSD-port now, Christoph.
@fail2ban/maintainers any objections against this "fix"?

**Comment by chtheis** [comment]
> @chtheis <https://github.com/chtheis> probably you don't need to extend the BSD-port now, Christoph.

I've already submitted the patch. It's not a big deal, copy and past
some lines from other services, and it wouldn't hurt :)

I haven't seen in other init.d scripts that they will take care of
missing directories, so your patch will help at least there.
