### ISSUE TITLE
witch datepattern for Feb 16 16:39:18

### ISSUE THREAD

**Issue by pkfran** [fail2ban/fail2ban#2637]
Hello thank you to give me the datepattern for this kind of date syntax in my log
Feb 16 16:39:18

**Comment by sebres** [comment]
1. Normally this belongs to our default patterns, so you must not specify this.
```
fail2ban-regex 'Feb 16 16:39:18 error from 192.0.2.1' '^ error from <ADDR>$'
...
Date template hits:
|- [# of hits] date format
|  [1] {^LN-BEG}(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
```
2. But corresponding pattern were `^%b %d %H:%M:%S` (use `%%` in config):
```
datepattern = ^%%b %%d %%H:%%M:%%S
```

**Comment by pkfran** [comment]
thank you very much
