### ISSUE TITLE
Loglevel for specific filter

### ISSUE THREAD

**Issue by momala454** [fail2ban/fail2ban#2640]
I have a filter that detect flooders that do a lot of requests, so it detect every request done, but ban only when it's detecting a lot in a specific timeframe.
Unfortunately, i have the loglevel "INFO", which cause all "found" to be listed on the logfile, this means that my log file is filled with "found" for this filter.
How can i disable the logging of "found" for this specific filter, so lowering the loglevel for this filter ?

If i change the global loglevel, it will not show the found for the other filters

**Comment by sebres** [comment]
As fail2ban uses a central logger it is quite impossible at the moment to set different log-level on particular jail or filter (it will be logged by `fail2ban.sever.filter` and changing on one filter will change it in the other, where last wins).
Although it would not expect too many modifications to change this behavior for logging of this specific message only (in the filter), to do that properly it would affect several modules (together with configuration, coverage etc), so I don't see the effort would justify this questionable "feature".

Either disable that for all jails - level 21 (`INFO` + 1) or `NOTICE` or ignore this messages (`logrotate` would help to hold it slimly as well as `grep` etc could help you by search of messages).
Or even rewrite your service logging to produce fewer (e. g. summarized) messages by the flooders detection.
For example if you use `nginx`, it has a module [ngx_http_limit_req_module](http://nginx.org/en/docs/http/ngx_http_limit_req_module.html) so you could use `limit_req` for specific location cumulating all the "failures" from flooders, so you can write summarized message into the log for fail2ban (let nginx count it for you before fail2ban gets involved).
See [wiki :: Best practice](https://github.com/fail2ban/fail2ban/wiki/Best-practice) for more information.
