### ISSUE TITLE
Guacamole filter log issue

### ISSUE THREAD

**Issue by jerkovicl** [fail2ban/fail2ban#2645]
dont know what i am doing wrong but cant seem to get the guacamole jail working.
Using apache guacamole container behind traefik proxy. Tried manually banning some ip and rules are being added in cloudflare.

fail2ban log output: 
```
2020-02-22 20:52:36,527 fail2ban.CommandAction  [1]: DEBUG     Set name = 'guacamole-auth'
2020-02-22 20:52:36,527 fail2ban.CommandAction  [1]: DEBUG     Set port = 'http,https'
2020-02-22 20:52:36,527 fail2ban.CommandAction  [1]: DEBUG     Set protocol = 'tcp'
2020-02-22 20:52:36,527 fail2ban.CommandAction  [1]: DEBUG     Set chain = '<known/chain>'
2020-02-22 20:52:36,527 fail2ban.CommandAction  [1]: DEBUG     Set actname = 'cloudflare'
2020-02-22 20:52:36,528 fail2ban.CommandAction  [1]: DEBUG     Set cfuser = 'xxxx'
2020-02-22 20:52:36,528 fail2ban.CommandAction  [1]: DEBUG     Set cftoken = 'xxx'
2020-02-22 20:52:36,528 fail2ban.jail           [1]: DEBUG   Starting jail 'guacamole-auth'
2020-02-22 20:52:36,528 fail2ban.filterpyinotif [1]: DEBUG   [guacamole-auth] filter started (pyinotifier)
2020-02-22 20:52:36,528 fail2ban.jail           [1]: INFO    Jail 'guacamole-auth' started
2020-02-22 20:52:36,529 fail2ban.transmitter    [1]: DEBUG   Status: ready
Server ready
2020-02-22 20:53:01,954 fail2ban.filterpyinotif [1]: DEBUG   Event queue size: 16
2020-02-22 20:53:01,954 fail2ban.filterpyinotif [1]: DEBUG   <_RawEvent cookie=0 mask=0x2 name='' wd=2 >
2020-02-22 20:53:01,979 fail2ban.filterpyinotif [1]: DEBUG   Event queue size: 16
2020-02-22 20:53:01,979 fail2ban.filterpyinotif [1]: DEBUG   <_RawEvent cookie=0 mask=0x2 name='' wd=2 >
2020-02-22 20:53:07,132 fail2ban.filterpyinotif [1]: DEBUG   Event queue size: 16
2020-02-22 20:53:07,132 fail2ban.filterpyinotif [1]: DEBUG   <_RawEvent cookie=0 mask=0x2 name='' wd=2 >
2020-02-22 20:53:07,133 fail2ban.filterpyinotif [1]: DEBUG   Event queue size: 16
2020-02-22 20:53:07,133 fail2ban.filterpyinotif [1]: DEBUG   <_RawEvent cookie=0 mask=0x2 name='' wd=2 >
2020-02-22 20:53:07,134 fail2ban.filterpyinotif [1]: DEBUG   Event queue size: 16
```

> jail.d/guacamole.conf
```
[DEFAULT]
banaction = cloudflare

[guacamole-auth]
enabled = true
logpath = /var/log/guacamole/guacd.log
port = http,https

bantime = -1
maxretry = 5
```
> filter.d/guacamole-auth.conf
```
[Definition]
failregex = \bAuthentication attempt from \[<HOST>(?:,.*)?\] for user ".*" failed\.
ignoreregex =
```

> config/guacamole/logback.xml
```
<configuration>
        <!-- Appender for debugging -->
        <appender name="GUAC-DEBUG" class="ch.qos.logback.core.ConsoleAppender">
                <encoder>
                        <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
                </encoder>
        </appender>
        <!-- Appender for debugging in a file-->
        <appender name="GUAC-DEBUG_FILE" class="ch.qos.logback.core.FileAppender">
                <file>/usr/local/tomcat/logs/guacd.log</file>
                <encoder>
                        <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
                </encoder>
        </appender>
        <!-- Log at DEBUG level -->
        <root level="debug">
                <appender-ref ref="GUAC-DEBUG"/>
                <appender-ref ref="GUAC-DEBUG_FILE"/>
        </root>
</configuration>
```
> jail status
```
/ # fail2ban-client status guacamole-auth
Status for the jail: guacamole-auth
|- Filter
|  |- Currently failed: 0
|  |- Total failed:     0
|  `- File list:        /var/log/guacamole/guacd.log
`- Actions
   |- Currently banned: 0
   |- Total banned:     0
   `- Banned IP list:
```

> regex test
```
Results
=======

Failregex: 15 total
|-  #) [# of hits] regular expression
|   1) [15] \bAuthentication attempt from \[<HOST>(?:,.*)?\] for user ".*" failed\.
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [376] {^LN-BEG}24hour:Minute:Second
`-

Lines: 376 lines, 0 ignored, 15 matched, 361 missed
[processed in 0.04 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all 361 lines
```

**Comment by sebres** [comment]
I don't see an "error" right now, well maybe excepting...

> jail.d/guacamole.conf

Your jail is called `guacamole-auth` (as the section in `jail.d/guacamole.conf` also), but the config is called `guacamole.conf` so it rather addresses the jail `guacamole` which is not present there.

Either rename `jail.d/guacamole.conf` to `jail.d/guacamole-auth.conf` or remove it and place this content into `jail.local` in root of `/etc/fail2ban`.

You can control which runtime parameter you have with `fail2ban-client -d | grep guacamole`, I guess something is not overwritten (e. g. logpath) by this "invalid" config file.
Anyway provide the excerpt here if you mean all parameters are correct.

**Comment by sebres** [comment]
Note also related PR #2631 (`filter = guacamole[logging=webapp]`) targeting similar issue.

**Comment by jerkovicl** [comment]
Renamed `jail.d/guacamole.conf` but still getting same debug messages.
Output of command `fail2ban-client -d | grep guacamole` you meantioned is:
```
/ # fail2ban-client -d | grep guacamole
['add', 'guacamole_auth', 'auto']
['set', 'guacamole_auth', 'usedns', 'warn']
['set', 'guacamole_auth', 'addfailregex', '\\bAuthentication attempt from \\[<HOST>(?:,.*)?\\] for user ".*" failed\\.']
['set', 'guacamole_auth', 'maxretry', 5]
['set', 'guacamole_auth', 'maxmatches', 5]
['set', 'guacamole_auth', 'findtime', '10m']
['set', 'guacamole_auth', 'bantime', '-1']
['set', 'guacamole_auth', 'ignorecommand', '']
['set', 'guacamole_auth', 'logencoding', 'auto']
['set', 'guacamole_auth', 'addlogpath', '/var/log/guacamole/guacd.log', 'head']
['set', 'guacamole_auth', 'addaction', 'cloudflare']
['multi-set', 'guacamole_auth', 'action', 'cloudflare', [['actionstart', ''], ['actionstop', ''], ['actioncheck', ''], ['actionban', 'curl -s -X POST "https://api.cloudflare.com/client/v4/user/firewall/access_rules/rules" \\\n-H "X-Auth-Email: xxxx" \\\n-H "X-Auth-Key: xxxx" \\\n-H "Content-Type: application/json" \\\n--data \'{"mode":"block","configuration":{"target":"ip","value":"<ip>"},"notes":"Fail2ban guacamole_auth"}\''], ['actionunban', 'curl -s -X DELETE "https://api.cloudflare.com/client/v4/user/firewall/access_rules/rules/$( \\\ncurl -s -X GET "https://api.cloudflare.com/client/v4/user/firewall/access_rules/rules?mode=block&configuration_target=ip&configuration_value=<ip>&page=1&per_page=1&match=all" \\\n-H "X-Auth-Email: xxxx" \\\n-H "X-Auth-Key: xxxx" \\\n-H "Content-Type:application/json" | awk -F"[,:}]" \'{for(i=1;i<=NF;i++){if($i~/\'id\'\\042/){print $(i+1);}}}\' | tr -d \'"\' | sed -e \'s/^[ \\t]*//\' | head -n 1)" \\\n-H "X-Auth-Email: xxxx" \\\n-H "X-Auth-Key: xxxx" \\\n-H "Content-Type: application/json"'], ['name', 'guacamole_auth'], ['port', 'http,https,80,443'], ['protocol', 'tcp'], ['chain', '<known/chain>'], ['actname', 'cloudflare'], ['cfuser', 'xxxx'], ['cftoken', 'xxxx']]]
['start', 'guacamole_auth']
```

**Comment by sebres** [comment]
Ok, if your test of fail2ban-regex was also against `/var/log/guacamole/guacd.log` (where it has found at least 15 failures), then your filter seems to work.
Take a look for first answer in our [wiki](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works) whether you can find something affecting you, why it may not match.

Also note that fail2ban (since 0.9) knows the last position in log (stored in sqlite database together with md5 of first line to recognize log-rotation), so after restart it does not process the file from begin (basically it starts either from last known position or from a log entry that corresponds `now - findtime` but in any case not earlier as last known position). 
And a reload would do nothing at all (remain the current position and simply update runtime from config values).
In both cases you'll not catch any match for already bypassed messages (by previous runs of f2b).
Either delete fail2ban database (and increase `findtime`) to find that, or simply try to generate new messages (for example by yourself) to check it would work.

Additionally, you did not provide your fail2ban version...

In some strange (obscure) cases DEBUG may be too small level, try HEAVYDEBUG (or better start with 7 if you have fail2ban >= 0.10),  but note it'd produce a lot of messages.

**Comment by jerkovicl** [comment]
I am using latest version:
```
 fail2ban-client version
0.11.1
```

I will try with new messages in log

**Comment by jerkovicl** [comment]
Activated TRACEDEBUG, so filter finds the correct line then outputs DEBUG message, and its same for every other "Working on line" message
```
2020-02-27 15:01:28,502 fail2ban.filter         [1]: TRACE Working on line 14:01:28.180 [http-nio-8080-exec-2] DEBUG o.a.g.r.auth.AuthenticationService - Anonymous authentication attempt from [xx.xx.xx.xx, xx.xx.xx.xx, xx.xx.xx.xx] failed.
2020-02-27 15:01:34,461 fail2ban.filterpyinotif [1]: DEBUG   Event queue size: 16
2020-02-27 15:01:34,461 fail2ban.filterpyinotif [1]: DEBUG   <_RawEvent cookie=0 mask=0x2 name= wd=2 >
```

**Comment by jerkovicl** [comment]
Activated TRACEDEBUG, so filter finds the correct line then outputs DEBUG message, and its same for every other "Working on line" message
```
2020-02-27 15:01:28,502 fail2ban.filter         [1]: TRACE   Working on line '14:01:28.180 [http-nio-8080-exec-2] DEBUG o.a.g.r.auth.AuthenticationService - Authentication attempt from [xx.xx.xx.xx, xx.xx.xx.xx, xx.xx.xx.xx] for user failed.\n'
2020-02-27 15:01:34,461 fail2ban.filterpyinotif [1]: DEBUG   Event queue size: 16
2020-02-27 15:01:34,461 fail2ban.filterpyinotif [1]: DEBUG   <_RawEvent cookie=0 mask=0x2 name='' wd=2 >
```

**Comment by sebres** [comment]
Log-Line:
> `14:01:28.180 [http-nio-8080-exec-2] DEBUG o.a.g.r.auth.AuthenticationService - Anonymous authentication attempt from [xx.xx.xx.xx, xx.xx.xx.xx, xx.xx.xx.xx] failed.`
> `14:01:28.180 [http-nio-8080-exec-2] DEBUG o.a.g.r.auth.AuthenticationService - Authentication attempt from [xx.xx.xx.xx, xx.xx.xx.xx, xx.xx.xx.xx] for user failed.`

Regexp:
> `\bAuthentication attempt from \[<HOST>(?:,.*)?\] for user ".*" failed\.`

would never match (lower-case `a`uthentication as well as missing mandatory user name or `for user ...` in the message).

Although I don't know you should really generate a match for this "anonymous" messages (e. g. if it is a part of handshake phase, so every auth-attempt would cause that firstly), but if you really need it, you can try something like this:
```diff
-\bAuthentication attempt from \[<HOST>(?:,.*)?\] for user ".*" failed\.
+\b[Aa]uthentication attempt from \[<HOST>(?:,[^\]]*)?\] (?:for user (?:"[^"]*" )?)?failed\.\s*$
```
Note I used anchor `$` here, but normally it'd be good if such RE's are anchored from both sides, so better this one:
```ini
maxlines = 1
datepattern = ^%%H:%%M:%%S\.%%f
failregex = ^\s*\[[^\]]+\] \S+ \S*auth.AuthenticationService - (?:Anonymous )?[Aa]uthentication attempt from \[<HOST>(?:,[^\]]*)?\] (?:for user (?:"[^"]*" )?)?failed\.\s*$
```
I don't understand why your second example has a new-line at end of line:
`2020-02-27 15:01:28,502 fail2ban.filter         [1]: TRACE   Working on line '... for user failed.\n'`
Normally it is not expected by single-line filters and an anchor `$` would not match there in this case.
This is a bit weird (but possibly this `maxlines = 2` got included from original filter?).
But I also rewrote right-trim of new-lines in latest versions, possibly the logging of `Working on line` occurs before the trim takes place.

**Comment by jerkovicl** [comment]
Yeah I copied that anonymous part from log by mistake should be without just wanted to show the flow of execution, I don't need regex to catch that part. I will try with your regex and see what happens

**Comment by jerkovicl** [comment]
After adjusting max lines and date pattern in filter jail still getting same results:

```
/ # fail2ban-client -d | grep guacamole
['add', 'guacamole_auth', 'auto']
['set', 'guacamole_auth', 'usedns', 'warn']
['set', 'guacamole_auth', 'maxlines', 1]
['set', 'guacamole_auth', 'addfailregex', '\\bAuthentication attempt from \\[<HOST>(?:,.*)?\\] for user ".*" failed\\.']
['set', 'guacamole_auth', 'datepattern', '^%H:%M:%S\\.%f']
['set', 'guacamole_auth', 'maxretry', 5]
['set', 'guacamole_auth', 'maxmatches', 5]
['set', 'guacamole_auth', 'findtime', '10m']
['set', 'guacamole_auth', 'bantime', '-1']
['set', 'guacamole_auth', 'ignorecommand', '']
['set', 'guacamole_auth', 'logencoding', 'auto']
['set', 'guacamole_auth', 'addlogpath', '/var/log/guacamole/guacd.log', 'head']
['set', 'guacamole_auth', 'addaction', 'cloudflare']
```
```
2020-02-27 19:23:15,627 fail2ban.filter         [1]: TRACE   Working on line '18:23:15.626 [http-nio-8080-exec-2] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from [xxx.xxx.xxx.xx, xx.xx.xx.xx, xx.xx.xx.xx] for user "hrjk" failed.\n'
2020-02-27 19:23:15,627 fail2ban.filterpyinotif [1]: DEBUG   Event queue size: 16
2020-02-27 19:23:15,627 fail2ban.filterpyinotif [1]: DEBUG   <_RawEvent cookie=0 mask=0x2 name='' wd=2 >
2020-02-27 19:23:18,777 fail2ban.filterpyinotif [1]: DEBUG   Event queue size: 16
2020-02-27 19:23:18,777 fail2ban.filterpyinotif [1]: DEBUG   <_RawEvent cookie=0 mask=0x2 name='' wd=2 >
```

**Comment by sebres** [comment]
if you would try `fail2ban-regex -vv ...` you would see the timestamp fail2ban recognized, I assume `Thu Feb 27 18:23:15 2020` for your example message in TRACE.

It is really your timezone (looks like UTC/GMT to me). If not, this may be cause that fail2ban ignores that as too old failures - then you have to correct zone in service (or your system).

If it is a timezone issue (normally fail2ban is working with system timezone, so same as init.d/systemd/etc):
-  the logger (or service) you trying to monitor may use another TZ for some reasons (or due to some bug/refresh issue/misconfiguration) and because the string does not contains TZ in timestamp (and/or `datepattern doesn't consider it) - the system TZ (or rather fail2ban TZ) is used;
- the right way is always to find and correct time or TZ where it is wrong... so in related service (or logger);
- as a workaround (to adjust a time offset) one can use an option `logtimezone` to specify default TZ for log (see #1792) in order to force fail2ban to calculate another "correct" offset; but if this is not GMT/UTC, it is a bit ugly e.g. could become incorrect later once the real time of service will be adjusted (corrected) or for example TZ has a DST switch.

Also note the answer in [FAQ on our wiki](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works) for other possible reasons why "Fail2ban does not detect some authentication failures ...".


> i dont know where does the \n come from...

It does no matter in your case anyway (your regex is not anchored).

**Comment by jerkovicl** [comment]
Yep finally solved it, it was timezone issue!!
Guacamole didn't have proper timezone so when i gave it TZ variable regex finally worked. 
Thx alot for help man.

**Comment by benrubson** [comment]
You could also start your Guacamole container passing it the correct `TZ` environment variable :+1:

**Comment by jerkovicl** [comment]
@benrubson  thats what i did
