### ISSUE TITLE
bantime too long handling

### ISSUE THREAD

**Issue by heraldb** [fail2ban/fail2ban#2648]
### Environment:

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: CentOS Linux release 7.7.1908 (Core)
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

When I configured bantime for 4 weeks (2419200 seconds), fail2ban started up successfully and every now and then it reported happily banned IP-adresses. However, nothing was blocked. The server was not protected by fail2ban in any way.

This way fail2ban can make you feel safe month after month, while you're not.

#### Steps to reproduce
In this case I used firewalld (install package fail2ban-firewalld). Just configure fail2ban with a bantime of 4 weeks by putting "bantime = 2419200" in /etc/fail2ban/jail.local. Restart fail2ban by "systemctl restart fail2ban"

#### Expected behavior
Since the maximum bantime is 2147483 (which is less than configured), the creation of rules in firewalld fail. I would expect fail2ban not be able to start, or to start while setting bantime to the maximum value while giving a warning.

#### Observed behavior
The fail2ban service started without any problem. Only if you check the logfile, you can see errors.  

```
[] fail2ban.utils          [13523]: ERROR   7ffa5aca6348 -- exec: ipset create f2b-postfix hash:ip timeout 2419200  
firewall-cmd --direct --add-rule ipv4 filter INPUT_direct 0 -p tcp -m multiport --dports smtp,465 -m set --match-set f2b-postfix src -j REJECT --reject-with icmp-port-unreachable  
[]fail2ban.utils          [13523]: ERROR   7ffa5aca6348 -- stderr: "ipset v7.1: Syntax error: '2419200' is out of range 0-2147483"  
[]fail2ban.utils          [13523]: ERROR   7ffa5aca6348 -- stderr: "Error: COMMAND_FAILED: '/usr/sbin/iptables-restore -w -n' failed: iptables-restore v1.4.21: Set f2b-postfix doesn't exist."
```
For every attempt by fail2ban to ban an IP, firewalld logs an error

```
[] ERROR: '/usr/sbin/iptables-restore -w -n' failed: iptables-restore v1.4.21: Set f2b-postfix doesn't exist.
```

#### Any additional information
With a proper value for bantime, everything worked as expected.

#### Any customizations done to /etc/fail2ban/ configuration
I only did changes to /etc/fail2ban/jail.local. The crucial line was of course

```
bantime = 2419200
```
Once again: after changing the value to something lower than 2147483, all went well.

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
This is fixed in newer version. See #2179 for details as well as workaround to fix it for you.
