### ISSUE TITLE
Fail2ban does not catch systemd log lines generated by php-fpm when php-fpm is running as an unprivileged user

### ISSUE THREAD

**Issue by twheel** [fail2ban/fail2ban#2653]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): 0.11.1
- OS, including release name/version: Arch Linux up to date
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
Fail2ban does not catch systemd journal lines generated by php-fpm when php-fpm is running as an unprivileged user.

#### Steps to reproduce
Configure a php-fpm pool with e.g.
```
user=twheel
group=twheel
```
Using this instead works as expected:
```
user=http
group=http
```
#### Expected behavior
Fail2ban should catch log lines in either case.
#### Observed behavior
Fail2ban only catches log lines when the php-fpm user is `http`
#### Any additional information
journalctl -t phpMyAdmin -e (obfuscated):
```
Mar 08 20:18:35 hostname.example.com phpMyAdmin[550900]: user denied: bad_user (mysql-denied) from <HOST>
Mar 08 20:19:38 hostname.example.com phpMyAdmin[550977]: user denied: bad_user (mysql-denied) from <HOST>
```
(First one was with php-fpm running as `http`, second with it running as `twheel`.)
Fail2ban log line corresponding to first journal line:
```
2020-03-08 20:18:36,043 fail2ban.filter         [548645]: INFO    [phpmyadmin-syslog] Ignore <HOST> by ip
```
There is no fail2ban log line corresponding to the second journal line.
Verbose journalctl output for the http instance:
```
Sun 2020-03-08 20:18:35.636713 EDT [s=7189c83dbd004285a808b2f8c46e3443;i=3ccdb5;b=75655e1741af4c57846925fda379f1a4;m=661a0de502;t=5a060f1af03f6;x=201234c4726078b0]
    _TRANSPORT=syslog
    _COMM=php-fpm
    _EXE=/usr/bin/php-fpm
    _SYSTEMD_CGROUP=/system.slice/php-fpm.service
    _SYSTEMD_UNIT=php-fpm.service
    _SYSTEMD_SLICE=system.slice
    _BOOT_ID=75655e1741af4c57846925fda379f1a4
    _MACHINE_ID=fcc8857ae69b4766be3bcc41ae0a7ce0
    _HOSTNAME=hostname.example.com
    SYSLOG_FACILITY=10
    _CAP_EFFECTIVE=0
    PRIORITY=4
    SYSLOG_IDENTIFIER=phpMyAdmin
    _UID=33
    _GID=33
    _CMDLINE=php-fpm: pool virtual.example.com
    _SYSTEMD_INVOCATION_ID=c96322b371424048a1c92f7432fa48d9
    SYSLOG_PID=550900
    SYSLOG_TIMESTAMP=Mar  8 20:18:35 
    MESSAGE=user denied: bad_user (mysql-denied) from <HOST>
    _PID=550900
    _SOURCE_REALTIME_TIMESTAMP=1583713115636713
```
Verbose journalctl output for the twheel instance:
```
Sun 2020-03-08 20:19:38.699789 EDT [s=8d5190a3d9494d62a98423c8eec34271;i=3ccdda;b=75655e1741af4c57846925fda379f1a4;m=661dd02943;t=5a060f5714837;x=3badb3f683289f45]
    _TRANSPORT=syslog
    _UID=1001
    _GID=1001
    _CAP_EFFECTIVE=0
    _SYSTEMD_SLICE=system.slice
    _BOOT_ID=75655e1741af4c57846925fda379f1a4
    _MACHINE_ID=fcc8857ae69b4766be3bcc41ae0a7ce0
    _HOSTNAME=hostname.example.com
    _COMM=php-fpm
    _EXE=/usr/bin/php-fpm
    _SYSTEMD_CGROUP=/system.slice/php-fpm.service
    _SYSTEMD_UNIT=php-fpm.service
    _CMDLINE=php-fpm: pool virtual.example.com
    PRIORITY=4
    SYSLOG_FACILITY=10
    SYSLOG_IDENTIFIER=phpMyAdmin
    MESSAGE=user denied: bad_user (mysql-denied) from <HOST>
    SYSLOG_PID=550977
    SYSLOG_TIMESTAMP=Mar  8 20:19:38 
    _PID=550977
    _SYSTEMD_INVOCATION_ID=4ede4325b90345f094090cb55676a383
    _SOURCE_REALTIME_TIMESTAMP=1583713178699789
```
### Configuration, dump and another helpful excerpts
fail2ban-client -d | grep 'phpmyadmin-syslog' 
```
['add', 'phpmyadmin-syslog', 'systemd']
['set', 'phpmyadmin-syslog', 'usedns', 'warn']
['set', 'phpmyadmin-syslog', 'addfailregex', '^\\s*(?:\\S+\\s+)?(?:\\S*(?:\\[\\d+\\])?:?\\s+)?(?:kernel:\\s?\\[ *\\d+\\.\\d+\\]:?\\s+)?user denied: (?:\\S+|.*?) \\(mysql-denied\\) from <HOST>\\s*$']
['set', 'phpmyadmin-syslog', 'datepattern', '{^LN-BEG}']
['set', 'phpmyadmin-syslog', 'addjournalmatch', 'SYSLOG_IDENTIFIER=phpMyAdmin']
['set', 'phpmyadmin-syslog', 'maxretry', 3]
['set', 'phpmyadmin-syslog', 'maxmatches', 3]
['set', 'phpmyadmin-syslog', 'findtime', '15m']
['set', 'phpmyadmin-syslog', 'bantime', '10m']
['set', 'phpmyadmin-syslog', 'ignorecommand', '']
['set', 'phpmyadmin-syslog', 'addignoreip', '127.0.0.1/8', '<HOST>']
['set', 'phpmyadmin-syslog', 'logencoding', 'auto']
['set', 'phpmyadmin-syslog', 'addaction', 'iptables-multiport']
['multi-set', 'phpmyadmin-syslog', 'action', 'iptables-multiport', [['actionstart', '<iptables> -N f2b-phpmyadmin-syslog\n<iptables> -A f2b-phpmyadmin-syslog -j RETURN\n<iptables> -I INPUT -p tcp -m multiport --dports http,https -j f2b-phpmyadmin-syslog'], ['actionstop', '<iptables> -D INPUT -p tcp -m multiport --dports http,https -j f2b-phpmyadmin-syslog\n<iptables> -F f2b-phpmyadmin-syslog\n<iptables> -X f2b-phpmyadmin-syslog'], ['actionflush', '<iptables> -F f2b-phpmyadmin-syslog'], ['actioncheck', "<iptables> -n -L INPUT | grep -q 'f2b-phpmyadmin-syslog[ \\t]'"], ['actionban', '<iptables> -I f2b-phpmyadmin-syslog 1 -s <ip> -j <blocktype>'], ['actionunban', '<iptables> -D f2b-phpmyadmin-syslog -s <ip> -j <blocktype>'], ['name', 'phpmyadmin-syslog'], ['bantime', '10m'], ['port', 'http,https'], ['protocol', 'tcp'], ['chain', '<known/chain>'], ['actname', 'iptables-multiport'], ['blocktype', 'REJECT --reject-with icmp-port-unreachable'], ['returntype', 'RETURN'], ['lockingopt', '-w'], ['iptables', 'iptables <lockingopt>'], ['blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unreachable'], ['iptables?family=inet6', 'ip6tables <lockingopt>']]]
['start', 'phpmyadmin-syslog']
```
#### Any customizations done to /etc/fail2ban/ configuration
```
backend = systemd
```
#### Relevant parts of /var/log/fail2ban.log file:
```
2020-03-08 20:18:36,043 fail2ban.filter         [548645]: INFO    [phpmyadmin-syslog] Ignore <HOST> by ip
```
#### Relevant lines from monitored log files in question:
```
Mar 08 20:18:35 hostname.example.com phpMyAdmin[550900]: user denied: bad_user (mysql-denied) from <HOST>
Mar 08 20:19:38 hostname.example.com phpMyAdmin[550977]: user denied: bad_user (mysql-denied) from <HOST>
```

**Comment by sebres** [comment]
No idea at the moment what exactly can cause that. Excepting possibly #2444 - to avoid "too many open files" issue on a lot of users systemd journals, the default `journalflags` is changed to system only (4).

If your unprivileged user logs to different journal file, you'll see different results using this:
```bash
# system journal only:
fail2ban-regex systemd-journal phpmyadmin-syslog
# local journals:
fail2ban-regex 'systemd-journal[journalflags=1]' phpmyadmin-syslog
```

Then either try to force php-fpm (or user unit even) to log into main system instance of journal, or specify `backend = systemd[journalflags=1]` for this jail to consider all journals (just note that in this case you could catch another issue, like #2392).

**Comment by twheel** [comment]
> If your unprivileged user logs to different journal file, you'll see different results using this:

This is exactly what’s happening, thank you!

fail2ban-regex systemd-journal phpmyadmin-syslog
`Failregex: 33 total`

fail2ban-regex 'systemd-journal[journalflags=1]' phpmyadmin-syslog
`Failregex: 38 total`

Do you know how I can force php-fpm to log into the main system instance of the journal?

**Comment by sebres** [comment]
You have to change target of journal for the service... For example take a look in [journald.conf(5)](https://manpages.debian.org/testing/systemd/journald.conf.5.en.html) for `SplitMode`.

For example specifying this in journald.conf of your php-fpm unit could solve that:
```ini
[Journal]
SplitMode=none
```
But note the documentation:
> In this mode unprivileged users generally do not have access to their own log data.

You can also configure forwarding to traditional syslog daemon as well as then replicate/redirect it related to facility or severity of message.
