### ISSUE TITLE
fail2ban-regex doesn't honor mode settings in jail.local

### ISSUE THREAD

**Issue by rhavenn** [fail2ban/fail2ban#2655]
FreeBSD server with the latest version installed from ports. I was trying to verify my configuration was matching, etc...for sshd service by using fail2ban-regex.

`fail2ban-regex /var/log/auth.log /usr/local/etc/fail2ban/filter.d/sshd.conf`

This doesn't seem to honor the `mode=aggressive` setting in the jail.local file, so it appeared as though my key exchange failures, etc...weren't matching when they in fact were. Perhaps an option to load the configure file? or at least a mention in the man page about editing the filter file manually for the mode for testing.

It worked fine once I edited `sshd.conf` to have _aggressive_ set.

thanks for the tool!

**Comment by sebres** [comment]
> This doesn't seem to honor the mode=aggressive setting in the jail.local file

It works as documented (yet)... `fail2ban-regex` tests either the filter or the regex, Jail settings (neither local nor default) are not involved at all at the moment.

I have a development branch where the behavior is changed (if name of jail is supplied instead of filter file name).
Unless it's not yet merged (for version >= 0.10) you can supply the filter parameters to the filter (in the same way the jail config doing that), for example:
```bash
fail2ban-regex /var/log/auth.log 'sshd[mode=aggressive]'
```

**Comment by trobriander** [comment]
> It worked fine once I edited `sshd.conf` to have _aggressive_ set.
> 


I thought I was going crazy. I did the same thing as you to make it work. 

These did not work in jail.local (using Fail2Ban **v0.10.5**)

`[sshd]
enabled  = true
filter = sshd[mode=aggressive]
logpath  = /var/log/secure
maxretry = 5
mode     = aggressive`

**Comment by sebres** [comment]
> These did not work in jail.local (using Fail2Ban v0.10.5)

What do you mean as "did not work"?... 
**This RFE is still open** (so not yet implemented) - as already said `fail2ban-regex` does not consider jail-settings at all.
The second argument supplied to `fail2ban-regex` is a `failregex` or `filter` (path or name), **nothing from jails-settings is read at all** yet.

But the filter support parameters, so to test what you want (as written above) use:
```bash
fail2ban-regex /var/log/secure sshd[mode=aggressive]
```

If you mean it does not work in fail2ban-server, you should check our [wiki here](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works)...

And last but not least, don't overwrite filter in jail, it is enough to set `mode` of jail to do the same thing (regardless `fail2ban-regex` problem):
```ini
[sshd]
enabled  = true
mode     = aggressive
logpath  = /var/log/secure
```
which is supplied to the filter (as specified in default section).

**Comment by trobriander** [comment]
> ```shell
> fail2ban-regex /var/log/secure sshd[mode=aggressive]
> ```
 
Thanks, that is good to know. And yes the below is what I originally tried. 

> ```ini
> [sshd]
> enabled  = true
> mode     = aggressive
> logpath  = /var/log/secure
> ```

**Comment by sebres** [comment]
`fail2ban-regex` extended to load settings from jail (by simple name it'd prefer jail to the filter now);
to load the settings from filter one could use filter name with extension or short filter path:
```diff
- fail2ban-regex ... sshd           ; # jail (jail.conf + jail.local)
+ fail2ban-regex ... sshd.conf      ; # filter (sshd.conf + sshd.local)
# or:
+ fail2ban-regex ... filter.d/sshd  ; # filter (sshd.conf + sshd.local)
```
