### ISSUE TITLE
How to monitor fail2ban status (on host) from inside docker container?

### ISSUE THREAD

**Issue by positron96** [fail2ban/fail2ban#2659]
I've tried to search here and on google, but have not found an answer. This is either an enhancement-proposal or a how-to-question.

I have a telegraf docker сontainer that is monitoring my server. fail2ban is protecting host system and I'd like to moitor the status of fail2ban jails via telegraf. There is a plugin in telegraf for that, but it calls fail2ban-client which is not present inside container. 

Is there an easy way to feed fail2ban status into a container? 
I tried to mount fail2ban-client binary and fail2ban.sock inside container, but it obviously required python and a bunch of other stuff that telegraf container does not have.

PS This issue is basically from here: https://github.com/influxdata/telegraf/issues/4953

**Comment by sebres** [comment]
Fail2ban uses a socket for communication between client and server, per default it is unix socket, something like `?/var?/run/fail2ban/fail2ban.sock`.
You can specify it in `fail2ban.conf` or `fail2ban.local` as well as provide via command-line parameter `-s` by call of `fail2ban-client` (or `fail2ban-sever`), which overwrite the value from config file.

Either you have to provide it inside docket to correct (shared) path that corresponds the path to the host where fail2ban-server is running (also note the answer to similar question https://github.com/fail2ban/fail2ban/issues/2649#issuecomment-594626516), or you have to switch to another socket type like tcp-port or something else what you can use for communication between docker and host system.

**Comment by positron96** [comment]
Thanks for the response! 
Your answer only covers the way to make socket available inside container, but it also requires running fail2ban-client inside docker container, right? Is there a way to do it when that container does not have any python facilities (telegraf is a bare golang app. so the container is minimal)? Or is socket protocol documented anywhere so that one can prototype a simple bash script to query status?

**Comment by sebres** [comment]
Yes but then you have either to simulate python pickle protocol (it's not too hard) or if you can provide readonly access to fail2ban.sqlite database you could read the status from there (at least the bans).
If interesting I can provide here the statements to retrieve current bans and bans from some last period (depending on dbpurge). It is important to know the Fail2ban version.

**Comment by positron96** [comment]
That would be very interesting, thank you! The version is 0.9.6, directly from debian 9 repos.

**Comment by sebres** [comment]
OK, up to 0.11 the statement to gets active bans could looks like this:
```sql
select jail, ip, 
  datetime(timeofban, 'unixepoch', 'localtime') as 'beginofban', 
  datetime(timeofban+bantime, 'unixepoch', 'localtime') as 'endofban', 
  bantime
from bans
-- where endofban > now:
where datetime(timeofban + bantime, 'unixepoch', 'localtime') > datetime('now', 'localtime')
order by jail, ip
```
But note that you don't have the field `bantime` in 0.9th database, so you have to replace it with value of bantime (in seconds) configured for corresponding jail (and then repeat that statement for several jails with different bantimes, adding criteria `and jail in ('sshd', 'dovecot', ...)` grouped by bantime).

Newest version (>= 0.11) have already this field in the `bans` table.

Of course you can use it from batch (shell) using something like that:
```bash
sqlite3 'file:/var/lib/fail2ban/fail2ban.sqlite3?mode=ro' "$sql"
```
Note: open it readonly to avoid blocking of fail2ban to long time.
