### ISSUE TITLE
Postfix SASL authentification errors not caught in version 0.10.5 on fedora 31

### ISSUE THREAD

**Issue by kovarto** [fail2ban/fail2ban#2663]
I have upgraded from 0.10.4 to 0.10.5 on fedora 31, x86_64, using standard unchanged installation files. The jail postfix-sasl stopped working, it is not catching any messages from syslog. All other jails (dovecot, sshd) are working as usual.
Downgrading back to 0.10.4 solves the issue - again, nothing changed (only jail.local -
```
[DEFAULT]
banaction = iptables-multiport
[postfix-sasl]
enabled = true
findtime = 2h
maxretry = 3
bantime = 24h
[dovecot]
enabled = true
findtime = 2h
maxtretry = 3
bantime = 24h
[sshd]
enabled = true
findtime = 5m
maxretry = 5
bantime = 3d
```
)

**Comment by sebres** [comment]
Our issue template was made not for nothing and it is basically pretty clear.
Either you can provide the expected info described there, or you can try to seek help by fedora maintainers or open a ticket in the responsible issue tracker.

You could also check it by yourself (compare the output of following command before and after upgrade):
```
fail2ban-client -d | grep postfix-sasl
```

Also note the answer for first question in this FAQ on our [wiki](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works).

Closed unless more info provided.
