### ISSUE TITLE
already banned from sshd and pam-generic jails, firewalld not banning?

### ISSUE THREAD

**Issue by RobbieTheK** [fail2ban/fail2ban#2666]
Running `fail2ban-0.10.5-2.fc31.noarch`, so Fedora 31. I'm getting several IP's that appear to be bypassing the ban.

Why would the `recidive `jail not be picking up on this IP? See the jail settings at the end.

Log snips:

```
2020-03-11 11:14:29,382 fail2ban.actions        [1539290]: WARNING [pam-generic] 150.136.217.144 already banned
2020-03-11 11:14:30,602 fail2ban.filter         [1539290]: INFO    [sshd] Found 150.136.217.144 - 2020-03-11 11:14:30
2020-03-11 11:14:31,140 fail2ban.actions        [1539290]: WARNING [sshd] 150.136.217.144 already banned
2020-03-11 11:14:31,352 fail2ban.filter         [1539290]: INFO    [sshd] Found 150.136.217.144 - 2020-03-11 11:14:30
2020-03-11 11:14:31,356 fail2ban.filter         [1539290]: INFO    [pam-generic] Found 150.136.217.144 - 2020-03-11 11:14:30
2020-03-11 11:14:33,316 fail2ban.filter         [1539290]: INFO    [sshd] Found 150.136.217.144 - 2020-03-11 11:14:33
2020-03-11 11:14:33,318 fail2ban.filter         [1539290]: INFO    [sshd] Found 150.136.217.144 - 2020-03-11 11:14:33
2020-03-11 11:14:33,604 fail2ban.filter         [1539290]: INFO    [pam-generic] Found 150.136.217.144 - 2020-03-11 11:14:33
2020-03-11 11:14:36,352 fail2ban.filter         [1539290]: INFO    [sshd] Found 150.136.217.144 - 2020-03-11 11:14:35
2020-03-11 11:14:38,559 fail2ban.filter         [1539290]: INFO    [sshd] Found 150.136.217.144 - 2020-03-11 11:14:38
2020-03-11 11:14:38,602 fail2ban.filter         [1539290]: INFO    [pam-generic] Found 150.136.217.144 - 2020-03-11 11:14:38
2020-03-11 11:14:38,796 fail2ban.actions        [1539290]: WARNING [pam-generic] 150.136.217.144 already banned
2020-03-11 11:14:39,152 fail2ban.actions        [1539290]: WARNING [sshd] 150.136.217.144 already banned
2020-03-11 11:14:40,352 fail2ban.filter         [1539290]: INFO    [sshd] Found 150.136.217.144 - 2020-03-11 11:14:40
2020-03-11 11:14:40,852 fail2ban.filter         [1539290]: INFO    [sshd] Found 150.136.217.144 - 2020-03-11 11:14:40
2020-03-11 11:14:40,856 fail2ban.filter         [1539290]: INFO    [pam-generic] Found 150.136.217.144 - 2020-03-11 11:14:40
2020-03-11 11:14:43,061 fail2ban.filter         [1539290]: INFO    [sshd] Found 150.136.217.144 - 2020-03-11 11:14:42
2020-03-11 11:14:43,063 fail2ban.filter         [1539290]: INFO    [sshd] Found 150.136.217.144 - 2020-03-11 11:14:43
2020-03-11 11:14:43,603 fail2ban.filter         [1539290]: INFO    [pam-generic] Found 150.136.217.144 - 2020-03-11 11:14:43
2020-03-11 11:14:45,352 fail2ban.filter         [1539290]: INFO    [sshd] Found 150.136.217.144 - 2020-03-11 11:14:45
2020-03-11 11:14:45,852 fail2ban.filter         [1539290]: INFO    [sshd] Found 150.136.217.144 - 2020-03-11 11:14:45
2020-03-11 11:14:45,856 fail2ban.filter         [1539290]: INFO    [pam-generic] Found 150.136.217.144 - 2020-03-11 11:14:45
```

jail.local snip:

```
[DEFAULT]
bantime = 3600
sender = root

#action = %(action_mwl)s
action = %(action_)s
#backend = polling
#default_backend = polling
mta = sendmail
#loglevel = DEBUG
backend = auto
banaction = firewallcmd-ipset
#banaction_allports = firewallcmd-ipset
[sshd]
filter = sshd[mode=aggressive]
#filter = sshd
enabled = true
logpath  = /var/log/secure
port    = ssh,sftp

[pam-generic]
enabled  = true
# pam-generic filter can be customized to monitor specific subset of 'tty's
filter   = pam-generic
# port actually must be irrelevant but lets leave it all for some possible
uses
port     = all
#banaction = iptables-allports
#port     = anyport
backend  = pyinotify
logpath  = /var/log/secure
maxretry = 3

[recidive]
enabled  = true
filter   = recidive
logpath  = /var/log/fail2ban.log
           /var/log/fail2ban.log-[!.gz]
banaction = firewallcmd-ipset
action =   badips[category="ssh", key="xxxx"]
bantime   =  -1 ; permanent
findtime = 86400   ; 1 day
maxretry = 3
```

Here's a `fail2ban-client -d | grep 'pam-generic'`

```
['add', 'pam-generic', 'systemd']
['set', 'pam-generic', 'usedns', 'warn']
['set', 'pam-generic', 'prefregex', '^\\s*(?:\\S+\\s+)?(?:\\S*(?:\\[\\d+\\])?:?\\s+)?(?:kernel:\\s?\\[ *\\d+\\.\\d+\\]:?\\s+)?\\(?pam_unix(?:\\(\\S+\\))?\\)?:?\\s+authentication failure;(?:\\s+(?:(?:logname|e?uid)=\\S*)){0,3} tty=\\S* <F-CONTENT>.+</F-CONTENT>$']
['set', 'pam-generic', 'addfailregex', '^ruser=<F-ALT_USER>(?:\\S*|.*?)</F-ALT_USER> rhost=<HOST>(?:\\s+user=<F-USER>(?:\\S*|.*?)</F-USER>)?\\s*$']
['set', 'pam-generic', 'datepattern', '{^LN-BEG}']
['set', 'pam-generic', 'maxretry', 3]
['set', 'pam-generic', 'maxmatches', 3]
['set', 'pam-generic', 'findtime', '900']
['set', 'pam-generic', 'bantime', '3600']
['set', 'pam-generic', 'ignorecommand', '']
['set', 'pam-generic', 'addignoreip', '127.0.0.1/8']
['set', 'pam-generic', 'logencoding', 'auto']
['set', 'pam-generic', 'addaction', 'firewallcmd-ipset']
['multi-set', 'pam-generic', 'action', 'firewallcmd-ipset', [['actionstart', 'ipset create <ipmset> hash:ip timeout <bantime><familyopt>\nfirewall-cmd --direct --add-rule <family> filter INPUT_direct 0 -p tcp -m set --match-set <ipmset> src -j REJECT --reject-with <rejecttype>'], ['actionstop', 'firewall-cmd --direct --remove-rule <family> filter INPUT_direct 0 -p tcp -m set --match-set <ipmset> src -j REJECT --reject-with <rejecttype>\nipset flush <ipmset>\nipset destroy <ipmset>'], ['actionflush', 'ipset flush <ipmset>'], ['actionban', 'ipset add <ipmset> <ip> timeout <bantime> -exist'], ['actionunban', 'ipset del <ipmset> <ip> -exist'], ['actiontype', '<allports>'], ['name', 'pam-generic'], ['bantime', '0'], ['port', '0:65535'], ['protocol', 'tcp'], ['chain', '<known/chain>'], ['actname', 'firewallcmd-ipset'], ['family', 'ipv4'], ['zone', 'public'], ['service', 'ssh'], ['rejecttype', 'icmp-port-unreachable'], ['blocktype', 'REJECT --reject-with <rejecttype>'], ['rich-blocktype', "reject type='<rejecttype>'"], ['family?family=inet6', 'ipv6'], ['rejecttype?family=inet6', 'icmp6-port-unreachable'], ['allports', '-p <protocol>'], ['multiport', '-p <protocol> -m multiport --dports <port>'], ['ipmset', 'f2b-<name>'], ['familyopt', ''], ['ipmset?family=inet6', 'f2b-<name>6'], ['familyopt?family=inet6', '<sp>family inet6']]]
['start', 'pam-generic']
```

`firewalld `is running. the status shows it's good. Below are some other firewalld commands and ipset results.  
```
systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled;
vendor preset: enabled)
   Active: active (running) since Sun 2020-02-02 02:22:56 EST; 1 months 8
days ago
     Docs: man:firewalld(1)
 Main PID: 1462547 (firewalld)
    Tasks: 3 (limit: 76733)
   Memory: 38.5M
      CPU: 27min 44.617s
   CGroup: /system.slice/firewalld.service
           └─1462547 /usr/bin/python3 /usr/sbin/firewalld --nofork --nopid

Warning: Journal has been rotated since unit was started. Log output is
incomplete or unavailable.
```

Is something misconfigured with `firewalld`? Shouldn't `ipset list` show banned IPs?

```
firewall-cmd --direct --get-all-rules
ipv4 filter INPUT_direct 0 -p tcp -m multiport --dports http,https -m set
--match-set f2b-nginx-botsearch src -j REJECT --reject-with
icmp-port-unreachable

ipset list
Name: f2b-sshd
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536 timeout 3600
Size in memory: 21976
References: 0
Number of entries: 0
Members:

Name: f2b-pam-generic
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536 timeout 3600
Size in memory: 10456
References: 0
Number of entries: 0
Members:

Name: f2b-apache-botsearch
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536 timeout 3600
Size in memory: 9592
References: 0
Number of entries: 0
Members:
Name: f2b-apache-noscript
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536 timeout 3600
Size in memory: 6328
References: 0
Number of entries: 0
Members:

Name: f2b-apache-auth
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536 timeout 3600
Size in memory: 1144
References: 0
Number of entries: 0
Members:

Name: f2b-nginx-botsearch
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536 timeout 3600
Size in memory: 568
References: 1
Number of entries: 0
Members:
```

**Comment by sebres** [comment]
>  I'm getting several IP's that appear to be bypassing the ban.

Why we are continuously discussing the same (all the reasons why it can be is described in our [wiki](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works)), I have nothing further to add here.

Also please examine your fail2ban.log whether you'd find some errors there.
And because firewalld is not really native net-filter sub-system (it is just a front-end management tool), also examine your native backend (iptables, nftables and ipset) that will be controlled by firewalld.

> Is something misconfigured with firewalld? 

Also this was already many times answered, for example in #1609 (see also https://github.com/fail2ban/fail2ban/issues/2503#issuecomment-53310550 as well as original firewalld issue for that https://github.com/t-woerner/firewalld/issues/44)?

So yes, but rather not with firewalld directly, either default firewalld configuration is not really suitable for fail2ban (or some other blacklists) - the iptables net-filter seems to be "misconfigured" by firewalld in the way how it creates the basic rules, so it is quasi impossible to ban something (create black-listing rules before white-listing rules allowing something).

> Shouldn't ipset list show banned IPs?

Yes, but I don't see any output of ipset in your excerpts. 
If you mean all the `Number of entries: 0`, then it is not an issue, I guess this is because current implementation of action `firewallcmd-ipset` doesn't use native firewalld ipset implementation (there is a PR #2620 which would probably solve that).
So check it with `ipset list`, but it would not help. unless firewalld does not create net-filter rules properly (see firewalld issue above).

> Why would the recidive jail not be picking up on this IP? See the jail settings at the end.

Oh people, really?
Please don't mix several things in single issue.
But shortly:
1. do you see `[recidive] Found` in log?
2. do you see `[recidive] Ban` in log?
3. do you still remember your issue #2569 (because your recidive configuration seems to be still the same).

There are still dozen other questions the most of all are answered in our wiki.

**Comment by RobbieTheK** [comment]
> Also please examine your fail2ban.log whether you'd find some errors there.
> And because firewalld is not really native net-filter sub-system (it is just a front-end management tool), also examine your native backend (iptables, nftables and ipset) that will be controlled by firewalld.

Finally some progress with Fedora/CentOS maintainers of Fail2ban, have a [look at this Bugzilla entry](https://bugzilla.redhat.com/show_bug.cgi?id=1823746#c0):

> The default banaction set by fail2ban-firewalld in the jail.d/00-firewalld.conf file is firewallcmd-ipset. This will run 'firewall-cmd --direct' iptables-commands as the action, which will not have any effect since firewalld uses nftables as its default backend (on CentOS 8).
> 
> Changing the default banaction to firewallcmd-rich-rules fixes this issue.

Also look at [comment 19](https://bugzilla.redhat.com/show_bug.cgi?id=1823746#c19). The `port `option is broken if using `any `or `allports`, so `port = 0-65535` is the work around (dash rather than colon)

> > Is something misconfigured with firewalld?
> 
> Also this was already many times answered, for example in #1609 (see also #2503 (comment) as well as original firewalld issue for that https://github.com/t-woerner/firewalld/issues/44)?

Broken link on the Firewalld Github issue.

> Also this was already many times answered, for example in #1609 (see also [#2503 (comment)](https://github.com/fail2ban/fail2ban/issues/2503#issuecomment-53310550) as well as original firewalld 
> > Why would the recidive jail not be picking up on this IP? See the jail settings at the end.
> 
> Oh people, really?
> Please don't mix several things in single issue.
> But shortly:
> 
> 1. do you see `[recidive] Found` in log?
> 2. do you see `[recidive] Ban` in log?

From [my comment at the BZ entry](https://bugzilla.redhat.com/show_bug.cgi?id=1823746#c20), I can't get `recidive `to work with `firewalld/ipset/rich-rules`, but reverting to `iptables `works fine.
