### ISSUE TITLE
An incomprehensible error when starting fail2ban

### ISSUE THREAD

**Issue by lokha** [fail2ban/fail2ban#2668]
version - 0.10.6-dev

```shell
root@vm7:~# fail2ban-client -d
['set', 'syslogsocket', 'auto']
['set', 'loglevel', 'DEBUG']
['set', 'logtarget', '/var/log/fail2ban.log']
['set', 'dbfile', '/var/lib/fail2ban/fail2ban.sqlite3']
['set', 'dbmaxmatches', 10]
['set', 'dbpurgeage', '1d']
```

```shell
root@vm7:~# service fail2ban restart
Job for fail2ban.service failed because the control process exited with error code.
See "systemctl status fail2ban.service" and "journalctl -xe" for details.
```

journalctl -xe:
```shell
Mar 25 05:08:16 vm7.mineland.net systemd[1]: Starting LSB: Start/stop fail2ban...
-- Subject: Unit fail2ban.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit fail2ban.service has begun starting up.
Mar 25 05:08:16 vm7.mineland.net fail2ban[31542]: Starting Authentication failure monitor: fail2ban failed!
Mar 25 05:08:16 vm7.mineland.net systemd[1]: fail2ban.service: Control process exited, code=exited status=1
Mar 25 05:08:16 vm7.mineland.net systemd[1]: Failed to start LSB: Start/stop fail2ban.
-- Subject: Unit fail2ban.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit fail2ban.service has failed.
--
-- The result is failed.
Mar 25 05:08:16 vm7.mineland.net systemd[1]: fail2ban.service: Unit entered failed state.
Mar 25 05:08:16 vm7.mineland.net systemd[1]: fail2ban.service: Failed with result 'exit-code'.

```

the log /var/log/fail2ban.log does not create

I have no jails yet
```shell
root@vm7:~# fail2ban-client status
Status
|- Number of jail:      0
`- Jail list:
```

I tried deleting /var/lib/fail2ban/fail2ban.sqlite3, it did not help

but at the same time everyone, fail2ban-client reload writes "OK"

**Comment by sebres** [comment]
> the log /var/log/fail2ban.log does not create

Hmm... it seems that fail2ban-server doesn't started yet (or `--logtarget` specified in service unit file is something other).

> service fail2ban restart

I have no idea how your systemd or sysv unit does look (it is matter of maintainer for your distribution, at least if you use unit from your distribution)...
I guess something is not correct in the configs (paths etc) or even unit expected something.

To check what is going on here please call it directly:
```
# to start:
?sudo? fail2ban-client -vv start
# to restart:
?sudo? fail2ban-client -vv restart
# to stop:
?sudo? fail2ban-client stop
```
If it is working (without error), please provide your service unit file.

Anyway with our default systemd-unit (see template [fail2ban.service.in](https://github.com/fail2ban/fail2ban/blob/0.10/files/fail2ban.service.in)), a start as well as a restart work pretty well (regardless the existence of jails).

**Comment by lokha** [comment]
I'm sorry, I forgot about this issue. and, unfortunately, I already forgot how I solved the problem for myself. but thanks for your reply
