### ISSUE TITLE
SElinux blocks access to IPv6 disable flag

### ISSUE THREAD

**Issue by verne-wv** [fail2ban/fail2ban#2669]
#2217 # Environment:
installed 0.10.5-2 from EPEL on RedHat7

this system has IPv6 disabled, causing this file to contain an ASCII 0

/sys/module/ipv6/parameters/disable

one configuration generates errors in /var/log/messages from SELinux as

SELinux is preventing /usr/bin/python2.7 from read access on the file disable.
[...]
fix with ... ausearch -c 'f2b/f.xmlrpc'   ...

.. so I tried to fix that with a custom SELinux policy of 

require {
        type sysfs_t;
        type fail2ban_t;
        class file read;
}

#============= fail2ban_t ==============
allow fail2ban_t sysfs_t:file read;

now I get another SELinux error message

SELinux is preventing f2b/f.wordpress from open access on the file /sys/module/ipv6/parameters/disable

and the suggested fix from audit2allow is

require {
        type sysfs_t;
        type fail2ban_t;
        class file { open read };
}

#============= fail2ban_t ==============
allow fail2ban_t sysfs_t:file open;

#!!!! This avc is allowed in the current policy
allow fail2ban_t sysfs_t:file read;

first, how do I find out exactly what and why the tags/modules/names of f2b/f.xmlrpc and f2b/f.wordpress are reported and what these modules even do ?

Maybe I don't understand ... is reading that file the common way, perhaps the only way, to determine if IPv6 is enabled or disabled?

https://bugzilla.redhat.com/show_bug.cgi?id=1777562 suggests their is an updated SELinux policy for Centos8/RedHat8 to handle this .... but I was hoping for a more elegant way to just tell fail2ban not to bother reading that file.

As far as I can tell, fail2ban continues to run, but generates a number of SELinux messsages in /var/log/messages ... so maybe my issue is just cosmetic.

the test jail I created has the filter of

[Definition]
failregex = <HOST>.*POST \/wordpress\/wp-login\.php

and is configured with (from jail.local)

[wordpress_brutes]
enabled = true
logpath = /var/log/virtualmin/*_access_log
filter = filter_wordpress_brutes
action = iptables-allports[name=wordpress_brutes,protocol=tcp]
maxretry = 2

thoughts anyone ?

**Comment by sebres** [comment]
> first, how do I find out exactly what and why the tags/modules/names of f2b/f.xmlrpc and f2b/f.wordpress are reported and what these modules even do ?

`f2b/f.xmlrpc` and `f2b/f.wordpress` are names for filter threads (in 0.10.5), and I think the IPv6 access that here could happen only were DNS-resolve to check the found address is a foreign address (due to `ignoreself` option which is true per default). Unless the filter would indeed (mistakenly) catch some IPv6 or host (by enabled `usedns`) that can be resolved to IPv6.

Normally fail2ban should get a new parameter to disable/enable IPv6, but it was no need until now.

**Comment by sebres** [comment]
See https://github.com/fail2ban/fail2ban/issues/2804#issuecomment-768394379 for such a new option to disable / enable IPv6.

**Comment by SpareSimian** [comment]
For those who trip over this bug and find this issue, here's a good analysis. TLDR, remove myhostname from your /etc/nsswitch.com file. 
https://shaunc.com/blog/article/resolving-selinux-audit-failures-with-fail2ban-on-rhel-centos-7~P6MRkQ7kgegt
