### ISSUE TITLE
There is IP in the banned list, but why hasn't this IP been forbidden to access my server through HTTP

### ISSUE THREAD

**Issue by meansw** [fail2ban/fail2ban#2672]
I wanted to disable scanning my web server for malicious IP, but I ran into a problem.

1. I created a web404.conf file in the following path
`/etc/fail2ban/filter.d/web404.conf`
The contents are as follows:
```
[Definition]
failregex = ^<HOST>.*"(GET|POST).*" (404|444|403|400) .*$

```
2. I created a file jal.local in the following path
`/etc/fail2ban/jail.local`
The contents are as follows:
```
[DEFAULT]
bantime = 86400
findtime = 200
Maxretry = 5
[web404]
enabled  = true
filter   = web404
action   = firewallcmd-ipset[name=web404, port=http, protocol=tcp]
logpath  = /var/log/httpd/access_log
bantime  = 86400
Maxretry = 5
```

3. Use the fail2ban-client reload command,
Get the following information:
```
WARNING 'ignoreregex' not defined in 'Definition'. Using default one: ''
WARNING 'actioncheck' not defined in 'Definition'. Using default one: ''
```

4. Use the firewall-cmd -- direct -- get-all-rules command,
Get the following information:
`ipv4 filter INPUT_direct 0 -p tcp -m multiport --dports http -m set --match-set fail2ban-web404 src -j REJECT --reject-with icmp-port-unreachable
`
5. Use the "fail2ban-client status web404" command,
The information is as follows:
```
Status for the jail: web404
- filter
|  |- File list:        /var/log/httpd/access_log
|  |- Currently failed: 1
|  `- Total failed:     8
- action
|- Currently banned: 1
|` - IP list: x x x.xxx.x.xx (this is the IP I use for testing)
`- Total banned:     1
```
6.
```
# ipset list
Name: fail2ban-web404
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536 timeout 600
Size in memory: 312
References: 1
Number of entries: 0
Members:

Name: f2b-web404
Type: hash:ip
Revision: 4
Header: family inet hashsize 1024 maxelem 65536 timeout 86400
Size in memory: 120
References: 0
Number of entries: 0
Members:
```

6. But why the IP I use for testing can still access my server through HTTP?

**Comment by jasononggo** [comment]
> I wanted to disable scanning my web server for malicious IP, but I ran into a problem.
> 
> 1. I created a web404.conf file in the following path
>    `/etc/fail2ban/filter.d/web404.conf`
>    The contents are as follows:
> 
> ```
> [Definition]
> failregex = ^<HOST>.*"(GET|POST).*" (404|444|403|400) .*$
> ```
> 
> 1. I created a file jal.local in the following path
>    `/etc/fail2ban/jail.local`
>    The contents are as follows:
> 
> ```
> [DEFAULT]
> bantime = 86400
> findtime = 200
> Maxretry = 5
> [web404]
> enabled  = true
> filter   = web404
> action   = firewallcmd-ipset[name=web404, port=http, protocol=tcp]
> logpath  = /var/log/httpd/access_log
> bantime  = 86400
> Maxretry = 5
> ```
> 
> 1. Use the fail2ban-client reload command,
>    Get the following information:
> 
> ```
> WARNING 'ignoreregex' not defined in 'Definition'. Using default one: ''
> WARNING 'actioncheck' not defined in 'Definition'. Using default one: ''
> ```
> 
> 1. Use the firewall-cmd -- direct -- get-all-rules command,
>    Get the following information:
>    `ipv4 filter INPUT_direct 0 -p tcp -m multiport --dports http -m set --match-set fail2ban-web404 src -j REJECT --reject-with icmp-port-unreachable `
> 2. Use the "fail2ban-client status web404" command,
>    The information is as follows:
> 
> ```
> Status for the jail: web404
> - filter
> |  |- File list:        /var/log/httpd/access_log
> |  |- Currently failed: 1
> |  `- Total failed:     8
> - action
> |- Currently banned: 1
> |` - IP list: x x x.xxx.x.xx (this is the IP I use for testing)
> `- Total banned:     1
> ```
> 
> 
> ```
> # ipset list
> Name: fail2ban-web404
> Type: hash:ip
> Revision: 4
> Header: family inet hashsize 1024 maxelem 65536 timeout 600
> Size in memory: 312
> References: 1
> Number of entries: 0
> Members:
> 
> Name: f2b-web404
> Type: hash:ip
> Revision: 4
> Header: family inet hashsize 1024 maxelem 65536 timeout 86400
> Size in memory: 120
> References: 0
> Number of entries: 0
> Members:
> ```
> 
> 1. But why the IP I use for testing can still access my server through HTTP?

You closed this issue. I assume you have solved it. I have similar problem, could you please write the resolution here.

**Comment by meansw** [comment]
> > I wanted to disable scanning my web server for malicious IP, but I ran into a problem.
> > 
> > 1. I created a web404.conf file in the following path
> >    `/etc/fail2ban/filter.d/web404.conf`
> >    The contents are as follows:
> > 
> > ```
> > [Definition]
> > failregex = ^<HOST>.*"(GET|POST).*" (404|444|403|400) .*$
> > ```
> > 
> > 
> > 
> > 1. I created a file jal.local in the following path
> >    `/etc/fail2ban/jail.local`
> >    The contents are as follows:
> > 
> > ```
> > [DEFAULT]
> > bantime = 86400
> > findtime = 200
> > Maxretry = 5
> > [web404]
> > enabled  = true
> > filter   = web404
> > action   = firewallcmd-ipset[name=web404, port=http, protocol=tcp]
> > logpath  = /var/log/httpd/access_log
> > bantime  = 86400
> > Maxretry = 5
> > ```
> > 
> > 
> > 
> > 1. Use the fail2ban-client reload command,
> >    Get the following information:
> > 
> > ```
> > WARNING 'ignoreregex' not defined in 'Definition'. Using default one: ''
> > WARNING 'actioncheck' not defined in 'Definition'. Using default one: ''
> > ```
> > 
> > 
> > 
> > 1. Use the firewall-cmd -- direct -- get-all-rules command,
> >    Get the following information:
> >    `ipv4 filter INPUT_direct 0 -p tcp -m multiport --dports http -m set --match-set fail2ban-web404 src -j REJECT --reject-with icmp-port-unreachable `
> > 2. Use the "fail2ban-client status web404" command,
> >    The information is as follows:
> > 
> > ```
> > Status for the jail: web404
> > - filter
> > |  |- File list:        /var/log/httpd/access_log
> > |  |- Currently failed: 1
> > |  `- Total failed:     8
> > - action
> > |- Currently banned: 1
> > |` - IP list: x x x.xxx.x.xx (this is the IP I use for testing)
> > `- Total banned:     1
> > ```
> > 
> > 
> > ```
> > # ipset list
> > Name: fail2ban-web404
> > Type: hash:ip
> > Revision: 4
> > Header: family inet hashsize 1024 maxelem 65536 timeout 600
> > Size in memory: 312
> > References: 1
> > Number of entries: 0
> > Members:
> > 
> > Name: f2b-web404
> > Type: hash:ip
> > Revision: 4
> > Header: family inet hashsize 1024 maxelem 65536 timeout 86400
> > Size in memory: 120
> > References: 0
> > Number of entries: 0
> > Members:
> > ```
> > 
> > 
> > 
> > 1. But why the IP I use for testing can still access my server through HTTP?
> 
> You closed this issue. I assume you have solved it. I have similar problem, could you please write the resolution here.


I do as below, it works in my server:

**```
1.安装：github上的教程；创建链接：如果github上的命令用不了，用fail2ban官网的手册上的命令
下载源码：
git clone https://github.com/fail2ban/fail2ban.git
cd fail2ban
sudo python setup.py install 

cp files/debian-initd /etc/init.d/fail2ban
ln -s /etc/init.d/fail2ban /etc/rc2.d/S20fail2ban
service fail2ban start

2.在/etc/fail2ban/filter.d/创建web404.conf过滤规则
内容：
[Definition]

failregex = ^<HOST>.*"(GET|POST).*" (404|444|403|400) .*$

3.在/etc/fail2ban创建jail.local文件：
[DEFAULT]

enabled = false
bantime = 86400
banaction = firewallcmd-ipset

action = %(action_)s

[web404]

enabled = true
filter  = web404
logpath = /var/log/httpd/access_log

4.在/etc/fail2ban/action.d创建iptables-blocktype.local文件：
[INCLUDES]

after = iptables-blocktype.local

[Init]

blocktype = DROP

5.重启fail2ban：
service fail2ban restart

6.重载fail2ban监狱：
fail2ban-client reload

7.重启防火墙：
firewall-cmd --reload
```**
