### ISSUE TITLE
Not banning asterisk rules, but sshd ban works

### ISSUE THREAD

**Issue by xnext40** [fail2ban/fail2ban#2674]
### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): 0.10.5
- OS, including release name/version: CentOS Linux release 7.7.1908 (Core)
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

banning stops work after update to 0.10.5

manual execute fail2ban-client set asterisk banip x.x.x.x -> works

**Comment by xnext40** [comment]
['add', 'asterisk', 'systemd']
['set', 'asterisk', 'usedns', 'warn']
['set', 'asterisk', 'prefregex', '^\\s*(?:\\S+\\s+)?(?:\\S*(?:\\[\\d+\\])?:?\\s+)?(?:kernel:\\s?\\[ *\\d+\\.\\d+\\]:?\\s+)?(?:NOTICE|SECURITY|WARNING)(?:\\s*\\[\\d+\\]):?(?:\\[C-[\\da-f]*\\])?:?\\s*[^:]+:\\s?\\d* <F-CONTENT>.+</F-CONTENT>$']
['multi-set', 'asterisk', 'addfailregex', ["^Registration from '[^']*' failed for '<HOST>(:\\d+)?' - (?:Wrong password|Username/auth name mismatch|No matching peer found|Not a local domain|Device does not match ACL|Peer is not supposed to register|ACL error \\(permit/deny\\)|Not a local domain)$", "^Call from '[^']*' \\(<HOST>:\\d+\\) to extension '[^']*' rejected because extension not found in context", '^(?:Host )?<HOST> (?:failed (?:to authenticate\\b|MD5 authentication\\b)|tried to authenticate with nonexistent user\\b)', "^No registration for peer '[^']*' \\(from <HOST>\\)$", "^hacking attempt detected '<HOST>'$", '^SecurityEvent="(?:FailedACL|InvalidAccountID|ChallengeResponseFailed|InvalidPassword)"(?:(?:,(?!RemoteAddress=)\\w+="[^"]*")*|.*?),RemoteAddress="IPV[46]/(UDP|TCP|WS)/<HOST>/\\d+"(?:,(?!RemoteAddress=)\\w+="[^"]*")*$', '^"Rejecting unknown SIP connection from <HOST>"$', "^Request (?:'[^']*' )?from '(?:[^']*|.*?)' failed for '<HOST>(?::\\d+)?'\\s\\(callid: [^\\)]*\\) - (?:No matching endpoint found|Not match Endpoint(?: Contact)? ACL|(?:Failed|Error) to authenticate)\\s*$", '^Unknown Call from [\\W\\w\\+]+ to [\\W\\w\\+]+, Details: IP <HOST>.*$']]
['set', 'asterisk', 'datepattern', '{^LN-BEG}']
['set', 'asterisk', 'maxretry', 3]
['set', 'asterisk', 'addignoreip', '127.0.0.1/8', '172.17.0.0/12', '128.75.229.70', '81.88.194.44', '109.248.225.2', '178.140.48.8', '37.16.82.101', '37.46.247.189', '37.57.168.92', '37.46.247.228', '213.170.92.166', '81.18.128.190', '173.212.249.206', '95.181.202.193', '95.131.26.210', '82.149.203.98', '94.100.82.86', '95.79.59.21', '178.249.242.51', '195.18.25.99', '193.34.92.30', '194.146.228.114', '178.20.238.194', '91.224.140.219', '91.224.140.179', '91.224.140.180', '91.224.140.181', '91.224.140.182', '91.224.140.183', '91.224.140.184', '91.224.140.216', '91.224.140.211', '213.170.92.166', '77.72.132.130']
['set', 'asterisk', 'logencoding', 'auto']
['set', 'asterisk', 'bantime', '86400']
['set', 'asterisk', 'ignorecommand', '']
['set', 'asterisk', 'findtime', '10m']
['set', 'asterisk', 'addaction', 'iptables-multiport-tcp']
['multi-set', 'asterisk', 'action', 'iptables-multiport-tcp', [['actionunban', '<iptables> -D f2b-asterisk-tcp -s <ip> -j <blocktype>'], ['actionflush', '<iptables> -F f2b-asterisk-tcp'], ['actionstop', '<iptables> -D INPUT -p tcp -m multiport --dports 5060,5061,5038,8088 -j f2b-asterisk-tcp\n<iptables> -F f2b-asterisk-tcp\n<iptables> -X f2b-asterisk-tcp'], ['actionstart', '<iptables> -N f2b-asterisk-tcp\n<iptables> -A f2b-asterisk-tcp -j RETURN\n<iptables> -I INPUT -p tcp -m multiport --dports 5060,5061,5038,8088 -j f2b-asterisk-tcp'], ['actionban', '<iptables> -I f2b-asterisk-tcp 1 -s <ip> -j <blocktype>'], ['actioncheck', "<iptables> -n -L INPUT | grep -q 'f2b-asterisk-tcp[ \\t]'"], ['iptables', 'iptables <lockingopt>'], ['lockingopt', '-w'], ['blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unreachable'], ['protocol', 'tcp'], ['name', 'asterisk-tcp'], ['chain', '<known/chain>'], ['returntype', 'RETURN'], ['iptables?family=inet6', 'ip6tables <lockingopt>'], ['blocktype', 'REJECT --reject-with icmp-port-unreachable'], ['actname', 'iptables-multiport-tcp'], ['port', '5060,5061,5038,8088']]]
['set', 'asterisk', 'addaction', 'iptables-multiport-udp']
['multi-set', 'asterisk', 'action', 'iptables-multiport-udp', [['actionunban', '<iptables> -D f2b-asterisk-udp -s <ip> -j <blocktype>'], ['actionflush', '<iptables> -F f2b-asterisk-udp'], ['actionstop', '<iptables> -D INPUT -p udp -m multiport --dports 5060,5061,5038,8088 -j f2b-asterisk-udp\n<iptables> -F f2b-asterisk-udp\n<iptables> -X f2b-asterisk-udp'], ['actionstart', '<iptables> -N f2b-asterisk-udp\n<iptables> -A f2b-asterisk-udp -j RETURN\n<iptables> -I INPUT -p udp -m multiport --dports 5060,5061,5038,8088 -j f2b-asterisk-udp'], ['actionban', '<iptables> -I f2b-asterisk-udp 1 -s <ip> -j <blocktype>'], ['actioncheck', "<iptables> -n -L INPUT | grep -q 'f2b-asterisk-udp[ \\t]'"], ['iptables', 'iptables <lockingopt>'], ['lockingopt', '-w'], ['blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unreachable'], ['protocol', 'udp'], ['name', 'asterisk-udp'], ['chain', '<known/chain>'], ['returntype', 'RETURN'], ['iptables?family=inet6', 'ip6tables <lockingopt>'], ['blocktype', 'REJECT --reject-with icmp-port-unreachable'], ['actname', 'iptables-multiport-udp'], ['port', '5060,5061,5038,8088']]]
['set', 'asterisk', 'addaction', 'sendmail-whois']
['multi-set', 'asterisk', 'action', 'sendmail-whois', [['actionunban', ''], ['norestored', True], ['actionstop', 'printf %b "Subject: [Fail2Ban] asterisk: stopped on <fq-hostname>\nDate: `LC_ALL=C date +"%a, %d %h %Y %T %z"`\nFrom: Fail2Ban <fail2ban>\nTo: root@localhost\\n\nHi,\\n\nThe jail asterisk has been stopped.\\n\nRegards,\\n\nFail2Ban" | /usr/sbin/sendmail -f "fail2ban" "root@localhost"'], ['actionstart', 'printf %b "Subject: [Fail2Ban] asterisk: started on <fq-hostname>\nDate: `LC_ALL=C date +"%a, %d %h %Y %T %z"`\nFrom: Fail2Ban <fail2ban>\nTo: root@localhost\\n\nHi,\\n\nThe jail asterisk has been started successfully.\\n\nRegards,\\n\nFail2Ban" | /usr/sbin/sendmail -f "fail2ban" "root@localhost"'], ['actionban', 'printf %b "Subject: [Fail2Ban] asterisk: banned <ip> from <fq-hostname>\nDate: `LC_ALL=C date +"%a, %d %h %Y %T %z"`\nFrom: Fail2Ban <fail2ban>\nTo: root@localhost\\n\nHi,\\n\nThe IP <ip> has just been banned by Fail2Ban after\n<failures> attempts against asterisk.\\n\\n\nHere is more information about <ip> :\\n\n`whois <ip> || echo "missing whois program"`\\n\nRegards,\\n\nFail2Ban" | /usr/sbin/sendmail -f "fail2ban" "root@localhost"'], ['actioncheck', ''], ['name', 'asterisk'], ['dest', 'root@localhost'], ['mailcmd', '/usr/sbin/sendmail -f "<sender>" "<dest>"'], ['actname', 'sendmail-whois'], ['sendername', 'Fail2Ban'], ['sender', 'fail2ban']]]
['start', 'asterisk']

**Comment by sebres** [comment]
All the reasons, why fail2ban does not find failures or does not ban the IP, have been described in our [wiki](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works).
Shortly check your `backend` and/or `logpath` (whether it is systemd journal or log-file), timezone, etc pp.

Also note that all predefined configurations are matter of maintainers of your distribution.

Otherwise check it with `fail2ban-regex systemd-journal asterisk` (whether you see some matches), provide an exact message that was not recognized, where exactly it was logged, etc. pp.
I'll close it unless more info provided.

**Comment by sebres** [comment]
> Using fail2ban-regex i check **logfiles**

You said "logfiles", but your damp above show the jail is configured with backend `systemd` (that does monitor the journal not the log-file).
If it is really log-file, set `backend = auto` in your `jail.local` for asterisk jail.

> but banning not work

I guess it is rather not the banning that doesn't work, but the failures-messages that are not recognized either (so you does not see `[asterisk] Found ...` in fail2ban.log).

**Comment by xnext40** [comment]
am not using jail.local, i can set backend in jail.d directory file asterisk....?

**Comment by xnext40** [comment]
`['add', 'asterisk', 'auto']
['set', 'asterisk', 'usedns', 'warn']
['set', 'asterisk', 'prefregex', '^(?:\\[\\])?\\s*(?:<[^.]+\\.[^.]+>\\s+)?(?:\\S+\\s+)?(?:kernel:\\s?\\[ *\\d+\\.\\d+\\]:?\\s+)?(?:@vserver_\\S+\\s+)?(?:(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?\\S*(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?\\S*(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)\\s+)?(?:\\[ID \\d+ \\S+\\]\\s+)?(?:NOTICE|SECURITY|WARNING)(?:\\s*\\[\\d+\\]):?(?:\\[C-[\\da-f]*\\])?:?\\s*[^:]+:\\s?\\d* <F-CONTENT>.+</F-CONTENT>$']
['multi-set', 'asterisk', 'addfailregex', ["^Registration from '[^']*' failed for '<HOST>(:\\d+)?' - (?:Wrong password|Username/auth name mismatch|No matching peer found|Not a local domain|Device does not match ACL|Peer is not supposed to register|ACL error \\(permit/deny\\)|Not a local domain)$", "^Call from '[^']*' \\(<HOST>:\\d+\\) to extension '[^']*' rejected because extension not found in context", '^(?:Host )?<HOST> (?:failed (?:to authenticate\\b|MD5 authentication\\b)|tried to authenticate with nonexistent user\\b)', "^No registration for peer '[^']*' \\(from <HOST>\\)$", "^hacking attempt detected '<HOST>'$", '^SecurityEvent="(?:FailedACL|InvalidAccountID|ChallengeResponseFailed|InvalidPassword)"(?:(?:,(?!RemoteAddress=)\\w+="[^"]*")*|.*?),RemoteAddress="IPV[46]/(UDP|TCP|WS)/<HOST>/\\d+"(?:,(?!RemoteAddress=)\\w+="[^"]*")*$', '^"Rejecting unknown SIP connection from <HOST>"$', "^Request (?:'[^']*' )?from '(?:[^']*|.*?)' failed for '<HOST>(?::\\d+)?'\\s\\(callid: [^\\)]*\\) - (?:No matching endpoint found|Not match Endpoint(?: Contact)? ACL|(?:Failed|Error) to authenticate)\\s*$", '^Unknown Call from [\\W\\w\\+]+ to [\\W\\w\\+]+, Details: IP <HOST>.*$']]
['set', 'asterisk', 'datepattern', '{^LN-BEG}']
['set', 'asterisk', 'maxretry', 3]
['set', 'asterisk', 'addignoreip', '127.0.0.1/8', '172.17.0.0/12', '128.75.229.70', '81.88.194.44', '109.248.225.2', '178.140.48.8', '37.16.82.101', '37.46.247.189', '37.57.168.92', '37.46.247.228', '213.170.92.166', '81.18.128.190', '173.212.249.206', '95.181.202.193', '95.131.26.210', '82.149.203.98', '94.100.82.86', '95.79.59.21', '178.249.242.51', '195.18.25.99', '193.34.92.30', '194.146.228.114', '178.20.238.194', '91.224.140.219', '91.224.140.179', '91.224.140.180', '91.224.140.181', '91.224.140.182', '91.224.140.183', '91.224.140.184', '91.224.140.216', '91.224.140.211', '213.170.92.166', '77.72.132.130']
['set', 'asterisk', 'logencoding', 'auto']
['set', 'asterisk', 'maxmatches', 3]
['set', 'asterisk', 'ignorecommand', '']
['set', 'asterisk', 'bantime', '86400']
['set', 'asterisk', 'findtime', '10m']
['set', 'asterisk', 'addlogpath', '/var/log/asterisk/full', 'head']
['set', 'asterisk', 'addlogpath', '/var/log/asterisk/messages', 'head']
['set', 'asterisk', 'addaction', 'iptables-multiport-tcp']
['multi-set', 'asterisk', 'action', 'iptables-multiport-tcp', [['actionunban', '<iptables> -D f2b-asterisk-tcp -s <ip> -j <blocktype>'], ['actionflush', '<iptables> -F f2b-asterisk-tcp'], ['actionstop', '<iptables> -D INPUT -p tcp -m multiport --dports 5060,5061,5038,8088 -j f2b-asterisk-tcp\n<iptables> -F f2b-asterisk-tcp\n<iptables> -X f2b-asterisk-tcp'], ['actionstart', '<iptables> -N f2b-asterisk-tcp\n<iptables> -A f2b-asterisk-tcp -j RETURN\n<iptables> -I INPUT -p tcp -m multiport --dports 5060,5061,5038,8088 -j f2b-asterisk-tcp'], ['actionban', '<iptables> -I f2b-asterisk-tcp 1 -s <ip> -j <blocktype>'], ['actioncheck', "<iptables> -n -L INPUT | grep -q 'f2b-asterisk-tcp[ \\t]'"], ['iptables', 'iptables <lockingopt>'], ['lockingopt', '-w'], ['blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unreachable'], ['protocol', 'tcp'], ['name', 'asterisk-tcp'], ['chain', '<known/chain>'], ['returntype', 'RETURN'], ['iptables?family=inet6', 'ip6tables <lockingopt>'], ['blocktype', 'REJECT --reject-with icmp-port-unreachable'], ['actname', 'iptables-multiport-tcp'], ['port', '5060,5061,5038,8088']]]
['set', 'asterisk', 'addaction', 'iptables-multiport-udp']
['multi-set', 'asterisk', 'action', 'iptables-multiport-udp', [['actionunban', '<iptables> -D f2b-asterisk-udp -s <ip> -j <blocktype>'], ['actionflush', '<iptables> -F f2b-asterisk-udp'], ['actionstop', '<iptables> -D INPUT -p udp -m multiport --dports 5060,5061,5038,8088 -j f2b-asterisk-udp\n<iptables> -F f2b-asterisk-udp\n<iptables> -X f2b-asterisk-udp'], ['actionstart', '<iptables> -N f2b-asterisk-udp\n<iptables> -A f2b-asterisk-udp -j RETURN\n<iptables> -I INPUT -p udp -m multiport --dports 5060,5061,5038,8088 -j f2b-asterisk-udp'], ['actionban', '<iptables> -I f2b-asterisk-udp 1 -s <ip> -j <blocktype>'], ['actioncheck', "<iptables> -n -L INPUT | grep -q 'f2b-asterisk-udp[ \\t]'"], ['iptables', 'iptables <lockingopt>'], ['lockingopt', '-w'], ['blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unreachable'], ['protocol', 'udp'], ['name', 'asterisk-udp'], ['chain', '<known/chain>'], ['returntype', 'RETURN'], ['iptables?family=inet6', 'ip6tables <lockingopt>'], ['blocktype', 'REJECT --reject-with icmp-port-unreachable'], ['actname', 'iptables-multiport-udp'], ['port', '5060,5061,5038,8088']]]
['set', 'asterisk', 'addaction', 'sendmail-whois']
['multi-set', 'asterisk', 'action', 'sendmail-whois', [['actionunban', ''], ['norestored', True], ['actionstop', 'printf %b "Subject: [Fail2Ban] asterisk: stopped on <fq-hostname>\nDate: `LC_ALL=C date +"%a, %d %h %Y %T %z"`\nFrom: Fail2Ban <fail2ban>\nTo: root@localhost\\n\nHi,\\n\nThe jail asterisk has been stopped.\\n\nRegards,\\n\nFail2Ban" | /usr/sbin/sendmail -f "fail2ban" "root@localhost"'], ['actionstart', 'printf %b "Subject: [Fail2Ban] asterisk: started on <fq-hostname>\nDate: `LC_ALL=C date +"%a, %d %h %Y %T %z"`\nFrom: Fail2Ban <fail2ban>\nTo: root@localhost\\n\nHi,\\n\nThe jail asterisk has been started successfully.\\n\nRegards,\\n\nFail2Ban" | /usr/sbin/sendmail -f "fail2ban" "root@localhost"'], ['actionban', 'printf %b "Subject: [Fail2Ban] asterisk: banned <ip> from <fq-hostname>\nDate: `LC_ALL=C date +"%a, %d %h %Y %T %z"`\nFrom: Fail2Ban <fail2ban>\nTo: root@localhost\\n\nHi,\\n\nThe IP <ip> has just been banned by Fail2Ban after\n<failures> attempts against asterisk.\\n\\n\nHere is more information about <ip> :\\n\n`whois <ip> || echo "missing whois program"`\\n\nRegards,\\n\nFail2Ban" | /usr/sbin/sendmail -f "fail2ban" "root@localhost"'], ['actioncheck', ''], ['name', 'asterisk'], ['dest', 'root@localhost'], ['mailcmd', '/usr/sbin/sendmail -f "<sender>" "<dest>"'], ['actname', 'sendmail-whois'], ['sendername', 'Fail2Ban'], ['sender', 'fail2ban']]]
['start', 'asterisk']`

**Comment by xnext40** [comment]
i will check and post result
