### ISSUE TITLE
regex for extra mode under sshd might be outdated

### ISSUE THREAD

**Issue by rfr** [fail2ban/fail2ban#2682]
#683 # Environment:

v0.10.2 on ubuntu 18.04.1 LTS

### The issue:

fail2ban doesn't recognize those kinds of login attempts with mode set to "extra" under sshd in jail.local. I think the regex is outdated? Or am I understanding it wrong? The difference I see is the word "supported" in the regex, which is missing in my logs.

```
Apr  7 21:07:02 ubuntu-16gb-nbg1-1 sshd[8395]: Disconnected from authenticating user root 217.77.212.60 port 1858 [preauth]
Apr  7 21:07:45 ubuntu-16gb-nbg1-1 sshd[8399]: error: Received disconnect from 217.77.212.60 port 1883:14: No authentication methods available [preauth]
```

**Comment by sebres** [comment]
Fixed in 136781d627aa70ab88f3fac3b6df398c21dc7387.
Thx!
