### ISSUE TITLE
Fail2ban v0.10.5 doesn't persist manual banned IPs after service restart

### ISSUE THREAD

**Issue by mohammedragabsoftxpert** [fail2ban/fail2ban#2683]
Just upgraded from f2b v0.9.6 to v0.10.5 on Ubuntu 14.04, and it is banning normally according to my old jails that i copied from my previous version.

But when i restart the service, it persist only the IPs that was banned with the configured enabled jails. All manually banned IPs like `fail2ban-client set sshd banip 1.2.3.4` are gone when i do restart. That wasn't the normal behavior on old versions i used.

Any help please?

**Comment by sebres** [comment]
See https://github.com/fail2ban/fail2ban/issues/2647#issuecomment-593544036

**Comment by mohammedragabsoftxpert** [comment]
@sebres Thanks a alot. So should i pull the 0.10.6-dev version to have the new updates instead of 10.5, or just take the changes?

**Comment by mohammedragabsoftxpert** [comment]
@sebres Thanks a lot, worked :)
