### ISSUE TITLE
jail.conf for xl2tpd

### ISSUE THREAD

**Issue by dropbrick** [fail2ban/fail2ban#2691]
Hi,
I am unable to find the right info on the internet, maybe I'm blind....but is it possible to set up a jail in jail.conf for xl2tpd ? I'd like to make sure if someone tries to log in to the VPN it gets banned after X attempts..

Thanks!

**Comment by sebres** [comment]
> but is it possible to set up a jail in jail.conf for xl2tpd

I don't know that there is some ready filter for xl2tpd.
To provide some failregex or even a filter, more info is needed: at least a log excerpt (that corresponds a failure attempt), journal unit or identifier (for systemd journal), etc pp.

Closed unless more info appropriable.
