### ISSUE TITLE
fail2ban-regex does not find logs from services running as unprivileged users

### ISSUE THREAD

**Issue by n8henrie** [fail2ban/fail2ban#2696]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): Fail2Ban v0.11.1
- OS, including release name/version: Arch Linux, 5.6.3
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

Using the `systemd-journal` backend, `journalmatch` seems to be getting the wrong logs for my service file.

Querying journalctl directly, I see plenty of my tests that I'm hoping to catch (`401 POST`).

```console
$ journalctl _SYSTEMD_UNIT=ml.service --grep '401 POST' -n 20
-- Logs begin at Fri 2019-10-04 15:41:24 MDT, end at Sat 2020-04-18 10:28:35 MDT. --
Apr 18 07:14:25 mymachine python[1029]: [W 07:14:25.805 LabApp] 401 POST /login?next=%2Flab%3F (127.0.0.1) 1.32ms referer=https://[REDACTED]/login?next=%2Flab%3F
Apr 18 07:16:33 mymachine python[1029]: [W 07:16:33.988 LabApp] 401 POST /login?next=%2Flab%3F (127.0.0.1) 1.39ms referer=https://[REDACTED]/login?next=%2Flab%3F
Apr 18 07:18:55 mymachine python[1029]: [W 07:18:55.339 LabApp] 401 POST /login?next=%2Flab%3F (127.0.0.1) 1.33ms referer=https://[REDACTED]/login?next=%2Flab%3F
Apr 18 07:18:59 mymachine python[1029]: [W 07:18:59.130 LabApp] 401 POST /login?next=%2Flab%3F (127.0.0.1) 1.40ms referer=https://[REDACTED]/login?next=%2Flab%3F
Apr 18 10:15:47 mymachine python[1029]: [W 10:15:47.176 LabApp] 401 POST /login?next=%2Flab%3F (192.168.0.115) 1.49ms referer=https://mymachine.local:[REDACTED]/login?next=%2Flab%3F
```

Using `fail2ban-regex`, I am seeing completely different logs in `--print-all-missed` -- so it seems like it isn't even looking at the right systemd unit?

```console
$ sudo fail2ban-regex --journalmatch='_SYSTEMD_UNIT=ml.service' systemd-journal '.*401.*<HOST>.*' --print-all-missed
Running tests
=============

Use   failregex line : .*401.*<HOST>.*
Use         systemd journal
Use         encoding : UTF-8
Use    journal match : _SYSTEMD_UNIT=ml.service


Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Lines: 20 lines, 0 ignored, 0 matched, 20 missed
[processed in 0.00 sec]

|- Missed line(s):
|  2020-04-15T08:38:09.182740mymachine sudoedit[30446]: pam_unix(sudo:session): session opened for user root by (uid=0)
|  2020-04-15T08:38:31.154128mymachine sudoedit[30446]: pam_unix(sudo:session): session closed for user root
|  2020-04-15T08:38:43.311124mymachine sudo[30499]: pam_unix(sudo:session): session opened for user root by (uid=0)
|  2020-04-15T08:38:43.467930mymachine sudo[30499]: pam_unix(sudo:session): session closed for user root
`-
```

#### Expected behavior

I expect `sudo fail2ban-regex --journalmatch='_SYSTEMD_UNIT=ml.service'` to be showing me the same logs as `journalctl _SYSTEMD_UNIT=ml.service`.

#### Observed behavior

I'm seeing entirely different logs.

**Comment by n8henrie** [comment]
Gah.

Finally found [this][0] while led me to [this](https://github.com/fail2ban/fail2ban/wiki/Upgrading-to-v0.10.5-Breaks-WP-Fail2ban-and-Other-Jails).

My systemd service file is running with `User=me`. The logs in question *don't* show up with `journalctl --system -u ml.service`.

Using `backend = systemd[journalflags=1]` was the solution, and `fail2ban-regex systemd-journal[journalflags=1] ...` correctly identifies the matches.

As of the time of writing, the [wordpress link above][0] is the *only* result for `fail2ban-regex "backend = systemd[journalflags=1]"` on duckduckgo, and one of only 4 results for that query on Google; 2 of 4 are duplicates, with the only other link being [this issue](https://github.com/fail2ban/fail2ban/issues/2653). The term `journalflags` doesn't appear in `man fail2ban-regex`, `man fail2ban`, `man 5 jail.conf`, or anywhere I can find on fail2ban.org. I think it may be reasonable to at least make a note of it in `man fail2ban-regex`; I've not done much manpage editing, but given that it's likely to be a very small edit, I'm happy to work on PR if it would be helpful.

[0]: https://wordpress.org/support/topic/using-wp-fail2ban-with-systemd-logging/

**Comment by sebres** [comment]
> I'm happy to work on PR if it would be helpful.

I'd never say "no" for PR's extending documentation :)
