### ISSUE TITLE
courier-smtp prefregex

### ISSUE THREAD

**Issue by neilromig** [fail2ban/fail2ban#2697]
Latest courier release (1.0.12) has revised log format for error messages containing a port number.

### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.1.11
- OS, including release name/version: Arch
- [ X] Fail2Ban installed via OS/distribution mechanisms
- [X ] You have not applied any additional foreign patches to the codebase

### The issue:
Filter fails to match failed login attempts

#### Steps to reproduce
Use courier-smtp filter as supplied

#### Expected behavior
Failed logins should be matched and banned

#### Observed behavior
No matches

#### Relevant lines from monitored log files in question:
old format:
```
Apr 14 14:38:29 mymailserver courieresmtpd[113461]: error,relay=::ffff:45.142.195.2,msg="535 Authentication failed.",cmd: AUTH LOGIN mareike@co.uk
```
new format:
```
Apr 21 06:45:37 mymailserver courieresmtpd[425070]: error,relay=::ffff:45.142.195.3,port=43632,msg="535 Authentication failed.",cmd: AUTH LOGIN PlcmSpIp@co.uk
```

**Comment by sebres** [comment]
Fixed in affd9cef5f2ddb5c596e1aa3789ba18b5c987ba1, thank you!
