### ISSUE TITLE
[0.10.5] Banned IP address still can access the web through HTTP and HTTPS

### ISSUE THREAD

**Issue by jasononggo** [fail2ban/fail2ban#2698]
`sudo fail2ban-client -d | grep odoo-login` output

```
['add', 'odoo-login', 'auto']
['set', 'odoo-login', 'usedns', 'warn']
['set', 'odoo-login', 'addfailregex', '^ \\d+ INFO \\S+ \\S+ Login failed for db:\\S+ login:\\S+ from <HOST>']
['set', 'odoo-login', 'maxretry', 10]
['set', 'odoo-login', 'maxmatches', 10]
['set', 'odoo-login', 'findtime', '60']
['set', 'odoo-login', 'bantime', '900']
['set', 'odoo-login', 'ignorecommand', '']
['set', 'odoo-login', 'logencoding', 'auto']
['set', 'odoo-login', 'addlogpath', '/var/log/odoo/odoo.log', 'head']
['set', 'odoo-login', 'addaction', 'iptables-multiport']
['multi-set', 'odoo-login', 'action', 'iptables-multiport', [['actionstart', '<iptables> -N f2b-odoo-login\n<iptables> -A f2b-odoo-login -j RETURN\n<iptables> -I INPUT -p tcp -m multiport --dports http,https -j f2b-odoo-login'], ['actionstop', '<iptables> -D INPUT -p tcp -m multiport --dports http,https -j f2b-odoo-login\n<iptables> -F f2b-odoo-login\n<iptables> -X f2b-odoo-login'], ['actionflush', '<iptables> -F f2b-odoo-login'], ['actioncheck', "<iptables> -n -L INPUT | grep -q 'f2b-odoo-login[ \\t]'"], ['actionban', '<iptables> -I f2b-odoo-login 1 -s <ip> -j <blocktype>'], ['actionunban', '<iptables> -D f2b-odoo-login -s <ip> -j <blocktype>'], ['name', 'odoo-login'], ['bantime', '900'], ['port', 'http,https'], ['protocol', 'tcp'], ['chain', '<known/chain>'], ['actname', 'iptables-multiport'], ['blocktype', 'REJECT --reject-with icmp-port-unreachable'], ['returntype', 'RETURN'], ['lockingopt', '-w'], ['iptables', 'iptables <lockingopt>'], ['blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unreachable'], ['iptables?family=inet6', 'ip6tables <lockingopt>']]]
['start', 'odoo-login']
```

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): 0.10.5
- OS, including release name/version:  Centos 8.1.1911
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

`cat /etc/fail2ban/filter.d/odoo-login.conf` output:
```
# Odoo bruteforce login banning rule
[Definition]
failregex = ^ \d+ INFO \S+ \S+ Login failed for db:\S+ login:\S+ from <HOST>

```
`cat /etc/fail2ban/jail.local` output
```
[DEFAULT]
# Ban hosts for one hour:
bantime = 3600
findtime = 600
maxretry = 3

# Override /etc/fail2ban/jail.d/00-firewalld.conf:
banaction = iptables-multiport

[sshd]
enabled = true

[odoo-login]
enabled = true
port = http,https
bantime = 900
maxretry = 10
findtime = 60
logpath = /var/log/odoo/odoo.log
```

### The issue:

Banned IP address still can access through HTTP and HTTPS

#### Steps to reproduce
1. create non-root user, add the new user to the wheel group.
2. `git clone https://github.com/jasononggo/docker-odoo-letsencrypt.git`
3. `bash ./environment.sh`
4. `sudo docker-compose up`
5. make a request to /web/login from remote computer 10 times in a row.
6. or ban ip address manually `sudo fail2ban-client set odoo-login banip <ip address>`

#### Expected behavior
Unable to access the web through HTTP and HTTPS.

#### Observed behavior
Work as usual.

#### Any additional information
If you intentionally ban yourself in jail `sshd`, you will not be able to access the SSH port.

#### Relevant parts of /var/log/fail2ban.log file:
```
2020-04-21 15:40:18,169 fail2ban.actions        [19899]: NOTICE  [odoo-login] Ban 158.140.187.220
2020-04-21 15:40:53,801 fail2ban.actions        [19899]: NOTICE  [odoo-login] Ban 103.119.66.127
```
There is some issue with Odoo:13.0 and werkzeug:0.14.1 while behind proxy, the IP Address mentioned by https://whatismyipaddress.com/ is different. I decided to ban both but still can access the web through HTTP and HTTPS.

#### Relevant lines from monitored log files in question:
`2020-04-21 17:11:40,502 1 INFO test odoo.addons.base.models.res_users: Login failed for db:test login:test from 158.140.187.220`

**Comment by sebres** [comment]
There may be several reasons why the banning action does not work:

1. because you've mentioned docker, note this similar issue #2292 (and #2511) better study through both to understand how your docker container is protected by the host (or how they are working together) or whether the banning on the host side is hindered by some forwarding rules of docker.
2. net-filter subsystem does not work properly for certain constellation (e. g. ignores already established connections, so a keep-alive connection is still able to make requests);
For `iptable-multiport` at least check the rules for `f2b-odoo-login`, e. g. in  INPUT chain `iptables -nL INPUT` and whether it contains the IP that should be banned, for example `iptables -nL f2b-odoo-login | grep 158.140.187.220`
3. it has some white-listening rules in INPUT chain that avoid entering the fail2ban blocking chains, for instance see https://github.com/fail2ban/fail2ban/issues/2545#issuecomment-543087971 and below;

Now I tend to assign this to 3rd part issues.

**Comment by jasononggo** [comment]
Thank you. Adding `chain = DOCKER-USER` ensure the fail2ban rule is included in the docker iptables.

I've push a fix to the master branch in jasononggo/docker-odoo-letsencrypt
