### ISSUE TITLE
no error message if fail2ban fails to start as service

### ISSUE THREAD

**Issue by JustinLawrenceMS** [fail2ban/fail2ban#2701]
_We will be very grateful, if your problem was described as completely as possible,
enclosing excerpts from logs (if possible within DEBUG mode, if no errors evident
within INFO mode), and configuration in particular of effected relevant settings
(e.g., with ` fail2ban-client -d | grep 'affected-jail-name' ` for a particular
jail troubleshooting).
Thank you in advance for the details, because such issues like "It does not work" 
alone could not help to resolve anything!
Thanks! (remove this paragraph and other comments upon reading)_

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes):

v0.10.2

- OS, including release name/version: 

Ubuntu 18.04 LTS

- [ ] Fail2Ban installed via OS/distribution mechanisms

apt install fail2ban

- [ ] You have not applied any additional foreign patches to the codebase

No foreign patches

- [ ] Some customizations were done to the configuration (provide details below is so)

Enabled all apache related jails.

### The issue:

Fail2ban fails silently on 

```systemctl restart fail2ban```

It would be awesome if the service left an alert in the console when fail2ban fails. 

#### Steps to reproduce

Create a configuration in jail.local that will break startup when you restart fail2ban.  Then

```systemctl restart fail2ban```

#### Expected behavior

It would be awesome if it said something like

```
Error:  Fail2ban did not start.  Consult journalctl -xe for more details
```

#### Observed behavior

Silence

#### Any customizations done to /etc/fail2ban/ configuration

I enabled every apache jail.

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
This is rather a matter of corresponding service unit file (which is supported by maintainers rather).
1. If you don't need a restart, you can do that with `fail2ban-client` command:
`fail2ban-client reload`.
2. Many units allow to switch standard output or standard error channels to console. For instance, it is possible for systemd if you'd set `StandardOutput=tty` and `StandardError=tty` you'd be able to redirect it to the console, so run `systemctl edit fail2ban` and add this to override config-file:
```ini
[Service]
StandardOutput=tty
StandardError=tty
```
