### ISSUE TITLE
Multiple tests with segfaults on s390x

### ISSUE THREAD

**Issue by Ikke** [fail2ban/fail2ban#2708]
When running the test suite on Alpine Linux on our s390x builders, multiple tests fail with segfaults:

```
testGetBansMerged (fail2ban.tests.databasetestcase.DatabaseTest) ... Segmentation fault (core dumped)
testAddBanInvalidEncoded (fail2ban.tests.databasetestcase.DatabaseTest) ... Segmentation fault (core dumped)
testServerJails_Sendmail (fail2ban.tests.fail2banclienttestcase.Fail2banServerTest) ... Segmentation fault (core dumped)
testServerReloadTest (fail2ban.tests.fail2banclienttestcase.Fail2banServerTest) ... Segmentation fault (core dumped) 
```
I had to skip each test before the next one came up.

Here is the backtrace of `testServerReloadTest (fail2ban.tests.fail2banclienttestcase.Fail2banServerTest)`:

<details>
<summary>backtrace</summary>
<pre>
#0  0x000003ffa045c562 in memcmp (vl=0x2aa3bdbc71f, vr=0x0, n=<optimized out>) at src/string/memcmp.c:6
6       src/string/memcmp.c: No such file or directory.
[Current thread is 1 (LWP 2547)]
(gdb) bt
#0  0x000003ffa045c562 in memcmp (vl=0x2aa3bdbc71f, vr=0x0, n=<optimized out>) at src/string/memcmp.c:6
#1  0x000003ff9e3cb818 in ?? () from /usr/lib/libsqlite3.so.0
#2  0x000003ff9e3f0a0e in ?? () from /usr/lib/libsqlite3.so.0
#3  0x000003ff9e416fe6 in ?? () from /usr/lib/libsqlite3.so.0
#4  0x000003ff9e41c328 in sqlite3_step () from /usr/lib/libsqlite3.so.0
#5  0x000003ff9e512632 in pysqlite_step (connection=<optimized out>, statement=0x2aa3bda4738) at /home/buildozer/aports/main/python3/src/Python-3.8.2/Modules/_sqlite/util.c:27
#6  _pysqlite_query_execute (args=<optimized out>, multiple=0, self=<optimized out>) at /home/buildozer/aports/main/python3/src/Python-3.8.2/Modules/_sqlite/cursor.c:515
#7  pysqlite_cursor_execute (self=<optimized out>, args=<optimized out>) at /home/buildozer/aports/main/python3/src/Python-3.8.2/Modules/_sqlite/cursor.c:612
#8  0x000003ffa01671f6 in method_vectorcall_VARARGS (func=0x3ff9e658c20, args=0x3ff9e0e61e0, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/descrobject.c:300
#9  0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9e658c20, args=0x3ff9e0e61e0, nargsf=9223372036854775811, kwnames=0x0) at ./Include/cpython/abstract.h:127
#10 0x000003ffa0179b04 in call_function (tstate=tstate@entry=0x2aa3bd68360, pp_stack=0x3ff9c7b8708, pp_stack@entry=<error reading variable: value has been optimized out>, oparg=oparg@entry=3, kwnames=kwnames@entry=0x0)
    at Python/ceval.c:4946
#11 0x000003ffa01915ee in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3486
#12 0x000003ffa0156408 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=4, globals=<optimized out>) at Objects/call.c:283
#13 0x000003ffa015aed8 in PyVectorcall_Call (callable=0x3ff9e656ca0, tuple=<optimized out>, kwargs=<optimized out>) at Objects/call.c:199
#14 0x000003ffa0191acc in do_call_core (kwdict=<optimized out>, callargs=0x3ff9be51ef0, func=<optimized out>, tstate=<optimized out>) at Python/ceval.c:5034
#15 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3559
#16 0x000003ffa0182352 in _PyEval_EvalCodeWithName (_co=0x3ff9e649be0, globals=globals@entry=0x3ff9e646f00, locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=3, kwnames=0x0, kwargs=0x3ff9e2953f0, kwcount=0, kwstep=1,
    defs=0x0, defcount=0, kwdefs=0x0, closure=0x3ff9e652cd0, name=0x3ff9e71b770, qualname=0x3ff9e6511c0) at Python/ceval.c:4298
#17 0x000003ffa018249c in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:435
#18 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9e656d30, args=0x3ff9e2953d8, nargsf=9223372036854775811, kwnames=0x0) at ./Include/cpython/abstract.h:127
#19 0x000003ffa0179b04 in call_function (tstate=tstate@entry=0x2aa3bd68360, pp_stack=0x3ff9c7b8f30, pp_stack@entry=<error reading variable: value has been optimized out>, oparg=oparg@entry=3, kwnames=kwnames@entry=0x0)
    at Python/ceval.c:4946
#20 0x000003ffa01915ee in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3486
#21 0x000003ffa0182352 in _PyEval_EvalCodeWithName (_co=0x3ff9e7197c0, globals=globals@entry=0x3ff9e70e800, locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=3, kwnames=0x0, kwargs=0x3ff9f3f63c0, kwcount=0, kwstep=1,
    defs=0x3ff9e71bf58, defcount=2, kwdefs=0x0, closure=0x0, name=0x3ff9e740230, qualname=0x3ff9e71a850) at Python/ceval.c:4298
#22 0x000003ffa018249c in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:435
#23 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9e6c40d0, args=0x3ff9f3f63a8, nargsf=9223372036854775811, kwnames=0x0) at ./Include/cpython/abstract.h:127
#24 0x000003ffa0179b04 in call_function (tstate=tstate@entry=0x2aa3bd68360, pp_stack=0x3ff9c7b9440, pp_stack@entry=<error reading variable: value has been optimized out>, oparg=oparg@entry=3, kwnames=kwnames@entry=0x0)
    at Python/ceval.c:4946
#25 0x000003ffa01915ee in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3486
#26 0x000003ffa0182352 in _PyEval_EvalCodeWithName (_co=0x3ff9e6f9c90, globals=globals@entry=0x3ff9e6eff00, locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=4, kwnames=0x0, kwargs=0x2aa3b847618, kwcount=0, kwstep=1,
    defs=0x3ff9e6fcc88, defcount=1, kwdefs=0x0, closure=0x0, name=0x3ff9e740230, qualname=0x3ff9e6f8e40) at Python/ceval.c:4298
#27 0x000003ffa018249c in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:435
#28 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9e663550, args=0x2aa3b8475f8, nargsf=9223372036854775812, kwnames=0x0) at ./Include/cpython/abstract.h:127
#29 0x000003ffa0179b04 in call_function (tstate=tstate@entry=0x2aa3bd68360, pp_stack=0x3ff9c7b9950, pp_stack@entry=<error reading variable: value has been optimized out>, oparg=oparg@entry=4, kwnames=kwnames@entry=0x0)
    at Python/ceval.c:4946
#30 0x000003ffa01915ee in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3486
#31 0x000003ffa0182352 in _PyEval_EvalCodeWithName (_co=0x3ff9e649240, globals=globals@entry=0x3ff9e641f00, locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=2, kwnames=0x0, kwargs=0x2aa3bcb3048, kwcount=0, kwstep=1,
    defs=0x3ff9e645568, defcount=1, kwdefs=0x0, closure=0x0, name=0x3ff9e646bf0, qualname=0x3ff9e644a30) at Python/ceval.c:4298
#32 0x000003ffa018249c in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:435
#33 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9e648310, args=0x2aa3bcb3038, nargsf=9223372036854775810, kwnames=0x0) at ./Include/cpython/abstract.h:127
#34 0x000003ffa0179b04 in call_function (tstate=tstate@entry=0x2aa3bd68360, pp_stack=0x3ff9c7b9e60, pp_stack@entry=<error reading variable: value has been optimized out>, oparg=oparg@entry=2, kwnames=kwnames@entry=0x0)
    at Python/ceval.c:4946
#35 0x000003ffa01915ee in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3486
#36 0x000003ffa0156408 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=2, globals=<optimized out>) at Objects/call.c:283
#37 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9e648280, args=0x2aa3be972a0, nargsf=9223372036854775810, kwnames=0x0) at ./Include/cpython/abstract.h:127
#38 0x000003ffa0179b04 in call_function (tstate=tstate@entry=0x2aa3bd68360, pp_stack=0x3ff9c7ba210, pp_stack@entry=<error reading variable: value has been optimized out>, oparg=oparg@entry=2, kwnames=kwnames@entry=0x0)
    at Python/ceval.c:4946
#39 0x000003ffa01915ee in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3486
#40 0x000003ffa0156408 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=2, globals=<optimized out>) at Objects/call.c:283
#41 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9e648280, args=0x3ff9bf419d8, nargsf=9223372036854775810, kwnames=0x0) at ./Include/cpython/abstract.h:127
#42 0x000003ffa0179b04 in call_function (tstate=tstate@entry=0x2aa3bd68360, pp_stack=0x3ff9c7ba5c0, pp_stack@entry=<error reading variable: value has been optimized out>, oparg=oparg@entry=2, kwnames=kwnames@entry=0x0)
    at Python/ceval.c:4946
#43 0x000003ffa01915ee in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3486
#44 0x000003ffa0156408 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=2, globals=<optimized out>) at Objects/call.c:283
#45 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9e6481f0, args=0x3ff9bf3f1c8, nargsf=9223372036854775810, kwnames=0x0) at ./Include/cpython/abstract.h:127
#46 0x000003ffa0179b04 in call_function (tstate=tstate@entry=0x2aa3bd68360, pp_stack=0x3ff9c7ba970, pp_stack@entry=<error reading variable: value has been optimized out>, oparg=oparg@entry=2, kwnames=kwnames@entry=0x0)
    at Python/ceval.c:4946
#47 0x000003ffa01915ee in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3486
#48 0x000003ffa0156408 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=1, globals=<optimized out>) at Objects/call.c:283
#49 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9e8b0430, args=0x2aa3be94900, nargsf=9223372036854775809, kwnames=0x0) at ./Include/cpython/abstract.h:127
#50 0x000003ffa0179b04 in call_function (tstate=tstate@entry=0x2aa3bd68360, pp_stack=0x3ff9c7bad20, pp_stack@entry=<error reading variable: value has been optimized out>, oparg=oparg@entry=1, kwnames=kwnames@entry=0x0)
--Type <RET> for more, q to quit, c to continue without paging--
    at Python/ceval.c:4946
#51 0x000003ffa01915ee in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3486
#52 0x000003ffa0156408 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=1, globals=<optimized out>) at Objects/call.c:283
#53 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9e8ab3a0, args=0x3ff9f3bf358, nargsf=9223372036854775809, kwnames=0x0) at ./Include/cpython/abstract.h:127
#54 0x000003ffa0179b04 in call_function (tstate=tstate@entry=0x2aa3bd68360, pp_stack=0x3ff9c7bb0d0, pp_stack@entry=<error reading variable: value has been optimized out>, oparg=oparg@entry=1, kwnames=kwnames@entry=0x0)
    at Python/ceval.c:4946
#55 0x000003ffa01915ee in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3486
#56 0x000003ffa0156408 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=1, globals=<optimized out>) at Objects/call.c:283
#57 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9e8aa040, args=0x3ff9bf30558, nargsf=9223372036854775809, kwnames=0x0) at ./Include/cpython/abstract.h:127
#58 0x000003ffa0179b04 in call_function (tstate=tstate@entry=0x2aa3bd68360, pp_stack=0x3ff9c7bb480, pp_stack@entry=<error reading variable: value has been optimized out>, oparg=oparg@entry=1, kwnames=kwnames@entry=0x0)
    at Python/ceval.c:4946
#59 0x000003ffa01915ee in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3486
#60 0x000003ffa0156408 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=1, globals=<optimized out>) at Objects/call.c:283
#61 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9e8a9160, args=0x3ff9be13e00, nargsf=9223372036854775809, kwnames=0x0) at ./Include/cpython/abstract.h:127
#62 0x000003ffa0179b04 in call_function (tstate=tstate@entry=0x2aa3bd68360, pp_stack=0x3ff9c7bb838, pp_stack@entry=<error reading variable: value has been optimized out>, oparg=oparg@entry=1, kwnames=kwnames@entry=0x0)
    at Python/ceval.c:4946
#63 0x000003ffa019161c in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3500
#64 0x000003ffa0182352 in _PyEval_EvalCodeWithName (_co=0x3ff9e8a0190, globals=globals@entry=0x3ff9e890fc0, locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=1, kwnames=0x0, kwargs=0x2aa3bb1a638, kwcount=0, kwstep=1,
    defs=0x3ff9ea45118, defcount=2, kwdefs=0x0, closure=0x0, name=0x3ff9fad2970, qualname=0x3ff9fad2970) at Python/ceval.c:4298
#65 0x000003ffa018249c in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:435
#66 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9e8a93a0, args=0x2aa3bb1a630, nargsf=9223372036854775809, kwnames=0x0) at ./Include/cpython/abstract.h:127
#67 0x000003ffa0179b04 in call_function (tstate=tstate@entry=0x2aa3bd68360, pp_stack=0x3ff9c7bbd48, pp_stack@entry=<error reading variable: value has been optimized out>, oparg=oparg@entry=1, kwnames=kwnames@entry=0x0)
    at Python/ceval.c:4946
#68 0x000003ffa019161c in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3500
#69 0x000003ffa0182352 in _PyEval_EvalCodeWithName (_co=0x3ff9e899030, globals=globals@entry=0x3ff9e885080, locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=1, kwnames=0x3ff9e893098, kwargs=0x3ff9e2955c8, kwcount=3,
    kwstep=1, defs=0x3ff9e893e98, defcount=3, kwdefs=0x0, closure=0x0, name=0x3ff9f27c2f0, qualname=0x3ff9f27c2f0) at Python/ceval.c:4298
#70 0x000003ffa018249c in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:435
#71 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9e894b80, args=0x3ff9e2955c0, nargsf=9223372036854775809, kwnames=0x3ff9e893080) at ./Include/cpython/abstract.h:127
#72 0x000003ffa0179b04 in call_function (tstate=tstate@entry=0x2aa3bd68360, pp_stack=0x3ff9c7bc260, pp_stack@entry=<error reading variable: value has been optimized out>, oparg=oparg@entry=4, kwnames=kwnames@entry=0x3ff9e893080)
    at Python/ceval.c:4946
#73 0x000003ffa01916c0 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3515
#74 0x000003ffa0182352 in _PyEval_EvalCodeWithName (_co=0x3ff9e8993a0, globals=globals@entry=0x3ff9e885080, locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=3, kwnames=0x0, kwargs=0x2aa3bd02490, kwcount=0, kwstep=1,
    defs=0x3ff9ea49c58, defcount=2, kwdefs=0x0, closure=0x0, name=0x3ffa04ceb70, qualname=0x3ff9e89a490) at Python/ceval.c:4298
#75 0x000003ffa018249c in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:435
#76 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9e8b0790, args=0x2aa3bd02478, nargsf=9223372036854775811, kwnames=0x0) at ./Include/cpython/abstract.h:127
#77 0x000003ffa0179b04 in call_function (tstate=tstate@entry=0x2aa3bd68360, pp_stack=0x3ff9c7bc760, pp_stack@entry=<error reading variable: value has been optimized out>, oparg=oparg@entry=3, kwnames=kwnames@entry=0x0)
    at Python/ceval.c:4946
#78 0x000003ffa01915ee in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3486
#79 0x000003ffa0182352 in _PyEval_EvalCodeWithName (_co=0x3ff9e6f9190, globals=globals@entry=0x3ff9e6eff00, locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=4, kwnames=0x3ff9e24e6b8, kwargs=0x2aa3bd01fc8, kwcount=1,
    kwstep=1, defs=0x3ff9e6462d8, defcount=3, kwdefs=0x0, closure=0x0, name=0x3ffa04ceb70, qualname=0x3ff9e6f7930) at Python/ceval.c:4298
#80 0x000003ffa018249c in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:435
#81 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9e661ca0, args=0x2aa3bd01fa8, nargsf=4, kwnames=0x3ff9e24e6a0) at ./Include/cpython/abstract.h:127
#82 0x000003ffa0179cb4 in method_vectorcall (method=<optimized out>, args=0x2aa3bd01fb0, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/classobject.c:60
#83 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9c576d40, args=0x2aa3bd01fb0, nargsf=9223372036854775811, kwnames=0x3ff9e24e6a0) at ./Include/cpython/abstract.h:127
#84 0x000003ffa0179b04 in call_function (tstate=tstate@entry=0x2aa3bd68360, pp_stack=0x3ff9c7bcdf8, pp_stack@entry=<error reading variable: value has been optimized out>, oparg=oparg@entry=4, kwnames=kwnames@entry=0x3ff9e24e6a0)
    at Python/ceval.c:4946
#85 0x000003ffa01916c0 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3515
#86 0x000003ffa0182352 in _PyEval_EvalCodeWithName (_co=0x3ff9e260030, globals=globals@entry=0x3ff9e249d00, locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=2, kwnames=0x0, kwargs=0x2aa3bd4f240, kwcount=0, kwstep=1,
    defs=0x3ff9e2625f8, defcount=1, kwdefs=0x0, closure=0x0, name=0x3ff9e25c7b0, qualname=0x3ff9e25d390) at Python/ceval.c:4298
#87 0x000003ffa018249c in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:435
#88 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9e267ca0, args=0x2aa3bd4f230, nargsf=9223372036854775810, kwnames=0x0) at ./Include/cpython/abstract.h:127
#89 0x000003ffa0179b04 in call_function (tstate=tstate@entry=0x2aa3bd68360, pp_stack=0x3ff9c7bd2f8, pp_stack@entry=<error reading variable: value has been optimized out>, oparg=oparg@entry=2, kwnames=kwnames@entry=0x0)
    at Python/ceval.c:4946
#90 0x000003ffa019155c in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3469
#91 0x000003ffa0182352 in _PyEval_EvalCodeWithName (_co=0x3ff9e265710, globals=globals@entry=0x3ff9e249d00, locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=2, kwnames=0x0, kwargs=0x3ff9c551530, kwcount=0, kwstep=1,
    defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x3ffa04ceb70, qualname=0x3ff9e266710) at Python/ceval.c:4298
#92 0x000003ffa018249c in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:435
#93 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9e267ee0, args=0x3ff9c551520, nargsf=9223372036854775810, kwnames=0x0) at ./Include/cpython/abstract.h:127
#94 0x000003ffa0179b04 in call_function (tstate=tstate@entry=0x2aa3bd68360, pp_stack=0x3ff9c7bd808, pp_stack@entry=<error reading variable: value has been optimized out>, oparg=oparg@entry=2, kwnames=kwnames@entry=0x0)
    at Python/ceval.c:4946
#95 0x000003ffa01915ee in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3486
#96 0x000003ffa0156408 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=1, globals=<optimized out>) at Objects/call.c:283
#97 0x000003ffa015aed8 in PyVectorcall_Call (callable=0x3ff9e267c10, tuple=<optimized out>, kwargs=<optimized out>) at Objects/call.c:199
--Type <RET> for more, q to quit, c to continue without paging--c
#98 0x000003ffa0191acc in do_call_core (kwdict=<optimized out>, callargs=0x3ff9c55ed30, func=<optimized out>, tstate=<optimized out>) at Python/ceval.c:5034
#99 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3559
#100 0x000003ffa0156408 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=4, globals=<optimized out>) at Objects/call.c:283
#101 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9ee528b0, args=0x3ff9c56b3b8, nargsf=9223372036854775812, kwnames=0x0) at ./Include/cpython/abstract.h:127
#102 0x000003ffa0179b04 in call_function (tstate=tstate@entry=0x2aa3bd68360, pp_stack=0x3ff9c7bded0, pp_stack@entry=<error reading variable: value has been optimized out>, oparg=oparg@entry=4, kwnames=kwnames@entry=0x0) at Python/ceval.c:4946
#103 0x000003ffa01915ee in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3486
#104 0x000003ffa0182352 in _PyEval_EvalCodeWithName (_co=0x3ff9ef72450, globals=globals@entry=0x3ff9f278f40, locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=4, kwnames=0x0, kwargs=0x3ff9c56b1f0, kwcount=0, kwstep=1, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x3ff9f7d2f70, qualname=0x3ff9ef71670) at Python/ceval.c:4298
#105 0x000003ffa018249c in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:435
#106 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9ee57790, args=0x3ff9c56b1d0, nargsf=9223372036854775812, kwnames=0x0) at ./Include/cpython/abstract.h:127
#107 0x000003ffa0179b04 in call_function (tstate=tstate@entry=0x2aa3bd68360, pp_stack=0x3ff9c7be3e0, pp_stack@entry=<error reading variable: value has been optimized out>, oparg=oparg@entry=4, kwnames=kwnames@entry=0x0) at Python/ceval.c:4946
#108 0x000003ffa01915ee in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3486
#109 0x000003ffa0182352 in _PyEval_EvalCodeWithName (_co=0x3ff9e245660, globals=globals@entry=0x3ff9e5ed980, locals=locals@entry=0x0, args=<optimized out>, argcount=argcount@entry=4, kwnames=0x0, kwargs=0x3ff9c6869b0, kwcount=0, kwstep=1, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x3ff9e243c70, qualname=0x3ff9e2460f0) at Python/ceval.c:4298
#110 0x000003ffa018249c in _PyFunction_Vectorcall (func=<optimized out>, stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>) at Objects/call.c:435
#111 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9e26b820, args=0x3ff9c686990, nargsf=9223372036854775812, kwnames=0x0) at ./Include/cpython/abstract.h:127
#112 0x000003ffa0179b04 in call_function (tstate=tstate@entry=0x2aa3bd68360, pp_stack=0x3ff9c7be8f0, pp_stack@entry=<error reading variable: value has been optimized out>, oparg=oparg@entry=4, kwnames=kwnames@entry=0x0) at Python/ceval.c:4946
#113 0x000003ffa01915ee in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3486
#114 0x000003ffa0156408 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=4, globals=<optimized out>) at Objects/call.c:283
#115 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9e26b8b0, args=0x3ff9c7beb90, nargsf=4, kwnames=0x0) at ./Include/cpython/abstract.h:127
#116 0x000003ffa0179d9e in method_vectorcall (method=method@entry=0x3ff9c567d80, args=0x3ff9c6b9c58, nargsf=nargsf@entry=3, kwnames=0x0) at Objects/classobject.c:89
#117 0x000003ffa015aed8 in PyVectorcall_Call (callable=0x3ff9c567d80, tuple=<optimized out>, kwargs=<optimized out>) at Objects/call.c:199
#118 0x000003ffa0191acc in do_call_core (kwdict=<optimized out>, callargs=0x3ff9c6b9c40, func=<optimized out>, tstate=<optimized out>) at Python/ceval.c:5034
#119 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3559
#120 0x000003ffa0156408 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=1, globals=<optimized out>) at Objects/call.c:283
#121 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9fd3cc10, args=0x3ff9c52ebb8, nargsf=9223372036854775809, kwnames=0x0) at ./Include/cpython/abstract.h:127
#122 0x000003ffa0179b04 in call_function (tstate=tstate@entry=0x2aa3bd68360, pp_stack=0x3ff9c7bf130, pp_stack@entry=<error reading variable: value has been optimized out>, oparg=oparg@entry=1, kwnames=kwnames@entry=0x0) at Python/ceval.c:4946
#123 0x000003ffa01915ee in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3486
#124 0x000003ffa0156408 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=1, globals=<optimized out>) at Objects/call.c:283
#125 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9fd3cee0, args=0x3ff9c4fbfb8, nargsf=9223372036854775809, kwnames=0x0) at ./Include/cpython/abstract.h:127
#126 0x000003ffa0179b04 in call_function (tstate=tstate@entry=0x2aa3bd68360, pp_stack=0x3ff9c7bf4e0, pp_stack@entry=<error reading variable: value has been optimized out>, oparg=oparg@entry=1, kwnames=kwnames@entry=0x0) at Python/ceval.c:4946
#127 0x000003ffa01915ee in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3486
#128 0x000003ffa0156408 in function_code_fastcall (co=<optimized out>, args=<optimized out>, nargs=1, globals=<optimized out>) at Objects/call.c:283
#129 0x000003ffa017997e in _PyObject_Vectorcall (callable=0x3ff9fd3cca0, args=0x3ff9c7bf778, nargsf=1, kwnames=0x0) at ./Include/cpython/abstract.h:127
#130 0x000003ffa0179d10 in method_vectorcall (method=method@entry=0x3ff9c569980, args=0x3ffa04be058, nargsf=nargsf@entry=0, kwnames=0x0) at Objects/classobject.c:67
#131 0x000003ffa015aed8 in PyVectorcall_Call (callable=0x3ff9c569980, tuple=<optimized out>, kwargs=<optimized out>) at Objects/call.c:199
#132 0x000003ffa02308a0 in t_bootstrap (boot_raw=boot_raw@entry=0x3ff9c56d540) at ./Modules/_threadmodule.c:1002
#133 0x000003ffa01a2a64 in pythread_wrapper (arg=<optimized out>) at Python/thread_pthread.h:232
#134 0x000003ffa046119c in start (p=0x3ff9c7bfae8) at src/thread/pthread_create.c:192
#135 0x000003ffa046d65c in __clone () at src/thread/s390x/clone.s:45
</pre>
</details>

Please let me know if you need more information.

**Comment by sebres** [comment]
This is surely an issue of either pysqlite module or python itself.
We cannot do something here to fix or workaround it.
Skipping the tests would just retard the issue (it'd happen in a production later).

**Comment by Ikke** [comment]
Thanks, we'll be disabling fail2ban on s390x for now until we find out what's going on.
