### ISSUE TITLE
Log error after changing to Apache 2.4 and php-fpm

### ISSUE THREAD

**Issue by spawnzao** [fail2ban/fail2ban#2717]
### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): Fail2Ban v0.9.7
- OS, including release name/version: CentOS Linux release 7.7.1908 (Core)
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

After changing to Apache 2.4 and PHP-FPM fail2ban stopped recognizing ModSecurity errors.

Client tag is duplicated, I believe this is the problem.

#### Any additional information
Server version: Apache/2.4.6 (CentOS)
Server built:   Apr  2 2020 13:13:23
Server's Module Magic Number: 20120211:24
Server loaded:  APR 1.4.8, APR-UTIL 1.5.2
Compiled using: APR 1.4.8, APR-UTIL 1.5.2
Architecture:   64-bit
Server MPM:     event

##### Before
```
[Sat May 09 00:09:19.798944 2020] [:error] [pid 22226] [client x.x.x.x] ModSecurity: Access denied with code 401 (phase 2). Operator EQ matched 1 at IP:blocked. [file "/etc/httpd/modsecurity.d/activated_rules/modsecurity_wp_login.conf"] [line "14"] [id "500000"] [msg "Ip address blocked for 15 minutes, more than 5 login attempts in 3 minutes."] [hostname "xxx.xx.xxx.xx"] [uri "/wp-login.php"] [unique_id "XrYe33M3ExvQAAAKg"]
[Sat May 09 00:10:29.442382 2020] [:error] [pid 22343] [client x.x.x.x] ModSecurity: Access denied with code 401 (phase 2). Operator EQ matched 1 at IP:blocked. [file "/etc/httpd/modsecurity.d/activated_rules/modsecurity_wp_login.conf"] [line "14"] [id "500000"] [msg "Ip address blocked for 15 minutes, more than 5 login attempts in 3 minutes."] [hostname "xxx.xx.xxx.xx"] [uri "/wp-login.php"] [unique_id "XrYfJSIO02Ypp1YwAAAR0"]
```
##### After
```
[Sat May 09 00:35:49.447278 2020] [:error] [pid 22406:tid 139985340565248] [client x.x.x.x:47722] [client x.x.x.x] ModSecurity: Access denied with code 401 (phase 2). Operator EQ matched 1 at IP:blocked. [file "/etc/httpd/modsecurity.d/activated_rules/modsecurity_wp_login.conf"] [line "14"] [id "500000"] [msg "Ip address blocked for 15 minutes, more than 5 login attempts in 3 minutes."] [hostname "xxx.xx.xxx.xx"] [uri "/wp-login.php"] [unique_id "XrYlFb5IY3I@EoLORAAAAo"], referer: https://xxx.xx.xxx.xx/wp-login.php
[Sat May 09 00:35:52.389262 2020] [:error] [pid 22406:tid 139985298601728] [client x.x.x.x:47762] [client x.x.x.x] ModSecurity: Access denied with code 401 (phase 2). Operator EQ matched 1 at IP:blocked. [file "/etc/httpd/modsecurity.d/activated_rules/modsecurity_wp_login.conf"] [line "14"] [id "500000"] [msg "Ip address blocked for 15 minutes, more than 5 login attempts in 3 minutes."] [hostname "xxx.xx.xxx.xx"] [uri "/wp-login.php"] [unique_id "XrYlGL5IY3I@EoLOgAAAA8"], referer: https://xxx.xx.xxx.xx/wp-login.php
```

**Comment by sebres** [comment]
v0.9.7 is outdated, checked with 0.10 now in e700ccc6671d64aa725905763c66d74522bbd6ca - it works without any issue;
thus closing now.
