### ISSUE TITLE
_grep_logs and action_mwl with systemd

### ISSUE THREAD

**Issue by shapeshed** [fail2ban/fail2ban#2727]
### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban 0.11.1
- Arch Linux, rolling release.
- Postfix 3.5.1
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)
```
/etc/fail2ban/jail.local

[DEFAULT]
destemail   = my@domain.com
sender      = my@domain.com
action      = %(action_mwl)s
backend     = systemd
```

```
/etc/fail2ban/jail.d/postfix.conf

[postfix]
enabled = true
mode = aggressive
findtime = 5m
bantime = 60m
```

### The issue:

Emails delivered by fail2ban using the `mwl` action do not include lines from the log. I traced this through the code and see that the logs are retrieved here

https://github.com/fail2ban/fail2ban/blob/bb0f732ae69894b22306dd7efa213513e3acd8a2/config/action.d/helpers-common.conf#L7

This assumes a file so where systemd is used it fails and logfile is not set. Here is the DEBUG log where logpath is not set so there is nothing to grep. 

```
2020-05-16 10:15:07,288 fail2ban.action         [307848]: #09-Lev. ( printf %b "Subject: [Fail2Ban] postfix: banned 78.128.113.100 from myhost
Date: `LC_ALL=C date +"%a, %d %h %Y %T %z"`
From: Fail2Ban <my@domain.com>
To: my@domain.com\n
Hi,\n
The IP 78.128.113.100 has just been banned by Fail2Ban after
5 attempts against postfix.\n\n
Here is more information about 78.128.113.100 :\n"
whois 78.128.113.100 || echo "missing whois program";
printf %b "\nLines containing failures of 78.128.113.100 (max 1000)\n";
logpath=""; grep -m 1000 -wF "78.128.113.100" $logpath | tail -n 1000;
printf %b "\n
Regards,\n
Fail2Ban" ) | /usr/bin/sendmail -f "my@domain.com" "my@domain.com"
```

I am able to manually retrieve the logs with 

```
journalctl -u postfix -n 1000 | grep -m 1000 -wF "78.128.113.100"
```
Should the action_mwl work with systemd or is this a bug?

**Comment by sebres** [comment]
This actions are rather an atavism (and have been developed as systemd journal was not yet available).
Fail2ban already know the messages that had cause a ban (as tag `<matches>`), you can use an action [sendmail-whois-matches](https://github.com/fail2ban/fail2ban/blob/master/config/action.d/sendmail-whois-matches.conf) instead of action `sendmail-whois-lines`.

Or you could overwrite `_grep_logs` in `action.d/helpers-common.local` (but then it would affect all jails). Another variant is to specify that per jail, something like:
```ini
[postfix]
action=%(action_mwl)s[_grep_logs='journalctl -u postfix -n 1000 | grep -m 1000 -wF "<ip>"']
```

**Comment by shapeshed** [comment]
Thanks for this and for your work on fail2ban!

For any other systemd users the override I used was 

```
[postfix]
action=%(action_mwl)s[_grep_logs='journalctl -q -u postfix -n 1000 -g "<ip>"']
```
