### ISSUE TITLE
a lot of "RETURN" targets in different chains

### ISSUE THREAD

**Issue by ecxod** [fail2ban/fail2ban#2728]
I do not know if it is a bug or a hidden feature but I have a lot of similar rules in all f2b chains that look like this :

```
Chain f2b-postfix-sasl (0 references)
target     prot opt source               destination
RETURN     all  --  0.0.0.0/0            0.0.0.0/0
RETURN     all  --  0.0.0.0/0            0.0.0.0/0
[....... about 10000 times ...]
RETURN     all  --  0.0.0.0/0            0.0.0.0/0
RETURN     all  --  0.0.0.0/0            0.0.0.0/0
```

**Comment by sebres** [comment]
Hmm... this is definitely not correct.
Normally the chains of fail2ban (created by start of fail2ban or on demand by first ban only, depending on fail2ban version) contain only one such RETURN rule at end of the chain (after all banned IPs).

Which fail2ban version and action it is?
Can you also provide an output of `?sudo? fail2ban-client -d | grep postfix-sasl`?

**Comment by sebres** [comment]
Neither I can reproduce it, nor I see where it could happen without some customizations.
Closed unless more info provided.
