### ISSUE TITLE
Help needed with configuring

### ISSUE THREAD

**Issue by jfirestorm44** [fail2ban/fail2ban#2729]
### Environment:
Home NAS

- Fail2Ban version (including any possible distribution suffixes): 10.2
- OS, including release name/version: Raspbian Buster Lite
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

I'm not sure this is the right place but I couldn't find any dedicated forum for this program. I, for the life of me, can't figure out how to make the fail2ban-regex give me good results. I am new to linux based software and know very little about regex so that is part of the problem. I have created a txt file called "test.log" and another file called "jellyfilter.conf" for testing purposes. When I run the following:
```
sudo fail2ban-regex /srv/dev-disk-by-label-HomeDrive/"config files"/fail2ban/test2.log /srv/dev-disk-by-label-HomeDrive/"config files"/fail2ban/jellyfilter.conf
 ```
I get the below message:
```
Running tests
=============

Use   failregex line : /srv/dev-disk-by-label-HomeDrive/config files/fail...
ERROR: No failure-id group in '/srv/dev-disk-by-label-HomeDrive/config files/fail2ban/jellyfilter.conf'
```
No matter how many times I try to alter my failregex I can't get it to work. Here is what I put inot the test.log file:
```
{"log":"[11:45:54] [ERR] [4] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: [12.123.12.123] Invalid username or password entered. URL: http://jellyfin.mydomain.duckdns.org/Users/authenticatebyname\n","stream":"stdout","time":"2020-05-22T11:45:54.938405196Z"}
```
That is what is produced from the jellyfin container when I have a bad login attempt.

And here are all the variations (there's been a lot more) for the failregex I've tried:
```
\bEmby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: \[<HOST>\]\sInvalid\susername\sor\spassword\sentered\.\b
```
```
^([\w\W\.\:]+)\sError processing request: \[<HOST>\] Invalid username or password entered\.$
```
```
^.*Emby\.Server\.Implementations\.HttpServer\.HttpListenerHost: Error processing request: <HOST> Invalid username or password entered\.$
```

I have tried this also to check the date format
```
jfirestorm44@raspberrypi:~ $ sudo fail2ban-regex "2020-05-21T01:02:28.178257566Z                                                      129.167.12.2" "<HOST>"

Running tests
=============

Use   failregex line : <HOST>
Use      single line : 2020-05-21T01:02:28.178257566Z 129.167.12.2


Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] {^LN-BEG}ExYear(?P<_sep>[-/.])Month(?P=_sep)Day(?:T|  ?)24hour:Minute:Sec                                                     ond(?:[.,]Microseconds)?(?:\s*Zone offset)?
`-

Lines: 1 lines, 0 ignored, 0 matched, 1 missed
[processed in 0.01 sec]

|- Missed line(s):
|  2020-05-21T01:02:28.178257566Z 129.167.12.2
`-
```
Does that mean it's good? Sorry I'm completely new to this. Any help would be great. Thank you in advance!

**Comment by jfirestorm44** [comment]
So it seems like part of my problem was using a testing filter outside of the 'filter.d' directory caused issues. I created the file inside the directory and now I am just getting Date/Time issues.

```
jfirestorm44@raspberrypi:/etc/fail2ban/filter.d $ sudo fail2ban-regex /var/lib/docker/containers/d5964d76ca147b7ef74cbd48a0c696c311edb6696c49622aa474efbc73333358/d5964d76ca147b7ef74cbd48a0c696c311edb6696c49622aa474efbc73333358-json.log /etc/fail2ban/filter.d/jellyfin.conf

Running tests
=============

Use   failregex filter file : jellyfin, basedir: /etc/fail2ban
Use         log file : /var/lib/docker/containers/d5964d76ca147b7ef74cbd48a0c696c311edb6696c49622aa474efbc73333358/d5964d76ca147b7ef74cbd48a0c696c311edb6696c49622aa474efbc73333358-json.log
Use         encoding : UTF-8


Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [2282] ExYear(?P<_sep>[-/.])Month(?P=_sep)Day(?:T|  ?)24hour:Minute:Second(?:[.,]Microseconds)?(?:\s*Zone offset)?
`-

Lines: 2282 lines, 0 ignored, 0 matched, 2282 missed
[processed in 2.61 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all 2282 lines
```

How can I fix that?

**Comment by jfirestorm44** [comment]
Ok I got rid of the Date Template error but I don't know if I did it properly or not. Using  `datepattern` I matched it to the date at the END of the jellyfin log. The problem is I don't know if Fail2ban looks at the end of a log file for the date. So here is what I have now.

jail.local
```
[jellyfin]
port     = http,https
logpath  = /var/lib/docker/containers/d5964d76ca147b7ef74cbd48a0c696c311edb6696c49622aa474efbc73333358/d5964d76ca147b7ef74cbd48a0c696c311edb6696c49622aa474efbc73333358-json.log
maxretry = 3
bantime  = 30
banaction = iptables-multiport
filter   = jellyfin
enabled  = true
```
What a login error looks like in my jellyfin log:
```
{"log":"[11:45:54] [ERR] [4] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: [12.123.12.123] Invalid username or password entered. URL: http://jellyfin.jnorth007.duckdns.org/Users/authenticatebyname\n","stream":"stdout","time":"2020-05-22T11:45:54.938405196Z"}
```

jellyfin.conf
```
# Fail2Ban for jellyfin
#
#
[Definition]
datepattern = ^.*%%Y-%%b-%%dT%%H:%%M:%%S:%%f$
failregex = ^.*\[<HOST>\]\sInvalid$

ignoreregex =
```
And here is what my test looks like (Still no matches):
```
Running tests
=============

Use   failregex filter file : jellyfin, basedir: /etc/fail2ban
Use      datepattern : ^.*Year-MON-DayT24hour:Minute:Second:Microseconds$
Use         log file : /var/lib/docker/containers/d5964d76ca147b7ef74cbd48a0c696c311edb6696c49622aa474efbc73333358/d5964d76ca147b7ef74cbd48a0c696c311edb6696c49622aa474efbc73333358-json.log
Use         encoding : UTF-8


Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:

Lines: 3278 lines, 0 ignored, 0 matched, 3278 missed
[processed in 0.29 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all 3278 lines
```

1) Does fail2ban look through the whole line to find the DTG or does it need it to be at the beginning? 
2) Can you tell me if my datepattern is correct for the log I posted? 
3) Can you help me get this working in anyway possible? Please.

Thank you!

**Comment by rucksman** [comment]
You sould improve datepattern. From what I do unterstand about datepattern there is no need for `^.*` in the beginning (althoug I am not 100% sure).

The pattern itself should be `%%Y-%%m-%%dT%%H:%%M:%%S.%%fZ` (not tested). So month and the colon right before the milliseconds are wrong.

**Comment by jfirestorm44** [comment]
Thank you. I did find more guidance on Python datepattern and I now have:

`^"%%Y-%%m-%%dT%%H:%%M:%%S.%%f%%Z"$`

I have also tried it without the %%Z and without the quotes. I've tried it without the ^ and $ at the begining snd end also. I've tried many many variations. I really believe the problem is that fail2ban only looks at the beginning of the log line for the DTG and not the end. My DTG is at the end of the line and I can't seem to find the right code to capture it. I have this working for other processes/apps just not this one. Do you know if there's is any way to get it to grab the DTG from the dn of my log line?

**Comment by sebres** [comment]
Since 0.10 default datepatterns regexp are anchored to begin of message string or to the word-boundaries.
Also note that parsing of `Z` is important (because it signaling fail2ban that the timestamp belongs to UTC time zone rather than current system time zone).
I would use something like that:
```ini
datepattern = "time":"%%Y-%%m-%%dT%%H:%%M:%%S\.%%f\d*%%Z"
```
Note `%f\d*`, because `%f` matches only up to microseconds (6 digits maximally).
