### ISSUE TITLE
Can someone explain what DB PURGE AGE means?

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [fail2ban/fail2ban#2730]
What I read was, Age at which bans should be purged from the database. So, if I perma ban an IP by using -1 for ban time. Does DB PURGE AGE purge that perma ban from the database after? I'm kinda confused on what it supposed to do.

Thanks!

**Comment by sebres** [comment]
> I'm kinda confused on what it supposed to do.

It is supposed to clean up sqlite database to remove too old (obsolete and no more interesting) bans.
On a well visited server it can grow too heavy, so to avoid that purge is called periodically and removes all tickets with time of ban smaller as now - dbpurgeage.
Database is used to restore still active tickets by restart (v.0.10) and to find recidive (already known) evildoers to increase ban time (v.0.11).

Also note that persistent ban may be too bad in sense of load of the server (overloading net-filter subsystem, fail2ban etc).
Something like `3w` is really enough.
