### ISSUE TITLE
No bans although filter works

### ISSUE THREAD

**Issue by rucksman** [fail2ban/fail2ban#2731]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): 0.10.2-2
- OS, including release name/version:  Ubuntu 18.04.4 LTS
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x ] You have not applied any additional foreign patches to the codebase
- [x ] Some customizations were done to the configuration (provide details below is so)

### The issue:
I am running Gitlab in a Docker container and want to ban IPs that try to attack the ssh part of Gitlab.

This is what I added to my jail.local:
```
[docker-gitlab-sshd]
enabled  = true
port     = 11222
filter   = docker-gitlab-sshd
logpath  = /data/gitlab/logs/sshd/current
maxretry = 10
```
This is my filter:
```
[Definition]
failregex = ^ Invalid user .* from <HOST>
ignoreregex =
datepattern = ^%%Y-%%m-%%d_%%H:%%M:%%S.%%f
```
I am trying now to ssh into Gitlab and enter 14 times the wrong password.

When doing this:
```
fail2ban-regex -v /data/gitlab/logs/sshd/current /etc/fail2ban/filter.d/docker-gitlab-sshd.conf
```
I get this (shortend the 64 hits to only my attempts):
```
Running tests
=============

Use   failregex filter file : docker-gitlab-sshd, basedir: /etc/fail2ban
Use      datepattern : ^Year-Month-Day_24hour:Minute:Second.Microseconds
Use         log file : /data/gitlab/logs/sshd/current
Use         encoding : UTF-8


Results
=======

Failregex: 64 total
|-  #) [# of hits] regular expression
|   1) [64] ^ Invalid user .* from <HOST>
|     XXX.XXX.XXX.XXX  Sat May 23 18:13:58 2020
|     XXX.XXX.XXX.XXX  Sat May 23 18:14:14 2020
|      XXX.XXX.XXX.XXX  Sat May 23 18:14:16 2020
|      XXX.XXX.XXX.XXX  Sat May 23 18:14:18 2020
|      XXX.XXX.XXX.XXX Sat May 23 18:14:21 2020
|      XXX.XXX.XXX.XXX  Sat May 23 18:14:23 2020
|      XXX.XXX.XXX.XXX  Sat May 23 18:14:25 2020
|      XXX.XXX.XXX.XXX  Sat May 23 18:14:28 2020
|      XXX.XXX.XXX.XXX  Sat May 23 18:14:30 2020
|      XXX.XXX.XXX.XXX  Sat May 23 18:14:32 2020
|      XXX.XXX.XXX.XXX  Sat May 23 18:14:34 2020
|      XXX.XXX.XXX.XXX  Sat May 23 18:14:36 2020
|      XXX.XXX.XXX.XXX  Sat May 23 18:14:38 2020
|      XXX.XXX.XXX.XXX  Sat May 23 18:14:40 2020
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [258] ^Year-Month-Day_24hour:Minute:Second.Microseconds
`-

Lines: 258 lines, 0 ignored, 64 matched, 194 missed
[processed in 0.01 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all 194 lines
```
My interpretation from this output: everything works. But no: obviously this did not work, because normally I should not have been able to enter the password so often (but be banned after the 10th attempt). To double check this:
```
fail2ban-client status docker-gitlab-sshd
```
shows:
```
Status for the jail: docker-gitlab-sshd
|- Filter
|  |- Currently failed: 0
|  |- Total failed:     0
|  `- File list:        /data/gitlab/logs/sshd/current
`- Actions
   |- Currently banned: 0
   |- Total banned:     0
   `- Banned IP list:
```
Why is that???

In /var/log/fail2ban.log there is nothing suspicious:
```
INFO    Jail 'docker-gitlab-sshd' uses pyinotify {}
INFO    Initiated 'pyinotify' backend
INFO      date pattern `'^%Y-%m-%d_%H:%M:%S.%f'`: `^Year-Month-Day_24hour:Minute:Second.Microseconds`
INFO    Added logfile: '/data/gitlab/logs/sshd/current' (pos = 21465, hash = a67a287f8e02ae400af8e70a0e6927cfcaa0019e)
INFO      encoding: UTF-8
INFO      maxRetry: 10
INFO      findtime: 600
INFO      banTime: 600
INFO    Jail 'sshd' started
INFO    Jail 'docker-gitlab-sshd' started
```

So what goes wrong here?

### Update
First problem solved. Reason for not showing "Currently failed" or "Total failed" is wrong timezone in the container. I have not found a way to set the correct tmezone until now, but as a kind of workaround I extended "findtime" to 24 hours. No I get the following weird output after
```
fail2ban-client status docker-gitlab-sshd
```
```
Status for the jail: docker-gitlab-sshd
|- Filter
|  |- Currently failed: 1
|  |- Total failed:     13
|  `- File list:        /data/gitlab/logs/sshd/current
`- Actions
   |- Currently banned: 0
   |- Total banned:     1
   `- Banned IP list:
```
What does that mean? Why is "Total banned" set to 1 whereas "Currently banned" is 0? And why is there no IP listed here? Obviously there is some problem, because I was even able to enter the wrong password more than 10 times, altough fail2ban registered all attempts. What do I have to do to make it work?

### Update 2
I also extended bantime to 24h, and now I get
```
Status for the jail: docker-gitlab-sshd
|- Filter
|  |- Currently failed: 2
|  |- Total failed:     3
|  `- File list:        /srv/gitlab/logs/sshd/current
`- Actions
   |- Currently banned: 1
   |- Total banned:     1
   `- Banned IP list:   XXX.XXX.XXX.XXX
```
Nevertheless I am still able to connect to the container and enter worng credentials, I guess this is not the expected behaviour?

iptables shows:
```
Chain f2b-docker-gitlab-sshd (1 references)
target     prot opt source               destination
REJECT     all  --  XXX.XXX.XXX.XXX         0.0.0.0/0            reject-with icmp-port-unreachable
RETURN     all  --  0.0.0.0/0            0.0.0.0/0
```

**Comment by rucksman** [comment]
### Solved
The solution was hard to find, but at the same time very simple to implement: Just adding the following line to my jail definition did the trick:
```
action   = iptables-allports[chain="FORWARD"]
```

**Comment by adduc** [comment]
For anyone else stumbling across this issue, GitLab's SSH logs are in UTC.

If your system is set to a different timezone and is running a version of fail2ban 0.10.0 or later, `logtimezone = UTC` can be added to your jail definition to process timestamps accurately.

The current jail configuration I'm using for GitLab SSH:

```
[gitlab]
filter = gitlab
enabled = true
logpath = /path/to/gitlab/logs/sshd/current
port = 12222
maxretry = 10
logtimezone = UTC
backend = polling
action   = iptables-allports[chain="FORWARD"]
```
