### ISSUE TITLE
fail2ban does not want to be friends with sslh

### ISSUE THREAD

**Issue by f1h0** [fail2ban/fail2ban#2738]
I do not know what to do, fail2ban blocked my server has locked himself
because I have, in addition ```sslh```.
When I connect via ssh and port 443 to the log file auth.log I see the IP of my server.
A should be the same in ```Nginx``` logs the user's IP no ip server
what to do?
I have a whole does not go, everything stopped

```
ver Fail2Ban v0.9.3
```

**Comment by sebres** [comment]
Fail2ban v0.9 has `ignoreip` and `ignorecommand` options to specify ignore IPs/hosts or to provide the command checking a ticket.
Fail2ban v0.10 has additionally `ignoreself` which if set to true would ignore all own IP addresses.

Another reasons are described in FAQ in [wiki :: How fail2ban works](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works), see second question/answer.

> I have, in addition sslh

We does not have such jail/filter on bord.., No idea what is wrong with your config.
But basically fail2ban has allports actions (probably you have used for the jail) and multiport actions (you can use to block specified ports only).

**Comment by klausmcm** [comment]
> I do not know what to do, fail2ban blocked my server has locked himself
> because I have, in addition `sslh`.
> When I connect via ssh and port 443 to the log file auth.log I see the IP of my server.
> A should be the same in `Nginx` logs the user's IP no ip server
> what to do?
> I have a whole does not go, everything stopped
> 
> ```
> ver Fail2Ban v0.9.3
> ```

The issue I had with *sslh* is that the logged IP is always 127.0.0.1. I replaced sslh with HAProxy and enabled the PROXY protocol in HAProxy so that all the backend servers are able to see the client's IP instead of localhost.
