### ISSUE TITLE
Fail2ban UNBAN

### ISSUE THREAD

**Issue by aaPanel** [fail2ban/fail2ban#2739]
Hello, 

our panel installation provides fail2ban as a free plug-in. 

Recently, users received feedback that the IP cannot be banned. We found that it was a problem caused by using the latest dev version. 

It was changed to yum / apt and returned to normal after installation. 

Here Give you feedback, 

best regards

**Comment by sebres** [comment]
> Recently, users received feedback that the IP cannot be banned.

Perfect that your users received the feedback, strange is why we don't do that?

> We found that it was a problem caused by using the latest dev version.

Nice. So you can surely describe more precise what is the problem exactly?
Unless more (any) info provided I can close it here and give you only few advices:
- don't use dev-versions if you're not familiar
- try to describe the issue as precise as possible and follow the issue template (at least give any info that can help to solve that)
- and last but not least - read the docu. [wiki](https://github.com/fail2ban/fail2ban/wiki), installation descriptions (and I hope you're not banned by google and co).
