### ISSUE TITLE
ENH: Expand bantime possibilities, eg minimum and maximum length bans

### ISSUE THREAD

**Issue by superian** [fail2ban/fail2ban#274]
When a number of bots are used against a server at the same time in a coordinated attack, they can cause problems due to the number of requests. Currently, fail2ban will catch the attacks and ban them all for the same time. If the attack is continuing when the bans expire, the same flood will happen. Repeat.

If it were possible to say 'ban for a minimum of n seconds and a maximum of m seconds', this could be spread out after the initial bans, as it is likely that not all bans will expire at the same time. At the point of banning, a random number between 0 and (m-n) would be added to n to determine the actual length.

**Comment by sebres** [comment]
implemented in #1460
