### ISSUE TITLE
Failregex does not work with Russian text

### ISSUE THREAD

**Issue by lokha** [fail2ban/fail2ban#2743]
I am trying to configure failregex with Russian text, but it refuses to work. I am almost sure that the problem is in the Russian text. I tested, it worked with English text, but not Russian.

Log file: 
[out.txt](https://github.com/fail2ban/fail2ban/files/4713175/out.txt)

fail2ban-regex:
```shell
fail2ban-regex -d "^\[%H:%M:%S" /home/mcraft/out.txt ".+\[BotFilter\] Игрок \/<ADDR>:[0-9]+\/.* провалил проверку: Неправильное падение"
```

Debian 9, fail2ban version: Fail2Ban v0.10.6-dev

Is it possible to configure regex expressions with Russian text?

**Comment by sebres** [comment]
Python 2.x?

Prior to python 3.3, python's re-module basically did not support any unicode tokens (given as string with unicode characters in regular expression). However, python unicode strings, have always supported the `\uFFFF` (or `\xFF` for byte representation of utf-8) notation, but it depends how exactly the scanning input string is converted after read from log (bytes, string or unicode).

So either you'd rewrite it with `\uFFFF` or `\xFF` notation for every Russian character (and I'm still unsure it'd work) or would simply install fail2ban with newest python version, where it works out of the box:
```bash
$ fail2ban-python --version
Python 3.5.3

$ fail2ban-regex /tmp/out.txt /tmp/out.conf

Running tests
=============

Use   failregex file : /tmp/out.conf
Use      datepattern : ^\[24hour:Minute:Second\]\s+
Use         log file : /tmp/out.txt
Use         encoding : UTF-8


Results
=======

Failregex: 43 total
|-  #) [# of hits] regular expression
|   1) [43] ^\[[^\]]+\]: \[BotFilter\] Игрок /<ADDR>:\d{1,5}/<F-USER>\S+</F-USER> провалил проверку: Неправильное падение
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [305] ^\[24hour:Minute:Second\]\s+
`-

Lines: 348 lines, 0 ignored, 43 matched, 305 missed
```
filter (`/tmp/out.conf`):
```ini
[Definition]
failregex = ^\[[^\]]+\]: \[BotFilter\] Игрок /<ADDR>:\d{1,5}/<F-USER>\S+</F-USER> провалил проверку: Неправильное падение
datepattern = ^\[%%H:%%M:%%S\]\s+
```

**Comment by lokha** [comment]
how to configure fail2ban to use python 3? I have it installed on the host
```
root@host5:~# python3 --version
Python 3.5.3
```

**Comment by sebres** [comment]
Well, you have to install it using python3 (`./fail2ban-2to3` and `?sudo? python3 setup.py install`).
See https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually for more information.
