### ISSUE TITLE
Integrate with firewalld on Fedora 32 using nftables sets and rules

### ISSUE THREAD

**Issue by ajayramaswamy** [fail2ban/fail2ban#2746]
In current Fedora 32 the only way of using firewalld and fail2ban is rich rules. This causes many problems when the system boots and there are a lot of ips to be banned. It takes many minutes for the ruleset to be loaded

I have hacked up a modified nftables.conf in fail2ban to work well with firewalld and so far it looks good.

A description of what is happening

first create a set
```
nft add set inet firewalld f2b-sshd { type ipv4_addr\; flags dynamic, timeout\; timeout 3600s \; }
```

then a chain for the rules

```
nft add chain inet firewalld process_fail2ban
```

then a rule for each set in that chain

```
nft add rule inet firewalld process_fail2ban ip saddr@f2b-sshd tcp dport {22, 80, 443, 9090}  log prefix "f2b-sshd " counter drop
```
and finally hook up that chain in to some place in firewalld builtin chains

```
nft insert rule inet firewalld filter_INPUT_ZONES jump process_fail2ban 
```
this point depends on number of zones that are active, order of interfaces etc

I have attached my current running config files for others to test and reproduce
action files go in /etc/fail2ban/action.d/
[nftables.local.txt](https://github.com/fail2ban/fail2ban/files/4733459/nftables.local.txt)
[nftables-common.local.txt](https://github.com/fail2ban/fail2ban/files/4733460/nftables-common.local.txt)

and jail goes in /etc/fail2ban/jail.d/
[jail.local.txt](https://github.com/fail2ban/fail2ban/files/4733461/jail.local.txt)

I have also asked in firewalld issue tracker for some hooks and enhancements to make this easier
https://github.com/firewalld/firewalld/issues/642

**Comment by sebres** [comment]
Although I quite don't follow what the issue exactly is (or is it rather a feature request?)...
But we have released new completely rewritten nftables action (see #2254) that isolates fail2ban chains into separate table.
From one side your adjustments are probably not compatible (for instance there is no nftables-common anymore), from other side it may be simpler now to provide customization to this action.

> This causes many problems when the system boots and there are a lot of ips to be banned. 

And what would they be?

> It takes many minutes for the ruleset to be loaded

Well, this is basic issue of every action unless bulk ban going implemented.
I don't see how your adjustment could help to speed-up it,

**Comment by ajayramaswamy** [comment]
Thank you for the clarification I have now deployed the solution based off

> But we have released new completely rewritten nftables action (see #2254) that isolates fail2ban chains into separate table.

It seems to be working well on my webserver I will monitor and report if any further issues come up
