### ISSUE TITLE
OpenWRT support

### ISSUE THREAD

**Issue by peci1** [fail2ban/fail2ban#2753]
This is not as much an issue as an announcement: I've prepared support scripts that allow easy installation of fail2ban on OpenWRT systems, including procd launch scripts and a simple uci config for the location of the database file.

You'll find it at https://github.com/peci1/fail2ban_openwrt .

I've no ambitions towards packaging fail2ban as an official OpenWRT package, but if there's will from somebody else, I can offer my help. Also, if you'd like to pull the init system config files directly into fail2ban, I can help with that.

**Comment by erdoukki** [comment]
thanks

**Comment by sebres** [comment]
We have wiki here for such things, so you could add it to [Miscellaneous](https://github.com/fail2ban/fail2ban/wiki#miscellaneous) section or some new page to the wiki.
I'll close this here as no issue.

**Comment by peci1** [comment]
Okay, I added the link to the Wiki into Misc section: https://github.com/fail2ban/fail2ban/wiki/Home/89fc3f5867727a14e35d776e8edc162ed86515d9 .

**Comment by erdoukki** [comment]
@peci1 thanks !
