### ISSUE TITLE
Unable to use nftables with default config (Raspbian 10)

### ISSUE THREAD

**Issue by dgedgedge** [fail2ban/fail2ban#2760]
### Environment:

- [x] Fail2Ban installed via OS/distribution mechanisms 
- [ ] You have not applied any additional foreign patches to the codebase 
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:
I had some errors from fail2ban using nft: 

the computed cmd did not work :
`nft insert rule inet filter input meta l4proto tcp ip saddr @f2b-sshd reject`

with initial nftables:
```
table inet filter {
        chain input {
                # Assign a high priority to reject as fast as possible and avoid more complex rule evaluation
                type filter hook input priority 100;
        }
}

```

I first though looking at the past issue that it was an issue with the chain name.
In fact the issue was here the "reject" cmd.

Changing in action.d/nftables-common.conf  blocktype to drop instead of reject
solved the issue.

note: the previous cmd "nft add set inet filter f2b-sshd \{ type ipv4_addr\; \}" did work.

### Configuration, dump and another helpful excerpts

```
> Distributor ID:	Raspbian
> Description:	Raspbian GNU/Linux 10 (buster)
> Release:	10
> Codename:	buster
```

```
ii  fail2ban       0.10.2-2.1   all          ban hosts that cause multiple authentication errors
ii  nftables       0.9.0-2      armhf        Program to control packet filtering rules by Netfilter project

```
#### Any customizations done to /etc/fail2ban/ configuration
```
root@jetcomp:~# diff /etc/fail2ban/jail.conf /etc/fail2ban/jail.conf.pkgori 
49c49
< ignorself = true
---
> #ignorself = true
54c54
< ignoreip = 127.0.0.1/8 ::1 192.168.202.10 89.156.39.124 
---
> #ignoreip = 127.0.0.1/8 ::1
63,68c63
< #bantime  = 10m
< #bantime  = 600
< bantime  = 86400   ; 1 day
< #bantime  = 604800   ; 1 week
< #bantime  = 2592000   ; 1 mounth
< #bantime  = 315336000   ; 1 year
---
> bantime  = 10m
72,77c67
< #findtime  = 10m
< #findtime = 600
< #findtime = 86400   ; 1 day
< #findtime = 604800   ; 1 week
< findtime = 2592000   ; 1 mounth
< #findtime = 315336000   ; 1 year
---
> findtime  = 10m
80c70
< maxretry = 3
---
> maxretry = 5
101,102c91
< #backend = auto
< backend = polling
---
> backend = auto
166d151
< #chain = input
182,185c167,168
< #banaction = iptables-multiport
< #banaction_allports = iptables-allports
< banaction = nftables-multiport
< banaction_allports = nftables-allports
---
> banaction = iptables-multiport
> banaction_allports = iptables-allports
244,245c227
< #action = %(action_)s
< action = %(action_mw)s
---
> action = %(action_)s

```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
2020-06-19 15:27:27,399 fail2ban.utils          [27323]: Level 39 755248e0 -- exec: nft add set inet filter f2b-sshd \{ type ipv4_addr\; \}
nft insert rule inet filter input meta l4proto tcp ip saddr @f2b-sshd reject
2020-06-19 15:27:27,401 fail2ban.utils          [27323]: ERROR   755248e0 -- stderr: 'Error: Could not process rule: No such file or directory'
2020-06-19 15:27:27,401 fail2ban.utils          [27323]: ERROR   755248e0 -- stderr: 'insert rule inet filter input meta l4proto tcp ip saddr @f2b-sshd reject'
2020-06-19 15:27:27,402 fail2ban.utils          [27323]: ERROR   755248e0 -- stderr: '^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'
2020-06-19 15:27:27,402 fail2ban.utils          [27323]: ERROR   755248e0 -- returned 1
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
> Changing in action.d/nftables-common.conf blocktype to drop instead of reject
solved the issue.

Don't do that in default configs (it can be overwritten with next upgrade, let alone new fail2ban version does not have nftables-common anymore):
- either overwrite it directly in your `jail.local`, for instance:
```ini
[Default]
banaction=nftables-multiport[blocktype=drop]
banaction_allports = nftables-allports[blocktype=drop]
```
- or create a `nftables-common.local` file instead and set it there (but note, as written above, this is not available in newest fail2ban versions, see #2254).

> In fact the issue was here the "reject" cmd.
> Could not process rule: No such file or directory

In fact this either a 3rd party compat issue (e. g. of raspbian maintainers) or your own nft-configuration (or some firewall service).
Reject is normally a legal statement and fully supported since linux kernel 3.18. I don't know why it is not available in your pi-box.
See https://wiki.nftables.org/wiki-nftables/index.php/Rejecting_traffic

Also note #2217 for a discussion reject vs. drop.
