### ISSUE TITLE
Install fails to produce working installation on Buster (Rapsberry Pi OS)

### ISSUE THREAD

**Issue by Pi-DD** [fail2ban/fail2ban#2769]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.10.2-2.1
- OS, including release name/version: Raspberry Pi OS - Buster
- [ X] Fail2Ban installed via OS/distribution mechanisms
- [ X] You have not applied any additional foreign patches to the codebase
- [x ] Some customizations were done to the configuration (provide details below is so)

### The issue:
During installation this message is given....

[fail2ban-tmpfiles.conf:1] Line references path below legacy directory /var/run/, updating /var/run/fail2ban → /run/fail2ban; please update the tmpfiles.d/ drop-in file accordingly.

Attempt to get fail2ban status produces...
 Failed to access socket path: /var/run/fail2ban/fail2ban.sock. Is fail2ban running?

Status of service gives 

pi@DDhomepi8:~ $ sudo systemctl status fail2ban.service
● fail2ban.service - Fail2Ban Service
   Loaded: loaded (/lib/systemd/system/fail2ban.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-07-01 17:25:57 BST; 11s ago
     Docs: man:fail2ban(1)
  Process: 16322 ExecStartPre=/bin/mkdir -p /var/run/fail2ban (code=exited, status=0/SUCCESS)
  Process: 16323 ExecStart=/usr/bin/fail2ban-server -xf start (code=exited, status=255/EXCEPTION)
 Main PID: 16323 (code=exited, status=255/EXCEPTION)

Jul 01 17:25:57 DDhomepi8 systemd[1]: Starting Fail2Ban Service...
Jul 01 17:25:57 DDhomepi8 systemd[1]: Started Fail2Ban Service.
Jul 01 17:25:57 DDhomepi8 fail2ban-server[16323]:  No file(s) found for glob /var/log/audit/audit.log
Jul 01 17:25:57 DDhomepi8 fail2ban-server[16323]:  Failed during configuration: Have not found any log file for selinux-ssh jail
Jul 01 17:25:57 DDhomepi8 fail2ban-server[16323]:  Async configuration of server failed
Jul 01 17:25:57 DDhomepi8 systemd[1]: fail2ban.service: Main process exited, code=exited, status=255/EXCEPTION
Jul 01 17:25:57 DDhomepi8 systemd[1]: fail2ban.service: Failed with result 'exit-code'.

#### Steps to reproduce
De-install, clean up, re-install- same thing every time. 
### Configuration, dump and another helpful excerpts
No log file produced! 
#### Any customizations done to /etc/fail2ban/ configuration
`Standard jails enabled, ignore set to local IP range ``
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_
No log file produced
```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
> During installation this message is given....
> Line references path below legacy directory /var/run/ ...

See #2474 

> Install fails to produce working installation on Buster (Rapsberry Pi OS)

I'm not sure what you are calling a "working installation" (since no one jail is enabled per default after installation)...
If you mean that fail2ban is unable to start. then check your configuration - the log excerpt is pretty clear:
```
Jul 01 17:25:57 DDhomepi8 fail2ban-server[16323]: No file(s) found for glob /var/log/audit/audit.log
Jul 01 17:25:57 DDhomepi8 fail2ban-server[16323]: Failed during configuration: Have not found any log file for selinux-ssh jail
Jul 01 17:25:57 DDhomepi8 fail2ban-server[16323]: Async configuration of server failed
```
This means that you have configured `selinux-ssh` jail which referencing `/var/log/audit/audit.log` as `logpath`, which simply does not exist.
Either configure proper path (or switch to systemd backend if it is journal), or disable this jail.

Also note [wiki :: Proper fail2ban configuration](https://github.com/fail2ban/fail2ban/wiki/Proper-fail2ban-configuration) or [wiki :: Troubleshooting](https://github.com/fail2ban/fail2ban/wiki/Troubleshooting)

**Comment by gazzat5** [comment]
I have this problem with 0.10.2

I have configured logpath in [sshd] to point to the correct log, but the error persists.  Backend = auto, banaction = iptables-multiport

**Comment by gazzat5** [comment]
my issue was that i had 
[default]
enabled = true

enabling all jails even ones that weren't valid/configured.
