### ISSUE TITLE
Fail2ban doesn't detect wrong http login

### ISSUE THREAD

**Issue by walker9** [fail2ban/fail2ban#2776]
### Environment:
- 0.8.11-1
- Ubuntu 14.04.6
- iptables 1.4.21-1ubuntu1
- [x ] Fail2Ban installed via OS/distribution mechanisms
- [x ] You have not applied any additional foreign patches to the codebase

### The issue:

Have tried with many wrong HTTP logins, but the IP will not banned.

**jail.conf**
```
bantime  = 60800
findtime = 600
maxretry = 3
banaction = iptables-multiport (Have tried here also iptables and iptables-new)

[apache]
enabled  = true
port     = http,https
filter   = apache-auth
logpath  = /var/log/apache*/*error.log
maxretry = 3
```

**apache-auth.conf**
`failregex = ^%(_apache_error_client)s (AH01617: )?user .* authentication failure for "\S*": Password Mismatch$`

**Apache error.log**
```
[Tue Jul 14 15:07:57.811678 2020] [auth_basic:error] [pid 14981] [client 85.127.183.1:50538] AH01617: user admin: authentication failure for "/test": Password Mismatch
[Tue Jul 14 15:08:01.462037 2020] [auth_basic:error] [pid 14981] [client 85.127.183.1:50538] AH01617: user admin: authentication failure for "/test": Password Mismatch
[Tue Jul 14 15:08:04.667583 2020] [auth_basic:error] [pid 14981] [client 85.127.183.1:50538] AH01617: user admin: authentication failure for "/test": Password Mismatch
[Tue Jul 14 15:08:08.005547 2020] [auth_basic:error] [pid 14981] [client 85.127.183.1:50538] AH01617: user admin: authentication failure for "/test": Password Mismatch
[Tue Jul 14 15:08:11.363976 2020] [auth_basic:error] [pid 14981] [client 85.127.183.1:50538] AH01617: user admin: authentication failure for "/test": Password Mismatch
[Tue Jul 14 15:08:15.404780 2020] [auth_basic:error] [pid 14981] [client 85.127.183.1:50538] AH01617: user admin: authentication failure for "/test": Password Mismatch 
```

**Output from console: fail2ban-client status apache**
```
Status for the jail: apache
|- filter
|  |- File list:        /var/log/apache2/error.log
|  |- Currently failed: 0
|  `- Total failed:     0
`- action
   |- Currently banned: 0
   |  `- IP list:
   `- Total banned:     0
```

#### Relevant parts of /var/log/fail2ban.log file:
No errors or something else

**Comment by sebres** [comment]
I don't know what exactly hinder fail2ban to consider this failures, but v.0.8 is too old.
Either it is a RE or a datepattern...

You could try to update the filter with 0.9th version - [apache-auth.conf](https://github.com/fail2ban/fail2ban/blob/0.9/config/filter.d/apache-auth.conf) e. g. together with an include `apache-common.conf`.

which would interpolate the matching RE as:

```regex
^\[\] \[(:?error|\S+:\S+)\]( \[pid \d+(:\S+ \d+)?\])? \[client <HOST>(:\d{1,5})?\] (AH01617: )?user .*? authentication failure for "\S*": Password Mismatch(, referer: \S+)?$
```

Or better upgrade your outdated fail2ban version.

**Comment by walker9** [comment]
Thanks sebres with your pattern for apache-auth.conf it works. So i will try to renew some conf files in filter.d
