### ISSUE TITLE
Documentation Issue: Wiki - incorrect info in "HOWTO fail2ban with OpenVPN"

### ISSUE THREAD

**Issue by looselyhuman** [fail2ban/fail2ban#2780]
### Environment
Debian Buster
```
fail2ban:
  Installed: 0.10.2-2.1
  Candidate: 0.10.2-2.1
  Version table:
 *** 0.10.2-2.1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

### The issue:
https://www.fail2ban.org/wiki/index.php/HOWTO_fail2ban_with_OpenVPN

```
Create /etc/fail2ban/jail.d/openvpn containing:

# Fail2Ban configuration fragment for OpenVPN

[openvpn]
enabled  = true
port     = 1194
protocol = udp
filter   = openvpn
logpath  = /var/log/openvpn.log
maxretry = 3
```

This should begin:
`Create /etc/fail2ban/jail.d/openvpn.local containing:`
(note .local)

#### Steps to reproduce
1.) Create /etc/fail2ban/jail.d/openvpn
2.) Restart fail2ban
3.) `cat /var/log/fail2ban.log | grep open vpn`

#### Expected behavior
Should see references to openvpn in log.

#### Observed behavior
No references to openvpn in log.

#### Mitigation
`mv /etc/fail2ban/jail.d/openvpn /etc/fail2ban/jail.d/openvpn.local` and it works as expected.  Just a documentation issue.

**Comment by sebres** [comment]
yes, webpage/wiki of fail2ban is outdated...
just to link to #2580 (https://github.com/fail2ban/fail2ban/issues/2580#issuecomment-591397627)

**Comment by sebres** [comment]
let us avoid duplicates and handle this in #2580
