### ISSUE TITLE
FR: filter traefik-auth with JSON logfile

### ISSUE THREAD

**Issue by mr-manuel** [fail2ban/fail2ban#2783]
Would it be possible to have a regex filter for the JSON logfile of Traefik? Maybe @crazy-max is the right one for this?

Here is a sample:
`{"ClientAddr":"123.123.123.123:33796","ClientHost":"123.123.123.123","ClientPort":"33796","ClientUsername":"-","DownstreamContentSize":17,"DownstreamStatus":401,"Duration":114023,"OriginContentSize":17,"OriginDuration":27129,"OriginStatus":401,"Overhead":86894,"RequestAddr":"www.domain.tld","RequestContentSize":0,"RequestCount":434,"RequestHost":"www.domain.tld","RequestMethod":"GET","RequestPath":"/index.php","RequestPort":"-","RequestProtocol":"HTTP/2.0","RequestScheme":"https","RetryAttempts":0,"RouterName":"router__www_domain_tld@file","StartLocal":"2020-07-18T15:51:43.865140321+02:00","StartUTC":"2020-07-18T13:51:43.865140321Z","entryPointName":"web-secure","level":"info","msg":"","request_User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0","request_X-Forwarded-Host":"www.domain.tld","request_X-Forwarded-Port":"443","request_X-Forwarded-Proto":"https","time":"2020-07-18T15:51:43+02:00"}`

https://github.com/fail2ban/fail2ban/blob/78fc99ec7ee8185fe478091a21655a6a400bae09/config/filter.d/traefik-auth.conf#L59

Thanks a lot :)

Regards,
Manuel

**Comment by crazy-max** [comment]
Hi @mr-manuel,

A simple way to fulfill your need is to send the logs to an aggregator like [fluentd](https://docs.fluentd.org/) using the [fluentd Docker logging driver](https://docs.docker.com/config/containers/logging/fluentd/) and then send these logs from fluentd in a file that can be read by Fail2ban.

The only downside will be that your logs will no longer be viewable in the console. Multi logging drivers are only available for Docker Enterprise. But I'm currently working on a new way to handle logs with Docker using the Docker API to allow multi logging drivers. This will allow to send both logs to the console but also to a file and also to other managers like fluentd.

**Comment by mr-manuel** [comment]
Hi @crazy-max,

I'm not using docker and the logfiles are directly accessable by fail2ban. By trying I created this filter

`failregex = ^{"ClientAddr".*"ClientHost":"<HOST>".*"ClientUsername":"<usrre-<mode>>".*"OriginStatus":401,.*"RequestMethod":"<req-method>".*}`

but I'm not sure if this is secure enough. Maybe you can take a look and/or have a besser way?

**Comment by crazy-max** [comment]
@mr-manuel,

I think ti would be easier to use the [Common Log Format (CLF)](https://docs.traefik.io/observability/access-logs/#format) for your logs. See this [example](https://github.com/crazy-max/docker-fail2ban/blob/master/examples/jails/traefik/filter.d/traefik-auth.conf).

**Comment by sebres** [comment]
> but I'm not sure if this is secure enough.

It is not. 
Catch-all's are never good, still worse if they are coming before the `<HOST>` tag.

See https://github.com/fail2ban/fail2ban/issues/2330#issuecomment-459965597 for an example for better regex (more securely replacement of `.*` bypassing unneeded JSON groups).
