### ISSUE TITLE
Not matched regex for extra mode in sendmail-reject filter

### ISSUE THREAD

**Issue by Albram** [fail2ban/fail2ban#2787]
### Environment:
- py37-fail2ban-0.11.1_1
- FreeBSD 12.1-RELEASE-p7 GENERIC  amd64
- [X] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:
Not matched regex for mode = extra (or aggressive) in fail2ban/filter.d/sendmail-reject.conf when sendmail 8.15.2 smtp daemons started with default names.
In sendmail.cf (or sendmail.mc) smtp daemons have default names IPv4 and IPv6 and not match with regex.

#### Steps to reproduce
/usr/local/etc/fail2ban/jail.local

[sendmail-reject]
enabled  = true
mode    = extra

#### Expected behavior
Ban for rejected hosts when regex matched.
#### Observed behavior
No detecting and bans for hosts matched with regex rule for extra mode.
#### Any additional information
I`m change regex in sendmail-reject.conf  for workaround this problem (see below).
#### Any customizations done to /etc/fail2ban/ configuration
Change regex in /sendmail-reject.conf from:
```
mdre-extra = ^(?:\S+ )?\[(?:IPv6:<IP6>|<IP4>)\](?: \(may be forged\))? did not issue (?:[A-Z]{4}[/ ]?)+during connection to (?:TLS)?M(?:TA|S[PA])(?:-\w+)?$
```
To:
```
mdre-extra = ^(?:\S+ )?\[(?:IPv6:<IP6>|<IP4>)\](?: \(may be forged\))? did not issue (?:[A-Z]{4}[/ ]?)+during connection to (?:TLS)?(?:M)?(?:TA|S[PA])?(?:-\w+)?(?:IPv)?(?:4|6)?$

```
#### Relevant lines from monitored log files in question:

```
Jul 26 17:27:10 host sm-mta[50437]: 06QDQnNf050437: localhost [127.0.0.1] did not issue MAIL/EXPN/VRFY/ETRN during connection to IPv4
```

**Comment by sebres** [comment]
fixed in 07fa9f29129f53924f6850f01adeb8fb7c699060
