### ISSUE TITLE
Not all ban actions are logged

### ISSUE THREAD

**Issue by xciser77** [fail2ban/fail2ban#2788]
### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): 0.9.6
- OS, including release name/version: Red Hat Enterprise Linux Server release 6.10 (Santiago)
- [x] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
I have installed fail2ban to check the ammount of request that are made by ips. If there are to many request between a time period it should be banned and if this happens 3 times in a timeframe it should be banned longer.

The banning works, but the recidive doesnt works. After some searching I found that the banning is not always logged in de /var/etc/messages and because of that the recidive doesn't get to the count of three. This is part of the logging:
Jul 28 06:47:15 aserver fail2ban.actions[12265]: NOTICE [apache-ips] Unban 5.79.127.43
Jul 28 06:58:15 aserver fail2ban.actions[12265]: NOTICE [apache-ips] Unban 5.79.127.43
Jul 28 06:59:13 aserver fail2ban.actions[12265]: NOTICE [apache-ips] Ban 5.79.127.43
Jul 28 07:09:14 aserver fail2ban.actions[12265]: NOTICE [apache-ips] Unban 5.79.127.43
Jul 28 07:21:12 aserver fail2ban.actions[12265]: NOTICE [apache-ips] Unban 5.79.127.43
Jul 28 07:32:12 aserver fail2ban.actions[12265]: NOTICE [apache-ips] Unban 5.79.127.43
Jul 28 07:34:13 aserver fail2ban.actions[12265]: NOTICE [apache-ips] Ban 5.79.127.43
Jul 28 07:44:13 aserver fail2ban.actions[12265]: NOTICE [apache-ips] Unban 5.79.127.43
Jul 28 07:55:12 aserver fail2ban.actions[12265]: NOTICE [apache-ips] Unban 5.79.127.43

Here you can see the ban/unbun actions. Unban is always logged, but the ban actions isn't, bu the ip is banned because I get an email of the ban action and iptables also shows it blocked. But because it's only logged 2 ban actions, the recidive isn't kicked in.

### Configuration, dump and another helpful excerpts
[apache-ips]
enabled = true
port = http,https
filter = apache-ips
logpath = /var/logs/apache/fail2ban.txt
bantime = 600
findtime = 120
maxretry = 10000
action = %(action_mwl)s

[recidive]
enabled = true
logpath  = /var/log/messages
banaction = %(banaction_allports)s
bantime  = 259200 ; 3 days
findtime = 86400  ; 1 day
maxretry = 3

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
I never saw such behavior, also not in v.0.9.
But since 0.9.6 is outdated I have no intention to investigate our time into search for the reason or some fix.
Please upgrade your fail2ban version to 0.10 or 0.11.
