### ISSUE TITLE
Fail2ban not blocking user-agents with special characters.

### ISSUE THREAD

**Issue by rajshekarmsg** [fail2ban/fail2ban#2789]
We have configured fail2ban in Suse-Linux Environment and tested with some bots and it is working fine.  We are facing issue when we append some special characters to user-agents and it is not blocking.  Please find below regex configuration.

failregex = (?:\[\]\s+)?\<HOST> [^"]*"[^"]*" \d+ \d+ [^"]*"[^"]*\b(?:EmailCollector|DuckDuckBot/1\.0|Atomic_Email_Hunter/4\.0|atSpider/1\.0|WebEMailExtrac|TrackBack/1\.02|sogou music spider|Googlebot/2\.1)\b

It is blocking all the bots which is listed in regex but getting 200 response if we pass special characters in the user agent and it is not blocked by fail2ban.  Below is the sample user-agents which is not blocked by fail2ban.

DuckDuckBot%2f1%2e0%3b%20(%2bhttp%3a%2f%2fduckduckgo%2ecom%2fduckduckbot%2ehtml)
DuckDuckBot%2f2%2e0%3b%20(%2bhttp%3a%2f%2fduckduckgo%2ecom%2fduckduckbot%2ehtml)

**Comment by TorontoMedia** [comment]
To handle percent-encoded characters you could change the slashes to `(?:/|(?:%2[fF]))` and the periods to `(?:\.|(?:%2[eE]))`. 

So for an example your regex would be `(?:[]\s+)?<HOST> [^"]"[^"]" \d+ \d+ [^"]"[^"]\b(?:EmailCollector|DuckDuckBot(?:/|(?:%2[fF]))1(?:\.|(?:%2[eE]))0|Atomic_Email_Hunter(?:/|(?:%2[fF]))4(?:\.|(?:%2[eE]))0|atSpider(?:/|(?:%2[fF]))1(?:\.|(?:%2[eE]))0|WebEMailExtrac|TrackBack(?:/|(?:%2[fF]))1(?:\.|(?:%2[eE]))02|sogou music spider|Googlebot(?:/|(?:%2[fF]))2(?:\.|(?:%2[eE]))1)\b`

or you could optimize it to be `(?:[]\s+)?<HOST> [^"]"[^"]" \d+ \d+ [^"]"[^"]\b(?:EmailCollector|DuckDuckBot|Atomic_Email_Hunter|atSpider|WebEMailExtrac|TrackBack|sogou music spider|Googlebot)(?:(?:/|(?:%2[fF]))\d+(?:\.|(?:%2[eE]))\d+)?\b` and that would handle any one of those bots with or without a version number.

**Comment by rajshekarmsg** [comment]
It worked, thank you.

**Comment by TorontoMedia** [comment]
You're welcome, I glad it worked for you.
