### ISSUE TITLE
firewallcmd-ipset 'timeout' conflict

### ISSUE THREAD

**Issue by TorontoMedia** [fail2ban/fail2ban#2790]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 1.0.1.dev1
- OS, including release name/version: Fedora 32
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

The 'timeout' option in action firewallcmd-ipset.conf conflicts with the 'timeout' variable in the class CommandAction in action.py.

Since timeout is probably a common option you would see in an action, I say we rename the variable and all references to `CommandAction.timeout` to `CommandAction.execution_timeout`. Any other suggestions?

#### Steps to reproduce

Enable any jail with  `banaction = firewallcmd-ipset`.

#### Expected behavior

Successful execution of the command.

#### Observed behavior

Command `actionstart` times out after 0 seconds but if you change the timeout option in firewallcmd-ipset to a reasonable enough time to execute the command it finishes successfully. 

#### Relevant parts of /var/log/fail2ban.log file:

> 2020-07-28 19:23:10,755 fail2ban.utils          [87977]: ERROR   ffff8b12f230 -- exec: ipset create f2b-sshd hash:ip timeout 0
> firewall-cmd --direct --add-rule ipv4 filter INPUT_direct 0 -p tcp -m multiport --dports ssh -m set --match-set f2b-sshd src -j REJECT --reject-with icmp-port-unreachable
> 2020-07-28 19:23:10,756 fail2ban.utils          [87977]: ERROR   ffff8b12f230 -- timed out after 0 seconds.

**Comment by sebres** [comment]
Hmm... Related to [ipset-documentation](https://ipset.netfilter.org/ipset.man.html#lbAJ) timeout 0 means persistent entry.
Because since fail2ban v.0.11 the `bantime` is dynamic (due to incremental banning), to completely exclude the issues like #2670 which may occur because of deviation by the retarded prolongation, time adjustment or some drifts etc, the handling gets rewritten now (see #2703), so the fail2ban alone manages now the banning entries, without to handle it in ipset, no expiration by timeout.

Does not Fedora 32 support this parameter in ipset? Or does it not mean permanent there? 
Can you please check the man of ipset there?
> Zero timeout value means the entry is added permanent to the set.

**Comment by TorontoMedia** [comment]
Ipset zero timeout is supported in Fedora.

The issue is that the timeout option in firewallcmd-ipset.conf and I assume other actions: https://github.com/fail2ban/fail2ban/blob/78fc99ec7ee8185fe478091a21655a6a400bae09/config/action.d/firewallcmd-ipset.conf#L53 is overwriting the timeout variable in CommandAction: https://github.com/fail2ban/fail2ban/blob/78fc99ec7ee8185fe478091a21655a6a400bae09/fail2ban/server/action.py#L458

so executeCmd is being called with a timeout of 0 which result in these errors:
````
2020-08-03 11:19:39,524 fail2ban.utils          [128429]: ERROR   ffff8a7d5be0 -- exec: ipset create f2b-sshd hash:ip timeout 0
firewall-cmd --direct --add-rule ipv4 filter INPUT_direct 0 -p tcp -m multiport --dports ssh -m set --match-set f2b-sshd src -j REJECT --reject-with icmp-port-unreachable
2020-08-03 11:19:39,525 fail2ban.utils          [128429]: ERROR   ffff8a7d5be0 -- timed out after 0 seconds.
2020-08-03 11:19:39,727 fail2ban.utils          [128429]: ERROR   ipset create f2b-sshd hash:ip timeout 0
firewall-cmd --direct --add-rule ipv4 filter INPUT_direct 0 -p tcp -m multiport --dports ssh -m set --match-set f2b-sshd src -j REJECT --reject-with icmp-port-unreachable -- failed with [Errno 3] No such process
2020-08-03 11:19:39,729 fail2ban.utils          [128429]: ERROR   ffff8a7d5be0 -- killed with SIGTERM (return code: -15)
````

**Comment by sebres** [comment]
Oh... the names conflict. I'll take a closer look. Thx!

**Comment by sebres** [comment]
Merge in 9100d07c039a5fed978b0bc5280568c95c3aff50 to 0.10, I'll merge it in 0.11 / 1.0 later

**Comment by TorontoMedia** [comment]
> Oh... the names conflict. I'll take a closer look. Thx!

No problem, thank you for taking a look and fixing the issue.
