### ISSUE TITLE
Ssh login errors are not picked up when using a namespace

### ISSUE THREAD

**Issue by xupwup** [fail2ban/fail2ban#2793]
### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): v0.11.1
- OS, including release name/version:  Archlinux, kernel 5.7.9-arch1-1
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

When using a logging namespace for sshd, fail2ban no longer picks up the logs. The result is that no new IPs will be banned.

#### Steps to reproduce
Configure sshd.service like this:

```
  [Service]
  LogNamespace=ssh
```

Logs from ssh are then viewable with `journalctl --namespace ssh`

#### Expected behavior

Fail2ban still bans after x failed login attempts

#### Observed behavior

Fail2ban does not act upon failed login attempts anymore.

**Comment by TorontoMedia** [comment]
You can add the journal field `_NAMESPACE=ssh` to the filters `journalmatch` parameter using one of three ways mentioned here https://github.com/fail2ban/fail2ban/issues/2520#issuecomment-530086101 and here https://github.com/fail2ban/fail2ban/issues/2520#issuecomment-530410518.

So for an example in `jail.local' under your jail definition you could do:

`filter = sshd[journalmatch="_SYSTEMD_UNIT=sshd.service + _COMM=sshd + _NAMESPACE=ssh"]`

or if supported:

`journalmatch= _SYSTEMD_UNIT=sshd.service + _COMM=sshd + _NAMESPACE=ssh`

**Comment by xupwup** [comment]
I've edited jail.d/sshd.local, and added the journalmatch line. I've tried a few things:

-  journalmatch = _SYSTEMD_UNIT=sshd.service + _COMM=sshd + _NAMESPACE=ssh
-- /var/log/fail2ban.log shows messages like "found..." corresponding to logs in `journalctl`. (Note: just callling `journalctl` only shows messages from the default namespace)
-  journalmatch = _SYSTEMD_UNIT=sshd.service + _NAMESPACE=ssh
-- /var/log/fail2ban.log shows messages like "found..." corresponding to logs in `journalctl`
-  journalmatch = _SYSTEMD_UNIT=sshd.service + _COMM=sshd
-- /var/log/fail2ban.log shows messages like "found..." corresponding to logs in `journalctl`
-  journalmatch = _NAMESPACE=ssh
-- /var/log/fail2ban.log only shows "restore ban"

So all in all, it seems that the _NAMESPACE property has no effect.

It does show this in the logs though:
INFO    [sshd] Added journal match for: '_SYSTEMD_UNIT=sshd.service + _COMM=sshd + _NAMESPACE=ssh'

**Comment by TorontoMedia** [comment]
Sorry I forgot the systemd backend will load the system journal file by default, so depending on how systemd is configured the namespace 'ssh' journal file might be in `/var/log/journal` or `/run/log/journal` and you can tell the systemd backend to load that journal file with the `journalfiles` parameter.

So for an example in your jail definition you can do:
````
[sshd]
backend = systemd[journalfiles="/var/log/journal/*.ssh"]
````

**Comment by xupwup** [comment]
That nearly worked. I've adjusted it to:
```
backend = systemd[journalfiles="/var/log/journal/*.ssh/*"]
```

This works!

**Comment by TorontoMedia** [comment]
No problem, there's also the `journalpath` parameter that might work too.
