### ISSUE TITLE
IPs are detected by recidive and added to iptabels, but are completely ignored

### ISSUE THREAD

**Issue by InvisibleKind** [fail2ban/fail2ban#2797]
Hello,

I'm facing strange issue since last update of Debian from 10.4 to 10.5.

Fail2ban is able to detect evil clients and block them in corresponding jails, but somehow it doesn't work for a recidive jail.

A live example: an IP 212.70.149.35  is getting multiple times to _exim-iptables_ jail. I've got already 87 email since yesterday, that this IP is blocked by the jail.

This IP get's successfully blocked by exim-iptables jail for 10 minutes, but somehow doesn't get blocked by recidive. Well, in fact it gets blocked, but still is able to access the system. See below an explanation:

If I check the logs to find out, if it was catched by recidive:
`cat /var/log/fail2ban.log | grep "recidive.* 212.70.149.35"`

I see this:

> ***CUT***
> 2020-08-05 08:14:21,362 fail2ban.actions        [506]: WARNING [recidive] 212.70.149.35 already banned
> 2020-08-05 08:25:57,779 fail2ban.filter         [506]: INFO    [recidive] Found 212.70.149.35 - 2020-08-05 08:25:57
> 2020-08-05 08:37:18,240 fail2ban.filter         [506]: INFO    [recidive] Found 212.70.149.35 - 2020-08-05 08:37:18
> 2020-08-05 08:48:41,191 fail2ban.filter         [506]: INFO    [recidive] Found 212.70.149.35 - 2020-08-05 08:48:41
> 2020-08-05 08:59:50,241 fail2ban.filter         [506]: INFO    [recidive] Found 212.70.149.35 - 2020-08-05 08:59:50
> 2020-08-05 09:11:14,530 fail2ban.filter         [506]: INFO    [recidive] Found 212.70.149.35 - 2020-08-05 09:11:14
> 2020-08-05 09:11:14,893 fail2ban.actions        [506]: WARNING [recidive] 212.70.149.35 already banned
> 2020-08-05 09:22:31,598 fail2ban.filter         [506]: INFO    [recidive] Found 212.70.149.35 - 2020-08-05 09:22:31
> 2020-08-05 09:33:46,857 fail2ban.filter         [506]: INFO    [recidive] Found 212.70.149.35 - 2020-08-05 09:33:46
> 2020-08-05 09:45:07,664 fail2ban.filter         [506]: INFO    [recidive] Found 212.70.149.35 - 2020-08-05 09:45:07
> 2020-08-05 09:56:45,891 fail2ban.filter         [506]: INFO    [recidive] Found 212.70.149.35 - 2020-08-05 09:56:45
> 2020-08-05 10:08:17,159 fail2ban.filter         [506]: INFO    [recidive] Found 212.70.149.35 - 2020-08-05 10:08:17
> 2020-08-05 10:08:17,599 fail2ban.actions        [506]: WARNING [recidive] 212.70.149.35 already banned
> 2020-08-05 10:19:34,233 fail2ban.filter         [506]: INFO    [recidive] Found 212.70.149.35 - 2020-08-05 10:19:34
> 2020-08-05 10:30:43,419 fail2ban.filter         [506]: INFO    [recidive] Found 212.70.149.35 - 2020-08-05 10:30:43
> 2020-08-05 10:42:21,597 fail2ban.filter         [506]: INFO    [recidive] Found 212.70.149.35 - 2020-08-05 10:42:21

And, yes  I see the IP in list if blocked by recidive:
`fail2ban-client status recidive`

> Status for the jail: recidive
> |- Filter
> |  |- Currently failed:	1
> |  |- Total failed:	91
> |  `- File list:	/var/log/fail2ban.log
> `- Actions
>    |- Currently banned:	12
>    |- Total banned:	12
>    `- Banned IP list:	212.70.149.35 91.191.209.132 91.191.209.142 91.191.209.153 91.191.209.188 91.191.209.190 91.191.209.193 91.191.209.203 91.191.209.37 91.191.209.47 91.191.209.72 91.191.209.94

And I can see it in iptables:
`iptables -L -v -n`

> Chain INPUT (policy DROP 35403 packets, 5211K bytes)
>  pkts bytes target     prot opt in     out     source               destination
> 43008   12M fail2ban-SSH  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22
>  1151  302K fail2ban-VESTA  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8083
> 13707  812K fail2ban-MAIL  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 25,465,587,2525,110,995,143,993
>  135K   85M ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED
>   399 23940 ACCEPT     all  --  *      *       37.120.187.163       0.0.0.0/0
>  1599 95940 ACCEPT     all  --  *      *       127.0.0.1            0.0.0.0/0
>  2137  122K ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22
>   682 36026 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 80,443
>  1091 55196 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 21,12000:12100
>   538 40501 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:53
>   187  8084 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:53
>   484 27884 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 25,465,587,2525
>    53  2708 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 110,995
>    65  3284 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 143,993
>    52  3132 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8083
>   580 45066 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0
> 
> Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
>  pkts bytes target     prot opt in     out     source               destination
> 
> Chain OUTPUT (policy ACCEPT 184K packets, 258M bytes)
>  pkts bytes target     prot opt in     out     source               destination
> 
> Chain fail2ban-SSH (1 references)
>  pkts bytes target     prot opt in     out     source               destination
> 42749   12M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0
> 
> Chain fail2ban-VESTA (1 references)
>  pkts bytes target     prot opt in     out     source               destination
>  1151  302K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0
> 
> Chain fail2ban-MAIL (1 references)
>  pkts bytes target     prot opt in     out     source               destination
>    74  3990 REJECT     all  --  *      *       212.70.149.35        0.0.0.0/0            reject-with icmp-port-unreachable
>  8419  512K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0
> 
> Chain f2b-sshd (0 references)
>  pkts bytes target     prot opt in     out     source               destination
>     0     0 REJECT     all  --  *      *       5.101.107.190        0.0.0.0/0            reject-with icmp-port-unreachable
>     0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0
> 
> Chain vesta (0 references)
>  pkts bytes target     prot opt in     out     source               destination
> 
> Chain f2b-recidive (0 references)
>  pkts bytes target     prot opt in     out     source               destination
>     0     0 REJECT     all  --  *      *       91.191.209.94        0.0.0.0/0            reject-with icmp-port-unreachable
>     0     0 REJECT     all  --  *      *       91.191.209.72        0.0.0.0/0            reject-with icmp-port-unreachable
>     0     0 REJECT     all  --  *      *       91.191.209.47        0.0.0.0/0            reject-with icmp-port-unreachable
>     0     0 REJECT     all  --  *      *       91.191.209.37        0.0.0.0/0            reject-with icmp-port-unreachable
>     0     0 REJECT     all  --  *      *       91.191.209.203       0.0.0.0/0            reject-with icmp-port-unreachable
>     0     0 REJECT     all  --  *      *       91.191.209.193       0.0.0.0/0            reject-with icmp-port-unreachable
>     0     0 REJECT     all  --  *      *       91.191.209.190       0.0.0.0/0            reject-with icmp-port-unreachable
>     0     0 REJECT     all  --  *      *       91.191.209.188       0.0.0.0/0            reject-with icmp-port-unreachable
>     0     0 REJECT     all  --  *      *       91.191.209.153       0.0.0.0/0            reject-with icmp-port-unreachable
>     0     0 REJECT     all  --  *      *       91.191.209.142       0.0.0.0/0            reject-with icmp-port-unreachable
>     0     0 REJECT     all  --  *      *       91.191.209.132       0.0.0.0/0            reject-with icmp-port-unreachable
>   569 34140 REJECT     all  --  *      *       212.70.149.35        0.0.0.0/0            reject-with icmp-port-unreachable
> 45800   86M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

So in output below, the IP is still banned by chain fail2ban-MAIL chain, but as soon as it is released, the f2b-recidive chain doesn't block it anymore, although it is still there.

The one thing, that I see different:
> Chain fail2ban-MAIL (1 references)
vs
> Chain f2b-recidive (0 references)

But I don't have a clue, what to do with it to fix it. Probably it should be in INPUT chain, but I'd expect fail2ban to add it automatically without my explicit interaction.

Any ideas on it?

**Comment by sebres** [comment]
You seem to have a very strange constellation in iptables: some chains are called `f2b-*`, but some others `fail2ban-*` (very old, some 0.9.x version).
Thereby no one chain of `f2b-*` is referenced in INPUT chain, so it is pretty clear why it does not work, but not clear what exactly has caused that.
Please stop fail2ban, remove all iptables rules for chains starting with `f2b-` and `fail2ban-` and start fail2ban again.

**Comment by InvisibleKind** [comment]
Thank you @sebres 
your solution worked, after I removed the mentioned iptables rules, the recidive chain was added to INPUT and now working again.
