### ISSUE TITLE
Duplicate sqlite files

### ISSUE THREAD

**Issue by compata** [fail2ban/fail2ban#2801]
I have two machines, each installed recently and both running Fedora 32. Each has the package fail2ban-0.11.1-9.fc32.noarch installed and no local configuration changes have been applied. On one of the machines, performing "systemctl restart fail2ban" works as expected. On the other, it almost works exactly the same way except that the file /var/lib/fail2ban/fail2ban.sqlite3 is duplicated into a new file /var/lib/fail2ban/fail2ban.sqlite3.$date.$time (where $date and $time are values representing when the restart occurred). I can't find any difference in any conf file nor in the systemd service file. I must avoid this unnecessary duplication to prevent repeated restarts from chewing up a huge pile of storage. What could account for this difference?

**Comment by sebres** [comment]
Fail2ban seems to try an upgrade or repair of sqlite-database for some reason (see fail2ban.log for more info).
If it is not successful either the database is corrupt or it is too large.
See an answer https://github.com/fail2ban/fail2ban/issues/2796#issuecomment-668021423 for similar issue.
