### ISSUE TITLE
Release signing public key

### ISSUE THREAD

**Issue by xlumen** [fail2ban/fail2ban#2806]
The tar releases on Github are accompanied by an .asc signature file. I have been searching for a corresponding public key with which to verify the releases but could not fine one. Could you put the public key on the fail2ban.org website and Github or point me to it in case it is already there?

**Comment by sebres** [comment]
You can always find the public key on common public key servers (e.g. OpenPGP keyserver) by name or IDs:
http://keys.gnupg.net/pks/lookup?search=sebres&fingerprint=on&op=index
http://keys.gnupg.net/pks/lookup?search=0xBD0A882C&fingerprint=on&op=index
http://keys.gnupg.net/pks/lookup?search=0x683BF1BEBD0A882C&fingerprint=on&op=index

Also if you don't have a public key, the fingerprint of signing key is showing if you'll try to check the signature:
```
$  gpg --verify fail2ban-0.10.5.tar.gz.asc fail2ban-0.10.5.tar.gz
gpg: Signature made Fri 10 Jan 2020 01:44:34 PM CET
gpg:                using RSA key 8738559E26F671DF9E2C6D9E683BF1BEBD0A882C
gpg: Can't check signature: No public key
```
The short ID are last 8 letter, the long ID are last 16 letter of fingerprint (lower 32 respective 64 bits of the fingerprint):
```
Fingerprint: 8738 559E 26F6 71DF 9E2C 6D9E 683B F1BE BD0A 882C
Long ID:                                0x 683B F1BE BD0A 882C
Short ID:                                         0x BD0A 882C
```

Anyway, this is a public key used by signing of releases - http://keys.gnupg.net/pks/lookup?op=get&search=0x683BF1BEBD0A882C
