### ISSUE TITLE
Suitable log level for recidive filter? 

### ISSUE THREAD

**Issue by utags** [fail2ban/fail2ban#2812]
In my VPS i keep separate log file for Fail2Ban and it   rotate every week. Normally my log file over 20MB. Currently my VPS Fail2Ban log level is info. 

I use Fail2Ban Recidive filter to ban repeated offenders. I use recidive filter find time 7 days. 

In order to keep Fail2Ban log file small and use recidive filter which log level should I use?

**Comment by sebres** [comment]
Level NOTICE is enough for recidive jail.
