### ISSUE TITLE
Zimbra sendmail

### ISSUE THREAD

**Issue by Copyrght** [fail2ban/fail2ban#2823]
Hi. I cant setup mail notification for zimbra server. Maybe you can help me. There is some of my settings

jail.conf

[zimbra-account]
enabled = true
filter = zimbra
action = iptables-allports[name=Zimbra-account]
sendmail[name=Zimbra-account, dest=email@domain.com]
logpath = /opt/zimbra/log/mailbox.log
bantime = 600
maxretry = 5

sendmail.conf

actionban = printf %%b "Subject: [Fail2Ban] <name>: banned <ip> from `uname -n`
Date: `LC_ALL=C date +"%%a, %%d %%h %%Y %%T %%z"`
From: <sendername> <<sender>>
To: <dest>\n
Hi,\n
The IP <ip> has just been banned by Fail2Ban after
<failures> attempts against <name>.\n
Regards,\n
Fail2Ban" | /opt/zimbra/common/sbin/sendmail -f <sender> <dest>

**Comment by sebres** [comment]
Space is mandatory (as continuation of multi-line parameter).
So if you don't have a space before sendmail, add it like here:
```diff
 action = iptables-allports[name=Zimbra-account]
-sendmail[name=Zimbra-account, dest=email@domain.com]
+         sendmail[name=Zimbra-account, dest=email@domain.com]
```
Also see how it is specified by mail actions
https://github.com/fail2ban/fail2ban/blob/ed20d457b21d298cf8a8569ab2eb09546e8065c4/config/jail.conf#L194-L195

Same is valid for actionban in action-conf.
https://github.com/fail2ban/fail2ban/blob/ed20d457b21d298cf8a8569ab2eb09546e8065c4/config/action.d/sendmail.conf#L22-L30

**Comment by Copyrght** [comment]
Ok. This working, but there is another problem. I found in logs error: 
"error while loading shared libraries: libcrypto.so.1.0.0: "cannot enable executable stack as shared object requires: Permission denied"

When i run sendmail commannd in console, mail is sending, but when its runs from fail2ban i got this error in logs. I have libcrypto/libssl 1.0.1e

**Comment by sebres** [comment]
> `error while loading shared libraries: libcrypto.so.1.0.0`
> When i run sendmail commannd in console, mail is sending, but when its runs from fail2ban i got this error in logs.

Running fail2ban as service surely uses different set of environment values as if you'd start it from console. So check and add expected path (e. g. PATH or LD_LIBRARY_PATH).
Also note for similar issue - https://askubuntu.com/questions/1116133/ubuntu-18-04-libcrypto-so-1-0-0-cannot-open-shared-object-file-no-such-file-o
