### ISSUE TITLE
No easy documentation for adding custom actions.

### ISSUE THREAD

**Issue by nickwebcouk** [fail2ban/fail2ban#2826]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): 10.2
- OS, including release name/version: Linux 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

My issue isn't a problem with the application - that works,. May issue is that there does not appear to be an easy way to view and add custom actions.

I have tried to look at the actions.d folder in addition to the jail.conf and I have no idea what's happening. In my mind, I should be able to add an acitonban setting that calls a system command, seeing as thats what happens when it ban's IP's.

I've tried to read the documentation at https://www.fail2ban.org/wiki/index.php/Manual but this references only 0.8, with a notice in the jail.conf file staing

```
# WARNING: heavily refactored in 0.9.0 release.  Please review and
#          customize settings for your setup.
```

I am running fail2ban 10.2.

From the main wiki page the Google+ and Google+ Fail2Ban Users Community both don't appear to exist any more.

The Mailinglist looks like it wants to sign me up for sourcefourge marketing emails which I am not ok with. This leaves me with here. I know github isn't really the place for asking these questions but I just don't know what to do.

I also checked under https://www.fail2ban.org/wiki/index.php/HOWTO_Seek_Help and went into the IRC room. I received a reply just asking me to check out https://github.com/fail2ban/fail2ban/blob/master/config/action.d/badips.conf which I did, but seeing as that also includes a python script that confused me even more!

In its default state, fail2ban runs perfectly. I want to extend what this does by adding a simple custom action each time an IP has been banned. I don't care about it being unbanned, or watched, or whatever, simply banned.

I have created a separate jail.local file where I have added in the following

```[sshd]
enabled = true
filter = sshd
logpath = /var/log/auth.log
port = ssh
actionban = curl --fail http://xx.xx/ban.php
```

however this does not invoke the curl command. What am I meant to do? IS there a new doc library that explains how to add custom actions anywhere? Can someone point me in the rough direction?

#### Steps to reproduce

add custom actionban and observe it not being called

#### Expected behavior

to call actionban without having to modify bundled files

#### Any customizations done to /etc/fail2ban/ configuration

as above
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
As for docu, please read [man for jail](https://manpages.debian.org/experimental/fail2ban/jail.conf.5.en.html)

Back to this - it's impossible to specify new action (or single attributes) directly in jail section (in `jail.local`) - you have to set an action name(s), which you'd have in `action.d` directory.

If you want to set other banning action, you can set `banaction` in `jail.local` (overwrites default set in `jail.local` default section or some includes):
```ini
[sshd]
enabled = true
banaction = my-action[my-host="some-host.example.com"]
```
if you need rather to add some action (additionally to banning action), use `action` parameter, take a look how it is defined in default section, for example:
```ini
[sshd]
enabled = true
action = %(action_)s
         my-action[my-host="some-host.example.com", some-other-parameter="some-value"]
```
so it will ban with default action and call your custom action hereafter.
(Note that space(s) before name of action are mandatory here).

And then create action file with same name (`/etc/fail2ban/action.d/my-action.conf` or `.local`) and define your action config there:
```ini
[Definition]
# sends get request like "http://example.com/ban.php?jail=sshd&ip=192.0.2.100&user=bad%20hacker":
actionban = curl -G --data-urlencode "jail=%(name)s" --data-urlencode "ip=<ip>" --data-urlencode "user=<F-USER>" --fail "http://<my-host>/ban.php"
# sends get request like "http://example.com/unban.php?jail=sshd&ip=192.0.2.100":
actionunban = curl -G --data-urlencode "jail=%(name)s" --data-urlencode "ip=<ip>" --fail "http://<my-host>/unban.php"

[Init]
# overwrite this in jail as action parameter:
my-host = 127.0.0.1
```

For other examples with curl you can search for [curl and action](https://github.com/fail2ban/fail2ban/search?q=curl+filename%3A.conf&type=code).

> I received a reply just asking me to check out `action.d/badips.conf` which I did, but seeing as that also includes a python script that confused me even more!

Huh? Did you mean `action.d/badips.py`? It is totally another (pythonic) action and basically has nothing to do with `badips.conf`.
Fail2ban supports both types of action (command action as conf-file and pythonic action as py-file and use `action = my-action.py` syntax).

**Comment by nickwebcouk** [comment]
Perfect. I think you've just helped me tremendously! I'll write up a quick blog post at some point but you've certainly made it clearer.

Thanks again!
