### ISSUE TITLE
Documentation Nit: HTTP 502 'Bad Gateway' for 2016 slide deck

### ISSUE THREAD

**Issue by MandyBaxter** [fail2ban/fail2ban#2827]
#2217 # The issue:
https://fri-software-days.ch/images/2016/archive/Presentation_Fri_Software_Days_2016_Jaquier.pdf
gets
502 Bad Gateway
nginx/1.10.3 (Ubuntu)

_Summary here_

#### Steps to reproduce
Point browser, pull trigger.

#### Expected behavior
Receipt of a PDF'd slide deck, relayed via the http proxy from some other http server.

#### Observed behavior
502 Bad Gateway

**Comment by MandyBaxter** [comment]
Ah. Forgot to mention -- the wiki has this link at
https://www.fail2ban.org/wiki/index.php/Presentations

**Comment by sebres** [comment]
let us avoid duplicates and handle this in #2580
