### ISSUE TITLE
Docker - cannot open smtp.gmail.com

### ISSUE THREAD

**Issue by truncsphere** [fail2ban/fail2ban#2835]
_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): 0.11.1
- OS, including release name/version:  Docker v 19.03.12
- [x ] Fail2Ban installed via OS/distribution mechanisms
- [x ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Email notifications are no longer working. These stopped working about 2 months ago (haven't been able to troubleshoot yet). 

#### Steps to reproduce
Docker compose:

> version: '2'
> services:
>   fail2ban:
>     image: crazymax/fail2ban:latest
>     container_name: fail2ban
>     network_mode: "host"
>     restart: unless-stopped
>     cap_add:
>     - NET_ADMIN
>     - NET_RAW
>     volumes:
>     - /var/log:/var/log:ro
>     - /docker/fail2ban/data:/data
>     environment:
>     - TZ=America/Los_Angeles
>     - F2B_MAX_RETRY=3
>     - F2B_DEST_EMAIL=someemail@gmail.com
>     - F2B_SENDER=someemail@gmail.com
>     - F2B_ACTION=%(action_mw)s
>     - SSMTP_HOST=smtp.gmail.com
>     - SSMTP_PORT=587
>     - SSMTP_HOSTNAME=smtp.gmail.com
>     - SSMTP_USER=someemail@gmail.com
>     - SSMTP_PASSWORD=********
>     - SSMTP_TLS=YES

#### Expected behavior

- Email when Fail2Ban is restarted
- Email when a new ban occurred

#### Observed behavior
Log file: 

> Fail2Ban" | /usr/sbin/sendmail -f "root@docker01" "root@localhost"
> 
> 
> 2020-09-25 10:22:35,305 fail2ban.utils          [1]: ERROR   7f5c070e12f0 -- stderr: 'SSL_connect: No error information'
> 
> 
> 2020-09-25 10:22:35,305 fail2ban.utils          [1]: ERROR   7f5c070e12f0 -- stderr: 'sendmail: Cannot open smtp.gmail.com:587'
> 
> 
> 2020-09-25 10:22:35,305 fail2ban.utils          [1]: ERROR   7f5c070e12f0 -- returned 1
> 
> 
> 2020-09-25 10:22:35,305 fail2ban.actions        [1]: ERROR   Failed to start jail 'traefik-auth' action 'sendmail-whois': Error starting action Jail('traefik-auth')/sendmail-whois: 'Script error'

#### Any additional information
No configuration changes occurred from when it used to work till now. 

#### Any customizations done to /etc/fail2ban/ configuration
```
N/A
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```

```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
> stderr: 'SSL_connect: No error information'
> stderr: 'sendmail: Cannot open smtp.gmail.com:587'

This is not a matter of fail2ban, but rather of sendmail (configuration of that, or of the action).

You can also try to do it same command from the shell:
```
echo "... Fail2Ban" | /usr/sbin/sendmail -f "root@docker01" "root@localhost"
```
I have no idea why it does not work for you. Either fix it for sendmail, or switch mailing action to something what is working on your system.
