### ISSUE TITLE
action.d/bsd-ipfw.conf: shell return values may no be larger than 255, so selection of rule-no fails

### ISSUE THREAD

**Issue by czauner-privat** [fail2ban/fail2ban#2836]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): py37-fail2ban-0.11.1_1
- OS, including release name/version: FreeBSD 12.1-RELEASE-p10 GENERIC  amd64
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

Yes, but not relevant for the issue.

### The issue:

the provided action.d/bsd-ipfw.conf tries to select the ipfw - rule number as the next free 
rule-number after the provided <lowest_rule_num>. This is done by ask'ing through the 
output of `ipfw show`. The next free number b is returned via `exit b`. And then read back 
via `num=$?`.

**Problem:** shell return values may not be larger than 255. ipfw rule-numbers can be larger,
and often are. The code produces somehow unexpected results for lowest_rule_num > 255.

#### Steps to reproduce

Just set up any jail, using bsd-ipfw for instance:
`action = bsd-ipfw[port="80,443",block="tcp",table="80",lowest_rule_num="50000",blocktype="deny"]`

#### Expected behavior

Should result in an ipfw-entry looking like: 
[ipfw show output, given that 50000 was available]
`50000     6     360 deny tcp from table(80) to me 80,443`

#### Observed behavior

[ipfw show output, given that 50000 was available]
`80           0          0 deny tcp from table(80) to me 80,443`

=> the '80' in the first row is a result of 50000 mod 256

#### Any additional information

**Solution:** 'print' the found numbers, an read that back. 

so instead of:
`actionstart = ipfw show | fgrep -c -m 1 -s 'table(<table>)' > /dev/null 2>&1 || ( ipfw show | awk 'BEGIN { b = <lowest_rule_num> } { if ($1 < b) {} else if ($1 == b) { b = $1 + 1 } else { e = b } } END { if (e) exit e  else exit b }'; num=$?; ipfw -q add $num <blocktype> <block> from table\(<table>\) to me <port>; echo $num > "<startstatefile>" )`

use:
`actionstart = ipfw show | fgrep -c -m 1 -s 'table(<table>)' > /dev/null 2>&1 || ( num=$( ipfw show | awk 'BEGIN { b = <lowest_rule_num> } { if ($1 < b) {} else if ($1 == b) { b = $1 + 1 } else { e = b } } END { if (e) { print e } else { print  b } }'); ipfw -q add $num <blocktype> <block> from table\(<table>\) to me <port>; echo $num > "<startstatefile>" )`

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
Fixed in 1418bcdf5bb01dd210f4d37b5c2de8ccd0c658e4.
Thx!
