### ISSUE TITLE
PID file needs relocation for 'most distros'

### ISSUE THREAD

**Issue by egberts** [fail2ban/fail2ban#2839]
### Environment:

- Fail2Ban version: 0.10.2-2.1
- OS, including release name/version: 
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

The PID file is moving to `/run` from `/var/run` throughout the Unix ecosystem.

#### Any additional information

I think this is the direction that many distros are taking when creating the PID and socket files which is to put them under `/run/<daemon>` subdirectory.  Debian has converted nearly 90% of their daemons; RedHat has started.  Gentoo too.  Suse, as well.

One downside of using tmpfile.d approach with `/run/fail2ban` would get deleted after a reboot.    

So, [FreeDesktop](https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html) has this to say:
> System daemons frequently require private runtime directories below /run to store communication sockets and similar. For these, it is better to use `RuntimeDirectory=` in their unit files (see systemd.exec(5) for details), if the flexibility provided by `tmpfiles.d` is not required.

So, there is this systemd's `RuntimeDirectory=` option.  As long as we do not have complicated sub-subdirectory under `/run/fail2ban`, we can use systemd's `RuntimeDirectory=fail2ban` setting to easily auto-create this `/run/fail2ban` subdirectory (as needed) with proper file permissions, but this would still require separate packaging for non-systemd platform.

The new `fail2ban.service.in` would have:
```ini
[Service]

Type=simple

StandardInput=null
StandardOutput=journal
StandardError=journal
EnvironmentFile=-/etc/default/fail2ban

# Relaxed security settings
Group=fail2ban
RuntimeDirectory=fail2ban
RuntimeDirectoryMode=0755

ExecStart=@SBINDIR@/fail2ban-server ${FAIL2BAN_OPT} -xf start
# if should be logged in systemd journal, use following line or set logtarget to sysout in fail2ban.local
# ExecStart=@SBINDIR@/fail2ban-server -${FAIL2BAN_OPT} xf --logtarget=sysout start

ExecStop=@BINDIR@/fail2ban-client stop
ExecReload=@BINDIR@/fail2ban-client reload

PIDFile=/run/fail2ban/fail2ban.pid

Restart=on-failure
RestartPreventExitStatus=0 255
```

### Alternative Security Settings
Assuming that there exist a user with a user ID of `fail2ban` (we block that  via /bin/nologin in /etc/passwd), 

* this user ID (either by file permission or supplemental group ID) cannot have write privilege to any of its files, so all config files and script are user-root-owned and 
* that `fail2ban` group ID is used only for socket communication or read-only of configuration files...

#### Permission by File Permission Only
```ini
Group=fail2ban
RuntimeDirectory=fail2ban
#RuntimeDirectoryMode=0755
```

#### Permission by Group Supplementary ID
For user having `fail2ban` group supplementary ID (adding a user to /etc/group):
```
Group=fail2ban
RuntimeDirectory=fail2ban
RuntimeDirectoryMode=0750  # major change here
```
-----
Note: Assigning fail2ban user to Python script isn't all that beneficial. Group, yes.
```
User=
```

**Comment by sebres** [comment]
as for relocation /var/run to /run, there were already several issues (like #2174), which all have been already solved and released in new version (0.10.2 is just too old).

as for RuntimeDirectory, see PR #2537 which provide that, so may be this PR should be extended instead of this new issue.
If it's so, let us avoid duplicates, and then close it here and request changes on that PR, please.

**Comment by sebres** [comment]
OK, so let us remain at PR #2537.

**Comment by egberts** [comment]
I'm surprised that fail2ban.service failed in latest master due to lack of a man page.

```init
[Unit]
...
Documentation=man:fail2ban(1)
```

Further confirmed by:
```bash
systemd-analyze verify fail2ban.service 
```
reporting
```console
fail2ban.service: Command 'man fail2ban(1)' failed with code 16
```

Easily fixed  by copying the `fail2ban/man` to `/usr[/local]/man`:
```bash
cp fail2ban/man/*.1 /usr/local/man/man1/
cp fail2ban/man/*.5 /usr/local/man/man5/
```

**Comment by sebres** [comment]
Indeed, the core fail2ban setup does not install man pages... 
I'll see whether it should be changed per default (will install it) or we'll need an entry in readme etc describing the current behavior.
