### ISSUE TITLE
Consider supporting/switching to use regex module instead of standard re

### ISSUE THREAD

**Issue by yarikoptic** [fail2ban/fail2ban#284]
Well, I got intrigued by http://www.debuggex.com/ and thought if would have been cool if we could troubleshoot regexes there when needed.  But ATM it supports only JavaScript and PCRE (perl) regular expressions and we do seems to use a subset of Python re features incompatible with PCRE (e.g. ```(?P<name>...)```).  So I have ran into http://stackoverflow.com/a/7066413/1265472 which outlined problems with unicode support in stock ```re``` module and recommending https://pypi.python.org/pypi/regex altogether.

On a quick thought it seems we do not rely much on anything related for mentioned unicode matching, so I am not sure if such a switch altogether is warranted, but just wanted to leave this comment for future references.

**Comment by leeclemens** [comment]
"Debuggex will not stay free." no real value in moving from Pythons core regex, imho, as if that statement about cost/licensing wasn't enough. Closing.
