### ISSUE TITLE
Incomplete 2to3 transition: ConfigParser package got renamed

### ISSUE THREAD

**Issue by egberts** [fail2ban/fail2ban#2853]
### Environment:
- Fail2Ban version (including any possible distribution suffixes): 11.0
- OS, including release name/version: Debian 10.5
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Just pulled the latest master "11.0" and got missing `ConfigParser` when working with Python 3.7.

Turns out that there is some more 2to3 work that needs to be done, notably with ConfigParser module.

#### Expected behavior

Runs cleanly without Python3  missing `ConfigParser` module.

#### Any additional information

Python doc says:
> The ConfigParser module has been renamed to configparser in Python 3. The 2to3 tool will automatically adapt imports when converting your sources to Python 3. You can use this to write Python programs which can be customized by end users easily. 

* https://docs.python.org/2/library/configparser.html  (read first-line)
* https://docs.python.org/3.8/library/configparser.html  (notice  all-lowercase)

Some say that this Python code snippet will ensure continual Python2 and Python  3 operation.
```python
if sys.version_info[0] == 2:
    import ConfigParser as configparser
else:
    import configparser
```

**Comment by egberts** [comment]
Has a backported python-configparser-3.5.0b2-1 which has done the renaming of the ConfigParser module.

**Comment by egberts** [comment]
http://python-future.org/automatic_conversion.html#stage-1-safe-fixes

**Comment by sebres** [comment]
> Turns out that there is some more 2to3 work that needs to be done, notably with ConfigParser module.

How you think it works in our test-suite, e. g. see related Travis build - https://travis-ci.org/github/fail2ban/fail2ban
I also cannot reproduce that, so I guess something is wrong with your setup (please provide what you're doing exactly).
Basic installation sequence with python 3.x:
```bash
# git clone https://github.com/fail2ban/fail2ban.git
cd fail2ban
./fail2ban-2to3
sudo python3 setup.py install
```
