### ISSUE TITLE
Tasking: Python PEP? Futurize, pylint, 2to3

### ISSUE THREAD

**Issue by egberts** [fail2ban/fail2ban#2854]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): master
- OS, including release name/version: all
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Just a question.

Who is working on the following technical accuracy?

* `futurize`
* `pylint`
* `2to3`

**Comment by sebres** [comment]
As for technical "accuracy" - fail2ban has a test-suite with very good coverage (over 98%), so after 2to3 the same tests (working for 2.x) should pass also.
As regards "Who is working" - what do you mean exactly? Review? Or did you notice some issue with that?

**Comment by egberts** [comment]
I retracted this issue as an non-issue.  My setup was bad.
