### ISSUE TITLE
Doesn't work with Python 3.8 and pip 20.1.1

### ISSUE THREAD

**Issue by iredmail** [fail2ban/fail2ban#2857]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): `0.11.1` (Downloaded from github, installed with pip locally)
- OS, including release name/version: `OpenBSD 6.8, amd64`
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

1. Install fail2ban locally with pip 20.1.1 (the one available in OpenBSD website), it creates config fils under `/usr/local/lib/python3.8/site-packages/etc/fail2ban/` (correct directory should be `/etc/fail2ban/`). Not sure whether it's a pip or fail2ban issue.
2. Fail2ban failed to start due to few Python 3.8 compatible issues.
  - `iteritems()` is gone in Python 3.8, but many files still use it.
  - Module `ConfigParser` has been renamed to `configparser` in Python 3.x, but 2 files still use this name:
    - `client/configreader.py` https://github.com/fail2ban/fail2ban/blob/master/fail2ban/client/configreader.py#L29
    - `client/fail2banregex.py` https://github.com/fail2ban/fail2ban/blob/master/fail2ban/client/fail2banregex.py#L46
  - File `server/ipdns.py` is not compatible with Python 3.8, it raised error `ERROR: invalid syntax (ipdns.py, line 312)`. https://github.com/fail2ban/fail2ban/blob/master/fail2ban/server/ipdns.py#L312

There might be some more issues, but didn't go further yet.

#### Steps to reproduce

- Install python 3.8 and pip (package name `py3-pip`) on OpenBSD 6.8.
- Install Fail2ban-0.11.1 with pip locally.

#### Expected behavior

Fully compatible with Python 3.8 and start the service.

#### Observed behavior

Failed to start.

**Comment by sebres** [comment]
> Install fail2ban locally with pip 20.1.1 ...

It is described in readme how fail2ban can be installed manually. I have no idea why or for which purposes you may need pip here.

> Fail2ban failed to start due to few Python 3.8 compatible issues.

Fail2ban sources are 2.x compatible per default. Use 2to3 to make 3.x compatible installation:
```bash
# git clone https://github.com/fail2ban/fail2ban.git
cd fail2ban
./fail2ban-2to3
sudo python3 setup.py install
```
