### ISSUE TITLE
Selinux policy module

### ISSUE THREAD

**Issue by Copyrght** [fail2ban/fail2ban#2858]
Hi. Selinux is blocking my zimbra sendmail and i remove the fail2ban policy module. How can i rebuild it ? Centos 6. Fail2Ban 0.9.6-1

**Comment by sebres** [comment]
No idea. Maybe you can reinstall that from your distro (I guess it's called fail2ban_selinux or similar)?
Anyway the fail2ban from stock repo doesn't operate with selinux policies and doesn't contain that.

@fail2ban/maintainers some ideas?

**Comment by hobbes1069** [comment]
Where did you get the fail2band package? If it's EPEL then you would want to report the bug on bugzilla.redhat.com against the EPEL product. Although looking here:

https://src.fedoraproject.org/rpms/fail2ban

It doesn't look like fail2ban is supported on EL 6, only 7 and up.
