### ISSUE TITLE
Fail2ban Not restarting with fail2ban-client

### ISSUE THREAD

**Issue by JEAholding** [fail2ban/fail2ban#2859]
### Environment:
The system are VIRTUAL machine with Xen Community.

- Fail2Ban version (including any possible distribution suffixes):
Multiple VERSION
CentOS 7 
fail2ban-client -V
0.11.1
OpenSuse LEAP 15.2 
fail2ban-client -V
0.10.4

- [X] Fail2Ban installed via OS/distribution mechanisms

### The issue:
When 

fail2ban-client restart' 
or 
'fail2ban-client -i'
restart

Results:
Shutdown successful
Server ready

All of the fail2ban-client status JAIL showing....  
YET:
### Service fail2ban status  
>* fail2ban.service - Fail2Ban Service
   Loaded: loaded (/usr/lib/systemd/system/fail2ban.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2020-10-23 19:18:15 EDT; 1min 28s ago
     Docs: man:fail2ban(1)
  Process: 59822 ExecStop=/usr/bin/fail2ban-client stop (code=exited, status=255)
  Process: 40619 ExecStart=/usr/bin/fail2ban-server -xf $FAIL2BAN_OPTIONS start (code=exited, status=0/SUCCESS)
  Process: 40798 ExecStartPre=/bin/mkdir -p /run/fail2ban (code=exited, status=0/SUCCESS)
 Main PID: 40619 (code=exited, status=0/SUCCESS)
Oct 23 16:09:27 rpbx3 systemd[1]: Starting Fail2Ban Service...
Oct 23 16:09:27 rpbx3 systemd[1]: Started Fail2Ban Service.
Oct 23 16:09:27 rpbx3 fail2ban-server[40799]: 2020-10-23 16:09:27,525 fail2ban                [40799]: ERROR   Server already running
Oct 23 16:09:27 rpbx3 fail2ban-server[40799]: 2020-10-23 16:09:27,526 fail2ban                [40799]: ERROR   Async configuration of server failed
Oct 23 19:18:15 rpbx3 fail2ban-client[59822]: 2020-10-23 19:18:15,682 fail2ban                [59822]: ERROR   Failed to access socket path: /var/run/fail2ban/fail2ban>
Oct 23 19:18:15 rpbx3 systemd[1]: fail2ban.service: Control process exited, code=exited status=255
Oct 23 19:18:15 rpbx3 systemd[1]: fail2ban.service: Unit entered failed state.
Oct 23 19:18:15 rpbx3 systemd[1]: fail2ban.service: Failed with result 'exit-code'.'

I look at the socket path: it is showing when restart is done AND is close when fail2ban stop/service fail2ban stop 

I made some very small MODIFICATION into the jail.conf -> jail.local files. I check that the /var/run/fail2ban has 755 directory. 

Everything seems to work but service showing failed fail2ban-client status 

### fail2ban-client -d 

>'['set', 'syslogsocket', 'auto']
['set', 'loglevel', 'INFO']
['set', 'logtarget', '/var/log/fail2ban.log']
['set', 'dbfile', '/var/lib/fail2ban/fail2ban.sqlite3']
['set', 'dbpurgeage', '1d']
['add', 'sshd', 'systemd']
['set', 'sshd', 'maxlines', 1]
['set', 'sshd', 'prefregex', '^<F-MLFID>(?:\\[\\])?\\s*(?:<[^.]+\\.[^.]+>\\s+)?(?:\\S+\\s+)?(?:kernel: \\[ *\\d+\\.\\d+\\]\\s+)?(?:@vserver_\\S+\\s+)?(?:(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)\\s+)?(?:\\[ID \\d+ \\S+\\]\\s+)?</F-MLFID>(?:(?:error|fatal): (?:PAM: )?)?<F-CONTENT>.+</F-CONTENT>$']
['multi-set', 'sshd', 'addfailregex', ['^[aA]uthentication (?:failure|error|failed) for <F-USER>.*</F-USER> from <HOST>( via \\S+)?(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^User not known to the underlying authentication module for <F-USER>.*</F-USER> from <HOST>(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^Failed publickey for invalid user <F-USER>(?P<cond_user>\\S+)|(?:(?! from ).)*?</F-USER> from <HOST>(?: (?:port \\d+|on \\S+)){0,2}(?: ssh\\d*)?(?(cond_user): |(?:(?:(?! from ).)*)$)', '^Failed \\b(?!publickey)\\S+ for (?P<cond_inv>invalid user )?<F-USER>(?P<cond_user>\\S+)|(?(cond_inv)(?:(?! from ).)*?|[^:]+)</F-USER> from <HOST>(?: (?:port \\d+|on \\S+)){0,2}(?: ssh\\d*)?(?(cond_user): |(?:(?:(?! from ).)*)$)', '^<F-USER>ROOT</F-USER> LOGIN REFUSED FROM <HOST>', '^[iI](?:llegal|nvalid) user <F-USER>.*?</F-USER> from <HOST>(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^User <F-USER>.+</F-USER> from <HOST> not allowed because not listed in AllowUsers(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^User <F-USER>.+</F-USER> from <HOST> not allowed because listed in DenyUsers(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^User <F-USER>.+</F-USER> from <HOST> not allowed because not in any group(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^refused connect from \\S+ \\(<HOST>\\)', '^Received <F-MLFFORGET>disconnect</F-MLFFORGET> from <HOST>(?: (?:port \\d+|on \\S+)){0,2}:\\s*3: .*: Auth fail(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^User <F-USER>.+</F-USER> from <HOST> not allowed because a group is listed in DenyGroups(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', "^User <F-USER>.+</F-USER> from <HOST> not allowed because none of user's groups are listed in AllowGroups(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$", '^<F-NOFAIL>pam_[a-z]+\\(sshd:auth\\):\\s+authentication failure;</F-NOFAIL>(?:\\s+(?:(?:logname|e?uid|tty)=\\S*)){0,4}\\s+ruser=<F-ALT_USER>\\S*</F-ALT_USER>\\s+rhost=<HOST>(?:\\s+user=<F-USER>\\S*</F-USER>)?(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^(error: )?maximum authentication attempts exceeded for <F-USER>.*</F-USER> from <HOST>(?: (?:port \\d+|on \\S+)){0,2}(?: ssh\\d*)?(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^User <F-USER>.+</F-USER> not allowed because account is locked(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*', '^<F-MLFFORGET>Disconnecting</F-MLFFORGET>: Too many authentication failures(?: for <F-USER>.+?</F-USER>)?(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^<F-NOFAIL>Received <F-MLFFORGET>disconnect</F-MLFFORGET></F-NOFAIL> from <HOST>(?: (?:port \\d+|on \\S+)){0,2}:\\s*11:', '^<F-NOFAIL>Connection <F-MLFFORGET>closed</F-MLFFORGET></F-NOFAIL> by(?: authenticating user <F-USER>\\S+|.+?</F-USER>)? <HOST>(?:(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*|\\s*)$', '^<F-MLFFORGET><F-NOFAIL>Accepted \\w+</F-NOFAIL></F-MLFFORGET> for <F-USER>\\S+</F-USER> from <HOST>(?:\\s|$)', '^<F-NOFAIL>Connection from</F-NOFAIL> <HOST>']]
['set', 'sshd', 'datepattern', '{^LN-BEG}']
['set', 'sshd', 'addjournalmatch', '_SYSTEMD_UNIT=sshd.service', '+', '_COMM=sshd']
['set', 'sshd', 'maxretry', 3]
['set', 'sshd', 'findtime', '605000']
['set', 'sshd', 'bantime', '1175000']
['set', 'sshd', 'usedns', 'warn']
['set', 'sshd', 'ignorecommand', '']
['set', 'sshd', 'ignoreself', True]
['set', 'sshd', 'addignoreip', '127.0.0.1/8']
['set', 'sshd', 'logencoding', 'auto']
['set', 'sshd', 'addaction', 'iptables-multiport']
['multi-set', 'sshd', 'action', 'iptables-multiport', [['actionstart', '<iptables> -N f2b-sshd\n<iptables> -A f2b-sshd -j RETURN\n<iptables> -I INPUT -p all -m multiport --dports ssh -j f2b-sshd'], ['actionstop', '<iptables> -D INPUT -p all -m multiport --dports ssh -j f2b-sshd\n<iptables> -F f2b-sshd\n<iptables> -X f2b-sshd'], ['actionflush', '<iptables> -F f2b-sshd'], ['actioncheck', "<iptables> -n -L INPUT | grep -q 'f2b-sshd[ \\t]'"], ['actionban', '<iptables> -I f2b-sshd 1 -s <ip> -j <blocktype>'], ['actionunban', '<iptables> -D f2b-sshd -s <ip> -j <blocktype>'], ['name', 'sshd'], ['protocol', 'all'], ['port', 'ssh'], ['actname', 'iptables-multiport'], ['chain', 'INPUT'], ['blocktype', 'REJECT --reject-with icmp-port-unreachable'], ['returntype', 'RETURN'], ['lockingopt', '-w'], ['iptables', 'iptables <lockingopt>'], ['blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unreachable'], ['iptables?family=inet6', 'ip6tables <lockingopt>']]]
['set', 'sshd', 'addaction', 'sendmail']
['multi-set', 'sshd', 'action', 'sendmail', [['actionstart', 'printf %b "Subject: [Fail2Ban] sshd-rpbx3-jail: started on <fq-hostname>\nDate: `LC_ALL=C date +"%a, %d %h %Y %T %z"`\nFrom: Fail2Ban <fail2ban-sshd-rpbx3@local.local>\nTo: anemail@.com\\n\nHi,\\n\nThe jail sshd-rpbx3-jail has been started successfully.\\n\nRegards,\\n\nFail2Ban" | /usr/sbin/sendmail -f fail2ban-sshd-rpbx3@local.local anemail@.com'], ['actionstop', 'printf %b "Subject: [Fail2Ban] sshd-rpbx3-jail: stopped on <fq-hostname>\nDate: `LC_ALL=C date +"%a, %d %h %Y %T %z"`\nFrom: Fail2Ban <fail2ban-sshd-rpbx3@local.local>\nTo: anemail@.com\\n\nHi,\\n\nThe jail sshd-rpbx3-jail has been stopped.\\n\nRegards,\\n\nFail2Ban" | /usr/sbin/sendmail -f fail2ban-sshd-rpbx3@local.local anemail@.com'], ['actioncheck', ''], ['actionban', 'printf %b "Subject: [Fail2Ban] sshd-rpbx3-jail: banned <ip> from <fq-hostname>\nDate: `LC_ALL=C date +"%a, %d %h %Y %T %z"`\nFrom: Fail2Ban <fail2ban-sshd-rpbx3@local.local>\nTo: anemail@.com\\n\nHi,\\n\nThe IP <ip> has just been banned by Fail2Ban after\n<failures> attempts against sshd-rpbx3-jail.\\n\nRegards,\\n\nFail2Ban" | /usr/sbin/sendmail -f fail2ban-sshd-rpbx3@local.local anemail@.com'], ['actionunban', ''], ['norestored', True], ['name', 'sshd-rpbx3-jail'], ['dest', 'anemail@.com'], ['sender', 'fail2ban-sshd-rpbx3@local.local'], ['actname', 'sendmail'], ['sendername', 'Fail2Ban']]]
['add', 'asterisk', 'auto']
['set', 'asterisk', 'prefregex', '^(?:\\[\\])?\\s*(?:<[^.]+\\.[^.]+>\\s+)?(?:\\S+\\s+)?(?:kernel: \\[ *\\d+\\.\\d+\\]\\s+)?(?:@vserver_\\S+\\s+)?(?:(?:(?:\\s*\\[\\d+\\])?:\\s+[\\[\\(]?asterisk(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?asterisk(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\s*\\[\\d+\\])?:?)\\s+)?(?:\\[ID \\d+ \\S+\\]\\s+)?(?:NOTICE|SECURITY|WARNING)(?:\\s*\\[\\d+\\]):?(?:\\[C-[\\da-f]*\\])? [^:]+:\\d*(?:(?: in)? \\w+:)? <F-CONTENT>.+</F-CONTENT>$']
['multi-set', 'asterisk', 'addfailregex', ["^Registration from '[^']*' failed for '<HOST>(:\\d+)?' - (?:Wrong password|Username/auth name mismatch|No matching peer found|Not a local domain|Device does not match ACL|Peer is not supposed to register|ACL error \\(permit/deny\\)|Not a local domain)$", "^Call from '[^']*' \\(<HOST>:\\d+\\) to extension '[^']*' rejected because extension not found in context", '^(?:Host )?<HOST> (?:failed (?:to authenticate\\b|MD5 authentication\\b)|tried to authenticate with nonexistent user\\b)', "^No registration for peer '[^']*' \\(from <HOST>\\)$", "^hacking attempt detected '<HOST>'$", '^SecurityEvent="(?:FailedACL|InvalidAccountID|ChallengeResponseFailed|InvalidPassword)"(?:(?:,(?!RemoteAddress=)\\w+="[^"]*")*|.*?),RemoteAddress="IPV[46]/(UDP|TCP|WS)/<HOST>/\\d+"(?:,(?!RemoteAddress=)\\w+="[^"]*")*$', '^"Rejecting unknown SIP connection from <HOST>"$', "^Request (?:'[^']*' )?from '(?:[^']*|.*?)' failed for '<HOST>(?::\\d+)?'\\s\\(callid: [^\\)]*\\) - (?:No matching endpoint found|Not match Endpoint(?: Contact)? ACL|(?:Failed|Error) to authenticate)\\s*$", '^(?:\\[\\])?\\s*(?:<[^.]+\\.[^.]+>\\s+)?(?:\\S+\\s+)?(?:kernel: \\[ *\\d+\\.\\d+\\]\\s+)?(?:@vserver_\\S+\\s+)?(?:(?:(?:\\s*\\[\\d+\\])?:\\s+[\\[\\(]?asterisk(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?asterisk(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\s*\\[\\d+\\])?:?)\\s+)?(?:\\[ID \\d+ \\S+\\]\\s+)?(?:NOTICE|SECURITY|WARNING)(?:\\s*\\[\\d+\\]):?(?:\\[C-[\\da-f]*\\])? [^:]+:\\d*(?:(?: in)? \\w+:)? Failed to authenticate (user|device) [^@]+@<HOST>\\S*$']]
['set', 'asterisk', 'datepattern', '{^LN-BEG}']
['set', 'asterisk', 'maxretry', 3]
['set', 'asterisk', 'findtime', '605000']
['set', 'asterisk', 'bantime', '1805000']
['set', 'asterisk', 'usedns', 'warn']
['set', 'asterisk', 'ignorecommand', '']
['set', 'asterisk', 'ignoreself', True]
['set', 'asterisk', 'addignoreip', '127.0.0.1/8']
['set', 'asterisk', 'addignoreip', '192.168.0.1/24']
['set', 'asterisk', 'logencoding', 'auto']
['set', 'asterisk', 'addlogpath', '/var/log/asterisk/messages', 'head']
['set', 'asterisk', 'addaction', 'iptables-multiport']
['multi-set', 'asterisk', 'action', 'iptables-multiport', [['actionstart', '<iptables> -N f2b-asterisk\n<iptables> -A f2b-asterisk -j RETURN\n<iptables> -I INPUT -p all -m multiport --dports 5060 -j f2b-asterisk'], ['actionstop', '<iptables> -D INPUT -p all -m multiport --dports 5060 -j f2b-asterisk\n<iptables> -F f2b-asterisk\n<iptables> -X f2b-asterisk'], ['actionflush', '<iptables> -F f2b-asterisk'], ['actioncheck', "<iptables> -n -L INPUT | grep -q 'f2b-asterisk[ \\t]'"], ['actionban', '<iptables> -I f2b-asterisk 1 -s <ip> -j <blocktype>'], ['actionunban', '<iptables> -D f2b-asterisk -s <ip> -j <blocktype>'], ['name', 'asterisk'], ['protocol', 'all'], ['port', '5060'], ['actname', 'iptables-multiport'], ['chain', 'INPUT'], ['blocktype', 'REJECT --reject-with icmp-port-unreachable'], ['returntype', 'RETURN'], ['lockingopt', '-w'], ['iptables', 'iptables <lockingopt>'], ['blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unreachable'], ['iptables?family=inet6', 'ip6tables <lockingopt>']]]
['set', 'asterisk', 'addaction', 'sendmail']
['multi-set', 'asterisk', 'action', 'sendmail', [['actionstart', 'printf %b "Subject: [Fail2Ban] asterisk-rpbx3-jail: started on <fq-hostname>\nDate: `LC_ALL=C date +"%a, %d %h %Y %T %z"`\nFrom: Fail2Ban <fail2ban-asterisk-rpbx3@local.local>\nTo: anemail@.com\\n\nHi,\\n\nThe jail asterisk-rpbx3-jail has been started successfully.\\n\nRegards,\\n\nFail2Ban" | /usr/sbin/sendmail -f fail2ban-asterisk-rpbx3@local.local anemail@.com'], ['actionstop', 'printf %b "Subject: [Fail2Ban] asterisk-rpbx3-jail: stopped on <fq-hostname>\nDate: `LC_ALL=C date +"%a, %d %h %Y %T %z"`\nFrom: Fail2Ban <fail2ban-asterisk-rpbx3@local.local>\nTo: anemail@.com\\n\nHi,\\n\nThe jail asterisk-rpbx3-jail has been stopped.\\n\nRegards,\\n\nFail2Ban" | /usr/sbin/sendmail -f fail2ban-asterisk-rpbx3@local.local anemail@.com'], ['actioncheck', ''], ['actionban', 'printf %b "Subject: [Fail2Ban] asterisk-rpbx3-jail: banned <ip> from <fq-hostname>\nDate: `LC_ALL=C date +"%a, %d %h %Y %T %z"`\nFrom: Fail2Ban <fail2ban-asterisk-rpbx3@local.local>\nTo: anemail@.com\\n\nHi,\\n\nThe IP <ip> has just been banned by Fail2Ban after\n<failures> attempts against asterisk-rpbx3-jail.\\n\nRegards,\\n\nFail2Ban" | /usr/sbin/sendmail -f fail2ban-asterisk-rpbx3@local.local anemail@.com'], ['actionunban', ''], ['norestored', True], ['name', 'asterisk-rpbx3-jail'], ['dest', 'anemail@.com'], ['sender', 'fail2ban-asterisk-rpbx3@local.local'], ['actname', 'sendmail'], ['sendername', 'Fail2Ban']]]
['add', 'recidive', 'auto']
['set', 'recidive', 'addfailregex', '^(?:\\[\\])?\\s*(?:<[^.]+\\.[^.]+>\\s+)?(?:\\S+\\s+)?(?:kernel: \\[ *\\d+\\.\\d+\\]\\s+)?(?:@vserver_\\S+\\s+)?(?:(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?(?:fail2ban(?:-server|\\.actions)\\s*)(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?(?:fail2ban(?:-server|\\.actions)\\s*)(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)\\s+)?(?:\\[ID \\d+ \\S+\\]\\s+)?(?:\\s*fail2ban\\.actions\\s*(?:\\[\\d+\\])?:\\s+)?NOTICE\\s+\\[(?!recidive\\])(?:.*)\\]\\s+Ban\\s+<HOST>\\s*$']
['set', 'recidive', 'datepattern', '^{DATE}']
['set', 'recidive', 'addjournalmatch', '_SYSTEMD_UNIT=fail2ban.service', 'PRIORITY=5']
['set', 'recidive', 'maxretry', 2]
['set', 'recidive', 'findtime', '1d']
['set', 'recidive', 'bantime', '10w']
['set', 'recidive', 'usedns', 'warn']
['set', 'recidive', 'ignorecommand', '']
['set', 'recidive', 'ignoreself', True]
['set', 'recidive', 'addignoreip', '127.0.0.1/8']
['set', 'recidive', 'addignoreip', '192.168.0.1/24']
['set', 'recidive', 'logencoding', 'auto']
['set', 'recidive', 'addlogpath', '/var/log/fail2ban.log', 'head']
['set', 'recidive', 'addaction', 'iptables-allports']
['multi-set', 'recidive', 'action', 'iptables-allports', [['actionstart', '<iptables> -N f2b-recidive\n<iptables> -A f2b-recidive -j RETURN\n<iptables> -I INPUT -p tcp -j f2b-recidive'], ['actionstop', '<iptables> -D INPUT -p tcp -j f2b-recidive\n<iptables> -F f2b-recidive\n<iptables> -X f2b-recidive'], ['actionflush', '<iptables> -F f2b-recidive'], ['actioncheck', "<iptables> -n -L INPUT | grep -q 'f2b-recidive[ \\t]'"], ['actionban', '<iptables> -I f2b-recidive 1 -s <ip> -j <blocktype>'], ['actionunban', '<iptables> -D f2b-recidive -s <ip> -j <blocktype>'], ['name', 'recidive'], ['bantime', '10w'], ['port', '0:65535'], ['protocol', 'tcp'], ['chain', '<known/chain>'], ['actname', 'iptables-allports'], ['blocktype', 'REJECT --reject-with icmp-port-unreachable'], ['returntype', 'RETURN'], ['lockingopt', '-w'], ['iptables', 'iptables <lockingopt>'], ['blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unreachable'], ['iptables?family=inet6', 'ip6tables <lockingopt>']]]
['start', 'sshd']
['start', 'asterisk']
['start', 'recidive']'

### service fail2ban start
>'* fail2ban.service - Fail2Ban Service
   Loaded: loaded (/usr/lib/systemd/system/fail2ban.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2020-10-23 19:36:51 EDT; 3s ago
     Docs: man:fail2ban(1)
  Process: 61715 ExecStop=/usr/bin/fail2ban-client stop (code=exited, status=0/SUCCESS)
  Process: 61970 ExecStartPre=/bin/mkdir -p /run/fail2ban (code=exited, status=0/SUCCESS)
 Main PID: 61810 (fail2ban-server)
    Tasks: 0
   CGroup: /system.slice/fail2ban.service
           61810 /usr/bin/python3 /usr/bin/fail2ban-server --async -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban>>/fail2ban.pid --loglevel INFO --logtarg
Oct 23 19:36:51 rpbx3 systemd[1]: Starting Fail2Ban Service...
Oct 23 19:36:51 rpbx3 systemd[1]: Started Fail2Ban Service.
Oct 23 19:36:52 rpbx3 fail2ban-server[61971]: 2020-10-23 19:36:52,120 fail2ban                [61971]: ERROR   Server already running
Oct 23 19:36:52 rpbx3 fail2ban-server[61971]: 2020-10-23 19:36:52,120 fail2ban                [61971]: ERROR   Async configuration of server failed
lines 1-15/15 (END)...skipping...
 fail2ban.service - Fail2Ban Service
   Loaded: loaded (/usr/lib/systemd/system/fail2ban.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2020-10-23 19:36:51 EDT; 3s ago
     Docs: man:fail2ban(1)
  Process: 61715 ExecStop=/usr/bin/fail2ban-client stop (code=exited, status=0/SUCCESS)
  Process: 61970 ExecStartPre=/bin/mkdir -p /run/fail2ban (code=exited, status=0/SUCCESS)
 Main PID: 61810 (fail2ban-server)
    Tasks: 0
CGroup: /system.slice/fail2ban.service
            61810 /usr/bin/python3 /usr/bin/fail2ban-server --async -b -s /var/run/fail2ban/fail2ban.sock -p /var/run/fail2ban/fail2ban.pid --loglevel INFO --logtar
Oct 23 19:36:51 rpbx3 systemd[1]: Starting Fail2Ban Service...
Oct 23 19:36:51 rpbx3 systemd[1]: Started Fail2Ban Service.
Oct 23 19:36:52 rpbx3 fail2ban-server[61971]: 2020-10-23 19:36:52,120 fail2ban                [61971]: ERROR   Server already running
Oct 23 19:36:52 rpbx3 fail2ban-server[61971]: 2020-10-23 19:36:52,120 fail2ban                [61971]: ERROR   Async configuration of server failed

=== Question or Resolution
Any suggestion what might be the issue? 
On a fresh install before I did any modification to jail.local file everything seems to work.
I have multiple VM with same issue and different Linux Variant. I have not modified the original filter.d files. 
The issue does not occur with 
>service fail2ban restart

```
```

**Comment by sebres** [comment]
Take a look in `/var/log/fail2ban.log` file.
