### ISSUE TITLE
fail2ban-client unban --all not releases all banned ip's

### ISSUE THREAD

**Issue by Offerel** [fail2ban/fail2ban#2861]
#Environment:
- Fail2Ban version (including any possible distribution suffixes): 0.10.2-2.1
- OS, including release name/version: Debian, Raspbian (Buster)
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
I tried to release all banned IP Adresses with the command `fail2ban-client unban --all`. Most of the IP addresses was released after this but not all. The Jails nginx-botsearch and nginx-no-proxy have banned IP's after this command.

#### Steps to reproduce
* Open an bash shell and type the command `fail2ban-client unban --all`
* Re-check iptables with `iptables -L -n`
* Banned IP's are listed for the jails nginx-botsearch and nginx-no-proxy
* The IP's can successfully be released with `fail2ban-client set nginx-botsearch unbanip <IP address>`

#### Expected behavior
The command `fail2ban-client unban --all` should release all ip addresses banned by fail2ban

#### Observed behavior
Only some IP addresses are released, instead of all

**Comment by sebres** [comment]
The fail2ban is multi-tasking, so this handling is running parallel with regular work of fail2ban-server - some IPs can be banned as long as unban process is in progress (also note that `unban --all` is working jail after jail, so already unbanned jails are processing regularly further, so can ban new IPs with pending failures).
