### ISSUE TITLE
badips.com down, times out

### ISSUE THREAD

**Issue by RobbieTheK** [fail2ban/fail2ban#2862]
I see certain pages within the badips.com domain like the[ badips.conf file](https://www.badips.com/asset/fail2ban/badips.conf) are up but the home page is down 
![image](https://user-images.githubusercontent.com/21204619/97310984-3cabe480-183a-11eb-9ccb-fcd8920fc46d.png). This isn't a Fail2ban issue but I wanted to alert folks that this is happening. I see there was a [recent enhancement](https://github.com/fail2ban/fail2ban/issues/2600), perhaps checking for the site availability could also be added to that?

**Comment by sebres** [comment]
3rd party stuff
