### ISSUE TITLE
Badbots update: add PetalBot

### ISSUE THREAD

**Issue by Tectract** [fail2ban/fail2ban#2863]
### The issue:

PetalBot, run by a partner of the Chinese Communist Party and Huawei, is a persistent web threat and server nuisance.

See here: aspiegel.com/petalbot

string 'PetalBot' should be added to the "apache-badbots" file, in the badbots string.

#### Relevant lines from monitored log files in question:

www.myserver.io:443 114.119.150.210 - - [28/Oct/2020:18:58:21 -0600] "GET /scraping/my/wiki/Indexed_pages&action=edit&redlink=1 HTTP/1.1" 404 14806 "-" "Mozilla/5.0 (Linux; Android 7.0;) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; PetalBot;+https://aspiegel.com/petalbot)

**Comment by Tectract** [comment]
Also, "SemRush" should be added. They are attacking my wordpress logins, seems to be some sort of script-kiddie bot that can be pointed at any server, and I'm also getting advanced attack attempts on my servers directly from SemRush Corporate IP addresses in the Netherlands.

**Comment by sebres** [comment]
There is already an open (cumulative) issue about a badbots, thus to avoid duplicates, further in #1950
