### ISSUE TITLE
Regex test is ok but still doesn't ban

### ISSUE THREAD

**Issue by Turab** [fail2ban/fail2ban#2864]
Hi.

I am using default Bitwarden jail to watch Bitwarden_rs modfying the regex accordingly like;

```
[bitwarden]
port    = http,https
logpath = /var/log/bitwarden.log
datepattern = "%Y-%m-%d %H:%M:%S"
enabled = true
```

And this is the regex test result:

```
Results
=======

Failregex: 44 total
|-  #) [# of hits] regular expression
|   1) [44] ^.*Username or password is incorrect\. Try again\. IP: <HOST>\. Username:.*$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [427] Year-Month-Day 24hour:Minute:Second
`-

Lines: 427 lines, 0 ignored, 44 matched, 383 missed
[processed in 0.05 sec]
```

It can correctly parse the log file but never bans and never includes in fail2ban.log

Edit: Sorry false alarm. Bitwarden and Bitwarden_rs have different regex; it turns out I am testing Bitwarden_rs regex but applying Bitwarden default. I put failregex in jail.local and now it works.

**Comment by sebres** [comment]
> Edit: Sorry false alarm. Bitwarden and Bitwarden_rs have different regex; it turns out I am testing Bitwarden_rs regex but applying Bitwarden default. I put failregex in jail.local and now it works.

Thus closing it.
