### ISSUE TITLE
F2B SSHD jail stopped detecting on Nov1

### ISSUE THREAD

**Issue by Spire9** [fail2ban/fail2ban#2867]
#2217 
`# Environment:
LAMP
Ubuntu 18.04
Fail2Ban v0.10.2
OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017

- [X ] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
I haven't had any detection on SSHD since Nov1 (daylight savings day).  My times look good to me.  I have restarted the server multiple times since.

#### Steps to reproduce
View logs.
#### Expected behavior
Ban the foreign attempts.  Honestly, I haven't seen any username guessing since Nov1, they have all been attempts against root.  FYI, root only can use a certificate for login.
#### Observed behavior
auth.log fills up with attempts against root, fail2ban logs nothing.
#### Any additional information
I acknowlege these attempts against root are aborting, but I'm pretty sure they used to cause bans.
#### Any customizations done to /etc/fail2ban/ configuration
```
[sshd]
enabled = true
findtime = 25h
bantime = 8d
maxretry = 1
port = 33
```

#### Relevant parts of /var/log/fail2ban.log file:
*Nothing*

#### Relevant lines from monitored log files in question:

```
Nov  5 21:44:45 www sshd[23366]: Received disconnect from 122.51.200.223 port 35228:11: Bye Bye [preauth]
Nov  5 21:44:45 www sshd[23366]: Disconnected from authenticating user root 122.51.200.223 port 35228 [preauth]
Nov  5 21:46:23 www sshd[23569]: Received disconnect from 188.131.140.160 port 57704:11: Bye Bye [preauth]
Nov  5 21:46:23 www sshd[23569]: Disconnected from authenticating user root 188.131.140.160 port 57704 [preauth]
Nov  5 21:47:46 www sshd[23755]: Received disconnect from 159.203.102.122 port 51928:11: Bye Bye [preauth]
Nov  5 21:47:46 www sshd[23755]: Disconnected from authenticating user root 159.203.102.122 port 51928 [preauth]
Nov  5 21:51:52 www sshd[24261]: Received disconnect from 188.166.20.136 port 36906:11: Bye Bye [preauth]
Nov  5 21:51:52 www sshd[24261]: Disconnected from authenticating user root 188.166.20.136 port 36906 [preauth]
Nov  5 22:01:37 www sshd[25543]: Received disconnect from 58.16.83.221 port 49510:11: Bye Bye [preauth]
Nov  5 22:01:37 www sshd[25543]: Disconnected from authenticating user root 58.16.83.221 port 49510 [preauth]
Nov  5 22:03:07 www sshd[25721]: Received disconnect from 43.226.148.89 port 32780:11: Bye Bye [preauth]
Nov  5 22:03:07 www sshd[25721]: Disconnected from authenticating user root 43.226.148.89 port 32780 [preauth]
```

```
# fail2ban-regex /var/log/auth.log sshd

Running tests
=============

Use   failregex filter file : sshd, basedir: /etc/fail2ban
Use         maxlines : 1
Use      datepattern : Default Detectors
Use         log file : /var/log/auth.log
Use         encoding : UTF-8


Results
=======

Failregex: 42 total
|-  #) [# of hits] regular expression
|   6) [1] ^[iI](?:llegal|nvalid) user <F-USER>.*?</F-USER> from <HOST>(?: port \d+)?(?: on \S+(?: port \d+)?)?\s*$
|  20) [32] ^<F-MLFFORGET><F-NOFAIL>Accepted publickey</F-NOFAIL></F-MLFFORGET> for \S+ from <HOST>(?:\s|$)
|  21) [9] ^<F-NOFAIL>Connection from</F-NOFAIL> <HOST>
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [2452] {^LN-BEG}(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
`-

Lines: 2452 lines, 0 ignored, 42 matched, 2410 missed
[processed in 0.60 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all 2410 lines
```

```
# fail2ban-client status sshd
Status for the jail: sshd
|- Filter
|  |- Currently failed: 0
|  |- Total failed:     0
|  `- File list:        /var/log/auth.log
`- Actions
   |- Currently banned: 0
   |- Total banned:     0
   `- Banned IP list:
```

```
# fail2ban-client -d | grep 'sshd'
['add', 'sshd', 'auto']
['set', 'sshd', 'maxlines', 1]
['set', 'sshd', 'prefregex', '^<F-MLFID>(?:\\[\\])?\\s*(?:<[^.]+\\.[^.]+>\\s+)?(?:\\S+\\s+)?(?:kernel: \\[ *\\d+\\.\\d+\\]\\s+)?(?:@vserver_\\S+\\s+)?(?:(?:(?:\\[\\d+\\])?:\\s+[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?|[\\[\\(]?sshd(?:\\(\\S+\\))?[\\]\\)]?:?(?:\\[\\d+\\])?:?)\\s+)?(?:\\[ID \\d+ \\S+\\]\\s+)?</F-MLFID>(?:(?:error|fatal): (?:PAM: )?)?<F-CONTENT>.+</F-CONTENT>$']
['multi-set', 'sshd', 'addfailregex', ['^[aA]uthentication (?:failure|error|failed) for <F-USER>.*</F-USER> from <HOST>( via \\S+)?\\s*(?: \\[preauth\\])?\\s*$', '^User not known to the underlying authentication module for <F-USER>.*</F-USER> from <HOST>\\s*(?: \\[preauth\\])?\\s*$', '^Failed \\S+ for invalid user <F-USER>(?P<cond_user>\\S+)|(?:(?! from ).)*?</F-USER> from <HOST>(?: port \\d+)?(?: on \\S+(?: port \\d+)?)?(?: ssh\\d*)?(?(cond_user): |(?:(?:(?! from ).)*)$)', '^Failed \\b(?!publickey)\\S+ for (?P<cond_inv>invalid user )?<F-USER>(?P<cond_user>\\S+)|(?(cond_inv)(?:(?! from ).)*?|[^:]+)</F-USER> from <HOST>(?: port \\d+)?(?: on \\S+(?: port \\d+)?)?(?: ssh\\d*)?(?(cond_user): |(?:(?:(?! from ).)*)$)', '^<F-USER>ROOT</F-USER> LOGIN REFUSED.* FROM <HOST>\\s*(?: \\[preauth\\])?\\s*$', '^[iI](?:llegal|nvalid) user <F-USER>.*?</F-USER> from <HOST>(?: port \\d+)?(?: on \\S+(?: port \\d+)?)?\\s*$', '^User <F-USER>.+</F-USER> from <HOST> not allowed because not listed in AllowUsers\\s*(?: \\[preauth\\])?\\s*$', '^User <F-USER>.+</F-USER> from <HOST> not allowed because listed in DenyUsers\\s*(?: \\[preauth\\])?\\s*$', '^User <F-USER>.+</F-USER> from <HOST> not allowed because not in any group\\s*(?: \\[preauth\\])?\\s*$', '^refused connect from \\S+ \\(<HOST>\\)\\s*(?: \\[preauth\\])?\\s*$', '^Received <F-MLFFORGET>disconnect</F-MLFFORGET> from <HOST>(?: port \\d+)?(?: on \\S+(?: port \\d+)?)?:\\s*3: .*: Auth fail(?: \\[preauth\\])?\\s*$', '^User <F-USER>.+</F-USER> from <HOST> not allowed because a group is listed in DenyGroups\\s*(?: \\[preauth\\])?\\s*$', "^User <F-USER>.+</F-USER> from <HOST> not allowed because none of user's groups are listed in AllowGroups\\s*(?: \\[preauth\\])?\\s*$", '^pam_unix\\(sshd:auth\\):\\s+authentication failure;\\s*logname=\\S*\\s*uid=\\d*\\s*euid=\\d*\\s*tty=\\S*\\s*ruser=<F-USER>\\S*</F-USER>\\s*rhost=<HOST>\\s.*(?: \\[preauth\\])?\\s*$', '^(error: )?maximum authentication attempts exceeded for <F-USER>.*</F-USER> from <HOST>(?: port \\d+)?(?: on \\S+(?: port \\d+)?)?(?: ssh\\d*)?(?: \\[preauth\\])?\\s*$', '^User <F-USER>.+</F-USER> not allowed because account is locked(?: \\[preauth\\])?\\s*', '^<F-MLFFORGET>Disconnecting</F-MLFFORGET>: Too many authentication failures(?: for <F-USER>.+?</F-USER>)?(?: \\[preauth\\])?\\s*', '^<F-NOFAIL>Received <F-MLFFORGET>disconnect</F-MLFFORGET></F-NOFAIL> from <HOST>: 11:', '^<F-NOFAIL>Connection <F-MLFFORGET>closed</F-MLFFORGET></F-NOFAIL> by <HOST>(?: \\[preauth\\])?\\s*$', '^<F-MLFFORGET><F-NOFAIL>Accepted publickey</F-NOFAIL></F-MLFFORGET> for \\S+ from <HOST>(?:\\s|$)', '^<F-NOFAIL>Connection from</F-NOFAIL> <HOST>']]
['set', 'sshd', 'datepattern', '{^LN-BEG}']
['set', 'sshd', 'addjournalmatch', '_SYSTEMD_UNIT=sshd.service', '+', '_COMM=sshd']
['set', 'sshd', 'addlogpath', '/var/log/auth.log', 'head']
['set', 'sshd', 'logencoding', 'auto']
['set', 'sshd', 'maxretry', 1]
['set', 'sshd', 'findtime', '25h']
['set', 'sshd', 'bantime', '8d']
['set', 'sshd', 'usedns', 'warn']
['set', 'sshd', 'ignorecommand', '']
['set', 'sshd', 'addignoreip', '127.0.0.1']
['set', 'sshd', 'addignoreip', '::1']
['set', 'sshd', 'addignoreip', '123.123.12.123']
['set', 'sshd', 'addignoreip', '123.12.12.12']
['set', 'sshd', 'addignoreip', '123.123.0.0/16']
['set', 'sshd', 'addaction', 'iptables-allports']
['multi-set', 'sshd', 'action', 'iptables-allports', [['actionstart', '<iptables> -N f2b-sshd\n<iptables> -A f2b-sshd -j RETURN\n<iptables> -I INPUT -p tcp -j f2b-sshd'], ['actionstop', '<iptables> -D INPUT -p tcp -j f2b-sshd\n<iptables> -F f2b-sshd\n<iptables> -X f2b-sshd'], ['actionflush', '<iptables> -F f2b-sshd'], ['actioncheck', "<iptables> -n -L INPUT | grep -q 'f2b-sshd[ \\t]'"], ['actionban', '<iptables> -I f2b-sshd 1 -s <ip> -j <blocktype>'], ['actionunban', '<iptables> -D f2b-sshd -s <ip> -j <blocktype>'], ['name', 'sshd'], ['bantime', '8d'], ['port', '33'], ['protocol', 'tcp'], ['chain', '<known/chain>'], ['actname', 'iptables-allports'], ['blocktype', 'REJECT --reject-with icmp-port-unreachable'], ['returntype', 'RETURN'], ['lockingopt', '-w'], ['iptables', 'iptables <lockingopt>'], ['blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unreachable'], ['iptables?family=inet6', 'ip6tables <lockingopt>']]]
['start', 'sshd']
```

**Comment by sebres** [comment]
Both types of messages in your excerpt `Received disconnect ...` and `Disconnected from authenticating user ...` on `preauth` phase don't mean that an authentication takes place at all, so they are not causing failures in mode `normal`, which is supposed to recognize authentication failures only.
To ban more aggressively resp. to consider DOS or flood on preauth phase, you've to set mode to `ddos` or `aggressive`.
To test it use `fail2ban-regex /var/log/auth.log sshd[mode=aggressive]`.

> Honestly, I haven't seen any username guessing since Nov1, they have all been attempts against root. FYI, root only can use a certificate for login.

I guess because it is changed by sshd service (no authentication possible without key-file) or logging gets changed per default, or something similar. You can try more verbose log-level of sshd logging, e. g. try to specify `LogLevel VERBOSE` in `/etc/ssh/sshd_config`.

**Comment by Spire9** [comment]
Thanks for having a look.  I should have posted the [mode=aggressive] results, which only adds 4 detections...

```
# fail2ban-regex /var/log/auth.log sshd[mode=aggressive]

Running tests
=============

Use   failregex filter file : sshd, basedir: /etc/fail2ban
Use   filter options : {'mode': 'aggressive'}
Use         maxlines : 1
Use      datepattern : Default Detectors
Use         log file : /var/log/auth.log
Use         encoding : UTF-8


Results
=======

Failregex: 63 total
|-  #) [# of hits] regular expression
|   6) [1] ^[iI](?:llegal|nvalid) user <F-USER>.*?</F-USER> from <HOST>(?: port \d+)?(?: on \S+(?: port \d+)?)?\s*$
|  20) [49] ^<F-MLFFORGET><F-NOFAIL>Accepted publickey</F-NOFAIL></F-MLFFORGET> for \S+ from <HOST>(?:\s|$)
|  22) [4] ^Connection <F-MLFFORGET>reset</F-MLFFORGET> by <HOST>(?: port \d+)?(?: on \S+(?: port \d+)?)?(?: \[preauth\])?\s*
|  29) [9] ^<F-NOFAIL>Connection from</F-NOFAIL> <HOST>
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [3561] {^LN-BEG}(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
`-

Lines: 3561 lines, 0 ignored, 63 matched, 3498 missed
[processed in 1.18 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all 3498 lines
```

**Comment by sebres** [comment]
> I should have posted the [mode=aggressive] results, which only adds 4 detections...

OK, the regex enhancement for `Disconnected from ... [preauth]` seems to be provided in f77398c49d4eeb529a1684a27dcfbf5b6aaafa66 (released in 0.10.5 and 0.11.1)... 
Fail2ban 0.10.2 has an old config file yet.

<details><summary>Test for <code>fail2ban-regex -vv /tmp/gh-2867.txt sshd[mode=aggressive] ...</code></summary>

```
$ fail2ban-regex -vv /tmp/gh-2867.txt sshd[mode=aggressive]

Running tests
=============

Use   failregex filter file : sshd, basedir: /etc/fail2ban/
Use   filter options : {'mode': 'aggressive'}
Real  filter options : {'logtype': 'file', 'mode': 'aggressive', 'datepattern': '{^LN-BEG}'}
Use         maxlines : 1
Use      datepattern : {^LN-BEG} : Default Detectors
Use         log file : /tmp/gh-2867.txt
Use         encoding : UTF-8


Results
=======

Prefregex: 12 total
|  ^(?P<mlfid>(?:\[\])?\s*(?:<[^.]+\.[^.]+>\s+)?(?:\S+\s+)?(?:kernel:\s?\[ *\d+\.\d+\]:?\s+)?(?:@vserver_\S+\s+)?(?:(?:(?:\[\d+\])?:\s+[\[\(]?sshd(?:\(\S+\))?[\]\)]?:?|[\[\(]?sshd(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)\s+)?(?:\[ID \d+ \S+\]\s+)?)(?:(?:error|fatal): (?:PAM: )?)?(?P<content>.+)$
...
`-

Failregex: 12 total
|-  #) [# of hits] regular expression
...
|  19) [6] ^<F-NOFAIL>Received <F-MLFFORGET>disconnect</F-MLFFORGET></F-NOFAIL> from <HOST>(?: (?:port \d+|on \S+)){0,2}:\s*11:
|      122.51.200.223  Thu Nov 05 21:44:45 2020
|      188.131.140.160  Thu Nov 05 21:46:23 2020
|      159.203.102.122  Thu Nov 05 21:47:46 2020
|      188.166.20.136  Thu Nov 05 21:51:52 2020
|      58.16.83.221  Thu Nov 05 22:01:37 2020
|      43.226.148.89  Thu Nov 05 22:03:07 2020
|  20) [6] ^<F-MLFFORGET>(Connection (?:closed|reset)|Disconnected)</F-MLFFORGET> (?:by|from)(?: (?:invalid|authenticating) user <F-USER>\S+|.*?</F-USER>)? <HOST>(?: (?:port \d+|on \S+)){0,2}\s+\[preauth\]\s*$
|      122.51.200.223  Thu Nov 05 21:44:45 2020
|      188.131.140.160  Thu Nov 05 21:46:23 2020
|      159.203.102.122  Thu Nov 05 21:47:46 2020
|      188.166.20.136  Thu Nov 05 21:51:52 2020
|      58.16.83.221  Thu Nov 05 22:01:37 2020
|      43.226.148.89  Thu Nov 05 22:03:07 2020
...
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [12] {^LN-BEG}(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
...
`-

Lines: 12 lines, 6 ignored, 6 matched, 0 missed
[processed in 0.00 sec]

|- Ignored line(s):
|  Nov  5 21:44:45 www sshd[23366]: Received disconnect from 122.51.200.223 port 35228:11: Bye Bye [preauth]
|  Nov  5 21:46:23 www sshd[23569]: Received disconnect from 188.131.140.160 port 57704:11: Bye Bye [preauth]
|  Nov  5 21:47:46 www sshd[23755]: Received disconnect from 159.203.102.122 port 51928:11: Bye Bye [preauth]
|  Nov  5 21:51:52 www sshd[24261]: Received disconnect from 188.166.20.136 port 36906:11: Bye Bye [preauth]
|  Nov  5 22:01:37 www sshd[25543]: Received disconnect from 58.16.83.221 port 49510:11: Bye Bye [preauth]
|  Nov  5 22:03:07 www sshd[25721]: Received disconnect from 43.226.148.89 port 32780:11: Bye Bye [preauth]
`-
```
</details>

The changes should be compatible across versions, so you can try to update your sshd config with this one - https://github.com/fail2ban/fail2ban/blob/0.10/config/filter.d/sshd.conf.

**Comment by Spire9** [comment]
Thank you Sebres, the new sshd.conf file did the trick!  
I'm curious why my fail2ban version isn't the latest version?  I thought all my software was running the latest version available...  Except for my Ubuntu 18.04, because when I tried updating to 20.04 my system ran out of memory and bricked :(  

I made a $15 donation for you guys :)  I would encourage anyone getting help on the support page (of any project) to take a moment and donate.  Here's the fail2ban donation page:
https://www.fail2ban.org/wiki/index.php/Fail2ban:Site_support

As a side note, I think more people would go through with donations if they could enter the amount in USD.  Is that something you can setup Sebres?  For those of us that don't know how many CHF equal a US Dollar, we get nervous.  We don't want to accidentally donate the value of a house LOL.

**Comment by sebres** [comment]
> I'm curious why my fail2ban version isn't the latest version? I thought all my software was running the latest version available...

There are 3 possibilities:
- wait for release/upgrade for your distro;
- install from other repo or distro-version (pinning etc.). I don't think fail2ban has any dependency that could cause packages conflicts.
- install from source (and update include configs and install service file manually).

@fail2ban/maintainers I plan to release 0.10.6 (and 0.11.2) soon, can we please upgrade fail2ban distributions.
@yarikoptic forgotten debian? :) 

> I made a $15 donation for you guys

Thank you very much! Appreciated!

> As a side note, I think more people would go through with donations if they could enter the amount in USD. Is that something you can setup Sebres?

We have an "issue" for that #2818 + also github has published its own sponsorship program... maybe we get accomplished all this at some point :)

**Comment by Spire9** [comment]
Thanks.  I hope to see a fail2ban update though the automatic updater soon.  I see as of right now, the version has not updated.  Thanks again for the helpful support Sebres.

**Comment by yarikoptic** [comment]
> @fail2ban/maintainers I plan to release 0.10.6 (and 0.11.2) soon, can we please upgrade fail2ban distributions.
> @yarikoptic forgotten debian? :)

well, you must not be afraid of me going senile: great Debian people took over Fail2Ban in Debian proper, so it is all up-to-date there: http://packages.debian.org/fail2ban shows 0.11.1 in sid(unstable) and bullseye(testing), and updated packaging lives now at https://salsa.debian.org/python-team/applications/fail2ban.git . Buster indeed has only 0.10.2-2.1, so no bugfixes from 0.10.x series -- every upload/diff would need to solve some critical/security issue, etc so it is not possible to just upload 0.10.6 into debian stable.

Backports and NeuroDebian backports are indeed lagging -- there was some tiny bump with automated backporting and I had no time to look into it.  May be would do for 0.11.2 ;)

**Comment by Spire9** [comment]
@yarikoptic , I think this topic servers as the "would need to solve some critical/security issue" you require.  Please work to get Ubuntu users the version we need for a fully functional November 2020.  Thanks.

**Comment by yarikoptic** [comment]
Sorry @Spire9 , I little care NOT about Ubuntu, take to MOTUs if you want something in Ubuntu

**Comment by Spire9** [comment]
> 
> 
> Sorry @Spire9 , I little care NOT about Ubuntu, take to MOTUs if you want something in Ubuntu

The urban dictionary says MOTUS might mean Moron Of The United States.  So I gather you hate the US and Ubuntu/Debian.  And you are taking that hate out on me, a donor that 3 days ago gave $15 to support the good work of the fail2ban team?  I'd be surprised if @fail2ban/maintainers and @sebres feel that is proper conduct.

**Comment by yarikoptic** [comment]
https://wiki.ubuntu.com/MOTU

**Comment by Spire9** [comment]
Holy hell, I just noticed this modified Fail2Ban v0.10.2 is trying to ban my valid logins!  I was just one power outage away from never being able to log in again.  (My home has a dynamic IP, so after a power outage I don't have IGNORE privileges in fail2ban.)

```
2020-11-19 10:56:16,987 fail2ban.filter         [899]: INFO    [sshd] Ignore 123.123.12.123 by ip
2020-11-19 10:56:22,971 fail2ban.filter         [899]: INFO    [sshd] Ignore 123.123.12.123 by ip
2020-11-19 11:00:03,557 fail2ban.filter         [899]: INFO    [sshd] Ignore 123.123.12.123 by ip
```

```
Nov 19 10:56:16 www sshd[12781]: Accepted publickey for root from 123.123.12.123 port 52004 ssh2: RSA SHA256:hfve278974Lj1ExF274oyhs/gmoKHveUVdRHtSgx7y5
Nov 19 10:56:16 www sshd[12781]: pam_unix(sshd:session): session opened for user root by (uid=0)
Nov 19 10:56:17 www systemd-logind[888]: New session 176 of user root.
Nov 19 10:56:17 www systemd: pam_unix(systemd-user:session): session opened for user root by (uid=0)
Nov 19 10:56:22 www sshd[12907]: Accepted publickey for root from 123.123.12.123 port 52005 ssh2: RSA SHA256:hfve278974Lj1ExF274oyhs/gmoKHveUVdRHtSgx7y5
Nov 19 10:56:22 www sshd[12907]: pam_unix(sshd:session): session opened for user root by (uid=0)
Nov 19 10:56:22 www systemd-logind[888]: New session 178 of user root.
Nov 19 11:00:03 www sshd[13463]: Accepted publickey for root from 123.123.12.123 port 52022 ssh2: RSA SHA256:hfve278974Lj1ExF274oyhs/gmoKHveUVdRHtSgx7y5
Nov 19 11:00:03 www sshd[13463]: pam_unix(sshd:session): session opened for user root by (uid=0)
Nov 19 11:00:03 www systemd-logind[888]: New session 179 of user root.
```

**Comment by sebres** [comment]
Hmm... No one of messages from your excerpt should cause a failure in sense of fail2ban.

> I just noticed this modified Fail2Ban v0.10.2 is trying to ban my valid logins! 

What does "modified" mean?
Do you mean that you've used sshd-filter from current 0.10th branch (0.10.6)?

The RE with `<F-MLFGAINED>Accepted \w+</F-MLFGAINED>` looks indeed not compatible to 0.10.2, this option was introduced in 1c1d2cc435d6e8f1eb4a1b60c935a1385a82e295 2 years ago and I guess 0.10.4 or 0.10.5 only.
In this case you have to revert it as before this change, to `<F-NOFAIL>Accepted \w+</F-NOFAIL>`:
```diff
-            ^<F-MLFFORGET><F-MLFGAINED>Accepted \w+</F-MLFGAINED></F-MLFFORGET> for <F-USER>\S+</F-USER> from <HOST>(?:\s|$)
+            ^<F-MLFFORGET><F-NOFAIL>Accepted \w+</F-NOFAIL></F-MLFFORGET> for <F-USER>\S+</F-USER> from <HOST>(?:\s|$)
```
Or even upgrade to 0.10.5.

**Comment by Spire9** [comment]
It's all stock, except for the modification we discussed/implemented in this topic.

https://github.com/fail2ban/fail2ban/issues/2867#issuecomment-723955634
> The changes should be compatible across versions, so you can try to update your sshd config with this one - https://github.com/fail2ban/fail2ban/blob/0.10/config/filter.d/sshd.conf.

And yes, I immediately put the old file back in effect when I discovered the issue.

**Comment by Spire9** [comment]
> Or even upgrade to 0.10.5.

I don't know how.  It's not released.
And as we saw today, the effects of me running something custom could end in total server loss.

**Comment by sebres** [comment]
OK, version [0.10.6](https://github.com/fail2ban/fail2ban/releases/tag/0.10.6) is released now. It also contains debian package now (fail2ban_0.10.6-1.upstream1_all.deb).
0.11 will follow.

**Comment by Spire9** [comment]
Excellent sebres, it's much appreciated!
I have ran the ```apt-get update && apt-get upgrade``` commands a few times since you posted, but it must need some more time to propagate?  I will try again in the days that follow.

**Comment by sebres** [comment]
> ... but it must need some more time to propagate? I will try again in the days that follow.

Nope, nope, nope! 
I'm neither a maintainer of debian, nor of some other distribution (since I have basically lack of time for active development, maintaining would affect it still more)...
So the package I built, is for manual installation only. And this version would probably never be rolled out on your (stable) distribution. 
As @yarikoptic said above, "no bugfixes from 0.10.x series -- every upload/diff would need to solve some critical/security issue, etc so it is not possible to just upload 0.10.6 into debian stable", and I think it is not very different on ubuntu. 
Sure it is unlikely, but so being the upgrade policies there.

So you have the choice:

- either to find some alternate repository you could obtain newer version from (e. g. from newer version of ubuntu or backports, using apt pinning).
- or to install it manually as deb-package:
```bash
cd /tmp/
# 1) download deb package and signature:
wget https://github.com/fail2ban/fail2ban/releases/download/0.10.6/fail2ban_0.10.6-1.upstream1_all.deb \
     https://github.com/fail2ban/fail2ban/releases/download/0.10.6/fail2ban_0.10.6-1.upstream1_all.deb.asc

# 2) check signature (if you want to be sure file is unmodified):
gpg --verify fail2ban_0.10.6-1~upstream1_all.deb.asc fail2ban_0.10.6-1~upstream1_all.deb

# 3) view details of the package:
dpkg -I fail2ban_0.10.6-1.upstream1_all.deb

# 4a) either install package using dpkg (standalone package, don't regard dependencies):
sudo dpkg -i fail2ban_0.10.6-1.upstream1_all.deb
# if the package introduces some "broken" dependencies (I don't think so in case of fail2ban which has few dependencies),
# to fix the unmet dependency issue, run this:
sudo apt -f install

# 4b) or install package using gdebi (that will take care of installation of dependencies):
sudo gdebi fail2ban_0.10.6-1.upstream1_all.deb
# if you want to check anyway whether there are some broken packages and fix them automatically, you can run:
sudo apt -f install
```
- or even to install it manually from source (see README file).

Same is valid for [0.11.2](https://github.com/fail2ban/fail2ban/releases/tag/0.11.2) (if you want to try that, it is totally compatible with a small exception regarding database if you need back to 0.10, see Compatibility section in https://github.com/fail2ban/fail2ban/blob/0.11.2/ChangeLog#L12).
