### ISSUE TITLE
Default jail config contains malicious link

### ISSUE THREAD

**Issue by alexpovel** [fail2ban/fail2ban#2868]
**Do not visit the malicious link discussed below.**

### Environment:

- Fail2Ban version (including any possible distribution suffixes): 0.10.2
- OS, including release name/version: Debian 10/buster
- [x] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

On a fresh install, I went through `/etc/fail2ban/jail.conf` to get a feeling for the software configuration. I noticed Counter Strike (the game) has a section. However, a link contained there leads to a malicious website.

#### Steps to reproduce

Very simple. On a fresh install, do:

```bash
$ grep "www\.cstrike" /etc/fail2ban/jail.conf
# Firewall: http://www.cstrike-planet.com/faq/6
```

#### Expected behavior

Not have a malicious link.
Also, provided the website wasn't malicious, an HTTPS link.

#### Observed behavior

Has a link to a malicious website.

#### Any additional information

Some malicious entity [seems to have taken over the domain](https://steamcommunity.com/app/240/discussions/0/154643720193622649/), 4 years ago! I guess no one noticed for all this time because no one self-hosts CS anymore (you can't self-host CS:GO anyway, which is itself almost 10 years old already).

Googling *cstrike-planet* yields no results pointing to that website, further confirming its demise/ill-intent.

When I visited the link expecting a normal website, NoScript first blocked it entirely. After unblocking (a normal process), uBlock Origin protection jumped in (usually never happens). Noped out at that point. So, of course, **do not** visit that website.

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
Oops! I removed the link for all versions starting from 0.9.
Thx for the report!
