### ISSUE TITLE
Logpath is ignored if default backend is systemd

### ISSUE THREAD

**Issue by basti12203** [fail2ban/fail2ban#2871]
fail2ban 0.10.2 debian
jail.d/local.conf:
`[DEFAULT]`
`backend  = systemd`

`[roundcube-auth]`
`logpath  = /var/log/roundcube/errors`

When set the backend in the jail it is work as expected.
In thing it is better to ignore default backend when a logpath is set.

Whats your opinion?

**Comment by polyzen** [comment]
You changed the default backend from `auto` to `systemd`. `logpath` is not used by that backend:
https://github.com/fail2ban/fail2ban/blob/f518d42c590f4ea3d8632937dc6ad7e875419b00/man/jail.conf.5#L288-L301

Also see:
https://github.com/fail2ban/fail2ban/blob/adbfdc222d6fe00f6f3e1e5e32adaf928c5685ab/config/jail.conf#L430-L431

**Comment by sebres** [comment]
If your default backend is systemd (so monitoring journal), you have to specify one of the file-related backends (or use `auto` to automatically select it by availability) **for all the jails** which are expecting to monitor log-files:
```diff
 [roundcube-auth]
 logpath = /var/log/roundcube/errors
+backend = auto
```
