### ISSUE TITLE
Why I cannot block ipv6

### ISSUE THREAD

**Issue by Rhandyx** [fail2ban/fail2ban#2883]
I have install latest version 0.11.2
I try to enable 
apache-auth

I set in jail.conf
[apache-auth]
enable=true
ports=80,443

I try to ban my ip but is not working 

banaction=iptables-multiport

Here is the output of my iptables

[ip6tables.txt](https://github.com/fail2ban/fail2ban/files/5612923/ip6tables.txt)

**Comment by sebres** [comment]
1. it is `enabled` not `enable`:
```diff
-enable=true
+enabled=true
```
2. please provide an excerpt of `fail2ban-client -d | grep apache-auth`, as well as an excerpt from the related log-file with the messages corresponding your attempts.
3. If "my ip" means own server IP, it can be ignored by `ignoreself` (default true) or `ignoreip`.

**Comment by Rhandyx** [comment]
Hi
i just write wrong here enable instead of enabled
The ip i try to ban is ipv6 from my home and not from server
ipv4 ban works

I have attach ip6tables,txt for show iptables rules created for fail2ban

here the output` fail2ban-client -d | grep apache-auth`

```
['add', 'apache-auth', 'auto']
['set', 'apache-auth', 'usedns', 'warn']
['set', 'apache-auth', 'prefregex', '^\\[\\]\\s\\[(:?error|(?!evasive)\\S+:\\S+)\\]( \\[pid \\d+(:\\S+ \\d+)?\\])? \\[client <HOST>(:\\d{1,5})?\\] (?:AH\\d+: )?<F-CONTENT>.+</F-CONTENT>$']
['multi-set', 'apache-auth', 'addfailregex', ['^client (?:denied by server configuration|used wrong authentication scheme)\\b', '^user (?!`)<F-USER>(?:\\S*|.*?)</F-USER> (?:auth(?:oriz|entic)ation failure|not found|denied by provider)\\b', '^Authorization of user <F-USER>(?:\\S*|.*?)</F-USER> to access .*? failed\\b', '^([A-Z]\\w+: )?user <F-USER>(?:\\S*|.*?)</F-USER>: password mismatch\\b', "^([A-Z]\\w+: )?user `<F-USER>(?:[^']*|.*?)</F-USER>' in realm `.+' (auth(?:oriz|entic)ation failure|not found|denied by provider)\\b", '^([A-Z]\\w+: )?invalid nonce .* received - length is not\\b', "^([A-Z]\\w+: )?realm mismatch - got `(?:[^']*|.*?)' but expected\\b", "^([A-Z]\\w+: )?unknown algorithm `(?:[^']*|.*?)' received\\b", "^invalid qop `(?:[^']*|.*?)' received\\b", '^([A-Z]\\w+: )?invalid nonce .*? received - user attempted time travel\\b', '^(?:No h|H)ostname \\S+ provided via SNI(?:, but no hostname provided| and hostname \\S+ provided| for a name based virtual host)\\b']]
['set', 'apache-auth', 'datepattern', '{^LN-BEG}']
['set', 'apache-auth', 'maxmatches', 3]
['set', 'apache-auth', 'maxretry', 3]
['set', 'apache-auth', 'logencoding', 'auto']
['set', 'apache-auth', 'ignorecommand', '']
['set', 'apache-auth', 'findtime', '10m']
['set', 'apache-auth', 'bantime', '10m']
['set', 'apache-auth', 'addlogpath', '/var/log/apache2/error.log', 'head']
['set', 'apache-auth', 'addaction', 'iptables-multiport']
['multi-set', 'apache-auth', 'action', 'iptables-multiport', [['actionunban', '<iptables> -D f2b-apache-auth -s <ip> -j <blocktype>'], ['actionflush', '<iptables> -F f2b-apache-auth'], ['actionstop', '<iptables> -D INPUT -p tcp -m multiport --dports http,https -j f2b-apache-auth\n<iptables> -F f2b-apache-auth\n<iptables> -X f2b-apache-auth'], ['actionstart', '<iptables> -N f2b-apache-auth\n<iptables> -A f2b-apache-auth -j RETURN\n<iptables> -I INPUT -p tcp -m multiport --dports http,https -j f2b-apache-auth'], ['actionban', '<iptables> -I f2b-apache-auth 1 -s <ip> -j <blocktype>'], ['actioncheck', "<iptables> -n -L INPUT | grep -q 'f2b-apache-auth[ \\t]'"], ['iptables', 'iptables <lockingopt>'], ['lockingopt', '-w'], ['blocktype?family=inet6', 'REJECT --reject-with icmp6-port-unreachable'], ['protocol', 'tcp'], ['name', 'apache-auth'], ['chain', '<known/chain>'], ['returntype', 'RETURN'], ['iptables?family=inet6', 'ip6tables <lockingopt>'], ['blocktype', 'REJECT --reject-with icmp-port-unreachable'], ['actname', 'iptables-multiport'], ['port', 'http,https']]]
['start', 'apache-auth']

```

**Comment by sebres** [comment]
So basically it bans the IPv6 (2001:...:4e53you is your, and you see also `Ban 2001:...:4e53` in fail2ban.log), but the ban does not really block (you are still able to connect to the server)?

It can have several reasons:
- firewall or net-filter issues (e. g. some rules allowing established connections)
- keep-alive on apache side (does not cause close on auth issues)
etc.

I cannot tell you what exactly avoids proper working of banning, it looks to me like some 3rd party issue on your side.

**Comment by Rhandyx** [comment]
Can you help found the issue? 
I can paste here all iptables rules and ports on jail.

**Comment by sebres** [comment]
Well, I could try...

**Comment by Rhandyx** [comment]
Not the perfect solution but I have block all ipv6 using ufw firewall and now logs only have ipv4. In addiction i have configure cloudflare match action with cloudflare api key, now the fail2ban block on cloudflare and in Iptables.
