### ISSUE TITLE
badips action should be removed

### ISSUE THREAD

**Issue by vinc17fr** [fail2ban/fail2ban#2889]
badips.com is no longer active, and unfortunately fail2ban does no report the errors (if one doesn't look at the logs, one doesn't notice them). See

- https://www.webhostingtalk.com/showthread.php?t=1786089

- https://www.spinics.net/lists/fail2ban/msg02399.html

Since badips.com has been down for more than a year, the corresponding action should be removed.

**Comment by sebres** [comment]
Thx for notice!

> unfortunately fail2ban does no report the errors (if one doesn't look at the logs, one doesn't notice them). 

How you expect a service working in background should report the errors (outside of logs)? :)

> Since badips.com has been down for more than a year, the corresponding action should be removed.

Probably. The one thing I would like to note here is, this action can be good example or template for new actions for some alternatives  But we have git, so one could still find it in previous revisions.

**Comment by vinc17fr** [comment]
> How you expect a service working in background should report the errors (outside of logs)? :)

There could be an option to send a mail in case of error. For instance, that's what `cron` does by default.

> > Since badips.com has been down for more than a year, the corresponding action should be removed.
>
> Probably. The one thing I would like to note here is, this action can be good example or template for new actions for some alternatives But we have git, so one could still find it in previous revisions.

One possibility would be to comment out the current actionban line, and to add one that does nothing if order to avoid unnoticed errors.

**Comment by bunder2015** [comment]
Hello, I too noticed badips started having issues in the fall, only to go completely offline around November/December.  Since then I've been working on something functionally similar, and I would like to include fail2ban integration.  Is there any reference documentation for adding services for downloading lists and reporting ips?  Thanks

**Comment by sebres** [comment]
Well, I'm afraid excepting the regular manuals it were the source code of that action only. @benrubson was working in #2603 (and before), so possibly he could help you there also. Or if you have particular issue, you can ask right here (or in new issue, PR), we'll try to answer your questions.
And fail2ban integration must not be necessarily an action, there are several ways depending on initial situation and the intention.

**Comment by sebres** [comment]
done in 6f4b6ec8ccdb68c75aec8225d8fa2b03ed19f320
