### ISSUE TITLE
Create hook for modifying fail notification in syslog

### ISSUE THREAD

**Issue by sbesl** [fail2ban/fail2ban#2892]
For banning subnets/ip ranges/CIDR blocks, one of the main problems is determining whether a CIDR block should be banned. Opinions differ on how to determine the block from the host. To allow user to do this however they see fit, it would work neatly if it'd be possible to hookup a shell command / script to write the syslog message or to format the string that's written to syslog.

This impacts processLineAndAdd() in fail2ban/fail2ban/server/filter.py

**Comment by sebres** [comment]
Don't follow what you mean as a hook or else what exactly "determining whether a CIDR block should be banned" together with the hook should mean.
If you mean a possibility to match subnet in log - it is already implemented in #2559.
As regards the main problem - it is not really that what you're trying to describe: the main issue is a maintenance of subnets as proper ID range in fail- and ban-managers, regardless how the expanding of IP to subnet happens (automatic or using some hook). Without to solve this firstly no one hook would help to implement subnet banning properly.

Anyway, all the subnet matters are and must be discussed further in #927.
