### ISSUE TITLE
Ban country or region - how to?

### ISSUE THREAD

**Issue by Roberto6969** [fail2ban/fail2ban#2894]
Hello,
I can't find out steps how to ban for example one country (particularly China).
Here is described:
Follow the instructions at http://ip2location.com/developers/python to install the IP2Location Python library.
but instruction from that page has an error (in "python setup.py build")
Is this the right way to setup baning a country or is any other way?

Thank You!

**Comment by sebres** [comment]
At the moment there is no possibility to consider geoip info in banning process (excepting probably `ignorecommand` which could check country of IP, or some special handling from logging process, see https://github.com/fail2ban/fail2ban/issues/2443#issuecomment-500734470 for example).

There are several experimental branches of me containing geoip support, but they are not yet merged for several reasons (inclusive lack of time).

Duplicate of #1854.
