### ISSUE TITLE
Jellyfin fail2ban Regex Filter won't matched

### ISSUE THREAD

**Issue by gotton** [fail2ban/fail2ban#2912]
Hello,

I'm trying to build a Fail2ban filter for jellyfin but i can't get it to work.

Here is the entry log :
`[2021-01-17 23:02:16.383 +01:00] [INF] Authentication request for "***" has been denied (IP: "**.**.**.**").`

So i tried to build a filter :
`[Definition]
failregex = ^\[INF\] Authentication request for ".*" has been denied \(IP: "<HOST>"\).$
ignoreregex = 192.168.1.*`

when i tried my filter with fail2ban-regex with a log that i'm certain contained this authentification issue, i get :

`Failregex: 0 total
Ignoreregex: 105 total
|-  #) [# of hits] regular expression
|   1) [105] 192.168.1.*
`-

`Date template hits:
|- [# of hits] date format
|  [2718] {^LN-BEG}ExYear(?P<_sep>[-/.])Month(?P=_sep)Day(?:T|  ?)24hour:Minute:Second(?:[.,]Microseconds)?(?:\s*Zone offset)?
`-

`Lines: 3288 lines, 105 ignored, 0 matched, 3183 missed
[processed in 0.23 sec]
Ignored line(s): too many to print.  Use --print-all-ignored to print all 105 lines
Missed line(s): too many to print.  Use --print-all-missed to print all 3183 lines`

So if i'm not mistaking, the regex is correctly written (maybe not effective but i do not get any error), the date template is ok, but there is no match.

Maybe my filter is not well written ?

If anybody could give me some help ?

Thanks.

**Comment by sebres** [comment]
> So if i'm not mistaking, the regex is correctly written

Well, not really - the fail2ban cut the part of timestamp from the line out before it applies failregex, but in your case the brackets and space still remain, so use something like `(?:\[\]\s+)?` to extend the RE:
```diff
-^\[INF\] Authentication request for ".*" has been denied \(IP: "<HOST>"\).$
+^(?:\[\]\s+)?\[INF\] Authentication request for "[^"]*" has been denied \(IP: "<HOST>"\)\.$
```

> ignoreregex = 192.168.1.*

Correct (fewer vulnerable) would be something like `192\.168\.1\.\d+` or even `\(IP: "192\.168\.1\.\d+"\)\.$`...
But better don't do that. Parameter `ignoreregex` is for completely other purposes, better set (or extend) `ignoreip` in related jail.

**Comment by gotton** [comment]
Ok thanks.

I remove the ignoregex (that i had already set in fail2ban anyway).

I tried your proposal and i get this error :
`ERROR: Unable to compile regular expression '+^(?:\[\]\s+)?\[INF\] Authentication request for "[^"]*" has been denied \(IP: "(?:\[?(?:(?:::f{4,6}:)?(?P<ip4>(?:\d{1,3}\.){3}\d{1,3})|(?P<ip6>(?:[0-9a-fA-F]{1,4}::?|::){1,7}(?:[0-9a-fA-F]{1,4}|(?<=:):)))\]?|(?P<dns>[\w\-.^_]*\w))"\)\.$'`

Maybe it's the - in the timestamp that is causing issue. i tried +^(?:\[\]**\-**\s+)? but i'm guessing its not that simple.

**Comment by sebres** [comment]
no first "+" you see in diff is a mark for add line (in opposite to "-" for remove line), it is not a part of regex, you have to remove it of course.

**Comment by gotton** [comment]
Perfect :

`Lines: 3288 lines, 0 ignored, 3 matched, 3285 missed`

Thanks a lot
