### ISSUE TITLE
Database is too large

### ISSUE THREAD

**Issue by richman1000000** [fail2ban/fail2ban#2918]
_We will be very grateful, if your problem was described as completely as possible,
enclosing excerpts from logs (if possible within DEBUG mode, if no errors evident
within INFO mode), and configuration in particular of effected relevant settings
(e.g., with ` fail2ban-client -d | grep 'affected-jail-name' ` for a particular
jail troubleshooting).
Thank you in advance for the details, because such issues like "It does not work" 
alone could not help to resolve anything!
Thanks! (remove this paragraph and other comments upon reading)_

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes): Fail2Ban v0.10.2
- OS, including release name/version:  debian 10.7
- [x ] Fail2Ban installed via OS/distribution mechanisms
- [ x] You have not applied any additional foreign patches to the codebase
- [ x] Some customizations were done to the configuration (provide details below is so)

### The issue:

database is keeps growing too big, fail2ban consumes a lot of CPU and memory with size of database

#### Steps to reproduce
install in WHITE IP interface.
set up ban time to 1 year
#### Expected behavior
Most of the time we don't need to know why some IP was banned. especially for SSH bans.
line in configuration which will allow us to choose whether we need or not a recording of "data" column in table "bans"

#### Observed behavior
database grows really large cause column "data" have too much information

![image](https://user-images.githubusercontent.com/9943374/106255832-9356ff00-622b-11eb-8207-2f9d99ba0230.png)
 
#### Any additional information
as a workaround I used sqlight3 command and purged column manually 

`update bans set data=NULL`

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
It is depending on the `maxretry` value specified for the jail, but this can be solved with another option `dbmaxmatches` (implemented in #2402), which can help to hold database slimmer. In newer version it is 5 by default (so saves maximal 5 last noticed failures per ticket).
Also note there was an issue (#1267) with purge (resolved in 0.11), so the database did not clean periodically (therefore grows).
The "fix" for that would be either to switch to 0.11 or as workaround periodically purge it manually (in cron or timer), see https://github.com/fail2ban/fail2ban/issues/1316#issuecomment-178815912.

**Comment by richman1000000** [comment]
Well, would prefer to not record in 1st place
This is just a work around.

**Comment by sebres** [comment]
> Well, would prefer to not record in 1st place

Well, in mentioned newer versions following entries would do exactly that (not record at all):
`fail2ban.local:`
```ini
[DEFAULT]
dbmaxmatches = 0
```
`jail.local:`
```ini
[DEFAULT]
maxmatches = 0
```
I don't know what you're calling a workaround.

**Comment by richman1000000** [comment]
`maxmatches = 0` doesn't affect content of  "DATA" column in table "bans".
I actually don't want to limit `maxmatches `

By reducing DATABASE size reduces memory consumption and CPU consumption without limiting speed of fail2ban actual performance during "restoring bans" process

![image](https://user-images.githubusercontent.com/9943374/106423154-ea99e100-6470-11eb-9bcf-33733cd5905d.png)

in practice I need only "ip" and "timeofban" to be filled.
![image](https://user-images.githubusercontent.com/9943374/106423611-d4d8eb80-6471-11eb-84d5-7b34e34ad0a0.png)


`I don't know what you're calling a workaround.`
This is why I think `maxmatches  `and direct `sqlite3 ` cleaning are workarounds.

The true solution of this behavior is possibility  to switch recording into "DATA" and "JAIL" column on/off only in case necessary.

**Comment by sebres** [comment]
> maxmatches = 0 doesn't affect content of "DATA" column in table "bans".

This is false, `maxmatches = 0` would avoid that fail2ban accumulates logged failure messages in the ticket in memory (but so it would restrict saving it to db too), `dbmaxmatches = 0` is affecting database only (but it is a jail independent setting).
Both would cause that the DATA column contains only few info about the ticket.

> I actually don't want to limit maxmatches

Then specify `dbmaxmatches = 0` only.

> The true solution of this behavior is possibility to switch recording into "DATA" and "JAIL" column on/off only in case necessary.

You can completely disable database (just it is not advisable at least for 0.11 if incremental banning is enabled, because it is used for searching for bad ips). As for jail column it is expected to distinguish the tickets of different jails (if you have only one jail, this doesn't mean other people using it also with single jail only). By the way, newest version of fail2ban would get completely different schema (where jail is only an ID) and failures (if not disabled) are stored in different table also.

**Comment by MrPeteH** [comment]
Something is completely undocumented AFAIK:
* ASSUME: I want to use Incremental banning; my formula allows up to 15 bans which produces an 8 month ban time.
* I don't need a super huge database. In particular, the "data" field is only needed for most-recent bans

QUESTIONS:
* Does setting dbmaxmatches = 0 impact my formula?
* Does setting maxmatches = 0 impact my formula?
* Does purging the sqlite3 database impact my formula?
ASSUME I will have a number of reboots in the 8 month max-ban timeframe.

**Comment by sebres** [comment]
> Does setting dbmaxmatches = 0 impact my formula?
Does setting maxmatches = 0 impact my formula?

Answer is "No" for 2 first of your questions.
- `dbmaxmatches` holds small the database (no matches stored there)
- `maxmatches` holds small the fail manager list (the memory) - no matched lines are stored in memory, but one cannot use `<matches>` tag in actions.

> Does purging the sqlite3 database impact my formula?

Conditionally - fail2ban would not know the "bad" intruders anymore and those last bancount (how many times they were already banned), so it'd start to count from 1 for all IPs. All that regardless a reboots (known as bad IPs are searching in database only, not in memory).

Note that fail2ban has also an automatic purge function, which would remove non-persistent bans those starttime of ban exceeds purgeage and last bantime 3 times exceeds purgearge.
