### ISSUE TITLE
banned ip can log in true password !

### ISSUE THREAD

**Issue by minivipers** [fail2ban/fail2ban#2923]
2021-01-31 20:34:49,934 fail2ban.filter         [36080]: INFO    [sshd] Found xx.43.229.72 - 2021-01-31 20:34:49
2021-01-31 20:34:50,635 fail2ban.actions        [36080]: NOTICE  [sshd] Ban xx.43.229.72
2021-01-31 20:36:35,226 fail2ban.filter         [36080]: INFO    [sshd] Found xx.43.229.72 - 2021-01-31 20:36:35
2021-01-31 20:36:35,480 fail2ban.actions        [36080]: WARNING [sshd] xx.43.229.72 already banned

I have tested fail2ban with 2 ssh to portforwarded linux 20.04 LTS system

one of shh I opened " sudo tail -f /var/log/fail2ban.log " to see the action.
the IP above xx.43.229.72 is my cell phone and i tried multiple access by typing wrong password. I configure max_entry=1 and duration=1000d

however I typed true password on my cellphone and success to log in

Should my cellphone ip banned until the time ended...
sould not be supposed to ban my ip even if i type true password?

**Comment by sebres** [comment]
If you see `[sshd] Ban <IP>`, the ban takes place and `already banned` signalling you that something is not correct either with your banning action of the jail or with your net-filter subsystem.

Also note https://github.com/fail2ban/fail2ban/issues/2798#issuecomment-669837095, https://github.com/fail2ban/fail2ban/issues/2698#issuecomment-617336143 and other similar issues with `Already banned`...

Shortly - if you see corresponding entries in your net-filter or net-subsystem (e. g. iptables), fail2ban works as expected and that is your configuration what avoids correct banning.
Check the related iptables entries (INPUT chain has correct reference to f2b-sshd, it refers to a correct port, and f2b-sshd chain contains the IP)...
