### ISSUE TITLE
Fail2ban on MacOS Mojave (10.14.6)

### ISSUE THREAD

**Issue by ifuchs** [fail2ban/fail2ban#2930]
I would like to run fail2ban on MacOS (v10.14.6). Brew install fail2ban worked fine but I am unclear as to whether I need more than /usr/local/etc/jail.local. Also, does anyone have a sample jail.local for MacOS which will block ssh authentication failures?

**Comment by sebres** [comment]
> I am unclear as to whether I need more than /usr/local/etc/jail.local

Hmm... do you mean `etc/fail2ban/jail.local` either?

> does anyone have a sample jail.local for MacOS which will block ssh authentication failures?

In principle you have to find the log-file where sshd is actually logging on your system (and set it in jail.local for sshd jail as `logpath`).
Note https://stackoverflow.com/questions/43382825/where-to-find-sshd-logs-on-macos-sierra, it is for Sierra, but probably can be helpful anyway.
You can also check the filter with `fail2ban-regex /path/to/sshd.log sshd` whether you'd find some matches.
If it is either a systemd journal (no idea mojave using that, you could try `journalctl -u sshd`), then you have to install `python-systemd` or `python3-systemd` package (depending on your version fail2ban was installed, check `fail2ban-python --version`) and set `backend = systemd` in `jail.local` for sshd jail.
To check the filter use `fail2ban-regex systemd-journal sshd` then.

If it is some new style (e. g. unified logging format), so you would not find any match with default filter setting, please provide the excerpt of sshd-log here.

That's it as for the filter.

Now you'd need to set a proper banning action (depending on firewall or net-filter subsystem you use or availability for mojave). I guess it would be [pf](https://github.com/fail2ban/fail2ban/blob/0.10/config/action.d/pf.conf).
But normally it must be already prepared for you by maintainers (depending on repository you installed fail2ban from).
See for `banaction` in `jail.conf` and in include-file specified in includes section (`before = paths-*.conf`), or use `fail2ban-client -d | grep action` to find or check which is configured by default.

If you have specified another port for sshd (or you have some other services listening on other ports with openssh), you have to set it in jail also.

So your jail.local may look like this:
```ini

[DEFAULT]
# default banning actions:
banaction = pf[actiontype="<multiport>"]
banaction_allports = pf[actiontype="<allports>"]

[sshd]
# set proper path to sshd log:
logpath = /path/to/sshd.log
# uncomment following line if it is systemd-journal:
#backend = systemd
# uncomment following line if you want aggressive banning:
#mode = aggressive

# to overwrite default ban-action:
#banaction = pf[actiontype="<multiport>"]
# to ban allports use this instead of "<multiport>":
#banaction = pf[actiontype="<allports>"]

# uncomment following line and set it to the port(s) sshd service(s) listening (comma-separated):
#port = ssh

enabled = true
```
