### ISSUE TITLE
Python 3.10ImportError: cannot import name 'MutableMapping' from 'collections'

### ISSUE THREAD

**Issue by hobbes1069** [fail2ban/fail2ban#2931]
fail2ban 0.11.2 on Fedora Rawhide

TLDR:
bpo-37324: Remove deprecated aliases to Collections Abstract Base Classes
from the collections module.

https://docs.python.org/3.10/whatsnew/changelog.html#python-3-10-0-alpha-5

Full details:
https://bugzilla.redhat.com/show_bug.cgi?id=1926201

**Comment by sebres** [comment]
Looks like it is restriction of alpha 5 only (works with alpha 4), trying to cover that now (GH actions seem to support this python version now):
https://github.com/fail2ban/fail2ban/runs/1856010598?check_suite_focus=true

OK, I'll try to fix it soon.

**Comment by sebres** [comment]
Fixed now in branch [py-3-10-alpha-5](https://github.com/fail2ban/fail2ban/compare/ea26509594a3220b012071604d73bb42d0ecae2c...py-3-10-alpha-5), see https://github.com/fail2ban/fail2ban/runs/1856355540?check_suite_focus=true...
(I guess, it could be pretty simply the matter of `2to3`, but OK since it is easy to fix on our side and 2.x is completely outdated).

I'll rebase it later to 0.10/0.11 (just for completion) and reintegrate it to master.

By the way, which version will be delivered to Fedora Rawhide? 0.11.x or 1.0 (if it becomes released)?

**Comment by hobbes1069** [comment]
Rawhide (future 34 release) will be updated to the latest release when it becomes available. Will any manual porting to 1.0 be required? That would affect whether I update other releases (32 & 33)

**Comment by sebres** [comment]
OK, good to know.

> Will any manual porting to 1.0 be required?

Dunno right now (should wait before release)... There are 2 small (potential) incompatibilities right now: https://github.com/fail2ban/fail2ban/blob/ea26509594a3220b012071604d73bb42d0ecae2c/ChangeLog#L13-L18

But this list can grow before it gets released.

**Comment by hobbes1069** [comment]
Ok, worst case I only update Rawhide. Actually f34 is going to branch soon so it most likely would wind up in Fedora 35.

**Comment by sebres** [comment]
rebased to 0.10 and merged in 0.10/0.11/1.0 (294ec73f629d0e29cece3a1eb5dd60b6fccea41f etc)

**Comment by nPHYN1T3** [comment]
Had some issues building but got it however now it kicks out...
Mar 16 15:20:34 host fail2ban-server[461555]: ERROR: No module named 'ConfigParser'

**Comment by sebres** [comment]
The description is there - https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually#manual-installation-from-source
Shortly - don't forget 2to3 step... and it shall be invoked on a clean copy (if you already tried to build/setup, it'd create some files, so better delete it and clone or unzip again).

**Comment by nPHYN1T3** [comment]
Sorry man this is all disjointed. The readme lacks this stuff and the steps/flow aren't overly laid out.

Running in a clean build directory

./fail2ban-2to3 
RefactoringTool: Skipping optional fixer: buffer
RefactoringTool: Skipping optional fixer: idioms
RefactoringTool: Skipping optional fixer: set_literal
RefactoringTool: Skipping optional fixer: ws_comma
RefactoringTool: No changes to bin/fail2ban-client
Traceback (most recent call last):
  File "/usr/bin/2to3", line 5, in <module>
    sys.exit(main("lib2to3.fixes"))
  File "/usr/lib/python3.10/lib2to3/main.py", line 263, in main
    rt.refactor(args, options.write, options.doctests_only,
  File "/usr/lib/python3.10/lib2to3/refactor.py", line 690, in refactor
    return super(MultiprocessRefactoringTool, self).refactor(
  File "/usr/lib/python3.10/lib2to3/refactor.py", line 286, in refactor
    self.refactor_file(dir_or_file, write, doctests_only)
  File "/usr/lib/python3.10/lib2to3/refactor.py", line 731, in refactor_file
    return super(MultiprocessRefactoringTool, self).refactor_file(
  File "/usr/lib/python3.10/lib2to3/refactor.py", line 326, in refactor_file
    input, encoding = self._read_python_source(filename)
  File "/usr/lib/python3.10/lib2to3/refactor.py", line 322, in _read_python_source
    return f.read(), encoding
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 24: invalid start byte
Fail!

**Comment by sebres** [comment]
> Running in a clean build directory

Doh!... this isn't clean. I guess you still have bin/fail2ban-python, which isn't a part of source (it is the link to python created by setup process).
Ensure it is clean an repeat.

**Comment by nPHYN1T3** [comment]
Again order is not straight forward with steps jumping around. I make a clean build, built, then did the 2to3 which is the 2to3 is the build not another step of the build. That completed but...

systemctl status fail2ban.service
× fail2ban.service - Fail2Ban Service
     Loaded: error (Reason: Unit fail2ban.service failed to load prop
erly, please adjust/correct and reload service manager: Device or resource busy)
     Active: failed (Result: exit-code) since Wed 2022-03-16 16:03:07
 CST; 11min ago
       Docs: man:fail2ban(1)
   Main PID: 463466 (code=exited, status=255/EXCEPTION)
        CPU: 58ms

**Comment by sebres** [comment]
> I make a clean build, built, then did the 2to3

Oh God! Read the link I provided above.
First ./fail2ban-2to3, then setup.

**Comment by nPHYN1T3** [comment]
I did read it but after the fact, normally the build readme will have those things. That said even the links above have things hidden in drop arrows and other links.

So while it built it's not working so I've going over things trying to find out why it's no longer banning offenders.

**Comment by sebres** [comment]
I'll add it to the Readme, but...
When people don't even follow [direct instructions](https://github.com/fail2ban/fail2ban/issues/2931#issuecomment-1069663402) we can put it on hundred places with similar success.
Previously step 2to3 was a part of setup process, but it was removed due to compat reasons with new setuptools, #3098. I could check whether the setup may reject build or install unless become converted properly.

**Comment by elderlabs** [comment]
Currently installing from `testing` on Debian. After running `systemctl restart fail2ban`, seems to work fine. Obviously, some are weary of installing from testing, but those that know how shouldn't have much issue at all.
