### ISSUE TITLE
Many errors and failed tests from fail2ban-testcases

### ISSUE THREAD

**Issue by hadallen** [fail2ban/fail2ban#2933]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): `0.11.2`
- OS, including release name/version: `Arch Linux ARM aarch64 5.4.79-2-v8 on Raspberry Pi 4 Model B Rev 1.2`
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

Many errors and failed tested when `fail2ban-testcases` is used. 
sshd jail is active and working without issue, and with workaround, caddy jail works too
First discovered when `fail2ban-regex` used to test failregex in caddy.conf

#### Steps to reproduce
run `fail2ban-testcases`

or test a regex conf on a logfile:
`fail2ban-regex access.log /etc/fail2ban/filter.d/caddy.conf``

#### Expected behavior
`fail2ban-regex` (when detecting dates) and `fail2ban-testcases` run without error

#### Observed behavior
`fail2ban-regex` will pass if I supply a few lines from the log into the command directly. it will fail if it is reading from the log file
`fail2ban-regex` will fail if datepattern is matched (declaring a blank or unmatched datepattern will run without error)

#### Any customizations done to /etc/fail2ban/ configuration
caddy.conf:
```
[Definition]
failregex = X-Forwarded-For":\["<HOST>.* HTTP/[0-9]\.[0-9]\\" 401
ignoreregex =
datepattern =
```

caddy jail in jail.local:
```
[caddy]
enabled = true
filter = caddy
logpath = /srv/http/.docker/caddy/logs/access.rutorrent.log
banTime = 1d
findTime = 120m
maxretry = 5
```

#### Relevant lines from monitored log files in question:

**[I made a gist of the fail2ban-testcases output](https://gist.github.com/hadallen/049f516029d3412544cc28b1bdd02f50)**

And this is the error from datedetector.py when I run ```fail2ban-regex``` with datepattern matches
```
Traceback (most recent call last):
  File "/usr/bin/fail2ban-regex", line 34, in <module>
    exec_command_line()
  File "/usr/lib/python3.9/site-packages/fail2ban/client/fail2banregex.py", line 836, in exec_command_line
    if not fail2banRegex.start(args):
  File "/usr/lib/python3.9/site-packages/fail2ban/client/fail2banregex.py", line 776, in start
    self.process(test_lines)
  File "/usr/lib/python3.9/site-packages/fail2ban/client/fail2banregex.py", line 584, in process
    line_datetimestripped, ret, is_ignored = self.testRegex(line)
  File "/usr/lib/python3.9/site-packages/fail2ban/client/fail2banregex.py", line 456, in testRegex
    found = self._filter.processLine(line, date)
  File "/usr/lib/python3.9/site-packages/fail2ban/server/filter.py", line 613, in processLine
    timeMatch = self.dateDetector.matchTime(line)
  File "/usr/lib/python3.9/site-packages/fail2ban/server/datedetector.py", line 368, in matchTime
    (line[distance] == self.__lastPos[2] and not self.__lastPos[2].isalnum())
IndexError: string index out of range
```

**Comment by sebres** [comment]
see https://github.com/fail2ban/fail2ban/issues/2904#issuecomment-754042663 and #2915
