### ISSUE TITLE
wishlist: filter.d/sshd.conf should filter for "Unable to negotiate"

### ISSUE THREAD

**Issue by oz42** [fail2ban/fail2ban#2934]
Version 0.11.2
FreeBSD 12.2-RELEASE-p3

jail.d/ssh-ipfw.local:
[ssh-ipfw]
enabled = true
mode = aggressive
filter = sshd
action = myipfw[name=SSH, port=ssh, protocol=tcp]
         mail-whois[name=SSH]
logpath = /var/log/auth.log
findtime = 4h
maxretry = 2
bantime = 1d

action.d/myipfw.conf essentially contains "actionban = ipfw table 3 add <ip>"

Right now, fail2ban ignores log lines containing "Unable to negotiate". It would be great if these log lines also triggered a banip.

**Comment by sebres** [comment]
See https://github.com/fail2ban/fail2ban/issues/2525#issuecomment-530763577
Shortly it is not an authentication failure, so considering only in mode `aggressive` (or `extra`).
