### ISSUE TITLE
Failregex for iptables logs

### ISSUE THREAD

**Issue by robijas** [fail2ban/fail2ban#2937]
Hello, im sure that this question exist already but i cant find it, sorry.
Im trying to find failregex for fail2ban from iptables log shown below:

`Feb 13 14:12:19 server kernel: [2262787.219904] IPTables-Rejected: IN=eno1 OUT= MAC=a4:bf:01:14:df:0a:00:ff:ff:ff:ff:fe:08:00 SRC=162.159.136.232 DST=11.22.33.44.55 LEN=39 TOS=0x00 PREC=0x00 TTL=111 ID=56338 PROTO=UDP SPT=40472 DPT=27777 LEN=19 `

**Comment by sebres** [comment]
Here is an example - https://github.com/fail2ban/fail2ban/issues/1945#issuecomment-362247222
If you cannot rewrite the RE for other prefix, e. g. for `IPTables-Rejected`, or has some questions, don't hesitate to ping me here, I'd try to help.

**Comment by sebres** [comment]
This one would work:
```
^\s*\S+\s+kernel:(?: +\[[^\]]+\])? IPTables-Rejected: (?:\b(?:IN=\w+|OUT=|(?:(?!OUT=|IN=)[A-Z]+=[^ \[]*)+) )*SRC=<HOST> DST=\S+
```
If you need it for more than 1 log-prefix (for instance also to consider `IPTables-Dropped` or `IPTables-Invalid`), just extend it like:
```diff
- ^\s*\S+\s+kernel:(?: +\[[^\]]+\])? IPTables-Rejected: (?:\b(?:IN=\w+|OUT=|(?:(?!OUT=|IN=)[A-Z]+=[^ \[]*)+) )*SRC=<HOST> DST=\S+
+ ^\s*\S+\s+kernel:(?: +\[[^\]]+\])? IPTables-(?:Rejected|Dropped|Invalid): (?:\b(?:IN=\w+|OUT=|(?:(?!OUT=|IN=)[A-Z]+=[^ \[]*)+) )*SRC=<HOST> DST=\S+
```

**Comment by robijas** [comment]
works, ty for fast responce
