### ISSUE TITLE
Wondering why legit ssh users get banned

### ISSUE THREAD

**Issue by jurgenhaas** [fail2ban/fail2ban#2938]
Since we've updated from 0.10.4 to 0.11.2 last week we get several complaints from legit ssh users, that they get banned, e.g. when they do some git push or svn commit commands, which go over SSH.

What we see in the logs is only valid SSH communication, but still the ban.

**fail2ban.log**

```
2021-02-12 22:47:34,295 fail2ban.filter         [23358]: INFO    [sshd] Found 1.2.3.4 - 2021-02-12 22:47:34
2021-02-12 22:47:39,714 fail2ban.filter         [23358]: INFO    [sshd] Found 1.2.3.4 - 2021-02-12 22:47:39
2021-02-12 22:47:45,154 fail2ban.filter         [23358]: INFO    [sshd] Found 1.2.3.4 - 2021-02-12 22:47:45
2021-02-12 22:47:50,691 fail2ban.filter         [23358]: INFO    [sshd] Found 1.2.3.4 - 2021-02-12 22:47:50
2021-02-12 22:47:56,219 fail2ban.filter         [23358]: INFO    [sshd] Found 1.2.3.4 - 2021-02-12 22:47:55
2021-02-12 22:47:56,522 fail2ban.actions        [23358]: NOTICE  [sshd] Ban 1.2.3.4
```

**auth.log**

```
Feb 12 22:47:34 tdbm1 sshd[21711]: Accepted publickey for someknownuser from 1.2.3.4 port 50732 ssh2: RSA SHA256:5Vpnz7NssdJfOnFc/0gIHGTKbC5rc3TCYEy1ehUB3Ko
Feb 12 22:47:36 tdbm1 sshd[21743]: Received disconnect from 1.2.3.4 port 50732:11: disconnected by user
Feb 12 22:47:36 tdbm1 sshd[21743]: Disconnected from 1.2.3.4 port 50732
Feb 12 22:47:39 tdbm1 sshd[21759]: Accepted publickey for someknownuser from 1.2.3.4 port 50734 ssh2: RSA SHA256:5Vpnz7NssdJfOnFc/0gIHGTKbC5rc3TCYEy1ehUB3Ko
Feb 12 22:47:42 tdbm1 sshd[21791]: Received disconnect from 1.2.3.4 port 50734:11: disconnected by user
Feb 12 22:47:42 tdbm1 sshd[21791]: Disconnected from 1.2.3.4 port 50734
Feb 12 22:47:45 tdbm1 sshd[21803]: Accepted publickey for someknownuser from 1.2.3.4 port 50735 ssh2: RSA SHA256:5Vpnz7NssdJfOnFc/0gIHGTKbC5rc3TCYEy1ehUB3Ko
Feb 12 22:47:47 tdbm1 sshd[21840]: Received disconnect from 1.2.3.4 port 50735:11: disconnected by user
Feb 12 22:47:47 tdbm1 sshd[21840]: Disconnected from 1.2.3.4 port 50735
Feb 12 22:47:50 tdbm1 sshd[21875]: Accepted publickey for someknownuser from 1.2.3.4 port 50736 ssh2: RSA SHA256:5Vpnz7NssdJfOnFc/0gIHGTKbC5rc3TCYEy1ehUB3Ko
Feb 12 22:47:53 tdbm1 sshd[21911]: Received disconnect from 1.2.3.4 port 50736:11: disconnected by user
Feb 12 22:47:53 tdbm1 sshd[21911]: Disconnected from 1.2.3.4 port 50736
Feb 12 22:47:55 tdbm1 sshd[21921]: Accepted publickey for someknownuser from 1.2.3.4 port 50737 ssh2: RSA SHA256:5Vpnz7NssdJfOnFc/0gIHGTKbC5rc3TCYEy1ehUB3Ko
```

We haven't changed any configuration and just use the default out of the box.

Any hint what's wrong here?

**Comment by sebres** [comment]
Huh? This looks like it would recognize `Accepted publickey` messages as failures.
What do you see if you try this:
```bash
fail2ban-regex -o row /tmp/log sshd
# if mode aggressive is set by jail use this:
fail2ban-regex -o row /tmp/log sshd[mode=aggressive]
```
(for your excerpt stored in `/tmp/log` it returns 0 rows to me as expected).

Please provide the configuration damp for sshd jail - `fail2ban-client -d | grep sshd`

You can find RE matching `Accepted` and others in the dump, but this are marked as `NOFAIL` (or `MLFGAINED`) so it is just a helper to save IP for the session (for future failure messages that are not containing IP), as well as to forget all failures on gained access if no attempts for other user names happened in the session.

May be it is just an upgrade issue (wrong path in service unit/init-script or wrong python version for which 0.11 is not installed) - so you still running some old fail2ban version (but `/etc/fail2ban` contains newest config of 0.11).
What do you see in fail2ban.log if fail2ban gets started? The message must be `Starting Fail2ban v0.11.2`.

**Comment by jurgenhaas** [comment]
Oh, it seems to be installing fail2ban at a place where it is not picked up by all hosts. We're running Ubuntu 18 (and some still 16) and we had 0.10.4 on all of them before. The way we install fail2ban is to download the tar ball and execute `python3 setup.py install` where Python is 3.6 on Ubuntu 18 and 3.5 on the Ubuntu 16 hosts.

We've updated last week on 50+ hosts and found the final installation at 4 different locations:

- /usr/local/lib/python3/dist-packages
- /usr/lib/python3/dist-packages
- /usr/lib/python3.6/site-packages
- /usr/lib/python3.5/site-packages

For those installations that ended up in `.../dist-packages` the correct version of the client got picked up. For those ending up in `.../site-packages` the system continued using version 0.10.4 - so I guess this is the reason for the misbehaviour.

I couldn't find any reasonable pattern when the installer used which destination. Do you have any recommendation on how to make this more reliable?

**Comment by jurgenhaas** [comment]
To add to this: even when I remove older versions of fail2ban before running `python3 setup.py install`, the installation still goes to `.../site-packages` where Python doesn't find the package. When I run `pip3 list` afterwards, it doesn't list fail2ban.

When I move the result from site-packages to dist-packages it is then working just fine.

**Comment by sebres** [comment]
Take a look at https://stackoverflow.com/a/9388115/7161854

> Do you have any recommendation on how to make this more reliable?

This is matter of distribution you use (or its maintainers, if they made some platform related customization), but setup-tools has several prefix parameters (e. g. `--install-scripts`, see `python3 setup.py install --help` for details).
But it is a nonsense to me that python/setup installing into directory which can not be found hereafter.
What is your system and where you obtained this fail2ban version to install?

**Comment by jurgenhaas** [comment]
We're on Ubuntu and we haven't tailored any of the Python installer options, at least not knowingly. We're using Ansible to provision all out hosts and that should be pretty straight forward usually. TBH, Python's dependency management is not the most transparent either, so that platform doesn't surprise me too much anymore.

Turn out, the option for the setup script is not `--install-script`, it's the `--install-lib` that needs to be used. The former one influences where the fail2ban-client and other scripts get copied to.

The fail2ban version we install is obtained from `https://github.com/fail2ban/fail2ban/archive/{{ fail2ban_version }}.tar.gz` where `{{ fail2ban_version }}` is a variable which currently is set to 0.11.2

**Comment by sebres** [comment]
Are you sure the install takes place under root (or with sudo)? Because site-packages is rather user related stuff.
Anyway I'd guess it is probably something with that old Ubuntu or python.

I don't know how we can help here, thus will close it for now.
