### ISSUE TITLE
 Hestia bans my IP daily

### ISSUE THREAD

**Issue by LVgames** [fail2ban/fail2ban#2940]
After updating the panel, my ip started getting a RECIDIVE ban every day.
```
/var/log/fail2ban.log:10857:2021-02-16 23:05:49,580 fail2ban.actions        [188                                            75]: NOTICE  [recidive] Unban 94.190.1.49
/var/log/fail2ban.log:11904:2021-02-16 23:41:37,502 fail2ban.actions        [104                                            6]: NOTICE  [recidive] Restore Ban 94.190.1.49
```
At the same time, the lists of blocked IPs over the past few days began to be counted in hundreds, which may be the problem

**Comment by sebres** [comment]
> After updating the panel

What is the "panel"? Fail2ban version? Distribution?
We have our issue template not for nothing. Thus I'll close it unless more info provided.

> my ip started getting a RECIDIVE ban every day.

Recidive jail bans IPs that going banned `maxretry` times during `findtime` in other jails of fail2ban (searching for messages `[jail] Ban <IP>` in fail2ban.log).
So firstly you need to check what is happening within other jails with this IP (e. g. find the jail and reason for ban).

[FAQ here](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works) contains some answers for question "Fail2ban detects resp. incorrectly blocks some authentication attempts as failure (e. g. bans my IP address)".

> [recidive] Restore Ban ...

Normally this takes place after restart of fail2ban for all active bans - I guess your `recidive` jail may be persistent (`bantime = -1` or has some large `bantime`). To completely removal the ticket in such case you have to unban it manually (see `fail2ban-client --help` how you can unban IP per jail or in all jails).
