### ISSUE TITLE
fail2ban stopped banning at end of month

### ISSUE THREAD

**Issue by RainerD66** [fail2ban/fail2ban#2943]
_We will be very grateful, if your problem was described as completely as possible,
enclosing excerpts from logs (if possible within DEBUG mode, if no errors evident
within INFO mode), and configuration in particular of effected relevant settings
(e.g., with ` fail2ban-client -d | grep 'affected-jail-name' ` for a particular
jail troubleshooting).
Thank you in advance for the details, because such issues like "It does not work" 
alone could not help to resolve anything!
Thanks! (remove this paragraph and other comments upon reading)_

### Environment:

_Fill out and check (`[x]`) the boxes which apply. If your Fail2Ban version is outdated, 
and you can't verify that the issue persists in the recent release, better seek support 
from the distribution you obtained Fail2Ban from_

- Fail2Ban version (including any possible distribution suffixes):
- OS, including release name/version: 
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:
I used the iRedMail script to install a mail server with fail2ban.
Everything was running fine, but at the end of month January at 0:00 on the first of Feb fail2ban simply stopped banning.
Logs are empty since then, server is running.

#### Any customizations done to /etc/fail2ban/ configuration
```
```

#### Relevant parts of /var/log/fail2ban.log file:
_preferably obtained while running fail2ban with `loglevel = 4`_

```
```

#### Relevant lines from monitored log files in question:

```
```

**Comment by sebres** [comment]
> Logs are empty since then, server is running.

Do you have configured a log-rotation for fail2ban? If yes, how it looks? (it must be something like [fail2ban-logrotate](https://github.com/fail2ban/fail2ban/blob/master/files/fail2ban-logrotate)).
Anyway I guess it is some issue of log-rotation, so try `?sudo? fail2ban-client flushlogs` and then take a look at fail2ban.log.

**Comment by RainerD66** [comment]
Thank you for your reply!

No change. Log is empty. No, I have not configured log-rotation.

**Comment by sebres** [comment]
> Log is empty. 
> No, I have not configured log-rotation.

Take a attentive look at that 2 sentences. Don't you see a contradiction here? How can the log be empty if there is no log-rotation?
As already said, just try this command and see whether fail2ban will start to log again:
```
?sudo? fail2ban-client flushlogs
```
If you don't have configured special log-rotation for fail2ban, may be this is just a default log-rotation on your system. 
Then install fail2ban log-rotation I mentioned above (which doing flashlogs in postrotate.

Also status and other commands of fail2ban-client (as well as iptables/nftables) can provide you an info whether fail2ban still working and what it is currently doing.

But I'm 100% sure it is log-rotate (empty log, 00:00 creation time, etc).

By the way, if you said "Logs are empty since then", which logs exactly do you mean?

**Comment by RainerD66** [comment]
Hi!

What I meant was that I have not configured log-rotation myself. It must 
either be the default configuration or was configured by the iRedMail 
script.

I have several logfiles:
/var/log/fail2ban.log  /var/log/fail2ban.log.1  /var/log/fail2ban.log.2  
/var/log/fail2ban.log.3

So, there is some log-rotation happening?
But they are all empty, only /var/log/fail2ban.log.3 has entries:

...
Jan 30 23:37:04 server fail2ban.actions [296]: NOTICE [postfix-pregreet] 
Ban 192.241.192.74
Jan 30 23:55:55 server fail2ban.actions [296]: NOTICE [postfix-pregreet] 
Unban 193.56.29.102
Jan 31 00:00:00 server fail2ban.server [296]: INFO flush performed on 
SYSLOG
^^^
last line

"sudo fail2ban-client flushlogs" has no effect.
So, I should install fail2ban log-rotation?

Thanx for your help.

**Comment by sebres** [comment]
> or was configured by the iRedMail script.

I have no idea what iRedMail is and what is doing.

> "sudo fail2ban-client flushlogs" has no effect.

Which effect do you expecting? It just signals fail2ban that it must reopen log after rotation. But you'll see the messages in log only if some failure gets found and ban occurs.

> flush performed on SYSLOG

Basically this means that `flushlogs` was called, so correct postrotate must be there (seems to be executed, so you don't need to install fail2ban log-rotation). Although following is strange:
- How it is possible that fail2ban still logs in rotated log this one message (normally postrotate occurs **after rotation**);
- If there was really no rollower/flush in fail2ban, it must then write in rotated log further (similar to this aforementioned message), but it does not.

I don't really know what can cause that it does not log at all hereafter (neither in previous nor in new log).

Also note your log target is SYSLOG - this is definitely not default logtarget.
In latest fail2ban versions it logs using pythons SysLogHandler (which is intended to communicate with system log service, for example listening for udp on 514 port). So I think it must not be affected by rotation at all (no matter flushlogs is invoked or not), but I'm unsure it is correct log target for you.
Do you see some errors at begin of fail2ban.log (at time point if it was started), like `Syslog socket file: ... does not exists or is not a socket`?
What is your system logging daemon? And also provide your distribution and fail2ban version.

**Comment by sebres** [comment]
I don't know how we can help here (tested logtarget SYSLOG with stable debian and it works well, redirecting syslog fail2ban messages to fail2ban.log, rotate and flushlogs working as expected).
May be syslog just stops redirecting to `/var/log/fail2ban.log`? What it is in your case? For rsyslog check also `/var/log/syslog` or `/var/log/daemon`, for systemd journal check output of `journalctl -r | grep fail2ban | head -n 10`.
If target `SYSLOG` does not work for you for some reason, change `logtarget` (in fail2ban.conf or fail2ban.local) to some better appropriated target for your system (`/var/log/fail2ban.log` for log-file, `SYSOUT` for systemd journal if fail2ban is running as systemd unit, etc).
