### ISSUE TITLE
Fail to add another ssh regexp

### ISSUE THREAD

**Issue by ericxuo** [fail2ban/fail2ban#2957]
Hi,

I've noticed that some ssh connection errors were not caught by fail2abn.
Ex : this line is matching : 
```
|  Mar  4 10:15:36 ordi4 sshd[27490]: Connection closed by authenticating user root 116.110.154.43 port 43100 [preauth]
```
I guess by this line in the file sshd.conf : 
```
^<F-NOFAIL>Connection <F-MLFFORGET>closed</F-MLFFORGET></F-NOFAIL> by%(__authng_user)s <HOST><mdrp-<mode>-suff-onclosed>
```
This line was not matching : 
```
|  Mar  4 16:07:47 ordi4 sshd[19806]: Disconnected from authenticating    user root 40.72.104.122  port 36268 [preauth]
```
So I've duplicated the previous regexp and modified it the following way : 
```
^<F-NOFAIL>Disconnected <F-MLFFORGET>from</F-MLFFORGET></F-NOFAIL>%(__authng_user)s <HOST><mdrp-<mode>-suff-onclosed>
```
But it still fails to catch the line.

Could you help me to make it work ?

Regards.

Xuo.

**Comment by sebres** [comment]
People, why we provide the issue template, which inter alia clearly says:
- Before reporting or requesting, please make sure to search the open and closed issues for any reports in the past
- If you have rather some question, please open or join to some discussion

Anyway this (as well as some others) is your answer - https://github.com/fail2ban/fail2ban/issues/2867#issuecomment-723452246
```ini
[sshd]
mode = aggressive
```

> But it still fails to catch the line.

As for `<F-NOFAIL>...</F-NOFAIL>` - this is a marker for no failure (mostly used in `normal` mode) which signals that this is just a helper regex, useable to consider IP of the session, to be able to find failures from same session that doesn't contain the IP in message.
If it is failure in sense of other modes, like `aggressive`, the same regex become indeed duplicated without `<F-NOFAIL>` marker.

For instance:
```diff
msg='Mar  4 16:07:47 srv sshd[19806]: Disconnected from authenticating user root 192.0.2.1 port 36268 [preauth]'
- $ fail2ban-regex  "$msg" sshd
+ $ fail2ban-regex  "$msg" sshd[mode=aggressive]
...
- Lines: 1 lines, 1 ignored, 0 matched, 0 missed
+ Lines: 1 lines, 0 ignored, 1 matched, 0 missed
