### ISSUE TITLE
Custom port not banned

### ISSUE THREAD

**Issue by tobiascapin** [fail2ban/fail2ban#2974]
I have installed a new Ubuntu 20.10 server with the default distribution of Fail2Ban v0.11.1.
I would like to set a custom port for PURE-FTP jain, then I added this jail.local file:
```
[pure-ftpd]
enabled = true
port = 2121
```

I tried to ban an IP, the ban works, but iptable filters the default ftp port defined in jail.conf instead of the custom one.

`sudo iptables -L INPUT -v -n`
This is the iptables output:
`f2b-pure-ftpd  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 21,20,990,989`

Am I missing something to apply the jail.local settings? I have just restarted the systemd service.

**Comment by tobiascapin** [comment]
Looks like the iptables output is not updated until the next ban, is not enought to restart fail2ban. Sorry.

**Comment by sebres** [comment]
Restart of whole fail2ban is not necessary, but one has surely to restart the affected jail.
```
?sudo? fail2ban-client restart pure-ftpd
```
