### ISSUE TITLE
[RFE]: add: fail2ban-client status --all

### ISSUE THREAD

**Issue by someone-somenet-org** [fail2ban/fail2ban#2975]
Add a `--all` switch to `fail2ban-client status` to list all active jails at once.

#### Description
Make it easier to iterate over all active jails by allowing to list all at once.

#### Considered alternatives
Add `fail2ban-client status-all` to list all active jails at once.

**Comment by sebres** [comment]
> to list all active jails at once.

`fail2ban-client status` doing exactly that.
Do you rather mean to list **all tickets of** all active jails?

**Comment by someone-somenet-org** [comment]
> > to list all active jails at once.
> 
> `fail2ban-client status` doing exactly that.
> Do you rather mean to list **all tickets of** all active jails?

not sure what you call tickets.
When you run `fail2ban-client status` you get a boring and non-machine-readable list of existing jails without any details.

While `fail2ban-client status <JAIL>` gives details of said jail.

The proposal is to add a way to get these stats for all jails in one call as my current workaround ``fail2ban-client status | grep "Jail list" | sed -E -e 's/`- Jail list:\s*//' -e 's/,?//g' | tr ' ' '\0' | tr -d '\n' | xargs -0 -n1 -i'{}' -- fail2ban-client status {}`` is not really user friendly.

**Comment by mmitch** [comment]
I have written a small shell script that basically does the same as the one-liner from the previous comment but creates a tabular output:

```
# fail2ban-statistics
JAIL                      FILTER       ACTIONS  
                        cur  total    cur  total
------------------------------------------------
apache-auth               3      3      0      0
apache-modsecurity        0      0      0      0
apache-nohome             0      0      0      0
apache-noscript          13     17      0      0
apache-overflows          0      0      0      0
apache-shellshock         0      0      0      0
cyrus-imap                0      0      0      0
exim                     25   1543      0      6
murmur                    0      0      0      0
mysqld-auth               0      0      0      0
php-url-fopen             0      0      0      0
sieve                     0      0      0      0
sshd                      4   1385      2     61
stunnel                   0      0      0      0
```
source: https://github.com/mmitch/mitchscripts/blob/master/bash/fail2ban-statistics

I am happy to contribute this script if it finds a nice place in fail2ban.
I don't know where to put it, so I can't open a pull request.

**Comment by catofnineswords** [comment]
Three years later and this feature request is still being desired.
There are several discussions on various forums about this, and countless gists comprising one-liners,  bash functions and other oddities.

Please add the --all to our jail statuses.

**Comment by sebres** [comment]
There is yet another similar command already implemented - `fail2ban-client banned` (see https://github.com/fail2ban/fail2ban/issues/2725#issuecomment-631519265). However it is rather for some automated processing (because returns pythonic dictionary).
