### ISSUE TITLE
Fail2ban finding, but not banning.

### ISSUE THREAD

**Issue by ronnie-lazarus** [fail2ban/fail2ban#2978]
I'm on a fresh Ubuntu 20.04 LTS and installed fail2ban via apt install fail2ban.

I was able to get the application to read my haproxy logs at /var/log/haproxy-traffic.log. I was also able to get the regex to match correct and as seen from the LOGs, at /var/log/fail2ban.log, clearly everything except for the banning seems to be working well.

![image](https://user-images.githubusercontent.com/22115598/111811057-abc6ca00-88fc-11eb-9910-9107464057b7.png)

My backend is set to 'auto' and thus is using pinotify. My jail.local is as below:

banaction = iptables-multiport
banaction_allports = iptables-allports

action = %(action_)s
[haproxy]

enabled  = true
bantime  = 1d
findtime = 5
maxretry = 2
filter   = haproxy-brute
logpath  = /var/log/haproxy-traffic.log
port    = 443,5000,5001,5002

The ports on my server constantly getting attacked are for a TCP Passthrough tunnel to one of our client's server.

Any help would be greatly appreciated here.

Thanks,

**Comment by sebres** [comment]
From [wiki :: How fail2ban works](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works):

- the IP goes to ban if it makes at least `maxretry` failures within `findtime` seconds. So if you've configured `maxretry=5` and `findtime=10m` (default values) then it needs at least 5 failures (5 attempts) within 10 minutes to ban an IP.<br/>

Your `findtime` is 5 seconds, so by `maxretry` 2 an IP must make 2 attempts in 5 seconds to gets banned.

Did you probably mean `5m` (for 5 minutes)?
```diff
- findtime = 5
+ findtime = 5m
```

**Comment by ronnie-lazarus** [comment]
Well just like with everything else, I sorted this one out myself. Don't
know why though as I had checked that my server date/time and logs
date/time was already in sync. But idk how, after i configured tzdata,
restart rsyslogd and fail2ban, everything is working now. Who knew?

Thanks either ways,
Regards,
