### ISSUE TITLE
[BR]: "'FilterPyinotify' object has no attribute 'isAlive'",

### ISSUE THREAD

**Issue by edbelcher47** [fail2ban/fail2ban#2980]
### Environment:

uname -a
Linux thor 5.4.0-67-generic #75-Ubuntu SMP Fri Feb 19 18:03:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

fail2ban-client --version
Fail2Ban v0.11.1

python --version
Python 2.7.18

python3 --version
Python 3.9.0+

### The issue:
Odd entries in log, appears to stop logging, yet service appears to continue to execute.

#### Relevant parts of /var/log/fail2ban.log file:
2021-03-19 12:43:30,565 fail2ban                [3532]: ERROR   NOK: ("'FilterPyinotify' object has no attribute 'isAlive'",)

**Comment by sebres** [comment]
Fixed in 55e76c0b807e87f6a04d459bb9c59da33c98572b (released in 0.10.6 and 0.11.2).
