### ISSUE TITLE
[BR]: filter ssh/auth log "Connection closed by authenticating user <user> <host>" doesnt work

### ISSUE THREAD

**Issue by kemoc** [fail2ban/fail2ban#2981]
### Environment:

Ubuntu 2004

- Fail2Ban version  : 
- OS, including release name/version : 
- [x] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase 
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
I have enabled ssh mode = ddos-other or extra-other
but IP from messages like "Connection closed by authenticating user [user] [host]" doesnt block
when i failure log in with password then i am blocked but above not

#### Steps to reproduce
install fail2ban
enable 
[sshd]
enabled = true
mode = ddos-other

restart service

on your local machine setup .ssh/config
Host [IP]
 HostName [IP]
 PreferredAuthentications publickey
 etc.
Remember to have different keys local - remote to get on remote log: "Connection closed by authenticating user [user] [host]"

#### Expected behavior
disable host (local machine IP)

#### Observed behavior
i can try log in without ban

### Configuration, dump and another helpful excerpts
tell how if needed

#### Any customizations done to /etc/fail2ban/ configuration

```
[sshd]
enabled = true
mode = ddos-other
```

#### Relevant parts of /var/log/fail2ban.log file:

how do that, i have running fail2ban by deamon/systemctl
```
```

#### Relevant lines from monitored log files:

i can't do that, it contains user names and IPs
```
```

**Comment by kemoc** [comment]
mode = aggressive helped, what is the difference?

**Comment by sebres** [comment]
Neither mode `ddos-other`, nor `extra-other` existing in sshd-filter. 
They're calling `ddos` and `extra` and are the modes only monitoring certain "attack" vectors (either DDoS similar circumstances, like continuous connections without authentication, or invalid or unsupported authentication algorithms etc) and don't include standard sshd rules monitoring authentication issues only. So this modes are rather for usage of sshd-filter in different jails (for example with larger `maxretry` to avoid possible false positives, if some legitimate user has slow or unstable connection or connectivity troubles).
However mode `aggressive` combining all regex's from all groups, so can be used to recognize every known vector (failed authentication as well as DDoS- and other disorders) in a single jail.
