### ISSUE TITLE
[BR]: Wildcard logpath not working

### ISSUE THREAD

**Issue by jffz** [fail2ban/fail2ban#2983]
Saw it already referenced in #1313 but not sure if it is related or not.

### Environment:

- Fail2Ban version  : 
- OS, including release name/version : 
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
Wildcards are stripped from jail logpath

#### Steps to reproduce
Configure wildcard in jail logpath

#### Expected behavior
Wilcards shouldn't be stripped and matching files should be add in logpath

#### Observed behavior
Wildcards are stripped and only exact matching pattern without wildcard is added to jail logpath.

#### Any additional information
Debian 10
fail2ban 0.10.2-2.1
Logfiles matching wildcard expression exists before fail2ban starts

### Configuration, dump and another helpful excerpts
```
~# grep apache -A 6  /etc/fail2ban/jail.local
[apache]
enabled = true
filter = apache-auth
findtime = 600
logpath = /var/log/apache*/*error.log
port = http,https

[apache-noscripts]
enabled = true
filter = apache-noscript
logpath = /var/log/apache*/*error.log
maxretry = 3
port = http,https

[apache-overflows]
enabled = true
filter = apache-overflows
logpath = /var/log/apache*/*error.log
maxretry = 3
port = http,https

[apache-badbots]
enabled = true
filter = apache-badbots
logpath = /var/log/apache*/*error.log
maxretry = 3
port = http,https

[apache-nohome]
enabled = true
filter = apache-nohome
logpath = /var/log/apache*/*error.log
maxretry = 3
port = http,https
```

```
~# fail2ban-client -d | grep apache | grep logpath
['set', 'apache-badbots', 'addlogpath', '/var/log/apache2/error.log', 'head']
['set', 'apache-overflows', 'addlogpath', '/var/log/apache2/error.log', 'head']
['set', 'apache-nohome', 'addlogpath', '/var/log/apache2/error.log', 'head']
['set', 'apache', 'addlogpath', '/var/log/apache2/error.log', 'head']
['set', 'apache-noscripts', 'addlogpath', '/var/log/apache2/error.log', 'head']
```

```
~# ll /var/log/apache2/
total 888
-rw-r----- 1 root adm      0 Jan 25 21:05 access.log
-rw-r----- 1 root adm   1361 Mar 25 11:22 error.log
-rw-r----- 1 root adm    665 Mar 25 00:00 error.log.1
-rw-r----- 1 root adm    371 Mar  6 00:00 error.log.10.gz
-rw-r----- 1 root adm    371 Mar  5 00:00 error.log.11.gz
-rw-r----- 1 root adm    368 Mar  4 00:00 error.log.12.gz
-rw-r----- 1 root adm    369 Mar  3 00:00 error.log.13.gz
-rw-r----- 1 root adm    370 Mar  2 00:00 error.log.14.gz
-rw-r----- 1 root adm   1032 Mar 24 00:00 error.log.2.gz
-rw-r----- 1 root adm   1843 Mar 23 00:00 error.log.3.gz
-rw-r----- 1 root adm    388 Mar 22 00:00 error.log.4.gz
-rw-r----- 1 root adm    323 Mar 10 00:00 error.log.5.gz
-rw-r----- 1 root adm    370 Mar 10 00:00 error.log.6.gz
-rw-r----- 1 root adm    369 Mar  9 00:00 error.log.7.gz
-rw-r----- 1 root adm    366 Mar  8 00:00 error.log.8.gz
-rw-r----- 1 root adm    368 Mar  7 00:00 error.log.9.gz
-rw-r----- 1 root adm 169675 Mar 25 13:42 other_vhosts_access.log
-rw-r----- 1 root adm 210626 Mar 24 23:36 other_vhosts_access.log.1
-rw-r----- 1 root adm  17387 Mar  5 23:23 other_vhosts_access.log.10.gz
-rw-r----- 1 root adm   8713 Mar  4 23:58 other_vhosts_access.log.11.gz
-rw-r----- 1 root adm  13569 Mar  3 23:53 other_vhosts_access.log.12.gz
-rw-r----- 1 root adm   8392 Mar  2 23:40 other_vhosts_access.log.13.gz
-rw-r----- 1 root adm  11294 Mar  1 23:50 other_vhosts_access.log.14.gz
-rw-r----- 1 root adm 125163 Mar 23 23:49 other_vhosts_access.log.2.gz
-rw-r----- 1 root adm 192418 Mar 22 23:59 other_vhosts_access.log.3.gz
-rw-r----- 1 root adm   6279 Mar 21 23:57 other_vhosts_access.log.4.gz
-rw-r----- 1 root adm    894 Mar 10 01:14 other_vhosts_access.log.5.gz
-rw-r----- 1 root adm  10425 Mar  9 23:45 other_vhosts_access.log.6.gz
-rw-r----- 1 root adm  10269 Mar  8 23:56 other_vhosts_access.log.7.gz
-rw-r----- 1 root adm  10546 Mar  7 23:44 other_vhosts_access.log.8.gz
-rw-r----- 1 root adm   9732 Mar  6 23:27 other_vhosts_access.log.9.gz
```

#### Any customizations done to /etc/fail2ban/ configuration
none

#### Relevant parts of /var/log/fail2ban.log file:
nothing in debug mode

**Comment by sebres** [comment]
> Wildcards are stripped and only exact matching pattern without wildcard is added to jail logpath.

What do you mean as stripped? grep pattern `*` means 0 or N concurrency of any character, 
so `apache*` matches `apache2`, and `*error.log` matches `error.log`.
There are no more files which can be matched `*error.log` pattern in `/var/log/apache2/` directory.
Moreover it were incorrect to provide pattern like `*error.log.*`, because `error.log.1` is rotated (and `error.log.*.gz` are additionally zipped), so they would not grow anymore and monitoring of such files makes no sense at all.

For instance there is no `other_vhosts_error.log` or even other error-files, only `other_vhosts_access.log`

Thus this:

> `/var/log/apache*/*error.log`
> `['set', 'apache-badbots', 'addlogpath', '/var/log/apache2/error.log', 'head']`
> `~# ll /var/log/apache2/`
> `-rw-r----- 1 root adm   1361 Mar 25 11:22 error.log`
 
is totally correct.
