### ISSUE TITLE
[RFE]: Filter documentation woefully unclear, incomplete, wrong

### ISSUE THREAD

**Issue by otheus** [fail2ban/fail2ban#2986]
#### Feature request type
I found the official documentation (PDF version for 0.8) as well as the wiki page (https://www.fail2ban.org/wiki/index.php/MANUAL_0_8) incredibly frustrating to follow, especially in regards to the _Filters_ section.  

Some of the information is wrong or (w.r.t. 0.11) obsolete. 
For instance,
1. In the `failregex` example, 4 expresions are given but the documentation says '3 rules'
2.  "`<HOST>` in your regexes. `<HOST>` is an alias for `(?:::f{4,6}:)?(?P<host>\S+)`" is incorrect, as it is now `<ip4>` not `<host>`. 
3. The whole concept of substitutions with `<...>` is completely unclear. What is the difference between that and `%(....)s`? 
4. What is the "s" for? Only trial and error proved it was necessary. 
5. Why are variable names beginning with double-underscores? 
6. Is there a possibility (how?) to perform arbitrary (mathematical) expressions? For instance, if a named-matched numeric field is greater or less than a value? Or if a captured string matches another captured string elsewhere in the same line?

**Comment by sebres** [comment]
Partially [man pages](https://manpages.debian.org/unstable/fail2ban/jail.conf.5.en.html) and github [wiki](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-substitution-resp.-runtime-interpolation-works) answering your questions.
But I try to provide the answers here (for current fail2ban versions):
1. obsolete
2. this interpolated value of this and other tags changing from time to time, and it depends very strictly on options of the jail where it is used (`usedns`, IPv6 allowed or not) and can be:
  - `(?:\[?(?:(?:::f{4,6}:)?(?P<ip4>(?:\d{1,3}\.){3}\d{1,3})|(?P<ip6>(?:[0-9a-fA-F]{1,4}::?|::){1,7}(?:[0-9a-fA-F]{1,4}|(?<=:):)))\]?|(?P<dns>[\w\-.^_]*\w))` - both IP families are supported, `usedns` is allowed (`yes` or `warn`)
  - `\[?(?:(?:::f{4,6}:)?(?P<ip4>(?:\d{1,3}\.){3}\d{1,3})|(?P<ip6>(?:[0-9a-fA-F]{1,4}::?|::){1,7}(?:[0-9a-fA-F]{1,4}|(?<=:):)))\]?` - both IP families are supported, `usedns` is disallowed (`no`)
  - there are other tags you can also use to target only failure identifier you need:
    * `<ADDR>` or `<F-ADDR/>` - only IP addresses, without hostnames
    * `<IP4>` or `<F-IP4/>` - only IPv4 address
    * `<IP6>` or `<F-IP6/>` - only IPv6 address
    * `<DNS>` or `<F-DNS/>` - only hostname
    * `<F-ID>...</F-ID>` - free RE targeting identifier used for ban (instead of IP/host)
    * every of abovementioned `<F-*>` tags can be specified with custom RE, for example<br/> `(?:ip4:<F-IP4>\S+</F-IP4>|ip6:<F-IP6>\S+</F-IP6>)`.
3. please, read the link to the wiki I provided above. Shortly - `%(...)s` is default python substitution for ini-files (working at the config read time), whereas `<...>` is own enhancement of fail2ban doing dynamic interpolation to the runtime or config read time depending on the context (additionally allowing recursive substitution, like:<br> `<a-<b>>` -> firstly interpolated as `<a-value-of-b>` and then searching and replacing this tag if it is exists (specified).
4. which `s` do you mean? if it is ending of `%(...)s`, then as already said it is pythons [string formatting operations](https://docs.python.org/2.7/library/stdtypes.html#string-formatting) used to reference section variables here.
5. single or double underscore typically used to avoid confusion with some future enhancements of tags (e. g. just means some parameter interpolated mostly local only. But you can use naming convention you like.
6. As for mathematical expressions in config-files interpolation - no, it is impossible right now. Only thing which is possible is to use recursive interpolation, e. g. see how parameter `mode` is used in filters, for example in 6b90ca820f5244fd88e8b407419da359d5d068b9 interpolation of `<usrre-<mode>>` is conditional and depends on value of mode: https://github.com/fail2ban/fail2ban/blob/6b90ca820f5244fd88e8b407419da359d5d068b9/config/filter.d/traefik-auth.conf#L73-L76
  Or you can take a look at common-config how conditional `datepattern` is build per default (depending on `logtype`) which even works across sections - e. g. targeting datepattern parameter in sections which names matching `lt_<logtype>`: https://github.com/fail2ban/fail2ban/blob/80a33b1dee5538b40ef753e13bbddcdbbfd7f38c/config/filter.d/common.conf#L68
  Although I have an experimental branch using formula's and python lambdas to config interpolation time and a run-time, but it is not yet portable to original fail2ban right now (I need to prepare master branch for this firstly, e. g. adjust several tests cases etc).<br/>
  If you rather mean some mathematical expressions **in actions**, then sure you can do everything either using python (in pythonic actions) or your default shell expressions (or whatever you like to use there) in command actions.

Several points simply refer to obsolete documentation (v.0.8) and #2580 is the issue for this concerns. Let's avoid duplicate so please further in #2580.
But you can ping us here if you have still some questions.

**Comment by otheus** [comment]
Thank you very much. You are right, there is much in the man pages that answered my questions, but there is quite a bit that isn't there, so I must have been confused about where I had read what.  

I wan't aware of the fail2ban github wiki. Man, *four* sources of documentation. Oof. 

I like your idea of python-lambdas in the filter-condition expression. That would potentially elevate the functionality of fail2ban to enterprise-level, state-based firewalls.

At any rate, I'm very happy now with fail2ban doing what it's doing.
