### ISSUE TITLE
[FR]: Postfix "RCPT from unknown: 504 5.5.2 <>: Helo command rejected: need fully-qualified hostname"

### ISSUE THREAD

**Issue by blackcoder87** [fail2ban/fail2ban#2995]
### Environment:

- Fail2Ban version : 0.10.2-2.1 (took the latest postfix.conf filter as of 8th April 2021 though)
- OS, including release name/version : Debian GNU/Linux 10.9 (buster)

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : postfix.conf
- Service, project or product name, including release name/version : postfix 3.4.14-0+deb10u1

#### Log or journal information
- Log file name(s) : /var/log/mail.log

#### Any additional information

A line like "RCPT from unknown: 504 5.5.2 <>: Helo command rejected: need fully-qualified hostname" does not get detected by fail2ban. I see that the similar line with "EHLO" gets detected by fail2ban already, but not the one starting with "RCPT".
There might be a good reason to not detect them that I am not aware of.

https://github.com/fail2ban/fail2ban/blob/ba7daef86c521ceda4ee48b5f221485dd98a13ad/config/filter.d/postfix.conf#L22
Changing that line (adding RCPT) to the one quoted below seems to do the job for me.
```
^(EHLO|RCPT) from [^[]*\[<HOST>\]%(_port)s: 504 5\.5\.\d+ (<[^>]*>)?: Helo command rejected: need fully-qualified hostname\b
```

#### failures in sense of fail2ban filter (fail2ban must match):
```
Apr  6 13:05:01 server postfix/smtpd[20589]: NOQUEUE: reject: RCPT from unknown[23.172.112.116]: 504 5.5.2 <WIN-6A0KEE6QVP5>: Helo command rejected: need fully-qualified hostname; from=<spameri@tiscali.it> to=<spameri@tiscali.it> proto=ESMTP helo=<WIN-6A0KEE6QVP5>
Apr  6 14:19:51 server postfix/smtpd[21201]: NOQUEUE: reject: RCPT from unknown[77.247.110.228]: 504 5.5.2 <win2012r2RDP>: Helo command rejected: need fully-qualified hostname; from=<spameri@tiscali.it> to=<spameri@tiscali.it> proto=ESMTP helo=<win2012r2RDP>
Apr  6 16:19:50 server postfix/smtpd[21560]: NOQUEUE: reject: RCPT from unknown[49.84.100.213]: 504 5.5.2 <Hc-Vm-Pc>: Helo command rejected: need fully-qualified hostname; from=<kota@mydomain.tld> to=<3123827806@qq.com> proto=ESMTP helo=<Hc-Vm-Pc>
Apr  6 16:19:50 server postfix/smtpd[21560]: NOQUEUE: reject: RCPT from unknown[49.84.100.213]: 504 5.5.2 <Hc-Vm-Pc>: Helo command rejected: need fully-qualified hostname; from=<mqxf@mydomain.tld> to=<3123827806@qq.com> proto=ESMTP helo=<Hc-Vm-Pc>
```

**Comment by sebres** [comment]
Fixed in ae3e9b9149c36e3334447e869667bcf171ff0a3a. Thx!
