### ISSUE TITLE
[FR]: Postfix "RCPT from unknown: 550 5.7.25 Client host rejected: cannot find your hostname"

### ISSUE THREAD

**Issue by blackcoder87** [fail2ban/fail2ban#2996]
### Environment:

- Fail2Ban version : 0.10.2-2.1 (took the latest postfix.conf filter as of 8th April 2021 though)
- OS, including release name/version : Debian GNU/Linux 10.9 (buster)

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : postfix.conf
- Service, project or product name, including release name/version : postfix 3.4.14-0+deb10u1

#### Log or journal information
- Log file name(s) : /var/log/mail.log

#### Any additional information

An administrator might chose to return a different reject code than the default 450.
In that case it is probably quiet common to return 550 to indicate a permanent block for policy reason and to let the other site know to not bother retrying. If the other site still retries then that might be an even bigger reason for fail2ban to catch the log line than with a reject code of 450.

> - https://tools.ietf.org/html/rfc5321#section-4.2.3
450 Requested mail action not taken: mailbox unavailable (e.g., mailbox busy or temporarily blocked for policy reasons)
550 Requested action not taken: mailbox unavailable (e.g., mailbox not found, no access, or command rejected for policy reasons)

For example as suggested in an arstechnica series on how to setup an e-mail server:
https://arstechnica.com/information-technology/2014/03/taking-e-mail-back-part-2-arming-your-server-with-postfix-dovecot/2/

- /etc/postfix/main.cf
```
## Dealing with rejection: use permanent 550 errors to stop retries
unknown_address_reject_code = 550
unknown_hostname_reject_code = 550
unknown_client_reject_code = 550
```

http://www.postfix.org/postconf.5.html#unknown_address_reject_code
http://www.postfix.org/postconf.5.html#unknown_hostname_reject_code
http://www.postfix.org/postconf.5.html#unknown_client_reject_code

https://github.com/fail2ban/fail2ban/blob/ba7daef86c521ceda4ee48b5f221485dd98a13ad/config/filter.d/postfix.conf#L20
Changing that line like shown below catches the log lines with the non default reject code for me:
```
^RCPT from [^[]*\[<HOST>\]%(_port)s: [45]5[04] [45]\.7\.\d+ (?:Service unavailable\b|Client host rejected: cannot find your (reverse )?hostname\b)
```

#### failures in sense of fail2ban filter (fail2ban must match):
```
Apr  4 03:10:56 server postfix/smtpd[7754]: NOQUEUE: reject: RCPT from unknown[5.188.206.246]: 550 5.7.25 Client host rejected: cannot find your hostname, [5.188.206.246]; from=<laqqubtbyop@ms-andante.de> to=<sxhcpltqhpex@mydomain.tld> proto=ESMTP helo=<[5.188.206.246]>
Apr  4 03:11:28 server postfix/smtpd[7754]: NOQUEUE: reject: RCPT from unknown[5.188.206.246]: 550 5.7.25 Client host rejected: cannot find your hostname, [5.188.206.246]; from=<lfkrazifndi@ms-andante.de> to=<sxhcpltqhpex@mydomain.tld> proto=ESMTP helo=<[5.188.206.246]>
Apr  4 03:11:57 server postfix/smtpd[7754]: NOQUEUE: reject: RCPT from unknown[5.188.206.246]: 550 5.7.25 Client host rejected: cannot find your hostname, [5.188.206.246]; from=<hihbivwrlpm@ms-andante.de> to=<sxhcpltqhpex@mydomain.tld> proto=ESMTP helo=<[5.188.206.246]>
Apr  4 06:43:17 server postfix/smtpd[8814]: NOQUEUE: reject: RCPT from unknown[5.188.206.246]: 550 5.7.25 Client host rejected: cannot find your hostname, [5.188.206.246]; from=<vxtzgqgkan@kasecurities.com> to=<myxdmbluumi@mydomain.tld> proto=ESMTP helo=<[5.188.206.246]>
Apr  4 06:43:47 server postfix/smtpd[8814]: NOQUEUE: reject: RCPT from unknown[5.188.206.246]: 550 5.7.25 Client host rejected: cannot find your hostname, [5.188.206.246]; from=<quajtqvdinp@kasecurities.com> to=<myxdmbluumi@mydomain.tld> proto=ESMTP helo=<[5.188.206.246]>
Apr  4 06:44:17 server postfix/smtpd[8814]: NOQUEUE: reject: RCPT from unknown[5.188.206.246]: 550 5.7.25 Client host rejected: cannot find your hostname, [5.188.206.246]; from=<qufpznfjsdo@kasecurities.com> to=<myxdmbluumi@mydomain.tld> proto=ESMTP helo=<[5.188.206.246]>
Apr  4 10:16:00 server postfix/smtpd[9473]: NOQUEUE: reject: RCPT from unknown[5.188.206.246]: 550 5.7.25 Client host rejected: cannot find your hostname, [5.188.206.246]; from=<tbxqfysmkvg@chinashippingmed.it> to=<lqrnhaszfbqe@mydomain.tld> proto=ESMTP helo=<[5.188.206.246]>
Apr  4 10:16:27 server postfix/smtpd[9473]: NOQUEUE: reject: RCPT from unknown[5.188.206.246]: 550 5.7.25 Client host rejected: cannot find your hostname, [5.188.206.246]; from=<cknzxoxcsf@chinashippingmed.it> to=<lqrnhaszfbqe@mydomain.tld> proto=ESMTP helo=<[5.188.206.246]>
Apr  4 10:16:59 server postfix/smtpd[9473]: NOQUEUE: reject: RCPT from unknown[5.188.206.246]: 550 5.7.25 Client host rejected: cannot find your hostname, [5.188.206.246]; from=<nbnixaldvqyd@chinashippingmed.it> to=<lqrnhaszfbqe@mydomain.tld> proto=ESMTP helo=<[5.188.206.246]>
```

**Comment by sebres** [comment]
Fixed in ae3e9b9149c36e3334447e869667bcf171ff0a3a. Thx!
