### ISSUE TITLE
[RFE]: add some way to retry a ban action

### ISSUE THREAD

**Issue by Thermi** [fail2ban/fail2ban#2997]
#### Feature request type

If the banaction fails, it'd be great if we could specify that it is to be retried X times. E.g. for the currently sometimes failing blocklist_de action, that'd be great.

#### Description

Just add something like retries=x where the default is 0 or something.

#### Considered alternatives

Doing it in the actions themselves would require changing any action that could be useful for, leading to large fragmentation of 
action files between users doing their own modification. That then leads to a lot of package manager added backup and new files (e.g. opkg-new, opkg-old, ...).

**Comment by sebres** [comment]
There is another issue targeting same problem - #2318 (work is almost completed, I'll provide an ultimate solution soon).
Thus closing (let us avoid duplicates).
