### ISSUE TITLE
log line match

### ISSUE THREAD

**Issue by vesselict** [fail2ban/fail2ban#3002]
Hi
I already posted this on sourceforge userlists, but don't know if that's the same.. anyway....

I setup a custom filter and it works, but I want on action beside the
ban ip, to send also corresponding log line from log to remote syslog...
Now is there any information on variables to get and pass on action
script beside <HOST>.

I saw on fail2ban-regex when I test verbose that outputs IP and
timestamp, now a quick dirty approach could be to grep timestamp and IP (although it seems timestamp is not of log file rather than fail2ban's)
on log file and push output line to remote syslog, problem is that I
can't seem  to find the variable of timestamp to pass on action script.
Ideal would be if there is variable to it's log line itself...

Any help appreciated

**Comment by sebres** [comment]
People, why we asking in our issue templates the version of fail2ban?

Here is an excerpt of every tag which is allowed in **current** fail2ban version:
https://github.com/fail2ban/fail2ban/blob/6893d5a8b78fbdf263df8a233b3b9ac343c7a02c/fail2ban/server/actions.py#L379-L406
(you did not provide your fail2ban version, so I some "variables" may be not available in your case)

Short description of tags probably related your concerns:
- `<time>` ticket time (time of failure caused ban);
- `<matches>` - list of failures (lines up to `maxretry` separated by new-line) caused a ban;
- `<F-*>` - something matching a captured group defined in filter as `<F-*>...</F-*>` (for example action tag `<F-USER>` contains value of `<F-USER>...</F-USER>` defined in filter).

> beside the ban ip, to send also corresponding log line from log to remote syslog...

```ini
# bulk send in single command over ssh:
actionban = ssh user@192.0.2.1 get-remote-ban-logs.sh "<sh-hostname>" "<matches>"

# bulk send of original messages to logger remotely:
actionban = echo "<matches>" | logger -n 192.0.2.1 -t fail2ban -p user.notice &

# send of pre-processed (rewritten) messages to logger remotely:
actionban = echo "<matches>" | while read -r line; do
               # line=$(do-some-rewrite "$line")
               logger -n 192.0.2.1 -t fail2ban -p user.notice "$line"
            done
```
Note that `<matches>` contains original log-lines, so probably you would need some pre-processing removing prefix (and/or parsing the unit, tag, id or priority) from every message before it is going to the logger.

**Comment by vesselict** [comment]
thank you..

this is what I was looking for..

Just for the info
version is 0.11.2 on CentOS 8

thanks again..
