### ISSUE TITLE
[FR]: Sendmail SMTP RCPT Flooding: "Fix reverse DNS for"

### ISSUE THREAD

**Issue by redvivi** [fail2ban/fail2ban#3012]
### Environment:

- Fail2Ban version: `0.11.1`
- OS, including release name/version : `Ubuntu 20.04.2 LTS`

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : `sendmail-reject.conf`
- Service, project or product name, including release name/version : `8.15.2-18`
- Repository or URL (if known) : https://salsa.debian.org/debian/sendmail/-/tree/debian/8.15.2-18
- Service type : `Email Server`
- Ports and protocols the service is listening : `25`

#### Log or journal information

- Log file name(s) : `/var/log/mail.log` containing SMTP RCPT flooding

### Relevant lines from monitored log files:

```
Apr 24 11:20:27 localhost sm-mta[275631]: 13O9Ixhq275631: ruleset=check_rcpt, arg1=<linda@domain.com>, relay=[1.23.456.78], reject=550 5.7.1 <linda@domain.com>... Fix reverse DNS for 1.23.456.78
Apr 24 11:20:27 localhost sm-mta[275631]: 13O9Ixhq275631: ruleset=check_rcpt, arg1=<linda@domain.com>, relay=[1.23.456.78], reject=550 5.7.1 <linda@domain.com>... Fix reverse DNS for 1.23.456.78
Apr 24 11:20:28 localhost sm-mta[275631]: 13O9Ixhq275631: ruleset=check_rcpt, arg1=<linda@domain.com>, relay=[1.23.456.78], reject=550 5.7.1 <linda@domain.com>... Fix reverse DNS for 1.23.456.78
Apr 24 11:20:31 localhost sm-mta[275631]: 13O9Ixhq275631: ruleset=check_rcpt, arg1=<linda@domain.com>, relay=[1.23.456.78], reject=550 5.7.1 <linda@domain.com>... Fix reverse DNS for 1.23.456.78
```

#### failures in sense of fail2ban filter (fail2ban must match):
```
Apr 24 11:20:27 localhost sm-mta[275631]: 13O9Ixhq275631: ruleset=check_rcpt, arg1=<linda@domain.com>, relay=[1.23.456.78], reject=550 5.7.1 <linda@domain.com>... Fix reverse DNS for 1.23.456.78
```

#### legitimate messages (fail2ban should not consider as failures):
```
N/A
```

**Comment by sebres** [comment]
Fixed in 87f717e0e038afeb9b2ac98617fc3d907ddc49bc. Thx!
