### ISSUE TITLE
[FR]: apache-fakegooglebot - ignore rule for Mac OS?

### ISSUE THREAD

**Issue by clusterx** [fail2ban/fail2ban#3013]
It seems Mac OS had a brilliant idea of using google as UA and these are now blocked via apache-fakegooglebot ...
Is there a solution here to use an ignore rule for Mac OS browser with google UA string?

**Comment by sebres** [comment]
> It seems Mac OS had a brilliant idea of using google as UA

What exactly is logged as user agent?

> Is there a solution here to use an ignore rule for Mac OS browser with google UA string?

How you can do that? I mean how the jail must distinguish real fake googlebots from such browsers, where the IPs of both don't belong to google subnets and the rule for the difference between fake and real is based on its IP or its subnet.

If the user agent string contains something special, that could be considered as a sign to bypass, sure it is possible, just why the same agent cannot be used tomorrow by bots, so they will scan everything without a ban?

**Comment by clusterx** [comment]
> > It seems Mac OS had a brilliant idea of using google as UA
> 
> What exactly is logged as user agent?
> 
> > Is there a solution here to use an ignore rule for Mac OS browser with google UA string?
> 
> How you can do that? I mean how the jail must distinguish real fake googlebots from such browsers, where the IPs of both don't belong to google subnets and the rule for the difference between fake and real is based on its IP or its subnet.
> 
> If the user agent string contains something special, that could be considered as a sign to bypass, sure it is possible, just why the same agent cannot be used tomorrow by bots, so they will scan everything without a ban?


thank you, maybe I didn't find the right log either (maybe too late) ... this one does not contain the google UA string but this IP was blocked via apache-fakegooglebot:
[code]
[26/Apr/2021:11:39:12 +0200] "GET / HTTP/1.1" 200 11706 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15"
/var/log/apache2/default/access.log:xxx.xxx.xxx.xxx - - [26/Apr/2021:11:39:17 +0200] "-" 408 - "-" "-"
[/code]

**Comment by sebres** [comment]
What is this? I cannot relate this 2 lines to any log-format I know...

Anyway, jail `apache-fakegooglebot` would only ban log-lines looking like this:
```
192.0.2.1 - - - [26/Apr/2021:12:29:44 ] example.com "GET / HTTP/1.1" 200 814 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" + 293 1149 546
```
The filter `apache-fakegooglebot` is not really good (containing catch-all's etc), see https://github.com/fail2ban/fail2ban/blob/6893d5a8b78fbdf263df8a233b3b9ac343c7a02c/config/filter.d/apache-fakegooglebot.conf#L5

but the regex of filter requires at least the string `Googlebot` within the log message.
So it would never match the lines from your excerpt.
Please grep everything from log for the IP supposed to be banned and provide here the excerpt.

As for "bad" filter regex, although (I don't use apache at all and) neither I'm author of this filter, nor I had ever approved a merge for such weak regex, but I think it must be rewritten to something like this:
```ini
failregex = ^<HOST> \S+ \S+(?: \S+)?(?: \[\s*\])? \S+ "[A-Z]+ /\S* [^"]*" \d+ \d+ \"-\" "[^"]*\bGooglebot/[^"]*"
```
just it would not be backwards compatible (doesn't match any log-format, where it may work previously).
