### ISSUE TITLE
[BR]: fail2ban-client ping fails with python 3.8 installed

### ISSUE THREAD

**Issue by mfechner** [fail2ban/fail2ban#3014]
### Environment:

- Fail2Ban version  : py38-fail2ban-0.11.2
- OS, including release name/version : FreeBSD 13.0
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Executing `fail2ban-client ping` shows the error:
```
2021-05-01 09:07:37,846 fail2ban                [78833]: ERROR   'str' object has no attribute 'args'
```

#### Steps to reproduce

Take a current FreeBSD with the main ports branch (which switch python to 3.8) and execute `fail2ban-client`.

#### Expected behavior

It should work like with python 3.7.

#### Observed behavior

It displays an error message:
```
2021-05-01 09:07:37,846 fail2ban                [78833]: ERROR   'str' object has no attribute 'args'
```

**Comment by chtheis** [comment]
I had the same problem when I updated python a couple of days before. In my case it turned out that in /var/run/fail2ban the files fail2ban.pid and fail2ban.sock were left over and removing them (after stopping the fail2ban service) solved my problem.
I didn't follow the upgrade procedure to its full extend so I assumed it was my fault, but it may be sthg in the upgrade procedure of python and / or the interplay with fail2ban.

**Comment by mundschenk-at** [comment]
I had the same issue and the procedure described by @chtheis fixed things for me. This looks like a cleanup issue with the FreeBSD port.

**Comment by mfechner** [comment]
Thanks for this tips.
I look deeper into it and saw that fail2ban was running with python 3.7.
I killed the process and restarted it and now it is working again as expected.

**Comment by sebres** [comment]
> I killed the process and restarted it...

FWIW, killing of fail2ban may leave some rules of net-filtering subsystem depending to used banning action (which will remain infinitely unless you restart the host). I order to get a clean state it would be better to remove or flush all chains and rules created by fail2ban (after kill or stop before its (re)start).

**Comment by mehov** [comment]
I did the usual Debian `apt-get full-upgrade` and ran into this issue. Thank you @chtheis for the tip, `service fail2ban restart` fixed it for me
