### ISSUE TITLE
[BR]: fail2ban-regex: "IndexError: string index out of range" on incomplete date

### ISSUE THREAD

**Issue by nuno-silva** [fail2ban/fail2ban#3020]
### Environment:

- Fail2Ban version: `Fail2Ban v0.11.2`
- OS, including release name/version : Gentoo/Linux, portage tree 20210505 snapshot
- Python 3.8.8
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

Log line with incomplete date causes *string index out of range* crash in fail2ban-regex.

Also crashes with `failregex=^<HOST>`, etc.

#### Steps to reproduce

1. Install docker or Gentoo
2. In a Gentoo shell (`docker run -it gentoo/stage3`), run the following to install fail2ban:
```sh
emerge-webrsync
emerge fail2ban --quiet-build=y -q
```
3. And to trigger the crash:
```sh
echo -e "[Definition]\nfailregex=" > /etc/fail2ban/filter.d/test.conf

echo -e "10.0.0.2 - - [02/May/2021:18:40:55 +0100] \"GET / HTTP/1.1\" 302 328 \"-\" \"Mozilla/5.0\" \"-\"\n10.0.0.2 - - [02/May/2021:18:40:55\n" > /log.txt

fail2ban-regex /log.txt test
```

#### Expected behavior

fail2ban-regex should not crash.

#### Observed behavior

fail2ban-regex crashes:

```
# fail2ban-regex /log.txt test

Running tests
=============

Use   failregex filter file : test, basedir: /etc/fail2ban
Use         log file : /log.txt
Use         encoding : UTF-8

Traceback (most recent call last):
  File "/usr/bin/fail2ban-regex", line 34, in <module>
    exec_command_line()
  File "/usr/lib/python3.8/site-packages/fail2ban/client/fail2banregex.py", line 836, in exec_command_line
    if not fail2banRegex.start(args):
  File "/usr/lib/python3.8/site-packages/fail2ban/client/fail2banregex.py", line 776, in start
    self.process(test_lines)
  File "/usr/lib/python3.8/site-packages/fail2ban/client/fail2banregex.py", line 584, in process
    line_datetimestripped, ret, is_ignored = self.testRegex(line)
  File "/usr/lib/python3.8/site-packages/fail2ban/client/fail2banregex.py", line 456, in testRegex
    found = self._filter.processLine(line, date)
  File "/usr/lib/python3.8/site-packages/fail2ban/server/filter.py", line 613, in processLine
    timeMatch = self.dateDetector.matchTime(line)
  File "/usr/lib/python3.8/site-packages/fail2ban/server/datedetector.py", line 371, in matchTime
    (line[endpos-1] == self.__lastEndPos[1] and not self.__lastEndPos[1].isalnum())
IndexError: string index out of range
```

#### Any additional information

Also reproduced using Python 3.9.2 (Gentoo, Fail2Ban **v0.11.2**).

Could not reproduce in Ubuntu (Fail2Ban **v0.11.1**).

Only happens after having read a valid date in the previous line.

#### Any customizations done to /etc/fail2ban/ configuration

Only changed `/etc/fail2ban/filter.d/test.conf`:
```
[Definition]
failregex=
```

#### Relevant parts of /var/log/fail2ban.log file:

N/A

#### Relevant lines from monitored log files:

```
10.0.0.2 - - [02/May/2021:18:40:55 +0100] "GET / HTTP/1.1" 302 328 "-" "Mozilla/5.0" "-"
10.0.0.2 - - [02/May/2021:18:40:55
```

**Comment by sebres** [comment]
Although it is a bit unexpected state - rather the logging process needs to flush on whole (fulfilled) line, it is indeed a bug and I'll fix it soon.
Thx for report!

**Comment by nuno-silva** [comment]
Thank you :)

Let me just add that the log is incomplete because I wrote it like that.

I started debugging this from a 269KB log file that triggers a _similar_ (but probably related) crash and while trying to produce a minimal log that would trigger the bug, I found the present issue.
The original log does not contain incomplete lines (that I could find), and I could not yet determine which line triggers the other crash bug, which is:

```
Traceback (most recent call last):
  File "/usr/bin/fail2ban-regex", line 34, in <module>
    exec_command_line()
  File "/usr/lib/python3.9/site-packages/fail2ban/client/fail2banregex.py", line 836, in exec_command_line
    if not fail2banRegex.start(args):
  File "/usr/lib/python3.9/site-packages/fail2ban/client/fail2banregex.py", line 776, in start
    self.process(test_lines)
  File "/usr/lib/python3.9/site-packages/fail2ban/client/fail2banregex.py", line 584, in process
    line_datetimestripped, ret, is_ignored = self.testRegex(line)
  File "/usr/lib/python3.9/site-packages/fail2ban/client/fail2banregex.py", line 456, in testRegex
    found = self._filter.processLine(line, date)
  File "/usr/lib/python3.9/site-packages/fail2ban/server/filter.py", line 613, in processLine
    timeMatch = self.dateDetector.matchTime(line)
  File "/usr/lib/python3.9/site-packages/fail2ban/server/datedetector.py", line 368, in matchTime
    (line[distance] == self.__lastPos[2] and not self.__lastPos[2].isalnum())
IndexError: string index out of range
```

I'm still trying to figure out what lines trigger this other crash. I don't want to upload my whole logs, so I'll give you an update soon.

**Comment by sebres** [comment]
you don't need to investigate deeper (found and fixed already, WiP on the test cases)

**Comment by nuno-silva** [comment]
Thank you for the fix.

Meanwhile, I got it down to these 3 lines:

```
1.1.1.180 - - [03/May/2021:01:42:22 +0100] "GET /a/ HTTP/1.1" 401 466 "-" "a" "-"
1.1.1.180 - JhbGXVCJ9.eyJCI6MTYyMDAn0.mPSnBNqz0TspY-uA4uQtaS-ko2CkbIJCc5DGX95-4mVsX6XswDrQ4NdAyw [03/May/2021:01:42:22 +0100] "GET /a/ HTTP/1.1" 403 531 "-" "a" "-"
1.1.1.180 - - [03/May/2021:01:44:05 +0100] "GET /a/ HTTP/1.1" 401 466 "-" "a" "-"
```
If I delete a few random chars from the "giant username" field (the one before the date) it no longer triggers the IndexError from my last comment. E.g. this one no longer triggers it ¯\_(ツ)_/¯ :

```
1.1.1.180 - - [03/May/2021:01:42:22 +0100] "GET /a/ HTTP/1.1" 401 466 "-" "a" "-"
1.1.1.180 - JhbGXVCJ9.eyJCIn0.mPSspY-uA4S-ko2CX95-4mVsX4NdAyw [03/May/2021:01:42:22 +0100] "GET /a/ HTTP/1.1" 403 531 "-" "a" "-"
1.1.1.180 - - [03/May/2021:01:44:05 +0100] "GET /a/ HTTP/1.1" 401 466 "-" "a" "-"
```

Is it somehow matching a partial date in the giant username?
Can you confirm your fix would apply to this too?

**Comment by sebres** [comment]
Fixed in ef5c826c74c160d33d4b79b23d564f944d16a9dd (waiting for CI and if OK will merge it to all further branches).

The error is basically happen because the datepattern is not specified, and fail2ban uses default pattern set (and an unanchored pattern matches, but then check boundaries fails on incomplete too short line).
You can avoid this (also with your current version) if you specify more precise anchored `datepattern` in filter (jail) or directly in command line:, for example
```
fail2ban-regex -d '^\S+\s+\S+\s+\S+(\s+\[%d(?P<_sep>[-/])%b(?P=_sep)%Y[ :]?%H:%M:%S(?:\.%f)?(?: %z)?\])' "$log_or_lines" '^<ADDR>'
```

> Is it somehow matching a partial date in the giant username?
> Can you confirm your fix would apply to this too?

No (as already said it was not well boundaries check for last known pattern)...
And yes it would, however...

But it is not advisable to use foreign data in line before address or datepattern (and possibly some "anchors" in your regex especially if it is too weak), so if you can, I'd recommend to change the log-format (e. g. to `TIME IP another stuff`), and to anchor date pattern and start of failregex, for instance like here:
```bash
fail2ban-regex -d '^\[{DATE}\]\s+' '[03/May/2021:01:42:22 +0100] 192.0.2.1 - - "GET ...' '^\s*<ADDR> \S+ \S+ "[A-Z]+'
```
(Note: the part of string matching datepattern is cut from line out before failregex gets applied, so it doesn't need to be matched there, so you could anchor it like here by the space).

**Comment by sebres** [comment]
merged

**Comment by nuno-silva** [comment]
Thank you for the clarification.

I just confirmed that applying ef5c826c74c on top of fail2ban v0.11.2 fixes the crash. :muscle: 

Regarding the log format, I understand what you mean but I'm using the default nginx log_format and I'm afraid of breaking other jails by changing the order of things :/ I'll try to "anchor" things in the regex though.

Once again, thank you for the fix and for your work :)

**Comment by sebres** [comment]
FWIW, since it looks like access log, this [wiki article](https://github.com/fail2ban/fail2ban/wiki/Best-practice) may be also interesting to you (especially part about parasite log traffic).

**Comment by nuno-silva** [comment]
Thank you, I'll take a look!
