### ISSUE TITLE
PGP/GPG Public-Key & Fingerprint for Release

### ISSUE THREAD

**Issue by aendeavor** [fail2ban/fail2ban#3026]
Hey there,

I'm coming from docker-mailserver/docker-mailserver#1965 where we are currently implementing F2B version 0.11.2. We want to check the release with a public key and fingerprint, but couldn't find them, see https://github.com/docker-mailserver/docker-mailserver/pull/1965#discussion_r630957451

Can someone help us?

**Comment by sebres** [comment]
You can find an id or fingerprint of key used in signature with following command:
```
gpg --list-packets fail2ban-0.11.2.tar.gz.asc
```
Then search in some of public gpg keys servers of your choice for this [keyid](http://keys.gnupg.net/pks/lookup?search=0x683BF1BEBD0A882C&fingerprint=on) or [fingerprint](keys.gnupg.net/pks/lookup?search=0x8738559E26F671DF9E2C6D9E683BF1BEBD0A882C&fingerprint=on).

Or even much simpler for an [author mail](http://keys.gnupg.net/pks/lookup?search=%40sebres.de&fingerprint=on).

Also see #2806
