### ISSUE TITLE
[FR]: postfix command limits

### ISSUE THREAD

**Issue by fanto666** [fail2ban/fail2ban#3040]
### Environment:

- Fail2Ban version  : 0.10.2-2.1
- OS, including release name/version : Debian GNU/Linux 10 (buster)

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : postfix.conf
- Service, project or product name, including release name/version : postfix 3.4.14-0+deb10u1
- Repository or URL (if known) : 
- Service type : 
- Ports and protocols the service is listening : 

#### Log or journal information

- Log file name(s) : /var/log/mail.log

#### Any additional information

abusive clients/bots hitting command limit produce special errors in log file.
documented in http://www.postfix.org/POSTSCREEN_README.html

These can be catched by adding "COMMAND (TIME|COUNT|LENGTH) LIMIT" to mdpr-ddos:

```
mdpr-ddos = (?:lost connection after(?! DATA) [A-Z]+|disconnect(?= from \S+(?: \S+=\d+)* auth=0/(?:[1-9]|\d\d+))|(?:PREGREET \d+|HANGUP) after \S+|COMMAND (?:TIME|COUNT|LENGTH) LIMIT)
```

#### failures in sense of fail2ban filter (fail2ban must match):

```
Jun  8 23:14:28 proxy2 postfix/postscreen[473]: COMMAND TIME LIMIT from [117.69.31.77]:3608 after CONNECT
Jun  8 23:14:54 proxy2 postfix/postscreen[473]: COMMAND COUNT LIMIT from [185.143.223.26]:15592 after RCPT
```

**Comment by sebres** [comment]
Done in 579c6a94aff0bb680090b3be1aef91491cf0a061. Thx again!
