### ISSUE TITLE
[FR]: Samba? & How to add new Postfix.conf failregex

### ISSUE THREAD

**Issue by zer0nem0** [fail2ban/fail2ban#3045]
### Environment:

- Fail2Ban version  : 
- OS, including release name/version : 

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : 
- Service, project or product name, including release name/version : 
- Repository or URL (if known) : 
- Service type : 
- Ports and protocols the service is listening : 

#### Log or journal information

- Log file name(s) : 

- Journal identifier or unit name : 

#### failures in sense of fail2ban filter (fail2ban must match):

```
```

#### legitimate messages (fail2ban should not consider as failures):

```
```

**Comment by sebres** [comment]
> Samba? & How to add new Postfix.conf failregex

What do you want to tell us with this "very meaningful" statement?

Please don't confuse this with stack exchange platform (serverfault etc) or forums/chat/IRC channels. This here is a developer repository. 
But I'm sure even on mentioned places to ask something with a single sentence like you did it would be a bad practice.
Also our issue template tells what you have to do and what must be filled in the issue.

Sorry, but I'll close it.

**Comment by sebres** [comment]
<blockquote>

Hi Serbes..

Can i add the failregex new code to other regex down my postfix conf like example so:
```
failregex = ^%(__prefix_line)sNOQUEUE: reject: RCPT from \S+[]: 554 5.7.1 .$
^%(_pref)s from [^[][]%(_port)s: [45][50][04] [45].\d.\d+ (?:(?:<[^>]*>)?: )?(?:(?:Helo command|(?:Sender|Recipient) address) rejected: )?(?:Service unavailable|User unknown|(?:Client host|Command|Data command) rejected|Relay access denied|(?:Host|Domain) not found|need fully-qualified hostname|match)\b
```
Anyway i need your big help.. I cant use my old samba.conf

Do you have any idea for debian 10 samba.conf a regex?

I need a regex just for this words:

Denied connection from

original syslog
```
[2021/06/18 03:16:20.638853, 0] ../lib/util/access.c:365(allow_access)
Denied connection from 14.99.254.xxx (14.99.254.xxx)
[2021/06/18 03:16:20.638961, 1] ../source3/smbd/process.c:3824(smbd_add_connection)
Connection denied from ipv4:14.99.254.xxx:59617 to ipv4:5.aa.bb.xx:445
```
I have this old samba config:

Thanks your help!
</blockquote>

**Comment by zer0nem0** [comment]
I just want to ask do you have any sabba.conf failregex you fucktard?
Pls do for me maybe just one good sentence :P

Go fuk urself noob.. next time ddosing ur shit website

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by sebres** [comment]
I already started to write you an answer, but...
But I don't take a part on conversations with people like you.
Reported. Blocked. Bye.
