### ISSUE TITLE
How to write a re for fail2ban?

### ISSUE THREAD

**Issue by MikoyChinese** [fail2ban/fail2ban#3055]
Hi,

Here is my log file format:

```
[20210714-14:35:30] [INFO ] Socket 12: AF_INET6 connection received from ::ffff:133.13.106.152 port 38200
...
```

The fillter conf:

```
[Definition]
datepattern = ^\[%%Y%%m%%d-%%H:%%M:%%S\]
failregex = ^\s*\[INFO\s+\]\s+Socket\s+\d+:\s+AF_INET\d+\s+connection\s+received\s+from\s+::ffff:<F-ID/>
```

But when I run fail2ban-regex log.txt filter.conf, it only returns `ERROR: No failure-id group in`, if I run `fail2ban-regex log.txt '^\[%%Y%%m%%d-%%H:%%M:%%S\]^\s*\[INFO\s+\]\s+Socket\s+\d+:\s+AF_INET\d+\s+connection\s+received\s+from\s+::ffff:<F-ID/>'`, it has no matched.

Can you help to get the ip such like the log file `133.13.106.152` to fillter conf?

**Comment by sebres** [comment]
> it has no matched.

But it should. 
What is your fail2ban version? I guess 0.9, because, tags like `<F-ID>` are provided starting from 0.10 and 0.9th version does not support it.

Anyway since you don't need here to use `<F-ID/>` (it is for non-IP jails), you can use `<HOST>` instead (also note that IPs in `::ffff:...` format will be also matched by this tag.

```diff
- failregex = ^\s*\[INFO\s+\]\s+Socket\s+\d+:\s+AF_INET\d+\s+connection\s+received\s+from\s+::ffff:<F-ID/>
+ failregex = ^\s*\[INFO\s*\]\s+Socket\s+\d+:\s+AF_INET\d+\s+connection\s+received\s+from\s+<HOST>
```
(for 0.10 and higher better is to use tag `<ADDR>` instead of `<HOST>` for pure IP input)

**Comment by MikoyChinese** [comment]
I am using fail2ban-regex 0.11.1 to check the re filter, and I try your solution to run `fail2ban-regex test.log test.conf`, it only returns:

```
Running tests
=============

Use   failregex line : test.conf
ERROR: No failure-id group in 'test.conf'
```

**test.log**

```
[20210714-14:35:30] [INFO ] Socket 12: AF_INET6 connection received from ::ffff:133.13.106.152 port 38200
```

**test.conf**

```
[Definition]
datepattern = ^\[%%Y%%m%%d-%%H:%%M:%%S\]
failregex = ^\s*\[INFO\s*\]\s+Socket\s+\d+:\s+AF_INET\d+\s+connection\s+received\s+from\s+<HOST>
```

So I am so confused.

**Comment by sebres** [comment]
OK, where is your `test.conf`?
It looks like the argument is considering as a failregex and not as filter file name.

- either you'd place your filter in `/etc/fail2ban/filter.d`, then it is possible to supply it as `test` (or `test.conf`)
- or you'd provide the whole file name to `fail2ban-regex`, either something like `"$(pwd)/test.conf"` or `./test.conf`

Another variant to test it (without filter) would be:
```
fail2ban-regex -d "$datepattern" "$msg_or_log" "$re"
```
so in your case:
```
msg='[20210714-14:35:30] [INFO ] Socket 12: AF_INET6 connection received from ::ffff:133.13.106.152 port 38200'
fail2ban-regex -d '^\[%Y%m%d-%H:%M:%S\]' "$msg" '^\s*\[INFO\s+\]\s+Socket\s+\d+:\s+AF_INET\d+\s+connection\s+received\s+from\s+<ADDR>'
```
then you can set it directly in jail (without filter file):
```ini
[test-jail]
filter =
datepattern = ^\[%%Y%%m%%d-%%H:%%M:%%S\]
failregex = ^\s*\[INFO\s*\]\s+Socket\s+\d+:\s+AF_INET\d+\s+connection\s+received\s+from\s+<ADDR>
```

**Comment by MikoyChinese** [comment]
Fine, I change the `test.conf` to `./test.conf`, now it is working for matching. 
Thanks for your help, you are great.
