### ISSUE TITLE
[BR]: failregex working on CLI but not in filter config

### ISSUE THREAD

**Issue by Yannik** [fail2ban/fail2ban#3062]
### Environment:

- Fail2Ban version: 0.10.2-2.1
- OS, including release name/version : debian
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase

### The issue:
I'm trying to match the following log-lines:

```
time="2021-07-19T18:13:58Z" level=debug msg="Answering question for domain" domain=pizzaseo.com. qtype=RRSIG rcode=NXDOMAIN remoteaddr="172.17.0.1:53469"
time="2021-07-19T18:13:58Z" level=debug msg="Answering question for domain" domain=pizzaseo.com. qtype=RRSIG rcode=NXDOMAIN remoteaddr="98.156.167.222:80"
```

The lines are correctly matched using the following cli call: `fail2ban-regex ~/fail2ban.log "^.* rcode=NXDOMAIN remoteaddr=\"<HOST>:\d+\"$"`
However, when using a failregex definition in a filter config file, no lines are matched: `fail2ban-regex ~/fail2ban.log /etc/fail2ban/filter.d/myfilter.conf`

`myfilter.conf`:
```
[INCLUDES]
before = common.conf

[Definition]
failregex = ^.* rcode=NXDOMAIN remoteaddr="<HOST>:\d+"$
```
I also tried escaping the double quotes, leaving of the `^` and `$`, but none of that worked. The debuggex (-D option, [example](https://www.debuggex.com/?re=.%2A+rcode%3DNXDOMAIN+remoteaddr%3D%22%28%3F%3A%28%3F%3A%3A%3Af%7B4%2C6%7D%3A%29%3F%28%3FP%3Cip4%3E%28%3F%3A%5Cd%7B1%2C3%7D%5C.%29%7B3%7D%5Cd%7B1%2C3%7D%29%7C%5C%5B%3F%28%3FP%3Cip6%3E%28%3F%3A%5B0-9a-fA-F%5D%7B1%2C4%7D%3A%3A%3F%7C%3A%3A%29%7B1%2C7%7D%28%3F%3A%5B0-9a-fA-F%5D%7B1%2C4%7D%7C%28%3F%3C%3D%3A%29%3A%29%29%5C%5D%3F%7C%28%3FP%3Cdns%3E%5B%5Cw%5C-.%5E_%5D%2A%5Cw%29%29%3A%5Cd%2B.%2A&str=time%3D%222021-07-19T18%3A14%3A14Z%22+level%3Ddebug+msg%3D%22Answering+question+for+domain%22+domain%3Dpizzaseo.com.+qtype%3DRRSIG+rcode%3DNXDOMAIN+remoteaddr%3D%22172.17.0.1%3A53469%22&flavor=python)) actually shows the lines should be matched correctly.

**Comment by sebres** [comment]
By default the include `common.conf` provides `{^LN-BEG}` as `datepattern`, which uses default timestamps **anchored** at begin of line.
You don't need this include at all (because don't use something from there), so just delete first 2 lines from filter.

Just I wouldn't recommend this RE, as well as the unanchored (default) datepattern. Better use something like this:
```ini
[Definition]
datepattern = ^time="%%Y-%%m-%%dT%%H:%%M:%%S(?:%%z)?"\s+
failregex = ^\s*level=debug msg="Answering question for domain" domain=\S+ qtype=RRSIG rcode=NXDOMAIN remoteaddr="<HOST>:\d+"$
```

**Comment by Yannik** [comment]
Thank you very much, @sebres!

**Comment by Yannik** [comment]
Hey @sebres,

using the filter for a logfile works fine, but when using `systemd-journal` and `journalmatch` as log source, it does not work anymore, because (according to `--print-all-missed`), the lines being matched against look like this:
```
|  2021-08-02T17:31:49.745511myhostname d13f76add715[803]: time="2021-08-02T15:31:49Z" level=debug msg="Answering question for domain" domain=pizzaseo.com. qtype=RRSIG rcode=NXDOMAIN remoteaddr="79.247.161.200:40157"
|  2021-08-02T17:38:12.794863myhostname d13f76add715[803]: time="2021-08-02T15:38:12Z" level=debug msg="Answering question for domain" domain=pizzaseo.com. qtype=RRSIG rcode=NXDOMAIN remoteaddr="79.247.161.200:35509"
```
Is there an option to automatically ignore the journald-timestamp/hostname/process-name/process-id prefix, so that the filter works both with a logfile and with systemd-journald?

**Comment by sebres** [comment]
> Is there an option to automatically ignore the journald-timestamp/hostname/process-name/process-id prefix, so that the filter works both with a logfile and with systemd-journald?

Conditionally. And `common.conf` could indeed help here, but in your case it is much simpler even without common include:
```ini
[Definition]
datepattern = ^time="%%Y-%%m-%%dT%%H:%%M:%%S(?:%%z)?"\s+
failregex = ^\s*(?:\S+ \S+\[\d+\]: (?:time=\S+)?)?\s*level=debug msg="Answering question for domain" domain=\S+ qtype=RRSIG rcode=NXDOMAIN remoteaddr="<HOST>:\d+"$
```
The part `(?:\S+ \S+\[\d+\]: (?:time=\S+)?)?` will match `host process[...]: time="..."` optionally, and `datepattern` is ignored by systemd backend (timestamp is retrieved from journal entry), so this variant must work for both log-file and journal.

**Comment by Yannik** [comment]
@sebres Thank you so much, I have extracted your suggested regex to a variable like this:
```
__prefix_journal = \s*(?:\S+ \S+\[\d+\]: (?:time=\S+)?)?
failregex = ^%(__prefix_journal)s\s*level=debug msg="Answering question for domain" domain=\S+ qtype=\S+ rcode=NXDOMAIN remoteaddr="<HOST>:\d+"$
``` 
...and it works just as it should!
