### ISSUE TITLE
Does Fail2ban support specified directory installation? 

### ISSUE THREAD

**Issue by fubingting** [fail2ban/fail2ban#3070]
#### Feature request type
Does Fail2ban support specified directory installation? 

#### Description
Many configuration files are specified in /etc, /usr. Does Fail2ban support installation in a specified directory? Can configuration files such as / etc/fail2ban specify a directory during installation?What parameters do Ineed to add to the installation command

**Comment by sebres** [comment]
> Does Fail2ban support installation in a specified directory?

Fail2ban setup using pythons `distutils` (and `setuptools`) to install itself so you can use any prefixes both modules are accepting on your system. Use `./setup.py install --help` to see which parameters it accept (you can also use `--dry-run` to check the installation without really to install).

BTW. You don't need to install fail2ban at all, you can use it as portable or standalone version - see [wiki :: How to test newer fail2ban version resp. use fail2ban standalone instance](https://github.com/fail2ban/fail2ban/wiki/How-to-test-newer-fail2ban-version-resp.-use-fail2ban-standalone-instance).
