### ISSUE TITLE
[BR] [0.11.1]:  date/time format not found

### ISSUE THREAD

**Issue by tuxmaster5000** [fail2ban/fail2ban#3075]
fail2ban-regex /tmp/test '<HOST>.+appswitcher.+401$'

> will show this format:
> Running tests
> =============
> 
> Use   failregex line : <HOST>.+appswitcher.+401$
> Use         log file : /tmp/test
> Use         encoding : UTF-8
> 
> 
> Results
> =======
> 
> Failregex: 1 total
> |-  #) [# of hits] regular expression
> |   1) [1] <HOST>.+appswitcher.+401$
> `-
> 
> Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [42] {^LN-BEG}Day(?P<_sep>[-/])MON(?P=_sep)ExYear[ :]?24hour:Minute:Second(?:\.Microseconds)?(?: Zone offset)?
`-

But using "{^LN-BEG}Day(?P<_sep>[-/])MON(?P=_sep)ExYear[ :]?24hour:Minute:Second(?:\.Microseconds)?(?: Zone offset)?" as  an date format:
```
failregex = <HOST>.+appswitcher.+401$
datepattern = {^LN-BEG}Day(?P<_sep>[-/])MON(?P=_sep)ExYear[ :]?24hour:Minute:Second(?:\.Microseconds)?(?: Zone offset)?
```
will fails with:

> 2021-07-27 14:02:40,903 fail2ban.filter         [71444]: WARNING Found a match for u'[27/Jul/2021:14:02:40 +0200] 51.158.186.59 TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384 "GET /rest/menu/latest/appswitcher?_=1627387360400 HTTP/1.1" 401' but no valid date/time found for u'[27/Jul/2021:14:02:40 +0200] 51.158.186.59 TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384 "GET /rest/menu/latest/appswitcher?_=1627387360400 HTTP/1.1" 401'. Please try setting a custom date pattern (see man page jail.conf(5)). If format is complex, please file a detailed issue on https://github.com/fail2ban/fail2ban/issues in order to get support for this format.

What make I wrong?

**Comment by tuxmaster5000** [comment]
Here an sample of the log file:
[27/Jul/2021:13:59:12 +0200] 51.158.186.59 TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384 "POST /j_atl_security_check HTTP/1.1" -
[27/Jul/2021:13:59:12 +0200] 51.158.186.59 TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384 "GET /login?nextUrl=%2Fdashboard HTTP/1.1" 11155
[27/Jul/2021:13:59:13 +0200] 51.158.186.59 TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384 "GET /rest/menu/latest/appswitcher?_=1627387153000 HTTP/1.1" 401

**Comment by sebres** [comment]
You was trying to use abbreviated artificial "name" of default patterns as `datepattern`. This would not work.

If you need a more precise pattern for this, it will be something like that:
```ini
datepattern = ^\[%%d/%%b/%%Y:%%H:%%M:%%S(?: %%z)?\]\s+
```
And as an example for more precise filter:
```ini
datepattern = ^\[%%d/%%b/%%Y:%%H:%%M:%%S(?: %%z)?\]\s+
failregex = ^<ADDR> [^"]*"[A-Z]+ /[^"]+/appswitcher\b[^"]*" 401
```
