### ISSUE TITLE
[BR]: Issue with the Installer built in to the git distro

### ISSUE THREAD

**Issue by spine001** [fail2ban/fail2ban#3076]
When following the git installation instructions, for version 1.01 in Ubuntu 20.04.2 after having previously installed version 0.11 that prepackaged for installation with apt with the distribution of Ubuntu Linux 20.04.2. You encounter the following problem:
Lost in the screen logging you get a warning:
```
...
copying build/scripts-2.7/fail2ban-server -> /usr/local/bin
copying build/scripts-2.7/fail2ban-client -> /usr/local/bin
copying build/scripts-2.7/fail2ban-regex -> /usr/local/bin
copying build/scripts-2.7/fail2ban-testcases -> /usr/local/bin
WARNING: Cannot find root-base option, check the bin-path to fail2ban-scripts in "fail2ban.service".
Creating build/fail2ban.service (from fail2ban.service.in): @BINDIR@ -> /usr/local/bin
creating fail2ban-python binding -> /usr/local/bin
changing mode of /usr/local/bin/fail2ban-server to 755
changing mode of /usr/local/bin/fail2ban-client to 755
changing mode of /usr/local/bin/fail2ban-regex to 755
changing mode of /usr/local/bin/fail2ban-testcases to 755
running install_data
copying config/paths-debian.conf -> /etc/fail2ban
...
And at the end this (confusing for me) information:
```
Please do not forget to update your configuration files.
They are in "/etc/fail2ban/".

You can also install systemd service-unit file from "build/fail2ban.service"
resp. corresponding init script from "files/*-initd".```
```
When I go and check my /usr/local/bin I find that the files there are still from the old 0.11 March 2020 distribution.

I also find that there is another copy of the same older files under /user/bin (not links)

The fail2ban.service files are also from the previous version, haven't been updated.

Shouldn't this be corrected in the installer? Shouldn't  the files be only in one /bin directory? It may be advisable to do some cleaning of previous installations before starting the new one. People should be able to timeshift if anything goes wrong.

Question:
I corrected these problems by:
1. copying the files from the installation directory to the /user/local/bin directory with the following commands:
sudo cp ./scripts-2.7/fail2ban-server /usr/local/bin
sudo cp ./scripts-2.7/fail2ban-client /usr/local/bin
sudo cp ./scripts-.7/fail2ban-regex /usr/local/bin
sudo cp ./scripts-2.7/fail2ban-testcases /usr/local/bin
/usr/bin$ sudo cp -av ../local/bin/fail2ban-python ./
/usr/bin$ sudo cp
/usr/bin$ sudo cp ../local/bin/fail2ban* ./
./fail2ban/build$ sudo cp fail2ban.service /var/lib/systemd/deb-systemd-helper-enabled/multi-user.target.wants/fail2ban.service
sudo cp fail2ban.service /usr/lib/systemd/system/fail2ban.service

I use both python 2.7.18 and python 3.8.10 in my system, the old fail2ban-python in 0.11 was linked to python 3.8.10 and the new one after the installation is now linked with 2.7.18

So my questions are:
1.- Is what I did correct?
2.- Am I missing some steps?
3.- Should I change the link to point at python3?

Thanks!

**Comment by sebres** [comment]
> Shouldn't this be corrected in the installer? Shouldn't  the files be only in one /bin directory? 

Basically this is a matter of maintainers (because the prefixes/directories where it gets to be installed is distribution related stuff).

> Is what I did correct?

No. You have to uninstall distribution-based fail2ban installation before you install it manually.

> Am I missing some steps?

Take a look at [wiki :: How to install or upgrade fail2ban manually](https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually). If you mean we have missed some points there, welcome with the amendments suggestions.

> Should I change the link to point at python3?

No, or rather not directly. If you want either use fail2ban with python3, you have to install it for python3 (so `2to3` firstly and then `python3 setup.py install`).
Otherwise you may use old (not upgraded) version of fail2ban module installed for python 3.

**Comment by spine001** [comment]
Thanks
