### ISSUE TITLE
[BR]: Likely antoher configuration of documentation bug

### ISSUE THREAD

**Issue by spine001** [fail2ban/fail2ban#3077]
```
ulio@julio-Z390-UD:~$ fail2ban-client version
2021-08-01 15:49:20,700 fail2ban                [3939]: ERROR   Permission denied to socket: /var/run/fail2ban/fail2ban.sock, (you must be root)
julio@julio-Z390-UD:~$ fail2ban-client -V
1.0.1.1
```

**Comment by sebres** [comment]
`fail2ban-client version` try to send command `version` to the server (to do that you must be root/sudoer).
Otherwise try:
```diff
-fail2ban-client version
+# version of server:
+sudo fail2ban-client version
+# version of client:
+fail2ban-client --version
```

**Comment by spine001** [comment]
HI sebres, sorry not trying ot be dense. I know what you said. Thanks. My point was that for anybody following the documentation, you get an error when issuing the command that it tells you to, so we need to fix the documentation, at least in the Readme.md file.
