### ISSUE TITLE
[FR]: New datetime format

### ISSUE THREAD

**Issue by duhvir** [fail2ban/fail2ban#3079]
#### Feature request type
  Some daemons uses datetime format "YYYYMMDDHHMMSS". For example "slapd"
20210809151212 <host> slapd[689855]: conn=1030 fd=12 ACCEPT from IP=<x.y.z.a>:48503 (IP=0.0.0.0:389)

#### Description
  This format not detected as epoch, because is not. And I can't add format to "server/datedetector.py" because format doesn't contains separators.

#### Considered alternatives
  See no such. But my python knowledge is limited

**Comment by duhvir** [comment]
# YYYYMMDDHHMMSS
        r"%ExY%Exm%Exd%H%M%S",

**Comment by sebres** [comment]
You don't need to customize `server/datedetector.py` - just set `datepattern` to the jails (or filters) using this timestamp format:
```ini
datepattern = ^%%Y%%m%%d%%H%%M%%S
```
