### ISSUE TITLE
[RFE]: Use cloudflare API token instead of global key

### ISSUE THREAD

**Issue by ElDavoo** [fail2ban/fail2ban#3080]
#### Feature request type
I'd like cloudflare.conf to use a specific API key that only has access to the firewall instead of giving the global API key.

#### Description
There are two ways to access CloudFlare's APIs : The first is the "quick and dirty" way, with a global API key that has access to everything in your account. It is essentially equivalent to your password.
The second way is by using API Tokens, that are made specifically for one application and only has the required permissions. As example, the token for fail2ban would only have the permission to read and write firewall rules.

I have no idea if it is actually feasible to do in fail2ban as you probably need to make multiple requests

**Comment by sebres** [comment]
Making of multiple requests is not an issue, I guess you'd need to preserve some response data (tokens or session-ids?) in order to use by the ban requests...
This is feasible in fail2ban, just at the moment the command actions are not really suitable for that, but it'd be pretty simple with pythonic actions.
For few examples see [action.d/smtp.py](https://github.com/fail2ban/fail2ban/blob/10cd81552538fa950cefc32787b9f82b5ee1b998/config/action.d/smtp.py#L72) or [action.d/badips.py](https://github.com/fail2ban/fail2ban/blob/b25d8565fc23da58f97d1da649b46d27fb80b64a/config/action.d/badips.py#L39)

**Comment by wpkc** [comment]
This looks easy to do judging by information available [here.](https://api.cloudflare.com/#getting-started-requests)  

Here is the Global API Key method (which uses the account email + an API key)
```
curl -X GET "https://api.cloudflare.com/client/v4/zones/cd7d0123e3012345da9420df9514dad0" \
     -H "Content-Type:application/json" \
     -H "X-Auth-Key:1234567893feefc5f0q5000bfo0c38d90bbeb" \
     -H "X-Auth-Email:example@example.com"
```

Here is the Authorization Bearer Token method (which only uses an API key)
```
curl -X GET "https://api.cloudflare.com/client/v4/zones/cd7d0123e3012345da9420df9514dad0" \
     -H "Content-Type:application/json" \
     -H "Authorization: Bearer YQSn-xWAQiiEh9qM58wZNnyQS7FUdoqGIUAbrh7T"
```


I would suggest the following for cloudflare-restv4.conf...
```
# Option:  actionban
# Notes.:  command executed when banning an IP. Take care that the
#          command is executed with Fail2Ban user rights.
# Tags:    <ip>  IP address
#          <failures>  number of failures
#          <time>  unix timestamp of the ban time
# Values:  CMD
#
actionban = curl -s -X POST https://api.cloudflare.com/client/v4/user/firewall/access_rules/rules \
	-H "Authorization: Bearer <cfkey>" -H "Content-Type: application/json" \
	--data '{"mode":"block","configuration":{"target":"ip","value":"<ip>"},"notes":"Banned by Fail2Ban"}'

# Option:  actionunban
# Notes.:  command executed when unbanning an IP. Take care that the
#          command is executed with Fail2Ban user rights.
# Tags:    <ip>  IP address
#          <failures>  number of failures
#          <time>  unix timestamp of the ban time
# Values:  CMD
#
actionunban = curl -s -X GET -H "Authorization: Bearer <cfkey>" -H "Content-Type: application/json" \
	"https://api.cloudflare.com/client/v4/user/firewall/access_rules/rules?page=1&per_page=5&mode=block&configuration.target=ip&configuration.value=<ip>&notes=Banned by Fail2Ban&match=all&order=configuration.value&direction=desc" | \
	python -c "import sys, json; print json.load(sys.stdin)['result'][0]['id'];" | \
	xargs -I@@ curl -s -X DELETE -H "Authorization: Bearer <cfkey>" -H "Content-Type: application/json" https://api.cloudflare.com/client/v4/user/firewall/access_rules/rules/@@
```

Then in jail.local, get rid of the unneeded cfemail and use cfapikey for the bearer token...
```
cfapikey = YQSn-xWAQiiEh9qM58wZNnyQS7FUdoqGIUAbrh7T
action_cf_v4 = cloudflare-restv4[cfkey="%(cfapikey)s"]
```

Pretty straight forward.

If you care about backward compatibility, then I recommend creating a new action script with a new name.  Maybe /fail2ban/action.d/cloudflare-restv4-bearer-token.conf.

**Comment by wpkc** [comment]
I set up a new repository with a new CloudFlare action file, if anyone wants to try it out...
[github.com/wpkc/fail2ban-action-cloudflare-restv4-bearer-token](https://github.com/wpkc/fail2ban-action-cloudflare-restv4-bearer-token)

I also threw together a blog article to explain how it works...
[kazimer.com/fail2ban-cloudflare-action-using-authorization-bearer-token/](https://www.kazimer.com/fail2ban-cloudflare-action-using-authorization-bearer-token/)

Enjoy!

**Comment by wpkc** [comment]
Nah.  I'm no fail2ban expert.  Others can argue out what it should be.  I just leave my suggestions.

**Comment by charliesjc** [comment]
I've been experimenting with this and I am also no expert at all. But I found the above didn't work for me so I modded the last bit of the unban action to this:

`actionunban = curl -s -X DELETE -H 'Authorization: Bearer <cfkey>' \
              https://api.cloudflare.com/client/v4/user/firewall/access_rules/rules/$(curl -s -X GET -H 'Authorization: Bearer <cfkey>' \
              'https://api.cloudflare.com/client/v4/user/firewall/access_rules/rules?mode=block&configuration_target=ip&configuration_value=<ip>&page=1&per_page=1' | jq -r '.result[] | .id')`

The main difference is I just used jq. It was installed by default on my Ubuntu 20.04 system.
