### ISSUE TITLE
fail2ban does not search by regex

### ISSUE THREAD

**Issue by Keller18306** [fail2ban/fail2ban#3082]
![image](https://user-images.githubusercontent.com/23178771/129264938-0d81be46-b396-4ed3-a892-2a3d498a1257.png)
![image](https://user-images.githubusercontent.com/23178771/129265055-1a6478ea-9c28-452d-985f-a79fa798a3ac.png)

**Comment by sebres** [comment]
Fail2ban before #2814 (0.10.6/0.11.2) is unable to process the line without a match of timestamp.
Your timestamp format is unknown for fail2ban (isn't matching by its default templates), so you have to specify own `datepattern`.

```bash
fail2ban-regex -d '^\[%d.%m.%Y %H:%M:%S,%f\]:\s*' '[07.08.2021 22:02:23,674]: 127.0.0.1 on port 22' '^<ADDR> on port'
```

```ini
datepattern = ^\[%%d.%%m.%%Y %%H:%%M:%%S,%%f\]:\s*
failregex = ^<ADDR> on port
```
