### ISSUE TITLE
[FR]:  datepattern  problem

### ISSUE THREAD

**Issue by korvinys095** [fail2ban/fail2ban#3091]
Fail2Ban v0.9.6

Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch

- Service type :  xrdp
- Ports and protocols the service is listening : name=rdp, port="3389,3390,3391", protocol=tcp
```
WARNING Found a match for '[20210824-14:23:30] [INFO ] A connection received from: ::ffff:112.29.139.34 port 12207' but no valid date/time found for '[20210824-14:23:30] [INFO ] A connection received from: ::ffff:112.29.139.34 port 12207'. Please try setting a custom date pattern (see man page jail.conf(5)). If format is complex, please file a detailed issue on https://github.com/fail2ban/fail2ban/issues in order to get support for this format.
```
Config of jail
/etc/fail2ban/jail.d/xrdp
```ini
[xrdp]
enabled = true
filter = xrdp
action = iptables-multiport[name=rdp, port="3389,3390,3391", protocol=tcp]
logpath = /var/log/xrdp.log
maxretry = 5
```
/etc/fail2ban/filter.d/xrdp.conf 
```
[Definition]

# Example 
# [20210824-13:30:33] [INFO ] A connection received from: ::ffff:112.29.139.34 port 11968

failregex = connection received from: <HOST> 
ignoreregex =
datepattern = %Y%m%d-%H:%M:%S
```

I check use fail2ban-regex
```
$ fail2ban-regex -v -d "^\[%Y%m%d-%H:%M:%S\]" "[20210824-14:21:14] [INFO ] A connection received from: ::ffff:112.29.139.34 port 1219" /etc/fail2ban/filter.d/rdp.conf

Running tests
=============

Use      datepattern : ^\[YearMonthDay-24hour:Minute:Second\]
Use   failregex filter file : rdp, basedir: /etc/fail2ban
Use      single line : [20210824-14:21:14] [INFO ] A connection received ...


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] connection received from: <HOST>
|      112.29.139.34  Tue Aug 24 14:21:14 2021
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] ^\[YearMonthDay-24hour:Minute:Second\]
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.00 sec]
```

**Comment by korvinys095** [comment]
I have mistake in location of config. sure, it in /etc/fail2ban/jail.cof

**Comment by sebres** [comment]
So if I understand correctly the issue looks like it works with fail2ban-regex (with specifying of datepattern using parameter `-d`) but does not work within fail2ban?

You fail2ban version is too old (0.9.6), for this version the datepattern must be included in section `Init`, so change your filter in this way:
```diff
 [Definition]
 failregex = ...
+[Init]
 datepattern = %Y%m%d-%H:%M:%S
```

**Comment by korvinys095** [comment]
> So if I understand correctly the issue looks like it works with fail2ban-regex (with specifying of datepattern using parameter `-d`) but does not work within fail2ban (or in fail2ban-regex without `-d ...`)?
> 
> You fail2ban version is too old (0.9.6), for this version the parameter `datepattern` must be included in section `Init`, so change your filter in this way:
> 
> ```diff
>  [Definition]
>  failregex = ...
> +[Init]
>  datepattern = %%Y%%m%%d-%%H:%%M:%%S
> ```
> 
> Also note that `%`-char must be escaped in the configs - written as double `%`-char like `%%`

Thank you so match! I can't install different version on Debian 9 =(
