### ISSUE TITLE
[RFE]: minor - standardize return messages from commands

### ISSUE THREAD

**Issue by attritionorg** [fail2ban/fail2ban#3094]
#### Feature request type
'fail2ban-client' output should be standardized

#### Description
www /squirrel/fail2ban/filter.d# fail2ban-client unban 1.2.3.4
1
www /squirrel/fail2ban/filter.d# fail2ban-client reload
OK

Rather than a 0/1 reply for unban, it should have more friendly output matching the reload command.

**Comment by sebres** [comment]
> 'fail2ban-client' output should be standardized

There is no standard. The commands return what is more appropriate for the result of them. Basically beautifier module formatting the output more user "friendly", which indeed could be replaced by something else, see #855 for example.

Additionally we shall avoid backwards incompatible changes.

> fail2ban-client unban ...;  fail2ban-client reload 

Whereas the former returns count of tickets got unbanned (can be more than 1 or even 0), the later signaling a success.

Let us avoid duplicates, thus close and further in #855 please (also if other "standardized" formatter will be not necessarily JSON).
