### ISSUE TITLE
[BR]: build fails against setuptools 58+

### ISSUE THREAD

**Issue by stanislavlevin** [fail2ban/fail2ban#3098]
This project has option `use_2to3` in `setup.py`, which support has been removed in setuptools since version 58.0.0 https://setuptools.readthedocs.io/en/latest/history.html#v58-0-0:
> 2086: Removed support for 2to3 during builds. Projects should port to a unified codebase or pin to an older version of Setuptools using PEP 518 build-requires.

The build fails with:
> /usr/bin/python3 setup.py build
error in fail2ban setup command: use_2to3 is invalid

**Comment by sebres** [comment]
Basically the way would be 2to3 firstly and then setup, like here:
```bash
./fail2ban-2to3
python3 setup.py build
```
so we can indeed remove it in setup.

**Comment by stanislavlevin** [comment]
FYI https://docs.python.org/3/library/2to3.html#module-lib2to3:
> Deprecated since version 3.10: Python 3.9 will switch to a PEG parser (see PEP 617), and Python 3.10 may include new language syntax that is not parsable by lib2to3’s LL(1) parser. The lib2to3 module may be removed from the standard library in a future Python version. Consider third-party alternatives such as LibCST or parso.

**Comment by invakid404** [comment]
Hello @sebres. Are there any updates on this? We're also hit by this issue over at Funtoo Linux.

**Comment by sebres** [comment]
2to3 is removed for now in setup completely.
To install/build for python3 from source, it is necessary to convert to py3 codebase before setup (invoke `2to3` or `./fail2ban-2to3` firstly).
The people installing from distros must be not affected.

**Comment by invakid404** [comment]
Thanks for resolving the issue @sebres. Will a new release be published or should we resort to building master for now?

**Comment by sebres** [comment]
New releases will be surely published at some point (I have no plan right now when exactly)...
And master (v.1.0) was not yet released at all (and I have to do much more stuff to release it, since there are several todo's on my side)...
Note that this was fixed in 0.10 / 0.11 / 1.0 branches.
