### ISSUE TITLE
[RFE]: Possibility to ban a list of IPs in one go.

### ISSUE THREAD

**Issue by gnosoz** [fail2ban/fail2ban#3099]
#### Feature request type
Possibility to ban a list of IPs in one go.

#### Description
Would be great to have the possibility to populate the bans in one go maybe by simply having a line on the jail.local for the singular jail or in the general / default section that upon restart will perform the required ban_action. 

Something like the following...
```
[DEFAULT]
ignoreip = x y z
**banip = ip1 ip2 ip3 ip4... ipn+1 **

[jailname]
ignoreip = x y z
**banip = ip1 ip2 ip3 ip4... ipn+1 **
```
Likewise this could be implemented as a command like the following:
```
fail2ban-client set <jailname> banlist ip1 ip2...ipn
fail2ban-client set <jailname> banlist </path/file.extension>

```

#### Considered alternatives
Currently we are running an ansible playbook from a server to a cluster of remote machines which bans each ip on a given list in each remote machine with the  command ` fail2ban set <jailname> banip <ip>`

This is proving an extremely slow process because it needs to ban them one by one and await confirmation prior sending to the remote machine the next ip to ban

#### Any additional information
The lists usually amounts to circa 50/100 ips and with a cluster of hundreds of machine the current process via ansible playbook is taking roughly a couple of hours

**Comment by sebres** [comment]
As for banip as a setting, I don't really see any advantage of such configuration:
- either it is something related to persistent banning (a jail with all-ports action and `bantime = -1` is enough)
- or one would do that directly in firewall/net-filter

As for manual banning of multiple IPs using `fail2ban-client`, it is already available in newer versions (0.10.5 and 0.11.1), see #2351.

As for performance, it will change as soon we'd provide bulk ban support for the actions.
