### ISSUE TITLE
[BR]: ERROR  fail2ban-client get NOK: ('list index out of range',)

### ISSUE THREAD

**Issue by kasumiru** [fail2ban/fail2ban#3101]
- Fail2Ban version: Fail2Ban v1.0.1.dev1
- OS, including release name/version :  debian 10

type `fail2ban-client get` and I see error:
```
2021-09-15 15:45:47,945 fail2ban                [2446]: ERROR   NOK: ('list index out of range',)
Sorry but the command is invalid
```
and my sqlite3 file: `-rw------- 1 root root 89M 2021.09.15 15:48 /var/lib/fail2ban/fail2ban.sqlite3`

And fail2ban cant block nobody new..
May be it is not a bug, but looks like a bug. 
ps: last opened bug report: https://sourceforge.net/p/fail2ban/bugs/73/ 
option `dbpurgeage = ` it is not solution, it is temporary, not garanted workaround.

**Comment by sebres** [comment]
Well it looks like 2 issues to me:
1. There is probably no check for valid parameters in `fail2ban-client get`, it expects an option (or a jail-name and option) to get.
But this "error" cannot and would never cause the second issue (the server should run further)...
2. <blockquote>fail2ban cant block nobody new..</blockquote>
There is not enough info, what exactly happens here... 
- are there some entries or errors in fail2ban.log which could explain it? 
- do you see entries like `[jail] Found <IP>` in fail2ban.log? etc.

As for DB size - 89M is not big, I saw much more larger fail2ban databases.

> option dbpurgeage = it is not solution, it is temporary, not garanted workaround.

What do you mean as workaround?.. Workaround for what exactly?

**Comment by kasumiru** [comment]
Thank Your for quick answer!

1. ```
00:16:28-root@gwhg: ~ # fail2ban-client get sshd
2021-09-16 00:16:53,742 fail2ban                [26928]: ERROR   NOK: ('list index out of range',)
Sorry but the command is invalid
00:16:21-root@gwhg: ~ # fail2ban-client status
Status
|- Number of jail:      1
`- Jail list:   sshd
```
2.  `fail2ban cant block nobody new..`.
 Then post this BR, I checked fail2ban and it was not worked. Now (after decrease ban time parameters, and restart) fatil2ban normally worked - blocked new ssh connection, but.... still have a:```
01:04:46-root@gwhg: ~ # fail2ban-client get sshd
2021-09-16 01:04:46,617 fail2ban                [28916]: ERROR   NOK: ('list index out of range',)
Sorry but the command is invalid
```
fatil2ban log file: 
[part_of_fail2ban.log](https://github.com/fail2ban/fail2ban/files/7173560/part_of_fail2ban.log)

**Comment by sebres** [comment]
Take an attentive look at what I wrote above:
*it expects an option (or a **jail-name and option**) to get.*

So try this:
```diff
- fail2ban-client get sshd
+ fail2ban-client get sshd $option
```
the option can be for instance "banip", so `fail2ban-client get sshd banip` would return banned ips of sshd jail.

And `fail2ban-client --help` would show you the usage syntax.

**Comment by kasumiru** [comment]
ok, I see, it's not a bug, it's my mistake, excuse me!
