### ISSUE TITLE
postfix-sasl filter not catching log entries

### ISSUE THREAD

**Issue by lnappa** [fail2ban/fail2ban#3103]
Hello,
Fail2Ban v0.10.2
Linux 4.15.0-156-generic #163-Ubuntu SMP Thu Aug 19 23:31:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

I replaced "%(__prefix_line)s" with ".*" in postfix-sasl.conf to make the filter catch the loglines below.

Any ideas why "%(__prefix_line)s" prevent match?

postfix-sasl.conf: 

```
# Fail2Ban filter for postfix authentication failures
#

[INCLUDES]

before = common.conf

[Definition]

_daemon = postfix/smtpd

#failregex = ^%(__prefix_line)swarning: [-._\w]+\[<HOST>\]: SASL (?:LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed(: [ A-Za-z0-9+/]*={0,2})?\s*$
failregex = ^.*warning: [-._\w]+\[<HOST>\]: SASL (?:LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed(: [ A-Za-z0-9+/]*={0,2})?\s*$

# Author: Yaroslav Halchenko

```
First few log lines, changed actual host name and IPs:
```
$ grep 'authentication failed' /var/log/mail.log
Sep 12 06:47:48 <host name> postfix/submission/smtpd[21681]: warning: unknown[<IP>]: SASL LOGIN authentication failed: authentication failure
Sep 12 08:27:26 <host name> postfix/submission/smtpd[4619]: warning: unknown[<IP>]: SASL LOGIN authentication failed: authentication failure
Sep 12 08:57:58 <host name> postfix/submission/smtpd[19361]: warning: unknown[<IP>]: SASL LOGIN authentication failed: authentication failure
Sep 12 09:03:20 <host name> postfix/submission/smtpd[22020]: warning: unknown[<IP>]: SASL LOGIN authentication failed: authentication failure
Sep 12 09:33:36 <host name> postfix/submission/smtpd[4152]: warning: unknown[<IP>]: SASL LOGIN authentication failed: authentication failure
...
```

**Comment by sebres** [comment]
> Fail2Ban v0.10.2
> I replaced "%(__prefix_line)s" with ".*" in postfix-sasl.conf to make the filter catch the loglines below.

In 0.10.2 there is common filter `filter.d/postfix.conf` which is supposed to use with different `mode`.
https://github.com/fail2ban/fail2ban/blob/a45488465e0dd547eb8479c0fa9fd577c1837213/config/jail.conf#L632-L634

Where you have this "old" config and why it is still used in your `jail.conf`?
See https://github.com/fail2ban/fail2ban/wiki/Proper-fail2ban-configuration, shortly:
- avoid modifying of stock fail2ban .conf-files, and...
- don't copy .conf-files to .local-files (create empty .local files and change custom settings only).

> Any ideas why "%(__prefix_line)s" prevent match?

This works as expected in stock filter with mode `auth` (used in jail `postfix-sasl`) and `aggressive`:

```
$ msg='Sep 12 06:47:48 host postfix/submission/smtpd[21681]: warning: unknown[192.0.2.1]: SASL LOGIN authentication failed: authentication failure'
$ fail2ban-regex "$msg" postfix[mode=auth]
...
Lines: 1 lines, 0 ignored, 1 matched, 0 missed
````

So use original 0.10th configuration and it'd work.

**Comment by Th-Barth** [comment]
Hello,
sorry for opening this issue again, but I dont get the solution presented here to work. 

This is my match in the console:

```shell
$ msg='Apr 27 19:10:24 mx1 postfix/smtpd[26199]: warning: unknown[ip-address]: SASL LOGIN authentication failed: UGFzc3dvcmQ6, sasl_username=ichat'

$ fail2ban-regex "$msg" postfix[mode=auth]

[...]
Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.00 sec]
``` 

Then I copied the postfix-sasl section into the empty created /etc/fail2ban/jail.local

```shell
[postfix-sasl]
enabled = true
maxretry = 3
bantime  = 1h
filter   = postfix[mode=auth]
port     = smtp,465,submission,imap,imaps,pop3,pop3s
logpath  = %(postfix_log)s
backend = systemd
```

```shell
$ systemctl restart fail2ban

Apr 27 19:56:23 mx1 fail2ban-client[26913]: Shutdown successful
Apr 27 19:56:23 mx1 systemd[1]: fail2ban.service: Deactivated successfully.
Apr 27 19:56:23 mx1 systemd[1]: Stopped fail2ban.service - Fail2Ban Service.
Apr 27 19:56:23 mx1 systemd[1]: fail2ban.service: Consumed 6.563s CPU time.
Apr 27 19:56:23 mx1 systemd[1]: Started fail2ban.service - Fail2Ban Service.
Apr 27 19:56:23 mx1 fail2ban-server[26924]: 2024-04-27 19:56:23,474 fail2ban.configreader   [26924]: WARNING 'allowipv6' not defined in 'Definition'. Using default one: 'auto'
Apr 27 19:56:23 mx1 fail2ban-server[26924]: Server ready
```
In the journal I get to see the "authentication failed"-messages  again and again, but the f2b-client status keeps empty

```shell
$ fail2ban-client status postfix-sasl
Status for the jail: postfix-sasl
|- Filter
|  |- Currently failed:	0
|  |- Total failed:	0
|  - Journal matches:	_SYSTEMD_UNIT=postfix.service
   |- Actions
   |- Currently banned:	0
   |- Total banned:	0
   - Banned IP list:	
```


System is Debian 12

Did I forget something?

**Comment by sebres** [comment]
The question is what you see with:
```
fail2ban-regex systemd-journal postfix[mode=auth]
```
If it doesn't find the lines, it may be affected by 2 issues:
- either it is wrong `journamatch` (`_SYSTEMD_UNIT=postfix.service` is too few, see https://github.com/fail2ban/fail2ban/pull/3692/files for example)
You can output the message with `journalctl` in JSON format and check what `_SYSTEMD_UNIT` it contains.
- or it is wrong monitoring `journalflags` of the backend, see #2444
You can also check it with fail2ban-regex:
```
fail2ban-regex systemd-journal[journalflags=1] postfix[mode=auth]
```

**Comment by Th-Barth** [comment]
Hi, thanks for your help! After a long search in the web, I had found a solution. Because of systemd, I had to adjust the journalmatch option [(fail2ban_postfix_sasl)](https://enricorossi.org/blog/2022/fail2ban_postfix_sasl/) My current jail.local: 

```shell
[DEFAULT]
backend = systemd
bantime = 3h
maxretry = 3
findtime = 6h
 
[sshd]
enabled = true
 
[postfix]
enabled  = true
mode = auth
journalmatch = SYSLOG_IDENTIFIER=postfix/smtpd
``` 

```shell
$ fail2ban-client status postfix

Status for the jail: postfix
|- Filter
|  |- Currently failed:	0
|  |- Total failed:	252
|  `- Journal matches:	_SYSTEMD_UNIT=postfix.service + SYSLOG_IDENTIFIER=postfix/smtpd
`- Actions
   |- Currently banned:	12
   |- Total banned:	96
   `- Banned IP list: [ip-list]
```
