### ISSUE TITLE
fail2ban does nothing to protect apache server

### ISSUE THREAD

**Issue by vicn1222** [fail2ban/fail2ban#3110]
Hi,

I install fail2ban in my CentOS 8 server using "dnf install -y fail2ban". I set up jail.local in /etc/fail2ban as below. I didn't change any fail2ban files, except adding the jail.local file. The server is up-to-date using "dnf update -y".

"fail2ban-client version" gives 0.11.2

It protects the sshd. I try remote login with wrong password, it blocks my ip, which tells the fail2ban is working.

However, it does nothing on the apache server. The apache logpath is correct. Time zone is correct.

I did "ab -n 1000 -c 20 https://www.myserver.com/", it doesn't block my ip.

"fail2ban-client status" gives 10 jails, which is correct too. 

Can anyone please tell what is wrong my jail.local file? Many thanks

<pre>
[DEFAULT]
bantime  = 10m

findtime  = 600
maxretry = 3

banaction = iptables-allports

apache_error_log = /home/www/domains/logs/apache_error_log
apache_access_log = /home/www/domains/logs/apache_access_log

backend = systemd

[sshd]
enabled = true
port    = 1222
maxretry = 1
bantime  = 1h

[apache-badbots]
enabled = true
port    = 80,443
logpath = /home/www/domains/logs/apache_access_log

[apache-noscript]
enabled = true
port    = 80,443
logpath = /home/www/domains/logs/apache_error_log

[apache-overflows]
enabled = true
port    = 80,443
logpath = /home/www/domains/logs/apache_access_log

[apache-botsearch]
enabled = true
port    = 80,443
logpath = /home/www/domains/logs/apache_access_log

[apache-fakegooglebot]
enabled = true
port    = 80,443
logpath = /home/www/domains/logs/apache_access_log

[apache-modsecurity]
enabled = true
port    = 80,443
logpath = /home/www/domains/logs/apache_access_log

[apache-shellshock]
enabled = true
port    = 80,443
logpath = /home/www/domains/logs/apache_access_log

[php-url-fopen]
enabled = true
port    = 80,443
logpath = /home/www/domains/logs/apache_access_log

[block-all-dem-noobs]
enabled = true
port = http,https
filter = block-all-dem-noobs
logpath = /home/www/domains/logs/apache_access_log
maxretry = 10
findtime = 5
bantime = 600
action = iptables[name=HTTP, port=http, protocol=tcp]
</pre>

**Comment by sebres** [comment]
> However, it does nothing on the apache server. 

Fail2ban is just a tool and it protects only against vectors you configured to recognize as failures.

> I did `ab -n 1000 -c 20 https://www.myserver.com/`, it doesn't block my ip.

Why it should? Do you have any constellation where you have connection or request limits?
With other words which filter exactly should do that?

Please provide the log-excerpt from apache log-file related to your attempts.

**Comment by vicn1222** [comment]
Hi sebres,

Thank you for your response.

Below is the attack, how can I config fail2ban to block the ip? Many thanks

[code]
194.61.25.18 - - [27/Sep/2021:16:29:46 -0500] "GET /insider-trading-search?q=1%22%%27%2F%2A%2A%2FAND%2F%2A%2A%2F%28SELECT%2F%2A%2A%2F1767%2F%2A%2A%2FFROM%2F%2A%2A%2F%28SELECT%28SLEEP%285%29%29%29bOBp%29%2F%2A%2A%2FAND%2F%2A%2A%2F%27fpGV%%27%3D%27fpGV HTTP/1.1" 403 199 "https://www.mydomain.com:443/" "Mozilla/5.0 (Windows; U; Windows NT 5.1; rv:1.7.3) Gecko/20041001 Firefox/0.10.1"
194.61.25.18 - - [27/Sep/2021:16:29:46 -0500] "GET /insider-trading-search?q=1%22%27%2F%2A%2A%2FAND%2F%2A%2A%2F%28SELECT%2F%2A%2A%2F1767%2F%2A%2A%2FFROM%2F%2A%2A%2F%28SELECT%28SLEEP%285%29%29%29bOBp%29%2F%2A%2A%2FAND%2F%2A%2A%2F%27ZAdj%27%2F%2A%2A%2FLIKE%2F%2A%2A%2F%27ZAdj HTTP/1.1" 403 199 "https://www.mydomain.com:443/" "Mozilla/5.0 (Windows; U; Windows NT 5.1; rv:1.7.3) Gecko/20041001 Firefox/0.10.1"
194.61.25.18 - - [27/Sep/2021:16:29:47 -0500] "GET /insider-trading-search?q=1%22%22%29%2F%2A%2A%2FAND%2F%2A%2A%2F%28SELECT%2F%2A%2A%2F1767%2F%2A%2A%2FFROM%2F%2A%2A%2F%28SELECT%28SLEEP%285%29%29%29bOBp%29%2F%2A%2A%2FAND%2F%2A%2A%2F%28%22pQTN%22%3D%22pQTN HTTP/1.1" 403 199 "https://www.mydomain.com:443/" "Mozilla/5.0 (Windows; U; Windows NT 5.1; rv:1.7.3) Gecko/20041001 Firefox/0.10.1"
194.61.25.18 - - [27/Sep/2021:16:29:47 -0500] "GET /insider-trading-search?q=1%22%22%29%29%2F%2A%2A%2FAND%2F%2A%2A%2F%28SELECT%2F%2A%2A%2F1767%2F%2A%2A%2FFROM%2F%2A%2A%2F%28SELECT%28SLEEP%285%29%29%29bOBp%29%2F%2A%2A%2FAND%2F%2A%2A%2F%28%28%22HyKg%22%3D%22HyKg HTTP/1.1" 403 199 "https://www.mydomain.com:443/" "Mozilla/5.0 (Windows; U; Windows NT 5.1; rv:1.7.3) Gecko/20041001 Firefox/0.10.1"
194.61.25.18 - - [27/Sep/2021:16:29:48 -0500] "GET /insider-trading-search?q=1%22%22%29%29%29%2F%2A%2A%2FAND%2F%2A%2A%2F%28SELECT%2F%2A%2A%2F1767%2F%2A%2A%2FFROM%2F%2A%2A%2F%28SELECT%28SLEEP%285%29%29%29bOBp%29%2F%2A%2A%2FAND%2F%2A%2A%2F%28%28%28%22cwVi%22%3D%22cwVi HTTP/1.1" 403 199 "https://www.mydomain.com:443/" "Mozilla/5.0 (Windows; U; Windows NT 5.1; rv:1.7.3) Gecko/20041001 Firefox/0.10.1"
194.61.25.18 - - [27/Sep/2021:16:29:48 -0500] "GET /insider-trading-search?q=1%22%22%2F%2A%2A%2FAND%2F%2A%2A%2F%28SELECT%2F%2A%2A%2F1767%2F%2A%2A%2FFROM%2F%2A%2A%2F%28SELECT%28SLEEP%285%29%29%29bOBp%29%2F%2A%2A%2FAND%2F%2A%2A%2F%22aeEl%22%3D%22aeEl HTTP/1.1" 403 199 "https://www.mydomain.com:443/" "Mozilla/5.0 (Windows; U; Windows NT 5.1; rv:1.7.3) Gecko/20041001 Firefox/0.10.1"
194.61.25.18 - - [27/Sep/2021:16:29:49 -0500] "GET /insider-trading-search?q=1%22%22%29%2F%2A%2A%2FAND%2F%2A%2A%2F%28SELECT%2F%2A%2A%2F1767%2F%2A%2A%2FFROM%2F%2A%2A%2F%28SELECT%28SLEEP%285%29%29%29bOBp%29%2F%2A%2A%2FAND%2F%2A%2A%2F%28%22QBrj%22%2F%2A%2A%2FLIKE%2F%2A%2A%2F%22QBrj HTTP/1.1" 403 199 "https://www.mydomain.com:443/" "Mozilla/5.0 (Windows; U; Windows NT 5.1; rv:1.7.3) Gecko/20041001 Firefox/0.10.1"
194.61.25.18 - - [27/Sep/2021:16:29:49 -0500] "GET /insider-trading-search?q=1%22%22%29%29%2F%2A%2A%2FAND%2F%2A%2A%2F%28SELECT%2F%2A%2A%2F1767%2F%2A%2A%2FFROM%2F%2A%2A%2F%28SELECT%28SLEEP%285%29%29%29bOBp%29%2F%2A%2A%2FAND%2F%2A%2A%2F%28%28%22ZXQQ%22%2F%2A%2A%2FLIKE%2F%2A%2A%2F%22ZXQQ HTTP/1.1" 403 199 "https://www.mydomain.com:443/" "Mozilla/5.0 (Windows; U; Windows NT 5.1; rv:1.7.3) Gecko/20041001 Firefox/0.10.1"
194.61.25.18 - - [27/Sep/2021:16:29:50 -0500] "GET /insider-trading-search?q=1%22%22%29%29%29%2F%2A%2A%2FAND%2F%2A%2A%2F%28SELECT%2F%2A%2A%2F1767%2F%2A%2A%2FFROM%2F%2A%2A%2F%28SELECT%28SLEEP%285%29%29%29bOBp%29%2F%2A%2A%2FAND%2F%2A%2A%2F%28%28%28%22elxS%22%2F%2A%2A%2FLIKE%2F%2A%2A%2F%22elxS HTTP/1.1" 403 199 "https://www.mydomain.com:443/" "Mozilla/5.0 (Windows; U; Windows NT 5.1; rv:1.7.3) Gecko/20041001 Firefox/0.10.1"
194.61.25.18 - - [27/Sep/2021:16:29:50 -0500] "GET /insider-trading-search?q=1%22%22%2F%2A%2A%2FAND%2F%2A%2A%2F%28SELECT%2F%2A%2A%2F1767%2F%2A%2A%2FFROM%2F%2A%2A%2F%28SELECT%28SLEEP%285%29%29%29bOBp%29%2F%2A%2A%2FAND%2F%2A%2A%2F%22PGOE%22%2F%2A%2A%2FLIKE%2F%2A%2A%2F%22PGOE HTTP/1.1" 403 199 "https://www.mydomain.com:443/" "Mozilla/5.0 (Windows; U; Windows NT 5.1; rv:1.7.3) Gecko/20041001 Firefox/0.10.1"
194.61.25.18 - - [27/Sep/2021:16:29:51 -0500] "GET /insider-trading-search?q=1%22%2F%2A%2A%2FAND%2F%2A%2A%2F%28SELECT%2F%2A%2A%2F1767%2F%2A%2A%2FFROM%2F%2A%2A%2F%28SELECT%28SLEEP%285%29%29%29bOBp%29--%2F%2A%2A%2Frogx HTTP/1.1" 403 199 "https://www.mydomain.com:443/" "Mozilla/5.0 (Windows; U; Windows NT 5.1; rv:1.7.3) Gecko/20041001 Firefox/0.10.1"
194.61.25.18 - - [27/Sep/2021:16:29:51 -0500] "GET /insider-trading-search?q=1%22%2F%2A%2A%2FAND%2F%2A%2A%2F%28SELECT%2F%2A%2A%2F1767%2F%2A%2A%2FFROM%2F%2A%2A%2F%28SELECT%28SLEEP%285%29%29%29bOBp%29%23%2F%2A%2A%2FAUzR HTTP/1.1" 403 199 "https://www.mydomain.com:443/" "Mozilla/5.0 (Windows; U; Windows NT 5.1; rv:1.7.3) Gecko/20041001 Firefox/0.10.1"

[/code]

**Comment by sebres** [comment]
I guess you need to match the errored requests (like forbidden/403)...

This is a jail which would match them:
```ini
[apache-errors]
filter =
logpath = /path/to/log...
datepattern = ^\S+ \S+ \S+( \[{DATE}\])
# match all 4xx and 5xx excluding 401 and 404:
errcode = (?!40[14])[45]\d\d
failregex = ^<ADDR> \S+ \S+ "[A-Z]+ /[^"]*" %(errcode)s\b
```
If you need additionally the URI-filtering, you have to rewrite `/[^"]*` to something more precise. 
For example `(?!/(?:1st|2nd|3rd))/[^"]*` would match any URL excepting `/1st`, `/2nd` and `/3rd`.
To match 403 only set `errcode = 403`.

Please note that monitoring of access-log directly is not advisable, see https://github.com/fail2ban/fail2ban/wiki/Best-practice for details.
