### ISSUE TITLE
[FR]: lighttpd-auth not matching

### ISSUE THREAD

**Issue by bjmgeek** [fail2ban/fail2ban#3116]
### Environment:

- Fail2Ban version  : 0.11.2-2
- OS, including release name/version : Debian GNU/Linux 11 (bullseye)
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : lighttpd-auth
- Service, project or product name, including release name/version : lighttpd 1.4.59-1
- Repository or URL (if known) : https://github.com/lighttpd/lighttpd1.4
- Service type : web-server
- Ports and protocols the service is listening : 80, 443

#### Log or journal information

- Log file name(s) : /var/log/lighttpd/error.log

- Journal identifier or unit name : lighttpd.service

#### failures in sense of fail2ban filter (fail2ban must match):

```
2021-09-30 16:05:33: mod_auth.c.828) password doesn't match for /secure/ username: test IP: 123.123.123.123
```

#### legitimate messages (fail2ban should not consider as failures):

```
```

**Comment by sebres** [comment]
Hmm... strange that it was changed in this weird way (removed first open parenthesis char and comma before IP).

But corresponding the source code the comma is indeed removed (at least for `password doesn't match` message):
https://github.com/lighttpd/lighttpd1.4/blob/6ffabc960789fa284b16006d97456eb070e07824/src/mod_auth.c#L840-L841
Just open parenthesis seems to be still there:
https://github.com/lighttpd/lighttpd1.4/blob/6ffabc960789fa284b16006d97456eb070e07824/src/log.c#L113
However maybe `log_buffer_vprintf` writes the remaining formatted error message to wrong offset (-1 char), so it overwrites this `(`-char in buffer.

The fix would be something like that:
```diff
- failregex = ^: \((?:http|mod)_auth\.c\.\d+\) (?:password doesn\'t match .* username: .*|digest: auth failed for .*: wrong password|get_password failed), IP: <HOST>\s*$
+ failregex = ^: \(?(?:http|mod)_auth\.c\.\d+\) (?:password doesn\'t match .* username: .*|digest: auth failed for .*: wrong password|get_password failed),? IP: <HOST>\s*$
```
so making both chars optional.

But to adjust to the source code (and to avoid catch-all's) it could be something like that:
```ini
failregex = ^: \(?(?:http|mod)_auth\.c\.\d+\) (?:password doesn\'t match for (?:\S+|.*?) username:\s+<F-USER>(?:\S+|.*?)</F-USER>\s*|digest: auth failed(?: for\s+<F-ALT_USER>(?:\S+|.*?)</F-ALT_USER>\s*)?: (?:wrong password|uri mismatch \([^\)]*\))|get_password failed),? IP: <HOST>\s*$
```

**Comment by bjmgeek** [comment]
It turns out it's a bug in lighttpd: https://redmine.lighttpd.net/issues/3105

However, until the upstream lighttpd gets pushed out, I'll try those regexes.

**Comment by bjmgeek** [comment]
I added the second regex in filter.d/lighttpd-auth.local, and the line matches now
```
[Definition]

failregex = %(known/failregex)s
            ^: \(?(?:http|mod)_auth\.c\.\d+\) (?:password doesn\'t match for (?:\S+|.*?) username:\s+<F-USER>(?:\S+|.*?)</F-USER>\s*|digest: auth failed(?: for\s+<F-ALT_USER>(?:\S+|.*?)</F-ALT_USER>\s*)?: (?:wrong password|uri mismatch \([^\)]*\))|get_password failed),? IP: <HOST>\s*$
```
Thanks for the help!
