### ISSUE TITLE
"cannot import name 'Mapping' from 'collections'" on startup - Python 3.10

### ISSUE THREAD

**Issue by jameslbrown** [fail2ban/fail2ban#3142]
### Environment:

- Fail2Ban version  : 0.11.1
- OS, including release name/version : macOS 10.15.7 Catalina
- [X ] Fail2Ban installed via OS/distribution mechanisms: Homebrew
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

#### Steps to reproduce
Upgrade from Python 3.9.7 to Python 3.10.0_2

#### Observed behavior
% sudo /usr/local/opt/fail2ban/bin/fail2ban-client -x start
2021-10-29 16:23:00,047 fail2ban                [72151]: ERROR   cannot import name 'Mapping' from 'collections' (/usr/local/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)

**Comment by pathros** [comment]
This same error shows up when trying to install fail2ban on Ubuntu 22.04. The version installed of fail2ban is `Fail2Ban v0.11.2`.

Any ideas on how to fix it and make it work?

**Comment by sebres** [comment]
> Any ideas on how to fix it and make it work?

At the moment it'd be installation from source - https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually.
I'll try to make a newest releases as soon as possible.

**Comment by nPHYN1T3** [comment]
Source fails as well. Initially it failed due to 2to3 not being installed. Installing it and running the 2to3 set up yields UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 24: invalid start byte
Fail!

**Comment by ashish-greycube** [comment]
> > Any ideas on how to fix it and make it work?
> 
> At the moment it'd be installation from source - https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually. I'll try to make a newest releases as soon as possible.

I am facing the same issue i.e.
ERROR: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
Ubuntu 22.04. The version installed of fail2ban is Fail2Ban v0.11.1
what version it is fixed?
