### ISSUE TITLE
Better support for Fedora/RedHat paths

### ISSUE THREAD

**Issue by opoplawski** [fail2ban/fail2ban#315]
We have to maintain a number of patches in the Fedora/EPEL fail2ban packages to convert from the Debian log paths to Fedora/RedHat versions.  It would be nice if we could somehow maintain this upstream.  Perhaps we could move to a templated jail.conf with the appropriate paths plugged in at install time.  Thoughts?

**Comment by leeclemens** [comment]
Is this fixed up with the config/paths-*.conf configs?

One change is https://github.com/fail2ban/fail2ban/commit/ef29d7bd2929d6b493337a9f4e22b3613ff07007, but that is a file rename, so original implementation is probably earlier.

**Comment by leeclemens** [comment]
Is this closeable, given the paths-* configs?

**Comment by yarikoptic** [comment]
I think indeed we could close it for now, although it lead to a fruitful (although not finished) brainstorm on autodetection of the systems and choosing specific config automagically.  We might come to it later ;)
