### ISSUE TITLE
[BR]: Fail2ban + UFW fails when banning, "stderr: error: invalid position '1'"

### ISSUE THREAD

**Issue by EldonMcGuinness** [fail2ban/fail2ban#3157]
### Environment:
- Fail2Ban version: fail2ban/focal,now 0.11.1-1 all 
- OS, including release name/version : Ubuntu 20.04.3
- UFW version: ufw/focal,now 0.36-6 all
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

Utilizing UFW to manage the firewall

### The issue:

If you try to utilize fail2ban with an empty rule set/firewall it gives you an error saying it could not ban the IP:
`2021-11-09 03:39:18,410 fail2ban.utils          [2489620]: ERROR   7fcf0ab0d8b0 -- stderr: "ERROR: Invalid position '1'"`

#### Steps to reproduce
* Clearout all rules from ufw
* Trigger a ban
* See the error

#### Expected behavior
One would expect the ban to be added to UFW

#### Observed behavior
Ban is not added to UFW

#### Any additional information
This can be resolved by first adding any old rule, `ufw allow 80`, and then trying again.

#### Relevant parts of /var/log/fail2ban.log file:

```
2021-11-09 03:39:18,410 fail2ban.utils          [2489620]: ERROR   7fcf0ab0d8b0 -- stderr: "ERROR: Invalid position '1'"
```

**Comment by EldonMcGuinness** [comment]
Closing as this can be solved with the same edit of the ``action.d/ufw.conf`` file outlined in #2331, perhaps this title will help others find it and not need another issue created. 😄 

Changing this:
```
ufw insert <insertpos> <blocktype> from <ip> to <destination> $app
```

To this:
```
ufw prepend <blocktype> from <ip> to <destination> $app
```

**Comment by ztjuh** [comment]
What would the `actionunban` look like?

**Comment by sebres** [comment]
`actionunban` is not affected by the issue, because insert position is only needed by ban.

But you can see in newest version of action how it is implemented now:
https://github.com/fail2ban/fail2ban/blob/80805cabfcf57dd0454d47d7f86d43c6738ce629/config/action.d/ufw.conf#L28-L33
