### ISSUE TITLE
[FR]: Gotify

### ISSUE THREAD

**Issue by schklom** [fail2ban/fail2ban#3159]
### Environment:

- Fail2Ban version  : 0.11.2
- OS, including release name/version : Debian 11

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : 
- Service, project or product name, including release name/version : Gotify 2.1.0
- Repository or URL (if known) : https://github.com/gotify/server
- Service type : Notification
- Ports and protocols the service is listening : 443

#### Log or journal information

- Log file name(s) : /var/log/docker/gotify/gotify.log

#### failures in sense of fail2ban filter (fail2ban must match):

```sh
[GIN] 2021/11/15 - 19:41:42 | 401 |  189.725107ms |    my.ip.address | POST     "/client"
Error #01: you need to provide a valid access token or user credentials to access this api
[GIN] 2021/11/15 - 19:41:49 | 401 |     558.904µs |    my.ip.address | POST     "/client"
Error #01: you need to provide a valid access token or user credentials to access this api
[GIN] 2021/11/15 - 19:41:56 | 401 |     534.367µs |    my.ip.address | POST     "/client"
Error #01: you need to provide a valid access token or user credentials to access this api
```

#### legitimate messages (fail2ban should not consider as failures):

```sh
[GIN] 2021/11/15 - 20:52:31 | 200 |   27.132068ms |    my.ip.address | GET      "/image/E_NhkbI-oS-aSHlXoossb1l6H.png"
[GIN] 2021/11/15 - 20:52:32 | 200 |     860.051µs |    my.ip.address | GET      "/client"
[GIN] 2021/11/15 - 20:52:33 | 200 |    1.718029ms |    my.ip.address | GET      "/plugin"
```

#### EDIT
`my.ip.address` should be replaced with `client.ip.address`. It is the ip I want to ban.

**Comment by sebres** [comment]
What does `my.ip.address` means? The IP of host where the server is running? Or IP of the client doing the request?

**Comment by schklom** [comment]
> What does `my.ip.address` means?

My bad, I missed the ambiguous notation. This refers to the client's IP I want to ban.

**Comment by sebres** [comment]
OK, the jail for this could look like this:

```ini
[gotify]
maxlines = 2
datepattern = ^\[GIN\] %%Y/%%m/%%d - %%H:%%M:%%S\s+\|\s+
failregex = ^\s*401\s+\|\s+\S+\s+\|\s+<ADDR>[^\n]+\nError \#\d+: you need to provide a valid access token or user credentials to access this api
```
or even much simpler (in single line matching):
```ini
[gotify]
datepattern = ^\[GIN\] %%Y/%%m/%%d - %%H:%%M:%%S\s+\|\s+
failregex = ^\s*401\s+\|\s+\S+\s+\|\s+<ADDR>
```

But since it looks like a web-server (or websocket server), the first authentication could also produce 401st error in log (due to "handshake" during authentication phase, if the login-data is supplied first after server invitation for authorization).
To ensure it is not the case in order to avoid possible false positives one needs to check how such legitimate requests would deviate from failure requests.

**Comment by schklom** [comment]
@sebres Thank you so much, it's working great, you're amazing 😃

You're right, it is a web-server. More specifically it's a self-hosted notification system. A webhook lets users send notifications.
My usecase is server and computer notifications. I'll look into setting up fail2ban with it soon \^\^

> To ensure it is not the case in order to avoid possible false positives one needs to check how such legitimate requests would deviate from failure requests.

You're right, I'll look it up when I have time. At worst, I'll just post an issue on their repo, ask them, and link here to there.

In the meantime, I think I should close this. Feel free to re-open if you think it's better :)

**Comment by sebres** [comment]
> I'll look it up when I have time. At worst, I'll just post an issue on their repo, ask them, and link here to there.

FWIW, normally the web-servers (e. g. nginx) logging either 401-response with user name if authentication fails and without user name (or with `-` as user) if it was an initial request. Another variant would be to log completely different messages or to avoid logging in the initial case (the connection/session doing first attempt ever and would get 401 response to initiate login-process, not to signal the authentication attempt is refused).
Just both may be error-prone if a client can start legitimate attempt with some login not matching exactly this server (for instance the client has several credentials which it trying one after the other) - in this case nothing can help against possible false positives, excepting probably an increase of `maxretry` or decrease of `findtime` for this jail.
