### ISSUE TITLE
[FR]: shellinabox

### ISSUE THREAD

**Issue by sphh** [fail2ban/fail2ban#3163]
### Environment:

- Fail2Ban version  : 0.11.1
- OS, including release name/version : Debian 10.11

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : –
- Service, project or product name, including release name/version : shellinabox 2.21
- Repository or URL (if known) : https://github.com/shellinabox/shellinabox/
- Service type : web
- Ports and protocols the service is listening : 4200, http(s)

#### Log or journal information

- Log file name(s) : /var/log/auth.log

- Journal identifier or unit name : shellinabox

#### failures in sense of fail2ban filter (fail2ban must match):

For an unknown user:
```
Nov 21 13:19:15 qqq login[28756]: pam_securetty(login:auth): access denied: tty '/dev/pts/2' is not secure !
Nov 21 13:19:25 qqq login[28756]: pam_unix(login:auth): check pass; user unknown
Nov 21 13:19:25 qqq login[28756]: pam_unix(login:auth): authentication failure; logname=SHELLINABOX uid=0 euid=0 tty=/dev/pts/2 ruser= rhost=185.162.235.240
Nov 21 13:19:28 qqq login[28756]: FAILED LOGIN (1) on '/dev/pts/2' from '185.162.235.240' FOR 'UNKNOWN', User not known to the underlying authentication module
Nov 21 13:19:36 qqq login[28756]: pam_securetty(login:auth): access denied: tty '/dev/pts/2' is not secure !
```

For a mistyped password (`<username>` is the actual name used to log in):
```
Nov 21 13:47:42 qqq login[21121]: pam_unix(login:auth): authentication failure; logname=SHELLINABOX uid=0 euid=0 tty=/dev/pts/2 ruser= rhost=62.240.134.11  user=<username>
Nov 21 13:47:45 qqq login[21121]: FAILED LOGIN (1) on '/dev/pts/2' from '62.240.134.11' FOR '<username>', Authentication failure
```

#### legitimate messages (fail2ban should not consider as failures):

Successful log in:
```
Nov 21 13:48:28 qqq login[22221]: pam_unix(login:session): session opened for user <username> by SHELLINABOX(uid=0)
```

**Comment by sebres** [comment]
There is already a jail monitoring pam-authentication failures - [pam-generic](https://github.com/fail2ban/fail2ban/blob/0.10/config/filter.d/pam-generic.conf).

Just enable it in `jail.local` and it will work:
```ini
[pam-generic]
enabled = true
```

To see what exactly it would match use:
```bash
fail2ban-regex -v --print-all-matched /var/log/auth.log pam-generic
```
