### ISSUE TITLE
[FR]: roundcube-auth when behind a proxy

### ISSUE THREAD

**Issue by bnxdev** [fail2ban/fail2ban#3167]
### Environment:

- Fail2Ban version  : 0.11.2
- OS, including release name/version : CentOS Linux release 7.9.2009 (Core)

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : roundcube-auth

### Modification:

I'm running nginx behind haproxy (which adds a `X-Forwarded-For` header) and this is getting added to log files, but the current filters do not know about this and will not match anything.

Here are some sample logs, first from main log file `errors`:
```
[01-Dec-2021 19:07:35 +0000]: <7vrb6kgr> IMAP Error: Login failed for user@domain.com against 127.0.0.1 from 1.2.3.4 (X-Forwarded-For: 1.2.3.4). AUTHENTICATE LOGIN: A0001 NO [AUTHENTICATIONFAILED] Authentication failed. in /usr/share/nginx/html/program/lib/Roundcube/rcube_imap.php on line 211 (POST /?_task=login&_action=login)
```
And when `$config['log_logins'] = true;` is enabled in roundcube, logs from `userlogins.log`:
```
[01-Dec-2021 19:30:48 +0000]: <7vrb6kgr> Failed login for user@domain.com from 1.2.3.4 (X-Forwarded-For: 1.2.3.4) in session 7vrb6kgrindb97hg (error: 1)
```

**The change:**
`(\s?\(X-Forwarded-For: [\d\.]+\))?` has been added right after `HOST` for both failregexes

Full lines:
```
failregex = ^(?:FAILED login|Login failed) for <F-USER>.*</F-USER> from <HOST>(\s?\(X-Forwarded-For: [\d\.]+\))?(?:(?:\([^\)]*\))?\. (?:(?! from ).)*(?: user=(?P=user))? in \S+\.php on line \d+ \(\S+ \S+\))?$
            ^(?:<[\w]+> )?Failed login for <F-USER>.*</F-USER> from <HOST>(\s?\(X-Forwarded-For: [\d\.]+\))? in session \w+( \(error: \d\))?$
```

My regex does not change the capture used by fail2ban, it's just an expansion of the failregex to allow this use case. It assumes web servers and proxies are set up correctly and that the existing `HOST` is still the real user IP and not that of the proxy. (I wouldn't say it's the job of fail2ban to police that though, as it would be user misconfiguration).

**Regex explained:**

```
(
	\s? // my logs had no space here before a recent update, so this will exist in the wild
	\(X-Forwarded-For: [\d\.]+\) // The header, I didn't want to capture this IP so I just used a basic match
)? // optional, obviously!
```

I am not a regex or fail2ban expert by any means, but this was required to get it working on my system. Changes welcome!

Hope it helps. I can supply any additional info if required.

**Comment by sebres** [comment]
I would use this one either:
```regex
...<HOST> (?:\(X-Forwarded-For: [^\)]+\)\s+)?...
```
1. specified after the space it wouldn't necessarily enter a new (optional) branch on mandatory space after the address, so would do that only on open parenthesis
2. uses non-capturing groups `(?:...)` (a bit faster)
3. matching also IPv6, or even everything else up to the round closed parenthesis.

**Comment by sebres** [comment]
The issie with this approach (ignoring forwarded address) is - it would depend how exactly the proxies are configured (or whether the proxying address is interesting) or what exactly one would need to consider as a banning IP, if in some common case the IPs become different.
So I don't think the filter should be extended this way, at least not by default.

**Comment by bnxdev** [comment]
Thank you for the improved filter!

I wanted to at least create a record here that other people can refer to (save someone elses time debugging), but I agree there's a whole issue around proxies and which address to use.

I'll explain my use case and why I'm OK with ignoring it (e.g. correctly configured):
- I use haproxy to dynamically load a SSL cert depending on the domain name used but everything is eventually sent to nginx.
- [nginx is configured with](https://nginx.org/en/docs/http/ngx_http_realip_module.html) `set_real_ip_from` and `real_ip_header` which tell nginx to trust haproxy and take the real IP from the `X-Forwarded-For` header that haproxy adds
- This has the effect of making the proxy "transparent" and the real user IP (not the proxy) shows in nginx logs and used as `$_SERVER['REMOTE_ADDR']` in PHP for example
- Therefore `HOST` and `X-Forwarded-For` will always be identitcal in these logs

And yes there's always the possibility that header can be misconfigured or even manipulated, so it should be up to the user. 

For example: If you don't configure your webserver in a simmilar fashion (and a proxy is used) then `HOST` will be the proxy IP, and `X-Forwarded-For` is the "real" IP which would not work with this modification, and would start banning the proxy.

Services like Cloudflare will also add this header, so I imagine this issue might exist in the wild.

I agree that it should not be by default, perhaps a new `mode`... Something for me to play around with.

Thanks for your time 👍
