### ISSUE TITLE
List of IPs banned since the beginning?

### ISSUE THREAD

**Issue by kalleboy** [fail2ban/fail2ban#3170]
Is there any way to get the total list of IPs that fail2ban banned? I mean, not the current IPs being blocked, but all the IPs.

How can I activate such an option, if possible? Is it possible to log them into an another file?

Thanks!

**Comment by sebres** [comment]
> List of IPs banned since the beginning?

I don't think you can obtain such a list **since the beginning**.
Because it containing only fail2ban-database (which will be purged periodically) or fail2ban.log (which can be rotated).

To get it from log use:
```bash
# all jails:
grep -hoP 'NOTICE\s+ \[[^\]]+\] Ban \K[\w\.:]+' /var/log/fail2ban.* | sort | uniq
# single jail:
grep -hoP "NOTICE\s+ \[$jail\] Ban \K[\w\.:]+" /var/log/fail2ban.* | sort | uniq
```
To get it from database:
```bash
# long term storage (only version >= 0.11):
sqlite3 "file:/var/lib/fail2ban/fail2ban.sqlite3?mode=ro" "select distinct ip from bips"
sqlite3 "file:/var/lib/fail2ban/fail2ban.sqlite3?mode=ro" "select distinct ip from bips where jail = '$jail'"
# for version >= 0.9 (purged more intensively than bips table):
sqlite3 "file:/var/lib/fail2ban/fail2ban.sqlite3?mode=ro" "select distinct ip from bans"
sqlite3 "file:/var/lib/fail2ban/fail2ban.sqlite3?mode=ro" "select distinct ip from bans where jail = '$jail'"
```

> Is it possible to log them into an another file?

You can write own action logging it (via logger, journal, to database, whatever or even simply into the file), e. g. `action.d/log-ban.conf`:
```ini
[Definition]
actionban = echo "<ip>" >> %(logfile)s
[Init]
logfile = /var/log/fail2ban-banned.log
```
and then in `jail.local` for default section or some jail:
```ini
[DEFAULT]
action = %(known/action)s
         log-ban
```

**Comment by kalleboy** [comment]
Thanks a lot for your very detailed answer. Much appreciated.

My last question; even though I have fail2ban activated and working correctly, I see in my log file:
"POST //wp-login.php HTTP/1.1" 200

(Please notice '//') so perhaps that's why fail2ban skips it?

Because I have:

failregex = ^<HOST> .* "POST /wp-login.php HTTP.* 200

in wordpress-ban.conf file of mine. 

Should I add a second line, and would fail2ban work correctly with a file like:

failregex = ^<HOST> .* "POST /wp-login.php HTTP.* 200
failregex = ^<HOST> .* "POST //wp-login.php HTTP.* 200

or is there any regex, some sort of a wildcard like;

failregex = ^<HOST> .* "POST *wp-login.php HTTP.* 200

Looking forward to hearing back from you,
Regards.

**Comment by sebres** [comment]
> Should I add a second line

No. A second regex can be added as second line without `failregex = ` but at least one space (space means a continuation of parameter, and new-line separating the regexs).

But in your case it is enough to add `/?` (which means optional slash), or even add to the slash `+` (means as many slashes as possible).

What I don't understand why you want to block a request answering with 200 (looks like processed request, 200 means OK), so how you want to distinguish them from legitimate attempts (your jail is calling wordpress-ban).
And why only POST requests...
Anyway your regex is bad (have catch-all's `.*` etc), better would be to write it as exact as possible. So if the log-line looks somehow like:
```
192.0.2.1 - - [<timestamp>] "POST //wp-login.php HTTP/1.1" 200 3467 "-" "-"
```
the precise regex could look like:
```regex
^<ADDR> \S+ \S+(?: [])? "[A-Z]+ /+wp-login\.php [^"]*" 200\b
```
Just normally one'd consider only failed requests (responding with 3xx, 4xx or 5xx, but not a 200).

**Comment by kalleboy** [comment]
Hello. 

Thanks for truly great info, many thanks! 

Why I use such a line? Only for WordPress login brute-forcers. So, if someone tries to login to my Blog (I really receive, tons of bots, such scripts) 10 times in 60 seconds, it gets blocked. That's why I have;

failregex = ^<HOST> .* "POST /wp-login.php HTTP.* 200

but obviously, a wrong one, right?

So, if I'd like to correct it (with as many slashes as possible) is the following line ok?

[Definition]
failregex = ^<ADDR> \S+ \S+(?: [])? "[A-Z]+ /+wp-login\.php [^"]*" 200\b

Could you please explain your sentence; "but at least one space (space means a continuation of parameter, and new-line separating the regexs)." further? 

And finally, why not <HOST> but <ADDR>? 

Thanks so much once again,
Regards.

**Comment by kalleboy** [comment]
And as a note, a successful login will not return a 200. It actually returns a 302 redirect so the regex does not match.

**Comment by sebres** [comment]
> is the following line ok?

I didn't know your log format, so I wrote is for an example I provided above. You can test the filter or regex by yourself with fail2ban-regex.

> Could you please explain your sentence...

It is documented, people!
```ini
failregex = regex 1
           regex 2
```
> And finally, why not `<HOST>` but `<ADDR>`?

ADDR is a new tag matching only IP, HOST would also match a hostname, but if unneeded, is slower than former.
