### ISSUE TITLE
WHERE THE HELL IS THE JAIL.LOCAL FILE

### ISSUE THREAD

**Issue by SirEpiclyAmazing** [fail2ban/fail2ban#3183]
OH WAIT, IT DOESNT EXIST LMAOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by sebres** [comment]
Hmm?...

Sure it doesn't exists. As soooooo many other `.local` files for hundreds and thousands of config-files in linux and unix.

Normally one creates a new empty `*.local` file (in same directory of `*.conf` file) and stores there the custom settings one needs to specify (or to overwrite provided by default settings).

One could also change `jail.conf` (and possibly other) stock file, but it is not advisable, see [wiki :: Proper fail2ban configuration](https://github.com/fail2ban/fail2ban/wiki/Proper-fail2ban-configuration).
