### ISSUE TITLE
[BR]: Jail.local does not exist (/etc/fail2ban/jail.local)

### ISSUE THREAD

**Issue by SirEpiclyAmazing** [fail2ban/fail2ban#3184]
### Environment:

- Fail2Ban version  : 
- OS, including release name/version : 
- [YES] Fail2Ban installed via OS/distribution mechanisms
- [YES] You have not applied any additional foreign patches to the codebase
- [NO] Some customizations were done to the configuration (provide details below is so)

### The issue:

 /etc/fail2ban/jail.local does not exist

#### Steps to reproduce
Install fail2ban with systemctl, type `sudo nano  /etc/fail2ban/jail.local`
#### Expected behavior
It exists and has configs
#### Observed behavior
A new file is being created
#### Any customizations done to /etc/fail2ban/ configuration

```
```

#### Relevant parts of /var/log/fail2ban.log file:

```
```

#### Relevant lines from monitored log files:

```
```

**Comment by sebres** [comment]
dup of #3183
