### ISSUE TITLE
[BR]: not blocking SSH bruteforce

### ISSUE THREAD

**Issue by Lieta2** [fail2ban/fail2ban#3194]
### Environment:

- Fail2Ban version  : v0.11.1

- OS, including release name/version : Ubuntu 20.04.3 LTS
- [x ] Fail2Ban installed via OS/distribution mechanisms
- [x ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

not blocking SSH bruteforce

#### Steps to reproduce
fail2ban-regex /var/log/auth.log /etc/fail2ban/filter.d/sshd.conf
#### Expected behavior
Success
#### Observed behavior
Running tests
=============

Use   failregex filter file : sshd, basedir: /etc/fail2ban
Use         maxlines : 1
Use      datepattern : Default Detectors
Use         log file : /var/log/auth.log
Use         encoding : UTF-8

Results
=======

Failregex: 12644 total
|-  #) [# of hits] regular expression
|   4) [3765] ^Failed \b(?!publickey)\S+ for (?P<cond_inv>invalid user )?<F-USER>(?P<cond_user>\S+)|(?(cond_inv)(?:(?! from ).)*?|[^:]+)</F-USER> from <HOST>(?: (?:port \d+|on \S+)){0,2}(?: ssh\d*)?(?(cond_user): |(?:(?:(?! from ).)*)$)
|   6) [2] ^[iI](?:llegal|nvalid) user <F-USER>.*?</F-USER> from <HOST>(?: (?:port \d+|on \S+|\[preauth\])){0,3}\s*$
|  14) [3765] ^<F-NOFAIL>pam_[a-z]+\(sshd:auth\):\s+authentication failure;</F-NOFAIL>(?:\s+(?:(?:logname|e?uid|tty)=\S*)){0,4}\s+ruser=<F-ALT_USER>\S*</F-ALT_USER>\s+rhost=<HOST>(?:\s+user=<F-USER>\S*</F-USER>)?(?: (?:port \d+|on \S+|\[preauth\])){0,3}\s*$
|  19) [3] ^<F-NOFAIL>Received <F-MLFFORGET>disconnect</F-MLFFORGET></F-NOFAIL> from <HOST>(?: (?:port \d+|on \S+)){0,2}:\s*11:
|  20) [5100] ^<F-NOFAIL><F-MLFFORGET>(Connection closed|Disconnected)</F-MLFFORGET></F-NOFAIL> (?:by|from)(?: (?:invalid|authenticating) user <F-USER>\S+|.+?</F-USER>)? <HOST>(?:(?: (?:port \d+|on \S+|\[preauth\])){0,3}\s*|\s*)$
|  21) [9] ^<F-MLFFORGET><F-MLFGAINED>Accepted \w+</F-MLFGAINED></F-MLFFORGET> for <F-USER>\S+</F-USER> from <HOST>(?:\s|$)
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [77445] {^LN-BEG}(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
`-

Lines: 77445 lines, 8877 ignored, 3767 matched, 64801 missed
[processed in 3.50 sec]

Ignored line(s): too many to print.  Use --print-all-ignored to print all 8877 lines
Missed line(s): too many to print.  Use --print-all-missed to print all 64801 lines
#### Any customizations done to /etc/fail2ban/ configuration

```
```

#### Relevant parts of /var/log/fail2ban.log file:

```
```

#### Relevant lines from monitored log files:

```
```

**Comment by sebres** [comment]
> Lines: 77445 lines, 8877 ignored, 3767 matched, 64801 missed

There are 3767 matches found if you test it with fail2ban-regex. So basically sshd-filter working as expected. 
I don't understand your issue. Please explain.

> Expected behavior: Success

`fail2ban-regex` only tests the filter (or regex) against log-excerpt or message, it does not ban the IPs found in log.
If you need it - try to use `?sudo? fail2ban-client set "$jail" banip $ip1 ... $ipN`, where you could capture the IP list from result of fail2ban-regex, e.g. grep them from verbose output `fail2ban-regex -v` (or use `fail2ban-regex -o 'ip' ...` for newer versions to get IPs, no idea whether 0.11.1 already supporting option `-o` or `--output`).

Fail2ban server will ban all that IP if it is running, jail sshd is enabled, etc - see [FAQ in wiki :: How fail2ban works](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works).

For instance, add to your `/etc/fail2ban/jail.local` (create empty file if not exists yet) all expected parameters, e. g.:
```ini
[sshd]
# mode = aggressive
enabled = true
```
and reload fail2ban:
```bash
?sudo? fail2ban-client reload
```
or restart it (expected if something action related or the backend changes):
```bash
# ?sudo? fail2ban-client restart
systemctl restart fail2ban
```

**Comment by Lieta2** [comment]
Why it's not blocking?
fail2ban-client status sshd
Status for the jail: sshd
|- Filter
|  |- Currently failed:	0
|  |- Total failed:	3
|  `- File list:	/var/log/auth.log
`- Actions
   |- Currently banned:	0
   |- Total banned:	0
   `- Banned IP list:	

cat /etc/fail2ban/jail.local 
[sshd]
enabled = true
port = 443
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = -1
ignoreip = 85.255.64.158

**Comment by Lieta2** [comment]
Will it help if I add:
action   = iptables[name=SSH, port=443, protocol=tcp]
to /etc/fail2ban/jail.local ?

**Comment by sebres** [comment]
> Why it's not blocking?

Related to your status and log it has found 3 failures only, 2 for `167.71...` and 1 for `170.106....`, to be banned it needs 3 (`maxretry`) failures during `10m` (600 seconds `findtime`) from single IP to ban it.

Note that by restart fail2ban continues to ban from last known position (since last stop), in your case it was `2207822`, so it would not rescan already processed (previously) messages.
To force fail2ban to do that, you need to reset it in fail2ban-sqlite database (or even remove it completely - `/var/lib/fail2ban/fail2ban.sqlite3`). 
But why? Just wait unless they coming back and they will be banned.

> Will it help if I add: `action = ...`

No. You still don't have any ban, so it has nothing with the action.
