### ISSUE TITLE
[BR]: ModuleNotFoundError: No module named 'fail2ban'

### ISSUE THREAD

**Issue by billouetaudrey** [fail2ban/fail2ban#3202]
Hello, today I try fail2ban-client or fail2ban-server but not working
I think it's python version related

Hope you can help me

Thanks

### Environment:
Raspberry + Dietpi Bulleyes

#### Any additional information
Python 3.9.9

root@raspberrypi:~# fail2ban-server status
Traceback (most recent call last):
  File "/usr/bin/fail2ban-server", line 34, in <module>
    from fail2ban.client.fail2banserver import exec_command_line, sys
ModuleNotFoundError: No module named 'fail2ban'

**Comment by sebres** [comment]
> I think it's python version related

Yes. And it depends how you install fail2ban and python. Fail2ban setup process also installing itself as module for python version used by build or install process.
Basically if you upgrade python, you have either to upgrade (reinstall) fail2ban, or to fix shebangs of starter scripts (`fail2ban-client`, `fail2ban-server` and `fail2ban-regex`).
Normally upstream fail2ban setup provides also a link to python version used for build, so you can check it with `fail2ban-python --version` (just it depends how it was upgraded).

Anyway, my assumption that fail2ban was either installed for other python version (inclusive 2.7, so for example `python` started 2.x previously and now it starts 3.x), or it (or python) is upgraded with some issue. Another variant is a path conflict, so you may have several starters and wrong is winning now, so try to find which one is correct, e. g. with `whereis fail2ban-client`.

Also note this https://github.com/fail2ban/fail2ban/issues/3193#issuecomment-1001619134 as well as some other duplicates (one could find in "Issues" list).

**Comment by billouetaudrey** [comment]
Thanks :)

Do you want I continue in other comment ?

BTW I try to reinstall fail2ban with dietpi-software and apt install ( with remove and purge before )

**Comment by sebres** [comment]
No, both issues are closed, basically because they are really 3rd party (we cannot do something to "fix" or avoid it in the future)... 
But you can surely continue here.

> `fail2ban-python -c 'from fail2ban.version import version; print(version)'`

So I guess `fail2ban-python --version` would also say 3.9.9?
Then I assume you upgraded python and (for some reason) there was no dependency to fail2ban, or the upgrade process didn't obtain the fail2ban module (from 3.x.y to 3.9.9).

1. How you installed fail2ban? Which version (stock or manually from source)?
2. When it was installed? Bulleyes or previous releases?
3. How it gets upgraded?

Anyway to repair this you need to reinstall fail2ban (don't forget to make a backup for `/etc/fail2ban` before you do this).

**Comment by billouetaudrey** [comment]
1 - fail2ban-python --version give 3.9.9
2 - With apt-get ( I think from here : http://raspbian.raspberrypi.org/raspbian/ bullseye )
3 - Before bulleyes but pretty sure it's since I update python ( manually from source )

I already try to fully reinstall fail2ban :'(

**Comment by billouetaudrey** [comment]
Lemme try to do this :

apt autoremove fail2ban
apt purge fail2ban
and
git clone https://github.com/fail2ban/fail2ban.git
cd fail2ban
sudo python setup.py install

**Comment by sebres** [comment]
> but pretty sure it's since I update python ( manually from source )

Well, if you do that you can forget the dependencies of apt. An you need surely reinstall fail2ban (probably also from source).

> Lemme try to do this

Won't work (at least you forgot 2to3).
See https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually

**Comment by billouetaudrey** [comment]
Ok thanks, lemme try, tonight or tomorrow;, thanks so much

**Comment by sebres** [comment]
Or may be it would work however... if `python` (you used by install) is 2.7

**Comment by billouetaudrey** [comment]
fixed :)

root@raspberrypi:~/fail2ban# fail2ban-client status sshd
Status for the jail: sshd
|- Filter
|  |- Currently failed: 0
|  |- Total failed:     0
|  `- File list:        /var/log/auth.log
`- Actions
   |- Currently banned: 0
   |- Total banned:     0
   `- Banned IP list:
root@raspberrypi:~/fail2ban# fail2ban-client status apache-
apache-auth           apache-badbots        apache-fakegooglebot  apache-noscript       apache-overflows
root@raspberrypi:~/fail2ban# fail2ban-client status apache-auth
Status for the jail: apache-auth
|- Filter
|  |- Currently failed: 0
|  |- Total failed:     0
|  `- File list:        /var/log/apache2/error.log
`- Actions
   |- Currently banned: 0
   |- Total banned:     0
   `- Banned IP list:

git clone https://github.com/fail2ban/fail2ban.git
cd fail2ban
sudo python2.7 setup.py install
sudo cp ./build/fail2ban.service /etc/systemd/system/fail2ban.service
systemctl daemon-reload
systemctl restart fail2ban


Now let see tomorrow if some ip are ban lol

**Comment by billouetaudrey** [comment]
Seem to not ban any ip;, will see tomorrow ;) thanks again !
