### ISSUE TITLE
[BR]: Attempting to build on Ubuntu - Syntax Errors in files

### ISSUE THREAD

**Issue by kevdogg** [fail2ban/fail2ban#3206]
Thanks to the contributors to the project.

I'm having issues building fail2ban from source using the main branch.  I'm on Ubuntu 20.04 using 3.8.10. 

I'm using a virtualenv to build with following pip packages:
```
Package       Version
------------- -------
dnspython     2.2.0
pip           20.0.2
pkg-resources 0.0.0
pyinotify     0.9.6
setuptools    44.0.0
```

Attempting to build the packages I'm getting the following errors:
```
  File "/home/kevdog/python/fail2ban/venv/lib/python3.8/site-packages/fail2ban/tests/filtertestcase.py", line 1766
    % m for m in 53, 54, 57, 58])
                   ^
SyntaxError: invalid syntax

  File "/home/kevdog/python/fail2ban/venv/lib/python3.8/site-packages/fail2ban/tests/misctestcase.py", line 265
    print deep_function(3)
          ^
SyntaxError: invalid syntax

  File "/home/kevdog/python/fail2ban/venv/lib/python3.8/site-packages/fail2ban/server/ipdns.py", line 333
    mask = ~(0xFFFFFFFFL >> cidr)
                       ^
SyntaxError: invalid syntax
```
I've also tried building as root however have the same errors.  I'm slightly new to build python packages from source however I was wondering if someone could point me in the correct direction.
Thanks.

**Comment by sebres** [comment]
Forgotten [2to3](https://github.com/fail2ban/fail2ban/runs/4855321233?check_suite_focus=true#step:7:4)?
Source code of fail2ban is 2.x based.
Anyway the build process is similar to install, so also note - https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually#manual-installation-from-source
