### ISSUE TITLE
[BR]:  Named refused filter regex misses client id 

### ISSUE THREAD

**Issue by warrenc5** [fail2ban/fail2ban#3207]
I have had to update the filter for **filter.d/named-refused.conf**

```
- prefregex = ^%(__line_prefix)s( error:)?\s*client <HOST>#\S+( \([\S.]+\))?: <F-CONTENT>.+</F-CONTENT>$
+ prefregex = ^%(__line_prefix)s( error:)?\s*client (@0x[0-9a-f]*)? <HOST>#\S+( \([\S.]+\))?: <F-CONTENT>.+</F-CONTENT>$

```

`
ii  bind9          1:9.11.5.P4+dfsg-5.1+deb10u6 amd64        Internet Domain Name Server
ii  fail2ban       0.10.2-2.1   all          ban hosts that cause multiple authentication errors
`

And it emits logs (to syslog) like this - see the @0x was tripping the filter

`26-Jan-2022 00:11:55.642 client @0x7fe20c0c79b0 8.38.116.159#59449 (census.gov): query (cache) 'census.gov/ANY/IN' denied
`

**Comment by sebres** [comment]
Current version of filter already matching this message:
https://github.com/fail2ban/fail2ban/blob/bf689c27b833d4cafc6ce34ada214cd4df2d7d86/config/filter.d/named-refused.conf#L37
(initially fixed in #2406)
