### ISSUE TITLE
redundant logpath variables and default sendmail-whois-lines

### ISSUE THREAD

**Issue by Zurd** [fail2ban/fail2ban#321]
By default, the jail.conf file use the action sendmail-whois, however sendmail-whois-lines is much more useful, having this one by default would be better for everyone.

You do need the logpath variable in the action parameters and the logpath (again) in the jail configuration like that :
sendmail-whois-lines[name=dovecot, dest=your@email.com
  mailto:your@email.com, sender=fail2ban@email.com
  mailto:fail2ban@email.com, logpath=/var/log/dovecot.log]
logpath  = /var/log/dovecot.log

It is redundant that way though, having just only one logpath would be better.

**Comment by sebres** [comment]
> By default, the jail.conf file use the action sendmail-whois, however sendmail-whois-lines

By default, fail2ban uses the action specified in `banaction`. And it is e. g. `iptables-multiport` (or `iptables-allports` for some jails) by default (corresponding your distribution configuration). 
Another actions can be configured (per jail or in default section) using `action = ...` (and it is up to you alone).
 
Or possibly, you misunderstand how fail2ban configuration works. We using cross-config variable substitution like `some_action[logpath="%(logpath)s"]`, so it can get it during interpolation of action parameters.

All what you need you can see in following example:
```INI
#jail.local:
[DEFAULT]
mta = sendmail
my_mail_action = %(mta)s-whois-lines[name=%(__name__)s, sender="%(sender)s", dest="%(destemail)s", logpath="%(logpath)s", chain="%(chain)s"]

# using default pre-defined mail-action:
[my-jail-1]
logpath = /var/log/my-service-1.log
action = %(action_mwl)s
enabled = true

# using my own mail-action:
[my-jail-2]
logpath = /var/log/my-service-2.log
action = %(banaction)s
         %(my_mail_action)s
enabled = true
```

In both cases fail2ban will interpolate (recursive) the `logpath` variable of `jail.local` within `logpath=%(logpath)s` of action, so this action will get it via init-parameters...

For more info - [wiki: How fail2ban substitution resp. runtime interpolation works](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-substitution-resp.-runtime-interpolation-works).
