### ISSUE TITLE
[FR]: Cannot match regex but I can't find the error

### ISSUE THREAD

**Issue by skibbipl** [fail2ban/fail2ban#3213]
### Environment:

- Fail2Ban version  : 0.11.2 (official debian package)
- OS, including release name/version : debian bookworm (testing)

I'm trying to create custom filters for matching invalid logins to gitea but I cannot match any entries.

### filter
```
[Definition]
failregex =  .*(Failed authentication attempt|invalid credentials|Attempted access of unknown user).* from <HOST>
journalmatch = _SYSTEMD_UNIT='gitea.service'
ignoreregex =
```

### jail
```
[gitea]
enabled = true
backend = systemd
filter = gitea
```

### logs
```
Feb 06 16:29:26 xxx gitea[2761403]: 2022/02/06 16:29:26 Started POST /user/login for 111.222.333.444:0
Feb 06 16:29:26 xxx gitea[2761403]: 2022/02/06 16:29:26 ...ers/web/auth/auth.go:200:SignInPost() [I] Failed authentication attempt for dksis from 111.222.333.444:0: user does not exist [uid: 0, name: dksis, keyid: 0]
Feb 06 16:29:26 xxx gitea[2761403]: 2022/02/06 16:29:26 Completed POST /user/login 200 OK in 8.047359ms
```

### regexp test
```
fail2ban-regex systemd-journal /etc/fail2ban/filter.d/gitea.conf

Running tests
=============

Use   failregex filter file : gitea, basedir: /etc/fail2ban
Use         systemd journal
Use         encoding : UTF-8
Use    journal match : _SYSTEMD_UNIT=gitea.service


Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Lines: 2810 lines, 0 ignored, 0 matched, 2810 missed
[processed in 0.20 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all 2810 lines
```

**Comment by sebres** [comment]
Although the regex is a bit "vulnerable" doe to unanchored matter and the catch-alls, it should work with your log format.
Testing it against your log-excerpt shows `3 lines, 0 ignored, 1 matched, 2 missed`.
Therefore my assumption is that the filtering by `_SYSTEMD_UNIT=gitea.service` may be the reason that you don't find any match testing against systemd journal.
Try to check it with: 
```
journalctl -n 10000 _SYSTEMD_UNIT=gitea.service | grep 'Failed authentication attempt'
```
and then check with this which `_SYSTEMD_UNIT` was set for that entries:
```
journalctl -o json -n 10 -g '.*Failed authentication attempt.*'
```
and whether you'd be able to find some other field (like SYSLOG_IDENTIFIER etc) instead of _SYSTEMD_UNIT.

Back to regex, better use something more precise (and anchored at least at the start of message) like that:
```ini
failregex = ^\s*\S+ gitea\[\d+\]: (?:[\d/]+ [\d:]+ )?\S+ \[\w+\] (?:Failed authentication attempt|...) for <F-USER>\S+</F-USER> from <ADDR>
```
But as already said it is not the reason at the moment.

**Comment by skibbipl** [comment]
Hi, thanks for the update. I tried:
```
journalctl -n 10000 _SYSTEMD_UNIT=gitea.service | grep 'Failed authentication attempt'
```
and it returns entries. I tried to filter with `SYSLOG_IDENTIFIER=gitea` yet still fail2ban doesn't detect entries in the log...

**Comment by sebres** [comment]
What do you see here?
```
fail2ban-regex --print-all-missed systemd-journal gitea | grep 'Failed authentication attempt'
```

**Comment by skibbipl** [comment]
Hi,
I can see multiple entries like this:
```
|  2022-02-06T16:29:49.088120xxx gitea[2761403]: 2022/02/06 16:29:49 ...ers/web/auth/auth.go:200:SignInPost() [I] Failed authentication attempt for dksis from xxx.yyy.zzz.aaa:0: user does not exist [uid: 0, name: dksis, keyid: 0]
```

**Comment by sebres** [comment]
So and? I see pretty well a match here (I guess there must be a space between timestamp and `xxx`, anyway the output is simulated):
```
$ fail2ban-regex -v \
  '2022-02-06T16:29:49.088120 xxx gitea[2761403]: 2022/02/06 16:29:49 ...ers/web/auth/auth.go:200:SignInPost() [I] Failed authentication attempt for dksis from 192.0.2.1:0: user does not exist ...' \
  '^\s*\S+ gitea\[\d+\]: (?:[\d/]+ [\d:]+ )?\S+ \[\w+\] (?:Failed authentication attempt|...) for <F-USER>\S+</F-USER> from <ADDR>'

Running tests
=============

Use   failregex line : ^\s*\S+ gitea\[\d+\]: (?:[\d/]+ [\d:]+ )?\S+ \[\w+...
Use      single line : 2022-02-06T16:29:49.088120 xxx gitea[2761403]: 202...


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] ^\s*\S+ gitea\[\d+\]: (?:[\d/]+ [\d:]+ )?\S+ \[\w+\] (?:Failed authentication attempt|...) for <F-USER>\S+</F-USER> from <ADDR>
|      192.0.2.1  Sun Feb 06 16:29:49 2022
`-

...
Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.00 sec]
```
no matter which RE I'd test here your or mine.

So something is wrong yet, either with your filter or with your kind of blacken (e. g. how you modifying the message).

What would you see with this:
```
fail2ban-regex systemd-journal '^\s*\S+ gitea\[\d+\]: (?:[\d/]+ [\d:]+ )?\S+ \[\w+\] (?:Failed authentication attempt|...) for <F-USER>\S+</F-USER> from <ADDR>'
```
If there are matches, then try this:
```
printf '[Definition]\nfailregex = ^\s*\S+ gitea\[\d+\]: (?:[\d/]+ [\d:]+ )?\S+ \[\w+\] (?:Failed authentication attempt|...) for <F-USER>\S+</F-USER> from <ADDR>\njournalmatch = _SYSTEMD_UNIT=gitea.service' > /tmp/gitea.conf
fail2ban-regex systemd-journal /tmp/gitea.conf
```
If it's matching too, check what do you still have in your filter (e. g. compared to /tmp/gitea.conf).

**Comment by skibbipl** [comment]
Hi, I really appreciate your time and sorry for bothering you. Definitely something is wrong. The
```
fail2ban-regex systemd-journal '^\s*\S+ gitea\[\d+\]: (?:[\d/]+ [\d:]+ )?\S+ \[\w+\] (?:Failed authentication attempt|...) for <F-USER>\S+</F-USER> from <ADDR>'
```
returns no matches.
And my example logs are modified only by masking IP and hostname. And there is no space between date and hostname according to fail2ban-regex. This is suspicious to me - in journalctl -u gitea I can see the logs like this:
```
Feb 06 16:29:49 hostname gitea[2761403]: 2022/02/06 16:29:49 ...ers/web/auth/auth.go:200:SignInPost() [I] Failed authentication attempt for dksis from 111.222.333.444:0: user does not exist [uid: 0, name: dksis, keyid: 0]
```
But in `fail2ban-regex` the logs are different:
```
|  2022-02-06T16:29:49.088120hostname gitea[2761403]: 2022/02/06 16:29:49 ...ers/web/auth/auth.go:200:SignInPost() [I] Failed authentication attempt for dksis from 111.222.333.444:0: user does not exist [uid: 0, name: dksis, keyid: 0]
```
Maybe there is some kind of issue with encoding/locale?

**Comment by sebres** [comment]
But this one is working?
```
fail2ban-regex -v \
  '2022-02-06T16:29:49.088120 xxx gitea[2761403]: 2022/02/06 16:29:49 ...ers/web/auth/auth.go:200:SignInPost() [I] Failed authentication attempt for dksis from 192.0.2.1:0: user does not exist ...' \
  '^\s*\S+ gitea\[\d+\]: (?:[\d/]+ [\d:]+ )?\S+ \[\w+\] (?:Failed authentication attempt|...) for <F-USER>\S+</F-USER> from <ADDR>'
```
Because if yes, I don't follow why it should not work against systemd-journal, no matter how output does look there (with or without space between timestamp and hostname, let alone the regex is built that it could match both, due to `^\s*` and by systemd backend it doesn't match timestamp at all, because it is already in fields).

> in `journalctl -u gitea` I can see the logs like this

Can you export that to some temp-file and check fail2ban-regex against this temp-file (instead of systemd-journal) with filter or regex?

> Maybe there is some kind of issue with encoding/locale?

I don't see any special character, only pure ascii, do you?

Just to ensure it is not some error of 0.11.2 (however I don't remember any), can you try to clone newest version and test from it (you don't need to install it for test purposes, but you'd need to install `2to3`):
```
mkdir /tmp/test-f2b; cd /tmp/test-f2b
git clone --depth 1 -b 0.11 https://github.com/fail2ban/fail2ban .
./fail2ban-2to3
PYTHONPATH=. python3 bin/fail2ban-regex ...
```
I'm curious whether it would find something.

**Comment by sebres** [comment]
Hmm... then it looks like systemd-module has been changed in debian bookworm (or something is with python binding there).

Can you provide an excerpt of heavydebug output:
```
printf '[Definition]\nfailregex = ^\s*\S+ gitea\[\d+\]: (?:[\d/]+ [\d:]+ )?\S+ \[\w+\] (?:Failed authentication attempt|...) for <F-USER>\S+</F-USER> from <ADDR>\njournalmatch = _SYSTEMD_UNIT=gitea.service' > /tmp/gitea.conf
PYTHONPATH=. python3 bin/fail2ban-regex -l 5 systemd-journal /tmp/gitea.conf
```
it will be too wordy, but what I need are few blocks with every 5 lines between `Read systemd journal entry`:
```
2022-02-07 18:13:58,827 fail2ban.filtersystemd  [1482]: HEAVY  H: [~jailless~] Read systemd journal entry: ... Failed authentication attempt ...
2022-02-07 18:13:58,827 fail2ban.filter         [1482]: TRACE  T: Working on line ...
2022-02-07 18:13:58,827 fail2ban.filter         [1482]: HEAVY  H: Looking for match ...
2022-02-07 18:13:58,827 fail2ban.filter         [1482]: HEAVY  H:   Looking for failregex 0 - '^\\s*\\S+ gitea\\[\\d+\\]: (?:[\\d/]+ [\\d:]+ )?\\S+ \\[\\w+\\] (?:Failed authentication attempt|...) for (?P<user>\\S+) from \\[?(?:(?:::f{4,6}:)?(?P<ip4>(?:\\d{1,3}\\.){3}\\d{1,3})|(?P<ip6>(?:[0-9a-fA-F]{1,4}::?|::){1,7}(?:[0-9a-fA-F]{1,4}|(?<=:):)))\\]?'
2022-02-07 18:13:58,827 fail2ban.filtersystemd  [1482]: HEAVY  H: [~jailless~] Read systemd journal entry: ...
```
and better if you'd not blacken something there (I'm unsure that some special chars wouldn't be removed during changing).

**Comment by skibbipl** [comment]
I just replaced hostname and IP - no special characters were masked.
```
2022-02-07 18:28:09,650 fail2ban.filtersystemd  [3686303]: HEAVY  H: [~jailless~] Read systemd journal entry: 2022-02-06T16:29:49.088120 hostname gitea[2761403]: 2022/02/06 16:29:49 ...ers/web/auth/auth.go:200:SignInPost() [I] Failed authentication attempt for dksis from 111.222.333.444:0: user does not exist [uid: 0, name: dksis, keyid: 0]
2022-02-07 18:28:09,650 fail2ban.filter         [3686303]: TRACE  T: Working on line ('', '2022-02-06T16:29:49.088120', 'hostname gitea[2761403]: \x1b[36m2022/02/06 16:29:49 \x1b[0m\x1b[32m...ers/web/auth/auth.go:200:\x1b[32mSignInPost()\x1b[0m \x1b[1;32m[I]\x1b[0m Failed authentication attempt for \x1b[1mdksis\x1b[0m from \x1b[1m111.222.333.444:0\x1b[0m: \x1b[1muser does not exist [uid: 0, name: dksis, keyid: 0]\x1b[0m')
2022-02-07 18:28:09,650 fail2ban.filter         [3686303]: HEAVY  H: Looking for match of [('', '2022-02-06T16:29:49.088120', 'hostname gitea[2761403]: \x1b[36m2022/02/06 16:29:49 \x1b[0m\x1b[32m...ers/web/auth/auth.go:200:\x1b[32mSignInPost()\x1b[0m \x1b[1;32m[I]\x1b[0m Failed authentication attempt for \x1b[1mdksis\x1b[0m from \x1b[1m111.222.333.444:0\x1b[0m: \x1b[1muser does not exist [uid: 0, name: dksis, keyid: 0]\x1b[0m')]
2022-02-07 18:28:09,650 fail2ban.filter         [3686303]: HEAVY  H:   Looking for failregex 0 - '^\\s*\\S+ gitea\\[\\d+\\]: (?:[\\d/]+ [\\d:]+ )?\\S+ \\[\\w+\\] (?:Failed authentication attempt|...) for (?P<user>\\S+) from \\[?(?:(?:::f{4,6}:)?(?P<ip4>(?:\\d{1,3}\\.){3}\\d{1,3})|(?P<ip6>(?:[0-9a-fA-F]{1,4}::?|::){1,7}(?:[0-9a-fA-F]{1,4}|(?<=:):)))\\]?'
```

**Comment by sebres** [comment]
Take a closer look at this:
```
hostname gitea[2761403]: \x1b[36m2022/02/06 16:29:49 \x1b[0m\x1b[32m...
```
what illustrates that in your systemd journal are special chars (that may be invisible in the console if not allowed/supported) - `\x1b[36m` is an escape sequence making the text blue.
I don't think it is systemd module (especially if another jails/filters are working as expected), rather I assume that this is this gitea (or whatever is logging there)... So you have 2 possibilities to "fix" that:
- either you'd configure its logger so it does not colorize the message (disable something like `log.ColorFormatted`, see https://docs.gitea.io/en-us/logging-configuration/#colorformat--colorformatted for details)
- or you add this as RE for every escape sequence to failregex, e. g. `\x1b[36m` etc could be matched by `(?:\x1b[\d+m)?`, so you have to extend failregex at several places where ESC-sequences can be found.

**Comment by skibbipl** [comment]
And this is just so obvious - you're absolutely right, gitea log is colored! I'm sorry for taking your time.

**Comment by skibbipl** [comment]
Finally I used following regexp:
```
failregex = ^\s*\S+ gitea\[\d+\]: (?:\x1b\[\d+m)?(?:[\d/]+ [\d:]+ )\S+ \S+ (?:Failed authentication attempt|invalid credentials|Attempted access of unknown user) for (?:\x1b\[\d+m)?<F-USER>\S+</F-USER>(?:\x1b\[\d+m)? from (?:\x1b\[\d+m)?<ADDR>:\d+
```
