### ISSUE TITLE
The configuration information reflected in the log file is different from the configuration file.（and another other problem）

### ISSUE THREAD

**Issue by Xingeqwd** [fail2ban/fail2ban#3215]
**Environment**
Fail2Ban version : 0.11.2
OS, including release name/version : redhat centos  7
The various runtime libraries required by the program should be complete.
**Foreword**
As I said in the title, this is such an miraculous phenomenon, the config in the log file different with config file
**Problem situation** 
changing and saving the config file in "/etc/fail2ban/jail.d/ssh.local"(the changed file is like)
![image](https://user-images.githubusercontent.com/46107662/153257782-afd6685e-c454-4c88-97bb-810612862544.png)
process the command "fail2ban-client reload"
![image](https://user-images.githubusercontent.com/46107662/153253722-db8e522a-cd8c-4347-9a6e-9a6d98e58055.png)
process the command "vim -R /var/log/fail2ban.log"(The configuration information reflected in the log file is like)
![image](https://user-images.githubusercontent.com/46107662/153254457-d786cbd1-5ff7-47e7-a740-c1394a346ab6.png)
**Problem situation** (Replenish)
As we can see, the configuration information reflected in the log file is different from the configuration file.(such as: in config,  maxRetry=3,but in the loging file, maxRetry=5)
I've checked various forums and tried to solve the problem myself, but I can't think of/find a valid solution, this is such an miraculous phenomenon!
**Another issue** 
In addition, I am using "iptables", so I added a line of "action" configuration to the ssh-iptables configuration file, but "iptables -L" shows that there is no such IP address when writing "Ban x.x.x.x" in the log file.
By hte way, The result reported by the command like "systemctl status fail2ban", "fail2ban-client status"  is all OK
**Afterword**
Because my first language is not English, this article might contain some grammatical errors, please bear with me.
Also, please ignore the occlusion somewhere in the config file, I've overridden it for neatness and privacy reasons
The mentioned above is my issue,  If you need any additional information for this issue, please feel free to say.
A huge thanks for everyone who watching this issue post or trying to help me.

**Comment by sebres** [comment]
1. you seem to confuse how the config files are looking.

> "/etc/fail2ban/jail.d/ssh.local"

If you have multiple config files for jails, every *single* jail should be placed into `/etc/fail2ban/jail.d/some-jail.conf` file.
But then fail2ban would only take a look for this single jail `some-jail`, so the section must be called `[some-jail]` not `[SOME-JAIL]` (note the case-sensitivity) and also not `some-jail-iptables`. The name of jail must be equal the name of file without extension `.conf` or `.local`.

In your case for "/etc/fail2ban/jail.d/ssh.local", you must have:
```ini
[ssh]
...
enabled = true
```

Another way is to use single config file `/etc/fail2ban/jail.local` for multiple jails (overwriting `/etc/fail2ban/jail.conf`), so for example it would be enough:
```ini
[sshd]
maxretry = 3
enabled = true

[nginx-http-auth]
enabled = true
```
to overwrite `maxretry` and enable the default [sshd](https://github.com/fail2ban/fail2ban/blob/8ac49b58582cfe82626307b5a8b0574a63499d95/config/jail.conf#L274) jail (note it is called `sshd` not `ssh` in stock version) as well as `nginx-http-auth` jail.

> maxRetry=3

```diff
- maxRetry=3
+ maxretry = 3
```
Again, all sections and parameters in fail2ban are case sensitive.

See [wiki :: Proper fail2ban configuration](https://github.com/fail2ban/fail2ban/wiki/Proper-fail2ban-configuration) and [man jail.conf.5](https://manpages.debian.org/unstable/fail2ban/jail.conf.5.en.html) for details.

2. What do you see if you try to dump parameters?
```bash
fail2ban-client -d | grep 'ssh.*maxretry'
```
This way you can check which parameter will be supplied to fail2ban by (re)start or reload.

3. By the way, reload has certain restrictions compared to `restart` (at the moment)... for example action related changes by reload would affect only starting run-time parameters, but if the action already started (by first ban), the chains (or whatever action creates) may still contain previous values. Thus if you change the action or action-relevant parameters for jail (not `maxretry`), you need to restart fail2ban (see [#2716](https://github.com/fail2ban/fail2ban/issues/2716#issuecomment-624758371)).

**Comment by sebres** [comment]
> but "iptables -L" shows that there is no such IP address when writing "Ban x.x.x.x" in the log file.

- either it is the same issue like with `maxretry` (wrong config and case-sensitivity of section)
- or you have some issue with iptables or its action, see the answer for 2nd question in FAQ of [wiki :: How fail2ban works](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works).
BTW, sometimes adding option `-n` (so `iptables -nL`) helps to find the IP (without `-n` it may be found as some reverse DNS).
And take a look in fail2ban.log whether there are some errors after `Ban ...`.

Also you can simply overwrite `banaction` (for every jail or even for default like here), so the [action_](https://github.com/fail2ban/fail2ban/blob/eea1881b734b73599a21df2bfbe58b11f78d0a46/config/jail.conf#L212) and resulting [action](https://github.com/fail2ban/fail2ban/blob/eea1881b734b73599a21df2bfbe58b11f78d0a46/config/jail.conf#L268) interpolation gets all parameters correctly:
```ini
[DEFAULT]
banaction = iptables-multiport
banaction_allports = iptables-allports
```

**Comment by Xingeqwd** [comment]
@sebres thank you very much! Your suggestion is very helpful to me. These issues should have all been resolved.

**In order to help people who encounter similar problem in the future to solve the problem more conveniently, I will write some more detailed information about the problem.**

Regarding the problem that the configuration information reflected in the log file is different from the configuration file, I think there should be two possible causes as shown below:
- first, It's the case-sensitivity of "maxRetry"(I just changed it last night, I forgot to change it back)
- second, The difference between the configuration file and the actual configuration should be caused by the inconsistency of the configuration file name and jail name

Regarding the reason why the baning of fail2ban does not take effect, I think there should be one possible causes as shown below:
- The action line in the configuration file is incorrectly configured, resulting in no substantive action being taken.
the correct "action" line(for me, or iptables users) should be:
`banaction = iptables-multiport`
instead of 
`action = iptables[name=nginx, port=http, protocol=tcp]`

By the way, (For those of you who encounter similar problems) If you have all the above-mentioned issues, try to check if there is no conflict in the names of jail and configuration files, restart the fail2ban service, etc.

All in all, This series of problems have been successfully solved, thanks for evryone trying to help me.
