### ISSUE TITLE
[BR]: install failed on my openwrt device

### ISSUE THREAD

**Issue by sean908** [fail2ban/fail2ban#3220]
### Environment:

- Fail2Ban version  : 0.11.2
- OS, including release name/version : Linux OpenWrt 5.4.170 SMP PREEMPT Wed Jan 5 23:02:24 CST 2022 aarch64 GNU/Linux
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
running `python setup.py install` and found some errs
> byte-compiling /usr/lib/python3.9/site-packages/fail2ban/tests/filtertestcase.py to filtertestcase.cpython-39.pyc
  File "/usr/lib/python3.9/site-packages/fail2ban/tests/filtertestcase.py", line 1778
    				   % m for m in 53, 54, 57, 58])
    				                  ^
SyntaxError: invalid syntax
> byte-compiling /usr/lib/python3.9/site-packages/fail2ban/tests/misctestcase.py to misctestcase.cpython-39.pyc
  File "/usr/lib/python3.9/site-packages/fail2ban/tests/misctestcase.py", line 259
    				print deep_function(3)
    				      ^
SyntaxError: invalid syntax
> byte-compiling /usr/lib/python3.9/site-packages/fail2ban/server/ipdns.py to ipdns.cpython-39.pyc
  File "/usr/lib/python3.9/site-packages/fail2ban/server/ipdns.py", line 333
    					mask = ~(0xFFFFFFFFL >> cidr)
    					                   ^
SyntaxError: invalid syntax

#### Any additional information
after the installation, I ran `fail2ban-client -h` and get the following info
> Traceback (most recent call last):
  File "/usr/bin/fail2ban-client", line 34, in <module>
    from fail2ban.client.fail2banclient import exec_command_line, sys
  File "/usr/lib/python3.9/site-packages/fail2ban/client/fail2banclient.py", line 39, in <module>
    from ..server.utils import Utils
  File "/usr/lib/python3.9/site-packages/fail2ban/server/utils.py", line 56, in <module>
    for name, num in signal.__dict__.iteritems() if name.startswith("SIG"))
AttributeError: 'dict' object has no attribute 'iteritems'

#### Any customizations done to /etc/fail2ban/ configuration

```
```

#### Relevant parts of /var/log/fail2ban.log file:

```
```

#### Relevant lines from monitored log files:

```
```

**Comment by sebres** [comment]
See https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually#manual-installation-from-source
(Shortly missing ./fail2ban-2to3 before install or build)

Also note https://github.com/fail2ban/fail2ban/issues/2712#issuecomment-1028900927 (you need a clean copy if you run 2to3, so reset or clone fresh working copy or unpack downloaded version again).
