### ISSUE TITLE
[RFE]: Log source over network

### ISSUE THREAD

**Issue by gr3m1in** [fail2ban/fail2ban#3234]
It would be very useful to have an option of feeding the fail2ban instance with logs over network from remote syslog instance.

Most of well-known and mature syslog servers, like syslog-ng and rsyslog, do support sending logs to remote instances to perform centralized logging.
Such a centralized logging server normally should NOT be located on a border host with fail2ban installed.
And having a more complicated infrastructure, with different servers spread among multiple hosts, leads to centralized logging, which, in order, makes it useful to feed fail2ban from such centralized log server.
Such approach will also allow to feed multiple border instances, with fail2ban installed, from single centralized syslog over internal network, which should improve the security by applying the restrictions to all the border hosts.

**Comment by sebres** [comment]
dup of #3043 (or probably #881)
