### ISSUE TITLE
[BR]: Failed to restart firewalld.service: Transaction contains conflicting jobs 'restart' and 'stop' for fail2ban.service

### ISSUE THREAD

**Issue by szotsaki** [fail2ban/fail2ban#3236]
### Environment:

- Fail2Ban version  : 0.11.2-bp153.2.3.1
- systemd version: 246.16
- OS, including release name/version : openSUSE Leap 15.3
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

When I try to restart `firewalld.service` it fails because of the following error message:

```
Failed to restart firewalld.service: Transaction contains conflicting jobs 'restart' and 'stop' for fail2ban.service. Probably contradicting requirement dependencies configured.
See system logs and 'systemctl status firewalld.service' for details.
```

### Configuration, dump and another helpful excerpts

Current `fail2ban.service` file content:

```
[Unit]
Description=Fail2Ban Service
Documentation=man:fail2ban(1)
After=network.target iptables.service firewalld.service ip6tables.service ipset.service nftables.service
PartOf=firewalld.service ipset.service nftables.service

[Service]
Type=simple
EnvironmentFile=-/etc/sysconfig/fail2ban
Environment="PYTHONNOUSERSITE=1"
ExecStartPre=/bin/mkdir -p /run/fail2ban
ExecStart=/usr/bin/fail2ban-server -xf $FAIL2BAN_OPTIONS start
# if should be logged in systemd journal, use following line or set logtarget to sysout in fail2ban.local
# ExecStart=/usr/bin/fail2ban-server -xf --logtarget=sysout start
ExecStop=/usr/bin/fail2ban-client stop
ExecReload=/usr/bin/fail2ban-client reload
PIDFile=/run/fail2ban/fail2ban.pid
Restart=on-failure
RestartPreventExitStatus=0 255

[Install]
WantedBy=multi-user.target
```

`firewalld.service:`
```
[Unit]
Description=firewalld - dynamic firewall daemon
Before=network-pre.target
Wants=network-pre.target
After=dbus.service
After=polkit.service
Conflicts=iptables.service ip6tables.service ebtables.service ipset.service nftables.service
Documentation=man:firewalld(1)

[Service]
EnvironmentFile=-/etc/sysconfig/firewalld
ExecStart=/usr/sbin/firewalld --nofork --nopid $FIREWALLD_ARGS
ExecReload=/bin/kill -HUP $MAINPID
# supress to log debug and error output also to /var/log/messages
StandardOutput=null
StandardError=null
Type=dbus
BusName=org.fedoraproject.FirewallD1
KillMode=mixed

[Install]
WantedBy=multi-user.target
Alias=dbus-org.fedoraproject.FirewallD1.service
```

`firewalld.service` is depending on `fail2ban.service` but not the other way around (however you see it mentioned only in the `fail2ban.service` file):

```
$> systemctl list-dependencies firewalld.service | grep fail2ban
● ├─fail2ban.service
$> systemctl list-dependencies fail2ban.service | grep firewalld
```

**Comment by sebres** [comment]
> `firewalld.service` is depending on `fail2ban.service` but not the other way around

In normal case it must be exactly vice versa: `fail2ban` requires `firewalld` (if it'd use `firewalld` banning actions). I don't know why it must be in another direction (why firewalld may require fail2ban to start).
Also your excerpts of systemd units show that picture.
Check whether you have some locally declared unit overrides, e. g. in `/etc/systemd/system/*.service.d/` folder (replace `*` with `fail2ban` and `firewalld`) or use `?sudo? systemctl cat ...` and `?sudo? systemctl edit ...` to show or edit local configuration.

If you don't have local configs introducing conflicts, it is matter of fail2ban maintainers for your distribution.
@fail2ban/maintainers any idea what may be wrong with openSUSE's fail2ban / firewalld packets?

**Comment by sebres** [comment]
Perhaps it is the "conflicts" line in `firewalld`:
```
Conflicts=iptables.service ip6tables.service ebtables.service ipset.service nftables.service
```
because fail2ban.service is depending on some of them (by default all network filter sub-system are mentioned as dependencies), e. g. this is used in upstream release:
https://github.com/fail2ban/fail2ban/blob/8c4d02403b4768fb1a76372a7a462fc903c2711e/files/fail2ban.service.in#L4-L5

If it is indeed this conflict, as a workaround, you could override `After` (and probably `PartOf`) entries of unit section for fail2ban (e. g. with `?sudo? systemctl edit fail2ban`):

1. without `firewalld.service` if you don't use `firewalld` actions and firewalld at all:
```ini
 [Unit]
After=network.target iptables.service ip6tables.service ipset.service nftables.service
PartOf=ipset.service nftables.service
```

2. with `firewalld.service` only, if you use `firewalld` actions or firewalld:
```ini
[Unit]
After=network.target firewalld.service
PartOf=firewalld.service
```
