### ISSUE TITLE
[FR]: Gopher (port 70)

### ISSUE THREAD

**Issue by drbeco** [fail2ban/fail2ban#3238]
This is not a filter "request" per se.

I've created a new filter for gopher (gophernicus, port 70), and I would like to submit it to the project, if that is ok.

This filter will prevent attempts to send a SIGINT  by checking syslog gophernicus error `File not found` and banning the IP.

### Environment:

- Fail2Ban version  : Fail2Ban v0.11.2
- OS, including release name/version :  Slackware 15.0 x86_64

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : /etc/fail2ban/filter.d/gopher.conf
- Service, project or product name, including release name/version :  gopher / gophernicus server
- Repository :  none. A single file. I can create it as repository, but it is overkill
- Service type :  filter
- Ports and protocols the service is listening : 70 / tcp

Please let me know how to proceed to provide the filter to this project. Thanks

**Comment by drbeco** [comment]
I'm gonna try a PR. Please let me know if I did it right, or if you need anything to be changed.

**Comment by sebres** [comment]
thus closing it now, further in #3240
