### ISSUE TITLE
fail2ban fails in my case where no auth.log file

### ISSUE THREAD

**Issue by gaamaaresosa** [fail2ban/fail2ban#3245]
I use Raspberry Pi-4 with Buster 32bit OS (Linux)
To extend the SD card life we avoid more frequent read/write op.
We disable rsyslog service to avoid log writing on SD card.

So no /var/log/auth.log is expected.
Now fail2ban fails to stats its service and not doing the BAN !

Please help me some alternate solution which is not depending and system log files.

**Comment by sebres** [comment]
> To extend the SD card life we avoid more frequent read/write op.

Strange idea, particularly if one thinks about that in linux/unix many many things are files.
And that such a "frequent" read would not happen because the buffer (written currently) must be still in system cache.

> So no /var/log/auth.log is expected...  not doing the BAN !

First of all read the first sentence of [https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works].
At the moment fail2ban is able to monitor log file (`backend = auto`) and systemd journal (`backend = systemd`) only.
No other backends are implemented in this stock repo.
However the monitoring isn't really necessary, because fail2ban can be notified about every failed attempt over command line or pickle protocol (via unix socket) sending `set $jail attempt ...` to fail2ban server, see https://github.com/fail2ban/fail2ban/issues/2559#issuecomment-548851675 for an example how one can implement that.
Just in this case the service you want to protect with fail2ban must support such functionality (or you have to extend it with that facilities).
But I don't think that a invocation of external program would not cause occasionally some read.

Alternatively you may think about some RAM-disk for the log-files, just RPi has few memory, so your ramdisk would be probably not so large, so you've often to rotate the files within.

Another variant would be to write some new backend monitoring, hmm... what would that monitor instead of file or journal? Pipe? Unix-socket? Which service(s) do you plan to protect?

For completely alternate solutions please seek for help on stackexchange (serverfault, superuser, etc). This repository serves fail2ban needs.

**Comment by sebres** [comment]
> Anyhow fail2ban is smart to detect 5 failures. 

There is no magic, fail2ban works as I described above. No log files or journal - no detection.
Either you have still another jail monitoring different files or something similar. As already said - no magic.

> Let me assume auth.log file is used for some advance security and self log.

No, it is mandatory for some jail your fail2ban is configured.
You can see which is it with this command:
```
fail2ban-client -d | grep auth.log
```
And you can surely disable this jail (but then it'd stop to detect failures for that service) or remove the log path or replace it with another one (but then, well the same as above).

**Comment by sebres** [comment]
For example sshd or pam-generic jails may monitor auth.log, if you'd disable that jails, your fail2ban would not ban intruders anymore, that bruteforcing sshd or PAM authentication service.

**Comment by gaamaaresosa** [comment]
Here I compared 2 systems (Raspberrry Pi -4 Box)
One is without disabling the log generation and other logging disabled.
Do you think still its my local issue ?

**SYSTEM WHERE NO LOG IS DISABBLED:**    
pi@Raspberry:~$ fail2ban-client -d | grep auth.log
['set', 'sshd', 'addlogpath', '/var/log/auth.log', 'head']
['set', 'sshd-persistent', 'addlogpath', '/var/log/auth.log', 'head']
    
    
pi@Raspberry:~$ sudo systemctl status fail2ban
[sudo] password for pi:
● fail2ban.service - Fail2Ban Service
     Loaded: loaded (/lib/systemd/system/fail2ban.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-03-22 09:57:15 IST; 1 day 11h ago
       Docs: man:fail2ban(1)
    Process: 732 ExecStartPre=/bin/mkdir -p /run/fail2ban (code=exited, status=0/SUCCESS)
   Main PID: 755 (f2b/server)
      Tasks: 7 (limit: 2101)
     CGroup: /system.slice/fail2ban.service
             └─755 /usr/bin/python3 /usr/bin/fail2ban-server -xf start

Mar 22 09:57:15 pi systemd[1]: Starting Fail2Ban Service...
Mar 22 09:57:15 pi systemd[1]: Started Fail2Ban Service.
Mar 22 10:16:09 pi fail2ban-server[755]: Server ready


    
**SYSTEM WHERE LOG IS DISABBLED:**        
pi@Raspberry:~ $ fail2ban-client -d | grep auth.log
 No file(s) found for glob /var/log/auth.log
 Have not found any log file for sshd jail
 No file(s) found for glob /var/log/auth.log
 Have not found any log file for sshd-persistent jail

    
pi@Raspberry:~ $ sudo systemctl status fail2ban
● fail2ban.service - Fail2Ban Service
   Loaded: loaded (/lib/systemd/system/fail2ban.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2022-03-23 21:17:11 IST; 20min ago
     Docs: man:fail2ban(1)
 Main PID: 784 (code=exited, status=255/EXCEPTION)

Mar 23 21:17:11 Raspberry fail2ban-server[784]:  Failed during configuration: Have not found any log file for sshd jail
Mar 23 21:17:11 Raspberry fail2ban-server[784]:  Async configuration of server failed
Mar 23 21:17:11 Raspberry systemd[1]: fail2ban.service: Main process exited, code=exited, status=255/EXCEPTION
Mar 23 21:17:11 Raspberry systemd[1]: fail2ban.service: Failed with result 'exit-code'.
Mar 23 21:23:59 Raspberry systemd[1]: /lib/systemd/system/fail2ban.service:12: PIDFile= references path below legacy dir
Mar 23 21:24:11 Raspberry systemd[1]: /lib/systemd/system/fail2ban.service:12: PIDFile= references path below legacy dir
Mar 23 21:26:38 Raspberry systemd[1]: /lib/systemd/system/fail2ban.service:12: PIDFile= references path below legacy directory /var/ru
Mar 23 21:26:39 Raspberry systemd[1]: /lib/systemd/system/fail2ban.service:12: PIDFile= references path below legacy directory /var/ru
Mar 23 21:26:40 Raspberry systemd[1]: /lib/systemd/system/fail2ban.service:12: PIDFile= references path below legacy directory /var/ru
Mar 23 21:26:41 Raspberry systemd[1]: /lib/systemd/system/fail2ban.service:12: PIDFile= references path below legacy directory /var/ru
lines 1-16/16 (END)

**Comment by gaamaaresosa** [comment]
May be my /etc/fail2ban/jail.local files wrongly configured ?
**logpath = /var/log/auth.log**

sudo nano /etc/fail2ban/jail.local
    
[sshd]
enabled = true
port = 2002
filter = sshd
**logpath = /var/log/auth.log**
bantime = 600
findtime = 600
maxretry = 5

[sshd-persistent]
enabled = true
port = 2002
filter = sshd
**logpath = /var/log/auth.log**
bantime = 604800
findtime = 604800
maxretry = 19

**Comment by sebres** [comment]
> May be my /etc/fail2ban/jail.local files wrongly configured ?

No! Are you kidding me?! 
Please read again how fail2ban work (https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works).

Either the log file or the journal is **MANDATORY** to make the jails `sshd` or `sshd-persistent` work at all. 
At the moment there are no out-of-the-box solution in fail2ban for sshd to notify fail2ban directly without monitoring the log/journal. This is the way how default backends of fail2ban work.
So you have to provide some log where sshd writes the failures or to switch `backend` to `systemd` (but sshd must also log into systemd journal otherwise fail2ban would not detect anything from sshd). 
Or to disable both jails (with a consequence that fail2ban would not protect this service anymore).

Savvy?

**Comment by gaamaaresosa** [comment]
I am really sorry for not reading the bottom line that without auth.log (or journal) fail2ban won't work properly.
Since I am from Windows background slowly learning the linux architecture.
Honestly still I don't know what is journal.
Can you please help me how to block auth.log writes every commands I use on my main app on auth.log ?
I expect auth.log should write only ssh login related information or anything related to authentication (security)

**Comment by sebres** [comment]
> Honestly still I don't know what is journal.

Journal is journal. See man for [journalctl](https://manpages.debian.org/buster/systemd/journalctl.1.en.html) for details. 
If your system supporting journal, ensure your sshd would log there, and you can check whether it basically works for you with:
```
fail2ban-regex systemd-journal sshd[mode=aggressive]
```
If you'd find matches, just add `backend = systemd` to the jail and restart fail2ban (or jail).

> I expect auth.log should write only ssh login related information or anything related to authentication (security)

It is rsyslog rules that target the logfile (typically by the facility, but one can write own rules), see `/etc/rsyslog.conf` or `/etc/rsyslog.d/*` for rules looking like:
```
auth,authpriv.*                 /var/log/auth.log
```
This among other things means that anything with facility `auth` would be added to auth.log (additionally to syslog).
So the message logged by the command:
```
logger -t 'xxxx' --id=12345 -p auth.info 'My message with auth facility'
```
would be added to syslog (whatever it is) and additionally to the `/var/log/auth.log`

You must check what exactly and which parameters your program uses to log and which rules causes that this messages arriving on auth.log.

**Comment by gaamaaresosa** [comment]
Thanks again...
I will try all your suggestion soon.

**Comment by gaamaaresosa** [comment]
I think I have to learn making rules to ban extra logs by auth.log and then try fail2ban.
This reply seems again it expects /var/log/lastlog file.

pi@Raspberry:~ $ fail2ban-regex systemd-journal sshd[mode=aggressive]

Running tests
=============

Use   failregex filter file : sshd, basedir: /etc/fail2ban
Use   filter options : {'mode': 'aggressive'}
Use         maxlines : 1
Use      datepattern : Default Detectors
Use         systemd journal
Use         encoding : UTF-8
Use    journal match : _SYSTEMD_UNIT=sshd.service + _COMM=sshd


Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:

Lines: 11 lines, 0 ignored, 0 matched, 11 missed
[processed in 0.01 sec]

|- Missed line(s):
|  2022-03-26T03:17:05.112484GB-Raspberry sshd[646]: Server listening on 0.0.0.0 port 2002.
|  2022-03-26T03:17:05.112628GB-Raspberry sshd[646]: Server listening on :: port 2002.
|  2022-03-26T03:27:34.350607GB-Raspberry sshd[646]: Received signal 15; terminating.
|  2022-03-26T03:28:04.664537GB-Raspberry sshd[1916]: Server listening on 0.0.0.0 port 2002.
|  2022-03-26T03:28:04.664645GB-Raspberry sshd[1916]: Server listening on :: port 2002.
|  2022-03-26T03:28:04.731620GB-Raspberry sshd[1916]: Received signal 15; terminating.
|  2022-03-26T03:28:04.796105GB-Raspberry sshd[1924]: Server listening on 0.0.0.0 port 2002.
|  2022-03-26T03:28:04.796203GB-Raspberry sshd[1924]: Server listening on :: port 2002.
|  2022-03-26T03:28:39.548703GB-Raspberry sshd[2125]: Accepted password for gstreama from 192.168.1.4 port 2665 ssh2
|  2022-03-26T03:28:39.597537GB-Raspberry sshd[2125]: lastlog_openseek: Couldn't stat /var/log/lastlog: No such file or directory
|  2022-03-26T03:28:39.598324GB-Raspberry sshd[2125]: lastlog_openseek: Couldn't stat /var/log/lastlog: No such file or directory

**Comment by sebres** [comment]
So your sshd seems to log to systemd journal, therefore you can switch that jails to systemd backend.

As for lastlog, it has nothing to do with fail2ban, your sshd simply miss the info about last logins, see https://lists.debian.org/debian-user/2009/04/msg01923.html

**Comment by gaamaaresosa** [comment]
Thanks again for your help.
After I manually created the lastlog file and set permissions

Now I see below reply.
Any how let me learn and fix it.



pi@Raspberry:~ $ fail2ban-regex systemd-journal sshd[mode=aggressive]

Running tests
=============

Use   failregex filter file : sshd, basedir: /etc/fail2ban
Use   filter options : {'mode': 'aggressive'}
Use         maxlines : 1
Use      datepattern : Default Detectors
Use         systemd journal
Use         encoding : UTF-8
Use    journal match : _SYSTEMD_UNIT=sshd.service + _COMM=sshd


Results
=======

Failregex: 5 total
|-  #) [# of hits] regular expression
|   4) [5] ^Failed \b(?!publickey)\S+ for (?P<cond_inv>invalid user )?<F-USER>(?P<cond_user>\S+)|(?(cond_inv)(?:(?! from ).)*?|[^:]+)</F-USER> from <HOST>(?: port \d+)?(?: on \S+(?: port \d+)?)?(?: ssh\d*)?(?(cond_user): |(?:(?:(?! from ).)*)$)
`-

Ignoreregex: 0 total

Date template hits:

Lines: 31 lines, 0 ignored, 5 matched, 26 missed
[processed in 0.02 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all 26 lines

**Comment by gaamaaresosa** [comment]
Hi Sebres !
Thanks a million for your patience to tech me few things.
Now I learnt the rsyslog rules, removed all unwanted logs except only the sshd logs for fail2ban.
Seems its working fine as expected.
