### ISSUE TITLE
[BR]: complete silent failure - re-attaching net ifaces

### ISSUE THREAD

**Issue by lejeczek** [fail2ban/fail2ban#3246]
### Environment:

- Fail2Ban version  : 
- OS, including release name/version : 
- [x ] Fail2Ban installed via OS/distribution mechanisms
- [x ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Detach net iface from the system - it's not 100% certain that de/attach iface is the crucial part here, but it's how it reproduces the problem - and let bans expire then:
Later re/attach net iface, which in my case is a public-facing connection, to see that suspicious activity starts to arrive, 'ssh' most obvious.
yet!!
'fail2ban-client' does not report those "activities" nor 'nft' gets those - fail2ban, thus whole system remains oblivious to those attacks.
I waited for minutes, for hours but until I manually
-> $ systemctl restart fail2ban.service 
'fail2ban' remains is such completely "broken" state.
That manual 'systemd' restart gets all IPs reported and 'nft-fixed' immediately.
 

#### Any additional information

fail2ban-firewalld-0.11.2-11.el9.noarch
fail2ban-server-0.11.2-11.el9.noarch
CentOS 9

#### Any customizations done to /etc/fail2ban/ configuration

```
```

#### Relevant parts of /var/log/fail2ban.log file:

```
```

#### Relevant lines from monitored log files:

```
```

**Comment by sebres** [comment]
Although I wouldn't necessary say that I'd expect that a net-filter subsystem must react on reset of ifaces...

Fail2ban doesn't have directly to do with ifaces at all. It is the matter of banning action or else the related net-filter subsystem.
For instance I assume you're using nftables as banning action.

Then the simplest case of banned single IP 192.0.2.1 would look like:
```bash
nft add table inet f2b-table
nft add set inet f2b-table addr-set-f2b \{ type ipv4_addr\; \}
nft add element inet f2b-table addr-set-f2b \{ 192.0.2.1 \}
```
The finally table and set looks like this:
```bash
$ nft list table inet f2b-table
table inet f2b-table {
        set addr-set-f2b {
                type ipv4_addr
                elements = { 192.0.2.1 }
        }
}
```
<details><summary>clean up commands for that...</summary>

```
nft flush set inet f2b-table addr-set-f2b && nft delete set inet f2b-table addr-set-f2b
# nft delete table inet f2b-table
```
</details>

Do you see some iface related rule there?

However if you'd tell me that the ntf-rules disappearing after reattach of ifaces, then we can probably do something, otherwise I don't see how we could help here... And there are already many enhancements in new versions making some of banning actions more breakdown safe and able to restore sane net-filter environment of fail2ban with rebanning IPs etc.

Just a reattach of ifaces is a bit different situation (which may expect some extra activities from admin).

Anyway the fair question is: Why you open the issue in fail2ban and not in nftables bug tracker?
To me it is a clear 3rd party issue (let alone I'm still unsure it can be considered as a real issue at all), thus... sorry but I'll close it here.

**Comment by lejeczek** [comment]
I use: banaction = firewallcmd-allports
I'm not sure how do you mean 'third-party' - I'd think that 'third-party', whatever that might be, operates under control of 'fail2ban'

I did not think it was certain that re/attach net iface is the critical bit here - it was just how I found out - I'd imagine the same must happen when connection(s) via which "activities" come in, are down/off - eg. pull network lead out - or perhaps in general, system just stop recording/seeing those activities (for whatever reason)

To simplify take 'ssh' - if network connection(s), not only re/attach iface, plays no role.
a) no more bans after certain point in time
b) bans expire (which is when 'fail2ban-client' shows nothing in (Banned IP list')
c) later new ban candidates begin to arrive (via ssh)
but 'fail2ban-client' still shows no IPs banned while 'ssh' continues to log more & repeating rouge IPs.
This new(or same but expired) IPs will not show up in 'fail2ban' until a restart with/via 'systemd'

Would that be still 3rd party?

**Comment by sebres** [comment]
> I'm not sure how do you mean 'third-party' - I'd think that 'third-party', whatever that might be, operates under control of 'fail2ban'

Third-party issue means that something outside of fail2ban facilities doesn't work as expected. If fail2ban using some action to ban IPs and the utility using in this action behaves weird, it is simply not an issue of fail2ban.

You have the choice:
- either to switch to another (and better native) net-filter action;
- or find out what happens exactly, e. g. (and provide here the proofs that it is really the issue of fail2ban, because it doesn't do something properly with that action);
- or (if firewalld doesn't work as expected) to open the issue in bug tracker of firewalld.

> but 'fail2ban-client' still shows no IPs banned while 'ssh' continues to log more & repeating rouge IPs.

OK, this has noting todo with the action you use. If fail2ban doesn't ban anymore, it means that the filter of jail doesn't find a failures or that the backend of jail doesn't recognize notifications in log or journal. 
See https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works for the FAQ.
Just I didn't see that this happening at some point only and gets "fixed" by restart only.
Can it be that the log-file get rotated in some unusual way (e. g. by rotation the old file is renamed, new file is created but the service still logging in old file)?

This all is totally confusing now, so can you probably tell us what exactly doesn't work in your case.
If it is the filter (so you don't see `[sshd?] Found ...` in fail2ban.log and don't see finding by `fail2ban-client status ssh`), please provide except of the log/journal as well as the output of:
```
fail2ban-client -d | grep ssh
```

And please extend the fields of issue template above (Fail2Ban version, OS, including release name/version etc).

**Comment by lejeczek** [comment]
I took bit longer & watch it more - original "issue" of iface being re/move is irrelevant now - so perhaps it is a separate bug? (I see similar, different placeholder though - https://github.com/linuxserver/docker-swag/issues/94)
I see this happens after several hours - did not time it so cannot tell if there is a pattern, sorry.
Here (so now different filter action)... :
After certain period of time where fail2ban does not add/create new bans, I can see 'systemd' logs new ssh "failures", snippets from there:
...
Failed password for root from 20.197.197.11 port 56876 ssh2
pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=20.197.197.11 user=root
Failed password for root from 20.197.197.11 port 46524 ssh2
pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=20.197.197.11 user=root
Failed password for root from 20.197.197.11 port 36218 ssh2
pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=20.197.197.11 user=root
Failed password for root from 20.197.197.11 port 54110 ssh2
pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=20.197.197.11 user=root
Failed password for root from 20.197.197.11 port 43748 ssh2
...
So that above qualifies for immediate ban yet fail2ban remains "blind" to that.
Why I do not think it seems like 'config' issue? - certainly not user end of it - because that IP from above snippets(and others which were "ignored") gets into "Banned IP list" (&nft table), the moment I do:
-> $ systemctl restart fail2ban.service

I'm not an expert on journald logs but I believe "logrotate" should no apply.

`fail2ban-client -d | grep ssh
['add', 'sshd', 'systemd']
['set', 'sshd', 'usedns', 'warn']
['set', 'sshd', 'prefregex', '^<F-MLFID>\\s*(?:\\S+\\s+)?(?:sshd(?:\\[\\d+\\])?:?\\s+)?(?:kernel:\\s?\\[ *\\d+\\.\\d+\\]:?\\s+)?</F-MLFID>(?:(?:error|fatal): (?:PAM: )?)?<F-CONTENT>.+</F-CONTENT>$']
['set', 'sshd', 'maxlines', 1]
['multi-set', 'sshd', 'addfailregex', ['^[aA]uthentication (?:failure|error|failed) for <F-USER>.*</F-USER> from <HOST>( via \\S+)?(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^User not known to the underlying authentication module for <F-USER>.*</F-USER> from <HOST>(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^Failed publickey for invalid user <F-USER>(?P<cond_user>\\S+)|(?:(?! from ).)*?</F-USER> from <HOST>(?: (?:port \\d+|on \\S+)){0,2}(?: ssh\\d*)?(?(cond_user): |(?:(?:(?! from ).)*)$)', '^Failed (?:<F-NOFAIL>publickey</F-NOFAIL>|\\S+) for (?P<cond_inv>invalid user )?<F-USER>(?P<cond_user>\\S+)|(?(cond_inv)(?:(?! from ).)*?|[^:]+)</F-USER> from <HOST>(?: (?:port \\d+|on \\S+)){0,2}(?: ssh\\d*)?(?(cond_user): |(?:(?:(?! from ).)*)$)', '^<F-USER>ROOT</F-USER> LOGIN REFUSED FROM <HOST>', '^[iI](?:llegal|nvalid) user <F-USER>.*?</F-USER> from <HOST>(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^User <F-USER>\\S+|.*?</F-USER> from <HOST> not allowed because not listed in AllowUsers(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^User <F-USER>\\S+|.*?</F-USER> from <HOST> not allowed because listed in DenyUsers(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^User <F-USER>\\S+|.*?</F-USER> from <HOST> not allowed because not in any group(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^refused connect from \\S+ \\(<HOST>\\)', '^Received <F-MLFFORGET>disconnect</F-MLFFORGET> from <HOST>(?: (?:port \\d+|on \\S+)){0,2}:\\s*3: .*: Auth fail(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^User <F-USER>\\S+|.*?</F-USER> from <HOST> not allowed because a group is listed in DenyGroups(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', "^User <F-USER>\\S+|.*?</F-USER> from <HOST> not allowed because none of user's groups are listed in AllowGroups(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$", '^<F-NOFAIL>pam_[a-z]+\\(sshd:auth\\):\\s+authentication failure;</F-NOFAIL>(?:\\s+(?:(?:logname|e?uid|tty)=\\S*)){0,4}\\s+ruser=<F-ALT_USER>\\S*</F-ALT_USER>\\s+rhost=<HOST>(?:\\s+user=<F-USER>\\S*</F-USER>)?(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^maximum authentication attempts exceeded for <F-USER>.*</F-USER> from <HOST>(?: (?:port \\d+|on \\S+)){0,2}(?: ssh\\d*)?(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^User <F-USER>\\S+|.*?</F-USER> not allowed because account is locked(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*', '^<F-MLFFORGET>Disconnecting</F-MLFFORGET>(?: from)?(?: (?:invalid|authenticating)) user <F-USER>\\S+</F-USER> <HOST>(?: (?:port \\d+|on \\S+)){0,2}:\\s*Change of username or service not allowed:\\s*.*\\[preauth\\]\\s*$', '^Disconnecting: Too many authentication failures(?: for <F-USER>\\S+|.*?</F-USER>)?(?: (?:port \\d+|on \\S+|\\[preauth\\])){0,3}\\s*$', '^<F-NOFAIL>Received <F-MLFFORGET>disconnect</F-MLFFORGET></F-NOFAIL> from <HOST>(?: (?:port \\d+|on \\S+)){0,2}:\\s*11:', '^<F-MLFFORGET>Disconnected</F-MLFFORGET>(?: from)?(?: (?:invalid|authenticating)) user <F-USER>\\S+|.*?</F-USER> <HOST>(?: (?:port \\d+|on \\S+)){0,2} \\[preauth\\]\\s*$', '^<F-MLFFORGET><F-MLFGAINED>Accepted \\w+</F-MLFGAINED></F-MLFFORGET> for <F-USER>\\S+</F-USER> from <HOST>(?:\\s|$)', '^Received <F-MLFFORGET>disconnect</F-MLFFORGET> from <HOST>(?: (?:port \\d+|on \\S+)){0,2}:\\s*14: No(?: supported)? authentication methods available', '^Unable to negotiate with <HOST>(?: (?:port \\d+|on \\S+)){0,2}: no matching (?:(?:\\w+ (?!found\\b)){0,2}\\w+) found.', '^Unable to negotiate a (?:(?:\\w+ (?!found\\b)){0,2}\\w+)', '^no matching (?:(?:\\w+ (?!found\\b)){0,2}\\w+) found:', '^<F-NOFAIL>Connection from</F-NOFAIL> <HOST>']]
['set', 'sshd', 'datepattern', '{^LN-BEG}']
['set', 'sshd', 'addjournalmatch', '_SYSTEMD_UNIT=sshd.service', '+', '_COMM=sshd']
['set', 'sshd', 'maxretry', 2]
['set', 'sshd', 'maxmatches', 2]
['set', 'sshd', 'findtime', '10m']
['set', 'sshd', 'bantime', '96h']
['set', 'sshd', 'bantime.increment', True]
['set', 'sshd', 'ignorecommand', '']
['set', 'sshd', 'addignoreip', '127.0.0.1/8']
['set', 'sshd', 'logencoding', 'auto']
['set', 'sshd', 'addaction', 'nftables']
['multi-set', 'sshd', 'action', 'nftables', [['actionstart', "nft add table inet f2b-table\nnft -- add chain inet f2b-table f2b-chain \\{ type filter hook input priority -1 \\; \\}\nnft add set inet f2b-table <addr_set> \\{ type <addr_type>\\; \\}\nfor proto in $(echo 'tcp' | sed 's/,/ /g'); do\nnft add rule inet f2b-table f2b-chain $proto dport \\{ $(echo 'ssh' | sed s/:/-/g) \\} <addr_family> saddr @<addr_set> reject\ndone"], ['actionstop', "{ nft -a list chain inet f2b-table f2b-chain | grep -oP '@<addr_set>\\s+.*\\s+\\Khandle\\s+(\\d+)$'; } | while read -r hdl; do\nnft delete rule inet f2b-table f2b-chain $hdl; done\nnft delete set inet f2b-table <addr_set>\n{ nft list table inet f2b-table | grep -qP '^\\s+set\\s+'; } || {\nnft delete table inet f2b-table\n}"], ['actionflush', "{ nft flush set inet f2b-table <addr_set> 2> /dev/null; } || {\n{ nft -a list chain inet f2b-table f2b-chain | grep -oP '@<addr_set>\\s+.*\\s+\\Khandle\\s+(\\d+)$'; } | while read -r hdl; do\nnft delete rule inet f2b-table f2b-chain $hdl; done\nnft delete set inet f2b-table <addr_set>\nnft add set inet f2b-table <addr_set> \\{ type <addr_type>\\; \\}\nfor proto in $(echo 'tcp' | sed 's/,/ /g'); do\nnft add rule inet f2b-table f2b-chain $proto dport \\{ $(echo 'ssh' | sed s/:/-/g) \\} <addr_family> saddr @<addr_set> reject\ndone\n}"], ['actioncheck', "nft list chain inet f2b-table f2b-chain | grep -q '@<addr_set>[ \\t]'"], ['actionban', 'nft add element inet f2b-table <addr_set> \\{ <ip> \\}'], ['actionunban', 'nft delete element inet f2b-table <addr_set> \\{ <ip> \\}'], ['port', 'ssh'], ['protocol', 'tcp'], ['chain', '<known/chain>'], ['name', 'sshd'], ['actname', 'nftables'], ['table', 'f2b-table'], ['table_family', 'inet'], ['chain_type', 'filter'], ['chain_hook', 'input'], ['chain_priority', '-1'], ['addr_type', 'ipv4_addr'], ['blocktype', 'reject'], ['nftables', 'nft'], ['addr_set', 'addr-set-<name>'], ['addr_family', 'ip'], ['addr_family?family=inet6', 'ip6'], ['addr_type?family=inet6', 'ipv6_addr'], ['addr_set?family=inet6', 'addr6-set-<name>']]]
['start', 'sshd']
`
My jail.local

`[DEFAULT]
maxretry = 2

banaction = nftables
banaction_allports = nftables-allports
bantime = 96h
bantime.increment = true

ignoreip = 127.0.0.1/8

action = %(action_)s

[sshd]
enabled = true
mode = extra
`

**Comment by lejeczek** [comment]
also p.s 
SELinux related issue should be reported here?
At the time of fail2ban systemctl restart I see:
...
SELinux is preventing /usr/bin/python3.9 from watch access on the directory /run/log/journal/f939025e34f84b7799d1833fe4815c66. For complete SELinux messages run: sealert -l 42268e72-39c2-42fd-9f5a-d18944b68753
...
Which translates to:

module my-f2bfsshd 1.0;

require {
	type fail2ban_t;
	type syslogd_var_run_t;
	class dir watch;
}

#============= fail2ban_t ==============
allow fail2ban_t syslogd_var_run_t:dir watch;

I wish we had booleans for them all.
thanks, L.

**Comment by sebres** [comment]
> After certain period of time where fail2ban does not add/create new bans

Can you see when exactly it stop to find failures? So there are no `[sshd] Found` anymore. And whether it is always roughly same time.

> I'm not an expert on journald logs but I believe "logrotate" should no apply.

Yes or rather conditionally. Normal log rotation is surely not interesting here at all, but a rotation of journal inside a systemd could theoretically affect it (just then it would be a bug inside systemd API logging or monitoring journal and I didn't heard about yet).

> SELinux is preventing /usr/bin/python3.9 from watch access on the directory

I'm not a friend of selinux-policies, so not so familiar with them and cannot help you here, but the message looks very much as related.
You could try to generate a local policy module allowing the access. Or try to disable selinux temporarily to check whether it could be an issues of selinux. Just it's confusing that the watch access gets lost occasionally only.

**Comment by lejeczek** [comment]
It most likely looks is missing/absent SELinux (custom) policies - now after ~24hrs, fail2ban continues to ban successfully.
Many Internet stories on how SELinux prevented disasters, but from my own experience too I will add - cover/include SELinux as well, nobody can tell better what's needed there, than developers themselves.
thanks, L.

**Comment by sebres** [comment]
> cover/include SELinux as well, nobody can tell better what's needed there, than developers themselves.

Matter of @fail2ban/maintainers probably... 
Any idea what a distribution may include for proper coverage of SELinux basics?

**Comment by lejeczek** [comment]
Since I run off rhel based OSes I feed back all SELinux (any binary/app) related issues to those Bugzillas - and can tell that some do come with that bit attached: fail2ban-selinux, that's Fedora, some don't, as per my report here - centOS.
And for that same reason - talking in Bugzilla - can say package maintainer often call for help to app developers.
Certainly would make it lot easier for distros - and those who use SELinux will have it all very similar, certainly "enterprise" types - to provide some sort of SE base, to include some core stuff for most common critical setups.
