### ISSUE TITLE
[BR]: fail2ban-regex matching against only few lines with systemd-journal

### ISSUE THREAD

**Issue by rdbisme** [fail2ban/fail2ban#3250]
### Environment:

- Fail2Ban version Fail2Ban v0.11.2
- OS, including release name/version : Archlinux, `Linux gagazet 5.15.32-1-lts #1 SMP Mon, 28 Mar 2022 08:54:31 +0000 x86_64 GNU/Linux`
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

```
# cat /etc/fail2ban/filter.d/nginx-botsearch.local
[Definition]
journalmatch = _SYSTEMD_UNIT=nginx.service
```

### The issue:
I'm trying to investigate with the `fail2ban-regex` command how to make `nginx-botsearch` to work while nginx logging into journald. The problem is when I use the command, it just finds 17 lines, but the journal contains much more lines. 

#### Steps to reproduce
```
# fail2ban-regex -m '_SYSTEMD_UNIT=nginx.service' systemd-journal /etc/fail2ban/filter.d/nginx-botsearch.local
Running tests
=============

Use   failregex filter file : nginx-botsearch, basedir: /etc/fail2ban
Use      datepattern : {^LN-BEG}%ExY(?P<_sep>[-/.])%m(?P=_sep)%d[T ]%H:%M:%S(?:[.,]%f)?(?:\s*%z)?
^[^\[]*\[({DATE})
{^LN-BEG} : Default Detectors
Use         systemd journal
Use         encoding : UTF-8
Use    journal match : _SYSTEMD_UNIT=nginx.service


Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:

Lines: 17 lines, 0 ignored, 0 matched, 17 missed
```

While
```
# journalctl -b -u nginx | wc -l
486
```

#### Expected behavior
I would expect the processing of the entire journald lines for `nginx.service` unit

#### Observed behavior
It seems to find just 17 lines. 

#### Any customizations done to /etc/fail2ban/ configuration

```
```

#### Relevant parts of /var/log/fail2ban.log file:

```
```

#### Relevant lines from monitored log files:

```
```

**Comment by sebres** [comment]
Hmm.... Strange.
Maybe it is the user log which contain the more lines? Fail2ban in the latest versions scans only system and run-time logs (see #2444 and a possible solution in similar issue [#2696](https://github.com/fail2ban/fail2ban/issues/2696#issuecomment-615960220)

If it is not this (and you still see less entries with `[journalflags=1]`), try to find out what exactly is different with this messages, e. g. output a JSON formatted messages and compare what is different there or provide them here (one of that was found by fail2ban and one that was not found) even in JSON format.
