### ISSUE TITLE
[RFE]: disable startup and shutdown emails

### ISSUE THREAD

**Issue by oz42** [fail2ban/fail2ban#3271]
#### Feature request type
fail2ban is too noisy at startup and shutdown

#### Description
Please add a configuration parameter to disable only the emails that are generated at startup and at shutdown. I tried a workaround that I found somewhere, but it did not work.

**Comment by sebres** [comment]
Although I never understand the necessity to use mail actions at all (e. g. to notify by each ban/unban)...

Assuming you use some mail action from jail like https://github.com/fail2ban/fail2ban/blob/f81f85569d88da74d76f286b431dc54d0ae00748/config/jail.conf#L215-L216

The "correct" workaround to avoid start/stop mails would be to set `actionstart` and `actionstop` to empty value.
Either in corresponding action local file `/etc/fail2ban/action.d/sendmail-whois.local`:
```ini
[Definition]
actionstart =
actionstop =
```
or in `jail.local`:
```ini
action = %(action_mw)s[actionstart='',actionstop='']
```
