### ISSUE TITLE
[RFE]: filters for firewalld (or even just iptables) denial logging

### ISSUE THREAD

**Issue by brianjmurrell** [fail2ban/fail2ban#3277]
#### Feature request type
I'm surprised not to be able to find any filter matches for firewalld (or even raw iptables) log matches for hosts hitting closed ports.

Am I just not seeing it and it's there?

**Comment by sebres** [comment]
something like [that #1945](https://github.com/fail2ban/fail2ban/issues/1945#issuecomment-362247222) ?
