### ISSUE TITLE
Missing modules after updates 

### ISSUE THREAD

**Issue by mgaulton** [fail2ban/fail2ban#3281]
So I'm running opensuse tumbleweed, and recently the base python changed to 3.10.
I ran into a couple of issues but I haven't been able to resolve this one.
The modules were still under python3.8 site-packages so I removed the folders.
After uninstall and force reinstall of the rpm package, I get the below and I'm not sure what to try next.
Any suggestions appreciated.

server6:~ # fail2ban-client status
Traceback (most recent call last):
  File "/usr/bin/fail2ban-client", line 34, in <module>
    from fail2ban.client.fail2banclient import exec_command_line, sys
ModuleNotFoundError: No module named 'fail2ban'

**Comment by mgaulton** [comment]
So I pulled the git repo and did a manual install, then reinstall the rpm, this seems to have corrected it.
The only quirck was I had to replace all backend values with auto to get the jails to load.

**Comment by sebres** [comment]
Yes, that is the way if one does not find newer package/repository maintained by someone for the distro.
FWIW the link to our wiki about that:
https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually
