### ISSUE TITLE
[BR]: tag <matches>'s value not well formatted

### ISSUE THREAD

**Issue by wdzeng** [fail2ban/fail2ban#3293]
### Environment:

- Fail2Ban version : _0.11.2_
- OS, including release name/version : _Fedora release 35 (Thirty Five)_
- [x] Fail2Ban installed via OS/distribution mechanisms : _Yes, installed with `dnf`_
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

The value of `<matches>` tag is not well formatted for `sshd` service. The value looks like:

```
2022-06-02T19:58:46.695370example.com sshd[1571006]: Failed password for ......
```

There should be a space between timestamp and hostname, e.g.:

```
2022-06-02T19:58:46.695370 example.com sshd[1571006]: Failed password for ......
```

#### Steps to reproduce

0. Install fail2ban.

1. Create following three files. 

    ```
    # fail2ban.local
    [DEFAULT]
    loglevel = DEBUG
    ```
    
    ```
    # jail.local
    [sshd]
    enabled = true
    action = test
    ```
    
    ```
    # actions.d/test.conf
    [Definition]
    actionstart =
    actionstop =
    actioncheck =
    actionban = echo "<matches>" >&2
    actionunban =
    ```

2. Start fail2ban.

3. Wait until an IP is banned for `sshd` service.

4. View fail2ban.log and we could find that the logs contain message with improper format.

    ```
    2022-06-02 19:58:47,115 fail2ban.utils          [1570801]: DEBUG   7faaf3ed7cc0 -- stderr: '2022-06-02T19:58:44.523180example.com sshd[1571006]: ......
    ```

#### Expected behavior

There should be a space between timestamp and hostname.

#### Observed behavior

A space is missing between timestamp and hostname.

#### Any additional information

I have examined that if we modify the `getMatches` function in [_ticket.py_](https://github.com/fail2ban/fail2ban/blob/0.11.2/fail2ban/server/ticket.py#L155) at line 155:

```py
def getMatches(self):
    return [(line if not isinstance(line, (list, tuple)) else " ".join(line).strip()) \
        for line in self._data.get('matches', ())]
```

then this issue can be fixed, but I am not sure if this edit may cause new problem.

**Comment by sebres** [comment]
Looks like this missing space affects systemd backend only (jails monitoring systemd journal).
I'll fix that soon, thanks for info.
FWIW, there is another similar issue with `<matches>` tag - https://github.com/fail2ban/fail2ban/issues/3275#issuecomment-1126073999
