### ISSUE TITLE
RuntimeError: Error flushing action Jail('ssh-iptables')/iptables-SSH: 'Script error'

### ISSUE THREAD

**Issue by ericxuo** [fail2ban/fail2ban#3306]
Hi,

I'm using fail2ban-0.11.2-1.1.mga8.noarch.
Since 2 days, I get this kind of issue : 

During handling of the above exception, another exception occurred:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/fail2ban/server/jailthread.py", line 69, in run_with_except_hook
    run(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/fail2ban/server/actions.py", line 368, in run
    self.__flushBan(stop=True)
  File "/usr/lib/python3.8/site-packages/fail2ban/server/actions.py", line 666, in __flushBan
    action.consistencyCheck(_beforeRepair)
  File "/usr/lib/python3.8/site-packages/fail2ban/server/action.py", line 690, in consistencyCheck
    if started and not self._invariantCheck(family, beforeRepair):
  File "/usr/lib/python3.8/site-packages/fail2ban/server/action.py", line 916, in _invariantCheck
    if beforeRepair and not beforeRepair():
  File "/usr/lib/python3.8/site-packages/fail2ban/server/actions.py", line 663, in _beforeRepair
    self._logSys.error("Invariant check failed. Flush is impossible.")
AttributeError: 'Actions' object has no attribute '_logSys'
2022-06-15 20:58:08,865 fail2ban.utils          [406919]: ERROR   7f765569e4e0 -- exec: iptables -w -F f2b-SSH
2022-06-15 20:58:08,871 fail2ban.utils          [406919]: ERROR   7f765569e4e0 -- stderr: 'iptables: No chain/target/match by that name.'
2022-06-15 20:58:08,871 fail2ban.utils          [406919]: ERROR   7f765569e4e0 -- returned 1
2022-06-15 20:58:08,872 fail2ban.actions        [406919]: ERROR   Failed to flush bans in jail 'ssh-iptables' action 'iptables-SSH': Error flushing action Jail('ssh-iptables')/iptables-SSH: 'Script error'
2022-06-15 20:58:08,902 fail2ban.utils          [406919]: ERROR   7f765569c420 -- exec: iptables -w -n -L INPUT | grep -q 'f2b-SSH[ \t]'
2022-06-15 20:58:08,903 fail2ban.utils          [406919]: ERROR   7f765569c420 -- returned 1
2022-06-15 20:58:08,903 fail2ban                [406919]: CRITICAL Unhandled exception in Fail2Ban:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/fail2ban/server/actions.py", line 653, in __flushBan
    if action.flush():
  File "/usr/lib/python3.8/site-packages/fail2ban/server/action.py", line 637, in flush
    return self._executeOperation('<actionflush>', 'flushing', family=family, afterExec=_afterFlush)
  File "/usr/lib/python3.8/site-packages/fail2ban/server/action.py", line 476, in _executeOperation
    raise RuntimeError("Error %s action %s/%s: %r" % (operation, self._jail, self._name, err))
RuntimeError: Error flushing action Jail('ssh-iptables')/iptables-SSH: 'Script error'
```
Till now, fail2ban was working fine. I know that as I was receiving a lot of mails about banned ips. Yesterday and today I've received none.

Could you help me to solve that issue.

Regards.

Xuo.

PS : 

# systemctl status fail2ban
● fail2ban.service - Fail2Ban Service
     Loaded: loaded (/etc/systemd/system/fail2ban.service; enabled; vendor preset: disabled)
     Active: active (running) since Wed 2022-06-15 20:59:16 CEST; 28min ago
       Docs: man:fail2ban(1)
    Process: 1618 ExecStartPre=/bin/mkdir -p /run/fail2ban (code=exited, status=0/SUCCESS)
   Main PID: 1684 (fail2ban-server)
      Tasks: 29 (limit: 14223)
     Memory: 64.6M
        CPU: 3min 56.713s
     CGroup: /system.slice/fail2ban.service
             └─1684 /usr/bin/python3 -s /usr/bin/fail2ban-server -xf start

juin 15 20:59:16 ordi4 systemd[1]: Starting Fail2Ban Service...
juin 15 20:59:16 ordi4 systemd[1]: Started Fail2Ban Service.
juin 15 20:59:23 ordi4 fail2ban-server[1684]: Server ready

# iptables -L f2b-SSH                                                                            
Chain f2b-SSH (1 references)                                                                                      
target     prot opt source               destination    

                                                          
# shorewall show f2b-SSH                                                                         
Shorewall 5.2.8 Chain f2b-SSH at ordi4 - mer. 15 juin 2022 21:26:26 CEST                                          

Counters reset mer. 15 juin 2022 20:59:17 CEST                                                                    

Chain f2b-SSH (1 references)                                                                                      
 pkts bytes target     prot opt in     out     source               destination                                   

# From /etc/fail2ban/jail.local : 

[ssh-iptables]
enabled  = true
mode = aggressive
filter   = sshd
action   = iptables[name=SSH, port=ssh, protocol=tcp]
               sendmail-whois[name=SSH, dest=xuo, sender=root]
logpath  = /var/log/auth.log
maxretry = 2

**Comment by ericxuo** [comment]
Hi,

Since 2 days it seemed to be working fine. But I've got the same issue yesterday. But I've noticed something weird.
The first error occurred at 17h43  on 06/18.
**2022-06-18 17:43:13**,019 fail2ban.utils          [765564]: ERROR   7effe3d8eb70 -- exec: iptables -w -D INPUT -p tcp -m multiport --dports http,https -j f2b-SUBSONIC2

And at the same time, I've rebooted my pc : 
\# journalctl -b | more                                                               
-- Logs begin at Thu 2022-05-26 17:37:19 CEST, end at Sun 2022-06-19 18:02:01 CEST. --
**juin 18 17:44:00** ordi4 kernel: microcode: microcode updated early to revision 0x21, date = 2019-02-13

So I wonder if these error messages do not happen because of the reboot of my pc.
Next time, I'll stop the fail2ban daemon properly, reboot my pc and check the logs.

Regards.

Xuo.

**Comment by sebres** [comment]
Good news, you seem to have found a bug, e. g. copy & paste or so in https://github.com/fail2ban/fail2ban/blob/bc075ea682a3e3678ac5449cb1baeb0420655e8d/fail2ban/server/actions.py#L669
It must be:
```diff
- 							self._logSys.error("Invariant check failed. Flush is impossible.")
+ 							logSys.error("Invariant check failed. Flush is impossible.")
```
Bad news, it is just an after-effect (even just impossibility to log an error that a flush was not possible).

Initially the issue occurs by `iptables -w -F f2b-SSH` with `iptables: No chain/target/match by that name.`, that means the chain `f2b-SSH` doesn't exists (anymore).
This can happen due to several reasons:
- conflicting chains - the same chain name used by two jails due to misconfiguration (please check the dump `fail2ban-client -d | grep f2b-SSH`)
- something (bug of some service or script) flushing fail2ban's chains in iptables
- dependencies issue which causes that a shutdown of net-filter/firewall occurs before fail2ban or both teardown simultaneously

**Comment by sebres** [comment]
Fixed merged to all branches. Thus close it (note that the reason for flush impossibility is 3rd party issue).

**Comment by ericxuo** [comment]
Hi,

I confirm that the issue occurs when the server is rebooted.
And, yes, this is not a fail2ban issue but I wanted to understand the reason for these errors in the logs.

Regards.

Xuo.
