### ISSUE TITLE
[A]: cannot install with python 3.x; [Q]: do 2to3 firstly

### ISSUE THREAD

**Issue by vadimbk** [fail2ban/fail2ban#3323]
### Environment:
Ubuntu 20.04, 22.04 
fail2ban-1.0.1

- Fail2Ban version  : 
- OS, including release name/version : 
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [x ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Multiple errors during installation:
....
  File "/usr/local/lib/python3.8/dist-packages/fail2ban/tests/misctestcase.py", line 259
    print deep_function(3)
          ^
SyntaxError: invalid syntax

byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/tests/clientreadertestcase.py to clientreadertestcase.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/tests/datedetectortestcase.py to datedetectortestcase.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/tests/fail2banclienttestcase.py to fail2banclienttestcase.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/tests/servertestcase.py to servertestcase.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/tests/dummyjail.py to dummyjail.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/tests/filtertestcase.py to filtertestcase.cpython-38.pyc
  File "/usr/local/lib/python3.8/dist-packages/fail2ban/tests/filtertestcase.py", line 1778
    % m for m in 53, 54, 57, 58])
                   ^
SyntaxError: invalid syntax

byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/tests/databasetestcase.py to databasetestcase.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/tests/__init__.py to __init__.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/tests/sockettestcase.py to sockettestcase.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/tests/failmanagertestcase.py to failmanagertestcase.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/tests/banmanagertestcase.py to banmanagertestcase.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/tests/action_d/__init__.py to __init__.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/tests/action_d/test_smtp.py to test_smtp.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/tests/actionstestcase.py to actionstestcase.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/tests/tickettestcase.py to tickettestcase.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/tests/samplestestcase.py to samplestestcase.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/tests/observertestcase.py to observertestcase.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/tests/utils.py to utils.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/tests/fail2banregextestcase.py to fail2banregextestcase.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/__init__.py to __init__.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/server/datetemplate.py to datetemplate.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/server/database.py to database.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/server/ticket.py to ticket.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/server/jail.py to jail.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/server/filtersystemd.py to filtersystemd.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/fail2ban/server/ipdns.py to ipdns.cpython-38.pyc
  File "/usr/local/lib/python3.8/dist-packages/fail2ban/server/ipdns.py", line 335
    mask = ~(0xFFFFFFFFL >> cidr)
                       ^
...
and process ends without success 
SyntaxError: invalid syntax

#### Steps to reproduce
Ubuntu 20.04
python3 setup.py install

#### Expected behavior
Normal installation

#### Any additional information
Python 2 do the trick.

#### Any customizations done to /etc/fail2ban/ configuration

```
```

#### Relevant parts of /var/log/fail2ban.log file:

```
```

#### Relevant lines from monitored log files:

```
```

**Comment by sebres** [comment]
People, please read the installation documentation.

Also our [wiki :: How to install or upgrade fail2ban manually](https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually#manual-installation-from-source) says it clear:

- If you want to use `python3` execute `./fail2ban-2to3` (and then use `python3` in command below)

Also note https://github.com/fail2ban/fail2ban/issues/3206#issuecomment-1020167150, https://github.com/fail2ban/fail2ban/issues/2712#issuecomment-1028900927 (you need a clean copy if you run 2to3, so reset or clone fresh working copy or unpack downloaded version again) and other similar issues.
