### ISSUE TITLE
Reinstall Results in No Config Files[BR]: 

### ISSUE THREAD

**Issue by TheSQLGuru** [fail2ban/fail2ban#3327]
A. I am a Linux semi-noob. I am also sorry this is so long, but I work in technology as a top-tier consultant, and I counsel my clients to always seek to provide ANYTHING they think could be relevant forensics to help me find a root cause of their problem. I would provide log information, but I refer back to the first sentence in part A. :-)  

Oh, and thanks for any assistance with this!

B. As directed, I did search this Issue listing, and I found (https://github.com/fail2ban/fail2ban/issues/3118), which indicates that I can extract config files manually using a download of some form here on Github. I can probably stumble my way into getting the default set of configuration files I need placed into the requisite directories, thus actually solving this problem myself. 

However, I will continue my report in case it is some actual bug/flaw that can be addressed by the devs, which would prevent others from having this issue in the future. If it doesn't, then the only thing lost is my time putting this together and hopefully no more than a few tens of minutes of someone's time reviewing this ticket. 

C. Sequence of Actions Leading to Problem:

all actions performed after: sudo su

I am using Raspberry Pi OS with GUI, latest build as of 20220728

Fail2Ban was installed with:  
apt install fail2ban

# apt remove fail2ban
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
python3-systemd whois
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
fail2ban
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 2,142 kB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 93691 files and directories currently installed.)
Removing fail2ban (0.11.2-2) ...
Processing triggers for man-db (2.9.4-2) ...

I modified /etc/fail2ban/jail.config file directly, instead of copyiung it to jail.local first

I wanted to correct that, so I uninstalled with : 
apt remove fail2ban

I had a shell open and pwd was /etc/fail2ban when I did this action. I noticed that all files and directories for /etc/fail2ban were still in place. I thought maybe the dir tree wasn't removed as part of the uninstallation due to my "being" in that dir at the uninstall time. So I removed /etc/fail2ban with: 
rm -rdv /etc/fail2ban

This removed all files and the /etc/fail2ban dir.

#### Expected behavior 1

Either ALL files and the then-empty /etc/fail2ban dir are REMOVED by the installation, or better yet the uninstall process PROMPTS the user to ask if they want configuration information removed (i.e. they may be intending to reinstall and want to keep their current config).

#### Observed behavior 1

As explained above, files are left behind.

MY MAIN PROBLEM:

When I reinstall fail2ban, it will NOT create ANY files in /etc/fail2ban, just the empty directories. This is repeatable.

apt install fail2ban

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Suggested packages:
mailx monit sqlite3
The following NEW packages will be installed:
fail2ban
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 451 kB of archives.
After this operation, 2,142 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bullseye/main arm64 fail2ban all 0.11.2-2 [451 kB]
Fetched 451 kB in 0s (908 kB/s)
Selecting previously unselected package fail2ban.
(Reading database ... 93412 files and directories currently installed.)
Preparing to unpack .../fail2ban_0.11.2-2_all.deb ...
Unpacking fail2ban (0.11.2-2) ...
Setting up fail2ban (0.11.2-2) ...
Processing triggers for man-db (2.9.4-2) ...

#### Expected behavior 2

ls -lahF /etc/fail2ban        

should show a fully populated dir tree with (in my case) all default installation files in that tree

#### Observed behavior 2

ls -lahF /etc/fail2ban        

gets me this output, and there are zero files in the tree:

drwxr-xr-x 6 root root 4.0K Jul 31 15:58 ./
drwxr-xr-x 125 root root 12K Jul 31 15:58 ../
drwxr-xr-x 2 root root 4.0K Jul 31 15:58 action.d/
drwxr-xr-x 2 root root 4.0K Jul 11 2021 fail2ban.d/
drwxr-xr-x 3 root root 4.0K Jul 31 15:58 filter.d/
drwxr-xr-x 2 root root 4.0K Jul 31 15:58 jail.d/

#### Any additional information

As a debugging mechanism, I had another shell running during an installation, and repeatedly checked the folder the installation process in the other shell. I thought perhaps something I did may have caused files to be deleted as part of the install.

ls -lahF /etc/fail2ban

I initially received this output during the install process:

total 32K
drwxr-xr-x 6 root root 4.0K Jul 31 15:58 ./
drwxr-xr-x 125 root root 12K Jul 31 15:58 ../
drwxr-xr-x 2 root root 4.0K Jul 31 15:58 action.d/
drwxr-xr-x 2 root root 4.0K Jul 11 2021 fail2ban.d/
drwxr-xr-x 3 root root 4.0K Jul 31 15:58 filter.d/
drwxr-xr-x 2 root root 4.0K Jul 31 15:58 jail.d/

But I received ONE hit with this output. This clearly shows numerous additional items in the tree:

total 80K
drwxr-xr-x 6 root root 4.0K Jul 31 16:22 ./
drwxr-xr-x 125 root root 12K Jul 31 15:58 ../
drwxr-xr-x 2 root root 4.0K Jul 31 16:22 action.d/
-rw-r--r-- 1 root root 2.8K Nov 23 2020 fail2ban.conf.dpkg-new
drwxr-xr-x 2 root root 4.0K Jul 11 2021 fail2ban.d/
drwxr-xr-x 3 root root 4.0K Jul 31 16:22 filter.d/
-rw-r--r-- 1 root root 25K Nov 23 2020 jail.conf.dpkg-new
drwxr-xr-x 2 root root 4.0K Jul 31 16:22 jail.d/
-rw-r--r-- 1 root root 645 Nov 23 2020 paths-arch.conf.dpkg-new
-rw-r--r-- 1 root root 2.8K Nov 23 2020 paths-common.conf.dpkg-new
-rw-r--r-- 1 root root 573 Nov 23 2020 paths-debian.conf.dpkg-new
-rw-r--r-- 1 root root 738 Nov 23 2020 paths-opensuse.conf.dpkg-new

But when the install was complete, I was back to empty dir tree:

total 32K
drwxr-xr-x 6 root root 4.0K Jul 31 16:22 ./
drwxr-xr-x 125 root root 12K Jul 31 15:58 ../
drwxr-xr-x 2 root root 4.0K Jul 31 16:22 action.d/
drwxr-xr-x 2 root root 4.0K Jul 11 2021 fail2ban.d/
drwxr-xr-x 3 root root 4.0K Jul 31 16:22 filter.d/
drwxr-xr-x 2 root root 4.0K Jul 31 16:22 jail.d/

**Comment by iosifache** [comment]
Hi, @TheSQLGuru,

I reached the same issue when integrating Fail2ban in [MutableSecurity](https://github.com/MutableSecurity/mutablesecurity). The purpose there was to automate the deployment and management of Fail2ban (testing if it is properly set and functioning, changing its configuration from a single command, etc.).

Indeed, as @sebres said in #3118, it was a third-party issue, namely a misuse of the operating system's utilities 😄.

Long story short, if you run `apt remove` (without the `--purge` flag) and `apt install` afterwards, `apt` expected to find the old Fail2ban configuration in `/etc/fail2ban`. If you delete this folder, you either need to mark Fail2ban as purged (rerun `apt remove --purge fail2ban`) and reinstall as usual (`apt install fail2ban`), or follow the [official installation guide](https://github.com/fail2ban/fail2ban#installation), which implies a manual repository cloning or release download.

PS: I replicated the issue in a VM when re-checking the first solution I propose. The output is below.

<details>
<summary>Output</summary>

```
iosifache@server:/mutablesecurity$ sudo apt remove fail2ban
[...]
iosifache@server:/mutablesecurity$ ls /etc/fail2ban/
action.d  fail2ban.conf  filter.d  jail.conf  jail.d  paths-arch.conf  paths-common.conf  paths-debian.conf  paths-opensuse.conf
iosifache@server:/mutablesecurity$ sudo rm -rf /etc/fail2ban/
iosifache@server:/mutablesecurity$ sudo apt install fail2ban
[...]
iosifache@server:/mutablesecurity$ sudo fail2ban-client status
2022-08-04 08:39:36,386 fail2ban.configreader   [63231]: ERROR   Found no accessible config files for 'fail2ban' under /etc/fail2ban
2022-08-04 08:39:36,387 fail2ban.configreader   [63231]: ERROR   No section: 'Definition'
2022-08-04 08:39:36,387 fail2ban.configreader   [63231]: ERROR   No section: 'Definition'
2022-08-04 08:39:36,388 fail2ban.configreader   [63231]: ERROR   No section: 'Definition'
2022-08-04 08:39:36,388 fail2ban.configreader   [63231]: ERROR   No section: 'Definition'
2022-08-04 08:39:36,389 fail2ban.configreader   [63231]: ERROR   No section: 'Definition'
Status
|- Number of jail:      0
`- Jail list:
iosifache@server:/mutablesecurity$ sudo apt remove --purge fail2ban
[...]
iosifache@server:/mutablesecurity$ sudo apt install fail2ban
[...]
iosifache@server:/mutablesecurity$ sudo fail2ban-client status
Status
|- Number of jail:      1
`- Jail list:   sshd
```

</details>

**Comment by sebres** [comment]
Thx @iosifache for the explanation (and for saving my time to answering this;)
(as for "third-party issue" - it is also used in cases if the issue caused by something outside of this repository, e. g. like in case of this issue which is a common `apt` or `dpkg` mechanisms either and this repo doesn't really have any impact on that)

Regarding installation guide - there is [yet another one in our wiki](https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually)

Thus close.
