### ISSUE TITLE
Fail2ban stops detecting postfix-sasl auth failures

### ISSUE THREAD

**Issue by ShuaBlue** [fail2ban/fail2ban#3355]
### Discussed in https://github.com/fail2ban/fail2ban/discussions/3354

<div type='discussions-op-text'>

<sup>Originally posted by **ShuaBlue** September 16, 2022</sup>
I have been going nuts trying to figure this out. I am using CentOS 9 stream, with postfix 2:3.5.9-19.el9 and f2b 0.11.2-12.el9. 

I have both postfix and postfix-sasl jails enabled. I get attempts to login to the postfix submission port and they fail with authentication failure. F2b seems to pick up a few of them as "found" right after starting the f2b service. Then, after some time, f2b stops detecting any more failed auth attempts.

Auth login attempt that was caught by f2b:
```Sep 16 22:48:30 postfix postfix/submission/smtpd[2563]: connect from unknown[5.253.204.58]
Sep 16 22:48:44 postfix postfix/submission/smtpd[2563]: Anonymous TLS connection established from unknown[5.253.204.58]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Sep 16 22:48:47 postfix postfix/submission/smtpd[2563]: warning: unknown[5.253.204.58]: SASL LOGIN authentication failed: authentication failure
Sep 16 22:48:47 postfix postfix/submission/smtpd[2563]: disconnect from unknown[5.253.204.58] ehlo=2 starttls=1 auth=0/1 quit=1 commands=4/5
```
F2b sees this and detects it:
```2022-09-16 22:48:48,648 fail2ban.filter         [2437]: INFO    [postfix-sasl] Found 5.253.204.58 - 2022-09-16 22:48:47```

Then, some time later, another similar event is shown in postfix log:
```Sep 16 23:22:51 postfix postfix/submission/smtpd[2605]: connect from unknown[94.46.179.80]
Sep 16 23:23:05 postfix postfix/submission/smtpd[2605]: Anonymous TLS connection established from unknown[94.46.179.80]: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
Sep 16 23:23:08 postfix postfix/submission/smtpd[2605]: warning: unknown[94.46.179.80]: SASL LOGIN authentication failed: authentication failure
Sep 16 23:23:08 postfix postfix/submission/smtpd[2605]: disconnect from unknown[94.46.179.80] ehlo=2 starttls=1 auth=0/1 quit=1 commands=4/5
```

regex seems to find the offender
But nothing this time f2b does not log it and doesn't have any other info in the log file. Any subsequent auth failures are not detected from any IP. If I restart f2b service, then the IPs are detected, but eventually they stop being detected again after some time.

This is my jail status:
```Status
- Number of jail:      2
- Jail list:   postfix, postfix-sasl
```

This is the configuration for postfix-sasl:
```
[postfix-sasl]
enabled = true
findtime = 86400
bantime = 604800
maxretry = 3
filter   = postfix[mode=auth]
port     = smtp,465,submission,imap,imaps,pop3,pop3s
logpath  = %(postfix_log)s
backend  = %(postfix_backend)s
```

**Comment by sebres** [comment]
Further in #3354 (let's avoid duplicates)
