### ISSUE TITLE
[RFE]: please tag/publish a new release publish

### ISSUE THREAD

**Issue by sylvestre** [fail2ban/fail2ban#3359]
It would be nice to have a new release.
Debian will be soon in freeze mode and it has been a while since fail2ban a a new release (Nov 2020).
359 commits has been pushed since

thanks

**Comment by sebres** [comment]
Will do, just... 
There is not really resolved #3059 (#3071), but I guess many distributions have anyway already considered https://github.com/fail2ban/fail2ban/security/advisories/GHSA-m985-3f3v-cwmm and thus patched f2b by themselves.
And my opinion is unchanged here - better to be safe by default (and do some customization to get it working) as to provide a gap for a known vulni (again by default).

**Comment by sebres** [comment]
Done!
https://github.com/fail2ban/fail2ban/releases/tag/1.0.1

**Comment by sylvestre** [comment]
Many thanks :)

**Comment by sebres** [comment]
@sylvestre an ugly error (#3370) has crept into the release... what is to do here in your opinion?
- [ ] make a release with update as soon as possible
- [ ] retard updated release a bit in order to wait for some other possible errors
- [ ] do nothing (the release will get a patch built by maintainers)

**Comment by sylvestre** [comment]
@sebres make a new release asap :)
releases are cheap

**Comment by sebres** [comment]
OK, will do.

> releases are cheap

Well, how one can see they don't :) let alone the effort to made them (I don't speak about a simple tag)

**Comment by sylvestre** [comment]
Ah ah, yeah, right ;)

**Comment by sebres** [comment]
Done - https://github.com/fail2ban/fail2ban/releases/tag/1.0.2
