### ISSUE TITLE
[RFE]: Need a way for Python 3 users to install Fail2Ban without distutils

### ISSUE THREAD

**Issue by jpbion** [fail2ban/fail2ban#3361]
#### Feature request type
Fail2ban needs a documented way for Python3 users to install Fail2ban when distutils goes away in 3.12. 

#### Description
Much like it is easy to run '2to3' to install fail2ban under Python3, there needs to be a way to install fail2ban when distutils goes away in 3.12.

#### Considered alternatives
I'm not sure what alternatives there will be for non-Python programmers to install fail2ban when distutils disappears. This is a looming problem that is getting closer - and is not going away.

#### Any additional information
None that I can think of.

**Comment by sebres** [comment]
There is simply no problem at all. We will completely switch to python-3.x-based development sooner that distutils disappears, so `2to3` will be unneeded.
Alternatively there will be 2 versions (one 2.x based to support python 2.7 for some older boxes and another 3.x based).
