### ISSUE TITLE
[BR]: No module named 'ConfigParser' then python ≥ 3.9

### ISSUE THREAD

**Issue by kasumiru** [fail2ban/fail2ban#3367]
### Environment:

- Fail2Ban version  :  Fail2Ban v1.0.1, Fail2Ban v1.0.2.dev1
- OS, including release name/version : CentOS Stream release 9, VERSION="10 (buster)"
- [ ] Fail2Ban installed via OS/distribution mechanisms: python3.9 setup.py install
- [ ] You have not applied any additional foreign patches to the codebase: NO
- [ ] Some customizations were done to the configuration (provide details below is so): NO

#### Any additional information
`./fail2ban-2to3`: 
```RefactoringTool: Skipping optional fixer: buffer
RefactoringTool: Skipping optional fixer: idioms
RefactoringTool: Skipping optional fixer: set_literal
RefactoringTool: Skipping optional fixer: ws_comma
RefactoringTool: No changes to bin/fail2ban-client
Traceback (most recent call last):
  File "/bin/2to3", line 5, in <module>
    sys.exit(main("lib2to3.fixes"))
  File "/usr/lib64/python3.9/lib2to3/main.py", line 263, in main
    rt.refactor(args, options.write, options.doctests_only,
  File "/usr/lib64/python3.9/lib2to3/refactor.py", line 690, in refactor
    return super(MultiprocessRefactoringTool, self).refactor(
  File "/usr/lib64/python3.9/lib2to3/refactor.py", line 286, in refactor
    self.refactor_file(dir_or_file, write, doctests_only)
  File "/usr/lib64/python3.9/lib2to3/refactor.py", line 731, in refactor_file
    return super(MultiprocessRefactoringTool, self).refactor_file(
  File "/usr/lib64/python3.9/lib2to3/refactor.py", line 326, in refactor_file
    input, encoding = self._read_python_source(filename)
  File "/usr/lib64/python3.9/lib2to3/refactor.py", line 322, in _read_python_source
    return f.read(), encoding
  File "/usr/lib64/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd8 in position 40: invalid continuation byte
Fail!
```

**Comment by sebres** [comment]
> `2to3` ... `'utf-8' codec can't decode byte 0xd8 in position 40: invalid continuation byte`

It doesn't look like a clean copy, you seem to have already tried to start it (build/install) before 2to3?
This must be executed **as first**. Try to make a clean copy, e. g. remove `bin/fail2ban-python` from source and repeat.
See https://github.com/fail2ban/fail2ban/issues/2712#issuecomment-1028900927, https://github.com/fail2ban/fail2ban/issues/3323#issuecomment-1191871144, etc.
