### ISSUE TITLE
[RFE]: How can I use Fail2Ban in Kubernetes?

### ISSUE THREAD

**Issue by arezvani** [fail2ban/fail2ban#3371]
How can I use Fail2Ban in Kubernetes?
Are there any alternatives that can do this job?
I want to use that for my databases.

**Comment by sebres** [comment]
There is repository for docker - https://github.com/crazy-max/docker-fail2ban, may be you can use it in Kubernetes...
Also one can always install upstream fail2ban from source in a container (or on bare-metal host), everything you need is described in the [README](https://github.com/fail2ban/fail2ban/blob/master/README.md#installation) or in our [wiki](https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually#manual-installation-from-source).
