### ISSUE TITLE
Please, help - can't make it to ban http GET requests

### ISSUE THREAD

**Issue by leonpollak** [fail2ban/fail2ban#3373]
Several days of fighting.
My configuration is SME server 10 and fail2ban version 0.11.2.
I run fail2ban-regex /var/log/httpd/access_log apache-get-dos.conf :
```
Running tests
=============
Use   failregex filter file : apache-get-dos, basedir: /etc/fail2ban
Use      datepattern : {^LN-BEG} : Default Detectors
Use         log file : /var/log/httpd/access_log
Use         encoding : UTF-8

Results
=======
Failregex: 373 total
|-  #) [# of hits] regular expression
|   1) [373] <HOST> .+\"(?:GET|POST|HEAD|PUT|DELETE).+HTTP\/\d\.\d\" (?:301|302|303|304|400|401|403|404|405|500) \d+ .+$
`-
Ignoreregex: 0 total
Date template hits:
Lines: 1269 lines, 0 ignored, 373 matched, 896 missed
[processed in 0.43 sec]
Missed line(s): too many to print.  Use --print-all-missed to print all 896 lines
```
--------------
From this I understand that there should be 373 matches in the fail2ban log file, but there are none.
I am not sure about the date template - nothing in this line, is it ok?
My date pattern seems to be correct and to work, as when there was an error, I saw warnings in the log file:
datepattern = %%d/%%b/%%Y:%%H:%%M:%%S %%z

I perfectly know that this is my error, but what to do next?

Many thanks ahead for any help.

**Comment by sebres** [comment]
> there should be 373 matches in the fail2ban log file, but there are none

If I correct understand you don't see `[apache-get-dos] Found 192.0.2.1` in fail2ban.log?
If so, there are several reasons why it may not work (see the link to wiki below), for instance the entries are obsolete (exceeded `findtime` or `bantime`) or the TZ is incorrect, etc.

> My date pattern seems to be correct and to work
> `Use      datepattern : {^LN-BEG} : Default Detectors`

Well, the latest says that filter uses default datepatterns of fail2ban - you have to specify the `datepattern` either in filter, or in jail directly (and reload fail2ban).

> I perfectly know that this is my error, but what to do next?

See the first QA in FAQ in the wiki - https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works

BTW, your RE looks vulnerable to me (it is not anchored and has a catch-all), better use something like that:
```diff
- failregex = <HOST> .+\"(?:GET|POST|HEAD|PUT|DELETE).+HTTP\/\d\.\d\" (?:301|302|303|304|400|401|403|404|405|500) \d+ .+$
+ failregex = ^\s*<ADDR> [^"]*\"[A-Z]+[^"]*" (?:30[1234]|40[01345]|500)
```
(you did not provide the messages example, so I don't know which format it has, above it is for typical apache access-log)
Also note https://github.com/fail2ban/fail2ban/wiki/Best-practice#reduce-parasitic-log-traffic
