### ISSUE TITLE
What is the maximum value of bantime ?

### ISSUE THREAD

**Issue by m2acgi** [fail2ban/fail2ban#3376]
What is the maximum value of bantime ?

**Comment by sebres** [comment]
Basically it depends on used banaction (if it need that value for something, like `iptables-ipset` previously).
In case of fail2ban self it is 0X7FFFFFFFFFFF (140737488355327, what means 4461763-th year) or -1 for persistent banning.
But I would recommend not larger than something like `5w` (e. g. 5 weeks), even with `bantime.increment = true` as `bantime.maxtime = 5w`. 
What will be fully enough to ban recidive evildoers (repeating the attempt latter) as well as not to waste the system resources by large fail2ban and net-filter tables and chains (consider the lot of dynamic IPs, etc).
