### ISSUE TITLE
[RFE]: Add support for netmasks

### ISSUE THREAD

**Issue by thk686** [fail2ban/fail2ban#3377]
#### Feature request type
  A lot of bots seem to originate in a small number of domains

#### Description
  Perhaps add a netmask = XX option?

#### Considered alternatives
  It is easy to create a new action e.g. copy iptables-allports to iptables-allports-16 and add
    actionban = \<iptables\> -I f2b-\<name\> 1 -s \<ip\>/16 -j \<blocktype\>
    actionunban = \<iptables\> -D f2b-\<name\> -s \<ip\>/16 -j \<blocktype\>
to the file.

#### Any additional information
  The database will not necessarily recognize some bans as redundant unless its uses the netmask but that seems not too harmful.

**Comment by sebres** [comment]
Let us avoid duplicates. Further in #927

**Comment by thk686** [comment]
No worries. I've realized after a trial run that fail2ban is a silly idea and I really want a simple whitelist.
