### ISSUE TITLE
Update debian packages

### ISSUE THREAD

**Issue by Ludo-code** [fail2ban/fail2ban#3384]
Hello, dear team and user can you updates the package for debian ubuntu and other debian based distribution?

**Comment by sebres** [comment]
Which packages and version do you mean?
Newer debian-based distributions will get an update. For older versions it is simple either from backports, or using [pinning](https://help.ubuntu.com/community/PinningHowto) or do apt-install specific package from testing repository (after binding it with low priority):
```
apt install -t testing fail2ban
```

For everything else there are [packages released here](https://github.com/fail2ban/fail2ban/releases).
Or even installing from source.
See https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually for details how to install both variants.

**Comment by Ludo-code** [comment]
> Which packages and version do you mean?
> Newer debian-based distributions will get an update. For older versions it is simple either from backports, or using [pinning](https://help.ubuntu.com/community/PinningHowto) or do apt-install specific package from testing repository (after binding it with low priority):
> ```
> apt install -t testing fail2ban
> ```
> 
> For everything else there are [packages released here](https://github.com/fail2ban/fail2ban/releases).
> Or even installing from source.
> See https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually for details how to install both variants.

So in ubuntu 22.04 LTS, the package it's going on or I must to set backports?

**Comment by sebres** [comment]
Related to https://packages.ubuntu.com/jammy/fail2ban it is v.0.11.2-6.
It is surely not the latest version, but I don't know the exact upgrade policies of Ubuntu maintainers, so maybe only testing repository will get v.1.0.1. @fail2ban/maintainers, @sylvestre what do you think?

But again, what is your issue exactly?

**Comment by Ludo-code** [comment]
> Related to https://packages.ubuntu.com/jammy/fail2ban it is v.0.11.2-6.
> It is surely not the latest version, but I don't know the exact upgrade policies of Ubuntu maintainers, so maybe only testing repository will get v.1.0.1. @fail2ban/maintainers, @sylvestre what do you think?
> 
> But again, what is your issue exactly?

I have just wanted to know if you know when the package can be updated

**Comment by yarikoptic** [comment]
We have 1.0.1 in Debian experimental since  28 Sep 2022  thanks to @sylvestre .  If he so far is satisfied with it, he might as well upload it to unstable whenever get a chance, from there it would relatively quickly propagate into testing and then might be backported for current debian stable. Ubuntu would pick it up from unstable iirc at some point.

**Comment by Ludo-code** [comment]
Thanks you :)

**Comment by sebres** [comment]
FWIW, I owe still an update, see https://github.com/fail2ban/fail2ban/issues/3359#issuecomment-1266937294

**Comment by sylvestre** [comment]
Yeah, I have been waiting for https://github.com/fail2ban/fail2ban/issues/3359#issuecomment-1266937294 before uploading in debian unstable :)
