### ISSUE TITLE
Nginx jail for reverse proxy hosting multiple sites

### ISSUE THREAD

**Issue by Blason** [fail2ban/fail2ban#3385]
Hi Team,

I have a nginx reverse proxy is being used for for reverse proxying multiple sites behind web servers. Now the issue is - All those stanza are storing the logs in different folders. Like e.g.
web1.example.com => /var/log/nginx/web1
we2.example.com => /var/log/nginx/web2

How do I create a environment and I do not intend to use all the jails. I am writing my own jail; how do I code those?
Below is the right way?

[nginx-ips-web1]
enabled = true
port = http,https
logpath = /var/log/nginx/web1/access.log
bantime = -1
findtime = 10m
maxretry = 1

[nginx-ips-web2]
enabled = true
port = http,https
logpath = /var/log/nginx/web2/access.log
bantime = -1
findtime = 10m
maxretry = 1

**Comment by sebres** [comment]
Yes. 
I would additionally set `backend = auto` for both jails to ensure file-related backend is used (if default is systemd).
