### ISSUE TITLE
[FR]: selinux-common and selinux-ssh filters not matching anymore

### ISSUE THREAD

**Issue by droesen** [fail2ban/fail2ban#3405]
### Environment:

- Fail2Ban version  : fail2ban-1.0.1-1.el9.noarch
- OS, including release name/version : Rocky 9 (RHEL 9) fully updated

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : selinux-common & selinux-ssh
- Service, project or product name, including release name/version : OpenSSH with auditd
- Repository or URL (if known) : 
- Service type : 
- Ports and protocols the service is listening : 22

#### Log or journal information

- Log file name(s) : /var/log/audit/audit.log

#### failures in sense of fail2ban filter (fail2ban must match):

```
type=USER_AUTH msg=audit(1668381071.865:373474): pid=173582 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='op=PAM:authentication grantors=? acct="root" exe="/usr/sbin/sshd" hostname=x.x.x.x addr=192.0.2.111 terminal=ssh res=failed'^]UID="root" AUID="unset"
```

#### PROBLEM STATEMENT #########################

I'm trying to get fail2ban working on Rocky 9 via EPEL package, using the "selinux-ssh" jail. This doesn't work for two reasons.

Reason 1 is the _msg defined in filter.d/selinux-ssh.conf:

```
_msg = op=\S+ acct=(?P<_quote_acct>"?)\S+(?P=_quote_acct) exe="%(_exe)s"
hostname=(\?|(\d+\.){3}\d+) addr=<HOST> terminal=%(_terminal)s res=failed
```

This one is missing provision for the "grantors=?" which is being logged at least on RHEL8 and RHEL9 systems (and their rebuilds like Rocky, AlmaLinux etc.) as well as at least on Fedora 35. I'm finding references to the PAM grantors logging at least as far back as 2015 so this not a really new thing.

The next problem is the definition of failregex in filter.d/selinux-common.conf:

```
failregex = ^type=%(_type)s msg=audit\(:\d+\): (user )?pid=\d+ uid=%(_uid)s auid=%(_auid)s ses=\d+ subj=%(_subj)s msg='%(_msg)s'$
```

This doesn't match at all as after the _msg there is not immediately end-of-line, but additional

```
^]UID="root" AUID="unset"
```

I'm unsure wether that is a bug in auditd or so, or wether that's really supposed to be there. What I'm pretty sure is NOT correct is the special character "^]" between the msg='...' and UID="root". Anyway, removing the "$" at the end of the failregexp as a quick-and-dirty workaround makes it work. Again, I'm seeing this unexpected appendix at least on RHEL9, RHEL8 and Fedora 35 systems.

**Comment by sebres** [comment]
> I'm unsure wether that is a bug in auditd or so

Looks indeed like a bug somewhere (as if some data from previous remaining buffer, because NTS-zero is missing somewhere or a buffer overrun). Anyway it'd be better to open an issue in related repositories.

>  Anyway, removing the "$" at the end of the failregexp as a quick-and-dirty workaround makes it work

Yep, I'll take a look whether the end-anchor really needed here (some foreign input and catch-all similar circumstances before the address matching tag).

**Comment by kava005** [comment]
https://github.com/mitchellkrogza/Suspicious.Snooping.Sniffing.Hacking.IP.Addresses/issues/92.184.108.27

**Comment by sebres** [comment]
@kava005  ??
*(what should I find there?)*

**Comment by droesen** [comment]
> Looks indeed like a bug somewhere (as if some data from previous remaining buffer, because NTS-zero is missing somewhere or a buffer overrun). Anyway it'd be better to open an issue in related repositories.

Done: https://bugzilla.redhat.com/show_bug.cgi?id=2142610

**Comment by droesen** [comment]
Yes, we just found out it's intentional:

/* This is the character that separates event data from enrichment fields */
#define AUDIT_INTERP_SEPARATOR 0x1D

So it looks like the failregex indeed has to deal with it

**Comment by droesen** [comment]
https://github.com/linux-audit/audit-documentation/wiki/SPEC-Audit-Event-Enrichment

According to Steven (via bugzilla ticket) nobody is supposed to directly parse audit.log, but I guess that's what we need to do here...

**Comment by sebres** [comment]
done in 82506f0586d5e3365c74dbb3d51d2ab31bede2a0, tests are welcome

**Comment by droesen** [comment]
Seems to work fine here (tested on Rocky 9.0 box with fail2ban-1.0.1-1.el9.noarch
