### ISSUE TITLE
[BR]: None timestamp causing filtering warnings

### ISSUE THREAD

**Issue by riptusk331** [fail2ban/fail2ban#3429]
### Environment:
- Fail2Ban version: _v0.11.2_ 
- OS, including release name/version : _Ubuntu 22.04.1 LTS (Jammy)_
- System timezone: _America/New_York (EST, -0500)_
- [X] Fail2Ban installed via OS/distribution mechanisms
- [X] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)

### The issue:

I am receiving warnings from `nginx-http-auth` filter around the timezone that references a `None` timestamp and complains about a large deviation. See the `fail2ban.log` section below for an excerpt of the warning message.

I searched through previous issues on this repo, and one of the top results is [this issue page](https://github.com/fail2ban/fail2ban/issues/2882). The issue this user was experiencing though had 2 timestamps in the error message. I'm only displaying one here. I searched through the comments of that issue, and it does appear one other person had the problem ([here](https://github.com/fail2ban/fail2ban/issues/2882#issuecomment-779196555)), but they never responded to you after asking for follow up.

#### Steps to reproduce
Install & configure fail2ban as I have described here and open it up to public http/https traffic

#### Expected behavior
No warning

#### Observed behavior
Receiving a warning as described above in "The issue" section

#### Any additional information
Backend server: nginx/1.18.0 (Ubuntu)
Domains: ryanjoyce.net, riptusk.com
Using Linux UFW to block all except 80/443
Not using any kind of WAF at the moment

#### Any customizations done to /etc/fail2ban/ configuration
No changes made to fail2ban.conf
No changes made to filter files
Created a `jail.local` configuration file and made a few changes in there:
```
#### added my own IP to ignoreip
ignoreip = 127.0.0.1/8 ::1 67.86.72.158

#### enabled nginx-http-auth filter and updated log file location
[nginx-http-auth]
enabled = true
port    = http,https
logpath = /var/log/website_access.log

#### enabled nginx-bot filter and updated log file location
[nginx-botsearch]
enabled  = true
port     = http,https
logpath  = /var/log/website_access.log
maxretry = 2
```

#### Relevant parts of /var/log/fail2ban.log file:
```
**OCCURRENCE 1:**
2022-12-13 11:35:18,890 fail2ban.filter         [42054]: WARNING [nginx-http-auth] Simulate NOW in operation since found time has too large deviation None ~ 1670949318.8904867 +/- 60
2022-12-13 11:35:18,890 fail2ban.filter         [42054]: WARNING [nginx-http-auth] Please check jail has possibly a timezone issue. Line with odd timestamp: 77.247.126.152 - - [13/Dec/2022:11:35:18 -0500] "GET / HTTP/1.1" 200 122 "http://ryanjoyce.net/" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/533.4 (KHTML, like Gecko) Chrome/5.0.375.99 Safari/533.4"


**OCCURRENCE 2:**
2022-12-14 11:37:46,381 fail2ban.filter         [42054]: WARNING [nginx-http-auth] Simulate NOW in operation since found time has too large deviation None ~ 1671035866.381609 +/- 60
2022-12-14 11:37:46,382 fail2ban.filter         [42054]: WARNING [nginx-http-auth] Please check jail has possibly a timezone issue. Line with odd timestamp: 66.249.73.55 - - [14/Dec/2022:11:37:45 -0500] "GET / HTTP/1.1" 200 139 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"

```

#### Relevant lines from monitored log files:

```
**OCCURRENCE 1:**
77.247.126.152 - - [13/Dec/2022:11:35:18 -0500] "GET / HTTP/1.1" 200 122 "http://ryanjoyce.net/" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/533.4 (KHTML, like Gecko) Chrome/5.0.375.99 Safari/533.4"

**OCCURRENCE 2:**
66.249.73.55 - - [14/Dec/2022:11:37:45 -0500] "GET / HTTP/1.1" 200 139 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"

```

Thank you in advance.

**Comment by sebres** [comment]
Shortly: this timestamp format is not detected by default in fail2ban (and it is not set in filter), you have to specify custom `datepattern` for that jails:
```ini
[nginx-http-auth]
...
datepattern = ^[^\[]*\[(%%d/%%b/%%Y:%%H:%%M:%%S(?: %%z)?)\]

[nginx-botsearch]
...
datepattern = ^[^\[]*\[(%%d/%%b/%%Y:%%H:%%M:%%S(?: %%z)?)\]
```
(here additionally anchored to begin of line bypassing everything before first open square bracket `[`)

By the way, original stock `nginx-http-auth` is supposed to monitor error-log (and not access-log), so your approach to use it with access-log is doomed to fail - either you've to rewrite it (with different regex considering failed 401th response, ignoring handshake's 401th requests) or to change the logpath to the error-log.

**Comment by riptusk331** [comment]
Ah - thank you, didn't realize I needed it pointed at the error-log instead
of access-log.
