### ISSUE TITLE
[BR]: ASCII art says Fail2ban, text says Fail2Ban

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#3432]
Which one is the desired one? Fail2ban or Fail2Ban?
https://github.com/fail2ban/fail2ban/blob/master/README.md

**Comment by sebres** [comment]
> ASCII art says Fail2ban

I don't think so, it looks like lower case, so `fail2ban`.

> Which one is the desired one?

I don't put great value on the spelling (case sensitivity), cannot even say whether I prefer some notation, but mostly use it in lowercase (like a \*nix command/service), but with capitalized first later if sentence starts from fail2ban. 
What doesn't say `Fail2Ban` would be somehow wrong :)
