### ISSUE TITLE
Website/Wiki is not up-to-date

### ISSUE THREAD

**Issue by Neustradamus** [fail2ban/fail2ban#3440]
Dear @fail2ban team,

In first, I wish you a Happy New Year!

Can you update the old website/wiki?

News are very old:
- https://www.fail2ban.org/wiki/index.php/Main_Page
- https://www.fail2ban.org/wiki/index.php/News

Old links on homepage, Google+ is dead:
- https://plus.google.com/100687954024121389562
- https://plus.google.com/u/0/communities/116239755221726938303?cfem=1

Thanks in advance.

PS: Maybe there are other points too.

**Comment by sebres** [comment]
Dup of #2580. 

Persistently no time to do that.
As for more actual wiki - see https://github.com/fail2ban/fail2ban/wiki

Thus closed - let's avoid duplicates.
