### ISSUE TITLE
[FR]: Ajout de cockpit-project

### ISSUE THREAD

**Issue by Ludo-code** [fail2ban/fail2ban#3444]
Webmin étant déjà présent dans le projet, et pour les personnes utilisant sont alternative cockpit cela pourrait être sympathique d'ajouter un support pour cockpit-project...

**Comment by sebres** [comment]
Firstly note that the common language here is English. Would you perhaps, please, be so kind and use the language that everyone'll understand here.

Regarding the support of cockpit (I guess you mean the filter similar to `filter.d/webmin-auth.conf`), sure it'd be possible, but as our filter request template (that you ignored) says, we'll need more info, at least:
- Service, project or product name, including release name/version
- Repository or URL (if known)
- Ports and protocols the service is listening
- Log file name(s)
- Journal identifier or unit name (if logged in systemd-journal)

And last but not least (well the important one):
- **An excerpt from log/journal with messages of failed (and possibly successful) attempts.**

Without the info one can't do anything, thus closed unless more info provided. 
Sorry, but no arms, no cookies.

**Comment by sebres** [comment]
Also note https://github.com/cockpit-project/cockpit/issues/722 
As I can see it seems to log with pam-authenticating failures, if so then `pam-generic` will be probably your filter candidate.
