### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by mayeaux** [fail2ban/fail2ban#3448]
Jan 22 16:24:27 ns570095 fail2ban-server[18006]: Traceback (most recent call last):
Jan 22 16:24:27 ns570095 fail2ban-server[18006]:   File "/usr/bin/fail2ban-server", line 34, in <module>
Jan 22 16:24:27 ns570095 fail2ban-server[18006]:     from fail2ban.client.fail2banserver import exec_command_line, sys
Jan 22 16:24:27 ns570095 fail2ban-server[18006]:   File "/usr/lib/python3/dist-packages/fail2ban/client/fail2banserver
Jan 22 16:24:27 ns570095 fail2ban-server[18006]:     async = self._conf.get("async", False)
Jan 22 16:24:27 ns570095 fail2ban-server[18006]:           ^
Jan 22 16:24:27 ns570095 fail2ban-server[18006]: SyntaxError: invalid syntax

sudo apt-get install fail2ban

sudo service fail2ban start

**Comment by sebres** [comment]
How you installed it? Where you obtained the fail2ban from? And which version is it?
*why people continuously ignore our issue template*

As for the error - it looks like forgotten 2to3, see https://github.com/fail2ban/fail2ban/issues/3323#issuecomment-1191871144
