### ISSUE TITLE
Fail2ban slow shutdown（usage of stop_without_unban） pls？

### ISSUE THREAD

**Issue by Xingeqwd** [fail2ban/fail2ban#3451]
Hello there, i think i am almost a rookie, the fail2ban version I am using is v0.11.2.

There are nearly 10,000 banned IPs in my several jail rules, 
these caused the unban operation of fail2ban to take too long when switching on and off or even stopping or starting the process
_It will report "a stop job is running for fail2ban stop_without_unban"_

After various finding and trying, I found out that phenomenon should be caused by unbaning process of f2b for all the ip when its started and stopped
and fortunately, I saw a master mentioned this “stop_without_unban parameter” in [link](https://github.com/fail2ban/fail2ban/issues/1588), 
but unfortunately I don't know how to use it.

**I think this way of "without unban" should be better than "accelerate unban"**, After all, the former only needs to adding a parameter

In my guessing, It should not be done through systemctl, and the parameters of fail2ban-client have not been found, I thought that it may be through the modification of a certain configuration file?

So may i ask that how is “stop_without_unban” used?  or any other thinkings please?
Thanks to everyone, thank you for reading this text( or helping me else)

**Comment by Xingeqwd** [comment]
BTW, A netizen mentioned a speed-up method in another place before. on [link](https://github.com/fail2ban/fail2ban/issues/1588#issuecomment-1401675980)
I tried it, but there was no obvious speed-up effect. This should be the configuration of 2g4c, and it still takes about a minute or two.
But still here to say thanks to him!

**Comment by sebres** [comment]
I don't know what exactly did you try... anyway there is no such option `stop_without_unban`, but an action can set `actionflush` to flush all bans in one piece.
If your firewall/netfilter used in action cannot flush at all, but you don't need unban by stop of fail2ban, you can simply set this to the action:
```ini
actionflush = true
```
Alternatively for already existing action it is also possible to specify that directly in jail:
```ini
banaction = %(known/banaction)s[actionflush=true]
```
Just note that this gets active only after reload of jail(s), so do `fail2ban-client reload` before you try to stop it...
Also note that fail2ban would not distinguish between manual stop during normal operation (e. g. to do restart of fail2ban, upgrade, etc) and stop by shutdown (at the moment there is no such recognition). Thus the action must be safe against existing IP in sets/chains (e. g. if fail2ban or jails get restarted, to avoid double values or errors by next start following the stop). So better would be implement a regular flush, not to mention that it is normally very fast, e. g. for instance `actionflush` of iptables/ipset/nftables action takes few milliseconds only.

**Comment by Xingeqwd** [comment]
> I don't know what exactly did you try... anyway there is no such option `stop_without_unban`, but an action can set `actionflush` to flush all bans in one piece. If your firewall/netfilter used in action cannot flush at all, but you don't need unban by stop of fail2ban, you can simply set this to the action:
> 
> ```ini
> actionflush = true
> ```
> 
> Alternatively for already existing action it is also possible to specify that directly in jail:
> 
> ```ini
> banaction = %(known/banaction)s[actionflush=true]
> ```
> 
> Just note that this gets active only after reload of jail(s), so do `fail2ban-client reload` before you try to stop it... Also note that fail2ban would not distinguish between manual stop during normal operation (e. g. to do restart of fail2ban, upgrade, etc) and stop by shutdown (at the moment there is no such recognition). Thus the action must be safe against existing IP in sets/chains (e. g. if fail2ban or jails get restarted, to avoid double values or errors by next start following the stop). So better would be implement a regular flush, not to mention that it is normally very fast, e. g. for instance `actionflush` of iptables/ipset/nftables action takes few milliseconds only.

Oh, Thank you! it's you said this, bro

![image](https://user-images.githubusercontent.com/46107662/214283518-d3602a45-20ea-4b5e-b422-9535427dfa5e.png)
But anyway, hope this be useful to accelerate the slow phenomenon ( i would implement these measures ASAP)

Thank you very much!

**Comment by Xingeqwd** [comment]
YEAH BRO!
That's issue are ABSOLUTELY, CERTAINLY, STRAIGHTLY solved my issue, THANKS TO THIS BRO,
I just added this line in my jail config file.
And the server start(shutdown) speed ARE SOOOOOOOO FAST! only a few seconds!
