### ISSUE TITLE
[RFE]: iptables action: support inserting jump rule at specific position

### ISSUE THREAD

**Issue by calestyo** [fail2ban/fail2ban#3453]
#### Feature request type
fail2ban should support inserting the jump rule at a specific position instead of the first place in the `INPUT` chain.

#### Description
As far as I understand, fail2ban, with `iptables` as action, inserts the jump rules for a given chain always at the first position of INPUT:
https://github.com/fail2ban/fail2ban/blob/f93a538693f25c5e735cf88a0f2fc942b943d18b/config/action.d/iptables.conf#L71

Now for many setups this will be just fine, but I always wanted the rule to be added at a specific position in order not to possibly mess around with other rules in more complex setups.<br>
Also, it allows for things like an `ESTABLISHED` rule to keep connections open, even if fail2ban may block it already (e.g. when one did some testing and accidentally locked oneself).

For years I did something like replacing the respective defaults of the following in `iptables-multiport.conf` with:
```
actionstart = <iptables> -N f2b-<name>
              <iptables> -A f2b-<name> -j <returntype>
              rulenum="$( <iptables> -L <chain> --line-numbers  |  grep '/\* f2b-hook-<name> \*/'  |  cut -d ' ' -f 1 )"
              <iptables> -R <chain> "${rulenum}" -p <protocol> -m multiport --dports <port> -j f2b-<name>
```
and
```
actionstop = rulenum="$( <iptables> -L <chain> --line-numbers  |  grep f2b-<name>  |  cut -d ' ' -f 1 )"
             <iptables> -R <chain> "${rulenum}" --in-interface lo -m comment --comment f2b-hook-<name>
```

The idea is, that my static iptables rules loaded by the distro have a dummy hook like:
```
-A INPUT --in-interface lo  -m comment --comment "f2b-hook-sshd"
```
at the position where I want the jump rule to be.

With the new fail2ban version (1.x) this got a bit more complicated, especially these:
https://github.com/fail2ban/fail2ban/blob/f93a538693f25c5e735cf88a0f2fc942b943d18b/config/action.d/iptables.conf#L70-L84
I don't fully understand how they're intended to be used.

Anyway... it would be nice if something like this could be supported out of the box, or at least with a simple config switch.

Perhaps instead of replacing, as I did previously and as shown above, it would be enough if one just inserts the rules at the position of the dummy-hook-rule.<br>
Should also be less fragile against possible races and simplify that iteration you do over multiple protos.

Thanks,
Chris.

**Comment by calestyo** [comment]
FYI:
Right now I simply do this in `fail2ban/config/action.d/iptables.conf`:
```
_ipt_add_rules = <_ipt_for_proto-iter>
              { %(_ipt_check_rule)s >/dev/null 2>&1; } || { n="$( <iptables> -L <chain> --line-numbers | grep '/\* f2b-hook-<name> \*/$' | cut -d ' ' -f 1 )"; n="$(( ${n}+1 ))"; { [ -n "${n##*[!0-9]*}" ] && [ -n "${n##0[0-9]*}" ]; } && <iptables> -I <chain> "${n}" %(_ipt_chain_rule)s; }
              <_ipt_for_proto-done>
```

The checks `{ [ -n "${n##*[!0-9]*}" ] && [ -n "${n##0[0-9]*}" ]; }` make sure that it's only positive natural numbers.

**Comment by sebres** [comment]
> I always wanted the rule to be added at a specific position in order not to possibly mess around with other rules in more complex setups.

Why?
If you anyway modify iptables rules, why just not insert new chain (e. g. `F2B`) to the `INPUT` at expected position, and switch action's parameter `chain` from `INPUT` to `F2B`? 
For instance (in jail.local):
```ini
[DEFAULT]
chain = F2B
```
Then the picture of rules would look like that:
<details><summary><code>iptables -nL</code> example (mostly `iptables-ipset` action) ...</summary>

```bash
Chain INPUT (policy DROP)
target              prot opt source        destination
My_Trusted          all  --  0.0.0.0/0     0.0.0.0/0
Custom_Before_Rule2 ...
...
Custom_Before_RuleN ...
F2B                 all  --  0.0.0.0/0     0.0.0.0/0
Custom_After_Rule1  ...
...
Custom_After_RuleN  ...

Chain FORWARD (policy DROP)
target              prot opt source        destination
...

Chain OUTPUT (policy DROP)
target              prot opt source        destination
...

Chain My_Trusted (1 references)
target              prot opt source        destination
ACCEPT              all  --  192.0.2.0/24  0.0.0.0/0

Chain F2B (1 references)
REJECT              tcp  --  0.0.0.0/0     0.0.0.0/0  multiport dports 80,443 match-set f2b-nginx src reject-with icmp-port-unreachable
REJECT              all  --  0.0.0.0/0     0.0.0.0/0  match-set f2b-pam-generic src reject-with icmp-port-unreachable
REJECT              tcp  --  0.0.0.0/0     0.0.0.0/0  multiport dports 22 match-set f2b-sshd src reject-with icmp-port-unreachable
DROP                all  --  0.0.0.0/0     0.0.0.0/0  match-set f2b-drop-evil
...
```
</details>
Reference to chain `F2B` (created by you) takes place in the middle of `INPUT` chain, exactly where you'd need to place it.
Rules created in the chain `F2B` (created by fail2ban) listed at end of example in chain `F2B`.

The same approach is possible for `FORWARD` or whatever chain you'd still need to adjust,

It is the solely correct way to go, in my opinion. Simply, safe, no hacks and fewer error-prone.

**Comment by calestyo** [comment]
But doesn't that mean that F2B would add all of it's jump rules to `F2B`?

That costs one quite some flexibility, as in my schema you can place them per jail type.

It's also a matter of performance. I've had systems where f2b had some thousands of blocked entries for a certain jail type.

Typically one wants those packets that are to be accepted being done so before such long f2b chains, because these really cause a huge impact on the load of the kernel.

So if one has e.g. jail-A with typically few entries and jail-B with loads of... one may want to have them in different places.

**Comment by sebres** [comment]
> But doesn't that mean that F2B would add all of it's jump rules to F2B?

No. What you see in `F2B` chain above are all the `ipset` matching rules (it's single entry per jail and the IPs are in sets of `ipset`).
Without ipset (e. g. `iptables-multiport` or `iptables-allports`) you'd get still one chain `f2b-*` per jail and a new rule in `F2B` for port/proto/etc and all the IPs matching rules going into corresponding chain `f2b-*`.

> That costs one quite some flexibility, as in my schema you can place them per jail type.

I don't see why it may be needed by jail type, but...
what is the problem to define multiple chains (http, mail, terminal, etc) and then add `chain = whatever` to corresponding jail to place it's chain reference to proper place?

I'd not call the approach finding some position with grep by comment as flexible. The issue with such a "flexibility" - mostly it is a mess at end, additionally error-prone and timing- or race-condition fragile. Let alone fail2ban actions initialize on demand by first ban, so may appear in different order.

> It's also a matter of performance.

I don't see how a positioning by offset compared to positioning by name would help to speed up it?

> Typically one wants those packets that are to be accepted being done so before such long f2b chains

And where it is a problem with named chains like `F2B` between all other rules?

> So if one has e.g. jail-A with typically few entries and jail-B with loads of... one may want to have them in different places.

Why? 
If everything in the matching rule to target the chains is equal, e. g. both have the same ports, protocol, etc pp, the IP must pass jail-A and jail-B chains to be accepted, no matter which order they have. I don't follow this argument at all.
Also you can reduce load and increase performance if you'd switch to `iptables-ipset` (or to `nft`) actions. Using one of them, it is almost to neglect how large the sets become.

**Comment by calestyo** [comment]
Ah, so I can set `chain` per jail?!

And as far as I understood you, the idea would be to:
- create e.g. a `F2B-jump-ssh` in my iptables rules
- also set up my own jump rules into that (`F2B-jump-ssh`), just at the position where I want it to be (and where I'd have right now the comment rule serving as hook
- set `chain` of the (e.g.) `ssh` jail to `F2B-jump-ssh`

Having only 1 `F2B-jump` queue for all, works of course also, but would again defeat the purpose of being able to exactly select (per jail) where the rules shall be inserted.

Now `fail2ban` would create (with `iptables-multiport`) a single jump rule for `-p tcp` and `multiport dports ssh` into the actual chain that contains the ban rules e.g. `f2b-sshd`.

Right?

Well, I guess that would work... but TBH it feels a bit messy:
- For each (actual= `f2b-<jail>` chain, where I want the jump to happen at another position, I'd need a corresponding jump-chain, which (at least in the case of `iptables-multiport` and if only one protocol is used) would always only contain 1 rule. It's effectively just one (unnecessary) further jump, which also makes the output of `iptables -L` more messy.
- These jump chains, would always exist and I'd need to set them up in such a way, that they're always processed (even if empty). My way with the comment rule creates however a rule that is ignored by netfilter. It does nothing but serving fail2ban as the hint where to insert the rules.

> I'd not call the approach finding some position with grep by comment as flexible.

Why? I can select for each jail with a simple comment rule, where fail2ban should add any further rules for this.<br>
And since `grep` is only invoked once per added (jump) rule (not per ban rules) this shouldn't be too costly in terms of performance.<br>
The only real problem where it could break is if iptables output changes.

> The issue with such a "flexibility" - mostly it is a mess at end, additionally error-prone and timing- or race-condition fragile. Let alone fail2ban actions initialize on demand by first ban, so may appear in different order.

Hmm that's indeed a point, I mean I don't think it's a mess (contrary), but with fail2ban running, it's indeed be prone to races. :-/

Guess the only safe way is then indeed using such an intermediate chain. Thus closing.

Thanks for your insight :-)

**Comment by calestyo** [comment]
Maybe you might want to add as a hint somewhere, that `__name__` can be used to get a section’s name.

With that I was able to set on global:
```
[DEFAULT]
chain = f2b-jump-%(__name__)s
```
Which (AFAIU) would then work out of the box for any jails. So e.g. it would place the actual jump rules for ssh into a chain `f2b-jump-sshd`.
