### ISSUE TITLE
Custom NGINX Log Format

### ISSUE THREAD

**Issue by elionth** [fail2ban/fail2ban#3456]
I would appreciate any help from someone more experienced with Fail2Ban.

I have changed NGINX log formatting to include more details per visitor (see example below). However, I have noticed that Fail2Ban does not ban anything anymore. Can anyone include a filter example to ban bad visitors please.

New NGINX Log Fortmatting:
```
{"remote_addr": "123.45.678.9", "msec": "1676144413.308", "connection": "394489", "connection_requests": "1", "pid": "1737", "request_id": "c629dd11793730ea69ee8e8bb22630dd", "request_length": "262", "remote_user": "", "remote_port": "49634", "time_local": "11/Feb/2023:11:40:13 -0800", "time_iso8601": "2023-02-11T11:40:13-08:00", "request": "GET /wp-admin.php HTTP/2.0", "request_uri": "/wp-admin.php", "args": "", "status": "404", "body_bytes_sent": "153", "bytes_sent": "233", "http_referer": "", "http_user_agent": "Mozilla/5.0 (Android 12; Mobile; rv:109.0) Gecko/109.0 Firefox/109.0", "http_x_forwarded_for": "", "http_host": “domain.com”, "server_name": “domain.com”, "request_time": "0.000", "upstream": "", "upstream_connect_time": "", "upstream_header_time": "", "upstream_response_time": "", "upstream_response_length": "", "upstream_cache_status": "", "ssl_protocol": "TLSv1.2", "ssl_cipher": "XXXX-XXX-XXXXXXx-xXxxXX", "scheme": "https", "request_method": "GET", "server_protocol": "HTTP/2.0", "pipe": ".", "gzip_ratio": "", "http_cf_ray": "","geoip_city": "Seattle","geoip_country_name": "USA","geoip_country_code": "US"}
```

OLD Wordpress Filter:
```ini
[Definition]
failregex = ^<HOST> .* "(GET|POST|HEAD) /(wp-login\.php|xmlrpc\.php)
```

Thank you

**Comment by elionth** [comment]
Looks like it is about the order of information in the log and regex as explained [here](https://stackoverflow.com/questions/41447414/fail2ban-scan-for-403-in-nginx-access-logs)


Anyone familiar with Regex that can assist in making this version of log format work or any another suggestions?

**Comment by sebres** [comment]
Well, this is artificial JSON... fail2ban is not yet suitable to parse JSON directly (see RFE #2932).

One can surely construct something like that:
```ini
# datepattern = "time_iso8601":\s*"%%Y%%m%%dT%%H:%%M:%%S(?:%%z)?",\s*
datepattern = "msec":\s*"{EPOCH}",\s*

_groupre = (?:"(?!(?:remote_addr|request_uri|status)\b)\w+"\s*:\s*(?:"[^"]*"|\w+)\s*[,\}]\s*)

_uri=[^"]+
_code=[45]0\d+

failregex = ^\{%(_groupre)s*"remote_addr"\s*:\s*"<ADDR>",\s*%(_groupre)s*"request_uri"\s*:\s*"%(_uri)s",\s*%(_groupre)s*"status"\s*:\s*"%(_code)s"

```
Adjust parameters `_code` and `_uri` if you'd restrict it more specifically, e. g. something like:
`_uri = /(?:wp-(?:login|admin)|xmlrpc)\b[^"]*`

But parsing of JSON with regex is so lala idea.

Anyway if you're able to rewrite the format (e. g. reorder the tokens) I'd place `msec`, `remote_addr`, `request_uri` and `status` at begin of JSON structure.
