### ISSUE TITLE
[BR]: 0 Jails, no SQLite3 database - 'out of the box' on Debian 11 (Bullseye) w/ Python 3.7–3.10

### ISSUE THREAD

**Issue by dinocovelli-paramount** [fail2ban/fail2ban#3457]
### Environment:
- Fail2Ban version : 0.11.2 (python3.9)
- OS, including release name/version : Debian GNU/Linux 11 (bullseye), 5.10.0-21-amd64
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
I installed fail2ban from apt and had this issue, then found the instructions here and followed them to install it manually:
https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually
The issue still occurs; snippet of commands and errors here:

 $ `systemctl enable fail2ban`
```
Created symlink /etc/systemd/system/multi-user.target.wants/fail2ban.service → /etc/systemd/system/fail2ban.service.
 $ `systemctl status fail2ban`
● fail2ban.service - Fail2Ban Service
     Loaded: loaded (/etc/systemd/system/fail2ban.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2023-02-11 17:39:58 EST; 6min ago
       Docs: man:fail2ban(1)
   Main PID: 3178016 (code=exited, status=255/EXCEPTION)
        CPU: 72ms

Feb 11 17:39:58 <host> systemd[1]: Starting Fail2Ban Service...
Feb 11 17:39:58 <host> systemd[1]: Started Fail2Ban Service.
Feb 11 17:39:58 <host> fail2ban-server[3178016]: 2023-02-11 17:39:58,284 fail2ban                [3178016]: ERROR   'Fail2banClient' object has no attribute '_set_server'
Feb 11 17:39:58 <host> systemd[1]: fail2ban.service: Main process exited, code=exited, status=255/EXCEPTION
Feb 11 17:39:58 <host> systemd[1]: fail2ban.service: Failed with result 'exit-code'.
```

 $ `fail2ban-client start`
```
2023-02-11 17:47:08,467 fail2ban.configreader   [3183773]: WARNING 'allowipv6' not defined in 'Definition'. Using default one: 'auto'
2023-02-11 17:47:08,560 fail2ban                [3183773]: ERROR   NOK: ("Invalid command 'auto' (no set action or not yet implemented)",)
Server ready
```

The SQLite3 database was not created:
 $ `ls /var/lib/fail2ban`

#### Steps to reproduce
`wget --no-check-certificate https://github.com/fail2ban/fail2ban/archive/0.11.2.tar.gz -O ./fail2ban_0.11.2.tar.gz`
`tar -zxf fail2ban_0.11.2.tar.gz`
`cd ./fail2ban-0.11.2`
`./fail2ban-2to3`
`python3 setup.py install --without-tests`
`cp ./build/fail2ban.service /etc/systemd/system/fail2ban.service`
`systemctl enable fail2ban`

#### Expected behavior
 $ `systemctl status fail2ban`
```
Active: active (running)
```

 $ `fail2ban-client status`
```
Status
|- Number of jail:  1
`- Jail list:  sshd
```

#### Observed behavior
 $ `systemctl status fail2ban`
```
Active: failed
```

The default Debian build has an sshd jail configured, so the number of jails should be 1 but it's 0:
 $ `fail2ban-client status`
```
Status
|- Number of jail:  0
`- Jail list:  
```

#### Any additional information
I installed python3.7 and python3.10 and symlinked each to **/usr/local/bin/fail2ban-python** to test other versions of python, neither made a difference.

### Configuration, dump and another helpful excerpts
I recreated this with the default configuration for ease of troubleshooting.

#### Any customizations done to /etc/fail2ban/ configuration
No.

For troubleshooting, I imported a **jail.local** file from another system that has multiple jails enabled, but this error persisted. The **fail2ban.log** showed the jails loading and the server starting, but **fail2ban-client status** still  showed number of jails at 0, and there still was no SQLite3 database created.

For this issue:
```
'allowipv6' not defined in 'Definition'
```
I created a **fail2ban.local** file, added `[Definition]` and under it: `allowipv6 = no` but that error persisted. I also tried the other suggested values like `false` but nothing changed.

#### Relevant parts of /var/log/fail2ban.log file:
```
2023-02-11 17:47:08,544 fail2ban.server         [3183776]: INFO    --------------------------------------------------
2023-02-11 17:47:08,544 fail2ban.server         [3183776]: INFO    Starting Fail2ban v1.0.2
2023-02-11 17:47:08,544 fail2ban.server         [3183776]: INFO    Daemon started
2023-02-11 17:47:08,545 fail2ban.observer       [3183776]: INFO    Observer start...
2023-02-11 17:47:08,559 fail2ban.transmitter    [3183776]: WARNING Command ['server-stream', [['set', 'syslogsocket', 'auto'], ['set', 'loglevel', 'INFO'], ['set', 'logtarget', '/var/log/fail2ban.log'], ['set', 'allowipv6', 'auto'], ['set', 'dbfile', '/var/lib/fail2ban/fail2ban.SQLite33'], ['set', 'dbmaxmatches', 10], ['set', 'dbpurgeage', '1d']]] has failed. Received Exception("Invalid command 'auto' (no set action or not yet implemented)")
```

#### Relevant lines from monitored log files:
No other relevant logs.

**Comment by sebres** [comment]
Hmm... there is something strange. I don't see what can cause that error.
1. can you provide output of `fail2ban-client --dp`
2. try to set loglevel to heavydebug (or start fail2ban-server in foreground like below) and see whether the log additionally contains some call stack after error:
```bash
fail2ban-server --loglevel 10 --logtarget=STDOUT -f
```

**Comment by dinocovelli-paramount** [comment]
$ `fail2ban-client --dp`
```
2023-02-12 12:19:48,281 fail2ban.configreader   [1404568]: WARNING 'allowipv6' not defined in 'Definition'. Using default one: 'auto'
['set', 'syslogsocket', 'auto']
['set', 'loglevel', 'INFO']
['set', 'logtarget', '/var/log/fail2ban.log']
['set', 'allowipv6', 'auto']
['set', 'dbfile', '/var/lib/fail2ban/fail2ban.sqlite3']
['set', 'dbmaxmatches', 10]
['set', 'dbpurgeage', '1d']'
```

 $ `fail2ban-server --loglevel 10 --logtarget=STDOUT -f`
 ```
 2023-02-12 12:23:53,221 fail2ban                [1408182]: ERROR   'Fail2banClient' object has no attribute '_set_server'
 ```

 $ `tail /var/log/fail2ban.log`
 ```
 2023-02-11 19:09:37,634 fail2ban.server         [3233629]: INFO    --------------------------------------------------
2023-02-11 19:09:37,634 fail2ban.server         [3233629]: INFO    Starting Fail2ban v1.0.2
2023-02-11 19:09:37,635 fail2ban.server         [3233629]: INFO    Daemon started
2023-02-11 19:09:37,635 fail2ban.observer       [3233629]: INFO    Observer start...
2023-02-11 19:09:37,651 fail2ban.transmitter    [3233629]: WARNING Command ['server-stream', [['set', 'syslogsocket', 'auto'], ['set', 'loglevel', 'INFO'], ['set', 'logtarget', '/var/log/fail2ban.log'], ['set', 'allowipv6', 'auto'], ['set', 'dbfile', '/var/lib/fail2ban/fail2ban.sqlite3'], ['set', 'dbmaxmatches', 10], ['set', 'dbpurgeage', '1d']]] has failed. Received Exception("Invalid command 'auto' (no set action or not yet implemented)")
2023-02-11 19:09:52,189 fail2ban.server         [3233629]: INFO    Shutdown in progress...
2023-02-11 19:09:52,189 fail2ban.observer       [3233629]: INFO    Observer stop ... try to end queue 5 seconds
2023-02-11 19:09:52,210 fail2ban.observer       [3233629]: INFO    Observer stopped, 0 events remaining.
2023-02-11 19:09:52,250 fail2ban.server         [3233629]: INFO    Stopping all jails
2023-02-11 19:09:52,250 fail2ban.server         [3233629]: INFO    Exiting Fail2ban
 ```
Is it normal that I installed v0.11 and fail2ban-client is reporting v1.0.2?

**Comment by sebres** [comment]
> 'Fail2banClient' object has no attribute '_set_server'

Strange.
Class `Fail2banClient` must have `_set_server`, no matter 0.11.x or 1.0.x version.
https://github.com/fail2ban/fail2ban/blob/2df58c5281facd73e73778a734a90f7d4fe95468/fail2ban/client/fail2banclient.py#L178

What exactly did you install and for which version of python?
```
fail2ban-python --version
fail2ban-python -c 'from fail2ban.version import version; print(version)''
fail2ban-server --version
```

It is probably just a versions mismatch (several version installed differently, some old client/server links in path).
What do you see with `whereis fail2ban-server`?

> Is it normal that I installed v0.11 and fail2ban-client is reporting v1.0.2?

No. It must report the version you've installed.

**Comment by sebres** [comment]
> I created a fail2ban.local file, added [Definition] and under it: allowipv6 = no but that error persisted. 

It is not an error but warning...

Anyway, the file `/etc/fail2ban/fail2ban.local` contains:
```ini
[Definition]
allowipv6 = no
```
and you still see the warning?

**Comment by dinocovelli-paramount** [comment]
> What exactly did you install and for which version of python?

That info is in "Steps to reproduce"- the only extra bit is that Python 3.9 is what's installed on my system. Python 3.9 the only Python version currently available through the default apt repo in Debian 11. 

I did suspect the issue might be related to Python versioning, so I also tried making a symlink from `fail2ban-python` to Python 3.7 and 3.10 that I manually installed strictly for troubleshooting this issue.

Other details:
 $ `fail2ban-python --version`
```
Python 3.10.9
```

 $ `fail2ban-python -c 'from fail2ban.version import version; print(version)'`
 ```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'fail2ban'
```

 $ `fail2ban-server --version`
 ```
 Fail2Ban v1.0.2
 ```

 $ `whereis fail2ban-server`
```
fail2ban-server: /usr/local/bin/fail2ban-server
```

And a little more:
$ `fail2ban-client start`
```
2023-02-12 17:56:30,768 fail2ban                [137246]: ERROR   NOK: ("Invalid command 'no' (no set action or not yet implemented)",)
Server ready
```

$ `tail /var/log/fail2ban.log`
```
2023-02-12 17:56:30,753 fail2ban.server         [137249]: INFO    --------------------------------------------------
2023-02-12 17:56:30,754 fail2ban.server         [137249]: INFO    Starting Fail2ban v1.0.2
2023-02-12 17:56:30,754 fail2ban.server         [137249]: INFO    Daemon started
2023-02-12 17:56:30,755 fail2ban.observer       [137249]: INFO    Observer start...
2023-02-12 17:56:30,768 fail2ban.transmitter    [137249]: WARNING Command ['server-stream', [['set', 'syslogsocket', 'auto'], ['set', 'loglevel', 'INFO'], ['set', 'logtarget', '/var/log/fail2ban.log'], ['set', 'allowipv6', 'no'], ['set', 'dbfile', '/var/lib/fail2ban/fail2ban.sqlite3'], ['set', 'dbmaxmatches', 10], ['set', 'dbpurgeage', '1d']]] has failed. Received Exception("Invalid command 'no' (no set action or not yet implemented)")
```

**Comment by dinocovelli-paramount** [comment]
> Anyway, the file `/etc/fail2ban/fail2ban.local` contains:
> 
> ```ini
> [Definition]
> allowipv6 = no
> ```
> 
> and you still see the warning?

I added the 'allowipv6' declaration to `/etc/fail2ban/fail2ban.local` and it got rid of that error. I must have been putting that in the wrong place? Thank you!

**Comment by sebres** [comment]
> so I also tried making a symlink from fail2ban-python to Python 3.7 and then 3.10 which I manually installed

it doesn't work this way, you have to install the fail2ban module to the corresponding version (or symlink it also).

> fail2ban-client start
2023-02-12 17:56:30,768 fail2ban                [137246]: ERROR   NOK: ("Invalid command 'no' (no set action or not yet implemented)",)
Server ready

Still more and more strange.
So you were able to start it using client, but not with server directly in foreground?.. weird.
As for the error, I'll try to find the possible reasons for that, but it's totally unclear.

**Comment by dinocovelli-paramount** [comment]
> it doesn't work this way, you have to install the fail2ban module to the corresponding version (or symlink it also).

Understood, so it's worth mentioning that python3.7 seems to be incompatible with Debian 11 (installing it on Debian 11 removed some critical modules that made the system unstable). 

I tried to install the fail2ban module using python3.10 but it complains about 2to3 being invalid:

 $ `/usr/local/bin/python3.10 setup.py install`
```
error in fail2ban setup command: use_2to3 is invalid.
```

**Comment by sebres** [comment]
Although I can imagine a sole reason now where it may happen.
If your current directory is something containing fail2ban module (like the root directory of installation zip).

For instance:
```bash
~/prj$ python3 -c 'from fail2ban.version import version; print(version)'
1.0.2-1~upstream1
~/prj$ cd fail2ban
~/prj/fail2ban$ python3 -c 'from fail2ban.version import version; print(version)'
1.0.3.dev1
```
so if one would start fail2ban-server or fail2ban-client, it strictly depends from which current directory one does it (whether current directory would also contain fail2ban module, no matter installed or not).

The reason for that is strange decision of python's people preferring current directory in modules path:
```python
$ python3 -c 'import sys; print("\n".join(map(repr, sys.path)))'
''                              <--- this weird one means current dir ---
'/usr/lib/python39.zip'
'/usr/lib/python3.9'
...
'/usr/lib/python3/dist-packages'
```
Very questionable decision ever, and basically a reason of many confusions and disasters... so many of us [are unhappy](https://discuss.python.org/t/python-flag-envvar-to-not-put-current-directory-on-sys-path-but-dont-ignore-pythonpath/4235) with that situation.
There is even a [CVE for that](https://bugs.python.org/issue5753) etc.

**Comment by dinocovelli-paramount** [comment]
> Very questionable decision ever, and basically a reason of many confusions and disasters... so many of us [are unhappy](https://discuss.python.org/t/python-flag-envvar-to-not-put-current-directory-on-sys-path-but-dont-ignore-pythonpath/4235) with that situation.
> There is even a [CVE for that](https://bugs.python.org/issue5753) etc.

Oof! 

OK, I've got bad news and good news to report. You were correct, it seems as though v1.0.2 was installed on our system at some point. So I ran this command which seemed to remove all versions:
```
rm -rf /etc/fail2ban \
  /etc/init.d/fail2ban \
  /usr/share/fail2ban \
  /usr/bin/fail2ban* \
  /usr/local/bin/fail2ban* \
  /usr/local/lib/python3.*/dist-packages/fail2ban*
```
### Bad News with v.1.0.2
I tried a fresh install of v1.0.2 with python3.9. I'm not looking to troubleshoot this but I will share the outcome below:
```
 $ cp ./build/fail2ban.service /etc/systemd/system/fail2ban.service

 $ systemctl enable fail2ban
Created symlink /etc/systemd/system/multi-user.target.wants/fail2ban.service → /etc/systemd/system/fail2ban.service.

 $ systemctl status fail2ban
● fail2ban.service - Fail2Ban Service
     Loaded: loaded (/etc/systemd/system/fail2ban.service; enabled; vendor preset: enabled)
     Active: inactive (dead)
       Docs: man:fail2ban(1)

 $ systemctl start fail2ban

 $ systemctl status fail2ban
● fail2ban.service - Fail2Ban Service
     Loaded: loaded (/etc/systemd/system/fail2ban.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2023-02-13 10:00:29 EST; 2s ago
       Docs: man:fail2ban(1)
    Process: 906501 ExecStartPre=/bin/mkdir -p /run/fail2ban (code=exited, status=0/SUCCESS)
    Process: 906502 ExecStart=/usr/local/bin/fail2ban-server -xf start (code=exited, status=255/EXCEPTION)
   Main PID: 906502 (code=exited, status=255/EXCEPTION)
        CPU: 64ms

Feb 13 10:00:29 ca2uceus systemd[1]: Starting Fail2Ban Service...
Feb 13 10:00:29 ca2uceus systemd[1]: Started Fail2Ban Service.
Feb 13 10:00:29 ca2uceus fail2ban-server[906502]: ERROR: No module named 'ConfigParser'
Feb 13 10:00:29 ca2uceus systemd[1]: fail2ban.service: Main process exited, code=exited, status=255/EXCEPTION
Feb 13 10:00:29 ca2uceus systemd[1]: fail2ban.service: Failed with result 'exit-code'.

 $ fail2ban-client -d
Traceback (most recent call last):
  File "/usr/local/bin/fail2ban-client", line 34, in <module>
    from fail2ban.client.fail2banclient import exec_command_line, sys
  File "/usr/local/lib/python3.9/dist-packages/fail2ban/client/fail2banclient.py", line 39, in <module>
    from ..server.utils import Utils
  File "/usr/local/lib/python3.9/dist-packages/fail2ban/server/utils.py", line 56, in <module>
    for name, num in signal.__dict__.iteritems() if name.startswith("SIG"))
AttributeError: 'dict' object has no attribute 'iteritems'
```
I gave up troubleshooting at this stage and completely removed v1.0.2.
### Good News with v0.11.2
With all references to v1.0.2 gone, a fresh install of v0.11.2 is now running happily.

Thank you!

**Comment by sebres** [comment]
> Bad News with v.1.0.2
> No module named 'ConfigParser'
> AttributeError: 'dict' object has no attribute 'iteritems'

Nope. 
This is again some issue on your side. I guess missing 2to3, because neither `ConfigParser` nor `dict.iteritems` is available for python3 (2to3 would have rewritten them). Just I wonder how it got then installed at all.

**Comment by dinocovelli-paramount** [comment]
> 2to3 would have rewritten them

I forgot to include that information but `2to3` gave an error and was unable to run. I wasn't sure if that was necessary to use with 1.0.2. 

Is it worth recreating? It sounds like a weird edge case. I'm happy to stick with a functioning 0.11.2.
