### ISSUE TITLE
[FR]: MikroTik RouterOS login failure

### ISSUE THREAD

**Issue by vitkabele** [fail2ban/fail2ban#3458]
Add filter for MikroTik RouterOS logs, detecting login failures.

The MikroTik RouterOS enables sending logs to a remote syslog server, where the analysis can be performed by fail2ban.

Entries like:
```
Feb 15 11:29:03 gw.local system,error,critical login failure for user admin from 192.168.33.2 via web
Feb 15 11:57:42 gw.local system,error,critical login failure for user  from 2001:470:1:c84::24 via ssh
```

(Note the empty username in the second row.)

**Comment by sebres** [comment]
Possibly either:
```ini
failregex = ^\s*gw\.\S+ system,error,critical login failure for user<F-USER>.*?</F-USER> from <ADDR> via \S+$
```
or (when no user with space character allowed):
```ini
failregex = ^\s*gw\.\S+ system,error,critical login failure for user <F-USER>\S*</F-USER> from <ADDR>
```
But...

> Note the empty username in the second row.

Is it just a mistake in logging mechanisms, in case of login via ssh (so user never logged)? 
Or something like a handshake where first attempt (without username) causes always this single message?

In the second case (we must ignore such messages), the `*` in `<F-USER>` group must be replaced by `+` in both variants of RE.

**Comment by vitkabele** [comment]
> Is it just a mistake in logging mechanisms, in case of login via ssh (so user never logged)?
> Or something like a handshake where first attempt (without username) initiating login causes always this single message?

It seems to be just a mistake. It occurs rarely and not before every login so probably not the handshake variant.

Closing the issue and opening PR.
