### ISSUE TITLE
[BR]: Fail2Ban not honoring the findtime of 24-hours when 'pyinotify' is the backend

### ISSUE THREAD

**Issue by simdol2** [fail2ban/fail2ban#3461]
Fail2Ban v0.11.2, installed using OS-distribution package.
OS: Ubuntu 22.04 LTS
Bug: The "findtime" of one-day is not being honored when 'pyinotify' is the backend. Only new occurrences of the offences are causing the ban. The past occurrences of the offence that are in within the "findtime of one-day" are not being considered for the ban.

Note: I am attaching the f2ban log. I am using "nftables" and hence had to do some experiments to link nftables and fail2ban using systemd. Hence please ignore the errors in the log file which are because of the experiments. But the ban of IP  "45.8.22.217" should have been done by Fail2Ban whenever I restart the Fail2Ban since the offences were within 24-hours.
[fail2ban-log.zip](https://github.com/fail2ban/fail2ban/files/10777213/fail2ban-log.zip)

**Comment by sebres** [comment]
> But the ban of IP ... should have been done by Fail2Ban whenever I restart the Fail2Ban since the offences were within 24-hours.

Fail2ban uses database where it stores last position of the log-file, it processed previously. So after restart it would seek to the last known position in log and process only new entries.
See [#3252 ](https://github.com/fail2ban/fail2ban/issues/2909#issuecomment-758036512) for details.
