### ISSUE TITLE
[BR]: fail2ban.service: Main process exited, code=exited, status=255/n/a

### ISSUE THREAD

**Issue by hoochanlon** [fail2ban/fail2ban#3462]
reinstall not useful.

![catch2023-02-20 10 25 15](https://user-images.githubusercontent.com/35732922/219995619-9f704a56-66b4-4907-a0bc-991a17a41beb.png)

**Comment by sebres** [comment]
Our issue template says clearly and explicitly what description exactly you need to provide.
It is impossible to help you without more information.
For instance I see 4 errors in the screenshot (but not the error messages), and since they are from configreader and jailreader, I guess some jail configuration is invalid.
Thus closed unless more info provided.

**Comment by hoochanlon** [comment]
Thanks. I found it.

1.  Best to update yum and epel-release
2. CentOS 7 and above require fail2ban-firewalld and fail2ban-systemd
3. It is recommended to replace `vi /etc/fail2ban/jail.config` with `vi /etc/fail2ban/jail.local`.Keeping the negative effects of the operation localized.
  3.1.  Because in doing so, even if the negative effects of improper configuration can be controlled locally, jail.local itself. Also easy to debug.

For example:

![funcry](https://user-images.githubusercontent.com/35732922/220092961-f48c5c72-9f23-4941-bc83-840eed0d8bd5.png)

```
yum install epel-release -y && yum update -y
yum install fail2ban-firewalld fail2ban-systemd -y 
```

```
systemctl enable fail2ban.service && systemctl start fail2ban.service
```

Refer:  
* [csdn-centos8 install Nginx Error nginx.service: Unit cannot be reloaded becau lines 1-5](https://blog.csdn.net/m0_47748508/article/details/119203994)
* [Peking University-fail2ban install](https://its.pku.edu.cn/faq_fail2ban.jsp)
* [douban-CentOS7 - Installing and Configuring Fail2ban Tutorial](https://m.douban.com/note/626688457/)

**Comment by hoochanlon** [comment]
ps: https://wiki.archlinux.org/title/Fail2ban
