### ISSUE TITLE
[BR]: Found the solution to the "the jail "ssh_iptables' does not exist" and "View fail2ban.log for errors and exceptions" errors

### ISSUE THREAD

**Issue by hoochanlon** [fail2ban/fail2ban#3463]
**Problem 1**：Used `fail2ban-client status ssh_iptables`  error: ...the jail "ssh_iptables' does not exist.

**Solution**: 

"ssh_iptables" is the module option name in  jail.config or jail.local, needs rename. For example:

![catch2023-02-21 09 55 47](https://user-images.githubusercontent.com/35732922/220244834-46b2d9e0-8ebb-47ab-8f63-2e2cd3c0f891.png)

---

**Problem 2**：View fail2ban.log for errors and exceptions

![catch2023-02-21 10 40 23](https://user-images.githubusercontent.com/35732922/220246380-0e32e20a-53a0-4ae9-8908-947b448511b5.png)

**Solution**:

" fail2ban.transmitter WARNING Command " is  look like json. Remove comments. For Example: 

![catch2023-02-21 10 44 16](https://user-images.githubusercontent.com/35732922/220243738-629acc7c-3da0-4d58-a3b2-a8d3dc7236aa.png)

---
**For Test**

Password test

![catch2023-02-21 10 47 08](https://user-images.githubusercontent.com/35732922/220247269-a85f0287-9d29-4e87-aa3f-54c725f0c50c.png)

Success

![catch2023-02-21 11 37 27](https://user-images.githubusercontent.com/35732922/220247662-e2da19c7-1087-4030-a2a8-1c4900595725.png)

For other questions see：https://github.com/fail2ban/fail2ban/issues/3462#issue-1591009334 .

Thank you.

**Comment by sebres** [comment]
I don't understand your issue at all. 
If it is some question, use Discussions instead.
For a bug report we need fully fulfilled issue as suggested in the issue template.
And last but not least, please don't use screenshots - copy the messages instead and paste it between markdown code-block:
\`\`\`
\<messages going here\>
\`\`\`
