### ISSUE TITLE
[FR]: postfix - Not matching "Sender address rejected: Access denied"

### ISSUE THREAD

**Issue by sbn-purchark** [fail2ban/fail2ban#3474]
From the default postfix filter:
```
mdre-normal=^%(_pref)s from [^[]*\[<HOST>\]%(_port)s: [45][50][04] [45]\.\d\.\d+ (?:(?:<[^>]*>)?: )?(?:(?:Helo command|(?:Sender|Recipient) address) rejected: )?(?:Service unavailable|(?:Client host|Command|Data command) rejected|Relay access denied|(?:Host|Domain) not found|need fully-qualified hostname|match%(exre-user)s)\b
```

I see "Sender address reject:", but the additional message "Access denied" is missing. This is apparently the default postfix message for a _check_sender_access_ rejection.

### Environment:
- Fail2Ban version  : 1.0.2-1 (deb from Ubuntu Lunar/23.04)
- Postfix version: postfix/jammy,now 3.6.4-1ubuntu1 amd64 
- OS, including release name/version : Ubuntu 22.04.2 LTS

#### Service, project or product which log or journal should be monitored
- Name of filter or jail in Fail2Ban (if already exists) : postfix
- Relevant Postfix restriction: `smtpd_sender_restrictions = check_sender_access hash:/etc/postfix/sender_access_reject`
  - Using default return codes & messages.

#### Log or journal information
- Log file name(s) : /var/log/mail.log
- Journal identifier or unit name : N/A

### Relevant lines from monitored log files:
```
Mar  7 01:19:59 wes postfix/smtpd[188214]: NOQUEUE: reject: RCPT from unknown[107.182.128.219]: 554 5.7.1 <spameri@tiscali.it>: Sender address rejected: Access denied; from=<spameri@tiscali.it> to=<spameri@tiscali.it> proto=ESMTP helo=<WIN-CLJ1B0GQ6JP>
```

**Comment by sbn-purchark** [comment]
I would like to add that the same is also true for `smtpd_helo_restrictions = check_helo_access`. There is a match for "Helo command rejected", not not the "Access denied" part.

```
Mar  8 00:40:05 wes postfix/smtpd[193883]: NOQUEUE: reject: RCPT from unknown[79.110.62.237]: 554 5.7.1 <dom.tld>: Helo command rejected: Access denied; from=<ADMINISTRATOR@dom.tld> to=<lp@dom.tld> proto=ESMTP helo=<dom.tld>
```

Both are being used atm to block usage of my own domains from external.

**Comment by MrPeteH** [comment]
Here's my own set of enhanced regex in `postfix.conf`. A bunch of added checks to normal (you decide which ones you want ;) ... plus mdre_auth[3-6] for various types of additional attack.
(NB: I've also created additional filters for postfix/anvil, postfix/policy-spf, and opendkim)
With a VERY old domain name, I'm finally beginning to see some peace and quiet between the attacks.

```
mdre-normal=^RCPT from [^[]*\[<HOST>\]%(_port)s: 55[04] 5\.7\.1\s
            ^EHLO from [^[]*\[<HOST>\]%(_port)s: 504 5\.5\.2 (<[^>]*>)?: Helo command rejected: need fully-qualified hostname\b
            ^VRFY from [^[]*\[<HOST>\]%(_port)s: 550 5\.1\.1\s
            ^RCPT from [^[]*\[<HOST>\]%(_port)s: 550 5\.1\.1\s
            ^RCPT from [^[]*\[<HOST>\]%(_port)s: 450 4\.1\.8 (<[^>]*>)?: Sender address rejected: Domain not found\b
            ^RCPT from [^[]*\[<HOST>\]%(_port)s: 450 4\.1\.1 (<[^>]*>)?: Recipient address rejected: unverified address: unknown user\b
            ^RCPT from [^[]*\[<HOST>\]%(_port)s: 45[04] 4\.7\.[125]+ (?:Service unavailable\b|Client host rejected: cannot find your (reverse )?hostname\b)
            ^from [^[]*\[<HOST>\]%(_port)s:?

# todo: check/remove "Invalid authentication mechanism" from ignore list, if gh-1243 will get finished (see gh-1297).
mdpr-auth = warning:
mdre-auth = ^[^[]*\[<HOST>\]%(_port)s: SASL ((?i)LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed:(?! Connection lost to authentication server| Invalid authentication mechanism)
mdre-auth2= ^[^[]*\[<HOST>\]%(_port)s: SASL ((?i)LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed:(?! Connection lost to authentication server)

# auth3 -- one more scam type
#  auth4 -- lots of simple SASL bad logins
#  auth5 SSL probe
#  auth6 - both spam and horrific wget-based attacks
mdre-auth3= ^hostname %(__hostname)s does not resolve to address <HOST>: Name or service not known
mdre-auth4= ^[^[]*\[<HOST>\]%(_port)s: SASL ((?i)LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed
mdre-auth5= ^SSL_accept error from [^[]*\[<HOST>\]: lost connection
mdre-auth6= ^Illegal address syntax from [^[]*\[<HOST>\] in MAIL command

# Mode "rbl" currently included in mode "normal", but if needed for jail "postfix-rbl" only:
mdpr-rbl = %(mdpr-normal)s
mdre-rbl  = ^RCPT from [^[]*\[<HOST>\]%(_port)s: [45]54 [45]\.7\.1 Service unavailable; Client host \[\S+\] blocked\b

mdpr-more = (?:%(mdpr-normal)s|%(mdpr-auth)s)
mdre-more = %(mdre-auth3)s
            %(mdre-auth4)s
            %(mdre-auth5)s
            %(mdre-auth6)s
            %(mdre-auth)s
            %(mdre-normal)s

mdpr-ddos = lost connection after(?! DATA) [A-Z]+
mdre-ddos = ^from [^[]*\[<HOST>\]%(_port)s:?

mdpr-extra = (?:%(mdpr-auth)s|%(mdpr-normal)s)
mdre-extra = %(mdre-auth)s
            %(mdre-normal)s

mdpr-aggressive = (?:%(mdpr-auth)s|%(mdpr-normal)s|%(mdpr-ddos)s)
mdre-aggressive = %(mdre-auth2)s
                  %(mdre-normal)s

```

**Comment by sebres** [comment]
> Here's my own set of enhanced regex in postfix.conf. 

@MrPeteH we need at least one message matched every single RE in filter to able to add some to our stock filter.

> plus mdre_auth[3-6] for various types of additional attack

Which you added only for mode `more`, so they wouldn't match in mode `aggressive` (basically for all filters of f2b the mode `aggressive` means normally match all possible types of failure).

**Comment by MrPeteH** [comment]
> @MrPeteH we need at least one message matched every single RE in filter to able to add some to our stock filter.

Sorry, I am not sure I understand (and apologies for delay: dealing with a LOT of RL issues, incl a death...)

Are you saying you need at least one example message for each RE in the filter? I can assemble that. If NOT, then please explain in a different way. ;)

**Comment by sebres** [comment]
Yes, this is also mandatory in the test filter factory, since every regex needs to be covered in the tests.
