### ISSUE TITLE
Simple regex matches but does not ban - This will be easy for you

### ISSUE THREAD

**Issue by AdmiralNoisyBottom** [fail2ban/fail2ban#3492]
I am running Almalinux 9 with fail2ban 1.01.

I have recently seen some odd entries in my access logs such as;

`91.107.211.87 - - [09/Apr/2023:08:17:15 +0800] "GET /rindex.php?action=add&parameter=verwrmmjqx.php%7Chttps%3A%2F%2Fpaste.bingner.com%2Fpaste%2Fmhcmm%2Fraw HTTP/1.1" 404 31 "www.google.com" "Mozlila/5.0 (Linux; Android 7.0; SM-G892A Bulid/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.107 Moblie Safari/537.36"`

All I want to do is ban any mention of rindex.php.

The appropriate jail starts. The regex I am using is;

`failregex = "<HOST>.*rindex\.php"`

`fail2ban-regex /var/log/nginx/access.log "<HOST>.*rindex\.php"`

The above shows many matches. The rindex.php thing is mentioned in every access log for all domains here.

When fail2ban is restarted nothing is mentioned in the fail2ban.log and no matches are found. 

"fail2ban-client status" displays 0 for all logs.

I have spent hours banging my head against a brick wall trying different regex's without success.

Any ideas where I've gone wrong. All other enabled jails function normally and have been working for a long time. I'm reasonably new to the world of linux and can't wrap my head around regex's.

**Comment by sebres** [comment]
> `failregex = "<HOST>.*rindex\.php"`

Don't put the quotes (that are not in message) in `failregex` in the config file (it is OK for the shell - it's called quotation and used to supply string as single argument, but not in the config file).

Additionally your RE is vulnerable (unanchored and has a catch-all). Use something like that instead:
```ini
failregex = ^<ADDR> \S+ \S+ [^"]*"[A-Z]+ /rindex\.php\?[^"]*" 404
```

Also note that monitoring of access-log directly is not recommended, see [wiki :: Best practice](https://github.com/fail2ban/fail2ban/wiki/Best-practice), especially the part [Reduce parasitic log-traffic](https://github.com/fail2ban/fail2ban/wiki/Best-practice#reduce-parasitic-log-traffic).

> Any ideas where I've gone wrong.

I guess, exactly here are already mentioned quotes-character in config.

Another possible issues are described in [FAQ in wiki :: How fail2ban works](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works).
