### ISSUE TITLE
[BR]: Making ipthreat.conf work

### ISSUE THREAD

**Issue by Lutzion** [fail2ban/fail2ban#3494]
Since about 6 month there is an action ipthreat.conf

The idea is to report brute forcing ip-addresses to ipthreat.net and in return get the reported ip-adresses from ipthreat.net to block them with an ipset.

As i like the idea of that function i checked out the git repository, because ubuntu has old version 0.11 included.

In the documentation of ipthreat net 
[https://ipthreat.net/integrations/fail2ban](https://ipthreat.net/integrations/fail2ban)
in step 2 there is a hint to extend `jail.conf` with

```
# add to section [DEFAULT]
action = %(action_)s
         %(action_ipthreat)s[]
```

When (re)starting fail2ban i get the error:

> section 'sshd' contains an interpolation key 'action_ipthreat' which is
> not a valid option name. Raw value: '%(action_mwl)s\n%(action_ipthreat)s[]'

So i searched for `action_ipthreat` in the whole fail2ban repository and
i did not find it.

Please add the missing entry

### Environment:

- Fail2Ban version  : Fail2Ban v1.0.3.dev1
- OS, including release name/version : Ubuntu 22.04.2 LTS
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
fail2ban does not start. Error like described above

#### Steps to reproduce
add to section [DEFAULT]
action = %(action_)s
         %(action_ipthreat)s[]

#### Expected behavior
fail2ban should start

#### Observed behavior
it does not

**Comment by sebres** [comment]
Yes, `not a valid option name` means that there is no definition `action_ipthreat` to substitute `%(action_ipthreat)s`.
So one need to define it, like you did it. Or alternatively just:
```diff
 action = %(action_)s
-         %(action_ipthreat)s[...]
+         ipthreat[...]
```
