### ISSUE TITLE
[FR]: fail2ban-regex failregex searching only first line

### ISSUE THREAD

**Issue by PabReg** [fail2ban/fail2ban#3506]
- Fail2Ban version v0.10.2 
- OS, including release name/version :  Ubuntu 18.04.6 LTS

I created a filter zimbra-web.conf:

```
 cat /etc/fail2ban/filter.d/zimbra-web.conf
[Definition]
failregex = \[oip=<HOST>;.* SoapEngine - handler exception: authentication failed for .*, account not found$
;oip=<HOST>;.* SoapEngine - handler exception: authentication failed for .* missing userPassword$
;oip=<HOST>;.* Error occurred during authentication: authentication failed for .* missing userPassword.$

ignoreregex =
```

Running fail2ban-regex:

```
 sudo fail2ban-regex /opt/zimbra/log/mailbox.log /etc/fail2ban/filter.d/zimbra-web.conf

Running tests
=============

Use   failregex filter file : zimbra-web, basedir: /etc/fail2ban
Use         log file : /opt/zimbra/log/mailbox.log
Use         encoding : UTF-8


Results
=======

Failregex: 926 total
|-  #) [# of hits] regular expression
|   1) [926] \[oip=<HOST>;.* SoapEngine - handler exception: authentication failed for .*, account not found$
`-

Ignoreregex: 0 total

----------
```
Only first line of failregex is checked, other two are ignored.
If I'm running missing failregexes one by one it does find matches:

```
sudo fail2ban-regex /opt/zimbra/log/mailbox.log ";oip=<HOST>;.* SoapEngine - handler exception: authentication failed for .* missing userPassword$"

Running tests
=============

Use   failregex line : ;oip=<HOST>;.* SoapEngine - handler exception: aut...
Use         log file : /opt/zimbra/log/mailbox.log
Use         encoding : UTF-8


Results
=======

Failregex: 49 total
|-  #) [# of hits] regular expression
|   1) [49] ;oip=<HOST>;.* SoapEngine - handler exception: authentication failed for .* missing userPassword$
`-

sudo fail2ban-regex /opt/zimbra/log/mailbox.log ";oip=<HOST>;.* Error occurred during authentication: authentication failed for .* missing userPassword.$"

Running tests
=============

Use   failregex line : ;oip=<HOST>;.* Error occurred during authenticatio...
Use         log file : /opt/zimbra/log/mailbox.log
Use         encoding : UTF-8


Results
=======

Failregex: 1099 total
|-  #) [# of hits] regular expression
|   1) [1099] ;oip=<HOST>;.* Error occurred during authentication: authentication failed for .* missing userPassword.$
`-

Ignoreregex: 0 total
```
Why could fail2ban-regex ignore other lines of failregex?

**Comment by sebres** [comment]
> Only first line of failregex is checked, other two are ignored.

You have to insert at least one space before every additional regex, for example:
```ini
failregex = ...re1...
            ...re2...
            ...re3...
```
Also note that lines starting with `;` (or `#`) are comments in config files.

BTW, your REs are vulnerable - are not anchored and have catch-alls.

**Comment by PabReg** [comment]
Thank you for your reply.
I think the case will be a symbol `;` in config. How can I insert a regex which starts with `;` ?

**Comment by sebres** [comment]
> I think the case will be a symbol ; in config.

And I told you already what the reason is - a space is mandatory in parameter continuation after new-line.
In that case the config parser also wouldn't consider semicolon as a comment char.

By the way, I assume the line you want to match doesn't start with `;` symbol too, so if you'd properly anchor it and write a part of regex matching the prefix of string (but not as `^.*` since it's ugly and not an anchor), it would obviously not start with a semicolon.
Our issue template also requests the log excerpt (messages you want to match), so if you had provide it, one could help you by the regex's.

**Comment by PabReg** [comment]
Yes I added the space in the begging of the line and escape char `\` before `;` and now all three regexes matches.

I would be very gratefull if you could optimize my regex. Adding two lines from log file:

2023-04-26 14:08:59,905 INFO  [Pop3SSLServer-1] [ip=10.10.10.10;oip=1.1.1.1;cid=313987;] account - Error occurred during authentication: authentication failed for [user@domain.com]. Reason: missing userPassword.

2023-04-26 14:59:26,483 INFO  [qtp2011482127-254486:smtp://mail.domain.com:7073/service/admin/soap/] [name=user@domain.com;oip=159.224.54.196;oport=38167;oproto=smtp;soapId=2ef0bfa6;] SoapEngine - handler exception: authentication failed for [user@domain.com], missing userPassword

**Comment by sebres** [comment]
Both lines can be pretty well covered with a single RE:
```ini
failregex = ^\s*INFO\s+\[[^\]]+\]\s+\[(?:[^\]]*;)?oip=<ADDR>[^\]]*\]\s+(?:account - Error occurred during authentication|SoapEngine - handler exception): authentication failed for \[<F-USER>[^\]]*</F-USER>\]
```
(thereby `\[(?:[^\]]*;)?oip=<ADDR>[^\]]*\]` matches `[...;oip=192.0.2.1;...]` as well as `[oip=192.0.2.1]`)

**Comment by PabReg** [comment]
thank you for your reply. I think this RE would also triger this line:

2023-04-26 16:05:42,158 INFO  [Pop3SSLServer-0] [ip=10.10.10.10;oip=1.1.1.1;cid=329867;] account - Error occurred during authentication: authentication failed for [user@domain.com]. Reason: external LDAP auth failed, LDAP error:  - unable to ldap authenticate: 80090308: LdapErr: DSID-0C09044E, comment: AcceptSecurityContext error, data 52e, v2580.

And I would like to skip this line for now. How could I ignore it?

**Comment by sebres** [comment]
One can add a negative lookahead `(?!...)` to the RE, so it'd approximately mean "match unless followed by ...":

```diff
- ^\s*INFO\s+\[[^\]]+\]\s+\[(?:[^\]]*;)?oip=<ADDR>[^\]]*\]\s+(?:account - Error occurred during authentication|SoapEngine - handler exception): authentication failed for \[<F-USER>[^\]]*</F-USER>\]
+ ^\s*INFO\s+\[[^\]]+\]\s+\[(?:[^\]]*;)?oip=<ADDR>[^\]]*\]\s+(?:account - Error occurred during authentication|SoapEngine - handler exception): authentication failed for \[<F-USER>[^\]]*</F-USER>\](?!\. Reason: external LDAP auth failed\b)
```
or allow positive match only by adding of `[\.,] (?:Reason: )?missing userPassword\b`:
```diff
- ^\s*INFO\s+\[[^\]]+\]\s+\[(?:[^\]]*;)?oip=<ADDR>[^\]]*\]\s+(?:account - Error occurred during authentication|SoapEngine - handler exception): authentication failed for \[<F-USER>[^\]]*</F-USER>\]
+ ^\s*INFO\s+\[[^\]]+\]\s+\[(?:[^\]]*;)?oip=<ADDR>[^\]]*\]\s+(?:account - Error occurred during authentication|SoapEngine - handler exception): authentication failed for \[<F-USER>[^\]]*</F-USER>\][\.,] (?:Reason: )?missing userPassword\b
```

**Comment by PabReg** [comment]
thank you very much
