### ISSUE TITLE
[BR]: Python 3.11 causes DeprecationWarning: module sre_constants is deprecated

### ISSUE THREAD

**Issue by hannob** [fail2ban/fail2ban#3508]
### Environment:

- Fail2Ban version: 1.0.2
- OS, including release name/version : Gentoo
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

When one runs fail2ban with warnings enabled in python 3.11 it causes a deprecation warning:
```
/usr/lib/python3.11/site-packages/fail2ban/server/failregex.py:25: DeprecationWarning: module sre_constants is deprecated
```

#### Steps to reproduce

Set env variable PYTHONWARNINGS=d and run fail2ban.

#### Expected behavior

No warning.

#### Observed behavior

Above warning.

**Comment by sebres** [comment]
It's only used to have an exception class `sre_constants.error`...
So can be more or less safe replaced with `re.error` (since it is also imported from compiler there). 
I'll provide the fix soon. Thx!
