### ISSUE TITLE
[BR]: README - link for gamin is broken

### ISSUE THREAD

**Issue by javaveryhot** [fail2ban/fail2ban#3509]
### The issue:

gamin gnome link in readme gives 404

**Comment by sebres** [comment]
> gamin gnome link in readme gives 404

Well it seems to be obsolete anyway - fail2ban doesn't work with gamin since python 3 (see #1330, e. g. python-gamin requires python2). Let alone it was always a bit peculiar `backend` (also the slowest one).
I tend to remove its support for fail2ban completely.

**Comment by sebres** [comment]
> Is there a way to use inotify watches?

Yes. Install pyinotify module and set `backend = pyinotify` (or `backend = auto`) for the file related jails or default section in jail.local.

**Comment by sebres** [comment]
closed in 226a59445a8046b7f86c3bc072be1d78555ccdb0
