### ISSUE TITLE
Blocking corrupted urls not IPs ?

### ISSUE THREAD

**Issue by exxosuk** [fail2ban/fail2ban#3516]
In the log file it all looks fine with IPs.  though in actual IP tables I seem to get "urls" ?  

REJECT     all  --  43.129.77.146        anywhere             reject-with icmp-port-unreachable
REJECT     all  --  41.90.67.42          anywhere             reject-with icmp-port-unreachable
REJECT     all  --  39.106.226.227       anywhere             reject-with icmp-port-unreachable
REJECT     all  --  38.153.121.39        anywhere             reject-with icmp-port-unreachable
REJECT     all  --  unn-37-19-205-204.datapacket.com  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  ns3368740.ip-37-187-89.eu  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  36.78.203.67         anywhere             reject-with icmp-port-unreachable
REJECT     all  --  ec2-35-174-0-125.compute-1.amazonaws.com  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  24.133.130.56        anywhere             reject-with icmp-port-unreachable
REJECT     all  --  223.224.6.84         anywhere             reject-with icmp-port-unreachable
REJECT     all  --  216.244.66.233       anywhere             reject-with icmp-port-unreachable
REJECT     all  --  216.244.66.229       anywhere             reject-with icmp-port-unreachable
REJECT     all  --  203.56.198.90        anywhere             reject-with icmp-port-unreachable
REJECT     all  --  203.25.216.221       anywhere             reject-with icmp-port-unreachable
REJECT     all  --  203.188.230.167      anywhere             reject-with icmp-port-unreachable
REJECT     all  --  2.58.46.48           anywhere             reject-with icmp-port-unreachable
REJECT     all  --  196.196.164.80       anywhere             reject-with icmp-port-unreachable
REJECT     all  --  ns3036181.ip-193-70-81.eu  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  vps-zap1085316-1.zap-srv.com  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  ns501595.ip-192-99-36.net  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  modem-down75.netlp.com.ar  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  host-186-148-97-175.ufinet.com.pa  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  host72.186-108-207.telecom.net.ar  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  9.bl.bot.semrush.com  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  8.bl.bot.semrush.com  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  6.bl.bot.semrush.com  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  5.bl.bot.semrush.com  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  43.bl.bot.semrush.com  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  42.bl.bot.semrush.com  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  41.bl.bot.semrush.com  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  40.bl.bot.semrush.com  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  4.bl.bot.semrush.com  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  38.bl.bot.semrush.com  anywhere             reject-with icmp-port-unreachable
REJECT     all  --  37.bl.bot.semrush.com  anywhere             reject-with icmp-port-unreachable

It seems to happen with multiple filters, does anybody know why ?

**Comment by sebres** [comment]
> though in actual IP tables I seem to get "urls" ?

You don't. This is reverse lookup by default output of `iptables` and co. Use [-n or --numeric](https://manpages.debian.org/unstable/iptables/iptables.8.en.html#n) parameter, e.g.:
```
iptables -nL
```
