### ISSUE TITLE
[RFE]: 

### ISSUE THREAD

**Issue by FOSSBOSS** [fail2ban/fail2ban#3522]
just a minor request really. if the comment in /etc/fail2ban/jail.conf
"# "bantime" is the number of seconds that a host is banned."

could be changed to include the various identifiers of time  for  banning.
and or be worded something like this:

"# "bantime" is the amount of time that a host is banned. s seconds  m  minutes h hours d days y years"

or whatever the options are. I'm not clear on what the identifiers are.  I know s,m,h  all seem to work. 
I think it could make the bantime usage more clear.

**Comment by sebres** [comment]
> I'm not clear on what the identifiers are.

https://manpages.debian.org/testing/fail2ban/jail.conf.5.en.html#TIME_ABBREVIATION_FORMAT

I don't think that all this belongs to the `jail.conf`. 
Basically manpage is exactly right place for that.

Although I'll try to rephrase it in jail.conf a shorter way.
