### ISSUE TITLE
[BR]: 

### ISSUE THREAD

**Issue by screwball22** [fail2ban/fail2ban#3550]
### Environment:

- Fail2Ban version  : 
- OS, including release name/version : 
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

#### Any customizations done to /etc/fail2ban/ configuration

```
```

#### Relevant parts of /var/log/fail2ban.log file:

```
```

#### Relevant lines from monitored log files:

```
```

**Comment by sebres** [comment]
Closed as empty.
