### ISSUE TITLE
Fail2ban is not starting

### ISSUE THREAD

**Issue by KxmischerLasse** [fail2ban/fail2ban#3551]
### Environment:

- Fail2Ban version  : 
- OS, including release name/version : 1.0.2-2
- [ yes ] Fail2Ban installed via OS/distribution mechanisms
- [ yes ] You have not applied any additional foreign patches to the codebase
- [ no ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Fail2ban is not starting on Debian 12

#### Steps to reproduce

apt install fail2ban
systemctl status fail2ban

#### Expected behavior

Fail2ban should start

#### Observed behavior

Fail2ban doesnt start

#### Any customizations done to /etc/fail2ban/ configuration

```
```

#### Relevant parts of /var/log/fail2ban.log file:

```
```

#### Relevant lines from monitored log files:

![image](https://github.com/fail2ban/fail2ban/assets/67797390/91b4e269-8cec-41ca-960c-098feee558e4)

```
```

**Comment by sebres** [comment]
It seems not find any log file for sahd jail (and backend used by jail is file related, polling, pyinotify or auto)...
What do you see by `fail2ban-client -d | grep sshd`? If the `logpath` is wrong, set correct `logpath`. If it's rather a systemd journal - set another backend:
```ini
[sshd]
backend = systemd
...
enabled = true
```
@fail2ban/maintainers isn't debians default backend systemd?

**Comment by KxmischerLasse** [comment]
![image](https://github.com/fail2ban/fail2ban/assets/67797390/5ee53a70-7440-4fa1-97fd-9c8e3f3d06b0)

This is the output of fail2ban-client -d | grep sshd

**Comment by sebres** [comment]
Your backend is file based - `['add', 'sshd', 'auto']` will use `polling` or `pyinotify` depending on installation of packages.
Strange is that in your output is no `logpath`, normally it'd be something like `/var/log/auth.log` (or I missed it in the screenshot, better would be a copy and paste instead)...
Anyway, as already said, if sshd is logging to journal you have to set backend as described above, if it is file you have to set the `logpath`.
As I know by default debians sshd would log to systemd journal, to check it use `fail2ban-regex systemd-journal sshd` and see whether it will find something (e. g. found `Lines` at end is larger than 0). If yes, set backend to systemd in jail and restart fail2ban.
