### ISSUE TITLE
[BR]: SOGo regex doesn't match when behind IIS reverse proxy

### ISSUE THREAD

**Issue by Todd1561** [fail2ban/fail2ban#3565]
Version 1.0.2 on Debian 12.1.  No customizations.

I have SOGo (as installed via iRedMail server) behind a Windows IIS reverse proxy.  With that setup failed entries look like the below:
`Aug 24 11:13:26 sogod [2347]: SOGoRootPage Login from '172.20.0.44:56383, 172.20.0.200' for user 'Todd' might not have worked - password policy: 65535  grace: -1  expire: -1  bound: 0`

Notice the addition of the port # after the first IP address.  It seems to be throwing off the regex pattern and not catching these lines.  If I remove the port # and test with fail2ban-regex it works fine.  I know there have been commits in the past to deal specifically with reverse proxies so I'm assuming it's something about IIS that's causing the port number to be added.  SOGo is being hosted by nginx on the Debian server BTW.

**Comment by sebres** [comment]
The issue can be simply fixed by adding `(?::\d+)?` to match the port optionally like that:
```diff
- failregex = ^ sogod \[\d+\]: SOGoRootPage Login from '<HOST>(?:,[^']*)?' for user '[^']*' might not have worked( - password policy: \d*  grace: -?\d*  expire: -?\d*  bound: -?\d*)?\s*$
+ failregex = ^ sogod \[\d+\]: SOGoRootPage Login from '<ADDR>(?::\d+)?(?:,[^']*)?' for user '[^']*' might not have worked( - password policy: \d*  grace: -?\d*  expire: -?\d*  bound: -?\d*)?\s*$
```
just... this will get an issue by short IPv6 mistakenly considering last part of address as a port.
Also alternative like `(?::\d{5})?` is a bit ugly, since it'd ignore short ports (or vice versa mistakenly consider it as IPv6 part).
If they using brackets for safe logging of IPv6, one could use something like that `(?:<IP4>|\[<IP6>\])(?::\d+)?`, what would be safe, but... One'd need the example excerpt logged by IPv6 address.

**Comment by Todd1561** [comment]
Thanks for the quick reply, the new regex did indeed fix the original issue.  Although, fail2ban still doesn't work because this server is behind a reverse proxy so while the offending IP address is blocked, since all requests are coming from my proxy server the block doesn't do anything.  This seems to be a problem in general with fail2ban so I'll probably need to come up with some way to relay the blocks to my IIS reverse proxy server for this to work.

**Comment by sebres** [comment]
> Thanks for the quick reply, the new regex did indeed fix the original issue.

Well, conditionally, because of aforementioned issues with IPv6.

> I'll probably need to come up with some way to relay the blocks to my IIS reverse proxy server for this to work.

No idea about IIS, if you'd use nginx instead - there is an action for such kind of ban - [action.d/nginx-block-map.conf](https://github.com/fail2ban/fail2ban/blob/master/config/action.d/nginx-block-map.conf).
