### ISSUE TITLE
[BR]: Fresh Debian Bookworm install won't start

### ISSUE THREAD

**Issue by jameskimmel** [fail2ban/fail2ban#3574]
### Environment:

- Fail2Ban version  : v1.0.2
- OS, including release name/version : Debian 12 bookworm
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Fresh Debian Bookworm install won't start. 

#### Steps to reproduce
Fresh Debian 12 installation.
sudo apt install fail2ban
sudo systemctl status fail2ban shows failed

#### Expected behavior
sudo systemctl status fail2ban  should show active

#### Observed behavior
output from systemctl status fail2ban
```
 fail2ban.service - Fail2Ban Service
     Loaded: loaded (/lib/systemd/system/fail2ban.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-09-15 12:34:46 CEST; 1min 47s ago
   Duration: 71ms
       Docs: man:fail2ban(1)
    Process: 1027 ExecStart=/usr/bin/fail2ban-server -xf start (code=exited, status=255/EXCEPTION)
   Main PID: 1027 (code=exited, status=255/EXCEPTION)
        CPU: 68ms

Sep 15 12:34:46 jelly systemd[1]: Started fail2ban.service - Fail2Ban Service.
Sep 15 12:34:46 jelly fail2ban-server[1027]: 2023-09-15 12:34:46,418 fail2ban.configreader   [1027]: WARNING 'allowipv6' not defined in 'Definition'. Using default one: 'auto'
Sep 15 12:34:46 jelly fail2ban-server[1027]: 2023-09-15 12:34:46,427 fail2ban                [1027]: ERROR   Failed during configuration: Have not found any log file for sshd jail
Sep 15 12:34:46 jelly fail2ban-server[1027]: 2023-09-15 12:34:46,428 fail2ban                [1027]: ERROR   Async configuration of server failed
Sep 15 12:34:46 jelly systemd[1]: fail2ban.service: Main process exited, code=exited, status=255/EXCEPTION
Sep 15 12:34:46 jelly systemd[1]: fail2ban.service: Failed with result 'exit-code'.

```

#### Any additional information

Log is empty. Please let me know if I can provide additional informations. 

Setting sshd in /etc/fail2ban/jail.d/defaults-debian.conf to no mitigates the problem, but I wonder why this is not the default?

**Comment by sebres** [comment]
Dup of https://github.com/fail2ban/fail2ban/issues/3292
See https://github.com/fail2ban/fail2ban/issues/3292#issuecomment-1142503461 for a solution.
