### ISSUE TITLE
[BR]: fail2ban.filter         [481]: ERROR   Failed to process line: '', caught exception: IndexError('string index out of range')

### ISSUE THREAD

**Issue by averlon** [fail2ban/fail2ban#3599]
### Environment:

- Fail2Ban version  : 0.11.2
- OS, including release name/version : Ubuntu 22.04.3 LTS
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

#### Any customizations done to /etc/fail2ban/ configuration

```
```

#### Relevant parts of /var/log/fail2ban.log file:

```
```

#### Relevant lines from monitored log files:

```
```

**Comment by averlon** [comment]
unfortunately I cannot identfiy what caused this error and to what jail or filter it might be related.

Is there any chance to find out? If not, yould you please enhance this error message with more details to enable root cause analysis.
Thanks

**Comment by sebres** [comment]
See https://github.com/fail2ban/fail2ban/issues/2967#issuecomment-796820642
