### ISSUE TITLE
Iptables uses dns, not ip

### ISSUE THREAD

**Issue by mrkacg1** [fail2ban/fail2ban#3602]
Hello. I am configuring the program in debian. It recognizes the blocks but in iptables it appears like this:

![image](https://github.com/fail2ban/fail2ban/assets/26174637/7576b4f4-54f4-4178-8f58-dfb822098e94)

The blocking is not done, since I still have the opportunity to connect.

Any ideas? I have already modified usedns=no in jail.conf

Thanks.

**Comment by sebres** [comment]
> Iptables uses dns, not ip

This is not correct - `iptables --list` without `--numeric` shows DNS if it can resolve that. 
See [man iptables](https://ipset.netfilter.org/iptables.man.html):
```
-n, --numeric
    Numeric output. IP addresses and port numbers will be printed in numeric format. 
    By default, the program will try to display them as host names, network names, or services (whenever applicable).
```

Use `iptables -nL` instead.

>  I have already modified `usedns=no` in jail.conf

This has nothing to do with iptables. This option would stop to find, parse FQDN in log messages and would not resolve them to IPs anymore. With other words tag `<HOST>` will match only IP addresses (basically works like tag `<ADDR>`).

> The blocking is not done, since I still have the opportunity to connect.

Please see the FAQ in [wiki :: How fail2ban works](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works) (second question) for the possible reason why it doesn't work for you.

I guess either wrong IP e. g. real IP vs. proxying IP (`X-Forwarded-For`)... or wrong or missing port (service still listening on different or additional address)... or something whitelisting connection or bypass rules of iptables. Or still worse - net-filter doesn't work at all (no idea why, need more data to investigate deeper).

Thus closed. I'll reopen the issue if you'd provide more info.
