### ISSUE TITLE
[BR]: Built-in slapd filter not working

### ISSUE THREAD

**Issue by kernstock** [fail2ban/fail2ban#3604]
### Environment:

- Fail2Ban version: v1.0.2
- OS, including release name/version : Rocky Linux 9.2 (Blue Onyx)
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase

### The issue:

The built-in filter for slapd does not detect failed attempts.

#### Steps to reproduce

Install and configure and run slapd and activate fail2ban's built-in slapd jail.

#### Expected behavior

The jail should recognize failed bind attempts.

#### Observed behavior

It does not.

### Additional Information

OpenLDAP 2.6

### Configuration, dump and another helpful excerpts

`/etc/fail2ban/jail.local`
```
[slapd]
enabled = true
port    = ldap,ldaps
logpath = /var/log/slapd.log
```

#### Relevant parts of /var/log/fail2ban.log file:
```
2023-10-16 11:42:43,772 fail2ban.jail           [474077]: INFO    Creating new jail 'slapd'
2023-10-16 11:42:43,773 fail2ban.jail           [474077]: INFO    Jail 'slapd' uses poller {}
2023-10-16 11:42:43,776 fail2ban.filter         [474077]: INFO    Added logfile: '/var/log/slapd.log' (pos = 0, hash = ec1a800af8e9acd73ea2f6013c304ff008342041)
2023-10-16 11:42:43,782 fail2ban.jail           [474077]: INFO    Jail 'slapd' started
```

#### Relevant lines from monitored log files:
`/var/log/slapd.log`
```
Oct 16 12:00:11 localhost slapd[568321]: conn=1120 fd=13 ACCEPT from IP=**redacted**:52504 (IP=0.0.0.0:636)
Oct 16 12:00:11 localhost slapd[568321]: conn=1120 fd=13 TLS established tls_ssf=256 ssf=256 tls_proto=TLSv1.3 tls_cipher=TLS_AES_256_GCM_SHA384
Oct 16 12:00:11 localhost slapd[568321]: conn=1120 op=0 BIND dn="**redacted**" method=128
Oct 16 12:00:11 localhost slapd[568321]: conn=1120 op=0 RESULT tag=97 err=49 qtime=0.000011 etime=0.000961 text=
Oct 16 12:00:11 localhost slapd[568321]: conn=1120 op=1 UNBIND
Oct 16 12:00:11 localhost slapd[568321]: conn=1120 fd=13 closed
```

**Comment by sebres** [comment]
Basically this patch could fix that:
```diff
- failregex = ^(?P<__prefix>%(__prefix_line)s)conn=(?P<_conn_>\d+) fd=\d+ ACCEPT from IP=<HOST>:\d{1,5} \(IP=\S+\)\s*<SKIPLINES>(?P=__prefix)conn=(?P=_conn_) op=\d+ RESULT(?:\s(?!err)\S+=\S*)* err=49 text=[\w\s]*$
+ failregex = ^(?P<__prefix>%(__prefix_line)s)conn=(?P<_conn_>\d+) fd=\d+ ACCEPT from IP=<HOST>:\d{1,5} \(IP=\S+\)\s*<SKIPLINES>(?P=__prefix)conn=(?P=_conn_) op=\d+ RESULT(?:\s(?!err)\S+=\S*)* err=49\b
```
But I don't like obsolete multi-line processing (with `maxlines`), so better the filter would look like that:
```ini
[INCLUDES]
before = common.conf

[Definition]
_daemon = slapd
prefregex = ^%(__prefix_line)sconn=<F-MLFID>\d+</F-MLFID>(?: (?:fd|op)=\d+){0,2} (?=ACCEPT|RESULT)<F-CONTENT>.+</F-CONTENT>$
failregex = ^<F-NOFAIL>ACCEPT</F-NOFAIL> from IP=<ADDR>:\d{1,5}\s+
            ^RESULT(?:\s(?!err)\S+=\S*)* err=49\b
ignoreregex =
maxlines = 1
```

**Comment by kernstock** [comment]
@sebres Thanks! Works like a charm from what I gather.

I think for the `maxlines = 1` to persist, it should be:

```
[INCLUDES]
before = common.conf

[Definition]
_daemon = slapd
prefregex = ^%(__prefix_line)sconn=<F-MLFID>\d+</F-MLFID>(?: (?:fd|op)=\d+){0,2} (?=ACCEPT|RESULT)<F-CONTENT>.+</F-CONTENT>$
failregex = ^<F-NOFAIL>ACCEPT</F-NOFAIL> from IP=<ADDR>:\d{1,5}\s+
            ^RESULT(?:\s(?!err)\S+=\S*)* err=49\b
ignoreregex =

[Init]
maxlines = 1
```

I might be wrong though.

**Comment by sebres** [comment]
> I think for the maxlines = 1 to persist, it should be ...

Value of `maxlines` is by default 1, so it's no need to specify (previously it was also in the Init section for possibility to change it from jail, because historic it was expected there, it is not needed anymore there and anyway 1 now).
