### ISSUE TITLE
[RFE]: Support for Cloudflare bearer authorization

### ISSUE THREAD

**Issue by ev0net** [fail2ban/fail2ban#3609]
#### Feature request type
Fail2ban is currently using legacy authorization for Cloudflare. Can we support Cloudflare current, non-legacy authorization for the action for: https://github.com/fail2ban/fail2ban/blob/master/config/action.d/cloudflare.conf

#### Description
Existing Fail2Ban Cloudflare auth: `-H 'X-Auth-Email: <cfuser>' -H 'X-Auth-Key: <cftoken>'`

Cloudflare current, non-legacy authorization is: `-H 'Authorization: Bearer <API_TOKEN>'`

https://developers.cloudflare.com/fundamentals/api/get-started/create-token/

To preserve existing functionality, does it make sense to:

1. Do a new file name i.e. cloudflare-bearer.conf (or similar) AND let me know the file name you'd like
OR
2. Add to /action.d/cloudflare.conf as COMMENTED code:

LINE: 68
```
_cf_api_prms = -H 'X-Auth-Email: <cfuser>' -H 'X-Auth-Key: <cftoken>' -H 'Content-Type: application/json'
# _cf_api_prms = -H 'Authorization: Bearer <cfbearer>' -H 'Content-Type: application/json'
```

LINE: 81
```
cftoken =

cfuser =

# cfbearer = 
```

AND add explanation with this link at the top: https://developers.cloudflare.com/fundamentals/api/get-started/create-token/

Given the ease of this change and the code already posted in this issue, I'd imagine someone could easily slot it into their existing workflow. If not, I'm happy to do a pull request. Let me know. Thanks!

**Comment by sebres** [comment]
There is still one action `action.d/cloudflare-token`, which seems to use legacy auth too:
https://github.com/fail2ban/fail2ban/blob/eed319e896f603471cc4027b353b8535faac4208/config/action.d/cloudflare-token.conf#L65

**Comment by ev0net** [comment]
Thanks for pointing that out. I have 0.11.2-6 installed via hestia-cp. They haven't added 1.0.2-2 yet so that file was missing for me. I should have checked the versions first and looked that the current release before posting. Sorry to waste your time. Thanks!
