### ISSUE TITLE
Ubuntu 22LTS - fail2ban not working for guacamole.

### ISSUE THREAD

**Issue by ebym** [fail2ban/fail2ban#3617]
fail2ban/jammy,now 0.11.2-6 all [installed]

Have configured jail and filters for guacamole, but ip is not getting blocked even after several failed login attempts. I'm not certain if i have missed anything critical. Thanks.

**fail2ban jail configuration**

/etc/fail2ban/jail.local
```
bantime  = 10m
findtime  = 10m
maxretry = 5

[guacamole]
enabled = true
port     = http,https
logpath  = /var/log/tomcat9/catalina.out
bantime = 10m
findtime = 60m
maxretry = 3
```

**filter configuration**

/etc/fail2ban/filter.d/guacamole.conf 
```
[Definition]
logging = catalina
failregex = <L_<logging>/failregex>
maxlines = <L_<logging>/maxlines>
datepattern = <L_<logging>/datepattern>

[L_catalina]
failregex = ^.*WARN  o\.a\.g\.r\.auth\.AuthenticationService - Authentication attempt from <HOST> for user "[^"]*" failed\.$
maxlines = 3
datepattern = ^%%H:%%M:%%S.%%f

[L_webapp]
failregex = ^.*WARN  o\.a\.g\.r\.auth\.AuthenticationService - Authentication attempt from <HOST> for user "[^"]*" failed\.$
maxlines = 1
datepattern = ^%%H:%%M:%%S.%%f
```

$ cat /var/log/tomcat9/catalina.out
```
[2023-10-28 12:11:24] [info] 12:11:24.051 [http-nio-8080-exec-8] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from \xxx.xxx.xxx.101 for user "root" failed.
[2023-10-28 12:11:43] [info] 12:11:43.270 [http-nio-8080-exec-9] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from \xxx.xxx.xxx.101 for user "admin" failed.
[2023-10-28 12:11:58] [info] 12:11:58.960 [http-nio-8080-exec-7] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from \xxx.xxx.xxx.101 for user "administrator" failed.
[2023-10-28 12:12:08] [info] 12:12:08.259 [http-nio-8080-exec-6] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from \xxx.xxx.xxx.101 for user "root" failed.
[2023-10-28 12:12:17] [info] 12:12:17.522 [http-nio-8080-exec-2] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from \xxx.xxx.xxx.101 for user "apple" failed.
[2023-10-28 12:16:43] [info] 12:16:43.260 [http-nio-8080-exec-3] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from \xxx.xxx.xxx.101 for user "admin" failed.
[2023-10-28 12:16:56] [info] 12:16:56.660 [http-nio-8080-exec-7] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from \xxx.xxx.xxx.101 for user "administrator" failed.
[2023-10-28 12:17:02] [info] 12:17:02.150 [http-nio-8080-exec-9] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from \xxx.xxx.xxx.101 for user "administrator" failed.
[2023-10-28 12:17:08] [info] 12:17:08.100 [http-nio-8080-exec-2] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from \xxx.xxx.xxx.101 for user "administrator" failed.
[2023-10-28 12:17:15] [info] 12:17:15.400 [http-nio-8080-exec-1] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from \xxx.xxx.xxx.101 for user "root" failed.
[2023-10-28 12:17:23] [info] 12:17:23.820 [http-nio-8080-exec-5] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from \xxx.xxx.xxx.101 for user "hp" failed.
```
$ sudo fail2ban-client status guacamole
```
Status for the jail: guacamole
|- Filter
|  |- Currently failed:	0
|  |- Total failed:	0
|  `- File list:	/var/log/tomcat9/catalina.out
`- Actions
   |- Currently banned:	0
   |- Total banned:	0
   `- Banned IP list:	
```

**Comment by sebres** [comment]
The filter is not compatible for this log-format for whatever reasons (I saw already dozen different formats provided in filter requests for guacamole, e. g. #2879, #3346, etc).
The RE for this format could look like:
```ini
[guacamole]
enabled = true
filter =
failregex = ^(?:\[\]\s+)?\[info\] \S+ \[[^\]]+\] WARN\s+o\.a\.g\.r\.auth\.AuthenticationService - Authentication attempt from <ADDR> for user "<F-USER>[^"]*</F-USER>" failed\.
...
```
(guessing that in the log-excerpt the `\`-char before IP is a typo arisen by blackening, if not and it presents in the message - simply add `\\` (double backslash) direct before `<ADDR>`).

I will not update the filter, because simply don't know one which we'd need to consider, since as already said, out there are hundred of different formats for that...

**Comment by sebres** [comment]
> Thanks, your failregex format did not work.

Well, as already said (read attentively what I wrote above) - you need to add `\\` before `<ADDR>` if the message really contains backslash before IP.
So:
```ini
filter =
failregex = ^(?:\[\]\s+)?\[info\] \S+ \[[^\]]+\] WARN\s+o\.a\.g\.r\.auth\.AuthenticationService - Authentication attempt from \\<ADDR> for user "<F-USER>[^"]*</F-USER>" failed\.
```
Also note - I did reset the filter (set it to empty string) to avoid usage of other parameters specified in the stock filter, which may be wrong (for instance the datepattern or something else).

> Following failregex is matching and working

This is vulnerable RE (for example because it is unanchored, since `^.*` is not an anchor) and we'll never provide such REs here and will also never recommend to use that in production for several reasons.

> Since Date template hits: are still 0 - Is datepatern significant or is it's matching optional for fail2ban to work properly ?

I guess you still use stock filter... The pattern specified in original filter would not match surely (it is anchored at begin of message, in your log it is enclosed in  `[]` instead.
Either don't use it (fail2ban would detect it automatically), or set another one, for instance `^\[%%Y-%%m-%%d %%H:%%M:%%S\]\s+`
And yes - datepatern is significant, at least it must be correct or set to `{NONE}` if log-file doesn't contain timestamp or one want to renounce a date/time (e. g. bad for the time seeks by initial scan, etc).

You can also test RE with fail2ban-regex (just use it enclosed in single quotes instead of filter).

Anyway if you want a filter (with datepattern), here you go:
```ini
[Definition]
failregex = ^\s*\[info\] \S+ \[[^\]]+\] WARN\s+o\.a\.g\.r\.auth\.AuthenticationService - Authentication attempt from \\<ADDR> for user "<F-USER>[^"]*</F-USER>" failed\.
datepattern = ^\[%%Y-%%m-%%d %%H:%%M:%%S\]\s+
```

**Comment by ebym** [comment]
Thanks.  For some reason `\\<ADDR>` did not work earlier. I must have missed something while testing with `fail2ban-regex`.

Yes i was using the stock filter for `datepattern`.

One question regarding `bantime`,  what would happen to the ip used by `user a` in the following scenario with following jail configuration. 
```
bantime.increment = true
bantime.rndtime = 45

bantime  = 10m
findtime  = 1h
maxretry = 3
```

e.g.
1. 10:10:10am - failed ip addr for user a.
2. 10:10:10am - failed ip addr for user a.
3. 10:10:10am - authenticated user z.
4. 10:10:10am - authenticated user k.
5. 10:10:20am - failed ip addr for user a.
6. 10:10:30am - authenticated user y.
7. 10:10:30am - failed ip addr for user a.

My understanding is, 
(A) `maxlines=3` look for consecutive hits from same ip, hence it will not ban `user a` ip. 
(B) If there are 4nos of  consecutive hits from same ip, ip is banned and 10mins later automatically released, after `user a` can attempt to login again from the same ip. - I have tested this.
(C) `user a` can attempt to login from another ip and attempt 2 login tries and so on....

Is it possible to keep `user a` ip banned for the duration of `findtime`  if `user a` tries again and fail another 2 attempts from previously banned ip ?.

-------------------------------------------------------------------
Following is working as expected. Thanks again.
```
failregex = ^\s*\[info\] \S+ \[[^\]]+\] WARN\s+o\.a\.g\.r\.auth\.AuthenticationService - Authentication attempt from \\<ADDR> for user "<F-USER>[^"]*</F-USER>" failed\.
datepattern = ^\[%%Y-%%m-%%d %%H:%%M:%%S\]\s+
```

**Comment by sebres** [comment]
> One question regarding bantime, what would happen to the ip used by user a in the following scenario with following jail configuration.
> ...
> Is it possible to keep `user a` ip banned for the duration of `findtime` if `user a` tries again and fail another 2 attempts from previously banned ip ?.

I don't fully understand what you try to explain here, but...

At the moment fail2ban consider the user only for hardening certain rules (e. g. handling a different users attempts from same IP as a sign not to reset attempts counter with gained access message by `<F-MLFGAINED>` tag - this is used to prevent situation where someone having a valid user account try to bruteforce another accounts and then reset failures count by single success attempt with a login using his legitimate account in hope to forget previous attempts). At the moment it is sole usage of user, excepting the possibility to get it with tag `<F-USER>` in action and output users with `fail2ban-regex -o`:
```
fail2ban-regex -o "<ip> -- <F-USER> -- <msg>" /path/to/log filter
```
or read them from fail2ban database.

As for `bantime.increment` - fail2ban doesn't consider directly the user by this mechanism directly: it simply increases `bantime` and reduces `maxretry` by the same factor for the recidive attempts for known as bad IP (ID), see a [table in #1460](https://github.com/fail2ban/fail2ban/pull/1460) how it'd do that.
Theoretically one can define own formula with `bantime.formula` to somehow consider the user too, just at the moment it would affect the `bantime` and `maxretry` in the same matter.

If you'd rather consider user for the ban-identifier, you may need to change the filter to combine both IP/user with `<F-TUPLE_ID>` or similar stuff, but it would also expect different action that can handle 2 values - `<ip>` and `<F-USER>` (see also [wiki :: How to ban something other as host (IP address), like user or mail, etc.](https://github.com/fail2ban/fail2ban/wiki/How-to-ban-something-other-as-host-(IP-address),-like-user-or-mail,-etc.)).

If you rather mean you want something like subnet banning (or recognize a bruteforce attack from multiple IPs) - this is still a feature request [see the RFE for that](https://github.com/fail2ban/fail2ban/issues/927).

**Comment by ebym** [comment]
> I don't fully understand what you try to explain here, but...

I was testing ip banning with config setting posted earlier and observed the following,

1. when login attempt is failed, ip is banned after consecutive failed logins, and ip is unbanned after automatically. 
2. user can attempt to login to from the same ip within `findtime = 1h` and fails. Currently, it allow another 3 attempts[`maxretry = 3`] before banning ip again and the same attempts can be repeated 5 times within an hour with `bantime = 10m`. This would be 20 failed attempts within an hour from single ip.

If login fails from once banned ip, Is it is possible to keep user ip banned for the duration of `findtime` or specified period ?.

e.g.

1. user ip banned for 10mins. - _genuine reasons - user may have forgotten password or forgot caps lock is on._
2. user attempts again twice after ban duration and fail, within `findtime` value - _this attempt can be with malicious intent or trying to bruteforce accounts. And legitimate users would contact support team by this time._
3. This time, keep user ip banned for specified period or `findtime` - 

Is this feature already available ?.

Thanks.

**Comment by sebres** [comment]
> Currently, it allow another 3 attempts[`maxretry = 3`] before banning ip again and the same attempts can be repeated 5 times within an hour with `bantime = 10m`. 

No, with `bantime.increment = true` it does not. As already said, every next time the attack begins, it'd need fewer attempts to be banned (again, see the [table in #1460](https://github.com/fail2ban/fail2ban/pull/1460)). This mean after 1st ban, the 2nd ban reached after 2 attempts and it double as long (20m), 3rd time it gets banned after 1 attempt and take 40m.

This is the table for `bantime.increment = true`, `bantime.maxtime = 3w` and initial ban 10m (`bantime = 10m`)...

Known|Ban-Count|Attempts|Ban-time
--|--|--|--
No|1|3|10m
Yes|2|2|20m
Yes|3|1|40m
Yes|4|1|80m (1h 20m)
Yes|5|1|160m (2h 40m)
...|...|...|...
Yes|N|1|30240m (3w)

> This would be 20 failed attempts within an hour from single ip.

Again - no. The IP has only 6 attempts in first hour (see first 3 rows in table above - it'd take 70m). And 1 attempt in following hour (80m) and it'd be banned for double of time every next attempt.
That all without to consider user name at all in any way.

> If login fails from once banned ip, Is it is possible to keep user ip banned for the duration of findtime or specified period ?.

It is already the case - the user and other data are stored in fail2ban DB.

> Is this feature already available ?.

I guess I am still incapable to follow the approach, however I have experimental version that can affect incremental banning factor, so one'd be able to consider user name (or even its switch by further attempts) to affect `maxretry` and `bantime` for recidive IPs. WiP.

**Comment by ebym** [comment]
Many thanks for the detailed explanation. 

For some reason the banned ip is NOT shown after service restart. Is this normal behaviour ?. Tthe version i'm running is ` fail2ban/jammy,now 0.11.2-6 all [installed]`. This could be the reason it is not working properly.

initial fail2ban status. please note Total failed and Total banned values.
```
Status for the jail: guacamole
|- Filter
|  |- Currently failed:	0
|  |- Total failed:	3
|  `- File list:	/var/log/tomcat9/catalina.out
`- Actions
   |- Currently banned:	0
   |- Total banned:	1
   `- Banned IP list:	
```

edited jail config to modify` bantime.maxtime` & `bantime.rndtime` values and restarted service.

```
$ sudo nano /etc/fail2ban/jail.conf 
$ sudo systemctl restart fail2ban.service 
$ sudo systemctl status fail2ban.service 
● fail2ban.service - Fail2Ban Service
     Loaded: loaded (/lib/systemd/system/fail2ban.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-11-08 13:28:52 IST; 14s ago
       Docs: man:fail2ban(1)
   Main PID: 97847 (fail2ban-server)
      Tasks: 11 (limit: 9308)
     Memory: 12.9M
        CPU: 158ms
     CGroup: /system.slice/fail2ban.service
             └─97847 /usr/bin/python3 /usr/bin/fail2ban-server -xf start

Nov 08 13:28:52 piitpl.co.in systemd[1]: Started Fail2Ban Service.
Nov 08 13:28:52 piitpl.co.in fail2ban-server[97847]: Server ready
```

After service restart, Total failed and banned count become zero !!!.

```
$ sudo fail2ban-client status guacamole
Status for the jail: guacamole
|- Filter
|  |- Currently failed:	0
|  |- Total failed:	0
|  `- File list:	/var/log/tomcat9/catalina.out
`- Actions
   |- Currently banned:	0
   |- Total banned:	0
   `- Banned IP list:	
```
Thanks.

**Comment by sebres** [comment]
> For some reason the banned ip is NOT shown after service restart. Is this normal behaviour ?.

It is only possible if the time of restart reaches the end of ban (so the ticket expiered), otherwise the ban should be restored.
There was a [bug](https://github.com/fail2ban/fail2ban/pull/1807) in restore mechanisms, but only persistent tickets (`bantime = -1`) were affected. Excepting that there is no known issues about it, so all active tickets must be restored (unless fail2ban database gets deleted for some reason).

> After service restart, Total failed and banned count become zero !!!.

Fail2ban doesn't have persistent statistic right now. See [#2123 (comment)](https://github.com/fail2ban/fail2ban/issues/2123#issuecomment-387026191).

**Comment by ebym** [comment]
Thanks,

You are correct, the banned ip vanishes only after end of ban.

I will check and confirm in sqllite if banned ip is cleared or not.
