### ISSUE TITLE
fail2ban action ufw does not support applications with a space in the name eg "Apache Full"

### ISSUE THREAD

**Issue by eedgar** [fail2ban/fail2ban#3618]
the action ufw should be supported to use quotes around app names.

**Comment by sebres** [comment]
You have not followed our issue template (e. g. not provided your fail2ban version)...
I don't see where it'd be needed in current version of filter:
https://github.com/fail2ban/fail2ban/blob/eed319e896f603471cc4027b353b8535faac4208/config/action.d/ufw.conf#L20-L33
`"<application>"` is enclosed in quotes everywhere.
