### ISSUE TITLE
[FR]: Apache-auth filter in Fail2Ban misses 'remote' keyword in logs

### ISSUE THREAD

**Issue by ItsMarcoDE** [fail2ban/fail2ban#3622]
### Environment:
Fail2Ban version: 1.0.2
OS, including release name/version: Debian 12

### Service, project or product which log or journal should be monitored
Name of filter or jail in Fail2Ban: apache-auth
Service, project or product name, including release name/version: Apache Web Server 2.4.57
Service type: Web Server
Ports and protocols the service is listening: HTTP (80), HTTPS (443)

### Any additional information
Some Apache error logs use "remote" instead of "client" to indicate the remote client's IP address, causing fail2ban not to recognize failed authentication attempts properly.

### Relevant lines from monitored log files:
`[Mon Nov 06 13:39:56.637868 2023] [auth_basic:error] [pid 3175001:tid 140494544914112] [remote 171...:35924] AH01618: user rfghuu not found: /admin`
`[Mon Nov 06 13:39:58.441441 2023] [auth_basic:error] [pid 3175001:tid 140494452414144] [remote 171...:35924] AH01618: user rggvj not found: /admin`
`[Mon Nov 06 13:40:00.244168 2023] [auth_basic:error] [pid 3175001:tid 140494696277696] [remote 171...:35924] AH01618: user ggvbk not found: /admin`

### Changes proposed:
In the apache-common.conf, modifying the _apache_error_client definition to include "remote" alongside "client" as some Apache logs refer to the client IP with "remote".

From:
`_apache_error_client = <apache-prefix>\[(:?error|<apache-pref-ignore>\S+:\S+)\]( \[pid \d+(:\S+ \d+)?\])? \[client <HOST>(:\d{1,5})?\]`

To:
`_apache_error_client = <apache-prefix>\[(:?error|<apache-pref-ignore>\S+:\S+)\]( \[pid \d+(:\S+ \d+)?\])? \[(client|remote) <HOST>(:\d{1,5})?\]`

This modification correctly identified the failed login attempts in my Apache logs, which use the "remote" identifier.

**Comment by knurz** [comment]
This also effects Ubuntu 22.04 0.11.2-6.

@ItsMarcoDE Thx for posting.
