### ISSUE TITLE
Understanding maxmatches

### ISSUE THREAD

**Issue by xeruf** [fail2ban/fail2ban#3632]
I read through https://github.com/fail2ban/fail2ban/pull/2402 but I think it fails to clarify one thing - if matches are not held in memory, what is done differently? Are they saved to the DB right away?
Does this option impact behavior or is it only a performance tradeoff between RAM Usage and Disk writes?

**Comment by sebres** [comment]
> if matches are not held in memory, what is done differently? 

It would hold `maxmatches` last messages in memory (FIFO), but the count of attempts gets incremented by every new match (to ban the ticket by reaching `maxretry` in a `findtime`).

> Are they saved to the DB right away?

No. Fail2ban would only save the messages that are available in memory to the time point of ban.
