### ISSUE TITLE
[BR]: IP 127.0.0.1 banned but website still accessible by 127.0.0.1 

### ISSUE THREAD

**Issue by IssueFindings** [fail2ban/fail2ban#3640]
Hello,
I discover that now the IP 127.0.0.1 is ignored by default.
So, I add the option `ignoreself = false` in the paragraph [DEFAULT] of the file /etc/fail2ban/jail.d/custom.conf

That works ! The IP 127.0.0.1 is listed in the Banned IP list of Fail2Ban but I can still access the website through IP 127.0.0.1
Someone can explain me why ?

Have a nice day.

**Comment by sebres** [comment]
Well, it depends... For instance on the banaction used for jail or net-filter settings or default firewall rules.
Usually and often loopback will be whitelisted in firewall to avoid many issues.
Also the packet from 127.0.0.1 coming through a specific interface: the `lo` (loopback) interface whereas the banning action may create a rule for `eth0` or whatever Interface of your network adapter (you can see all your interfaces with a command like `ifconfig`).
Anyway normally it makes no sense to ban loopback at all.
