### ISSUE TITLE
[BR]: Fail2ban not filtering ssh on Debian 12 due to journalctl controlling logs

### ISSUE THREAD

**Issue by huornlmj** [fail2ban/fail2ban#3645]
### Environment:

- Fail2Ban version: 1.0.2-2 
- OS, including release name/version : Debian 12.
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:
Because Debian 12 uses journalctl for ssh logs and not auth.log, fail2ban refuses to start as there is no ssh log file to point it to.

#### Steps to reproduce
Install fail2ban on a Debian 12 system.  Observe the following:
```console
$ sudo systemctl status fail2ban.service
× fail2ban.service - Fail2Ban Service
     Loaded: loaded (/lib/systemd/system/fail2ban.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Sat 2023-12-09 10:05:12 UTC; 7min ago
   Duration: 96ms
       Docs: man:fail2ban(1)
    Process: 65873 ExecStart=/usr/bin/fail2ban-server -xf start (code=exited, status=255/EXCEPTION)
   Main PID: 65873 (code=exited, status=255/EXCEPTION)
        CPU: 71ms

Dec 09 10:05:12 localhost systemd[1]: Started fail2ban.service - Fail2Ban Service.
Dec 09 10:05:12 localhost fail2ban-server[65873]: 2023-12-09 10:05:12,592 fail2ban.configreader   [65873]: WARNING 'allowipv6' not defined in 'Definition'. Using default one: 'auto'
Dec 09 10:05:12 localhost fail2ban-server[65873]: 2023-12-09 10:05:12,599 fail2ban                [65873]: ERROR   Failed during configuration: Have not found any log file for sshd jail
Dec 09 10:05:12 localhost fail2ban-server[65873]: 2023-12-09 10:05:12,601 fail2ban                [65873]: ERROR   Async configuration of server failed
Dec 09 10:05:12 localhost systemd[1]: fail2ban.service: Main process exited, code=exited, status=255/EXCEPTION
Dec 09 10:05:12 localhost systemd[1]: fail2ban.service: Failed with result 'exit-code'.

```

#### Expected behavior
Have some way to get fail2ban work with journalctl logging.

#### Observed behavior
Doesn't work, doesn't start.
#### Relevant parts of /var/log/fail2ban.log file:

```
```

#### Relevant lines from monitored log files:
The fail2ban.log file is empty because the daemon won't start.

**Comment by sebres** [comment]
Dup of https://github.com/fail2ban/fail2ban/issues/3292
See https://github.com/fail2ban/fail2ban/issues/3292#issuecomment-1142503461 for a solution.
