### ISSUE TITLE
[BR]: nginx-http-auth filter does not match because of two subsequent timestamps from systemd-journald and nginx

### ISSUE THREAD

**Issue by PanCakeConnaisseur** [fail2ban/fail2ban#3646]
When a user login using basic HTTP authentication is attempted and the username does not exist, this is logged in the error log of nginx and AFAICU nginx-http-auth is the appropriate jail to catch this. AFAIK, the error log can not be changed in nginx and it always adds a timestamp to the error message. When using the systemd backend, systemd-journald also adds a timestamp. This results in error logs such as 

```
Dez 09 21:35:20 myhostname nginx[983478]: 2023/12/09 21:35:20 [error] 983478#983478: *3 user "fakeusername" was not found in "/var/lib/nginx/htpasswd-for-myhostname.example.com", client: 111.22.33.44, server: myhostname.example.com, request: "GET / HTTP/2.0", host: "myhostname.example.com"
```
Note the two timestamps. The primary filter provided for nginx-http-auth does not account for this double timestamp:

`^\s*\[error\] \d+#\d+: \*\d+ user "(?:[^"]+|.*?)":? (?:password mismatch|was not found in "[^\"]*"), client: <HOST>, server: \S*, request: "\S+ \S+ HTTP/\d+\.\d+", host: "\S+"(?:, referrer: "\S+")?\s*$`.

This leads to fail2ban not reacting to login attempts with non-existing users. 

# Workaround

Changing the start of the expression from `^\s*\[error\]` to `^.*\[error\]` resolves this problem and the filter matches.

# Versions
```
# fail2ban-client -V
1.0.2
```
Installed on NixOS 23.11 stable. I have applied no further patches.

# jail.local

```
[DEFAULT]
backend = systemd
banaction = iptables-multiport
banaction_allports = iptables-allport
bantime = 10m
bantime.increment = true
bantime.maxtime = 24h
bantime.overalljails = true
bantime.rndtime = 10m
ignoreip = 127.0.0.1/8 ::1 10.0.0.0/24 192.168.0.0/24
maxretry = 3

[INCLUDES]
before = paths-nixos.conf

[nginx-bad-request]
enabled = true

[nginx-http-auth]
enabled = true
findtime = 1d
mode = normal

[sshd]
enabled = true
findtime = 1d
mode = aggressive
port = 22
publickey = invalid
```

# /etc/fail2ban/filter.d/nginx-http-auth.conf 
```
# fail2ban filter configuration for nginx


[Definition]

mode = normal

mdre-auth = ^\s*\[error\] \d+#\d+: \*\d+ user "(?:[^"]+|.*?)":? (?:password mismatch|was not found in "[^\"]*"), client: <HOST>, server: \S*, request: "\S+ \S+ HTTP/\d+\.\d+", host: "\S+"(?:, referrer: "\S+")?\s*$
mdre-fallback = ^\s*\[crit\] \d+#\d+: \*\d+ SSL_do_handshake\(\) failed \(SSL: error:\S+(?: \S+){1,3} too (?:long|short)\)[^,]*, client: <HOST>

mdre-normal = %(mdre-auth)s
mdre-aggressive = %(mdre-auth)s
                  %(mdre-fallback)s

failregex = <mdre-<mode>>

ignoreregex = 

datepattern = {^LN-BEG}

journalmatch = _SYSTEMD_UNIT=nginx.service + _COMM=nginx

# DEV NOTES:
# mdre-auth:
# Based on samples in https://github.com/fail2ban/fail2ban/pull/43/files
# Extensive search of all nginx auth failures not done yet.
# 
# Author: Daniel Black

# mdre-fallback:
# Ban people checking for TLS_FALLBACK_SCSV repeatedly
# https://stackoverflow.com/questions/28010492/nginx-critical-error-with-ssl-handshaking/28010608#28010608
# Author: Stephan Orlowsky
```

**Comment by sebres** [comment]
> the error log can not be changed in nginx and it always adds a timestamp to the error message

Imho, it depends on how the log-forwarding to syslog in configured.

> Changing the start of the expression from ^\s*\[error\] to ^.*\[error\] resolves this problem and the filter matches.

This is ugly workaround, since the RE becomes vulnerable due to broken anchor - because `^.*` is quasi the same as if it were missing, so no anchor anymore and REs may match everywhere (also against a user input with an "injection" attempt), additionally it becomes very slow, especially on long messages, since it must search the whole message.

Anyway for people having that format here is interim workaround:
```diff
- mdre-auth = ^\s*\[error\] \d+#\d+: \*\d+ user "(?:[^"]+|.*?)":? (?:password mismatch|was not found in "[^\"]*"), client: <HOST>, server: \S*, request: "\S+ \S+ HTTP/\d+\.\d+", host: "\S+"(?:, referrer: "\S+")?\s*$
+ mdre-auth = ^\s*(?:(?!\[)\S+ nginx\[\d+\]: [^\[]*)?\[error\] \d+#\d+: \*\d+ user "(?:[^"]+|.*?)":? (?:password mismatch|was not found in "[^\"]*"), client: <HOST>, server: \S*, request: "\S+ \S+ HTTP/\d+\.\d+", host: "\S+"(?:, referrer: "\S+")?\s*$
- mdre-fallback = ^\s*\[crit\] \d+#\d+: \*\d+ SSL_do_handshake\(\) failed \(SSL: error:\S+(?: \S+){1,3} too (?:long|short)\)[^,]*, client: <HOST>
+ mdre-fallback = ^\s*(?:(?!\[)\S+ nginx\[\d+\]: [^\[]*)?\[crit\] \d+#\d+: \*\d+ SSL_do_handshake\(\) failed \(SSL: error:\S+(?: \S+){1,3} too (?:long|short)\)[^,]*, client: <HOST>
```
(`(?:(?!\[)\S+ nginx\[\d+\]: [^\[]*)?` would optionally match systemd prefix with also optional additional timestamp)

**Comment by PanCakeConnaisseur** [comment]
Thanks a lot for the quick resolution. I suspected that my workaround is a dirty hack.

**Comment by Owned67** [comment]
> ```diff
> mdre-fallback = ^\s*(?:(?!\[)\S+ nginx\[\d+\]: [^\[]*)?\[crit\] \d+#\d+: \*\d+ SSL_do_handshake\(\) failed \(SSL: error:\S+(?: \S+){1,3} too (?:long|short)\)[^,]*, client: <HOST>
> ```

Ive apply but always same it return 228 missed... any suggestion?

Debian 11 
Fail2ban 0.11.2

**Comment by sebres** [comment]
People... nobody can provide any suggestions, if you give zero info.
In order to help you, we need at least one "missed" message you complain about...
Try it with:
```bash
fail2ban-regex --print-all-missed systemd-journal 'nginx-http-auth[mode=aggressive]'
```
and provide few lines that are still missed by filter as an example.

**Comment by Owned67** [comment]
[f2b.txt](https://github.com/fail2ban/fail2ban/files/14922963/f2b.txt)

**Comment by sebres** [comment]
It doesn't look to me that your nginx writes the error-log to systemd journal - there is no one message which should be matched by filter. I see only warnings or start emergency-messages (throwed by start of nginx-unit per worker), nothing else.

If you mean it must be really systemd journal, try to find out (with `journalctl` in json output) which tags it uses exactly, current filter use `_SYSTEMD_UNIT=nginx.service + _COMM=nginx`.
For instance:
```
journalctl -o json | grep nginx
```
(or something similar)

If not (errorlog is a file) - you must use `backend = auto` and set proper `logpath` for this jail.

**Comment by Owned67** [comment]
ok ok will check later, too many result with journalctl -o json | grep nginx... no time for check all now xD

Thanks for helped me!
