### ISSUE TITLE
[BR]: backend = systemd seems to ignore user journals

### ISSUE THREAD

**Issue by redder86** [fail2ban/fail2ban#3649]
### Environment:

- Fail2Ban version 1.0.2
- OS, including release name/version : Fedora 38, RPM installation
- [X ] Fail2Ban installed via OS/distribution mechanisms
- [X ] You have not applied any additional foreign patches to the codebase
- [X ] Some customizations were done to the configuration (provide details below is so)

### The issue:

I had configured fail2ban jail.d to monitor ASSP running as systemd assp.service, system user assp, and ASSP was logging to the systemd journal.  However, fail2ban was not seeing the assp user journal entries - only the system ones.

So, it would seem that fail2ban was looking in /var/log/journal/system.journal but not also in the /var/log/journal/user-1002.journal.

To resolve this I reconfigured systemd journald to "Storage=volatile" (which puts all journald entries in /run/log/journal/system.journal), and that appears to have gotten fail2ban to see the assp.service entries.

Probably fail2ban should also filter user journal entries with "backend = systemd", there should be some other option to specify the systemd user journal to filter, or there should be some documentation about disabling user journals.

**Comment by sebres** [comment]
Shortly, not a bug but feature... The reason for that is #2392 (issue can lead to "Too many open files" errors). 
Since #2444 it ignores user journals by default.

Read [man jail.conf.5 # systemd](https://manpages.debian.org/bookworm/fail2ban/jail.conf.5.en.html#systemd) for details.

Possible solution:
#### jail.local
```ini
backend = systemd[journalflags=1]
```
#### fail2ban-regex
```bash
fail2ban-regex 'systemd-journal[journalflags=1]' ...
```
