### ISSUE TITLE
[BR]: Can't get firewall bans to go into a different zone

### ISSUE THREAD

**Issue by brad2014** [fail2ban/fail2ban#3656]
### Environment:

- Fail2Ban version  : 
- OS, including release name/version : 
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

I want to tell fail2ban to put postfix bans into firewalld "internal" zone.  I see that action.s/firewalld-common.conf sets zone to "public".  I tried overriding it in jail.local, but I must not be doing it right, and I can't find any documentation.

#### Steps to reproduce

My jail.local file is simply:

```
[DEFAULT]
ignoreip = 127.0.0.1/8 10.0.0.0/8 
bantime = 1d
findtime = 1d
zone = internal

[postfix]
enabled = true
mode = aggressive
```

#### Expected behavior

I expect to see bans appear when I do:

```
# firewall-cmd --list-rich-rules --zone=internal
```

#### Observed behavior

Instead I see bans appear when I do:

```
# firewall-cmd --list-rich-rules --zone=public
```

#### Any additional information

I'm using the stock fail2ban bundled with Rocky 9:

fail2ban-1.0.2-7.el9.noarch

#### Any customizations done to /etc/fail2ban/ configuration

```
```

#### Relevant parts of /var/log/fail2ban.log file:

```
```

#### Relevant lines from monitored log files:

```
```

**Comment by sebres** [comment]
> I tried overriding it in jail.local, but I must not be doing it right

I don't see how you were trying to override defaults (in your jail.local is nothing about `banaction` or even `action`).
But indeed setting of `zone` in default section would change nothing, unless this parameter supplied to the action (and it doesn't normally), see:
https://github.com/fail2ban/fail2ban/blob/9bedc3c38385a2eb3c62677360c520a58819b9b1/config/jail.conf#L208-L212

Moreover I don't see where the banactions set to firewalld action (some distro-include?)...

Anyway, here you go:
```ini
[DEFAULT]
zone = internal
banaction = firewallcmd-multiport[zone='%(zone)s']
banaction_allports = firewallcmd-allports[zone='%(zone)s']

# or simply:

banaction = firewallcmd-multiport[zone=internal]
banaction_allports = firewallcmd-allports[zone=internal]
```
(don't know which banaction you use, so for example used `firewallcmd-multiport` and `firewallcmd-allports` here)

Another way would be to overwrite it in `action.d/firewalld-common.local`:
```ini
[Init]
zone = internal
```
(this way it would be valid for all `firewalld-*` using `firewalld-common` include and its parameter `zone`).

**Comment by lejeczek** [comment]
Are you sure @sebres that is a good/valid example to use/give?
From what I see - what comes with my Centos 9's packages - banaction _firewallcmd-multiport_ does not need/use the concept of **zone** - it utilizes firewalld's **--direct**
When I look at **nftables** it seems that, that _firewallcmd-multiport (via firewalld) goes only into **ip filter** table, creating **chains** (only)there.

Moreover, with my **f2b** version v1.0.2 seems that:
`zone = public`
has no effect at all - eg. with **firewallcmd-rich-rules** (there firewalld utilizes _zones_ , yes) rules (nftables as a result) always go into whatever firewalld has set as the **default** zone (& only that zone)

Nowhere I see any **action** (in default configs) utilize _--zone_ and I wonder how would that/anything work?
