### ISSUE TITLE
Unavailability of iptables-multiport on VPS

### ISSUE THREAD

**Issue by intmainreturnzero** [fail2ban/fail2ban#3659]
Hi folks,

I have an instance on Linode where I wish to use fail2ban to minimize spam authentication attempts on my Dovecot service.

Upon starting to use fail2ban, I noticed error entries on the lines of 

Failed to execute ban jail 'dovecot' action 'iptables-multiport'.

I had also read somewhere that this can happen with VPSs, but I couldn't find a solution to get around this. For Dovecot, I think fail2ban tries to block the IP on IMAP, IMAPS, POP and other ports with iptables-multiport. 

Is there a workaround where it would ban the above ports iteratively without having to use multiport. I am not sure if that's possible since I'm a new user of fail2ban and haven't use iptables before either.

**Comment by sebres** [comment]
Which error message exactly do you have? Can you provide a log excerpt around the message?

> Is there a workaround where it would ban the above ports iteratively without having to use multiport

Yes, however it is a bit ugly - you have to define N singleport actions for N ports, with different chains or modify the action to add N chains with 1 ipset, etc. There are many variants.

Also you can try another action if your distro supports another net-filter, like nftables.

Alternatively just switch to iptables-allports action:
```ini
banaction = iptables-allports
```
Sure that would ban the IP completely regardless the port, but if false positives are almost to neglect, it'd be also an option.

**Comment by intmainreturnzero** [comment]
Thank you for the reply! In my case, I had run the system update just before installing fail2ban and the system update had updated the Kernel.

I guess there was some issue with using iptables kernel modules with the partial update without a reboot.

After reboot, things worked perfectly well with iptables-multiport.

Also a side note, I had originally tried to reach out to the fail2ban-users mailing list, but I couldn't find the full mail address anywhere :( Could you please document the mailing list address somewhere? I tried fail2ban-users@sourceforge.net but the mail bounced.

Once again, thank you for your reply, closing this issue.
