### ISSUE TITLE
[BR]: Failed during configuration: Have not found any log file for jupyterlab jail (log not in /var/log)

### ISSUE THREAD

**Issue by PasaOpasen** [fail2ban/fail2ban#3666]
Cannot start because of this error from the next jail:
```
[jupyterlab]
enabled = true
port = 8888
filter = jupyterlab
backend = polling

logpath = /srv/lab.log

maxretry = 6
bantime = 20
findtime = 300
```

The file `/srv/lab.log` exists and is found as I see in `fail2ban-client --dp` output (on non-existing file there will be no `addlogpath` row):
```
['add', 'jupyterlab', 'polling']
['set', 'jupyterlab', 'usedns', 'warn']
['set', 'jupyterlab', 'addignoreregex', "''"]
['multi-set', 'jupyterlab', 'addfailregex', ['PAM Authentication failed \\(.*@<HOST>\\)', '(404|401) (GET|HEAD|POST|PUT|DELETE) .* \\(@<HOST>\\) .*ms']]
['set', 'jupyterlab', 'maxretry', 6]
['set', 'jupyterlab', 'maxmatches', 6]
['set', 'jupyterlab', 'findtime', '300']
['set', 'jupyterlab', 'bantime', '20']
['set', 'jupyterlab', 'ignorecommand', '']
['set', 'jupyterlab', 'logencoding', 'auto']
['set', 'jupyterlab', 'addlogpath', '/srv/lab.log', 'head']
['set', 'jupyterlab', 'addaction', 'firewallcmd-rich-rules']
['multi-set', 'jupyterlab', 'action', 'firewallcmd-rich-rules', [['actionstart', ''], ['actionstop', ''], ['actioncheck', ''], ['actionban', 'ports="8888"; for p in $(echo $ports | tr ", " " "); do firewall-cmd --add-rich-rule="rule family=\'<family>\' source address=\'<ip>\' port port=\'$p\' protocol=\'tcp\' reject type=\'<rejecttype>\'"; done'], ['actionunban', 'ports="8888"; for p in $(echo $ports | tr ", " " "); do firewall-cmd --remove-rich-rule="rule family=\'<family>\' source address=\'<ip>\' port port=\'$p\' protocol=\'tcp\' reject type=\'<rejecttype>\'"; done'], ['port', '8888'], ['protocol', 'tcp'], ['chain', '<known/chain>'], ['name', 'jupyterlab'], ['actname', 'firewallcmd-rich-rules'], ['family', 'ipv4'], ['zone', 'public'], ['service', 'ssh'], ['rejecttype', 'icmp-port-unreachable'], ['blocktype', 'REJECT --reject-with <rejecttype>'], ['rich-blocktype', "reject type='<rejecttype>'"], ['family?family=inet6', 'ipv6'], ['rejecttype?family=inet6', 'icmp6-port-unreachable']]]
['start', 'sshd']
['start', 'jupyterlab']
```

```
[pasa@fedora-16-64 fail2ban]$ ls -lah /srv/lab.log 
-rw-r--r--. 1 pasa pasa 5.9K Jan 19 12:51 /srv/lab.log
```

I made file copies and links in `/var/log`:
```
[pasa@fedora-16-64 fail2ban]$ ls -lah /var/log | grep lab
-rw-r--r--. 1 pasa   pasa            5.9K Jan 19 12:59 lab2.log
lrwxrwxrwx. 1 root   root              12 Jan 19 13:00 lab3.log -> /srv/lab.log
-rw-r--r--. 1 root   root            5.9K Jan 19 12:56 lab.log
```
And both `lab.log` and `lab2.log` files do not make problem if I use them as `logpath`. But the symlink does.

Maybe there are some trusted directories? 

Version:
```
Fail2Ban v1.0.2
```
on Fedora 38

**Comment by sebres** [comment]
The error "Have not found any log file" occurs definitely if fail2ban-client cannot find a file matching logpath for the jail.
There are no exceptions. Thus check paths, permissions (also selinux policies), etc.

**Comment by sebres** [comment]
Yes, if you dump the config from console it looks like the glob is there.
However as one can see around https://github.com/fail2ban/fail2ban/blob/9bedc3c38385a2eb3c62677360c520a58819b9b1/fail2ban/client/jailreader.py#L275-L276
the error is only possible if no file found by glob, so `found_files` is still 0.
In that case there will be no `addlogpath` for that jail.

I don't know how you start it and where you get the error from, it doesn't look like the error is there if you dump the config.

> how can I check how exactly the daemon fails to start? Is there some advanced logging for this?

It depends on the distro and the type of init-system.

For an alternative attempt to start (not as service) one could try to use this:
```bash
# start (daemonize in background)
?sudo? fail2ban-client -vv start
# stop
?sudo? fail2ban-client stop

# or start in foreground (use ctrl+c to stop it):
?sudo? fail2ban-server -vvf --logtarget=sysout start
```
and I guess it will work too, because it seems to work by simple dump from console... so you have to find why it doesn't work if it starts as service/systemd-unit/init-script/whatever.

**Comment by PasaOpasen** [comment]
I found that the problem goes from Python `os.stat` permission error; in such case `os.path.exists returns False`; I tried to solve it but no chance. It raises only when the service runs as systemd unit and not manually. Moving target logs location solved the problem

**Comment by sebres** [comment]
> I found that the problem goes from Python os.stat permission error; in such case os.path.exists returns False

Sure, just they are basically mapped to the corresponding syscalls, so it is not a python issue.

> It raises only when the service runs as systemd unit and not manually.

As already said, there can be dozen reasons why the path is not accessible if service running as systemd unit.
Neither this is pythons issue, nor the issue of fail2ban.
