### ISSUE TITLE
unable to create multiple logs folders in logpath

### ISSUE THREAD

**Issue by AndMck** [fail2ban/fail2ban#3683]
I am trying to add to file locations which are not under /var/log and the documentation states that i only need to place a space between each like this logpath = /logs/sftp/stderr /logs/sftp/user.log  i have added this config to the [sshd]  section in my jail.local, this is configured in a ubuntu container, when i build with docker , everything looks ok, but when i cat the jail.local file, the 2nd location /logs/sftp/user.log is not there. I can modify within the container but then i get an error when trying to restart fail2ban. 
```
fail2ban-client reload
2024-02-27 16:58:13,254 fail2ban                [634]: ERROR   Failed during configuration: Source contains parsing errors: '/etc/fail2ban/jail.local'
        [line 247]: '/logs/sftp/user.log\n'
```

**Comment by sebres** [comment]
It doesn't look like a space between paths.
Corresponding to error message:
```
[line 247]: '/logs/sftp/user.log\n'
```
it looks like it were something like that:
```ini
...
[jail]
logpath = /logs/sftp/stderr
/logs/sftp/user.log
```
Take a careful look at line 247. Anyway the error means there is no space at that line.

To fix that just add few spaces after new-line before the second path, like:
```ini
...
[jail]
logpath = /logs/sftp/stderr
          /logs/sftp/user.log
```
And yes, 1 space would be enough too.

By the way, (if one consider the large lines number - 247), did you copied stock jail.conf as jail.local?
If yes, better don't do that - jail.local should normally contain only options you want overwrite.

**Comment by AndMck** [comment]
Apologies I did not thank you for your response, much appreciated as i was on leave.
