### ISSUE TITLE
[FR]: I want to ban every host in log but I can't figure it out. 

### ISSUE THREAD

**Issue by AdmiralNoisyBottom** [fail2ban/fail2ban#3705]
I have a special log file in which only bad guys are recorded. If a host is found in the log I want it banned.

I've tried the following three, and many more;
```
failregex = ^<HOST> .
failregex = ^<HOST> .*
failregex = <HOST> 
```
I have never gotten my head around regex! 

Simply put, if it is in the log it should be banned!

HELP!

### Environment:

- Fail2Ban version  : 
- OS, including release name/version : 

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : 
- Service, project or product name, including release name/version : 
- Repository or URL (if known) : 
- Service type : 
- Ports and protocols the service is listening : 

#### Log or journal information

- Log file name(s) : 

- Journal identifier or unit name : 

#### failures in sense of fail2ban filter (fail2ban must match):

```
```

#### legitimate messages (fail2ban should not consider as failures):

```
```

**Comment by sebres** [comment]
Our issue template says clearly and explicitly what is needed for a filter request.
At least an excerpt with relevant log-lines is expected.
Thus closed, Please extend your request with needed info and I'll reopen it.

**Comment by AdmiralNoisyBottom** [comment]
My apologies for not following the rules, at the time of writing my filter request I felt (incorrectly) that because every entry in the log file was to be banned; then the version, example log etc. was unnecessary. I will ensure I provide this information in the future.
