### ISSUE TITLE
[FR]: coturn.log regex filter

### ISSUE THREAD

**Issue by TheCBiker** [fail2ban/fail2ban#3708]
Is there anyone here who has a good regex filter for coturn.log.
Unfortunately I fail with this.

Thank you

### Environment:

- Fail2Ban version  :  **v0.11.2**
- OS, including release name/version : **Debian GNU/Linux 11 (bullseye)**

#### Service, project or product which log or journal should be monitored

- Service, project or product name, including release name/version : **Coturn-4.5.2**
- Ports and protocols the service is listening :  **TCP Port 5349**

#### Log or journal information
I would like to block this IP-Adresses shown in /var/log/coturn/coturn.log
I am unable to create a corresponding regex filter and am hoping for help.
```
590556: : log file opened: /var/log/coturn/coturn.log
590556: : ERROR: session 001000000000000026: TLS/TCP socket error: Connection reset by peer 87.236.176.180:39497
590589: : ERROR: session 002000000000000036: TLS/TCP socket error: Connection reset by peer 87.236.176.173:44935
590622: : ERROR: session 000000000000000030: TLS/TCP socket error: Connection reset by peer 87.236.176.167:54539
590688: : ERROR: session 002000000000000038: TLS/TCP socket error: Connection reset by peer 87.236.176.159:33173
590798: : ERROR: session 003000000000000026: TLS/TCP socket error: Connection reset by peer 87.236.176.149:37701
590831: : ERROR: session 000000000000000032: TLS/TCP socket error: Connection reset by peer 87.236.176.155:43745
590864: : ERROR: session 003000000000000027: TLS/TCP socket error: Connection reset by peer 87.236.176.160:41971
591848: : ERROR: session 002000000000000039: TCP socket error: Connection reset by peer 194.165.16.72:65461
```

#### Any additional information
My jail configuration looks like this:
```ini
[coturn]
backend = auto
enabled = true
port = 5349
protocol = tcp
filter = coturn
maxretry = 1
bantime = -1
findtime = 1h
logpath = /var/log/coturn/coturn.log
```

Thank you

**Comment by sebres** [comment]
People! We have a template for the filter request, that describe what one needs to be able to provide a filter:
At least "relevant lines from monitored log files" is expected.
Thus closed. Please extend expected info above, and I'll reopen it.

**Comment by TheCBiker** [comment]
@sebres 

sorry for my hasty request.
I hope I have all the necessary information complete.

**Comment by sebres** [comment]
Firstly the log seems not to have a timestamp, but fortunately 0.11.2 already supports `datepattern = {NONE}` (it was the first release for #2814). Without this setting it would never match, regardless failregex is correct or not.

Also this errors can be caused by instable connection of some users, so use it carefully (and increase `maxretry`, otherwise you can get false positives by first unexpected connection abort).

To test the RE (and no datepattern) try this:
```
fail2ban-regex -d '{NONE}' /var/log/coturn/coturn.log '^\s*\d+: : ERROR: session \w+: [A-Z/]+ socket error: Connection reset by peer <ADDR>:\d+'
```

And this can be used for the jail (filter-less):
```ini
[coturn]
...
filter =
failregex = ^\s*\d+: : ERROR: session \w+: [A-Z/]+ socket error: Connection reset by peer <ADDR>:\d+
datepattern = {NONE}
```
Or here is your filter:
```ini
[Definition]
failregex = ^\s*\d+: : ERROR: session \w+: [A-Z/]+ socket error: Connection reset by peer <ADDR>:\d+
datepattern = {NONE}
```

**Comment by TheCBiker** [comment]
Wow, that was quick.
Many thanks for your effort. I'll test it right away.
I would never have been able to do that

**Comment by sebres** [comment]
You are welcome...

I would also not use persistent banning here (`bantime = -1`).
Instead, you can try `bantime.increment` with initial small `bantime`, so recidive evildoers get banned for longer time (and faster) after repeated attempts, and good IPs banned by accident will experience short ban only (here 1 minute), unless they repeat it in near time.
And maxtime of 5 weeks is more than enough for this (more or less it means about 10 extra attempts from single IP per year).
Also it'd hold the ban-list small and not bother fail2ban with a lot of IPs which never come back (changed or dynamic IPs), so handle host resources sensibly.
```ini
bantime = 1m
bantime.increment = true
bantime.maxtime = 5w
```

**Comment by TheCBiker** [comment]
very good tip, thank you very much
