### ISSUE TITLE
[BR]: fail2ban complains about missing key in the default config file

### ISSUE THREAD

**Issue by merlinz01** [fail2ban/fail2ban#3714]
### Environment:

- Fail2Ban version  : 1.0.2-2
- OS, including release name/version : Debian 12
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration

### The issue:

The default config file has `allowipv6` commented out, and fail2ban complains about it.

#### Steps to reproduce
Install from Debian repository and check systemd logs.

#### Expected behavior
No warnings

#### Observed behavior
An error is logged because `allowipv6` is not defined in the config file.
`WARNING 'allowipv6' not defined in 'Definition'. Using default one: 'auto'`

### Configuration, dump and another helpful excerpts
Default config from deb install

#### Relevant parts of `journalctl -u fail2ban`:
```
fail2ban-server[577104]: 2024-04-01 17:02:35,520 fail2ban.configreader   [577104]: WARNING 'allowipv6' not defined in 'Definition'. Using default one: 'auto'
```

# The simple fix:

Uncomment line 62 in the default `fail2ban.conf`.

**Comment by sebres** [comment]
Dup of #3420.
Closed in 432e7e1e93936f09e349e80d94254e5f43d0cc8a.
