### ISSUE TITLE
[FR]: Fail2Ban stops functioning periodically without any evident reason

### ISSUE THREAD

**Issue by Apashh** [fail2ban/fail2ban#3716]
### Environment:

- Fail2Ban version: 1.0.2-2
- OS, including release name/version: Debian 12

### The issue:

Fail2Ban stops functioning periodically without any evident reason. Graylog alerts us when there are more than 500 error requests, and we've noticed that Fail2Ban doesn't seem to work during these periods. When we access the machine, Fail2Ban appears to be up and running without any errors. However, simply restarting it resolves the issue temporarily.

#### Steps to reproduce
No ideas

#### Expected behavior
We expect Fail2Ban to continue functioning without interruption, effectively banning IP addresses that trigger the defined rules.

#### Observed behavior
Fail2Ban stops banning IP addresses periodically when Graylog alerts us about more than 500 error requests.

#### Any additional information
This issue occurs periodically and seems to coincide with spikes in error requests. Fail2Ban appears to be running without errors when accessed directly on the machine. However, it stops banning IP addresses during these periods of high error requests. Restarting Fail2Ban resolves the issue temporarily.

### Configuration, dump and another helpful excerpts
Jail.conf : 
```ini
[DEFAULT]
sendername = Fail2ban
chain = DOCKER-USER
banaction = docker-all
action = %(action_mw)s[from=**emailaddress@domain.com**, password=**pass**,destination=**dest_address@domain.com**, sendername=Fail2Ban]
mta = mail
[sshd]
enabled = true
chain = INPUT
port = ssh,22
bantime = -1
maxretry = 3

[nginx-http-auth]
enabled = true
filter = nginx-http-auth
port = http,https
logpath = /var/log/container-npm/proxy-host-*_error.log
bantime = 86400
maxretry = 3

[nginx-http-auth-redirect]
enabled = true
filter = nginx-http-auth
port = http,https
logpath = /var/log/container-npm/redirection-host*_error.log
bantime = 86400
maxretry = 3

[nginx-badbots]
enabled = true
port = http,https
filter = nginx-badbots
logpath = /var/log/container-npm/proxy-host-*_access.log
bantime = 86400
maxretry = 2

[nginx-badbots-redirect]
enabled = true
port = http,https
filter = nginx-badbots
logpath = /var/log/container-npm/redirection-host*_access.log
bantime = 86400
maxretry = 2

[asm-custom-docker]
enabled = true
port = http,https
filter = asm-custom-docker
logpath = /var/log/container-npm/proxy-host-*_access.log
bantime = 86400
maxretry = 6

[asm-custom-docker-redirect]
enabled = true
port = http,https
filter = asm-custom-docker
logpath = /var/log/container-npm/redirection-host*_access.log
bantime = 86400
maxretry = 6

[nginx-nohome]
enabled = true
port = http,https
filter = nginx-nohome
logpath = /var/log/container-npm/proxy-host-*_access.log
bantime = 86400
maxretry = 2

[nginx-nohome-redirect]
enabled = true
port = http,https
filter = nginx-nohome
logpath = /var/log/container-npm/redirection-host*_access.log
bantime = 86400
maxretry = 2

[httpd-forbidden]
enabled = true
port = http,https
filter = httpd-forbidden
logpath = /var/log/container-npm/proxy-host-*_error.log
bantime = 86400
maxretry = 6

[httpd-forbidden-redirect]
enabled = true
port = http,https
filter = httpd-forbidden
logpath = /var/log/container-npm/redirection-host*_error.log
bantime = 86400
maxretry = 6
```
#### Any customizations done to /etc/fail2ban/ configuration
No custom just send log to SYSLOG (graylog)
Last LOG : 
![image](https://github.com/fail2ban/fail2ban/assets/83477029/7d3ba706-7656-4359-8e1f-aecb72ed974b)

Thanks for help !

**Comment by sebres** [comment]
1. how many jails are affected by the issue (at the time-point where "fail2ban stops to work")?
2. what does happen in fail2ban.log? does it contain some errors, especially something like `Too many errors at once ..., going idle`
3. don't you also see `[some-jail-name] Found ...` anymore for affected jails? Or it is only bans what stop to work.
4. if so, can you still ban something manually, for instance:
```
fail2ban-client set asm-custom-docker banip 192.0.2.111
fail2ban-client unbanip 192.0.2.111
```
5. is it always the same time when it stops to work? if yes, can it be the time of log-rotation?
6. how the log-rotation is done? are the monitored logs exists after log-rotation (recreated empty logs)? what do you see in monitored logs after log-rotation (few first log-lines)? do the affected services recognize the rotation and don't still continue to write in old (rotated) logs?
7. what is the banning action `docker-all` (there is no such stock action)?
8. how many bans are there? how many memory fail2ban is consuming?
9. can you try it without `action = %(action_mw)s...` (just comment it out and restart)?

And please don't provide log-excerpts as pictures.

**Comment by Apashh** [comment]
Bonjour,

Désolé de la réponse tardive.
Seulement la prison asm-custom-docker est concernée par le souci. C'est la seule qui ne ban plus du tout.

Quand je regarde le fail2ban.log, indique bien ce qu'il bannit. Pas d'erreurs précises.

Ce sont que les interdictions pour la jail asm-custom-docker qui ne fonctionnent plus.

Je vous confirme que je peux continuer de ban manuellement une adresse IP et aussi deban.

C'est souvent dimache ou lundi. En effet j'ai une rotation de log, qui s'exécute chaque semaine, il conserve 1 mois et recréé à chaque fois un log, est-ce le souci ?

DOCKER-ALL est utilisé car les logs survellés sont sous un DOCKER (nginx proxy manager) de la VM ou tourne Fail2ban.

Aujourd'hui, 11 jails tournent.

Fail2ban utilise même pas 1Go de RAM.

Cordialement,

**Comment by sebres** [comment]
> When I look at the fail2ban.log, it clearly shows what it is banning. No specific errors.

Also for mentioned jail `asm-custom-docker`?

> It's just the bans for the asm-custom-docker jail that no longer work.

Again, what exactly is doesn't work? Also this sentence contradicts with the previous sentence...

I asked 9 questions, can you please answer **all** of them, better point by point?
E. g.:
1. answer 1
2. answer 2
3. ...

> I confirm that I can continue to manually ban an IP address and also deban.

So "jail doesn't work" means, it stop to detect new findings rather? People we can't read your thoughts!..

> it keeps 1 month and recreates a log each time, is this the problem?

It depend how the rotation is done. Definitely wrong is to move part of log-file (with outdated messages) to head of log, because detection of log-file rotation will detect all them as new messages.
For proper log-rotation see [man logrotate](https://manpages.debian.org/stable/logrotate/logrotate.8.en.html).
Shortly, it'd rename rotated log (and compress it if needed) and create empty one for current log.

But it still doesn't really explain the problem to me at the moment. 
Excepting possibly the issue with a long logfile and poor regex - if there is a lot of messages (from mentioned "1 month") in log, which fail2ban consider as new, it'd start to process this messages again, if the RE is poor (slow), it make take very long time til it'd begin to process really new messages.

> Fail2ban doesn't even use 1GB of RAM.

1GB may be too heavy... which mem did you mean here (virt, res, etc)? 
Better would be the output from something like `ps aux | { head -n 1; grep 'bash'; }` 
Or even `cat /proc/$pid/status` (for fail2ban pid)...

**Comment by sebres** [comment]
Just as an idea (to ensure it's consistent handling) - maybe it is cached file in container? 
See https://github.com/fail2ban/fail2ban/issues/3779#issuecomment-2198587073

**Comment by Apashh** [comment]
Hello,

I have realized your differents points.
I will be back in few days to inform you about a problem or not ! :)

Thnak you again !
