### ISSUE TITLE
[RFE]: multi-line ignoreip doesn't handle end-of-line comments

### ISSUE THREAD

**Issue by jhgarrison** [fail2ban/fail2ban#3722]
#### Feature request type

Allow comments at end of lines in multi-line `ignoreip` settings

#### Description

Currently long `ignoreip` strings can be broken into multiple lines by starting subsequent lines with whitespace. For example

```
ignoreip =
    166.128.0.0/9 107.64.0.0/10          # AT&T
    127.0.0.0/8                                     # Localhost
    24.20.0.0/15 24.16.0.0/13 70.56.0.0/14          # Comcast
    97.112.0.0/12 174.174.0.0/17                    # Comcast
```

Those comments at the end of each line are not treated as comments, resulting in this:

```
$ sudo fail2ban-client get postfix ignoreip
These IP addresses/networks are ignored:
|- #
|- AT&T
|- 127.0.0.0/8
|- Localhost
|- 24.20.0.0/15
|- 24.16.0.0/13
|- 70.56.0.0/14
|- Comcast
|- 97.112.0.0/12
`- 174.174.0.0/17
```

It would be nice to be able to add end-of-line comments when ignoring multiple groups of ip addresses.

Note: This really straddles the line between a bug report and RFE, since adding text strings and `#` to the list of ignored IPs is probably incorrect.

**Comment by sebres** [comment]
IIRC, inline comments at end of line in pythons ini-files should be started with semi-colon and space:
```ini
ignoreip =
    192.0.2.1          ; first
    192.0.2.2          ; second
```
Related to [man jail.conf.5 # CONFIGURATION_FILES_FORMAT](https://manpages.debian.org/bookworm/fail2ban/jail.conf.5.en.html#CONFIGURATION_FILES_FORMAT):

*Comments: use '#' for comment lines and '; ' (space is important) for inline comments.*

Alternatively, if inline comments don't work for you (I didn't test it with multi-line), use it in this way:
```ini
ignoreip =
    # first:
    192.0.2.1
    # second:
    192.0.2.2
```

Dup of #226

**Comment by Chealer** [comment]
Thank you for reporting Jim and thank you for the workaround @sebres 

Note that this does not duplicate #226, which is about a failure to start.

**Comment by sebres** [comment]
> thank you for the workaround

This is not a workaround at all - it is the way how one'd configure regularly.

> Note that this does not duplicate #226, which is about a failure to start.

Well, it is. Because the errors may be simply the after-effect of the misconfiguration.

**Comment by Chealer** [comment]
@sebres wrote:
> > thank you for the workaround
> 
> This is not a workaround at all - it is the way how one'd configure regularly.

Right. I did not mean the alternative is inferior and should be used temporarily; all I meant by "workaround" in this case is that it allows avoiding the reported issue.

> > Note that this does not duplicate [#226](https://github.com/fail2ban/fail2ban/issues/226), which is about a failure to start.
> 
> Well, it is. Because the errors may be simply the after-effect of the misconfiguration.

Sorry, I am not sure which errors you refer to or what your point is.

**Comment by sebres** [comment]
> Sorry, I am not sure which errors you refer to or what your point is.

> which is about a >> **failure to start** <<.

That errors.

**Comment by Chealer** [comment]
I think I understand what you meant Sergey. The failure to start tracked in #226 must indeed be caused by a misinterpretation of the configuration. And both this issue and #226 likely have the same technical cause (misinterpretation of hashes). All I was saying is that this report does not duplicate #226.
