### ISSUE TITLE
[FR]: sshd_filter not matching password authentication failed log line

### ISSUE THREAD

**Issue by aikooo7** [fail2ban/fail2ban#3730]
Be aware I am using linuxserver docker image but since the filter is the same and probably pulled from here I decided to do the issue here.

### Environment:

- Fail2Ban version  :  v1.0.2
- OS, including release name/version : Information inside docker:
NAME="Alpine Linux"                                                    VERSION_ID=3.19.1

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : sshd
- Service, project or product name, including release name/version : sshd
- Repository or URL (if known) : 
- Service type : remote access 
- Ports and protocols the service is listening : 2222

#### Log or journal information

- Log file name(s) : ssh.log, pulled from /var/log/messages using auth.* regex pattern.

#### failures in sense of fail2ban filter (fail2ban must match):

```
Apr 28 13:11:39 localhost auth.info sshd[27366]: Failed password for REDACTED_USER from REDACTED_IP port 38066 ssh2
```

**Comment by sebres** [comment]
The reason for that is unexpected prefix - `auth.info` between hostname and service name (`localhost auth.info sshd`) is normally not present in log.

Either you'd change the format if syslog or whatever, so it would not generate that (no idea where one can change it)...

Or you adjust the prefix-line (e. g. rewrite default hostname of common prefix-line), either in `jail.local` for sshd jail only:
```ini
[sshd]
filter = %(known/filter)s[__hostname="\S+(?: [a-z]+\.[a-z]+)?"]
```
Or in `filter.d/common.local` for all jails based on common-include:
```ini
[DEFAULT]
__hostname = \S+(?: [a-z]+\.[a-z]+)?
```

**Comment by aikooo7** [comment]
> The reason for that is unexpected prefix - `auth.info` between hostname and service name (`localhost auth.info sshd`) is normally not present in log.
> 
> Either you'd change the format if syslog or whatever, so it would not generate that (no idea where one can change it)...
> 
> Or you adjust the prefix-line (e. g. rewrite default hostname of common prefix-line), either in `jail.local` for sshd jail only:
> ```ini
> [sshd]
> filter = %(known/filter)s[__hostname="\S+(?: [a-z]+\.[a-z]+)?"]
> ```
> Or in `filter.d/common.local` for all jails based on common-include:
> ```ini
> [DEFAULT]
> __hostname = \S+(?: [a-z]+\.[a-z]+)?
> ```

Hey!

I used your first method and it worked flawlessly, thank you so much.

For me this is fixed so I am going to close the issue.
