### ISSUE TITLE
[BR]:  basic setup fail

### ISSUE THREAD

**Issue by fbifido** [fail2ban/fail2ban#3736]
debian 12.5 minimal with ssh

apt install fail2ban
nano /etc/fail2ban/jail.conf , find [sshd], add maxretry =3, enable = true
reboot now.
- everything is working.

- I was told not to modify any *.conf file, no i created an empty jail.local file, then paste this in:
[sshd]
port    = ssh
logpath = %(sshd_log)s
backend = %(sshd_backend)s
maxretry = 3
enable = true

after reboot only getting this error message:
"[519]: ERROR  Failed during configuration: Have not found any log file for sshd jail"
Apr 30 14:06:54 koha-01 systemd[1]: fail2ban.service: Main process exited, code=exited, status=255/EXCEPTION
Apr 30 14:06:54 koha-01 systemd[1]: fail2ban.service: Failed with result 'exit-code'.

I know little about linux, but how hard is it to follow a simple tutorial and have it work:
https://www.howtogeek.com/675010/how-to-secure-your-linux-computer-with-fail2ban/

**Comment by mrkacg1** [comment]
hi,
change in jail config: backend=systemd

**Comment by sebres** [comment]
Dup of #3292, already fixed in newest version.
