### ISSUE TITLE
Not working filter apache logs

### ISSUE THREAD

**Issue by mrkacg1** [fail2ban/fail2ban#3737]
Version: 1.0.2
Debian 12.5

I have created the filter in jail.local:

[apache-404]
enabled = true
port = http, https
filter=apache-404
logpath = /var/log/apache/*access*.log
bantime = 172800
findtime = 600
maxretry = 5

Filter:
[Definition]
failregex = ^<HOST> - .* "(GET|POST|HEAD).*HTTP.*" (404|444|403|400|301) .*$

#Ignorar, no aplica
ignoreregex =.*(robots.txt|favicon.ico|jpg|png)

But it does not work.

What seems strange to me is that the filter does not show the apache files

![image](https://github.com/fail2ban/fail2ban/assets/26174637/1e5eaf08-8a2b-4136-a154-a69e22b6a28a)

Other server config - Debian 10 - Fail2ban 0.10.2 - Working

![image](https://github.com/fail2ban/fail2ban/assets/26174637/8d131a13-adaa-4812-98b2-f01a445b53c0)

The difference may be that debian 10: backend=auto - Debian 15: backend=systemd

I had to configure backend=systemd, because I got the error: Failed during configuration: Have not found any log file for sshd jail

**Comment by sebres** [comment]
> I had to configure backend=systemd, because I got the error: Failed during configuration: Have not found any log file for sshd jail

You have to do that only for jail `sshd` (section `[sshd]`). If for contrary it will be set for default section, every jail without own setting of backend will get this default value. In this case you have to add `backend = auto` to `[apache-404]`.
