### ISSUE TITLE
[BR]: ERROR No module named 'asynchat' on Ubuntu 24.04

### ISSUE THREAD

**Issue by imar-io** [fail2ban/fail2ban#3755]
### Environment:

- Fail2Ban version: 1.0.2-3
- OS, including release name/version: Ubuntu 24.04  
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

![fail2ban](https://github.com/fail2ban/fail2ban/assets/44345442/be009a8a-41e8-41f3-a287-39bf9fc3ee6f)

I have installed fail2ban on a freshly set up Ubuntu 24.04 and am receiving the error shown in the screenshot. No configuration or similar has been modified

#### Steps to reproduce

apt update
apt dist-upgrade -y
apt install fail2ban -y

**Comment by JonnyBDev** [comment]
This is related to an unsupported Python version in the new Ubuntu 24.04. Fail2ban already updated their package to be compatible with the used version of Python, but updates can take a while to reach stable within the main ubuntu repo.

Workaround is to manually install the latest fail2ban version.

Commands to past into your terminal (stolen from https://www.airix.net/index.php?option=com_content&view=article&id=89&catid=35&Itemid=149)
```
cd /tmp/
# 1) download deb package and signature:
wget -O fail2ban.deb https://github.com/fail2ban/fail2ban/releases/download/1.1.0/fail2ban_1.1.0-1.upstream1_all.deb
wget -O fail2ban.deb.asc https://github.com/fail2ban/fail2ban/releases/download/1.1.0/fail2ban_1.1.0-1.upstream1_all.deb.asc

# 2) check signature (if you want to be sure file is unmodified):
gpg --verify fail2ban.deb.asc fail2ban.deb

# 3) view details of the package:
dpkg -I fail2ban.deb

# 4) to ensure the upgrade run gentler (protocol of previous version may be incompatible), stop fail2ban before install:
# using service:
sudo service fail2ban stop

# 5a) install package using dpkg (standalone package, don't regard dependencies):
sudo dpkg -i fail2ban.deb
# if the package introduces some "broken" dependencies (I don't think so in case of fail2ban which has few dependencies),
# to fix the unmet dependency issue, run this:
sudo apt -f install
```

**Comment by sebres** [comment]
Dup of #3754 (and basically of #3487, where it was fixed and newer version is released).

**Comment by Stemist** [comment]
This issue affected me today. Thank you for posting this!

**Comment by alexdcodes** [comment]
Basically put the above into a script to add [Fail2ban.sh](https://github.com/alexdcodes/ConfigureUbuntu/blob/main/fail2ban/install.sh)

**Comment by GwynethLlewelyn** [comment]
Perfect, works like a charm!

Consider `sudo systemctl stop fail2ban` instead of `sudo service fail2ban stop` — we hope that one day fail2ban may be fully systemd-compliant and not require the 'old school' scripts any longer, and, as such, that information might be useful for those searching on Google in the far future 😸

**Comment by sebres** [comment]
> Consider `sudo systemctl stop fail2ban` instead of `sudo service fail2ban stop`

Both are aliases in systemd environment, unless you still have some init-scripts, because `service` would prefer sysvinit, otherwise it is just a wrapper to `systemctl`.
So if they behave differently for you, maybe there are some "surviving" init-scripts (check `/etc/init.d` directory).

> we hope that one day fail2ban may be fully systemd-compliant and not require the 'old school' scripts any longer

It is... already long long time.

**Comment by william20210206** [comment]
#3754 is the BEST and easiest way to solve the  problem
