### ISSUE TITLE
[FR]: Wordpress Fail2ban filter not processing authentication failures on Debian bookworm

### ISSUE THREAD

**Issue by shaneonabike** [fail2ban/fail2ban#3756]
Hi there,

Thanks so much for fail2ban and all your amazing work. I'm trying to get wp-fail2ban to integrate with Debian bookwork (their new journalctl) and struggling for the last few days. After I have a solution I'm going to post it on their forums for others. It's a pretty great integration with fail2ban. Any help would be really appreciated!

### Environment:

- Fail2Ban version  : 1.0.2 
- [x] Fail2Ban installed via OS/distribution mechanism
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration via a new filter.d (see below)  
- OS: Debian bookworm 
- Installed perl-systemd to get Systemd logging
- Using Wordpress [WP-Fail2ban Plugin](https://wordpress.org/plugins/wp-fail2ban/)

#### Service, project or product which log or journal should be monitored

Fail2ban ships with (one) of the following fail2ban confs:

```
WP-F# Fail2Ban filter for hard failures
# Auto-generated: 2024-01-28T18:48:23+00:00
#

[INCLUDES]

before = common.conf

[Definition]

_daemon = (?:wordpress|wp)

failregex = ^%(__prefix_line)sUntrusted X-Forwarded-For header from <HOST>$
            ^%(__prefix_line)sREST authentication attempt for unknown user .* from <HOST>$
            ^%(__prefix_line)sXML-RPC authentication attempt for unknown user .* from <HOST>$
            ^%(__prefix_line)sImmediately block connections from <HOST>$
            ^%(__prefix_line)sBlocked access from country '..' from <HOST>$
            ^%(__prefix_line)sXML-RPC request blocked from <HOST>$
            ^%(__prefix_line)s.*; Bogus Pingback from <HOST>$
            ^%(__prefix_line)sAkismet discarded spam comment from <HOST>$
            ^%(__prefix_line)sSpam comment \d+ from <HOST>$
            ^%(__prefix_line)sBlocked authentication attempt for .* from <HOST>$
            ^%(__prefix_line)sXML-RPC multicall authentication failure from <HOST>$
            ^%(__prefix_line)sPingback error .* generated from <HOST>$
            ^%(__prefix_line)sBlocked user enumeration attempt from <HOST>$

ignoreregex =

# DEV Notes:
# Requires the 'WP fail2ban' plugin:
# https://wp-fail2ban.com/
#
# Author: Charles Lecklider

```
On other OS systems (or previous Debian versions) we could simply use this and the logs worked, but now that all logs goes through JournalCtl it's a bit more complicated. To get it working I had to push out the logs (created by the plugin) to ```LOCAL0``` as ```LOCAL_AUTH``` and the other logs were not appearing. ``LOCAL0``` is working and I can see the entries in JournalCtl perfectly.

In my custom ```jail.d/wordpress.conf``` I have (because the logs are actually going to the Php service:

```
[wordpress-hard]
enabled = true
filter = wordpress-hard
backend = systemd
journalmatch = _SYSTEMD_UNIT=php8.0-fpm.service
# + SYSLOG_FACILITY=4 Do I need this?
maxretry = 1
port = http,https

```

#### Log or journal information

JournalCtl output looks like this (in debug mode)

```
_MACHINE_ID=abc
_HOSTNAME=bees
_RUNTIME_SCOPE=system
_SYSTEMD_SLICE=system.slice
PRIORITY=5
SYSLOG_FACILITY=4
_UID=123
_GID=123
_COMM=php-fpm8.0
_EXE=/usr/sbin/php-fpm8.0
_CMDLINE="php-fpm: pool www"
_SYSTEMD_CGROUP=/system.slice/php8.0-fpm.service
_SYSTEMD_UNIT=php8.0-fpm.service
_SYSTEMD_INVOCATION_ID=83f5ad502bae46dabccfd4cc04c9f1ac
SYSLOG_IDENTIFIER=wordpress(mysite.com)
SYSLOG_PID=228148
SYSLOG_TIMESTAMP=Jun  5 03:35:00 
MESSAGE=Blocked user enumeration attempt from 77.220.193.76
_PID=228148
_SOURCE_REALTIME_TIMESTAMP=1717572900121955
__CURSOR=s=627d8de0bbd9433fb0f114e19cc9dd1e;i=2bfe33;b=c2842ca3b7d545baae2a842a243768f8;m=27b1af43aa7;t=6>
__REALTIME_TIMESTAMP=1717572972678906
__MONOTONIC_TIMESTAMP=2727756446375
_BOOT_ID=c2842ca3b7d545baae2a842a243768f8
_TRANSPORT=syslog
PRIORITY=6
_SELINUX_CONTEXT
```
So I used the information above to determine that I should use ```journalmatch = _SYSTEMD_UNIT=php8.0-fpm.service```

#### Fail2ban-client status

```
Status for the jail: wordpress-hard
|- Filter
|  |- Currently failed:	0
|  |- Total failed:	0
|  `- Journal matches:	_SYSTEMD_UNIT=php8.0-fpm.service
`- Actions
   |- Currently banned:	0
   |- Total banned:	0
   `- Banned IP list:	
   ```

### Fail2ban-regex

```
fail2ban-regex systemd-journal[journalflags=1] wordpress-hard -D

Running tests
=============

Use   failregex filter file : wordpress-hard, basedir: /etc/fail2ban
Use      datepattern : {^LN-BEG} : Default Detectors
Use         systemd journal
Use         encoding : UTF-8


Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:

Lines: 946814 lines, 0 ignored, 0 matched, 946814 missed
[processed in 31.13 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all 946814 lines
```

Using ```systemd-journal[journalflags=1]``` or without the extra ```[journalflags=1]``` doesn't seem to change anything (I read somewhere else that this might help).

## Questions

- Is there any suggestions as to how I can tweak the filter.d file to work ? I don't really understand why it's not picking up the things properly. Previous Debian did work and I feel it has something to do with how I am specifying where it should fine things via ```journalmatch``` but that could be a false clue.
- Is there a way to specify a different ```journalmatch``` that isn't php8.0 related, because I'm worried that if I upgrade at some point to the latest PHP it would break things (and I prefer a more generic solution)

Thanks again for any advice you might be able to provide

**Comment by sebres** [comment]
I guess it may be something with prefix-ine, e. g. `_daemon = (?:wordpress|wp)` or whatever...
Especially if I see `SYSLOG_IDENTIFIER=wordpress(mysite.com)`, I guess the abovemention message would look like:
```
Jun  5 03:35:00 host wordpress(mysite.com)[228148]: Blocked user enumeration attempt from 192.0.2.76
```
it looks like for this the _daemon must be something like that:
```
_daemon = (?:wordpress|wp)(?:\([^\)]*\))?
```
*(next time please provide an excerpt from journal with at least one message (plain) you want to match.)*

You can also rewrite it without common include and prefix-line:
```ini
failregex = ^\s*\w+ (?:wordpress|wp)(?:\([^\)]*\))?\[\d+\]: Blocked user enumeration attempt from <ADDR>
# or with own prefix-line:
__prefix_line = \s*\w+ (?:wordpress|wp)(?:\([^\)]*\))?\[\d+\]:\s
failregex = ^%(__prefix_line)sBlocked user enumeration attempt from <ADDR>
```

By the way, you could combine all the REs to single `failregex` (it'd make the search many times faster)...
For example:
```ini
failregex = ^\s*\w+ (?:wordpress|wp)(?:\([^\)]*\))?\[\d+\]: (?:Blocked user enumeration attempt|Untrusted X-Forwarded-For header|...) from <ADDR>$
```
(`<ADDR>` is also faster and more precise than `<HOST>` if only IPs and no hostname expected)

**Comment by shaneonabike** [comment]
Nice this is amazing @sebres  thank you so much! I especially appreciate the optimization tips to make it perform faster and better! I'll post that to the developer to hopefully make the changes

Sorry about not providing a full log example. In fact, mine are a bit different (including here for others to see to help)

```2024-06-06T07:39:58.980111-04:00 bees wordpress(mysite.com)[420757]: Blocked authentication attempt for admin from 104.244.78.186```

I had to tweak it slightly because the date was different and wouldn't resolve. I have no idea why JournalCtl has such a strange date but whatever.

```
failregex = ([^\s]+)\s+(?:wordpress|wp)(?:\([^\)]*\))?\[\d+\]: (?:Empty username|Authentication failure fo
r .*|REST authentication failure for .*|XML-RPC authentication failure for .*|Authentication attempt for u
nknown user .*|Blocked username authentication attempt for .*|Pingback requested from|Comment attempt on .
* post \d+) from <ADDR>$

```

Now it's finding 2580 hits via regex so we are in business :fireworks:

Thanks again!

**Comment by shaneonabike** [comment]
BTW I wanted to ask about the second question I had. In terms of the journalmatch there really isn't an easy solution for that I would imagine because I can't just do ```_SYSTEMD_UNIT=php8.*-fpm.service``` where ```*``` represents any version of PHP?

**Comment by shaneonabike** [comment]
Interesting and you're right I don't need to capture that.

I tried again with your suggestion and I think I found the problem `\s*` seems to trip it up. When I use the following it works! I'm not awesome at regex but the research I found ```\w*``` is ok to grab all alphanumeric.

```
^\w* (?:wordpress|wp)(?:\([^\)]*\))?\[\d+\]: (?:Empty username|Authentication failure for .*|REST authentication failure for .*|XML-RPC authentication failure for .*|Authentication attempt for unknown user .*|Blocked username authentication attempt for .*|Pingback requested from|Comment attempt on .* post \d+) from <ADDR>$
```
```
fail2ban-regex systemd-journal "^\w* (?:wordpress|wp)(?:\([^\)]*\))?\[\d+\]: (?:Empty username|Authentication failure for .*|REST authentication failure for .*|XML-RPC authentication failure for .*|Authentication attempt for unknown user .*|Blocked username authentication attempt for .*|Pingback requested from|Comment attempt on .* post \d+) from <ADDR>$"

Running tests
=============

Use   failregex line : ^\w* (?:wordpress|wp)(?:\([^\)]*\))?\[\d+\]: (?:Em...
Use         systemd journal
Use         encoding : UTF-8


Results
=======

Failregex: 2725 total
|-  #) [# of hits] regular expression
|   1) [2725] ^\w* (?:wordpress|wp)(?:\([^\)]*\))?\[\d+\]: (?:Empty username|Authentication failure for .*|REST authentication failure for .*|XML-RPC authentication failure for .*|Authentication attempt for unknown user .*|Blocked username authentication attempt for .*|Pingback requested from|Comment attempt on .* post \d+) from <ADDR>$
`-

Ignoreregex: 0 total

Lines: 1031487 lines, 0 ignored, 2725 matched, 1028762 missed
[processed in 26.78 sec]
```

**Comment by sebres** [comment]
> `\s*` seems to trip it up...

No, `\s*` is not an issue at all - `*` means as many spaces as possible, but 0 spaces is also alright.

> I found `\w*` is ok to grab all alphanumeric

Sure, but even there `*` means 0, whereas in my variant it has `+` (at least one char), because it'd match a hostname (`bees` in your case), so I don't really follow the issue with my prefix,
because `^\s*\w+ (?:wordpress|wp)...` must pretty well match `bees wordpress...`.

Maybe the API doesn't insert `bees` for whatever reason, so it starts directly with `wordpress...` (then it'd deviate from `journalctl` output)...

Just for people want debug it deeper: the only possibility to follow the problem is either `--print-all-missed` argument for `fail2ban-regex`, to see the message how fail2ban gets it.

Or using debug level:
```
fail2ban-regex -l 5 ... | grep 'Looking for match'
```
would show something like this (containing a tuple with message that fail2ban will really process with `failregex`):
```
... Looking for match of [('', 'Jun  5 03:35:00', ' host wordpress(mysite.com)[228148]: ...
```
