### ISSUE TITLE
[BR]:The jail set in the configuration file is not loaded

### ISSUE THREAD

**Issue by tigerJX95** [fail2ban/fail2ban#3758]
### Environment:

- Fail2Ban version  : 1.1.0
- OS, including release name/version : Rockylinux9.3, python version python3.9
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

 
    Hello author, I am finding a problem with your latest version of  1.1.0, and I would like to ask you here. First of all, I downloaded the source code zip package from github, and then unzipped it and installed it to the system according to your method, and then I used my other centos7 system that also runs this fail2ban to copy the configuration, and put it in the same directory without any changes, and then restart the service, no error was found, and the service was successfully started, but it was only started, and the custom jail in the configuration file was not loaded. 
    I looked at /var/log/fail2ban.log and found that there was only a message about the service starting and connecting to the database, and there was no information about the creation of a jail. If you run the fail2ban-client status view, you can find that the number of jail is 0 and the jail list is empty.(The screenshot is at the end of the article)
    For the same configuration, I am running fine under centos 7.9 fail2ban version 0.11.2, and the corresponding jail configuration creation information can be viewed in the log files.
    The first time I asked on github, I was a little overwhelmed, but I thought it was a good start. I hope you can help me, thanks.

![QQ图片20240606084032](https://github.com/fail2ban/fail2ban/assets/169267775/d588a378-ef58-49a4-807b-6f9769fc2887)

![QQ图片20240606084022](https://github.com/fail2ban/fail2ban/assets/169267775/974bbedd-cdc6-4dc3-8cdb-e8e9c3e61639)

#### Any customizations done to /etc/fail2ban/ configuration

```
```

#### Relevant parts of /var/log/fail2ban.log file:
!

```

```

#### Relevant lines from monitored log files:

```
```

**Comment by sebres** [comment]
> Hello author, I am finding a problem with your latest version of  1.1.0...

No, you don't.

> and the custom jail in the configuration file was not loaded. 

Normally the config directory is `/etc/fail2ban` and custom jail is either in `/etc/fail2ban/jail.local` or `/etc/fail2ban/jail.d/*.conf`...
Is it? (you didn't provided any info how exactly it is configured).

However this path may differ depending on distro and kind of installation (different root-path), etc.

You can check which config files are loaded (and which jails need to be) with:
```
fail2ban-client -vvvd
```

Also is this jail enabled? I mean does it have `enabled = true` in the jail section?

> For the same configuration, I am running fine under centos 7.9 fail2ban version 0.11.2, and the corresponding jail ...

Well I guess it is installed via packet manager of the distro and not manually?..
In the case of manual install from source it depends on many factors why it may differ.
One large difference - no one jail is enabled in stock fail2ban by default, in opposite to distro-package, where it may be done by the maintainers (e. g. IIRC debian package enables sshd jail by default).

**Comment by tigerJX95** [comment]
In centos 7.9, my config file sshd.local is placed under /etc/fail2ban/jail.d/, but this does not apply under rocky9.3, and the service will be reported with an error. I tried putting it under /etc/fail2ban/ and then the service started normally.


I ran the command you gave fail2ban-client -vvvd, and here is the result, it should be that jail.local is not loaded, I don't know what the reason is

 +   71 7F1AA9660740 fail2ban.configreader     INFO  Loading configs for fail2ban under /etc/fail2ban
 +   72 7F1AA9660740 fail2ban.configreader     DEBUG Reading configs for fail2ban under /etc/fail2ban
 +   72 7F1AA9660740 fail2ban.configreader     DEBUG Reading config files: /etc/fail2ban/fail2ban.conf
 +   73 7F1AA9660740 fail2ban.configparserinc  INFO    Loading files: ['/etc/fail2ban/fail2ban.conf']
 +   73 7F1AA9660740 fail2ban.configparserinc  TRACE     Reading file: /etc/fail2ban/fail2ban.conf
 +   74 7F1AA9660740 fail2ban.configparserinc  INFO    Loading files: ['/etc/fail2ban/fail2ban.conf']
 +   74 7F1AA9660740 fail2ban.configparserinc  TRACE     Shared file: /etc/fail2ban/fail2ban.conf
 +   74 7F1AA9660740 fail2ban                  INFO  Using socket file /var/run/fail2ban/fail2ban.sock
 +   74 7F1AA9660740 fail2ban                  INFO  Using pid file /var/run/fail2ban/fail2ban.pid, [INFO] logging to /var/log/fail2ban.log
 +   75 7F1AA9660740 fail2ban.configreader     INFO  Loading configs for jail under /etc/fail2ban
 +   75 7F1AA9660740 fail2ban.configreader     DEBUG Reading configs for jail under /etc/fail2ban
 +   75 7F1AA9660740 fail2ban.configreader     DEBUG Reading config files: /etc/fail2ban/jail.conf
 +   76 7F1AA9660740 fail2ban.configparserinc  INFO    Loading files: ['/etc/fail2ban/jail.conf']
 +   76 7F1AA9660740 fail2ban.configparserinc  TRACE     Reading file: /etc/fail2ban/jail.conf
 +   82 7F1AA9660740 fail2ban.configparserinc  INFO    Loading files: ['/etc/fail2ban/paths-debian.conf']
 +   83 7F1AA9660740 fail2ban.configparserinc  TRACE     Reading file: /etc/fail2ban/paths-debian.conf
 +   83 7F1AA9660740 fail2ban.configparserinc  INFO    Loading files: ['/etc/fail2ban/paths-common.conf']
 +   83 7F1AA9660740 fail2ban.configparserinc  TRACE     Reading file: /etc/fail2ban/paths-common.conf
 +   84 7F1AA9660740 fail2ban.configparserinc  INFO    Loading files: ['/etc/fail2ban/paths-overrides.local']
 +   84 7F1AA9660740 fail2ban.configparserinc  TRACE     Reading file: /etc/fail2ban/paths-overrides.local
 +   85 7F1AA9660740 fail2ban.configparserinc  INFO    Loading files: ['/etc/fail2ban/paths-common.conf', '/etc/fail2ban/paths-debian.conf', '/etc/fail2ban/jail.conf']
 +   85 7F1AA9660740 fail2ban.configparserinc  TRACE     Shared file: /etc/fail2ban/paths-common.conf
 +   85 7F1AA9660740 fail2ban.configparserinc  TRACE     Shared file: /etc/fail2ban/paths-debian.conf
 +   85 7F1AA9660740 fail2ban.configparserinc  TRACE     Shared file: /etc/fail2ban/jail.conf
 +   85 7F1AA9660740 fail2ban.configreader     DEBUG 'allowipv6' not defined in 'Definition'. Using default one: 'auto'
['set', 'syslogsocket', 'auto']
['set', 'loglevel', 'INFO']
['set', 'logtarget', '/var/log/fail2ban.log']
['set', 'allowipv6', 'auto']
['set', 'dbfile', '/var/lib/fail2ban/fail2ban.sqlite3']
['set', 'dbmaxmatches', 10]
['set', 'dbpurgeage', '1d']
 +   91 7F1AA9660740 fail2ban                  DEBUG Exit with code 0
=========================================================================


The content of my jail profile is very simple, as follows, the enable option is turned on.

[sshd]
enabled = true
port   = ssh
action = iptables[name=SSH, port=22, protocol=tcp]
logpath = /var/log/secure
backend = %(sshd_backend)s
bantime = 12h
findtime = 6h
maxretry = 3

As mentioned above, if the information I provided is incorrect, please also correct it, thank you.

**Comment by sebres** [comment]
Related to verbose output above it does not want to load from `/etc/fail2ban/jail.d/*` at all.
I have no idea why it not work on your side (permissions? selinux policies? etc), but normally it must.
To test it I put this to `/etc/fail2ban/jail.d/xxx.local`:
```ini
[xxx]
enabled = true
logpath = /var/log/auth.log
filter =
failregex = 'test <ADDR>'
```
<details>
<summary>and stock fail2ban 1.1.0 shows this (as expected)...</summary>

```
$ fail2ban-client -vvvd
 +   30 7FC8CDE6D040 fail2ban.configreader     INFO  Loading configs for fail2ban under /etc/fail2ban
 +   30 7FC8CDE6D040 fail2ban.configreader     DEBUG Reading configs for fail2ban under /etc/fail2ban
 +   30 7FC8CDE6D040 fail2ban.configreader     DEBUG Reading config files: /etc/fail2ban/fail2ban.conf
 +   30 7FC8CDE6D040 fail2ban.configparserinc  INFO    Loading files: ['/etc/fail2ban/fail2ban.conf']
 +   30 7FC8CDE6D040 fail2ban.configparserinc  TRACE     Reading file: /etc/fail2ban/fail2ban.conf
 +   31 7FC8CDE6D040 fail2ban.configparserinc  INFO    Loading files: ['/etc/fail2ban/fail2ban.conf']
 +   31 7FC8CDE6D040 fail2ban.configparserinc  TRACE     Shared file: /etc/fail2ban/fail2ban.conf
 +   31 7FC8CDE6D040 fail2ban                  INFO  Using socket file /var/run/fail2ban/fail2ban.sock
 +   31 7FC8CDE6D040 fail2ban                  INFO  Using pid file /var/run/fail2ban/fail2ban.pid, [INFO] logging to /var/log/fail2ban.log
 +   31 7FC8CDE6D040 fail2ban.configreader     INFO  Loading configs for jail under /etc/fail2ban
 +   31 7FC8CDE6D040 fail2ban.configreader     DEBUG Reading configs for jail under /etc/fail2ban
 +   31 7FC8CDE6D040 fail2ban.configreader     DEBUG Reading config files: /etc/fail2ban/jail.conf, /etc/fail2ban/jail.local, /etc/fail2ban/jail.d/xxx.local
 +   32 7FC8CDE6D040 fail2ban.configparserinc  INFO    Loading files: ['/etc/fail2ban/jail.conf']
 +   32 7FC8CDE6D040 fail2ban.configparserinc  TRACE     Reading file: /etc/fail2ban/jail.conf
 +   35 7FC8CDE6D040 fail2ban.configparserinc  INFO    Loading files: ['/etc/fail2ban/paths-debian.conf']
 +   35 7FC8CDE6D040 fail2ban.configparserinc  TRACE     Reading file: /etc/fail2ban/paths-debian.conf
 +   35 7FC8CDE6D040 fail2ban.configparserinc  INFO    Loading files: ['/etc/fail2ban/paths-common.conf']
 +   35 7FC8CDE6D040 fail2ban.configparserinc  TRACE     Reading file: /etc/fail2ban/paths-common.conf
 +   36 7FC8CDE6D040 fail2ban.configparserinc  INFO    Loading files: ['/etc/fail2ban/paths-overrides.local']
 +   36 7FC8CDE6D040 fail2ban.configparserinc  TRACE     Reading file: /etc/fail2ban/paths-overrides.local
 +   36 7FC8CDE6D040 fail2ban.configparserinc  INFO    Loading files: ['/etc/fail2ban/jail.local']
 +   36 7FC8CDE6D040 fail2ban.configparserinc  TRACE     Reading file: /etc/fail2ban/jail.local
 +   36 7FC8CDE6D040 fail2ban.configparserinc  INFO    Loading files: ['/etc/fail2ban/jail.d/xxx.local']
 +   36 7FC8CDE6D040 fail2ban.configparserinc  TRACE     Reading file: /etc/fail2ban/jail.d/xxx.local
 +   37 7FC8CDE6D040 fail2ban.configparserinc  INFO    Loading files: ['/etc/fail2ban/paths-common.conf', '/etc/fail2ban/paths-debian.conf', '/etc/fail2ban/jail.conf', '/etc/fail2ban/jail.local', '/etc/fail2ban/jail.d/xxx.local']
 +   37 7FC8CDE6D040 fail2ban.configparserinc  TRACE     Shared file: /etc/fail2ban/paths-common.conf
 +   37 7FC8CDE6D040 fail2ban.configparserinc  TRACE     Shared file: /etc/fail2ban/paths-debian.conf
 +   37 7FC8CDE6D040 fail2ban.configparserinc  TRACE     Shared file: /etc/fail2ban/jail.conf
 +   37 7FC8CDE6D040 fail2ban.configparserinc  TRACE     Shared file: /etc/fail2ban/jail.local
 +   37 7FC8CDE6D040 fail2ban.configparserinc  TRACE     Shared file: /etc/fail2ban/jail.d/xxx.local
 +   37 7FC8CDE6D040 fail2ban.configreader     DEBUG 'allowipv6' not defined in 'Definition'. Using default one: 'auto'
...
 +   49 7FC8CDE6D040 fail2ban.jailreader       WARNI No filter set for jail xxx
['set', 'syslogsocket', 'auto']
['set', 'loglevel', 'INFO']
['set', 'logtarget', '/var/log/fail2ban.log']
['set', 'allowipv6', 'auto']
['set', 'dbfile', '/var/lib/fail2ban/fail2ban.sqlite3']
['set', 'dbmaxmatches', 10]
['set', 'dbpurgeage', '1d']
['add', 'xxx', 'auto']
['set', 'xxx', 'usedns', 'warn']
['set', 'xxx', 'addfailregex', "'test <ADDR>'"]
['set', 'xxx', 'maxretry', 5]
['set', 'xxx', 'maxmatches', 5]
['set', 'xxx', 'findtime', '10m']
['set', 'xxx', 'bantime', '10m']
['set', 'xxx', 'ignorecommand', '']
['set', 'xxx', 'logencoding', 'auto']
['set', 'xxx', 'addlogpath', '/var/log/auth.log', 'head']
['set', 'xxx', 'addaction', 'nftables']
['multi-set', 'xxx', 'action', 'nftables', ...]
...
['start', 'xxx']
```
</details>

Thereby this message is significant and doesn't look like in your case:
```
... INFO    Loading files: [..., '/etc/fail2ban/jail.conf', '/etc/fail2ban/jail.local', '/etc/fail2ban/jail.d/xxx.local']
```
So on your side I would expect something like this:
```diff
- +   85 7F1AA9660740 fail2ban.configparserinc  INFO    Loading files: [..., '/etc/fail2ban/jail.conf']
+ +   85 7F1AA9660740 fail2ban.configparserinc  INFO    Loading files: [..., '/etc/fail2ban/jail.conf', '/etc/fail2ban/jail.d/sshd.local']
```
So assuming that file `/etc/fail2ban/jail.d/sshd.local` is somehow "invisible" for fail2ban. And as already said, guessing something like permissions, SELinux or whatever.

If you cannot find out what is wrong with `jail.d/sshd.local`, you can try to put all your jails to `/etc/fail2ban/jail.local` (single file for many jails)... Hope this'd help.

**Comment by tigerJX95** [comment]
I'm sorry, but I'm not very good at using some of github's features. I'll learn to use it well, though. Now I've finally figured out what the problem is, the reason is that the logpath is not specified, so I specified the log path for /var/log/secure. (This time the issue was found in the logs.) In the screenshot of my last reply, you can see that there were only three lines of output with the fail2-client -vvvd command before, but this time there are a lot of them, and I don't know why, haha, which made me find the problem) It turns out that the default program uses auth.log globally. But I don't specify the path of the log file in my configuration (in the fail2ban 0.11-2 version, I do not specify the logpath in my config file, but it is normal to use it), but just adding the logpath path still doesn't work, I changed my original configuration file sshd.local to jail.local, fail2ban.service service can be successfully started, with my custom name is not possible, the service will fail to start. I wonder if this is a fixed way of writing the program? Just just use a name like jail.local? In fail2ban version 0.11.2 it is possible to use a custom name, such as sshd.local.Thank you for your pointers and replies.

Identify the problem
![cuowu](https://github.com/fail2ban/fail2ban/assets/169267775/110ea564-9ae4-4d44-823f-79ac10c04400)

Finally successfully read the configuration
![ok](https://github.com/fail2ban/fail2ban/assets/169267775/65ed3696-b718-409a-8818-bae0653924a8)

**Comment by tigerJX95** [comment]
I'm sorry, but I'm not very good at using some of github's features. I'll learn to use it well, though. Now I've finally figured out what the problem is, the reason is that the logpath is not specified, so I specified the log path for /var/log/secure. This time the issue was found in the logs. In the screenshot of my last reply, The output from the fail2ban-client -vvvd command doesn't see anything wrong, but this time there are a lot of them, and I don't know why, haha, which made me find the problem,It turns out that the default program uses auth.log globally. But I don't specify the path of the log file in my configuration (in the fail2ban 0.11-2 version, I do not specify the logpath in my config file, but it is normal to use it), but just adding the logpath path still doesn't work, I changed my original configuration file sshd.local to jail.local, fail2ban.service service can be successfully started, with my custom name is not possible, the service will fail to start. I wonder if this is a fixed way of writing the program? Just just use a name like jail.local? In fail2ban version 0.11.2 it is possible to use a custom name, such as sshd.local.Thank you for your pointers and replies.

Identify the problem
![cuowu](https://github.com/fail2ban/fail2ban/assets/169267775/110ea564-9ae4-4d44-823f-79ac10c04400)

Finally successfully read the configuration
![ok](https://github.com/fail2ban/fail2ban/assets/169267775/65ed3696-b718-409a-8818-bae0653924a8)

**Comment by sebres** [comment]
> I do not specify the logpath in my config file, but it is normal to use it), 

All the default parameters are depend on version of fail2ban, distribution (include used in default jail.conf), changes that maintainers did in config files.
In this case it is normal situation that you see differences between maintained v.0.11.2 and stock v.1.1, for instance because installed from source v.1.1 will use `/etc/fail2ban/paths-debian.conf` whereas maintained v.0.11.2 probably used maintained version of it (and not for debian too).

> but just adding the logpath path still doesn't work, I changed my original configuration file sshd.local to jail.local, fail2ban.service service can be successfully started, with my custom name is not possible, the service will fail to start. 

Again: `jail.local` is a config that overwrites `jail.conf` and must be placed parallel to it, whether `sshd.local` (or `sshd.conf`) is a single jail fail and must be placed to `jail.d` folder. Path `/etc/fail2ban/sshd.local` is wrong and will not be loaded by default, unless some (maintainer) config includes it. 
Thus:
```diff
  /etc/fail2ban/jail.local
- /etc/fail2ban/sshd.local
+ /etc/fail2ban/jail.d/sshd.local 
```

> I wonder if this is a fixed way of writing the program? 

I wonder why people not familiar with the stuff installing something from source instead of use the maintained package and then bother why something is different.

> Just just use a name like jail.local? In fail2ban version 0.11.2 it is possible to use a custom name, such as sshd.local.

Again. It is indeed possible, however **stock** fail2ban (which you installed) would only load it from `jail.d` folder but not from root of `/etc/fail2ban`.
This is and was never possible.

**Comment by tigerJX95** [comment]
>I wonder why people not familiar with the stuff installing something from source instead of use the maintained package and then bother why something is different.

It's true that a newbie like me should install the rpm package (Rocky's package is version 1.0.2-12) to avoid unnecessary toss-ups, but maybe I was personally curious and wanted to try the latest version, so I had this experience



>All the default parameters are depend on version of fail2ban, distribution (include used in default jail.conf), changes that maintainers did in config files.
In this case it is normal situation that you see differences between maintained v.0.11.2 and stock v.1.1, for instance because installed from source v.1.1 will use whereas maintained v.0.11.2 probably used maintained version of it (and not for debian too)./etc/fail2ban/paths-debian.conf

>Again. It is indeed possible, however stock fail2ban (which you installed) would only load it from folder but not from root of .
This is and was never possible.jail.d/etc/fail2ban

Thanks again for your reply, I'll keep in mind the directory placement rules for profiles
