### ISSUE TITLE
>Jail not being loaded issue

### ISSUE THREAD

**Issue by tigerJX95** [fail2ban/fail2ban#3759]
> Hello author, I am finding a problem with your latest version of  1.1.0...

No, you don't.

> and the custom jail in the configuration file was not loaded. 

Normally the config directory is `/etc/fail2ban` and custom jail is either in `/etc/fail2ban/jail.local` or `/etc/fail2ban/jail.d/*.conf`...
Is it? (you didn't provided any info how exactly it is configured).

However this path may differ depending on distro and kind of installation (different root-path), etc.

You can check which config files are loaded (and which jails need to be) with:
```
fail2ban-client -vvvd
```

Also is this jail enabled? I mean does it have `enabled = true` in the jail section?

> For the same configuration, I am running fine under centos 7.9 fail2ban version 0.11.2, and the corresponding jail ...

Well I guess it is installed via packet manager of the distro and not manually?..
In the case of manual install from source it depends on many factors why it may differ.
One large difference - no one jail is enabled in stock fail2ban by default, in opposite to distro-package, where it may be done by the maintainers (e. g. IIRC debian package enables sshd jail by default).

_Originally posted by @sebres in https://github.com/fail2ban/fail2ban/issues/3758#issuecomment-2152216399_

**Comment by tigerJX95** [comment]
In centos 7.9, my config file sshd.local is placed under /etc/fail2ban/jail.d/, but this does not apply under rocky9.3, and the service will be reported with an error. I tried putting it under /etc/fail2ban/ and then the service started normally.

I ran the command you gave fail2ban-client -vvvd, and here is the result, it should be that jail.local is not loaded, I don't know what the reason is

71 7F1AA9660740 fail2ban.configreader INFO Loading configs for fail2ban under /etc/fail2ban
72 7F1AA9660740 fail2ban.configreader DEBUG Reading configs for fail2ban under /etc/fail2ban
72 7F1AA9660740 fail2ban.configreader DEBUG Reading config files: /etc/fail2ban/fail2ban.conf
73 7F1AA9660740 fail2ban.configparserinc INFO Loading files: ['/etc/fail2ban/fail2ban.conf']
73 7F1AA9660740 fail2ban.configparserinc TRACE Reading file: /etc/fail2ban/fail2ban.conf
74 7F1AA9660740 fail2ban.configparserinc INFO Loading files: ['/etc/fail2ban/fail2ban.conf']
74 7F1AA9660740 fail2ban.configparserinc TRACE Shared file: /etc/fail2ban/fail2ban.conf
74 7F1AA9660740 fail2ban INFO Using socket file /var/run/fail2ban/fail2ban.sock
74 7F1AA9660740 fail2ban INFO Using pid file /var/run/fail2ban/fail2ban.pid, [INFO] logging to /var/log/fail2ban.log
75 7F1AA9660740 fail2ban.configreader INFO Loading configs for jail under /etc/fail2ban
75 7F1AA9660740 fail2ban.configreader DEBUG Reading configs for jail under /etc/fail2ban
75 7F1AA9660740 fail2ban.configreader DEBUG Reading config files: /etc/fail2ban/jail.conf
76 7F1AA9660740 fail2ban.configparserinc INFO Loading files: ['/etc/fail2ban/jail.conf']
76 7F1AA9660740 fail2ban.configparserinc TRACE Reading file: /etc/fail2ban/jail.conf
82 7F1AA9660740 fail2ban.configparserinc INFO Loading files: ['/etc/fail2ban/paths-debian.conf']
83 7F1AA9660740 fail2ban.configparserinc TRACE Reading file: /etc/fail2ban/paths-debian.conf
83 7F1AA9660740 fail2ban.configparserinc INFO Loading files: ['/etc/fail2ban/paths-common.conf']
83 7F1AA9660740 fail2ban.configparserinc TRACE Reading file: /etc/fail2ban/paths-common.conf
84 7F1AA9660740 fail2ban.configparserinc INFO Loading files: ['/etc/fail2ban/paths-overrides.local']
84 7F1AA9660740 fail2ban.configparserinc TRACE Reading file: /etc/fail2ban/paths-overrides.local
85 7F1AA9660740 fail2ban.configparserinc INFO Loading files: ['/etc/fail2ban/paths-common.conf', '/etc/fail2ban/paths-debian.conf', '/etc/fail2ban/jail.conf']
85 7F1AA9660740 fail2ban.configparserinc TRACE Shared file: /etc/fail2ban/paths-common.conf
85 7F1AA9660740 fail2ban.configparserinc TRACE Shared file: /etc/fail2ban/paths-debian.conf
85 7F1AA9660740 fail2ban.configparserinc TRACE Shared file: /etc/fail2ban/jail.conf
85 7F1AA9660740 fail2ban.configreader DEBUG 'allowipv6' not defined in 'Definition'. Using default one: 'auto'
['set', 'syslogsocket', 'auto']
['set', 'loglevel', 'INFO']
['set', 'logtarget', '/var/log/fail2ban.log']
['set', 'allowipv6', 'auto']
['set', 'dbfile', '/var/lib/fail2ban/fail2ban.sqlite3']
['set', 'dbmaxmatches', 10]
['set', 'dbpurgeage', '1d']
91 7F1AA9660740 fail2ban DEBUG Exit with code 0
=========================================================================
The content of my jail profile is very simple, as follows, the enable option is turned on.

[sshd]
enabled = true
port = ssh
action = iptables[name=SSH, port=22, protocol=tcp]
logpath = /var/log/secure
backend = %(sshd_backend)s
bantime = 12h
findtime = 6h
maxretry = 3

As mentioned above, if the information I provided is incorrect, please also correct it, thank you.

**Comment by sebres** [comment]
Why did you duplicate #3758?

The issue is closed, but you can still comment there and we'll see that in the notifications tracker.
The close state is just for us (because we cannot really help there, or rather neither to reproduce it, nor to retrace that somehow). It is clearly something with your installation or permissions or whatever.

So lets avoid duplicates, thus closed. Further within #3758
