### ISSUE TITLE
[BR]: Can't start fail2ban service on Ubuntu 24.04

### ISSUE THREAD

**Issue by bognini** [fail2ban/fail2ban#3763]
Hi all,
I'm unable to activate the fail2ban service on Ubuntu 24.04
I even purged the program, did the removal to delete all folders/files and reinstall fail2ban but the service always fails to start.
Below the messages I get when I do a status check... can someone help me make this thing work? thanks in advance:

_~$ sudo systemctl enable fail2ban_
Synchronizing state of fail2ban.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable fail2ban

_~$ sudo systemctl status fail2ban_
**× fail2ban.service - Fail2Ban Service
     Loaded: loaded (/usr/lib/systemd/system/fail2ban.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Mon 2024-06-10 16:59:03 UTC; 16s ago
   Duration: 245ms
       Docs: man:fail2ban(1)
   Main PID: 1565 (code=exited, status=255/EXCEPTION)
        CPU: 237ms

Jun 10 16:59:03 dolibarr systemd[1]: Started fail2ban.service - Fail2Ban Service.
Jun 10 16:59:03 dolibarr fail2ban-server[1565]: 2024-06-10 16:59:03,328 fail2ban.configreader   [1565]: WARNING 'allowipv6' not defined in 'Definition'. Using default one: 'auto'
Jun 10 16:59:03 dolibarr fail2ban-server[1565]: 2024-06-10 16:59:03,366 fail2ban                [1565]: ERROR   Failed during configuration: Have not found any log file for web-dol-bruteforce jail
Jun 10 16:59:03 dolibarr fail2ban-server[1565]: 2024-06-10 16:59:03,367 fail2ban                [1565]: ERROR   Async configuration of server failed
Jun 10 16:59:03 dolibarr systemd[1]: fail2ban.service: Main process exited, code=exited, status=255/EXCEPTION
Jun 10 16:59:03 dolibarr systemd[1]: fail2ban.service: Failed with result 'exit-code'.**

**Comment by sebres** [comment]
> `Failed during configuration: Have not found any log file for web-dol-bruteforce jail`

As you can see it is configuration issue.
You have to find the jail `web-dol-bruteforce` and check its `logpath` (this path pattern doesn't find any file).

To show the parameter you could use:
```
fail2ban-client -d | grep 'web-dol-bruteforce.*logpath'
```

To find the config where the jail is configured try:
```
grep -r '\[web-dol-bruteforce\]' /etc/fail2ban/
```

Dup of #1593 etc.
