### ISSUE TITLE
[BR]: You can use root commands

### ISSUE THREAD

**Issue by Panonim** [fail2ban/fail2ban#3764]
![obraz](https://github.com/fail2ban/fail2ban/assets/58903942/6dea1b4e-364b-48a3-ae41-a73a921d7df4)
As shown in the picture you cant use any commands wich requires roots 

Details: 
Os: PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
Version: I can't use the command, but it was downloaded using apt at: `Tue Jun 11 17:50:55 UTC 2024`

How to recreate: 
1. Downlaod the fail2ban
2. Use commands wich requires root
3. Try to use root with commands
That's most likley all, the process what I did is in the picture.

**If you need more info contact me via comments**

**Comment by Panonim** [comment]
**Found Version** fail2ban/stable,stable,stable,stable,now 1.0.2-2 all [installed]

**Comment by sebres** [comment]
```diff
- fail2ban status
- sudo fail2ban status
+ sudo fail2ban-client status
```
