### ISSUE TITLE
[BR]: ERROR Failed to access socket path: /var/run/fail2ban/fail2ban.sock. Is fail2ban running

### ISSUE THREAD

**Issue by edmoncu** [fail2ban/fail2ban#3777]
### Environment:

- Fail2Ban version  : 
- OS, including release name/version : 
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

#### Steps to reproduce
Did the normal installation and launching the program

#### Expected behavior
It should show the list of services being monitored (ex: SSH)

#### Observed behavior
ERROR Failed to access socket path: /var/run/fail2ban/fail2ban.sock. Is fail2ban running 

#### Any additional information
Running on Debian 12 64-bit with OpenVPN Access Server.
Copied fail2ban.conf and jail.conf to *.local and made no modification

#### Any customizations done to /etc/fail2ban/ configuration

```
```

#### Relevant parts of /var/log/fail2ban.log file:

```
```

#### Relevant lines from monitored log files:

```
```

**Comment by sebres** [comment]
It seems to be not started, so check it with `?sudo? systemctl status fail2ban`...
To check fail2ban configuration try `?sudo? fail2ban-client -t` (e. g. if some configuration error is there).

Also note a known issues #3551, #3417 and others (if the error will be the wrong backend)...

By the way...

> Copied fail2ban.conf and jail.conf to *.local and made no modification

Why you did that? I mean a copy... \*.local files need to contain only the values you want to change.
Please don't do that (the old configs may be incompatible to new configs, so it may miss some include or definition from them), but one doesn't "upgrade" local files.

**Comment by kidigital101** [comment]
same problem here installed however get error :failed to access socket path /var/run/fail2ban/fail2ban.sock

**Comment by kidigital101** [comment]
sudo apt install fail2ban
sudo cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
sudo nano /etc/fail2ban/jail.local
sudo fail2ban-client status
sudo apt-get fail2ban
systemctl status fail2ban
sudo systemctl enable fail2ban
sudo systemctl start fail2ban
sudo systemctl status fail2ban
:)
