### ISSUE TITLE
[BR]: filter regex looks right, but URLs starting with two slashes not matched, although pattern for that

### ISSUE THREAD

**Issue by timreeves** [fail2ban/fail2ban#3780]
### Environment:

- Fail2Ban v1.0.2
- Debian 11.10
- Fail2Ban installed via Plesk
- I have not applied any additional foreign patches to the codebase
- Some customizations were done to the configuration: Plesk + own jails/filters

### The issue:

Plesk used to prefer Apache, nowadays Plesk support for Nginx is quite good, but still no jails for nginx. So I developed them myself, they work well. But lately I've been seeing that the access logs on some servers are getting larger. This is due to attacks trying out typical possible ways to get information about, or directly hack into, the server. So I gathered a lot of the typical hack attempts producing 404s and made a filter with them. I've been testing it with fail2ban-regex.

The filter basically works - but not for one typical attack vector. I've seen this a fair bit, that the attacker intentionally doubles up the slash at the front of the URL, like this: Instead of /wp-content/ the call was //wp-content/ (with TWO slashes at the front). I assume the intention is to bypass some defense mechanisms. Such requests are in the log I tested with, among many other attack URLs. All get found except the "two slashes" variants.

#### Steps to reproduce
Copy out my filter and run it over an nginx log containing lines like these:

91.92.241.0 - - [24/Jun/2024:20:28:09 +0200] "GET //wp-content/plugins/fix/up.php HTTP/1.1" 404 548 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36"

198.244.171.0 - - [27/Jun/2024:15:01:12 +0200] "GET //wp-includes/wlwmanifest.xml HTTP/1.1" 404 548 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0 Safari/537.36"

198.244.171.0 - - [27/Jun/2024:15:01:12 +0200] "GET //blog/wp-includes/wlwmanifest.xml HTTP/1.1" 404 548 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0 Safari/537.36"

198.244.171.0 - - [27/Jun/2024:15:01:12 +0200] "GET //web/wp-includes/wlwmanifest.xml HTTP/1.1" 404 548 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0 Safari/537.36"

198.244.171.0 - - [27/Jun/2024:15:01:12 +0200] "GET //wordpress/wp-includes/wlwmanifest.xml HTTP/1.1" 404 548 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0 Safari/537.36"

198.244.171.0 - - [27/Jun/2024:15:01:12 +0200] "GET //website/wp-includes/wlwmanifest.xml HTTP/1.1" 404 548 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0 Safari/537.36"

198.244.171.0 - - [27/Jun/2024:15:01:12 +0200] "GET //wp/wp-includes/wlwmanifest.xml HTTP/1.1" 404 548 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0 Safari/537.36"

198.244.171.0 - - [27/Jun/2024:15:01:12 +0200] "GET //news/wp-includes/wlwmanifest.xml HTTP/1.1" 404 548 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0 Safari/537.36"

#### Expected behavior

The filter should find such lines - there is one slash before the alternatives, and some of the alternatives start with a second slash.

#### Observed behavior

It does not find them.

#### Any additional information

fail2ban-regex --print-all-missed access_ssl_log /var/private/fail2ban/filter.d/nginx-404-attack-urls.conf | grep ' 404 ' >bug.txt

#### Any customizations done to /etc/fail2ban/ configuration
nginx-404-attack-urls.conf:
```
[Definition]

failregex = ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) \/(\.env|\.git|www/.env|www/.git|cgi-bin/|app/|api/|sql/|admin/|db/|ztp/|js/|owa/|portal|login|script|wp-login\.php|wp-settings\.php|xmlrpc\.php|/wp-content/|/wordpress/|/web|/news|/test/wp-|/blog/|/site/|cgi-binluci|webui/|actuator/|geoserver/web/|tinymce/|ckeditor/|plugins/|sdk|odinhttpcall|fileman/|lib/fileman/|\+CSCOE\+/logon\.html|ecp/Current/exporttool/|evox/about|phpmyadmin/index\.php|bc|bk|backup|wordpress|old|new|home|main|ads\.txt|app-ads\.txt|admin\.html|start\.html|home\.html|default\.html|sftp-config\.json|ssh-config\.json|\.vscode/sftp\.json|\.well-known/pki-validation/wp-login\.php|\.DS_Store|js/NewWindow_2_all\.js|dns-query|cluster|remote/login|owa/auth/logon\.aspx|vendor/phpunit/phpunit/src/Util/PHP/eval-stdin\.php|Public/home/js/check\.js|static/admin/javascript/hetong\.js|owncloud/|cmd,/|vendor/phpunit/phpunit/phpunit\.xml|HNAP1|alive\.php|remote/|redmine/\.env|__tests__/|debug/|web/debug/|sapi/debug/|config\.json|AwsConfig\.json|aws\.json|conf\.json|env\.json|\.json|deployment-config\.json|credentials/config\.json|sendgrid\.json|ws-config\.json|db/robomongo\.json|robomongo\.json|\.aws/|parameters\.yml|_profiler/|version|assets/|clients/|frontend/|smtp\.json|client_secrets\.json|sellers\.json|app_dev\.php/|phpinfo\.php|solr/|v2/|.well-known/security.txt|ReportServer|simple\.php|class\.api\.php|identity|Remote|RDWeb|auth|/query?|status\.php|System/)\S* \S+\" 404 .+$

ignoreregex =
```

**Comment by timreeves** [comment]
An obvious attempt to get this working would be to put the first slash in each alternative - which would be inelegant (I haven't tried it).

**Comment by sebres** [comment]
> filter regex looks right, but URLs starting with two slashes not matched, although pattern for that

It doesn't.
The RE definitely misses some URIs, or prefixes... 
If I try to match your RE against your excerpt I see this with `fail2ban-regex`:
```
Lines: 8 lines, 0 ignored, 6 matched, 2 missed
```
And the 2 missed lines contain `//wp-includes/wlwmanifest.xml` and `//wp/wp-includes/wlwmanifest.xml`.

In your URI-patterns there is no `wp-includes` at all, so they will never found.

Sorry, but firstly check attentive your concern (in this case the RE and better several times) before you open a bug report somewhere.

Here is a diff that may help here... I also removed leading slash in all URI-patterns, `/+` matches as many slashes as possible, added optional prefix matching `website` or `wp`, but also removed an anchor with a catch-all (`.+$` makes no sence):

```diff
- ^<HOST> \- \S+ \[\] \"(GET|POST|HEAD) \/(\.env|\.git|www/.env|www/.git|cgi-bin/|app/|api/|sql/|admin/|db/|ztp/|js/|owa/|portal|login|script|wp-login\.php|wp-settings\.php|xmlrpc\.php|/wp-content/|/wordpress/|/web|/news|/test/wp-|/blog/|/site/|cgi-binluci|webui/|actuator/|geoserver/web/|tinymce/|ckeditor/|plugins/|sdk|odinhttpcall|fileman/|lib/fileman/|\+CSCOE\+/logon\.html|ecp/Current/exporttool/|evox/about|phpmyadmin/index\.php|bc|bk|backup|wordpress|old|new|home|main|ads\.txt|app-ads\.txt|admin\.html|start\.html|home\.html|default\.html|sftp-config\.json|ssh-config\.json|\.vscode/sftp\.json|\.well-known/pki-validation/wp-login\.php|\.DS_Store|js/NewWindow_2_all\.js|dns-query|cluster|remote/login|owa/auth/logon\.aspx|vendor/phpunit/phpunit/src/Util/PHP/eval-stdin\.php|Public/home/js/check\.js|static/admin/javascript/hetong\.js|owncloud/|cmd,/|vendor/phpunit/phpunit/phpunit\.xml|HNAP1|alive\.php|remote/|redmine/\.env|__tests__/|debug/|web/debug/|sapi/debug/|config\.json|AwsConfig\.json|aws\.json|conf\.json|env\.json|\.json|deployment-config\.json|credentials/config\.json|sendgrid\.json|ws-config\.json|db/robomongo\.json|robomongo\.json|\.aws/|parameters\.yml|_profiler/|version|assets/|clients/|frontend/|smtp\.json|client_secrets\.json|sellers\.json|app_dev\.php/|phpinfo\.php|solr/|v2/|.well-known/security.txt|ReportServer|simple\.php|class\.api\.php|identity|Remote|RDWeb|auth|/query?|status\.php|System/)\S* \S+\" 404 .+$
+ ^<ADDR> [^\"]+"[^/]* /+(?:(?:website|wp)/+)?(?:\.env|\.git|www/.env|www/.git|cgi-bin/|app/|api/|sql/|admin/|db/|ztp/|js/|owa/|portal|login|script|wp-login\.php|wp-settings\.php|xmlrpc\.php|wp-(?:content|includes)/|wordpress/|web|news|test/wp-|blog/|site/|cgi-binluci|webui/|actuator/|geoserver/web/|tinymce/|ckeditor/|plugins/|sdk|odinhttpcall|fileman/|lib/fileman/|\+CSCOE\+/logon\.html|ecp/Current/exporttool/|evox/about|phpmyadmin/index\.php|bc|bk|backup|wordpress|old|new|home|main|ads\.txt|app-ads\.txt|admin\.html|start\.html|home\.html|default\.html|sftp-config\.json|ssh-config\.json|\.vscode/sftp\.json|\.well-known/pki-validation/wp-login\.php|\.DS_Store|js/NewWindow_2_all\.js|dns-query|cluster|remote/login|owa/auth/logon\.aspx|vendor/phpunit/phpunit/src/Util/PHP/eval-stdin\.php|Public/home/js/check\.js|static/admin/javascript/hetong\.js|owncloud/|cmd,/|vendor/phpunit/phpunit/phpunit\.xml|HNAP1|alive\.php|remote/|redmine/\.env|__tests__/|debug/|web/debug/|sapi/debug/|config\.json|AwsConfig\.json|aws\.json|conf\.json|env\.json|\.json|deployment-config\.json|credentials/config\.json|sendgrid\.json|ws-config\.json|db/robomongo\.json|robomongo\.json|\.aws/|parameters\.yml|_profiler/|version|assets/|clients/|frontend/|smtp\.json|client_secrets\.json|sellers\.json|app_dev\.php/|phpinfo\.php|solr/|v2/|.well-known/security.txt|ReportServer|simple\.php|class\.api\.php|identity|Remote|RDWeb|auth|query?|status\.php|System/)\b[^"]*" 404
```

**Comment by timreeves** [comment]
Hi Sergey,

I used to be pretty nifty with regex... back in the day. Now I'm pushing 70 and am not _quite_ so sharp as then. But still, I plod at things and get them done.

Many thanks for your suggested improved regex! I've dissected it and understood the improvements. But the fact remains, that no line with an address starting "//" is matched. Of course "/+" should do the trick. I also tried [/]+ and /[/]*, to no avail. I tested also with "//.env", a very simple case which is matched when as "/.env", no joy. It looks to me as if the double slash at the start of the address is being somehow modified before the regex is applied - otherwise, how could all these differently formulated expressions all fail?

Would be really grateful if you could have another look at it!

Cheers,
Tim

**Comment by sebres** [comment]
> It looks to me as if the double slash at the start of the address is being somehow modified before the regex is applied - otherwise, how could all these differently formulated expressions all fail?

No, generally it does not.
Pythonic REs doesn't handle slashes specially and pythons config-parser only consider `#` (at begin of line) or ` ;` (semicolon after space) as inline-comments. Thus 2 slashes are just 2 simple chars in python or fail2ban context.
You can also check the real RE coming from configuration with `fail2ban-client -d | grep "$jailname.*failregex"`... 
I'm pretty sure the `//` would be there.

> But the fact remains, that no line with an address starting "//" is matched.

Do you have concrete example?

Your 8 example messages from the issue description are matched by your RE, excepting 2 messages, but I already wrote why not... Please read attentively my explanation above about "2 missed lines".
Because the reason for the miss is completely different and has nothing to do with double slash.

So please provide exact example (message and regex) where `//` doesn't work.

Here is the counterexample from me:
```bash
$ fail2ban-regex "$(date +%s) 192.0.2.1 - //test" "^\s*<ADDR> - //\w+"
...
Lines: 1 lines, 0 ignored, 1 matched, 0 missed
```

**Comment by timreeves** [comment]
Hi Sergey,

I _thought_ I tried it with this line:

198.244.171.0 - - [27/Jun/2024:15:01:12 +0200] "GET //.env HTTP/1.1" 404 548 "-" "Mozilla/5.0 (Windows NT 10.0; Win64;
 x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0 Safari/537.36"

but it seems that something was wrong with the way I tested it. Now I'm getting the expected results - after having made the new filter version live.

Could it be that when I call: fail2ban-regex attack-samples.txt nginx-404-attack-urls.conf
that some reference is still made to the live system?

Apart from that, sorry to have caused you bother and many thanks for your help.

Vielen Dank nach Hamburg!

Tim

**Comment by sebres** [comment]
Still one comment by the way - neither reload, nor restart of fail2ban would process the logfile or journal from scratch - it knows the last position (stored in database) as well as consider `findtime` and `bantime` by the checks whether the entries are new, so maybe it was your mistake - to expect the log will be rescanned and old messages will be considered after restart, because it would not happen. Here is an RFE for the rescan facility with more details - https://github.com/fail2ban/fail2ban/issues/2909#issuecomment-758036512
