### ISSUE TITLE
[FR]: SSHD filter doesn't work on Arch to due to daemon name having changed to sshd-session

### ISSUE THREAD

**Issue by MatthijsSchuurman** [fail2ban/fail2ban#3785]
It seems that with the latest updates on Arch the daemon name of `sshd` has changed to `sshd-session`. This causes the sshd filter to ignore all sshd lines and consequently not ban any IPs. 

Changing `/etc/fail2ban/filter.d/sshd.conf` as follows fixes the issue however this is of course a nasty workaround:
```diff
- _daemon = sshd
+ _daemon = sshd-session
```

I used `fail2ban-regex ./sshd.log /etc/fail2ban/filter.d/sshd.conf -v` to trace down the issue which showed the daemon name was in the content section instead of the mlfid:
`{'mlfid': ' host ', 'content': 'sshd-session[1234567]: Invalid user nono from 1.2.3.4 port 12345'}`

### Environment:
- Fail2Ban version 1.1.0-4
- OS, including release name/version : Arch (up-to-date)

#### Service, project or product which log or journal should be monitored
- Name of filter or jail in Fail2Ban (if already exists) : sshd
- Service, project or product name, including release name/version : sshd
- Ports and protocols the service is listening : 22

#### Log or journal information
- Log file name(s) :  Systemd journal
- Journal identifier or unit name : sshd

#### failures in sense of fail2ban filter (fail2ban must match):
```
Jul 04 11:48:26 my.host.com sshd-session[1234567]: Failed password for root from 1.2.3.4 port 12345 ssh2
```

**Comment by sebres** [comment]
See #3782.

**Comment by sebres** [comment]
Just by the way, to consider all messages (also which are still raised with `sshd`), better would be to change it like in mentioned PR:
```diff
- _daemon = sshd-session
+ _daemon = sshd(?:-session)?
```

**Comment by thissuper** [comment]
@sebres Hi, Can the new version of fail2ban automatically detect "_daemon"?

**Comment by thissuper** [comment]
> Just by the way, to consider all messages (also which are still raised with `sshd`), better would be to change it like in mentioned PR:
> 
> ```diff
> - _daemon = sshd-session
> + _daemon = sshd(?:-session)?
> ```

Great, thank you very much!

**Comment by seanm** [comment]
Isn't defending against ssh attacks one of the main uses of fail2ban?

Shouldn't therefore a new release be made to include this fix?

**Comment by sebres** [comment]
> Isn't defending against ssh attacks one of the main uses of fail2ban?

We are not responsible for the maintenance of fail2ban across all distros. You can surely find the responsible person in the description of fail2ban package for your distribution.

> Shouldn't therefore a new release be made to include this fix?

New release to update some filter? Seriously?..
Simplest patch is fully enough to do that.
