### ISSUE TITLE
[BR]: ERROR   Backend 'systemd' failed to initialize due to No module named 'distutils'

### ISSUE THREAD

**Issue by alrf** [fail2ban/fail2ban#3787]
### Environment:

- Fail2Ban version  : 1.1.0
- OS, including release name/version : Fedora CoreOS 39
- Python version: 3.12.2
- [ ] Fail2Ban installed via OS/distribution mechanisms: Fail2ban installed from source code (https://github.com/fail2ban/fail2ban/archive/refs/tags/1.1.0.tar.gz).
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

My python version is 3.12.2, fail2ban v1.1.0 service doesn't start and fails with error: 
`Backend 'systemd' failed to initialize due to No module named 'distutils'` 
when `backend = systemd` in a jail is used:
```
cat /etc/fail2ban/jail.d/defaults-sshd.conf
[sshd]
enabled = true
backend = systemd
```

According to [PEP 632](https://www.python.org/dev/peps/pep-0632/), distutils will be formally marked as deprecated, and in Python 3.12, it will be removed.

#### Steps to reproduce

Add a file:
```
cat /etc/fail2ban/jail.d/defaults-sshd.conf
[sshd]
enabled = true
backend = systemd
```

#### Expected behavior

Fail2ban service works and doesn't fail.

#### Observed behavior

Fail2ban service doesn't start and fails.

#### Any customizations done to /etc/fail2ban/ configuration

```
cat /etc/fail2ban/jail.d/defaults-sshd.conf
[sshd]
enabled = true
backend = systemd
```

#### Relevant parts of /var/log/fail2ban.log file:

```
2024-07-08 10:28:42,552 fail2ban.jail           [2952516]: ERROR   Backend 'systemd' failed to initialize due to No module named 'distutils'
2024-07-08 10:28:42,552 fail2ban.jail           [2952516]: ERROR   Failed to initialize any backend for Jail 'sshd'
```

**Comment by alrf** [comment]
Installed `python3-setuptools` and it works.

**Comment by sebres** [comment]
By the way, the last references for `distutils` are removed in ac62658c10f492911f8a0037a0bcf97c8521cd78 (#3728)... 
So it'll be unneeded anymore in newer versions.
