### ISSUE TITLE
[RFE]: nftables ingress hook

### ISSUE THREAD

**Issue by howardkent** [fail2ban/fail2ban#3792]
#### Feature request type
Enchance the nftables.conf action file to support the ingress hook

#### Description
Supporting the nftables ingress hook would be beneficial for intercepting banned addresses earlier in the packet processing.

#### Considered alternatives
There isn't really an alternative, other than the prerouting hook that is already supported, but that is later in the packet processing.

#### Any additional information
Suggest to use nftables-common.local to indicate which interface the ingress hook should attach to.

**Comment by sebres** [comment]
I don't follow the RFE...

You can specify the hook just be setting of `chain_hook` parameter of action.
Thus it is enough to do:
```
[DEFAULT]
banaction = nftables
banaction_allports = nftables[type=allports]

[jail1]
# this jail uses default hook (`chain_hook=prerouting`)
enabled = true

[jail2]
# this jail uses ingress hook:
banaction = nftables[chain_hook=ingress]
enabled = true

[jail3]
# this jail uses forward hook:
banaction = nftables[chain_hook=forward]
enabled = true
```
In the same way you can overwrite the default hook (either in `DEFAULT` section of `jail.local`, or by setting `chain_hook` in `Init` section of `action.d/nftables.local`).

So please explain what do you mean with this RFE exactly...
I'll close it (as already implemented), till more info provided.

**Comment by sebres** [comment]
Not a problem at all, just add it to the hook parameter inside single or double quotes (`chain_hook` would be interpolated without quotation currently, exactly for that needs):
```ini
banaction = nftables[chain_hook="ingress device eth0"]
```
And for `action.d/nftables.local` (if it's needed globally for some reason) it'd look like that:
```ini
[Init]
chain_hook = ingress device eth0
```
