### ISSUE TITLE
[FR]: postfix NOQUEUE: reject: CONNECT from unknown

### ISSUE THREAD

**Issue by BradWaite** [fail2ban/fail2ban#3800]
### Environment:

- Fail2Ban version  : fail2ban-1.1.0
- OS, including release name/version : FreeBSD 14.1-RELEASE

#### Service, project or product which log or journal should be monitored

- Name of filter or jail in Fail2Ban (if already exists) : postfix
- Service, project or product name, including release name/version : postfix
- Repository or URL (if known) : 
- Service type : mail
- Ports and protocols the service is listening : smtp, submission

#### Log or journal information

- Log file name(s) : /var/log/maillog

- Journal identifier or unit name : 

#### Any additional information
'_pref = [A-Z]{4}' matches 'RCPT', 'EHLO', 'VRFY', etc, but does not match 'CONNECT'.

I'm not sure where that string is originating, but likely due to 'smtpd_client_restrictions = reject_unknown_client_hostname' in postfix's main.cf.

'_pref = [A-Z]+' solves the problem.

#### failures in sense of fail2ban filter (fail2ban must match):

```
Jul 20 19:00:55 mail postfix/smtpd[7749]: NOQUEUE: reject: CONNECT from unknown[178.215.236.114]: 450 4.7.25 Client host rejected: cannot find your hostname, [178.215.236.114]; proto=SMTP
```

#### legitimate messages (fail2ban should not consider as failures):

```
```

**Comment by sebres** [comment]
Must be fixed in 93810fff75640ddfe4c248e670ed80b5d225bf10 now.
Thx for the report!
