### ISSUE TITLE
[BR]: THE WIKI IS OPEN TO EDIT, FIX THAT

### ISSUE THREAD

**Issue by mosab3** [fail2ban/fail2ban#3810]
### Environment:

- Fail2Ban version  : 
- OS, including release name/version : 
- [ ] Fail2Ban installed via OS/distribution mechanisms
- [ ] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

#### Steps to reproduce

the wiki page is literally open to edit by anyone

#### Expected behavior

  Only thoses with permission should able to edit, not anyone.

#### Any additional information

I recommend restricting editing for contribiutor only, checkout `Restrict editing to collaborators only ` under repo settings -> General -> Features -> Restrict editing to collaborators only

**Comment by sebres** [comment]
> the wiki page is literally open to edit by anyone

Well, by anyone **from GH**. We are aware and this is an intention not a oversight.

The reasons for that is:
- wiki is a git-repository and thus a) versioned and b) distributed across several places (what is quasi a backup at the same time)
- therefore it is pretty simple to control (check and compare the revisions) and to restore it to some state on demand (as you could see, your test attempt are no more there, I reverted the wiki to previous revision)
- we do a control of the wiki, periodically (and see the changes on the repo)
- there was no one abusive incident until now, so the decision was and still is let it open for GH-community yet.
