### ISSUE TITLE
FAIL2BAN on Linux (Debian 12 - bookworm) - Action "xarf-login-attack-local.conf" since yesterday not working any longer

### ISSUE THREAD

**Issue by newbie-red** [fail2ban/fail2ban#3830]
I might have a quick question in relation to FAIL2BAN on Linux (Debian 12  - bookworm);

OS:                        **debian 12 - bookworm**
Software-Version: **fail2ban 1.0.2**

quick description of my environment:
in my **jail.local** there is just 1 single defined jail: for **SSHD**
```
action_cf_mwlf = **cloudflare**[cfuser="%(cfemail)s", cftoken="%(cfapikey)s"]
                **abuseipdb**[abuseipdb_apikey="%(my-abuseipdb_apikey)s", abuseipdb_category="18,22"]
                %**(mta)s-whois-lines-local**[sender="%(sender)s", dest="%(destemail)s", logpath="%(logpath)s",
                chain="%(chain)s"]
                **blocklist_de**[email="%(sender)s", service="%(__name__)s", apikey="%(blocklist_de_apikey)s",
                agent="%(fail2ban_agent)s"]
                **xarf-login-attack-local**[service=%(__name__)s, sender="%(sender)s", bcc="%(bcc)s",
                 logpath="%(logpath)s", port="%(port)s"]
```

user@linux-syslog:/etc/fail2ban/action.d$ **sudo fail2ban-client get sshd actions**
The jail sshd has the following actions:
**cloudflare, abuseipdb, sendmail-whois-lines-local, xarf-login-attack-local, blocklist_de**

cloudflare: working fine - no problem at all;
abuseipdb: working fine - no problem at all;
sendmail-whois-lines-local: working fine - no problem at all;

blocklist_de: not working any longer since yesterday: **CURL error 400**
xarf-loginattack-local: not working any longer since yesterday: **CURL error 400**

Please could any of you tell me what am I doing wrong?
I can not find the error by myself: sorry for that;

Kind Regards, and thanks alot ahead

**Comment by sebres** [comment]
The error (if it is really an error) can be found in fail2ban.log. So please provide the excerpt from fail2ban log (where it fails and additional lines before and hereafter).
