### ISSUE TITLE
[RFE]: Modify cloudflare.conf in action.d folder for Cloudflare custom API keys readiness

### ISSUE THREAD

**Issue by daniel-san05** [fail2ban/fail2ban#3839]
#### Feature request type
Modify cloudflare.conf in action.d folder for use with hardened Cloudflare API token and not using the global Cloudflare account API key anymore.

#### Description
Cloudflare is providing a permission concept for API tokens. For creating IP access rules with Fail2Ban action via Cloudflare API no global API key is needed anymore.

#### Considered alternatives
Change line 68 in the file cloudflare.conf with following cf api params:  
`_cf_api_prms = -H 'X-Auth-Email: <cfuser>' -H 'Authorization: Bearer <cftoken>' -H 'Content-Type: application/json'`
#### Any additional information
In Cloudflare Dashboard a custom API can be created with following rights:
- All accounts - Account Firewall Access Rules:Edit
and
- All accounts - Account Firewall Access Rules:Read

I have tested it successfully in my Fail2Ban docker container.

**Comment by sebres** [comment]
Hmm... Doesn't [cloudflare-token.conf](https://github.com/fail2ban/fail2ban/blob/master/config/action.d/cloudflare-token.conf) uses Bearer Token (action gets introduced in #3080)?
