### ISSUE TITLE
[BR]: fail2ban-client set jail attempt works without bantime.increment

### ISSUE THREAD

**Issue by N0TScrooge** [fail2ban/fail2ban#3845]
**Fasban2ban-client set "jail" attempt "ip"** "Isn't it required to use the Bantime.increment settings?"

Is it conceived or is it a mistake?

**Comment by sebres** [comment]
Hmm... Indeed, the manually added attempts are not sent to the observer, so it doesn't take the known ban-count into account.
I'll fix it soon.
