### ISSUE TITLE
No matches in JSON data ?

### ISSUE THREAD

**Issue by exxosuk** [fail2ban/fail2ban#3846]
I have been trying to do this for the past several hours.. Ordinarily I don't have any problems with creating rules with the normal access.log.  However I'm trying to extract IP addresses from a json file and it just refuses to cooperate :( 

For example some data is
`{ "seconds" : 1727709422, "action" : "allow", "class" : "Misc activity", "b64_data" : "7sD6ZgAAAABdqQUAAAAAAAMxODUuNTIuMi4xNzI=", "dir" : "C2S", "dst_addr" : "185.52.2.172", "dst_ap" : "185.52.2.172:0", "eth_dst" : "FA:16:3E:20:5E:C0", "eth_len" : 71, "eth_src" : "24:FC:4E:48:07:07", "eth_type" : "0x800", "gid" : 1, "icmp_code" : 0, "icmp_id" : 54771, "icmp_seq" : 37343, "icmp_type" : 8, "iface" : "ens3", "ip_id" : 27800, "ip_len" : 37, "msg" : "PROTOCOL-ICMP PING", "mpls" : 0, "pkt_gen" : "raw", "pkt_len" : 57, "pkt_num" : 5515218, "priority" : 3, "proto" : "ICMP", "rev" : 8, "rule" : "1:384:8", "service" : "unknown", "sid" : 384, "src_addr" : "101.44.161.230", "src_ap" : "101.44.161.230:0", "tos" : 0, "ttl" : 48, "vlan" : 0, "timestamp" : "09/30-16:17:02.455464" }
{ "seconds" : 1727709422, "action" : "allow", "class" : "Misc activity", "b64_data" : "7sD6ZgAAAABdqQUAAAAAAAMxODUuNTIuMi4xNzI=", "dir" : "S2C", "dst_addr" : "101.44.161.230", "dst_ap" : "101.44.161.230:0", "eth_dst" : "00:00:5E:00:01:23", "eth_len" : 71, "eth_src" : "FA:16:3E:20:5E:C0", "eth_type" : "0x800", "gid" : 1, "icmp_code" : 0, "icmp_id" : 54771, "icmp_seq" : 37343, "icmp_type" : 0, "iface" : "ens3", "ip_id" : 47372, "ip_len" : 37, "msg" : "PROTOCOL-ICMP Echo Reply", "mpls" : 0, "pkt_gen" : "raw", "pkt_len" : 57, "pkt_num" : 5515220, "priority" : 3, "proto" : "ICMP", "rev" : 8, "rule" : "1:408:8", "service" : "unknown", "sid" : 408, "src_addr" : "185.52.2.172", "src_ap" : "185.52.2.172:0", "tos" : 0, "ttl" : 64, "vlan" : 0, "timestamp" : "09/30-16:17:02.455576" }
{ "seconds" : 1727709423, "action" : "allow", "class" : "Detection of a Network Scan", "b64_data" : "TS1TRUFSQ0ggKiBIVFRQLzEuMQ0KSE9TVDogMjM5LjI1NS4yNTUuMjUwOjE5MDANCk1BTjogInNzZHA6ZGlzY292ZXIiDQpTVDogdXBucDpyb290ZGV2aWNlDQpNWDogNQ0KDQo=", "dir" : "C2S", "dst_addr" : "239.255.255.250", "dst_ap" : "239.255.255.250:1900", "dst_port" : 1900, "eth_dst" : "01:00:5E:7F:FF:FA", "eth_len" : 143, "eth_src" : "FA:16:3E:48:58:7D", "eth_type" : "0x800", "gid" : 1, "iface" : "ens3", "ip_id" : 41364, "ip_len" : 109, "msg" : "INDICATOR-SCAN UPnP service discover attempt", "mpls" : 0, "pkt_gen" : "raw", "pkt_len" : 129, "pkt_num" : 5516346, "priority" : 3, "proto" : "UDP", "rev" : 16, "rule" : "1:1917:16", "service" : "unknown", "sid" : 1917, "src_addr" : "185.52.1.110", "src_ap" : "185.52.1.110:53340", "src_port" : 53340, "tos" : 0, "ttl" : 1, "udp_len" : 109, "vlan" : 0, "timestamp" : "09/30-16:17:03.238076" }
`

While I try a very simple rule such as 
`src_addr"\s*:\s*"<HOST>`

And nothing matches. 

 If I try a online tool simply without the <HOST>

![json](https://github.com/user-attachments/assets/db7e8c69-2c25-4181-b627-8f084e97c1b4)

It seems to match file. 

I have tried milling different things, but just seems totally impossible, and I don't understand why ?

**Comment by exxosuk** [comment]
I also should mention the data does seem to be on separate lines but the formatting messes it up a bit...


![1](https://github.com/user-attachments/assets/b5dc7752-acac-42ee-ae52-81e6f0949c01)

**Comment by exxosuk** [comment]
I may have stumbled on a solution of sorts...

`datepattern = %%m/%%d-%%H:%%M:%%S
failregex = {.*"src_addr"\s*:\s*"<HOST>".*}`

Though I cannot really work out if it actually needs the date pattern or not.....

**Comment by sebres** [comment]
Just a note: faster and better (because anchored) date-pattern for this may be:
```ini
datepattern = ^\{\s*"seconds"\s*:\s*{EPOCH}
```

**Comment by exxosuk** [comment]
Thanks, I will give it a try.
