### ISSUE TITLE
[BR]: Is there a way to unban all IPS

### ISSUE THREAD

**Issue by mai1x9** [fail2ban/fail2ban#3852]
I could not find no where how to unban all ips. This is ridiculous that this feature is not present. Plus unbanning the IP is not working.

**Comment by sebres** [comment]
> I could not find no where how to unban all ips. This is ridiculous that this feature is not present.

```bash
# all IPs regardless the jails:
fail2ban-client unban --all
# all IPs in certain jail only:
fail2ban-client restart --unban "$jail"
```

See https://manpages.debian.org/testing/fail2ban/fail2ban-client.1.en.html#unban

> Plus unbanning the IP is not working.

Sorry, but "is not working" doesn't exist in IT-world... You need to be a little bit more precise with the description.
Thus closed unless more info provided.
