### ISSUE TITLE
[BR]: fail2ban ignore ingnoreip if use fail2ban-client set jail banip <IP>

### ISSUE THREAD

**Issue by N0TScrooge** [fail2ban/fail2ban#3853]
fail2ban ignore ingnoreip if use fail2ban-client set jail banip <IP>

Is it conceived or is it a mistake?

```
#fail2ban-client set fail2ban_from_neighbors banip 2.2.2.2
1

```

2024-10-10 17:02:38,087 fail2ban.actions        [832302]: NOTICE  [fail2ban_from_neighbors] Ban 2.2.2.2

```
#fail2ban-client get  fail2ban_from_neighbors ignoreip
These IP addresses/networks are ignored:
|- 127.0.0.0/8
......
|- 2.2.2.2
`- ::1

```
jail.d/fail2ban_from_neighbors.local
[fail2ban_from_neighbors]
...
ignoreip    = 127.0.0.1/8 ::1 2.2.2.2 
.....

```
#fail2ban-client -V
1.1.1.1
```

and 

```
#fail2ban-client -V
0.11.2
```

**Comment by sebres** [comment]
> fail2ban ignore ingnoreip if use fail2ban-client set jail banip
> Is it conceived or is it a mistake?

It is indeed intended behavior, quote from obsolete version:
https://github.com/fail2ban/fail2ban/blob/2ed414ed09b3bb4c478abc9366a1ff22024a33c9/fail2ban/server/filter.py#L337-L338

However this warning (and the check) was removed later in future versions (somewhere in v.0.10). 
The user knows better.
