### ISSUE TITLE
[BR]: ERROR NOK: ("'NoneType' object has no attribute 'lower'",)

### ISSUE THREAD

**Issue by julioseibei** [fail2ban/fail2ban#3854]
### Environment:

- Fail2Ban version  : 
- Fail2Ban v0.11.2
- OS, including release name/version : 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
and
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

#### Steps to reproduce

When running
systemctl stop fail2ban
and
sudo fail2ban-client -vvv -x start
the error is displayed
+ 882 7F0FCAE4B740 fail2ban ERROR NOK: ("'NoneType' object has no attribute 'lower'",)
however, the service starts normally, since
systemctl status fail2ban
does not display an error.
The log shows
['start', 'traefik-auth']]] has failed. Received AttributeError("'NoneType' object has no attribute 'lower'")

#### Any customizations done to /etc/fail2ban/ configuration

```
```

#### Relevant parts of /var/log/fail2ban.log file:

['start', 'traefik-auth']]] has failed. Received AttributeError("'NoneType' object has no attribute 'lower'")

#### Relevant lines from monitored log files:

['start', 'traefik-auth']]] has failed. Received AttributeError("'NoneType' object has no attribute 'lower'")

**Comment by sebres** [comment]
It looks like something wrong in the configuration. 
Please provide the output of config dump `fail2ban-client -d`

**Comment by sebres** [comment]
Hmm... Neither I see something wrong here nor I can reproduce it.
Don't you see some error in fail2ban.log? Especially with traceback (callstack)?..
If don't - can you try to start it with DEBUG level, e. g. `sudo fail2ban-client -vvv --loglevel=DEBUG -x start`?

**Comment by julioseibei** [comment]
# systemctl stop fail2ban
# sudo fail2ban-client -vvv --loglevel=DEBUG -x start
 +   41 7FE0882A6740 fail2ban.configreader     INFO  Loading configs for fail2ban under /etc/fail2ban
 +   41 7FE0882A6740 fail2ban.configreader     DEBUG Reading configs for fail2ban under /etc/fail2ban
 +   41 7FE0882A6740 fail2ban.configreader     DEBUG Reading config files: /etc/fail2ban/fail2ban.local
 +   41 7FE0882A6740 fail2ban.configparserinc  INFO    Loading files: ['/etc/fail2ban/fail2ban.local']
 +   42 7FE0882A6740 fail2ban.configparserinc  TRACE     Reading file: /etc/fail2ban/fail2ban.local
 +   42 7FE0882A6740 fail2ban.configparserinc  INFO    Loading files: ['/etc/fail2ban/fail2ban.local']
 +   42 7FE0882A6740 fail2ban.configparserinc  TRACE     Shared file: /etc/fail2ban/fail2ban.local
 +   42 7FE0882A6740 fail2ban                  INFO  Using socket file /var/run/fail2ban/fail2ban.sock
 +   42 7FE0882A6740 fail2ban                  INFO  Using pid file /var/run/fail2ban/fail2ban.pid, [DEBUG] logging to /var/log/fail2ban.log
 +   43 7FE0882A6740 fail2ban                  HEAVY CMD: ['ping', 0.1]
 +   43 7FE0882A6740 fail2ban                  HEAVY OK : 'pong'
 +   44 7FE0882A6740 fail2ban                  ERROR Server already running
 +   44 7FE0882A6740 fail2ban                  DEBUG Exit with code 255

In fail2ban.log:
+138066585 7F399098D740 fail2ban.server           INFO  rollover performed on /var/log/fail2ban.log

**Comment by sebres** [comment]
> Server already running

This is basically another error - so your attempt to start fail2ban did not happen at all, therefore the error is not logged.
You have to stop it and ensure that fail2ban process get down before try to start it again.

> It looks like this... or something in Python... I don't know

I know, but there are too many possible `lower()` invocations, and since I cannot reproduce it, it is unknown which one is affected. Let alone I don't see under normal circumstances which one may indeed be None, all pieces look like they will be a string.

**Comment by julioseibei** [comment]
I stop Fail2ban and killed the fail2ban processes (only one) and then:
sudo fail2ban-client -vvv --loglevel=DEBUG -x start

See the output:
[dump1.log](https://github.com/user-attachments/files/17386762/dump1.log)

**Comment by sebres** [comment]
Oh people... What is logged in the fail2ban.log for this start sequence?

**Comment by sebres** [comment]
Anyway, something looks wrong with configuration of `uwimap-auth` together with `named-refused-udp` jails - somehow they put together in the stream and many parameters are missing and broken there:
```python
['add', 'uwimap-auth', 'systemd\n\n\n\n\n[named-refused-udp]\nfilter   = named-refused\nport     = domain,953\nprotocol = udp\nlogpath  = /var/log/named/security.log'], 
['set', 'uwimap-auth', 'usedns', 'warn'], ...
```
If you cannot find the bug, can you provide the excerpt of config with this 2 jails (exactly as it is configured in your `jail.local` or `jail.conf`)?

**Comment by julioseibei** [comment]
See, the jails are as installed, without modifications.
So, the bug came ready, people.
I don't have to find any bug, i was trying to help.
My time is worth as much as yours.
Easy, people!

jail.local

...
[uwimap-auth]

port   = imap,imaps
logpath = %(syslog_mail)s
backend = %(syslog_backend)s


#
#
# DNS servers
#


# !!! WARNING !!!
#   Since UDP is connection-less protocol, spoofing of IP and imitation
#   of illegal actions is way too simple.  Thus enabling of this filter
#   might provide an easy way for implementing a DoS against a chosen
#   victim. See
#    http://nion.modprobe.de/blog/archives/690-fail2ban-+-dns-fail.html
#   Please DO NOT USE this jail unless you know what you are doing.
#
# IMPORTANT: see filter.d/named-refused for instructions to enable logging
# This jail blocks UDP traffic for DNS requests.
 [named-refused-udp]
#
 filter   = named-refused
 port     = domain,953
 protocol = udp
 logpath  = /var/log/named/security.log

# IMPORTANT: see filter.d/named-refused for instructions to enable logging
# This jail blocks TCP traffic for DNS requests.

[named-refused]

port     = domain,953
logpath  = /var/log/named/security.log
...

**Comment by julioseibei** [comment]
See, the jails are as installed, no modifications.
So, the bug came ready, people.
I don't have to find any bug, i was trying to help.
My time is worth as much as yours.
Easy, people!

jail.local

...
[uwimap-auth]

port   = imap,imaps
logpath = %(syslog_mail)s
backend = %(syslog_backend)s

#
#
# DNS servers
#


# !!! WARNING !!!
#   Since UDP is connection-less protocol, spoofing of IP and imitation
#   of illegal actions is way too simple.  Thus enabling of this filter
#   might provide an easy way for implementing a DoS against a chosen
#   victim. See
#    http://nion.modprobe.de/blog/archives/690-fail2ban-+-dns-fail.html
#   Please DO NOT USE this jail unless you know what you are doing.
#
# IMPORTANT: see filter.d/named-refused for instructions to enable logging
# This jail blocks UDP traffic for DNS requests.
# [named-refused-udp]
#
# filter   = named-refused
# port     = domain,953
# protocol = udp
# logpath  = /var/log/named/security.log

# IMPORTANT: see filter.d/named-refused for instructions to enable logging
# This jail blocks TCP traffic for DNS requests.

[named-refused]

port     = domain,953
logpath  = /var/log/named/security.log

...

I uninstalled and reinstalled and configured it.
It seems to be working.
