### ISSUE TITLE
[BR]: Can't ban from a  list of IPs ?

### ISSUE THREAD

**Issue by exxosuk** [fail2ban/fail2ban#3861]
Fail2Ban v0.11.1

if I run 

`sudo fail2ban-regex -v /etc/fail2ban/unmatched_ips.txt /etc/fail2ban/filter.d/manual-blacklist.conf`

with

```
[Definition]
datepattern = ^  
failregex = ^<HOST>\s*$
```

I just get

`Running tests
=============

Use   failregex filter file : manual-blacklist, basedir: /etc/fail2ban
Use      datepattern : ^  # Disables date parsing
Use         log file : /etc/fail2ban/unmatched_ips.txt
Use         encoding : UTF-8

Results
=======

Failregex: 0 total
|-  #) [# of hits] regular expression
|   1) [0] ^<HOST>\s*$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [0] ^  # Disables date parsing
`-

Lines: 9384 lines, 0 ignored, 0 matched, 9384 missed
[processed in 0.42 sec]
`

In the log it shows..

`2024-10-18 20:09:31,353 fail2ban.filter         [3577625]: WARNING Found a match for '46.0.192.13' but no valid date/time found for '46.0.192.13'. Please try setting a custom date pattern (see man page jail.conf(5)). If format is complex, please file a detailed issue on https://github.com/fail2ban/fail2ban/issues in order to get support for this format.
`

But the IP is not banned. 

The IP list is just a list of IPs, no spaces or anything in the file. Tried all sorts. The only thing which seems to work is if I have something like

`103.102.230.7 - - [18/Oct/2024:04:39:55 +0100]`

works with the correct regex. 

So either F2B doesn't support direct IP blocking from a list, or there is something I am missing ?

**Comment by exxosuk** [comment]
I'm even more confused now, as now its just done this. 

`fail2ban-client status manual-blacklist
Status for the jail: manual-blacklist
|- Filter
|  |- Currently failed: 0
|  |- Total failed:     0
|  `- File list:        /var/log/nginx/offending_ips.txt /var/log/nginx/fake_ips.txt /etc/fail2ban/unmatched_ips.txt
`- Actions
   |- Currently banned: 5
   |- Total banned:     5
   `- Banned IP list:   111.251.230.122 139.192.87.55 77.246.99.200 138.199.19.178 103.161.69.46
`

Which come from the file offending_ips.txt (only 5) So that's worked. Though the other 2 files have a list of IPs and nothing is found. The format of the IP file is not different I think..

But still a manual run doesn't show anything the same results from the same file. 

`sudo fail2ban-regex -v /etc/fail2ban/offending_ips.txt /etc/fail2ban/filter.d/manual-blacklist.conf

Running tests
=============

Use   failregex filter file : manual-blacklist, basedir: /etc/fail2ban
Use      datepattern : ^  # Disables date parsing
Use      single line : /etc/fail2ban/offending_ips.txt


Results
=======

Failregex: 0 total
|-  #) [# of hits] regular expression
|   1) [0] ^<HOST>\s*$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [0] ^  # Disables date parsing
`-

Lines: 1 lines, 0 ignored, 0 matched, 1 missed
[processed in 0.00 sec]

|- Missed line(s):
|  /etc/fail2ban/offending_ips.txt
`-
`

But for a manual run, shouldn't it be showing the same 5 IPs as it matched earlier ?

**Comment by sebres** [comment]
Normally timestamp is required in the line for match, however special datepattern `{NONE}` can be used to circumvent this (then it'd always consider now as the timestamp of failure).
Implemented in #2814

**Comment by exxosuk** [comment]
> Normally timestamp is required in the line for match, however special datepattern `{NONE}` can be used to circumvent this (then it'd always consider now as the timestamp of failure). Implemented in #2814

Thanks, Though I still get the same problem :(

`datepattern = {NONE}
failregex = ^<HOST>\s*$`

`fail2ban-regex /etc/fail2ban/unmatched_ips.txt /etc/fail2ban/filter.d/manual-blacklist

Running tests
=============

Use   failregex filter file : manual-blacklist, basedir: /etc/fail2ban
Use      datepattern : {NONE}
Use         log file : /etc/fail2ban/unmatched_ips.txt
Use         encoding : UTF-8


Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:

Lines: 9384 lines, 0 ignored, 0 matched, 9384 missed
[processed in 0.46 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all 9384 lines
`
F2B obviously finds the file and knows content is in the file, but it still doesn't "see" the IPs in the file. I really don't get why ?

**Comment by sebres** [comment]
I cannot reproduce it, neither with latest version, nor with latest 0.11:
```bash
$ seq -f "192.0.2.%g" 5 > /tmp/log; fail2ban-regex --print-all-matched --print-all-missed -d '{NONE}' /tmp/log '^<ADDR>'

Running tests
=============

Use      datepattern : {NONE} : ^
Use   failregex line : ^<ADDR>
Use         log file : /tmp/log
Use         encoding : UTF-8


Results
=======

Failregex: 5 total
|-  #) [# of hits] regular expression
|   1) [5] ^<ADDR>
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [5] ^
`-

Lines: 5 lines, 0 ignored, 5 matched, 0 missed
[processed in 0.00 sec]

|- Matched line(s):
|  192.0.2.1
|  192.0.2.2
|  192.0.2.3
|  192.0.2.4
|  192.0.2.5
`-
```
Maybe it is something with your file or format... Please provide the excerpt with few lines (or an output of test above).

However I guess your version is simply too old (I tested it with latest 0.11th branch - v.0.11.2).
If your maintained repository has no update - you could try to update it manually: https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually

**Comment by exxosuk** [comment]
Thanks for your feedback. 

All my file has is a list of IPs..

![1](https://github.com/user-attachments/assets/dd319ce6-5d7d-40e9-9ddc-9b067e806415)

and with cat -A /etc/fail2ban/unmatched_ips.tx

64.62.197.233$
64.62.197.146$
64.67.125.148$
64.62.197.217$
96.45.16.67$
64.72.101.186$
64.62.197.105$
96.70.176.106$
95.181.94.204$
95.204.92.226$
64.62.197.128$
95.221.37.33$
98.100.77.252$

The exact version just says
Fail2Ban v0.11.1

also

apt show fail2ban
Package: fail2ban
Version: 0.11.1-1ubuntu0.1~esm1
Priority: optional
Section: net
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Python Modules Team <python-modules-team@lists.alioth.debian.org>
Installed-Size: 2012 kB
Depends: python3:any, lsb-base (>= 2.0-7)
Recommends: nftables | iptables, whois, python3-pyinotify, python3-systemd
Suggests: mailx, system-log-daemon, monit, sqlite3
Download-Size: 375 kB
APT-Manual-Installed: yes
APT-Sources: https://esm.ubuntu.com/apps/ubuntu focal-apps-security/main amd64 Packages
Description: ban hosts that cause multiple authentication errors

N: There is 1 additional record. Please use the '-a' switch to see it


Everything on the server is updated from official Ubuntu repo. But I guess its not maintained in the official repo now. So I guess my only option is try to and do the manual updates... thanks for your help.

**Comment by sebres** [comment]
> 64.62.197.233$
> 64.62.197.146$

In this case (because of the dollar-characters) the RE must be:
```diff
- failregex = ^<HOST>\s*$
+ failregex = ^<HOST>\s*\$?
```
(`$` is an end-anchor, `\$` is a character, `\$?` is optional $-character)

Or better:
```diff
- failregex = ^<HOST>\s*$
+ failregex = ^<ADDR>
```
(unanchored end, `<ADDR>` instead of `<HOST>` if only IPs expected)

**Comment by exxosuk** [comment]
Thanks, regex I am not good at by far. 

I tried the ones you suggest, but it doesn't make any odds. Still get the same issue.. 

 sudo fail2ban-regex /etc/fail2ban/unmatched_ips.txt /etc/fail2ban/filter.d/manual-blacklist

Running tests
=============

Use   failregex filter file : manual-blacklist, basedir: /etc/fail2ban
Use      datepattern : {NONE}
Use         log file : /etc/fail2ban/unmatched_ips.txt
Use         encoding : UTF-8


Results
=======

Failregex: 0 total

Ignoreregex: 0 total

Date template hits:

Lines: 8303 lines, 0 ignored, 0 matched, 8303 missed
[processed in 0.38 sec]

Missed line(s): too many to print.  Use --print-all-missed to print all 8303 lines

**Comment by sebres** [comment]
> Still get the same issue..

Sure.  As already said, the PR #2814 supporting datepattern `{NONE}` (and the possibility to match lines without timestamp) was released with 0.11.2, you have 0.11.1.

I wanted just to point out to possible another error you had with an regex.

**Comment by exxosuk** [comment]
ah ok thanks. I will see if I can copy it all to a test server and make sure nothing breaks while trying to update it all manually. Thanks for your help.

**Comment by exxosuk** [comment]
I setup a test server to try this out on.. So upgraded now..

fail2ban-client -V
1.1.0

sudo fail2ban-regex /etc/fail2ban/unmatched_ips.txt /etc/fail2ban/filter.d/manual-blacklist


Running tests
=============

Use      filter file : manual-blacklist, basedir: /etc/fail2ban
Use      datepattern : {NONE} : ^
Use         log file : /etc/fail2ban/unmatched_ips.txt
Use         encoding : UTF-8


Results
=======

Failregex: 8303 total
|-  #) [# of hits] regular expression
|   1) [8303] ^<ADDR>
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [8303] ^
`-

Lines: 8303 lines, 0 ignored, 8303 matched, 0 missed
[processed in 0.31 sec]

So it all seems fixed now and correctly obtaining the IPs!

Thanks!
