### ISSUE TITLE
[BR]: Fail2ban error

### ISSUE THREAD

**Issue by ReFleX9** [fail2ban/fail2ban#3870]
I am making my own VPN on VDS with a script 3x - ui. Os is Ubunte 22.04. I also want to connect it so that it would be impossible for several users to connect using the same configuration. I set an access log for "./access.log" via 3x-ui. But such an error was found (attached a photo). I tried to solve the problem through the GPT chat, he advised me to create a jail file and write it there(attached a photo). But in the end, the error remains. I would be very grateful for help in this matter, since I do not really understand this.

![изображение_2024-10-30_225324083](https://github.com/user-attachments/assets/64300db4-bd66-4131-a9fb-55b8dd8adb6d)
![изображение_2024-10-30_225334532](https://github.com/user-attachments/assets/1101c828-ccc8-4acf-9709-fe3420ad24f0)

**Comment by sebres** [comment]
The error mean "Have not found any log file for **sshd** jail" - the emphasis is sshd. 
You have tried to create jail `3x-ui` which has nothing to do with error message you provided in first screenshot (by the way, don't do that - provide the text excerpts for the console output, not the screenshots).

You have to change the backend for **sshd** jail. 
So create empty file /etc/fail2ban/jail.local and add this to the file:
```ini
[sshd]
backend = systemd
enabled = true
```
(for debian derivatives sshd may be enabled by default by maintainers)

Also See https://github.com/fail2ban/fail2ban/issues/3292#issuecomment-1142503461 for more details.

Regarding your jail `3x-ui` - I guess you don't really understand what you're doing:
- ports 443 and ssh basically belong to different things - 443 is for https, whether ssh (normally 22) is sshd port;
- access.log (logpath) and ssh-port look also not correct to me;
- backend `systemd` will monitor systemd journal, but you specified `logpath` (so the `backend` must be rather `auto`);
- etc
