### ISSUE TITLE
Why doesn't it work fail2ban?

### ISSUE THREAD

**Issue by draconMo** [fail2ban/fail2ban#3876]
Debian12 + iptables+ fail2ban+postfix+dovecot
It is necessary to protect port 143 from password guessing(I use the blocking filter that comes with fail2ban /etc/fail2ban/filter.d/dovecot.conf)

[dovecot]
enabled = true
port = imap
protocol = tcp
filter = dovecot
maxretry = 3
bantime = 3600
findtime = 60
 
systemctl restart fail2ban

I see in fail2ban.log
2024-11-07 15:58:41,904 fail2ban.filter         [454408]: INFO    [dovecot] Found  *.*.37.198 - 2024-11-07 15:58:41

But a denying rule is not created in Iptables

**Comment by sebres** [comment]
> `INFO [dovecot] Found ...`

It has found single attempt, to cause ban it should find `maxretry` failures (3 in your case) during `findtime` (60 seconds).
In such case you'd also see `NOTICE [dovecot] Ban ...` after the finding.

See the FAQ https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works for more details.

I'd suggest to increase `findtime`, but it is your decision...
