### ISSUE TITLE
[RFE]: Does logtarget can be set in jail.local?

### ISSUE THREAD

**Issue by wx2020** [fail2ban/fail2ban#3877]
#### Feature request type
The logtarget option can be set in files under the jail.d folder to separate the logging output for a specific jail.

#### Description
I use a sshd.local file in folder jail.d like this:
```
[DEFAULT]
ignoreip = 127.0.0.1/8 ::1
           172.30.0.0/16
logtarget = /config/log/fail2ban/ban_sshd.log
[sshd]
enabled = true
port = 22
filter = sshd
logpath = /var/log/auth.log
bantime  = 1h
bantime.increment = true
bantime.factor = 168
bantime.maxtime = 8w
findtime  = 5m
maxretry = 3
action = iptables
```

But when i restart fail2ban, the log about jail sshd still be in the path "/config/log/fail2ban/fail2ban.log" be set in fail2ban.conf:
```
[DEFAULT]

# Option: loglevel
# Notes.: Set the log level output.
#         CRITICAL
#         ERROR
#         WARNING
#         NOTICE
#         INFO
#         DEBUG
# Values: [ LEVEL ]  Default: INFO
#
loglevel = INFO

# Option: logtarget
# Notes.: Set the log target. This could be a file, SYSTEMD-JOURNAL, SYSLOG, STDERR or STDOUT.
#         Only one log target can be specified.
#         If you change logtarget from the default value and you are
#         using logrotate -- also adjust or disable rotation in the
#         corresponding configuration file
#         (e.g. /etc/logrotate.d/fail2ban on Debian systems)
# Values: [ STDOUT | STDERR | SYSLOG | SYSOUT | SYSTEMD-JOURNAL | FILE ]  Default: STDERR
#
# lsio value
logtarget = /config/log/fail2ban/fail2ban.log

```
#### Considered alternatives
Does Does logtarget can be set in jail.local?

Please help me.

**Comment by sebres** [comment]
No, currently it is not possible... `logtarget` is only option of fail2ban.conf (or fail2ban.local) and fail2ban uses centralized logger for all its modules.
Although I don't really follow the necessity to log something per jail... However if it is just to see the bans for the jail, you can write own action (similar to [dummy](https://github.com/fail2ban/fail2ban/blob/master/config/action.d/dummy.conf)) and add it as second action to the jail:
```ini
[sshd]
action = %(action_)s
         dummy[target="/path/to/the/log"]
```
