### ISSUE TITLE
[BR]: fail2ban (1.0.2) from raspberry pi OS Lite bookworm repository is not well configured

### ISSUE THREAD

**Issue by beta-tester** [fail2ban/fail2ban#3890]
i have a web server running with lighttpd (at port 80, 443) and sshd running.
the OS of the webserver is the official and actual Raspberry Pi OS Lite (bookworm)

when i install fail2ban via `apt install fail2ban`, fail2ban does not work.
because of an error:
```journalctl
Dec 05 15:16:01 web-server1 systemd[1]: ssh.service: Scheduled restart job, restart counter is at 1.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ Automatic restarting of the unit ssh.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
Dec 05 15:16:01 web-server1 systemd[1]: Stopped ssh.service - OpenBSD Secure Shell server.
░░ Subject: A stop job for unit ssh.service has finished
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A stop job for unit ssh.service has finished.
░░ 
░░ The job identifier is 18648 and the job result is done.
Dec 05 15:16:03 web-server1 sshd[10026]: /etc/ssh/sshd_config line 132: Directive 'Port' is not allowed within a Match block
Dec 05 15:16:01 web-server1 systemd[1]: Starting ssh.service - OpenBSD Secure Shell server...
░░ Subject: A start job for unit ssh.service has begun execution
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit ssh.service has begun execution.
░░ 
░░ The job identifier is 18648.
Dec 05 15:16:03 web-server1 sshd[10027]: /etc/ssh/sshd_config line 132: Directive 'Port' is not allowed within a Match block
Dec 05 15:16:02 web-server1 systemd[1]: ssh.service: Control process exited, code=exited, status=255/EXCEPTION
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ An ExecStartPre= process belonging to unit ssh.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 255.
Dec 05 15:16:03 web-server1 sshd[10028]: /etc/ssh/sshd_config line 132: Directive 'Port' is not allowed within a Match block
Dec 05 15:16:02 web-server1 systemd[1]: ssh.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit ssh.service has entered the 'failed' state with result 'exit-code'.
Dec 05 15:16:02 web-server1 systemd[1]: Failed to start ssh.service - OpenBSD Secure Shell server.
░░ Subject: A start job for unit ssh.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ A start job for unit ssh.service has finished with a failure.
░░ 
░░ The job identifier is 18648 and the job result is failed.
Dec 05 15:16:02 web-server1 systemd[1]: ssh.service: Scheduled restart job, restart counter is at 2.
...
```

i had to install rsyslog first to make fail2ban happy.

but even then, fail2ban does not recoglize the installed lighttpd.
at least nothing to see in the output of `fail2ban-client status`

i created a jail.local file by hand to handle sshd and lighttpd:
```config
[sshd]
enabled  = true
port     = ssh,2222
filter   = sshd
logpath  = /var/log/auth.log
maxretry = 2

[lighttpd-auth]
enabled  = true
port     = http,https
filter   = lighttpd-auth
logpath  = /var/log/lighttpd/error.log
maxretry = 3
```

when i watch the output of `fail2ban-client -d`, i see entries with `'addaction', 'iptables-multiport']`. i guess fail2ban uses iptables rules to ban ip addresses. but the OS bookworm uses nftables and not iptables.

to me, it looks like fail2ban is not well configured out-of-the-box fpr Raspberry Pi OS Lite bookworm.

### Environment:

- Fail2Ban version 1.0.2
  ```bash
  $ sudo fail2ban-client version
  1.0.2
  ```
- OS, including release name/version :
  ```bash
  $ uname -a
  Linux web-server1 6.6.62+rpt-rpi-v6 #1 Raspbian 1:6.6.62-1+rpt1 (2024-11-25) armv6l GNU/Linux
  $ cat /etc/os-release 
  PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"
  NAME="Raspbian GNU/Linux"
  VERSION_ID="12"
  VERSION="12 (bookworm)"
  VERSION_CODENAME=bookworm
  ID=raspbian
  ID_LIKE=debian
  HOME_URL="http://www.raspbian.org/"
  SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
  BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
  ``` 
- [X] Fail2Ban installed via OS/distribution mechanisms
  ```bash
  sudo apt install fail2ban
  ```
- [ ] You have not applied any additional foreign patches to the codebase
- [X] Some customizations were done to the configuration (provide details below is so)
  after fail2ban failed to start out-of-the-box, i installed rsyslog and made a jail.local file by hand:
  ```config
  [sshd]
  enabled  = true
  port     = ssh,2222
  filter   = sshd
  logpath  = /var/log/auth.log
  maxretry = 2

  [lighttpd-auth]
  enabled  = true
  port     = http,https
  filter   = lighttpd-auth
  logpath  = /var/log/lighttpd/error.log
  maxretry = 3
  ```

### The issue:
- fail2ban failed to start out-of-the-box bacause of errors.
- fail2ban does not recognize lighttpd and sshd out-of-the-box
- fail2ban uses iftables rules on a systen that only supports nftables
- fail2ban requires rsyslog on a system that only uses journalctl

#### Steps to reproduce
- install the official raspberry pi OS Lite to a raspberry Pi 1 B
  https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2024-11-19/2024-11-19-raspios-bookworm-armhf-lite.img.xz
- install sshd and lighttpd `apt install sshd lihttpd`
- restart system 'reboot'
- install fail2ban `apt install fail2ban`
- try to see the output of `sudo fail2ban-client version`
  `ERROR Failed to access socket path: /var/run/fail2ban/fail2ban.sock. Is fail2ban running?`
- list journal `sudo journalctl -xeu fail2ban.service`
  `ERROR Failed during configuration: Have not found any log file for sshd jail`

#### Expected behavior
i expect the fail2ban will at least show the version out-of-the-box.
and is configured for standard installation of sshd and lighttpd.on a bookworm system that has no rsyslog installed and that uses nftables.

#### Observed behavior
see above

#### Any additional information
see above

### Configuration, dump and another helpful excerpts
see above

**Comment by sebres** [comment]
> fail2ban does not work because of an error...

You have provided the errors of ssh.service, not of the fail2ban. They have basically nothing to do with fail2ban.

> ERROR Failed during configuration: Have not found any log file for sshd jail

OK, this looks like the message of fail2ban. See https://github.com/fail2ban/fail2ban/issues/3292#issuecomment-1142503461 for the solution.

> i had to install rsyslog first to make fail2ban happy.

No you would have simply configure correct backend (systemd) or logpath (if it is file) for the sshd jail.

> i guess fail2ban uses iptables rules to ban ip addresses. but the OS bookworm uses nftables and not iptables.

Yes this was the case for some debians in stock fail2ban (but IIRC not in debian branch), now it is nftables anyway, see d0d07285234871bad3dc0c359d0ec03365b6dddc.

> but even then, fail2ban does not recoglize the installed lighttpd.

If you mean there is no bans - you have to provide examples from its log (you mean they need to be banned) and/or better the output of `fail2ban-regex ... lighttpd-auth`. Also note the FAQ in https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works

Otherwise please, be more precise what exactly "does not recognize" shall mean, with excerpts, examples etc.

> i expect the fail2ban will at least show the version out-of-the-box.

Use `fail2ban-client --version` or `fail2ban-server --version`, not `fail2ban-client version` (which is trying to send command `version` to fail2ban server).

> to me, it looks like fail2ban is not well configured out-of-the-box fpr Raspberry Pi OS Lite bookworm.

This is common stock repository of fail2ban development (basically without special configs or adjustments for any OS/platform, excepting few main settings).
You have rather to open the issue and seek for support by the maintainers of fail2ban packet for your OS, or update it to newer version.
With the best will, would we ever be able to maintain fail2ban here for every distro and platform, let alone could be responsible for any version provided with some packet manager.

**Comment by sebres** [comment]
> there were no error in the ssh.service. it was an error in the fail2ban service.

Yes but you provided a lot of ssh.service errors: see the large excerpt in your issue description, in particular lines between:
```
Dec 05 15:16:01 web-server1 systemd[1]: ssh.service: Scheduled restart job, restart counter is at 1.
...
Dec 05 15:16:02 web-server1 systemd[1]: ssh.service: Scheduled restart job, restart counter is at 2.
```
Nothing of them was related to fail2ban service.

> i am an enduser. the installes package should just start out-of-the-box without any handmade configuration and not run into an error out-of-the-box.

No. Neither you installed fail2ban from here, nor it was latest version, nor it shall start out-of-the-box without any handmade configuration. 
It is just a tool, which needs a lot of configurations. Either accept this, or don't use it. Anyway, as already said, it is not the matter of this repository (despite whether we provide a generic deb-package too).

> my thought was that lighttpd is one of the standard packages that fail2ban can ...

There are millions packages... All the filters/jails of fail2ban are created by users, contributed it as it was tested for certain version of service, platform and OS, it may not work for some circumstances on your platform.
I already wrote what you may do to ask here for help.

> i thought the fail2ban maintainer keepes its packaged in best shape or best experience for endusers.

Then ask the maintainers of your package. There are not necessarily here.

> on the main README.md it is written like this `fail2ban-client version`. so i used that syntax.

Again, this will ask running fail2ban server instance about its version. Your fail2ban was unable to start, so the answer of command was correct (it is not running).

> i am an enduser. i have no knowledge who is responsable for what version is configured for what distro.

No problem... However it is usual for linux, and one could search in internet or simply do:
```
apt show fail2ban
# or
apt show fail2ban | grep Maintainer
```

> i thought the fail2ban maintainer keepes its packaged in best shape or best experience for endusers.

They do mostly, but without any guarantee...
However it is really complex matter. And we have no influence on that, neither when nor what exactly will be released by their repos and how often the packages become updated.

Anyway, out-of-the-box is surely nice to have, but it is too perfect and a bit strange expectation for the sysadmin tool like fail2ban.

**Comment by beta-tester** [comment]
thank you for your time and explaination.
and yes, i missed that i wrongly copy-n-pasted the log of ssh insted of fail2ban. that was definitely my fault.
