### ISSUE TITLE
[BR]: fail2ban cuts the first digit of IP when moving to iptables

### ISSUE THREAD

**Issue by FredFeuerstein0815** [fail2ban/fail2ban#3893]
fail2ban 1.0.2-2
raspiOS Debian 12 Bookworm arm64

fail2ban cuts the first digit of IP when moving to iptables

Example:
`fail2ban-regex /var/log/apache2/access.log --print-all-matched '^.<HOST>.*https://github.com/robertdavidgraham/masscan*..*$'`

Found this line:
|  80.94.93.191 - - [10/Dec/2024:04:18:18 +0100] "GET / HTTP/1.0" 302 433 "-" "masscan/1.0 (https://github.com/robertdavidgraham/masscan)"

Then put it in myfilter.conf an run:
fail2ban-regex /var/log/apache2/access.log --print-all-matched /etc/fail2ban/filter.d/myfilter.conf

Found this line again:
|  80.94.93.191 - - [10/Dec/2024:04:18:18 +0100] "GET / HTTP/1.0" 302 433 "-" "masscan/1.0 (https://github.com/robertdavidgraham/masscan)"

Put it in myjail.local restart fail2ban.

iptable -L
Chain f2b-myfilter (1 references)
target     prot opt source               destination
REJECT     all  --  0.94.93.191          anywhere             reject-with icmp-port-unreachable

Where is the first digit of IP gone ?
Lost ?

**Comment by FredFeuerstein0815** [comment]
My failure, leading point at `.<HOST>`

**Comment by sebres** [comment]
> My failure, leading point ...

Yes.
The filter works in fail2ban-regex exactly in the same as in fail2ban server.

Just try it with `-o '<ip> : <msg>'` to output the IP:
```
fail2ban-regex -o '<ip> : <msg>' "$log" "$re"
```

By the way, your RE is vulnerable (and slow due to catch-all `.*`)... You could use something like this instead:
```
^<ADDR> [^"]*"[^"]*" \d+ \d+ "[^"]*" "(?:masscan)
```

**Comment by FredFeuerstein0815** [comment]
Thanks.
