### ISSUE TITLE
[BR]: Docs: FILTERS contains outdated URL to sourcecodebrowser page

### ISSUE THREAD

**Issue by pano9000** [fail2ban/fail2ban#3896]
Hi all,

just noticed that the `FILTERS` doc file contains a "TIP" block that points to a link to sourcecodebrowser.

```
.. TIP::
     For looking through source code - http://sourcecodebrowser.com/ . It has
     call graphs and can browse different versions.
```

However that service seems to be dead since quite a while and the link currently redirects to some dubious gambling related site.
This was previously looking something like that apparently: https://web.archive.org/web/20160322213113/https://sourcecodebrowser.com/

**Comment by sebres** [comment]
Merged. Thx!
