### ISSUE TITLE
sshd.conf missing some matches

### ISSUE THREAD

**Issue by phoenix-9** [fail2ban/fail2ban#3907]
https://github.com/fail2ban/fail2ban/blob/51358e158797b4efceb9c88ea48f7bfbbfb9b161/config/filter.d/sshd.conf#L73

The regex is:
`mdre-ddos = ^(?:Did not receive identification string from|Timeout before authentication for) <HOST>`

The log line (debian openssh 1:9.9p1-3) is:
`Dec 25 05:35:52 marc sshd[3931221]: Timeout before authentication for connection from 140.246.52.32 to ...`

So it's not triggering because the regex is missing "connection from".

**Comment by sebres** [comment]
Thx!.. 
Fixed in 89b5f3bb1ecd3789b3271b648eeb83c620668e6f
