### ISSUE TITLE
[RFE]: Add "flags interval" to _nft_add_set in action.d/nftables.conf

### ISSUE THREAD

**Issue by jhgarrison** [fail2ban/fail2ban#3908]
#### Feature request type

A trivial change to support CIDR addresses in nftables
#### Description

In the definition of `_nft_add_set`, add `flags interval \;` after `type <addr_type>\;`

This will allow banning CIDR address ranges, useful for manual jails

#### Considered alternatives

None

#### Any additional information

I will submit a pull request unless someone objects.

**Comment by sebres** [comment]
see #3125

**Comment by jhgarrison** [comment]
Understood, thanks.  I hope one day that, beyond manual jails, that fail2ban can detect probes from CIDR ranges and generate the appropriate wider bans.  

Nowadays I'm seeing a lot of probing from multiple addresses in /22 or larger subnets, which fail2ban cannot detect.
