### ISSUE TITLE
Fail2Ban fails to start on Ubuntu noble with python 3.12 - ModuleNotFoundError: No module named 'imp' 

### ISSUE THREAD

**Issue by baluballa** [fail2ban/fail2ban#3910]
- Fail2Ban version  : 
- OS, including release name/version : **ubuntu 24.04.1 LTS (noble)  fail2ban version (1.0.2-3ubuntu0.1)**
- [ X] Fail2Ban installed via OS/distribution mechanisms **apt-get**
- [ X] You have not applied any additional foreign patches to the codebase
- [ X] Some customizations were done to the configuration (provide details below is so)

### The issue:
_Hi all,_

After upgrading my system ubuntu to version 24.04.1 LTS (noble) my fail2ban will not start. Ubuntu 'noble' is using python 3.12 as default. I have reinstalled fail2ban using apt-get as described in the wiki. However still fail2ban will not start giving this error message after sys:

Google search indicates the module imp is deprecated in python 3.12 and replaced with "importlib"

#### Steps to reproduce
fails to start by  systemctl start fail2ban
#### Expected behavior
server starts without issue.

#### Observed behavior
```
Traceback (most recent call last): 
File "/usr/local/bin/fail2ban-server", line 34, in <module> 
File "/usr/local/lib/python3.12/dist-packages/fail2ban/client/fail2banserver.py", line 26, in <module>
from .fail2bancmdline import Fail2banCmdLine, ServerExecutionException, \ 
File "/usr/local/lib/python3.12/dist-packages/fail2ban/client/fail2bancmdline.py", line 30, in <module>
from ..helpers import getLogger, str2LogLevel, getVerbosityFormat, BrokenPipeError
File "/usr/local/lib/python3.12/dist-packages/fail2ban/helpers.py", line 35, in <module>
import imp 
ModuleNotFoundError: No module named 'imp' 
fail2ban.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by sebres** [comment]
Despite `import imp` is unknown to me (imho `helper.py` never had this line in 3.x branch), the version 1.0.2 was basically never compatible to python 3.12 - the first version with its support was [1.1.0](https://github.com/fail2ban/fail2ban/releases/tag/1.1.0). See #3487 and others.
Although I don't know what exactly the maintainers of Ubuntu package did patched within 1.0.2-3ubuntu0.1.

You could seek for the help by maintainers of your distribution or install the deb-package 1.1.0 from here, see the link above and the [wiki :: how to install ...](https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually)
