### ISSUE TITLE
server errors lost in daemon mode before log target set

### ISSUE THREAD

**Issue by grooverdan** [fail2ban/fail2ban#400]
Start with a left over socket and start a new server with force.

So a condition in the start here where nothing is logged.

in server/server.py:start self.__createDaemon seems to close all the files descriptors and therefore log messages go to /dev/null until its the logtarget is configured by the client.

Therefore the bunch of pid and socket errors isn't logged.

Based on #399 code however the conditions of failure still exist.

<pre>
$ ls -la /tmp/s.sock
srwx------. 1 dan dan 0 Oct 15 10:58 /tmp/s.sock

$ strace -f -s 99  -o /tmp/xxxx  ./fail2ban-client -s /tmp/s.sock -x  -c config/ start
2013-10-15 11:23:53,324 fail2ban.server : INFO   Starting Fail2ban v0.8.10.dev
2013-10-15 11:23:53,326 fail2ban.server : INFO   Starting in daemon mode

/tmp/xxxx shows

17147 close(0)                          = 0
17147 close(1)                          = 0
17147 close(2)                          = 0
17147 close(3)                          = -1 EBADF (Bad file descriptor)
....
17147 open("/dev/null", O_RDONLY)       = 0
17147 open("/dev/null", O_RDWR)         = 1
17147 open("/dev/null", O_RDWR)         = 2
17147 stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2183, ...}) = 0
17147 write(1, "2013-10-15 11:23:53,481 fail2ban.server : INFO   Daemon started\n", 64) = 64
17147 open("/var/run/fail2ban/fail2ban.pid", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 ENOENT (No such file or directory)
17147 stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2183, ...}) = 0
17147 write(1, "2013-10-15 11:23:53,482 fail2ban.server : ERROR  Unable to create PID file: [Errno 2] No such file "..., 146) = 146
17147 unlink("/tmp/s.sock")             = 0
17147 stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2183, ...}) = 0
17147 write(1, "2013-10-15 11:23:53,483 fail2ban.server : WARNING Forced execution of the server by removing socket"..., 112) = 112
...
17144 connect(3, {sa_family=AF_FILE, sun_path="/tmp/s.sock"}, 13 <unfinished ...>
..
17144 sendto(3, "\200\2]q\0(U\3setq\1U\10loglevelq\2U\0013q\3e.<F2B_END_COMMAND>", 49, 0, NULL, 0 <unfinished ...>
...
17144 sendto(3, "\200\2]q\0(U\3setq\1U\tlogtargetq\2U\r/tmp/f2b2.logq\3e.<F2B_END_COMMAND>", 62, 0, NULL, 0 <unfinished ...>
</pre>

**Comment by sebres** [comment]
I believe it was fixed in 0.10-cs branch (client-server completelly rewritten).
Reopen if I'm wrong...
