### ISSUE TITLE
Pass variable from custom filer to custom email files?

### ISSUE THREAD

**Issue by poblabs** [fail2ban/fail2ban#402]
I'm using fail2ban in conjunction with mod_security to scan my apache log files and ban wordpress brute force attacks. It's working great, but am looking for a little more detail in the email reports. 

I know I can use regex to grab the site name from the log entry. 

So my question: is it possible to set a variable in the filter file containing the regex of the site that was attempted to get into, and pass that variable to a custom email script?

Thanks

**Comment by sebres** [comment]
implemented in #1698
