### ISSUE TITLE
"tripwire" setup

### ISSUE THREAD

**Issue by yarikoptic** [fail2ban/fail2ban#42]
following a question brought up on the mailing list and memories about http://sourceforge.net/projects/tripwire/, it might be cool to get a simple action + filter + jail tandem to implement a simple tripwire  by making iptables log accesses to otherwise unused commonly probed ports.

**Comment by leeclemens** [comment]
Seems excessive now that I think about it, would require logging every DROP/REJECT or inserting a rule where fail2ban does not usually (before any drop? dynamically somehow to see all traffic not explicitly accepted?). I'd probably suggest closing this Issue without further ideas.

**Comment by yarikoptic** [comment]
well -- someone motivated could still come up with some recipe for piping those LOGs to fail2ban (thus avoiding permanent file storage) etc.  Just a wishlist, so why not to keep it floating around?

**Comment by leeclemens** [comment]
Fair enough, I was flipping through the 100+ issues looking for something to help with and was a bit overcome/scattered by so many ... I'll say spurious, for lack of a better word ... requests. This particularly was a bit counter-intuitive to what I have learned as best firewall logging practice, so feel unlikely to be implemented even if coded into fail2ban. Just my two-cents :)

**Comment by yarikoptic** [comment]
ok -- tagged with  a brand new tag and closed to improve SNR on the issue tracker ;)
