### ISSUE TITLE
iptables -m state removed in 3.7 kernels

### ISSUE THREAD

**Issue by grooverdan** [fail2ban/fail2ban#459]
According to http://stackroulette.com/serverfault/358996/iptables-whats-the-difference-between-m-state-and-m-conntrack though http://git.netfilter.org/iptables/commit/?id=e612a9d285477e9951349dd137305393a1255b19 seems to introduce a compatibility layer.

probably need to replace with ctstate

http://inai.de/documents/Perfect_Ruleset.pdf

I'm still looking for which kernel had the ctstate netfilter api there.

**Comment by sebres** [comment]
```bash
uname -r
4.8.0-37-generic
```
And following works still fine (tried on different kernels from 3.2 to 4.8):
```bash
iptables -N f2b-test && iptables -I f2b-test -m state --state NEW
iptables -L f2b-test
  Chain f2b-test (0 references)
  target     prot opt source               destination
             all  --  anywhere             anywhere             state NEW
iptables -F f2b-test && iptables -X f2b-test
```
