### ISSUE TITLE
DNS cache of values for ignore

### ISSUE THREAD

**Issue by grooverdan** [fail2ban/fail2ban#475]
While looking at #401 I see that there is a DNS lookup for domains when going through the filter.inIngoreIPList for every ban.

As DNS has a TTL it may be worth keep in a temporary cache from previous results to look through.

Should we bother doing another DNS query if there is a cached one? I suspect not.

**Comment by leeclemens** [comment]
Why wouldn't the DNS server deal with the DNS record's TTL (as they do)? There are already local DNS caching solutions that have much more robust functionality in this regard.

**Comment by leeclemens** [comment]
I'd hate to reinvent the wheel here, let DNS servers cache; if admins install local DNS caching services - let that work as expected.

**Comment by sebres** [comment]
Done in 0.10-branch
