### ISSUE TITLE
Allow python code based actions

### ISSUE THREAD

**Issue by kwirk** [fail2ban/fail2ban#496]
Reference comments at end of #491.

Add ability to create an _action-name_.py action file. Something along the lines of having a `CustomAction` class with an `__init__` method for accepting the `jail` and `options` (based on current config `[Init]` section. This class should have an `actionStart`, `actionStop`, `actionCheck` method, and also `actionBan` and `actionUnban` methods which accept a `FailTicket`. Static methods could be taken from current `server.action.Action` to ease use of command line e.g. via `executeCmd` and use of `replaceTag`. Inheritance could be used to allow simple overriding of methods to ease addition or customisation of new actions.

Overall would give python familiar users greater power and flexibility.

Current text config files should still be support, as simpler actions, like _iptables_, already work well, and python code would likely be overly complex.

Thought and ideas from @fail2ban/contributors and others welcomed. :smile:

**Comment by johnwbyrd** [comment]
It's not immediately clear to me why running Python code as an action or jail should be any less secure than running arbitrary shell commands.  

Interacting with complicated actions and jails (such as Cloudflare V4) require non-trivial sequences of operations.  It seems to me that the action base class could be extended into an ActionPython class, which interprets provided strings as Python that should be search/replaced with the current list of action variables, and then run in a jail-like environment.

Niceties would include verifying that Python exists on the path, and not permitting any action that depends on Python to run if Python is not accessible (though it should be, given that we are running Python at the moment).

I'm going to politely suggest reopening this, unless someone has a good reason why this cannot be done, aside from nonspecific FUD.
