### ISSUE TITLE
Icewarp POP Log Format

### ISSUE THREAD

**Issue by GuillaumeWinter** [fail2ban/fail2ban#499]
Hi,
I'm trying to setup a jail for pop logs from icewarp http://www.icewarp.com/ on CentOS  ( log format cannot be modified :( ).

It logs in separate files every day (filename has timestamp format *20131217*.log for example)

POP logs lines look like : 
IP_ADDRESS    [B6A3CB90] 10:14:55 >>> -ERR Unknown user or incorrect password

I cannot get fail2ban-regex to match because the timestamp is not at the beginning of the line.

How could it be possible to add a new filter for this log format ?

If you need any more details / log extracts, I'd be pleased to give you more.

Thanx in advance.

**Comment by sebres** [comment]
Fixed in #1583.
Custom dateformat (`%%H:%%M:%%S` or more preciser `\] %%H:%%M:%%S`) should be specified in the jail (or filter).
