### ISSUE TITLE
default change - reject instead of drop != making fail2ban better

### ISSUE THREAD

**Issue by leeclemens** [fail2ban/fail2ban#507]
I wanted to create this since I noticed the iptables default was changed from DROP to REJECT --reject-with icmp-port-unreachable

With network security related hardware/software, it is generally thought that DROP is better for a number of reasons:
- common sense "provide as little information as possible" concept. DROP is NO information.
- it eliminates additional processing on the attacked system, caused directly by the attacker
- it eliminates network traffic directly caused by the attacker
- it causes the attacker's attack to take longer (drop = timeout from the attacker's perspective vs. a quick icmp error and the attacker can move on instantly)

I believe DROP or the equivalent behavior is appropriate as a default action and the changes to default to REJECT with ICMP should be reverted.

I am welcome to this being a conversation, because a lot of commits would need to be reverted...while I greatly appreciate the dynamic nature of setting the action which was added in the same commits.

I understand these are only defaults and they are overridable, but I also believe default settings should be 'best practice' and most widely used....and I believe DROP rather than REJECT with ICMP fits that criteria.

**Comment by demis-palma** [comment]
[Industry best practices](http://www.chiark.greenend.org.uk/~peterb/network/drop-vs-reject) say that:
> "DROP offers no effective barrier to hostile forces but can dramatically slow down applications run by legitimate users. DROP should not normally be used."

**Comment by leeclemens** [comment]
@demis-palma I'm not sure why you drug this up (or what your link text "Industry best practices" is based upon), but your quote says it all :) You offer one benefit of using DROP as opposed to REJECT and no down side.

**Comment by demis-palma** [comment]
Since all of you have talked about Industry best practices, but nobody has cited a reliable source for the claim, I just linked the best source I could find.
I've done it for future readers. I don't expect leeclemens to read the document linked, and judging on his reply, he didn't.

**Comment by yarikoptic** [comment]
Thanks everyone for the participation.
This issue was closed and I consider it having enough of discussion, thus locking it to let it RiP ;)
