### ISSUE TITLE
Fail2ban does not work after upgrading to 0.8.11 - Auto detect backend method problem

### ISSUE THREAD

**Issue by remotehelp** [fail2ban/fail2ban#509]
Hello people!

Fail2ban does not work after upgrading to 0.8.11 - Auto detect backend method problem

Read for details:
http://www.remoteshaman.com/unix/common/fail2ban-does-not-work-after-upgrading

or translate version:
http://translate.google.com/translate?client=tmpg&hl=en&langpair=ru|en&u=http%3A//www.remoteshaman.com/unix/common/fail2ban-does-not-work-after-upgrading%3Fhitcount%3D0

**Comment by leeclemens** [comment]
Very old version, no update for almost a year and a half...
