### ISSUE TITLE
pyinotify back end to support globs

### ISSUE THREAD

**Issue by grooverdan** [fail2ban/fail2ban#511]
the pyinotify add_watch method seems to support it (with glob and recurs, and auto_add arguements). Just need to be more careful with paths/patterns in the filterpyinotify callback

For #499 and http://sourceforge.net/mailarchive/forum.php?thread_name=52B1AC22.2000701%40whyscream.net&forum_name=fail2ban-users

Need also to catch events to close FileContainers IN_CLOSE_WRITE and OPEN in case it gets opened again.

**Comment by sebres** [comment]
Just as link to #1379

**Comment by sebres** [comment]
Further in #1379, so I close it.
