### ISSUE TITLE
Jails are not working properly while adding same filter into two jails

### ISSUE THREAD

**Issue by letscorp** [fail2ban/fail2ban#57]
Hi There,

When adding two are more jails with the same filter and have a different bantime and findtime, the jails are started perfectly and working fine. But any one of the enabled jail with same filter will block the IP address. And other jails are not working properly.

While verifying the status of each jails, any one of the jail have "Currently failed" and "Total failed" list and all other jails status having zero in "Currently failed" and "Total failed" list. 

My jail.conf configuration are as follows,

[ssh-iptables]

enabled  = true
filter   = sshd
action   = iptables[name=SSH, port=ssh, protocol=tcp]
           sendmail-whois[name=SSH, dest=root, sender=fail2ban@localhost]
logpath  = /var/log/secure
bantime  = 600
findtime  = 300
maxretry = 3

[ssh-frequent]

enabled  = true
filter   = sshd
action   = iptables-allports[name=SSH-FREQUENT, protocol=all]
           sendmail-whois[name=SSH-FREQUENT, dest=root, sender=fail2ban@localhost]
logpath  = /var/log/secure
bantime  = 86400
findtime  = 604800
maxretry = 20

Is this above jail configuration have any problem?. If yes, please suggest configuration to block the IP with different bantime and findtime for same filter and jail.

My Fail2ban version: Fail2Ban v0.8.6
My Python version: Python 2.6.8

Regards,
Vella

**Comment by vnanobashvili** [comment]
Investigating fail2ban.log issue - the file took 100% of disk space on the host and fail2ban service along with other logging (httpd access/errors ) have stopped working. The file took almost 18GB out of 20GB allocated to the VM.
fail2ban.log is showing a lot of log records for the last two days related to fail2ban.datedetector in DEBUG mode. Might be related to daylight saving issue.

**Comment by vnanobashvili** [comment]
Head of the fail2ban.log file is showing that the issue began at around daylight savings time change:
2017-03-12 03:35:01,802 fail2ban.server [4219]: INFO rollover performed on /var/log/fail2ban.log
2017-03-12 03:35:02,147 fail2ban.filterpoll [4219]: DEBUG /var/log/httpd/access_log has been modified
2017-03-12 03:35:02,148 fail2ban.datedetector [4219]: DEBUG Sorting the template list
2017-03-12 03:35:02,148 fail2ban.datedetector [4219]: DEBUG Winning template: Day(?P<_sep>[-/])MON(?P=_sep)Year[ :]?24hour:Minute:Second(?:\.Microseconds)?(?: Zone offset)? with 3440 hits
2017-03-12 04:00:12,006 fail2ban.filterpoll [4219]: DEBUG /var/log/httpd/access_log has been modified
2017-03-12 04:00:12,007 fail2ban.filter [4219]: INFO Log rotation detected for /var/log/httpd/access_log
2017-03-12 04:00:12,008 fail2ban.datedetector [4219]: DEBUG Matched time template Day(?P<_sep>[-/])MON(?P=_sep)Year[ :]?24hour:Minute:Second(?:\.Microseconds)?(?: Zone offset)?
2017-03-12 04:00:12,009 fail2ban.datedetector [4219]: DEBUG Got time 1489291212.000000 for "u'12/Mar/2017:04:00:12 +0000'" using template Day(?P<_sep>[-/])MON(?P=_sep)Year[ :]?24hour:Minute:Second(?:\.Microseconds)?(?: Zone offset)?
2017-03-12 04:00:12,010 fail2ban.datedetector [4219]: DEBUG Sorting the template list
2017-03-12 04:00:12,010 fail2ban.datedetector [4219]: DEBUG Winning template: Day(?P<_sep>[-/])MON(?P=_sep)Year[ :]?24hour:Minute:Second(?:\.Microseconds)?(?: Zone offset)? with 3441 hits

**Comment by vnanobashvili** [comment]
Any ideas what could have caused the issue? I believe something related to the time - although the VM is running time zone in UTC. Any help will be appreciated. Can I delete the fail2ban.log file and will it be recreated if I restart fail2ban service or the VM itself?

**Comment by sebres** [comment]
> Head of the fail2ban.log file is showing that the issue began

I don't see any issue here (that all is normal if it running in debug level)
I hope you've not the recidive jail on (because it's very bad idea to do this together with debug level).
> Can I delete the fail2ban.log file

yes

And switch log level to INFO. 
DEBUG is a log level that should be used temporary only.

**Comment by vnanobashvili** [comment]
Cool, thanks. What is a recidive jail?

**Comment by sebres** [comment]
> What is a recidive jail?

https://github.com/fail2ban/fail2ban/blob/master/config/jail.conf#L743

**Comment by vnanobashvili** [comment]
Got it. Basically I am using a separate jail for persistent abusers - which btw is suing the same action expression only of course in a different action file. Basically that persistent jail of course scans fail2ban.log for repeated bans. Would this be a problem, or could have caused the problem?

**Comment by sebres** [comment]
As I already wrote recidive (so scanning of fail2ban.log) and debug level together is very bad idea.
No matter which name your recidive filter/jail/action have.
The scanning of fail2ban.log + debug is evil.

**Comment by vnanobashvili** [comment]
Excellent! thanks for you help Sebres, that was really helpful and informative.

**Comment by vnanobashvili** [comment]
Anybody knows how to put multiple IP checks in a filter file?

**Comment by sebres** [comment]
> put multiple IP checks in a filter file?

If you meant multiple IPs in the single line of the log-file - it is currently impossible (without hacking).

But if you've there a hostname (dns) that represents multiple IPs, the `<HOST>` will match it and all its IPs will be blocked out of the box (if `usedns = yes` or `usedns = warn`).

This issue is a wrong place to do that.
And please be more concrete next time (to also understand the people what you are asking). e. g. provide some example resp. excerpt of such log-file.

**Comment by vnanobashvili** [comment]
what I asked is the following,:

When there is a proxy or proxy chain and you want to ban the last IP address from the chain:
If you put X-Forwarded-For - Apache log record would be appended by that header in the end

client IP, proxy1IP, proxy2IP

If I want to ban/unban the last IP address - proxy2IP - any idea how to do that? do I put multiple <HOST> expressions in the filter? Any suggestions...

**Comment by vnanobashvili** [comment]
multiple <HOST> expressions I meant

**Comment by vnanobashvili** [comment]
oh this is filtering for HOST

**Comment by sebres** [comment]
> If I want to ban/unban the last IP address 

I told you - provide an example.
I told you - wrong place here (make new issue, resp. seek for helps anyplace else (stackoverflow or similar).

Nevertheless, `fail2ban-regex` is your friend by building of the filter rules.
```bash
fail2ban-regex -v '2017-01-01 10:00:00 log line with 3 IPs: 1.2.3.4, 2.3.4.5, 3.4.5.6' '^\s*log line with 3 IPs: \S+, \S+, <HOST>$'
...
Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] ^\s*log line with 3 IPs: \S+, \S+, <HOST>$
|      3.4.5.6  Sun Jan 01 10:00:00 2017
`-
...
```

> multiple `<HOST>` expressions

As already said is not possible (`<HOST>` is a capture, only one capture allowed, only one success regex match per line possible, etc.) But as if I understand correctly you need only last IP. See example above.

**Comment by eharris** [comment]
I am still seeing this in 0.9.6-2 (Debian stable/stretch version).  I have two jails for sshd:

`
[sshd]
enabled  = true
maxretry = 6

# And a second ssh that gets quick hack attempts with long delays between bursts
[sshd_burst]
enabled  = true
maxretry = 3
filter   = sshd
findtime = 10
bantime  = 86400  # 1 day
`

Using this, only the first one `[sshd]` is ever detected in my logs, `[sshd_burst]` is never detected.

**Comment by vnanobashvili** [comment]
Strange, you are following up on a 5 year old issue, which is not relevant
for a long time now... You can close whatever you want to close. I don't
even recall what it was about...
Regards,


Vlad Nanobashvili,
MBA | CISSP-ISSAP | CCSP | CISM | CCSK | P.Eng

[image: Inline image 1]

**Comment by sebres** [comment]
> Has this issue been fixed?

@m2acgi What is your issue exactly? The subject says "Jails are not working properly while adding same filter into two jails". 
Fact is you can have hundred jails with the same filter (the filter only describes the monitoring rules like `failregex` etc). 
I don't know any reason where the filter of one jail would somehow bother another jail (also don't think it was ever true for some older version). So there was simply nothing to fix.

However if it is about such recidive jails (like in examples above, so jails monitoring the same log or journal) - you don't need second jails like that at all - newer version (>= 0.11) has a new feature `bantime.increment`, which can help to eliminate recidive evildoers (ban them for longer time and faster by repeated attempts).

One possible issue you can have probably would be the large `findtime` (in example above `findtime = 604800` is 7 days). Namely with the memory (and possibly the performance) due to large list of failures - fail2ban could cumulate a lot of failures in 7 days, so the list can be really huge.
For a similar discussion about large `findtime` window this see #2118 or #https://github.com/fail2ban/fail2ban/issues/2911#issuecomment-760925717

For another possible reasons why something doesn't work please see the FAQ in https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works

**Comment by m2acgi** [comment]
@sebres Thank you for your reply.

Sorry for my poor English. My jail conf like this:

```
[my-app]
enabled  = true
port     = 1234
logpath  = /root/my-app/logs/my-app-out.log

bantime  = 365d
findtime = 5m
maxretry = 3
```

The hackers try several times with different IP then they know the value of findtime and maxretry, then the hackers can use another IP to excute brute-force attacks.

As I've set very long ban time, so `bantime.increment` is not an good option.

What I want exactly to do is to create mutile jails, monitor the same one log, like this:

```
[my-app1]
enabled  = true
port     = 1234
filter   = my-app
logpath  = /root/my-app/logs/my-app-out.log

bantime  = 365d
findtime = 5m
maxretry = 3


[my-app2]
enabled  = true
port     = 1234
filter   = my-app
logpath  = /root/my-app/logs/my-app-out.log

bantime  = 365d
findtime = 24h
maxretry = 10
```

Is this supported by fail2ban ?

Thanks.

**Comment by sebres** [comment]
> Twice every 5 minutes, or 3 times every 6 minutes.

Well, you could simply increase the `findtime` and `maxrerty` to get the same burst as the first jail, so would not need the 2nd jail. 

> As I've set very long ban time, so bantime.increment is not an good option.

You don't need such long ban times (something like few weeks or months is fully enough)... But by bantime.increment you can control the distance to further bans with `bantime.factor`, `bantime.formula` or`bantime.multipliers`.
Also setting `bantime.rndtime` can help to confuse "smart" bots to estimate a bantime.
But OK.

> Is this supported by fail2ban ?

Sure. The jails are totally independent, so there is no reason why 2nd jail must ignore some of 10 attempts in 24h (also if they are noticed by 1st jail too).
The only issue I can imagine if the banning action doesn't distinguish the chains by the rules, so creates the same rule for both jails, and either the net-filter don't allow duplicates (you'd see the error in fail2ban.log in that case after 2nd ban) or removes both rules by unban of the earliest ticket (so the attacker is able to connect during active long ban). Example of such action can be `shorewall` e. g. #2031 or `route` e. g. #2373.
Another issue with banning action may be your long bantime, for instance some actions, like `iptables-ipset` previously used own expiration and the value could be too large, e. g. `ipset` doesn't allow timeout larger than 2147483 which means 24d (this also would produce an error in fail2ban.log), see #2703 where it was fixed for `iptables-ipset` action.

Anyway until you don't provide more data (what exactly "doesn't work" mean in your case) we'd be unable to help you.
Doesn't second jail find the attempts from some IP (no `[my-app2] Found` in fail2ban.log)?
Doesn't second jail ban the IP after 10 findings in 24h (no `[my-app2] Ban` in fail2ban.log)?
Ban is there, but evildoer is still able to connect?
Etc.

I already show you the link to our FAQ where the reasons for all that reasons are pretty good described - https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works

Please check all that firstly and if you mean being affected by some another problem, provide the excerpt of my-app-out.log (illustrating the issue for some IP), fail2ban.log (with some errors, or grep by IP/errors) or dump of `fail2ban-client -d` that show the whole configuration for both jails.

And last but not least, stupid question: is the 2nd jail really active - did you restart/reload the fail2ban after you added the 2nd jail to jail.local?

**Comment by m2acgi** [comment]
:thumbsup: Thank you very much!
