### ISSUE TITLE
Fail2ban 0.8.12 doesn't catch anything with pyinotify [ArchLinux armv6]

### ISSUE THREAD

**Issue by Anthony25** [fail2ban/fail2ban#597]
Hello,
Fail2ban doesn't catch anything with pyinotify since the upgrade to 0.8.12, whereas it works with gamin.
Even in verbose mode, I don't see any error in the logfile, and fail2ban detects pyinotify, so I don't see what is wrong...

ArchLinux ARMv6 (Raspberry Pi)

Thank you !

**Comment by leeclemens** [comment]
Please upgrade...it's been a long time, so I'm going to close this now. Please reopen if you use the latest version and still experience this issue.
