### ISSUE TITLE
include multiple jail config snippets/files

### ISSUE THREAD

**Issue by jnorell** [fail2ban/fail2ban#622]
It would be nice if fail2ban supported including multiple config pieces from external files, eg. maybe:

<pre>
include jail.d/*.conf
include jail.d/*.local
</pre>

This would allow a place for system packages to provide appropriate config snippets to be updated by packages or external systems, like you can with filter.d and action.d.

I do realize the jail config is local to the system, but there are use cases where it would be very useful, eg. in the DTC webhosting control panel.  DTC changes dependencies/daemons at times, and has some non-standard log file locations setup; it could provide jail configuration that is always up to date, without having to try to parse/update jail.local, which is currently the only option.

Can a .conf provide all the config bits, then a .local file override specific settings for the same section name?  (Ie. the .local doesn't wipe out an entire .conf section of the same name.)  If so it should be fairly safe; the admin can override the default settings if needed, or simply set enabled = false if desired.

**Comment by kfcviptel** [comment]
I've been looking for an exact answer, does it override or append.
in jail.conf we have
ignoreip = 127.0.0.1/8

In jail.d/home.conf I then have
ignoreip = myip

Will this discard whitelist of 127.0.0.1/8?

**Comment by sebres** [comment]
> Will this discard whitelist of 127.0.0.1/8?

Only for the jail `home`

If you need to extend it, you can use (>= 0.9.4): 
```
ignoreip = %(known/ignoreip)s myip
```

You can see wich parameters the jail will get using dump:
```
fail2ban-client -d | grep home
```

BTW directly modifying of the stock configuration files is wrong (use *.local instead). See https://github.com/fail2ban/fail2ban/wiki for more information.

**Comment by kfcviptel** [comment]
Thanks for the clarification.
