### ISSUE TITLE
dest for sendmail-whois doesn't accept multiple emails addresses

### ISSUE THREAD

**Issue by ranamalo** [fail2ban/fail2ban#632]
Using a space like this:

sendmail-whois[name=SSH, dest=user1@domain.com user2@domain, sender=fail2ban@example.com, sendername="Fail2Ban"]

results in a complaint in the maillog of:
554 Transaction failed: Domain contains control or whitespace

Using a comma like this:

sendmail-whois[name=SSH, dest=user1@domain.com, user2@domain, sender=fail2ban@example.com, sendername="Fail2Ban"]

results in an error upon restart:

Starting fail2ban: ERROR  Invalid argument ['user2@domain.com'] in 'name=SSH, dest=user1@domain.com, user2@domain.com, sender=fail2ban@example.com, sendername="Fail2Ban"'

**Comment by szepeviktor** [comment]
@yarikoptic This causes the following error in `| /usr/sbin/sendmail -f <sender> <dest>`
```
Sep  7 13:55:22 mangare courieresmtp: id=0000000000080365.0000000055ED7B29.00005BB4,from=<fail2ban@mangare.olaszelelmiszer.hu>,addr=<admin@szepe.net,***@gmail.com>: 401 4.1.3 Bad recipient address syntax
```

**Comment by szepeviktor** [comment]
The `To:` header needs a comma but sendmail needs spaces.

**Comment by szepeviktor** [comment]
I've added a `cc` variable to `action = ...` and `Cc: <cc>` to the email template in the action.
