### ISSUE TITLE
pass2allow

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#648]
Allowing hosts to connect (e.g. to FTP)
https://gist.github.com/szepeviktor/9606110

Does it make sense?

**Comment by leeclemens** [comment]
I think this should be closed.

At least as I understand it, make an HTTP request to /knocking/ and get unbanned? If I'm wrong, please let me know.

As fail2ban is essentially a 'security device/software', having an unauthenticated way to get around a firewall just seems like a bad idea.

**Comment by szepeviktor** [comment]
Deer @leeclemens!
This is not for unbanning a previously banned IP.
This is something like [knockd](http://www.zeroflux.org/projects/knock), it opens up a port that is closed by default like much abused FTP or SSH. And you won't receive that much emails.

- port closed
- you knock in at a special URL or HTML forms that does a POST and writes into `error.log`
- pass2allow opens up the port for a predefined time (`bantime`)
- you may use the opened port now
- you should finish before `bantime` elapses
- the port then gets closed

**Comment by leeclemens** [comment]
Seems like this can be done already ? This seems like a too much of a corner case to be incorporated into fail2ban. If you disagree, please let me know, but it seems may be a lot of better ways to achieve what seems to be your root objective (authenticated file transfer?).

**Comment by szepeviktor** [comment]
May I get a link if I open a repo?
`fail2ban-pass2allow`

**Comment by yarikoptic** [comment]
Actually (as a former user of knocking setups) I think it might be a worthwhile addition to fail2ban since it indeed seems to be quite simple to implement and would be of use without demanding new tools to be installed etc.  So if I got it right -- we would need just a werserver specific filter/regex + jail definition with blocktype=accept and maxretry=1.  Correct @szepeviktor ?

**Comment by leeclemens** [comment]
new configs are one thing :) Is there a pull request associated with this? It seems like everything was already figured out ~16 months ago (precipitous for me closing it).

**Comment by szepeviktor** [comment]
@yarikoptic Yes.
The protected service (could be FTP, SSH, POP3, anything that can be abused) is closed by an iptables rule. When pass2allow filter triggers pass2allow action than this protected service get opened to one IP address only.

**Comment by yarikoptic** [comment]
@szepeviktor yeap -- I know how knocking works ;)  @leeclemens -- indeed PR would be nice, and it should "Fix" this issue then if @szepeviktor is planing to craft one... if not, please close this issue @szepeviktor 

Cheers!

**Comment by leeclemens** [comment]
knocking is not reliable for NAT'ed clients and does not prevent sending credentials in cleartext (FTP/POP3, etc), personally I'd suggest not relying on it. Inclusion in fail2ban may imply some level security.

**Comment by szepeviktor** [comment]
Excuse me.
FTPS, SSH, POP3S.

**Comment by leeclemens** [comment]
Are you relying on only knocking for Authentication? (Also, you haven't addressed knocking to Authorize an IP when they are NAT'd.)

**Comment by szepeviktor** [comment]
"If you know the HTTP/AUTH password you can *try* to log into SSH for an hour."

**Comment by leeclemens** [comment]
I see you still avoid the NAT issue I continue to pose. Still seems a bit security through obscurity to me. fail2ban is suited to watching SSH logs for failed logins and blocking access. Won't fail2ban just block their failed SSH attempts anyway?  I guess you could be avoiding a few initial attempts, but what is your ultimate goal here? (And can you address the NAT problem with your approach?)

**Comment by szepeviktor** [comment]
You're right. If someone behind NAT knocks in, everyone on that NAT will have access to the protected service. But that service also need authentication. So all those NAT users only get a chance to abuse that service.

**Comment by leeclemens** [comment]
Isn't fail2ban designed to prevent users from "abusing" the service? There is a gap between being denied  TCP access to the port and being allowed to fail authentication 3-whatever times...I'm just trying to assess the value of it (I assume your fail2ban setup also blocks access after X failed attempts...even after they 'knocked' in?).

**Comment by szepeviktor** [comment]
Oh! I see your point.
After opening the TCP port other jails could ban the user.

**Comment by yarikoptic** [comment]
On Fri, 03 Jul 2015, Viktor Szépe wrote:

>    You're right. If someone behind NAT knocks in, everyone on that NAT will
>    have access to the protected service. But that service also need
>    authentication. So all those NAT users only get a chance to abuse that
>    service.

There is always a tradeoff between features and security.  If I come up
with a knocking URL someone discovers to abuse it (I do not access from
public NAT), I would need to change that URL after detecting all those
failed attempts sneaking in.   So how likely I would get a
persistent attacker on my NAT -- close to 0% chance.  Thus I would use
this feature comfortably.

But your point is valid, so for this jail/action we should provide a
clear description/warning on possibility of abuse from local NAT folks,
or from anyone else happen you share your logs/stats from the webserver
publicly ;)

**Comment by leeclemens** [comment]
Agreed, If configs are contributed, and properly warned about (re: NAT, obfuscation), I'm probably fine with it :)  Multiple attackers behind a NAT exist, like it or not. So long as no one is forced to use this (imho) horrible 'security' scheme. And it's not two-factor authentication, btw.

**Comment by sebres** [comment]
I don't think that we would be responsible for incorrect setting up knocking together with NAT. The same applies to proxy etc. People, which allow such access without authentication, didn't understand basic concepts, but that has nothing to do with the f2b self.
Knocking, whether port or http(s), would be basically a good supplement for f2b and this feature will make this easier, imho, it's alright.

**Comment by szepeviktor** [comment]
Continuing in https://github.com/fail2ban/fail2ban/pull/1112
