### ISSUE TITLE
FreeSWITCH Can't find user filter

### ISSUE THREAD

**Issue by nandy1925** [fail2ban/fail2ban#649]
Just thwarted an attack.  I was wondering why the filter didn't detect "Can't find user" warnings.  The attacker used alphabetic username. So I modified [\d+@\d...] into [.+@\d...] to catch all characters used.

```
failregex = ^\.\d+ \[WARNING\] sofia_reg\.c:\d+ SIP auth (failure|challenge) \((REGISTER|INVITE)\) on sofia profile \'[^']+\' for \[.*\] from ip <HOST>$
            ^\.\d+ \[WARNING\] sofia_reg\.c:\d+ Can't find user \[\d+@\d+\.\d+\.\d+\.\d+\] from <HOST>$
```

Modified filter

---

```
failregex = ^\.\d+ \[WARNING\] sofia_reg\.c:\d+ SIP auth (failure|challenge) \((REGISTER|INVITE)\) on sofia profile \'[^']+\' for \[.*\] from ip <HOST>$
            ^\.\d+ \[WARNING\] sofia_reg\.c:\d+ Can't find user \[.+@\d+\.\d+\.\d+\.\d+\] from <HOST>$
```

**Comment by nandy1925** [comment]
Just made another modification to the filter containing the line Can't find user ...
From "Can't"  to "Can.t". It seems it didn't catch '.  I was wondering because in this thread it was able to catch those warning messages.

**Comment by ramifourati** [comment]
Hi,
I configured fail2ban for my freeswitch but its not working for freeswitch i don't know why it worked for ssh fine and then it didn't work.
Any help is much appreciated

**Comment by sebres** [comment]
Seems to be fixed. 
Currently tested with:
```bash
$ fail2ban-regex "Mar 17 12:43:14 freeswitch freeswitch[31461]: 2014-03-17 12:43:14.571392 [WARNING] sofia_reg.c:2543 Can't find user [edc@168.6.124.171] from 188.138.4.208" freeswitch
...
Lines: 1 lines, 0 ignored, 1 matched, 0 missed
```

**Comment by Mimikoo** [comment]
the regex
`^\.\d+` \[WARNING\] sofia_reg\.c:\d+ Can't find user \[.+@\d+\.\d+\.\d+\.\d+\] from <HOST>$`
does not work if domain is in alphanumeric like: example.com I use:
`^\.\d+ \[WARNING\] sofia_reg\.c:\d+ Can't find user \[.+@.+\] from <HOST>$`
fail2ban-regex detects this kind of intrusion, but fail2ban daemon doesnot detect. freeswitch.log have o+r and subsequent path to it is readable.

**Comment by sebres** [comment]
> the regex does not work if domain is in alphanumeric like: example.com

Please show here an example (better an excerpt of the log-file)...

> fail2ban-regex detects this kind of intrusion, but fail2ban daemon doesnot detect

This is impossible - both use the same failure detection API... 
The only thing that going is vice versa, if called with `--usedns=no` for lines without IP (but hostname instead).
Could you please provide an example.

**Comment by Mimikoo** [comment]
I've resolved the problem, despite fail2ban-regex works on
`^\.\d+ \[WARNING\] sofia_reg\.c:\d+ Can't find user \[.+@.+\] from <HOST>$`
fail2ban daemon does not correctly detect lines:
`2017-08-15 15:34:54.304373 [WARNING] sofia_reg.c:2679 Can't find user [216@example.com] from 5.62.63.147`
See the start of line where timestamp is write. So I changed to:
`\[WARNING\] sofia_reg\.c:\d+ Can't find user \[.+@.+\] from <HOST>$`
And fail2ban detects this regex.

**Comment by Mimikoo** [comment]
I want to mention that this is Debian Squeezy (yes its old) system. fail2ban v0.8.4-SVN
I used this script for freeswitch:
https://raw.githubusercontent.com/fail2ban/fail2ban/master/config/filter.d/freeswitch.conf
I see in latest fail2ban a freeswitch.conf filter. I'l try to use this one.

**Comment by Mimikoo** [comment]
Yes, freeswitch.conf from 0.11 branch works fine, but fail2ban-regex does not detect this kind of fails. All of this gives 0 matches:
`fail2ban-regex "2017-08-15 08:45:36.704403 [WARNING] sofia_reg.c:2679 Can't find user [160@example.com] from 5.62.63.147" "%(_pref_line)s \[WARNING\] sofia_reg\.c:\d+ Can't find user \[[^@]+@[^\]]+\] from <HOST>$"
fail2ban-regex "2017-08-15 08:45:36.704403 [WARNING] sofia_reg.c:2679 Can't find user [160@example.com] from 5.62.63.147" "^%(__prefix_line)s(?:\d+-\d+-\d+ \d+:\d+:\d+\.\d+)? \[WARNING\] sofia_reg\.c:\d+ Can't find user \[[^@]+@[^\]]+\] from <HOST>$"
fail2ban-regex "2017-08-15 08:45:36.704403 [WARNING] sofia_reg.c:2679 Can't find user [160@example.com] from 5.62.63.147" "^(?:\d+-\d+-\d+ \d+:\d+:\d+\.\d+)? \[WARNING\] sofia_reg\.c:\d+ Can't find user \[[^@]+@[^\]]+\] from <HOST>$"`

But fail2ban daemon detects correctly.

**Comment by sebres** [comment]
> fail2ban-regex does not detect this kind of fails

the `%(_pref_line)s` interpolation can be substituted only within the filter self, if you tested it from command line give the filter-name `/etc/filter.d/freeswitch.local` or the fully substituted expression (or built manually).
Note: the date part (corresponding matched date-pattern) will be cut out from string before supplied to `failregex` search.

```bash
ln="2017-08-15 15:34:54.304373 [WARNING] sofia_reg.c:2679 Can't find user [216@example.com] from 5.62.63.147"
# 0.11 (0.10) via filter "freeswitch" or use "/etc/fail2ban/filter.d/freeswitch.conf" for versions < 0.10:
$ fail2ban-regex "$ln" freeswitch
# 0.11 (0.10) via manually failregex:
$ fail2ban-regex "$ln" "^\s*\[WARNING\] sofia_reg\.c:\d+ Can't find user \[[^@]+@[^\]]+\] from <HOST>$"
# any version, note: the millisecond-part (?:\.\d+)? is optional (will be cut out since 0.10th version, but not in previous versions):
$ fail2ban-regex "$ln" "^(?:\.\d+)? \[WARNING\] sofia_reg\.c:\d+ Can't find user \[[^@]+@[^\]]+\] from <HOST>$"
```
All three variants returns:
```
Lines: 1 lines, 0 ignored, 1 matched, 0 missed
```

> I want to mention that this is Debian Squeezy (yes its old) system. fail2ban v0.8.4-SVN

Firstly v0.8.4 is very-very old.
The config-files of newer (especially 0.10/0.11) versions can be incompatible (and we have neither the time nor the fancy to discuss here about how make it runable for such old versions. 
Too many things to take to the account (dependencies in code and other config-files, new features, etc.).
Just update your version...

**Comment by Mimikoo** [comment]
Yes version is old. It is from Debians repository. It can't be updated without updating Debian. Eventually I'll switch vis box to new version.
freeswitch.conf from v.0.11 did enabled detecting of intrusion inf the old fail2ban. This is a workaround for this box. For example this:
fail2ban-regex "$ln" freeswitch
will not work on old version. i just was confused that fail2ban-regex detected pattern, while fail2ban daemon did not. So this is an old version's problem.
Thanks for support. Seems I needed to post here to find some workarounds.

**Comment by sebres** [comment]
FWIW: [wiki](https://github.com/fail2ban/fail2ban/wiki/How-to-test-newer-fail2ban-version-resp.-use-fail2ban-standalone-instance) - to try fail2ban newer version without the installation (resp. standalone portable version).

**Comment by Mimikoo** [comment]
Thanks for suggestion. I will try this one when some errors I will see. For now if it is working - don't touch it. :)
