### ISSUE TITLE
Spurious fail2ban-client: WARNING Wrong value for 'loglevel' in 'Definition'. Using default one: ''INFO'' in log

### ISSUE THREAD

**Issue by opoplawski** [fail2ban/fail2ban#657]
Fresh 0.9 build for Fedora.  On startup get this in the log:

```
fail2ban-client: WARNING Wrong value for 'loglevel' in 'Definition'. Using default one: ''INFO''
```

But loglevel = INFO in [Definition] in /etc/fail2ban/jail.conf.

**Comment by larssn** [comment]
This is still present in the default config in 0.9.5. Setting loglevel to 1 makes it go away.
