### ISSUE TITLE
openvpn filters

### ISSUE THREAD

**Issue by yarikoptic** [fail2ban/fail2ban#725]
There was http://bugs.debian.org/748076 with tentative openvpn filters... 

```
failregex = .* ovpn-.* ::ffff:<HOST> Connection reset, restarting \[[0-9-]{1,2}\]
            .* ovpn-.* <HOST> Connection reset, restarting \[[0-9-]{1,2}\]
```

so need to be anchored properly and tested

**Comment by leeclemens** [comment]
Is `Connection reset, restarting` the log of the "failure"? i.e. If someone's connection is reset, they should be determined as bad and subsequently blocked by fail2ban? Or should we just be matching the AUTH_FAILED log @kwirk provided?

**Comment by sebres** [comment]
No idea what are the troubles to construct a filter for this old issue, RE is pretty simply:
```bash
$ msg='May 16 14:05:31 vpn-open1 ovpn-serveur-tcp[32360]: ::ffff:85.25.124.92 Connection reset, restarting [-1]'
$ fail2ban-regex "$msg" '^\s*\S+ \S+\[\d+\]: <ADDR> Connection reset, restarting \[-1\]'

Running tests
=============

Use   failregex line : ^\s*\S+ \S+\[\d+\]: <ADDR> Connection reset, resta...
Use      single line : May 16 14:05:31 vpn-open1 ovpn-serveur-tcp[32360]:...


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] ^\s*\S+ \S+\[\d+\]: <ADDR> Connection reset, restarting \[-1\]
|      85.25.124.92  Sat May 16 14:05:31 2020
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] {^LN-BEG}(?:DAY )?MON Day %k:Minute:Second(?:\.Microseconds)?(?: ExYear)?
|  ...
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.01 sec]
```

Thus closed.

**Comment by sthibaul** [comment]
> No idea what are the troubles to construct a filter for this old issue, RE is pretty simply

The question is not to construct a filter, but to include it in fail2ban filters, so downstreams don't have to each invent its own one.

**Comment by sebres** [comment]
To include it to fail2ban filters we'll need more info (at the moment impossible without jail due to rude test cases), basically everything what should be set by default in jail - logpath (or/and journal unit), port(s), etc.
Also the question is whether the log format is still the same (unchanged since 2014).
