### ISSUE TITLE
action_mwl and multi logs breaks start up

### ISSUE THREAD

**Issue by jomu78** [fail2ban/fail2ban#727]
Hi,

the patch from issue #231 never made it to a release, did it? AFAIK 0.8.13 still comes with the unpatched file.

jail.local

```
[apache]
enabled = true
port    = http,https
filter  = apache-auth
logpath = /var/log/apache2/error.log
          /var/customers/logs/*error.log
maxretry = 3
action  = %(action_mwl)s
```

Leads to. 

```
[....] Restarting authentication failure monitor: fail2banERROR  Error in action definition sendmail-whois-lines[name=apache, dest="<address>", logpath=<path>
ERROR  Errors in jail 'apache'. Skipping...
```

Using action action_mw it works. 
I tried to patch the file manually in my installation but it does not seem to work also. Is there something more I have to do next to changing the line and compile the file?

**Comment by ashakunt** [comment]
Do we have any ETA when this bug is going to be fixed?

**Comment by CNek** [comment]
Same problem here!
