### ISSUE TITLE
Multiple email notifications despite active ban

### ISSUE THREAD

**Issue by mikeg-de** [fail2ban/fail2ban#73]
There's an annoying chinese bot which is already banned in hosts.deny due to falied sshd attempts. Despite that fail2ban keeps sending notification emails. Is there a possibility – or do you consider it as an feature request – to check for an active ban in iptabels and/or hosts.deny before sending notifications?

Kind regards
Mike

**Comment by leeclemens** [comment]
Next week was almost 3 years ago, closing now - hopefully upgrading fixes this :)
