### ISSUE TITLE
systemd service file Restart option

### ISSUE THREAD

**Issue by kwirk** [fail2ban/fail2ban#736]
I was wondering if the _systemd_ service file `Restart` option should be changed from `always` to `on-failure`. There is probably legit reasons for someone to use _fail2ban-client_ to stop the service for example.

_systemd_ documentation for `Restart` option: http://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=

Thoughts @fail2ban/developers and @opoplawski?

**Comment by leeclemens** [comment]
PR's are welcome...the scripts aren't really part of fail2ban (the application) itself...and are subsequently platform/distro dependent. No response in over a year, so I'd suggest this be closed.

**Comment by sebres** [comment]
Fixed in 528a7a5abbf388def344387cd77f8f2fb54b532d
