### ISSUE TITLE
cleanup archaic code

### ISSUE THREAD

**Issue by yarikoptic** [fail2ban/fail2ban#742]
e.g. all the 

```
#@staticmethod
...
bleh = staticmethod(bleh)
```

patterns

**Comment by leeclemens** [comment]
`fail2ban.server.strptime` perhaps as well...a lot of code seems to be replaceable by (now available) built-in python modules (ipv6 related stuff too).

**Comment by sebres** [comment]
I don't know which archaic code we should still have... Reopen if I'm wrong
