### ISSUE TITLE
Error in FilterPyinotify

### ISSUE THREAD

**Issue by ghost** [fail2ban/fail2ban#755]
Hello!
Iam using here Ubuntu 14.04 (x64) and Fail2ban 0.8.13-1. Since a while I get the error: 

fail2ban.filter [22302]: ERROR   Error in FilterPyinotify callback: _strptime_time

I really dont have a idea what to do.
Thanks.

**Comment by leeclemens** [comment]
Pull request: https://github.com/fail2ban/fail2ban/pull/906

**Comment by playeren** [comment]
I just installed fail2ban on a Debian 8.6 with apt-get. I got fail2ban v0.8.13-1 with python-pyinotify v0.9.4-1, and got the `Error in FilterPyinotify callback: 'module' object has no attribute '_strptime_time'` in the fail2ban.log.

Did I get an older version without the fix, or am I doing something wrong?

I can make the error go away by setting backend=polling in jail.{conf|local}

**Comment by szepeviktor** [comment]
BTW you may download Fail2ban from sid as it is an `-all` package.
https://packages.debian.org/sid/fail2ban

**Comment by playeren** [comment]
Thanks @szepeviktor but I'm a bit worried about the hassle of keeping everything updated when mixing stable packages with SID and backports. I'm a wuss :) I'll stick to 'polling' for now, and wait until the fix hits me from a normal upgrade.

**Comment by chdh** [comment]
I also got `Error in FilterPyinotify callback: 'module' object has no attribute '_strptime_time'` on Debian 8.7 + Jessie Backports (fail2ban 0.8.13-1, python-pyinotify 0.9.5-1) and had to set `backend = polling`.

**Comment by NET-057** [comment]
Did all these changes [bug fixed](https://github.com/fail2ban/fail2ban/pull/906/files/d0bcacd97be8d2eac24c048d0f58b5b93ee90340#r22415265) . now that error is fix but not blocking any ip.

**Comment by szepeviktor** [comment]
@NET-057 Are you sure it is not blocking in the last 4 years?

**Comment by NET-057** [comment]
@szepeviktor 3 days ago. i installed fail2ban (v0.8.14) from [Link](https://www.fail2ban.org/wiki/index.php/Downloads). it works fine for CentOS. but when i tried it with ubuntu 14.04 it shows `ERROR Error in FilterPyinotify callback: _strptime_time`. during log parse  

i added 
`from time import strptime
strptime("2012", "%Y")` 

in fail2ban-regex, fail2ban-client, fail2ban-server (as here suggested [Issue](https://github.com/fail2ban/fail2ban/pull/906/files/d0bcacd97be8d2eac24c048d0f58b5b93ee90340#r22415265)) . Error gone but it not blocking IPs now.

**Comment by szepeviktor** [comment]
All right. 😱 I have zero experience in those version of software/opsys in 2021. Maybe someone else will help you.

**Comment by sebres** [comment]
>  i installed fail2ban (v0.8.14) from Link.

Why?... Why you're trying to use version outdated many years ago...
If there is no repo where you can obtain newer version, it is not a big problem to install [newest fail2ban from source](https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually), also for CentOS.

> Error gone but it not blocking IPs now.

First answer in [FAQ from this wiki](https://github.com/fail2ban/fail2ban/wiki/How-fail2ban-works) may help to solve 99% of the issues with banning, just 0.8 is really old, so I also don't know whereas everything described there is basically working for this old version.
