### ISSUE TITLE
race condition?  errored build with python3.3 on travis

### ISSUE THREAD

**Issue by yarikoptic** [fail2ban/fail2ban#767]
https://travis-ci.org/fail2ban/fail2ban/jobs/30270625

```
testStart (fail2ban.tests.action_d.test_badips.BadIPsActionTest) ... 
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

**Comment by leeclemens** [comment]
Been working for a while now, but I have seen badips failing...doesn't seem to be fail2ban's fault though (unreliable/unstable service?). Closing, but cross referencing https://github.com/fail2ban/fail2ban/issues/1089 unless you object.
