### ISSUE TITLE
Unban ip (bantime <0) is not remove from sqlite db

### ISSUE THREAD

**Issue by heximcz** [fail2ban/fail2ban#768]
root@pisek2:/tmp/fail2ban# **ipset list**
Name: f2b-sshd
Type: hash:ip
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 16520
References: 1
Members:
**192.168.239.108**

root@pisek2:/tmp/fail2ban# **fail2ban-client set sshd unbanip 192.168.239.108**
192.168.239.108

root@pisek2:/tmp/fail2ban# **ipset list**
Name: f2b-sshd
Type: hash:ip
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 16520
References: 1
Members:

root@pisek2:/tmp/fail2ban# **/etc/init.d/fail2ban restart**
**[ ok ] Restarting authentication failure monitor: fail2ban.**

root@pisek2:/tmp/fail2ban# **ipset list**
Name: f2b-sshd
Type: hash:ip
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 16520
References: 1
Members:
**192.168.239.108**

...
root@pisek2:/tmp/fail2ban# fail2ban-server -V
**Fail2Ban v0.9.0.dev**

**Comment by heximcz** [comment]
Problem still not resolved. I was test f2b v.0.9.2 with same result. IP is not deleted from db.

my test:

fail2ban-client set conntrack-ddos banip 10.10.10.11
fail2ban-client set conntrack-ddos unbanip 10.10.10.11
(in this step is ipset clear, but ip is still in db)

/etc/init.d/fail2ban restart
(in this step is IP back in ipset)

root@server:/var/lib/fail2ban# sqlite3 ./fail2ban.sqlite3 
SQLite version 3.7.13 2012-06-11 02:05:22
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> select * from bans;
conntrack-ddos|10.10.10.11|1435852772|{"matches": [], "failures": 1}
sqlite>

jail:
[conntrack-ddos]
enabled = true
protocol = all
banaction = iptables-ipset-proto4-allports
filter = conntrack-ddos
logpath = /var/log/messages
maxretry = 1
findtime = 60
bantime = 604800

**Comment by sebres** [comment]
merged.
