### ISSUE TITLE
Action does not seem to get executed

### ISSUE THREAD

**Issue by rprocks** [fail2ban/fail2ban#772]
Have created a sample log file for testing purpose, the contents are as follows

Jul 12 04:31:28 : Failed password for root from 199.71.214.66
Jul 12 04:31:28 : Failed password for root from 199.71.214.66
Jul 12 04:31:28 : Failed password for root from 199.71.214.66
Jul 12 04:31:28 : Failed password for root from 199.71.214.66
Jul 12 04:31:28 : Failed password for root from 199.71.214.66
Jul 12 04:31:28 : Failed password for root from 199.71.214.66
Jul 12 04:31:28 : Failed password for root from 199.71.214.66

running fail2ban-regex says that it mathced all of that, but when I run fail2ban, it does not seem to be running the action part,

filter is
Definition]

failregex = ^%(__prefix_line)sFailed \S+ for .*? from <HOST>$

and my jail.local is
enabled = true
filter = log-catch
backend = gamin
action = sendmail[name=temptest, dest=rakesh_gemin2003@yahoo.co.in]
logpath = /var/log/rakesh.log
maxretry=3

**Comment by leeclemens** [comment]
Please see http://www.fail2ban.org/wiki/index.php/HOWTO_Seek_Help
