### ISSUE TITLE
Fail2Ban autobans after password changed

### ISSUE THREAD

**Issue by kbray** [fail2ban/fail2ban#779]
We are currently using plesk which uses fail2ban, we have an issue where some clients that connect have multiple mailboxes and computers from 1 IP address. If 1 user changes there password from plesk there email client if it is still running will fail auth and autoban their ip address. Then nobody can connect to mail at all as all connections are refused from the ip.

Suggest creating a hash for the tried password and logging it, then make sure subsequent failures are not all the same password hash. If all attempts are the same password then it should not autoban as its definitely not a brute force attempt.

**Comment by leeclemens** [comment]
@kbray do any of the workarounds suggested work for you? As mentioned, fail2ban shouldn't even know the password, or even hash, as it is simply watching log files for regexes of failed auth attempts. If users are behind a NAT, that is a known shortcoming of blocking based upon IP. I'd like to close this issue if there is nothing further.

**Comment by kbray** [comment]
Go ahead and close since fail2ban is limited to the log file makes sense it cant do any more.

-Kris

On Feb 6, 2015, at 8:27 PM, Lee Clemens <notifications@github.com<mailto:notifications@github.com>> wrote:


@kbray<https://github.com/kbray> do any of the workarounds suggested work for you? As mentioned, fail2ban shouldn't even know the password, or even hash, as it is simply watching log files for regexes of failed auth attempts. If users are behind a NAT, that is a known shortcoming of blocking based upon IP. I'd like to close this issue if there is nothing further.

-

**Comment by buanzo** [comment]
You could implement a temporary whitelist for the IP addresses that logged
in succesfully. This way, even if they change their password and the email
client is not immediately updated with the new one,  a ban will not be
implemented.

**Comment by kbray** [comment]
Thats a great idea! Thanks!

-Kris

On Feb 7, 2015, at 5:48 AM, buanzo <notifications@github.com<mailto:notifications@github.com>> wrote:

You could implement a temporary whitelist for the IP addresses that logged
in succesfully. This way, even if they change their password and the email
client is not immediately updated with the new one, a ban will not be
implemented.
On Aug 8, 2014 4:08 PM, "kbray" <notifications@github.com<mailto:notifications@github.com>> wrote:

> We are currently using plesk which uses fail2ban, we have an issue where
> some clients that connect have multiple mailboxes and computers from 1 IP
> address. If 1 user changes there password from plesk there email client if
> it is still running will fail auth and autoban their ip address. Then
> nobody can connect to mail at all as all connections are refused from the
> ip.
>
> Suggest creating a hash for the tried password and logging it, then make
> sure subsequent failures are not all the same password hash. If all
> attempts are the same password then it should not autoban as its definitely
> not a brute force attempt.
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/fail2ban/fail2ban/issues/779>.
>

-

**Comment by leeclemens** [comment]
This issue isn't so much the log files, but that your users are behind a NAT. As you mentioned, I'll go ahead and close this.
