### ISSUE TITLE
Fail2ban for cPanel dovecot

### ISSUE THREAD

**Issue by halimzhz** [fail2ban/fail2ban#791]
Dear All,

I'm looking for 'failregex' to block any auth failed at cPanel /var/log/maillog, the line suppose to monitor is :

Aug 20 00:28:01 hostname dovecot: pop3-login: Disconnected (auth failed, 1 attempts in 6 secs): user=username@xxxx.com, method=PLAIN, rip=xx.xx.xx.xx, lip=yy.yy.yy.yy, session=<UC9C+P0AWgCX+nVM>

So how can i make the failregex to block the 'rip' IP ?

Please help and thank you so much

**Comment by leeclemens** [comment]
This seems the closest, from dovecot-auth (can you test it?):

^%(__prefix_line)s(pop3|imap)-login: (Info: )?(Aborted login|Disconnected)(: Inactivity)? \(((auth failed, \d+ attempts)( in \d+ secs)?|tried to use (disabled|disallowed) \S+ auth)\):( user=<\S*>,)?( method=\S+,)? rip=<HOST>(, lip=(\d{1,3}\.){3}\d{1,3})?(, TLS( handshaking(: SSL_accept\(\) failed: error:[\dA-F]+:SSL routines:[TLS\d]+_GET_CLIENT_HELLO:unknown protocol)?)?(: Disconnected)?)?(, session=<\S+>)?\s*$
