### ISSUE TITLE
Passing options into actions without explicit specification

### ISSUE THREAD

**Issue by mrc0mmand** [fail2ban/fail2ban#793]
As was discussed [here](https://github.com/fail2ban/fail2ban/commit/9fe0a69852e692fd9cc1f47acbf5b13a4d79273f#commitcomment-7451028), it would be better to pass options like 'bantime' into all actions 'globally' without explicit specification in [action shortcuts](https://github.com/fail2ban/fail2ban/blob/master/config/jail.conf#L153-L170).

**Comment by sebres** [comment]
Since 8403eab2c4d71c8662a58ae5fda642aca473ba36 (0.10-incr-dynamic-bantime) merged into #1460 this issue is not relevant anymore.
I'll merge #1460 in 0.10 soon, because in-between it is stable enough.
