### ISSUE TITLE
The detection of Time in a log file should not happen all time

### ISSUE THREAD

**Issue by csabattier** [fail2ban/fail2ban#795]
Since this new version i'm surprise and happy to see a database support in fail2ban and is a very good news :)
I use fail2ban to check different status of log file with different jail and action for a same log file.
So for that i saw in the debug mode each time i restart the server he try to calculate for each jail the time template associate to the log file. 
I saw in datedetector.py what fail2ban does and i saw he make a loop to analyze each line and try to determine the good time template to use getTime(self, line) function.

I'm not expert in python and i didn't  analyze the whole of project but i have the feeling that fail2ban don't check if the file have already a time template detected into it database and they are no condition to ignore date detector in case is already in database.
My guess is : add this condition.
My second guess is about the number of lines to analyze, by example if i have a file of 100MB, i have the feeling that fail2ban will take every lines of the file when he could take just a sample of this file (like 100 lines) to determine the date template to use.
I dont have the time and the expertise to add this functionnality so if anyone can do it,that could be wonderfull.

**Comment by sebres** [comment]
Definitely fixed in 0.10, so I recommend to test it...
I will close it now, just reopen if I'm wrong

**Comment by sebres** [comment]
The fix for this bug was meantime also merged in current master (branch 0.9)
