### ISSUE TITLE
Fail2ban restriction and exclude logfiles?

### ISSUE THREAD

**Issue by JuSSt1** [fail2ban/fail2ban#796]
Hello,

I want to configure my fail2ban to block brute force logins with Wordpress, but i need to exclude some logs when i turn on fail2ban, i have configured jail.conf like this:

logpath = /var/log/httpd/domains/*[!error].log

With this i exclude all logs that contains "error", but i need to do a second filter that contains "mail", so, if i configure jail.conf like this:

logpath = /var/log/httpd/domains/_[!error].log
                /var/log/httpd/domains/_[!mail].log

Fail2ban only loads domains with ".es" but not the rest,is not logic.

My question is, did i something wrong? or how i need to configure jail.conf to make this exclude?

Kind regards.

**Comment by hatifnatt** [comment]
Sorry for reviving this old topic, but I think it can be useful for anybody who came here in search of a solution "how to exclude some logs". Actually globs with negative part work fine. Sample files:
```bash
# ls -1 /tmp/test
a.error.log
a.log
b.error.log
b.log
```
Let's check in Python
```python
>>> import glob
>>> glob.glob('/tmp/test/*.log')
['/tmp/test/a.error.log', '/tmp/test/b.error.log', '/tmp/test/b.log', '/tmp/test/a.log']
>>> glob.glob('/tmp/test/*[!error].log')
['/tmp/test/b.log', '/tmp/test/a.log']
```
I think everything is  pretty clear from example above. All you need is something like `/path/to/logs/*[!exclude_this].log`

**Comment by sebres** [comment]
Indeed, good point @hatifnatt. Thx.

**Comment by tgoeg** [comment]
For anyone coming here in search for excludes:
The above (https://github.com/fail2ban/fail2ban/issues/796#issuecomment-423580283) is wrong, as the test case is incomplete. `[!error]` matches exactly _one_ character that is not `e`,`r` or `o` (so yes, it matches `a` and `b`).
See https://docs.python.org/3/library/fnmatch.html#module-fnmatch for details.

This feature is planned but not implemented yet. See #1379 for the current state of implementation.
