### ISSUE TITLE
Add more info to this warning ...

### ISSUE THREAD

**Issue by binarykitchen** [fail2ban/fail2ban#797]
```
WARNING 'ignoreregex' not defined in 'Definition'. Using default one: ''
   ...done.
```

Can you add which definition? A little more info would be extremely helpful. I have over 20 definitions and do not know to which one this warning is referring to.

**Comment by leeclemens** [comment]
Can you provide more context to this message? What happened before this was printed (did you run a command?) Do you have the full log line?

**Comment by binarykitchen** [comment]
sorry, this ticket is too old and i cannot reproduce it anymore

**Comment by sebres** [comment]
BTW, issue not relevant since #934 (and #858) merged;
