### ISSUE TITLE
Asterisk attackers sometimes use + in phone number which is not found by default filter

### ISSUE THREAD

**Issue by wlorin** [fail2ban/fail2ban#800]
Hi,

I sometimes get failed call attempts to numbers starting with a +, i.e. a line like this:

```
[2014-09-04 09:35:03] NOTICE[2075][C-00001d26] chan_sip.c: Call from '' (79.143.183.36:5070) to extension '+00447024047033' rejected because extension not found in context
'default'.
```

Because of the + in front of the number, the default fail2ban-filter doesn't recognize this as a failed attempt (it only looks for \d+). Hence, I recommend changing line 20 of filter.d/asterisk.conf to this:

```
^(%(__prefix_line)s|\[\]\s*)%(log_prefix)s Call from '[^']*' \(<HOST>:\d+\) to extension '\+?\d+' rejected because extension not found in context 'default'\.$
```

**Comment by sebres** [comment]
it was fixed in #1319
