### ISSUE TITLE
Ask to support date format of delegate

### ISSUE THREAD

**Issue by chtof** [fail2ban/fail2ban#801]
Delegate (www.delegate.org) date format is not currently supported by fail2ban.

To sum up, the date format is like this : 0MONTH/0DAY HOUR:MIN:SEC.?? 

Here is an extract of the log file :
09/04 16:45:36.65 [20311] 2520+0: -- Fork(OnetimeServer): 1400 -> 20311
09/04 17:39:09.28 [20046] 2519+0: {R} NAME OVERFLOW 0/1
09/04 17:39:09.28 [20046] 2519+0: {R} NAME OVERFLOW 0/1
09/04 17:39:09.28 [20046] 2519+0: {R} NAME OVERFLOW 0/1
09/04 17:39:09.28 [20046] 2519+0: {R} NAME OVERFLOW 0/1
09/04 17:39:09.28 [20046] 2519+0: {R} NAME OVERFLOW 0/1
09/04 17:39:09.28 [20046] 2519+0: {R} NAME OVERFLOW 0/1
09/04 17:39:09.28 [20046] 2519+0: {R} NAME OVERFLOW 0/1
09/04 17:39:09.28 [20046] 2519+0: {R} NAME OVERFLOW 0/1
09/04 17:39:09.28 [20046] 2519+0: {R} NAME OVERFLOW 0/1
09/04 17:39:09.28 [20046] 2519+0: {R} NAME OVERFLOW 0/1
09/04 17:39:09.28 [20046] 2519+0: {R} NAME OVERFLOW 0/1
09/04 17:45:36.65 [20311] 2520+0: (0) accepted [53] -@[41.9.8.7]mail.ahostname.fr:33818 (0.003s)(1)
09/04 17:45:36.66 [20311] 2520+0: PATH: ftp://10.1.2.3:21!10.1.2.106:21!mail.ahostname.fr:33818!anonymous@mail.ahostname.fr;1409845536
09/04 17:45:36.67 [20311] 2520+0: FTP server ftp://10.1.2.3:21/
09/04 17:45:36.67 [20311] 2520+0: FTPHOPS: 1 [53/53 - -1/-1]
09/04 17:45:36.67 [20311] 2520+0: ConnectToServer: DFLT=ftp://10.1.2.3:21 REAL=://:0
09/04 17:45:36.68 [20311] 2520+0: ConnectToServer connected [15] {10.1.2.3:21 <- 10.1.2.100:33673} [0.018s]
09/04 17:45:36.68 [20311] 2520+0: willSTLS_SV[ftp]: ServerFlags=0 EE9F2500
09/04 17:45:36.70 [20311] 2520+0: --WARN FTP_STARTTLS_withSV no REAL_PROTO (ftp)
09/04 17:45:36.70 [20311] 2520+0: willSTLS_SV[ftp]: ServerFlags=0 EE9F2500
09/04 17:45:37.01 [20311] 2520+0/1/1: bind_insock(23,10.1.2.106,0) = 0, errno=0
09/04 17:45:37.01 [20311] 2520+0/1/1: ### IDENT CONNECT(mail.ahostname.fr:113) TIMEOUT(1000ms) (111)
09/04 17:45:37.01 [20311] 2520+0/1/1: ## FTP_delayReject.0 USER [admin][]
09/04 17:45:37.01 [20311] 2520+0/1/1: ####LS cannot open /var/lib/nobody/delegate/act/delay/09/41.9.8.7:mail.ahostname.fr
09/04 17:45:37.30 [20311] 2520+0/1/1: disconnected from the client
09/04 17:45:37.59 [20311] 2520+0/1/1: disconnected [53] -@[41.9.8.7]mail.ahostname.fr:33818 (0.935s)(0)
09/04 17:45:37.59 [20311] 2520+0/1/1: #Sig/CSC finish 73 6 P2 R0 E0 {0 r0 t0} 0/0/0

Thanks in advance,
Regards,
  Christophe

**Comment by sebres** [comment]
Since we support `datepattern` in filter/jail, it can be easy resolved with adding it in filter (or since v.0.10 into jail)
```INI
datepattern = %%m/%%d %%H:%%M:%%S
```
I don't see any advantage of providing this format to the default date patterns of fail2ban.
