### ISSUE TITLE
Ask to support uTorrent Server's time format

### ISSUE THREAD

**Issue by vipzen** [fail2ban/fail2ban#802]
```
# fail2ban-regex /opt/utorrent-server-alpha-v3_3/utserver.log "HTTP: IP <HOST>"

Running tests
=============

Use regex line : HTTP: IP <HOST>
Use log file   : /opt/utorrent-server-alpha-v3_3/utserver.log

Found a match for '[20140805 00:18:15] HTTP: IP 187.56.156.2: Bad username/password
' but no valid date/time found for '[20140805 00:18:15] HTTP: IP 187.56.156.2: Bad username/password
'. Please contact the author in order to get support for this format
Found a match for '[20140805 00:18:18] HTTP: IP 187.56.156.2: Bad username/password
' but no valid date/time found for '[20140805 00:18:18] HTTP: IP 187.56.156.2: Bad username/password
'. Please contact the author in order to get support for this format
```

**Comment by sebres** [comment]
You can do it through setting of custom dateformat to `\[%%Y%%m%%d %%H:%%M:%%S\]` in your filter or in jail.local (v.0.10 only)...

Using fail2ban-regex without dual escape of `%` char (needed only in config files):
```bash
fail2ban-regex -v -d "\[%Y%m%d %H:%M:%S\]" "[20140805 00:18:15] HTTP: IP 187.56.156.2: Bad username/password" "^ HTTP: IP <HOST>"
```

**Comment by fa1rid** [comment]
The fail2ban-regex command work perfectly however the filter doesn't work.
Fail2ban detects the settings correctly but not detecting any new failed logins.

Filter I used:

```
[Definition]
failregex = ^ HTTP: IP <HOST>
ignoreregex = 
[Init]
datepattern = \[%%Y%%m%%d %%H:%%M:%%S\]

```
The log file shows new failed logins like:
`[20171106 06:32:11] HTTP: IP 80.227.103.106: Bad username/password`

Fail2ban Log:
`2017-12-06 06:32:01,850 fail2ban.filter         [1394]: INFO    Added logfile = /opt/utorrent-server-alpha-v3_3/utserver.log
2017-12-06 06:32:01,853 fail2ban.filter         [1394]: INFO    Set maxRetry = 5
2017-12-06 06:32:01,855 fail2ban.filter         [1394]: INFO    Set findtime = 600
2017-12-06 06:32:01,856 fail2ban.actions        [1394]: INFO    Set banTime = 900
2017-12-06 06:32:01,858 fail2ban.filter         [1394]: INFO    Date pattern set to `'\\[%Y%m%d %H:%M:%S\\]'`: `\[YearMonthDay 24hour:Minute:Second\]`
2017-12-06 06:32:02,029 fail2ban.jail           [1394]: INFO    Jail 'utorrent' started`
