### ISSUE TITLE
fail2ban apache-auth.conf filter doesn't match AH01630: client denied by server configuration

### ISSUE THREAD

**Issue by nickweeds** [fail2ban/fail2ban#810]
The fail2ban apache-auth.conf filter doesn't match the following Apache log:

[Sat Sep 13 21:06:46.102123 2014] [authz_core:error] [pid 17990] [client 195.154.105.219:48142] AH01630: client denied by server configuration: /var/lib/wordpress/xmlrpc.php

The Apache log line is also attached.

This is because the apache-auth.conf filter currently expects AH01797 rather than AH01630.

OS: Ubuntu 14.04.1 LTS
Fail2ban version: 0.8.11-1 (*)
Apache version: 2.4.7-1ubuntu4.1
No customisations to the fail2ban.conf distributed with Ubuntu 14.04.
No configuration changes except for enabling apache2 in jail.conf.
No logs in fail2ban.log.

(*) This is the version currently distributed with Ubuntu 14.04.
It is outdated but the fail2ban git master apache-auth.conf doesn't recognise AH01630 either.

This has been observed by others - see <http://ubuntuforums.org/showthread.php?t=2222269>.

Pull request to follow.

**Comment by mgedmin** [comment]
Shouldn't this bug be closed now, since #810 was merged?

**Comment by sebres** [comment]
It should, Thx
