### ISSUE TITLE
Ugly output of nagios plugin if -D is set to empty string

### ISSUE THREAD

**Issue by Aikhjarto** [fail2ban/fail2ban#811]
I don't want the output of the nagios plugin to start with "CHECK FAIL2BAN ACTIVITY" but directly with "OK - ". When I set -D to an empty string, the output start with " - OK - " which is pretty ugly.

``` bash
# /usr/lib/nagios/plugins/check_fail2ban -w 10 -c 20 -p -D ""
 - OK - 1 detected jails with 1 current banned IP(s) | ssh-iptables.currentBannedIP=1 
```

It would be much more attractive if the preceeding "-" is omited if an empty string is supplied with -D

**Comment by leeclemens** [comment]
An overhaul of the `fail2ban-client status` command is planned, do you know where/how to update this nagios plugin to use a newer interface?

**Comment by sebres** [comment]
- `fail2ban-client status` is already available;
- also fail2ban database could be used, since fail2ban have own sqlite-database;
- otherwise grep out resp. filter `- OK -`  with something else
