### ISSUE TITLE
Hard coded path to syslog socket in server/server.py

### ISSUE THREAD

**Issue by chtheis** [fail2ban/fail2ban#814]
server/server.py uses the hard coded path "/dev/log" as the path to syslog's unix socket. But that path is OS dependent, for FreeBSD it is /var/run/log and for Max OS X it is /var/run/syslog.

I have no idea how to code that OS independent. For FreeBSD I patch the path during installation.

**Comment by leeclemens** [comment]
This is interesting.

http://linux.die.net/man/8/syslogd

# Files:
## /dev/log
### The Unix domain socket to from where local syslog messages are read.

**Comment by leeclemens** [comment]
https://docs.python.org/2/library/logging.handlers.html

[...] on Linux it’s usually ‘/dev/log’ but on OS/X it’s ‘/var/run/syslog’. You’ll need to check your platform and use the appropriate address (you may need to do this check at runtime if your application needs to run on several platforms).

**Comment by yarikoptic** [comment]
I guess we should just add a platform.system() output dependent path
resolution there... what is output of 

python -c 'import platform; print(platform.system()' on BSDs and OSX
(Darwin I would guess)?

**Comment by leeclemens** [comment]
Missing close paran:

`python -c 'import platform; print(platform.system())'`

**Comment by leeclemens** [comment]
I was thinking of creating a list of paths and testing them all - but the list may exist in both test cases and main class.  Then I thought of including it in the path configurations, but wasn't sure how to get them imported into server.py without too much mess.

**Comment by yarikoptic** [comment]
first I thought also to make it a variable (fail2ban.conf would be the appropriate place since that is where logging details are defined), but decided that it would be just easier to make programmically.  We just need to assign some SYSLOG_DEV_PATH at the beginning of fail2ban/server/server.py depending on platform.system() and be done/resuse in tests

**Comment by leeclemens** [comment]
I tried to make it configurable based upon platform (like the log paths), but they aren't read in the same way as fail2ban.conf seems to be (and config variables seem to be hardcoded).

**Comment by leeclemens** [comment]
It's working with PR https://github.com/fail2ban/fail2ban/pull/949 , I know that is not your second thought with SYSLOG_DEV_PATH in server.py. If that were the approach, where would the potential paths be set to test for a socket file? It would still need to be configured somewhere.

**Comment by leeclemens** [comment]
@chtheis would you be able to test https://github.com/leeclemens/fail2ban/tree/enh/configSyslogSocket and set your syslog socket's path in fail2ban.local (like [Definition] syslogsocket = <socket>)?

**Comment by chtheis** [comment]
Am 06.02.2015 um 05:58 schrieb Lee Clemens:
> @chtheis <https://github.com/chtheis> would you be able to test
> https://github.com/leeclemens/fail2ban/tree/enh/configSyslogSocket and
> set your syslog socket's path in fail2ban.local (like [Definition]
> syslogsocket = )?

I will try


Christoph

**Comment by chtheis** [comment]
Am 06.02.2015 um 05:58 schrieb Lee Clemens:
> @chtheis <https://github.com/chtheis> would you be able to test
> https://github.com/leeclemens/fail2ban/tree/enh/configSyslogSocket and
> set your syslog socket's path in fail2ban.local (like [Definition] syslogsocket = )?

I tried it according to your instructions and fail2ban does the logging 
to the syslog facility: I enabled to write all log entries to all.log 
and found the fail2ban entries there. And, so far, no suspicious errors.


Christoph

**Comment by leeclemens** [comment]
Updated, should be able to set syslogsocket to "auto" now and have it determined by some predefined paths based upon platform. It can be overridden in fail2ban.local as well.
