### ISSUE TITLE
Lighter notification email: sendmail-geoip-lines.conf

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#835]
After installing geoiplookup:
```python
Country:`/usr/bin/geoiplookup -f /usr/share/GeoIP/GeoIP.dat "<ip>" | cut -d":" -f2-`\n\n
```
It uses a local binary database (thus querying faster) to detect country of origin.
Please consider adding `sendmail-geoip-lines.conf`.

**Comment by leeclemens** [comment]
I like this idea (I've always disliked the verbosity of the whois-sendmail action). I envision a munin plugin from one central point checking all of the blocked IPs by AS/Country/Continent and graphing them...perhaps a change to fail2ban-client to provide that information - in addition to an action here (but similar)

**Comment by szepeviktor** [comment]
You can use it right away:
https://github.com/szepeviktor/debian-server-tools/blob/master/security/fail2ban-conf/action.d/sendmail-geoip-lines.local
Note the not listed dependencies!

**Comment by leeclemens** [comment]
I didn't realize you already created it, do you have a pull request for the new action?

**Comment by szepeviktor** [comment]
No, this is my homemade version with some differences. That is why it is named `action.local`.
Cleaned up a bit:
https://github.com/szepeviktor/debian-server-tools/blob/master/security/fail2ban-conf/action.d/sendmail-geoip-lines.local

**Comment by szepeviktor** [comment]
@yarikoptic Would you merge a fail2ban-ized version of this?

**Comment by szepeviktor** [comment]
Munin draws this:
![munin](http://i.snag.gy/AO8H8.jpg)

**Comment by yarikoptic** [comment]
Off mail notification with geoip information?
Sure, why not (after I verify that it works for me :-) )

**Comment by leeclemens** [comment]
@szepeviktor munin-node has the fail2ban plugin, I was thinking of also graphing GeoIP/WHOIS info (# bans by RIR/country/AS) - slightly off-topic but the GeoIP made me think of it.

I think the new action would be a good addition.

**Comment by buanzo** [comment]
+1.

does it work ok against HEAD?

**Comment by leeclemens** [comment]
Newest fail2ban-client status <JAIL> <FLAVOR> exposes similar information - and I have working fail2ban plugins working with the output.

**Comment by szepeviktor** [comment]
@yarikoptic Please click [here to see my questions](https://github.com/fail2ban/fail2ban/pull/939).
