### ISSUE TITLE
set <JAIL> actionban <ACT> <CMD> with multiline command

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#843]
It would be nice to be able give a multiline and very long ban command (like a geoip lookup email with log lines) as a `fail2ban-client` option on the command line.
My command is 695 bytes long. I'd like to set it without reloading the jail.

**Comment by sebres** [comment]
0.10 provides this possibility and additionally the `fail2ban-client reload` that does not restart, but only refresh used configuration (even without unbanning/rebanning), see #1557 or `fail2ban-client --help` for more info.

**Comment by szepeviktor** [comment]
Thanks.
