### ISSUE TITLE
now we might need to watch out for segfaults?

### ISSUE THREAD

**Issue by yarikoptic** [fail2ban/fail2ban#844]
just got one

```
Nov  3 12:53:41 head1 kernel: [10129.153280] fail2ban-server[6297]: segfault at 26 ip 00007f9bab0203e0 sp 00007f9baa3d98a8 error 4 in libsqlite3.so.0.8.6[7f9bab00f000+a6000]
```

which came from libsqlite3-0 (3.7.13-1+deb7u1)
coincided with high CPU and I/O load on that box.   I think that has lead to the crash of fail2ban (doing too many things at once but recall that on one of the boxes fail2ban was refusing to start due to stale socket file... may be here ;) )

**Comment by yarikoptic** [comment]
So I have just uploaded 0.9.1+git44-gd65c4f8 (which includes #839) Debian packages to Debian experimental and backport builds to NeuroDebian's "unannounced" -devel repo, so interested ones could try out to see if helps avoiding this segfaults

**Comment by Ionic** [comment]
Applied your patches manually to the sid version of fail2ban and haven't seen a crash ever since.

**Comment by sebres** [comment]
Great.
I suspected, it goes broken after some multiple erroneous prepared statements.

**Comment by SvenKo** [comment]
Hi all,

maybe my information helps you: I had the problem, that fail2ban creates my ssh rule twice. On service start i got the "segmentaion fault" error message but fail2ban started and after that i had twice rules but not with the ip's from the fail2ban.sqlite3 file. It was a very big file (more than 400 entries in two weeks)! I stopped the fail2ban service, restartet iptables, deleted the file and started fail2ban again. Now everything is ok. There is definitely a bug with sqlite3. I use CentOS 7.1.1503 with fail2ban 0.9.1-4.el7.

**Comment by sebres** [comment]
No, 400 entries is at all not a big sqlite file. 
My greatest f2b.sqlite3 database now contains 35300 rows in table "bans" and 105800 rows in table "bips" (not in standard fail2ban, my branch 'ban-time-incr'). 
And I mean to have seen over 500K rows (Well, my purge works always :)
No one problem, since we have fixed several issues with database (lambdas and broken utf-8 chars), that all meanwhile should be in master.

But I don't know about content of 0.9.1-4.el7 in centos.

**Comment by sebres** [comment]
I believe it was fixed in ban ticket lambdas (inside actions.py and json-wrapper from database.py). 
We should be careful, so it should be always "exception" safe inside such constructs (never throw unhandled exceptions from such callbacks).
