### ISSUE TITLE
Enabling all jails?

### ISSUE THREAD

**Issue by ItsAdventureTime** [fail2ban/fail2ban#853]
Hi,

Well, I was just wondering how can I enable all jails? Like to prevent any future attacks (in case). My server has been compromised twice so I don't want that to happen again. Whenever I try to enable all the jails, nothing happens. I cannot start fail2ban because some log file is not found. I tried properly enabling some jails properly, via the jail.local file. For example, I have an Apache server installed. I was trying to enable all Apache related jails. Well, nothing happens. It still says the log file is not found yet I have Apache installed. How can I then prevent those attacks if I cannot start the software in the first place? Is there like a force launching of the software and ignoring the log files if they are not found or found, just continue launching it?

Thanks.

**Comment by leeclemens** [comment]
Not trying to be a naysayer, but if a new service's log appeared upon installation/start - what would prompt fail2ban to see it?  Perhaps inotify IN_CREATE to add the relevant jail?

**Comment by sebres** [comment]
further in #55
