### ISSUE TITLE
Client Server Mode?

### ISSUE THREAD

**Issue by MarvAmBass** [fail2ban/fail2ban#863]
Hi there,

is there something like a Client Server Mode?

Like if you're running fail2ban together with your e.g. webapp on one host, and trigger the firewall rules on the server. Like a Dockercontainer, and a Dockerhost.

I know this could be done as a simple hack with a perl script and some custom filter/action but Docker is such a important thing, that a lot of people could be helped if this was supported directly by fail2ban.

For Docker:
If you run Fail2Ban inside a non privileged Docker Container, you have the problem, that the container doesn't give you the permission to use iptables. You could run it in privileged mode, but you also want this feature to make your containers more secure.

Thanks

Marvin

**Comment by leeclemens** [comment]
I think this architecture is better described in https://github.com/fail2ban/fail2ban/issues/881, duplicate - so closing. Feel free to reopen if you disagree.
