### ISSUE TITLE
ssh new rule to be added

### ISSUE THREAD

**Issue by octavsly** [fail2ban/fail2ban#864]
The following attack is not detected by fail2ban version 0.9.1 (gentoo)

 Nov 24 23:46:39 weurope sshd[32686]: SSH: Server;Ltype: Version;Remote: 121.199.22.83-1780;Protocol: 2.0;Client: libssh2_1.4.3
Nov 24 23:46:40 weurope sshd[32686]: SSH: Server;Ltype: Kex;Remote: 121.199.22.83-1780;Enc: aes128-ctr;MAC: hmac-sha1;Comp: none [preauth]
Nov 24 23:46:41 weurope sshd[32686]: SSH: Server;Ltype: Authname;Remote: 121.199.22.83-1780;Name: root [preauth]
Nov 24 23:46:43 weurope sshd[32686]: fatal: Read from socket failed: Connection reset by peer [preauth]

To detect it I did add in sshd.conf the following:
^.*Remote: <HOST>-.*\n.*fatal: Read from socket failed: Connection reset by peer \[preauth\]$
This needs to be changed to a proper/better regexp.

**Comment by marcosfrm** [comment]
sshd[XXX]: error: Received disconnect from X.X.X.X: 14: No supported authentication methods available [preauth]

My server only allows pubkey auth. This error happens when one knows a valid user name but does not have the key.

I think it should be added.

**Comment by sebres** [comment]
@octavsly, @marcosfrm tests of #1209 are welcome

**Comment by octavsly** [comment]
I have tested the patch with the code present at the beginning of the ticket, and it works. 
It does match the HOST. 
Thank you.

**Comment by stevenengland** [comment]
Hi there, using the current 0.10 build and running
`fail2ban-regex -e UTF-8 /var/log/auth.log /etc/fail2ban/filter.d/sshd-aggressive.conf`
to catch all lines with filter regex from sshd.conf 
`^%(__prefix_line_sl)sReceived disconnect from <HOST>%(__on_port_opt)s: 14: No supported authentication methods available%(__suff)s$`
does not recognize lines like
`Jan 22 12:27:55 ubuntu sshd[3625]: error: Received disconnect from 192.168.2.92 port 1684:14: No supported authentication methods available [preauth]`
The (for testing-purposes) simplified version
`^.*<HOST>.*14: No supported authentication methods available.*$`
detects it. Can you please have a look?

**Comment by sebres** [comment]
Fixed, Thx...
