### ISSUE TITLE
Fail2Ban 0.9.0 on CentOS 7 error starting service

### ISSUE THREAD

**Issue by zzserg** [fail2ban/fail2ban#865]
Hi, All!
Please help me solve strange problem...
Environment: CentOS Linux 7 (Core) x86_64, Fail2Ban v0.9.0 from repo EPEL 7, OwnCloud 7.0.3 from OwnCloud CentOS 7 repo.
I succesfull setup all environment and manually start fail2ban via command:
[code]
fail2ban-client start
2014-11-26 13:14:05,884 fail2ban.server.server[26908]: INFO    Starting Fail2ban v0.9.0
2014-11-26 13:14:05,885 fail2ban.server.server[26908]: INFO    Starting in daemon mode
[/code]
All working fine!

Than i suceccfully enabling fail2ban.service via:
[code]
systemctl enable fail2ban.service
ln -s '/usr/lib/systemd/system/fail2ban.service' '/etc/systemd/system/multi-user.target.wants/fail2ban.service'
[/code]

But when i try starting fail2ban.service i got error:
[code]
systemctl start fail2ban.service
Job for fail2ban.service failed. See 'systemctl status fail2ban.service' and 'journalctl -xn' for details.[/code]
Result
[code]
systemctl status fail2ban.service
fail2ban.service - Fail2ban Service
   Loaded: loaded (/usr/lib/systemd/system/fail2ban.service; enabled)
   Active: activating (start) since Ср 2014-11-26 13:16:25 MSK; 2s ago
 Main PID: 26844 (code=exited, status=255);         : 27043 (fail2ban-client)
   CGroup: /system.slice/fail2ban.service
           └─27043 /usr/bin/python /usr/bin/fail2ban-client -x start
[/code]

[code]
journalctl -xn
ноя 26 13:29:21 cloud.acconcept.ru systemd[1]: Starting Fail2ban Service...
-- Subject: Unit fail2ban.service has begun with start-up
-- Defined-By: systemd
## -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

-- Unit fail2ban.service has begun starting up.
ноя 26 13:29:23 cloud.acconcept.ru fail2ban-client[27566]: ERROR  No file(s) foun
d for glob /var/www/html/owncloud/data/owncloud.log
ноя 26 13:29:23 cloud.acconcept.ru fail2ban-client[27566]: ERROR  Failed during c
onfiguration: Have not found any log file for owncloud jail
ноя 26 13:29:23 cloud.acconcept.ru systemd[1]: fail2ban.service: control process
exited, code=exited status=255
ноя 26 13:29:23 cloud.acconcept.ru systemd[1]: Failed to start Fail2ban Service.
-- Subject: Unit fail2ban.service has failed
-- Defined-By: systemd
## -- Unit fail2ban.service has failed.

-- The result is failed.
ноя 26 13:29:23 cloud.acconcept.ru systemd[1]: Unit fail2ban.service entered fail
ed state.
ноя 26 13:29:23 cloud.acconcept.ru systemd[1]: fail2ban.service holdoff time over
, scheduling restart.
ноя 26 13:29:23 cloud.acconcept.ru systemd[1]: Stopping Fail2ban Service...
-- Subject: Unit fail2ban.service has begun shutting down
-- Defined-By: systemd
## -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

-- Unit fail2ban.service has begun shutting down.
ноя 26 13:29:23 cloud.acconcept.ru systemd[1]: Starting Fail2ban Service...
-- Subject: Unit fail2ban.service has begun with start-up
-- Defined-By: systemd
## -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

-- Unit fail2ban.service has begun starting up.
[/code]

Content of /usr/lib/systemd/system/fail2ban.service
[code]
[Unit]
Description=Fail2ban Service
After=syslog.target network.target firewalld.service

[Service]
Type=forking
ExecStart=/usr/bin/fail2ban-client -x start
ExecStop=/usr/bin/fail2ban-client stop
ExecReload=/usr/bin/fail2ban-client reload
PIDFile=/var/run/fail2ban/fail2ban.pid
Restart=always

[Install]
WantedBy=multi-user.target
[/code]

Disabling SeLinux solve problem. It's not correct.

**Comment by AlexisWilke** [comment]
As a side note (I did not read everything here yet, I wrote #1593 ), my current solution is pretty simple: I create an empty log file when it is missing. I have many scripts / packages where I can do that, so it is easy enough for me. However, I think that is a problem that should be resolved in fail2ban instead.

In my case, `mail.warn` was missing:

    touch /var/log/mail.warn
    chmod 640 /var/log/mail.warn
    chown syslog.adm /var/log/mail.warn

That way, once a warning is generated, the jail functions as expected either way.

**Comment by AlexisWilke** [comment]
> Following scenario: host was reboot, no monitoring arranged on the host, now what would be better?

> * admin does not control journal-log and does not see the error, BUT the host is left to the attackers completely;

I personally think that this is not acceptable. The maximum possible protection should be in place on a startup. If it fails in one jail but I have 20 turned on, I want the other 19 to be in place.

The only reason for this behavior would be a for an administrator to test whether his new code is correct. For that, you could add a feature simile to `apache2ctl configtest` if not already available. That way one can see whether fail2ban will be able to load its configuration. Although it will also need to test whether the files it wants to open for reading can indeed be opened since that part is really important to the startup process.

> * admin does not control file2ban.log and does not see the error in ONE jail, BUT rest of the host is still protected;

This is the solution I personally like best. While adding new rules, you should be a responsible administrator and not forget to check whether your new rules actually function (i.e. test by adding fake logs and see that the block happens.)

**Comment by sebres** [comment]
I said nothing else... 
It must and will be made at some point, but we've currently a lot of another tasks with highest prio as this.

**Comment by sebres** [comment]
I'll close now, because the issue of subject is fixed now. 
Ultimate solution (auto-enabling of jail if log-file appears later) should be provided with #1379
