### ISSUE TITLE
Recidive seems not working...

### ISSUE THREAD

**Issue by 7starsone** [fail2ban/fail2ban#872]
hi,
the same IP banned 22 times in the same day on sshd...
but no recidive emails/ban...

shouldn't it ban for a week after the 5th ban or I have not got it right ?

```
[recidive]
enabled = true
logpath  = /var/log/fail2ban.log
port     = all
protocol = all
bantime  = 604800  ; 1 week
findtime = 86400   ; 1 day
maxretry = 5
```

p.s.:
in /var/log i have two fail2ban.log now
fail2ban.log
fail2ban.log-20141130.gz

can be this the issue?
maybe i should reduce the findtime = 86400 to eg. half 43200?

this is my /etc/logrotate.d/fail2ban on CentOS 7 now...

```
/var/log/fail2ban.log {
    rotate 7
    missingok
    compress
    postrotate
      /usr/bin/fail2ban-client flushlogs  1>/dev/null || true
    endscript
}
```

OR better if I change logpath = /var/log/fail2ban.log TO logpath = /var/log/fail2ban\* ?
i will try...
CentOS 7 64bit | fail2ban-0.9-9.el7.noarch
thanks

**Comment by unsalkorkmaz** [comment]
I am still getting this error:
```
2015-02-14 01:55:06,501 fail2ban.jail           [7245]: INFO    Jail 'recidive' started
2015-02-14 01:55:07,676 fail2ban.action         [7245]: ERROR   ipset create fail2ban-recidive hash:ip timeout 2590000
firewall-cmd --direct --add-rule ipv4 filter INPUT 0 -p all -m multiport --dports all -m set --match-set fail2ban-recidive src -j REJECT --reject-with icmp-port-unreachable -- stdout: "\x1b[91mError: COMMAND_FAILED: '/sbin/iptables -t filter -I INPUT_direct 11 -p all -m multiport --dports all -m set --match-set fail2ban-recidive src -j REJECT --reject-with icmp-port-unreachable' failed: iptables v1.4.21: multiport needs `-p tcp', `-p udp', `-p udplite', `-p sctp' or `-p dccp'\nTry `iptables -h' or 'iptables --help' for more information.\x1b[00m\n"
2015-02-14 01:55:07,677 fail2ban.action         [7245]: ERROR   ipset create fail2ban-recidive hash:ip timeout 2590000
firewall-cmd --direct --add-rule ipv4 filter INPUT 0 -p all -m multiport --dports all -m set --match-set fail2ban-recidive src -j REJECT --reject-with icmp-port-unreachable -- stderr: ''
2015-02-14 01:55:07,677 fail2ban.action         [7245]: ERROR   ipset create fail2ban-recidive hash:ip timeout 2590000
firewall-cmd --direct --add-rule ipv4 filter INPUT 0 -p all -m multiport --dports all -m set --match-set fail2ban-recidive src -j REJECT --reject-with icmp-port-unreachable -- returned 13
2015-02-14 01:55:07,678 fail2ban.actions        [7245]: ERROR   Failed to start jail 'recidive' action 'firewallcmd-ipset': Error starting action
```

fail2ban version:
```
fail2ban.noarch                        0.9.1-2.el7                         @epel
```

**Comment by stewartadam** [comment]
I have the same issue as well, it's because firewallcmd-ipset expects a specific protocol and port(s), but the recidive jail has protocol=all and port=all set so the command doesn't work.

I changed my jail.d/recidive.conf to:
```
[recidive]
enabled = true
backend = auto
logpath = /var/log/fail2ban.log
protocol = tcp
port = ssh,smtp,26,465,submission,imap2,imap3,imaps,pop3,pop3s,http,https,ftp,ftps,mysql
```
It works now, although this is not ideal since every new service I configure I must manually blacklist in this config file.

**Comment by leeclemens** [comment]
@unsalkorkmaz and @stewartadam, I would suggest creating a new issue, as this was closed several months ago and doesn't seem related to your issues. Please also include your jail configs, including at least the banaction if it is inherited.

**Comment by mrc0mmand** [comment]
@stewartadam, @unsalkorkmaz  You can easily fix this issue by setting the variable `protocol` to `tcp`. With this little edit it will work even with port ranges, such as default `0:65535`. If you want to ban connections for `udp` and other protocols as well, you'd have to most likely edit `firewallcmd-ipset` action.

Also, it would be probably reasonable to open a new issue for this problem (as @leeclemens suggested), as it would be great to have an option to control all protocols at once.

**Comment by unsalkorkmaz** [comment]
@mrc0mmand It seems problem is different then i thought first. Details: https://github.com/fail2ban/fail2ban/issues/959

**Comment by mrc0mmand** [comment]
@unsalkorkmaz Ah, sorry, I missed that one.
