### ISSUE TITLE
[FR] Recidive on pf (FreeBSD)

### ISSUE THREAD

**Issue by oparoz** [fail2ban/fail2ban#884]
From the comments

> Also, this jail has its drawbacks, namely in that it works only with iptables, or if you use a different blocking mechanism for this jail versus others (e.g. hostsdeny for most jails, and shorewall for this one).

Would be good to have something like Recidive on platforms which don't use iptables.
Wouldn't it be possible for pf to have an extra table for recidivists per example?

**Comment by sebres** [comment]
Jail `recidive` (as well as other allports jails) should work well good with pf-action, at least in newer versions (>= 0.10), using parameter `actiontype` specified as `allports`.

Example config:
```INI
# jail.local:

[DEFAULT]
banaction = pf
banaction_allports = pf[actiontype=<allports>]

[my-jail]
banaction = pf[actiontype=<allports>]
enabled = true
filter = ...
```
