### ISSUE TITLE
Emails from fail2ban 0.9.1 are timestamped with UTC time instead of local time

### ISSUE THREAD

**Issue by jimjoh** [fail2ban/fail2ban#911]
I first reported this here:
https://bugzilla.redhat.com/show_bug.cgi?id=1180850
but was redirected here.  Unsure if this is considered a bug, but this behavior surprised me.

Description of problem:
Whenever fail2ban sends an email it has a UTC time stamp instead of a local time zone time stamp (like most other local logs use).

Version-Release number of selected component (if applicable):
I'm using the fail2ban-0.9.1-2.el7 RPM on CentOS 7

How reproducible:
Every time

Steps to Reproduce:
1. Enable a jail (like sshd)
2. Use one of the email actions (like "%(action_mwl)s")
3. Create a ban that generates an email (fail2ban-client set sshd banip 1.2.3.4)

Actual results:
Get an email that has a UTC time stamp

Expected results:
Get an email that has a local time stamp

Additional info:
Since I"m only using the "%(action_mwl)s" action I only need to edit one file to change fail2ban to use local time.
vi /etc/fail2ban/action.d/sendmail-whois-lines.conf
-Prepend a # to the start of the actionban date line.
-For example find this section:
<pre>
actionban = printf %%b "Subject: [Fail2Ban] <name>: banned <ip> from `uname -n`
            Date: `LC_TIME=C date -u +"%%a, %%d %%h %%Y %%T +0000"`
</pre>

-And insert a # at the start of the second line so it looks like this:
<pre>
actionban = printf %%b "Subject: [Fail2Ban] <name>: banned <ip> from `uname -n`
#            Date: `LC_TIME=C date -u +"%%a, %%d %%h %%Y %%T +0000"``
</pre>
-This simple fix seems to work well for me, but since I don't understand what they're trying to do with "LC_TIME=C date" here YMMV.

I'm not sure if this is a bug or a feature.  I found a similar Debian bug report from 10 years ago, so at least I'm not the only one who doesn't like UTC dated emails.  See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=336449 for the other bug report.

**Comment by yarikoptic** [comment]
git log -p config/action.d/sendmail-whois.conf

could have helped a lot to identify "why?".  There are why's here:

commit 9fa54cf23309780f3563838c9d95a24e4b9a4c38

```
Author: Tom Hendrikx <tom@whyscream.net>
Date:   Fri Nov 18 22:08:41 2011 +0100

    Add Date: header for sendmail*.conf actions
    
    According to rfc2822, Date: headers are not optional.
    Added these to all sendmail action templates, format specification
    should conform to rfc and be portable across multiple platforms.

diff --git a/config/action.d/sendmail-whois.conf b/config/action.d/sendmail-whois.conf
index d029005..363c339 100644
--- a/config/action.d/sendmail-whois.conf
+++ b/config/action.d/sendmail-whois.conf
@@ -12,6 +12,7 @@
 # Values:  CMD
 #
 actionstart = printf %%b "Subject: [Fail2Ban] <name>: started
+              Date: `date -u +"%%a, %%d %%h %%Y %%T +0000"`
...
```

and then

commit 945ad3d9e65348a78318ca026dfcb5b31dbe736e

```
Author: Daniel Black <grooverdan@users.sourceforge.net>
Date:   Mon Apr 29 14:10:23 2013 +1000

    BF: ensure dates in email are in the C locale. Thanks iGeorgeX

diff --git a/config/action.d/sendmail-whois.conf b/config/action.d/sendmail-whois.conf
index f63fd36..6b7b938 100644
--- a/config/action.d/sendmail-whois.conf
+++ b/config/action.d/sendmail-whois.conf
@@ -12,7 +12,7 @@
 # Values:  CMD
 #
 actionstart = printf %%b "Subject: [Fail2Ban] <name>: started
-              Date: `date -u +"%%a, %%d %%h %%Y %%T +0000"`
+              Date: `LC_TIME=C date -u +"%%a, %%d %%h %%Y %%T +0000"`

```

so your "solution" is suboptimal ;)  I guess it should be smth like

$> LC_TIME=C date -u +"%a, %d %h %Y %X %z"

but for me it doesn't output with local offset even though I am in easter time zone:

Tue, 13 Jan 2015 02:47:33 +0000

so how?

**Comment by jimjoh** [comment]
Thanks for the detailed reply.  I'm not a programmer and could not have figured that out on my own.  I now understand why a date was added, however I still don't understand why the command is formatted like this to get UTC time:
`$ LC_TIME=C date -u +"%a, %d %h %Y %T +0000"`

Instead of simply using local time like this:
`$ date  +"%a, %d %h %Y %T %z"`

The 'date -u' in the original command sets it to UTC time.  For example to compare the commands:
`$ LC_TIME=C date -u +"%a, %d %h %Y %T +0000"`
`Tue, 13 Jan 2015 03:53:55 +0000`

`$ LC_TIME=C date  +"%a, %d %h %Y %T %z"`
`Mon, 12 Jan 2015 22:53:55 -0500`

Ultimately this is a pretty trivial issue, so I understand if it's closed as a non-bug now.  I understand why there's a date field and I know how to easily work around it. Thanks for the info.

**Comment by yarikoptic** [comment]
d'oh -- right -- ```-u```... actually I do not see any note of a conscious decision to use univeral time, nor I see recommendation for that in the rfc2822... so -- would you be interested to contribute?
go change all instances in the actions of using -u to the ones with "%T %z" , provide Changelog entry for such a change, add yourself to THANKS and send a PR with those changes? 
It is a valid report after all so I do not see why to close it without resolution  ;-)  unless someone from @fail2ban/developers decides that reporting with UTC timestamp is preferable in general

**Comment by jimjoh** [comment]
Unfortunately I don't know how to do any of the steps you listed to submit a changelog (and I don't have the time to learn how now).  If someone else wanted to submit this change I'd be happy to let them have the credit.  :)  Thanks again for your help, but I've reached the end of my technical skills.

**Comment by yarikoptic** [comment]
ok -- then eventually we will do.. cheers
