### ISSUE TITLE
Geo IP

### ISSUE THREAD

**Issue by martzuk** [fail2ban/fail2ban#92]
I followed the tutorial here: http://www.fail2ban.org/wiki/index.php/HOWTO_use_geoiplookup

I can't seem to get it to work, I modified the correct line (I took into account what looks like slightly newer syntax)

However when I have this line in the config rather than the original it stops fail2ban from actually banning anybody, also meaning that it doesn't record a ban line in the logfile.

This is the original line:
```python
logSys.warn("[%s] Ban %s" % (self.jail.getName(), str(aInfo["ip"])))
```
This is the new line: 
```python
logSys.warn("[%s] Ban %s %s" % (self.jail.getName(), str(aInfo["ip"], commands.getstatusoutput('geoiplookup ' + aInfo["ip"])[1][23:])))
```
I also added commands to the import line so it is: import time, logging, commands

Am I doing something wrong or would this functionality have broken after an update? The little python script at the top of the wiki page seems to work ok.

**Comment by leeclemens** [comment]
Got ERR_NAME_NOT_RESOLVED from that link, feel free to reopen or start a conversation on the mailing list if you have anything to add.
