### ISSUE TITLE
Some actions (e.g. send-mail) should not be ran upon banning on restart

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#921]
```
Lines containing IP:106.187.49.59 in /var/log/apache2/*error.log
(no lines here)
```

And there are no lines because logs are rotated.

``` apache
2015-01-21 15:14:27,823 fail2ban.actions        [29757]: NOTICE  [apache-combined] Ban 106.187.49.59
2015-01-23 01:08:56,059 fail2ban.actions        [2941]: NOTICE  [apache-combined] Ban 106.187.49.59
```

**Comment by szepeviktor** [comment]
There are 38 IPs blocked in this jail but I only get few emails. I do not understand.

**Comment by szepeviktor** [comment]
BTW. Persistent banning list is a very nice feature.

**Comment by yarikoptic** [comment]
so what is the problem really??? that email is empty because logs got rotated or what??? clarify plz

**Comment by szepeviktor** [comment]
1. Restart fai2ban server after a few weeks of operation
2. I get emails of bans. I do not understand why. Is it because of the persistent banning?
3. There are bans whos IP is not in the log anymore because log rotation.

Is it OK to get emails (`banaction`) on server restarts?

**Comment by szepeviktor** [comment]
What if I have 1000 bans and I restart the server?

**Comment by yarikoptic** [comment]
> I get emails of bans. I do not understand why. Is it because of the persistent banning?

yeap.  because how are those IPs get banned?  actionban command is ran, and you have "send email" there.  I guess ideally we should be able to identify which actions should be run always or only on non-restarts... but atm we don't have that feature. So I would edit title here to signal that this is what needed

**Comment by szepeviktor** [comment]
OK.
Thank you.

**Comment by sebres** [comment]
BTW: in #716 object `Ticket` has a property `restored`, can be used to check a ban was restored after restart (to filter/ignore some action).
