### ISSUE TITLE
Trouble with using pam_unix for auth failures

### ISSUE THREAD

**Issue by opoplawski** [fail2ban/fail2ban#928]
When using sssd (or ldap, or ..) for authentication you will see messages like:
````
Jan 27 08:53:23 mail auth: pam_unix(dovecot:auth): authentication failure; logname= uid=0 euid=0 tty=dovecot ruser=USER rhost=111.111.111.111  user=USER
Jan 27 08:53:23 mail auth: pam_sss(dovecot:auth): authentication success; logname= uid=0 euid=0 tty=dovecot ruser=USER rhost=111.111.111.111 user=USER
````
So instead of pam_unix in regexs, we should have something like %(pam_auth)s so you can set the pam authentication mechanism.  Perhaps fail2ban could parse /etc/nsswitch.conf to automatically determine what auth mechanism was in use:
````passwd:     files sss````

Current usage:
````
/etc/fail2ban/filter.d/dovecot.conf:failregex = ^%(__prefix_line)s(pam_unix(\(dovecot:auth\))?:)?\s+authentication failure; logname=\S* uid=\S* euid=\S* tty=dovecot ruser=\S* rhost=<HOST>(\s+user=\S*)?\s*$
/etc/fail2ban/filter.d/vsftpd.conf:__pam_re=\(?pam_unix(?:\(\S+\))?\)?:?
/etc/fail2ban/filter.d/pam-generic.conf:__pam_re=\(?pam_unix(?:\(\S+\))?\)?:?
/etc/fail2ban/filter.d/pam-generic.conf:# _daemon = \S*\(?pam_unix\)?
/etc/fail2ban/filter.d/wuftpd.conf:__pam_re=\(?pam_unix(?:\(wu-ftpd:auth\))?\)?:?
````
At least the vsftpd and wuftpd filters have a __pam_re that can be overridden.

**Comment by sebres** [comment]
agree

**Comment by opoplawski** [comment]
This sets up the variable.  No idea how to make this auto-generated.

**Comment by sebres** [comment]
I think it should not necessarily be "auto-generated" - just set default to `pam_unix`, and if someone wants anything else, it can be set simple to other value directly in jail.local.

**Comment by opoplawski** [comment]
There are other issues with pam_sss unfortunately - see https://www.centos.org/forums/viewtopic.php?t=1718 for an example.  The upshot is that there is no pam_sss authentication failed messages for unknown users.

**Comment by opoplawski** [comment]
Perhaps the real solution for unknown users is in pull #932 - by setting auth_verbose=yes in dovecot you can get unknown user errors and trigger off of those.  But you still need to be able to change the pam_* search.
