### ISSUE TITLE
Trailing whitespace

### ISSUE THREAD

**Issue by leeclemens** [fail2ban/fail2ban#943]
I'd like to clean up the trailing whitespace the is all over the place...but it would be a lot of lines updated (and hence blame cleared since github doesn't seem to support ignoring whitespace updates).

**Comment by yarikoptic** [comment]
and we have quite a bit of outstanding WiP which might result in undue merge conflicts... since in majority of the cases those are not impairing functionality -- let them be and slowly possibly prune them up while modifying/improving related parts of code

**Comment by leeclemens** [comment]
The tortoise approach :)  Does that mean only if a given line is changed, or if a file is being changed extra whitespace could be refactored as well?

**Comment by yarikoptic** [comment]
On Mon, 02 Feb 2015, Lee Clemens wrote:

>    The tortoise approach :) Does that mean only if a given line is changed,
>    or if a file is being changed extra whitespace could be refactored as
>    well?

line (and may be neighboring ones ;) )

once again -- I am afraid that large changes would cause undue conflicts

**Comment by leeclemens** [comment]
understood, and thanks for your clarification (as always) :)
