### ISSUE TITLE
sendmail-whois-ipjailmatches stops bans from working and causes 100% cpu usage when daemon is stopped

### ISSUE THREAD

**Issue by oksijun** [fail2ban/fail2ban#947]
I'm attempting to set up fail2ban 0.9.1 with the systemd backend.

In **jail.d/customisation.local**, I have :

```
*banaction  = iptables-multiport-log
action_mwi  = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
          %(mta)s-whois-ipjailmatches[name=%(__name__)s, dest="%(destemail)s", chain="%(chain)s"]
action      = %(action_mwi)s*
```

With this setup, bans aren't enforced (fail2ban finds IP addresses and logs them, but doesn't ban them) and when I stop the daemon fail2ban cpu usage hits 100%, and hangs at _"INFO    Stopping all jails"_

If I set _action_ to _%(action_mwl)s_, everything works fine, but the received emails don't contain any log lines (/var/log/proftpd.log doesn't exist because I'm using journald).

I tried smtp.py which works in my use case but doesn't handle whois lookups, so I'd like to help resolving this issue. Let me know if I can provide any further information to ease debugging.

**Comment by yarikoptic** [comment]
Let me just summarize, please let me if correctly:  if systemd backend used and action doesn't really involve banning (i.e. preventing possible next log msgs to appear) then fail2ban gets into 100% cpu usage... ?
Could you increase loglevel to debug and share the log leading/after "Stopping all jails"?

**Comment by oksijun** [comment]
Not exactly. If systemd backend is used, and sendmail-whois-ipjailmatches is used, then there are 2 problems:
1. bans don't work (iptables rules are not inserted)
2. fail2ban hits 100% cpu usage when stopped (systemctl stop fail2ban)

Here are the changes I have made to the default configuration (fail2ban 0.9.1 on arch linux):

**# cat jail.d/customisation.local**

    [DEFAULT]
    backend         = systemd
    action_mwi      = %(banaction)s[name=%(__name__)s, bantime="%(bantime)s", port="%(port)s", protocol="%(protocol)s", chain="%(chain)s"]
                      %(mta)s-whois-ipjailmatches[name=%(__name__)s, dest="%(destemail)s", chain="%(chain)s"]
    action          = %(action_mwi)s
    [proftpd]
    enabled         = true

**# diff filter.d/proftpd.conf filter.d/proftpd.local**

    22a23,26
    > [Init]
    > 
    > journalmatch = _SYSTEMD_UNIT=proftpd.service
    > 

Here are the contents of fail2ban.log with loglevel set to DEBUG : 

    2015-02-19 12:08:42,648 fail2ban.server         [13735]: INFO    Stopping all jails
    2015-02-19 12:08:42,654 fail2ban.server         [13735]: DEBUG   Stopping jail proftpd
    2015-02-19 12:08:43,586 fail2ban.filtersystemd  [13735]: DEBUG   proftpd filter terminated
    2015-02-19 12:10:12,796 fail2ban.server         [13735]: DEBUG   Caught signal 15. Exiting
    2015-02-19 12:10:12,802 fail2ban.asyncserver    [13735]: DEBUG   Socket shutdown
    2015-02-19 12:10:12,808 fail2ban.server         [13735]: INFO    Stopping all jails
    2015-02-19 12:10:12,814 fail2ban.server         [13735]: DEBUG   Stopping jail proftpd

Note that CPU hits 100% (fail2ban-server process) just after "Stopping jail proftpd". Eventually systemd kills the process ("Caught signal 15. Exiting") :

    Feb 19 12:10:12 myhost systemd[1]: fail2ban.service stopping timed out. Terminating.
    Feb 19 12:10:12 myhost fail2ban-client[13745]: WARNING Caught signal 15. Exiting
    Feb 19 12:10:12 myhost systemd[1]: fail2ban.service: control process exited, code=exited status=255
    Feb 19 12:11:43 myhost systemd[1]: fail2ban.service stop-sigterm timed out. Killing.
    Feb 19 12:11:43 myhost systemd[1]: fail2ban.service: main process exited, code=killed, status=9/KILL
    Feb 19 12:11:43 myhost systemd[1]: Unit fail2ban.service entered failed state.
    Feb 19 12:11:43 myhost systemd[1]: fail2ban.service failed.


Hope that helps, let me know if I can provide any more information.

**Comment by sebres** [comment]
Not reproducible on current versions, please let me know if issue still persists with newest versions.
