### ISSUE TITLE
Need to be able to run fail2ban-server under valgrind

### ISSUE THREAD

**Issue by opoplawski** [fail2ban/fail2ban#951]
I'm seeing crashes in fail2ban-server, apparently in libsystemd-journal.so (see https://bugzilla.redhat.com/show_bug.cgi?id=1188894).  I'd like to be able to run fail2ban-server under valgrind, but I can't figure out how.

fail2ban-client -f start still forks off the failb2ban-server process

fail2ban-server -f doesn't load any configs.

work around appears to be to run valgrind fail2ban-server -f and then run fail2ban-client reload.  But this should be easier.

**Comment by leeclemens** [comment]
`fail2ban-client -f` still calls os.execvp(), which replaces the current process - so isn't exactly running in the 'foreground' as expected.

ref: http://sourceforge.net/p/fail2ban/mailman/message/33356460/

**Comment by leeclemens** [comment]
@kwirk It looks like you committed some lines to use -b and -f in fail2ban-client, thoughts on this newly discovered issue? (genuine request for input; call to `os.execvp()` has been there since '06)

**Comment by sebres** [comment]
0.10 can run in foreground without fork etc. 
Also the [fail2ban.service](https://github.com/fail2ban/fail2ban/blob/0.10/files/fail2ban.service#L12) already updated there to start in this mode (directly as server), using configurator thread to read config (as client part directly within itself).
