### ISSUE TITLE
Ban C Class networks / C-Class-recidive

### ISSUE THREAD

**Issue by szepeviktor** [fail2ban/fail2ban#953]
```bash
# select first 2 octets of IP-s
# sort by number of occurrences
# TOP10
sqlite3 fail2ban.sqlite3 'select ip from bans;'|cut -d'.' -f1-3 \
    |sort -n|uniq -c|sort -n \
    |tail
```

Is it a good idea to ban the whole C Class after `N` bans in it?

**Comment by szepeviktor** [comment]
My output is

```
      9 46.174.67
     10 85.195.91
     11 46.118.29
     11 92.63.88
     13 212.129.63
     15 31.204.130
     18 94.23.33
     23 188.40.141
     23 46.105.113
     26 193.104.41
```
I would set `N` to 20.

**Comment by szepeviktor** [comment]
Could it be implemented as 1 sqlite query?

**Comment by leeclemens** [comment]
@szepeviktor Members of a class C network may not be from the same country - so I think this is not a good idea in practice. What correlation is there between one IP being banned and every other IP in the same class C network (other than being in the same class C network, obviously)?

**Comment by szepeviktor** [comment]
[Here](http://en.wikipedia.org/wiki/Classful_network) I read that a class C network has 256 IP-s, so `1.2.3.*`. Have you seen a C class that spreads over two countries?

**Comment by szepeviktor** [comment]
BTW. You may keep this limit at 100 to be sure it is a botnet.

**Comment by leeclemens** [comment]
Yes, that is what a class C address is - if classful network was still used (see below).

RIR's are responsible for multiple countries - and can (and do) allocate networks to different countries which are both subsets of the same /24 network (e.g. a /25 to an ISP in Germany and the other /25 to an ISP in Ukraine).

There is no basis for what you are attempting to do, so I don't think it matters what limit or threshold - as associating all members of the /24 is flawed logic from the start.

I was using "class C network" as a general term for a /24 network.

From the wikipedia article you cited:
"Classful networking was replaced by Classless Inter-Domain Routing (CIDR), starting in 1993 with the specification of RFC 1518 and RFC 1519...."

**Comment by szepeviktor** [comment]
Sorry!http://bgp.he.net/ip/193.251.160.151#_whois -> [GP](http://en.wikipedia.org/wiki/.gp)
http://bgp.he.net/ip/193.251.160.155#_whois -> FR

**Comment by szepeviktor** [comment]
Because fail2ban sends me more than 50 emails I still do:

```apache
## disable auth from attackers
<FilesMatch "(wp-login|xmlrpc)\.php$">
<Limit POST>
    Order Allow,Deny
    Allow from all
    # BT Italia S.p.A.
    Deny from 78.4.0.0/16
    Deny from 78.5.0.0/16
    Deny from 78.6.0.0/16
    Deny from 78.7.0.0/16
    Deny from 78.7.115.0/24
    # Fastweb S.p.A.
    Deny from 89.96.0.0/15
    Deny from 93.48.0.0/13
    Deny from 93.56.0.0/14
    Deny from 93.60.0.0/15
</Limit>
</FilesMatch>
```

**Comment by szepeviktor** [comment]
Do you have something in your mind?

**Comment by leeclemens** [comment]
@szepeviktor Given what I said and the two IPs you found that are so close, but allocated to different countries, do you still believe it is a good idea to block entire /24's based on one or some number of individual IP's being banned?

**Comment by szepeviktor** [comment]
No. It is bad idea.

**Comment by szepeviktor** [comment]
Could you help reduce the number of emails? Maybe based on whois `netname:`?

**Comment by leeclemens** [comment]
I think the email quantity topic is covered in Issue https://github.com/fail2ban/fail2ban/issues/832  Can this one be closed?

**Comment by szepeviktor** [comment]
I am sorry. I can do only debugging in python. It would be nice to have less emails.
