### ISSUE TITLE
Two new filter:  mailflood

### ISSUE THREAD

**Issue by MattMalone** [fail2ban/fail2ban#957]
Fail2ban is incredible.  I authored new filters.  I do not know how to do a pull request in github, and, my regular expressions are not great, but the two I wrote (in addition to the default sshd) have helped a lot.  The first one I did is an APACHE combo one that seems to be just a integration of the different apache ones that ship with fail2ban.  Maybe that is an idea... if one runs apache, why have a lot of separate jails?  The stock regexs are more complex and probably better, so I will leave out my combo filter.  

For sendmail, I have not seen a filter that ships with fail2ban that deals with mail flooding.  I was getting so many mail contacts that sendmail just responding to them was throwing "Connection rate limit exceeded" into the logs like 4000 times a minute.  It was slowing my system and virtually turning off my network.   It seemed like a DOS attack.  So, once sendmail logs that mail is coming too fast from any one source 6 times, they are temporarily jailed.   Someone better at regex authoring could probably improve the patterns, but, they have made my network work again so I am happy.  

Thanks again for the fail2ban framework that made it so easy to get up to speed and scratch this itch.

Log lines like this are the itch:
```
Feb 11 15:15:24 trunk sm-mta[8522]: ruleset=check_relay,  arg1=static-200-105-197-98.acelerate.net, arg2=200.105.197.98, relay=static-200-105-197-98.acelerate.net [200.105.197.98], reject=421 4.3.2 Connection rate limit exceeded.
```
In jail.conf add:
```
[mailflood]

enabled  = true
port     = smtp
filter   = mailflood
logpath  = /var/log/mail.log
maxretry = 2
bantime  = 3600

Filter mailflood.conf (I cannot put code in this commend without it looking funny so just the regex):
[INCLUDES]
before = common.conf
[Definition]
failregex = ^.\* arg1=[<HOST>], .\* Connection rate limit exceeded._$
            ^._ [<HOST>], .\* Connection rate limit exceeded._$
            ^._ [<HOST>] (may be forged), .\* Connection rate limit exceeded.*$

ignoreregex = 
```

**Comment by yarikoptic** [comment]
On Fri, 13 Feb 2015, MattMalone wrote:

> ...  I do not know how to do a pull request in github

it is really not a rocket science at all...
https://help.github.com/articles/using-pull-requests/#before-you-begin


> # Feb 11 15:15:24 trunk sm-mta[8522]: ruleset=check_relay, 
> #    arg1=static-200-105-197-98.acelerate.net, arg2=200.105.197.98, 
> #    relay=static-200-105-197-98.acelerate.net [200.105.197.98], 
> #    reject=421 4.3.2 Connection rate limit exceeded.

> # and other like them because they were flooding so fast they were threatening my network.  

> # Values:  TEXT

> failregex = ^.* arg1=\[<HOST>\], .* Connection rate limit exceeded.*$
>             ^.* \[<HOST>\], .* Connection rate limit exceeded.*$
>             ^.* \[<HOST>\] \(may be forged\), .* Connection rate limit exceeded.*$

they better be anchored upfront (so no ^.* which is pointless) and
more specific until "Connection rate limit..."  otherwise injection can
happen causing you DoS.

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by MattMalone** [comment]
No it is not rocket science or I would be able to understand it.  Really.  I do not think people who have learned Github-lingo realize how completely meaningless it appears to everyone else even after reading it a few times.  The example in the instructions does not make it clear how to propose adding a file to the filter.d directory without first forking the entire project.  Forking the entire project over the addition of a file seemed wrong, so, I did not do it.  Following your comments, I am so glad I did not vandalize this great project by forking it with my good intentions.    

Great input on how to improve the regex, I think, I did not really understand your suggested improvement.

**Comment by yarikoptic** [comment]
On Fri, 13 Feb 2015, MattMalone wrote:
>    project. Forking the entire project over the addition of a file seemed
>    wrong, so, I did not do it. 

;-) "forking" on github is perfectly fine -- don't be scared of that

> Following your comments, I am so glad I did
>    not vandalize this great project by forking it with my good intentions.

;)  once again -- "forking" would be desirable 

>    Great input on how to improve the regex, I think, I did not really
>    understand your suggested improvement.

see https://github.com/fail2ban/fail2ban/blob/HEAD/FILTERS#L223 which
might provide more descriptive answer

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by MattMalone** [comment]
OK then.  I used the following useful utility but to make it match the behaviour of fail2ban and fail2ban-regex, I had to:
 - substitute (\S+) for <HOST> 
 - I figured out I had to paste the log line without the date / time.
Once I got that then:

https://regex101.com/#python

Was very useful.  Now I have the following 2 rules:

failregex = ^\s*(\S+)\s+sm-mta\s*\[(\d+)\]\s*:\s+ruleset=check_relay,\s+arg1=\[<HOST>\],\s+arg2=(\S+),\s+relay=(\S+),\s+reject=421\s+(\S+)\s+Connection rate limit exceeded.\s*$
                 ^\s*(\S+)\s+sm-mta\s*\[(\d+)\]\s*:\s+ruleset=check_relay,\s+arg1=(\S+),\s+arg2=(\S+),\s+relay=(\S+)\s+\[<HOST>\](,?)\s+(\(may be forged\),\s+)?reject=421\s+(\S+)\s+Connection rate limit exceeded.\s*$

I have tested these two rules against all 7606 hits in my /var/log/mail.log using fail2ban-regex and it detects them all, 650 by the first one, 6956 by the second.   

Fail2ban-regex is less interactive.  I found puzzling out the regex much easier with the interactive tool above.   Regex also scrolls past my entire screen buffer when it gets hits.   An option to surpress the printing of individual hits or, an implementation of "last host repeated N times" would be useful.

**Comment by leeclemens** [comment]
@MattMalone You can increase your screen buffer or use a pager, such as `less`
