### ISSUE TITLE
if filter does not have journalmatch definition, its not working

### ISSUE THREAD

**Issue by unsalkorkmaz** [fail2ban/fail2ban#959]
From fail2ban log:
```
2015-02-14 04:45:18,860 fail2ban.filtersystemd  [14602]: NOTICE  Jail started without 'journalmatch' set. Jail regexs will be checked against all journal entries, which is not advised for performance reasons.
2015-02-14 04:45:18,861 fail2ban.jail           [14602]: INFO    Jail 'apache-auth' started
2015-02-14 04:45:18,864 fail2ban.filtersystemd  [14602]: NOTICE  Jail started without 'journalmatch' set. Jail regexs will be checked against all journal entries, which is not advised for performance reasons.
2015-02-14 04:45:18,866 fail2ban.jail           [14602]: INFO    Jail 'apache-badbots' started
2015-02-14 04:45:18,869 fail2ban.filtersystemd  [14602]: NOTICE  Jail started without 'journalmatch' set. Jail regexs will be checked against all journal entries, which is not advised for performance reasons.
2015-02-14 04:45:18,872 fail2ban.jail           [14602]: INFO    Jail 'apache-noscript' started
2015-02-14 04:45:18,877 fail2ban.filtersystemd  [14602]: NOTICE  Jail started without 'journalmatch' set. Jail regexs will be checked against all journal entries, which is not advised for performance reasons.
2015-02-14 04:45:18,882 fail2ban.jail           [14602]: INFO    Jail 'apache-nohome' started
2015-02-14 04:45:18,886 fail2ban.filtersystemd  [14602]: NOTICE  Jail started without 'journalmatch' set. Jail regexs will be checked against all journal entries, which is not advised for performance reasons.
```

I created paths-overrides.local for httpd logs:
```
[DEFAULT]
apache_error_log = /var/log/virtualmin/*error_log
apache_access_log = /var/log/virtualmin/*access_log
```

Those jails are not working. sshd working normally but it has journalmatch definition. Is that my custom problem or others have similar problem too? It seems if filter does not have journalmatch definition, its not working.

Operating system:	CentOS Linux 7.0.1406
Kernel and CPU:	Linux 3.10.0-123.20.1.el7.x86_64 on x86_64
Server Version: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 PHP/5.6.5 mod_perl/2.0.9dev Perl/v5.16.3
Server MPM: prefork
fail2ban.noarch                        0.9.1-2.el7                         @epel

**Comment by opoplawski** [comment]
Part of the problem is that in the epel fail2ban-systemd package I've set:

backend = systemd
in:
 /etc/fail2ban/jail.d/00-systemd.conf

The problem is that there are many daemons where the needed logs will not make it into the journal, like the httpd logs above.  For those jails they must always process the log files.  It may be a mistake to classify the journal as a "backend".

**Comment by unsalkorkmaz** [comment]
what is recommended backend for those jails in centos 7?

**Comment by opoplawski** [comment]
From man jail.conf:
       backend
              backend to be used to detect changes in the logpath. It defaults to "auto" which will try "pyinotify", "gamin", "systemd" before  "polling".  Any  of
              these can be specified. "pyinotify" is only valid on Linux systems with the "pyinotify" Python libraries. "gamin" requires the "gamin" libraries.

The problem is that systemd/journal really isn't a way to "detect changes in the logpath". It's an alternate source for logs.  I don't know if it is possible to run two different backends at the moment, but we'll need to be able to read from both the systemd journal and from regular log files.

**Comment by unsalkorkmaz** [comment]
So basically fail2ban's apache related jails are not working for centos 7 atm right? Do you have any suggestion for solution? (at least temporary)

Thanks for your time btw :bow:

**Comment by opoplawski** [comment]
You can remove the fail2ban-systemd package (and the fail2ban meta package) and use the default "auto" backend.

**Comment by unsalkorkmaz** [comment]
It seems we cant remove fail2ban-systemd:
```
Loaded plugins: fastestmirror, replace
Resolving Dependencies
--> Running transaction check
---> Package fail2ban-systemd.noarch 0:0.9.1-2.el7 will be erased
--> Processing Dependency: fail2ban-systemd = 0.9.1-2.el7 for package: fail2ban-0.9.1-2.el7.noarch
--> Running transaction check
---> Package fail2ban.noarch 0:0.9.1-2.el7 will be erased
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package                 Arch          Version               Repository    Size
================================================================================
Removing:
 fail2ban-systemd        noarch        0.9.1-2.el7           @epel        272
Removing for dependencies:
 fail2ban                noarch        0.9.1-2.el7           @epel        0.0

Transaction Summary
================================================================================
Remove  1 Package (+1 Dependent package)
```

**Comment by opoplawski** [comment]
As I said - you are perfectly free to remove the fail2ban meta-package.  It has no files (notice size = 0.0, and check with rpm -ql fail2ban), it only has dependencies to bring in the default fail2ban configuration.

**Comment by unsalkorkmaz** [comment]
Wow.. 
![cpu-week](https://cloud.githubusercontent.com/assets/207720/6241606/da344414-b728-11e4-8b3c-fdddb2e8747c.png)

You see iowait for last 2 days? thats what happened when i removed fail2ban-systemd and fail2ban used another backend. When i use iotop command, there was [jbd2/md2-8] with %50-80 IO percentage. I just stopped fail2ban and it returned normal.

**Comment by cultavix** [comment]
I've started to use Gamin as my backend, I've simply changed the file which fail2ban-systemd uses. Also make sure you install gamin. @unsalkorkmaz which nagios check are you using to get that beautiful graph?

**Comment by unsalkorkmaz** [comment]
I am not sure if i wanted gamin while my system using systemd. Those graphs from munin.

**Comment by kowach** [comment]
I have set backend to "polling" and journalmatch to empty in jail.local

    [spam-filter]
    enabled  = true
    port     = http
    logpath  = /var/log/spam_log
    backend  = polling
    journalmatch =
    action  = iptables-multiport

and it works, but ignores port "http". 

    iptables -n -L
    Chain INPUT (policy ACCEPT)
    target     prot opt source               destination
    f2b-default  tcp  --  0.0.0.0/0            0.0.0.0/0            state NEW multiport dports 22
     ...
    Chain f2b-default (1 references)
    target     prot opt source               destination
    REJECT     all  --  xx.xx.xx.xx         0.0.0.0/0            reject-with icmp-port-unreachable
    REJECT     all  --  yy.yy.yy.yy        0.0.0.0/0            reject-with icmp-port-unreachable


Why it's not blocking port 80 and why is chain name f2b-default and not f2b-spam-filter?

**Comment by yarikoptic** [comment]
added a comment by the backend definition4
