### ISSUE TITLE
Cook up 0.9.2 release

### ISSUE THREAD

**Issue by yarikoptic** [fail2ban/fail2ban#963]
This is just a discussion issue for @fail2ban/developers and @fail2ban/contributors .  We should really push out next release of fail2ban asap since number of fixes and improvements is quite large now.  But before we push it out I think we should still fix up few minor issues, which I have now kept/added to 0.9.2 milestone:
https://github.com/fail2ban/fail2ban/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.9.2
So whoever gets a moment -- please help out with those in favor of other issues (better concentrate on fixes than additions/extensions)
Any suggestions/recommendations on what to add/postpone?

**Comment by ache** [comment]
I think PR #952 cold be added safely and fix stale entries bug.

**Comment by yarikoptic** [comment]
thanks @ache -- I intended to but missed it, now added (just want ideally someone else to look at it as well )

**Comment by ache** [comment]
Thanx! Please look at #964 I just fill too. I am not sure here, but it looks like.

**Comment by leeclemens** [comment]
Cooked
