### ISSUE TITLE
It seems default dbpurgeage have too small interval

### ISSUE THREAD

**Issue by ache** [fail2ban/fail2ban#964]
Just compare
```
# Values: [ SECONDS ] Default: 86400 (24hours)
dbpurgeage = 86400
```
and
```
[recidive]
logpath = /var/log/fail2ban.log
banaction = iptables-allports
bantime = 604800 ; 1 week
```
Perhaps I misunderstand something, but dbpurgeage needs to be increased, like 1 week + 10 minutes (room for cleanup). We lost those entries from db otherwise.

**Comment by yarikoptic** [comment]
sounds logical, but did i read it right that you have observed described effect?
Since recidive jail is not enabled by default I would probably just add a comment near recidive jail hinting that dbpurgeage must be increased then... or do you think dragging db entries for so long has generic value?

**Comment by ache** [comment]
Yes, I enable "recidive" and observe missing entries, but with current release there are too many reasons for this effect, including mentioned one, fail2ban crashes, etc. it is hard to tell for sure what cause it.

I think adding comment near "recidive" will be enough, if you plan to keep it non-default, but I see no harm to enable it by default instead, along with dbpurgeage increasing:)

**Comment by szepeviktor** [comment]
I second. A big warning in `recivive.conf` or rather a 1 week `dbpurgeage`,

**Comment by szepeviktor** [comment]
Now I've notced I already have `dbpurgeage = 604800` as a default `fail2ban.local`,

**Comment by ache** [comment]
>I already have dbpurgeage = 604800
It needs to be slightly bigger than 1 week because you got concurrency (or deleting errors) otherwise between deleting those entries by f2b engine and purging them from db in the same time.

**Comment by szepeviktor** [comment]
:smile: I do not really care whether it's 1 week or 6 ½ days.

**Comment by leeclemens** [comment]
Since either option (`bantime` or `dbpurgeage`) can be modified, I'd suggest a comment/warning near both - since they are so closely related (I'm not sure of other jails that use the db).

**Comment by sebres** [comment]
BTW: at the moment it is irrelevant how large is `dbpurgeage`, because `purge` never takes place.
Fixed in #716 within observer module.

**Comment by szepeviktor** [comment]
Really??

**Comment by sebres** [comment]
Yes.

**Comment by szepeviktor** [comment]
:disappointed:
