### ISSUE TITLE
Wrong value for 'loglevel' in 'Definition'. 

### ISSUE THREAD

**Issue by tryitout2015** [fail2ban/fail2ban#967]
Fail2ban 0.9.1 on Ubuntu 14.04, manually updated from the "apt-get" installed 0.8.11 

When running <code> service fail2ban restart </code> , two warning messages appear:

<code>
WARNING Wrong value for 'loglevel' in 'Definition'. Using default one: '1'
</code>
<code>
WARNING 'logpath' not defined in 'INCLUDES'. Using default one: '/var/log/messages'
</code>

For the first warning msg, I've tried <code>fail2ban-client set loglevel INFO</code>, returning with an error:
<code>ERROR  NOK: ("invalid literal for int() with base 10: 'INFO'",)</code>
<code>invalid literal for int() with base 10: 'INFO'</code>

**Comment by tryitout2015** [comment]
Unsure if this is correct

<code></code>
<code></code>

**Comment by tryitout2015** [comment]
Solving the first warrning message with <code>service fail2ban stop</code> or <code>fail2ban-client stop</code> , then restart the service

**Comment by leeclemens** [comment]
iirc, loglevel changed from int to str declaration of `logging`'s level ("INFO"). There may be a descrepency between the configs and the `fail2ban-client set loglevel` command.

Does `fail2ban-client set loglevel 3` work?

Ideally, you should have loglevel defined in your configs and you won't need to worry about it.

**Comment by tryitout2015** [comment]
Thx, Lee. The loglevel appears to be locked in 1 (the default) and cannot be changed.

A temporary solution is to run <code>fail2ban-client stop</code> and then <code>fail2ban-client start</code>.  It functions well, as long as I keep my hands away from the server and only tweak the client,

The ultimate solution is directly installing 0.9.1 on Ubuntu 14.04. The 0.8.11 deb package + manual update to 0.9.1 will somehow lead to the weird warning messages.

**Comment by leeclemens** [comment]
I don't think it is 'locked in' as you say, but falling back to the default - based on the warning message. I'm glad you seem to have this sorted out now though. Can this be closed?

**Comment by tryitout2015** [comment]
Yes, 'falling back to the default' is a much more accurate description.
And this can be closed. Cheers.
