### ISSUE TITLE
firewallcmd-ipset action fails for recidive jail with protocol=all

### ISSUE THREAD

**Issue by stewartadam** [fail2ban/fail2ban#968]
Continuing the discussion from this issue: https://github.com/fail2ban/fail2ban/issues/872#issuecomment-74737819

The firewallcmd-ipset action fails for the recidive jail because it has protocol=all and port=all, while the commands executed by the action require that the protocol be set to either tcp or udp.

I would imagine that a way to fix this would be to simply introduce firewallcmd-ipset-both that executes a command blocking all ports on TCP and UDP independently.

As well, a temporary workaround is documented in the comment linked above.

**Comment by leeclemens** [comment]
Have you tried using `firewallcmd-allports` ?  That seems like it is intended to work the same as the iptables actions which block all protocols and all ports.

**Comment by pdf** [comment]
recidive should just use *-allports by default.

**Comment by gul916** [comment]
Hi,
I have the same problem with fail2ban 0.9.3-1 under fedora 22.
Here is my jail.local :

[recidive]
enabled  = true
port      = all
protocol = all
logpath  = /var/log/fail2ban.log
bantime  = 86400  ; 1 day
findtime = 86400  ; 1 day
maxretry = 3
banaction = firewallcmd-allports

I have tried also with iptables-allports, but it is not working. I have tested regex with fail2ban-regex /var/log/secure /etc/fail2ban/filter.d/sshd.conf and it finds 30 corresponding lines.

Any help would be appreciated
Thanks

**Comment by opoplawski** [comment]
@gul916 - that should be "action = firewallcmd-allports" - check your resulting config with "fail2ban-client get recidive action".

**Comment by sebres** [comment]
I don't see any advantage with new action like `firewallcmd-ipset-both`, because you can easy configure it without new action:
```INI
[recidive]
action   = %(banaction)s[name=%(__name__)s-tcp, port="%(port)s", protocol="tcp", chain="%(chain)s", actname=%(banaction)s-tcp]
           %(banaction)s[name=%(__name__)s-udp, port="%(port)s", protocol="udp", chain="%(chain)s", actname=%(banaction)s-udp]
```
Thus close this.

Note that if you will enable this also for connection-less protocol like UDP, I don't think it would be good idea, see warning in https://github.com/fail2ban/fail2ban/blob/0.10/config/jail.conf#L668
