### ISSUE TITLE
Touch icons request flood in apache by android phone

### ISSUE THREAD

**Issue by unsalkorkmaz** [fail2ban/fail2ban#970]
Hi,
I opened a question in serverfault but they locked question for some reason:
http://serverfault.com/questions/668167/touch-icons-request-flood-in-apache-by-android-phone

Probably because of a server/device conflict, innocent people are getting ban.
```
client denied by server configuration: /home/example/public_html/apple-touch-icon-precomposed.png
```
I dont want people get ban because of an icon request and i am bad at regex. Can you help me find a solution for this? maybe an ignoreregex for this.

**Comment by leeclemens** [comment]
This seems like an Apache configuration issue, not fail2ban. Can you access that file from your browser? Can you provide the access log for the request? At a minimum we'd need more info on your fail2ban setup to assist here.

**Comment by unsalkorkmaz** [comment]
Thing is.. I disable logging img/css/js etc requests for server performance. I pasted all logs for this problem in that serverfault question. Someone entered site with 1 page request but got ban because of his/her device called lots of apple-touch-icon-precomposed.png file. More importantly there is no apple-touch-icon-precomposed.png file declaration in html code. Basically there is no code for it but device is calling it repeatedly for some reason.

**Comment by leeclemens** [comment]
It seems like fail2ban is working as configured. The client is making a request which results in, I presume, a 403 - and fail2ban is banning them. I also presume you have indexes off and there is no default page for the directory the image is in?

I'm curious why you specified gamin and not relied on auto or specified pyinotify as the backend?

**Comment by unsalkorkmaz** [comment]
Fail2ban working as intended. You can check https://github.com/fail2ban/fail2ban/issues/959 for details of gamin backend. But problem is apache creates client denies problem because of device/apache conflict probably. I am just trying to find a way for apache-auth filter ignore those if its for apple-touch-icon-precomposed.png file.

**Comment by leeclemens** [comment]
As you said, fail2ban is working as intended - so I'd like to close this.  You can copy the filter and remove the regex if you really want to...I'm not really sure what you are looking to accomplish.

You may use an ignore regex for that particular file name in a filter.local file...it still seems too specific to your Apache and server config and what you're doing though, so it's up to you.

**Comment by unsalkorkmaz** [comment]
After all problems of apache, I am planning to use nginx reverse proxy in front of apache. This problem will probably gone with that.
