### ISSUE TITLE
Allow for multiple logtargets

### ISSUE THREAD

**Issue by kbabioch** [fail2ban/fail2ban#971]
According to the documentation it is not possible to define multiple logtargets:

       logtarget
              log target: filename, SYSLOG, STDERR or STDOUT. Default: STDERR . Only a single log target can be specified.  If you change logtarget
              from the default value and you are using logrotate -- also adjust or disable rotation in the corresponding configuration  file  (e.g.
              /etc/logrotate.d/fail2ban on Debian systems).

At least in my setup I'm using the journal, but would also like to have a classic text-based log file. Right now I have to use rsyslogd, using the journal as input and using appropriate selectors to output fail2ban's output to a particular file. It would be nice if this could be done with fail2ban itself.

**Comment by leeclemens** [comment]
What is your current configuration related to fail2ban logging?

**Comment by johnpatcher** [comment]
I'm logging to the journal using the SYSLOG target:

    logtarget = SYSLOG

rsyslog is then picking up the logs from the journal using the imjournal module. Then I'm selecting for fail2ban messages within rsyslogd and writing it to a dedicated file:

    :programname, startswith, "fail2ban" /var/log/fail2ban.log
    & ~

As already said it works, but personally I would prefer a more direct approach within fail2ban itself.

**Comment by leeclemens** [comment]
fail2ban can log to a file itself, by specifying the `filename`. Is that what you are looking to accomplish? If not, I think I'm missing so something, can you elaborate on what you are trying to achieve (e.g. what two targets/why two targets)?

**Comment by buanzo** [comment]
I would assume he is going for centralized logging via syslog, and
flexibility to filter which messages actually go to another logfile.

**Comment by leeclemens** [comment]
@buanzo I'm trying not to assume. Building syslog functionality into fail2ban doesn't seem useful when fail2ban can already log to syslog.

**Comment by johnpatcher** [comment]
Am 23.02.2015 um 23:21 schrieb Lee Clemens:
> fail2ban can log to a file itself, by specifying the `filename`.

I know, but I can't use `filename` and `SYSLOG` at the same time, which
is exactly the feature I would like to request. I'm using the `SYSLOG`
facility to log the systemd's journal, but would also like to have a
classical log file lying around, which can then be parsed by other log
monitoring software.

**Comment by johnpatcher** [comment]
Am 24.02.2015 um 00:15 schrieb Lee Clemens:
> @buanzo I'm trying not to assume. Building syslog functionality into
> fail2ban doesn't seem useful when fail2ban can already log to
> syslog.

While it can log to `SYSLOG`, it can not log to `SYSLOG` and `filename`
in parallel.

**Comment by leeclemens** [comment]
I believe syslog already provides the functionality you are looking for, and fail2ban already provides the ability to log to syslog - please correct me if I'm wrong. That said, I just don't see the benefit of re-inventing the wheel.

Python;s `logging` can use multiple targets, so a PR would be one thing. I just don't see this as a worthy use-case seeing as syslog was already designed for this.
