### ISSUE TITLE
unbanip - not remove IP from SQLite DB

### ISSUE THREAD

**Issue by coolex** [fail2ban/fail2ban#972]
I think it's error, maybe I'm wrong.

1) Fail2ban ban IP bacause it was message in log about DDoS attack - for 
1 week - it's ok
2) when I wanted to unban IP address I was use command:
fail2ban-client set <JAIL> unbanip <IP>
I works, IP was deleted from IPset.
But in SQLite DB in table bans is still line from log about DDoS attack.

But problem is when i reload firewall:
fail2ban-client -x stop
firewall stop
firewall start
(still OK)
fail2ban-client -x start

And unbaned IP shows up again in IPset.

Any idea what can I do?

I try last git version and it's still same.

Regards,
Kuba

**Comment by sebres** [comment]
I think, this IP can be baned again (log file will be scaned after f2b start and some failures for this ip found).
Please post an output of `grep "1.2.3.4" /var/log/fail2ban.log` (best with debug on).

**Comment by kernelt** [comment]
Hi all. I confirm that I have the same bug and I use f2b without firewalld.

[root@srv config]# uname -r
3.19.3-200.fc21.x86_64
[root@srv config]# fail2ban-client -V
Fail2Ban v0.9.1

[root@srv filter.d]# fail2ban-client set http-badscript unbanip IP1
IP1
[root@srv filter.d]# systemctl restart fail2ban
[root@srv filter.d]# egrep IP1 /var/log/fail2ban.log
2015-04-30 08:03:27,289 fail2ban.actions        [3067]: NOTICE  [http-badscript] Ban IP1

[root@srv config]# cat jail.local
...
bantime = 2592000
findtime  = 3600
maxretry = 3
backend = systemd
...
[http-badscript]
maxretry = 2
enabled = true
port = http,https
backend = pyinotify
logpath = /path/to/logs/access.log
...

After, I have cleared all logs and restart f2b - the IP1 wasn't deleted from f2b DB and it was banned again.

**Comment by heximcz** [comment]
Problem still not resolved. I was test f2b v.0.9.2 with same result. IP is not deleted from db.

my test:

fail2ban-client set conntrack-ddos banip 10.10.10.11
fail2ban-client set conntrack-ddos unbanip 10.10.10.11
(in this step is ipset clear, but ip is still in db)

/etc/init.d/fail2ban restart
(in this step is IP back in ipset)

root@server:/var/lib/fail2ban# sqlite3 ./fail2ban.sqlite3 
SQLite version 3.7.13 2012-06-11 02:05:22
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> select * from bans;
conntrack-ddos|10.10.10.11|1435852772|{"matches": [], "failures": 1}
sqlite> 


jail:
[conntrack-ddos]
enabled  = true
protocol = all
banaction = iptables-ipset-proto4-allports
filter   = conntrack-ddos
logpath  = /var/log/messages
maxretry = 1
findtime = 60
bantime  = 604800

**Comment by kernelt** [comment]
Anyone? Our servers can't work properly.

**Comment by sebres** [comment]
wait for travis, will merge hereafter (was simply merged from #716, because it works there)

**Comment by sebres** [comment]
merged.
