### ISSUE TITLE
Handling around iptables should be breakdown safe

### ISSUE THREAD

**Issue by sebres** [fail2ban/fail2ban#980]
Just as reminder for me.

To prevent such errors like `iptables: Too many links.` by stop/start after invalid banning / breakdown of f2b:
- (start) create chain only if it not already exists;
- (stop) removing of the chain should take place, also if some rules of it still available (or some rules should be removed if no references available anymore);
- (reload/restart) ensure that changing of parameters in configs (like port by multiport action) does not affect execution of commands like `actionstop` (to replace old rules with old port);
  at the moment because as identifier all parameters are used, it would be unable to remove old iptables chain from INPUT, so leave still one rule with the same name (but old port);
- (any) check a possibility to implement race-safe handling - although we use `-w` option, it is still open to a time-of-check-to-time-of-use race condition (TOCTTOU-RC): 
  * f2b check the rule (and for example if not available should create the chain/rule);
  * some foreign service removes it after check;
  * some further f2b handler (like create) could be not invoked (due to successful check).

  typical scenario showing TOCTTOU-RC (although during each single operation it is locked (`-w`), the whole script may fail if both running simultaneously, there are no common lock/unlock due to missing locking-capabilities in shell):
```bash
# process 1:
iptables -w -C INPUT -p tcp -j f2b-jail &>/dev/null || {
  iptables -w -N f2b-jail || :
  iptables -w -A f2b-jail -j DROP || :
  iptables -w -I INPUT -p tcp -j f2b-jail
}
# process 2:
iptables -w -C INPUT -p tcp -j f2b-jail &>/dev/null && {
  iptables -w -D INPUT -p tcp -j f2b-jail
  iptables -w -X f2b-jail
}
```

**Comment by sebres** [comment]
Possible the same or similar issue occurred in branch "ban-time-incr":
```
2015-02-09 10:42:56,285 fail2ban.action         [7401]: ERROR   iptables -n -L INPUT | grep -q 'f2b-ssh[ \t]' -- returned 1
2015-02-09 10:42:56,285 fail2ban.CommandAction  [7401]: ERROR   Invariant check failed. Trying to restore a sane environment
2015-02-09 10:42:56,389 fail2ban.action         [7401]: ERROR   iptables -D INPUT -p tcp --dport ssh -j f2b-ssh
iptables -F f2b-ssh
iptables -X f2b-ssh -- stderr: "iptables v1.4.14: Couldn't load target `f2b-ssh':No such file or directory\n\nTry `iptables -h' or 'iptables --help' for more information.\n
2015-02-09 10:42:56,390 fail2ban.action         [7401]: ERROR   iptables -D INPUT -p tcp --dport ssh -j f2b-ssh
iptables -F f2b-ssh
iptables -X f2b-ssh -- returned 1
2015-02-09 10:42:56,390 fail2ban.actions        [7401]: ERROR   Failed to execute unban jail 'ssh-iredmail' action 'iptables' info '{'matches': u'Feb  9 10:21:16 mail sshd[
```

**Comment by szepeviktor** [comment]
I expect Fail2ban not to silently fail.

**Comment by sebres** [comment]
> I expect Fail2ban not to silently fail.

Well the issue is about something orthogonal (affecting common action stabilities or else safety by invariant check and repair)...
What do you mean as a "not silently" exactly? Mail to admin in some certain error case?

**Comment by szepeviktor** [comment]
Let's write an erro to our log when `iptables -C` fails.

**Comment by sebres** [comment]
Sure it will be (or either it is already the case if an error occurs and a chain is missing).
The problem is neither `iptables -C ...` nor `iptables -L | grep -q ...` (used at the moment in `actioncheck` as a replacement for `iptables -C ...`) protecting you against subsequent errors (e. g. after effects, like chain reference is removed from INPUT or ipset gets deleted or doesn't created for some reason), see the issue description.
Also note that newest version (1.0, see https://github.com/fail2ban/fail2ban/issues/488#issuecomment-574676768) doing the invariant check only in error case (not like 0.9-0.11 before every ban), so certain preventive adjustment of several actions is required to do fully breakdown safe check and repair.

**Comment by sebres** [comment]
Done for master (1.0) now.
