### ISSUE TITLE
ipset in fail to ban time out increasing

### ISSUE THREAD

**Issue by ediazrod** [fail2ban/fail2ban#981]
Hi to alll I am using Debian 7 updated and one modification of ipset6 for shorewall.

At the beginning all runs ok but after of 12h the time out (I don't know why) increases a lot..

As example:

Name: f2b-EXIM
Type: hash:ip
Header: family inet hashsize 2048 maxelem 65536 timeout 86400
Size in memory: 106292
References: 2
Members:
105.210.83.33 timeout 4259454
95.22.184.22 timeout 895913
201.213.55.231 timeout 1031542
118.71.99.141 timeout 54835
190.22.152.31 timeout 63068

This is my action shorewall file.
# Option:  actionban
# Notes.:  command executed when banning an IP. Take care that the
# command is executed with Fail2Ban user rights.
# Tags:    See jail.conf(5) man page
# Values:  CMD
# 

actionban = ipset add f2b-<name> <ip> timeout <bantime> -exist
# Option:  actionunban

Why the time out is increased???

**Comment by sebres** [comment]
fail2ban version?
