### ISSUE TITLE
fail2ban show already banned but is not ipset

### ISSUE THREAD

**Issue by ediazrod** [fail2ban/fail2ban#982]
I have Debian 7 update with ipset in shorewall.
I have a ugly DDOS of 10000 IPs per day attacking my EXIM.

In my log see this:

fail2ban.log
```
2015-02-27 09:43:34,711 fail2ban.actions: WARNING [exim] Ban 120.164.42.80
2015-02-27 09:43:38,747 fail2ban.actions: WARNING [exim] 190.18.96.159 already banned
2015-02-27 09:43:54,856 fail2ban.actions: WARNING [exim] Ban 103.10.65.126
```
But is not in my ipset list:
 :/var/log# ipset list | wc
   8169   24508  239078
:/var/log#  ipset list | grep 190.18.96.159
in my fail2.ban.log
# /var/log# grep 190.18.96.159 fail2ban.log

2015-02-26 21:53:42,615 fail2ban.actions: WARNING [exim] Ban 190.18.96.159
2015-02-27 04:17:28,303 fail2ban.actions: WARNING [exim] 190.18.96.159 already banned
#2015-02-27 04:40:56,406 fail2ban.actions: WARNING [exim] 190.18.96.159 already banned

I make a lot of testing to be sure all ips is banned:
# Values:  CMD
# 

```
actionban = ipset add f2b-<name> <ip> timeout <bantime> -exist
```
# Option:  actionunban

And if I add this ip again is ok. 
```
adycoaduanas:/etc/fail2ban/action.d# ipset add f2b-EXIM 190.18.96.159
adycoaduanas:/etc/fail2ban/action.d# ipset list | grep 190.18.96.159
190.18.96.159 timeout 86392
```
How can I debug why fail2ban mark this ip as banned but is not in ipset??

**Comment by sebres** [comment]
It's somehow gone under... Sorry for silence.

You can try to set loglevel to DEBUG:
Runtime:
```
# fail2ban-client set loglevel 10
fail2ban-client set loglevel DEBUG
```
Or as config entry in /etc/fail2ban/fail2ban.local:
```
loglevel = DEBUG
```

But normally if some action fails, it writes the output of stderr with level ERROR.
I think it may be something wrong with your configuration.

So dump it, and check the action there is correct. For dump use:
```
fail2ban-client -d | grep exim
```

I'll close it now. Please reopen if still acute
