### ISSUE TITLE
Why Fail2ban restarts itself?

### ISSUE THREAD

**Issue by danielmt2k** [fail2ban/fail2ban#984]
Hi, 

Checking at the fail2ban log, I've noticed it's been restarted automatically. I have this entry:

> fail2ban.server [XXXX]: INFO Stopping all jails

And then, all the sequence to restart it, clearing all the banned IPs (even the recidive ones). Anyone know why the services is auto-stopping/restarting? The server is not.

Thanks.

**Comment by yarikoptic** [comment]
hard to say because no information is really given (versions, fail2ban.log, does it happen regularly? check then cron jobs and logrotate etc)

**Comment by yarikoptic** [comment]
due to absent information/interest from the original reporter, closing
