### ISSUE TITLE
Use #!/usr/bin/python -Es to avoid local changes

### ISSUE THREAD

**Issue by opoplawski** [fail2ban/fail2ban#990]
See https://bugzilla.redhat.com/show_bug.cgi?id=1202151

fail2ban probably should not attempt to load local python modules.  Thoughts?

**Comment by yarikoptic** [comment]
On Mon, 16 Mar 2015, Orion Poplawski wrote:

>    See https://bugzilla.redhat.com/show_bug.cgi?id=1202151

>    fail2ban probably should not attempt to load local python modules.
>    Thoughts?

so the recommendation is to  use "#!/usr/bin/python -Es" as the shebang
line to prevent side-effects of importing from PYTHONPATH etc

certainly sounds like a good strategy for the versions deployed
system-wide from the distribution packages.  But I am not sure if we
should do it in the mainline codebase -- would complicate testing etc.
So IMHO we should just provide this recommendation and adopt it in
Debian packages

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by opoplawski** [comment]
Yeah, does seem like a packaging option.  Is there a way to get this done at build/install time other than using sed?

**Comment by tomspur** [comment]
Could you maybe try `python setup.py build --executable="%{__python} -Es"`?

**Comment by yarikoptic** [comment]
On Wed, 18 Mar 2015, Thomas Spura wrote:

>    Could you maybe try python setup.py build --executable="%{__python} -Es"?

sweet ! thank you Thomas for the hint... pity (and strange) that
install  command doesn't support --executable 

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by opoplawski** [comment]
Ongoing Fedora discussion is here - https://fedorahosted.org/fpc/ticket/513 Looks like we may drop the -E flag, but this is very preliminary at this point.  Also brought this up on python-dev for debate - http://article.gmane.org/gmane.comp.python.devel/151990

**Comment by leeclemens** [comment]
Security concerns regarding the shebangs and Python virtual environments was mentioned by @opoplawski  before, but the plethora of shebangs for python scripts in various projects seem to suggest using `env` as commonplace. Is a malicious user with root access that executes some python script (and relies upon the shebang allowing their malicious python exe in the PATH) what you're concerned about? If I am misunderstanding, please help me understand your security concern.

**Comment by yarikoptic** [comment]
Since it seems that even in Fedora at distribution level decision was not to bother with -E or -s (@opoplawski, correct me if I am wrong please). But also it is definitely to be decided only at the level of centralized/unified distribution, and for our "portable" generic installation we shouldn't restrict in such a way.  Thus I will close for now

**Comment by opoplawski** [comment]
We've gone with -s, but yeah, this probably belongs at the distro level.
